### PR TITLE
Simple control flow analysis 

### PR DESCRIPTION
**Pull request by vladima**
This PR adds a basic control flow analysis to typescript compiler. Now it can detect unreachable code, implicit returns of undefined in functions, unused labels, fall- through between cases in switch statements. Some of these checks can be used in #393 or #274.

cfa

Disclaimer: This PR is not intended to be checked in as-is. What I rather want is to use it as a starting point to discuss:
- difference between warnings and errors. now all semantic errors that are produced by the compler can be treated as warnings - they do not block emit. However visually they are always presented as errors which might be confusing, I.e. I would expect message about unreachable code to be more like recommendation (presented using green squigglies or shadowed code) instead of being aggressively marked as error
- error suppression story - global and local

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
We should put this back on the radar again.

**Comment by NoelAbrahams** [comment]
>We should put this back on the radar again.

:+1:

**Comment by awerlang** [comment]
IMO, it overlaps with TSLint.

Regarding this, I'm concerned with the fact that I cannot use more mature JSHint or ESLint. Perhaps running them on the output (haven't tried that though).
As a TS user, I would prefer that it becomes a full superset of ES6, so I could have back other linters in my workflow.

**Comment by vladima** [comment]
closed in favor of #4788

**Pull request closed without merging**
