### PR TITLE
Add Intl.locale types

### LINKED ISSUE #37326: Add Intl.Locale to es2020 lib
## Search Terms

Locale, intl

## Suggestion

Add Intl.Locale to the es2020 build target libs. It is supported in recent NodeJS versions, and recent Chrome versions, making it a suitable feature for inclusion.

## Use Cases

Using the new Intl.Locale feature.

## Examples

```
console.log((new Intl.Locale('en-US')).language); // Outputs "en"
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by Dangoo**
Fixes #37326

I'm aware there's currently no entry in the Backlog for it, but a PR makes discussion easier.

Thanks for @boenrobot for bringing the issue up and @longlho for giving feedback on this!

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for the changes @Dangoo. 1 last thing I'd say is to rename `LDMLHourCycleKey` & `LDMLCollationCaseFirst` since they're not LDML concepts (LDML refers to UTS35 Unicode **L**ocale **D**ata **M**arkup **L**anguage) but rather just ECMA402.

**Review by hbroer — APPROVED** [review]

**Comment by hbroer** [comment]
Hi, what is the current state for this PR and when will it be merged? Can we do something? @orta

**Comment by Dangoo** [comment]
Hey, are there any blockers stopping you on bringing this in, or is there something we can do to support review/merging? @orta @RyanCavanaugh

**Comment by szuend** [comment]
Hey, we would like to use this PR in our project until it is merged. Can you confirm that the substance of this PR is available under TypeScript's Apache 2 license?

**Comment by JustJenFelice** [comment]
What is the status of this PR? 

This request for support for Intl spec doesn't seem like it would be controversial, yet the delay in resolving the lack of support is inexplicable. This PR was approved October 2020.

**Comment by orta** [comment]
Thanks @Dangoo - I've taken these changes and integrated them into https://github.com/microsoft/TypeScript/pull/45647 which I've just merged into main for 4.5 👍🏻

**Pull request closed without merging**
