### PR TITLE
Textually search for 'return' before exploring the tree for 'return' statements.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
For fun

@typescript-bot perf test this

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this draft PR. It's pretty old.

**Pull request closed without merging**
