### PR TITLE
Perform weak type checks when performing comparisons.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
See motivation at https://github.com/microsoft/TypeScript/pull/34552#discussion_r336279763

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this
@typescript-bot run dt

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by DanielRosenwasser** [comment]
Found one break in DefinitelyTyped in chrome-apps which was legitimate.

> /home/vsts/work/1/s/dtslint-runner/DefinitelyTyped/types/chrome-apps/test/index.ts:1645:9
> Operator '>' cannot be applied to types 'StorageChange' and 'number'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b0503ac10547e9e087febf36e83c600a62c444bb/types/chrome-apps/test/index.ts#L1644-L1648

`changes` is a `Record<string, StorageChange`, which means you can access any property (which is dumb).

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b0503ac10547e9e087febf36e83c600a62c444bb/types/chrome-apps/index.d.ts#L9037

But that means that `length` has the type `StorageChange`. Arguable that never letting users access arbitrary properties in the presence of index signatures would have prevented this better.

**Comment by jack-williams** [comment]
Just throwing this out there<sup>as a terrible suggestion</sup>.

If a _castable_ relation is being added, might it be reasonable to allow interfaces to be open when casting to. It avoids the pain of the following:
```ts
interface Foo {
    x: string;
    y: string;
}

interface JSONObj {
    [prop: string]: JSONableSub;
}

type JSONableSub = number | string | JSONObj;

declare const obj: JSONableSub;
const foo: Foo = obj as Foo; // error, Foo isn't assignable to JSONObj because it is an interface with no index signature.
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
This experiment is pretty old, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
