### PR TITLE
Exclude enum/number compatibility rule from comparable relation

### LINKED ISSUE #42442: Comparing numeric enum to number narrows variable to 'never'
# Bug Report

### 🔎 Search Terms

enum, number, never

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210121#code/KYOwrgtgBAolDeAoKKoEMoF4oEYA0yqARllAEwEC+iiAJsAMYA2aATsFE8AC5QBuALlgBuRAEsAZlAAUfKAEJM2AAwBKBIRRyAZNhgA6NKMpA)

### 💻 Code

```ts
enum E {
    a = 1,
    b = 2,
}

declare let v: E;
if (v !== 0) {
    v &= E.a;
}
```

### 🙁 Actual behavior

`v` is narrowed to `never` inside the IfStatement. The compound assignment gives a compile error: `Type 'number' is not assignable to type 'never'.(2322)`

### 🙂 Expected behavior

`v` is still of type `E` and there's no error.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #42442.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
The only test changes related to this PR are some new errors in the RWC vscode project. All but one of them are flagging real issues. For example, code that declares something as a `KeyCode[]`, but then compares element values to `-1`, which doesn't match any declared `KeyCode` member. So, the array declaration should really be `(KeyCode | -1)[]`.

The one undesired new error is related to this enum declaration in vs/editor/common/modes.ts:

```ts
/**
 * Open ended enum at runtime
 * @internal
 */
export const enum LanguageId {
	Null = 0,
	PlainText = 1
}
```

The intent here is for `LanguageId` to be a numeric (i.e. non-union) enum. This can be accomplished by changing one of the enum values to a computed expression:

```ts
export const enum LanguageId {
	Null = +0,
	PlainText = 1
}
```

Subtle, but actually an intended and documented behavior.

**Comment by DanielRosenwasser** [comment]
This seems like almost pure goodness, but I would still err on the side of saying that this can wait for 4.3. That `+0` workaround is pretty subtle.

**Comment by DanielRosenwasser** [comment]
What is the case for the non-union enum? It's unclear from that example.

**Comment by DanielRosenwasser** [comment]
Let me know if https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#union-enums-cannot-be-compared-to-any-number accurately reflects the change here.

**Comment by ahejlsberg** [comment]
> What is the case for the non-union enum? It's unclear from that example.

The code that broke compares a value of type `LanguageId` to the numeric value `73`. I guess the intent is to create symbolic names for a few special language IDs, but otherwise allow any integer value.

**Comment by ahejlsberg** [comment]
> Let me know if https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#union-enums-cannot-be-compared-to-any-number accurately reflects the change here.

Yes, looks good.

**Pull request merged**
