### PR TITLE
Move `hasOwn` from Object instance to Object constructor

### LINKED ISSUE #48206: lib.es2022: `hasOwn` appears to be defined on `Object` prototype rather than on constructor
# Bug Report

### 🔎 Search Terms

hasOwn, Object.hasOwn, es2022, prototype, lib.es2022.object.d.ts

### 🕗 Version & Regression Information

- This changed between versions 4.2.4 and 4.6.2

Appears to be introduced by https://github.com/microsoft/TypeScript/pull/46291

### ⏯ Playground Link

Doesn't appear to reproduce on Playground or Bug Workbench, reproduces in VS Code 1.66.0-insider (e80a0ca648fe9bef07070e4f7fb04e67f2243252) running TypeScript 4.6.2.

### 💻 Code

```ts
interface SomeComponentProps {
  requiredProp: boolean
  hasOwn?: boolean;
}

const SomeComponent: React.FC<SomeComponentProps> = () => {}

return <SomeComponent requiredProp />
```

### 🙁 Actual behavior

I ran into this issue because I was trying to upgrade the project from 4.3.5 to 4.6.2. The project has some object types with `hasOwn` as a boolean property.

```
// TS2322: Type '{ requiredProp: boolean }' is not assignable to type 'SomeComponentProps'.
  Types of property 'hasOwn' are incompatible.
    Type '(o: object, v: PropertyKey) => boolean' is not assignable to type 'boolean'.
```

### 🙂 Expected behavior

`hasOwn` should be a method of the `Object` constructor (`Object.hasOwn`), not the prototype (`foo.hasOwn`).

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #48206

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
🤦‍♂️

In checker.ts we have some logic for reporting whether or not the `lib` has to be adjusted for newer methods. Is that correct as well?

**Comment by DanielRosenwasser** [comment]
Nah should be fine.

image

**Review by DanielRosenwasser — APPROVED** [review]
Should we cherry-pick to release-4.6 and release a patch?

**Comment by RyanCavanaugh** [comment]
I think so, this will not be the first report of it

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-4.6

**Pull request merged**
