### PR TITLE
fix(41420): Parser allows optional chain in a type-location - `class ... implements` and `interface ... extends`

### LINKED ISSUE #41420: Parser allows optional chain in a type-location - `class ... implements` and `interface ... extends`
**TypeScript Version:**  4.2.0-dev.20201105

**Search Terms:**
class implements optional chain
interface extends optional chain

**Code**

```ts
namespace FG {
    export class A {
        prop: string = '';
    }
}

class AA extends FG.A {}
type B = FG.A;

// @ts-expect-error -- Class 'C' incorrectly implements class 'A'. ... Property 'prop' is missing in type 'C' but required in type 'A'.
class C implements FG?.A {}

interface D extends FG?.A {}
// @ts-expect-error -- Property 'prop' is missing in type '{}' but required in type 'D'.
const test: D = {};

// expected parser error -- ';' expected.
type E = FG?.A;
```

**Expected behavior:**
```ts
class C implements FG?.A {} // expected a parser error
interface D extends FG?.A {} // expected a parser error
```

**Actual behavior:**

No parser errors - syntax is allowed

**Playground Link:** https://www.typescriptlang.org/play?ts=4.2.0-dev.20201105#code/HYQwtgpgzgDiDGEAEAxA4kg3gKCXpEAHjAPYBOALkvADYhRRICCWu+7MZJMAXElBTIBLYAHMkAXiQByaQG42eAL7YV2WvUZMWRChGAATRugB0LTCooBPGMgBCk1GjMLsAejdIAAhSgBaIlt4CgCyLjIkPz8kAGE6BhkY6SQReHIyCGCaKxSwGBoISGBfanjGaSZpEyQTWqQABS5bShzpTm5koUYwLqgRcREka1tE5IAjAFcqDIBHCaEMgxTgIZtkCqr1Mtjc-ML9EvQAfjMsNRE9MgAzBGQAEQJCPUNjNBPzFQ9vXwDiTJCIGFyJFoo1uIDrDJ2jBOt1ev1lqsRtILOMpkhZvNFojhus7ps0sABENoBQ+A8pBZXF9Av8IEs4GQoICCECIlEZHJkrTgvSTNhcUgAKKOY4ubBAA

**Related Issues:**

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41420

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
This really isn't the appropriate fix because

```ts
class C extends Foo?.D {}
```

is totally valid working code. It's more about

```ts
class C implements Foo?.D {}
```

because `Foo?.D` isn't a valid QualifiedName for a namespace `Foo` and a type `D`.

**Comment by DanielRosenwasser** [comment]
I haven't given it much thought though and I'm not that familiar with the code.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Thanks for the feedback. I forgot to mark it as `Draft` because I have some questions.

Why does TS allow using the optional chain in `extends`?

```
class C extends Foo?.D {}
```

It is similar to 

```ts
class C extends (Foo === null || Foo === void 0 ? void 0 : Foo.D) {
}
```

And the case with `undefined` is not valid in TS and in JavaScript too.

```ts
class C extends (void 0) {} 
```

---
In the `checker` there are two similar errors
1. A_class_can_only_implement_an_identifier_Slashqualified_name_with_optional_type_arguments
```ts
if (!isEntityNameExpression(typeRefNode.expression)) {
  error(typeRefNode.expression, Diagnostics.A_class_can_only_implement_an_identifier_Slashqualified_name_with_optional_type_arguments);
}
```
2. An_interface_can_only_extend_an_identifier_Slashqualified_name_with_optional_type_arguments
```ts
if (!isEntityNameExpression(heritageElement.expression)) {
   error(heritageElement.expression, Diagnostics.An_interface_can_only_extend_an_identifier_Slashqualified_name_with_optional_type_arguments);
}
```
I'm not sure where do we need to handle the optional chain definition. parser/checker.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser What do you think would be the right direction to fix this issue? Does that make sense of my previous comment?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser What do you think about the right place to handle such cases? Do we need to do that in checker/parser?

**Comment by DanielRosenwasser** [comment]
> Why does TS allow using the optional chain in `extends`?

JavaScript allows it, so we do too.

I think the checker is the best place to handle it

**Comment by rbuckton** [comment]
This looks good, but it would be nice to add a test for what should happen if `A` is undefined:

```ts
namespace A1 {
    export class B1 {};
    export let B2: typeof B1 | undefined = B1;
}

// ok, we know A1 and B1 are defined
class C1 extends A1?.B1 {
}

// error, we know B2 can be undefined
class C2 extends A1?.B2 {
}

let A2: typeof A1 | undefined = A1;

// should be an error because A2 could be undefined;
class C3 extends A2?.B1 {
}

// error, we know B2 can be undefined
class C4 extends A2?.B2 {
}
```

In the above example, `C3` does not currently report an error and it should.

**Comment by a-tarasyuk** [comment]
@rbuckton Thanks for the review 👍🏻. Do you mean using `?.` in class heritage? I just used the expected behavior that related to interface/extends class/implements to fix the issue :). It seems to be an issue related to resolving the base type of a constructor., if a class/extensions issue needs to be resolved within this issue, I can investigate why `isConstructorType` returns the incorrect result.

**Review by rbuckton — APPROVED** [review]
I suppose we can merge this since it specifically targets `implements` clauses in a `class` and `extends` clauses of an `interface`. I'll open a separate issue about how we're incorrectly type-checking `class extends A2?.B1` in my example above.

**Comment by a-tarasyuk** [comment]
@rbuckton Thanks

**Pull request merged**
