### PR TITLE
add index signature for anonymous object literal type

### LINKED ISSUE #14951: type has no index signature
**TypeScript Version:**  2.2.2

**Code**

```ts
function getName(id: number) {
  return {
    1: 'one',
    2: 'two',
  }[id] || 'something else';
}

```

**Expected behavior:**
`{1: 'one'}[id]` type should be `string | undefined`
So I would expect the return type to be inferred as string.

**Actual behavior:**
> Element implicitly has an 'any' type because type '{ 1: string; 2: string; }' has no index signature.

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #14951 

- [ ] accept baseline

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@kingwl please see implementation comments in https://github.com/Microsoft/TypeScript/issues/14951#issuecomment-415289510 - we'd rather have a solution based on the entire property access expression instead of creating an index signature as originally suggested. Thanks!

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by Kingwl** [comment]
⬆️

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this again

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this one more time?

**Comment by RyanCavanaugh** [comment]
@kingwl this has a hairy conflict with master, can you investigate?

**Comment by weswigham** [comment]
I think the logic in this PR probably deserves less syntax-based checks and should _probably_ be updated logic in `getPropertyTypeForIndexType` for `FreshLiteral` object-flagged types.

**Comment by RyanCavanaugh** [comment]
Closing due to inactivity. Feel free to open a new PR later!

**Pull request closed without merging**
