### PR TITLE
Remove experimental flag to cache for-of length checks.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Were we just not seeing a perf improvement here?

**Comment by vladima** [comment]
@DanielRosenwasser yes, caching length of the array can be improve performance but it should be done on case-by-case basic since length of the array can be change as you iterate if elements were added\removed from the array during iteration.

**Comment by vladima** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Sure, I get that, but I thought that was the reason it was put behind a flag. Either way this is fine.

**Comment by vladima** [comment]
@DanielRosenwasser flag is not fine grained enough, it will enable\disable caching for everything which might be incorrect.

**Comment by DanielRosenwasser** [comment]
I understand that and I would presume that the users of such a flag would understand that as well, though I can see why it might not be the best choice.

**Pull request merged**
