### PR TITLE
Widen boolean literals when contextual type is full boolean type

### LINKED ISSUE #48363: Inconsistent boolean literal types
### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQg9gDwDwBUB8UC8UDeAoKQqAcwmAC4oAKASiwxQBoCiBnMyqgNwEMAbAK4RKKOpgxc4ASwAmeAL548MiAGM+PAE7QAZgIB2q4FLj6oAI0So03fkJE1K8ZOgDcS1adbAL+gIxYFohUAAw0roQA9JGwVvoCALbmEJpoeJ763r4ATE5xicmpgZYIoeFRMQDyANYeXj7m5gHYJVQ6-OzlUNGxyJZwfBA8+mkZWY25vUj9g8MYLcHtfJ0R3TEAopqacJqMQchL7Bj6cD48rKxSxPo85oNQwHBTM0MjeEA)

### 💻 Code

```ts
// Box<T> type is invariant in T

type Box<T> = {
    get: () => T,
    set: (value: T) => void
}

declare function box<T>(value: T): Box<T>;

const bn1 = box(0);  // Box<number>
const bn2: Box<number> = box(0);  // Ok

const bb1 = box(false);  // Box<boolean>
const bb2: Box<boolean> = box(false);  // Error, box<false> not assignable to Box<boolean>
```

### 🙁 Actual behavior

Error on `bb2` is surprising and inconsistent with lack of error on `bn2`.

### 🙂 Expected behavior

Expected the `box(false)` expression to have type `Box<boolean>` for both `bb1` and `bb2`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #48363.

Also fixes issue mentioned [here](https://github.com/microsoft/TypeScript/pull/29478#issuecomment-457875877) because boolean literals contextually typed by `boolean` are now widened.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
Apart from lots of `false` and `true` types changing to `boolean` (as expected), there are really only two notable changes in the baselines. One is in `excessPropertyCheckWithMultipleDiscriminants.ts`, simplified to:

```ts
let x: { kind: false, x: number } | { kind: boolean, x: string } = { kind: false, x: 42 };
```

Previously this would match against the first variant and succeed. It now matches against the second variant (because the `kind: false` in the object literal is given type `boolean` as it is contextually typed by `boolean`). It's possible to get the old behavior by writing `kind: false as const`. I think this change is acceptable.

The other change is in `inferFromGenericFunctionReturnTypes3.ts`:

```ts
declare function foldLeft<U>(z: U, f: (acc: U, t: boolean) => U): U;
let res: boolean = foldLeft(true, (acc, t) => acc && t);  // Was error, now ok
```

Previously the `true` literal wasn't widened and therefore `acc` and `t` would have type `true`, which doesn't work out. We now widen and the example works as expected.

**Comment by fatcerberus** [comment]
Someone brought this up in Discord:
```ts
let foo: boolean = false;
```
With the change in this PR, does this no longer narrow-on-assignment to `false`?

**Comment by ahejlsberg** [comment]
Several Definitely Typed packages are adversely affected. Closing this and putting up an alternate PR with less impact.

**Pull request closed without merging**
