### PR TITLE
Fixes #8582: Add Error.prototype.stack definition

### LINKED ISSUE #8582: Add Error.prototype.stack definition
Most browsers support `Error.prototype.stack`. the property should be defined as optional in lib.d.ts as:

```ts
interface Error {
    stack?: string;
}
```
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack

### PR DESCRIPTION
**Pull request by nojvek**
Fixes #8582: Add Error.prototype.stack definition

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Hey @nojvek, fixes are supposed to go into `src/lib` (check out the files [`CONTRIBUTING.md`](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes) and [`src/lib/README.md`](https://github.com/Microsoft/TypeScript/blob/master/src/lib/README.md)) and then we generally update the LKG when we deem appropriate. We also try not to change line endings in existing files. Could you resubmit so we can get a reasonable diff and generate the files appropriately?

**Comment by DanielRosenwasser** [comment]
Basically what I'm also saying is: only add the definition into `src/lib/` where it needs to go, don't run `jake LKG`.

**Comment by nojvek** [comment]
Yeah I totally forgot to push so it has the old commit. My bad. Sorry. I had made the edit in src/lib/es5.d.ts

**Comment by nojvek** [comment]
Fixed now.

**Comment by DanielRosenwasser** [comment]
That's a much nicer diff :smile: :+1:

**Comment by mhegazy** [comment]
thanks!

**Pull request merged**
