### PR TITLE
When reporting errors, compute diagnostics even if type relation has cached result

### LINKED ISSUE #3276: Diagnostic elaboration is not consistently reported in language service
Adapted from #3275:

``` TypeScript
class GenericThingamabob<T> {
    constructor(private entity: T) {}
    add(item: T) { }
}

class CouponInfo {
    private couponTag: {};
}

class Snake {
    private snakeTag: {};
}

var blah = new GenericThingamabob(new CouponInfo());

blah.add(new Snake());
//       ~~~~~~~~~~~
var x: CouponInfo = new Snake();
//  ~
```

On the first error, I get

```
Argument of type 'Snake' is not assignable to parameter of type 'CouponInfo'.
  Property 'couponTag' is missing in type 'Snake'
```

On the second, I get

```
Type 'Snake' is not assignable to type 'CouponInfo'.
```

Note that if you turned `blah.add(new Snake());` into a variable assignment like `var a: CouponInfo = new Snake()`, you'll get the same issue.

### PR DESCRIPTION
**Pull request by gabritto**
Updated version of #55234.
Fixes #3276.

Motivated by #57842.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by gabritto** [comment]
It doesn't seem like the case of reporting the same assignability error more than once is that frequent, since there were only 3 changes in user tests, none in top 400, and no perf impact.

Two things I want to do, though:
- Special case type comparison "overflow" cases so that we don't do the comparison again.
- Maybe only have this consistent assignability elaboration when we know we are in an editor scenario, if that's possible.

**Comment by gabritto** [comment]
@typescript-bot perf test this
@typescript-bot test top800

**Comment by gabritto** [comment]
@typescript-bot test this

**Comment by gabritto** [comment]
@typescript-bot user test this

**Review by weswigham — APPROVED** [review]
Perf still looks fine, baselines look good, and I already approved the old version of the PR :)

**Pull request merged**
