### PR TITLE
Excess discriminated types match all discriminable properties

### LINKED ISSUE #31655: Excess properties in tagged union not checked if type is optional and literal
**TypeScript Version:**  3.4.1, 3.5.1

**Search Terms:** tagged union optional literal excess properties props

**Code**

```ts
type Button = { tag: 'button'; type?: 'submit'; };
type Anchor = { tag: 'a'; type?: string; href: string };

type Union = Button | Anchor;
const obj: Union = {
    tag: 'button',
    type: 'submit',

    // no error, bad! :-(
    href: 'foo',
    // error, good! :-)
    href2: 'foo',
};
```

If I replace `Button` with:

``` ts
type Button = { tag: 'button'; type?: string };
```

That is, if I replace the optional string literal with an optional string, then it works as expected (I get an error for the excess prop `href`), suggesting this is down to the fact that we're using string literals?

### LINKED ISSUE #32657: Regression in discriminated unions when a common property may be boolean
**TypeScript Version:**
3.6.0-dev.20190801

**Search Terms:**
discriminated boolean, tagged boolean

**Code**

```ts
interface Base<T> {
    value: T;
}

interface Int extends Base<number> {
    type: "integer";
    multipleOf?: number;
}

interface Float extends Base<number> {
    type: "number";
}

interface Str extends Base<string> {
    type: "string";
    format?: string;
}

interface Bool extends Base<boolean> {
    type: "boolean";
}

type Primitive = Int | Float | Str | Bool;

const foo: Primitive = {
    type: "number",
    value: 10,
    multipleOf: 5,
    format: "what?"
}
```

**Expected behavior:**
The code should not compile, because properties `multipleOf` and `format` don't exist in type `Float`.

**Actual behavior:**
The code compiles without errors. Typescript version **3.1.6** is the last version which behaves as expected and prints the error message.

Removing the `Bool` interface from the union, or changing the type parameter on the `Bool` interface to any other type causes expected behavior.

Not using inheritance and defining the `value` property in each interface separately does not change the behavior.

**Playground Link:**
[LINK](https://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgEJwM4QDwBUB8yA3gFDLnIBucANgK4QBcyuA3CQL4kmiSyIoAkuGQQAHpBAATDGkw4QdALYAjaIVIVkYAJ4AHJsgBEvCAHNoR9lqV0aYYHpoQA8jAD8zRaujsuPcGh4JGQAMRoAezgwUQkIaVl0LGxvNSgNMgpdA2YjVMs-blN+EIBlMChYyRk5ZIwK0DMMrWzDI3qoRqtM8hgIqCVoz2QOxsKAvmCUVAiImir4mqScFVnnOBBmrP021bmIDe7-VuQABU6lYAdKFABeZGEYgB8wyOjkF-LKl5m59hIEBEQPVkH0IsxzsBLtc7sQetodrl8lAjAAaeHUeiGACMAAZ0TY7A4nK4YMwAKwEih9AbRXIAdwAFkMjJwgA)

**Related Issues:** -

### PR DESCRIPTION
**Pull request by sandersn**
Excess property checks only use discriminated types when exactly 1 type's properties from the target are related to all of the discriminable properties of the source. However, if more than 1 type from the target matches *any* property, we give up because there might be 2 discriminated types from the target union. 

This change actually checks whether all properties of all types in the target union are related to the discriminable properties of the source. This makes the list of discriminated type === 1 more often, which in turn makes excess property checks use a discriminated type more often.

I'm not sold on the value of this change vs its complexity. Opinions are welcome.

Fixes #31655
Fixes #32657

### CODE REVIEW

**Comment by weswigham** [comment]
https://github.com/microsoft/TypeScript/pull/32711 ?

**Comment by orta** [comment]
I can't attest too much to the complexity, but this feels like a useful fix to me 👍

**Comment by sandersn** [comment]
@weswigham Yep! #32711 is the same fix! Thanks for pointing that out. I still like this fix better, so I asked @jack-williams to take a look and see what he thinks.

**Comment by jack-williams** [comment]
@sandersn In short I think this is better and should be merged over mine.

If I understood the old code correctly: the requirement to discriminate to a type wasn't to match all discriminant properties, only that any matched properties were always of the same type. I tried replicating this behaviour so that you didn't need to match _all_ properties, just that all matched properties had an unambiguous candidate.

I'm not actually sure this requirement is necessary; instead, requiring that _all_ properties are matched (by a single type) seems to deliver the same results with cleaner code. Presumably if no candidate matches all discriminants then an error will get flagged later on because the union is unassignable to.

**Comment by sandersn** [comment]
Ah, I see. Yeah, I think my simpler definition is fine even if it's a bit stricter. And you are right that we'll catch any real assignability errors later on.

**Pull request merged**
