### PR TITLE
Add extensions to `bin` scripts.

### PR DESCRIPTION
**Pull request by sosoba**
Adption to changes in Node.
See https://github.com/nodejs/node/pull/31415

Fixes #

### CODE REVIEW

**Comment by orta** [comment]
I'm a bit wary that the ` bin/tsc → bin/tsc.js` feels likely to break something somewhere (given the amount of platforms / tools which embed TS.) Perhaps a safe solution is to add new files for the `.js`(each of these files is only 2 LOC long anyway)?

**Comment by sosoba** [comment]
> 
> Perhaps a safe solution is to add new files for the `.js`

It's a good point. Can i change PR and add "twins"?

**Comment by RyanCavanaugh** [comment]
Appears to be a fix for #39381

**Comment by weswigham** [comment]
We... don't set `type: module` in our `package.json` - #39381 is totally indicative of an error in the implementation of the experimental flag in `node` itself.

**Comment by RyanCavanaugh** [comment]
@weswigham effectively OP is experiencing this issue? https://github.com/nodejs/node/issues/33226

I don't think we should merge anything with nonzero risk in order to enable experimental node stuff

**Comment by weswigham** [comment]
Yep, that looks to be a report of the same thing.

**Comment by orta** [comment]
This makes sense, we should probably close this.

**Pull request closed without merging**
