### PR TITLE
Ignore the `keyofStringsOnly` setting so we can see who depends on it and how

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Per title

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by jakebailey** [comment]
@typescript-bot run top100

**Comment by jakebailey** [comment]
No, I'm silly.

@typescript-bot test top100

**Comment by sandersn** [comment]
@RyanCavanaugh @jakebailey Is this something we intend to ship or is the PR just an experiment?

**Pull request closed without merging**
