### PR TITLE
Support null in __extends helper

### PR DESCRIPTION
**Pull request by ahejlsberg**
With #3516 it is now possible for a class to extend `null` as permitted by ES6. This PR changes the `__extends` helper emitted for derived classes to properly support null base arguments in ES5 environments:

```typescript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```

Since `Object.create` is available only in ES5, an exception will be thrown for a null base argument in an ES3 environment. But that was already the case before, so we're no worse off.

### CODE REVIEW

**Comment by rbuckton** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by mhegazy** [comment]
:+1:

**Comment by vladima** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
We should consider addressing #1601 as part of this

**Comment by ahejlsberg** [comment]
Let's have resolution of #1601 be a separate issue.

**Pull request merged**
