### PR TITLE
Fixed crash when resolving a symbol on invalid private identifier in type reference

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by jakebailey** [comment]
Is there a linked issue / crash report for this?

**Comment by jakebailey** [comment]
@typescript-bot test it

**Review by jakebailey — APPROVED** [review]
Seems correct to me if perf doesn't change.

**Comment by Andarist** [comment]
> Is there a linked issue / crash report for this?

No, I noticed this crash in the playground's console when working on minimizing a repro for some other issue 😉

**Pull request merged**
