### PR TITLE
Cache control flow results across invocations

### LINKED ISSUE #29926: Extremely slow javascript compile (small file)
**TypeScript Version:**

 3.3.3 (OSX)

**Search Terms:**

slow javascript compile

**Code**

Compile with "time tsc --allowJs md4.js --outFile t.js"

```
Md4.prototype.hash = function () {
    var a, b, c, d, ab, bc, cd, da, blocks = this.blocks;

    if (this.first) {
      a = blocks[0] - 1;
      a = (a << 3) | (a >>> 29);
      d = ((a & 0xefcdab89) | (~a & 0x98badcfe)) + blocks[1] + 271733878;
      d = (d << 7) | (d >>> 25);
      c = ((d & a) | (~d & 0xefcdab89)) + blocks[2] - 1732584194;
      c = (c << 11) | (c >>> 21);
      b = ((c & d) | (~c & a)) + blocks[3] - 271733879;
      b = (b << 19) | (b >>> 13);
    } else {
      a = this.h0;
      b = this.h1;
      c = this.h2;
      d = this.h3;
      a += ((b & c) | (~b & d)) + blocks[0];
      a = (a << 3) | (a >>> 29);
      d += ((a & b) | (~a & c)) + blocks[1];
      d = (d << 7) | (d >>> 25);
      c += ((d & a) | (~d & b)) + blocks[2];
      c = (c << 11) | (c >>> 21);
      b += ((c & d) | (~c & a)) + blocks[3];
      b = (b << 19) | (b >>> 13);
    }
    
    /* not commented out: 1m44.091s, commented out: 0m1.867s, 
    a += ((b & c) | (~b & d)) + blocks[4];
    a = (a << 3) | (a >>> 29);
    d += ((a & b) | (~a & c)) + blocks[5];
    d = (d << 7) | (d >>> 25);
    c += ((d & a) | (~d & b)) + blocks[6];
    c = (c << 11) | (c >>> 21);
    b += ((c & d) | (~c & a)) + blocks[7];
    b = (b << 19) | (b >>> 13);
    a += ((b & c) | (~b & d)) + blocks[8];
    a = (a << 3) | (a >>> 29);
    d += ((a & b) | (~a & c)) + blocks[9];
    d = (d << 7) | (d >>> 25);
    c += ((d & a) | (~d & b)) + blocks[10];
    c = (c << 11) | (c >>> 21);
    b += ((c & d) | (~c & a)) + blocks[11];
    b = (b << 19) | (b >>> 13);
    a += ((b & c) | (~b & d)) + blocks[12];
    a = (a << 3) | (a >>> 29);
    d += ((a & b) | (~a & c)) + blocks[13];
    d = (d << 7) | (d >>> 25);
    c += ((d & a) | (~d & b)) + blocks[14];
    c = (c << 11) | (c >>> 21);
    b += ((c & d) | (~c & a)) + blocks[15];
    b = (b << 19) | (b >>> 13);

    bc = b & c;
    a += (bc | (b & d) | (c & d)) + blocks[0] + 1518500249;
    a = (a << 3) | (a >>> 29);
    ab = a & b;
    d += (ab | (a & c) | bc) + blocks[4] + 1518500249;
    d = (d << 5) | (d >>> 27);
    da = d & a;
    c += (da | (d & b) | ab) + blocks[8] + 1518500249;
    c = (c << 9) | (c >>> 23);
    cd = c & d;
    b += (cd | (c & a) | da) + blocks[12] + 1518500249;
    b = (b << 13) | (b >>> 19);
    bc = b & c;
    a += (bc | (b & d) | cd) + blocks[1] + 1518500249;
    a = (a << 3) | (a >>> 29);
    ab = a & b;
    d += (ab | (a & c) | bc) + blocks[5] + 1518500249;
    d = (d << 5) | (d >>> 27);
    da = d & a;
    c += (da | (d & b) | ab) + blocks[9] + 1518500249;
    c = (c << 9) | (c >>> 23);
    cd = c & d;
    b += (cd | (c & a) | da) + blocks[13] + 1518500249;
    b = (b << 13) | (b >>> 19);
    bc = b & c;
    a += (bc | (b & d) | cd) + blocks[2] + 1518500249;
    a = (a << 3) | (a >>> 29);
    ab = a & b;
    d += (ab | (a & c) | bc) + blocks[6] + 1518500249;
    d = (d << 5) | (d >>> 27);
    da = d & a;
    c += (da | (d & b) | ab) + blocks[10] + 1518500249;
    c = (c << 9) | (c >>> 23);
    cd = c & d;
    b += (cd | (c & a) | da) + blocks[14] + 1518500249;
    b = (b << 13) | (b >>> 19);
    bc = b & c;
    a += (bc | (b & d) | cd) + blocks[3] + 1518500249;
    a = (a << 3) | (a >>> 29);
    ab = a & b;
    d += (ab | (a & c) | bc) + blocks[7] + 1518500249;
    d = (d << 5) | (d >>> 27);
    da = d & a;
    c += (da | (d & b) | ab) + blocks[11] + 1518500249;
    c = (c << 9) | (c >>> 23);
    b += ((c & d) | (c & a) | da) + blocks[15] + 1518500249;
    b = (b << 13) | (b >>> 19);

    bc = b ^ c;
    a += (bc ^ d) + blocks[0] + 1859775393;
    a = (a << 3) | (a >>> 29);
    d += (bc ^ a) + blocks[8] + 1859775393;
    d = (d << 9) | (d >>> 23);
    da = d ^ a;
    c += (da ^ b) + blocks[4] + 1859775393;
    c = (c << 11) | (c >>> 21);
    b += (da ^ c) + blocks[12] + 1859775393;
    b = (b << 15) | (b >>> 17);
    bc = b ^ c;
    a += (bc ^ d) + blocks[2] + 1859775393;
    a = (a << 3) | (a >>> 29);
    d += (bc ^ a) + blocks[10] + 1859775393;
    d = (d << 9) | (d >>> 23);
    da = d ^ a;
    c += (da ^ b) + blocks[6] + 1859775393;
    c = (c << 11) | (c >>> 21);
    b += (da ^ c) + blocks[14] + 1859775393;
    b = (b << 15) | (b >>> 17);
    bc = b ^ c;
    a += (bc ^ d) + blocks[1] + 1859775393;
    a = (a << 3) | (a >>> 29);
    d += (bc ^ a) + blocks[9] + 1859775393;
    d = (d << 9) | (d >>> 23);
    da = d ^ a;
    c += (da ^ b) + blocks[5] + 1859775393;
    c = (c << 11) | (c >>> 21);
    b += (da ^ c) + blocks[13] + 1859775393;
    b = (b << 15) | (b >>> 17);
    bc = b ^ c;
    a += (bc ^ d) + blocks[3] + 1859775393;
    a = (a << 3) | (a >>> 29);
    d += (bc ^ a) + blocks[11] + 1859775393;
    d = (d << 9) | (d >>> 23);
    da = d ^ a;
    c += (da ^ b) + blocks[7] + 1859775393;
    c = (c << 11) | (c >>> 21);
    b += (da ^ c) + blocks[15] + 1859775393;
    b = (b << 15) | (b >>> 17);
    */

    if (this.first) {
      this.h0 = a + 1732584193 << 0;
      this.h1 = b - 271733879 << 0;
      this.h2 = c - 1732584194 << 0;
      this.h3 = d + 271733878 << 0;
      this.first = false;
    } else {
      this.h0 = this.h0 + a << 0;
      this.h1 = this.h1 + b << 0;
      this.h2 = this.h2 + c << 0;
      this.h3 = this.h3 + d << 0;
    }
  };
```

**Expected behavior:**

Insignificant increase in compile time when the code is not commented out.

**Actual behavior:**

Huge increase in compile time (from 2 seconds to 1 minute 44 seconds) when the code is not commented out

**Playground Link:** 

The behavior doesn't reproduce in TypeScript Playground.

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
As mentioned in #30945 and alluded to in #30931, our real issue with control flow is that we weren't caching across invocations of `getFlowTypeOfReference`, which meant that our standard check order (top to bottom) always triggered worst case exponential complexity as it repeatedly trampolined into and out of `getFlowTypeOfReference` with each subsequent expression. By memoizing the results between invocations, we neatly avoid this by reusing the results from the check of the prior line. We clear this cache at the start of `checkSourceFileWorker`, since flow graphs can never span multiple files and by clearing it we can keep the memory overhead of keeping the cache around lower. We can't really clear it fully at any inner boundaries (like function declarations), since the cache still would have some results form the outer layer we wanna keep around until we're done with that layer (we could track this with a hierarchical cache structure, but.... eh? is it worth it right now?).

Fixes #29926

### CODE REVIEW

**Comment by weswigham** [comment]
Rapidfire extended testing:

@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot perf test

**Comment by weswigham** [comment]
Alright @typescript-bot, give me another go at it; let's see if caching the new thing that we think may have a cost helps.

@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot perf test

**Comment by weswigham** [comment]
@typescript-bot perf test on the post-merge commit I just added just in case it's because the branch was out of date and we secretly introduced sick perf gains into `master` in the last day and that extra caching doesn't actually do much.

**Comment by ajafff** [comment]
> We clear this cache at the start of checkSourceFileWorker, since flow graphs can never span multiple files and by clearing it we can keep the memory overhead of keeping the cache around lower.

I guess there is no way to clear this cache when an API user queries types in arbitrary source files?
How much does it impact memory consumption?

**Comment by weswigham** [comment]
@typescript-bot perf test my latest hypothesis

**Comment by weswigham** [comment]
F. I think on the whole the dictionarylike-object actually performs worse than a native `Map`.

**Comment by weswigham** [comment]
@typescript-bot perf test this - after much iteration, I've found a cache structure with minimal perf impact to the non-bad cases. We also now only cache on `Assignment` flow nodes.

**Comment by weswigham** [comment]
Oh, also: 


@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by weswigham** [comment]
Neato, perf is clean, new test passes, rwc is clean, user suite matches `master`, and hopefully dt should match master once it's done.

@ahejlsberg just wanted to letchya know that I got a version of this working within acceptable parameters, so you should review.

**Comment by weswigham** [comment]
Yep, the one DT failure in `stompjs` is in `master`, so this PR is clean.

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot perf test

Gimmie some final extended approvals bot - DT and RWC should be clean, so hopefully this is all ☑

**Comment by weswigham** [comment]
All ✔ on both the functional and perf suites. @ahejlsberg I would _love_ a once over so I can merge this.

**Comment by ahejlsberg** [comment]
Did you consider making the cache for each assignment node a single key and `FlowType` instead of a full map? It looks to me like we'll rarely if ever cache more than a single key and type. And even then, if we just cache the most recent key and type we'll just recompute if need be. I did a quick experiment of replacing the map with a single key/type store, and it passes the tests just fine. And I would imagine it performs much better. I created a branch for the experiment [here](https://github.com/Microsoft/TypeScript/tree/singletonFlowAssignmentCache).

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Pull request merged**
