### PR TITLE
Fix Go To Source Definition in `--moduleResolution bundler`

### PR DESCRIPTION
**Pull request by andrewbranch**
Happened to notice that `require` wasn’t being followed while I was working on https://github.com/microsoft/vscode/pull/178840

### CODE REVIEW

**Comment by andrewbranch** [comment]
I’d really like to get this into a patch. It should be safe, since `noDtsResolution` is internal and only used by Go To Source Definition.

**Review by sheetalkamat — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
Seems good to me but CI is failing 😄

**Comment by andrewbranch** [comment]
I’m trying to go too fast and thereby going slow 😅

**Review by jakebailey — APPROVED** [review]
x2

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick to release-5.0

**Pull request merged**
