### PR TITLE
Fix: Namespace import doesn't work for modules exported with 'export=…

### LINKED ISSUE #7454: Update "export = <expr>" to use same logic as for "module.exports" in JavaScript files
Per discussion with @mhegazy . See #7249 for the targeted change for the "module.exports = <expr>" in JavaScript files case. Currently doing a namespace import (e.g. `import * as ns from "./mod"`) fails if "./mod" uses the `export = <expr>` syntax.

### PR DESCRIPTION
**Pull request by omefire**
Fixes #7454

### CODE REVIEW

**Comment by omefire** [comment]
@mhegazy, could you please take a look ?

**Comment by omefire** [comment]
The CI failure is due to the linter erroring out on Gulpfile.ts file, probably not related to my code.

**Comment by omefire** [comment]
@vladima could you please take a look at this PR ?

**Comment by vladima** [comment]
change looks ok, assuming that CI build is green

**Pull request closed without merging**
