### PR TITLE
Add resolveLibrary method on hosts and store resolvedLibraries in program so that resolutions can be reused

### PR DESCRIPTION
**Pull request by sheetalkamat**
With this PR:
- Program maintains `resolvedLibraries` which contains the `@typescript/libxxx` resolution and the actual file used as lib so that resolutions are not re-done just to answer if the file is "lib" (c5dc1a0de16d6d43956149a6285bc524382e5e3d though this one is only maintaining the actual lib file used the next commit: fc8c4da615d5e1da72829bc239fd5ef271fa5ad6 modifies to store the resolution to so it can be reused)
- Just like `resolveModuleNameLiterals` or `resolveTypeReferenceDirectiveReferences` we add ` resolveLibrary` method on all hosts and corresponding `hasInvalidatedLibResolutions` to determine if lib resolution is valid. This enables reuse of the library resolution and caching it across program boundaries. This also fixes to use different module resolution cache for library resolutions since its the cache with different options than module resolution. fc8c4da615d5e1da72829bc239fd5ef271fa5ad6
- In watch mode and tsserver, we watch library resolutions just like any other module resolution so on changes we can invoke program update and continue to reuse resolutions that are not invalidated. fc8c4da615d5e1da72829bc239fd5ef271fa5ad6

Fixes https://github.com/microsoft/TypeScript/issues/52759
Fixes https://github.com/microsoft/TypeScript/issues/52707

### CODE REVIEW

**Comment by andrewbranch** [comment]
IIRC module resolution is reported as part of parse time in the perf results? If so, looks like a win.

**Comment by jakebailey** [comment]
@typescript-bot perf test faster

**Comment by sheetalkamat** [comment]
@andrewbranch  @jakebailey  do we want to report library resolution times in `--extendedDiagnostics`? like module resolution times and type ref resolution times. I thought it wouldnt be much and hence not needed but open to adding it if you think that would be helpful to track.

**Comment by sheetalkamat** [comment]
Also for now made the API internal and can make it public if really needed.

**Review by jakebailey — APPROVED** [review]
> do we want to report library resolution times in --extendedDiagnostics? like module resolution times and type ref resolution times. I thought it wouldnt be much and hence not needed but open to adding it if you think that would be helpful to track.

If it's easy, then I feel like it can't hurt, but, it might not be worth it, yeah.

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
