### PR TITLE
package.json `exports` should have priority over `typesVersions`

### PR DESCRIPTION
**Pull request by andrewbranch**
package.json `exports` is a superset of the features supported by `typesVersions`, but currently `typesVersions` is consulted first. This prevents TypeScript from recognizing the `exports` for a path that also matches a `typesVersions` path, which is a big problem if the package wants to use conditional exports that benefit `--moduleResolution nodenext` and `typesVersions` for `--moduleResolution node`. As far as I can tell, this was just an oversight, as no existing tests broke when I changed the order.

Thanks to @fictitious for noticing at https://github.com/andrewbranch/example-subpath-exports-ts-compat/pull/1

### CODE REVIEW

**Review by weswigham — APPROVED** [review]
Maybe a `types@>=4` condition or the like would be useful as a test alongside the typesVersions object, too, if you're up for adding another test case.

**Comment by Andarist** [comment]
This probably needs a big call out in the docs in the `typesVersions` section (and somewhere in the `moduleResolution` stuff too).

**Comment by DanielRosenwasser** [comment]
How's this for the release notes?

> Previously, TypeScript incorrectly prioritized the `typesVersions` field over the `exports` field when resolving through a `package.json` under `--moduleResolution node16`.
> If this change impacts your library, you may need to add a type version selectors in your `exports` field.
> 
> ```diff
>   {
>       "type": "module",
>       "main": "./dist/main.js"
>       "typesVersions": {
>           "<4.8": { "": ["4.8-types/main.d.ts"] },
>           "*": { "": ["modern-types/main.d.ts"] }
>       },
>       "exports": {
>           "*": {
> +             "types@<4.8": "4.8-types/main.d.ts",
> +             "types": "modern-types/main.d.ts",
>               "import": "./dist/main.js"
>           }
>       }
>   }
> ```

**Comment by Andarist** [comment]
q: shouldn't the presented diff only add the `types@<4.8` key? With the logic from this PR in place - are `typesVersions` still handled with `--moduleResolution node16` if there no types-related key in `package.json#exports`? Or are those completely ignored with this `moduleResolution`?

**Comment by andrewbranch** [comment]
The presence of `exports` blocks any non-`exports` keys from contributing to package resolution. That has always been the intention and has been the case for the `types` and `main` fields.

**Comment by weswigham** [comment]
```
     "exports": {
          ".": {
             "import": {
                 "types@<4.8": "4.8-types/main.d.ts",
                 "types": "modern-types/main.d.ts",
                 "default": "./dist/main.js"
              }
          }
      }
```

Is how you should shape that export object, to accommodate types for a `require` condition or similar.

**Pull request merged**
