### PR TITLE
Always emit `any` for `get` accessors

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes at least half of #36216 by always emitting `any` for `get` accessors.

Note that `set` accessors stil emit without parameter types, and from what I can tell TypeScript 3.6 is okay with that under `noImplicitAny`.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.7

**Comment by rbuckton** [comment]
Don't we normally elide the type annotation for `private` declarations?

**Comment by weswigham** [comment]
Eeeyes? I think so. Unsure. @sandersn ?

**Comment by DanielRosenwasser** [comment]
Correct, in #36216 it was reported that 3.6.x incorrectly thinks that an error under `noImplicitAny`.

**Comment by DanielRosenwasser** [comment]
For the record, we stopped erroring on that in thanks to a PR from @ajaff in #33896.

**Comment by sandersn** [comment]
@rbuckton is right, we elide the type annotation for private declarations. The correct thing is not to error on then, so I don't think we should take this PR.

**Review by sandersn — CHANGES_REQUESTED** [review]
We should not error instead of emitting an `any` type.

**Comment by DanielRosenwasser** [comment]
Then please approve #36280

**Pull request closed without merging**
