### PR TITLE
fix missing react error with fragments in `react-native`

### LINKED ISSUE #60588: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
### 🔎 Search Terms

Hi, from ts 5.7, I'm getting the same error as reported in #60132 but for `jsx: react-native`. Wheneven I use `<></>`, I get the above error

### 🕗 Version & Regression Information

- This changed between versions 5.6 and 5.7

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=3&ts=5.7.2#code/JYWwDg9gTgLgBAbzgNWAUwO5wL5wGZQQhwDkUaAhgMYwC0AdhTMAG5okDcAUF2gB6RY+AK70awCPTgBhIpHpp6MABQBKBD3IxhUKQB4AfFzhw9qTAb0B6cxiMmz6O9dv3TVo9iA

### 💻 Code

```ts
import { View } from 'react-native';

export function Component(){

return <>
  <View></View>
  <View></View>
  </>
}
```

### 🙁 Actual behavior

The fragment shows an error

### 🙂 Expected behavior

This should work like ts 5.6 and shouldn't error

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by iisaduan**
fixes #60588 

same problem and fix as #60122

### CODE REVIEW

**Comment by iisaduan** [comment]
@typescript-bot test it

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.7

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.7

**Comment by DanielRosenwasser** [comment]
oops

**Comment by jakebailey** [comment]
the bot should not have been able to make two PRs, but I guess it did because the first got merged?

**Pull request merged**
