### PR TITLE
Do not watch root folders for failed lookup locations and effective type roots

### LINKED ISSUE #19170: Excessive DirectoryWatcher recursive logs and TypeScript server hang
**TypeScript Version:**  2.6.0-dev.20171013

**Repo**
1. Open vs code and open the vscode repo
2. run our npm install script: `./script/npm.sh install`

**bug**
I see a huge number of these messages in the TSServer log:

```
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/@types/minimist-cb6a846a/package.json.1048325057 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-filter-0a0f4d69/package.json.2424320078 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-filter-0a0f4d69/package.json.2424320078 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-mocha-524b0afc/package.json.3753437926 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-mocha-524b0afc/package.json.3753437926 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-bom-a87af56a/package.json.2803377959 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-bom-a87af56a/package.json.2803377959 PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.408] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-json-editor-4f38ed7e/test/byObject.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.413] DirectoryWatcher recursive:: Elapsed: 5ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-json-editor-4f38ed7e/test/byObject.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.413] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-tslint-ff59e88c/CHANGELOG.md PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.413] DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-tslint-ff59e88c/CHANGELOG.md PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.413] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-image-resize-2d801cc7/test/image_resize_test.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.418] DirectoryWatcher recursive:: Elapsed: 5ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-image-resize-2d801cc7/test/image_resize_test.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.418] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-buffer-64fa6fa0/test PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.418] DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-buffer-64fa6fa0/test PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.418] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/http-proxy-agent-4f953650/test/test.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.425] DirectoryWatcher recursive:: Elapsed: 7ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/http-proxy-agent-4f953650/test/test.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.425] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/https-proxy-agent-0189e983/test/test.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.431] DirectoryWatcher recursive:: Elapsed: 6ms Trigger: /Users/matb/projects/vscode/node_modules/.staging/https-proxy-agent-0189e983/test/test.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 17299[14:27:50.432] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/node_modules/.staging/gulp-uglify-f9893af5/lib/gulp-uglify-error.js PathInfo: /Users/matb/projects/vscode/node_modules Project: /Users/matb/projects/vscode/extensions/typescript/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
```

The log file is over 750mb now

The typescript server also appears to hang during the install process.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #19170

### CODE REVIEW

**Comment by mhegazy** [comment]
@mjbvz can you give this a quick test on the vscode scenario in #19170

**Comment by mjbvz** [comment]
Thanks for taking a look. Things look much better for tsserver responsiveness now. The log file does still grow fairly large and there are a number of log events for sub `node_modules` directories, such as `build/lib/watch/node_modules`:

```
Info 36810[14:33:46.246] DirectoryWatcher recursive:: Trigger: /Users/matb/projects/vscode/build/lib/watch/node_modules/.staging/fsevents-4d579504/node_modules/readable-stream/lib/_stream_passthrough.js PathInfo: /Users/matb/projects/vscode Project: /Users/matb/projects/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
```

Should these be excluded as well?

**Comment by sheetalkamat** [comment]
Sadly there is no way to exclude that and still keep project upto date.. The watched folder vscode will exist since the module resolution strategy for your project is amd, program is going to lookup files in this folder to resolve module names. Note that even though this is logged, it is not actionable since we eliminate many file additions/removals

**Comment by mhegazy** [comment]
Adding `baseUrl` and using `moduleResolution: node` should make sure that we only look under the source folder and do not walk higher (except for node_modules).

**Pull request merged**
