### PR TITLE
Improve detection of type variables in instantiated object types

### PR DESCRIPTION
**Pull request by ahejlsberg**
When an object type that references type parameters is instantiated, it is often the case that the resulting instantiated type _doesn't_ reference type parameters (because it is often the case that all type arguments are non-generic types). With this PR we improve our detection of such object types in order to short-circuit further pointless type instantiation and type inference involving those types.

The optimizations in this PR reduces the check time for the [material-ui](https://github.com/mui/material-ui) project by over 50%. (Note that the reduction isn't nearly as dramatic with the very old version of material-ui we use in our performance test suite.)

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by oliviertassinari** [comment]
Oh wow, @mnajdova you might want to run your TypeScript benchmark against this change, see if we can measure the impact.

**Review by weswigham — APPROVED** [review]
We can tighten these checks _even further_, when we want to, now that we're willing to rely on there not being any sneaky type variables outside the object's mapper (which, iirc, is what we've worried about when I've mentioned doing this in the past). Since mappers have inspectable sources and targets (where possible) nowadays, we can rig them to actually keep a set of _which_ type parameters remain unmapped for a given stack of mappers after instantiation when we compose them, and then use that to check if any of the inference targets are actually still present in the target type (thus, allowing us to skip inference on arguments or parts of types which only contain type parameters for outer calls).

**Comment by jakebailey** [comment]
```
Benchmark 1: 4.9
  Time (mean ± σ):     85.634 s ±  0.332 s    [User: 82.993 s, System: 2.638 s]
  Range (min … max):   85.384 s … 86.006 s    5 runs
 
Benchmark 2: 5.0
  Time (mean ± σ):     77.467 s ±  1.111 s    [User: 74.444 s, System: 3.016 s]
  Range (min … max):   76.656 s … 79.313 s    5 runs
 
Benchmark 3: PR 53246
  Time (mean ± σ):     49.761 s ±  0.355 s    [User: 47.202 s, System: 2.552 s]
  Range (min … max):   49.439 s … 50.297 s    5 runs
 
Summary
  'PR 53246' ran
    1.56 ± 0.02 times faster than '5.0'
    1.72 ± 0.01 times faster than '4.9'
```

☺️

**Comment by jakebailey** [comment]
Just in case anyone was confused as to why I'm not getting quite the great number, the above is the _total_ time end-to-end measured via `hyperfine` + `tsc`, so includes parse/bind/emit as well as check, whereas the PR description mentions specifically check time.

**Comment by tomaszs** [comment]
Hello, I was browsing that MR and the source code but have trouble understanding what is it about. It would be great to read a description for mortal human being because it's interesting. Great work BTW. Congrats on the results!

**Pull request merged**
