### PR TITLE
Narrow unions to the narrowest constituent on assignment

### LINKED ISSUE #47731: Narrow subtype-reduction-prone unions to their narrowest constituent
# Bug Report

Type narrowing doesn't seem to take into account an assignment I made to ensure the variable has the right type.

Maybe related? https://github.com/microsoft/TypeScript/issues/43584#issuecomment-816932485

### 🔎 Search Terms

type narrowing assignment 

### 🕗 Version & Regression Information

4.5.4

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "type narrowing"

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEEQBd5QFzwPYCMBW4qAPmgHYCeA2gLrwkCupoAZgJakjABQXrz8ACijwAvGPiMW7TgEp4Aby7xlaUfBpcAvvBAQAzgj6CAhAEEYMKOQB0rPecvkhMuYpXxkACxhYA7vA5-AFELLBgBGS0uSmtYqGouIA)

### 💻 Code

```ts
declare let a: object | any[] | undefined

if (a === undefined) {
    a = [] // I expect this line to have TS understand that a is any[] from now on
} else if (!Array.isArray(a)) {
    throw new Error()
}
[...a] // complains here because a is object | any[]
```

### 🙁 Actual behavior

`a` has type `object | any[]`

### 🙂 Expected behavior

`a` to have type `any[]`

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #47731

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot user test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot user test thsi

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
`+1.45s (+12.78%)` 😭

I don't think we can take this as-is (Compiler Unions project is fairly representative of union-heavy codebases) given the original bug isn't super compelling.

**Comment by Zzzen** [comment]
image

ok, nothing to see here

**Comment by matthargett** [comment]
Can we re-open this PR and rebase to recheck the performance now? I'm actually running into this problem, the ergonomics are not great.

**Comment by Zzzen** [comment]
The performance is unlikely to change. But it could be improved by caching. Do you know how to try the performance test suite at home? @RyanCavanaugh

**Pull request closed without merging**
