### PR TITLE
Emit class fields as-is with `target: es2022`

### LINKED ISSUE #47017: Emit class fields as-is with `target: es2022`
# Suggestion

## 🔍 Search Terms

es2022, class field

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Emit class fields as-is with `target: es2022`.

## 📃 Motivating Example

Projects targeting es2022 can emit class fields as-is.

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #47017

### CODE REVIEW

**Review by sandersn — APPROVED** [review]

**Comment by a-tarasyuk** [comment]
It seems this PR breaks the [build](https://github.com/microsoft/TypeScript/runs/4554420914?check_suite_focus=true). Not sure, maybe a need to update the baseline.

**Comment by sandersn** [comment]
Yep, it's because of the other recent PR that de-dupes private field errors. I'll update the baselines and send a PR.

**Comment by a-tarasyuk** [comment]
@sandersn I can make PR, with updated baselines.

**Comment by sandersn** [comment]
Don't worry, I've got it.

**Comment by a-tarasyuk** [comment]
Oke, thanks.

**Pull request merged**
