### PR TITLE
Array predicates should not have to return boolean

### LINKED ISSUE #27496: Array functions taking predicates should not have to return boolean.
## Search Terms

predicate find force boolean

## Suggestion

As per #5850 `array.prototype.filter` doesn't enforce `boolean` as a return type anymore. I want to propose the same behavior for wherever a predicate is needed. This means not only `filter`, but `find`, `some`, `every `and maybe others. These functions should not enforce boolean as return type of the predicate passed to them.

## Use Cases

This will be useful wherever the developer is looking for a result that is not missing some value(s).

## Examples

Say I want to find the first `parkSpace` that has `position`. This works in TypeScript 3.1.1:
`this.selectedParkSpace = this.parkSpaces.filter(o => o.position)[0] || null;`

but this doesn't:
`this.selectedParkSpace = this.parkSpaces.find(o => o.position) || null;`

For the latter, TypeScript complains:
> Type 'undefined' is not assignable to type 'boolean'.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

### PR DESCRIPTION
**Pull request by Excolo**
Changes predicate return type from `boolean` to `any` for array operations `find`, `findIndex`, `some` and `every`, such that the behavior matches that of the `filter` operation.

Fixes #27496

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Test bench:
```ts
function filter1<T>(arr: T[], pred: (arg: T) => any) { }
function filter2<T>(arr: T[], pred: (arg: T) => unknown) { }
function filter3<T>(arr: T[], pred: (arg: T) => boolean) { }
function filter4<T>(arr: T[], pred: (arg: T) => {}) { }
function filter5<T>(arr: T[], pred: (arg: T) => {} | null | undefined) { }

const arr = [0];

filter1(arr, i => { });
filter1(arr, i => "");
filter1(arr, i => { return; });
filter1(arr, i => { return null; });
filter1(arr, i => { return undefined; });

filter2(arr, i => { });
filter2(arr, i => "");
filter2(arr, i => { return; });
filter2(arr, i => { return null; });
filter2(arr, i => { return undefined; });

filter3(arr, i => { });
filter3(arr, i => "");
filter3(arr, i => { return; });
filter3(arr, i => { return null; });
filter3(arr, i => { return undefined; });

filter4(arr, i => { });
filter4(arr, i => "");
filter4(arr, i => { return; });
filter4(arr, i => { return null; });
filter4(arr, i => { return undefined; });

filter5(arr, i => { });
filter5(arr, i => "");
filter5(arr, i => { return; });
filter5(arr, i => { return null; });
filter5(arr, i => { return undefined; });
```
I think `filter5` has the best behavior of these when looking at both strictNullChecks on and off

**Comment by Excolo** [comment]
I agree, but it would still be slightly more restrictive than the filter function in plain JavaScript. Following the discussion in #5850 it sounds like `filter5` has the desired behavior. 

Should I change the `filter` function in the same go or should it be a subject of a separate PR?

**Comment by RyanCavanaugh** [comment]
I'm going to take this to the design meeting

**Comment by RyanCavanaugh** [comment]
This one's a bit out of date and we'd prefer a change to `unknown` per discussion notes. Sorry for the long timeline on this PR.

**Pull request closed without merging**
