### PR TITLE
Preserve source newlines all the things

### LINKED ISSUE #843: Emit does not preserve empty lines
Hi,

**TS Version**: 1.1

Given

``` TypeScript
function foo() {

    var x = 10;

    var y = 11;
}
```

 We used to get

``` JavaScript
function foo() {
    var x = 10;

    var y = 11;
}
```

In the new compiler the line break is missing

``` JavaScript
function foo() {
    var x = 10;
    var y = 11;
}
```

(Both compilers removed the first empty line, but the new compiler has gone a step further.)

This can affect the experience when debugging JavaScript in the browser.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
An experiment right now to see how the compiler does with preserving source newlines. Right now, the most interesting thing is seeing the bad emit - what is going wrong. The same issues might apply to refactorings/quick fixes, so we should understand what's going wrong and fix that.

Sorta fixes #843.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
It's really fascinating to see that this consistently adds up to half a second in compilation times on Node 10 for so many of these projects.

**Comment by andrewbranch** [comment]
I just merged #37846 into this to see how it does.

**Comment by andrewbranch** [comment]
Looks like all the semicolon-related ones are fixed, but I still see a bunch of synthesized statements starting immediately after a `}` token. https://github.com/microsoft/TypeScript/pull/37814/files#diff-c4678205d156e68a66bfc2a581356267R31

**Comment by andrewbranch** [comment]
I’m not sure whether it’s possible to hit that in a refactor, but I could debug the JS emit on one of these and see what the logical error is. I just might not have a test case to add for it.

**Comment by andrewbranch** [comment]
Pushed some commits that fix most of the problems at the cost of falling back to the non-source-peeking approach for any construct that fails to set an `original` node while going through the transformers. I fixed a couple instances of that in https://github.com/microsoft/TypeScript/pull/37814/commits/dd5413623a88dd672f7c171cb00dfe3b713cc73d. Kind of interesting. I’m not sure any of these new commits would affect refactors at all.

**Comment by mbroadst** [comment]
@andrewbranch is this change slated for a particular version, or just an experiment?

**Comment by andrewbranch** [comment]
It’s just an experiment, and in fact it’s more @DanielRosenwasser’s than mine, and I’m not sure what his thoughts on this are long-term. We’ve tossed around the idea of exposing this as an opt-in option. For my part, I’m currently pretty leery of that, because aside from the things that look clearly wrong in this diff, there are tons of constructs where we currently don’t check for whitespace, and adding a check to each of those places adds complexity and impacts performance.

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this draft PR. It's pretty old.

**Pull request closed without merging**
