### PR TITLE
Ignore awaited self tail calls when collecting the return type of an async function

### PR DESCRIPTION
**Pull request by Andarist**
closes https://github.com/microsoft/TypeScript/issues/55973
expands https://github.com/microsoft/TypeScript/pull/53995

cc @RyanCavanaugh

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Review by jakebailey — APPROVED** [review]
This seems correct to me. But, will wait for the extended results of course.

**Comment by jakebailey** [comment]
Hm, seems like this might be wrong as it's removing the JSDoc annotation around parens.

**Comment by jakebailey** [comment]
Of course, someone's already thought of this. We need:

```
skipParentheses(node, /*excludeJSDocTypeAssertions*/ true)
```

**Comment by jakebailey** [comment]
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Review by jakebailey — APPROVED** [review]
Seems correct to me (again)... 😄

**Pull request merged**
