### PR TITLE
Stage 3 Decorators normative changes

### LINKED ISSUE #56606: Normative changes to decorator "extra initializer" evaluation order
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Per https://github.com/pzuraq/ecma262/pull/12/files, which achieved consensus in the November 2023 TC39 meeting, the "extra initializers" for fields/auto-accessors (added by `context.addInitializer`) now need to be run independently for each field, _immediately after_ the field itself is initialized and defined on the class instance.

This results in the need to change our emit for Stage 3 decorators as follows:

Given:
```ts
class C {
  @dec a;
  @dec b;
  @dec f() { }
}
```

We currently emit (some parts elided):
```js
let C = (() => {
  ...
  return class C {
    static {
      ...
      __esDecorate(null, null, _f_decorators, { ... }, null, _instanceExtraInitializers);
      __esDecorate(null, null, _a_decorators, { ... }, _a_initializers, _instanceExtraInitializers);
      __esDecorate(null, null, _b_decorators, { ... }, _b_initializers, _instanceExtraInitializers);
      ...
    }
    a = (__runInitializers(this, _instanceExtraInitializers), __runInitializers(this, _a_initializers, void 0));
    b = __runInitializers(this, _b_initializers, void 0);
    f() { }
  };
})();
```

Here, we collect all "instance extra initializers" in a single array and evaluate them immediately after the `this` value is bound in the constructor (i.e. immediately upon entry to the constructor in a base class, or immediately after `super()` is called in a derived class). When fields are present, we evaluate the extra initializers as part of evaluating the initializer for the first field of the class.

After this change, we need to emit something like this instead:
```js
let C = (() => {
  ...
  let _a_extraInitializers = [];
  let _b_extraInitializers = [];
  return class C {
    static {
      __esDecorate(null, null, _f_decorators, { ... }, null, _instanceExtraInitializers);
      __esDecorate(null, null, _a_decorators, { ... }, _a_initializers, _a_extraInitializers);
      __esDecorate(null, null, _b_decorators, { ... }, _b_initializers, _b_extraInitializers);
    }
    constructor() {
      __runInitializers(this, _b_extraInitializers);
    }
    a = (__runInitializers(this, _instanceExtraInitializers), __runInitializers(this, _a_initializers, void 0));
    b = (__runInitializers(this, _a_extraInitializers), __runInitializers(this, _b_initializers, void 0));
    f() { }
  };
})();
```

Here, we still run the extra initializers for methods/getters/setters first, but we run the extra initializers for `a` after it is defined on the instance, but before we initialize `b`, and run the initializers for `b` at the top of the constructor, which is evaluated after `b` has been defined on the instance.

### PR DESCRIPTION
**Pull request by rbuckton**
This changes our Stage 3 Decorators down-level emit to align with recent normative changes to the proposal. 

Unfortunately, this will further complicate #55688, which pertains to the emit size for decorators, as this will increase overall emit size since we have to track "extra" initializers on a per-element basis.

Related pzuraq/ecma262#12
Related tc39/proposal-decorators#513
Fixes #56606

### CODE REVIEW

**Comment by fatcerberus** [comment]
*More* normative changes in Stage 3?  They really can’t nail this one down, can they?

**Comment by rbuckton** [comment]
> _More_ normative changes in Stage 3? They really can’t nail this one down, can they?

This happens with any large proposal. Runtimes generally don't start actual implementations until Stage 3, and once they do there is often feedback that requires normative changes based on implementation experience. The point of Stage 3 is to catch these issues when the rubber hits the road. So far, the changes to Decorators in Stage 3 have been relatively minor compared to other proposals of this magnitude and consist mostly of timing-related changes so that the feature is consistent and meets user expectations. Decorators is actually fairly stable in comparison, and the fact we have only had such minor changes is a testament to the time, energy, and attention to detail of everyone involved in the proposal.

**Comment by fatcerberus** [comment]
I guess it seems worse because IIRC decorators were stage 3 originally, then rolled back to stage 2 for a bit, and now are stage 3 again, so the normative changes since then stand out more.

**Review by jakebailey — APPROVED** [review]
Based on my naive understanding, LGTM 😄 

(Needs a `dprint fmt`).

**Pull request merged**
