### PR TITLE
Add intrinsic string manipulation type for case-changing methods

### LINKED ISSUE #44268: String case change methods should return intrinsic string manipulation types
# lib Update Request

## Configuration Check

My compilation *target* is `ES2018` and my *lib* is `["ES2016", "dom"]`.

## ~~Missing / Incorrect~~ Imprecise Definitions

At least `toUpperCase` and `toLowerCase` methods on `String`, maybe/probably also the `Locale` versions?

## Sample Code

````ts
type LittleT = "t" | "tt";
type BigT = Uppercase<LittleT>;
declare const smol: LittleT;
const big: BigT = smol.toUpperCase(); // err, string is not assignable to "T" | "TT
````

## Documentation Link

https://tc39.es/ecma262/#sec-string.prototype.tolowercase

## Note

I'm not sure about the `Locale` versions of these methods because I don't know what algorithm the "intrinsic" `Uppercase<T>` / `Lowercase<T>` helper types are required to follow.  (Do we need separate `LocaleUppercase` / `LocaleLowercase` helpers?)

### PR DESCRIPTION
**Pull request by jonkoops**
Fixes #44268

### CODE REVIEW

**Comment by Nixinova** [comment]
Why the close?

**Comment by jonkoops** [comment]
I have had no time to work on this further and the work here is incomplete.

**Comment by bfaulk96** [comment]
But what all is incomplete on this?

**Comment by RyanCavanaugh** [comment]
We don't add features to the language based on whether or not someone has sent a PR to implement them, so whether this PR is complete or not isn't particularly relevant.

**Pull request closed without merging**
