### PR TITLE
Remove old "start" script from package.json

### PR DESCRIPTION
**Pull request by PUNAMRAMPUKALE**
Fixes #
https://github.com/microsoft/TypeScript/issues/56581

### CODE REVIEW

**Comment by PUNAMRAMPUKALE** [comment]
> This PR doesn't have any linked issues. Please open an issue that references this PR. From there we can discuss and prioritise. comment Addressed

**Comment by PUNAMRAMPUKALE** [comment]
(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
This is most definitely not correct. The "built" dir is not shipped to users. The actual package is produced via `hereby lkg`

If anything, we should remove the start script.

**Comment by PUNAMRAMPUKALE** [comment]
@jakebailey shall I remove start script ? As I have checked with 'hereby log' it is working fine.

**Comment by PUNAMRAMPUKALE** [comment]
@jakebailey @typescript-bot @rictic @Peeja Can you please look into this issue.

**Comment by Peeja** [comment]
@PUNAMRAMPUKALE Sorry, what's this about? Was this an issue I was involved with?

**Comment by PUNAMRAMPUKALE** [comment]
@Peeja Not sure but this issue tagged under 'Infrastructure' label.

**Comment by jakebailey** [comment]
Please don't ping random people. Half of who you pinged don't work on TypeScript, and the other is a bot.

**Comment by PUNAMRAMPUKALE** [comment]
@jakebailey I will keep in mind.can you please confirm this PR as it is pending since a few days

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
