### PR TITLE
Make getCompletionEntryDetails and getCompletionEntrySymbol parameters non-optional

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes https://github.com/Microsoft/TypeScript/pull/19455#discussion_r147214986

### CODE REVIEW

**Comment by andy-ms** [comment]
@mhegazy Let's get this in for the 2.6 release.

**Comment by mhegazy** [comment]
Following https://github.com/Microsoft/TypeScript/pull/19455#discussion_r147300204, we should also change the API version

**Comment by mhegazy** [comment]
we also need that in release-2.6

**Comment by mhegazy** [comment]
@andy-ms we need to port this to release-2.6 and add a note about it in https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes

**Comment by angelozerr** [comment]
Thanks @mhegazy to have pinged me about this change. Is it possible to describe which methods change their signature  at https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes (it seems that it's just for completion)

In https://github.com/angelozerr/tslint-language-service we override only `getSemanticDiagnostics` and `getCodeFixesAtPosition`, so perhaps we need to do nothing. Thanks for your feedback!

**Comment by andy-ms** [comment]
@angelozerr Added the method names. If your code compiles that should mean that you don't need to change anything.

**Comment by angelozerr** [comment]
Thanks a lot @andy-ms !

**Pull request merged**
