### PR TITLE
Preserve alias symbols on references to type aliases via imports

### LINKED ISSUE #51106: some types compile to a massive conditional type that causes performance issues
# Bug Report
sorry i tried to create a minimal repro but this is the best i could do, so to reproduce this, run `npm install @detachhead/ts-helpers`
### 🔎 Search Terms
d.ts performance

### 🕗 Version & Regression Information
4.9.0-dev.20221007

### 💻 Code
takes like 2 minutes to compile:
```ts
import { power } from '@detachhead/ts-helpers/dist/utilityFunctions/Number'
power
```
takes a couple seconds to compile:
```ts
import { power } from '@detachhead/ts-helpers/src/utilityFunctions/Number'
power
```

### 🙁 Actual behavior
the `power` function is being compiled to return this huge conditional type that causes the compiler to hang for several minutes when it's imported:
```ts
// Number.ts
export const power = <Num extends number, PowerOf extends number>(
    num: Num,
    powerOf: PowerOf,
): Power<Num, PowerOf> => (num ** powerOf) as never
```
```ts
// Number.d.ts
export declare const power: <Num extends number, PowerOf extends number>(num: Num, powerOf: PowerOf) => number extends PowerOf ? PowerOf & number : PowerOf extends 0 ? 1 : number extends Subtract<PowerOf, 1> ? Subtract<PowerOf, 1> & number : Subtract<PowerOf, 1> extends infer T ? T extends Subtract<PowerOf, 1> ? T extends 0 ? Multiply<1, Num> : number extends Subtract<T, 1> ? Subtract<T, 1> & number : Subtract<T, 1> extends infer T_1 ? T_1 extends Subtract<T, 1> ? T_1 extends 0 ? Multiply<Multiply<1, Num>, Num> : number extends Subtract<T_1, 1> ? Subtract<T_1, 1> & number : Subtract<T_1, 1> extends infer T_2 ? T_2 extends Subtract<T_1, 1> ? T_2 extends 0 ? Multiply<Multiply<Multiply<1, Num>, Num>, Num> : number extends Subtract<T_2, 1> ? Subtract<T_2, 1> & number : Subtract<T_2, 1> extends infer T_3 ? T_3 extends Subtract<T_2, 1> ? T_3 extends 0 ? Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num> : number extends Subtract<T_3, 1> ? Subtract<T_3, 1> & number : Subtract<T_3, 1> extends infer T_4 ? T_4 extends Subtract<T_3, 1> ? T_4 extends 0 ? Multiply<Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num>, Num> : number extends Subtract<T_4, 1> ? Subtract<T_4, 1> & number : Subtract<T_4, 1> extends infer T_5 ? T_5 extends Subtract<T_4, 1> ? T_5 extends 0 ? Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num>, Num>, Num> : number extends Subtract<T_5, 1> ? Subtract<T_5, 1> & number : Subtract<T_5, 1> extends infer T_6 ? T_6 extends Subtract<T_5, 1> ? T_6 extends 0 ? Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num>, Num>, Num>, Num> : number extends Subtract<T_6, 1> ? Subtract<T_6, 1> & number : Subtract<T_6, 1> extends infer T_7 ? T_7 extends Subtract<T_6, 1> ? T_7 extends 0 ? Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num>, Num>, Num>, Num>, Num> : number extends Subtract<T_7, 1> ? Subtract<T_7, 1> & number : Subtract<T_7, 1> extends infer T_8 ? T_8 extends Subtract<T_7, 1> ? T_8 extends 0 ? Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num>, Num>, Num>, Num>, Num>, Num> : number extends Subtract<T_8, 1> ? Subtract<T_8, 1> & number : Subtract<T_8, 1> extends infer T_9 ? T_9 extends Subtract<T_8, 1> ? T_9 extends 0 ? Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<Multiply<1, Num>, Num>, Num>, Num>, Num>, Num>, Num>, Num>, Num>, Num> : any : never : never : never : never : never : never : never : never : never : never : never : never : never : never : never : never : never : never : never : never;
```

### 🙂 Expected behavior
```ts
// Number.d.ts
export declare const power: <Num extends number, PowerOf extends number>(
    num: Num,
    powerOf: PowerOf,
) => Power<Num, PowerOf>
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #51106

Technically, we could _always_ use the alias we're referring to as the alias symbol saved for an alias lookup, but that could be a lot of new type identities, and by limiting it to only cases where the type reference refers to an import alias, we capture the cases where referring to exactly the symbol exported is particularly important for reusing the imports/names the user has made available.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Comment by weswigham** [comment]
Perf looks good (sometimes unreasonably so - looking at you TFS), so this looks like a pretty good approach to the problem.

@typescript-bot test top100
@typescript-bot user test this
@typescript-bot test this

**Review by andrewbranch — APPROVED** [review]

**Comment by sandersn** [comment]
@typescript-bot run dt

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
Looks good; I started a DT run because something that increases the number of type identities sometimes fails there.

**Comment by weswigham** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
Breaks 2 DT packages (lambda-tester, mparticle__web-sdk), in a way I can't understand yet. I'll open a bug.

**Pull request merged**
