### PR TITLE
Allow Boolean() to be used to perform a null check

### LINKED ISSUE #16655: Boolean() cannot be used to perform a null check
**TypeScript Version:**  2.4.0

Apologies for today's issue raising binge.

**Code**

```ts
// Compiles
const nullCheckOne = (value?: number) => {
    if (!!value) {
        return value.toFixed(0);
    }

    return '';
}

const nullCheckTwo = (value?: number) => {
    if (Boolean(value)) {
        // Object is possibly 'undefined'
        return value.toFixed(0);
    }

    return '';
}

```
**Expected behavior:**
Both examples compile.

**Actual behavior:**
The latter example fails w/ `Object is possibly 'undefined'`.

**Explanation**
To my knowledge `!!value` and `Boolean(value)` are equivalent. I'm wondering what is the reason behind not supporting the second case. One reason I can think of would be an imported, non-typescript module, globally overriding it to something like: `Boolean = (value) => !value`.

### PR DESCRIPTION
**Pull request by ForbesLindesay**
Fixes #16655

This allows code like:

```typescript
const nullableValues = ['a', 'b', null];
const values: string[] = nullableValues.filter<string>(Boolean);
```

to be written and to typecheck. Unfortunately the generic type still has to be specified, otherwise TypeScript picks the other, less specific overload of `.filter`.

### CODE REVIEW

**Comment by beshanoe** [comment]
Hi, this is a really good initiative, do you think we can skip specifying generic after this
https://github.com/Microsoft/TypeScript/pull/30215 is merged?

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by ForbesLindesay** [comment]
@beshanoe I think that may be sufficient to allow us to skip specifying generic parameters. I'm not sure though without testing it.

I found:

```ts
function B<T>(value: T): value is Exclude<T, false | null | undefined | '' | 0> {
  return Boolean(value);
}
```

was already sufficient, but adding prototypes/new functions to the interface forces you to be explicit.

**Comment by RyanCavanaugh** [comment]
@ForbesLindesay can you merge this up with master? This will allow us to re-run the RWC suite to evaluate the effects of this on our real-world code database

**Comment by ForbesLindesay** [comment]
@RyanCavanaugh sorry I didn't see your message. I've merged it now.

**Comment by ForbesLindesay** [comment]
@RyanCavanaugh any update on this?

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
RWC is actually clean, ignore ❌

**Comment by ForbesLindesay** [comment]
@RyanCavanaugh any chance we can merge this? It's been a while and it's a very simple fix.

**Comment by victorouse** [comment]
> @RyanCavanaugh any chance we can merge this? It's been a while and it's a very simple fix.
☝️ 🙏

**Comment by pelotom** [comment]
Resolves #31164.

**Comment by natew** [comment]
I'm getting `unknown` now with 3.5.0-rc, when before it worked.

**Comment by silentroach** [comment]
broken by #31515

**Comment by city41** [comment]
This would be a great addition to the language. Have there been any plans on when it might land? 3.8 maybe?

**Comment by pret-a-porter** [comment]
@city41 Unfortunately it is still open #16655 Really strange thing, that behaviour of `!!someValue` differs from `Boolean(someValue)`

**Comment by ShanonJackson** [comment]
@RyanCavanaugh 

Can we revive this. Still continues to prevent usage of the .filter(Boolean) syntax sugar today.

**Comment by stevage** [comment]
Is there a good workaround in the meantime? I'm not sure how else to express `.filter(Boolean)` in a way Typescript accepts.

**Comment by jakebailey** [comment]
> Is there a good workaround in the meantime? I'm not sure how else to express `.filter(Boolean)` in a way Typescript accepts.

You can use type guards:

```ts
["", undefined, "test"].filter((x): x is string => typeof x === "string")
```
[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwTAvDA2gIkwGhgVzABMBTAMwEswSi9MoTpMBdAOkoBsGEAKHgDwCUALhj8YFCDGgIqAc1QA+GFACeABxIgyY1CjSYZ8zIIBQAenMxr1gHoB+IA)

**Comment by ShanonJackson** [comment]
```
.filter((x): x is NonNullable<typeof x> => Boolean(x))
```
Works universally for any `Array<T>`

**Comment by jonny133** [comment]
> ```
> .filter((x): x is NonNullable<typeof x> => Boolean(x))
> ```
> 
> Works universally for any `Array<T>`

The code in https://github.com/microsoft/TypeScript/pull/29955#issuecomment-470062531 more completely shows the result of `Boolean` excludes other falsey values

**Pull request merged**
