### PR TITLE
chore: add packageManager field to support corepack

### PR DESCRIPTION
**Pull request by Jack-Works**
Corepack is a new package manager manager that default ships in Node 16.9.0.

It will select the correct NPM version based on the "packageManager" field in the package.json

I added this field and set it to 6.14.15. It's the current latest NPM version that uses NPM lockfile version 1.

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]
This seems correct to me; I was going to ask about forward compatibility (I don't know if anyone's testing npm 6 with future versions of node, or if they will push patches to keep it going), but that doesn't really apply if we currently use the v1 lock file, and 7+ don't do it.

**Comment by Jack-Works** [comment]
Yeah, if anyone runs npm install in TS repo with NPMv7 or higher, they will have an extra step to resolve all dependencies, and the lock file will be upgraded to V2. Actually I suggest to use lockfile v2 since this only affects the developers of TypeScript

**Comment by jakebailey** [comment]
IMO it's not a good idea to upgrade to npm 7+ if we're still supporting LTS editions that come with npm 6 (otherwise, CI has to do further upgrades or face the "trying my best with v2" message), but it will be a good while until it's totally unsupported, so that's probably not a great motivator.

I know we have benchmarks and other CI that need to run on older versions of node (I think back to 10), but I think npm 7 can do node 10 (whereas npm 8 is node 12+, the current LTS).

Potentially once the lockfile is bumped to v2, we could drop this corepack entirely to not over-restrict (so long as the v2 format is fixed and agrees between npm 7 and npm 8, and so on).

**Comment by orta** [comment]
Agree, this is probably the right call until we move everything over to npm 7

**Pull request merged**
