### PR TITLE
Perf test PR for "Optimize source mapping into external source map sources"

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Reverts microsoft/TypeScript#40055

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@sheetalkamat looks like this may have actually been a (very minor) regression. Do you think that's just variance?

**Comment by JoostK** [comment]
@DanielRosenwasser thanks for running the perf tests, I do agree that it looks like a slight regression.

I opened #40130 that implements the alternative I mentioned in https://github.com/microsoft/TypeScript/pull/40055#discussion_r470853352, which does away with the full cache and fully removes the overhead from the source map generator (I actually like this approach much better than my original PR, looking at it now). Could you please trigger a perf run for that one as well?

---

Unrelated: I am being requested to sign the CLA in https://github.com/microsoft/TypeScript/pull/40130#issuecomment-675918007, which I wasn't in #40055. Maybe something you'll want to look into.

**Comment by sheetalkamat** [comment]
I think it would be better to merge this revert and then rebase #40130  and then run perf test on this.

**Pull request merged**
