### PR TITLE
With --isolatedModules, --declaration emit is now allowed and builder handles it for incremental compilation

### LINKED ISSUE #29490: Allow `emitDeclaration` and `isolatedModules` together
## Search Terms

isolated modules emit declaration

## Suggestion

In the blog post introducing Babel 7, it's recommended to use `--isolatedModules` in the "Caveats" section (https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/).

We use Babel to transpile our TS to better work with other tools in the ecosystem (such as Emotion or Jest), but we'd also still like to generate declaration files so consumers of our libraries can enjoy the type information.

However, when trying to follow the advice of adding `isolatedModules` to our config, we get the following warning:

```
tsconfig.json:5:5 - error TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.

5     "declaration": true,
      ~~~~~~~~~~~~~
```

## Use Cases

As mentioned, I'd like to create declaration files for libraries who are transpiled using `babel`. I'd also like to make sure that whatever guarantees `isolatedModules` adds to allowed syntax are present, outside of the type information.

Babel itself will complain if we use e.g. `const enum`, but that only happens at compile time - `isolatedModules` will also show a warning in the IDE while writing the code.

## Examples

Same as we currently get with `{"declaration": true, "emitDeclarationOnly": true}`, but with added `{"isolatedModules": true}`.

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by sheetalkamat**
Enables .d.ts emit with `--isolatedModules`
Builder handles the emit so that it can cache semantic diagnostics as well as do d.ts emit

Fixes #29490 and #32294

### CODE REVIEW

**Comment by pleerock** [comment]
now we'll be able to use react in monorepos

**Comment by Bnaya** [comment]
Will it make possible to use `isolatedModules` and `composite` ?

**Comment by sheetalkamat** [comment]
Ping for review

**Comment by pleerock** [comment]
@sheetalkamat since its merged into the master I guess it should be available in `3.7.0-dev.20191001` ? I just installed this version and still have this `Option 'declaration' cannot be specified with option 'isolatedModules'.` error.

**Comment by sheetalkamat** [comment]
@pleerock Please open a issue with steps to reproduce the issue. I don't see the issue with typescript@next on simple project

```
c:\temp\test2>node node_modules\typescript\lib\tsc.js -v
Version 3.7.0-dev.20191001

c:\temp\test2>node node_modules\typescript\lib\tsc.js  --listFiles --listEmittedFiles
TSFILE: c:/temp/test2/a.js
TSFILE: c:/temp/test2/a.d.ts
c:/temp/test2/node_modules/typescript/lib/lib.d.ts
c:/temp/test2/node_modules/typescript/lib/lib.es5.d.ts
c:/temp/test2/node_modules/typescript/lib/lib.dom.d.ts
c:/temp/test2/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
c:/temp/test2/node_modules/typescript/lib/lib.scripthost.d.ts
c:/temp/test2/a.ts

c:\temp\test2>type tsconfig.json
{
    "compilerOptions": {
        "isolatedModules": true,
        "declaration": true
    }
}
c:\temp\test2>
```

**Comment by pleerock** [comment]
@sheetalkamat you should try it in a composite project. reproduction: https://github.com/pleerock/learn-a

**Comment by sheetalkamat** [comment]
@pleerock Still no repro
```
c:\temp\learn-a>npm i

> command-join@2.0.1 postinstall c:\temp\learn-a\node_modules\command-join
> npx -p @seangenabe/tnx tnx || exit 0

npx: installed 1 in 2.048s

    Thanks for installing command-join!

    If you like this package, be sure to star its repo,
    and please consider donating:

        https://seangenabe.netlify.com/donate

npm WARN learn-a No repository field.
npm WARN learn-a No license field.

added 318 packages from 172 contributors and audited 1394 packages in 15.153s
found 0 vulnerabilities


c:\temp\learn-a>lerna bootstrap
lerna notice cli v3.13.1
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 3 packages

c:\temp\learn-a>node node_modules\typescript\lib\tsc.js -v
Version 3.7.0-dev.20191001

c:\temp\learn-a>node node_modules\typescript\lib\tsc.js -b -v packages --listFiles --listEmittedFiles
[11:31:06 AM] Projects in this build:
    * packages/pkg1/tsconfig.json
    * packages/pkg2/tsconfig.json
    * packages/pkg3/tsconfig.json
    * packages/tsconfig.json

[11:31:06 AM] Project 'packages/pkg1/tsconfig.json' is out of date because output file 'packages/pkg1/lib/foo.js' does not exist

[11:31:06 AM] Building project 'c:/temp/learn-a/packages/pkg1/tsconfig.json'...

TSFILE: c:/temp/learn-a/packages/pkg1/lib/foo.js.map
TSFILE: c:/temp/learn-a/packages/pkg1/lib/foo.js
TSFILE: c:/temp/learn-a/packages/pkg1/lib/foo.d.ts.map
TSFILE: c:/temp/learn-a/packages/pkg1/lib/foo.d.ts
TSFILE: c:/temp/learn-a/packages/pkg1/lib/index.js.map
TSFILE: c:/temp/learn-a/packages/pkg1/lib/index.js
TSFILE: c:/temp/learn-a/packages/pkg1/lib/index.d.ts.map
TSFILE: c:/temp/learn-a/packages/pkg1/lib/index.d.ts
TSFILE: c:/temp/learn-a/packages/pkg1/tsconfig.tsbuildinfo
c:/temp/learn-a/node_modules/typescript/lib/lib.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.es5.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.dom.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.scripthost.d.ts
c:/temp/learn-a/packages/pkg1/src/foo.ts
c:/temp/learn-a/packages/pkg1/src/index.ts
[11:31:08 AM] Project 'packages/pkg2/tsconfig.json' is out of date because output file 'packages/pkg2/lib/index.js' does not exist

[11:31:08 AM] Building project 'c:/temp/learn-a/packages/pkg2/tsconfig.json'...

TSFILE: c:/temp/learn-a/packages/pkg2/lib/index.js.map
TSFILE: c:/temp/learn-a/packages/pkg2/lib/index.js
TSFILE: c:/temp/learn-a/packages/pkg2/lib/index.d.ts.map
TSFILE: c:/temp/learn-a/packages/pkg2/lib/index.d.ts
TSFILE: c:/temp/learn-a/packages/pkg2/tsconfig.tsbuildinfo
c:/temp/learn-a/node_modules/typescript/lib/lib.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.es5.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.dom.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.scripthost.d.ts
c:/temp/learn-a/packages/pkg1/lib/foo.d.ts
c:/temp/learn-a/packages/pkg1/lib/index.d.ts
c:/temp/learn-a/packages/pkg2/src/index.ts
[11:31:08 AM] Project 'packages/pkg3/tsconfig.json' is out of date because output file 'packages/pkg3/lib/index.js' does not exist

[11:31:08 AM] Building project 'c:/temp/learn-a/packages/pkg3/tsconfig.json'...

TSFILE: c:/temp/learn-a/packages/pkg3/lib/index.js.map
TSFILE: c:/temp/learn-a/packages/pkg3/lib/index.js
TSFILE: c:/temp/learn-a/packages/pkg3/lib/index.d.ts.map
TSFILE: c:/temp/learn-a/packages/pkg3/lib/index.d.ts
TSFILE: c:/temp/learn-a/packages/pkg3/tsconfig.tsbuildinfo
c:/temp/learn-a/node_modules/typescript/lib/lib.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.es5.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.dom.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
c:/temp/learn-a/node_modules/typescript/lib/lib.scripthost.d.ts
c:/temp/learn-a/packages/pkg1/lib/foo.d.ts
c:/temp/learn-a/packages/pkg1/lib/index.d.ts
c:/temp/learn-a/packages/pkg2/lib/index.d.ts
c:/temp/learn-a/packages/pkg3/src/index.ts

c:\temp\learn-a>type packages\pkg3\tsconfig.json
{
  "extends": "../tsconfig.settings.json",
  "compilerOptions": {
    "outDir": "lib",
    "rootDir": "src",
    "isolatedModules": true
  },
  "references": [
    { "path": "../pkg1" },
    { "path": "../pkg2" }
  ]
}
c:\temp\learn-a>
```

**Comment by pleerock** [comment]
@sheetalkamat I apologize, my bad here. Thought I was using local version when running `tsc` instead of older global one, but I was wrong 🤦‍♂ Say no to globally installed modules 🙅‍♂ 

Everything is working on latest beta, thanks!

**Pull request merged**
