### PR TITLE
Fix #31319 : Narrow unit-unit inequality tests using comparability

### LINKED ISSUE #31319: type guard about const enum and string
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

**Code**

```ts
/**
 * Created by user on 2019/5/9.
 */

export const enum EnumTypeNode
{
	Pattern = "Pattern",
	Disjunction = "Disjunction",
}

export type NodeA = Disjunction | Pattern;

export interface NodeBase
{
	type: NodeA["type"]
}

export interface Disjunction extends NodeBase {
	type: EnumTypeNode.Disjunction
	alternatives: string[]
}

export interface Pattern extends NodeBase {
	type: EnumTypeNode.Pattern
	elements: string[]
}

let n: NodeA

if (n.type === "Disjunction")
{
	n.alternatives.slice()
}
else
{
	n.elements.slice()
	// Error: TS2339: Property 'elements' does not exist on type 'NodeA'.  Property 'elements' does not exist on type 'Disjunction'.
}

if (n.type === EnumTypeNode.Disjunction)
{
	n.alternatives.slice()
}
else
{
	n.elements.slice()
	// didn't have error
}
```

**Expected behavior:**

no error, `if (n.type === "Disjunction")` everything same as use `if (n.type === EnumTypeNode.Disjunction)`

**Actual behavior:**

> Error: TS2339: Property 'elements' does not exist on type 'NodeA'.
  Property 'elements' does not exist on type 'Disjunction'.

```ts
if (n.type === "Disjunction")
{
	n.alternatives.slice()
}
else
{
	n.elements.slice()
	// Error: TS2339: Property 'elements' does not exist on type 'NodeA'.
  Property 'elements' does not exist on type 'Disjunction'.
}
```

**Playground Link:** 

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/14210

### PR DESCRIPTION
**Pull request by jack-williams**
Fixes #31319

### CODE REVIEW

**Comment by jack-williams** [comment]
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot test this

**Comment by jack-williams** [comment]
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot test this

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot user test this
@typescript-bot test this

**Comment by weswigham** [comment]
All the tests look good post-merge, so I'm merging this~

**Pull request merged**
