### PR TITLE
Revert microsoft/TypeScript#33171

### LINKED ISSUE #35683: Uninitialized identifer causes compiler crash
**TypeScript Version:**  3.8.0-dev

**Code**

```ts
// Compile with --strict
let a: {};
a;
```

**Expected behavior:**

No crash.

**Actual behavior:**

Crash!

**Related Issues:**

Crash is caused by code added in #33171. Beyond this crash, I see several issues with that code. For example, it assumes that if the return type is a union type, then the type annotation AST node is a `UnionTypeNode`, which by no means is a given. For example, the return type node could be a reference to a type alias.

### PR DESCRIPTION
**Pull request by orta**
Reverts #33171 which should fix #35683

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@orta @RyanCavanaugh We should get this one merged for 3.8.

**Comment by orta** [comment]
Ah, my bad, I never got back to hit the merge button - just rebased, will merge on green

**Comment by ahejlsberg** [comment]
@orta Looks like the (now orphaned) error message didn't get deleted. We should fix that.

**Comment by orta** [comment]
Removed the error message - thanks https://github.com/microsoft/TypeScript/pull/36332

**Pull request merged**
