### PR TITLE
fix(52270): update optionalReplacementSpan in continuePreviousIncompleteResponse

### LINKED ISSUE #52270: optionalReplacementSpan not update when hit a incompleteCompletionsCache?
https://github.com/microsoft/TypeScript/blob/8586c995b57747bcc9abdfed901bea776644b5fb/src/services/completions.ts#L667-L671
Here when hit a cache, will directly return the cached one, but in the `continuePreviousIncompleteResponse` function, not sync the `optionalReplacementSpan`' value, so there will always return the cached `optionalReplacementSpan` value.
https://github.com/microsoft/TypeScript/blob/8586c995b57747bcc9abdfed901bea776644b5fb/src/services/completions.ts#L995

But `typescript-language-server` and `volar` all use this field to calculate  CompletionItem's `textEdit` (InsertReplaceEdit) field.
https://github.com/typescript-language-server/typescript-language-server/blob/d8b4cb698b6b74f12edb0a19e6c28b391cc0e985/src/completion.ts#L104

https://github.com/volarjs/plugins/blob/3c62a892e334806d2b76cd66d9c4670179d21398/packages/typescript/src/services/completions/basic.ts#L51-L54

So,  should this field also be updated here? or is typescript-language-server need calculated in other ways?

Here is the first time hit a `isInComplete`, the `optionalReplacementSpan`' end is `{line: 100, offset: 18}`

image

Then the following inputs hit the cache, trigger position is changed, but `optionalReplacementSpan` are not updated 
image

image

### PR DESCRIPTION
**Pull request by jadestrong**
Fixes #52270

### CODE REVIEW

**Comment by andrewbranch** [comment]
I don’t think there’s a way to write a test for this besides asserting the optionalReplacementSpan you expect in a unit test in `src/testRunner/unittests/tsserver/completionsIncomplete.ts`. The fourslash tests aren’t set up to do continuations IIRC.

**Comment by jadestrong** [comment]
image
I tried to add a regression test, here are the test results before this change

**Comment by jadestrong** [comment]
@microsoft-github-policy-service agree

**Review by andrewbranch — APPROVED** [review]
Thanks for catching this and fixing it! 🌟

**Pull request merged**
