### PR TITLE
Make tsserver.js a library

### PR DESCRIPTION
**Pull request by amcasey**
VS Code (and probably others) currently consumes both tsserver.js and
typescript.js, even though they have essentially the same content.  This
change makes it possible to use tsserver.js for both purposes, by
suppressing the server startup code (including requires) and adding a
declaration file (stripped of internals).

### CODE REVIEW

**Comment by amcasey** [comment]
I bet there's a cleverer way to skip the body of server.ts and I'd be happy to hear it.

**Comment by amcasey** [comment]
FYI @mjbvz, hopefully, this will save VS Code 8MB or so.

**Comment by amcasey** [comment]
Do I need to hook the new .d.ts file up to some sort of baseline/validation system?

**Comment by weswigham** [comment]
If we're considering this, the `tsserverlibrary` build is already this minus the startup code - perhaps we should just merge them?

**Comment by amcasey** [comment]
@weswigham What does "merge them" mean in this context?  Drop `tsserverlibrary`?

**Comment by weswigham** [comment]
`tsserverlibrary`'s build tasks already have the declaration files and API baselining set up - so copying the conditional startup code into the `tsserverlibrary` entrypoint, then renaming it to `tsserver`, I imagine.

**Comment by amcasey** [comment]
I've done my best to port the functionality of `tsserverlibrary` to `tsserver`, but they had slightly different watch functionality, so it might not be exact.

**Comment by amcasey** [comment]
Force update was just a rebase.  No manual merging required.

**Comment by amcasey** [comment]
There's a weird quirk there actually - unless we manually delete it next time we update the LKG, we'll continue to ship the old one.  (See also https://github.com/microsoft/TypeScript/pull/39330)

**Comment by weswigham** [comment]
AFAIK when we rewrote the LKG script, the only reason it doesn't automatically delete dead files was because there was some `.json` document or something which seemed dead but was also potentially consumed by VS (and may even be gone by now - or I could be thinking of `typesMap.json`, don't know), IIRC from a conversation from years ago.

**Comment by amcasey** [comment]
This would be a hack, so we're not going to pursue it.

**Pull request closed without merging**
