### PR TITLE
resolveName: remove useless case

### PR DESCRIPTION
**Pull request by ajafff**
PropertySignature cannot occur in a class.
The condition inside the clause required the parent to be a class, so it was never true.

This removes the case clause and the part of the condition that is now useless.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this because I'm paranoid

**Comment by ajafff** [comment]
I cannot reproduce that error locally. It's strange that this change caused new errors at all. There must be something else going wrong.
Are you sure the baselines were up-to-date before running RWC tests on this PR?
Could it help if I merge master into this PR?

Is it possible to view the code that has new errors or are these private projects?

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
We'll try again. If the error's still there I'll try to get a usable repro - the code in those suites is mostly not shareable due to not being public.

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this again?

**Comment by RyanCavanaugh** [comment]
Pushed up a newer copy of master to your fork, which it turns out is required. Rerunning tests

@typescript-bot test this

**Pull request merged**
