### PR TITLE
Add a jump table for unspecified hint emit to the printer

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
There's another switch below, but I just want to experiment with this first.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
That run seems really abnormal...

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Pull request closed without merging**
