### PR TITLE
do not error on 'super' property access in ES6

### LINKED ISSUE #338: Allow to call getter/setter logic When subclassing
http://typescript.codeplex.com/workitem/645

At the moment it's not possible to call super getter/setter when overriding properties:

``` typescript
class A {
    private _property: string;
    get property() { return this._property; }
    set property(value: string) { this._property = value }
}

class B extends A {
    set property(value: string) {
        super.property = value + " addition";
    }
}
```

### PR DESCRIPTION
**Pull request by vladima**
fixes #338. #4465

### CODE REVIEW

**Comment by mhegazy** [comment]
so how dose this work with non-accessor properties?

**Comment by vladima** [comment]
@mhegazy ES6 natively support it so there is no error. However results might be quite unexpected. Consider this example:
```javascript
'use strict'

class A {}
Object.defineProperty(A.prototype, "x", { value: 1 });
class A1 extends A {
    method() { return super.x; }
}

console.log(new A1().x);        // 1
console.log(new A1().method()); // 1

class B {
    constructor() {
        this.x = 2;
    }
}

class B1 extends B {
    method() { return super.x; }
}

console.log(new B1().x);        // 2
console.log(new B1().method()); // undefined
```
Reason is: `super` call inside `new B1()`  will set `x` on `this` meaning that it will be own property for `B1` but not for `B` so attempt to read it in `method` will return `undefined`.

**Comment by mhegazy** [comment]
yup. if you put it on the prototype it is going to work, except that all instances share the same variable, which is not expected, if you do not, super.x does not really point to any thing, as super and this are really the same object. that is the reason we did not allow it in the past. the question is should we do it now? we should talk about this in the design meeting.

**Comment by vladima** [comment]
AFAIR main reason why we did not do this downlevel was: super access to data and accessor properties is different so we'll need to emit helper  code to avoid runtime errors. For ES6 helpers are not necessary and the question is mostly: do we want to block potentially legitimate user scenarios just because we don't have way to know if super property access will use data or accesssor property.

**Comment by vladima** [comment]
pinging @RyanCavanaugh, can you pls confirm that this PR is approved on design meeting before I check it in?

**Comment by RyanCavanaugh** [comment]
:+1:

**Pull request merged**
