### PR TITLE
Add support for abstract constructor types

### LINKED ISSUE #26829: Extracting the instance type from the ctor value that works for abstract classes
## Search Terms

abstract class constructor type

## Suggestion

Currently, I think there is no way to express the type of constructor functions for abstract classes. On one hand that is correct because 'new' cannot be called on them. However, sometimes there is a need to tie an instance of the abstract class with the constructor function for type-checking.

## Use Cases

DI helper functions in angular and other frameworks.

## Examples

```typescript
// Angular calls this Type<T>
// https://github.com/angular/angular/blob/master/packages/core/src/type.ts#L25
interface Factory<T> extends Function {
  new (...args: any[]): T;
}

abstract class AC {
  abstract x: number;
}

class C extends AC {
  x = 0;
}

// a DI-like system, that returns instance of C for get(C) and get(AC).
// The mechanism is left unspecified.
declare function get<T>(token: Factory<T>): T;

let x1 = get(C);
let x2 = get(AC);  // error, underlying issue is that AC is not assignable to Factory<AC>
```

Basically, this is asking for a mechanism to go from a value `C`, where `C` is a symbol for a class (abstract or not), to the type `C`.

## Checklist

My suggestion meets these guidelines:
* [ ] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

### LINKED ISSUE #35576: No way to get generic type of an abstract class inside a factory function
**TypeScript Version:**  3.7.3

**Search Terms:** abstract class, generic, infer

**Code**

```ts
type InstanceViaNew<T> = T extends { new (...args: never[]): infer R } ? R : never
type InstanceViaProto<T> = T extends { prototype: infer R } ? R : never

function classFactory1<T>() {
  class CS {
    x!: T
  }

  return CS
}

const CSS = classFactory1<string>()
type CS1 = InstanceViaNew<typeof CSS>["x"] // ok, string
type CS2 = InstanceViaProto<typeof CSS>["x"] // not ok, any :(

function classFactory2<T>() {
  abstract class ACS {
    x!: T
  }

  return ACS
}

const ACS = classFactory2<string>()

type AC1 = InstanceViaNew<typeof ACS>["x"] // not ok, never (because abstract classes have no new) :(
type AC2 = InstanceViaProto<typeof ACS>["x"] // not ok, any :(
```

**Expected behavior:**

There should be a way to make abstract classes keep the generic information and use it.

**Actual behavior:**

There's no way to make abstract classes keep the generic information and use it (unless they are type-casted to non abstract classes by adding to them a fake constructor).

**Related Issues:** https://github.com/microsoft/TypeScript/issues/26829

### PR DESCRIPTION
**Pull request by rbuckton**
This adds support for the `abstract` keyword on constructor types and construct signatures, allowing you to indicate the signature is `abstract`. This also updates the definitions for `InstanceType` and `ConstructorParameters` to use the `abstract` modifier:

## Syntax
```ts
// constructor types
type T1 = abstract new () => any;
```

## Semantics
- Non-abstract constructor types are assignable to abstract constructor types if they would otherwise be assignable.
- Abstract constructor types are not assignable to non-abstract constructor types.
- Values with types containing abstract constructor types cannot be instantiated via `new` (this previously only applied to abstract classes)

## Examples - Basic Usage
```ts
type Constructor<T> = new (...args: any[]) => T;
type AbstractConstructor<T> = abstract new (...args: any[]) => T;
interface Obj<T> {
  x: T;
}

declare let c: Constructor<Obj<number>>;
declare let a: AbstractConstructor<Obj<number>>;

// assignability
a = c; // ok, a non-abstract constructor type can be assigned to an abstract constructor type
c = a; // error, an abstract constructor type cannot be assigned to a non-abstract constructor type

// new expression
new c(); // ok
new a(); // error, cannot create an instance of an abstract class

// inference and conditional types
type T1 = InstanceType<typeof c>["x"]; // number
type T2 = InstanceType<typeof a>["x"]; // number
```

## Examples - Mixins
```ts
interface Mixin { ... }
abstract class Base { ... }

declare function Mixin1<TBase extends new (...args: any[]) => {}>(base: TBase):
    TBase & (new (...args: any[]) => Mixin);

class Sub1 extends Mixin1(Base) { }
//                        ^^^^ TS2345: Argument of type 'typeof Base' is not assignable 
//                                     to parameter of type 'new (...args: any[]) => {}'.
//                                     Cannot assign an abstract constructor type to a 
//                                     non-abstract constructor type.

declare function Mixin2<TBase extends abstract new (...args: any[]) => {}>(base: TBase):
    TBase & (new (...args: any[]) => Mixin);

class Sub2 extends Mixin2(Base) { } // Ok
```

Fixes #26829
Fixes #35576

### CODE REVIEW

**Comment by rbuckton** [comment]
CC: @weswigham, @RyanCavanaugh, @DanielRosenwasser (as suggested reviewers is not working).

**Comment by ajafff** [comment]
Does this also support mixins with abstract classes? Could you add a test for that, too?

**Comment by rbuckton** [comment]
I'm going to revert support for `abstract` construct signatures in favor of investigating `class` type expressions:

```ts
// [source.ts]
function MyMixin<TBaseClass extends abstract new (...args: any[]) => any>(
  baseClass: TBaseClass
) {
  abstract class MyMixinClass extends baseClass {
    abstract abstractMethod(): void;
  }
  return MyMixinClass;
}

// [output.d.ts]
declare function MyMixin<TBaseClass extends abstract new (...args: any[]) => any>(
  baseClass: TBaseClass
): abstract class extends TBaseClass {
  abstract abstractMethod(): void;
};
```

**Comment by rbuckton** [comment]
Build failures seem to be due to the fact that eslint isn't handling the construct signatures having modifiers in `lib/es5.d.ts` so I'm reverting that part for now.

**Comment by trusktr** [comment]
> ```ts
> declare function MyMixin<TBaseClass extends abstract new (...args: any[]) => any>(baseClass: TBaseClass)
> ```

If the constraint for `TBaseClass` is an abstract constructor, can we still base a non-abstract class for `baseClass`?

It won't be helpful if we're stuck with either abstract or not-abstract.

I think what people _really_ want is that if they pass in an abstract class, then the mixin result is an abstract class (unless the mixin class implements the methods/properties), or if they pass a non-abstract class, then the mixin result is not abstract.

Otherwise the usability of mixins would be inflexible.

The following code has some type information omitted (like plain JS) so that I can clearly show the intention:

```ts
abstract class Foo {
  abstract fooMethod(): void
}

function CoolMixin(Base) {
  return class Cool extends Base {
    coolMethod() {}
  }
}

class MyClass extends Foo {
  // Required to implement the abstract fooMethod here.
  // ...
}

class MyOtherClass extends CoolMixin(Foo) {
  // Should also be required to implement the abstract fooMethod here.
  // ...
}
```

_That's_ what we need. Otherwise Mixins will continue to be inflexible and unusable compared to plain JS.

As a workaround, we could do the following but it is less ideal:

```ts
abstract class Foo {
  abstract fooMethod(): void
}

function CoolMixin(Base) {
  return class Cool extends Base {
    coolMethod() {}
  }
}

class MyClass extends Foo {
  // Required to implement the abstract fooMethod here.
  // ...
}

class _MyOtherClass extends Foo {
  // Required to implement the abstract fooMethod here.
}

class MyOtherClass extends CoolMixin(_MyOtherClass) {
  // ...
}
```

And if the mixin returns an abstract class, it should inherit abstractedness. So,


```ts
abstract class Foo {
  abstract fooMethod(): void
}

function OtherMixin(Base) {
  return abstract class Other extends Base {
    otherMethod() {}
  }
}

class MyClass extends Foo {
  // Required to implement fooMethod here.
  // ...
}

class MyOtherClass extends OtherMixin(Foo) {
  // Required to implement fooMethod and otherMethod here.
  // ...
}

class Bar {
  barMethod() {...}
}

// the previous OtherMixin application accepted an abstract class, and now this application accepts a non-abstract class:
class MyNextClass extends OtherMixin(Bar) {
  // Required to implement otherMethod here, and the barMethod is inherited.
  // ...
}
```

Note that last example in particular accepts both abstract and non-abstract base classes (I didn't show an example of `CoolMixin` accepting a non-abstract class but that should work too). 

I believe that's what we should aim for in TypeScript, otherwise we're not effectively modeling plain JS in a useful way.

**Comment by rbuckton** [comment]
@typescript-bot pack this

**Comment by rbuckton** [comment]
@trusktr: A `new () => T` type is assignable to an `abstract new () => T` type. A mixin definition that uses something like `<TBase extends abstract new (...args: any[]) => {}>(base: TBase) { ... }` will work for both abstract and non-abstract superclasses:

```ts
function Mixin<TBase extends abstract new (...args: any[]) => {}>(base: TBase) {
    class C extends base {
    }
    return C;
}

abstract class AbstractBase {
    abstract m(): number;
}

class ConcreteBase {
    m(): number { return 1;}
}

// error: C must implement abstract method `m`
class C extends Mixin(AbstractBase) {
}

// no error
class D extends Mixin(ConcreteBase) {
}
```

**Comment by rbuckton** [comment]
Although it should probably be an error for `class M extends base`, since `M` should also be marked `abstract`.

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by rbuckton** [comment]
@DanielRosenwasser: @andrewbranch suggested I add a unique error message for this case in checker. The best I've come up with is something like this:

```
Expected {0} arguments, but got {1}. Did you forget to add a 'void' type argument to your Promise?
```

Not sure I like the wording though. Any suggestions on a description?

**Comment by rbuckton** [comment]
Since this came up in todays design meeting, I'd like to explain my rationale for requiring the mixin class whose base type is a _generic `abstract` constructor type_:

> The reason I require `abstract` on the mixin class is to preserve the definition of abstract vs. concrete in TypeScript:
> 
> - If your class is declared `abstract`, you cannot create it via `new`.
> - You cannot declare a member of a class as `abstract` unless the class itself is marked `abstract`.
> - If you derive from a class marked `abstract`, the derived class must either also be `abstract` or provide an implementation of _all_ of its `abstract` members to be considered "concrete".
> 
> If you declare a mixin class that extends a _generic `abstract` constructor type_, you cannot know _all_ of its `abstract` members, as that is an infinite domain. Therefore, per the above definition of `abstract`, your mixin class must _also_ be declared `abstract`, otherwise we are inconsistent.
> 
> This does _not_ mean that all mixin classes suddenly have to be marked `abstract`, just ones that inherit from a generic `abstract` constructor type. For a constructor type to be `abstract` requires an intentional change by the developer, so it will not break existing code.
> 
> I believe it would be a mistake to allow you to elide `abstract` on a mixin class, unless we were to decide to allow you to elide `abstract` on any other class and just infer its "abstractness" from the fact the ckass has unimplemented `abstract` members. I would be fine with that direction as well, but in either case what I'm arguing for is consistency.

**Comment by rbuckton** [comment]
One additional change we may want to consider is whether we should allow interface members to be declared `abstract`, as you cannot easily define a mixin that produces an abstract class with a member that must be implemented by subclasses:

```ts
export interface Mixin {
  mixinMethod(): void;
}

export function Mixin<TBase extends new (...args: any[]) => any>(baseClass: TBase): 
  TBase & (abstract new (...args: any[]) => Mixin) {

  // NOTE: `baseClass` *is not* abstract
  // NOTE: `mixinClass` *is* abstract
  abstract class MixinClass extends baseClass implements Mixin {
    abstract mixinMethod(): void;
  }
  return MixinClass;
}
```

In the above listing, the definition of `MixinClass` is *technically* correct, as an instance of `MixinClass` would be assignable to `Mixin`, however you cannot define the "abstractness" of `mixinMethod` using an interface. You have to do something else instead:

```ts
// not exported since it doesn't actually exist as a value
declare abstract class AbstractMixin {
  abstract mixinMethod(): void;
}

export type Mixin = AbstractMixin;

export function Mixin<TBase extends new (...args: any[]) => any>(baseClass: TBase): 
  TBase & (abstract new (...args: any[]) => Mixin) {

  // NOTE: `baseClass` *is not* abstract
  // NOTE: `mixinClass` *is* abstract
  abstract class MixinClass extends baseClass implements Mixin {
    abstract mixinMethod(): void;
  }
  return MixinClass;
}
```

In this new listing, we use an `abstract class` definition, but only export a type alias pointing to its instance side. In this way, the "abstractness" of `mixinMethod` is preserved. However, this only works in modules. Global code has no easy way to hide the declared `class`, above.

It might make sense to allow interface members to be declared `abstract`. Technically speaking, an interface member is _already_ `abstract`, in that a class that implements the interface must implement the interface's members to be considered assignable to the interface (though there are some subtle differences compared to `abstract` members of a class). However, there is no way to signal that a member is _intentionally_ `abstract` like we can for a class declaration:

```ts
interface Mixin {
  abstract mixinMethod(): void; // intentionally abstract
}
```

However, that level of expressivity may need to wait on the introduction of a `class` type (see the discussion up-thread), which may follow in a later PR:

```ts
// NOTE: requires changing `InstanceType` to use `abstract`:
// type InstanceType<T extends abstract new (...args: any) => any> = 
//     T extends abstract new (...args: any) => infer R ? R : any;

type Mixin = InstanceType<abstract class {
  abstract mixinMethod(): void;
}>;

// or, alternatively:

type MixinClass = abstract class {
  constructor(...args: any[]);
  abstract mixinMethod(): void;
};
function Mixin<TBase extends new (...args: any[]) => any>(baseClass: TBase): TBase & MixinClass {
  ...
}
```

**Comment by rbuckton** [comment]
@weswigham, @ahejlsberg I still need reviewers for this.

**Comment by DanielRosenwasser** [comment]
I think the one thing that I'm still a little bit surprised about is that there's no way to rewrite the following example

```ts
abstract class Foo {
  abstract fooMethod(): void
}

function extendFoo(FooCtor: abstract new () => Foo) {
  // Error! Must implement 'fooMethod'
  return class extends FooCtor {
  }
}
```

in such a way that `Foo` is declared as any other object type like an interface.

The first reason I think this is weird is because `abstract` doesn't get funneled around as any other modifier, and so this gets a little funky as you try to do algebra over the properties.

```ts
abstract class Foo {
  abstract fooMethod(): void
}

// Homomorphic mapped type over `Foo`
type CopyFoo = {
    [K in keyof Foo]: Foo[K]
}

function extendFoo(FooCtor: abstract new () => CopyFoo) {
  // No error now!
  return class extends FooCtor {
  }
}
```

The second is that in order to model this sort of pattern, you always have to declare a class, even if you won't necessarily be extending from that class (and even if nobody is going to be extending from that class). That on its own feels kind of strange in our mostly-structural type system.

But I don't really know the right way to reconcile all of this - would "fixing" these issues mean that interfaces would have to allow `abstract` members? Would interfaces themselves need to be declared `abstract`? And how would this work with class/interface merging?

**Comment by rbuckton** [comment]
The issue is that we don't (yet) have a way to represent this type in any other way. #41587 will eventually add syntax that would permit this in type-space:

```ts

type TFoo = typeof abstract class {
  constructor();
  abstract fooMethod(): void;
};

function extendFoo(FooCtor: TFoo) { ... }
```

However, `typeof class` doesn't solve the issue that this is intended to solve. With `typeof class`, you still cannot infer the instance type, so there's no version of `InstanceType<T>` that could use `typeof class` on its own. However, with abstract constructor types, we can eventually rewrite `InstanceType<T>` as this:

```ts
type InstanceType<T extends abstract new (...args: any) => any> = T extends abstract new (...args: any) => infer R ? R : any;
```

With a new `InstanceType`, we *can* have a type definition that preserves `abstract` without introducing a class in the value-space:

```ts
type TFooInst = InstanceType<typeof abstract class {
  abstract fooMethod(): void;
}>;
```

In the end we will need *both* abstract constructor types *and* `typeof class`, but one is not dependent on the other. The main reason to ship abstract constructor types a version ahead of `typeof class` has to do with our dependency on typescript-eslint. Since typescript-eslint won't understand `abstract new` until it ships in a stable release, we need `abstract new` to ship one version prior to changing `InstanceType` to avoid lint errors in our own codebase. That way, by the time `typeof class` lands, we'll have a version of `InstanceType` that can be used in the way mentioned above.

Whether or not we eventually do something else for `abstract` in regards to interfaces or our type-algebra may be related to this feature, but is essentially out of scope as any decisions we make there are unlikely to impact the behavior of this feature. The only real cross-cutting concern I see would be that we might eventually *loosen* the restriction that classes extending from `abstract new` base types must themselves be declared abstract (instead basing it off of whatever new rules we come up with), and that wouldn't be a breaking change.

**Comment by rbuckton** [comment]
> I think the one thing that I'm still a little bit surprised about is that there's no way to rewrite the following example
> 
> ```ts
> abstract class Foo {
>   abstract fooMethod(): void
> }
> 
> function extendFoo(FooCtor: abstract new () => Foo) {
>   // Error! Must implement 'fooMethod'
>   return class extends FooCtor {
>   }
> }
> ```
> 
> in such a way that `Foo` is declared as any other object type like an interface.
> 

Actually, the example above isn't the problem, as `FooCtor` isn't *generic*, so you *can* return a non-abstract class:
```ts
function extendFoo(FooCtor: abstract new () => Foo) {
  // No error
  return class extends FooCtor {
    fooMethod(): void {} // implements it just fine.
  }
}
```

While this isn't necessarily sound, it aligns with other inconsistencies in the language, in that we assume `Foo` is the only instance type we'll create (even if you could pass an assignment compatible definition with *more* abstract methods).  The important bit we discussed in the design meeting in November was in regards to a *generic* abstract constructor type. When an abstract constructor type comes from the constraint of a generic, we cannot know *all* of the possible permutations of that generic, therefore we *must* ensure the result is still marked `abstract`. That flows through how we handle mixins in the language, such that abstract methods in the base must eventually be implemented:

```ts
interface Foo {
  normalMethod(): void;
}
declare function FooMixin<Ctor extends abstract new(...args: any[]) => any>(base: Ctor): Ctor & (abstract new (...args: any[]) => Foo);

class Concrete {}
class SubConcrete extends MixinFoo(Concrete) {} // ok

abstract class Abstract {
  abstract fooMethod(): void;
}
class SubConcreteAbstract extends FooMixin(Abstract) {
  // I must implement 'fooMethod' because it's marked 'abstract' in the base class.
  fooMethod(): void {}
}
```

**Comment by rbuckton** [comment]
> [...] Would interfaces themselves need to be declared `abstract`? [...]

No. We declare a `class` as `abstract` because it affects the *constructor* side. *If* we had `abstract` methods on interfaces, you might say the following are essentially the same:

```ts
// as a class
abstract class Foo {
  abstract fooMethod(): void;
}

// as an interface/constructor
interface Foo {
  abstract fooMethod(): void;
}
let Foo: abstract new () => Foo;
```

I would imagine that if we *did* introduce `abstract` in an interface method, we'd probably want to make `new () => Foo` an error since you cannot create an instance of an object with abstract methods, in the same way that `class Foo { abstract fooMethod(): void; }` is an error today.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by rbuckton** [comment]
I'll be pushing up a minor change to declaration emit/quick info shortly to handle inferred return types that result in an anonymous type with abstract construct signatures.

For reference, in this case:
```ts
// @target: esnext
// @declaration: true

interface Mixin {
    mixinMethod(): void;
}

function Mixin<TBase extends abstract new (...args: any[]) => any>(baseClass: TBase) {
    // must be `abstract` because we cannot know *all* of the possible abstract members that need to be
    // implemented for this to be concrete.
    abstract class MixinClass extends baseClass implements Mixin {
        mixinMethod(): void {}
        static staticMixinMethod(): void {}
    }
    return MixinClass;
}
```

We currently emit this:
```ts
declare function Mixin<TBase extends abstract new (...args: any[]) => any>(baseClass: TBase): {
    new (...args: any[]): { // does not preserve `abstract`
      [x: string]: any;
      mixinMethod(): void;
    };
    staticMixinMethod(): void;
}) & TBase;
```
When we need to emit this instead:
```ts
declare function Mixin<TBase extends abstract new (...args: any[]) => any>(baseClass: TBase): ((abstract new (...args: any[]) => {
    [x: string]: any;
    mixinMethod(): void;
}) & {
    staticMixinMethod(): void;
}) & TBase;
```

**Comment by rbuckton** [comment]
@RyanCavanaugh can you take one more look with the update for declaration emit?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by ITenthusiasm** [comment]
Sorry to ask, but has this already been released? `abstract` doesn't seem to be recognized keyword in my repository.

**Comment by MicahZoltu** [comment]
> This also updates the definitions for InstanceType and ConstructorParameters to use the abstract modifier

This doesn't appear to actually be present?  There is no mention of `ConstructorParameters` in the PR diff, and both `InstanceType` and `ConstructorParameters` don't support abstract classes in the latest version of TS.  You *can* build a custom `ConstructorParameters`, suggesting that this has been merged.

**Comment by rbuckton** [comment]
> > This also updates the definitions for InstanceType and ConstructorParameters to use the abstract modifier
> 
> This doesn't appear to actually be present? There is no mention of `ConstructorParameters` in the PR diff, and both `InstanceType` and `ConstructorParameters` don't support abstract classes in the latest version of TS. You _can_ build a custom `ConstructorParameters`, suggesting that this has been released.

They couldn't be added at the same time due to a lag between TS releases and the TypeScript ESLint plugin. They will be added by #43380.

**Comment by jcalz** [comment]
I was a little surprised that you can't write `{ abstract new(): Foo }` as a synonym for `abstract new() => Foo`.  Not sure if that's documented anywhere, but I figured I'd mention it.

**Comment by rbuckton** [comment]
It's hinted at a bit here: https://github.com/microsoft/TypeScript/pull/36392#issuecomment-725726390, but was something we discussed in a Design Meeting. Adding `abstract` signatures to an interface (and possibly `abstract` members as well) was something we didn't want to touch on yet with this feature, as it introduces significantly more complexity. The intent was for the [`typeof class`](https://github.com/microsoft/TypeScript/pull/41587) type to handle this, eventually.

**Comment by ntucker** [comment]
The declaration emit seems to not enforce abstract members...

from

```ts
type Constructor = abstract new (...args: any[]) => {};

function mixin<TBase extends Constructor>(Base: TBase) {
  abstract class MyClass extends Base {
    abstract abs(): void;
  }
  return MyClass;
}
```

I get 

```ts
type Constructor = abstract new (...args: any[]) => {};
declare function mixin<TBase extends Constructor>(Base: TBase): (abstract new (...args: any[]) => {
    abs(): void;
}) & TBase;
```

But if I use that as an ambient declaration (imagine publishing a package based on this). Then an implementation lacking abs doesn't error:

```ts
class Broken extends mixin(class {}) {
  field = 5;
}
```

**Comment by lorenzodallavecchia** [comment]
I have noticed that abstract constructor types do not accept a class with a `protected` constructor.
See this [playground](https://www.typescriptlang.org/play?ts=5.0.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVPwAow8BnDGZTHGALnigCNyYpN5UQB3QgOn9gBzUvSioAngG0AugEp4AXgB88HIwBW4DLPoA3HFmABuAFAmmLNhniQopUvACCARngBveJ6-efvv-ABfc2YKKxtoeycAJnd4AAcYHAwtEGAbMgoqDBp4Qnk3AMCzRFRCF1lTErKoivgAejr4DAALLAcQGESYUgAaeEZka1JmnGQINNQkkyA).

> Argument of type 'typeof A2' is not assignable to parameter of type 'abstract new (...args: any[]) => object'.
  Cannot assign a 'protected' constructor type to a 'public' constructor type.(2345)

What is the reason for this behavior?
Abstract constructors cannot be called anyway, so their visibility should not matter IMO.

**Pull request merged**
