### PR TITLE
Separate intersection type resolution process for publicly and non-publicly accessible mixin construct signatures

### LINKED ISSUE #42264: Mixin classes with private/protected constructors are subclassable
# Bug Report

### 🔎 Search Terms

mixin, private constructor

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Classes.
Versions tried:
- 3.7.4
- 4.1.3
- Nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-dev.20210108#code/GYVwdgxgLglg9mABABQE4FMBu6xQMogBGEANgIYDOFMYA5gLIwAeNAPACoBCl6i6TUHABMKiMOgDuACgB0csqloUAXIjJgAngG0AugEpEAXgB8azcancK6VVx4GA3gChEiDFBCokpSqIByCATE5FRkhCS8-IJgIohWvM6urgAOqDCYZIKIEAgUUKgg0HCosvKKKmba+oiJSa4UIMnoJXoA3C5JAL4d3d1OPlRxPDUdOWB5BUUtNb1O-SH+gUQDFGER7AAWqHAgtBsAogI41Ah8RzGi8SMpaRlZYxOFUMVSjh31jc2v7a6z-blQRABMBBFZrdCbba7DaMFhIQwoDDYXCghY0BjMGiWeztJziCRApbBXzgyE7PaHaInMDfPGSQkg5YLUlbckwzE0tpAA)

### 💻 Code

```ts
function PreventSubclassingMixin<TBase extends new(...args: any[]) => any>(Base: TBase) {
  return class NonSubclassable extends Base {
    private constructor(...args: any[]) {
      super();
    }
  }
}

class Base {
  constructor() {}
}

class NonSubclassableThroughExtension extends Base {
  private constructor() {
    super();
  }
}

const NonSubclassableThroughMixin = PreventSubclassingMixin(Base);

new NonSubclassableThroughExtension(); // Constructor of class 'NonSubclassableThroughExtension' is private and only accessible within the class declaration.(2673)
new NonSubclassableThroughMixin();
```

### 🙁 Actual behavior

`NonSubclassableThroughExtension` correctly throw an error — I've extended a superclass `Base`, which has a publicly accessible constructor, and provided a private constructor in the derived class. I can't access the derived class' constructor anymore:

```ts
new NonSubclassableThroughExtension(); // Constructor of class 'NonSubclassableThroughExtension' is private and only accessible within the class declaration.(2673)
```

The `PreventSubclassingMixin` supposedly works the same — it creates a class expression that extends the `Base` class with a public constructor and defines a private constructor, and returns it. The returned derived mixin class is supposedly identical to the example above. However, if I apply the mixin to the `Base`: `const NonSubclassableThroughMixin = PreventSubclassingMixin(Base)`, and try to initialize it, Typescript won't throw any error.

### 🙂 Expected behavior

`new NonSubclassableThroughMixin()` should throw a `Constructor of class 'NonSubclassableThroughExtension' is private and only accessible within the class declaration.(2673)`.

### PR DESCRIPTION
**Pull request by rafasofizada**
Fixes #42264

In `checker.ts > resolveIntersectionTypeMembers()`, instead of discarding and merging all mixin constructor signatures, we do so only for mixins with publicly accessible constructor signatures. Private or protected constructor signatures of mixins are not discarded/merged, and instead are added to the intersection type's constructor signatures.

**Details on bug cause are provided in [my comment to the bug report](https://github.com/microsoft/TypeScript/issues/42264#issuecomment-913928347).**

### CODE REVIEW

**Review by weswigham — APPROVED** [review]
I think the implementation looks like an improvement - I feel like a lot of this implementation is relying on us only considering mixins actually mixins if they only have exactly one construct signature - but I guess for now that's a safe enough assumption to make, seeing as we make it elsewhere. Maybe @ahejlsberg would have a more nuanced opinion about how different constructor visibilities should interact, but combining only all the public ones (while keeping the private signatures in for relationships' sake) seems fine to me. The inheritance of `protected` construct signatures from mixins might be a little odd in practice, though (I think you'd be able to use a `protected` mixin constructor signature so long as you're constructing a subtype instance within a subtype of the class you're mixing, which might be weird and way too loose).

@andrewbranch up to you if this should hit the beta/rc pipeline or be held longer/discussed at some point~

**Comment by andrewbranch** [comment]
Looks like a breaking change, so we’ll at least hold off until 4.6, which should give us some time to talk about it some and see if anyone else has feedback.

**Comment by sandersn** [comment]
@weswigham your review on this is very old, but it was positive. Should we take this change after all?

**Comment by sandersn** [comment]
This PR is now two years old. @weswigham @andrewbranch do you think this is worth taking? I'm not sure if it needs more discussion or if we just forgot about it.

**Comment by sandersn** [comment]
I'm going to close this for now since it's quite stale.

**Pull request closed without merging**
