### PR TITLE
Unify logic in typeof narrowing

### LINKED ISSUE #33180: Inconsistency with boolean negation as `void` type guards with `--strictNullChecks`
**TypeScript Version:**  `typescript@3.7.0-dev.20190831`

**Search Terms:** void guard strictNullChecks boolean negation refinement

**Code**

```ts
// Toggle strictNullChecks off and see the type error appear
// on line 7, while 2nd fn never errors and 3rd always errors
const getMaybeStringLen = (maybeString: string | void) => {
  if (maybeString === null || maybeString === undefined) {
    return undefined;
  }
  return maybeString.length;
};

const getMaybeStringLenBoolNegation = (maybeString: string | void) => {
  if (!maybeString) {
    return undefined;
  }
  return maybeString.length;
};

const getMaybeStringLenBoolCoercionNegation = (maybeString: string | void) => {
  if (!Boolean(maybeString)) {
    return undefined;
  }
  return maybeString.length;
};
```

**Expected behavior:**
- `strictNullChecks: false` behaves less strictly than `strictNullChecks: true`. Admittedly a loose criterion, but it seems like the stricter check fails with `strictNullChecks: false` and passes with `strictNullChecks: true`, while the type coercive check passes in both cases.

My confusion stems from the fact that `!` is a valid type guard for `void` for both compiler flags, while checking against `null` and `undefined` is valid for `strictNullChecks: true` only. 

As a bonus, while `!` is always valid, `!Boolean(x)` is never valid.

**Actual behavior:**
- `getMaybeStringLen`...
  - ...typechecks with `strictNullChecks: true`
  - ...**does NOT** typecheck with `strictNullChecks: false`
- `getMaybeStringLenBoolNegation`...
  - ...typechecks with `strictNullChecks: true`
  - ...typechecks with `strictNullChecks: false`
- `getMaybeStringLenBoolCoercionNegation`...
  - ...**does NOT** typecheck with `strictNullChecks: true`
  - ...**does NOT** typecheck with `strictNullChecks: false`

**Playground Link:** http://www.typescriptlang.org/play/#code/PTAEBUHsHNoGwKagM4BcBOBLAxqgcgK5xwDCAFgtgNbKiQBm9oAhgHYAmKCSqFoqATwAOSBOnSR0LISOboAUCDqtQcTKyQB2ADSgA7mUyJQAJg6h6KjQDcxoMRPS02nAMzpOzOHuYDaDyWR5bEhWNFBoBFQAWV8AIwQAZQx1aAAZBBUAXlAACgBbeKSU1mgALhQS6FAAH1BrSEx2AEpQLIA+UABveVBQTCYCouSsUrasnNYiOFq6woEEkdTxnIIOBHp1BBbu3r7QdCiCdBU19g2t9gBuPYBfPcPUY5V5xaqAOkRS3hvbm+DQuFIjFhlUMqwAEKQSBwPAIaDMVCYUJtPKvYqjcqVTG1eqNHYdXZ9AZ5ACE6KWpVaPX2ByOJ1AZwuGmudwe9JeoMxn0y0B+8j+8gBYVQESisQWGNS4KhMJIkDE2GRrDhCKRKJyQ0llKxaBxdQaTVahJp-UGpNliDYWremOa1L2fUez0Z602LJufXuTo5oApHy+fLIvxuQA

**Related Issues:** #1806, #8322, #10564

### PR DESCRIPTION
**Pull request by jack-williams**
In looking to resolve #33180 I want something like `if (typeof x === "boolean") { ... }` to narrow `x` to `boolean` when `x` is of type `boolean | void`, such behaviour is consistent with empty intersection reduction.

Doing so requires changing both `if` and `switch` logic. It also feels more robust moving forward to unify the logic in `if (typeof x === "boolean") { ... }` and `switch (typeof x) { ... }`, so I'm looking to merge this first and then fix the `void` case---hoping to avoid conflating any regressions.

### CODE REVIEW

**Comment by jack-williams** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

because bots don't get weekends.

**Comment by jack-williams** [comment]
User tests look like noise, I think.

**Comment by fatcerberus** [comment]
> In looking to resolve #33180 I want something like if (typeof x === "boolean") { ... } to narrow x to boolean when x is of type boolean | void

While this narrowing does match the reality at runtime, I'm not sure it's sound *semantically*, given that `void` represents random garbage to be discarded--the dual of `any`, as discussed in #33180 and also mentioned [here](https://github.com/microsoft/TypeScript/issues/33420#issuecomment-531426072).

IMO, any construct that allows a value of type `void` to be observed is inherently unsound and the type system should aim to prevent it whenever possible.  By this I mean:

```ts
declare let callback: () => void;
declare let knownToBeBool;

let x = Math.random() > 0.5 ? callback() : knownToBeBool;
if (typeof x === 'boolean') {
    // 'x' should NOT be narrowed here because it could leak the return value of 'callback'
    // (which we've already promised to ignore by declaring it 'void')
    x;
}
```

**Comment by jack-williams** [comment]
The `void` type is not dual to `any`, if it were then `void` would not be assignable to itself. The closest thing that resembles the dual of `any` is the `invalid` type that has been proposed.

**Comment by fatcerberus** [comment]
Quibbles about theoretical details aside (suffice to say there's no *practical* reason to disallow `void = void` assignments, duality notwithstanding), the point I made above stands: if a value possibly originates from the return value of a function type returning `void`, the type system should not allow that value to be observed (if it can be avoided) because the type promises that the value will be thrown away.

**Comment by fatcerberus** [comment]
In other words:
```ts
function doSomething(callback: () => void);
doSomethingLater(someRandoFunction);
```
Since `someRandoFunction` is allowed to return anything at all, I view `() => void` as an implicit promise that regardless of what it returns, it won't affect the outcome of `doSomething`.

**Comment by fatcerberus** [comment]
> The void type is not dual to any, if it were then void would not be assignable to itself.

Not related to this issue, but this just got me thinking, how much real-world code would break if this were actually the case... because if that change were made, `void` could probably work as `invalid` without adding a new keyword.

Function types *returning* `void` would still have to be assignable to each other though, so it might get tricky.

**Comment by AnyhowStep** [comment]
The `invalid` proposal needs custom error messages, though =P

**Comment by jack-williams** [comment]
If the proposed behaviour does not introduce significant real-world breaks I think it could be justified, though I don't know the landscape well enough. The behaviour feels slightly draconian though, given that even unconstrained type parameters can be inspected and narrowed.

The priority should be addressing the unsound behaviour that narrows `void` as if it were only inhabited by `null` or `undefined`---this is clearly wrong.

In modern TypeScript with `undefined` and `unknown` I'm not sure I really see the point of `void` anymore, but that is for a different thread.

**Comment by fatcerberus** [comment]
IMO `void` as the type of a *value* doesn’t really make sense.  But it *is* useful to be able to express “I want a function whose return value I don’t care about” and have the type system be able to back me up on that (i.e. if I say I don’t care but the code I write proves that I do, that should be a type error).  That can’t happen if the function is declared as returning, say, `unknown`—but using `undefined` here is overconstraining.

**Comment by fatcerberus** [comment]
To cut through the noise and be clear (and get back on-topic): I only mean to argue that narrowing `boolean | void` to `boolean` is unsafe for the same reason as the current narrowing behavior w.r.t. `undefined`.

**Comment by jack-williams** [comment]
> But it is useful to be able to express “I want a function whose return value I don’t care about” and have the type system be able to back me up on that (i.e. if I say I don’t care but the code I write proves that I do, that should be a type error). That can’t happen if the function is declared as returning, say, unknown—but using undefined here is overconstraining.

If this really is a desirable and bug-reducing feature I think the correct thing is to introduce non-narrowable type parameters and use generics.

> I only mean to argue that narrowing `boolean | void` to `boolean` is unsafe for the same reason as the current narrowing behavior w.r.t. undefined.

There may be similarities when interpreting the contract of `void` as some form of obfuscation, but in terms of runtime safety I think they are different. The linked issue that removed `void` under the predicate `!== undefined` is fundamentally misleading, and will lead to situations where you are told you have a string, but really you have a number.

Narrowing `void` under `typeof` is not misleading in this sense: if something has the runtime type of `"boolean"` then it satisfies the type `boolean`.

The former is clearly unsound under any reasonably definition and should be fixed. The latter is open to interpretation.

**Comment by fatcerberus** [comment]
The way I see `void` is as an unsound bottom type (hence the perceived duality with the unsound top type, `any`): it represents a type with no inhabitants like `never`, but is inherently unsound because the “value-producing” logic is still reachable.  A bottom type that acts like a union type.


Therefore, `boolean | never` can be seen as isomorphic to `Maybe<boolean>`, however this is merely an abstraction since we can’t *really* have a simply-typed variable that has no value.  The best we can do to maintain the illusion is treat the `void` as random noise - and if it’s random noise, there’s no reliable way to distinguish it from a valid value of type `boolean`.

I’ll see if I can come up with a practical example later, so we’re not dealing entirely with intangible theory.  If so I’ll also open a separate issue for discussion and stop spamming this one. :smile:

**Comment by ethanresnick** [comment]
Possibly relevant: https://github.com/microsoft/TypeScript/issues/32809

**Comment by jack-williams** [comment]
I'll get to merging this in the next week (for anyone planning to review this).

**Comment by jack-williams** [comment]
> It does need a merge though.

Will do!

**Comment by sandersn** [comment]
@jack-williams @weswigham should we close this now? I wasn't sure from the discussion whether it's completely obsoleted by #38311 but it sounds like it.

**Comment by jack-williams** [comment]
@sandersn The only objective here is to unify the logic of `typeof` narrowing in `switch` and `if` by sharing the code; there should be no functional change with this PR. 

#38311 changes the root type for discriminant narrowing, so I think it solves a different problem. I did have another PR which was correctly replaced.

I've merged master and moved things around to reduce the diff, hopefully this makes it clearer.

Feel free to close or merge, whatever you see fit. I think we should get this out of the open PR's either way!

**Pull request merged**
