### PR TITLE
fix(48291): TS1193 in JS File

### LINKED ISSUE #48291: TS1193 in JS File
# Bug Report

### 🔎 Search Terms

ts1193 
"An export declaration cannot have modifiers."

### 🕗 Version & Regression Information

- This changed between versions 4.5.5 and 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKaiAm8APAOgBcBnAKGlQAcB7AJxNAHIjgcBjWAV3wFpkLChRAQYCFOixdeA5EQBWlQvSagA3qHyRkPWM2RlQAIVABfUJAZ1UrdrL7x+AIxYBuEcABU3iqG9QAElIUABPOh5QBnhUOgA3eFASAAskgANwfBoYzmQSeFx05OQAcwAaZLTsMjIeJNxoMmQaGnhkBjIif0Cs+Bz4PILcHuAKVUZmLR09A1AjUABhCysbOzYORG4nfk4PLzAoOCQ0TGwtuWcXJUoxI8lTmQudzhuKIA)

### 💻 Code

```ts
/**
 * @deprecated
 */
export { default as C } from './include-c';
```

### 🙁 Actual behavior

I got error `TS1193: An export declaration cannot have modifiers`. When I remove the `@deprecated` tag, it disappears.

### 🙂 Expected behavior

Having a `@deprecated` tag should not trigger this error.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #48291

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Thanks as always @a-tarasyuk !

**Comment by Bartel-C8** [comment]
Will this be merged in 4.6.x branch as well? For me in 4.6.4 this is still broken?

**Comment by Bartel-C8** [comment]
@a-tarasyuk , just pinging you to get a notification, as I suspect you won't get an notificaiton automatically. Thanks!

**Comment by RyanCavanaugh** [comment]
We generally only backport critical fixes, which this isn't. 4.7 will be the first release containing this fix

**Comment by Bartel-C8** [comment]
@RyanCavanaugh : I understand the general concern. 

But in my specific case I am bound to 4.5.x then.
As my TS error resides in a module dependency, I have no control to update is (and actually it's just a TS bug, so nothing to be fixed upstream).
And upstepping to 4.7.x would mean upstepping my whole Webpack build (Electron) process, which involves updating ts-loader, which needs an updated webpack version (4 to 5), which is unfortunately not possible due to other issues...

Thank you anyway.
Kind regards.

**Pull request merged**
