### PR TITLE
Strip literal freshness of contextually typed literals

### LINKED ISSUE #49514: Type Predicate Function Inconsistent Across Identical Inferred Types
# Bug Report

### 🔎 Search Terms

type predicate filter flatMap null

### 🕗 Version & Regression Information

This is the behavior in every version I tried (that don't throw errors), and I reviewed all FAQ entries.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=4.7.2#code/JYWwDg9gTgLgBAbzgMTgXzgMyhEcBEMAzgLQwQQA2ARgKaUz4DcAUCwMYQB2R8RAhjGBFMwWkTgBeFnDgAeACoB1YABNaAGgB8ACgCUUrTPkKAcvyg4A7nFoAPGLS6qJytbV1cL1gFwoAdOaWEFaKQdZaBpJGsrJewVasLAD0AFRSkplZ2Tm5efkFhUV5cKnJbJw88MKmEDCmAK6UlFIm2joAbvyUDbR+CnAAPnBcTZR6fl09tHDCcAPRcFO9cACEmSNjSTAAnmAzAJKOeJJwAIKW-DtySMt9cLxQwFwA5kObzehaSZW8s8cARlaAiEIjERDkR1oIF0eh0AG1bt1en58AD8OgALp6Vi-arHABMwMEwlE4khx1hCKR01RBIxaGxuO4f2AxwAzMTQWSIVCYfpqUtkfdRp9GTiKiz4HciEDTvC2dCARp-tCCSrFSB2Zj-JhKIIALL8MA6TWGVUgfwgY06MDmsD+O56CV4rDABi0KC0VQANWFstaMoBuvdjigpqItXqYxxcGSyQeQk+lRg-GeEgABqLKBnZlw4Lt9nAfDpJVUhdMiAS-BcoFc5GiMcN8PT3tmtK14Y2VS38Crs5imHGEwIQDMvZBYN6C3sZvxMzKMxwpW6PV7ff6iacZQSQ2uI1HGs1Y-G4FmxrnOJZaOwYJQdnAXrRiLY7OweupVFgcHhC7QWEAA)

### 💻 Code

```ts
import { F } from "ts-toolbelt"; // can easily be replaced with raw TS code if needed

const satisfies =
  <TWide,>() =>
  <TNarrow extends TWide>(narrow: F.Narrow<TNarrow>) =>
    narrow;

const isNotNull = <T,>(value: T | null): value is T => value !== null;

type Item = Array<{ value: string | null }>;

const item1 = satisfies<Item>()([{ value: "1" }]);
const item2 = satisfies<Item>()([{ value: "2" }]);
const item3 = satisfies<Item>()([{ value: null }]);

const values1 = [item1, item2, item3].flatMap(item => item.map(p => p.value));
const filteredValues1 = values1.filter(isNotNull); // still contains `null` in type :(

const values2: Array<"1" | "2" | null> = ["1", "2", null]; // same reported type as `values`
const filteredValues2 = values2.filter(isNotNull); // `null` correctly gets excluded from type
```

### 🙁 Actual behavior

`filteredValues1` still contains `null` in its type when is shouldn't.

### 🙂 Expected behavior

`filteredValues1` should have the same type as `filteredValues2` (without `null`).

---

Originated from this Twitter thread: https://twitter.com/joealden_/status/1536335566891061249

### PR DESCRIPTION
**Pull request by andrewbranch**
I thought this would be way too heavy-handed, but surprisingly the baselines don’t look that bad?

Fixes #49514

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this faster

**Review by ahejlsberg — APPROVED** [review]
Looks good to me. Definitely seems wrong to infer fresh literal types for array literal elements and object literal properties.

**Comment by andrewbranch** [comment]
The puppeteer failure shows that `Object.freeze` is a fairly easy way to observe this change. I think the new behavior makes more sense, but it is certainly a breaking change:

```ts
const PUPPETEER_REVISIONS = Object.freeze({
  chromium: '1011831',
  firefox: 'latest',
});

let preferredRevision = PUPPETEER_REVISIONS.chromium; // Previously string, now "1011931"
preferredRevision = PUPPETEER_REVISIONS.firefox;      // Previously ok, now error
```

**Comment by AlCalzone** [comment]
Would it be possible to get a test build with this? I'd like to test if I can get rid of basically a ton of `as const` assertions with this.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by AlCalzone** [comment]
Doesn't look like that worked @andrewbranch

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
@andrewbranch I assume this is 4.9-bound, right?

**Comment by andrewbranch** [comment]
@sandersn yep.

**Comment by david10sing** [comment]
> The puppeteer failure shows that `Object.freeze` is a fairly easy way to observe this change. I think the new behavior makes more sense, but it is certainly a breaking change:
> 
> ```ts
> const PUPPETEER_REVISIONS = Object.freeze({
>   chromium: '1011831',
>   firefox: 'latest',
> });
> 
> let preferredRevision = PUPPETEER_REVISIONS.chromium; // Previously string, now "1011931"
> preferredRevision = PUPPETEER_REVISIONS.firefox;      // Previously ok, now error
> ```

Is there a proposed workaround for this? I am having the same issue here. https://github.com/microsoft/TypeScript/issues/52125

I think this new behaviour goes against JavaScript's syntax. In the example you gave above, I think it is fine to do the re-assignment but now we have TypeScript telling us that it is an error.

In my use case, creating an array from an immutable object and running includes on that array should not throw a type error.

With this breaking change, does this mean that to get around this, we need to do `[] as string[]`?

**Pull request merged**
