### PR TITLE
Updated dom related reference files according to new IE spec

### PR DESCRIPTION
**Pull request by zhengbli**
The IE team started to issue new specs in the format of XML files instead of webidl files for upcoming API changes. The new dom.generated.d.ts and webworker.d.ts are generated from the new XML specs to be consistent with IE Dom API changes.

### CODE REVIEW

**Comment by danquirk** [comment]
Have we run this change against our real world code suites? We need to make sure changing the order of overloads doesn't break anything.

**Comment by zhengbli** [comment]
There are indeed a bunch of breaking changes that cause 57 rwc tests to fail. And the reasons of failure are documented at: http://1drv.ms/1DFuYE7. Should the rwc tests be changed before merging?

Also, what do you mean by "the order of overloads"?

**Comment by mhegazy** [comment]
@zhengbli can you list the issues that will be fixed by this change as well.

**Comment by mhegazy** [comment]
looking at this diff is hard. can we sort the declarations in some order to make the diff more useful

**Comment by mhegazy** [comment]
also i do not think you need extensions.d.ts anymore. i could be wrong though. We have added them as some types in dom.generated.d.ts depended on them. if they are not used we should remove them and let es6.lib.d.ts be the only definition of these types.

**Comment by zhengbli** [comment]
Issues that would be fixed:
#2437 Missing properties: document.pointerLockElement and MouseEvent.movement 
#2416 WheelEvent constructor in lib.d.ts
#2029 Type definition of CustomEvent constructor needs parameter(s).
#1852 DOMStringMap is defined as an empty interface - this makes it awkward to use
#1850 "SOURCE"
#1618 "getElementsByTagName('svg')" does not returns NodeList of SVGSVGElement, but generic NodeList.
#1302 add declarations for HTML Touch events to lib.d.ts
#1224 EventListener interface does not accept objects with a handleEvent method
(not sure) #1075 IDBKeyRange definition is degraded
#674 MouseEvent constructor is missing parameters
#314 SourceBuffer.appendBuffer() is missing overload for ArrayBufferView param in lib.d.ts

**Comment by mhegazy** [comment]
That might need a new PR, or a force push on this branch, but it would be nice if we can get in the change to dom.generated.d.ts to sort it using the old script. Then add a commit with your change. this way we can look at the diff of the two commits and see the actual change.

**Pull request closed without merging**
