### PR TITLE
Adding -suppressExcessPropertyErrors compiler option

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR adds a `-suppressExcessPropertyErrors` experimental compiler option that the disables strict object literal assignment checking implemented in #3823. The intent of this compiler option is to allow existing code bases to compile until issues found by the strict object literal assignment checking are addressed.

### CODE REVIEW

**Comment by vladima** [comment]
:+1:

**Comment by mhegazy** [comment]
:+1:

**Comment by hcapp01** [comment]
how to set suppressexcesspropertyerrors in csproj

**Comment by mhegazy** [comment]
@hcapp01 add this to your project file:

```XML
<TypeScriptSuppressExcessPropertyErrors>true</TypeScriptSuppressExcessPropertyErrors>
```

for more documentation on all MSBuild property names see https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

**Comment by WanderWang** [comment]
:+1:

**Pull request merged**
