### PR TITLE
Fix `isGenericReducibleType` to allow HKT technique to function again

### LINKED ISSUE #53970: Inference is broken on intersection type utilizing polymorphic `this`
# Bug Report

### 🔎 Search Terms

inference, intersection, polymorphic this, deferred index access

### 🕗 Version & Regression Information

- This changed between versions 5.1.0-dev.20230313 and 5.1.0-dev.20230315

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230422&ssl=34&ssc=1&pln=1&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFQE8xgAZTAWwCMATTOAbwCg44phMaIkAbQuAIIAuOAFckAayQQA7kiYBfJk1CRYiFGiy4CxYAGEemAM7GAPADE4oVEhrHdJctToA+RizYcuvfgH0LEQtFZVVoeBg9QTAwPktrEFt7RzJKWkwAGkF3AF44KxtgOwcGL05uPjhIkhFxKVkkOCVWAH44AAorADJGMp9K4UEmgEoAbQByauBxgF1PEVL2ct98oKyl-v5BgSbQ8HCNVAwcPHwzAXdmVgA3TB5RYBEBEJV99WQj7VOiJzS6BKSDh+qRc9CufQq-CmIjOMAAFghjKMAEQCZEzVwvMLqGjAbBGdhwbDcYzwCiYMAieKFYopZzpVydGF6QwmcwWVzDOA5dznLIAIUZmCeMTiFiyFyy6BE7WFgi5PLg-IV7gEosIlgFmKYuPxmEJxKQpKqLKMpmZJFZpjM+GB9Lcyl1BLwhuNcrOSFE1DQ2vJYHaUytxmGTAA9KGCABlOAAVgAdAAGOMAFhErHTGYzfKVQph51cUplcoEKqVpbOgrDEfw0fjAEZEwBaXHXOMAJgTbYAzAnk2221SBFrZTLbXp7fQeotvJDBE8ANwjFFTdGFjrF0vK7nudpj36guBTiErQb8xcKMbIldzJh+gOmtnDWVZdp+UtvzyZr-p8NwAB6UaxomKYaOgaAOJ63pQJ+35fr+rA1kBDYJs2wCth23a9v2oHgWIkjSHITBAA)

### 💻 Code

```ts
export interface TypeLambda {
  readonly A: unknown
}

export interface TypeClass<F extends TypeLambda> {
  readonly _F: F
}

export type Apply<F extends TypeLambda, A> = F extends { readonly type: unknown }
  ? (F & { readonly A: A })['type']
  : { readonly F: F, readonly A: A }

export interface T<A> {
  value: A
}

export interface TTypeLambda extends TypeLambda {
  readonly type: T<this["A"]>
}

export declare const map: <F extends TypeLambda>(F: TypeClass<F>) => <A, B>(a: Apply<F, A>, f: (a: A) => B) => Apply<F, B>

declare const typeClass: TypeClass<TTypeLambda>

declare const a: T<number>

map(typeClass)
// TS 5.0.4:              <A, B>(a: T<A>, f: (a: A) => B) => T<B>
// TS 5.1.0-dev.20230422: <A, B>(a: (TTypeLambda & { readonly A: A; })["type"], f: (a: A) => B) => (TTypeLambda & { readonly A: B; })["type"]

map(typeClass)(a, (_) => _)
                // ^ TS 5.0.4 infers number
                //   TS 5.1.0-dev.20230422 infers unknown

```

### 🙁 Actual behavior

Each version including and after 5.1.0-dev.20230315 defers the index access in the `Apply` type and doesn't allow inference to continue.

### 🙂 Expected behavior

Inference should continue to work in this case.

After a bit of research, I think that #53098 is the PR that introduced this change.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53970.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Review by weswigham — APPROVED** [review]

**Comment by ecyrbe** [comment]
@ahejlsberg nice, i confirm that zodios use case is working again : [link to playground](https://www.staging-typescript.org/play?ts=5.1.0-pr-54112-10#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgNwBQFApgB6SxzAB2M1UmAhgMbVwCCzAJ4AtEsAgBnACpCw1AAo4AbsGLsAPAGVuAC2ohOcALxwArswDWzCAHdmAPkQU4cSXoOcAXHB37DlK4sYGYwPhbWdsyBcBChIWHmVjb2lGhUdAzwMHJ8AJLMmOwFCbLyAGI4IH6eGi5wZYoqauxwdGzMxJICwmLEEjK5ShCq6lAANPU1hhROpgAUjcOjrQBkiG4ehj7TRmgAlADaAETBoccAupQ09NDZuXAFRVAA8vGhjZW4u3WuS81jNq0DpdHqicRSf4jFoTKZbTizExwRZDAFrDbufzeXzw9BHY5xGAJS7XTJ3OA5eRwPoDABqnAANmpOGwAErUSRmBnwYz1AA+GLM3F4kkkPhgUDM1DIcGILOxnGE6H5guFHLFWEZkmlbSgOCgPkVQnQpNujBYbA4PD4NKkrIsMFA1ChKygvwaqOhgPa1E63UE4P6kM9rsRCHqUGonGIEGYDONAH0wGioAB+HwumExZSM5lsHzzTGeQ3CcZMZgJcLJKL7ExOW2SelMuVsjlcmDZ3Mt6j8SRCZjcAtF7ZwI1ls6JCIpZi14xOYYgYDajQNpt56jsznchxpDJm+AW9hcXjUkiZsb1H1+sEN8+aJAJidVyKpOAJwmVpIv5joJzhoIVqE4q6EuJzDpwlwnI+gEwCS9QfkBFIgZIYHwpBxzvu8sFXBQ6QUNwsaSPAZjalAuxIsgAB0EAAEYAFbUNwMDzP+TDED4VHMGYIA0ew8z7JMrjMJwIDUBxlFEVALAAOb8bh+zXJSfDSAADEiTzFDBnxVD8fR3hMFK5BAmDmKRuw7hQAD0lmuHAAB6qZUEAA)

**Comment by mikearnaldi** [comment]
Amazing thank you!

**Comment by ahejlsberg** [comment]
Latest commit reverts the changes to type inference and instead fixes the issue by making `isGenericReducibleType` more conversative. The previous logic would wrongly classify `TTypeLambda & { readonly A: A; }` as being reducible even though there are no discriminant properties in the type. That's now fixed.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by mikearnaldi** [comment]
Amazing! Looks great

**Comment by jakebailey** [comment]
@weswigham mentioned that this may break a case where two generic litearl `kind` props were intersected, but I can't seem to make this case up; can you give an example?

I've tried this to no avail. [Playground Link](https://www.staging-typescript.org/play?ts=5.1.0-pr-54112-28#code/FAFwngDgpgBAkgOxFATgZygYxAGQJbIoCGANgNJ4IAmAPAIIxQAey1aMARERzAD6cAjDgBoYAIUYsobTtz6COAPhgBeGAG8YAa0pUAXDDoBuGBBQB7CHQNoQKSgHMTAXxgAyDdt0GxJs5bEbO0cXYDCqLBIiFFhMcwRbGCo8ADMU1GkQA0RCDGx8QlIKahouEQVFcNT0mKQjYAB6BpgAPQB+MOAIzCiYmDiEkBg0IgBbKGykVDzcAlQi3VLuUTLK4AHEnWpVYbGoADotqnqmmDOz9vX4xP8rHZHx-dvjRubz1o6NoduJNQeDn4nN7nS5hFIAVwQ2Dw8SS5gAyuZxiAABaOeiSVhUdhleQcISiCTMLE4uT8fFKAAU5gEACtJrksLNCuRFnRCYoAJQaYDvL5ebZqGm0w66ervU7vS5867fCx3IV0p7yl4S4EXDoywameW-GDC5UBcXnSUgjrOIA)

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.1

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.1

... please?

**Pull request merged**
