### PR TITLE
Handle fsWatch event with accesstime change on mac os

### LINKED ISSUE #52876: Watch mode: `git diff` on macOS triggers rebuild
# Bug Report

### 🔎 Search Terms

- watch

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [configuring watch](https://www.typescriptlang.org/docs/handbook/configuring-watch.html)

### ⏯ Playground Link

N/A

### 💻 Code

Steps to reproduce:

1. In a Git repository with the following files: `main.ts` and `tsconfig.json`:
   ```json
   {
     "files": ["./main.ts"]
   }
   ```
2. Modify `main.ts` so Git has unstaged changes and then run:
   ```console
   $ tsc --project tsconfig.json --watch --diagnostics
   ```
3. Finally, run `git diff`.

### 🙁 Actual behavior

`tsc` rebuilds because `git diff` bumps the access timestamp (see `stat -x main.ts`).

This is particularly problematic for me because I use [`lazygit`](https://github.com/jesseduffield/lazygit) which refreshes the Git diff every few seconds.

https://user-images.githubusercontent.com/921609/220190714-de196ad4-baa9-4917-8afc-b4963682ddd5.mov

--

Output from `tsc`:

```
FileWatcher:: Triggered with /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 1:: WatchInfo: /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 250 undefined Source file
Scheduling update
Elapsed:: 0ms FileWatcher:: Triggered with /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 1:: WatchInfo: /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 250 undefined Source file
Synchronizing program
```

### 🙂 Expected behavior

`tsc` should not rebuild when the _access_ timestamp changes.

I suspect this is due to the behaviour of `fs.watch`. In that case, is there anything else we can do to improve the default behaviour for macOS users? (Assuming this issue only occurs on macOS because I haven't been able to test on other platforms.)

Note I am able to workaround by setting any of the following variables in my shell RC file:

```sh
export TSC_WATCHFILE=DynamicPriorityPolling
export TSC_WATCHFILE=PriorityPollingInterval
export TSC_WATCHFILE=UseFsEvents
export TSC_WATCHFILE=UseFsEventsOnParentDirectory
export TSC_NONPOLLING_WATCHER=true
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Send change event only if modified time has changed on mac os.
Fixes #52876

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot  pack this

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
Does Windows need this too? Similar is #52535.

**Comment by sheetalkamat** [comment]
Not without concrete repro steps.. `git diff` on windows doesnt trigger refresh..

**Review by jakebailey — APPROVED** [review]
LGTM though I do kinda wonder if asking for the mtime touches atime, thus causing an event itself... But surely not given the user reported all was well.

**Review by sheetalkamat — COMMENTED** [review]
This isnt the right fix and #57938 addresses the issue instead.

**Pull request merged**
