### PR TITLE
extend the list of extensions for module file names in node_modules f…

### PR DESCRIPTION
**Pull request by vladima**
…older

### CODE REVIEW

**Comment by mhegazy** [comment]
//cc: @sheetalkamat

**Comment by mhegazy** [comment]
:+1:

**Comment by weswigham** [comment]
Errrr, wasn't the reason we had this restriction in the first place because we thought people generally wouldn't want to be _inadvertently_ emitting the TS files we found in their `node_modules` directory? I understand that in the example in #5225 he wanted, explicitly, to effectively just use his `ts` files directly for type information, but as it stands right now, if we find a library with both an `index.ts` and an `index.d.ts`, we'll find the script file _first_ and (try to) reemit the library on compilation (rather than use any potential existing definitions).

**Comment by s-panferov** [comment]
@vladima @mhegazy thanks for the fast reaction, this is awesome! The solution is great, but, as @weswigham said, we may want to change the order of extensions [here](https://github.com/Microsoft/TypeScript/commit/d57ceb1d32380de7dba6a54350e7a6a750ebf675#diff-66cec844e251a1918deb897eabca206bR730) to use a `.d.ts` first if it is available and than fallback to `.ts` and `.tsx`, because it is backwards compatible with previous behaviour.

**Comment by mhegazy** [comment]
@vladima has a validation tool, that package authors should run. @vladima can you share your tool?

**Comment by basarat** [comment]
@s-panferov just for your info, a `.ts` file linked from typings will error out till https://github.com/Microsoft/TypeScript/issues/5278 is resolved :rose:

**Pull request merged**
