### PR TITLE
react starter needs node ref, accept fixed leveldown

### PR DESCRIPTION
**Pull request by weswigham**

### CODE REVIEW

**Comment by mhegazy** [comment]
seems wrong that you need react.d.ts and node.d.ts in the same compilation.. does leveldown really needs node?

**Comment by weswigham** [comment]
@mhegazy not `leveldown`, but the `react` starter; specifically because it uses `require` as a function.

**Comment by mhegazy** [comment]
`leveldown` seems to rely on node as well.. 

for `require`, requireJs should have been used instead..

Just to be clear, the test as you have now is fine, i am just noting an issue with the starter kit.

**Comment by sandersn** [comment]
Note to self: leveldown still failed for me until I deleted user/leveldown/node_modules. user tests might need to delete node_modules too.

**Pull request merged**
