### PR TITLE
Fix incorrect condition of noLib

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Comment by MichaelMitchell-at** [comment]
Verified this fixes the issue described in https://github.com/microsoft/TypeScript/issues/58863#issuecomment-2168784178 ! Thank you!

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
We should have run the extended tests on this; it this causes a crash in the vscode codebase, and also causes some 100 errors there too.

**Comment by jakebailey** [comment]
I had to revert this in #58935; it caused compilation of vscode to crash when `--diagnostics` was passed, and some 100+ missing lib errors.

**Comment by sheetalkamat** [comment]
> I had to revert this in #58935; it caused compilation of vscode to crash when `--diagnostics` was passed, and some 100+ missing lib errors.

The errors dont seem to be because of this PR. I ran `tsc -p src` with and without fix and the number of errors didnt change.
I do see the crash and looking into whats going on. But this fix is partially correct.

**Comment by jakebailey** [comment]
Oops, you're totally right. I think I was incorrectly comparing against another baseline. That being said, I don't know why they have the errors at all, https://github.com/microsoft/vscode/blob/main/src/tsconfig.base.json#L23 says ES2022 so we should also be pulling in ES2021.

**Comment by sheetalkamat** [comment]
Its because one of their file `c:/temp/vscode/src/vs/workbench/contrib/webview/browser/pre/service-worker.js` has `no-default-lib` is true. I will revisit #57524 and come up with some proposal but thats the cause.

**Pull request merged**
