### PR TITLE
BigInt type constructor should not accept any type

### LINKED ISSUE #38980: BigInt constructor should not accept any type
**TypeScript Version:**  3.9.3

**Search Terms:**

**Code**

**Expected behavior:**

```ts
interface BigIntConstructor {
    (value: string | number | bigint | boolean | object): bigint;
}
```

**Actual behavior:**

```ts
interface BigIntConstructor {
    (value?: any): bigint;
}
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by MattBidewell**
BigInt type constructor should not accept any type - [38980](https://github.com/microsoft/TypeScript/issues/38980)

Branch made on 01/10. 
PR Made on 01/10.

Fixes #38980

### CODE REVIEW

**Comment by MattBidewell** [comment]
(modified lib. My bad)

**Comment by sandersn** [comment]
@typescript-bot user test this
@typescript-bot run dt

**Comment by sandersn** [comment]
User tests don't have any new failures.

**Comment by fubar** [comment]
@MattBidewell this has been fixed in https://github.com/microsoft/TypeScript/pull/43204

**Comment by sandersn** [comment]
Thanks for noticing @fubar, and thanks for your PR @MattBidewell 

(#43204 is a redo of the older #38995 with a bogus change removed.)

**Pull request closed without merging**
