### PR TITLE
switch to tslint@next

### PR DESCRIPTION
**Pull request by vladima**

### CODE REVIEW

**Comment by mhegazy** [comment]
Looks like tslint need to update their peer dependency to include 2.2.

**Comment by vladima** [comment]
`tslint@next` is already [supports](https://github.com/palantir/tslint/blob/next/package.json#L69) updated

**Comment by vladima** [comment]
another peer dependency error comes from `gulp-typescript` - should be covered by [this](https://github.com/ivogabe/gulp-typescript/pull/457) PR

**Comment by vladima** [comment]
..and the build is green again!

**Pull request merged**
