### PR TITLE
Updated error message for TS2539

### LINKED ISSUE #39751: Error message for assigning to an imported variable is confusing
## Search Terms

TS2539 import variable

## Suggestion

```ts
import { v } from "somewhere";
// Error TS2539: Cannot assign to 'v' because it is not a variable.
v = 100;
```

The error message for TS2539 is confusing because `v` is actually a variable (at least regarding the ES spec where imported ones and other normal variables are described as different kinds of "bindings") . The true reason of the error is that it is an imported variable, so it would be better if we changed the message to, for example:

- Cannot assign to `v` because it is an imported variable.
- Cannot assign to `v` because it is immutable.
- Cannot assign to `v` because it is a constant. (same as `const` variable)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by hailin-zhang**
Fixes #39751

There were a number of different cases using this error code outside of the one reported so I used a more generic error message. Please let me know if a more descriptive message should be used 👍 

Thanks!

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Maybe "because it is not a writable binding" or something - immutable really does imply the entire structure is frozen. Maybe @sandersn has a suggestion.

**Comment by orta** [comment]
> `because it is not a writable binding`

is real jargon-y, perhaps we could narrow down the error handling and explicitly check that it's an import, then offer something like:

> `Cannot assign to '{0}' because it is imported value which cannot be changed`?

**Comment by sandersn** [comment]
I agree, the baselines show that the error happens on, at least, `enum`, `class`, `function`, `namespace`, `import`.

If the error distinguishes those cases, you could probably get away with a very simple error, something like:

`Cannot assign to '{0}' because it is an import.`

It might even be parametrisable:

`Cannot assign to '{0}' because it is a(n) {1}.`

**Comment by DanielRosenwasser** [comment]
```
'{0}' declarations like '{1}' cannot be assigned to.
```

**Comment by vuvuzella** [comment]
> ```
> '{0}' declarations like '{1}' cannot be assigned to.
> ```

I agree with the word declaration. Another variation can be
`Cannot assign to '{0}: Previous {1} declaration of the same name exists'`

**Comment by sandersn** [comment]
@hailin-zhang do you want to keep working on this?

**Comment by hailin-zhang** [comment]
@sandersn sorry for the lack an update, I am OK if somebody wants to take this ticket, if not then I can circle back once I have more time

**Comment by sandersn** [comment]
I switched to multiple languages, and, since `undefined` was the only one I didn't cover, switched back to the original message for that, since the original covers `undefined` nicely.

**Pull request merged**
