### PR TITLE
For composite projects with --out write tsbundleInfo file and use it to process shebang, prologues and other information

### LINKED ISSUE #25550: Duplicate `"use strict"` prologue in the generated output.
Duplicate `"use strict"` prologue in the generated output. 

See https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/tsc.js

### PR DESCRIPTION
**Pull request by sheetalkamat**
This is another version of #29582 and would be helpful to enable --stripInternal by recording those sections and not emitting those portions on final projects with --stripInternal (eg. generating typescript.d.ts)
Fixes  #25550

### CODE REVIEW

**Comment by weswigham** [comment]
@sheetalkamat Could we have both methods of looking up the metadata in place? The bundle info is nice for build pipelines that only use `tsc -b`, but it's very possible that in more complex pipelines the build intermediate outputs could be munged by other tools (and we don't keep an incremental cache of our own to rely on), in which case the `.tsbundleinfo` data would be out of date and the information would need to be recalculated from the sources anyway.

**Comment by weswigham** [comment]
@sheetalkamat I'm thinking more along the lines of build chains that just shell out to `tsc -b`, where they execute it once, then do another transform on the output (like minification, webpacking, or API-extracting), and where that secondary transform may be done in-place.

**Comment by sheetalkamat** [comment]
@weswigham I had chat with @RyanCavanaugh and we think at this moment the fall back parsing isn't necessary. 
We also discussed ".tsbundleinfo" being more information than just `--out` so instead of naming it as "outFile.tsBundleInfo" it should just be ".tsbundleinfo" and I will update the branch with that.

**Comment by sheetalkamat** [comment]
I am going to close this and open PR that is bigger set of changes where prepend mapping works much better.

**Pull request closed without merging**
