### PR TITLE
Fix false positive rewriteRelativeImportExtensions error on non-TS extensions

### LINKED ISSUE #60392: rewriteRelativeImportExtensions and resolveJsonModule
### 🔎 Search Terms

- `rewriteRelativeImportExtensions`
- `resolveJsonModule`
- `ts(2876)`
- rewrite json module
- import json path
- tsconfig, config options
- file path name
- import assert type json

### 🕗 Version & Regression Information

- This changed between versions `N/A` and `5.7.0-beta`
- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/59767
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about these config flags and JSON more generally (nothing found)
- I was unable to test this on prior versions because `rewriteRelativeImportExtensions` did not exist

### ⏯ Playground Link

_No response_

### 💻 Code

```jsonc
// package.json
{
  "type": "module"
}
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "module": "NodeNext",
    "rewriteRelativeImportExtensions": true,
    "resolveJsonModule": true,
  }
}
```

```jsonc
// example.json
{ "example": true }
```

```ts
// example.ts
import * as example from "./example.json" assert { type: "json" }
                         ^^^^^^^^^^^^^^^^
// This relative import path is unsafe to rewrite because it looks
// like a file name, but actually resolves to "./example.json". ts(2876)
```

### 🙁 Actual behavior

```ts
import * as example from "./example.json" assert { type: "json" }
                         ^^^^^^^^^^^^^^^^
// This relative import path is unsafe to rewrite because it looks
// like a file name, but actually resolves to "./example.json". ts(2876)
````

### 🙂 Expected behavior

No error

### Additional information about the issue

The documentation says:

```jsonc
/* Rewrite '.ts', '.tsx', '.mts', and '.cts' file extensions in relative import paths to their JavaScript equivalent in output files. */
```

I wouldn't expect this to apply any sort of change to a `.json` file.

### LINKED ISSUE #60396: rewriteRelativeImportExtensions with import mjs file into mts file => TS2876: This relative import path is unsafe
### 🔎 Search Terms

rewriteRelativeImportExtensions
ts(2876)

### 🕗 Version & Regression Information

- This changed between versions NA and 5.7.0-dev.20241103 or 5.7.0-beta

### ⏯ Playground Link

_No response_

### 💻 Code

//src/logger/logger.mjs
//File is JS m**j**s file!
```js
const logger = (message) => {
  console.log(message)
}
export default logger;
```
src/database/database.mts
//File is TS m**t**s file!
```ts
import logger from '../logger/logger.mjs';
```
// tsconfig.json, fragment
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": [
      "esnext"
    ],
    "allowJs": true,
    "esModuleInterop": true,
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "rewriteRelativeImportExtensions": true,
    "resolveJsonModule": true,
  }
}
```

// "package.json does not have any type overriding because project explicitly uses the correct filename extensions."

### 🙁 Actual behavior

import mjs  in mts file 
TS2876: This relative import path is unsafe to rewrite because it looks like a file name, but actually resolves to "../ logger/ logger. mjs"

But works good
 - on import .mjs into mjs files.
 - on import .mts files into both, mjs and mts.

### 🙂 Expected behavior

No error emitted. imported filename and extension is correct.

### Additional information about the issue

Reproduced on both, 5.7.0-beta and current ^5.7.0-dev.20241103

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #60392
Fixes #60396 

This check was unnecessary for the actual rewriting, but somehow forgot to include it for error checking.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Should this be patched in for 5.7 stable?

**Comment by andrewbranch** [comment]
Yes—I thought we hadn’t split off yet?

**Review by jakebailey — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot pick to release-5.7

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick to release-5.7

**Pull request merged**
