### PR TITLE
fix (lib): Loosen predicate return types of typed arrays, adapt docs

### PR DESCRIPTION
**Pull request by MichaelTamm**
This is a follow up to PR #31076

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@MichaelTamm can you address the merge conflict and then unassign yourself? Sorry for the delay and thanks!

**Comment by MichaelTamm** [comment]
@RyanCavanaugh: Merge conflict resolved.

**Comment by flundermicha** [comment]
@RyanCavanaugh: Merge conflicts resolved. (again)

**Comment by MichaelTamm** [comment]
@RyanCavanaugh: Merge conflicts resolved (once again).

**Comment by MichaelTamm** [comment]
Thanks. :)

**Pull request merged**
