### PR TITLE
Error messages for extending a specific type

### PR DESCRIPTION
**Pull request by prateekgoel**
Fixes https://github.com/Microsoft/TypeScript/issues/27890 as mentioned in the issue comments.
This is my first PR. Please suggest any changes required. I will be happy to include them.

### CODE REVIEW

**Comment by mattmccutchen** [comment]
You need to run `jake baseline-accept` after running `jake runtests` (or `jake runtests-parallel`) to update the baseline files.

**Comment by mattmccutchen** [comment]
Sorry, I should have been clearer.  The full messages I'm proposing:

- `Base constructor return type '{0}' is not an object type or intersection of object types with statically known members.`
- `An interface can only extend an object type or intersection of object types with statically known members.`
- `A class can only implement an object type or intersection of object types with statically known members.`

Thanks for working on this.

**Comment by prateekgoel** [comment]
Thanks, @mattmccutchen. I will update the messages today.

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, we can just proceed to review the code.

**Comment by prateekgoel** [comment]
@DanielRosenwasser Thank you for bringing that to my notice. I really missed that.
You can now proceed with the code review.

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
