### PR TITLE
Add support for --noEmitUnderscoreUnderscoreESModule flag

### PR DESCRIPTION
**Pull request by johnsoncodehk**
The '__esModule' is a standard for CommonJS, but forcing the emit '__esModule' does cause problems for many users.

Issues: https://github.com/microsoft/TypeScript/issues/30718 https://github.com/microsoft/TypeScript/issues/30166 https://github.com/microsoft/TypeScript/issues/22879 https://github.com/microsoft/TypeScript/issues/15795 https://github.com/microsoft/TypeScript/issues/15685 https://github.com/microsoft/TypeScript/issues/14351 https://github.com/microsoft/TypeScript/issues/13709#issuecomment-281927333

For me, I have a script that converts the CommonJS code into a baas cloud code, but the Typescript API has no way to remove '__esModule', I can only do replace string of this code:
```javascript
Object.defineProperty(exports, "__esModule", { value: true });
```
But this is not safe, I am not sure if Typescript will change this code in the future:

### CODE REVIEW

**Comment by YoungNovice** [comment]
good

**Comment by gavar** [comment]
any updates on that?

**Comment by RyanCavanaugh** [comment]
Which issue is approved to take a PR (i.e. is in the Backlog milestone) ?

**Comment by johnsoncodehk** [comment]
This problem may never be concerned about.
But here is a quick fix:
Search and replace all ```!currentModuleInfo.exportEquals``` to ```false``` under ```TYPESCRIPT_DIR/lib/```

**Comment by RyanCavanaugh** [comment]
We need an approved issue for a PR to be looked at, but there doesn't appear to be one.

Logged #32934 as the `typeof` check seems reasonable

**Comment by bdero** [comment]
I'm using Typescript in an embedded V8 context, and the engine does not assign `exports` automatically. Instead it only populates `module.exports`.

In my case, my code is not intended to run in any other JavaScript environment, so as a quick and dirty hack to delete these lines in the meantime, I'm using the `tsc-watch` tool to fire a script after successful watch builds in order to automatically delete the lines.

**package.json** scripts:
```json
  "scripts": {
    "watch": "sh node_modules/.bin/tsc-watch --onSuccess 'npm run patchTSOutput'",
    "patchTSOutput": "find . -path ./node_modules -prune -o -print | grep \\.js$ | xargs -n 1 ex '+g/^Object\\.defineProperty(exports,/d' -cwq"
  },
```

Just thought I'd share for other onlookers in the same situation. If you're running into this problem and you want to target many JavaScript environments, you'd probably be better off inserting undefined guards instead (similar to the suggestion in #32934).

**Review by Reality2byte — COMMENTED** [review]
T

**Pull request closed without merging**
