### PR TITLE
Make perfLogger potentially undefined rather than using a noop logger

### PR DESCRIPTION
**Pull request by jakebailey**
Effectively 100% of the time, ETW has not been loaded. Rather than using a noopLogger object, instead make `perfLogger` undefined when ETW isn't loaded, and reference with `?.` just like our other tracing API. This should be faster, and hopefully observable since we trace some of our most-called APIs like file reads/writes, parsing/binding, module resolution, etc.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by fatcerberus** [comment]
Seems like nearly no perf change (which I kind of figured anyway since the JIT will quickly inline noops out of existence).  That said, `?.` conveys what's actually happening much better.

**Comment by jakebailey** [comment]
Yes, I'd want this to be merged regardless of perf.

**Comment by fatcerberus** [comment]
I'm almost surprised this didn't _hurt_ perf, since it theoretically adds branching costs

**Comment by jakebailey** [comment]
The runtime is surprisingly good at figuring out the downleveled `?.`; my own perf testing had shown that even a ternary on `null`/`undefined` was faster than `||`!

**Comment by sheetalkamat** [comment]
This use to be big perf issue where if you did undefined check before calling function it would be slower compared to noop function. Looks like its not anymore ? @rbuckton might know more if thats true as i havent followed changes to this from runtime perspective to know if it impacts perf or not in recent runtimes.

**Comment by jakebailey** [comment]
We did this for tracing back in #42323, so, if there were any perf gotchas, I think they are all solved at this point.

**Review by sandersn — APPROVED** [review]
The change looks OK to me. As long as there's no performance regression, I don't have strong opinions about it.

**Pull request merged**
