### PR TITLE
Adding a JSDoc comment to the es5 type declarations to describe the functionality of Date.now()

### LINKED ISSUE #50565: lib.es5.d.ts - Add TSDoc comment to Date.now function
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

Hi.

I can never remember if `Date.now()` returns a value in seconds or in milliseconds.
Unfortunately, when hovering over this function in VSCode, Intellisense currently offers no clues about this dilemna.

The `DateConstructor` is currently defined like this : https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts#L908-L931

```ts
interface DateConstructor {
    new(): Date;
    new(value: number | string): Date;
    new(year: number, month: number, date?: number, hours?: number, minutes?: number, seconds?: number, ms?: number): Date;
    (): string;
    readonly prototype: Date;
    /**
     * Parses a string containing a date, and returns the number of milliseconds between that date and midnight, January 1, 1970.
     * @param s A date string
     */
    parse(s: string): number;
    /**
     * Returns the number of milliseconds between midnight, January 1, 1970 Universal Coordinated Time (UTC) (or GMT) and the specified date.
     * @param year The full year designation is required for cross-century date accuracy. If year is between 0 and 99 is used, then year is assumed to be 1900 + year.
     * @param month The month as a number between 0 and 11 (January to December).
     * @param date The date as a number between 1 and 31.
     * @param hours Must be supplied if minutes is supplied. A number from 0 to 23 (midnight to 11pm) that specifies the hour.
     * @param minutes Must be supplied if seconds is supplied. A number from 0 to 59 that specifies the minutes.
     * @param seconds Must be supplied if milliseconds is supplied. A number from 0 to 59 that specifies the seconds.
     * @param ms A number from 0 to 999 that specifies the milliseconds.
     */
    UTC(year: number, month: number, date?: number, hours?: number, minutes?: number, seconds?: number, ms?: number): number;
    now(): number;
}
```

The `now()` function has no dedicated TSDoc comment. I think adding one is the needed step to have Intellisense provide the insight.

Thanks

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now

### PR DESCRIPTION
**Pull request by ben-m-j-taylor**
Fixes #50565

Changes:
1. Added a JSDoc comment to the es5 type declarations that describes the functionality of `Date.now()`.
2. Updating the baselines: The only changes were line numbers in the declaration file being incremented by 1, which I believe is to be expected as I've added 1 line to the declaration file.

### CODE REVIEW

**Comment by MartinJohns** [comment]
Reading only the comment: is "current date" also UTC or local timezone?

**Comment by ben-m-j-taylor** [comment]
@MartinJohns Upon re-reading the description I had added I realised I could make it both clearer and more accurate, so I have updated it to the following, which is very similar to the description that MDN provides for `Date.now()`.

> Returns the number of milliseconds elapsed since midnight, January 1, 1970 Universal Coordinated Time (UTC).

**Comment by MartinJohns** [comment]
I'd say that's more clear, yeah. :thumbsup:

**Review by rafikalid — APPROVED** [review]

**Review by sandersn — APPROVED** [review]
Looks good. Can you please merge from main and re-run baselines?

**Comment by ben-m-j-taylor** [comment]
Thanks for sorting the merge out @sandersn, sorry that I didn't manage to get it in, I was having trouble getting the baselines in a good state after merging `main` in.

So once again, thanks for sorting that out 🙂

**Pull request merged**
