### PR TITLE
feat(45295): Consider adding setting that only shows inlay hint parameter names for simple literals (string, number, bool)

### LINKED ISSUE #45295: Consider adding setting that only shows inlay hint parameter names for simple literals (string, number, bool)
# Suggestion

## 🔍 Search Terms
- inlay hints
- parameter names
- typescript.inlayHints.parameterNames.enabled

## ✅ Viability Checklist

N/A, tooling related

## ⭐ Suggestion

Add a new setting that only shows inlay hints for simple literals. This would include:

- string
- number
- bool
- regexp literal?
- null?
- undefined?

Currently the `"typescript.inlayHints.parameterNames.enabled": "literals"` setting also shows parameter name hints for function, array, and object literals

I imagine this new setting would be called something like:  `"typescript.inlayHints.parameterNames.enabled": "simpleLiterals"`, although better names welcome

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45295

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
After discussing this with @RyanCavanaugh, our feeling was that the behavior of "simple literals" is actually how it ought to behave for "literals". We don't feel like most people's notion of literals includes object literals and function expressions. I'm not sure whether others have the same feeling here.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Thanks for the feedback. Do I need to delete this PR?

**Comment by DanielRosenwasser** [comment]
Yes, I've opened up #45557.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser ok

**Pull request closed without merging**
