### PR TITLE
feat(40004): Missing Compiler API predicate function: isNamedTupleMember

### LINKED ISSUE #40004: Missing Compiler API predicate function: isNamedTupleMember
## Search Terms

isNamedTupleMember

## Suggestion

TypeScript's Compiler APIs include `is` functions for all kinds of Nodes. For example, `isClassDeclaration`, `isBigIntLiteral`, and so on.

In TypeScript 4.0.1-rc1, a new kind of node is introduced: `NamedTupleMember`, but no `isNamedTupleMember` predicate function is exposed. For consistency with other kinds of Nodes, TypeScript should arguably also expose such a predicate function.

## Use Cases

- Custom Transformers (visiting and transforming Nodes in an AST)
- Working with the Compiler APIs
- etc

## Examples

```typescript
function visitNode (node: TS.Node, context: TS.TransformationContext, typescript: typeof TS): TS.VisitResult<TS.Node> {
    if (typescript.isNamedTupleMember(node) {
        return visitNamedTupleMember(node, context, typescript);
    }

    else if (...) {
        ....
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #40004

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@rbuckton should this land in 4.0?

**Comment by rbuckton** [comment]
It wouldn't hurt anything to add it and it would be helpful for API consumers

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.0 and LKG

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.0 and LKG

**Pull request merged**
