### PR TITLE
Fix declaration emit for imported export alias specifiers

### LINKED ISSUE #5938: Object detection for "Exported variable `` has or is using name `` from external module"
With the following structure:
- `node_modules/a/default.d.ts` containing a typing and a function
- `node_modules/a/package.json` containing a `typings` field to `default.d.ts`
- `src/default.ts`' re-exporting everything from `a` and exporting new functions
- `src/newFunctions.ts` using the `src/default.ts`

You get "exported variable has or is using name from external module" errors when using an object:

```
import * as b from './default';

// Bug: This does the same thing, but in an object. It should still compile fine, but it doesn't.
export let wrap = {
  findPersonById: function(id: number): b.IPerson {
    return b.findPersonById(id);
  }
}
```

However, when you don't use an object the functionality works as expected:

```
import * as b from './default';

// OK: Expected behavior. Since `b` exports everything from `a`, exporting `b.IPerson` is fine.
export function wrapFindPersonById(id: number): b.IPerson {
  return b.findPersonById(123);
}
```

Using `1.8.0-dev.20151204`. Full repo https://github.com/Deathspike/typescript-reference-bug-example/

### LINKED ISSUE #8612: “cannot be named” when generating declarations for re-exported classes
**TypeScript Version:** 

1.8.10 / nightly (1.9.0-dev.20160515)

**Code**

```ts
// file ThingA.ts
export class ThingA { } 

// file ThingB.ts
export class ThingB { }

// file Things.ts (re-export)
export {ThingA} from "./ThingA";
export {ThingB} from "./ThingB";

// file Test.ts (uses re-exported classes)
import * as things from "./Things";

export class Test {
    public method = (input: things.ThingA)  => { };
}

// compile
tsc Test.ts --declaration --outDir compiled

```

**Expected behavior:**
No errors
**Actual behavior:** 
> Test.ts(5,5): error TS4029: Public property 'method' of exported class has or is using name 'ThingA' from external module ".../ThingA" but cannot be named.

It seems declaration file can't be generated due to the `things.ThingA` reference, but in a similar case without re-exporting it works fine (I will give an example of this in the next post). 

If I change the import statement in Test.ts to this:
```ts
import {ThingA,ThingB} from "./Things";
```
(instead of `import * as things`) and further use `ThingA` directly, there are no errors, but this defeats the purpose of re-exporting.

### LINKED ISSUE #19825: Declaration emit for aliased exports used in export assignments is broken
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
// @declaration: true
// @filename: /a.ts
class C {}
export { C as D }

// @filename: /b.ts
import * as a from "./a";
export default a.D;

```

**Expected behavior:**
```ts
// /a.d.ts
declare class C {}
export { C as D }
// /b.d.ts 
import * as a from "./a";
declare const _default: typeof a.D;
export default _default;
```

**Actual behavior:**
```ts
/b.ts(2,1): error TS4082: Default export of the module has or is using private name 'default'.


==== /a.ts (0 errors) ====
    class C {}
    export { C as D }
    
==== /b.ts (1 errors) ====
    import * as a from "./a";
    export default a.D;
    ~~~~~~~~~~~~~~~~~~~
!!! error TS4082: Default export of the module has or is using private name 'default'.
```

I think #19428 may have been an indicator of a larger issue, and the fix applied for it may have been too narrow (or it may be unrelated, haven't run a bisect yet). I've been having issues merging the fix into the symbol display builder PR (since it either fixes the observed bug and breaks all the type/symbol baselines or doesn't fix the bug, depending on how I merge it), so to track down how to implement the fix in the node builder instead of the symbol display builder I started looking for similar cases to see how we behave and found this.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #19825
Fixes #8612
Fixes #5938

This was actually broken waaaaaay back in TS 1.6 by #3641; the real underlying issue which prompted that change has since been fixed by other changes, so all this line did was break things. 😄

### CODE REVIEW

**Comment by mhegazy** [comment]
@weswigham does this address https://github.com/Microsoft/TypeScript/issues/8612 as well?

**Comment by weswigham** [comment]
@mhegazy Yes. Yes it does. Added repro.

**Comment by mhegazy** [comment]
and https://github.com/Microsoft/TypeScript/issues/5938 probably

**Comment by weswigham** [comment]
Yup. We've had this bug for a long time, haven't we?

**Comment by mhegazy** [comment]
yes we did.

**Comment by mhegazy** [comment]
i guess i am to blame for that one 😊

**Comment by lukeshiru** [comment]
Great work guys! Thanks!

**Comment by jacobbogers** [comment]
Great, if i install tsc in the project, not globally, the newest it will compile; but vscode editor still marks it as an error,  maybe unrelated but its not picking up the new tsc? (globally de-installed tsc, so its only using the tsc of the project, me thinks)

**Comment by weswigham** [comment]
vscode has a copy of TS bundled with it. There's a workspace setting you can use to tell it to use the workspace certain instead.

**Comment by mhegazy** [comment]
Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.

**Comment by jamiewinder** [comment]
I was hoping this was meant to fix a long-time bugbear of mine; I cannot using declarations with modules that export styled-component components.

For example, this very basic, very common scenario:
```typescript
import styled from "styled-components";

export const Test = styled.div`
    color: black;
`;
```
i.e. just exporting a styled component, won't work because:
```bash
[ts] Exported variable 'Test' has or is using name 'React.ClassAttributes' from external module "node_modules/@types/react/index" but cannot be named.
[ts] Exported variable 'Test' has or is using name 'React.HTMLAttributes' from external module "node_modules/@types/react/index" but cannot be named.
[ts] Exported variable 'Test' has or is using name 'StyledComponentClass' from external module "node_modules/styled-components/typings/styled-components" but cannot be named.
```
Was this meant to fix this scenario? Because with 2.7.0-dev.20180103 I still get the same.

**Comment by weswigham** [comment]
No, that'd be related to #9944. For now you should be adding imports/references to the files whose types you need to use in your own declaration output, for now. For example,
```ts
import {StyledComponentClass}, styled from "styled-components";
import * as React from "react";

export const Test = styled.div`
    color: black;
`;
```

**Comment by jamiewinder** [comment]
OK, thanks. Unfortunately that approach doesn't work with `--noUnusedLocals` as you have to refer to the import at least once (which can force in somewhere, but it's messy). 

Thanks for clarifying.

**Pull request merged**
