### PR TITLE
Add a recurse checker to isRelatedTo to handle infinite loops 

### PR DESCRIPTION
**Pull request by orta**
This adds a check for how often `relatedTo` gets called, which is what is happening in #35804 

The recursion in 35804 occurs when an intersection is a being validated for common properties, this is the stack:

```sh
      at isPropertySymbolTypeRelated (src/compiler/checker.ts:16080:28)
      at propertyRelatedTo (src/compiler/checker.ts:16126:33)
      at propertiesRelatedTo (src/compiler/checker.ts:16265:45)
      at isRelatedTo (src/compiler/checker.ts:15128:34)
      at isPropertySymbolTypeRelated (src/compiler/checker.ts:16080:28)
```

The `this` keeps it recursing as it checks against the subtypes infinitely

250 as a limit is kind of an arbitrary number, I'm open to making it smaller (50 is the depth limit of `constraintDepth` for example) 

Interestingly, this also seems to improve the typing in the case of a very long union, where instead of an `any` - it's hitting the relatedTo depth limit and returning a type instead which is a free win I guess.

### CODE REVIEW

**Comment by weswigham** [comment]
`recursiveTypeRelatedTo` handles this already - any type structure which *could* be infinitely recursive is meant to go through that at some point.

**Comment by orta** [comment]
Switching to straight up use `recursiveTypeRelatedTo` instead of `isRelatedTo` [here](https://sourcegraph.com/github.com/microsoft/TypeScript@dbef230eb84d9bd6de539400de9ee4b9295a09e4/-/blob/src/compiler/checker.ts#L15604) ends failing a few thousand tests (while correctly passing the one I added ^_^) 

I think I need a way to extend [this if statement](https://sourcegraph.com/github.com/microsoft/TypeScript@dbef230eb84d9bd6de539400de9ee4b9295a09e4/-/blob/src/compiler/checker.ts#L15568) with a new else cause which checks for an interface with `: this` references - does that feel reasonable?

**Comment by ahejlsberg** [comment]
This isn't quite the right way to fix this issue. I'm going to put up a new PR.

**Comment by sandersn** [comment]
Looks like we took #37360 instead of this.

**Pull request closed without merging**
