### PR TITLE
Support for the ECMAScript 'throw' operator

### PR DESCRIPTION
**Pull request by rbuckton**
This PR adds support for the stage-2 ECMAScript 'throw' operator: https://github.com/tc39/proposal-throw-expressions.

NOTE: This feature does not yet support reachability checks at the expression level (e.g. in `(throw x), y`, `y` should be considered unreachable). I can investigate this either as part of this PR or (preferably) in a follow-up PR. Our current reachability algorithm does not work well with expressions and will require some further investigation to make it more robust.

Fixes: #18535

### CODE REVIEW

**Comment by weswigham** [comment]
@rbuckton Can you include a link to the ECMAScript proposal in the OP, for posterity?

**Comment by rbuckton** [comment]
@weswigham, I've updated the description. I was waiting on the transfer of the proposal repository to the tc39 organization.

**Comment by weswigham** [comment]
:+1:

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by rbuckton** [comment]
I'm going to add an `--experimentalThrowExpressions` option before this is merged.

**Comment by mhegazy** [comment]
Based on today's discussion (#18895), we want to hold off on this untill  it makes stage 3, then include it without a flag.

**Comment by mihailik** [comment]
Are there plans for a similar `try` expression?

```typescript
const _crypto = try { require('crypto') } catch { }
```

**Comment by plantain-00** [comment]
@mihailik 
need to propose it tc39 first https://github.com/tc39/proposals

**Comment by mihailik** [comment]
@plantain-00 not really, in fact it often goes in the opposite direction.

**Comment by Kovensky** [comment]
@mihailik nope, that is exactly how it is supposed to be done -- via TC39. TypeScript is not adding any additional syntax that is not being tracked by TC39, besides the current syntax that is being grandfathered in (as, namespace, enum) and JSX.

**Pull request closed without merging**
