### PR TITLE
Do not send first missing file event as well, Do not close typing installers watches just to recreate them

### LINKED ISSUE #22581: TSSERVER: import {…} from '//some/path' chokes tsserver/code (overloads CPU)
**TypeScript Version(s):**  2.7.0-rc 2.7.2 2.8.0-dev***

**Search Terms:** tsserver overloads ………………………

**Code**

```ts
// helpers.m.js
export { html, render } from '//node_modules/lit-html/lib/lit-extended.js';
```

**Expected behavior:**

Resolve at best, report issue at worse.

**Actual behavior:**

VS Code's tsserver sub process overloads CPU (sometimes 101% whatever that is)

**Workaround:**

This makes VS Code happy, but makes the code less compatible with requirements.

```ts
// helpers.m.js
export { html, render } from '/node_modules/lit-html/lib/lit-extended.js';
```

**Playground Link:**  

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/21274

### PR DESCRIPTION
**Pull request by sheetalkamat**
Handling as per https://github.com/Microsoft/TypeScript/pull/22496#issuecomment-372787915

Fixes #22581

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@amcasey can you please take a look. Thanks

**Comment by amcasey** [comment]
The missing file event part looks correct.  I haven't had a chance to read the TI bit yet.

**Comment by RyanCavanaugh** [comment]
What was the root cause of the bug? The code looks correct but the important behavioral difference between it and the old version isn't obvious.

**Comment by sheetalkamat** [comment]
There were two causes
1: The delete event was sent on first invoke from the fileWatcher of missing files.  (which we shouldnt)
2. Whenever the files are invalidated, we close all existing watches and create new watches which is expensive.. (it would be same list of files) which is what happens without the fix (since deleted is sent on first poll, invalidating the project, resulting in creating new install request which closes existing watch and sets new watcher which again sends file deleted event)

**Comment by sheetalkamat** [comment]
@RyanCavanaugh does that answer your question, Is it ready to merge. I would like to get this in tonights nightly. Thanks

**Pull request merged**
