### PR TITLE
Always create optional properties when spreading objects conditionally

### LINKED ISSUE #40754: Repeated conditional spreading of object literals results in OOM
**TypeScript Version:**  nightly (fc03982b73ebaabfdfd2ef25bc1538e86a635b7b)

**Search Terms:** spread, union, oom

**Playground Link:** [link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF0S4AueASuEjMADwoCuAtgEYgwA08tSSEIUKAfANwCwAKCEAzSijAYAlqngiAFAEoA3kPjr4Aek3wAKgE8ADgilp4UeOJkp4SEfABMAPXkoAtAEZF8aiDoM0ZgB3AAsGBBtTeAww+Cp-GFt7NEM4KGBbWgArcAw0NQ04DEoYG1VBDUqtHQB1KRikSiwYqNQQZnrEdmhDNBAzDCR4ZQBfeAB+Aqr4ADo5+TAcAG0PAF14ADINqemNReAlh3Wt4Z3d+FSkQwAGfGvGM40RxQfhCt3teDqY2xQES8M8E4YBCHSwyAgPT6AyGFjQUhQAHMOJkcpJ4PIAMQAZgALAAOACs2PGike6jmMwWy2xxw2p3e53UAOxUHwHleTI0LNo7M5u2e-OmlOpB1xdIZXOZMCuuLZ8A55KqANxvIVQqqgqVIv2S0JEvKUouMsMhPlisZTIBhLVFvOWstlR1ywAbAalZUAS7zRrzl7bb6ni9tfNdQB2d2O3YAsM+j3ck1hgNKh3nZ0HfGRo0A-FxqPTHPJ-PwVO7dNLACcWalAIreezJorRftweL5Y812rXIBHfrNZNHebAtbadDyw8a029MN-auE773YHHiH01LwrHBw8Rynktnhi3C6tA4cK81I7LG5WtJ3M8Xc9ZfPj0vvp8qa6q7fFN6fxrncsfxaegOqoAS2gYUpeHj6t+gEJnOZqgXuUGvkG4GzJBbowQ2c7eohd77i6KHqO+TqQRGWFIbGeFHnOSbUW+57rlSuoeJmFH4axh5+gO+JESWjEfpBVbsTR+51vR0YDk2EnEQJpHMcsDidiJ3FXEpXGSWp1x8SRGifOWDiTicyjVPAABiUgwJg8AAPI2QAsswEBIGAUCQvoSqfEBakeBp6heXBhiGXxny6f5OgGduxmeTo3lBQ4fmmXFDgnjJplhaZBnXtFxYBc+QUPuqMXKiaDjYiFOgZfpl4OF+OXnHlv5Bf+RW5bFgW1RV-FodVCkHA40H1R87X5QNiWNQCA1dVVEU1ZhQ3TBNpW4a1DUjU1DiEWloVyXps19Yc5ELVUS1qVRq3DSVZ3Tbt4XoQdDhscdlSnUFubbetk28R93XFQZwnPXtV1BeJF2LZ9pXSWDJ2VbdmWXtiymA3dcWI+NENXIjN09ftopLNiRnTsVqO+T9JPY39CNRUTbXA9iCVk4F9MU7T5bYtlNNrXThV2pdqPlT9M33XjeJdjDdMtbz4MSyzXNs4NnN80zCHQy9GOGNiNqC3DvUi-NivS6jK1S+LRuy5dbNHQbptM+dJtq3TdGq0DQts091sO6j73OyjTPfT76U67jurYgDHtA6joP2xHTNQ9Hd0OsVADCYRgAA1giiLwJgUD6GYIKcIC4jSBA0RhHAADkZgWH8mAgBkSDZLkydINZUCGMYsAwvAiIykE8AQAinAwBA+jwEE9QhGXEQ0PQiR2NP1DFQAogAHhgMAWKAhg-OkwD563GDMLQTTmB3sAgCgGCjwP-QDCEXAD0PsCjyGB0dkj4cFgOK23kaTUeG9B4dkP4RhoTioAviDsewujAPgP+XMIGwOAQHB2YCUwCRGAIQQIwgA)

**Related Issues:** #34853 addressed a related issue

An internal partner team is using this to conditionally override CSS properties (e.g. `...sizeLimited && { width: 100, height: 100 }` and is seeing OOM crashes in tsc and poor editor responsiveness.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #40754

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot test this
@typescript-bot perf test this

**Comment by amcasey** [comment]
Looks good in the project that inspired the bug.

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Review by ahejlsberg — APPROVED** [review]

**Comment by weswigham** [comment]
Do we want this in 4.1 or in 4.2?

**Comment by ahejlsberg** [comment]
I vote 4.1.

**Comment by amcasey** [comment]
FWIW, the [design notes](https://github.com/microsoft/TypeScript/issues/40779) suggested we settled on 4.2.

**Comment by weswigham** [comment]
Nobody seemed to suggest to moving this to 4.1 in today's standup, so I'm assuming I should do so.

**Pull request merged**
