### PR TITLE
Infer type parameters only from applicable contextual types

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/50719

### CODE REVIEW

**Comment by Andarist** [comment]
I failed the self-check without failing the test suite for the second time. 🍻 for the life achievements

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Check time performance and baselines don't seem to look good, unfortunately.

**Comment by Andarist** [comment]
@jakebailey I've pushed out a change - there is something funky in its 2 baseline changes but for now, I'd like to just learn its perf characteristics. Would you mind re-running the perf test suite?

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Pull request closed without merging**
