### PR TITLE
Covariant checking for callback parameters

### LINKED ISSUE #11022: Generic parameter inference for Promise.then oddity
**TypeScript Version:**  1.8.0 / nightly (2.0.5-dev.20160919)

**Code**

``` ts
interface Thenable<T> {
  then<U>(then: (value: T) => U | Thenable<U>): Thenable<U>;
}

declare let x: Thenable<string>;
declare function f(): Thenable<string|null>|null;
declare function g(): Thenable<string>;

let y = x.then((_) => {
  if (Math.random() < 0.5) {
    return f();
  } else {
    return g();
  }
});
```

**Expected behavior:**
`U` should be inferred to be `string | null` as that solves the type constraints. It can be verified by explicitly adding `then<string | null>.(...)` which type checks.

**Actual behavior:** 
TS errors with `Argument of type '(_: string) => Thenable<string> | null' is not assignable to parameter of type '(value: string) => string | Thenable<string>'.`

**Oddities:**
The following changes make the error disappear, while I expect them to have no relevance to the type of the closure:
- moving line 5 to line 8 - `declare let x` below `declare function f` and `g`.
- change of the type of x to `Thenable<number>`.
- add a field of type T to Thenable - `a: T`, that would make `Thenable` strictly covariant.
- replace with ternary expression - `(_) => (Math.random() < 0.5) ? f() : g()`

### LINKED ISSUE #14770: Generic parameters not fully type-checked (e.g., Promise)
**TypeScript Version:**  2.2.1

**Code**

```ts
const a: Promise<{ foo: 'bar' }> = Promise.resolve({ foo: 'typo' });
const b: Promise<{ foo: 'bar' }> = Promise.resolve({});
```

**Expected behavior:**

- `a` should type-check: it constrains `foo` to `'bar'` but is given `'typo'`.
- `b` should type-check: it requires `foo` but is given an object without `foo`.

**Actual behavior:**

Neither type-check.

The same types check fine when resolved directly:

```ts
// Type '{ foo: "typo"; }' is not assignable to type '{ foo: "bar"; }'.
//   Types of property 'foo' are incompatible.
//     Type '"typo"' is not assignable to type '"bar"'.
const a: { foo: 'bar' } = { foo: 'typo' });

// Type '{}' is not assignable to type '{ foo: "bar"; }'.
//   Property 'foo' is missing in type '{}'.
const b: { foo: 'bar' } = {};
```

Generic parameter type checks fail for objects/types of different shapes:

```ts
// Type 'Promise<{ foo: string; bar: string; }>' is not assignable to type 'Promise<{ foo: "bar"; }>'.
//   Type '{ foo: string; bar: string; }' is not assignable to type '{ foo: "bar"; }'.
//     Types of property 'foo' are incompatible.
//       Type 'string' is not assignable to type '"bar"'.
const a: Promise<{ foo: 'bar' }> = Promise.resolve({ foo: 'bar', bar: 'baz' });

// Type 'Promise<number>' is not assignable to type 'Promise<{ foo: "bar"; }>'.
//   Type 'number' is not assignable to type '{ foo: "bar"; }'.
const b: Promise<{ foo: 'bar' }> = Promise.resolve(1);
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
In order to ensure that any generic type `Foo<T>` is at least co-variant with respect to `T` no matter how `Foo` uses `T`, TypeScript relates parameters bi-variantly (given that parameters are input positions, they naturally relate only contra-variantly). However, when source and target parameters both have function types with a single call signature, we known we are relating two callback parameters. In that case it is sufficient to only relate the parameters of the signatures co-variantly because, similar to return values, callback parameters are output positions. With this PR we introduce that change. This means that a `Promise<T>` or `Observable<T>`, where `T` is used only in callback parameter positions, will be co-variant (as opposed to bi-variant) with respect to `T`, which solves a commonly reported issue.

This change finds several issues in our real world code suites that all appear to be legitimate  inconsistencies.

Fixes #11022.
Fixes #14770.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@mhegazy Want to take a look?

**Comment by ShawnTalbert** [comment]
is it too late to suggest Scala's +/- notation rather than C#'s in/out?

**Comment by acutmore** [comment]
@ShawnTalbert If not clear. This PR does not introduce any new syntax. Instead changes type assignability of generics where the type is only user in a function parameter position e.g Promise / Observable

```typescript
interface Box<T1> {
   foo(cb: (t: T1 => void)): void;
}
```

Before:

```typescript
declare const pA: Box<Animal>;
const p: Box<Cat> = pA; // no error 😿 
```

After:

```typescript
declare const pA: Box<Animal>;
const p: Box<Cat> = pA; // error 😺 
```

**Comment by ShawnTalbert** [comment]
Yes, wrong issue, sorry

**Comment by bmcbarron** [comment]
It appears that the solution was amended to ignore union with null/undefined. Should that be dependent on --strictNullChecks? At the moment, this does not seem to address #13513.

**Comment by ahejlsberg** [comment]
@bmcbarron #13513 is fixed by this PR in `--strictNullChecks` mode. Without `--strictNullChecks`, `undefined` is assignable to any type and is effectively ignored in union types, but has always been the case and isn't going to change.

**Comment by schotime** [comment]
This doesn't fix this problem unfortunately and this is usually the case if the callbacks are stored in different files and imported.

```
class Animal {}
class Cat extends Animal {
    public meow() {}
}

let promise: Promise<Animal> = null;
promise.then((cat: Cat) => { //Should error here but does not
  cat.meow();
});
```

**Pull request merged**
