### PR TITLE
Make preProcessFile public again

### PR DESCRIPTION
**Pull request by rbuckton**
The change in #10753 breaks `gulp-tsb` as it depends on the publicly exported `preProcessFile` function which was moved and marked internal. This change removes the `PreProcess` namespace and the `/* @internal */` marker from `src/services/preProcess.ts`.

### CODE REVIEW

**Comment by rbuckton** [comment]
@andy-ms, @mhegazy can you take a look?

**Comment by mhegazy** [comment]
Thanks. Can you do that for classifier and transpil as well. I think they got hidden in the move.

**Comment by mhegazy** [comment]
:+1:

**Comment by rbuckton** [comment]
The classifier is definitely broken, though transpile looks fine. I'll amend this PR with the same fix for classifier as well.

**Pull request merged**
