### PR TITLE
Use more universal ANSI sequence for 'clear screen and clear buffer'

### LINKED ISSUE #29829: compiler, when it watch mode, resets the screen colors
**TypeScript Version:**  3.4.0-dev.20190208

**Search Terms:** terminal, watcher

**Issue**

I'm using linux, and I have a custom terminal theme (I'm using [powerlevel-9k](https://github.com/bhilburn/powerlevel9k)). To make it look more pleasing, I tuned the terminal colors, but I did that through tput commands in my .zshrc:

```
tput initc 0 172 196 200
tput initc 1 800 210 100
tput initc 2 220 560 220
tput initc 3 800 460 180
tput initc 4 350 530 670
tput initc 5 630 380 470
tput initc 6 470 710 760
tput initc 7 810 810 810
tput initc 8 570 570 570
tput initc 9 1000 280 200
tput initc 10 720 710 0
tput initc 11 1000 780 430
tput initc 12 530 760 1000
tput initc 13 820 820 1000
tput initc 14 440 760 830
tput initc 15 910 910 910
```
I am loosing these customizations if I run typescript's compiler tsc in watch mode (tsc -w) and exit it through ctrl-c. When returning to the shell after that, the colors are the original ones, as if the tput commands were never executed. So it seems `tsc -w` is sending a too drastic reset command to the terminal, which does not only erase `tsc`'s output but can also discard some user's customizations to their terminal.

Notice that the issue occurs with the `xterm` and `kitty` terminals, but NOT with `gnome-terminal`, which seems to be a `gnome-terminal` or `vte` bug (see [kitty bug](https://github.com/kovidgoyal/kitty/issues/1367) and [vte bug](https://gitlab.gnome.org/GNOME/vte/issues/91)).

**Expected behavior:**
Running and exiting `tsc -w` shouldn't discard my color customizations to my terminal.

**Actual behavior:**
Running and exiting `tsc -w` discards my color customizations to my terminal.

Note that when searching if that bug was already reported, I stumbled upon the `--preserveWatchOutput` flag and I can confirm that when this flag is enabled, the issue is NOT present.

### LINKED ISSUE #57700: `tsc --watch` uses "incomplete" ANSI sequence for "clear buffer"
### 🔎 Search Terms

ansi, terminal, watch, reset

### 🕗 Version & Regression Information

I run `tsc --watch` in an iTerm2 terminal window for whatever project I'm working on, and I've been patching `tsc` for a long time, and finally decided to bring this before the team.

Checking the log, looks like this ANSI sequence (`x1Bc`) was committed via 08c6dc99 on Dec 2, 2017. 

`echo -e "\x1Bc"` *does* clear the screen, but the behaviour is not exactly well defined. In iTerm2, in particular, it pushes the scroll buffer off screen, but preserves it (you can scroll up to view the content).

`echo -e "\x1Bc\x1B[3J"` OTOH clears the screen *and explicitly clears the scroll buffer*, which I think is the desired behaviour.

### ⏯ Playground Link

N/A

### 💻 Code

```ts
clearScreen: () => {
    process.stdout.write("\x1Bc");
},
```

### 🙁 Actual behavior

In _VSCode and Terminal_, this sequence clears the screen and scroll buffer. In iTerm2 (and who knows where else – in searching for other examples, it's clear that other people *also* use this sequence, but I don't know which OSes)

### 🙂 Expected behavior

I expect `tsc --watch` to clear the terminal *and scroll history* in all terminals.

### Additional information about the issue

_No response_

### LINKED ISSUE #57894: `tsc --watch` changes shell's current directory to ~ in Terminal.app while running
### 🔎 Search Terms

watch current directory

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it's too much work

### ⏯ Playground Link

_No response_

### 💻 Code

```sh
tsc --watch -p ./
```

### 🙁 Actual behavior

When running the above command in macOS's Terminal.app and pressing Cmd+t to open a new shell it opens a new shell at my home directory

### 🙂 Expected behavior

Terminal.app should open the new shell in the same directory that I ran the command from.

### Additional information about the issue

```
webpack --watch
```

works the way I expect.

### PR DESCRIPTION
**Pull request by colinta**
Fixes #57700
Fixes #29829
Fixes #57894
Closes #59315

Tiny tiny patch to bring just a little more terminal support to `tsc --watch`. In my case, iTerm2 needs this `ESC [ 3J` sequence in order to clear screen _and remove scroll history_.

If there's a setting in iTerm2 to change this, I would happily do that, but I didn't see anything.

```
  92049 passing (6m)

Finished do-runtests-parallel in 6m 22.9s
Completed runtests-parallel in 6m 57.3s
✨  Done in 417.81s.
```

### CODE REVIEW

**Comment by mrazauskas** [comment]
For what it’s worth, the [`ansi-escapes`](https://github.com/sindresorhus/ansi-escapes) library has two similarly named methods: `clearScreen()` and `clearTerminal()`.

`clearScreen()` is the same as current `tsc --watch` implementation.

`clearTerminal()` is [more complex](https://github.com/sindresorhus/ansi-escapes/blob/8becab6761d767b90a34ec3d8792b3a8137fa845/index.js#L92-L98) and it is based on Jest's implementation (see https://github.com/sindresorhus/ansi-escapes/pull/6 and https://github.com/jestjs/jest/blob/6b120fbc5d1cadb3ef205bd1d48549155bed5dd1/packages/jest-util/src/specialChars.ts#L18-L20)

I am pointing to `ansi-escapes`, because it is rather widely used. Not sure if there are any standards in this field.

**Comment by jakebailey** [comment]
If we're going to do this, I'm somewhat inclined to take the more popular approach of using the same sequence that ansi-escapes/jest take, though that appears to be platform specific which may make our tests unhappy.

**Comment by colinta** [comment]
I wonder if we even need to make a distinction between mac and windows
```sh
echo -n -e "\u001B[2J\u001B[3J\u001B[H\u001B[0f"
```
Works on all my terminals (Terminal, iTerm, & VSCode). I don't have a Windows machine to test on, though.

**Comment by colinta** [comment]
The passage of time made me forget the ANSI sequence I had settled on, but I remembered this morning and updated this PR _one more time_.

So, the sequence in there is based on the one from ansi-sequences. It's just a combination of the two, without the OS check.

**Comment by jakebailey** [comment]
I believe that this also fixes #29829 (which I found via people commenting duplicates on the related issues to this PR's).

Planning on doing some local testing, though, it's just a lot of terminal emulators to test...

If we are doing this, I hope nobody relies on our specific escape sequence. I think not, but rather they depend on other watch messages.

**Comment by jakebailey** [comment]
I did some testing of this PR and #59315.

old behavior:

- linux, wsl vscode: can't scroll up ✅
- linux, wsl terminal: can't scroll up ✅
- linux, foot: can't scroll up ✅
- linux, tilix (vte): can't scroll up ✅
- windows 11, vscode, pwsh: can't scroll up ✅ 
- windows 11, terminal, pwsh: can't scroll up ✅
- windows 11, terminal, cmd: can't scroll up ✅
- windows 11, console host, cmd: can't scroll up ✅
- macos, kitty: can't scroll up ✅
- macos, terminal: *can scroll up* ❌
- macos, iterm: *can scroll up* ❌

We emit `0x1Bc`, causing #57894.


#57701

- linux, wsl vscode: can't scroll up ✅
- linux, wsl terminal: can't scroll up ✅
- linux, foot: can't scroll up ✅
- linux, tilix (vte): can't scroll up ✅
- windows 11, vscode, pwsh: can't scroll up ✅ 
- windows 11, terminal, pwsh: can't scroll up ✅
- windows 11, terminal, cmd: can't scroll up ✅
- windows 11, console host, cmd: can't scroll up ✅
- macos, kitty: can't scroll up ✅
- macos, terminal: *(changed) can't scroll up* ✅
- macos, iterm: *(changed) iterm asks for permission to clear screen, then can't scroll up* ✅

No `0x1Bc`, so should fix #57894.

#59315

- linux, wsl vscode: can't scroll up ✅
- linux, wsl terminal: can't scroll up ✅
- linux, foot: can't scroll up ✅
- linux, tilix (vte): can't scroll up ✅
- windows 11, vscode, pwsh: can't scroll up ✅ 
- windows 11, terminal, pwsh: *can scroll up* ❌
- windows 11, terminal, cmd: *can scroll up* ❌
- windows 11, console host, cmd: *can scroll up* ❌
- macos, kitty: can't scroll up ✅
- macos, terminal: can't scroll up ✅
- macos, terminal: *(changed) can't scroll up* ✅
- macos, iterm: *(changed) iterm asks for permission to clear screen, then can't scroll up* ✅3

No `0x1Bc`, so should fix #57894.

---

I have not tested on something like Windows 10 with cmd, though; but I'm fairly confident that this PR is good.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Using this launch task in our repo:

```
        {
            "label": "tsc: watch ./src with built",
            "type": "shell",
            "command": "node",
            "args": ["${workspaceFolder}/built/local/tsc.js", "--build", "${workspaceFolder}/src", "--watch"],
            "group": "build",
            "isBackground": true,
            "problemMatcher": [
                "$tsc-watch"
            ]
        },
```

Shows that the problem matcher in VS Code also works fine:

image

image

Then undo the bad code:

image

**Comment by mrazauskas** [comment]
Out of curiosity: what if `\u001B[2J\u001B[3J\u001B[H` is always emitted regardless of platform? Seemed like it is not covered in https://github.com/microsoft/TypeScript/pull/57701#issuecomment-2243607183. Or I misunderstood?

**Comment by jakebailey** [comment]
That's exactly what this PR does, if I'm understanding you correctly.

```diff ts
diff --git a/src/compiler/sys.ts b/src/compiler/sys.ts
index 32d7af09c03e7..cf9318afdd199 100644
--- a/src/compiler/sys.ts
+++ b/src/compiler/sys.ts
@@ -1619,7 +1619,7 @@ export let sys: System = (() => {
             setTimeout,
             clearTimeout,
             clearScreen: () => {
-                process.stdout.write("\x1Bc");
+                process.stdout.write("\x1B[2J\x1B[3J\x1BH\x1B[0f");
             },
             setBlocking: () => {
                 const handle = (process.stdout as any)?._handle as { setBlocking?: (value: boolean) => void; };
```

**Comment by mrazauskas** [comment]
> That's exactly what this PR does, if I'm understanding you correctly.

Almost. I am suggesting to skip `\x1B[0f`.

**Comment by jakebailey** [comment]
I can test that, but what effect are you trying to get by omitting that?

**Comment by jakebailey** [comment]
Tested, and omitting that seems to leave a bunch of space above the log, not actually clearing the screen. So it seems to be required.

**Comment by mrazauskas** [comment]
Thanks. That’s interesting. I thought that `\x1BH` and `\x1B[0f` both do the same thing. Only testing can proof that.

**Comment by mrazauskas** [comment]
Sorry, me again. Seems like `\x1BH` is missing `[` in this PR, but has it in #59315. Shouldn’t it read `\x1B[H`?

**Comment by ehoogeveen-medweb** [comment]
If I'm reading [this](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#tabs) correctly, `\x1BH` sets a horizontal tab stop whereas [`\x1B[H`](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#cursor-keys) sets the cursor to home and [`\x1B[0f`](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#cursor-positioning) moves the cursor to a particular position in the viewport (it seems to take 2 coordinates so I'm not sure what only providing 1 implies).

**Comment by ehoogeveen-medweb** [comment]
To add to the above, `\x1B[3J` should do nothing according to [this](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-modification) as `3` is not a valid value for `<n>`. So technically the following should both be equivalent and sufficient:
* `\x1B[2J\x1B[H`
* `\x1B[2J\x1B[f`

But maybe there are differences between terminals that mean you need more.

**Comment by jakebailey** [comment]
I'm going through all of the combos now (fixing the potential typo, trying those two shorter sequences).

**Comment by ehoogeveen-medweb** [comment]
Ah, that page is incomplete - `3J` indeed clears the scrollback, as commented [here](https://learn.microsoft.com/en-us/windows/console/clearing-the-screen) (and probably in other places). So you do need both:
* `\x1B[2J\x1B[3J\x1B[H`
* `\x1B[2J\x1B[3J\x1B[f`

**Comment by ehoogeveen-medweb** [comment]
According to [this](https://vt100.net/docs/vt510-rm/HVP.html), `CUP` (`\x1B[H` here) should be preferred over `HVP` (`\x1B[f` here) for "new applications". Either way they should be equivalent :)

**Comment by jakebailey** [comment]
#57701 but with `\x1B[H`

- linux, wsl vscode: can't scroll up ✅
- linux, wsl terminal: can't scroll up ✅
- linux, foot: can't scroll up ✅
- linux, tilix (vte): can't scroll up ✅
- windows 11, vscode, pwsh: can't scroll up ✅
- windows 11, terminal, pwsh: can't scroll up ✅
- windows 11, terminal, cmd: can't scroll up ✅
- windows 11, console host, cmd: can't scroll up ✅
- macos, kitty: can't scroll up ✅
- macos, terminal: can't scroll up ✅
- macos, iterm: can't scroll up ✅


Just `\x1B[2J\x1B[3J\x1B[H`

- linux, wsl vscode: can't scroll up ✅
- linux, wsl terminal: can't scroll up ✅
- linux, foot: can't scroll up ✅
- linux, tilix (vte): can't scroll up ✅
- windows 11, vscode, pwsh: can't scroll up ✅
- windows 11, terminal, pwsh: can't scroll up ✅
- windows 11, terminal, cmd: can't scroll up ✅
- windows 11, console host, cmd: can't scroll up ✅
- macos, kitty: can't scroll up ✅
- macos, terminal: can't scroll up ✅
- macos, iterm: can't scroll up ✅


Just `\x1B[2J\x1B[3J\x1B[f`

- linux, wsl vscode: can't scroll up ✅
- linux, wsl terminal: can't scroll up ✅
- linux, foot: can't scroll up ✅
- linux, tilix (vte): can't scroll up ✅
- windows 11, vscode, pwsh: can't scroll up ✅
- windows 11, terminal, pwsh: can't scroll up ✅
- windows 11, terminal, cmd: can't scroll up ✅
- windows 11, console host, cmd: can't scroll up ✅
- macos, kitty: can't scroll up ✅
- macos, terminal: can't scroll up ✅
- macos, iterm: can't scroll up ✅


However, not including `H` or `f` causes extra empty lines to be printed, so one of those must be present.

**Comment by jakebailey** [comment]
> According to [this](https://vt100.net/docs/vt510-rm/HVP.html), `CUP` (`\x1B[H` here) should be preferred over `HVP` (`\x1B[f` here) for "new applications". Either way they should be equivalent :)

That was the next question, which one to choose! Seems like we should be good with `\x1B[2J\x1B[3J\x1B[H`. Likely, the current PR only works because the typo didn't matter due to `[f`.

**Comment by ehoogeveen-medweb** [comment]
For completeness:
* The old sequence `\x1Bc` (`ESC c`) was [`RIS`](https://vt100.net/docs/vt510-rm/RIS.html) (Reset to Initial State)
* The new sequence `\x1B[2J` `\x1B[3J` `\x1B[H` (`CSI 2 J` `CSI 3 J` `CSI H`) is two [`ED`](https://vt100.net/docs/vt510-rm/ED.html) (Erase in Display) sequences followed by a [`CUP`](https://vt100.net/docs/vt510-rm/CUP.html) (Cursor Position) sequence
* Of these, `CSI 3 J` to clear scrollback is something that wasn't supported on the VT510 but was added as an extension to xterm and adopted by other terminals; see e.g. [here](https://www.xfree86.org/current/ctlseqs.html) (Erase Saved Lines)

**Pull request merged**
