### PR TITLE
[experiment] Naively make normalizeSlashes a no-op outside of Windows

### PR DESCRIPTION
**Pull request by jakebailey**
For #44174.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot test this

**Comment by jakebailey** [comment]
@typescript-bot test this

**Comment by jakebailey** [comment]
@typescript-bot test this

**Comment by jakebailey** [comment]
@typescript-bot test this

**Comment by dmichon-msft** [comment]
What OS does the perf suite run on?
Also, do you know what's causing that implausibly large impact on the Monaco and TFS test suites?

**Comment by jakebailey** [comment]
OS is Linux, a recent version of Ubuntu, which is the OS we'd want to test for this kind of change.

The implausible perf change is from those projects using the wrong kinds of slashes, e.g. monaco has a file like this:

```ts
/// <reference path="lib.d.ts" />
/// <reference path="client\extlib.d.ts" />
/// <reference path="client\vs\base\arrays.ts" />
/// <reference path="client\vs\base\assert.ts" />
/// <reference path="client\vs\base\async.ts" />
/// <reference path="client\vs\base\cookiesUtil.ts" />
/// <reference path="client\vs\base\diagnostics.ts" />
/// <reference path="client\vs\base\env.ts" />
// ...
```

So it's not actually type checking these files because it didn't find them. And, this is also the sort of thing we probably don't want to be breaking.

**Comment by ehoogeveen-medweb** [comment]
I'm a bit surprised that works at all. For example, I'd expect `client\vs\base\arrays.ts` to be interpreted as `client\u000bs\u0008asearrays.ts` or similar.

**Comment by jakebailey** [comment]
I'm not super surprised given those comments are effectively XML which has different escape rules.

But, I also doubt anyone is using these slashes in real codebases these days either.

**Pull request closed without merging**
