### PR TITLE
Fix very slow jsdoc search in chained special assignments

### LINKED ISSUE #23111: In JS, deeply chained exports assignments cause long compile time
This is from async/index.js
```js
exports.wrapSync = exports.selectSeries = exports.selectLimit = exports.select = exports.foldr = exports.foldl = exports.inject = exports.forEachOfLimit = exports.forEachOfSeries = exports.forEachOf = exports.forEachLimit = exports.forEachSeries = exports.forEach = exports.findSeries = exports.findLimit = exports.find = exports.anySeries = exports.anyLimit = exports.any = exports.allSeries = exports.allLimit = exports.all = exports.whilst = exports.waterfall = exports.until = exports.unmemoize = exports.tryEach = exports.transform = exports.timesSeries = exports.timesLimit = exports.times = exports.timeout = exports.sortBy = exports.someSeries = exports.someLimit = exports.some = exports.setImmediate = exports.series = exports.seq = exports.retryable = exports.retry = exports.rejectSeries = exports.rejectLimit = exports.reject = exports.reflectAll = exports.reflect = exports.reduceRight = exports.reduce = exports.race = exports.queue = exports.priorityQueue = exports.parallelLimit = exports.parallel = exports.nextTick = exports.memoize = exports.mapValuesSeries = exports.mapValuesLimit = exports.mapValues = exports.mapSeries = exports.mapLimit = exports.map = exports.log = exports.groupBySeries = exports.groupByLimit = exports.groupBy = exports.forever = exports.filterSeries = exports.filterLimit = exports.filter = exports.everySeries = exports.everyLimit = exports.every = exports.ensureAsync = exports.eachSeries = exports.eachOfSeries = exports.eachOfLimit = exports.eachOf = exports.eachLimit = exports.each = exports.during = exports.doWhilst = exports.doUntil = exports.doDuring = exports.dir = exports.detectSeries = exports.detectLimit = exports.detect = exports.constant = exports.concatSeries = exports.concatLimit = exports.concat = exports.compose = exports.cargo = exports.autoInject = exports.auto = exports.asyncify = exports.applyEachSeries = exports.applyEach = exports.apply = undefined;
```

**Expected behavior:**
Compiler is fine, and no jsdoc is found.

**Actual behavior:**
Compilation never finishes. Jsdoc now understands chained assignments, but takes exponential (factorial?) time to discover that no jsdoc is on any of the binary expressions.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #23111 

The fix is to only recur once per parent instead of twice. This means moving the chained-assignment check in a slightly less obvious place.

### CODE REVIEW

**Comment by sandersn** [comment]
That might be an improvement. I think it’s likely to lead to deep nesting. And the current order is reflected in the output order of discovered jsdoc tags, so changing it might change the resolution when conflicting tags occur.

I’ll try it, but I’ll put it in a separate, non-bug fix PR if it’s an improvement.

________________________________

**Comment by sandersn** [comment]
@DanielRosenwasser here's what I got from de-duping the repeated parent checks. If you like it I can put it in a separate PR after this one:

```ts
if (parent) {
    if(parent.kind === SyntaxKind.PropertyAssignment ||
       parent.kind === SyntaxKind.PropertyDeclaration ||
       getNestedModuleDeclaration(parent) ||
       isBinaryExpression(node) && getSpecialPropertyAssignmentKind(node) ||
       isBinaryExpression(parent) && getSpecialPropertyAssignmentKind(parent) ||
       node.kind === SyntaxKind.PropertyAccessExpression && parent.kind === SyntaxKind.ExpressionStatement) {
        getJSDocCommentsAndTagsWorker(parent);
    }
    if (parent.parent) {
        // Try to recognize this pattern when node is initializer of variable declaration and JSDoc comments are on containing variable statement.
        // /**
        //   * @param {number} name
        //   * @returns {number}
        //   */
        // var x = function(name) { return name.length; }
        if (getSingleVariableOfVariableStatement(parent.parent) === node || getSourceOfAssignment(parent.parent)) {
            getJSDocCommentsAndTagsWorker(parent.parent);
        }
        if (parent.parent.parent) {
            if (getSingleInitializerOfVariableStatementOrPropertyDeclaration(parent.parent.parent) === node || getSourceOfDefaultedAssignment(parent.parent.parent)) {
                getJSDocCommentsAndTagsWorker(parent.parent.parent);
            }
        }
    }
}
```

Note that I removed the initial indent that comes from context, so the lines are actually longer than this in the editor.

**Comment by andy-ms** [comment]
@sandersn Since this always ends in a call to `getJSDocCommentsAndTagsWorker`, maybe you could factor out a function `getJSDocCommentsAndTagsHost` that returns `parent` or `parent.parent` or `parent.parent.parent` or `undefined`.

**Comment by sandersn** [comment]
@andy-ms I tried this -- is it what you were proposing?

```ts
    function getJSDocCommentsAndTagsHost(node: Node) {
        return node.parent
            ? node.parent.parent
                ? node.parent.parent.parent ? node.parent.parent.parent : node.parent.parent
            : node.parent
        : undefined;
    }
        function getJSDocCommentsAndTagsWorker(node: Node): void {
            const host = getJSDocCommentsAndTagsHost(node);
            if (host &&
                (host.kind === SyntaxKind.PropertyAssignment ||
                 host.kind === SyntaxKind.PropertyDeclaration ||
                 getNestedModuleDeclaration(host) ||
                 getSingleVariableOfVariableStatement(host) === node ||
                 getSourceOfAssignment(host) ||
                 getSingleInitializerOfVariableStatementOrPropertyDeclaration(host) === node ||
                 getSourceOfDefaultedAssignment(host) ||
                 isBinaryExpression(node) && getSpecialPropertyAssignmentKind(node) !== SpecialPropertyAssignmentKind.None ||
                 isBinaryExpression(host) && getSpecialPropertyAssignmentKind(host) !== SpecialPropertyAssignmentKind.None ||
                 node.kind === SyntaxKind.PropertyAccessExpression && host.kind === SyntaxKind.ExpressionStatement)) {
                getJSDocCommentsAndTagsWorker(host);
            }
// ......
```

This doesn't work as-is, but might be close.

**Comment by andy-ms** [comment]
Working on it.

**Pull request merged**
