### PR TITLE
Format template internal spaces

### LINKED ISSUE #5030: An unnecessary space is inserted in ${...} by the auto formatter
This is what I get after Ctrl+K+D in VS:

```ts
throw Error(`${JSON.stringify(this.value) } cannot be found in ${JSON.stringify(y) }`);
```

As you see, a space was inserted after `JSON.stringify(...)`. The bug doesn't appear if a plain variable is used: `${x}`.

### PR DESCRIPTION
**Pull request by SaschaNaz**
Fixes #5030

Current:
```typescript
throw Error(`${          JSON.stringify("") } cannot be found in ${                  JSON.stringify("") } while ${   3   }`);
```

Fix:
```typescript
throw Error(`${JSON.stringify("")} cannot be found in ${JSON.stringify("")} while ${3}`);
```

### CODE REVIEW

**Comment by vladima** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
What if a user just wants one space around their expressions?

**Comment by mhegazy** [comment]
> What if a user just wants one space around their expressions?

I think this is fair. this also applies to imports using `import { x } from 'm'` and for these, i would say we need a new option that allows for adding them or removing them.

**Comment by Arnavion** [comment]
I really would like that option for template strings. With 1.7 in new VS I have to fight it every time I auto-format :( Should I open a new issue?

**Pull request merged**
