### PR TITLE
Support "exclude" property in tsconfig.json

### PR DESCRIPTION
**Pull request by ahejlsberg**
Implements #3043. A tsconfig.json file that doesn't specify a `files` property (and therefore implicitly references all *.ts files in all subdirectories) can now contain an `exclude` property that specifies a list of files and/or directories to exclude from the compilation. The `exclude` property must be an array of strings that each specify a file or folder name relative to the location of the tsconfig.json file. For example:
```javascript
{
    "compilerOptions": {
        "out": "test.js"
    },
    "exclude": [
        "node_modules",
        "test.ts",
        "utils/t2.ts"
    ]
}
```
The `exclude` list does not support wilcards. It must simply be a list of files and/or directories.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This should probably have a name that ties it more close to 'fileNames'.  i.e. 'excludedFileNames'.  That way we know that this is supposed to complement that tsconfig property.

**Comment by ahejlsberg** [comment]
The other property is called `files`, not `fileNames`. Since you can exclude both files and directories it would have to be `excludedFilesAndDirectories` which I think is over the top. I like the simple `exclude`.

**Comment by basarat** [comment]
> exclude.

`excludes` perhaps?

**Comment by yuit** [comment]
I like ``` excludes``` as well. If you decide to change, please update this [line] (https://github.com/Microsoft/TypeScript/pull/3188/files#diff-057bf8560e435e388ba45f7810c3d08dR400)

**Comment by rcollette** [comment]
Meh.   Seems to completely ignore the community feedback about globs.

**Comment by basarat** [comment]
> Seems to completely ignore the community feedback about globs.

Adding `globbing` support for matching might not be that hard if we can just copy in this battle tested code : https://github.com/isaacs/minimatch/blob/master/minimatch.js It is MIT https://github.com/isaacs/minimatch/blob/master/LICENSE

**Comment by rcollette** [comment]
I should have added more specifics.  We keep all feature related code in the same directory.   Unit tests are named *.spec.js  Doing a build and excluding tests (or otherwise) doesn't work for us when files must be excluded by name and not by pattern.

**Comment by paulvanbrenk** [comment]
:+1: 
Though I can see the advantage of having globbbing, and adding a similar `include` property could prove to be useful.

**Comment by rbuckton** [comment]
@ahejlsberg We discussed this briefly, but I have an alternative approach that supports "glob"-style pattern matching with recursive directories in this pull request: #3232.

**Comment by troyji** [comment]
I suspect `tsconfig.json` is destined for much broader use in the future.  Using the simple key `exclude` could become ambiguous quickly.  Consider a more specific key name.

**Comment by DanielRosenwasser** [comment]
Pluralization ("excludes") would be better, but I'd too prefer a more specific name.

**Comment by ahejlsberg** [comment]
We're going with the simple `exclude` property for now, but we'll continue to refine #3289 with the eventual goal of supporting glob-style patterns. Anything we do in #3289 will be backwards compatible with the simple exclude list.

**Comment by tinganho** [comment]
Does language service take `exclude` option into consideration? I happen to have the TS repo under `node_modules/typescript` and it takes a long time to autocomplete things.

I'm on VSCode 0.3 on a Mac. And I'm using the current master branch.

**Comment by mhegazy** [comment]
@tinganho this has been checked in recently. The Language Service support should be in 1.6 by the time it ships.

**Comment by basarat** [comment]
@rbuckton I'd like to add support for this and completely remove atom-typescript's custom `filesGlob` support. Can you think of any use case where a `glob` is still needed if `exclude` is supported?

**Comment by basarat** [comment]
> Can you think of any use case where a glob is still needed if exclude is supported

Quick use case: user needs to include source from only a few folders. So ignore my last query :wink:

**Comment by Mig1st4ck** [comment]
I use fileGlobs to order my ts files.
```
"filesGlob": [
        "./app/**/*.module.ts",
        "./app/**/*.ts",
        "!./node_modules/**/*.ts"
    ],
```

**Comment by mbalex99** [comment]
@Mig1st4ck your filesGlob reference is from Atom correct? This is not (yet) a native tsconfig feature right?

**Comment by basarat** [comment]
@mbalex99 yes. It is not native

**Comment by HeikoH** [comment]
is this available in 1.5.3? Adding an `exclude` option to my `tsconfig.json` seems to have no effect when I run `tsc`.

**Comment by HeikoH** [comment]
I guess not as it works as expected with a nightly (1.6) build

**Comment by JaKXz** [comment]
It would be great if the `exclude` property supported globs. I'm sure that's been said somewhere, but I'm trying to do something similar to @Mig1st4ck and not having luck excluding files with the `filesGlob` property and the `!` property (under the assumption that `filesGlob` handles the `!` glob operator and excludes those files).

**Pull request merged**
