### PR TITLE
Replace "tsc @args.txt" to "tsc --project tsconfig.json"

### LINKED ISSUE #14775: Replace 'tsc --help' output message's example for using response files
Right now if you write `tsc --help`, you'll get

```
Version 2.x.x-dev.123456
Syntax:   tsc [options] [file ...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @args.txt
```

Notice that last part: **`tsc @args.txt`**.

Response files are not something we've thought about in forever. `tsconfig.json` has been the standard way to use TypeScript for quite a bit now. The example given is confusing at this point.

I think we should either remove it entirely or use **`tsc --project tsconfig.json`**

### PR DESCRIPTION
**Pull request by misoguy**
Fixes #14775

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
That was fast! Thanks! 😄 

For the record, your commit's email address (`sj.hwang` at `wanted` dot com)  is not associated with your GitHub account. You may want to do so in your GitHub options, or amend your commit. Let us know if this isn't a big deal.

**Comment by misoguy** [comment]
Oh I didn't really think about my email address. I'll amend my commit to match it with my GitHub account. Thanks!

**Comment by misoguy** [comment]
I've amended my commit to match with my account :) Thanks for pointing it out 👍

**Comment by mhegazy** [comment]
thanks!

**Pull request merged**
