### PR TITLE
Only catalog types when tracing

### PR DESCRIPTION
**Pull request by amcasey**
(cherry picked from commit 9fd2b48c5112536919af452a9ef31681b97a07af)

### CODE REVIEW

**Comment by amcasey** [comment]
@typescript-bot perf test this

**Comment by amcasey** [comment]
This is a memory usage win that seems safe enough for a patch release.

**Comment by amcasey** [comment]
I really don't see how this could regress check time by 40%, especially since the same PR in master did not.  However, I'll investigate.

**Comment by amcasey** [comment]
@typescript-bot perf fix this

**Comment by amcasey** [comment]
@typescript-bot perf test this

**Comment by amcasey** [comment]
So I guess the perf results actually show that this PR closes the memory perf gap that existed between release-4.2 and master.

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request merged**
