### PR TITLE
Cache the results of simple identifiers before creating substrings.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Test.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by Kingwl** [comment]
Well... It seems has a  4.50% regression in the parser.

**Comment by DanielRosenwasser** [comment]
@Kingwl Well we found that when running on ant design, a pretty big chunk of allocations came from the scanner. This was an experiment to see if it had any general savings. Locally, here's what `--extendedDiagnostics` gave me with this change:

```diff
- Memory used:               503355K
+ Memory used:               475070K
```

**Comment by Kingwl** [comment]
What could happening if use the ESmap rather than the hash functor?

**Comment by DanielRosenwasser** [comment]
We can't use a Map because we don't have a key, and in order to get a key, we'd need to slice, which would cause the allocation.

By the way, this is all super experimental - it's something I decided to quickly try and iterate on to see if diagnostics tools could pick up on the changes in any meaningful way. I'm still playing with it.

**Comment by Kingwl** [comment]
> which would cause the allocation

I thought a local slice of string is acceptable if it could be release soon (Might by escape analysis or be allocated on stack). 

Sadly I'm not an expert of V8 or GC. Hope all goes well.

**Pull request closed without merging**
