### PR TITLE
Move `Promise<T>` declaration to `lib.es5.d.ts`

### PR DESCRIPTION
**Pull request by mhegazy**
Move the declaration of the `Promise` interface to `es5.d.ts` (and subsequently `lib.d.ts`). This allows for DOM APIs that return `Promise` to be typed accurately. 

The PR adds a specialized error message for missing `Promise` **value** declaration while `Promise` **type** is available.

Fixes: https://github.com/Microsoft/TypeScript/issues/13947

### CODE REVIEW

**Comment by itaysabato** [comment]
Hey there @mhegazy,

Can you please tell me how do I, as of now, avoid taking the `Promise` interface definition just added to `lib.es5.d.ts`?

Up until `2.2.1`, setting `"lib": ["dom", "es5", "es2015.core"]` did the job for me. Is there a way to achieve the equivalent?

Thanks!

**Comment by mhegazy** [comment]
I am afraid there is not a way to do this now. but this is only the `interface Promise` and not the value `Promise`. can you elaborate on your scenario?

**Comment by itaysabato** [comment]
Sure, I will gladly elaborate :) 

The thing is I am using Bluebird as a polyfill for promises by setting the global `Promise` value to the `bluebird` module both in client code and in node. I am also using `@types/bluebird` for typings of their extensions to the Promise API.

The only way I found to avoid clashing between the "bundled" Promise type and bluebird is to exclude the former from `tsconfig`.

I have noticed the differentiation made between the Promise interface and value but have not been able to use that to my advantage... Semantically what I would like is to declare `let Promise: typeof Bluebird;` but that does not seem to work properly.

I would be happy to learn about any kind of solution or workaround.

Thanks again.

**Comment by itaysabato** [comment]
@mhegazy Do you have any new insights on this?
I would like to at least know if this is a bug or am I doing something wrong...

Thanks a lot!

**Pull request merged**
