### PR TITLE
Add script for pack response postback

### PR DESCRIPTION
**Pull request by weswigham**

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@RyanCavanaugh any further improvements you'd like to this?

**Comment by sheetalkamat** [comment]
@weswigham Thank you for this. Its very convenient than having to build it on the local machine.
I remembered about this by recollecting there to be PR. Do you have the list of things typescript bot can do somewhere?

**Comment by weswigham** [comment]
@sheetalkamat https://github.com/microsoft/TypeScript/wiki/Triggering-Typescript-Bot

**Pull request merged**
