### PR TITLE
Fix: False Positive "Range out of order in character class" in Regular Expressions in Unicode Modes

### PR DESCRIPTION
**Pull request by graphemecluster**
The first appears to be my fault; the second is a regression of #58339.

### CODE REVIEW

**Review by sandersn — COMMENTED** [review]
The first change seems like a straightforward fix. @rbuckton does the second change make sense?

**Comment by sandersn** [comment]
@graphemecluster can you provide a link to a bug or at least the PR that caused the bug for the first fix?

**Review by rbuckton — APPROVED** [review]

**Comment by graphemecluster** [comment]
@sandersn
First: https://github.com/microsoft/TypeScript/pull/55600/files#diff-e19070e6b0ecc4de5f7d4bc6b42a9a71c8f23ce8ce155f7bd7cd48763170e506R1587
Second: https://github.com/microsoft/TypeScript/pull/58339/files?w=1#diff-e19070e6b0ecc4de5f7d4bc6b42a9a71c8f23ce8ce155f7bd7cd48763170e506R3462

**Comment by sandersn** [comment]
@typescript-bot test all

**Comment by sandersn** [comment]
@typescript-bot test it

**Comment by graphemecluster** [comment]
@rbuckton Just as a heads up, you might want to merge this (and also #58981) before the beta release.

**Pull request merged**
