### PR TITLE
Naive implementation for #6097

### PR DESCRIPTION
**Pull request by guybedford**
As in https://github.com/Microsoft/TypeScript/issues/6097 this adds System.register `__moduleName` reference support.

An optimization that can be included is to only add this argument when it is explicitly used in the code, making the output cleaner, but it would be removed by minification anyway if it is always output.

### CODE REVIEW

**Comment by vladima** [comment]
the change per se looks good, however can you please also update test baselines so we can see overall impact?
For compiler tests this can be done via
```
# do a clean build and run tests
jake clean local runtests
# accept current test results as baselines
jake baseline-accept
```

Unittests baselines should be updated in code.

**Comment by guybedford** [comment]
@vladima sure, I've updated the baselines and pushed that through. If going the collision detection route it might be nice to also only add the reference when it is already a free global `__moduleName` reference in the existing code.

**Comment by vladima** [comment]
thanks! can you please also update baselines in `transpile` set suite: https://github.com/Microsoft/TypeScript/blob/master/tests/cases/unittests/transpile.ts ?

**Comment by guybedford** [comment]
Sure, no problem... it looks like the tests are passing now.

**Comment by vladima** [comment]
@guybedford great, thanks!

**Comment by DanielRosenwasser** [comment]
@vladima is this ready to go in?

**Comment by DanielRosenwasser** [comment]
Discussed offline; one current problem is that we'll never report an error if a user defines their own `__moduleName`. I'd prefer if we had a solution that protects the user, but I can't definitely commit until @mhegazy returns.

**Comment by guybedford** [comment]
There isn't any actual conflict - if a user chooses to redefine `__moduleName` they can. Better tracking of this variable use in the implementation is definitely something to consider though.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
thanks @guybedford!

**Pull request merged**
