### PR TITLE
Improve prop type key when mapping over tuple

### PR DESCRIPTION
**Pull request by Andarist**
This makes it easier to map over tuples by allowing `T[K & number]` on the "right side" to preserve the per-position type of the input tuple.

A TS question on Twitter has been posted by @kof [here](https://twitter.com/oleg008/status/1508422774401949704) and I was sort of surprised that this solution didn't quite work as expected. So I got curious as to **why** it doesn't work and I've discovered that the prop type in the mapper is a string... and thus `K & number` gets reduced to `never` and then `Tuple[never]` produces a union of types at all position (which is somewhat surprising to me as with an object type I just get `never` back).

It seems that this trivial change~ improves this situation considerably and doesn't break any existing test cases. The improvement can be seen in [this diff](https://github.com/microsoft/TypeScript/compare/0b381cb8c91489378fc971742fdcbb3f8913f738..b25dacf528db825de13fc3ca6041a24360c2a7e8).

[TS playground 4.6](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdgEwJYGMIGcA8AVKEAewEi6UAggE4UCGIm1cIAfE1ALxQDeAUFFANoBpKEjhQA1hBAB7AGZRsAXQBcUQdwC+Abm7cA9HqjoAFtICuAGwRQU0uMGqiocMwFsARhArpuoSFABZEHhkNFIOENQMTH50YApRAHMAGmc3TwpFJh0DKDM4JDsoORFEKNITcysoTygwCgwvADcIBF9waABlYCQLCyDIsPZA4LKw-hcPL0UoADI0qYpdXPQkVzALJFkkVqgG+ukoWQppVyhjYGAwdGUDYAB3JEuvADpbVz1pCwhEgAZfgAceji1GAZnQegAjABWQEAFgATAiAOzIuFw36QgCccKxyN+cN0fmgAGE7A5RF5MAA1VgcHh8JrUCxmCCqak6bREjpQACqcHuNDAZPsjjgXiwuAIRBIUBFFPFFEw+XEcGk9zgTH4WWGDIEwickhk8iUqmwQjmCwyin4ACImSyILbFJydNwEBAUBZqA0jvkUD0iu93JScHhCMQEKR5WKqSq1RqtVkABS8Gzk2PeVT8F65pTJNMoZkWdzUFDiVTJ3MvB2sm58gVCmOU7w4JgASnYrCa0iQbXbqh7fbdHq9PugtjgcXTopbkNUzcVmDiCTgiWy7s93t9k+nk4VXgRC4zLcwkwyG+4wcpyf4+8zkNS95bCMUqWTtYgj6gn4RnbYrB6ruwA-sy85GPESTDJ+kI6HwwGgRYR5Wl40HMqyCKcu2bpAA)

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Interesting, I also use the string index in https://github.com/microsoft/TypeScript/pull/48433 maybe should be adapted too

**Comment by Andarist** [comment]
@mikearnaldi ye, if this PR here lands then the other one should be adjusted too. If yours lands first then I will add some additional tests here, related to your change.

**Comment by sandersn** [comment]
It would really be nice to have an associated bug with inline examples. But this does seem like a small change, so .. @weswigham, what do you think?

**Review by weswigham — COMMENTED** [review]
Tuple keys being number literals in the template is... probably a fine change? I'm unsure... Thing is, it's now possible to map from the strings back to the numbers (due to an inference change by @rbuckton ) so maybe we should just be OK with mapped types consistently returning the string form of the keys and allowing users to map those into the numbers if they actually need to?

**Comment by Andarist** [comment]
> Thing is, it's now possible to map from the strings back to the numbers (due to an inference change by @rbuckton ) so maybe we should just be OK with mapped types consistently returning the string form of the keys and allowing users to map those into the numbers if they actually need to?

While possible, I don't think this is that ergonomic from the user perspective - for what seems to be a standard~ use case. This kind of mapping is not too fancy - it's just mapping one tuple to another.

I would also argue that this matches the common expectations of array/tuple keys being numbers (`arr[0]`). It's possible to access using both strings and numbers but I don't think that many users think in terms of accessing array types with stringified integers. 

IMHO, this also matches better how we can expand a tuple to a union of the values:
```ts
type A = [0, '1']
type B = A[number] // 0 | ''
```

**Comment by ahejlsberg** [comment]
While I understand the motivation, I don't think it is right to change the iteration type to be numeric. A homomorphic mapped type is supposed to iterate over `keyof T` (or, in the case of tuples, some subset thereof) and with this change that wouldn't be the case.

Let me think about the scenario a bit and see if I can come up with something better.

**Comment by Andarist** [comment]
We could maintain the mentioned invariant if tuples would have numeric keys representing their indices and not their stringified equivalents. As a user - this would be much closer to how i think about arrays/tuples.

Separately from that - iterating over tuples could be it's own thing (annotated somehow, or using new syntax). A lot of quirks/unexpected behaviors happen because this piggy backs on regular, object-oriented, mapped types

**Comment by ahejlsberg** [comment]
> We could maintain the mentioned invariant if tuples would have numeric keys representing their indices and not their stringified equivalents. As a user - this would be much closer to how i think about arrays/tuples.

Agree in principle. Except it wouldn't work because tuples also have a numeric index signature which would "absorb" the numeric literal values when you ask for `keyof T`. For example, `keyof [true, false]` currently is `number | "0" | "1" | ...`, and the `number` would absorb the numeric literals in what you propose.

**Comment by Andarist** [comment]
Just added [a comment](https://github.com/microsoft/TypeScript/issues/48739#issuecomment-1106742633) on a related issue to this. The final solution there could be greatly simplified if we'd have an easier way to iterate over tuples position by position.

**Comment by ahejlsberg** [comment]
So, I'm putting together a PR that adds the following:

* Numeric index signatures apply when the index type is `${number}`. For example `` `Foo[][`${number}`]`` resolves to `Foo` instead of being an error. This is consistent with our existing rule that index signatures apply when the index type is a numeric string literal. For example `Foo[]['123']` already resolves to `Foo`.
* Intersections of type `string` and a template literal type reduce to just the template literal type. For some reason we never had that rule, but we should such that `` `Foo[][K & `${number}`]``, where `K` is some `keyof T`, can resolve to `Foo`.

With these changes, your example works when you write

```ts
type UnwrapContainers<T extends Container<unknown>[]> = {
    [K in keyof T]: T[K & `${number}`]["value"];
};
```

I'm also looking at possibly adding an implied `` `${number}` `` constraint to `K` in cases where it iterates over `keyof T` for some `T` constrained to an array type.

**Comment by Andarist** [comment]
I agree with the proposed changes - the first two seem like good semantic improvements when we consider existing functionality.

The proposed implied `${number}` constraint would mean that those changes wouldn't be needed for this use case to work, right? That's, of course, not a reason to skip introducing them - I'm just making sure that I understand this correctly. With this proposed change the ``K & `${number}` `` wouldn't be needed at all and we could simplify further:
```diff
type UnwrapContainers<T extends Container<unknown>[]> = {
-    [K in keyof T]: T[K & `${number}`]["value"];
+    [K in keyof T]: T[K]["value"];
};
```

I guess this would maintain the invariant about `K` always being a subset of `keyof T` since:
```ts
const b = ['', 9] as const
type Test = `${number}` & keyof typeof b
//   ^? type Test = "0" | "1"
```

**Comment by treybrisbane** [comment]
Thinking about the underlying problem... Is there any appetite for introducing distinct syntax for array/tuple mapping?

For example, something like
```ts
type StringifyElements<T extends ReadonlyArray<any>> = [[I in indexof T]: `${T[I]}`];
```
(doesn't have to be this syntax specifically!)

I realise the scope of such a feature is significantly beyond that of this PR 😅, but...

Over the years, I've used various hacks/workarounds to get the existing mapped type syntax to correctly transform array/tuple elements, and the results have always been fragile/unreliable. I usually end up using recursive types instead, but these are more complex and have their own problems. Having dedicated syntax here would definitely make my life easier!

The current mapped type syntax is a great tool for _general_ key/value transformation. While arrays/tuples _are_ objects, they're a _specialised form_ of object, and array/tuple mapping is a _specialised key/value transformation_. As such, having _specialised syntax_ for it would make sense in the same way that having specialised syntax for array value literals does.

Thoughts?

**Comment by ahejlsberg** [comment]
> Thinking about the underlying problem... Is there any appetite for introducing distinct syntax for array/tuple mapping?

With the improvements in #48837 there shouldn't be a need for distinct syntax for array/tuple mapping. Homomorphic mapped types constrained to array types should cover it.

**Comment by Andarist** [comment]
Closing in favor of the mentioned https://github.com/microsoft/TypeScript/pull/48837

**Pull request closed without merging**
