### PR TITLE
Fix emit for object rest on a module export

### LINKED ISSUE #32656: Exported variable declaration with destructured object literal and CommonJS module target
**TypeScript Version:**  3.6.0-dev.20190801

**Search Terms:**

destructuring, variable declatation, binding pattern, export, commonjs

**Code**

```ts
export const { x, ...rest } = { x: 'x', y: 'y' }
```

**Expected behavior:**

Similarly to array destructuring, make `_a` a temporary local identifier:

```js
var _a;
exports.x = (_a = { x: 'x', y: 'y' }, _a.x), exports.rest = __rest(_a, ["x"]);

```

**Actual behavior:**

```ts
exports._a = { x: 'x', y: 'y' }, exports.x = _a.x, exports.rest = __rest(_a, ["x"]);
```

Which fails at runtime because `_a` is not defined.

**Playground Link:**

https://www.typescriptlang.org/play/?target=1#code/KYDwDg9gTgLgBAYwgOwM7wN5xAGjgOkKmHTgF84BeOLEALjgHIRG8BPBxtx8gWACggA

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes the emit for object rest binding patterns on exported variables. 

Also fixes a few other small tooling bugs:
-  Fixes a bug in vary-by test configurations to allow running conformance/compiler tests against multiple module/target configurations.
- `gulp diff` and `gulp diff-rwc` no longer block until your diff tool is closed.
- You can add `// @noTypesAndSymbols: true` to the top of a test to skip .types and .symbols baselines if they're not relevant to the test.

Fixes #32656

### CODE REVIEW

**Comment by weswigham** [comment]
Do we have a test for the empty binding pattern - `export const {} = {};`? The emit for that seems strange in the playground.

**Comment by rbuckton** [comment]
Hmm. You are correct, those seem a bit odd.

**Comment by rbuckton** [comment]
We do this intentionally, even if its a bit strange and could be cleaned up. The idea is that we need to preserve any possible side effects of the initializer, and we're transforming a variable declaration to a variable declaration, so we need to emit *something*. Arguably, this could be cleaned up, but I don't believe that's related to the issue this intends to resolve.

**Comment by rbuckton** [comment]
I will add the tests, so that we can refer to them later and can validate regressions, but I don't intend to address the current emit for those in this PR.

**Pull request merged**
