### PR TITLE
Fix recursive types in @typedef

### LINKED ISSUE #39372: Jsdoc Type alias circularly references itself
**TypeScript Version:**  4.0.0-dev.20200701

**Search Terms:** Jsdoc type alias circularly references itself

I'm trying to describe json type in `.js` file using jsdoc.

```js
// Type alias 'JsonArray' circularly references itself.
/** @typedef {ReadonlyArray<Json>} JsonArray */
/** @typedef {{ readonly [key: string]: Json }} JsonRecord */
// Type alias 'Json' circularly references itself.
/** @typedef {boolean | number | string | null | JsonRecord | JsonArray | readonly []} Json */
```

It shows me some errors that JsonArray and Json types circularly reference to itself. 

Tried the same in `.ts` file. There got no errors.

```ts
type JsonArray = ReadonlyArray<Json>
type JsonRecord = { readonly [key: string]: Json }
// OK
type Json = boolean | number | string | null | JsonRecord | JsonArray | readonly []
```

Expected behaviour: Json types in `.js` and `.ts` files should work identical.

### LINKED ISSUE #40234: JSDocs @typedef parsing runs into infinite loop
**TypeScript Version:**  v4.1.0-dev.20200824

**Search Terms:**

**Code**

TS:

```ts
export type XMLObject<T> = {
  $A: {
    [K in keyof T]?: XMLObject<T[K]>[]
  },
  $O: {
    [K in keyof T]?: {
      $$?: Record<string, string>
    } & (T[K] extends string ? {$:string} : XMLObject<T[K]>)
  },
  $$?: Record<string, string>,
  } & {
  [K in keyof T]?: (
    T[K] extends string ? string
      : XMLObject<T[K]>
  )
};

const p:XMLObject<{foo:string}> = {};

```

JS:

```js
/**
 * @template T
 * @typedef {{
  $A: {
    [K in keyof T]?: XMLObject<T[K]>[]
  },
  $O: {
    [K in keyof T]?: {
      $$?: Record<string, string>
    } & (T[K] extends string ? {$:string} : XMLObject<T[K]>)
  },
  $$?: Record<string, string>,
  } & {
  [K in keyof T]?: (
    T[K] extends string ? string
      : XMLObject<T[K]>
  )
}} XMLObject<T> */

/** @type {XMLObject<{foo:string}>} */
const p = {};
```

**Expected behavior:**

VSCode Intellisense outputs should match and results should somewhat as fast in JS as in TS.

**Actual behavior:**

Extremely long parsing time, Intellisense mismatch and long, infinitely looping type details. Hovering over `XMLObject` in the playground link takes a very long time on JS.

JS: loop example

TS: 
loop example2

**Playground Link:**

JS: https://www.typescriptlang.org/play?ts=4.1.0-dev.20200824&useJavaScript=true#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUowICeqiAJogGaQDeNUkAJAIIBctDkkA2gNKQBLAHaQA1oiIB7argC6AfnYANALIAZAPIAjAFaIAxvAA8uPrIB83WQwC+AGgaMN7ely59BI8VJkKXnN0ZGRUgAJQNJACcyIwBneEjhAHM7SHjEoSTzAJtIADJIAApTXllIRAAPJCEyWLSE5Mh5WkZWdOTc5XVtPUMTM3MASlsHLiCQ8P0omPbM1Nms0chcgtcefmExCWk8PyKAkrLK6tr6jKSms+SAri7NXQNjQ+yuYZtc1Xvep-NoYHBwKBCPASIhaJ8eo8jDRKJJJG0GpkbOZciB-lMhPFIKhIABeWg2ADc4CAA

TS: https://www.typescriptlang.org/play?ts=4.1.0-dev.20200824#code/KYDwDg9gTgLgBDAnmYcAaBZAMgeQEYBWwAxjADwAqAfHALxwDeAUHHACQCCAXIy63AG0A0nACWAOzgBrYIggAzOBQC6Afh6ZchEuQrDlVAcr4BfADR82OHs36CRE6bIVK1NvnbZt1cAEoloABMyAGcYKAkAczM4MIjxSKoPOBM4ADI4AAo9IWU4UBhgcUCQ2PCouFVGNi44qNSNbHwiUkp9KgBKUwtWLx9-YiDQ8oSYuoSqHpT03lZhMUkZOUUVH0zknLyCopKy+MjKvajk1katFt12vi6TAG4mJkHxMLgwLk1mnTIGeQgIWpGkRMNHoDDuTCAA

**Related Issues:**

### PR DESCRIPTION
**Pull request by sandersn**
Previously this code path was broken and untested. Fortunately the fix is simple -- the code that looks for the alias' host needs to skip the JSDoc type expression node as it walks up the tree.

Fixes #39372
Fixes #40234

### CODE REVIEW

**Review by weswigham — APPROVED** [review]

**Comment by sandersn** [comment]
Oops, forgot to update baselines now that type aliases created by typedefs are properly deferred. I'll do that.

**Comment by kungfooman** [comment]
Why does this work for:

```js
/** @typedef {Json[]} JsonArray */
/** @typedef {{ readonly [key: string]: Json }} JsonRecord */
/** @typedef {boolean | number | string | null | JsonRecord | JsonArray | readonly []} Json */
```

But not if `JsonRecord` is defined like this:

```js
/** @typedef {Object<string, Json>} JsonRecord */
```

Then it errors with: `Type alias 'JsonRecord' circularly references itself.`

(thank you a lot for this PR, it is already tremendously useful)

**Comment by sandersn** [comment]
@kungfooman can you open a fresh bug for that?

**Comment by kungfooman** [comment]
> @kungfooman can you open a fresh bug for that?

@sandersn There is this one already, I think it's the same issue: https://github.com/microsoft/TypeScript/issues/46369

**Pull request merged**
