### PR TITLE
Improve detection of cases where subtype reduction is unnecessary

### LINKED ISSUE #53425: `if ('A' in el) {}` causes code below to error
# Bug Report

### 🔎 Search Terms

`narrowing in if`
`Argument of type 'unknown'`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230321#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQEE4BvAKDjkyigC5S5D6kBXAWwCM0BuOAXwDaAXW5k+ZMqEixEKNFlwFCAIVIUqNeiUbN2XKL2W7OPfsNHjJ4aPHQsk2GAghI4AMQAUIekTgAfJWUASjVKbBcAZ3gWCOBVAF44DxhjfRD4gD5SPlFKdGgk8KQouGAAGzgIdDgQADpqKBDySkoEao8AckIO2VKypr44AHohuHC2NmAUSpZ4GAALBAi4MuQ8GAg4NkwAazwOmLiPctrgnvGwBDK8AHcEBYhZ0ppodVb2juUe5D6mt5aRnAAOrzKZwDptJJdb6ucoDHqYDgQABueCWcCQEHg40mKFQABMZjAADRwBZ4VZIPBcMoQG5wO5lCpoKAFO4LWj-SiAlkFeiEKAAc3YU3gVTJAE8wPt7DtMTckN9lpj4JgIhEEIKkIjrmTNmBqJhJqgoJVqjApftWCYoB1ah4AEwAZgALABWIJcuCHZTHMqnIK8Fpwf7iSjiPhAA)

### 💻 Code

```ts
export interface IA {
  arr: { A: number; }[];
}

export interface IAB {
  arr: { A: number; B: number; }[];
}

export function F(x: IA | IAB) {
  const useB = (t: number) => {};
  for (const el of x.arr) {
    if ('A' in el) {} // comment out this line to make 'useB(el.B)' compile without error
    if ('B' in el) {
      // When 'if ('A' in el) {}' above is not commentted out, the line below will error with:
      // error : Argument of type 'unknown' is not assignable to parameter of type 'number'.(2345)
      useB(el.B);     
    }
  }
}
```

### 🙁 Actual behavior

```
useB(el.B);
     ^^^^
error : Argument of type 'unknown' is not assignable to parameter of type 'number'.(2345)
```

The above error is raised if the line `if ('A' in el) {}` is **not** commented out.
Commenting out `if ('A' in el) {}` compiles without error.

### 🙂 Expected behavior

That the line `if ('A' in el) {}` does not narrow the type of `el` in a way that prevents code outside of the `if` from compiling.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53425.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by jakebailey** [comment]
The new errors above actually seem... good?

**Comment by RyanCavanaugh** [comment]
Looks like people who declared something with
```ts
let x: void | number;
if (maybe) {
  x = 32;
}
x;
```
now get an error, which they absolutely should have.

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@jakebailey @RyanCavanaugh I think the new errors are better. They're caused by the change to use `initialType` in the calls to `isTypeSubsetOf` but aren't actually necessary to fix the original issue. Previously, the `undefined` we'd inject in the initial type to catch missing initialization situations was seen as a "foreign" type because it isn't part of the declared type. That would then cause use to perform subtype reduction, in which `void` would eat the `undefined`, leaving us with the declared type. That in turn would make it look like all code paths initialized the variable and we wouldn't report the error.

**Comment by fatcerberus** [comment]
To be fair, nobody should be declaring things as `T | void` anyway.  `void` !== `undefined`.  https://github.com/microsoft/TypeScript/issues/42709 FTW 😉

**Pull request merged**
