### PR TITLE
Adjust check in sys to fix browserify

### LINKED ISSUE #4359: `jake runtests-browser t=yourTestName` does not load any test on master branch
`jake runtests-browser t=yourTestName` has got broken and the `Run Tests` button just shows `passes: 0 failures: 0 duration: 0s`.

I'm testing on Windows 10 build 10240 and io.js v2.3.1. It had worked a week ago and got broken when I received the latest TypeScript bits. Updating io.js to version 3.0.0 doesn't fix this problem.

`jake runtests t=yourTestName` still works as expected.

### PR DESCRIPTION
**Pull request by vladima**
Fixes #4359

### CODE REVIEW

**Comment by vladima** [comment]
pinging @jbrantly as this change partially rolls back https://github.com/Microsoft/TypeScript/pull/4308

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by jbrantly** [comment]
I think that undoing #4308 is likely the wrong way to do it. That corrected behavior where browserify was "covering up" the issue (by shimming fs). I can see two ways of going about it.

1. Keep the current `return undefined` behavior for ts.sys in the case of a browser but reduce the test harness's dependency on it. For instance, the current error is because the CScript and Node executing environments currently *always* run and look like this:

    ```typescript
    export let readFile: typeof IO.readFile = ts.sys.readFile;
    export let writeFile: typeof IO.writeFile = ts.sys.writeFile;
    ```
but if you added some protection:

    ```typescript
    let sys = ts.sys || {};
    export let readFile: typeof IO.readFile = ts.sys.readFile;
    export let writeFile: typeof IO.writeFile = ts.sys.writeFile;
    ```
similar to the way you do the same for `fso` for CScript then that issue goes away. However, there are numerous other dependencies on `ts.sys` like `useCaseSensitiveFileNames` and `newLine` and it would probably be a pretty large undertaking to fix all occurrences. It's not clear to me if TypeScript, in general, is designed to run with `ts.sys` undefined.

2. Instead of returning undefined, go ahead and shim `ts.sys` in a minimal way that works for the browser. I did something like this:
    ```typescript
    return {
        args: [],
        newLine: "\n",
        useCaseSensitiveFileNames: false,
        write: null,
        readFile: null,
        writeFile: null,
        resolvePath: null,
        fileExists: null,
        directoryExists: null,
        createDirectory: null,
        getExecutingFilePath: null,
        getCurrentDirectory: () => "/",
        readDirectory: null,
        exit: null
    };
    ```
and that seemed to allow me to run the fourslash tests. This is roughly equivalent to allowing browserify to shim stuff.

**Comment by vladima** [comment]
closing in favor of #4394

**Pull request closed without merging**
