### PR TITLE
Const contexts for template literals

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we produce template literal types for template literal expressions in `const` assertions.

```ts
const tc1 = 'foo' as const;  // 'foo'
const tc2 = 'bar' as const;  // 'bar'
const tc3 = `${tc1}-${tc2}` as const;  // 'foo-bar'
const tc4 = [`${tc1}-${tc2}`, `${tc2}-${tc1}`] as const;  // readonly ['foo-bar', 'bar-foo']

function test<T extends string, U extends string>(x: T, y: U) {
    return `${x}-${y}` as const;  // `${T}-${U}`
}

const ts1 = test('foo', 'bar');  // 'foo-bar'
const ts2 = test('foo', !!true ? '0' : '1');  // 'foo-0' | 'foo-1'
const ts3 = test(!!true ? 'top' : 'bottom', !!true ? 'left' : 'right');  // 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'
```

The type of a template literal `` `aaa${x}bbb${y}ccc` `` in a const context is `` `aaa${X}bbb${Y}ccc` ``, where `X` and `Y` are the types of `x` and `y` respectively, or `string` when `x` or `y` is not assignable to `string | number | boolean | bigint`. Template literal types resulting from template literals in const contexts are _normalized_ as described in #40336, meaning that a resulting type may actually be a union of literal types.

### CODE REVIEW

**Review by weswigham — APPROVED** [review]

**Comment by Roaders** [comment]
Very nice!

**Comment by lizraeli** [comment]
This is incredible!

**Comment by Roaders** [comment]
So why isn't this available on the nightly build on playground yet?
If I select nightly it loads `4.1.0-dev.20200921` but I can see `4.1.0-dev.20200923` on [npmjs ](https://www.npmjs.com/package/typescript/v/4.1.0-dev.20200923)(tagged as `next`).

When I try to load 4.1.0-dev.20200923 into playground it fails... 😢

**Comment by weswigham** [comment]
Last night's (and I think the day before, too, maybe) nightly publish failed due to a tooling issue - there should be a new nightly in a few hours.

**Pull request merged**
