### PR TITLE
Try some functional refactor of some parser code

### PR DESCRIPTION
**Pull request by elibarzilay**
(Wondering if this will affect performance.)

### CODE REVIEW

**Comment by elibarzilay** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by elibarzilay** [comment]
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by elibarzilay** [comment]
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by elibarzilay** [comment]
@typescript-bot perf test this

**Comment by elibarzilay** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
This experiment is pretty old, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
