### PR TITLE
feat(37092): Improve error when default-importing from a module that `export *`s from a module with a default export

### LINKED ISSUE #37092: Improve error when default-importing from a module that `export *`s from a module with a default export
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

https://github.com/bluelovers/ws-react/blob/master/packages/react-use-localstorage/index.ts
```ts
export * from './core/v4';
//import createStorageHook from './core/v4';
//export default createStorageHook

//console.log(exports.default)
```

```ts
import createStorageHook from './src/core';
```

**Expected behavior:**

know "src/core" has default import

**Actual behavior:**

> Error:(2, 8) TS1192: Module '"src/core"' has no default export.

**Playground Link:** 

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/37090

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37092

### CODE REVIEW

**Comment by andrewbranch** [comment]
Two thoughts:

1. This could really stack up in unhelpful ways given the popularity of [barrels](https://basarat.gitbook.io/typescript/main-1/barrel) and how large they can often become. I would maybe just add the related info once, as something like `'export *' does not re-export a default.`
2. It only makes sense to issue this message if one or more of the ExportStar declaration targets actually _has_ a default export.

**Comment by a-tarasyuk** [comment]
> I would maybe just add the related info once, as something like 'export *' does not re-export a default

@andrewbranch Thanks for your feedback 👍.  Which _node_ do I need to use to add related info?

**Comment by andrewbranch** [comment]
I guess I’d attach it to the first one whose target has a default export.

**Comment by sheetalkamat** [comment]
@andrewbranch That makes it hard during incremental editing/diagnostics since then order of the checking would guide the diagnostic position ?

**Comment by andrewbranch** [comment]
I could be wrong, but I don’t _think_ that will be the case. `exportStar.declarations` should be filled by the binder in source order, and then you’d try to resolve the module (`resolveExternalModuleName`) of each one in order... the order of checking might determine whether those resolutions have already happened before, but I don’t see how that would affect the results you see when checking declarations in source order.

**Comment by a-tarasyuk** [comment]
@andrewbranch Done.

**Pull request merged**
