### PR TITLE
Don't emit an empty template head literal if there's a template span with a non-empty literal.

### LINKED ISSUE #1570: ES5 emit for template strings has some redundant empty strings
First line - TS, second line - current ES5 emit, third line - proposed ES5 emit

```javascript
console.log(`${ foo }b`);
console.log("" + foo + "b");
console.log(foo + "b");
```

```javascript
console.log(`${ foo }b${ bar }`);
console.log("" + foo + "b" + bar);
console.log(foo + "b" + bar);
```

```javascript
console.log(`${ foo }b${ bar }c`);
console.log("" + foo + "b" + bar + "c");
console.log(foo + "b" + bar + "c");
```

The current implementation always emits the template head, even if it's an empty string. However all that's really necessary is that one of the first two operands in the emit result must be a string literal. So if the first template span has a non-empty literal, the empty head literal can be omitted.

This is a nitpick but it does make for cleaner diffs when migrating string concats to the equivalent template string.

### PR DESCRIPTION
**Pull request by Arnavion**
Fixes #1570

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Great work @Arnavion! I'm going to sign off :+1:.

@mhegazy should make the final call on this.

**Comment by mhegazy** [comment]
:+1:

**Comment by Arnavion** [comment]
Thanks!

@DanielRosenwasser @mhegazy Any chance of getting this and #1577 in 1.4 too?

**Comment by DanielRosenwasser** [comment]
Unfortunately not, we're almost converged on 1.4, but I expect 1.5 to be released soon after anyway.

**Comment by Arnavion** [comment]
@DanielRosenwasser Seems this was force-pushed out of master?

**Comment by DanielRosenwasser** [comment]
This is bad. Let me try to resolve the issue.

**Comment by DanielRosenwasser** [comment]
@Arnavion should be fixed now.

**Comment by Arnavion** [comment]
@DanielRosenwasser Just noticed release-1.4 was also force-pushed back from ead4625 to ae0caed Every other branch is fine AFAICT

**Comment by DanielRosenwasser** [comment]
Thanks so much for catching that! I'll take care of that immediately.

**Pull request merged**
