### PR TITLE
fix(58955): @import JSDoc tag doesn't seem to account for resolution-mode import attribute in TS v5.5.2

### LINKED ISSUE #58955: `@import` JSDoc tag doesn't seem to account for `resolution-mode` import attribute in TS v5.5.2
### 🔎 Search Terms

"resolution-mode"

### 🕗 Version & Regression Information

I was unable to test this on prior versions because the `@import` tag is newly available on TS 5.5.2

### ⏯ Playground Link

_No response_

### 💻 Code

```ts
// @filename: esm/esm.js
export type MyType = { foo: 'bar' }

// @filename: cjs/cjs.js
// This works:
/** @typedef {import('../esm/esm.js', { with: { 'resolution-mode': 'import' } }).MyType} MyType */

// This doesn't:
/** @import {MyType} from '../esm/esm.js' with { 'resolution-mode': 'import' } */
```

I couldn't create a TS playground because of this issue: https://github.com/microsoft/TypeScript/issues/52666

### 🙁 Actual behavior

The `@import` usage in this context yields the following error:

> The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("../esm/esm.js")' call instead.
To convert this file to an ECMAScript module, change its file extension to '.mjs', or add the field "type": "module" to '/cjs/package.json'. ts(1479)

### 🙂 Expected behavior

The `@import` tag should account for import attributes like `with { 'resolution-mode': 'import' }` to enable cross CJS/ESM type imports.

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #58955

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]
This seems correct to me. Probably worth the 5.5 backport.

**Review by andrewbranch — APPROVED** [review]
Thanks @a-tarasyuk!

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick to release-5.5

**Comment by jakebailey** [comment]
I expect cherry-picking to fail just because these lines are ones that changed in the 5.5 bump for type predicate inference...

**Comment by a-tarasyuk** [comment]
@jakebailey should I make a new PR to the release branch?

**Comment by jakebailey** [comment]
No worries, I'll do it.

**Pull request merged**
