### PR TITLE
[Transforms] Merge master 09/01

### PR DESCRIPTION
**Pull request by yuit**
The last three comments are the ones that will need review

### CODE REVIEW

**Comment by kpreisser** [comment]
Hi @yuit, @rbuckton,
sorry to ask again, but can you give me information about the merging operation (squash commit vs. merge commit), as I commented in #10263?
In particular, I'm wondering why the pull request (Merge master 08/09) has been merged as a squash commit (single commit with all the changes) rather than a merge commit (which has two parent commits).

For example, commit 3f6aa3f3f0705cfc6bfe59920d49e76c12023953 seems to have been merged with the previous PR already (in the squash commit), but is included in this PR again, as AFAIK for Git it looks as if the last merged commit from the `master` branch to the transforms branch was 4a470bd27c6f4e06aa2ee8fa387a304366eb136c (the red graph represents the `master` branch, the black one the `mergeMaster_09/01` branch):
ts-transforms-branches


Thank you!

**Comment by rbuckton** [comment]
:+1:

**Comment by yuit** [comment]
@kpreisser Thanks for raising this up! I didn't saw your original comment until now and wasn't awared of the different. Now that I know I will not squash my commit. I normally do so when I merge to `master` but you are absolutely right that this should be done with merge commit which I will do so here. Thank you so much for sharing this

**Comment by kpreisser** [comment]
Great, thanks!

**Pull request merged**
