### PR TITLE
Instantiate generic conditional infer source types in the context of the target conditional

### LINKED ISSUE #26627: "Two different types with this name exist, but they are unrelated" emitted when same
**TypeScript Version:**  Version 3.1.0-dev.20180823

**Search Terms:** Different types with same name

**Code**

```ts
export type Constructor<T> = new (...args: any[]) => T
export type MappedResult<T> =
    T extends Boolean ? boolean :
    T extends Number ? number :
    T extends String ? string :
    T


interface X {
    decode<C extends Constructor<any>>(ctor: C): MappedResult<C extends Constructor<infer T> ? T : never>
}

class Y implements X {
    decode<C extends Constructor<any>>(ctor: C): MappedResult<C extends Constructor<infer T> ? T : never> {
        throw new Error()
    }
}
```

**Expected behavior:** It should compile without any error. Everything is in the same namespace, so it should be the same type.

**Actual behavior:** The quoted error below is emitted.

```text
$ tsc tsc-test.ts
tsc-test.ts:14:5 - error TS2416: Property 'decode' in type 'Y' is not assignable to the same property in base type 'X'.
  Type '<C extends import("tsc-test").Constructor<any>>(ctor: C) => import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>' is not assignable to type '<C extends import("tsc-test").Constructor<any>>(ctor: C) => import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>'. Two different types with this name exist, but they are unrelated.
    Type 'import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>' is not assignable to type 'import("tsc-test").MappedResult<C extends import("tsc-test").Constructor<infer T> ? T : never>'. Two different types with this name exist, but they are unrelated.

14     decode<C extends Constructor<any>>(ctor: C): MappedResult<C extends Constructor<infer T> ? T : never> {
       ~~~~~~
```

**Playground Link:** [Here][0]

**Related Issues:** None I can find

[0]: https://www.typescriptlang.org/play/#src=export%20type%20Constructor%3CT%3E%20%3D%20new%20(...args%3A%20any%5B%5D)%20%3D%3E%20T%0D%0Aexport%20type%20MappedResult%3CT%3E%20%3D%0D%0A%20%20%20%20T%20extends%20Boolean%20%3F%20boolean%20%3A%0D%0A%20%20%20%20T%20extends%20Number%20%3F%20number%20%3A%0D%0A%20%20%20%20T%20extends%20String%20%3F%20string%20%3A%0D%0A%20%20%20%20T%0D%0A%0D%0A%0D%0Ainterface%20X%20%7B%0D%0A%20%20%20%20decode%3CC%20extends%20Constructor%3Cany%3E%3E(ctor%3A%20C)%3A%20MappedResult%3CC%20extends%20Constructor%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3E%0D%0A%7D%0D%0A%0D%0Aclass%20Y%20implements%20X%20%7B%0D%0A%20%20%20%20decode%3CC%20extends%20Constructor%3Cany%3E%3E(ctor%3A%20C)%3A%20MappedResult%3CC%20extends%20Constructor%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20throw%20new%20Error()%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A

### PR DESCRIPTION
**Pull request by weswigham**
Fixes another part of #30732

Fixes #26627

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
Does this fix #26627?

**Comment by weswigham** [comment]
Huh, the perf failure is due to a regression in _emit time_ in _x64 only_ in _older node only_. @rbuckton - any insights?

**Comment by weswigham** [comment]
Yep, this fixes #26627

**Comment by weswigham** [comment]
RWC is clean (failure was just an unaccepted diff of some new baselines in master). The DT failures are all the same as in `master`. Perf seems... odd? As I said, older x64 node _only_ with a regression in _emit time_ only - not check time (and the emit time variance is high, too, at +/- 2-7%, which is sometimes more than the failing diff).

All in all, change seems good. @ahejlsberg wanna review?

**Pull request merged**
