### PR TITLE
Remove optionality for Promise resolve callback

### LINKED ISSUE #36749: `resolve()` of a promise accepts `undefined` when explicit generic type is specified
I am confused. It well can be the result of ECMAScript spec or something, but all this doesn't make sense to me.
**TypeScript Version:**  3.7.x-dev.201xxxxx
**Search Terms:** `promise undefined` and I looked through all of the 5 pages  + looked through FAQ
**Code:**
```TypeScript
type TypeA = {
  value: number;
}
const test = (): Promise<TypeA> => {
  return new Promise<TypeA>(resolve => {
    resolve(undefined); // Result of test() is Promise of TypeA. I return a promise that is resolved with  undefined and it's ok for some reason.
  });
};

const test2 = (): Promise<TypeA> => {
    return Promise.resolve(undefined);
};
test().then(typeAInstance => {
  // At this point here `typeAInstance` is of type TypeA and not! of `TypeA | undefined`
  console.log(typeAInstance.value.toFixed())
});
```

**Expected behavior:**
Both Functions should prevent me from doing writing stupid code at compile time.

**Actual behavior:**
Only second one does prevent me. First one allows runtime error to happened in the end.

**Playground Link:** http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200211&ssl=1&ssc=1&pln=14&pc=4#code/C4TwDgpgBAKuEEEoF4oG8BQUoDcCGANgK4QBcUAdkQLYBGEATgNwYC+GAxgPYUDOwUYBH4ooACgCU5AAoMu1AJa8IAHjiQEAPhTbM2BhGBEGFShADuUWfKWr1iTWIO8uBHNGS6s2KM9fuxIgoAEwgAMwUKCGCJFmxWWLYWbj4BIX4AJlFJGTlFZTV4LR10b31DY1NrfIgAOj83CECQ8MjoxNYWdOBJWuAACwgKMVANAElUvAoODy9sFJcCOoIuAHMRoon+KZna-GI64C4AMQUAD2jJCTZYoA

**Related Issues:** 

I don't understand where this `undefined` as one of the potential argument types  is coming from:
Screen Shot 2020-02-12 at 7 38 11 PM

My `lib.es5.d.ts` contains this:
```TypeScript
declare type PromiseConstructorLike = new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void) => PromiseLike<T>;
```

My `lib.es2015.promise.d.ts` contains this:
```TypeScript
new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
```

### PR DESCRIPTION
**Pull request by rbuckton**
This makes `value` required in the `resolve` callback for a new `Promise`. This shouldn't affect the ability to call `resolve()` without an argument when creating a `new Promise<void>`, as we already have logic in place that allows us to parameters whose types are `void` as optional.

Fixes #36749

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
@RyanCavanaugh, @weswigham, @DanielRosenwasser: This one is interesting because its an *improvement* for TypeScript code, but results in "breaks" for JavaScript code. 

In TS, the expectation is that `new Promise<number>(resolve => resolve())` should be an error, and that `new Promise<void>(resolve => resolve())` shouldn't, and that's fine. However, in the JS projects we use as part of the user test suite, they might just use `new Promise(resolve => resolve())` and we'll infer the type argument as `unknown`. This results in "breaks" in JS code because `unknown` doesn't follow the same rule for parameter optionality that `void` does.

It's a fairly small fix that in general is an improvement, however I'm not sure whether we would consider the JavaScript "breaks" as enough of a breaking change to hold off on merging this until 4.1, so some feedback here would be appreciated.

**Comment by weswigham** [comment]
Hm.... I mean, `unknown` includes `void` and `undefined` in its domain; perhaps the rule allowing the parameter to be dropped should be extended to types-which-possibly-include-void-in-their-domain?

**Comment by rbuckton** [comment]
@DanielRosenwasser, @RyanCavanaugh: I'm still interested in whether this is considered a "break" and if it should wait for 4.1, or if we should consider @weswigham's suggestion to extend the `void` optionality to `unknown` and `undefined` (and maybe `any`) for JavaScript only (in which case this might be feasible for `>=4.0.1 <4.1`)

**Comment by DanielRosenwasser** [comment]
This late in the release, I'd really prefer waiting until 4.1 for anything that feels close to a breaking change.

**Comment by ExE-Boss** [comment]
> This shouldn't affect the ability to call `resolve()` without an argument when creating a `new Promise<void>`, as we already have logic in place that allows us to parameters whose types are `void` as optional.

Does that mean that <https://github.com/microsoft/TypeScript/issues/29131> has been fixed?

**Comment by andrewbranch** [comment]
After discussing it in the design meeting, the suggestion to make trailing `unknown` parameters optional in JS seems reasonable to me. If there’s concern about it, that behavior could potentially be disabled in `--strictNullChecks`, where it might be ok to get people to add a `/** @type {Promise<void> */` (or `@return`, any way of adding the contextual type).

**Comment by rbuckton** [comment]
@typescript-bot user test this

**Comment by rbuckton** [comment]
From the user tests:
### office-ui-fabric
```
@uifabric/build: gulp/tasks/browserAdapters.ts:58:7 - error TS2554: Expected 1 arguments, but got 0.
@uifabric/build: 58       resolve();
@uifabric/build:          ~~~~~~~~~
@uifabric/build:   ../node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
@uifabric/build:     33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
@uifabric/build:                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
@uifabric/build:     An argument for 'value' was not provided.
```

This is due to the fact that the promise created [here](https://github.com/microsoft/fluentui/blob/c6bb7c2f98f9537d592dc6068eeffa15dd1beb8c/scripts/gulp/tasks/browserAdapters.ts#L44) has no type argument is inferred to `Promise<unknown>`. As this is a `.ts` file, we do not consider the value optional here, so this error is expected.

### xterm.js
```
src/browser/Terminal2.test.ts(80,11): error TS2554: Expected 1 arguments, but got 0.
```

This is again due to an [untyped `Promise`](https://github.com/xtermjs/xterm.js/blob/f811fb937e2f75aef8285647b9969b0cfd945ed0/src/browser/Terminal2.test.ts#L76) in a ts file being inferred to `unknown` and is expected of this change.

### adonis-framework
```
node_modules/adonis-framework/src/Static/index.js(45,18): error TS2554: Expected 1 arguments, but got 0.
```

This is due to the fact this is a .js file and our user tests compile js files with `--strictNullChecks`, so this error is expected. Without `--strictNullChecks`, #40057 would kick in and allow you to elide the argument.

### chrome-devtools-frontend
```
node_modules/chrome-devtools-frontend/front_end/bindings/FileUtils.js(210,33): error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => any'.
...
node_modules/chrome-devtools-frontend/front_end/persistence/FileSystemWorkspaceBinding.js(526,106): error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => any'.
...
node_modules/chrome-devtools-frontend/front_end/test_runner/TestRunner.js(28,5): error TS2554: Expected 1 arguments, but got 0.
...
node_modules/chrome-devtools-frontend/front_end/test_runner/TestRunner.js(207,40): error TS2322: Type '(value: any) => void' is not assignable to type '() => void'.
...
node_modules/chrome-devtools-frontend/front_end/test_runner/TestRunner.js(502,107): error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => any'.
...
node_modules/chrome-devtools-frontend/front_end/test_runner/TestRunner.js(947,58): error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => void'.
node_modules/chrome-devtools-frontend/front_end/test_runner/TestRunner.js(981,55): error TS2345: Argument of type '(value: any) => void' is not assignable to parameter of type '() => void'.
...
node_modules/chrome-devtools-frontend/front_end/timeline/ExtensionTracingSession.js(20,7): error TS2322: Type '(value: any) => void' is not assignable to type '() => any'.
```

In these cases, the promises need an appropriate contextual type. Some are typed as `Promise<any>` as that is the default inference in a .js file, and the resulting `resolve` callback argument is no longer considered optional and is thus unassignable to the jsdoc type `function()`. In one case, the promise is contextually typed to `Promise<undefined>` but the jsdoc type should be rewritten to `Promise<void>`.

### npm
```
node_modules/npm/lib/auth/legacy.js(12,81): error TS2554: Expected 1 arguments, but got 0.
```

This is again due to the fact we compile our JS user tests using `--strictNullChecks` and the promise has no contextual type.

### puppeteer
```
src/common/LifecycleWatcher.ts(137,7): error TS2322: Type '(value: void | PromiseLike<void>) => void' is not assignable to type '() => void'.
src/common/Target.ts(95,21): error TS2322: Type '(value: boolean | PromiseLike<boolean>) => void' is not assignable to type '() => void'.
src/node/BrowserFetcher.ts(548,28): error TS2345: Argument of type '(fulfill: () => void, reject: (Error: any) => void) => void' is not assignable to parameter of type '(resolve: (value: void | PromiseLike<void>) => void, reject: (reason?: any) => void) => void'.
  Types of parameters 'fulfill' and 'resolve' are incompatible.
```
- `LifecycleWatcher.ts` - This one is interesting. Even though we consider `void` to be "optional" for calls, we do not consider it to be optional for assignability purposes. 
- `Target.ts` - This looks like a bug in the user code. The promise is clearly typed as `Promise<boolean>`, but its resolve callback is being assigned to a field of type `() => void`, meaning that it is likely never resolved correctly (which is the kind of bug this PR intends to catch).
- `BrowserFetcher.ts` - As with `LifecycleWatcher.ts`, this is a case where we don't treat a `void` parameter as optional for assignability, only for calls.

@DanielRosenwasser, @RyanCavanaugh:

Regarding our existing support for treating trailing `void` parameters as optional, it seems we have a bug in that we only treat them as optional for calls, but not for assignability purposes. I will file that as a separate issue.

I'm also considering the possibility of giving an `await` expression whose value is unused the contextual type of `void | PromiseLike<void>`, for example:

```js
async function foo() {
    // type is `Promise<unknown>`.
    const x = new Promise(() => {});

    // type is `Promise<void>`
   await new Promise(() => {});
}
```

The result would be that some of the above errors would get the correct contextual type when the result is unused. I can create a separate PR for this case, which we can possibly discuss at the next design meeting.

**Comment by rbuckton** [comment]
I've filed https://github.com/microsoft/TypeScript/issues/40227 for the assignability related issue.

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
### User Tests

User Tests show expected breaks for js-only projects. These breaks don't exist when not in strict mode, and are addressable via `/** @type */` jsDoc type assertions.

### DT Tests
There are some breaks in DT tests that may need to be addressed:
  - [ ] `electron-spellchecker` - `Error in electron-spellchecker\nOK` - Unsure what is wrong here as there is no output.
  - [ ] `electron-prompt` - `Error in electon-prompt\nOK`
  - [ ] `electron-window-state` - `Error in electon-window-state\nOK`
  - [ ] `electron-localshortcut` - `Error in electon-localshortcut\nOK`
  - [ ] `memcached` - `Expected 1 arguments, but got 0`. These may be due to incorrect calls to `resolve` in the tests and if so are the kind of error this PR is intended to catch.
  - [ ] `system-task` - `Expected 1 arguments, but got 0`
  - [ ] `async-stream-emitter` - `Expected 1 arguments, but got 0`
  - [ ] `graphql-relay` - `Expected 1 arguments, but got 0`
  - [ ] `node-wit` - `Expected 1 arguments, but got 0`
  - [ ] `react-window-infinite-loader` - `Expected 1 arguments, but got 0`
  - [ ] `stream-demux` - `Expected 1 arguments, but got 0`
  - [ ] `undertaker` - `Expected 1 arguments, but got 0`
  - [ ] `xml` - `Expected 1 arguments, but got 0`
  - [ ] `listr` - `Expected 1 arguments, but got 0`
  - [ ] `mirrorx` - `Expected 1 arguments, but got 0`
  - [ ] `nightmare` - `Expected 1 arguments, but got 0`
  - [ ] `polka` - `Expected 1 arguments, but got 0`
  - [ ] `react-router-guard` - `Expected 1 arguments, but got 0`
  - [ ] `redux-form/v4` - `Expected 1 arguments, but got 0`
  - [ ] `redux-form/v5` - `Expected 1 arguments, but got 0`
  - [ ] `snapsvg` - `Argument of type (value: unknown) => void' is not assignable to a parameter of type '() => void'. Seems like the kind of error this PR is intended to produce.
  - [ ] `react-virtualized` - `Type '(value: unknown) => void' is not assignable to type '() => void'`. Seems like the kind of error this PR is intended to produce.
  - [ ] `fetch-mock` - Seems like the type specified to be assignable to `PromiseConstructor` is wrong and needs to be addressed in `fetch-mock`.
  - [x] `aframe` - `Property 'setHSL does not exist on type 'string | number | Color`. **Unrelated to this change**.

In general it seems the DT tests need to be updated, but that shouldn't be too difficult as correctly supplying an argument would be a backwards-compatible change.

### RWC Tests

Test failures in RWC seem to be expected and fall into the following categories:
- Untyped `Promise` usage in checked JS files in `--strict` mode.
- Untyped `Promise` usage in TS files when passing the `resolve` callback (whose type is `(value: unknown) => void`) to a function that expects `() => void`, which is the kind of error this PR is intended to produce.
- Expected changes to existing errors due to a change in the call signature for `resolve`.

### Summary

All errors in DT, User, and RWC tests are the expected outcome of this change. The DT tests mentioned above can be addressed by a backwards-compatible PR to DefinitelyTyped, which I can create prior to merging this PR.

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
All of the current failures in the DT test are due to the work @sandersn is doing to flip `"typesVersions"` and are unrelated to this change. It appears all of the failures from the previous DT test were addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47216

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
One last time, now that hopefully dtslint-runner is fixed...
@typescript-bot run dt

**Review by andrewbranch — APPROVED** [review]

**Comment by jfirebaugh** [comment]
FYI, this is a breaking change for utility functions that externalize the `resolve` and `reject` functions passed to the `Promise` constructor:

```ts
export function promiseResolveReject<T = void>(): [Promise<T>, (value?: T | PromiseLike<T>) => void, (reason?: any) => void] {
  let resolve: (value?: T | PromiseLike<T>) => void;
  let reject: (reason?: any) => void;
  const promise = new Promise<T>((resolve_, reject_) => {
    resolve = resolve_;
    reject = reject_;
  });
  return [promise, resolve!, reject!];
}
```

Error:

```
../../ts/src/util.ts(14,5): error TS2322: Type '(value: T | PromiseLike<T>) => void' is not assignable to type '(value?: T | PromiseLike<T> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'T | PromiseLike<T> | undefined' is not assignable to type 'T | PromiseLike<T>'.
      Type 'undefined' is not assignable to type 'T | PromiseLike<T>'.
```

**Comment by rbuckton** [comment]
Yes, this is a breaking change, but one that is a change in correctness that adds type-safety. The prior definition was unsafe as it allowed you to pass `undefined` to a `resolve` for a `Promise<number>`. Custom logic around `resolve` will unfortunately need to be updated to ensure correctness.

Above, you would need to change `let resolve` to `let resolve: (value: T | PromiseLike<T>) => void`, and the return type of the function to `[Promise<T>, (value: T | PromiseLike<T>) => void, (reason?: any) => void]`. There is no way for us to do that automatically.

CC @DanielRosenwasser to document in the 4.1 release notes that this is a breaking change intended to improve type safety.

**Comment by thw0rted** [comment]
I just upgraded to 4.1, and I'm trying to follow the conversation here and at https://github.com/microsoft/TypeScript/pull/40231 and https://github.com/microsoft/TypeScript/issues/41497.  My main problem is that, in code like this:

````ts
const p = new Promise<number | undefined>(resolve => {
  if (Math.random() > 0.5) { resolve(1); }
  else { resolve(); }
});
````

the type of `resolve` is `(value: number | PromiseLike<number | undefined> | undefined) => void` rather than `(value?: number | PromiseLike<number | undefined>)` which means that the call to `resolve()` with no argument is flagged.  I can pass an explicit `undefined` but this is against our style guide and our linter complains about it.  I can't change the Promise to `number | void` because the caller expects to assign the result to a `number | undefined`.

I think we're stuck changing our style guide to allow passing `undefined` explicitly, but I'd like to know what the team's intent was here -- maybe I'm missing something.

**Comment by osdiab** [comment]
I have this code in my codebase:

```
  return new Promise((resolve, reject) => {
    writeStream.on("finish", () => {
      resolve();
    });
    writeStream.on("error", (error) => {
      reject(error);
    });
  });
```

it doesn't actually parameterize `Promise` so I expected it to be fine, but I get the error that i need to provide a value for `resolve`; I'm walking around it by explicitly saying that this is a `Promise<void>` but it's def not what I expected, should the `Promise` generic default to `void` perhaps? `Promise<T = void> { ... }` and if you provide a non-void value I believe it would infer correctly anyway.

**Pull request merged**
