### PR TITLE
Show a diff when the  public api baselines fail

### PR DESCRIPTION
**Pull request by orta**
This uses the [jsdiff](https://github.com/kpdecker/jsdiff#readme) library which is already in our dependency tree to echo out the public API baseline differences. 

### Why

These tend to fail more on master, and you don't get to see what's up: https://github.com/microsoft/TypeScript/runs/779388787?check_suite_focus=true#step:4:170

### Alternatives

- We detect for CI via `process.env.CI` and _always_ do this for all baselines
- We use the `FourSlash.showTextDiff`, I did this initially, but it doesn't do a good job on large files as it prints the entire thing, not a focused subset

Looks like:
Screen Shot 2020-06-17 at 7 14 21 AM

----

If/when this is +1'd - I'll edit the PR to remove the failing test

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by orta** [comment]
Yeah, it shows failing results in the pack: https://typescript.visualstudio.com/TypeScript/_build/results?buildId=76845&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ec339c2b-c439-539d-f401-d5569bbc95f9

**Comment by andrewbranch** [comment]
@orta how hard would it be to un-red the diff? It’s red because it’s part of the error message but at a glance I read that whole thing as deleted lines.

**Comment by DanielRosenwasser** [comment]
I guess get rid of the test comment and let's merge

**Comment by orta** [comment]
I did both, will merge on green

**Pull request merged**
