### PR TITLE
Fix object spread runtime semantics

### LINKED ISSUE #31469: Destructuring object polyfill isn't equivalent to new JS
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** Destructuring object Polyfill assign

**Code**

```ts
const k = { o: 1, b: 2 };
const o = {
	o: 3,
	...k,
	b: k.o++,
};

console.log(o)
```

**Compiles to**
```js
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var k = { o: 1, b: 2 };
var o = __assign({ o: 3 }, k, { b: k.o++ });
console.log(o);
```

Compiling to `__assign({ o: 3 }, k, { b: k.o++ })` is not equivalent to the order in which the JS would execute. What would be equivalent is `__assign(__assign({ o: 3 }, k), { b: k.o++ })`

**Expected behavior:** { o: 1, b: 1 }

**Actual behavior:** {o: 2, b: 1}

**Playground Link:**  https://www.typescriptlang.org/play/#src=const%20k%20%3D%20%7B%20o%3A%201%2C%20b%3A%202%20%7D%3B%0Aconst%20o%20%3D%20%7B%0A%09o%3A%203%2C%0A%09...k%2C%0A%09b%3A%20k.o%2B%2B%2C%0A%7D%3B%0A%0Aconsole.log(o)

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
This fixes the runtime semantics for object spread for ES2017 and earlier.

We cannot call `__assign` with more than two elements, since any element could cause side effects. For
example:
```js
var k = { a: 1, b: 2 };
var o = { a: 3, ...k, b: k.a++ };
// expected: { a: 1, b: 1 }
```

If we translate the above to `__assign({ a: 3 }, k, { b: k.a++ })`, the `k.a++` will evaluate before
`k` is spread and we end up with `{ a: 2, b: 1 }`.

This also occurs for spread elements, not just property assignments:
```js
var k = { a: 1, get b() { l = { z: 9 }; return 2; } };
var l = { c: 3 };
var o = { ...k, ...l };
// expected: { a: 1, b: 2, z: 9 }
```

If we translate the above to `__assign({}, k, l)`, the `l` will evaluate before `k` is spread and we
end up with `{ a: 1, b: 2, c: 3 }`

Fixes #31469

### CODE REVIEW

**Comment by rbuckton** [comment]
CC: @weswigham, @RyanCavanaugh 
It looks like the GitHub suggested-reviewers API is down again so I can't add reviewers.

**Comment by rbuckton** [comment]
I wouldn't recommend it since you could, in theory, load two different TypeScript built outputs as scripts into the global scope and one would conflict with the other. If we changed the semantics to accept only a fixed set of arguments we'd probably need to rename the function and ship *both* in tslib.

**Comment by weswigham** [comment]
Yich, the compatibility/versioning story for tslib (and global helpers emitted by tsc) is pretty ugly then, isn't it. We could minimally use a simplified helper in module output, but....

**Comment by weswigham** [comment]
@rbuckton can we merge an RWC baseline update that's just the changes caused by this? I think I see some other unexpected baseline changes outstanding for RWC, but they're hard to pick out.

**Pull request merged**
