### PR TITLE
Add the Omit helper type

### LINKED ISSUE #30455: Add `Omit` as a known interface
## Search Terms

`Omit`

## Suggestion

Add the following type to lib.d.ts: 

```ts
type Omit<ObjectType, KeysType extends keyof ObjectType> = Pick<ObjectType, Exclude<keyof ObjectType, KeysType>>;
```

## More 
Origin : https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-420919470

From : https://github.com/sindresorhus/type-fest/blob/0226ef2092ee2b07a8714c832d106da659877a8f/index.d.ts#L75 `Please open new issues on TypeScript about making it built-in.`. I searched but couldn't find an issue, so here it is :rose:

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #30455.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot run dt

**Comment by DanielRosenwasser** [comment]
The only breakages on DefinitelyTyped seem to be

* amap-js-api
* amap-js-api-indoor-map
* amap-js-api-map3d

And those all really come from [`amap-js-api` unnecessarily plopping `Omit` in the global scope](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8de4063df7ae1ca492311a251caae02ff052ec32/types/amap-js-api/type-util.d.ts#L1-L3).

**Comment by DanielRosenwasser** [comment]
[A fix is now out to DefinitelyTyped's `amap-js-api` package.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34454)

[I used BigTSQuery to partially assess the breakage](https://bigtsquery.firebaseapp.com/query?selector=SourceFile:not(%5BexternalModuleIndicator%5D)%20%20%3E%20TypeAliasDeclaration%20%3E%20Identifier%5Bname%3DOmit%5D) with the following query

```
SourceFile:not([externalModuleIndicator]) > TypeAliasDeclaration > Identifier[name=Omit]
```

BigTSQuery isn't fully up to date (@urish out of curiosity, how recent is the dataset?), but we saw three distinct results:

* an old fork of [hollowverse](https://github.com/forabi/hollowverse/blob/441fc303a98e587ca462443ad7350b624534d40a/custom-typings/helpers.d.ts#L3) (@forabi)
* an old revision of [ArragroCMS.Examples](https://github.com/Arragro/ArragroCMS.Examples/commit/d0d1360a61d57b3ab2c7ae73781cf39d39a1ee3c) (thanks @mike-jewell)
* [this one test case we have in our repository](https://github.com/Microsoft/TypeScript/blob/b8f6ae4e256f2a5f47fe45b7fcfccfec941dc994/tests/cases/compiler/indexedAccessRetainsIndexSignature.ts#L3)

Also:

* [There are no global `InterfaceDeclaration`s named `Omit`](https://bigtsquery.firebaseapp.com/query?selector=SourceFile:not(%5BexternalModuleIndicator%5D)%20%20%3E%20InterfaceDeclaration%20%3E%20Identifier%5Bname%3DOmit%5D)
* [There are no global `ClassDeclaration`s named `Omit`](https://bigtsquery.firebaseapp.com/query?selector=SourceFile:not(%5BexternalModuleIndicator%5D)%20%20%3E%20ClassDeclaration%20%3E%20Identifier%5Bname%3DOmit%5D)

**Comment by DanielRosenwasser** [comment]
We discussed this at #30738 and believe that the breakage can be easily communicated and is more limited than we initially anticipated.

**Comment by levenleven** [comment]
Keys are not limited to `keyof T`. Is that on purpose?

**Comment by vkrol** [comment]
@levenleven
> Should we constrain K in the official definition?

> Nah

https://github.com/Microsoft/TypeScript/issues/30738

**Comment by DanielRosenwasser** [comment]
`Exclude` doesn't constrain its second type parameter on the first, so we felt like it would be strange to do that with `Omit`.

**Comment by DanielRosenwasser** [comment]
Note, if you feel that shouldn't be the case, I'd encourage you to open up a separate issue to discuss it.

**Comment by urish** [comment]
@DanielRosenwasser the BigTSQuery dataset has last been updated around June 2018. If you find it useful, I can spend some time updating it

**Comment by felixfbecker** [comment]
Can `Omit` please be made strict before 3.5 moves to stable? https://github.com/microsoft/TypeScript/issues/30825

**Comment by RyanCavanaugh** [comment]
@felixfbecker the definition was intentional.

**Comment by leoyli** [comment]
> `Exclude` doesn't constrain its second type parameter on the first, so we felt like it would be strange to do that with `Omit`.

But how a bout the case of `Pick`? Pick do constrain the use case.

`Pick`: pick members from a group to get a sub-group;
`Omit`: omit members in a group to get a sub-group;

As you can see, these 2 helper types are somehow complimentary. Looks pretty nature and intuitive when we use them together. How come `Omit` being permissive and `Pick` isn't???

When we make comparison, compare `Omit` with `Exclude` is like compare egg with chicken.  `Exclude` is comparable with `Extract` not `Omit, IMHO.

**Comment by leoyli** [comment]
@DanielRosenwasser 

> `Exclude` doesn't constrain its second type parameter on the first, so we felt like it would be strange to do that with `Omit`.

But how a bout the case of `Pick`? Pick do constrain the use case.

`Pick`: pick members from a group to get a sub-group;
`Omit`: omit members in a group to get a sub-group;

As you can see, these 2 helper types are somehow complimentary. Looks pretty nature and intuitive when we use them together. How come `Omit` being permissive and `Pick` isn't???

When we make comparison, compare `Omit` with `Exclude` is like compare egg with chicken.  `Exclude` is comparable with `Extract` not `Omit, IMHO.

**Comment by OliverJAsh** [comment]
I've ran into a few bugs which would have been caught if `K` was constrained (like it is for `Pick`). Any chance of reconsidering this?

**Comment by KazimirPodolski** [comment]
TypeScript is not open-source, it's source-available.

**Pull request merged**
