### PR TITLE
extract 'convertCompilerOptionsFromJson' to separate function

### LINKED ISSUE #5276: Provide an API to convert tsconfig.json to CompilerOptions
Since IDEs like VS Code use `tsconfig.json` to figure out how to parse a project, it makes sense for all the other build tools (gulp, broccoli, webpack, etc) to pull the tsc config from `tsconfig.json` as well, instead of having their own custom way to configure tsc.

In order for this to be seamless, Typescript needs to provide a way to parse tsconfig.json to `CompilerOptions` object. `tsc` already does this internally, but all of the apis it uses are private.

I've put together my own converter for Angular/broccoli-typescript, but it will get stale with the next version of typescript until I update my option mappings. See `ts-config-converter.ts` added in https://github.com/angular/angular/pull/4779/

I believe that this task is so common that it should be part of typescripts public api.

cc: @alexeagle

### PR DESCRIPTION
**Pull request by vladima**
fixes #5276

### CODE REVIEW

**Comment by vladima** [comment]
@sandersn any other comments?

**Comment by sandersn** [comment]
Looks good :+1:

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by IgorMinar** [comment]
Lgtm! Thanks

**Pull request merged**
