### PR TITLE
Always syntax only

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@mjbvz @minestarks @uniqueiniquity @amcasey @DanielRosenwasser @RyanCavanaugh 
https://github.com/microsoft/TypeScript/pull/38564#issuecomment-628309011 is build where syntaxOnly server can accept semantic commands as tsserver without --syntaxOnly also works as if it was passed in. This is on top of  #38561

**Comment by amcasey** [comment]
This is pretty cool.

**Comment by amcasey** [comment]
Maybe we should disable semantic diagnostics, since a lot of identifiers won't bind?

**Comment by amcasey** [comment]
F12 is showing me entries from lib.es2015.*.d.ts - were we expecting those to get pulled in?

**Comment by amcasey** [comment]
I'm having trouble wrapping my head around exactly how this will work if VS continues to send `openExternalProjects`, but I think I've convinced myself it's not a problem.

**Comment by amcasey** [comment]
I'm excited - I think this will be a great experience during project load.  My main concern is that we might regress the syntax server during normal operation.  I think it's worth moving ahead and making targeted fixes if that turns out to be a problem.

**Comment by sheetalkamat** [comment]
> My main concern is that we might regress the syntax server during normal operation. 
Wont cancellation tokens help with that

**Comment by sheetalkamat** [comment]
> Maybe we should disable semantic diagnostics, since a lot of identifiers won't bind?

Yes i didnt do that here intentionally here till we get some feedback .
I think other potential as compile on save and and similar.. Infact I think enabling selected ones is better approach than disabling few.. Eg completions, quickInfo, goto def,  questionably: find all refs

**Comment by amcasey** [comment]
> > My main concern is that we might regress the syntax server during normal operation.
> 
> Wont cancellation tokens help with that

I expect the memory usage to increase, which could be poorly received by the division (and users, if they notice).  The effectiveness of cancellation is harder to predict because VS has (so far) limited usage of the syntax server to things that need to be "instantaneous" and cancellation may not be fast enough to retain that performance.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Pull request closed without merging**
