### PR TITLE
Prevent valid JSX from being seen as the start of a generic arrow function, fix crashes

### LINKED ISSUE #52449: TS 5.0 internal compiler error: "Debug Failure. Expected 20 <= 19"
# Bug Report

### 🔎 Search Terms

Debug Failure. Expected 20 <= 19

### 🕗 Version & Regression Information

- This is a crash in Nightly (v5.0.0-dev.20230126)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230126#code/DwYw9gdgzgLgBAFTgUwB42RAJlA9APgCgg)

### 💻 Code

```ts
<const T extends/>
```

### 🙁 Actual behavior

```
Uncaught (in promise) Error: Debug Failure. Expected 20 <= 19
    fail https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:1824
    assertLessThanOrEqual https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:1861
    assertDiagnosticLocation https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:12898
    createFileDiagnostic https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:16567
    checkUnusedTypeParameters https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:68475
    checkUnusedIdentifiers https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:68393
    getSuggestionDiagnostics https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:40963
    getSuggestionDiagnostics https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:97949
    runWithCancellationToken https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:97895
    getSuggestionDiagnostics https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:97948
    computeSuggestionDiagnostics https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:110815
    getSuggestionDiagnostics https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:112409
    getSuggestionDiagnostics https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/language/typescript/tsWorker.js:170546
    fmr https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:16402
    d https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:15391
    handleMessage https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:15376
    k https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:15182
    h https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:15151
    handleMessage https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:15144
    onmessage https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:15381
    onmessage https://typescript.azureedge.net/cdn/5.0.0-dev.20230126/monaco/dev/vs/base/worker/workerMain.js:2244
```

### 🙂 Expected behavior

```js
"use strict";
React.createElement("const", { T: true, extends: true });
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #52449

The arrow function lookahead was too overzealous in determining what was "definitely" an arrow function. Switching a "true" to an "unknown" result fixes the issue.

~But, I am suspicious of this because there is no error saying that the variable `const` isn't found (unlike `T`).~

### CODE REVIEW

**Comment by jakebailey** [comment]
Consider me no longer suspicious; it's lowercase so it's an intrinsic.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
The recent esbuild commit regarding generic arrow functions in TSX files is related: https://github.com/evanw/esbuild/commit/8824778ae14d1a9301751d5384d6d9bd6477f1f7

However, there's sort of a mutual exclusivity between the relevant piece of code:

```ts
let fn = async <T> () => {};
```

And this test:

```ts
var x1 = <T>() => {}</T>;
x1.isElement;
```

I'm personally convinced both should parse (and so esbuild doesn't have to change), but I'm not totally sure how to get there given our current goofy arrow function parsing method.

**Comment by evanw** [comment]
Thanks for looking at this!

I'm worried that this PR potentially makes these already-complicated rules too much more complicated. Previously you could definitively tell whether something is an arrow function in JSX or not by examining the next few tokens. I thought that property was kind of nice. But now it depends on a lot more code and arbitrary look-ahead, which adds many more additional ambiguities to resolve.

For example, this PR currently means the following:

```
// JSX
<T extends />;
<T extends {...x} />;
<T extends {...x}>() = {}</T>;

// arrow
<T extends {}>() => {};
<T extends {...x}>() => {};
```

Having to distinguish between `<T extends {...x}>() = {}</T>` and `<T extends {...x}>() => {}` seems like unnecessary complexity to me (i.e. it might mean a lot of additional work for me as the author of another TSX-to-JS transpiler). While `{...x}` isn't currently valid type syntax, I've seen some comments on this issue tracker that sound like it's not out of the question to add it, so it could actually come up in the future.

Anyway, I thought I'd put a plug in for keeping the look-ahead rules for this edge case simple like they were before, instead of (as far as I understand) now requiring unbounded look-ahead and relying on the full details of TypeScript's arrow function parser (including error-recovery for invalid syntax).

It probably doesn't matter too much what's done here IMO since this is an edge case as long as the internal compiler error is fixed. But I was expecting something like the addition of a rule for the `/` token which would return `false` from `isArrowFunctionInJsx`.

**Comment by jakebailey** [comment]
I can understand that; having fixed numerous bugs in this same place it's getting a little frustrating.

I'll try and see if there's a more straightforward way here, but I'm having a little bit of a hard time thinking of how to do it.

**Comment by evanw** [comment]
Some quick thoughts (feel free to disregard). The internal compiler error could potentially be fixed like this:

```diff
 export function rangeOfTypeParameters(sourceFile: SourceFile, typeParameters: NodeArray<TypeParameterDeclaration>): TextRange {
     // Include the `<>`
     const pos = typeParameters.pos - 1;
-    const end = skipTrivia(sourceFile.text, typeParameters.end) + 1;
+    const end = Math.min(sourceFile.text.length, skipTrivia(sourceFile.text, typeParameters.end) + 1);
     return { pos, end };
 }
```

And if you wanted to add support for the `<T extends />` case, it could potentially be added like this:

```diff
 const isArrowFunctionInJsx = lookAhead(() => {
     parseOptional(SyntaxKind.ConstKeyword);
     const third = nextToken();
     if (third === SyntaxKind.ExtendsKeyword) {
         const fourth = nextToken();
         switch (fourth) {
             case SyntaxKind.EqualsToken:
             case SyntaxKind.GreaterThanToken:
+            case SyntaxKind.SlashToken:
                 return false;
             default:
                 return true;
         }
     }
     else if (third === SyntaxKind.CommaToken || third === SyntaxKind.EqualsToken) {
         return true;
     }
     return false;
 });
```

**Comment by jakebailey** [comment]
Oh, funny. I should have tried the latter (I later tried nearly the same thing to fix that other oddity you changed esbuild to match TypeScript on). I'll try it out in the morning.

**Comment by jakebailey** [comment]
That suggestion worked great, thanks!

I don't think we need to modify `rangeOfTypeParameters`, actually; the parser fix means the bad tree no longer appears, so the crash doesn't occur.

**Comment by evanw** [comment]
> I don't think we need to modify `rangeOfTypeParameters`, actually; the parser fix means the bad tree no longer appears, so the crash doesn't occur.

The crash can still occur in other cases such as `<T extends /=>`. Up to you whether you think that's important enough to fix or not (I don't have enough context).

**Comment by jakebailey** [comment]
Ah, you're totally right. I'll add that; we definitely don't want more crashes, even if the code doesn't parse.

**Comment by jakebailey** [comment]
I checked, and your suggested fix is again good; this probably fixes other potential crashes for users of this function in the LS. There's one other place which does a skipTrivia+1 but it's in a place where it's impossible for the file to not continue.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
