### PR TITLE
Resolve only relative references tree in the project (in syntax only mode)

### PR DESCRIPTION
**Pull request by sheetalkamat**
This resolves and follows all relative module references instead of just in open files

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@DanielRosenwasser The relative reference resolutions are also dependent on `rootDirs` option in config file. I am wondering if we should create inferred configured project that only reads options from config file  and not file list so we give more accurate result.. Thoughts?

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
I'm not quite as concerned with `rootDirs`, but maybe that's a bias of not having seen it nearly as much. If we're willing to read the `tsconfig.json`, then we probably also want to respect path mappings from the `paths` field too.

**Comment by DanielRosenwasser** [comment]
By the way, what's the difference between this and #39476?

**Comment by DanielRosenwasser** [comment]
Oh, is the idea that you would load up the entire project *except* for non-relative modules (e.g. `node_modules` imports)? From a gut feel, I don't think that that's desirable. I think a lot of codebases are large enough from their own size and we really want to minimize program construction time.

**Comment by sheetalkamat** [comment]
Thats correct.. It constructs relative reference tree and ignores node_module imports. 
The other one just resolves only in open file (only relative references)

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
Closing this since we definitely dont want whole tree.

**Pull request closed without merging**
