### PR TITLE
Handle variable declaration without initializer in Convert to ES6 Module

### LINKED ISSUE #21786: TypeError: Cannot read property 'kind' of undefined in 'Object.isIdentifier' during 'getApplicableRefactors'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.19.3
**command requested**: getApplicableRefactors
**hitting sessions**: 5469
**proportion of all sessions**: 0.0204163913496321
**stack**
```
TypeError: Cannot read property 'kind' of undefined
    at Object.isIdentifier (tsserver.js:9638:20)
    at Object.isExportsIdentifier (tsserver.js:7262:19)
    at Object.isExportsOrModuleExportsOrAlias (tsserver.js:19987:19)
    at isAtTriggerLocation (tsserver.js:80032:31)
    at isAtTriggerLocation (tsserver.js:80037:44)
    at Object.getAvailableActions (tsserver.js:80009:21)
    at unknown (tsserver.js:77123:128)
    at getIterator (tsserver.js:1733:23)
    at Object.next (tsserver.js:1728:35)
    at Object.arrayFrom (tsserver.js:2267:32)
    at Object.getApplicableRefactors (tsserver.js:77122:23)
    at Object.getApplicableRefactors (tsserver.js:83337:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:90194:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89150:61)
    at unknown (tsserver.js:90393:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90384:28)
    at IOSession.Session.executeCommand (tsserver.js:90393:33)
    at IOSession.Session.onMessage (tsserver.js:90413:35)
    at Interface.<anonymous> (tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by amcasey**
Fixes #21786 

@andy-ms I just guessed, so feel free to suggest a better solution.

### CODE REVIEW

**Comment by andy-ms** [comment]
Did you mean fixes #21810?

**Comment by andy-ms** [comment]
Never mind, I see that's a separate issue.

**Comment by amcasey** [comment]
Looks like it could be a dup though?

**Comment by andy-ms** [comment]
Have a separate fix for that at #21843. Will rebase that once this is in.

**Comment by amcasey** [comment]
@mhegazy Shall I port this to 2.7?

**Pull request merged**
