### PR TITLE
fix #11480, disallow delete operator on readonly property or index  signature

### LINKED ISSUE #11480: Deleting from readonly dictionary does not give a type error
**TypeScript Version:**  2.0.0, 2.0.3, nightly (2.1.0-dev.20161010)

**Code**

``` ts
// A *self-contained* demonstration of the problem follows...
'use strict';

interface X { readonly [key: string]: string }

const x: X = Object.freeze({
    "a": "A",
    "b": "B",
    "c": "C"
});

// Error: TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
x["a"] = "B";

// No error - but runtime exception
// TypeError: Cannot assign to read only property 'a' of object '#<Object>'
delete x["a"];
```

**Expected behavior:**
`delete x["a"];` should give a compile-time error (as it predictably leads to a runtime error later on).

**Actual behavior:** 
No compile-time error is given.

**Design Limitation (?)**
I understand that this may be a design limitation as in #11180, in this case, this is another vote for the --strictReadonlyChecks flag discussed in #11180.

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
Fixes #11480 

It changed more tests than I thought. Should we check delete operator only if it is a property access or indexer?

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Looks good to me. Pretty stupid that we allowed `delete x;` before

**Comment by HerringtonDarkholme** [comment]
Sorry, I didn't catch your point. 

Do you mean "check readonly property only when delete property access or indexer" is good or "disallow delete anything other than property access or indexer"?

For the latter, I think it would break namespace.
```typescript
namespace A {
  export var a = 123;
  delete a;
}
```

And it would break unintentional code like 

```typescript
// in other file like html
window.globalProperty = 123
// in ts
declare var globalProperty
delete globalPropery
```

**Comment by RyanCavanaugh** [comment]
I believe both of those should be errors for the sake of clarity (unless there are some compelling use cases from real code to bring up).

In the namespace case, it would be very confusing because the behavior would have to change (to become an error) depending on whether you wrote `export` (since non-exported vars don't become properties). Writing `delete A.a` is much clearer.

In the global case, we often require globals to be prefixed by `window.` anyway, which seems like the correct thing to do here as well. And since we'd have to resolve this differently in modules vs non-modules anyway, it's also confusing in that regard.

**Comment by HerringtonDarkholme** [comment]
@ahejlsberg I found `resolvedIndexInfo` is removed in #11929 . Is it intended? 
I need indexInfo in `checkDeleteExpression`, otherwise I need to handle delete in `getPropertyTypeForIndexType`

**Comment by mhegazy** [comment]
@HerringtonDarkholme can you refresh the PR.

**Comment by HerringtonDarkholme** [comment]
@dotnet-bot test ci please

**Comment by mhegazy** [comment]
@dotnet-bot test ci please

**Pull request merged**
