### PR TITLE
Make 'calendar' and 'numberingSystem' open strings in es2020.intl.

### LINKED ISSUE #42885: 'calendar' and 'numberingSystem' should not be string literals
@orta this should be revised/reverted. List of numbering system & calendar are NOT part of the ECMA402 spec. They conform to Unicode Locale Identifier semantic restriction, but the list can change every CLDR version which is separate from ECMA402.

Reference of failure upstream: https://github.com/formatjs/formatjs/issues/2616

_Originally posted by @longlho in https://github.com/microsoft/TypeScript/issues/42134#issuecomment-780844690_

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #42885

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@longlho please take a look and let me know whether I've missed anything.

**Comment by DanielRosenwasser** [comment]
Just as a heads up @batisteo, it looks like we won't be able to keep the change to use union types from #41880.

**Comment by longlho** [comment]
Thanks a lot for the quick fix! LGTM!

**Review by longlho — APPROVED** [review]

**Review by batisteo — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.2

**Comment by DanielRosenwasser** [comment]
And thank you for your patience and persistence - we appreciate the time to explain why a revert was the appropriate decision.

**Comment by longlho** [comment]
np happy to help!

**Pull request merged**
