### PR TITLE
move to code actions update and tests

### PR DESCRIPTION
**Pull request by justschen**
Fixes #https://github.com/microsoft/TypeScript/issues/58387

as discussed in the sync, we added the additional check to `implicit` and also mirrored the fixes from `move to file` for `move to new file`. 

a lot of tests were added (if excessive we can delete), and fixes to `move to new file` were added but also understand that `move to new file` will likely be deprecated anyways eventually. 

___

### regarding changing: https://github.com/microsoft/TypeScript/blob/5c21b7fd93cc60b05d560f931fb8bb26d7972f76/tests/cases/fourslash/moveToNewFile_prologueDirectives4.ts#L8

since `getApplicableRefactors` defaults to `implicit`:
https://github.com/microsoft/TypeScript/blob/5c21b7fd93cc60b05d560f931fb8bb26d7972f76/src/harness/fourslashImpl.ts#L4454

the test was changed to have no refactorings (to match our proposed case).

___

### regarding `implicit` vs `invoked`:
Check for `implicit` to follow our idea for `manual requested in vs code` vs. `not manually requested in vs code`, but let me know if our logic here makes sense!

cc. @aiday-mar @mjbvz

### CODE REVIEW

**Comment by justschen** [comment]
update @aiday-mar, looks like `triggerReason` gets passed all the way from typescript extension:

https://github.com/microsoft/vscode/blob/cdf94536b9dafc36582d2ecfd246897c6feb7d72/extensions/typescript-language-features/src/languageFeatures/refactor.ts#L551

```typescript
private toTsTriggerReason(context: vscode.CodeActionContext): Proto.RefactorTriggerReason | undefined {
	return context.triggerKind === vscode.CodeActionTriggerKind.Invoke ? 'invoked' : 'implicit';
}
```

which gets propagated thru `CodeActionTriggerKind` between automatic and invoke which we set in the model 👍

**Comment by aiday-mar** [comment]
Looks good, thanks!

**Comment by justschen** [comment]
cc. @andrewbranch @navya9singh @DanielRosenwasser (realized i never pinged or mentioned you guys on this 😨)

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Review by navya9singh — APPROVED** [review]

**Comment by justschen** [comment]
@andrewbranch @navya9singh awesome thanks guys! feel free to merge when ready (I'm not authorized here 🔢 )

**Pull request merged**
