### PR TITLE
Make isDefinition aware of declaring symbol

### LINKED ISSUE #42889: Add way to differentiate references for definitions at requesting location
# Bug Report

### 🔎 Search Terms

- references
- find all references

### Problem
We use the `references` request to power VS Code's references code lens feature. References returned by TS have an optional `isDefinition` property that tells if the reference is to a definition or not. We use this to avoid showing multiple references for a case such as:

```ts
function foo(a: number): number;
function foo(a: string): string;
function foo(a: string | number): string | number;
```

The references code lens basically just filtered out any references that are marked `isDefinition`

However this also prevents us from showing the correct reference count in cases such as:

```ts
interface IFoo {
    foo(): void;
}

class Foo implements IFoo {
    foo(): void { }
}
```

In this case, the two references to `foo` should have 1 reference, but we show 0 references because both references are definitions.

https://github.com/microsoft/vscode/issues/117021 shows another case with object literal shortcut

### Proposal
We'd like a new property on the references response that tells us if the reference belongs to definition from the requesting location (not yet sure what the name of this should be).

For a case with overloads such as:

```ts
function foo(a: number): number;
function foo(a: string): string;
function foo(a: string | number): string | number;
```

If we request references on any of the calls to `foo`, this new property would be marked true. However it would not be true in cases such as:

```ts
export const foo = 123;

console.log({ foo });
```

or:

```ts
interface IFoo {
    foo(): void;
}

class Foo implements IFoo {
    foo(): void { }
}
```

### PR DESCRIPTION
**Pull request by sandersn**
After this PR, `isDefinition` is only true when the declaring symbol is found, and the declaration for the reference's node is one of the symbol's declarations.

This improves the References Codelens, fixing the cases in #42889. 
Edit: Previously, I changed isDefinition for commonjs assignment declarations. The current PR now has a simple workaround for this case. I put the old discussion at the bottom.

## Remaining work ##

I still need to update a lot of baselines. However, the change itself is ready to review.

Fixes #42889

### Old ###

One change is with CommonJS aliases:

```js
// @filename: a.js
function f() { }
module.exports.f = f

// @filename: b.js
const { f } = require('./a')
f/**/
```

Previously `module.exports.f = f` has `isDefinition: true` and didn't contribute to `f`'s reference count. Now it has `isDefinition: false`, and it does.
This is arguable, since it's not a particularly interesting reference, even though it's technically correct. But fixing will involve re-creating the ad-hoc commonjs alias resolution code from the checker. I don't think it's worth it for an edge case like this.

### CODE REVIEW

**Comment by sandersn** [comment]
@mjbvz You're probably interested in this too.

@amcasey I tagged you on the review because this changes `isDefinition` for VS too. However, I think it's a good change -- basically a fix to an incomplete implementation. The only question is whether the old behaviour is critical to VS in some way. (I doubt it.)

**Review by mjbvz — APPROVED** [review]
LGTM

Here are the two places in the VS Code codebase where we use this property:

https://github.com/microsoft/vscode/blob/a4b011697892ab656e1071b42c8af4b192078f28/extensions/typescript-language-features/src/languageFeatures/references.ts#L35

https://github.com/microsoft/vscode/blob/73ae56b82b0fd268cab08e5903666025c1f6c335/extensions/typescript-language-features/src/languageFeatures/codeLens/referencesCodeLens.ts#L44

I think the new behavior makes sense in both instances

**Comment by sandersn** [comment]
Looking over the baselines, I can see that the changes are pretty much universally improvements.

**Comment by rchl** [comment]
I've noticed regressions in my tests that tests references returned from the typescript API.

For documents:
1. foo.ts
```ts
export function doStuff(): boolean {
    return true;
}
```
2. bar.ts
```ts
import { doStuff } from './foo';
doStuff();
```

getting references for `doStuff();` in `bar.ts`, one of the returned references is:

```
    {
      "file": "/../bar.ts",
      "start": {
        "line": 1,
        "offset": 10
      },
      "end": {
        "line": 1,
        "offset": 17
      },
      "contextStart": {
        "line": 1,
        "offset": 1
      },
      "contextEnd": {
        "line": 1,
        "offset": 33
      },
      "lineText": "import { doStuff } from './foo';",
      "isWriteAccess": true,
      "isDefinition": true
    },
```

where `isDefinition` is `true` while before `4.5.2` it was `false`.

Is that an intended change?

It seems to be problematic for the future I have that allows findings all callers of given symbol but with that change the import statement is included as a caller which doesn't seem right.

**Comment by rchl** [comment]
No comments about whether this is intended changed or not?

**Comment by amcasey** [comment]
ping @sandersn

**Comment by sandersn** [comment]
Yes, that change is intended. An import is not one of the declarations of `doStuff` in your example. Find-all-callers should be a subset of find-all-references -- `[doStuff]` is another example of a non-call reference that would have been included even before this change.

**Comment by rchl** [comment]
OK, thanks for clarifying.

**Pull request merged**
