### PR TITLE
Contextually type inherited properties (WIP)

### LINKED ISSUE #1373: Consider contextually typing class member functions by their base class/interface members
here is my code

```ts
    export enum SortDir
    {
        Asc,
        Desc,
        Flip
    }

    export interface ISortInfo
    {
        getvalue(x: QuerySummary): any; //change to number|string in TypeScript 1.4
        order: SortDir;
        ordercalc?: number;
    }

    class SortByQueryId implements ISortInfo
    {
        getvalue = x => x.QueryId;
        order = SortDir.Flip;
    }
```

when I type "x." I expect to see the properties of QuerySummary but I do not. VS still thinks the type is 'any'

### LINKED ISSUE #3667: Contextually type class property initializers by `extends`/`implements` types
When a property has exactly one type from an `extends` or `implements` clause, we should contextually type that property's initializer by the type from the clause. For example:

```ts
interface ThingListener {
	handleEvent: (x: MouseEvent) => void;
}

class Foo implements ThingListener {
	handleEvent = x => {
		// No error, but this code is incorrect
		console.log(x.timestamp);
	}
}
```

Ideally we could take this one step further when widening. The following behavior is also undesirable:
```ts
interface HasLength {
	length: number
}

class Foo implements HasLength {
	// length: any, not really what we intended
	length = undefined;
}

var x = new Foo();
x.length = 'wat'; // should not be allowed
```

e.g. #3666

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #3667. Fixes #1373. This code is based on a previous approach at #6118 and still needs some cleanup.

### CODE REVIEW

**Comment by sandersn** [comment]
@DanielRosenwasser here is the WIP version of inherited typing. It still has some contextual typing machinery in there that I will see if I can remove.

**Comment by appsforartists** [comment]
@sandersn Looks like this hasn't been touched in over a year.  What's the status here?

@DanielRosenwasser, @alexeagle , and I were talking the other day about #6118, and wondering if a path forward would be to only enable it with `noImplicitAny`.  That way, there's no backwards compat problem (because `noImplicitAny` means any code that could be contextually typed going forward would be explicitly typed now).  Moreover, if you end up with weirdness (like `typeof item === Item` instead of `Subitem`), you can fix it with explicit typing.

**Comment by sandersn** [comment]
@appsforartists: Briefly, irreconcilable problems with every approach we've tried. However, we haven't given up hope that some solution exists; we just haven't tried for 6 months or so. @DanielRosenwasser, if you want to resurrect this maybe we can talk about it in person to understand whether hiding it behind a flag would work.

On a pessimistic note, I re-read my notes on this PR that I made on #6118, and I noticed that the one bug it finds is also found by `--noImplicitAny`. So the feature might not prevent that many real bugs.

**Comment by appsforartists** [comment]
From my POV, it's less about finding bugs and more about making code easier to maintain.  Mix-ins, for instance, are a pain currently in TypeScript because you have to maintain each one's signature in two places (once in an interface and again in the implementation).

Then again, you clearly see value in solving this, so I don't need to sell you on it.  😃

**Comment by bios21** [comment]
Is there another PR incoming for this?
Most of the issues about this I've seen are closed. 

Also I've found nothing neither on the Roadmap or StackOverflow.
Is there any weirdly way to achieve the "basic"
```ts
interface I {
  f(n: number): string;
  p: string;
}
class C implements I {
  f = n => n.toString(); // n is correctly typed as `number`
  p = undefined; // correctly retains type `string`
}
```
from #6118 ?

**Pull request closed without merging**
