### PR TITLE
Update README.md, CONTRIBUTING.md and SECURITY.md

### LINKED ISSUE #58185: Update README.md, CONTRIBUTING.md and SECURITY.md to reduce mistakes
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Update README.md, CONTRIBUTING.md and SECURITY.md to reduce mistakes.

### PR DESCRIPTION
**Pull request by skanda890**
Fixes #58185

### CODE REVIEW

**Comment by skanda890** [comment]
> This PR doesn't have any linked issues. Please open an issue that references this PR. From there we can discuss and prioritise.

Check again.

**Comment by MartinJohns** [comment]
From the [Pull Request template](https://github.com/microsoft/TypeScript/blob/main/.github/pull_request_template.md?plain=1):

> ** Please don't send typo fixes! **  
> Please don't send a PR solely for the purpose of fixing a typo, unless that typo truly hurts understanding of the text. Each PR represents work for the maintainers, and that work should provide commensurate value.

Besides that, what is the point of these PR that you seemingly do for many repositories? Is this based on some automatic tool? Because some of the changes you do are **clearly wrong**.

For example, you added the word "or" again, which was already rejected in your other PR. Why do you do this again?

The name of the tool "fourslash" is wrongly replaced with "four slashes".

In another change you replace "commit" with "commits", which makes no sense in this context. You're basing your PR on a single commit, not on multiple commits.

You also replace a **tool command** "runtests" with "run tests", which will just not work and result in an error when trying to call it.

**Comment by skanda890** [comment]
> From the [Pull Request template](https://github.com/microsoft/TypeScript/blob/main/.github/pull_request_template.md?plain=1):
> 
> > ** Please don't send typo fixes! **
> > Please don't send a PR solely for the purpose of fixing a typo, unless that typo truly hurts understanding of the text. Each PR represents work for the maintainers, and that work should provide commensurate value.
> 
> Besides that, what is the point of these PR that you seemingly do for many repositories? Is this based on some automatic tool? Because some of the changes you do are **clearly wrong**.
> 
> For example, you added the word "or" again, which was already rejected in your other PR. Why do you do this again? The sentence is grammatically correct as it is.
> 
> You replace "a number of" with "some", changing the meaning and purpose of the sentence.
> 
> You unnecessarily replace "labelled" with "labeled", while "labelled" is valid spelling.
> 
> Changing "rebases against main" to "rebases against **the** main" is just more confusing in this context.
> 
> The name of the tool "fourslash" is wrongly replaced with "four slashes".
> 
> In another change you replace "commit" with "commits", which makes no sense in this context. You're basing your PR on a single commit, not on multiple commits.
> 
> You also replace a **tool command** "runtests" with "run tests", which will just not work and result in an error when trying to call it.

Grammarly changed that.

**Comment by RyanCavanaugh** [comment]
@skanda890 stop sending PRs that are just the result of you running automated tools on files. This is going to introduce more manifest errors than it does fix real problems. Consider this the first and last warning.

**Pull request closed without merging**
