### PR TITLE
Delete the {} and unconstrained type parameter assignability rule

### LINKED ISSUE #32330: Generic bounds not enforced on generic argument
**TypeScript Version:** typescript@3.6.0-dev.20190710, 3.5.1

**Search Terms:** generic bounds toString

**Code**

```ts
function f1<T>(o: T) {
  o.toString(); // error
  // This is expected, because T might be undefined or null
}

function f2<T extends {}>(o: T) {
  o.toString(); // no error
  // This is expected, this is the correct way to fix the above function.
}

function user<T>(t: T) {
  f1(t);  // Allowed, but irrelevant because f1() is invalid
  f2(t);  // Allowed?  <- this is the bug
  t.toString();  // Error, expected for the same reason as f1()
}
```

**Expected behavior:**
You should not be able to pass an arbitrary T into a function that demands `T extends {}`.

**Actual behavior:**
Despite `.toString()` being disallowed both in user() and in f1(), you can just pass it to f2() and still call `toString` on the same value.

**Playground Link:** 
http://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMAjAHgCoD4AUcBciGAlIgN4BQiicAdFHAMpQBOMYA5jsQNwUC+FCqEiwEyAEyZEAUwAeUGWAAmAZ3L9cBIqUrU6DZm07c+g4eGjwkIVTJaZcUQiXJVkKHFF7vgErz7UUPRMrOxcPuZAA

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #32330

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

If our baselines are any indication, removing this legacy compat rule is preeeeeeety breaky, but, much like the base change of constraint from `{}` to `unknown`, seems to call out a bunch of places where unsound stuff was going on.

**Comment by sandersn** [comment]
@weswigham I think the next step is to post an analysis of the breaks. Are there a lot? Are they worth it?

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by weswigham** [comment]
> Are there a lot?

Yes. Mostly, an unconstrained type parameter is no longer assignable to `{ [key: string]: any; }` or `Object` or `{}` (and it shouldn't be - `null` and `undefined` aren't...), which is apparently an assumption made in a bunch of types (mongodb, antd, immutable, a small bit of werpack, and some office-ui-fabric in the user suite, plus a bunch in RWC, and knex, mongodb, pouchdb, inquirer, wordpress, slickgrid, mangopay, dialogflow-fulfillment, d3, topojson-client, styled-components (!!!), rrc, mithril, redux-orm, some react components, and jsnox in DT).

Honestly, it looks like a lot in the DT error log, but it's not that bad; there are just some incorrect usages in some very depended-upon packages.

Y'know, it just seems like anywhere where people went "T is our unconstrained schema definition, right? right" not realizing that `string` and `undefined` probably aren't valid schema objects. (Or the types predate `object`)

> Are they worth it?

Maybe. Generally speaking, in pretty much every single break, the break can be fixed by writing an explicit `extends object`, as that's normally the original intent.

**Comment by weswigham** [comment]
Also, ourselves: The sanity check LKG build on pipelines catches us making the same mistake:
```ts
src/services/shims.ts(574,73): error TS2345: Argument of type '() => T' is not assignable to parameter of type '() => {}'.
  Type 'T' is not assignable to type '{}'.
src/services/shims.ts(575,62): error TS2352: Conversion of type '{}' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  '{}' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
src/services/utilities.ts(2744,88): error TS2769: No overload matches this call.
  Overload 1 of 2, '(array: readonly {}[], f: (x: {}, i: number) => U): U[]', gave the following error.
    Argument of type '(x: T, i: number) => U' is not assignable to parameter of type '(x: {}, i: number) => U'.
      Types of parameters 'x' and 'x' are incompatible.
        Type '{}' is not assignable to type 'T'.
          '{}' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
  Overload 2 of 2, '(array: readonly {}[] | undefined, f: (x: {}, i: number) => U): U[] | undefined', gave the following error.
    Argument of type '(x: T, i: number) => U' is not assignable to parameter of type '(x: {}, i: number) => U'.
      Types of parameters 'x' and 'x' are incompatible.
        Type '{}' is not assignable to type 'T'.
          '{}' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
src/services/utilities.ts(2744,96): error TS2345: Argument of type 'T | readonly T[]' is not assignable to parameter of type 'T'.
  Type 'readonly T[]' is not assignable to type 'T'.
    'readonly T[]' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
src/services/utilities.ts(2751,9): error TS2322: Type '{} | T' is not assignable to type 'T'.
  Type '{}' is not assignable to type 'T'.
    '{}' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint '{}'.
```

Namely in `shims` and `core` we were using some `{}` where we should have been using `unknown`.

**Comment by DanielRosenwasser** [comment]
From the design meeting: try to see whether we can at least give an actionable error on this change for users.

**Comment by sandersn** [comment]
@weswigham do you want to keep working on this? Seems like it got stuck adding an error.

**Comment by weswigham** [comment]
@sandersn This is now synced, _and_ has an informative related span that picks out the type parameter causing the error and suggests giving it an `extends object` constraint.

**Comment by weswigham** [comment]
@sandersn do you want to re-milestone this/add it to a design meeting backlog again?

**Comment by sandersn** [comment]
Let's bring it up at the design meeting.

**Comment by sandersn** [comment]
Did we ever bring this up at a design meeting? We miiight be able to squeeze it in before variance tomorrow or more likely next week.

**Comment by weswigham** [comment]
Based on my comments saying I implemented design meeting feedback (a helpful related span), we probably did at least once, but not again after that, given there's no linked notes.

**Pull request closed without merging**
