### PR TITLE
Don't add completion for method if the `this` parameter doesn't match

### LINKED ISSUE #20608: Intellisense suggests methods with mismatched "this" parameter types
**TypeScript Version:**  2.6.2

**Code**

```ts
class ValueWrapper<T> {
    constructor(private readonly value: T) {}

    public getValue(): T {
        return this.value;
    }

    public isZero(this: ValueWrapper<number>): boolean {
        return this.value === 0;
    }
}

const stringWrapper = new ValueWrapper<string>("hello");
const numberWrapper = new ValueWrapper<number>(42);
```

**Expected behavior:**

Intellisense should only suggest the `isZero` method on `numberWrapper`, but not for `stringWrapper`.

**Actual behavior:**

Intellisense does not filter out suggestions based on `this` param types. 
(screenshot from the Typescript Playground)

suggest

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20608

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Are we okay with this change if it means you can't get completions to use `.call`, `.bind`, or `.apply`?

**Comment by andy-ms** [comment]
I would think so because it's unusual to do `a.foo.call(b)` when `foo` is a method. (This change wouldn't affect a property.)
If you meant that we wouldn't get completions for `function f() {} f./**/`, I don't see why, because `call` has a parameter `this: Function` and `typeof f` should be assignable to `Function`.

**Comment by andy-ms** [comment]
Waiting for confirmation from @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
👍

**Pull request merged**
