### PR TITLE
charCodeAt defaults to first index: index is optional

### PR DESCRIPTION
**Pull request by SamuelMarks**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

Fixes #

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Why is this desirable? If I saw `str.charCodeAt()` I would have no idea what to expect. My best guess would be `NaN` but it looks like `charCodeAt` is more aggressive than most JS functions at rejecting non-numeric inputs, e.g. `"foo".charCodeAt("bar")` is `102`

**Comment by SamuelMarks** [comment]
@RyanCavanaugh Well I suppose it's a toss up between desirable and what is actually supported.

**Comment by DanielRosenwasser** [comment]
I don't think it's necessarily a problem to be a little more prescriptive in our `.d.ts` files. As an example, `isNaN` takes a `number` according to `lib.d.ts`, but in reality `isNaN` takes a value of any type.

**Comment by SamuelMarks** [comment]
Hmm, admittedly now that I think about it this is expected behaviour:
```
> isNaN()
true
```

**Comment by mhegazy** [comment]
Thanks for your PR. these files are not manually edited, they are auto-generated from a script in . You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

For future references, please file an issue first to track changes.

**Pull request closed without merging**
