### PR TITLE
Of keyword classification

### PR DESCRIPTION
**Pull request by JsonFreeman**
The 'of' keyword was not being classified because I forgot to change LastToken to point to OfKeyword.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
The API tests don't count as tests. :wink:

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Lexical classifier test?

**Comment by DanielRosenwasser** [comment]
Add another syntactic classifier test with a for-in/regular for loop.

**Comment by DanielRosenwasser** [comment]
Great work! :+1: once the tests pass.

**Pull request merged**
