### PR TITLE
Revert "Revert "Support declaration emit for late bound element acces…

### LINKED ISSUE #33569: Handle element access expressions in JS/TS with late-bound names
After #33220 adds support for late-bound assignment declarations, we still need work on better declaration emit support for those constructs.
See [this comment thread](https://github.com/microsoft/TypeScript/pull/33220#discussion_r321930029).

### PR DESCRIPTION
**Pull request by weswigham**
…ses assigned to functions in both TS and JS (#36593)" (#37034)"

This reverts commit 4d5464e1f9ab415cc0fdce59f3d88a4be203c2f2.

Fixes #33569

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot user test this so I can keep around a log of the `enhanced-resolve` failure until I isolate the issue.

**Comment by sandersn** [comment]
@weswigham is this meant for merging? Or is it waiting for additional fixes after you figure out the enhanced-resolve failure?

**Comment by weswigham** [comment]
Waiting for an additional fix~

**Comment by sandersn** [comment]
What is the additional fix?

**Comment by weswigham** [comment]
Mmmmm, sorry, I haven't gotten back to it yet; but I'm pretty sure I need to rethink how the cjs merge/late bound exports/normally bound exports merge sequence happens in its entirety. What this change does right now is ultimately a kind of hack; but the reason I tried that is because the alternative is essentially scrapping the current "cjs module symbol merge" model in the checker. It's not _great_, but I didn't _really_ want to undertake redoing it to better integrate with normal symbol member resolution if I could help it. The `enhanced-resolve` break  just proved that this hack wasn't robust enough for the real world, so the more complete work (to make it so "cjsy" exports are looked up either by normal export or late bound export resolution without overwriting the symbol) is required, probably.

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.

**Pull request closed without merging**
