### PR TITLE
ignore me, testing user tests

### PR DESCRIPTION
**Pull request by jakebailey**
For eventually testing https://github.com/microsoft/typescript-error-deltas/pull/119

### CODE REVIEW

**Comment by jakebailey** [comment]
What the

**Comment by jakebailey** [comment]
@typescript-bot user test this

**Comment by fatcerberus** [comment]
> What the

Yeah, this new `microsoft-github-policy-service` bot is... weird.  I've already seen it post 7+ closure notices in a row on issues marked as duplicates.

**Comment by jakebailey** [comment]
Where? Do you have a link?

Right now it's just that this service changed and so we can't post from typescript-bot anymore (and are moving off onto other stuff) but the duplicate handling should have already been moved to a new system.

**Comment by fatcerberus** [comment]
I haven't noticed it recently, typescript-bot seems to be closing them again.  This was the most recent one I could find with repeated closure notices: https://github.com/microsoft/TypeScript/issues/54490

**Comment by jakebailey** [comment]
Yeah, then we're good; that was fixed in #54566 and #54579.

**Comment by jakebailey** [comment]
@typescript-bot user test this

**Pull request closed without merging**
