### PR TITLE
Remove portability error when emitting declarations for incremental mode

### LINKED ISSUE #37960: Allow configuration of NodeBuilderFlags.AllowNodeModulesRelativePaths for un-distributed mono repos
## Search Terms

- AllowNodeModulesRelativePaths
-  The inferred type of ... cannot be named without a reference to ...
- #29808 
- https://github.com/microsoft/TypeScript/issues/30858
- https://github.com/microsoft/TypeScript/pull/27340

## Suggestion

Allow the optional use of `AllowNodeModulesRelativePaths` during declaration creation 

## Use Cases

I understand why @weswigham added https://github.com/microsoft/TypeScript/pull/27340 and it is correct for most consumers, especially those that publish packages for consumption on NPM. 

However, it seems like for npm style mono-repos where packages are only consumed locally and not published to a registry, it is valid to have seemingly non-portable TS references (lerna, pnpm, rush, yarn workspaces). A relative path to a node_module may still be valid as long as the structure stays consistent, which it does for this style of mono repo with a single node_modules directory. 

I am using a mono repo managed by Bazel and rules_nodejs and users are experiencing issues with the creation of declaration files that otherwise would contain relative paths to node_module files. https://github.com/bazelbuild/rules_nodejs/issues/1013

(The conversation in https://github.com/microsoft/TypeScript/issues/30858 was helpful, however, it seemed to still be focusing on resolving portable types, which is only necessary when distributing the declaration files. If they are consumed locally, portability is not a concern. 

## Examples

I'm not sure the best way (or standard way) for these flags to be set, however, I imagine an entry in the TSConfig Compiler Options would make the most sense: 

```diff
interface CompilerOptions {
  ...
+  allowUnportableDeclarationImports: true
} 
```

Currently I am patching Typescript to toggle on this  behavior and it appears it is working just as expected.

[typescript+3.7.3.patch.txt](https://github.com/microsoft/TypeScript/files/4476155/typescript%2B3.7.3.patch.txt)

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #37960

### CODE REVIEW

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
I dont think we need this change.. The test case you have will give exact same result atleast with nightly with or without your change

**Comment by evelant** [comment]
@sheetalkamat  This still seems to be an issue as of ts 4.8.3 when working with a pnpm mono repo.

**Comment by MaximSagan** [comment]
@weswigham Is there a blocker for getting this merged? There are still repos that are needing to patch TypeScript (as described in #37960) to get around this issue.

**Comment by sandersn** [comment]
@weswigham can you confirm whether this PR changes behavior with respect to main? Sounds like at least a couple of people are still seeing it.

**Comment by weswigham** [comment]
After looking into this again, I just don't think this is a good idea - while the declaration files for `incremental` aren't _necessarily_ there to be shipped, they *can* be, and the original issue requestors weren't even using `incremental` in the first place. IMO, this error is just a known caveat of using `incremental` or `composite` (or `declarations`), and the correct fix is just doing what is asked in the error and adding an explicit type annotation at the indicated location (in so doing, you usually are forced to realize the transitive typing dependency yourself and choose how to resolve it!). If we ever swap our incremental metadata from declaration files to something less-human-consumable, maybe we can relax this rule then.

**Pull request closed without merging**
