### PR TITLE
Ignore external modules that are included only through source of external module

### LINKED ISSUE #33926: TS 3.7 pollutes completion with inner modules used in referenced projects
**TypeScript Version:** 3.7.0-dev.20191010

**Search Terms:**
project references, composite, completion

**Code**

Clone https://github.com/asvetliakov/typescript-references-completion-issues
1) yarn
2) yarn run tsc -b
3) Go to src/module/mod.ts
4) Start typing ```const b: IA``` to trigger completion list

**Expected behavior:**
No symbols from ```aws-sdk```, e.g. ```IAM``` since ```aws-sdk``` is being used only in the inner module

**Actual behavior:**
see completion symbols from ```aws-sdk```

setting ```"disableSourceOfProjectReferenceRedirect": true``` to true resolves the problem, but i'd rather to not disable such good feature if possible

**Related Issues:** None

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #33926
Forgot to create this as draft, but note that this isn't ready for review since I doubt that the issue reported is actually desired behavior

### CODE REVIEW

**Comment by sheetalkamat** [comment]
I am not sure if we should be fixing this at all.. 
The repro has package json with dependency to `aws-sdk` so technically the behavior before this fix is better since the import wouldn't be wrong. The problem with repro is that the referenced project (files and config) is inside the root project and both project reference and root share the node_modules, Even in the test I wrote, if I `disableSourceOfProjectReferenceRedirect` is true and inner test exports something from `aws-sdk` we would start getting the auto import suggestions from the `aws-sdk`
@andrewbranch  can you comment on this since you have more context on what should happen here (may be @DanielRosenwasser has some input too)

**Comment by andrewbranch** [comment]
From original issue:

> No symbols from aws-sdk, e.g. IAM since aws-sdk is being used only in the inner module

This is not a behavior we should be asserting anything about right now—the fact that you only get auto-import suggestions once a package has been referenced once in your project is just a symptom of an implementation detail. It’s inconsistent with what happens with `@types` packages (you get suggestions for those eagerly, because we include them in your program automatically), and lots of people have asked if we can provide auto-imports for other packages eagerly.

Conversely, if the two projects had separate node_modules directories, we should ensure that unreachable auto-imports don’t leak from one to the other, but I _think_ that case is already handled today.

**Comment by asvetliakov** [comment]
[quote]
The problem with repro is that the referenced project (files and config) is inside the root project and both project reference and root share the node_modules
[/quote]
What about monorepo structure with hoisted ```node_modules``` folder ? technically a sub-projects share it too, but may have different ```package.json``` files.
Anyway, if the fix won't be included, what is your recommendation for the project structure in this case? Move the inner project to the separate private package ?

**Comment by andrewbranch** [comment]
@asvetliakov I’m not sure if I’m understanding your scenario correctly, so let me see:

```
/monorepo/
  node_modules/
    aws-sdk/
  packages/
    a/
      package.json { "aws-sdk": "*" }
      a.ts
      tsconfig.json { "composite": true }
    b/
      package.json {}
      b.ts
      tsconfig.json { "references": [{ "path": "../a" }] }
```

In this case, you should _not_ get import suggestions from `aws-sdk` in `b.ts`, because it does not exist in the only `package.json` visible to `b.ts`. If you do, that’s a bug. Does that answer your question?

**Comment by asvetliakov** [comment]
@andrewbranch 
Yes, thanks.

**Pull request closed without merging**
