### PR TITLE
Remove redundant code from `getResolvedSignatureWorker`

### PR DESCRIPTION
**Pull request by Andarist**
while investigating what extra tests I should add as part of https://github.com/microsoft/TypeScript/pull/52679 i noticed that some pieces here might not be needed (at least according to the existing test suite)

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot user test
@typescript-bot test top100

**Review by andrewbranch — CHANGES_REQUESTED** [review]
`getParseTreeNode` returns undefined when the input node is transformed. This is here to prevent crashes when API consumers try to do something they shouldn’t do. I think we want to keep it.

**Comment by Andarist** [comment]
In such a case, there is no point in this PR. More meaningful changes in this code are happening [here](https://github.com/microsoft/TypeScript/pull/52679) anyway

**Comment by Andarist** [comment]
@andrewbranch I got curious about this case - is there a way to write a unit~ test that would cover this scenario? 🤔

**Pull request closed without merging**
