### PR TITLE
Narrow via discriminant property through optional chain

### LINKED ISSUE #40397: Type refinment with optional chaining
**TypeScript Version:**  v4.0.2

**Search Terms:** optional chaining, type refinement

**Code**

```ts
type A = {
  type: 'A';
  name: string;
}

type B = {
  type: 'B';
}

// example one
function funcOne (arg: A | B | undefined) {
  const errorOne = arg?.name; // unexpected error ❌

  errorOne; // expected `string | undefined` but got `any`

  return errorOne;
}

// example two
function funcTwo (arg: A | B | undefined) {
  // note the optional chaining in the condition
  if (arg?.type === 'B') {
    arg; // `B`
    return 'B';
  }

  arg; // `A | B | undefined` ❌

  // arg cannot be of type B here
  const errorTwo = arg?.name; // unexpected error ❌

  return errorTwo;
}

// same as example 2, but no optional chaining in the condition
function funcTwoButWorks (arg: A | B | undefined) {
  // no optional chaining
  if (arg !== undefined && arg.type === 'B') {
    arg; // `B`
    return 'B';
  } 

  arg; // `A | undefined` ✅

  const result = arg?.name; // no error, yay ✅

  return result;
}
```

**Expected behavior:**
- in `funcOne` there should be no error and the result should be of type `string | undefined`.
- in `funcTwo` after the the if condition check `arg` should be of type `A | undefined`.

**Actual behavior:**
- in `funcOne` errors for optional chaining instead of inferring the type as `string | undefined`
- in `funcTwo` it does not extract type B from possible values for `arg`

**Playground Link:** [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeAoKVSQFxQOQ1wG40oA7AQwFsIcBnYAJwEtSBzYgXxRU2gCEEyErxy4+RFFxQB6aVAgAPKmAA20APakIKAGYBXUgGNgTTVH1GA8lqgAKcg1Y44AHygC3BgCYQdLCF4AlELohpr08gwM6gzW0IgOrAD8AHQU1IRQslAGipDGAZHRDFCAMuTc6BBRMXGZ2XkQBV5QAAb0zGxQnqQ+flpeLVAARnrAUKzqYy3kpCAtFVAMEMB6DKRFNVqc3PVKlKrQwADu6roGxqbrFoYAKid2ic5d7s-evv5BIVlypJOHABYaMAmTTkFRQQz-cgsFisKAsDCAiGaLxMEGkEhMHQPRypXgIeCIMS4YKodDoRJ1OQtPjzcmLZardbE4joKQUxxU1quF7dXofQblEjZRIQma-MZDDTY-ECQFLEhhUgRKrFO7qQSJVLpCBc3IKfLAQqqmJlBZLFZrDYMdXbGRyWhUaDkWjyPYHKAAJgANMNRmQNepgZcwRCoTDOgjgEilaj0WcjOjzOd1XxRgB1GIAa1d9kcTzcHhyPXe-VJwp+geDoPBkOhpFhmOxebhAEJCcX+f0oAAyHtQRIpfGEonicv0ynfVq0kjoC1MvDiVlQDhQBaT7ItHlvPoBQaAUHIFkqIktaHoVGMEri0k6ub9rb6QOQQFBDyR51bT+fgJwgA) 

**Related Issues:** maybe [38136](https://github.com/microsoft/TypeScript/issues/38136).

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40397

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by andrewbranch** [comment]
User and RWC tests are clean

**Comment by sandersn** [comment]
I'm still tweaking the DT tests, and the DT run was going to give the wrong output, so I cancelled the current run. I'll start a new one:

@typescript-bot run dt

**Review by weswigham — APPROVED** [review]

**Pull request merged**
