### PR TITLE
do not make inferences with the same source\target pair multiple times

### PR DESCRIPTION
**Pull request by vladima**
partial fix for #7081 
```ts
var a = new Rx.Subject<string>();
var b = new Rx.Subject<Immutable.Set<number>>();
var c1 = a.withLatestFrom(b, x => x); // 1

```
Total compilation time for an original repro case (above) has dropped from +20 minutes to 1.5s (check time: ~0.9s ). However caching is local to every inference session so it still scales pretty badly

Number of times line (1) appear in the code | Check time (s)
------------ | -------------
1 | 0.93
5 | 1.12
10 | 1.37
20 | 1.79
40 | 2.75
80 | 4.54
160 | 8.28
320 | 15.59 

Note: I'm not sure how to write a self-contained test for this issue without including `rx.all.d.ts` and `immutable.d.ts`

### CODE REVIEW

**Comment by vladima** [comment]
as a subsequent step we can set the maximum depth of nesting when we explore the structure of types during type inference. This approach seems to be promising and it scales better - these are numbers for the same test with max depth = 5

Number of times line (1) appear in the code | Check time (s)
------------ | -------------
1 | 0.81
5 | 0.88
10 | 0.93
20 | 1.08
40 | 1.27
80 | 1.72
160 | 2.69
320 | 4.49 

However before moving forward I'd like to verify that setting max depth does not lead to serious regressions in type inference in our real world code test suite.

**Comment by DanielRosenwasser** [comment]
LGTM, others should take a look

**Comment by mhegazy** [comment]
:+1:

**Comment by sandersn** [comment]
Does this address the checking of `typeof C` vs instantiated `typeof C` in a generic static function? If so, you can use the test from #7138, at 7a48fb27ffefe7fb03ad6ceb6a0c3e5a39630c11.

**Comment by vladima** [comment]
no, #7097 is not fixed with this change

**Comment by sandersn** [comment]
Oh well. :( :+1:, but with the caveat that my grasp on the caching mechanism is not too strong.

**Pull request merged**
