### PR TITLE
This handles when packages are symbol links in mono repo like scenarios to use source files instead of output d.ts from project reference

### LINKED ISSUE #34723: When monorepo like packages are linked through symlink and are not built editor cant resolve modules
@sheetalkamat - I am trying this out and noticed that it doesn't work in the case of things that are imported from the outDir rather than the src (in the case of a monorepo):

image

For a quick way to verify this, I prepared a monorepo for you to check it out:

https://github.com/kenotron/TypeScriptMonoRepo/tree/ts3.7

Things work okay if you do "yarn && yarn build", but if I understand this feature, it is meant to address the case where you can start editing in VS Code with Intellisense even before having to build something because we're traversing source rather than output.

_Originally posted by @kenotron in https://github.com/microsoft/TypeScript/pull/32028#issuecomment-545637314_

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #34723

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by kenotron** [comment]
This works! I've updated my branch to contain the tgz from this fix. Feel to test that out as well!

**Comment by sheetalkamat** [comment]
@RyanCavanaugh @DanielRosenwasser do we want this for 3.7 and is there going to be another 3.7 patch? I chatted with @kenotron offline and it seems to work for his scenario.

**Comment by kenotron** [comment]
> @RyanCavanaugh @DanielRosenwasser do we want this for 3.7 and is there going to be another 3.7 patch? I chatted with @kenotron offline and it seems to work for his scenario.

This is almost immediately going to provide lots of value for the 3.7 proj refs to source feature in monorepo scenarios. Lots of happy monorepo TS users there!

**Comment by sarpik** [comment]
Just tried this out myself and can confirm that it works (typescript + yarn workspaces).

After updating the typescript version, I just needed to restart `vscode` and that's it!

Good job @sheetalkamat & @kenotron - I'd love this included in `3.7` c:

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.7

**Pull request merged**
