### PR TITLE
Pin dependencies in release branch

### PR DESCRIPTION
**Pull request by amcasey**
With this change, you can build the branch using `npm ci && npm run build`.

### CODE REVIEW

**Comment by amcasey** [comment]
I'd like to do this for every release branch, going forward.  Re-adding people to the PR, since they probably care more now that it's not about 3.3. :smile:

**Comment by weswigham** [comment]
Should we also edit https://github.com/microsoft/TypeScript/blob/master/.github/workflows/new-release-branch.yaml to do this, while we're at it?

**Comment by amcasey** [comment]
@weswigham What is it?

**Comment by weswigham** [comment]
It's a bot powered workflow for setting up new release branches~

**Comment by amcasey** [comment]
@weswigham TBH, I prefer @andrewbranch's suggestion that we move to an automatically updated, checked in package-lock.json in master.  However, if we decide not to pursue that option, I agree that automating this process would be worthwhile.

**Comment by amcasey** [comment]
I want to merge this regardless of what we decide to do in master.  Objections?

**Comment by sandersn** [comment]
:+1: for this while we decide on a general solution.

**Pull request merged**
