### PR TITLE
allow type narrowing with NonNullExpression

### LINKED ISSUE #36958: non-null assertions break CFA
**TypeScript Version:**  3.7.x-dev.20200221

**Search Terms:**

**Code**

```ts
const m = ''.match('');
m?.[0] && m[0];
m?.[0]! && m[0];
m?.[0].length! > 0 && m[0];
m?.[0].split('').slice() && m[0];
m?.[0].split('')!.slice() && m[0];
```

**Expected behavior:**

```ts
const m = ''.match('');
m?.[0] && m[0]; // ok
m?.[0]! && m[0]; // ok
m?.[0].length! > 0 && m[0]; // ok
m?.[0].split('').slice() && m[0]; // ok
m?.[0].split('')!.slice() && m[0]; // ok
```

**Actual behavior:**

```ts
const m = ''.match('');
m?.[0] && m[0]; // ok
m?.[0]! && m[0]; // error
m?.[0].length! > 0 && m[0]; // error
m?.[0].split('').slice() && m[0]; // ok
m?.[0].split('')!.slice() && m[0]; // error
```

**Playground Link:** http://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200221&ssl=5&ssc=34&pln=4&pc=28#code/MYewdgzgLgBAtjAvDA5CgdHAhlYALACjQEoBuAKDgH50BtABgF0YAyF+Bxi6upgQlbs4nbjU7oANgFMwAcyh4BAPhj1BHJqN6N0EAA4SAllCIpiuo8CkFi64Zspimug8dPE+Fw1Zt2RQA

**Related Issues:**

### PR DESCRIPTION
**Pull request by uhyo**
Happy hacktoberfest! 🎃🥳

Fixes #36958.

## Example

**Code**

```ts
const m = ''.match('');
m! && m[0];
m?.[0]! && m[0];
```

**Current Behavior** (TS 4.1 Beta)

```
src/36958.ts:2:7 - error TS2531: Object is possibly 'null'.

2 m! && m[0];
        ~

src/36958.ts:3:12 - error TS2531: Object is possibly 'null'.

3 m?.[0]! && m[0];
             ~


Found 2 errors.
```

**New Behavior**

(no errors)

## Details & Discussion

This PR enables type narrowing when condition is a NonNullExpression.

The original issue includes following example, but this PR does not fix that case.

```ts
m?.[0].length! > 0 && m[0];
```

To fix this case, we have to take `expr > 0` and similar expressions into consideration, which I think is too complex compared to the outcome. How do you think?

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Review by weswigham — APPROVED** [review]
Assuming the perf tests come back OK (always a good idea to check with control flow changes), this looks great to me.

**Comment by weswigham** [comment]
@sandersn @ahejlsberg should this be 4.1 or 4.2 bound?

**Comment by sandersn** [comment]
I'd lean 4.2, but it's a small change so if the perf results come back clean, 4.1 would be OK too.

**Comment by ahejlsberg** [comment]
If perf looks good I'm fine with having this in 4.1.

**Review by ahejlsberg — APPROVED** [review]

**Pull request merged**
