### PR TITLE
Hack to allow concat to work even when an Array isn't assignable to ReadonlyArray

### LINKED ISSUE #20268: polymorphic arguments validation error
**TypeScript Version:**  2.7.0-dev.20171126 
(Introduced in 2.6)

**Code**

```ts
type Processor<T extends object> = <T1 extends T>(subj: T1) => T1
function doStuff<T extends object, T1 extends T>(parentProcessors: Array<Processor<T>>, childProcessors : Array<Processor<T1>>) {
    childProcessors.concat(parentProcessors);
}
```

**Expected behavior:**
pass validation (polymorphism etc.)

**Actual behavior:**
Error:(3, 28) TS2345:Argument of type 'Processor<T>[]' is not assignable to parameter of type 'Processor<T1> | ReadonlyArray<Processor<T1>>'.
  Type 'Processor<T>[]' is not assignable to type 'ReadonlyArray<Processor<T1>>'.
    Types of property 'indexOf' are incompatible.
      Type '(searchElement: Processor<T>, fromIndex?: number | undefined) => number' is not assignable to type '(searchElement: Processor<T1>, fromIndex?: number | undefined) => number'.
        Types of parameters 'searchElement' and 'searchElement' are incompatible.
          Types of parameters 'subj' and 'subj' are incompatible.
            Type 'T1' is not assignable to type 'T1'. Two different types with this name exist, but they are unrelated.
              Type 'T' is not assignable to type 'T1'.
                Type 'object' is not assignable to type 'T1'.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20268
Uses `T[] | ReadonlyArray<T>` instead of just `ReadonlyArray<T>`. There are probably a bunch of other places where we would need to do this to fix this error in general, but better to wait on #20454 for those instead.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Have you run this on RWC?

**Comment by andy-ms** [comment]
Will do tomorrow.

**Comment by andy-ms** [comment]
There are some rwc failures on master, but I compared this branch to master and didn't see any differences.

**Comment by ahejlsberg** [comment]
@mhegazy @sandersn This PR appears to account for 50% of the slowdown we've seen in the checker between 2.6.2 and 2.7. It single-handedly slows down the check phase of compiling the compiler by about 7%. I haven't researched exactly why, but I suspect it has to do with us performing lots of structural comparisons of array types.

The ideal way to fix this issue would be to have all the callback function types in `Array<T>` provide a `ReadonlyArray<T>` (modifying the array in a callback is surely a bad thing), but obviously that would be a breaking change.

**Comment by mhegazy** [comment]
@ahejlsberg has a possible fir to reorder the  https://github.com/Microsoft/TypeScript/pull/21462, can you take a look.

**Pull request merged**
