### PR TITLE
 getLeftmostExpression: handle AsExpression and NonNullExpression

### PR DESCRIPTION
**Pull request by ajafff**
Fixes: #25223

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Great! Can you add the tests from your original issue to our `src/unittests` folder? I'd say it should probably be in `transform.ts`, but maybe it should be in `printer.ts` depending on the answer to https://github.com/Microsoft/TypeScript/issues/25223#issuecomment-401630558

**Comment by ajafff** [comment]
I added a new file `src/testRunner/unittests/factory.ts` as I will probably add more tests for factory functions while I fix the remaining issues.
Note that I used `createArrowFunction` for testing to avoid conflicts with #25348

**Comment by mhegazy** [comment]
@rbuckton can you please review and merge

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
