### PR TITLE
Adds [unit] and [unitDisplay] to NumberFormatOptions

### LINKED ISSUE #38012: NumberFormatOptions interface is missing unit and unitDisplay properties.
**TypeScript Version:**  3.8.3 and Nightly

**Search Terms:** NumberFormatOptions unit unitDisplay

**Code**

```ts
console.log(new Intl.NumberFormat('en', {
    style: 'unit',
    unit: 'kilobyte',
    unitDisplay: 'short',
}).format(1.5));
```

**Expected behavior:**

`unit` and `unitDisplay` should be usable for [`NumberFormatOptions`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/NumberFormat). 

**Actual behavior:**

```
Argument of type '{ style: string; unit: string; }' is not assignable to parameter of type 'NumberFormatOptions'.
  Object literal may only specify known properties, and 'unit' does not exist in type 'NumberFormatOptions'.
```

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=5&pc=17#code/MYewdgziA2CmB00QHMAUZYHcAEBJMALtPAHICuAtgEawBOAYiLRQIYGoDksYHANNgG8AUNlHYIBAJ5wAXNg5kwASwJ8RYxSrkcA1kqRVJBWGrHZNBACJKIAB2gtJ2iAAsmq3kIC+ASngAzJlZ2AEZ4AFYfHwBuIA

**Related Issues:** 

* https://github.com/microsoft/TypeScript/issues/36533

### PR DESCRIPTION
**Pull request by obber**
Fixes #38012.

Adds the `unit` and `unitDisplay` option to [`NumberFormatOptions`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/NumberFormat) in `src/lib/es5.d.ts`

### CODE REVIEW

**Comment by barrymay** [comment]
This PR is perfectly fine, but while you're at it would be nice to get notation in there too :)

**Comment by BPScott** [comment]
Notation is covered in https://github.com/microsoft/TypeScript/pull/37721

**Comment by BPScott** [comment]
Yo @sandersn, any chance we'd be able to sneak this in before beta release in addition to #38013?

I think this needs to be updated to go in `es2020.intl.d.ts` same as that other PR

**Comment by sandersn** [comment]
I'll move this over to es2020.int.d.ts

**Comment by JonathanDCohen** [comment]
What's going on with this? I'm using Typescript 4.1.3 and still getting an error `Argument of type '{ style: string; unit: string; }' is not assignable to parameter of type 'NumberFormatOptions'.
  Object literal may only specify known properties, and 'unit' does not exist in type 'NumberFormatOptions'.`

**Pull request merged**
