### PR TITLE
Retain reexports in js emit even when they export nothing

### LINKED ISSUE #37123: `export * from "mod"` declarations are elided when `"mod"` has no exports
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// @filename: register.ts
const r: any[] = [];
export function register(data: any) {
  r.push(data);
}
// @filename: data1.ts
import { register } from "./";
register("ok");
// @filename: index.ts
export * from "./register";
export * from "./data1";
```

**Expected behavior:**
```js
// @filename: register.js
var r = [];
function register(data) {
  r.push(data);
}
exports.register = register;
// @filename: data1.js
var data1_1 = require("./");
data1_1.register("ok");
// @filename: index.js
// helpers
__exportStar(require("./register"), exports);
__exportStar(require("./data1"), exports);
```
**Actual behavior:**
```js
// @filename: register.js
var r = [];
function register(data) {
  r.push(data);
}
exports.register = register;
// @filename: data1.js
var data1_1 = require("./");
data1_1.register("ok");
// @filename: index.js
// helpers
__exportStar(require("./register"), exports);
```

The reexport for file `data1` is mistakenly dropped from `index.js`.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #37123

### CODE REVIEW

**Comment by weswigham** [comment]
cc @rbuckton (since you're the last one to interact with this ellision code) and @andrewbranch (since this is tangentially related to your `import type` stuff) - I'd like reviews, but GH reviewer suggestions are, as normal, slow~

**Comment by andrewbranch** [comment]
This is a breaking change, right? This feels exactly the same as `import { Type } from './a'` or `import * as types from './moduleThatOnlyExportsTypes'` to me, and the behavior for those is to elide unless `--importsNotSetAsValues` is `preserve` or `error`. We decided not to make that the default behavior because it would have meant that a user could break their program at runtime by upgrading their TypeScript version (by including modules that weren’t included before or by changing the module order). This is in the same boat, right?

**Comment by weswigham** [comment]
Sortof - in this case, I found our behavior super surprising for `export *`; it's _impossible_ to make an `export *` "locally used as a value", so unlike the others, it's looking at the shape of the _target_, which makes it _type directed_. It's very much against our design philosophy.

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by nickcolley** [comment]
> This is a breaking change, right? 

Hello, just so you are aware this change did break our project.

Please consider releasing TypeScript in [alignment with semantic versioning](https://semver.org/) in the future.

Thanks and take care 💚 

https://github.com/Financial-Times/dotcom-page-kit/pull/816

**Comment by stephenzsy** [comment]
would that be possible to have a flag turn off the always reexport even there is nothing? Some times they are .d.ts files and the bundler do not bundle them for browser side code. This would prevent us from upgrading to 3.9 or later versions

**Comment by jkieboom** [comment]
This also broke for our project. In our case we `export *` a `.d.ts` file, which will fail later at runtime because there is no actual `js` module. A compiler error for that would have been nice.

**Comment by weswigham** [comment]
There's no error for that because a module `.d.ts` file is supposed to correspond to a module at runtime. At least that's how our own emit works. That's why the declaration file's presence lets you write the import or reexport (with a js extension, even!) in the first place. We probably should consider a `export type * from "..."` to mirror `import type`, however. I think we may have an issue for that somewhere...

**Comment by narkowicz** [comment]
This also broke our projects due to `.d.ts` files. We're left with a `require` to a local path that doesn't exist in the compiled output. In lieu of a major version bump, a compilation warning would have been really valuable.

The compilation behaviour now seems inconsistent given that we can still re-export named types from a `.d.ts` file without affecting compiled JavaScript.

FWIW we have been using `.d.ts` in a way not strictly intended- these files are compiled from JSON Schemas and define a heap of external JSON data types, rather than JavaScript modules. Collections of these types are re-exported along with a suite of type guards etc. for consumption in other TS packages.

We've had to roll back to `3.8.3` until we can `export type * from "..."` which would cover our use case well.

**Pull request merged**
