### PR TITLE
Fun with constructor functions.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by Jack-Works** [comment]
try `{ __proto__: null } as T`? it's pure syntax with no runtime lookup. maybe it will be much faster

**Comment by DanielRosenwasser** [comment]
I don't *think* that will fare better - there's no reason why the checker would be better there for example.

But at this point we're just having fun! 🎲🎯

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by Jack-Works** [comment]
image

I wonder how to read the perf data. does that mean this PR uses +133.39% more memory than mainline? how is that possible?

**Comment by DanielRosenwasser** [comment]
Yes, it's using more than twice the amount of memory. Maybe the original version is better for cons-hashing on internal classes or something. 🤷🏻‍♂️

**Comment by Jack-Works** [comment]
what about the native ES6 class? wonder the perf data

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Pull request closed without merging**
