### PR TITLE
Add "navtree" and "navtree-full" server commands

### LINKED ISSUE #11250: Add `getNavigationTree` command to server
The output of NavBar is meant to be used for VS. so it returns a two lists of entries representing containers and children. this is not what other editors are looking for. We need a new command to return the tree instead of the serialized form.

See https://github.com/Microsoft/TypeScript/issues/11230#issuecomment-250429110 for more details.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #11250

Since we're defining a new data structure, it might be a good time to define enums for ScriptElementKind and ScriptElementKindModifier rather than strings.

### CODE REVIEW

**Comment by mhegazy** [comment]
@andy-ms can you also port this to release-2.0.5

**Comment by angelozerr** [comment]
@andy-ms could you explain please the difference between navtree and navbar? I have noticed that VSCode uses navtree. In my case I use navbar to fill Eclipse Outline.

Is navtree is more performant than navbar? The only difference that I have noticed is that body is  an object and not an array like navbar.

Many thanks for your answer.

**Comment by andy-ms** [comment]
[`navigationBarItemsFunctions`](https://github.com/Microsoft/TypeScript/blob/master/tests/cases/fourslash/navigationBarItemsFunctions.ts) is a good example.

It says that given this code:

```ts
function foo() {
	var x = 10;
	function bar() {
		var y = 10;
		function biz() {
			var z = 10;
		}
	}
}

function baz() {
	var v = 10;
}
```

with the navigation tree, we get output represented as a tree:

```
<global>
	baz
		v
	foo
		bar
			biz
				z
			y
		x
```

and with the navigation bar, we get a dual-column setup:

```
<global>
	baz
	foo
baz
	v
foo
	bar
	x
bar
	biz
	y
```

If the outline view supports N levels of nesting, you should use a tree, but if it only supports one, you should use the navigation bar.

(The navigation bar also makes some decisions about what's worthy of showing up in the left column, so `biz` only shows up on the right, so `z` never shows up at all.)

As for performance, I wouldn't expect much difference, because they share most of their code. The tree output will generally be smaller, as the navigation bar needs to duplicate entries for the left and right columns.

**Comment by angelozerr** [comment]
Many thanks @andy-ms for your great explanation!

I have integrated navtree inside typescript.java. Here the result:

 * If you are using TypeScript < 2.0.6, Outline will be filled like this:



 * otherwise the Outline will be filled like this:



See https://github.com/angelozerr/typescript.java/wiki/New-and-Noteworthy-1.1.0#outline-as-tree

**Pull request merged**
