### PR TITLE
Add handling for json parse errors in tsconfig

### LINKED ISSUE #4590: Misleading error message when project arguments points to folder that lacks 'tsconfig.json'
create new folder with name '1', run compiler passing path to this folder as a value of 'project' argument.
Error message: 
```
error TS5014: Failed to parse file '1/tsconfig.json': Unexpected token u.
```

### PR DESCRIPTION
**Pull request by weswigham**
Previously we would error within `parseJsonConfigFileContent` on an attempt to index an `undefined` value whenever we returned an error from `parseConfigFileTextToJson` (Which occurs anytime a `tsconfig.json` file has malformed JSON).

Also fixes #4590

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by vladima** [comment]
this change looks good. Maybe since you are already changing this part of the code you can add better error message for cases when tsconfig.json file is missing (#4590)?

**Comment by weswigham** [comment]
@vladima done.

**Comment by vladima** [comment]
:+1:

**Pull request merged**
