### PR TITLE
autocomplete works for const assertion.

### LINKED ISSUE #39384: const assertions break autocompletion
**TypeScript Version:**  3.4 - 3.9.5

**Search Terms:**

**Code**

```ts
function returnFoo<T extends {a: 1, b: 2}>(foo: T): T {
    return foo;
}

// ✅ auto-completion works
returnFoo({})

// ❌ auto-completion broken
returnFoo({} as const)
```

**Expected behavior:**
The Typescript language server should offer VSCode to add the missing fields `a` and `b` in function call literal. Thus, you should see something like this:
Screenshot 2020-07-02 at 14 52 29

**Actual behavior:**
VSCode just shows text-based suggestions:
Screenshot 2020-07-02 at 14 52 42

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html?ssl=10&ssc=1&pln=10&pc=23#code/GYVwdgxgLglg9mABAJwKZRMsAxOcA8AKoqgB5SpgAmAzogN4CGAXIgIwA0iARqwEwBfAHwAKYHlaEAlJIYAoRIpTpMScXADccgXLkB6PYkCg5IkYgocALQQ4AWwAOAG3TwkAdzjIA1jTloMWLhwIvQCUrr6hoAy5KbmVjYOzrAIPMhwXpR+KoF4IQKmdDZgNFBSQA)

**Related Issues:** -

I am not sure if the missing auto-completion works as intended. If so, I would like to understand why it should behave this way.

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #39384

### CODE REVIEW

**Comment by orta** [comment]
Nice work @ShuiRuTian  - this looks good to me, thanks!

**Comment by n4zim** [comment]
Hi ! 

Thanks @ShuiRuTian for this feature. I have however a recommendation for a case that doesn't work on my side.

So this will work :
```ts
const test1 = <Self extends { test: number }>(s: Self) => s
test1({  } as const)
```

But not that :
```ts
const test2 = <Self extends { test: number }>(s: () => Self) => s
test2(() => ({  } as const))
```

What do you think ?

Thank you for your help.

**Comment by ShuiRuTian** [comment]
@n4zim 
Thanks for feedback, the fix PR is on the way~

**Comment by n4zim** [comment]
@ShuiRuTian It's really nice of you, this well really going to help me, many thanks !

**Pull request merged**
