### PR TITLE
Revert ES3/ES5 downlevel computed property emit logic to not use tree rewriting

### LINKED ISSUE #2586: Incorrect emit for computed accessors in object literals in ES3/ES5
For each property, we emit something like

```JavaScript
_a[c] = Object.defineProperty({ enumerable: /* ...... */ })
```

rather than actually passing `_a` and `c` into `Object.defineProperty`.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #2586

### CODE REVIEW

**Comment by JsonFreeman** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
Hold off on this for just a bit.  I'd like to investigate some of the numbers around perf (both CPU and Memory).

**Comment by ahejlsberg** [comment]
@DanielRosenwasser We should get this one merged. No need to research perf.

**Comment by DanielRosenwasser** [comment]
Since I just did a merge, can @mhegazy, @CyrusNajmabadi, or @JsonFreeman review/re-review this?

**Comment by JsonFreeman** [comment]
I don't think there is a good way to review this. Just make sure all the tests are passing.

An alternative is to redo the merge, and commit without resolving conflicts, then resolve the conflicts as another commit. That way we can review the conflict resolution without reviewing the merge itself.

**Pull request merged**
