### PR TITLE
Add '(approximate)' to the beginning of quick info requests in PartialSemantic mode

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
image

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.0

**Comment by DanielRosenwasser** [comment]
Well, I did try both. Here's what same line looked like.

image

**Comment by ahejlsberg** [comment]
I like the single line better!

**Comment by DanielRosenwasser** [comment]
It's sort of a shame that "partial mode" is really something up to interpretation by each editor. Otherwise, I'd just say we should display "loading" which works kind of nicely when the semantic server comes back with a response.

**Comment by DanielRosenwasser** [comment]
This is what it'll look like

image

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.0 and LKG

**Comment by sheetalkamat** [comment]
Should we do this for completion details too?

**Comment by mjbvz** [comment]
Sorry @DanielRosenwasser, just seeing this now. I like the single line version.

A few questions:

- I think we may need to add some use facing explanation around `approximation`. Such as in the hover contents, have a string that says something like, `this result is an best effort approximation because the project is still loading` (with better phrasing)

- I believe VS Code could have determined this itself? Or are there cases where we can be sure the the partial server is returning the full result? If TS Server does need to tell us which results are approximate, would a new flag on the response object be better so that editors can determine how to display it?

**Comment by DanielRosenwasser** [comment]
I think ideally the editor would display this itself (and is capable of doing so); if we think we can get something to do this in the August release of VS Code, then I would say we should back out the change now.

**Pull request merged**
