### PR TITLE
Update lib dom for 4.2

### PR DESCRIPTION
**Pull request by orta**
Updates the dom.d.ts files - Key changes:

 - Some of the big DOM querying APIs default to HTMLElements (shoudn't be a breaking change)
 - Some of the DOM query APIs are now generic, so they can work with SVG or XHTML instead of just HTML DOMs
 - `import.meta.url` is now defined

Breaking changes

- DOM APIs which are deprecated, are now marked as deprecated
- The Streams API had some fields removed which aren't used in any browsers

https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/960

### CODE REVIEW

**Comment by orta** [comment]
OK, merging this and keeping an eye out over the week for changes

**Comment by ahejlsberg** [comment]
This PR breaks ***a lot*** of DT tests. In particular, lots of noise about modifiers of some `url` property not matching. Also, there's this new definition of `getElementById`:

```ts
getElementById<E extends Element = HTMLElement>(elementId: string): E | null;
```

Type parameters that aren't used in the parameter list are an anti-pattern. Using a type parameter only in the return type basically amounts to an implicit type cast to the contextual type, if any. In this case the change is also breaking because the new definition produces `Element` when inference from the contextual type infers a type that isn't assignable to `Element`, such as:

```ts
declare function getElementById<E extends Element>(s: string): E | null;
declare function foo(x: string | HTMLElement): void;
foo(getElementById('hello'));  // Now errors
```

What happens here is that we infer `string | HTMLElement` for `E` and since that isn't assignable to `Element`, we revert to the constraint `Element`, which then fails.

**Comment by ahejlsberg** [comment]
BTW, we typically run the DT tests before merging PRs like this. Having lots of breaks in the DT tests in master leads to a bunch of counter productive noise in other PRs.

**Comment by orta** [comment]
Oof, yeah, my bad - sorry, my first time sending them over from the DOM repo. 

I can revert tomorrow and look at extracting the Element changes out to get a safer merge

**Pull request merged**
