### PR TITLE
Remove docker and user tests, related infra

### PR DESCRIPTION
**Pull request by jakebailey**
These tests are currently failing because we haven't maintained these baselines.

After https://github.com/microsoft/typescript-error-deltas/pull/101, the error-deltas repo and tasks will contain the full set of user/docker tests, wrapped up in a form that we actually _do_ run and maintain.

Given the above, I think it's time to delete these runners.

Note that this is not RWC. We've already effectively committed to getting rid of RWC for more error deltas as well, but this is a different set of things.

### CODE REVIEW

**Comment by weswigham** [comment]
FWIW, you can also remove the DT and test262 runners, since they're even crustier - they've both only ever been invoked by hand, without persistent baseline capture. The DT runner isn't even useful on modern DT because it can't handle `// $ExpectError` stuff. The test262 runner only ever parsed a `test262` folder in the `internal` repo that's not been run for 8 years. (Which we can then remove, and then maybe we can add the [test262](https://github.com/tc39/test262) repo to the error deltas repo, so we actually cover parsing it)

**Comment by jakebailey** [comment]
Great, I'll look into that. For DT, there are also some tasks which involve copying things around, which I assume don't work either for that reason.

I'll try in a follow-up PR if this one looks good.

**Comment by jakebailey** [comment]
Reading the test262 repo, all of the files are `.case`, so testing them directly is probably less than trivial. Given we haven't needed them in 8 years... maybe we skip it?

**Review by weswigham — APPROVED** [review]
`.case`? I think that's the exception, not the rule - I think most of the test inputs of test262 are `.js`, like [this](https://github.com/tc39/test262/blob/main/test/language/future-reserved-words/double.js) and all we want out test to do is basically ensure we don't crash on parsing them, right? Right.

**Comment by jakebailey** [comment]
Ah, I was in https://github.com/tc39/test262/tree/main/src. I'll take a look.

**Pull request merged**
