### PR TITLE
[API] Support Auto / Manual error check mode, and support synchronous error checking request

### LINKED ISSUE #5829: TS Server should inform 'clients' about recomputed diagnostics
Clients currently need to actively request diagnostics for TS files from the tsserver. The are not pushed 'automatically' by the tsserver. This causes problems when the tsconfig.json file changes. Consider the following test case:
- a TS file with use of decorators.
- tsconfig.json doesn't have a experimentalDecorators flag.
- editor shows a corresponding error

User edits the tsconfig.json file and adds experimentalDecorators: true. 

Depending on timing the errors in the editor disappear. Here is what happens in detail in VSCode and tsserver:
- the tsconfig.json file gets saved: both tsserver and VSCode receive the file event
- case 1.) VSCode processes the file event first and requests diagnostics but the tsserver hasn't processed the event yet. As a result the errors don't disappear.
- case 2.) tsserver has processed the file event before VSCode requests diagnostics. The errors disappear.

To reliable fix this the tsserver must either inform the editor about a 'reload' of the tsconfig.json file so that the editor re-requests all diagnostics. Of we change the protocol in a way that the tsserver can decide by itself to re-compute diagnostics.

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #5829.

### CODE REVIEW

**Comment by zhengbli** [comment]
Pinging @mhegazy

**Comment by dbaeumer** [comment]
@zhengbli instead of making this a general option in the protocol on config basis I suggest to make this a property in the tsconfig.json like compileOnSave. This would make it self contained. Otherwise VS Code might end up storing this outside the tsconfig in its own settings which might not be nice.

**Comment by zhengbli** [comment]
@dbaeumer After some offline discussion, maybe it is not a good thing to add options to tsconfig right now, as the more comprehensive solution you are working on may introduce new options that are different from this PR's implementation. 

To avoid future breaking changes, it is also more appropriate for this PR to give clearer names to the checking mode. So instead of `automatic`, which might mean different things later with your builder models, calling it `autoCheckOpenedFiles` instead.

**Comment by zhengbli** [comment]
As @dbaeumer has already made progress in a more comprehensive model for project-level error checking, this simple implementation is not needed anymore. Also, as @vladima is working on moving VS to use tsserver, the synchronous diagnostics APIs are part of that work too. To avoid different implementation I am closing this PR and porting these APIs to master in another PR.

**Pull request closed without merging**
