### PR TITLE
fix(45294): Parameter inlay hints don't show for interpolated string when set to literals

### LINKED ISSUE #45294: Parameter inlay hints don't show for interpolated string when set to `literals`
*TS Template added by @mjbvz*

**TypeScript Version**: 4.4.0-dev.20210728

**Search Terms**
- inlay hints

---

With `"typescript.inlayHints.parameterNames.enabled": "literals"` set, and with a function like `function trace(message: string) {}`, inlay hints won't be shown for interpolated strings.

```ts
trace(/* message: */ 'foo'); // shows inlay
trace(`foo ${Data.now()}`); // won't show
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #45294

### CODE REVIEW

**Comment by Kingwl** [comment]
I’m not sure is template literal a literal?

**Comment by a-tarasyuk** [comment]
@Kingwl Yes, it is literal. `LastLiteralToken = NoSubstitutionTemplateLiteral`. I've added a test to cover that.

**Comment by Kingwl** [comment]
I thought NoSubstitutionTemplateLiteral is a literal but TemplateLiteral not...

**Comment by DanielRosenwasser** [comment]
I think for `literals` it's fine; for `simple literals` or whatever that ends up being, we might rethink it.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.4

**Pull request merged**
