### PR TITLE
Fixes issue 10530

### PR DESCRIPTION
**Pull request by easyrider**
Fixes https://github.com/microsoft/TypeScript/issues/10530 (since 2016)

This is my first PR in this project.
Please help with performance testing - I'd like to examine performance impact on mid/big size project.

Fixes:
```
    if (pirates[index].hands) pirates[index].hands++;
                              ~~~~~~~~~~~~~~~~~~~~
!!! error TS2532: Object is possibly 'undefined'.
```

### CODE REVIEW

**Comment by orta** [comment]
@typescript-bot perf test

**Comment by easyrider** [comment]
FYI: It looks like the performance impact is minimal 
Total Time: ± 0.48%
https://github.com/microsoft/TypeScript/pull/46121#issuecomment-929967379

**Comment by kitfit-dave** [comment]
Is there anyone still looking at merging this? It does not seem to have been fixed elsewhere.

**Comment by jakebailey** [comment]
The issue fixed by this PR was fixed in #57847 (for TS 5.5).

**Pull request closed without merging**
