### PR TITLE
Fix switch statement exhaustiveness checking

### LINKED ISSUE #34661: Exhaustive switch return type is incorrect without intermediate variable
**TypeScript Version:**  3.7.0-beta

**Search Terms:** enum switch

**Code**

```ts
enum Animal {
    DOG,

    // Add second member to avoid https://github.com/microsoft/TypeScript/issues/23572.
    CAT
}

const zoo: { animal: Animal } | undefined = { animal: Animal.DOG }

// OK.
function intermediateVariable(): Animal {
    const animal = zoo?.animal ?? Animal.DOG
    switch (animal) {
        case Animal.DOG: return Animal.DOG
        case Animal.CAT: return Animal.CAT
    }
}

// Error: Function lacks ending return statement and return type does not include 'undefined'.(2366)
function expression(): Animal {
    switch (zoo?.animal ?? Animal.DOG) {
        case Animal.DOG: return Animal.DOG
        case Animal.CAT: return Animal.CAT
    }
}
```

**Expected behavior:** Inferred type doesn't depend on intermediate state.

**Actual behavior:** Inferred type differs when an expression is switched on directly versus when the value is assigned to an untyped intermediate variable and then switched on.

**[Playground Link](https://www.typescriptlang.org/play/?ts=3.7-Beta#code/KYOwrgtgBAgiCWECGAbKBvAUFHUAiA8gOIA0m2uA9JbACa1QDOwAxgPYgMTAQBGwAJygAXNlCQA3NvAYALYcIAOjAFzUA5vGGywvAHTsIlCPBYC2jNgDNhlACoBPRcADKZ+ItvxGjMMEaUAEwAzACsAOyBehQ4AMIwdpgAvuTsIIzCUABebGwqGOIIyCj5cIioUElQAD5QYJzAVvAgwAwAvAVIRail3Sh6hESV5NRQBADS0Vb1LMLwHFDNwoLctPBIywBqSALrvCjAABQAlL3laFi4UGkZhedQHTlsAPx6XffPz7B9A8QxTAB3LQsWRQQ7vYrHDD-K4sJDMb7nX5EfICYDCMACECI4rImG4OEIsq4+J2VHozHY4moPSk-4pFKYUYAUQE5gE+QAYjM5gsUEgWABrRhQUBrEDqKBojFYpjCDY8UCZLoMaWUkROYBQWhsfxQEBsTLNFgoMC0LUAcnq5qaLVoFr0hxCADZncdMNMQLN5tjgAAPRRonw+k5nYrQq6MIHCEFgp6vCEVT44mmDKGXK4E+Fa6n9QbkmVUn6DfE4Qk5n6kgvq3O0hL05KYIA)** 

**Related Issues:**  #6155 #32905

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #34661.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by rbuckton** [comment]
@typescript-bot perf test

**Comment by rbuckton** [comment]
@typescript-bot perf test this

**Comment by weswigham** [comment]
@ahejlsberg this PR has broken our nightly publish (you can verify by checking out this branch and running `gulp LGK` then `gulp tests`). Namely, once an LKG is performed, we can no longer compile ourselves (our test harness, anyway). We get an implicit any error on line 922 of `vfs.ts`:
```
src/harness/vfs.ts:922:31 - error TS7022: 'stats' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```
in this code:
```ts
        private _getLinks(node: DirectoryInode) {
            if (!node.links) {
                const links = new collections.SortedMap<string, Inode>(this.stringComparer);
                const { source, resolver } = node;
                if (source && resolver) {
                    node.source = undefined;
                    node.resolver = undefined;
                    for (const name of resolver.readdirSync(source)) {
                        const path = vpath.combine(source, name);
                        const stats = resolver.statSync(path); // error on this variable declaration
                        switch (stats.mode & S_IFMT) {
                            case S_IFDIR:
                                const dir = this._mknod(node.dev, S_IFDIR, 0o777);
                                dir.source = vpath.combine(source, name);
                                dir.resolver = resolver;
                                this._addLink(node, links, name, dir);
                                break;
                            case S_IFREG:
                                const file = this._mknod(node.dev, S_IFREG, 0o666);
                                file.source = vpath.combine(source, name);
                                file.resolver = resolver;
                                file.size = stats.size;
                                this._addLink(node, links, name, file);
                                break;
                        }
                    }
                }
                else if (this._shadowRoot && node.shadowRoot) {
                    this._copyShadowLinks(this._shadowRoot._getLinks(node.shadowRoot), links);
                }
                node.links = links;
            }
            return node.links;
        }
```
we appear to be "finding" a completely bogus circularity. How would you like to handle it?

**Comment by ahejlsberg** [comment]
The root issue here is that we're a bit too aggressive in the exhaustiveness analysis. Specifically, when analyzing the possible control flows in a `switch` with no `default`, we *always* check whether the `switch` is exhaustive and, if so, turn the control flow type into `never` for the bypass branch. Here's a simple repro that errors in 3.7 even before this PR:

```ts
function foo() {
    const foo: number | undefined = 0;
    while (true) {
        const stats = foo;
        switch (stats) {
            case 1: break;
            case 2: break;
        }
    }
}
```

To determine the type of `stats` we need to determine the control flow type of `foo` which ends up checking for `switch` exhaustiveness in the back edge of the loop. And because the `switch` statement expression references `stats`, we have a circularity.

A better approach would be separately determine the type coming from the non-bypass control flows and the type coming from the bypass flow. Then, only if the type resulting from the bypass flow would widen the final type do we need to check whether to actually include it (i.e. only then do we need the exhaustiveness check). I'll work on a fix to implement that strategy.

**Comment by HolgerJeromin** [comment]
Does this fix this code, too?

````ts
type JsonDataTypeNames = 'string' | 'number' | 'object' | 'array' | 'boolean' | 'null' | 'integer';
declare var schemaType: JsonDataTypeNames | JsonDataTypeNames[] | undefined;

if (!Array.isArray(schemaType)) {                             
} else {            
    for (let i = 0, ii = schemaType.length; i < ii; i++) {
        let validType = schemaType[i];  // any in ts3.7! not JsonDataTypeNames as in 3.6
        switch (validType) { }
    }
}

````

**Comment by ahejlsberg** [comment]
@HolgerJeromin It does indeed!

**Pull request merged**
