### PR TITLE
Don't show lib.d.ts line numbers in symbol baselines

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
There's a ton of noise from the symbol baselines whenever we update lib.d.ts (e.g. #5123). These symbol locations aren't useful -- hide them instead so we only see useful symbol changes when making lib.d.ts updates.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Not 100% sure how I feel about it; while it is incredibly annoying, I have benefited from it when I tried some experimental stuff with re-ordering `lib.d.ts` in the harness.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
i would hope that @DanielRosenwasser's issue is a one-time thing.

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by sandersn** [comment]
:+1:
I'll wait to merge my PR until this one goes in -- I'll be able to slim it down considerably as a result.

**Pull request merged**
