### PR TITLE
Cache widened types

### LINKED ISSUE #29564: ts.TypeChecker.typeToTypeNode goes in infinite loop eating up CPU and Memory.
TypeScript Version: 3.2.2

Search Terms:
ts.TypeChecker.typeToTypeNode, 
ts.TypeLiteralNode,
ts.NodeBuilderFlags.NoTruncation

Description:

We are trying to use typescript compiler for getting the type of ObjectLiteralExpression and for the purpose we utilize following code:

```
getApparentTypeForObjectLiteralExpression(node : ts.Node) : {type : ts.Type, typeNode : ts.TypeNode} {
        let type : ts.Type = this.checker.getTypeAtLocation(node);
        let typeNode = this.checker.typeToTypeNode(type, undefined, ts.NodeBuilderFlags.NoTruncation);

        if(ts.isTypeLiteralNode(typeNode))
        {
            var memberCount = typeNode.members.length;
            var name : string;
            typeNode.members.forEach(member => {
                name +=  member.name;
                name += " , ";
            });
        }
        return {type, typeNode}
    }
```
When we run the above code over the attached file SEA3DAmmo.txt (rename file to SEA3DAmmo.js), the line this.checker.typeToTypeNode goes into infinite loop and the application consumes high CPU and Memory and the call does not return back atall.

This is an absolute blocker, may be i am doing some mistake. 
I also tried running with following options:
this.checker.typeToTypeNode(type, node, ts.NodeBuilderFlags.NoTruncation);
or
this.checker.typeToTypeNode(type, node.parent, ts.NodeBuilderFlags.NoTruncation);

**Expected behavior:**
It should return value and should not go in infinite loop.

[SEA3DAmmo.txt](https://github.com/Microsoft/TypeScript/files/2793068/SEA3DAmmo.txt)

### LINKED ISSUE #29597: Printing JS constructor function type causes out-of-memory error
**TypeScript Version:**  3.2.2 and 3.3.0-rc

**Search Terms:**
heap out of memory

**Code**
First of all, I don't expect there to be a valid use case of what I'm describing below. In fact a miss configuration in my build settings lead me to this. However I don't expect TSC to completely crash. Also I found that TS 3.1 had no problems with the code below so this might be a regression of TS 3.2.

Steps to reproduce the heap OOM
* npm install [chart.js](https://github.com/chartjs/Chart.js)
* cd into `node_modules/chart.js/dist`. You should find `Chart.min.js` there.
* create a `tsconfig.json` with the following content
```
{
  "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
      "downlevelIteration": true,
      "skipDefaultLibCheck": true,
      "moduleResolution": "node",
      "preserveConstEnums": false,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "jsx": "react",
      "noErrorTruncation": true,
      "noEmitOnError": false,
      "declaration": false,
      "stripInternal": true,
      "inlineSourceMap": true,
      "inlineSources": true,
      "sourceMap": false,
      "jsxFactory": "react",
      "noImplicitAny": true,
      "noImplicitReturns": true,
      "noImplicitThis": true,
      "noFallthroughCasesInSwitch": true,
      "strictNullChecks": true,
      "strictPropertyInitialization": true,
      "strictFunctionTypes": true,
      "noStrictGenericChecks": true,
      "noResolve": true,
      "types": [],
      "importHelpers": false,
      "allowJs": true,
      "checkJs": false
  },
  "files": [
      "./Chart.min.js",
  ],
  "compileOnSave": false
}
```
* run `tsc -p tsconfig.json --outDir foo` and see the JavaScript heap out of memory thrown.

**Expected behavior:**
Emits a file `foo/Chart.min.js`.
TS 3.1.6 finishes this in 1.7 seconds without any errors.

**Actual behavior:**
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Playground Link:** 
N/A

**Related Issues:** 
This looks similar to https://github.com/Microsoft/TypeScript/issues/29326 and https://github.com/Microsoft/TypeScript/issues/29511 but I don't understand it deep enough to tell if it's a duplicate.

### LINKED ISSUE #29902: OOM heap crash with -d or -w, and --noImplicitThis
**TypeScript Version:** 3.2 -  3.4.0-dev.20190213

**Search Terms:**
memory heap crash

**Code**

```ts
function createObj() {
  return {
    func1() {
      return this;
    },
    func2() {
      return this;
    },
    func3() {
      return this;
    },
    func4() {
      return this;
    },
    func5() {
      return this;
    },
    func6() {
      return this;
    },
    func7() {
      return this;
    },
    func8() {
      return this;
    },
    func9() {
      return this;
    }
  };
}
```

**Expected behavior:**

Run: `tsc --noImplicitThis -d test.ts`

No crash. There's no crash when there's only 8 functions, but the generated declaration file is 41 MB!

**Actual behavior:**

With 9 member functions tsc runs out of memory and crashes.

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #29902

Probably fixes #29564 (doesn't have a full repro)

Notably does _not_ fix #29597 - that has some more stuff going on - chart.min.js is uuuuuuge.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by weswigham** [comment]
@typescript-bot test this now that that lint is fixed 🤦‍♂

**Comment by weswigham** [comment]
DT passes, as expected 🌞

**Comment by weswigham** [comment]
@RyanCavanaugh All the test suites are gucci

**Comment by weswigham** [comment]
@typescript-bot perf test this - this should make for _some_ perf gains, even in older style code (but moreso in JS).

**Comment by AnyhowStep** [comment]
@weswigham
Do you think #31612 is related?

I think get an infinite loop, I have a repository+commit link in that issue with a repro (not minimal)

**Comment by weswigham** [comment]
Considering this wasn't published in a nighly until around... Now? I doubt it? Unless you mean the new nightly fixes your problem and you think this fixed it.

**Pull request merged**
