### PR TITLE
Allow GLBoolean as param in pixelstorei

### LINKED ISSUE #27542: Wrong WebGLRenderingContext interface definition for pixelStorei
**TypeScript Version:**  3.1.1

**Search Terms:**
pixelStorei

**Code**

```ts
gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
```

**Expected behavior:**
well compiled

**Actual behavior:**
TS2345: Argument of type 'true' is not assignable to parameter of type 'number'.

pixelStori definition in lib.dom.d.ts (in 3.1-rc and 3.1.1) :
```ts
pixelStorei(pname: GLenum, param: GLint): void;
```
sould be :
```ts
pixelStorei(pname: GLenum, param: GLint | GLboolean): void;
```
In 3.0.3, pixelStori definition was :
```ts
pixelStorei(pname: number, param: number | boolean): void;
```

### PR DESCRIPTION
**Pull request by AVGP**
Fixes #27542

### CODE REVIEW

**Comment by j-oliveras** [comment]
Files from `lib` folder are generated from `src/lib` folder. Some files from `src/lib` are generated from [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) repository.

Read [Contributing lib.d.ts fixes](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes) for more info.

**Comment by AVGP** [comment]
Fair enough, that's why I made the corresponding change in TSJS as well - see https://github.com/Microsoft/TSJS-lib-generator/pull/583

Unless I'm missing something, this PR is still needed to get the change into TypeScript, no?

**Comment by fatcerberus** [comment]
What's really bizarre is that this exact issue appears to have been fixed about 2 years ago:
https://github.com/Microsoft/TSJS-lib-generator/pull/178

But it's clearly broken now.  Was the change accidentally reverted?

**Comment by RyanCavanaugh** [comment]
TSJS-lib-generator is the correct place for this one

**Pull request closed without merging**
