### PR TITLE
fix(49546): 'Add missing properties' quick fix incorrectly handles symbol property

### LINKED ISSUE #49546: 'Add missing properties' quick fix incorrectly handles symbol property
# Bug Report

### 🔎 Search Terms
- quick fix
- code action
- add missing properties

### 🕗 Version & Regression Information

4.8.0-dev.20220614, not a regression

### 💻 Code
For the code:

```ts
const x: Iterable<number> = {}
```

Trigger the quick fix for `add missing properties` on `x`

### 🙁 Actual behavior

```ts
const x: Iterable<number> = {
    "__@iterator@15": function (): Iterator<number, any, undefined> {
        throw new Error("Function not implemented.");
    }
}
```

### 🙂 Expected behavior

```ts
const x: Iterable<number> = {
    [Symbol.iterator]: function (): Iterator<number, any, undefined> {
        throw new Error("Function not implemented.");
    }
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49546

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Comment by a-tarasyuk** [comment]
```ts
const m: unique symbol = Symbol();
interface T {
   [m]: string;
   a: number;
   b: string;
}
[|let p: T = {};|]
```

@RyanCavanaugh If the type contains at least one computed property, QF should not be suggested. Am I right?

**Comment by RyanCavanaugh** [comment]
I'm sort of on the fence, let me think about it more

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh I'm not sure what is the right way to resolve this edge case with naming collisions. We can skip computed properties and implement only known keys. Or we can try to find all the names in the current scope and try to rename something (not sure which name to rename) / or mark it as "unknown" key. Or completely skip QF. I think it depends on how often this case occurs.

**Comment by RyanCavanaugh** [comment]
Eh, this seems unlikely to break in practice. Let's see how it goes.

**Pull request merged**
