### PR TITLE
Updates the DOM APIs

### PR DESCRIPTION
**Pull request by orta**
Re: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1143

Most of the diff comes from more whitespace aware commenting.

---

# @types/web

## New interfaces

* `ElementInternals`

## Removed interfaces

* `PaymentAddress` - [Classed as obsolete](https://caniuse.com/mdn-api_paymentaddress)

## Modified

* CSSStyleDeclaration
  * Added: `accentColor`
* Document
  * Removed: `elementFromPoint`, `elementsFromPoint` - these live on `DocumentOrShadowRoot` instead
* HTMLElement
  * Added: `attachInternals`
* HTMLSlotElement
  * Added: `assign`
* Navigator
  * Added: `canShare`
  * Removed: `pointerEnabled` - removed from [spec in 2014](https://webplatform.github.io/docs/dom/Navigator/pointerEnabled/)
* ReadableStream
  * Removed: `forEach` - Doesn't seem to be in [the Readable Stream API](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#methods)
* Text
  * Removed: `assignedSlot` - This might be something we backtrack during the beta, will be easy to re-add if we want. https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/d42f963a7fc80796e7922eaa1cd10df939627cca#r57102539

### Non-value types

* MediaTrackConstraintSet
  * Added: `autoGainControl`, `noiseSuppression`
* MediaTrackSettings
  * Added: `autoGainControl`, `noiseSuppression`
* MediaTrackSupportedConstraints
  * Added: `autoGainControl`, `noiseSuppression`
* DocumentOrShadowRoot
  * Added: `elementFromPoint`, `elementsFromPoint`

## `index.iterable.d.ts`

No changes

### CODE REVIEW

**Comment by orta** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by orta** [comment]
@typescript-bot run dt

**Comment by orta** [comment]
@typescript-bot run dt

**Comment by orta** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56013 has covered all the changes to DT

**Review by sandersn — APPROVED** [review]

**Comment by MattiasBuelens** [comment]
> ReadableStream
> 
> * Removed: `forEach` - Doesn't seem to be in [the Readable Stream API](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#methods)

It looks like this faulty `forEach()` method still appears in [`lib.dom.d.ts` of TypeScript 4.5 beta](https://github.com/microsoft/TypeScript/blob/v4.5-beta/src/lib/dom.generated.d.ts#L10913)? It is correctly removed [over at TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/64a8151fe94ff2aad044600646ebc122e6b5db52/baselines/dom.generated.d.ts#L10890-L10897), so I'm not sure how it didn't make it into this PR. 😕

**Comment by orta** [comment]
Yeah, this feels off to me

**Comment by orta** [comment]
Alright, the deploy to TypeScript process is now completely automated which _mostly_ drops human error from the process. https://github.com/microsoft/TypeScript/pull/46222 contains the up-to-date DOM changes.

**Pull request merged**
