### PR TITLE
fixed issue https://github.com/Microsoft/TypeScript/issues/3486

### PR DESCRIPTION
**Pull request by ShyykoSerhiy**

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Hi there @ShyykoSerhiy, thanks for the PR - does this fully fix #3486, or only partially?

Additionally, in the future, could you give a descriptive title and link to the issue with the pound sign (`#`) followed by the issue number? For instance, here I might have written this issue with the following title and body:

> ## Make TypeScript compliant with strict mode
> Fixes issue #3486.

**Comment by ShyykoSerhiy** [comment]
Hi, It fully fixes #3486. I've also checked other files:
* tsc.js
* tsserver.js
* typescript.js
too, so TypeScript should be compliant with strict mode

**Comment by DanielRosenwasser** [comment]
Great - thanks @ShyykoSerhiy!

**Pull request merged**
