### PR TITLE
Make release-3.3 buildable

### PR DESCRIPTION
**Pull request by amcasey**
With this change, you can build the branch using `npm ci && gulp` (assuming you're not node 12, for some reason).

Note that I didn't update `.npmrc` or `package.json`.

### CODE REVIEW

**Comment by amcasey** [comment]
If people like this approach, I'll do it for `release-3.x` (unless someone sees value in going back further).

**Comment by rbuckton** [comment]
If we're adding a package-lock, don't we need to remove the package-lock setting in .npmrc?

**Comment by amcasey** [comment]
@rbuckton I thought that would only be helpful if we planned to regenerate the package-lock.json file, which seemed unlikely to me.

**Comment by amcasey** [comment]
@weswigham I assume the CI failures are because the pipeline(s) need to be updated to use `npm ci` if package-lock.json is present.  Unfortunately, I don't seem to have access (or, at least, signing in dumps me to a list of projects not including this CI).

**Comment by weswigham** [comment]
Signing in to ADO be like that sometimes. Getting the login to "stick" can actually be a pain.

**Comment by amcasey** [comment]
I've updated the config files so that future changes to package-lock.json won't be discarded.

@rbuckton @RyanCavanaugh Any objection to my updating the CI and making similar changes in the other 3.x branches?

**Comment by amcasey** [comment]
@weswigham Still no luck with sign-in.  Can you please confirm that I have the necessary access?

**Comment by amcasey** [comment]
If we want to test against node 6, we'll have to `npm install -g npm@latest` because npm 3 doesn't support `ci`.

**Comment by amcasey** [comment]
I created parallel Azure pipelines that use `npm ci` when `package-lock.json` is present and the `node10` run is green.  If we decide to go ahead with this change, I'll update the real pipelines.

**Comment by amcasey** [comment]
Gulp 3.X doesn't work with Node > 10. 😢

**Comment by amcasey** [comment]
That's as clean as CI is going to get.  Last call for objections...

**Pull request merged**
