### PR TITLE
Add support for extraFileExtensions on WatchCompilerHost

### PR DESCRIPTION
**Pull request by sheetalkamat**
To support typescript-eslint/typescript-eslint#1813

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
So just to be clear, there's a break in the API which needs to be documented - but any consumer that updates its usages of this function should be fixed?

**Comment by DanielRosenwasser** [comment]
If so, can somebody link me to the thing that caused the original break?

**Comment by uniqueiniquity** [comment]
https://github.com/microsoft/TypeScript/pull/37278 removed the function that was being used. I believe it was internal.

**Comment by DanielRosenwasser** [comment]
In that thread @JoshuaKGoldberg said removed something that appeared unused. If removing it affected things, then I assume it really *was* used. Can someone explain what happened step-by-step?

**Comment by uniqueiniquity** [comment]
From my perspective, Brad tagged me in https://github.com/typescript-eslint/typescript-eslint/issues/1813, I looped in Sheetal, and she quickly identified the issue and put up a fix.

@sheetalkamat Could you give us a sense of what happened regarding Josh's PR?

**Comment by sheetalkamat** [comment]
@DanielRosenwasser There was `onCachedDirectoryStructureHostCreate` method on `WatchCompilerHost` which was internal (intentionally) that we never re;lied on and hence was removed (the unused variable host was set in that method callback)` Given this was internal method, no body shouldnt have been relying on that but that was not the case and hence the break for eslint. I believe PR #37278 is correct though in removing those things.

**Pull request merged**
