### PR TITLE
Update version to 1.4.2

### PR DESCRIPTION
**Pull request by JsonFreeman**

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by bunnycode** [comment]
Is 1.4.2 ever going to get sent to NPM?

**Comment by JsonFreeman** [comment]
I think it is the same as 1.4.1. If I recall correctly, the npm release for 1.4.1 contained some extra fixes that were not supposed to be in 1.4.1, so we just called it 1.4.2.

**Comment by mhegazy** [comment]
@bunnycode there are [three bugs](https://github.com/Microsoft/TypeScript/issues?q=milestone%3A%22TypeScript+1.4.2%22+is%3Aclosed++label%3Afixed) that were fixed in between the two releases. only one of them touches the command line compiler. is #1714 what you are interested in?

**Comment by basarat** [comment]
so `1.4.2` milestone == `1.4.1` NPM version?

**Comment by JsonFreeman** [comment]
I think so, but double check with @mhegazy to be sure.

**Comment by mhegazy** [comment]
It really means Visual Studio 2015 CTP6. Which is 1.4.1 + 3 bug fixes.

**Pull request merged**
