### PR TITLE
Fixed widening errors locations in union-normalized object literal types

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/58150

### CODE REVIEW

**Comment by Andarist** [comment]
@jakebailey could u build a TS playground here?

**Comment by jakebailey** [comment]
@typescript-bot test it
@typescript-bot pack this

**Comment by Andarist** [comment]
Thank you! ❤️

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Review by gabritto — APPROVED** [review]

**Pull request merged**
