### PR TITLE
Use `object` type

### LINKED ISSUE #13493: Use `object` non primitive type instead of `Object` interface
Most `Object` type should be replaced by `object` type added by #12501.

**TypeScript Version:**  master

**Code**

lib/*.d.ts

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #13493

### CODE REVIEW

**Comment by falsandtru** [comment]
@sandersn @RyanCavanaugh @mhegazy Please review.

**Comment by falsandtru** [comment]
@sandersn @RyanCavanaugh @mhegazy @DanielRosenwasser

**Comment by sandersn** [comment]
Let's swap @sandersn with @rbuckton. I'm not fluent enough with runtime semantics to be a useful reviewer here.

**Comment by falsandtru** [comment]
I see, thanks.

**Comment by falsandtru** [comment]
@rbuckton Could you?

**Comment by falsandtru** [comment]
Thanks!

**Pull request merged**
