### PR TITLE
Bail early in getNarrowedTypeWorker if type is candidate

### PR DESCRIPTION
**Pull request by jakebailey**
This technically handles https://github.com/microsoft/TypeScript/issues/52345#issuecomment-1737898885 and maybe #55948, bringing it back to <=4.7 levels, but I think it's a little silly to narrow something to itself. But, probably cheap to check anyhow.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
I still feel like this might be slightly silly, but it seems really cheap and quick to just check for cases where we're trying to narrow something to itself and bail early without doing all of the other work.

**Comment by gabritto** [comment]
The change makes sense, but where in type checking the motivating case https://github.com/epmatsw/tsdemo/blob/main/slow.ts do we call `getNarrowedType` with `type` and `candidate` being the same?

**Comment by jakebailey** [comment]
I think the example has been updated; it used to be narrowing something to itself.

**Comment by gabritto** [comment]
> I think the example has been updated; it used to be narrowing something to itself.

Do you have an example then?

**Comment by jakebailey** [comment]
The repro repo has it if you go back a few commits: https://github.com/epmatsw/tsdemo/tree/b2a2af937e492819045ea4e880a56236494c2147

Something like:

```ts
function test(base: SpecificString) {
  if (isSpecificString(base)) {
    return base;
  }
}
```

Where `SpecificString` is a large union of literals.

**Comment by gabritto** [comment]
Ah, so it is an explicit narrowing to itself. I don't know how common it is, it doesn't seem like something you want to be doing, but then again you might be programming defensively and you want to validate at run time that something has a type, so I can see a case for writing this kind of code.
I think I agree that, as long as it's cheap to check and doesn't make anything slower, there's not a lot of harm in doing that.

**Review by gabritto — APPROVED** [review]

**Review by weswigham — APPROVED** [review]
Don't know if you're still waiting on my review for this, but this can be a reminder to merge this at some point~

**Comment by jakebailey** [comment]
I was, kinda; mainly I was trying to decide if this was even worthwhile if it's so rare and silly.

**Pull request merged**
