### PR TITLE
Fix RWC Runner. Only check if extensions property match support extensions specified in tsconfig

### PR DESCRIPTION
**Pull request by yuit**

### CODE REVIEW

**Comment by sandersn** [comment]
What's the context behind this change? I see that it now does not check `d.exclude` but I don't know enough about RWC to know why.

**Comment by yuit** [comment]
@sandersn we made a change in our compiler to always include "outdir" in "exclude". However, when we captured RWC, we record directories in used and its exclude property doesn't account for the new behavior. Unless we recapture, it block some tests to be run. One question I have is why do we check it in the first place @RyanCavanaugh may know.

**Comment by mhegazy** [comment]
:+1:

**Comment by yuit** [comment]
talk with @mhegazy  offline, the arguments won't make any different

**Pull request merged**
