### PR TITLE
Manually walk to make normalizeSlashes a no-op

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Experimental alternative to #44100.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
I could probably rewrite this in terms of `indexOf` like described by @rbuckton, I didn't see that comment. It might be faster.

**Comment by rbuckton** [comment]
The suggestion I made in #44100 avoids an array allocation.

**Comment by DanielRosenwasser** [comment]
> The suggestion I made in #44100 avoids an array allocation.

Isn't https://github.com/microsoft/TypeScript/pull/44100#issuecomment-841575001 potentially creating several intermediate "result" arrays on every iteration of the loop? Seems like it could go either way.

**Comment by DanielRosenwasser** [comment]
I guess I could technically just use one array.

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by amcasey** [comment]
Single run of large project load in node12 on linux:

indexOf
```
Type: wall
Time: May 18, 2021 at 1:29pm (PDT)
Duration: 38.46s, Total samples = 35755ms (92.98%)
Active filters:
   show=norm
Showing nodes accounting for 31856ms, 89.10% of 35755ms total
Dropped 5 nodes (cum <= 178.78ms)
      flat  flat%   sum%        cum   cum%
   26995ms 75.50% 75.50%    31881ms 89.17%  Interface._normalWrite readline.js:434
    4372ms 12.23% 87.73%     4556ms 12.74%  normalizePath /home/acasey/repos/ts_gh/built/local/tsserver.js:6028
     489ms  1.37% 89.10%      489ms  1.37%  normalizeSlashes /home/acasey/repos/ts_gh/built/local/tsserver.js:5917
```

This PR
```
Type: wall
Time: May 18, 2021 at 2:03pm (PDT)
Duration: 48.08s, Total samples = 44.53s (92.60%)
Active filters:
   show=norm
Showing nodes accounting for 40.63s, 91.26% of 44.53s total
Dropped 3 nodes (cum <= 0.22s)
      flat  flat%   sum%        cum   cum%
    30.98s 69.58% 69.58%     40.66s 91.32%  Interface._normalWrite readline.js:434
     5.55s 12.47% 82.05%      7.35s 16.50%  normalizePath /home/acasey/repos/ts_gh/built/local/tsserver.js:6021
     4.10s  9.21% 91.26%      4.10s  9.21%  normalizeSlashes /home/acasey/repos/ts_gh/built/local/tsserver.js:5899
```

The baseline includes other local changes, but was the same for both.

**Review by lastthyme — APPROVED** [review]

**Pull request closed without merging**
