### PR TITLE
Fixed crash in import fixes for augmented modules

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/58907

### CODE REVIEW

**Comment by iisaduan** [comment]
@typescript-bot test it

**Comment by Andarist** [comment]
The new error might be a positive change but I'm not entirely sure. Module augmentation is a weird beast.

Test case:
```ts
// @strict: true
// @module: nodenext
// @moduleResolution: nodenext
// @noEmit: true
// @skipLibCheck: true

// @filename: node_modules/urql/index.d.ts
type AnyVariables =
  | {
      [prop: string]: any;
    }
  | void
  | undefined;

declare function useQuery<Data = any, Variables extends AnyVariables = AnyVariables>(
  args: Variables
): Data;

export { AnyVariables, useQuery };

// @filename: src/index.ts
import { AnyVariables, useQuery } from 'urql';

declare module 'urql' {
  export function useQuery<Data = any, Variables extends AnyVariables = AnyVariables>(
    name: string,
    args: Variables
  ): Data;
}
```

The important ingredient here is `skipLibCheck: true`. The reported error gets reported with the current TS version only with `skipLibCheck: false`. With this branch it errors "consistently" with `skipLibCheck` and without it. Since the error is reported in both scenario in a `.ts` file... that's perhaps an improvement?

That said, I'm probably somewhat surprised that this is an error at all. I guess it's different to export a declaration using a modifier or using a separate export declaration but... it really feels like a detail that the user shouldn't be concerned with.

**Comment by iisaduan** [comment]
> That said, I'm probably somewhat surprised that this is an error at all. I guess it's different to export a declaration using a modifier or using a separate export declaration but... it really feels like a detail that the user shouldn't be concerned with.

I agree that it's a detail that users shouldn't need to worry about. I haven't had time to fully review the PR yet, but I was able to strip your original test case even further (below). It's interesting that the completion works if you remove `Container` out of the export list in `index.d.ts`, and instead export the declaration: `export interface Container`

```
// @module: nodenext
// @Filename: ./node_modules/@sapphire/pieces/index.d.ts
//// interface Container {
////   stores: unknown;
//// }
////
//// declare class Piece {
////   container: Container;
//// }
////
//// export { Piece, type Container };

// @FileName: ./augmentation.ts
//// declare module "@sapphire/pieces" {
////   interface Container {
////     client: unknown;
////   }
//// }

// @Filename: ./index.ts
//// import { Piece } from "@sapphire/pieces";
//// class FullPiece extends Piece {
////   /*1*/
//// }
```

**Comment by Andarist** [comment]
> I haven't had time to fully review the PR yet, but I was able to strip your original test case even further (below). 

Thanks. I just stopped reducing at the point that test could be easily debugged and proceeded to fixing it 😅 I added this now as an extra test case here.

> It's interesting that the completion works if in index.d.ts, you remove Container out of the export list, and instead export the declaration: export interface Container

That's likely related to the directly exported `Container` having `.exportSymbol`. The local symbol that gets exported through a separate export declaration doesn't have it.

**Comment by synulux** [comment]
Is there any progress on this? Like, a dev-release that can be installed through NPM with a fix, or maybe a workaround?

**Comment by gabritto** [comment]
> Is there any progress on this? Like, a dev-release that can be installed through NPM with a fix, or maybe a workaround?

Once this or another bug fix PR is merged, the [nightly build](https://www.typescriptlang.org/docs/handbook/nightly-builds.htm) of that day will contain the fix.

**Comment by gabritto** [comment]
> The new error might be a positive change but I'm not entirely sure. Module augmentation is a weird beast.
> 
> Test case:
> 
> ```ts
> // @strict: true
> // @module: nodenext
> // @moduleResolution: nodenext
> // @noEmit: true
> // @skipLibCheck: true
> 
> // @filename: node_modules/urql/index.d.ts
> type AnyVariables =
>   | {
>       [prop: string]: any;
>     }
>   | void
>   | undefined;
> 
> declare function useQuery<Data = any, Variables extends AnyVariables = AnyVariables>(
>   args: Variables
> ): Data;
> 
> export { AnyVariables, useQuery };
> 
> // @filename: src/index.ts
> import { AnyVariables, useQuery } from 'urql';
> 
> declare module 'urql' {
>   export function useQuery<Data = any, Variables extends AnyVariables = AnyVariables>(
>     name: string,
>     args: Variables
>   ): Data;
> }
> ```
> 
> The important ingredient here is `skipLibCheck: true`. The reported error gets reported with the current TS version only with `skipLibCheck: false`. With this branch it errors "consistently" with `skipLibCheck` and without it. Since the error is reported in both scenario in a `.ts` file... that's perhaps an improvement?
> 
> That said, I'm probably somewhat surprised that this is an error at all. I guess it's different to export a declaration using a modifier or using a separate export declaration but... it really feels like a detail that the user shouldn't be concerned with.
> 
> I'm also not sure how to even augment this correctly since [this is not allowed](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240627#code/JYWwDg9gTgLgBAbzgQQHYE8BqBDKxsBGANgKYDOANHAKpkkCKAriVOslAOaU11MvoAlcpFR04AXzgAzKBBBwARIygBHIgoDcAWABQugCYkAxkVwk4ICPsalFytQsS640xqiMxgEVHEa9mrAA8ACLYMNhwALxw2BhUOHiEpGRwJAAeMCSo+iloWLj4xORRKBgJhckAfAAUzi4xnGQAXDwMAWyNgeVJ5FSh4ZUUdQCULbRt-EJkInQhYdjxBT1kldp6Oi7pkLCIvv78EmviukA)



> The new error might be a positive change but I'm not entirely sure. Module augmentation is a weird beast.
> 
> Test case:
> 
> ```ts
> // @strict: true
> // @module: nodenext
> // @moduleResolution: nodenext
> // @noEmit: true
> // @skipLibCheck: true
> 
> // @filename: node_modules/urql/index.d.ts
> type AnyVariables =
>   | {
>       [prop: string]: any;
>     }
>   | void
>   | undefined;
> 
> declare function useQuery<Data = any, Variables extends AnyVariables = AnyVariables>(
>   args: Variables
> ): Data;
> 
> export { AnyVariables, useQuery };
> 
> // @filename: src/index.ts
> import { AnyVariables, useQuery } from 'urql';
> 
> declare module 'urql' {
>   export function useQuery<Data = any, Variables extends AnyVariables = AnyVariables>(
>     name: string,
>     args: Variables
>   ): Data;
> }
> ```
> 
> The important ingredient here is `skipLibCheck: true`. The reported error gets reported with the current TS version only with `skipLibCheck: false`. With this branch it errors "consistently" with `skipLibCheck` and without it. Since the error is reported in both scenario in a `.ts` file... that's perhaps an improvement?
> 
> That said, I'm probably somewhat surprised that this is an error at all. I guess it's different to export a declaration using a modifier or using a separate export declaration but... it really feels like a detail that the user shouldn't be concerned with.
> 
> I'm also not sure how to even augment this correctly since [this is not allowed](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240627#code/JYWwDg9gTgLgBAbzgQQHYE8BqBDKxsBGANgKYDOANHAKpkkCKAriVOslAOaU11MvoAlcpFR04AXzgAzKBBBwARIygBHIgoDcAWABQugCYkAxkVwk4ICPsalFytQsS640xqiMxgEVHEa9mrAA8ACLYMNhwALxw2BhUOHiEpGRwJAAeMCSo+iloWLj4xORRKBgJhckAfAAUzi4xnGQAXDwMAWyNgeVJ5FSh4ZUUdQCULbRt-EJkInQhYdjxBT1kldp6Oi7pkLCIvv78EmviukA)

This new error seems "correct" in that those two `useQuery` declarations should be considered overloads of the same function, but the error itself is of course wrong, because they are both exported, even though TypeScript doesn't think so. This last part is a bug tracked by #58756.

**Review by gabritto — APPROVED** [review]

**Comment by afern247** [comment]
having the same issue, is this ready to merge?

**Review by andrewbranch — CHANGES_REQUESTED** [review]
Isabel and I are investigating this, but I just wanted to block this from merging for now as it’s not correct. In Isabel’s test case, under this PR, we can see the merged `Container` interface symbol has a parent of a non-merged external module symbol, when (if anything), the parent of the merged export should be the merged module. In general, when merging two symbols, we don’t want to just arbitrarily pick the parent of one of the constituents to be the sole parent of the new symbol, which is what this PR is doing.

**Review by iisaduan — COMMENTED** [review]
I don't think this is the correct fix, for a couple reasons: 
1. If you alias the exported symbol that will be augmented (`Container` in this case), the crash still happens
2. The parent that is being assigned here is incorrect, as the merged symbol is not a descendent of the unmerged module/augmentation

I spent some time testing the module augmentation behavior and it does work correctly with the merged symbols not having parents. As a result, I don't think it makes sense to generate parents for all symbols of this type if they're not needed in typechecking.

I will open another PR that fixes autoimports directly. (#59582)

**Comment by Andarist** [comment]
superseded by https://github.com/microsoft/TypeScript/pull/59582

**Pull request closed without merging**
