### PR TITLE
Add 'extends' clause to 'infer' type

### PR DESCRIPTION
**Pull request by rbuckton**
This adds an optional `extends` clause to `infer T` to specify an explicit constraint for the `T` type parameter. When specified, 
the explicit constraint overrides the constraint we would have attempted to infer for `T`.

For example, if you wished to infer a type from the first element of a tuple but also constrain that type, you might currently need to write something like the following:

```ts
// This type alias serves as an example of any type with a constraint you might need to satisfy
type MustBeNumber<T extends number> = { y: T };

// Option 1, use a nested conditional
type X1<T> =
  T extends [infer U] ?
    U extends number ? MustBeNumber<U> :
    never :
  never;

// Option 2, use a secondary type to constrain the inference
type Is<T extends U, U> = T;
type X2<T> =
  T extends [Is<infer U, number>] ? MustBeNumber<U> :
  never;
```

For Option 1, you are forced to create two conditional types, resulting in two alternatives. If you are testing multiple other conditions, this could result in an unmanageable branching structure which results in the need to define additional type aliases for repeated branches:
```ts
type X1<T> =
  T extends [infer U] ? U extends number ? MustBeNumber<U> : 
    T extends {x: infer U} ? U extends number ? MustBeNumber<U> :
      ...
  // repeats...
  T extends {x: infer U} ? U extends number ? MustBeNumber<U> :
    ...
```

For Option 2, you are required to define a second type to enforce the constraint. While this is trivial, it is unreliable when inferring to the same type variable in more than one position, as it is possible to define disjoint constraints:
```ts
type X2<T> = T extends [Is<infer U, number>, Is<infer U, string>] ? MustBeNumber<U> : never; // U will always be `never`
```

In contrast, specifying an explicit constraint via `extends` allows us to achieve the simpler branching structure of Option 2, while providing additional safety by checking that the constraints are consistent:

```ts
// simpler branching due to combining the constraint
type X3<T> = T extends [infer U extends number] ? MustBeNumber<U> : never;

// all constraints for same type parameter must match, if present
type X4<T> = T extends [infer U extends number, infer U extends number] ? MustBeNumber<U> : never;

// only one type parameter needs to be constrained (similar to class/interface merging)
type X5<T> = T extends [infer U extends number, infer U] ? MustBeNumber<U> : never;
type X6<T> = T extends [infer U, infer U extends number] ? MustBeNumber<U> : never;

// errors on inconsistent constraints
type X7<T> = T extends [infer U extends string, infer U extends number] ? U : never;
// error: All declarations of 'U' must have identical constraints.
```

Related #48094

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Do we have a sense of what kind of libraries would benefit from this?

**Comment by rbuckton** [comment]
Probably anyone doing tuple type or template literal type manipulation, plus #48112. I regularly find myself needing to define something like `Is` or use `Extract` when inferring from tuple types when I need a more specific type than inference allows.

I found a few places that could leverage this:
- `type-fest`
  - https://cs.github.com/sindresorhus/type-fest/blob/cbd7ec510bd136ac045bbc74e391ee686b8a9a2f/source/get.d.ts?q=infer#L15-L19
  - https://cs.github.com/sindresorhus/type-fest/blob/cbd7ec510bd136ac045bbc74e391ee686b8a9a2f/source/get.d.ts#L59-L66 (could be written to a form that's easier to read)
  - https://cs.github.com/sindresorhus/type-fest/blob/cbd7ec510bd136ac045bbc74e391ee686b8a9a2f/source/join.d.ts?q=infer#L28-L29 (though there's possibly an inference bug that could be fixed here as well)
  - https://cs.github.com/sindresorhus/type-fest/blob/cbd7ec510bd136ac045bbc74e391ee686b8a9a2f/source/delimiter-case.d.ts?q=infer#L8-L20 (explicit constraints would reduce the number of `: never` branches)
- `material-ui`
  - https://cs.github.com/mui/material-ui/blob/2a81d58c7b9e10718474639dc613078050e512b9/packages/mui-joy/src/styles/defaultTheme.ts?q=infer#L31-L39
- `redux-orm` (on DefinitelyTyped)
  - https://cs.github.com/DefinitelyTyped/DefinitelyTyped/blob/2280eb45b474bf8e92ff34b1d2775afc03cffc6f/types/redux-orm/db/Table.d.ts#L34-L46
  - https://cs.github.com/DefinitelyTyped/DefinitelyTyped/blob/2280eb45b474bf8e92ff34b1d2775afc03cffc6f/types/redux-orm/Model.d.ts#L383-L389
- `react-router` (on DefinitelyTyped)
  - https://cs.github.com/DefinitelyTyped/DefinitelyTyped/blob/2280eb45b474bf8e92ff34b1d2775afc03cffc6f/types/react-router/index.d.ts?q=path%3A*.ts+%22infer%22#L157-L167 (could be simplified)
- `convict` (on DefinitelyTyped)
  - https://cs.github.com/DefinitelyTyped/DefinitelyTyped/blob/2280eb45b474bf8e92ff34b1d2775afc03cffc6f/types/convict/index.d.ts#L121-L129

**Comment by phryneas** [comment]
You can add the Redux ecosystem (Redux Toolkit, Reselect) to that list - we have a few cases where we have a
`Something<X> extends infer Y ? Y extends Bar ? /* actual logic */`.

I'm pretty sure @tannerlinsley will have quite a few uses in React Table for this, but that's speculation from my side.

**Comment by tannerlinsley** [comment]
I would greatly benefit from this in React Table and React Location where I am already writing a lot branching conditional types to both enforce and extract generics. It’s brittle. This would make those contracts easier to define and much more reliable.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by rbuckton** [comment]
In the design meeting we discussed the syntax ambiguity with `infer T extends U ?`. There are three approaches we can take:

1. Leave the precedence as written in this PR. This would be a breaking change since the following is perfectly legal TS today:
   ```ts
   type X<T> = T extends (infer U extends number ? 1 : 0) ? 1 : 0;
   ```
   If we chose this option, the above would become a parse error and existing code would need to change to parenthesize the `infer U`.

2. Use speculative parsing disambiguate `infer T extends U ?`. This means that we would speculatively parse the `extends` clause of an `infer` type, and if we encounter a `?` we would rewind. This is similar to how we speculatively parse arrow functions, but has the same drawback: If the type in the `extends` clause is very large we would have to re-parse it again. This may be acceptable as `infer T extends U ?` doesn't seem to be a common occurrence in the wild, and if a project does encounter a slowdown due to the lookahead, they can easily wrap the `infer` type in parens to avoid rewinding.

3. Use a cover grammar to disambiguate `infer T extends U ?`. This means that we would parse the `infer T extends U` as an infer type, and if we encounter a `?` following that type we would recreate the `infer` type *without* the constraint and reuse the node for the constraint. This avoids the performance implications of speculative parsing, but will require more thorough testing to ensure that it doesn't break incremental parsing scenarios.

4. Use a different keyword instead of `extends` for an `infer` type's constraint, such as `of` (i.e., `infer T of U`). This avoids the ambiguity, but introduces a second term with the same meaning as `extends`, which could be a source of confusion.

I investigated using something like JS's `[In]` parser context, however that approach didn't seem viable. The places we would want to allow `extends` in an `infer` type (such as in a parenthesized type) are the same places you might want to infer to the check type of a conditional type, so there was no way to separate them using a context flag.

**Comment by rbuckton** [comment]
> You can add the Redux ecosystem (Redux Toolkit, Reselect) to that list - we have a few cases where we have a `Something<X> extends infer Y ? Y extends Bar ? /* actual logic */`.
> 
> [...]

I have been a bit wary of classifying all cases of `... infer Y ? Y extends Bar ? ...` as possible use cases since `Y extends Bar ? ...` could also indicate the need to distribute over `Y` rather than merely constraining it. Switching to `infer T extends U` will definitely need to be accessed on a case-by-case basis.

**Comment by phryneas** [comment]
> > You can add the Redux ecosystem (Redux Toolkit, Reselect) to that list - we have a few cases where we have a `Something<X> extends infer Y ? Y extends Bar ? /* actual logic */`.
> > [...]
> 
> I have been a bit wary of classifying all cases of `... infer Y ? Y extends Bar ? ...` as possible use cases since `Y extends Bar ? ...` could also indicate the need to distribute over `Y` rather than merely constraining it. Switching to `infer T extends U` will definitely need to be assessed on a case-by-case basis.

Of course, but we only really use it in cases where we have the `else` case be `never` - we only really add that inner `extends` to make the compiler happy. Might not be the core of this PR, but it definitely helps us write code.

**Comment by RyanCavanaugh** [comment]
I'd also toss in "require parenthesization" as a possible parsing strategy
```ts
type X<T> = T extends (infer U extends number) ? 1 : 0;
```

**Comment by rbuckton** [comment]
> I'd also toss in "require parenthesization" as a possible parsing strategy
> 
> ```ts
> type X<T> = T extends (infer U extends number) ? 1 : 0;
> ```

Unfortunately, requiring parens alone doesn't resolve the ambiguity, since `T extends (infer U extends number ? 1 : 0) ? 1 : 0` is already legal (and thus we could still encounter a trailing `?`).

Right now I'm leaning towards (2) for its simplicity, but changing the `noConditionalTypes` parameter of `parseTypeWorker` into a parser context flag so that we can relax the need for parens in situations where we can be sure a trailing `?` wouldn't be ambiguous:

```ts
// ok, parsed as conditional
type X1<T> = T extends ((infer U) extends number ? 1 : 0) ? 1 : 0; 

// ok, parsed as `infer..extends` (speculative parse succeeds due to no trailing `?`)
type X2<T> = T extends (infer U extends number) ? 1 : 0; 

// ok, parsed as `infer..extends` (conditional types not allowed in 'extends type' of conditional)
type X3<T> = T extends infer U extends number ? 1 : 0; 

// ok, parsed as `infer..extends` (precedence wouldn't have parsed the `?` as part of a type operator)
type X4<T> = T extends keyof infer U extends number ? 1 : 0; 

// ok, parsed as conditional (speculative parse rewinds when it sees the first `?`)
type X5<T> = T extends { [P in infer U extends keyof T ? 1 : 0]: 1; } ? 1 : 0; 

// ok, parsed as `infer..extends` (no trailing `?`)
type X6<T> = T extends { [P in infer U extends keyof T]: 1; } ? 1 : 0; 

// ok, parsed as conditional (speculative parse rewinds when it sees the first `?`)
type X7<T> = T extends { [P in keyof T as infer U extends P ? 1 : 0]: 1; } ? 1 : 0; 

// ok, parsed as `infer..extends` (speculative parse succeeds due to no trailing `?`)
type X8<T> = T extends { [P in keyof T as infer U extends P]: 1; } ? 1 : 0; 
```

It doesn't work quite the same way as `[In]`, since it still requires speculative parsing, but its reliable and consistent and isn't a breaking change.

**Comment by treybrisbane** [comment]
I'm gonna go ahead and ask the dumb question: Why can't we _automatically_ derive the constraint of an inferred type binding from the constraint of the type being matched?

For example, given
```ts
type Quote<AString extends string> = `"${AString}"`;

type QuotedFirstElement<AStringTuple extends readonly string[]> =
  AStringTuple extends readonly [infer FirstElement, ...infer Rest]
    ? Quote<FirstElement> // Currently errors here, because `FirstElement` is only constrained to `unknown`
    : never;
```
why can't we say "well, since `AStringTuple` has a constraint of `readonly string[]`, any _elements_ we infer from it should therefore have a constraint of `string`"?

Intuitively, I suspect there's a very good reason for this and that I just haven't thought it through enough, but someone's gotta spring the trap! 😁

**Comment by rbuckton** [comment]
> I'm gonna go ahead and ask the dumb question: Why can't we _automatically_ derive the constraint of an inferred type binding from the constraint of the type being matched?

We do have automatic inference, and there are ways we can improve it. However, that still wouldn't solve the issue at hand. There are times where you need a more-specific type than what the inferred constraint might allow:

```ts
type X<T extends any[]> =
  T extends [infer U string, ...infer R] ? ... :
  T extends [infer U number, ...infer R] ? ... :
  ...;
```

Above, I might want to make branching decisions based on a more specific constraint. This also ties into #48094, which uses more specific inferences for `infer` in a template literal type to pull out numeric literals.

**Comment by rbuckton** [comment]
This last change modifies the parse based on https://github.com/microsoft/TypeScript/pull/48112#issuecomment-1062494194. 

I wanted to ensure that parenthesization was accurate, so I took a pass through the parenthesizer rule logic for types to be more accurate. One side-effect of that is that we'll emit fewer parens in declarations and diagnostics. Where we might have previously written `(A & B) | (C & D)`, we may now write `A & B | C & D`. The parens weren't strictly necessary, but they may have made the diagnostics more readable. I can make union/intersection parenthesization more aggressive in general, if necessary, or possibly just pass a more aggressive parenthesizer to the printer for `typeToString` if we only want it for diagnostics/quickinfo. 

@DanielRosenwasser, can you provide your thoughts on the change in diagnostics evidenced here: https://github.com/microsoft/TypeScript/pull/48112/commits/38eb41291c7331d1dcf07caf6523fddc97e88fa0?show-viewed-files=true&file-filters%5B%5D=#diff-daa0fded8957f3b2eecdd68e6f89377663f965eb6e9c2b83f36955200b6e858fL5-R6

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
In the user test suite, the only significant baseline change is this: https://github.com/typescript-bot/TypeScript/pull/228/files#diff-c7eb8eb5e1481e5f237ece83369923dbcb3f3ceedbbbbd36706d26f522ebc034L979, which is expected (given https://github.com/microsoft/TypeScript/pull/48112#issuecomment-1065437401)

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
@typescript-bot run dt

**Comment by rbuckton** [comment]
Ping @ahejlsberg, @weswigham, @sandersn, @RyanCavanaugh

**Review by weswigham — CHANGES_REQUESTED** [review]
`typeToTypeNodeHelper`' in the checker needs to include the constraint in the `context.inferTypeParameters` case of `type.flags & TypeFlags.TypeParameter`. If it's not there, we'll elide the constraints in error messages and inferred type declaration emit (eg, if one of these is inlined into a function return type).

Other than that, looks good - pretty simple.

**Comment by rbuckton** [comment]
> `typeToTypeNodeHelper` in the checker needs to include the constraint in the `context.inferTypeParameters` case of `type.flags & TypeFlags.TypeParameter`. If it's not there, we'll elide the constraints in error messages and inferred type declaration emit (eg, if one of these is inlined into a function return type).

I think the latest change should cover this. I reuse `getInferredTypeParameterConstraint`, and elide the `extends` clause if the constraint is something we would have inferred from the surrounding context. Constraints inferred from a type argument to a type references are preserved since the type reference may have been elided during `typeToTypeNode`.

**Review by weswigham — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

**Comment by DaniGuardiola** [comment]
Sorry to reply to a merged PR but I wanted to highlight that a new keyword with similar meaning (`satisfies`) might be introduced in https://github.com/microsoft/TypeScript/issues/47920, and I wonder if that might have been a better option here if that had been merged first. This is in relation to option 4 of [this comment](https://github.com/microsoft/TypeScript/pull/48112#issuecomment-1061104797).

**Pull request merged**
