### PR TITLE
Indirect calls for imported functions

### LINKED ISSUE #35420: Functions wrapped in `__importDefault` with allowSyntheticDefaultImports emit incorrect function calls
The following code:

```ts
import allSettled from "promise.allsettled";

const resolved = Promise.resolve(42);
const rejected = Promise.reject(-1);

allSettled([resolved, rejected]).then(results => {
  console.log(results);
});
```

Is transpiled into the following JS with `esModuleInterop` & `allowSyntheticDefaultImports`:

```js
"use strict";
var __importDefault =
  (this && this.__importDefault) ||
  function(mod) {
    return mod && mod.__esModule ? mod : { default: mod };
  };
Object.defineProperty(exports, "__esModule", { value: true });
const promise_allsettled_1 = __importDefault(require("promise.allsettled"));
const resolved = Promise.resolve(42);
const rejected = Promise.reject(-1);
promise_allsettled_1.default([resolved, rejected]).then(results => {
  console.log(results);
});
```

Full `tsconfig.json`:

```js
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
  },
  "include": [
    "src"
  ]
}
```

([CodeSandbox](https://codesandbox.io/s/inspiring-lewin-eyt6r).)

Executing this code leads to:

```
TypeError: #<Object> is not a constructor
    at Object.resolve (<anonymous>)
    at Object.PromiseResolve (/sandbox/node_modules/es-abstract/es2018.js:160:10)
    at /sandbox/node_modules/promise.allsettled/implementation.js:26:24
    at Function.from (<anonymous>)
    at Object.allSettled (/sandbox/node_modules/promise.allsettled/implementation.js:19:22)
    at Object.allSettled [as default] (/sandbox/node_modules/promise.allsettled/index.js:16:9)
    at Object.<anonymous> (/sandbox/src/demo.ts:6:11)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.m._compile (/sandbox/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

That is because the promise.allsettled package handles `this` according to the spec, see https://github.com/es-shims/Promise.allSettled/issues/5. The author of that library is @ljharb who will have deeper understanding of the specifics than I do. (Also, thanks for nudging me to report this issue!)

The problem is most likely the emitted function call, which looks like this:

```js
promise_allsettled_1.default([resolved, rejected]).then(results => {
  console.log(results);
});
```

In comparison, Babel + TS emits this (which works):

```js
(0, _promise.default)([resolved, rejected]).then(function (results) {
  console.log(results);
});
```

[Babel playground](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAQwDZIMoFMYyegJnAMyghDgHIxiRgBndAOmSTqx1zIG4AoLgYwgB2NeFHQ0ISAG544AXjgAFKrQajxU9AAoALACYAlN35CR6AFbpeMGfKUkV9URauaAtAEZDPJhlZ5NANpqEtK4ADRwTpbWuAC6-vQwABboAppqAK5IMDRyAHxwAN5ccHDG6gxIEADm6WJZOV4AvoZAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.7.4&externalPlugins=).

**TypeScript Version:**  3.7.2

**Search Terms:** `esModuleInterop`, `allowSyntheticDefaultImports`, emit, transpile, downlevel compile, ES Modules, default, wrapper, Node.js, module.

### PR DESCRIPTION
**Pull request by rbuckton**
Another attempt to address indirect calls for imported functions.

Fixes #35420

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot perf test

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
Other stuff looks fine but let's not include `package-lock.json` as part of this (if we want to do that at all)

**Comment by rbuckton** [comment]
package-lock existing is surprising. I thought we had an .npmrc that disabled package-lock.

**Comment by rbuckton** [comment]
I guess we started generating a `package-lock.json` at some point, but its still in our `.gitignore`. I've restored the version from `main`.

**Comment by rbuckton** [comment]
package-lock.json has been reverted. @RyanCavanaugh: any other conserns or should I merge?

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request merged**
