### PR TITLE
Add jsdoc nodes to fixupParentReferences function

### LINKED ISSUE #8676: Jsdoc `@template` issue in syntactic classifier
Consider the following: 

```ts
/**
 * @template T
 */
function ident<T>(x:T):T {
    return ident;
}
```

`getEncodedSyntacticClassifications` will fail with `Cannot read property 'text' of undefined`

**Stack**:
```
NodeObject.createChildren	@	ntypescript.js:50808
NodeObject.getChildren	@	ntypescript.js:50845
processJSDocTemplateTag	@	ntypescript.js:56304
classifyJSDocComment	@	ntypescript.js:56270
classifyComment	@	ntypescript.js:56243
classifyLeadingTriviaAndGetTokenStart	@	ntypescript.js:56213
tryClassifyNode	@	ntypescript.js:56345
processElement	@	ntypescript.js:56482
processElement	@	ntypescript.js:56484
processElement	@	ntypescript.js:56484
getEncodedSyntacticClassifications	@	ntypescript.js:56185
```

**Reason**: `sourceFile` is `undefined` somewhere in the stack

**Version** : latest as of this morning

refs https://github.com/alm-tools/alm/issues/82 :rose:

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #8676

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by basarat** [comment]
no :game_die: (dice) :-/

image

**Comment by mhegazy** [comment]
closing this one.

**Comment by mhegazy** [comment]
should be handled by https://github.com/Microsoft/TypeScript/pull/8103

**Pull request closed without merging**
