### PR TITLE
[experiment] playing around with default strictness

### PR DESCRIPTION
**Pull request by jakebailey**
ignore me, thx; just bored and curious

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ssalbdivad** [comment]
🚢🙏

**Comment by fatcerberus** [comment]
The number of new implicit-any errors this produces is alarming...

**Comment by jakebailey** [comment]
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Pull request closed without merging**
