### PR TITLE
Add ES2022 `Intl.Segmenter` type

### LINKED ISSUE #48523: Missing type of ES2022 `Intl.Segmenter`
# lib Update Request

## Configuration Check

My compilation *target* is `ES2022` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Intl.Segmenter`

## Sample Code

```ts
const SEGMENTER = new Intl.Segmenter('en', { granularity: 'grapheme' });
```

## Documentation Link

https://github.com/tc39/proposal-intl-segmenter

### PR DESCRIPTION
**Pull request by petamoriken**
Fixes #48523

### CODE REVIEW

**Review by jakebailey — COMMENTED** [review]
This is a nit, but it looks like every other lib `d.ts` file is formatted with four spaces, the standard we use in this repo, while the file added here uses two.

**Review by jakebailey — APPROVED** [review]

**Comment by leoriviera** [comment]
Taking a looking at the [MDN article for this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter#parameters), the locale is optional, meaning the first argument may be an object containing options for the segmenter.

**Comment by jakebailey** [comment]
The [syntax section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter#syntax) implies that you have to provide `locales` if you want to supply `options`. The definition in this PR already makes it optional in that way (pass `undefined`).

If you pass an options object as the first parameter, the Segmenter you get back doesn't work properly, so I don't think that's correct (even if it doesn't crash). Try deleting `'fr'` from the code example on the page and run it, then compare if you pass `undefined`.

**Comment by leoriviera** [comment]
I did weigh up the syntax section when writing this comment. Thank you for clarifying my understanding of this. I really appreciate it.

**Pull request merged**
