### PR TITLE
Defer indexed access T[K] with non-generic K

### LINKED ISSUE #12651: Method signatures containing references to properties of constrained generic types are resolving through the constraint instead of the supplied type argument
**TypeScript Version:** nightly (2.2.0-dev.20161203)

I currently find it somewhat hard to precisely describe the issue/suggestion, but I believe this use case should demonstrate it clearly:

```ts
type MethodDescriptor = {
	name: string;
	args: any[];
	returnValue: any;
}

function dispatchMethod<M extends MethodDescriptor>(name: M['name'], args: M['args']): M['returnValue'];

type SomeMethodDescriptor = {
	name: "someMethod";
	args: [number, string];
	returnValue: string[];
}

// Currently, there's no compilation error on the the invalid second argument type and the 
// return type is inferred as "any" instead of "string[]":
let result = dispatchMethod<SomeMethodDescriptor>("someMethod", ["hello", 35]);
```

The general idea here is that the types are used unconventionally: not to describe interfaces to run-time objects but as a way to "pack" a set of type arguments into an "object-like" compile-time entity. Perhaps this could be called something like "packed type arguments" or "type argument classes" or maybe "type argument schema containers"? I'm not sure.

Anyway, I was trying to write a general purpose dispatcher that can invoke a set of actions, and that seemed like a more elegant and type safe alternative to the more conventional:
```ts
function dispatchMethod<A extends any[], R>(name: string, args: A): R;

dispatchMethod<[number, string], string[]>("someMethod", ["hello", 35]); // <- errors as expected
```

### LINKED ISSUE #12723: Lookup types and polymorphic this issue
**TypeScript Version:**  2.1.4

**Code**

```ts
interface A<T> { value: T }
interface B extends A<string> { }

abstract class C<T extends A<any>> {
    private t: T;
    get a(): this['t']['value'] { return this.t.value };
}

class D extends C<B> {
    get b() { return this.a; }
}

```

**Expected behavior:**

I would expect that the type of ``D.b`` would be ``string``.

**Actual behavior:**

Type of  ``D.b`` is ``any``

### LINKED ISSUE #12744: Type inference problem in generic subtypes of index signature types
**TypeScript Version:**  2.1.4

**Code**

```ts
// Type with index signature
type StringToNumber = {[id: string]: number};

// This works!
type ShouldBeNumber = StringToNumber[keyof StringToNumber];
let x: ShouldBeNumber = <number>0;
let y: number = x;

// This doesn't work.
class Pred<X extends StringToNumber> {
  test(value: X[keyof X]) {
    // error TS2322: type 'X[keyof X]' is not assignable to type 'number'
    let slot: number = value;

    // error TS2352: Type 'X[keyof X]' cannot be converted to type 'number'.
    let slot2 = <number> value;
  }
}
```

**Expected behavior:**
If I understand the spec correctly, all of `X`'s properties must be subtypes of their corresponding properties in `StringToNumber`. All of `StringToNumber`'s properties are of type `number`, so `X[keyof X]` should be a subtype of / assignable to `number`.

**Actual behavior:**
As far as I can tell, no relationship is inferred between the types `X[keyof X]` and `number`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we defer resolution of indexed access types `T[K]` where `T` is generic and `K` is non-generic.

```ts
function getValue<T extends { value: string | number }>(obj: T): T['value'] {
    return obj.value;
}

let x1 = getValue({ value: 'hello' });  // string
let x2 = getValue({ value: 42 }); // number
```

In the example above, the indexed access type `T['value']` is permitted because `T` is constrained to a type that has a property named `value`. The type `T['value']` behaves like a subtype of `string | number` because that is the type of `value` in the constraint type, and when instantiation substitutes an actual type for `T`, the type of the `value` property in that actual type is substituted for `T['value']`.

Note that for backwards compatibility reasons, the expression `obj.value` is still eagerly resolved to type `string | number`. The expression must be explicitly coerced to `T['value']` using a type annotation or a type assertion in order to get the deferred behavior.

This PR also implements better circularity detection and reporting for indexed access types. For example:

```ts
type T1 = {
    x: T1['x'];  // Error
};
```

Note that circularities may sometimes result only for certain arguments to type parameters.

```ts
type T2<K extends 'x' | 'y'> = {
    x: T2<K>[K];  // Error
    y: number;
 }
 
declare let obj: T2<'x'>;
let x = obj.x;
```

If the type of `obj` above is changed to `T2<'y'>` the circularity error goes away.

Fixes #12651.
Fixes #12723.
Fixes #12744.

### CODE REVIEW

**Comment by eschwartz** [comment]
I just want to point out that once this is fixed, we should be able to implement a better `EventEmitter` definition, with typed events.

For example

```ts
// Encapulate an event's name and data
interface EventType<TName extends string, TData extends any> {
  name: TName;
  data: TData;
}

class EventEmitter<TEventType extends EventType<string, any>> {
  on<TType extends TEventType>(name: TType["name"], listener:(event: TType["data"]) => void):this;
  /*...*/
}
```

Usage:

```ts
type EventTypeA = EventType<'a', { foo: string; }>;
type EventTypeB = EventType<'b', { bar: string; }>;

const emitter = new EventEmitter<EventTypeA | EventTypeB>();

// emitter.on requires that the event name and data match the provided EventType
emitter.on<EventTypeA>('a', (evt) => {
  evt.foo;
});
emitter.on(EventTypeB>('b', (evt) => {
  evt.bar;
});
```

**Comment by eschwartz** [comment]
Any idea when this might be released? Should we be expecting a `2.1.5` to come out soon with this fix?

_(also, thanks for all the work on this. This is really cool stuff, and I'm having a ton of fun using it)_

**Comment by rotemdan** [comment]
I believe I've found an alternative, though less elegant, approach to [my dispatcher example](https://github.com/Microsoft/TypeScript/issues/12651#issuecomment-264734341) that doesn't rely on discriminated unions and might work with the new inference capability described here without any need for additional syntax:

```ts
type DispatcherSchema = { [name: string]: { args: any[]; returnType: any } };

class Dispatcher<S extends DispatcherSchema> {
	dispatch<K extends keyof S>(name: K, args: S[K]['args']): S[K]['returnType'] {
	}
}

type MySchema = {
	"read": { 
		args: [string, number]; 
		returnType: string[]
	}

	"write": {
		args: [string, string[], boolean]; 
		returnType: number
	}
}

const dispatcher = new Dispatcher<MySchema>();
var result = dispatcher.dispatch("read", ["myfile.txt", 35]); // <- ok
var result = dispatcher.dispatch("read", "myfile.txt"); // <- already fails
var result = dispatcher.dispatch("reed", ["myfile.txt", 35]); // <- already fails
var result = dispatcher.dispatch("write", ["myfile.txt", "oops", true]); // <- should fail with this PR
```

It seems promising but I have not tested this yet though (I'm waiting for the pull request to be merged and arrive to the nightly builds).

**Comment by eschwartz** [comment]
Just downloaded `typescript@2.2.0-dev.20161212`, and my `EventEmitter` example is working great :+1:

**Comment by eschwartz** [comment]
Any chance this can make it into [2.1.5](https://github.com/Microsoft/TypeScript/milestone/35)?

**Pull request merged**
