### PR TITLE
Make update-sublime depend on local task

### LINKED ISSUE #3805: 'jake update-sublime' doesn't work when workspace is clean
Repro:

```shell
jake clean
jake update-sublime
```

This tries to build tsserver, but tsserver needs tsc to be built and it isn't.

### PR DESCRIPTION
**Pull request by danquirk**
Fixes #3805

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Shouldn't `serverFile` depend on `local`?

**Comment by danquirk** [comment]
It could but the way we have it setup now doesn't allow that as far as I'm aware. serverFile only uses the file() not task(), so its dependencies can only be other file() targets and not task() targets. I think we'd have to make an actual serverFile task (as in 'jake serverFile' or something) in order to create that dependency chain. Right now nothing else depends on serverFile so we can just get away with this quick fix. Maybe by the time we need to do more we'll have migrated to grunt or gulp or something ;)

**Pull request merged**
