### PR TITLE
Run tests on all OSs

### PR DESCRIPTION
**Pull request by jakebailey**
Up until now, we only tested Linux in CI. It seems like a good idea to test all of our supported platforms and versions (especially since we get it "for free" in parallel).

### CODE REVIEW

**Comment by jakebailey** [comment]
Wow, after multiple reruns, I think `declarationEmitPrivatePromiseLikeInterface` is literally too slow to finish on a Windows CI builder with Node 14.

**Comment by jakebailey** [comment]
The above is hopefully better after #52382 (the PR saved a significant amount on that test). We'll see if it passes or if there's still more to find.

**Comment by jakebailey** [comment]
Marking this as ready-for-review; it seems to be working with that performance bump from reused Printers.

**Comment by jakebailey** [comment]
Oh, hm, it was actually macOS this last time that was slow. It's a minute or so faster now but not really in range of other machines.

**Review by weswigham — APPROVED** [review]
We'd probably be fine with only testing all OSes on latest `node`, coverage-wise, but the full matrix is fine, since, y'know, it's not like we're getting billed, right? 😆 (...do we have a GHA max worker limit?)

**Comment by jakebailey** [comment]
> (...do we have a GHA max worker limit?)

We totally don't; back Python's typeshed repo (equivalent to DT) runs _54_ jobs per PR/commit.

One reason I would be testing on the full matrix is that we've seen breaks like how Node upgraded its `icu` library and changed the output of `Date.toLocaleTimeString()`; that one happened to occur on Linux (so we caught it), but I think something like that is equally likely to happen on the other OSs too.

**Comment by jakebailey** [comment]
Well, I guess "latest" would get us those breaks, yeah. But I don't think there's really a downside of testing everything.

**Comment by jakebailey** [comment]
declarationEmitPrivatePromiseLikeInterface is still flaky, it seems. Will have to keep profiling it.

**Review by sheetalkamat — APPROVED** [review]

**Pull request merged**
