### PR TITLE
Add console types

### PR DESCRIPTION
**Pull request by sandersn**
From https://github.com/microsoft/TSJS-lib-generator/pull/452

Test diffs look OK, so I'm going to run user/docker/RWC/DT tests

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot user test this
@typescript-bot run dt
@typescript-but test this

**Comment by sandersn** [comment]
@typescript-bot test this

**Comment by sandersn** [comment]
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot test this

**Comment by sandersn** [comment]
@weswigham looks like both user tests and RWC tests fail. user tests run and then fail early on in the upload with

```
fatal: couldn't find remote ref refs/heads/37048/head
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
```

RWC tests fail when trying to open the PR with:

```
Branch 'rwc-pr-37048' set up to track remote branch 'rwc-pr-37048' from 'origin'.
Error: TF401179: An active pull request for the source and target branch already exists.
    at RestClient.<anonymous> (/home/vsts/work/1/s/internal/scripts/tsscripts/node_modules/typed-rest-client/RestClient.js:173:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/1/s/internal/scripts/tsscripts/node_modules/typed-rest-client/RestClient.js:6:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

So I guess this already opened a PR, but failed to switch over to pushing commits.

**Comment by weswigham** [comment]
Ah, I typo'd my change to the user test script in devops to retarget the PR to the branch head (it should be refs/pulls, not refs/heads).

The RWC thing is normal so long as an RWC diff PR already exists for the PR; that RWC diff PR still gets a forced update (and since the build itself already failed, I don't really consider the nonzero exit of the pr script to be an issue)

**Comment by weswigham** [comment]
The user run should now be using the correct ref name for the PR phase~

**Comment by sandersn** [comment]
Using the RWC run from 10:30, I see that:

1. Angular 2 used profile and profileEnd, and an MS internal project does too.
2. Assumes that `Window` has a property `console`, except that they use a custom subclass of Window so they don't get the `window: Window & typeof globalThis`.
3. Another one, but just has a type reference to `Window`.
3. Uses `Console` as a type. (these last two are in introspective code that is probably uncommon)
4. core-js tries to extend the `Console` type.

The main surprise for me was (1). (2) - (5) are definitely breaking changes, even though they are fairly rare.

**Pull request closed without merging**
