### PR TITLE
(Weak)map & set constructor for target ES5, lib ES6

### LINKED ISSUE #8407: Map constructor doesn't work with target ES5, lib ES6
**TypeScript Version:** 

1.7.5 / 1.8.0-beta / nightly (1.9.0-dev.20160430)

**Code**

```ts
const x = new Map([["a", 1]]); // Error
const y = new Map<string, number>([["a", 1]]); // Error
const z = new Map([<[string, number]>["a", 1]]); // Works
```
```json
{
	"compilerOptions": {
		"target": "es5",
		"lib": ["es2016"]
	}
}
```
**Expected behavior:**
No errors

**Actual behavior:** 
Errors are reported on the first two lines:
```
Argument of type '(string | number)[][]' is not assignable to parameter of type 'Iterable<[{}, {}]>'. 
Argument of type '(string | number)[][]' is not assignable to parameter of type 'Iterable<[string, number]>'.
```
I think the reason is that the compiler doesn't use iterators to resolve the type arguments when the target is ES5. Adding an overload to the `Map` constructor, which takes an array of tuples instead of an iterator, would probably fix this. I'm not sure whether this happens on more locations though, if so it might be worth to pick up iterators in the compiler even when the target is ES5.

### PR DESCRIPTION
**Pull request by ivogabe**
Fixes #8407

### CODE REVIEW

**Comment by yuit** [comment]
lgtm

**Comment by malibuzios** [comment]
I use `Map` in ES5 targets all the time, actually I heavily rely on it. My workaround used to be to my own custom declarations, however at some point I realized they were subtly incompatible with the ones for ES5 because of things like Iterators, Symbols etc. I also needed promises at some point. Eventually I gave up and simply added a copy of `lib.es6.d.ts` to all targets to override the default one. That actually seems to work fine somehow.. 

I also have polyfills for `Map` and `Set` for older browsers so I need to comply with the exact same interface for all targets. I'm not sure if this would eventually help but thanks.

**Comment by mhegazy** [comment]
This change should be made to [src\lib\es2015.collection.d.ts](https://github.com/Microsoft/TypeScript/blob/master/src/lib/es2015.collection.d.ts), this file is generated from the build. see https://github.com/Microsoft/TypeScript/blob/master/src/lib/README.md for more details.

**Comment by mhegazy** [comment]
closing for now. please resubmit for src\lib\es2015.collection.d.ts

**Pull request closed without merging**
