### PR TITLE
fix(58801): "Move to file" on global code unnecessarily imports/exports, generates invalid code

### LINKED ISSUE #58801: "Move to file" on global code unnecessarily imports/exports, generates invalid code
```ts
// main.ts

interface String {
    malkovich(): string;
}

[|String.prototype.malkovich = function (): string {
    return "malkovich";
}|]
```

1. Select the range.
2. Request "move to a new file"

## Current

```ts
// newFile.ts
import { String } from "./strs";

String.prototype.malkovich = function (): string {
    return "malkovich";
};

// main.ts
export export export export export export export interface String {
    malkovich(): string;
}

export export export export export export 
```

## Expected

```ts
// newFile.ts
String.prototype.malkovich = function (): string {
    return "malkovich";
};

// main.ts
interface String {
    malkovich(): string;
}

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #58801

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
This looks right, though it seems like it doesn’t explain the `export export export export export export function` bug 😄 Was there any clue about why that happened as you were debugging?

**Comment by a-tarasyuk** [comment]
@andrewbranch The `moveToFile` refactoring adds the same symbol to each declaration...

> targetFileImportsFromOldFile.set(symbol, isValidTypeOnlyUseSite); 

https://github.com/microsoft/TypeScript/blob/d8086f14b6b97c0df34a0cc2f56d4b5926a0c299/src/services/refactors/moveToFile.ts#L901-L912

**Comment by a-tarasyuk** [comment]
It looks like these changes fix the crash mentioned in https://github.com/microsoft/TypeScript/issues/58806., the [moveToNewFile_global3.ts](https://github.com/microsoft/TypeScript/pull/58811/files#diff-9eae48c3c4d39ae4bcaf52556262b5b15b814f53051e874e0ac120886e5d2804) test covers this case.

**Comment by andrewbranch** [comment]
Good to merge as soon as @navya9singh signs off!

**Review by DanielRosenwasser — APPROVED** [review]
I think I'm good with this, and I'd like to get it in for 5.5.2.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.5 and LKG

**Pull request merged**
