### PR TITLE
feat: support parser of record and tuple

### LINKED ISSUE #39831: proposal-record-tuple
https://github.com/tc39/proposal-record-tuple is stage-2.

I'm a little worry about the global Record object and our utils type Record<>.

### PR DESCRIPTION
**Pull request by Jack-Works**
close #39831

- [x] Parser
- [ ] Add global `Record`, `Tuple`, `Box` constructor
- [ ] Type check
- [ ] ~Emitter~ (No plan to work on the emitter like what TypeScript did on BigInt).
- [ ] Add tests
- [ ] Add `box` unwrap on completion
- [ ] Add `box` wrapper on completion

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Hey @Jack-Works, thanks for the PR. This feature is something that has pretty deep type system implications and I think it's something the core team needs to spend some time on discussing the finer details. You're obviously free to continue iterating, but I think we want to give a fair bit of warning that what ends up here might diverge drastically from the design we arrive at, and we may end up creating a separate pull request if those changes are very involved.

**Comment by Jack-Works** [comment]
Okay, so I may stop at the parser and very simple type integration. Is that ok? Or I can wait for the official design. @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Sorry I didn't see the above comment. We're open to experiments and understanding issues/constraints that you run into, but from our most recent design meeting it really seemed like others would be more comfortable with a PR that comes from the core team because of the scope of the feature.

**Comment by Jack-Works** [comment]
hope the official team can support this quick after it reach stage 3 or 4 👀

**Pull request closed without merging**
