### PR TITLE
Consider property accesses in heritage clauses as type-space references

### LINKED ISSUE #15487: <reference types="" /> is not emitted when dependency is in a namespace
**TypeScript Version:**  2.3.2

**Code**

```ts
// deps/dep/dep.d.ts
declare namespace NS {
    interface Dep {
    }
}
```

```json
// deps/dep/package.json
{
  "typings": "dep.d.ts"
}
```

-----

```ts
// src/index.ts
class Src implements NS.Dep {}
```

Compile with

```json
// src/tsconfig.json
{
    "compilerOptions": {
        "declaration": true,
        "types": [
            "dep"
        ],
        "typeRoots": [
            "../deps"
        ]
    }
}
```

**Expected behavior:**
```ts
// src/index.d.ts
/// <reference types="dep" />
declare class Src implements NS.Dep {
}
```

**Actual behavior:**
```ts
// index.d.ts
declare class Src implements NS.Dep {
}
```

If the `namespace` is removed from `dep.d.ts` (with an interface at the top-level), the `<reference>` _is_ (correctly) emitted.

### PR DESCRIPTION
**Pull request by weswigham**
at least for calculating type reference directives.

Fixes #15487

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Wait, I don't understand; in an `implements` heritage clause, I would have assumed we'd parse our a type reference, not a property access.

**Comment by RyanCavanaugh** [comment]
`parseHeritageClause` doesn't differentiate `implements` from `extends`; it always interprets the operands as expressions:
```ts
        function parseHeritageClause(): HeritageClause | undefined {
            const tok = token();
            if (tok === SyntaxKind.ExtendsKeyword || tok === SyntaxKind.ImplementsKeyword) {
                const node = <HeritageClause>createNode(SyntaxKind.HeritageClause);
                node.token = tok;
                nextToken();
                node.types = parseDelimitedList(ParsingContext.HeritageClauseElement, parseExpressionWithTypeArguments);
                return finishNode(node);
            }

            return undefined;
        }
```
e.g. `class C implements {} { }` is a semantic error, not a syntax error

**Comment by weswigham** [comment]
Yeah - it'd be kinda odd to parse them differently (it's make handling them a pain, at least, since you'd need both type-space and value-space codepaths for everything syntactically heritage-clause related).

**Comment by azz** [comment]
Thanks for the fix! Does this change also fix #15488?

**Pull request merged**
