### PR TITLE
Better typings for Array.concat(), etc.

### LINKED ISSUE #19535: Soundness issue with Array.prototype.concat and arrays of arrays
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
const foo: [number, string][] = [[1, 'one']];
console.log(foo.concat([2, 'two']));
```

**Expected behavior:**
Either `[[1, 'one'], [2, 'two']]` or a type error.

**Actual behavior:**
`[[1, 'one'], 2, 'two']`

### LINKED ISSUE #24579: Handle heterogeneous arrays in flat and flatMap
The typings for both flat and flatMap work ok for homogeneous arrays but do not handle tuple types well. Consider the current typings (with rename):

```ts
declare let arr: [[number, boolean], string];
let x0 = arr.flatten(0); // (string | [ number, boolean ])[]
let x1 = arr.flatten(1); // error
let x2 = arr.flatten(2); // error
```

Using conditional types and `infer` we can start to see a solution like:

```ts
type Flatten0<T> = T extends Array<infer U> ? Array<U> : never;

type Flatten1<T> = T extends Array<infer U>
    ? U extends Array<any> ? Flatten0<U> : never
    : never;
type Flatten2<T> = T extends Array<infer U>
    ? U extends Array<any> ? Flatten1<U> : never
    : never;
        
interface Array<T> {
    flat<T>(this: T, depth: 2): Flatten2<T>;
    flat<T>(this: T, depth: 1): Flatten1<T>;
    flat<T>(this: T, depth: 0): Flatten0<T>;
    flat<T>(this: T, depth: number): Array<T>
}
```

Which works great for array types and handles some tuple types better, but sacrifices a type error on the depth parameter when the array isn't nested that much, and more importantly, doesn't handle heterogeneous tuple cases, e.g. `[ [string, number], boolean]` should flatten to `[string, number, boolean]`. As far as I can tell, this is not possible without [variadic kinds](https://github.com/Microsoft/TypeScript/issues/5453). Additionally, this implementation would benefit hugely from a way to reference a type recursively, e.g. [https://github.com/Microsoft/TypeScript/issues/6230](6230) (I'm [not the only one](https://github.com/Microsoft/TypeScript/issues/22018) to notice this issue trying to type this API).

### LINKED ISSUE #26378: Support concat operations on arrays of different types
## Search Terms

concat, array, type

## Suggestion

Currently concat requires that arrays be of similar types (or arrays of arrays of similar type). This requirement can be too strict at times. Since concat doesn't change the source arrays, it seems reasonable to return an array of the union of the input array types. 

This can be achieved by adding an overload to Array.concat:

```
Array<T> {
  concat<U>(...items: (U | ConcatArray<U>)[]): Array<T|U>;
}
```

## Use Cases

Joining dissimilar arrays.

## Examples

Simple example below. A more realistic example would probably involve arrays of more complex, type-inferred objects that are mostly similar but slightly different.

const nums=[1,2,3];
const strs = ['a','b','c'];

// Currently, must do something like:
const arr1 = (nums as Array<string|number>).concat(strs);

// With this proposal we can instead use:
const arr2 = nums.concat(strs);

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

### LINKED ISSUE #26976: Add additional overloads to Array.prototype.concat
## Search Terms

concat never

## Suggestion

Add the following signatures to the `Array` interface:

```ts
interface Array<T> {
    concat<U>(this: Array<never>, ...items: ConcatArray<U>[]): U[];
    concat<U>(this: Array<never>, ...items: (U | ConcatArray<U>)[]): U[];
}
```

For my use case this is not needed in `ReadonlyArray`, but could be added for consistency.

## Use Cases

I often find myself in the need of using `Array.prototype.flatMap`, but since I target Node.js 6 it's not available. Therefore I try to replace it with `[].concat(someArray.map(mightReturnArray))`.
But then I get an error like `Type 'whatever' is not assignable to type 'never'.` (with `strictNullChecks` enabled).

## Examples

```ts
interface Array<T> {
    /**
     * Combines two or more arrays.
     * @param items Additional items to add to the end of array1.
     */
    concat<U>(this: Array<never>, ...items: ConcatArray<U>[]): U[];
    /**
     * Combines two or more arrays.
     * @param items Additional items to add to the end of array1.
     */
    concat<U>(this: Array<never>, ...items: (U | ConcatArray<U>)[]): U[];
}

// now OK
[].concat(['a']);
['a'].concat(['b']);

// still an error as expected
[1].concat(['a']);
```

http://www.typescriptlang.org/play/#src=interface%20Array%3CT%3E%20%7B%0A%20%20%20%20%2F**%0A%20%20%20%20%20*%20Combines%20two%20or%20more%20arrays.%0A%20%20%20%20%20*%20%40param%20items%20Additional%20items%20to%20add%20to%20the%20end%20of%20array1.%0A%20%20%20%20%20*%2F%0A%20%20%20%20concat%3CU%3E(this%3A%20Array%3Cnever%3E%2C%20...items%3A%20ConcatArray%3CU%3E%5B%5D)%3A%20U%5B%5D%3B%0A%20%20%20%20%2F**%0A%20%20%20%20%20*%20Combines%20two%20or%20more%20arrays.%0A%20%20%20%20%20*%20%40param%20items%20Additional%20items%20to%20add%20to%20the%20end%20of%20array1.%0A%20%20%20%20%20*%2F%0A%20%20%20%20concat%3CU%3E(this%3A%20Array%3Cnever%3E%2C%20...items%3A%20(U%20%7C%20ConcatArray%3CU%3E)%5B%5D)%3A%20U%5B%5D%3B%0A%7D%0A%0A%2F%2F%20now%20OK%0A%5B%5D.concat(%5B'a'%5D)%3B%0A%5B'a'%5D.concat(%5B'b'%5D)%3B%0A%0A%2F%2F%20still%20an%20error%20as%20expected%0A%5B1%5D.concat(%5B'a'%5D)%3B
Remember to enable `strictNullChecks`

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

### LINKED ISSUE #29604: Wrongly infers any[] from Array.prototype.flat, Array.prototype.concat
**TypeScript Version:**  3.2.4, 3.3.0-dev.20190126

**Search Terms:** array, flat, concat, any, unsound

**Code**

```ts
const a: boolean[] = [[17], ["foo"]].flat();  // wrongly accepted
const b: boolean[] = Array.prototype.concat([17], [19], [21]);  // wrongly accepted
```

Using `tsc --strict -t esnext`.

(What I’m really trying to do: find a type safe way to concatenate an array of arrays. It’d be nice if `[].concat(...arrays)` were accepted, which I think would be a consequence of #26976, but that’s not the issue I’m reporting here. `arrays.flat()` and `Array.prototype.concat(...arrays)` are accepted but apparently provide no type safety.)

**Expected behavior:** `[[17], ["foo"]].flat()` should be typed `(number | string)[]` (if it’s accepted at all), and `Array.prototype.concat([17], [19], [21])` should be typed `number[]`. In both cases the assignment to `boolean[]` should be rejected.

**Actual behavior:** TypeScript infers `any[]` for both right hand sides (even with `--noImplicitAny` implied by `--strict`), and accepts the assignments to `boolean[]` with no complaints.

**Playground Link:** Playground doesn’t support `esnext`, but here’s the [second line](https://www.typescriptlang.org/play/#src=const%20b%3A%20boolean%5B%5D%20%3D%20Array.prototype.concat(%5B17%5D%2C%20%5B19%5D%2C%20%5B21%5D)%3B).

**Related Issues:** #19535 for `concat` (but that one may have more to do with the difficulty of typing `concat`’s weird behavior when non-arrays are passed?), #26976

### LINKED ISSUE #31033: flatMap errors when callback returns certain union type
**TypeScript Version:**  3.4.3

**Search Terms:** flat, flatmap

**Code**

```ts
// Map<string, number[]>
const myMap = new Map([
  ['foo', [1, 2, 3]],
  ['bar', [4, 5, 6]]
]);

// string[]
const myArray = ['foo', 'bar', 'baz'];

// (key: any) => number[] | undefined
const mapFn = key => myMap.get(key);

const flatMapped = myArray.flatMap(mapFn);
```

**Actual behavior:**

With strict null checks on:

```
Argument of type '(key: any) => number[] | undefined' is not assignable to parameter of type '(this: undefined, value: string, index: number, array: string[]) => number | readonly number[]'.
  Type 'number[] | undefined' is not assignable to type 'number | readonly number[]'.
    Type 'undefined' is not assignable to type 'number | readonly number[]'. ts(2345)
```

Turning strict null checks off prevents the error as you might expect, but that's obviously not desirable.

**More code**

Seeing if doing the operations separately will help:

```ts
// (number[] | undefined)[]
const mapped = myArray.map(mapFn);

// any[] !!
const flattened = mapped.flat();
```

**Expected behavior:**

`flatMapped`/`flattened` result to be inferred as `(number | undefined)[]`.

**Playground Link:** 

Doesn't seem to be able to load the appropriate library definition, even with `/// <reference lib="es2019.array" />`

**Related Issues:** 

#29604 seems to be related to the `.flat()` part.

### PR DESCRIPTION
**Pull request by jablko**
Roll up #33606, #33620 and #33630

Fixes #19535
Fixes #24579
Fixes #26378
Fixes #26976
Fixes #29604
Fixes #31033

### CODE REVIEW

**Comment by jablko** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by orta** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by jablko** [comment]
@RyanCavanaugh Thanks! Could I please trouble you to trigger @typescript-bot run dt as well?

**Comment by RyanCavanaugh** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
@DanielRosenwasser we should probably discuss this in a design meeting after we get an analysis of how breaky it is to user/DT/RWC tests. Though maybe we should hold this until after [the existing effort to gather broken Array examples](https://github.com/microsoft/TypeScript/issues/36554) is done.

**Comment by ljharb** [comment]
Any update on this? I'm hoping it allows for idiomatic usage of eg `[].concat(a || [], b || [])`.

**Comment by sandersn** [comment]
This has been sitting for a long time, and a big part of that is the difficulty in making any change to array types. I think it has to be a single major update like #36554 nowadays. I'm going to close this PR, although it may be useful as a basis for a part of that work.

**Pull request closed without merging**
