### PR TITLE
Fixes the interaction of sourcemap and source comments

### LINKED ISSUE #4003: incorrect source map
I think the source maps being generated are incorrect in some instances.  I had an IntelliJ 'node' project working in 1.5.0-beta that experienced debugging problems (not stopping at some breakpoints, and not stopping at each line when stepping) when I moved to 1.5.3.  I have tracked down the problem (I think) to a difference in the source maps being generated if there are comments involved.  Some simplified code:

    module sas.tools
    {
        export class Test
        {
            public doX():void
            {
                let f:number=2;
                switch (f)
                {
                    case 1:
                        break;
                    case 2:
                        //line comment 1
                        //line comment 2
                        break;
                    case 3:
                        //a comment
                        break;
                }
            }
        }
    
    }

These json options:     
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "noImplicitAny":true,
    "suppressImplicitAnyIndexErrors":true,
    "target": "ES5",

1.5.0-beta sourcemap data: {"version":3,"file":"Test.js","sourceRoot":"","sources":["sourceMapTest/sas/tools/Test.ts"],"names":["sas","sas.tools","sas.tools.Test","sas.tools.Test.constructor","sas.tools.Test.doX"],"mappings":"AAAI,IAAO,GAAG,CAsBT;AAtBD,WAAO,GAAG;IAACA,IAAAA,KAAKA,CAsBfA;IAtBUA,WAAAA,KAAKA,EAChBA,CAACA;QACGC;YAAAC;YAkBAC,CAACA;YAhBUD,kBAAGA,GAAVA;gBAEIE,IAAIA,CAACA,GAAQA,CAACA,CAACA;gBACfA,MAAMA,CAACA,CAACA,CAACA,CAACA,CACVA,CAACA;oBACGA,KAAKA,CAACA;wBACFA,KAAKA,CAACA;oBACVA,KAAKA,CAACA;wBACFA,gBAAgBA;wBAChBA,gBAAgBA;wBAChBA,KAAKA,CAACA;oBACVA,KAAKA,CAACA;wBACFA,WAAWA;wBACXA,KAAKA,CAACA;gBACdA,CAACA;YACLA,CAACA;YACLF,WAACA;QAADA,CAACA,AAlBDD,IAkBCA;QAlBYA,UAAIA,OAkBhBA,CAAAA;IAELA,CAACA,EAtBUD,KAAKA,GAALA,SAAKA,KAALA,SAAKA,QAsBfA;AAADA,CAACA,EAtBM,GAAG,KAAH,GAAG,QAsBT"}
1.5.3 sourcemap data: {"version":3,"file":"Test.js","sourceRoot":"","sources":["sourceMapTest/sas/tools/Test.ts"],"names":["sas","sas.tools","sas.tools.Test","sas.tools.Test.constructor","sas.tools.Test.doX"],"mappings":"AAAA,IAAO,GAAG,CAsBT;AAtBD,WAAO,GAAG;IAACA,IAAAA,KAAKA,CAsBfA;IAtBUA,WAAAA,KAAKA,EAChBA,CAACA;QACGC;YAAAC;YAkBAC,CAACA;YAhBUD,kBAAGA,GAAVA;gBAEIE,IAAIA,CAACA,GAAQA,CAACA,CAACA;gBACfA,MAAMA,CAACA,CAACA,CAACA,CAACA,CACVA,CAACA;oBACGA,KAAKA,CAACA;wBACFA,KAAKA,CAACA;oBACVA,KAAKA,CAACA;wBAGFA,AAFAA,gBAAgBA;wBAChBA,gBAAgBA;wBAChBA,KAAKA,CAACA;oBACVA,KAAKA,CAACA;wBAEFA,AADAA,WAAWA;wBACXA,KAAKA,CAACA;gBACdA,CAACA;YACLA,CAACA;YACLF,WAACA;QAADA,CAACA,AAlBDD,IAkBCA;QAlBYA,UAAIA,OAkBhBA,CAAAA;IAELA,CAACA,EAtBUD,KAAKA,GAALA,SAAKA,KAALA,SAAKA,QAsBfA;AAADA,CAACA,EAtBM,GAAG,KAAH,GAAG,QAsBT"}

There are two differences, both at the comments inside the switch cases.  In both cases, the 1.5.3 map reports an entry at 
The main difference seems to be that the beta map lists (12, 20) as a location, while the 1.5.3 version doesn't (it lists 14, 20) instead.  The line returned appears to be the start of the last comment after the case keyword.  I don't know much about source maps, but I assume that the debugger is adding a breakpoint at a location that isn't valid, so the debugger just misses those locations.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #4003

### CODE REVIEW

**Comment by kitsonk** [comment]
I am still having issues with this on the `sourcemap` branch, here is a [visualisation of the map](https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gZm9vKCkgewogICAgY29uc29sZS5sb2coJ2ZvbycpOwp9Ci8qKgogKiBCYXIgZnVuY3Rpb24KICovCmZ1bmN0aW9uIGJhcigpIHsKICAgIGNvbnNvbGUubG9nKCdiYXInKTsKfQovLyBCYXogZnVuY3Rpb24KZnVuY3Rpb24gYmF6KCkgewogICAgY29uc29sZS5sb2coJ2JheicpOwp9CmZ1bmN0aW9uIHFhdCgpIHsKICAgIGNvbnNvbGUubG9nKCdxYXQnKTsKfQovLyMgc291cmNlTWFwcGluZ1VSTD1jb21tZW50LmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tbWVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9jb21tZW50LnRzIl0sIm5hbWVzIjpbImZvbyIsImJhciIsImJheiIsInFhdCJdLCJtYXBwaW5ncyI6IkFBQUE7SUFDRUEsT0FBT0EsQ0FBQ0EsR0FBR0EsQ0FBQ0EsS0FBS0EsQ0FBQ0EsQ0FBQ0E7QUFDckJBLENBQUNBO0FBS0QsQUFIQTs7R0FFRzs7SUFFREMsT0FBT0EsQ0FBQ0EsR0FBR0EsQ0FBQ0EsS0FBS0EsQ0FBQ0EsQ0FBQ0E7QUFDckJBLENBQUNBO0FBR0QsQUFEQSxlQUFlOztJQUViQyxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0E7QUFFRDtJQUNFQyxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0EifQ==,ZnVuY3Rpb24gZm9vKCkgewogIGNvbnNvbGUubG9nKCdmb28nKTsKfQoKLyoqCiAqIEJhciBmdW5jdGlvbgogKi8KZnVuY3Rpb24gYmFyKCkgewogIGNvbnNvbGUubG9nKCdiYXInKTsKfQoKLy8gQmF6IGZ1bmN0aW9uCmZ1bmN0aW9uIGJheigpIHsKICBjb25zb2xlLmxvZygnYmF6Jyk7Cn0KCmZ1bmN0aW9uIHFhdCgpIHsKICBjb25zb2xlLmxvZygncWF0Jyk7Cn0K) I get for the following:

```typescript
function foo() {
  console.log('foo');
}

/**
 * Bar function
 */
function bar() {
  console.log('bar');
}

// Baz function
function baz() {
  console.log('baz');
}

function qat() {
  console.log('qat');
}
```

You can still see that any comment block seem to anchor the next statement in the wrong place.

**Comment by sheetalkamat** [comment]
@kitsonk I compiled your code with the --sourcemap and saw the sourcemap being generated as [here](https://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gZm9vKCkgew0KICAgIGNvbnNvbGUubG9nKCdmb28nKTsNCn0NCi8qKg0KICogQmFyIGZ1bmN0aW9uDQogKi8NCmZ1bmN0aW9uIGJhcigpIHsNCiAgICBjb25zb2xlLmxvZygnYmFyJyk7DQp9DQovLyBCYXogZnVuY3Rpb24NCmZ1bmN0aW9uIGJheigpIHsNCiAgICBjb25zb2xlLmxvZygnYmF6Jyk7DQp9DQpmdW5jdGlvbiBxYXQoKSB7DQogICAgY29uc29sZS5sb2coJ3FhdCcpOw0KfQ0KLy8jIHNvdXJjZU1hcHBpbmdVUkw9YS5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImEudHMiXSwibmFtZXMiOlsiZm9vIiwiYmFyIiwiYmF6IiwicWF0Il0sIm1hcHBpbmdzIjoiQUFBQTtJQUNFQSxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0E7QUFFRDs7R0FFRztBQUNIO0lBQ0VDLE9BQU9BLENBQUNBLEdBQUdBLENBQUNBLEtBQUtBLENBQUNBLENBQUNBO0FBQ3JCQSxDQUFDQTtBQUVELGVBQWU7QUFDZjtJQUNFQyxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0E7QUFFRDtJQUNFQyxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0EifQ==,ZnVuY3Rpb24gZm9vKCkgew0KICBjb25zb2xlLmxvZygnZm9vJyk7DQp9DQoNCi8qKg0KICogQmFyIGZ1bmN0aW9uDQogKi8NCmZ1bmN0aW9uIGJhcigpIHsNCiAgY29uc29sZS5sb2coJ2JhcicpOw0KfQ0KDQovLyBCYXogZnVuY3Rpb24NCmZ1bmN0aW9uIGJheigpIHsNCiAgY29uc29sZS5sb2coJ2JheicpOw0KfQ0KDQpmdW5jdGlvbiBxYXQoKSB7DQogIGNvbnNvbGUubG9nKCdxYXQnKTsNCn0=)

**Comment by kitsonk** [comment]
@sheetalkamat I will try again, because you are right it does seem your source map is correct.  I might have gotten confused on which branch I was on.

**Comment by kitsonk** [comment]
@sheetalkamat yes, apologies, I get the [same results](http://sokra.github.io/source-map-visualization/#base64,ZnVuY3Rpb24gZm9vKCkgewogICAgY29uc29sZS5sb2coJ2ZvbycpOwp9Ci8qKgogKiBCYXIgZnVuY3Rpb24KICovCmZ1bmN0aW9uIGJhcigpIHsKICAgIGNvbnNvbGUubG9nKCdiYXInKTsKfQovLyBCYXogZnVuY3Rpb24KZnVuY3Rpb24gYmF6KCkgewogICAgY29uc29sZS5sb2coJ2JheicpOwp9CmZ1bmN0aW9uIHFhdCgpIHsKICAgIGNvbnNvbGUubG9nKCdxYXQnKTsKfQovLyMgc291cmNlTWFwcGluZ1VSTD1jb21tZW50LmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tbWVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImNvbW1lbnQudHMiXSwibmFtZXMiOlsiZm9vIiwiYmFyIiwiYmF6IiwicWF0Il0sIm1hcHBpbmdzIjoiQUFBQTtJQUNFQSxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0E7QUFFRDs7R0FFRztBQUNIO0lBQ0VDLE9BQU9BLENBQUNBLEdBQUdBLENBQUNBLEtBQUtBLENBQUNBLENBQUNBO0FBQ3JCQSxDQUFDQTtBQUVELGVBQWU7QUFDZjtJQUNFQyxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0E7QUFFRDtJQUNFQyxPQUFPQSxDQUFDQSxHQUFHQSxDQUFDQSxLQUFLQSxDQUFDQSxDQUFDQTtBQUNyQkEsQ0FBQ0EifQ==,ZnVuY3Rpb24gZm9vKCkgewogIGNvbnNvbGUubG9nKCdmb28nKTsKfQoKLyoqCiAqIEJhciBmdW5jdGlvbgogKi8KZnVuY3Rpb24gYmFyKCkgewogIGNvbnNvbGUubG9nKCdiYXInKTsKfQoKLy8gQmF6IGZ1bmN0aW9uCmZ1bmN0aW9uIGJheigpIHsKICBjb25zb2xlLmxvZygnYmF6Jyk7Cn0KCmZ1bmN0aW9uIHFhdCgpIHsKICBjb25zb2xlLmxvZygncWF0Jyk7Cn0K) as you.  I must have gotten confused... Now I am rubbing my hands together waiting for this to get merged! :smile:

**Comment by mhegazy** [comment]
:+1:

**Pull request merged**
