### PR TITLE
Report generic rest parameters as unreliable variance positions

### LINKED ISSUE #32948: Generic function with rest parameter assignability not transitive
**TypeScript Version:** 
+ 3.5.1
+ typescript@3.7.0-dev.20190815
+ https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
  https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz

**Search Terms:**

**Code**

```ts
/**
 * --strictFunctionTypes
 */

export type ExtendedMapper<HandledInputT, OutputT, ArgsT extends any[]> = (
    (name : string, mixed : HandledInputT, ...args : ArgsT) => OutputT
);

//type a = (name: string, mixed: any, args_0: any) => any
type a = ExtendedMapper<any, any, [any]>;
//type b = (name: string, mixed: any, ...args: any[]) => any
type b = ExtendedMapper<any, any, any[]>;
//3.5.1, typescript@3.7.0-dev.20190815
//Expected: "y"
//Actual  : "y"
//https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz
//Expected: "y"
//Actual  : "n" <-- Intentional?
type test = a extends b ? "y" : "n"

type a2 = (name: string, mixed: any, args_0: any) => any
type b2 = (name: string, mixed: any, ...args: any[]) => any
//3.5.1, typescript@3.7.0-dev.20190815
//Expected: "y"
//Actual  : "y"
//https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/40404/artifacts?artifactName=tgz&fileId=AD9D22CF70561BEAF5758E061B61D3FF891ADF664E37C532F5881393CE7DC83202&fileName=/typescript-3.7.0-insiders.20190815.tgz
//Expected: "y"
//Actual  : "y"
type test2 = a2 extends b2 ? "y" : "n"

//a extends b2 extends b
//However, a DOES NOT extend b
//It seems assignability is not transitive...

//"y" for all versions
type aExtendsB2 = a extends b2 ? "y" : "n"
//"y" for all versions
type b2ExtendsB = b2 extends b ? "y" : "n"

type TakeExtendedMapperRest<MapperT extends b> = (
    ["Blah", MapperT]
);

//Works in 3.5.1
//Fails for https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
export type ShouldWorkButFails<T extends a> = (
    //Type 'ExtendedMapper<any, any, [any]>' does not satisfy the constraint 'ExtendedMapper<any, any, any[]>'.
    //  Property '0' is missing in type 'any[]' but required in type '[any]'.ts(2344)
    //a -> b not allowed
    TakeExtendedMapperRest<T>
    //                     ~
);

//Works in 3.5.1
//Works in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
export type Workaround<T extends a> = (
    TakeExtendedMapperRest<
        //OK!
        //Takes advantage of a -> b2 -> b being allowed
        Extract<T, b2>
    >
);

//Works in 3.5.1
//Fails in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
type WorkaroundTest = TakeExtendedMapperRest<a>;

//Works in 3.5.1
//Works in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476
//type WorkaroundTest2 = ["Blah", ExtendedMapper<any, any, [any]>]
type WorkaroundTest2 = Workaround<a>; //Success
```

**Expected behavior:**

Build in https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521819476 should behave the same as 3.5.1 and typescript@3.7.0-dev.20190815

Assignability should be transitive.

a -> b2 -> b should imply a -> b

**Actual behavior:**

Assignability is not transitive

a -> b2 -> b **but** not a -> b

**Playground Link:** 
[Playground](http://www.typescriptlang.org/play/#code/PQKhCgAIUhaWDOAXATgSwMZIGIFcB2WaA9vgCoCeADgKYJQjDjg0AeVxKSkS1NkAUVZIa+ACY0xAWQCGVWigA8ACRniANpICS+KriRkANJADy+vQeMBBFAHMEZSGxHiEkNRQDaAXQB8kAF5IAAooSHDg-BkAW34ALkhkdHxbY2i0VklIBNUNbV19I0gAOlKZOzcEm3syAEpA-zMkCzJwWoBuZmBgXlp3QJCo2ISktBS0jMkEj2Ny+wB9AAZp-Ap6gP8PcF7+GQGhFwlpOQVFGfdV408PP07uncgAIwHImJoR1DHUyHTMsRWKMZSsU5ggAT51ptVts+E99sJREdZPIaEpzujVj5fHdgABmYoAVmKAEZjDsEBh0FQkAABfEAdmKi1gEgAbsUAEyLYkATkWAA5iQTwN0hLQsFNIAAiChSkXAKxYXAydThBIyuXdAAWSGaYO6tjQSC1uEexQwxGiwHSlOICGIADMkMBKLQAMqUtDU4B6dTqPEcnkcgAsAGI0AgELgaBborF8EhYASOcTBTzg-SAGzynV6uL3PgUqlIYqsiPK9TIXBiEjmy3ADAO+kyDDE4OZlnJgmwYPB3EYWCPDn92CLMQE-m43H0mgOmiPDDAeZyCPAR64NDqMRrjdbhDAYOLQ-B4DlJBoB0tpAIAD8Z4vV4Acm8AkhbAAvABkDs3NC0YgCKwABEeSAjkOQAYWwelFgJTNiQAIQEKxsAJekJwERZ4IQ+CgNxbBsH5HliWA7BM0zYMBGnCCCVxDlUP5QVcR5XEIIEekgIgycuQ5b9f2fWIAh6QtPWpWAGSZWAxgQNAJBQBBOW5PlBSJN933lMUYxEf5pVleVFSQCs1WlfApUgRR4EgHQXHPUgVRvGE+hEZABj2ZxETcZ4b10sz1VM5gHhkDkXiGd5Ek+cYfkmHT0QqJYAUhC4KEc-ghxCt4PmSb5fklc5gVBcFvESrZunxIlSR4ETizpYpGWZNlFN5AUhQ09gtMlDV9KVFVjM67VdSofVgENY1TTrK0bRQO1HWdV0aA9YsfVwP0AyDMMIyjGNLXjRNk1TXkM2zfq8wLWgiy9EsyyjFUqxrYhxobJsWzbDtxw5btexHIcRzHCcpxnOcFyXFd93XTdtzBvcDyPI9Ty4B8sFve9LywASaFfD8+M0f9AJAsDIOg2DsOQ1D0P5TDsNw-DCOI0jyMo6jaPoicmJYtiOK4ujFl4n9NDRoTyVExMJOZaTZNRBSuSalTijU1rxW09U9O6AyjOyHyUp4OgkGCoIgqcBFXCeYLvI1dWpX8+U3MNsRPOC9yjceeVlGIAB3GhWVRWZICAkwBDdSBHxMRwHbEJ55S0bgEBoGhojcGRIzQWwokeTcjQoSAI0gfBiG4VA1Bk89PeBLpgDNh1OHcP1IE9+SSHwehAoODyEN1-pQ7tyBTdlc3-O6cvK5VVVa5k0hG9hIdm9cBCBjSju4W73yTLlTWyBkABrGgp6RE5UQAJW1xRkQUEObc8-wglCcJwk8KUEPUGQtSlYxj9RMhvDaTp5QAdU4de3DGJAMqJJ5TYBkJuNwFcUCQFzINfMw0jQmjNLGa0mApr2idC6PgC0LpLRWnRNa4ZIzRljDtJMKY0yHRYOwTgedYRui1MQZaYhf4oHXghfQYCIGKFPoceOF8QhhHCN0OakAADk29JCvzRJcJKVwbi+DEZAMQxA6DZ1zokGQ54EAOgzsafgFoG75zGNwCRNspG7xkYCORSUsRiOKEIyA3RwgAAUpoKF4OIxYSis7pETikTO+BKp9DER4HwSj1zcBQDQAAjhuaJYdAEPDEdcVY3h7HXmCMOXstRHHdD2LAfwzwc7cCHm7SQji16b0kccFEKAD7IB4b4PJwBr5tPaR06+AA-T+pdWH-0CUAwkIDuj9IAUE2BQ0RpIIepNaamC5o4O9L6f0BCQxEM2qQ0Qu0KEHSzNQjgXBgn8H6eUJh4geEGz4e4ARV9r5VK3uY2pCgGlIEUI4tp3QTAAGkACEHzr4iI3momQYhWRqCQDIWw-BHT9EKcbOARSng0C+FXdQ5SxAAvCAcFAV4eHGCHM0tpzSOh9L-uMoZ5VQHgMrIMyZ8DpljRQXMjBs1sFCzwaswM6yNokO2ts8h+10z7IeKcqaBAxBkG1gMB5NTpGvLONiMlbCKXAOJD-cldKBpTMQUy+sLKZpYPdBylZq0eXEK2nGAVe1KH7NOicv+ZyJVSuQG3W+99H7P0EE86RZxZHnFSRQPwH9RWOvFeIF1OsBhivOWIRV7QnHADdLgDAGA6AICAA)

**Related Issues:** 

https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521826091

https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521834620

https://github.com/microsoft/TypeScript/pull/32924#issuecomment-521930291

I'm not sure which commit introduced this problem.

@weswigham

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #32948. Only `Unreliable` rather than `Unmeasurable` since it should be that in any case where the variance result is wrong, it's because the variance is overstrict because we have more relaxed arity-based rules on the signature than tuples have.

### CODE REVIEW

**Comment by jack-williams** [comment]
Might be worth checking DT for this. As it's `Unreliable` and not `Unmeasurable` I guess there wont be any questionable typing's that passed and now don't?

**Comment by weswigham** [comment]
@typescript-bot run dt

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot test this

**Comment by weswigham** [comment]
@typescript-bot user test this 😎

**Comment by weswigham** [comment]
`user` tests are just some updates the have yet to hit `master`, _everything_ is good 🎶 

@ahejlsberg sign-off would be much appreciated

**Comment by ahejlsberg** [comment]
Maybe add repro from #30301 and mark that as fixed.

**Comment by weswigham** [comment]
cc @RyanCavanaugh you bumped this from 3.7 to 3.8 yesterday - you may port to 3.7 if you wish, though.

**Pull request merged**
