### PR TITLE
Fix 46457: Improve autocomplete for union of tuples

### LINKED ISSUE #46457: Code hint not narrowed properly on union of literal tuple
# Bug Report

### 🔎 Search Terms
- code hint tuple
- code hint union

### 🕗 Version & Regression Information
4.4.4

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/DYUwLgBAbghsCuIBcEDaByG6A0F1QEZ0BdCAHzXQCMc8oAmEiAXkq130eIG4g)

### 💻 Code

```ts
let value: ['a', 'v1'] | ['b', 'v2'] = ['a', 'v']; // Type 'v' here and get code hint
```

### 🙁 Actual behavior

image

The first element is `'a'`, so the type of value should be narrowed to `['a', 'v1']`.
So that the code hint of the second element should only have `'v1'`, but actually got `'v1' | 'v2'`.

The compile result is correct, but it is not consistent with code hint.

### 🙂 Expected behavior

image

### PR DESCRIPTION
**Pull request by rynobax**
Fixes #46457

tbh I have no idea if this is the "right" way to go about fixing this, I used a lot of trial and error to get to these changes.  I'm assuming since all the tests pass it makes some sort of sense, but lmk if there's something fundamentally wrong with this approach.

### CODE REVIEW

**Comment by rynobax** [comment]
> @rynobax please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by andrewbranch — CHANGES_REQUESTED** [review]
This is pretty tricky. I don’t think this is the right place to do any filtering, because conceptually, it doesn’t make sense for a contextually typed literal to be able to change its own contextual type. The contextual type exists because of some higher level _context_, and the literal just sits in a position affected by that context. It should be a one-way relationship. (It’s also usually a bit of a red flag to change general type checker code for a completions-specific purpose.) You can probably use similar logic to this, but perform it in completions.ts.

**Comment by sandersn** [comment]
Do you want to keep working on this? Otherwise I'd like to close it to reduce the number of open PRs.

**Comment by rynobax** [comment]
I might circle back to this at some point, but feel free to close

**Pull request closed without merging**
