### PR TITLE
Higher order type parameter promotion fixes

### LINKED ISSUE #30324: Free type parameter no longer inferred in context of target
From https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33704

**TypeScript Version:**  3.4.0-dev.201xxxxx

**Code**

```ts
declare function identity<T>(a: T): T;
declare function times<T>(fn: (i: number) => T): (n: number) => T[];
const a2 = times(identity)(5); // => [0, 1, 2, 3, 4]
```

**Expected behavior:**
No error.

**Actual behavior:**
```
Argument of type '<T>(a: T) => T' is not assignable to parameter of type '(i: number) => T'.
  Type 'number' is not assignable to type 'T'.
```

From @googol
> I would have thought though that in R.times(R.identity) the type parameter T would be hoisted from R.identity to the composition such that R.times(R.identity): <T>(n: number) => T[]

I, personally, am surprised the `times` call fails - `<T>(x: T) => T` obviously satisfies `(i: number) => T`; The free `T` in `identity` should infer to `number` (due to instantiating the method in the context of the target), which should then provide an inference for the `T` on the target side (as now the return type should be instantiated to `number`). This is definitely [what used to happen](http://www.typescriptlang.org/play/#src=declare%20function%20identity%3CT%3E(a%3A%20T)%3A%20T%3B%0D%0Adeclare%20function%20times%3CT%3E(fn%3A%20(i%3A%20number)%20%3D%3E%20T)%3A%20(n%3A%20number)%20%3D%3E%20T%5B%5D%3B%0D%0Aconst%20a2%20%3D%20times(identity)(5)%3B%20%2F%2F%20%3D%3E%20%5B0%2C%201%2C%202%2C%203%2C%204%5D) (or something similar), so seems like a significant break.

cc @ahejlsberg - this seems like a sideffect of the better `pipe`-like checking we added last week.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR makes a couple of tweaks to our higher order type parameter promotion algorithm. Specifically, we don't promote type parameters of a function type argument when the contextual signature doesn't reference type parameters in parameter positions, and we now treat inferences made from parameter positions in type parameter promotion as contravariant.

Fixes #30324.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot run DT let's see if this fixes ramda completely~

**Comment by weswigham** [comment]
@typescript-bot run dt let's see if this fixes ramda completely~

**Comment by weswigham** [comment]
@ahejlsberg this looks new:
```ts
Error in css-tree
Error: /home/vsts/work/1/s/dtslint-runner/DefinitelyTyped/types/css-tree/css-tree-tests.ts:211:1
ERROR: 211:1  expect  Expected type to be:
  List<Test>
got:
  List<Test | null>
ERROR: 219:1  expect  Expected type to be:
  List<Test>
got:
  List<Test | null>
```
might be unrelated, though, don't know. The other failures are caused by #30334 and fixed by #30375.

**Comment by weswigham** [comment]
Here's the testcase from `css-tree`:
```ts
// @strict: true
type IteratorFn<TData, TResult, TContext = List<TData>> = (this: TContext, item: TData, node: ListItem<TData>, list: List<TData>) => TResult;
type FilterFn<TData, TResult extends TData, TContext = List<TData>> = (this: TContext, item: TData, node: ListItem<TData>, list: List<TData>) => item is TResult;

declare class List<TData> {
    filter<TContext, TResult extends TData>(fn: FilterFn<TData, TResult, TContext>, context: TContext): List<TResult>;
    filter<TResult extends TData>(fn: FilterFn<TData, TResult>): List<TResult>;
    filter<TContext>(fn: IteratorFn<TData, boolean, TContext>, context: TContext): List<TData>;
    filter(fn: IteratorFn<TData, boolean>): List<TData>;
}
interface Test {
    a: string;
}
const list2 = new List<Test | null>();
const filter1 = list2.filter(function(item, node, list): item is Test {
    this.b; // $ExpectType string
    item; // $ExpectType Test | null
    node; // $ExpectType ListItem<Test | null>
    list; // $ExpectType List<Test | null>
    return !!item;
}, {b: 'c'});
filter1; // $ExpectType List<Test>
```
the change in expected type of `filter1` does seem to be isolated to this branch. It seems like we're inferring `Test | null` for `TResult` when we should just be inferring `Test` - this is  likely due to the contravariant parameter inference?

**Comment by weswigham** [comment]
Noooooope, it's due to the subtle change in inference for return type predicates.

**Comment by weswigham** [comment]
Specifically, we check for a matching parameter index.... except we don't account for `this` parameters not really counting.

**Comment by weswigham** [comment]
I opened a PR against this PR - #30386 - with a fix.

**Comment by ahejlsberg** [comment]
Latest commit changes `IdentifierTypePredicate.parameterIndex` to be an index into `Signature.parameters`. It previously was an index into the parameter list of the declaration from which the signature was obtained, which meant we had latent off-by-one errors in signatures with a `this` parameter (signatures don't include `this` parameters in the parameters array). Since types always operate on `Signature` instances and since it is possible for `Signature` instances to have no declaration associated with them, it really doesn't make sense to store declaration indices.

**Comment by weswigham** [comment]
Wanna add the test from #30386 so we have more coverage?

**Comment by ahejlsberg** [comment]
@weswigham Sure, I can do that.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by weswigham** [comment]
The DT run looks great - just has the instantiation error that was in `master` back when this branch was first created, so this branch fixes ramda, as intended, and breaks nothing else now. 💓

**Pull request merged**
