### PR TITLE
Switched 'ts.performance' to a mixed mode only uses native performance APIs when necessary

### PR DESCRIPTION
**Pull request by rbuckton**
@amcasey recently discovered that the Web Performance API in NodeJS adds quite a bit more overhead to the total compile time than what we were doing before. This changes our use of native performance APIs in the following ways:

- Revert back to calculating our own `mark` times and `measure` durations in `ts.performance` rather than using `PerformanceObserver`.
- Conditionally call the native `mark` and `measure` when _any_ of the following are true:
  - We are running in the browser (since a debugger can start a cpu profile at any time)
  - We are running in NodeJS with Node's `--cpu-prof` option specified (to capture user timing events in the profile)
  - We are running in NodeJS with V8's `--prof` option specified (to capture user timing events in the profile)
  - We are running in NodeJS with our own `--generateCpuProfile` option specified (to capture user timing events in the profile)
  - We are running in NodeJS and `sys.debugMode` is true (since a debugger can start a cpu profile at any time)

If none of those cases are true, we will not call the native `mark` and `measure` methods. I've filed https://github.com/nodejs/diagnostics/issues/464 to track the performance issue we encountered in NodeJS, and it sounds like they plan to have a patch available in the near future that improves their implementation.

### CODE REVIEW

**Review by amcasey — APPROVED** [review]
The original repro had emit time tripled from a TS 4.0 baseline.  With this change, they're back within 10% of TS 4.0.  Since the repro is noisy and the number of other changes is huge, I'm satisfied.

**Comment by amcasey** [comment]
@typescript-bot perf test this

**Comment by rbuckton** [comment]
Perf numbers look good to me

**Comment by amcasey** [comment]
It looks like nothing in the perf suite does a meaningful amount of emit, which is probably why we missed the regression.  Should we add something?  (Unfortunately, I don't have an example in mind.)

**Pull request merged**
