### PR TITLE
Contextually type parenthesized expressions

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
This PR addresses #920.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
I'm a bit confused by this.  Isn't this a fairly big breaking change?  The language decision was, up front, that parentheses would turn off contextual typing.  With this change users may have code that now errors where it didn't before.

**Comment by danquirk** [comment]
Yes, issue #920 that this is fixing notes this is a breaking change, adding the tag for clarity.

**Comment by CyrusNajmabadi** [comment]
This break definitely concerns me.  Specifically, because it not just a break that occurs because we're deciding to change some off-hand part of the language, but because we're changing a part of the language we explicitly spec'ed as as a means to opt out of contextual typing.  i.e. we told users "if you don't want contextual typing, here's how you get out of it." and we're now taking that away.

**Comment by DanielRosenwasser** [comment]
Yup, I agree that it's something that we should discuss at a design meeting.

But I'll flat out admit that I put out this PR so that we could actually discuss it. The work is here, it's no longer an issue of getting around to it, just of deciding whether or not it's an appropriate change.

As a side note, we do mention it exactly once in the spec. We don't mention it at all in the TypeScript handbook. It's more likely that people learn about this "feature" by shooting themselves in the foot than by our documentation.

**Comment by RyanCavanaugh** [comment]
It was already discussed at the design meeting (see the comments in #920). Casting to `any` is still a valid workaround.

**Comment by DanielRosenwasser** [comment]
Actually, @RyanCavanaugh is right, we discussed this several weeks ago, my memory didn't serve me correctly.

Also, I think Github is having a caching issue of some sort; if I try to create a new PR from this branch to master, it will only show the last 4 commits (d5f0281 to 22174a1). I'll try updating this branch with a new commit of some sort, and if not I'll open up a different PR.

**Comment by JsonFreeman** [comment]
Can you resend this PR with the change by itself?

**Pull request closed without merging**
