### PR TITLE
Remove static-side inheritance checking

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
This is a PR so we can evaluate the effects of #4628

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I think this change is okay, since you'll be hit with structural assignability errors anyway if things don't pan out.

Can you sync with `master`?

**Comment by david-driscoll** [comment]
@DanielRosenwasser @RyanCavanaugh any updates on this? :+1:

**Comment by daladaysoft** [comment]
Hello, any update on this?

**Comment by isiahmeadows** [comment]
I'll note that in particular, I've seen a few other libraries need similar leniency (most notably Lazy.js) for instance methods.

**Comment by david-driscoll** [comment]
@RyanCavanaugh any idea if this might land at all?  ❤️

**Comment by mhegazy** [comment]
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

**Pull request closed without merging**
