### PR TITLE
Add error for using generalized expressions with export assignments in ambient contexts

### LINKED ISSUE #17991: Flag expressions in export assignments in ambient contexts as errors
```ts
declare module "foo" {
  export default 1 + 1;  // should not be allowed
}
```
originally reported in https://github.com/Microsoft/TypeScript/issues/16769

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #17991

### CODE REVIEW

**Comment by mhegazy** [comment]
Please add an entry for this change in https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-26

**Comment by weswigham** [comment]
@mhegazy done.

**Comment by andy-ms** [comment]
@weswigham I thought we were going to allow `export = class`? `DefinitelyTyped/types/express-brute-mongo` is broken by this.

**Comment by weswigham** [comment]
@andy-ms Nope, we said identifier or qualified name only. `export default class` gets a pass, since it gets parsed as a modifier on a class statement (rather than a default exported class expression) (and causes appropriate grammatical errors on the class from an ambient context); `export =`, however, _always_ parses as an expression; ergo: only identifiers or qualified names allowed in ambient contexts.
cc @mhegazy for feedback.

@andy-ms, can it be rewritten as 
```ts
import { Collection } from "mongodb";

/**
 * @summary MongoDB store adapter.
 * @class
 */
class MongoStore {
    /**
     * @summary Constructor.
     * @constructor
     * @param {Function} getCollection The collection.
     * @param {Object}   options       The otpions.
     */
    constructor(getCollection: (collection: (c: Collection) => void) => void, options?: Object);
}
export = MongoStore;
```
?

**Pull request merged**
