### PR TITLE
Use `export * as namespace` syntax in barrel modules.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
I noticed while writing the "moving to modules" blog post that we didn't use `export * as mod` syntax. I was wondering if there was a reason why, but it was an easy enough PR to kick off.

### CODE REVIEW

**Comment by jakebailey** [comment]
I'm afraid this is intentional; esbuild doesn't bundle this very well.

**Comment by jakebailey** [comment]
(compare the built output before and after and you'll see what I mean)

**Review by jakebailey — CHANGES_REQUESTED** [review]
Clicking the red button so we don't merge this, but obviously it'd be way better if this worked.

(Technically you can also stick `@internal` on this form which can be useful)

**Comment by DanielRosenwasser** [comment]
Let's close in the meantime then.

**Pull request closed without merging**
