### PR TITLE
Exempt ambient private properties from noImplicitAny

### PR DESCRIPTION
**Pull request by ajafff**
Fixes: #36630

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.

**Comment by ajafff** [comment]
Setting up a new dev machine is hard ... I fixed the email in the commit. It's now correctly linked to my account. Thank you for the heads up.

**Comment by DanielRosenwasser** [comment]
This will need to be cherry-picked into release-3.8

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.8 and LKG

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.8 and LKG

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.8

**Pull request merged**
