### PR TITLE
No recursive intersection property checks

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes the first half of #37600. I have manually verified that the instantiation depth error is gone.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
Regarding perf, `react-page` check time drops from 3s to just under 1s and memory consumption drops in half, so dramatically better. That said, the cause really is the recursive types, and the best fix would be to simplify those.

**Comment by ahejlsberg** [comment]
Some more data on the impact of this fix.

Compiling `react-page` with master:

```
Files:              191
Lines:            87660
Nodes:           295586
Identifiers:     105146
Symbols:         245477
Types:            51522
Instantiations:  274119
Memory used:    219966K
I/O read:         0.03s
I/O write:        0.00s
Parse time:       0.81s
Bind time:        0.33s
Check time:       3.10s
Emit time:        0.60s
Total time:       4.85s
```

Compiling fixed `react-page` with master:

```
Files:              191
Lines:            87660
Nodes:           295590
Identifiers:     105148
Symbols:         102597
Types:            16084
Instantiations:   67060
Memory used:    129625K
I/O read:         0.02s
I/O write:        0.00s
Parse time:       0.79s
Bind time:        0.33s
Check time:       1.18s
Emit time:        0.59s
Total time:       2.89s
```

Compiling `react-page` with this PR:

```
Files:              191
Lines:            87660
Nodes:           295586
Identifiers:     105146
Symbols:          86450
Types:            12290
Instantiations:   44560
Memory used:    125939K
I/O read:         0.02s
I/O write:        0.00s
Parse time:       0.82s
Bind time:        0.33s
Check time:       0.98s
Emit time:        0.67s
Total time:       2.79s
```

The fixed `react-page` has _two_ minor edits of adding a missing type parameter (the fix suggested in https://github.com/microsoft/TypeScript/issues/37600#issuecomment-611230251 needs to be applied to both `ContentPluginProps` and `LayoutPluginProps`).

With the fixed `react-page` we're still a bit slower on master than this PR, but also more correct (because we check recursively up to the depth limiter). I haven't seen other code bases that are appreciably slowed down by the recursive check, so I'm not really whether I want this PR vs. just fixing `react-page`.

**Comment by weswigham** [comment]
So... Adding the type parameter just ensures the type of the `Component` property is sufficiently similar that we quickly find a place to bail on the comparison (because we actually recur on the same type, rather than a variation of it); the fundamental type structure in play here is not uncommon - it's just a react higher order component, and a non-generic one, no less. The pattern is _relatively_ common in react libraries. Knowing that the 3.9 release has the ability to double check times and introduce non-meaningful, unactionable errors into this common pattern, if not for very carefully consistent code where it previously didn't really matter... Might not be great.

**Comment by ahejlsberg** [comment]
Ok, we'll go with this PR then.

**Comment by amcasey** [comment]
Are there any drawbacks?  This looks like a pure win.

**Comment by ahejlsberg** [comment]
> Are there any drawbacks? This looks like a pure win.

The checking is slightly looser. For example:

```ts
declare let x: { p: { a?: number, b: string } };
declare let z: { p: { a: null } } & { p: { b: string } };

x = z;  // No longer an error
```

We currently report an error on the example above. With this PR there is no error (as was the case before 3.9).

**Pull request merged**
