### PR TITLE
Improvements to `strictSubtypeRelation` and `getNarrowedType`

### LINKED ISSUE #50916: Type guard affects type of variable in surprising way
# Bug Report

### 🔎 Search Terms

type guard / fall through / narrow / change / lazy / evaluate

### 🕗 Version & Regression Information

- This changed between versions v4.7.4 and v4.8.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/C4TwDgpgBAkgJhAdsAlqAPAFQHxQLxQDeA2gNJQqJQDWEIA9gGZSYC6AXC2awL4DcAWABQw0JCgBlCABtGWXAUxQIAD2BI4AZygBXRNUT0A7lQD8sBMjQh5UToggA3CACdBIoYz0BjVPSoomvIAFI4AhtI6EJyYAJSc4ZHQgZIycjhEwlDZUC4QwDouVMAuUe48wqLg0ACqiCj++NmEYfY6ALYARq48UAA+RJ1tXT39RN7D3S78lZ4+flSqYe1g0hDBKpx1DYixmUI5FMzBgRuxe4QVBzkox6cq50RXh7dQJ5pnF883dx8PX1kfm97o9LoDsq93p8nuCjsC-qDvhDftCwR5DnkCkUoCp3IcAPT4w5QAB6pmEV1mYmgABFjIhvGFNMAAPKIaQgGCMAByEAgCDg6AkOkgLkw1QANJIdJ1xeJVOpEFppaK5RAFCrXGrlGoNNphbLqlBzMLVUbOAa1e5hF4GQsKJoAEwhRJRGLxKCu5LaOkmRnMtkcrm8-n8rBSqSyeS4QiwzGFYqlCDlWa23w7KBGeguahhFz0PRwDZber+C6wyGBR2opFw97V-4w67I+ENxEV35tgHNutVmsd1v9nuVp1Dl6dodx-IJnF4nKE4lkilAA)

### 💻 Code

```ts
type Identity<T> = {[K in keyof T]: T[K]};

type Self<T> = T extends unknown ? Identity<T> : never;

function is<T>(value: T): value is Self<T> {
    return true;
}

type Union =  {a: number} | {b: number} | {c: number};

function example(x: Union) {
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}

    return x;
    //     ^?
}
```

### 🙁 Actual behavior

The type of `x` is "narrowed" to `Identity<Identity<Identity<Identity<Identity<Identity<Identity<Identity<{a: number;}>>>>>>>> | Identity<Identity<Identity<Identity<Identity<Identity<Identity<Identity<{b: number;}>>>>>>>> | Identity<Identity<Identity<Identity<Identity<Identity<Identity<Identity<{c: number;}>>>>>>>>`

It's as if a variable gets narrowed to the union of the types of both sides of the type predicate, e.g.
```tsx
if (isA(aOrB)) {
  // `aOrB` gets narrowed to `A`
} else {
  // `aOrB` gets narrowed to `Exclude<typeof aOrB, A>`
}

// `aOrB` gets narrowed to `A | Exclude<typeof aOrB, A>` but it should just be left alone
```

### 🙂 Expected behavior

The type of `x` doesn't change.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes a number of inconsistencies related to the strict subtype relation and user defined type predicate narrowing. Specifically:

* In the strict subtype relation, `unknown` is related to `any` but `any` is not related to `unknown`. Previously, the two were mutually related.
* In the strict subtype relation, a non-fresh object type is not related to a another object type if the first type is missing an index signature. Previously, it was possible for such types to be mutually related.
* In the subtype and strict subtype relations, given a signature `S1` of the form `(...args: A) => R`, where `A` is `any`, `any[]`, `never`, or `never[]`, and `R` is `any` or `unknown`, and a signature `S2` not of that form, `S2` is related to `S1` but `S1` is not related to `S2`. Previously, it was possible for such signatures to be mutually related.
* The assignment expression `x = y` is has the same type as `y` with any object literal freshness preserved. Previously, object literal freshness was stripped.
* Narrowing by a user defined type predicate preserves the original type in the false branch for non-identical mutual subtypes.

The strict subtype relation primarily controls subtype reduction of union types. Subtype reduction occurs in control flow analysis and other situations that require determining a common supertype for multiple types. For example, given expressions `a` and `b` of type `A` and `B`, the element type of an array literal `[a, b]` is `A` if `B` is a subtype of `A`, `B` if `A` is a subtype of `B`, or `A | B` if neither is a subtype of the other. However, if `A` and `B` are mutual subtypes, the type chosen may ultimately depend on declaration order, which isn't desired. The goal of the strict subtype relation is to impose a stable ordering by eliminating mutual subtypes, and the first three rules above further that goal.

Fixes #50916.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by DanielRosenwasser** [comment]
@typescript-bot top200

**Comment by jakebailey** [comment]
Before we approve/merge this, can we make sure that cases like those listed in various replies to #48840 (and #52387) are all tested to be working with their desired behaviors?

**Comment by ahejlsberg** [comment]
@jakebailey This PR doesn't change anything with regards to #48840 and #52387.

**Comment by ahejlsberg** [comment]
@typescript-bot test top200

**Comment by ahejlsberg** [comment]
@DanielRosenwasser I don't think there's such a thing as `test200` in `typescript-bot`. The results of `test100` are here and, as we discussed, are acceptable.

**Comment by jakebailey** [comment]
> @jakebailey This PR doesn't change anything with regards to #48840 and #52387.

I guess I shouldn't have mentioned the PR as I think it drew the focus away from what I actually wanted checked. I meant that the issue thread (#48840) has some discussion as to what constitutes a top-function-type, which is changing in this PR via `isTopSignature`.

I'll just pack this PR and test it.

@typescript-bot pack this

**Comment by jakebailey** [comment]
Okay, the things I wanted to test appear to work fine, or at least have not changed behavior from 4.9 anywayn.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
Would you be able to add tests that demonstrate the ordering among supertypey functions?

```ts

type A = (...args: any) => unknown;
type B = (...args: any[]) => unknown;
type C = (...args: never) => unknown;
type D = (...args: never[]) => unknown;
type E = () => unknown;

type FnTypes = A | B | C | D | E;

declare function isSomeFunc<T>(x: any): x is T;

function checkA(f: FnTypes) {
    if (isSomeFunc<A>(f)) {
        f
    }
    else {
        f
    }
    f
}

function checkB(f: FnTypes) {
    if (isSomeFunc<B>(f)) {
        f
    }
    else {
        f
    }
    f
}

function checkC(f: FnTypes) {
    if (isSomeFunc<C>(f)) {
        f
    }
    else {
        f
    }
    f
}

function checkD(f: FnTypes) {
    if (isSomeFunc<D>(f)) {
        f
    }
    else {
        f
    }
    f
}

function checkE(f: FnTypes) {
    if (isSomeFunc<E>(f)) {
        f
    }
    else {
        f
    }
    f
}
```

**Comment by ahejlsberg** [comment]
@DanielRosenwasser More tests added.

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
