### PR TITLE
feat(49385): Inlay hint for type of literal-initialized constant is unnecessary

### LINKED ISSUE #49385: Inlay hint for type of literal-initialized constant is unnecessary
Given

```ts
const foo = "foo";
```

An editor will make this appear like

```ts
const foo: "foo" = "foo";
```

This gets worse for longer strings. For example:

image

This really doesn't need a type annotation.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49385

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
> Or do we need to omit variables with type declarations completely?

Can you give an example?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I meant the following case

```ts
interface Foo {
  a: number;
}
const a /* : Foo */ = { a: 1 }
        ^^^^^^^^^ - is it acceptable to have a hint here?
```

**Comment by DanielRosenwasser** [comment]
Hah, now we've got some more subtlety.

I would say no - first we shouldn't provide try to provide hints using structurally identical types. But for basic object types, my experience would be that that sort of hint stops being useful pretty quickly.

I guess this comes down to a few heuristics on "obvious" forms you should omit on for variables and parameter declarations

* A const initialized to a primitive literal.

  ```ts
  const foo = "...";
  ```

* A binding initialized with a type assertion

  ```ts
  const foo = { /*...*/} as SomeType;
  const bar = <SomeType>{ /*...*/};
  const baz = {/*...*/} as const;
  ```

* A binding initialized with a `new` expression where the instance type name and the constructor name are identical.


  ```ts
  class Foo {}
  namespace asd { export class Foo {} }
  const foo = new Foo();
  const foo = new asd.Foo();
  ```

* An object literal

   ```ts
   const foo = { a: 123, b: 456 };
   ```

@andrewbranch, @gabritto, and @jakebailey might have some thoughts.

**Comment by jakebailey** [comment]
I think those exceptions are all reasonable to my eye.

**Review by andrewbranch — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
