### PR TITLE
JsxTagNameExpression can only be Identifier | ThisExpression, not any PrimaryExpression

### PR DESCRIPTION
**Pull request by andy-ms**
Noticed this while looking at some jsx-using code -- we were typing this as `PrimaryExpression` but could be a lot more strict.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
I mean, while you're at it, it seems like `PropertyAccessExpression` is not particularly strict either, given https://github.com/facebook/jsx/blob/master/README.md. I think your change is fine but I would recommend waiting for someone more familiar with our grammar to agree.

**Comment by andy-ms** [comment]
I think we could just use `EntityNameExpression | ThisExpression`, but let's wait on #21588 first.

**Comment by andy-ms** [comment]
@uniqueiniquity @rbuckton Please re-review

**Comment by andy-ms** [comment]
@uniqueiniquity @rbuckton Please re-review

**Pull request merged**
