### PR TITLE
Make top-level getJSDoc* functions public

### LINKED ISSUE #13498: `getJsDocTags` does not return `@type` annotations
I am writing a typescript to JSON schema converter and use the typescript compiler to find out the types and comments of a typescript program. I am using `getJsDocTags` to get annotations and would like to read the `@type` annotation. 

**TypeScript Version:**  2.1.1

**Code**

```ts
/** @TJStype integer */
const integer: number = 1;
```

and

```ts
/** @type integer */
const integer: number = 1;
```

For the symbol `integer`, I am calling `symbol.getJsDocTags()`. 

**Expected behavior:**

I'd expect to the type jsdoc annotation. In other words, I expect the call to return `[{ name: 'type', text: 'integer' }]`. 

I understand that `integer` is not a valid js type but this behavior is surprising nonetheless. 

**Actual behavior:**

It is missing. I get am empty array `[]`.

### PR DESCRIPTION
**Pull request by sandersn**
* getJSDocParameterTags
* getJSDocAugmentsTag
* getJSDocClassTag
* getJSDocClassTag
* getJSDocTemplateTag
* getJSDocTypeTag
* getJSDocReturnTag
* getJSDocType
* getJSDocReturnType

Fixes #13498

### CODE REVIEW

**Comment by sandersn** [comment]
Still needs tests. 

Our API tests are basically (semi-)useful samples. @domoritz @navossoc @dmikov @kitsonk do you have realistic samples that would use these functions?

**Comment by navossoc** [comment]
@sandersn 

Well, getJsDocTags was used here: https://github.com/YousefED/typescript-json-schema
Doing some special annotations in the comments.

I'm not sure about the status of the project now.
I'm not using it anymore.

Related: https://github.com/YousefED/typescript-json-schema/issues/99

Sorry I can't be of more help.

**Comment by domoritz** [comment]
@novossoc I help maintain that project and also https://github.com/vega/ts-json-schema-generator. It'd be great to generate json schema properties from the jsdocs again.

**Comment by sandersn** [comment]
Thanks @domoritz and @navossoc for the links. I included some examples from those two projects.

**Pull request merged**
