### PR TITLE
Forbid functions named `require` in JS

### LINKED ISSUE #48726: When using `require()` in es modules, no TS2441 error occurs and `node_modules/@types` is automatically included in the project.
# Bug Report

### 🔎 Search Terms

cjs require

### 🕗 Version & Regression Information

- This changed between versions `4.0.5` and `4.2.3`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2&filetype=js#code/PQKhCgAIUgBAHAhgJ0QW0gbwM4BdkCWAdgOYC+keyUIw4AZgK5EDGuBA9kZMgKYCOjAnwAUVAJRYy4cCy55KHNLwCyHACaMANr0gBeHgKGiARCQ4cSOgLQstHbIz62l8AjuQnxAbhm8AHvAcyLhY2EqqGtq8ZL5AA+QA)

### 💻 Code

```ts repro
// @filename: index.js
// @checkJs: true

/**
 * @param {string} str
 */
function require(str) {}

const someModule = require("google-closure-compiler");

export {someModule};
```

### 🙁 Actual behavior

TS2792 occurs at the call to `require()`:

```js
const someModule = require("google-closure-compiler");
//                         ^^^^^^^^^^^^^^^^^^^^^^^^^----- Cannot find module 'google-closure-compiler'. option?
//                                                        Did you mean to set the 'moduleResolution' option to 'node',
//                                                        or to add aliases to the 'paths'
```

What's worse, if the project contains types in `node_modules/@types`, these will now be included in the project, regardless of the value set for `"typeRoots": []` in `tsconfig.json`, which is supposed to prevent this sort of behaviour.

From https://www.typescriptlang.org/tsconfig#typeRoots:
> If `typeRoots` is specified, only packages under `typeRoots` will be included.

For me this caused a long and painful process of figuring out why I kept getting errors for imports missing from the "path" module, even though I definitely disabled node imports.

[Here you can download](https://github.com/microsoft/TypeScript/files/8498452/jsRequireBug.zip) a reduced test case of the situation described above.

Run `tsc --noEmit -p jsconfig.json` in the folder and you'll get an error stating that `fromFileUrl` is not in the `"path"` module, even though `node_modules/@types` has been disabled and a custom path has been added in `jsconfig.json`.

### 🙂 Expected behavior

Either no error, or an error informing me that I can't use `require()` as it's already taken by the compiler. The latter is already the case with TypeScript files:
```ts
function require(str: string) {}
//       ^^^^^^^------ TS2441: Duplicate identifier 'require'.
//                     Compiler reserves name 'require' in top level scope of a module.
```
It's just missing inside JavaScript files.

### 🔃 Workarounds

Just don't name your functions `require` 😅. But you'd have to know that this issue is happening in the first place, which is not easy to figure out with no errors telling you this.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #48726

This is a maximal version that forbids it everywhere. I want to see how much of the user tests will break.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by sandersn** [comment]
:suspect:

**Comment by jakebailey** [comment]
Maybe this doesn't trigger because nobody's actually declaring a function named `require` in their own code, but consuming some other APIs / definitions which declare it for them, even if it's not the "real" one? e.g. webpack-dev, or my yarn plugin example?

**Review by ProKashif — APPROVED** [review]

**Comment by sandersn** [comment]
Based on the

**Pull request closed without merging**
