### PR TITLE
Fix Promise.reject static method signature (#10699)

### LINKED ISSUE #10699: Fix PromiseConstructor interface
**TypeScript Version:**  master

``` diff
interface PromiseConstructor {
-    reject(reason: any): Promise<never>;
-    reject<T>(reason: any): Promise<T>;
+    reject(reason?: any): Promise<never>;
}
```

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #10699

### CODE REVIEW

**Comment by falsandtru** [comment]
I'm not sure the following signatures are correct as the usage of `never` type. I think the second signature makes confusing, so it should be removed. @ahejlsberg can you tell me the advice?

```ts
interface PromiseConstructor {
    reject(reason: any): Promise<never>;
    reject<T>(reason: any): Promise<T>;
}
```

**Comment by mhegazy** [comment]
@falsandtru we had a long discussion about this in #10699. I do not see why you want to remove the overload. it does not impact your scenarios, but some users need it.

**Comment by falsandtru** [comment]
then i put only the agreed fix as a partial fix. so can you reopen this pr?

**Comment by mhegazy** [comment]
you have removed the generic signature:
```ts
reject<T>(reason: any): Promise<T>;
```

**Comment by falsandtru** [comment]
i cannot understand why you don't reopen this pr.

**Comment by mhegazy** [comment]
> i cannot understand why you don't reopen this pr.

I do not agree with the change of removing the generic overload. I have expressed this position and explained why in https://github.com/Microsoft/TypeScript/issues/10699#issuecomment-245065650, https://github.com/Microsoft/TypeScript/issues/10699#issuecomment-245134265, and https://github.com/Microsoft/TypeScript/issues/10699#issuecomment-246060751

**Pull request closed without merging**
