### PR TITLE
Disallow uninitialised property overrides

### PR DESCRIPTION
**Pull request by sandersn**
This PR is part of the migration from [[Set]] semantics to [[Define]] semantics. #27644 tracks the complete migration. This is the third step.

Briefly, uninitialised property declarations that must now use new syntax when the property overrides a property in a base class. The new syntax is only allowed in this case and is an error elsewhere. That's because when Typescript supports [[Define]] semantics, it will start emitting uninitialised property declarations, where previously it did not. This will be a major breaking change:

```ts
class B {
  p: number
}
class C extends B {
  p: 256 | 1000 // use whatever value you need here; it
}
```

Previously this emitted

```js
class B {}
class C extends B {}
```

When Typescript supports [[Define]] semantics, it will instead emit

```ts
class B {
  p
}
class C extends B {
  p
}
```

which will give both `B` and `C` and property `p` with the value `undefined`. (This is an error today with `strictNullChecks: true`.)

The new syntax will cause Typescript to emit the original JS output:

```ts
class B {
  p: number
}
class C extends B {
  declare p: 256 | 1000
}
```

This PR adds an error prompting the author to add the new syntax in order to avoid the breaking change. As you can see from the baselines, this error is pretty common. From my first run of our extended test suites, it looks pretty common in real code as well.

Note that the compiler can only check constructors for initialisation when `strictNullChecks: true`. I chose to be conservative and always issue the error for `strictNullChecks: false`.

## Other ways to fix the error

1. Make the overriding property abstract.
2. Make the base property abstract.
2. Give the overriding property an initialiser.
3. Initialise the overriding property in the constructor -- but this only works with `"strictNullChecks": true`.

### Notes

1. Adding a postfix-! will *not* fix the error; `!` is always erased, so, in the last example, `p!: 256 | 1000` would still result in `p === undefined` for [[Define]] semantics.
2. You can add `declare` to any uninitialised property, even if it's not an override. I previously had a check that prevented this, but I think an easy upgrade is valuable (you can *almost* write a regex for it).

## To test this PR

```json
{
    "devDependencies": {
        "typescript": "https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/44156/artifacts?artifactName=tgz&fileId=1E6A72F0C6E099FF6B046F9DBFDBA5D1CF45DD963781CEFBCFDBBDE15FD60F7C02&fileName=/typescript-3.7.0-insiders.20190916.tgz"
    }
}
```

## Future work
The upcoming flag to change class field emit to [[Define]] semantics should disable this error.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by AlCalzone** [comment]
Is there any way how I  can test my code against this? From reading your recent PRs it seems that one of my libraries will be affected by the change.

**Comment by sandersn** [comment]
@typescript-bot pack this
@AlCalzone the code isn't quite done yet, but typescript-bot will produce a tgz on Azure that you can point your package.json to.

The extended tests look pretty grim, but at least this error will be pretty easy to fix.

**Comment by sandersn** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by sandersn** [comment]
@rkirov @mprobst @evmar You will probably want to take a look at this PR too. The errors are easier to fix compared to #33401.

**Comment by sandersn** [comment]
The codefix is in -- @rbuckton I think this is ready for review now.

**Comment by ljharb** [comment]
It seems useful to ship `declare` syntax ASAP, and encourage people to migrate to it, before separately shipping the Set → Define change. Is that an option?

**Comment by sandersn** [comment]
@ljharb Our current plan is to ship the new syntax, the new errors, and the flag to switch to Define semantics at the same time. The flag will initially default to Set semantics, which also silences the errors. People can switch the flag on, fix errors, then switch it off again. Notably, the fixes for both errors are the same with both Set and Define semantics.

We'll discuss this at our design meeting on Friday so we should have a final decision then.

**Comment by ljharb** [comment]
Mainly thinking that the declare syntax is at least explicit, and that you may want to hold off merging the rest until after the next TC39 meeting, in case the topic comes up. (not trying to imply anything will change about the proposal)

**Comment by sandersn** [comment]
The errors in #33401 that disable accessor/property override mismatch are independently useful, although admittedly we haven't got many complaints from people confused by the current Set behaviour.

**Comment by sandersn** [comment]
Note: this-property assignments are still incorrectly erroring in JS.

**Comment by littledan** [comment]
@ljharb I don't see anything on the [October 2019 TC39 agenda](https://github.com/tc39/agendas/blob/master/2019/10.md) about this topic, and the deadline for adding agenda items has passed. Class fields have been stable with Define semantics for the whole time they have been at Stage 3, since 2017, and these semantics have shipped unflagged in Firefox, Chrome, and Node.js, as well as other environments.

**Comment by ljharb** [comment]
The deadline is for stage advancement; there’s no deadline for discussion topics, which is what i was alluding to.

**Comment by AlCalzone** [comment]
@sandersn Surprisingly little errors (only 3) in my codebase. I guess I squashed most of them when I switched testing to Babel+Jest. Back then I switched from redefining the class properties to interface merging, i.e.
```ts
class BaseClass {
  property: number
}

interface SubClass {
  property: 1 | 2 | 3
}

class SubClass extends BaseClass {
  // ...implementation
}
```
which is the ugly brother of the `define` syntax that has been proposed.

**Comment by sandersn** [comment]
This is now included in #33509. Thanks all for testing.

@AlCalzone we decided that interface merging is too esoteric a fix to recommend for the number of errors this causes. Also it's harder to write a codefix for.

@ljharb After our design meeting: #33509 has everything in one PR, and will keep the errors behind a flag while adding the new syntax for everyone to use.

**Comment by AlCalzone** [comment]
@sandersn is `define` inside classes going to be in 3.7?

**Comment by sandersn** [comment]
Yes. Well, `declare` is, I assume that's what you meant.

**Comment by AlCalzone** [comment]
👍🏻

**Pull request closed without merging**
