### PR TITLE
Better typings for Promise.resolve(), like #31117

### PR DESCRIPTION
**Pull request by jablko**

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
Unfortunately, this results in a breaking change in the version of `firebase` we test in our test suite, though it doesn't seem to affect the current version of `firebase`. I haven't been able to find a viable workaround as of yet, and I'm not sure if we should take a breaking change for such a small change to the API.

**Comment by rbuckton** [comment]
I also found an issue in the DefinitelyTyped tests for JQuery that may require a separate fix in the `Awaited` type.

**Comment by sandersn** [comment]
@rbuckton Is this ready to merge now?

**Comment by rbuckton** [comment]
I'd like to run the RWC and user tests once more to be sure.

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
This still causes a build break in firebase-sdk:

```
    /**
     * Takes an array of values and sequences them using the promise (or value)
     * returned by the supplied callback. The callback for each item is called
     * after the promise is resolved for the previous item.
     * The function returns a promise which is resolved after the promise for
     * the last item is resolved.
     */
    export function sequence<T, R>(
      values: T[],
      fn: (value: T, result?: R) => R | Promise<R>,
      initialValue?: R
    ): Promise<R> {
      let result = Promise.resolve(initialValue);
      values.forEach(value => {
        result = result.then(lastResult => fn(value, lastResult));
        ~~~~~~
!!! error TS2322: Type 'Promise<R | Awaited<R>>' is not assignable to type 'Promise<Awaited<R>>'.
!!! error TS2322:   Type 'R | Awaited<R>' is not assignable to type 'Awaited<R>'.
!!! error TS2322:     Type 'R' is not assignable to type 'Awaited<R>'.
      });
      return result as AnyDuringMigration;
    }
```

**Comment by sandersn** [comment]
Note that this breaks `@types/react-test-renderer`'s assumptions that they can create a type that *can't* be passed to Promise.resolve:

```ts
declare const UNDEFINED_VOID_ONLY: unique symbol;
export function act(callback: () => void | { [UNDEFINED_VOID_ONLY]: never }): DebugPromiseLike;

// Intentionally doesn't extend PromiseLike<never>.
// Ideally this should be as hard to accidentally use as possible.
export interface DebugPromiseLike {
    // the actual then() in here is 1-ary, but that doesn't count as a PromiseLike.
    then(onfulfilled: (value: never) => never, onrejected: (reason: never) => never): never;
}
// @ts-expect-error <-- this is no longer an error
Promise.resolve(act(() => {}));
```

I think this change is still OK, I just wanted to report on the break.

**Comment by sandersn** [comment]
This breaks vscode in a few places too, so we're going to revert it for 4.8 to give us a chance to figure out what to do.

**Pull request merged**
