### PR TITLE
Enable corepack in CI

### PR DESCRIPTION
**Pull request by jakebailey**
In lieu of https://github.com/actions/setup-node/issues/531, enable this by hand.

I'm pretty sure this works. If it doesn't, everything will fail and that'll tell me everything I need.

### CODE REVIEW

**Comment by fatcerberus** [comment]
The fact that we need a separate package manager to manage package managers is crazy; let's see how long until that space also gets fragmented and then we need a package manager manager manager...

**Comment by jakebailey** [comment]
> The fact that we need a separate package manager to manage package managers is crazy; let's see how long until that space also gets fragmented and then we need a package manager manager manager...

`volta`, `pacman`, .... 😄

**Review by sandersn — APPROVED** [review]
Seems fine to try. Why do we need this?

**Comment by jakebailey** [comment]
This insulates us from the version of npm provided by the version of node that's installed, instead using the version of npm declared in package.json. Really, this only matters for anything that intends to actually modify `package.json` or `package-lock.json`, so could be scoped down to just affect the update scripts, version bumpers, the release, etc, if desired, but if it were available on the setup-node action, I'd be enabling it everywhere.

Arguably, this should also be applied to the AzDo task we use to release TS to npm (non-nightly), as that's exactly what has broken us in the past; it using npm 6 which has different behavior that we use everywhere else.

**Comment by jakebailey** [comment]
I opted to remove all but the ones where it matters.

**Pull request merged**
