### PR TITLE
Use a function declaration vs a function expression to help deal with a reported Atom+IO.js issue.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
View this change with ```?w=1``` to get a better diff.

**Comment by basarat** [comment]
closes https://github.com/Microsoft/TypeScript/issues/2503

**Comment by mhegazy** [comment]
The change looks fine. i am not sure i understand the original issue though :). so which visit was undefined? and how is that fixed?

**Comment by basarat** [comment]
@mhegazy I don't understand the original reason either. But here it is mentioned again (https://github.com/Microsoft/TypeScript/pull/2505#issuecomment-86384213)

 I am calling `getNamedDeclarations` in a simple loop : https://github.com/TypeStrong/atom-typescript/blob/e8a908c884186109e52b78ccecb941b91e96420c/lib/main/lang/projectService.ts#L805 

It works fine for most projects *including* TypeScript :
image

However for atom-typescript itself, and specifically this source file : https://github.com/TypeStrong/atom-typescript/blob/master/lib/typings/mixto/mixto.d.ts

It gives the error as shown: 

image


```
ReferenceError: visit is not defined
    at visit (C:\Users\basaratsyed\.atom\packages\atom-typescript\node_modules\typescript\bin\typescript.js:28840:51)
    at visitEachNode (C:\Users\basaratsyed\.atom\packages\atom-typescript\node_modules\typescript\bin\typescript.js:4527:30)
    at Object.forEachChild (C:\Users\basaratsyed\.atom\packages\atom-typescript\node_modules\typescript\bin\typescript.js:4659:24)
    at SourceFileObject.getNamedDeclarations (C:\Users\basaratsyed\.atom\packages\atom-typescript\node_modules\typescript\bin\typescript.js:28796:20)
    at Object.getNavigateToItems (C:\Users\basaratsyed\.atom\packages\atom-typescript\dist\main\lang\projectService.js:600:36)
    at Child.RequesterResponder.processRequest (C:\Users\basaratsyed\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:38:60)
    at process.<anonymous> (C:\Users\basaratsyed\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:214:23)
    at process.emit (events.js:119:17)
    at handleMessage (child_process.js:326:10)
    at Pipe.channel.onread (child_process.js:354:11)"__proto__: Object
```

Fixes that work:
* storing `visit` in an explicit variable outside the forEach (I tried that first to see if my observation was correct). As this PR does. 
* renaming visit 


----- 

Note : I don't see *why* this error happens: 



The error is `ReferenceError`. This is the error one gets if there is `foo = 123` but no `var` in strict mode as shown: 

```js
"use strict"
foo = 123
```
```
C:\Users\basaratsyed\test.js:2
foo = 123
    ^
ReferenceError: foo is not defined
    at Object.<anonymous> (C:\Users\basaratsyed\test.js:2:5)
```

Not presented in this PR: Using `var visit` along with `visit = function (node) ...` also fixes it (coinciding with my understanding of `ReferenceError`). Surprisingly *renaming also fixed it* (as presented in this PR). I want to chalk this off as an `atom`(really `iojs` or v8) bug i.e. some issue with the name `visit` in this particular context under some *wierd* circumstances, that will sort itself out.

**Comment by mhegazy** [comment]
Thanks for the explanation. it is just concerning that this is happening, and i want to make sure we do not have other places where similar behavior could occur.

**Comment by DanielRosenwasser** [comment]
Yeah, can we actually link to the bug in io.js and/or node.js?

**Comment by vladima** [comment]
@basarat Can you tell me how to repro this issue locally? Without known root cause it looks like a magic and I don't like magic

**Comment by basarat** [comment]
@vladima agreed. Open atom-typescript with atom-typescript. Have a typescript file active in the editor. Press "ctrl+shift+r" to trigger project symbols resolution. This error will occur and get logged into the atom console as a rejected promise. 

Tips:
* "Ctrl+alt+I" to open atom console.
* Just install atom typescript like you normally would. Then using atoms settings pane you can open it up in atom. 
* feel free to modify code in typescript.js and prjectServices.ts

**Comment by basarat** [comment]
Open typescript in atom. Have a TS file active. And press ctrl+shift+r and this error will not happen.

**Comment by basarat** [comment]
Here is a gif to help along the repro. 

bug

**Comment by basarat** [comment]
A quick [google search](https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=referenceerror%20bug%20node) 

Does show previous bugs along similar lines: 
https://github.com/joyent/node/issues/6235 
https://github.com/node-inspector/node-inspector/issues/461

**Comment by vladima** [comment]
Interesting, I can repro the problem on my windows box, however everything works like charm on Linux. Let me check if I can fish out anything interesting

**Comment by Zoltu** [comment]
@basarat If you don't mind me asking, what tool do you use to create those gifs like the one in https://github.com/Microsoft/TypeScript/pull/2522#issuecomment-87189059?  Sorry for posting here, wasn't sure how else to ask.  Feel free to delete this message.

**Comment by basarat** [comment]
@Zoltu  https://screentogif.codeplex.com/ :rose:

**Pull request merged**
