### PR TITLE
Fix crash resolving ImportTypeNode in JSDoc

### LINKED ISSUE #40767: Casting to a type generated from an @enum => Maximum call stack size exceeded
**TypeScript Version:**  4.0.2 and next

**Search Terms:** @enum Maximum call stack size exceeded

**Code**

[typetest.zip](https://github.com/microsoft/TypeScript/files/5282727/typetest.zip)

and run `./run`

**Expected behavior:**

I don't exactly known, but at least a comprehensible error...

**Actual behavior:**

Getting:
```
/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:78602
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at getTypeOfFuncClassEnumModule (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:32607:25)
    at getTypeOfSymbol (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:32716:24)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35320:29)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35335:32)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35335:32)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
    at getTypeFromJSDocValueReference (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35335:32)
    at getTypeReferenceType (/home/external/sbrunner-cache/.npm/_npx/7357/lib/node_modules/typescript/lib/tsc.js:35308:33)
```

**Playground Link:** 

**Related Issues:** https://github.com/microsoft/TypeScript/issues/18161?

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40767

### CODE REVIEW

**Review by sandersn — COMMENTED** [review]
I believe that condition used to be there and I deleted it at one point. This fixes this crash, but let's make sure that it doesn't break the user tests in some way.

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by andrewbranch** [comment]
According to the user tests, this PR is responsible for the rebranding of Office Fabric UI as Fluent UI.

**Comment by sandersn** [comment]
Errr the Office Fabric *cof* Fluent UI tests are pretty broken right now, and the diff still contains unmerged diffs from master. Plus there's no JS in that project. I think we can take this as not causing any regressions.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
