### PR TITLE
regression(38485): Unable to specify `rawText` when programmatically creating tagged template literals

### LINKED ISSUE #38485: 3.9.1-rc regression: Unable to specify `rawText` when programmatically creating tagged template literals
**TypeScript Version:**  3.9.1-rc
**Search Terms:** tagged template literal rawText raw ES5

**Code**

The problem occurs when synthesising tagged template literals programmatically, and then trying to render them in ES5.

The API provides a method for specifying the "raw" parts of the template:

```ts
const template = ts.createNoSubstitutionTemplateLiteral('text', 'text');
```

But due to this regression this raw value is no longer being used.
An empty string is there, instead.

Here is a link to a reproduction: https://github.com/petebacondarwin/ts-3.9-rawtext-bug

**Expected behavior:**

```ts
$localize(__makeTemplateObject(["text"], ["text"]));
```

**Actual behavior:**

```ts
$localize(__makeTemplateObject(["text"], [""]));
```

**Playground Link:**
It is not possible to provide a Playground link because it only occurs when programmatically creating a tagged template literal AST node.

See the reproduction at https://github.com/petebacondarwin/ts-3.9-rawtext-bug

**Related Issues:**

This is a regression due to this commit: https://github.com/microsoft/TypeScript/commit/70399e146e2a426a2419adc3e3393fa0dc4cd59b#r39098346

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #38485

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
сс @DanielRosenwasser @rbuckton

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.9

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
@petebacondarwin a build should be available in a bit - can you verify that it works for you?

**Comment by petebacondarwin** [comment]
Will do. Thanks!

**Comment by petebacondarwin** [comment]
Testing now

**Comment by petebacondarwin** [comment]
That works for me! Thanks for dealing with this so quickly.

**Pull request merged**
