### PR TITLE
feat: infer implicit "this: this" or "this: typeof Class" for (static) class methods.

### PR DESCRIPTION
**Pull request by Jack-Works**
## Background

Calling a function with the wrong receiver is a common problem in the JavaScript ecosystem.

```js
class T {
    #url = '/'
    report(data: unknown) {
        fetch(this.#url, data)
    }
}

const { report } = new T
setTimeout(() => {
    report({}) // !!! no type error but crashes!
})
```

This problem can be resolved by an explicit `this` annotation in the class method signature.

```js
class T {
    #url = '/'
    report(this: this, data: unknown) {
        fetch(this.#url, data)
    }
}

const { report } = new T
setTimeout(() => {
    report({})
//  ~~~~~~~~~~
//  The 'this' context of type 'void' is not assignable to method's 'this' of type 'T'.
})
```

It's very hard to push the community to add the `this: this` signature and it looks redundant.

## Solution

This PR let the TypeScript infer the `this: this` parameter to prevent this kind of error.

### Class prototype methods

```ts
export class T {
    #brand: any
    // (method) T.thisFree(a: number, b: number): number
    thisFree(a: number, b: number) {
        return a + b
    }
    // (method) T.thisAware(this: this, a: number, b: number): number
    thisAware(a: number, b: number) {
        this.#brand
        return a + b
    }
}
class Q extends T {
    // (method) Q.thisAware(this: this, a: number, b: number): number
    thisAware(a: number, b: number): number {
        thisAware.call(this, 1, 2)
        return super.thisAware(a, b)
    }
}

const { thisFree, thisAware } = new T()
const { thisAware: thisAwareQ } = new Q()
thisFree(1, 2)
thisAware.call(new Q(), 1, 2)

thisAwareQ.call(new T(), 1, 2)
//             ~~~~~~~
// 'T' is assignable to the constraint of type 'this', but 'this' could be instantiated with a different subtype of constraint 'Q'.

   thisAware(1, 2)
// ~~~~~~~~~~~~~~~
// The 'this' context of type 'void' is not assignable to method's 'this' of type 'T'.

thisAware.call({}, 1, 2)
//             ~~
// Type '{}' is missing the following properties from type 'T': #brand, thisFree, thisAware
```

### Static class methods

```ts
class T {
    static value = 1
    // (method) T.thisFree(): void
    static thisFree() {}
    // (method) T.thisAware(T: typeof T): void
    static thisAware() {
        this.value
    }
}
class T2 extends T {}

const { thisAware, thisFree } = T
   thisAware()
// ~~~~~~~~~~~
// The 'this' context of type 'void' is not assignable to method's 'this' of type 'typeof T'.
thisAware.call(T) // ok
thisAware.call(T2) // ok
thisFree() // ok
```

## TODO

- [ ] emit .d.ts
- [ ] report error for anonymous class + static class method with this
- [ ] add tests

## Possible problem

This PR intended to add inferred `(this: this)` to the emitted `.d.ts` so it can spread to the ecosystem and strengthen the type of safety, but

- is it too strict for most users?
- does it need a flag to opt-in/opt-out? (enabled by default is better IMO, maybe in --strict)

I'll wait for the feedback from the TypeScript team, if they will accept this feature, I'll continue to work on this

### CODE REVIEW

**Comment by fatcerberus** [comment]
IIRC this intentionally wasn’t done because it makes all methods implicitly generic and tanks performance as a result

**Comment by fatcerberus** [comment]
FWIW: `this: typeof Class` won’t work for inherited static methods unless the subclass’s constructor signature is compatible.  There is no equivalent to `this: this` for static methods, unfortunately.

**Comment by jakebailey** [comment]
> IIRC this intentionally wasn’t done because it makes all methods implicitly generic and tanks performance as a result

Yep, this is precisely the problem with doing this.

For fun, though:

@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
Well, bad test, as this PR appears to break most of the test cases. Only material-ui compiles at all, and is a bit slower (but, that's just one number).

**Comment by Jack-Works** [comment]
> FWIW: `this: typeof Class` won’t work for inherited static methods unless the subclass’s constructor signature is compatible. There is no equivalent to `this: this` for static methods, unfortunately.

Yes, because this is possible:

```ts
class T {
    static method() {
        return new this()
    }
}
```

Therefore the constructor signature should also be compatible.

> as this PR appears to break most of the test cases

Yeah because it changes the emitted .d.ts.

**Comment by Jack-Works** [comment]
close since the team thinks it's a non-starter

**Pull request closed without merging**
