### PR TITLE
Update singleCompilation flag name to isolatedModules

### PR DESCRIPTION
**Pull request by mhegazy**

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Are we sure we want `isolatedModules` and not `isolatedModule`?

**Comment by yuit** [comment]
lgtm. though agree with @DanielRosenwasser's question. I have slight preference with ```isolatedModule```

**Comment by mhegazy** [comment]
the idea is you would use this with in a normal compilation, with multiple files, to ensure you can do the  compile them in isolation later, hence the "s".

**Pull request merged**
