### PR TITLE
New mocha reporter

### PR DESCRIPTION
**Pull request by danquirk**
Pretty simple change but the diff seems a little confused by some whitespace/reformatting changes. I made a new mocha reporter here https://github.com/danquirk/mocha-fivemat-progress-reporter that will report test output by test suite with a progress bar instead of one giant set of dots. This turns it on by default for ```jake runtests``` 

Note that after merging this everyone will be required to run ```npm install``` again to get the new reporter.

The final output when tests complete is unchanged, total time and a final list of aggregated failures are still reported.

Ex:

newreporter

### CODE REVIEW

**Comment by danquirk** [comment]
@DanielRosenwasser mentioned he might miss his red dots as some crazy means of figuring out which test failed. We could turn the progress bar red as soon as a failure occurs:

image

Alternatively/in addition we can just print test names immediately upon failure:
image

**Comment by DanielRosenwasser** [comment]
Yes, :+1: for crazy red loading bars.

**Comment by CyrusNajmabadi** [comment]
I'd prefer a red dot showing an error happened.  Then just print the errors at the end.  Having hte errors interspersed with progress info will just make investigation annoying.

**Comment by danquirk** [comment]
The final output is unchanged either way so you will always have the errors at the end in the way you're accustomed to with today's reporters. The interspersed name would allow you to immediately note a failure and start investigating while the rest of the tests continue.

**Comment by danquirk** [comment]
Made both of the changes in my first reply.

**Pull request merged**
