### PR TITLE
use XDG base directory compatible cache location

### LINKED ISSUE #12674: ATA puts types in $HOME/Microsoft
_From @Instagit on December 1, 2016 10:38_

- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

I have yet to find out how to reproduce this, but VS Code creates a *Microsoft/TypeScript/node_modules/* directory with the *types-registry* npm module in it in the home directory.

The package readme says

>This is the source code for the types-publisher service, which publishes the contents of DefinitelyTyped to npm.

I never set anything to be shared or published. So what exactly is this and what does it do?

_Copied from original issue: Microsoft/vscode#16318_

### PR DESCRIPTION
**Pull request by vladima**
fixes #12674

### CODE REVIEW

**Comment by mhegazy** [comment]
@Tyriar and @mjbvz  any more comments?

**Comment by mhegazy** [comment]
//CC: @billti

**Comment by mjbvz** [comment]
@vladima Is this targeting 2.2 or will it make it into 2.1?

**Comment by vladima** [comment]
current plan is that it will go into 2.2

**Comment by mjbvz** [comment]
Ok. At least users can work around this by installing an nightly TS 2.2 build.

We'll keep the bug open on the VSCode side until we pick up a TS build with the fix.

Thanks

**Pull request merged**
