### PR TITLE
fix(37791): Using object destructuring with ECMAScript's private field as computed property name leads to runtime error

### LINKED ISSUE #37791: Using object destructuring with ECMAScript's private field as computed property name leads to runtime error
**TypeScript Version:**  3.8.3

**Search Terms:** computed object property name destructuring private ECMAScript

**Code**
```ts
class PropertyAccessor {
    readonly #propertyName: string;

    constructor(propertyName: string) {
        this.#propertyName = propertyName;
    }

    getPropertyValue(obj: Record<string, string | undefined>): string | undefined {
        const { [this.#propertyName]: value } = obj;
        return value;
    }
}

const accessor = new PropertyAccessor('name');
console.log(
    accessor.getPropertyValue({ name: 'Adam' })
);
```

**Expected behavior:**
'Adam' is logged at runtime.

**Actual behavior:**
Runtime error occurs:
```
Private field '#propertyName' must be declared in an enclosing class 
```

**Additional information:**
I just started using TypeScript and I ran into this problem while converting one of my javascript projects, the behavior was confusing to me. It seems like the code is transpiled incorrectly, as it works when not using destructuring syntax:

```ts
const { [this.#propertyName]: value } = obj;
// compiles to
const { [(_propertyName = new WeakMap(), this.#propertyName)]: value } = obj;

const value = obj[this.#propertyName];
// compiles to
const value = obj[__classPrivateFieldGet(this, _propertyName)];
```

The error does not occur when using TypeScript's `private` field instead of ECMAScript's.
The error does not occur when targeting ESNext.

**Related Issues:** Maybe #26572 #26355? Doesn't seem like the same problem but similar keywords.

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, privateMap, value) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to set private field on non-instance");
    }
    privateMap.set(receiver, value);
    return value;
};
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, privateMap) {
    if (!privateMap.has(receiver)) {
        throw new TypeError("attempted to get private field on non-instance");
    }
    return privateMap.get(receiver);
};
var _propertyName;
class PropertyAccessor {
    constructor(propertyName) {
        _propertyName.set(this, void 0);
        __classPrivateFieldSet(this, _propertyName, propertyName);
    }
    getPropertyValue(obj) {
        const { [(_propertyName = new WeakMap(), this.#propertyName)]: value } = obj;
        return value;
    }
}
const accessor = new PropertyAccessor('name');
console.log(accessor.getPropertyValue({ name: 'Adam' }));

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=3.8.3#code/MYGwhgzhAEAKBOB7ADgU3gFwJ4EFjFSkXmgG8AoaK6eVMAE0QDsQtoBiZJNTLAOTABbVAC5oEDPACWTAOYBucpWrBmE+AFdgGYgAouKdNgHCx6mbICUZZdWoYAFlIgA6TtyP8hqaAF5oBjzG3op2AL5KdrKoGAiGvABqYCAaqLqIAEYAVmIASqiq8PQAPOZyADTikhbQAD7QGkz0qABmMqj0AHyWZtVydQ1Nre30NnZ2qkwSZNAA2o7OboGeJqgAumIAbsmp0GF+0JlZoeNUtBga8EzQ2ymoJ1QREeST02D4hBDEB0yoAO5wDy8PAEIjwXQAciY3ghlkUr0QIFQLhAiFkuls0HeoK+8Bc0ViQOwSTuulI0GhpmgEJw9CEEL2lnIcKAA)

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37791

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@rbuckton Could you review this PR?

**Comment by a-tarasyuk** [comment]
cc @rbuckton

**Comment by a-tarasyuk** [comment]
@rbuckton Could you review these changes? It was included in Milestone 4.0.1 and there is a chance to see the fix in an upcoming release to avoid using [workarounds](https://github.com/microsoft/TypeScript/issues/37791#issuecomment-617821315). Thanks in advance.

**Comment by rbuckton** [comment]
@typescript-bot pack this

**Comment by rbuckton** [comment]
I don't think this sufficiently resolves the issue. There are two different problems here that need to be addressed:

1. Somewhere in the _classFields.ts_ transform part of the previous AST is being added to the output AST without being visited.
2. Its important to know *where* the computed property name is. While your fix addresses the object literal case, it is still broken when used with a nested `class` declaration:

```ts
class Foo {
    #value;
    constructor(value) {
        this.#value = value;
    }
    getValue(data) {
        const obj = this;
        class Bar {
            #y;
            [obj.#value]() {}
        }
        return value;
    }
}
```

I think the problem with (1) is *in* `visitComputedPropertyName`:

https://github.com/microsoft/TypeScript/blob/052d7308e6f1a3916b4166d21d40e7b5d7e82411/src/compiler/transformers/classFields.ts#L187

This should probably read:
```ts
expressions.push(node.expression);
```

Because `name` is the original AST node, and `node` is the *visited* AST node.

The problem with (2) is that there's only one `pendingExpressions` array, when this should really be a fresh array when you descend into each new function scope.

**Comment by a-tarasyuk** [comment]
@rbuckton Thanks for the review 👍🏻. I've added additional changes/tests.

**Review by rbuckton — APPROVED** [review]
Looks good!

**Comment by a-tarasyuk** [comment]
@rbuckton Thanks

**Pull request merged**
