### PR TITLE
Experiment short-circuiting of union distribution

### LINKED ISSUE #47511: Experiment short-circuiting of union distribution
# Suggestion

## 🔍 Search Terms

union distribute short-circuit performance

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

@amcasey and I were discussing #47481 and he had an interesting observation. Consider this program:
```ts
type HugeUnion1 = "a" | "b" | "c" | "d" | ... [10,000 more];
type HugeUnion2 = "q" | "r" | "s" | "t" | ... [10,000 more];

type Square<T, U> = T extends U ? true : false;

type M = Square<T, U>;
```

*Naively*, when evaluating `M`, we need to check if every member of `HugeUnion1` is present in `HugeUnion2`. However, let's say we saw this (in the sorted form):
```ts
type HugeUnion1 = "a" | "q" | ... [10,000 more];
type HugeUnion2 = "a" | ... [10,000 more which do not include 'q'];
```
After evaluating `"a"`, we have a `true`. After evaluating `"q"`, we have a `false`. *We can skip the rest of the list* since no subsequent result will change the answer (because `T` does not appear in the conditional result)

Moreover, if instead of `false` we had `never`, we could immediately stop after seeing `true`, since `true | never` is just `true`

### PR DESCRIPTION
**Pull request by Zzzen**
Fixes #47511

Tried the following code on my machine, the check time is reduced from 24s to 6s. I'd like to see how it works for RWC. 
```ts
type HugeUnion1 = "a" | "q" | ... [10,000 more];
type HugeUnion2 = "a" | ... [10,000 more which do not include 'q'];

type Square<T, U> = T extends U ? true : false;

type M = Square<HugeUnion1, HugeUnion2>;
```

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot test top100

**Comment by jakebailey** [comment]
I feel like something's wrong with RWC; if doesn't reply?

**Comment by sandersn** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
Yeah, when I ran it, it didn't seem like we saw a boost, but we probably don't have something so bad in our test suite.

**Comment by jakebailey** [comment]
@Zzzen I took the liberty and merged main into this to retest it; hope you don't mind.

@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt

**Review by ahejlsberg — COMMENTED** [review]
This is superceded by the more general #53192.

**Pull request closed without merging**
