### PR TITLE
Add support for NumberFormatOptions notation

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/microsoft/TypeScript/issues/36533

Adds the `notation` option to [`NumberFormatOptions`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) in `src/lib/es5.d.ts`

I'm an experienced JS developer, but new to TypeScript, so if any changes are required to this PR you may have to give me some pointers.

### CODE REVIEW

**Comment by NarasimhaReddyY** [comment]
This should be merged.

**Comment by benmccann** [comment]
Thanks for assigning this to yourself @sandersn. Any chance you'd be able to take a quick look? I'm hoping it should be an easy review since it's only a couple lines.

**Comment by sandersn** [comment]
I typically merge lib changes at the beginning of a version to let people find breaks, so I'll wait until 4.0 in a few weeks. Touching the ES5 lib is bound to break somebody, no matter how small the change.

**Comment by maneetgoyal** [comment]
@benmccann @awibox Should this property go in `es5.d.ts` or `esnext.intl.d.ts` instead? 

I was just trying to draw some analogy with the `Array` object. All the common Array methods like `forEach`, `map`, etc. are in `es5.d.ts`. But the new ones like `.flatMap` and `.flat` are in `es2019.array.d.ts`.

`notation` recently became a standard property (right?). [ECMAScript 2021 Intl](https://tc39.es/ecma402/#sec-initializenumberformat) specs (draft) makes a mention of it. No mention in [ECMAScript 2019 Intl](https://ecma-international.org/ecma-402/#sec-initializenumberformat) specs. So should it go in `esnext.intl.d.ts`/`es2021.intl.d.ts` instead of `es5.d.ts`?

**Comment by BPScott** [comment]
Yo @sandersn, I'm guessing we've missed the boat for merging this and #38013 and we'll have to wait till the 4.1 cycle begins?

**Comment by sandersn** [comment]
Sorry for missing this. This should go into ES2020, not ES5, but if we can get it in before the beta on Monday it'll be fine to ship. I'm pretty sure the right place is es2020.intl.d.ts.

@benmccann I'll do it in the next day or so if I have time. I understand if you're sick of me forgetting about this. =)

**Comment by benmccann** [comment]
Great. Thanks so much @sandersn !  I'll leave the rest to you then. I'm pretty new to TypeScript, so I'm sure you have a much better handle on things than I do, but please let me know if there's anything I can do to help

**Pull request merged**
