### PR TITLE
Fix crash caused by incorrect bounds check (regression in 4.8)

### LINKED ISSUE #50479: getTypeFromTypeNodeWorker crashes with TypeError: Cannot read properties of undefined (reading 'kind')
# Bug Report

### 🔎 Search Terms

`"Cannot read properties of undefined"`, `getInferredTypeParameterConstraint`, `getTypeFromTypeNodeWorker`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.7.4 and 4.8.2

### ⏯ Playground Link

TBD

### 💻 Code

TBD

This is occurring in a private repo with a lot of code.

I plan to progressively delete code until I can whittle it down to a minimal repro but that may take several days so until then I thought I'd file this in case anyone has tips on where to start looking.

### 🙁 Actual behavior

```
❯ yarn build
yarn run v1.22.19
$ tsc
/home/birtles/referee/node_modules/typescript/lib/tsc.js:98394
                throw e;
                ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at getTypeFromTypeNodeWorker (/home/birtles/referee/node_modules/typescript/lib/tsc.js:53060:26)
    at getTypeFromTypeNode (/home/birtles/referee/node_modules/typescript/lib/tsc.js:53057:49)
    at getEffectiveTypeArgumentAtIndex (/home/birtles/referee/node_modules/typescript/lib/tsc.js:68314:24)
    at Array.<anonymous> (/home/birtles/referee/node_modules/typescript/lib/tsc.js:50294:52)
    at getMappedType (/home/birtles/referee/node_modules/typescript/lib/tsc.js:53203:46)
    at instantiateTypeWorker (/home/birtles/referee/node_modules/typescript/lib/tsc.js:53516:24)
    at instantiateTypeWithAlias (/home/birtles/referee/node_modules/typescript/lib/tsc.js:53509:26)
    at instantiateType (/home/birtles/referee/node_modules/typescript/lib/tsc.js:53495:37)
    at _loop_15 (/home/birtles/referee/node_modules/typescript/lib/tsc.js:50296:58)
    at getInferredTypeParameterConstraint (/home/birtles/referee/node_modules/typescript/lib/tsc.js:50327:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 🙂 Expected behavior

Build succeeds.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #50479.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@andrewbranch @DanielRosenwasser We'll want this one in 4.8.4.

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.8

**Comment by Ayc0** [comment]
Thanks for the fix!
Do you know if this will be deployed with the 4.8.4 or if it'll be with the next 4.9.x?

**Comment by ahejlsberg** [comment]
The fix will be in 4.8.4.

**Comment by Ayc0** [comment]
Thanks 🙏

**Pull request merged**
