### PR TITLE
processDiagnosticMessages: Simplify check for uniqueness of names

### PR DESCRIPTION
**Pull request by andy-ms**
Tested with:
```
diff TypeScript/src/compiler/diagnosticInformationMap.generated.ts TypeScript_1/TypeScript/src/compiler/diagnosticInformationMap.generated.ts
diff TypeScript/src/compiler/diagnosticMessages.generated.json TypeScript_1/TypeScript/src/compiler/diagnosticMessages.generated.json
```
No change.

### CODE REVIEW

**Comment by andy-ms** [comment]
@weswigham Any idea why `gulp generate-diagnostics` doesn't seem to run `processDiagnosticMessages.ts`?

**Comment by weswigham** [comment]
@andy-ms `if (needsUpdate(diagnosticMessagesJson, [generatedDiagnosticMessagesJSON, diagnosticInfoMapTs]))` is checking if the generatedJSON and info map TS file are older than the input json file. Editing the actual generation script won't change either of those files, so it won't be run. Add the generating ts or js file to the list of files to compare to to get it to consider it for change-time-tracking.

**Comment by andy-ms** [comment]
OK, I had been confused before because in the old implementation, `isCaseSensitive` was hard-coded to `false`. But we actually had the condition on backwards:
```ts
if (caseSensitive) {
    s1 = s1.toLowerCase();
    s2 = s2.toLowerCase();
}
```
Since `isCaseSensitive` was always false, `stringEquals` was just a `==` test.

**Comment by andy-ms** [comment]
@weswigham We already have both `Diagnostics.file` and `Diagnostics.FILE`. In one case we want this word to appear in lowercase, in another we want it uppercase. I don't see any problem with that.

**Comment by weswigham** [comment]
Alright.

**Pull request merged**
