### PR TITLE
Emit modules in strict mode

### LINKED ISSUE #3576: Emit 'use strict' code for input defined via ES6 modules
ES6 modules default to running the code in the module in the strict mode. When transpiling this input into ES5 the strict mode should be preserved.

As of Typescript 1.5 beta this is not the case:

input:

```
export class Foo{}
```

transpile with: `tsc --module commonjs test.ts`

actual output:

```
var Foo = (function () {
    function Foo() {
    }
    return Foo;
})();
exports.Foo = Foo;
```

expected output:

```
'use strict';

var Foo = (function () {
    function Foo() {
    }
    return Foo;
})();
exports.Foo = Foo;
```

The same issue affects output for amd and system module formats.

### LINKED ISSUE #4963: Should the strict-mode status of a file be dependent on its external module status
With #4811 merged we've decoupled ES6 module emit from the ES6 language level, allowing us to emit other module forms when targeting ES6. This brings up another interesting question - we parse _all_ external modules in strict mode, ES6 or not, when this is only a requirement for ES6 modules. Should we fix this and make the parse dependent on the module selection? Or should we emit `"use strict";` in non-ES6 forms so reality matches the parser? Even before #4811 we've actually had this wrong:
```ts
import * as foo from "./foo";

with (foo) {
	
}
```
We forbid the `with` as per strict mode, but we're emitting an amd module _without_ a `"use strict";` indicator. To be correct, when not targeting es6 modules, we should either disable strict mode when parsing or emit a `"use strict";`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #3576.
Closes #4963.

### CODE REVIEW

**Comment by mhegazy** [comment]
it is common for users to have "use strict" as their first line in a module anyways, now we will emit two.

**Comment by weswigham** [comment]
Correct! But this change would bring us inline with both babel and our own parser. There's also no harm in it.

**Comment by weswigham** [comment]
An interesting behavioral quirk this fixes is this:
```ts
export function what() {
  return this;
}
var x = what.call(2);
assert(typeof x === "number");
```
That assertion changes truthiness based on the strict mode status of the containing code. (Specifically, its only true in strict mode.)
So compiling this code in babel, the assertion is true, but with TS it is false at present.

**Comment by DanielRosenwasser** [comment]
You could just check if the first statement is a `"use strict"` directive.

**Comment by weswigham** [comment]
@DanielRosenwasser So you have asked, so you shall recieve

**Comment by yuit** [comment]
Look good :+1:  Could you add a test when users already have "use strict" and we omit the emitting.

**Comment by DanielRosenwasser** [comment]
:100:

**Comment by weswigham** [comment]
@yuit `tests/baselines/reference/modulePrologueAMD.js`, `tests/baselines/reference/modulePrologueCommonjs.js`, `tests/baselines/reference/modulePrologueSystem.js`, and `tests/baselines/reference/modulePrologueUmd.js` got ya covered

**Comment by mhegazy** [comment]
@weswigham can you add a blurb about this change and what breaks in the [breaking changes](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#modules-are-now-emitted-with-a-use-strict-prologue) page; mainly issues that the compiler will not catch but will break at runtime, e.g. eval introducing new variables, value of `this`, errors on calling function.caller, etc.. possibly reference https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Pull request merged**
