### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by falsandtru**
@RyanCavanaugh

### CODE REVIEW

**Comment by IllusionMH** [comment]
Why not current dev builds version`3.7` if `-dev.201xxxxx` part is still there ?

**Comment by RyanCavanaugh** [comment]
Yeah, let's just jump to 3.7. Thanks for the PR @falsandtru

**Comment by falsandtru** [comment]
Okay, fixed.

**Comment by orta** [comment]
Nice one 👍

**Pull request merged**
