### PR TITLE
Partially disable inference recursion tracking changes

### PR DESCRIPTION
**Pull request by ahejlsberg**
Experiment to see if partially disabling inference recursion tracking changes from recursive conditional types PR resolves the OOM we're seeing in the RWC test suites.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
@weswigham Hmm, the RWC suites are failing even when I back out the changes that could potentially consume more memory by generating more work. I'm pretty sure there's nothing left in the recursive conditional types PR that could be the cause. Wonder if something else could be?

**Comment by ahejlsberg** [comment]
@weswigham Also, [here](https://github.com/microsoft/TypeScript/pull/40002#issuecomment-673699939) I ran the RWC tests before merging the PR and I'm pretty certain they passed (sadly that build has now gone away). The fact that none of this repros locally of course makes it extra hard to track down.

**Comment by weswigham** [comment]
RWC should be fixed now~

**Comment by weswigham** [comment]
No idea how a change merged on the timeline _after_ your change was merged somehow affected your change's RWC run, though.

**Pull request closed without merging**
