### PR TITLE
Add browser field entries for all require calls in sys.ts

### PR DESCRIPTION
**Pull request by weswigham**
Per [this comment](https://github.com/microsoft/TypeScript/pull/33225#issuecomment-527872239)

### CODE REVIEW

**Comment by weswigham** [comment]
cc @andrewbranch who also seems to show interest in our packability

**Comment by andrewbranch** [comment]
Submodules changed 😖

**Comment by uniqueiniquity** [comment]
Looks good, though where is this documented? Having trouble finding it.

**Comment by AviVahl** [comment]
@uniqueiniquity https://github.com/defunctzombie/package-browser-field-spec via https://webpack.js.org/configuration/resolve/#resolvealiasfields

**Pull request merged**
