### PR TITLE
Inherit non-enumerable static properties

### PR DESCRIPTION
**Pull request by Sl1v3r**
In es6 classes, transpiled with Babel, static properies are being set with `object.defineProperty(Parent, { staticProperty: {  enumerable: false }})`, so TypeScript can't make proper extend.

Is there any reason not to set constructor's `__proto__` instead of copying properties with cycle?

```diff
 var __extends = (this && this.__extends) || function (d, b) {
-    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
+    if (b) Object.setPrototypeOf ? Object.setPrototypeOf(d, b) : d.__proto__ = b;
     function __() { this.constructor = d; }
     d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
 };
```

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Mutating `__proto__` (or calling `setPrototypeOf`) has significant perf impact in most runtimes.

It's not clear to me that we *should* copy down non-enumerable properties. Isn't that the spirit of non-enumerable?

**Comment by Sl1v3r** [comment]
Because according to standard (I'm pretty sure), classes static properties are not enumerable, I've checked latest webkit with classes support:
```javascript
class Test {
	static method() {}
}
for (var x in Test) console.log(x);
// nothing
```

But static properties must be inherited:
```javascript
class Child extends Test {);
typeof Child.method // "function"
```

So TypeScript can't properly extend javascript constructors, described as class in d.ts

[This](http://jsperf.com/manually-copying-properties-vs-changing-proto) test shows that mutating `__proto__` is really 38% slower in Сhrome, but even a little faster in Gecko and Chrome Mobile. Is this difference really meaningful?

**Comment by RyanCavanaugh** [comment]
It's not about the speed of the specific operation of setting `__proto__` itself, it's about the downstream effects in the runtime in terms of its ability to optimize code involving that object.

If you have an ES6 class to inherit from, then presumably the derived class can target ES6 emit and you're not going to be calling `__extends anyway`. If it's not an ES6 class, then (hopefully) its static members *are* enumerable and will be copied appropriately. What's the scenario for an ES5 class inheriting an ES6 class?

**Comment by Sl1v3r** [comment]
Well, this how javascript is meant to work. I thought, TypeScript compiler tries to line-up with standard. If it's goal is to improve javascript performance by the cost of changing it's standard behaviour.

I can't object, as this is ideological question.

Just to make make my intentions clear:

According to [ecma-262/6.0 14.5.14](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation) subclass is meant to have `__proto__` pointing at superConstructor:
. 5. If ClassHeritageopt is not present, then
... * ...
. 6. Else
... g. Else
..... ii. Let constructorParent be superclass
. 12. Let __constructorInfo__ be the result of performing DefineMethod for constructor with arguments _proto_ and _constructorParent_ as the optional _functionPrototype_ argument.
. 14. Let __F__ be _constructorInfo_.[[closure]]
. 17. Return __F__.

In latest webkit:
```javascript
class Parent {}
class Child extends Parent {}
Child.__proto__ // class Parent
```

**Comment by mhegazy** [comment]
The typescript compiler aims at following the JS semantics as much as possible; it also aims at producing clean, idiomatic and performant generated output. This means that sometimes utility of following the run-time semantics does not justify the cost, specially for a helper as prevalent as `__extends`.

One thing to note, you do not need to use the default `__extends` helper if you do not agree with its semantics, you can call the compiler with `--noEmitHelpers`, and provide your own `__extends` implementation.

**Pull request closed without merging**
