### PR TITLE
Add full format options to configure request and remove ability from open request

### PR DESCRIPTION
**Pull request by dbaeumer**
This is a follow up pull request from #2468. I followed @steveluc suggestion:

So my vote is just provide formatting options on configure, even removing them from open, because the editor may know that the server’s defaults are correct and because the editor may decide to send a configuration message for each file immediately after the open message.

I started a new pull request since the new one doesn't have much in common with the old one. I closed the old one.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
thanks

**Comment by steveluc** [comment]
:+1:

**Comment by dbaeumer** [comment]
Merged pull request into master.

**Comment by dbaeumer** [comment]
Although stated different by github I merged it over. I merged on my local machine. Had quite some conflicts.

**Pull request closed without merging**
