### PR TITLE
Fixes use of combination of options sourceRoot and mapRoot with inlineSourceMap and inlineSources

### PR DESCRIPTION
**Pull request by sheetalkamat**
Also handles : #5613

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by vsavkin** [comment]
Quick question.

Why is the combination of inlineSources and sourceRoot not allowed? 

Without being able to set sourceRoot, the source field will always contain relative paths. These paths are used in stack traces. So the the user will see "../../../../../angular2/src/core.ts", which can be confusing.

**Comment by mhegazy** [comment]
`--inlineSources` will inline the contents of the source file in the map, so the source file is not needed any more.

**Comment by vsavkin** [comment]
The source file is not used, but the sources property is still used in track traces.

**Pull request merged**
