### PR TITLE
Support tree-shakable imports for --target es2015

### LINKED ISSUE #16999: make tslib imports shakable
**TypeScript Version:**  2.4.1
when I use ts with config like:
```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "importHelpers": true,
    "module": "esnext",
    "noEmitHelpers": true,
    "target": "esnext"
  }
}
```
I notice that it come out with code like this
```ts
import * as tslib_1 from "tslib";
```
It is not good enough for tree-shaking by webpack.
Webpack actually bundle with the entire `tslib.es6.js`

And it's a bit heavy in my bundle 
image

**Expected behavior:**

```ts
import { __decorate } from "tslib"; 
// depends on funcitons that actually used with in this file
```

### PR DESCRIPTION
**Pull request by rbuckton**
Changes the emit for `--importHelpers` when the module kind is `es2015` or `esnext` so that they are tree-shakable by WebPack.

For example, we previously would emit:
```ts
// --module es2015
import * as tslib_1 from "tslib";
const obj = tslib_1.__assign({}, other);
```

But now we emit:
```ts
// --module es2015
import { __assign } from "tslib";
const obj = __assign({}, other);
```

The emit for `commonjs`, `amd`, `umd`, and `system` is unaffected.

Fixes #16999

### CODE REVIEW

**Comment by rbuckton** [comment]
> I'd expect our emit to be something like [...]

We explicitly don't do this for any helpers, because we allow you to replace helpers. If we renamed a helper because we found a declaration with the same name at the top-level, we would break that feature.

**Comment by weswigham** [comment]
> We explicitly don't do this for any helpers, because we allow you to replace helpers. If we renamed a helper because we found a declaration with the same name at the top-level, we would break that feature.

But that doesn't work for import helpers, because the helper gets imported and accessed via namespace (usually)?

**Comment by rbuckton** [comment]
"Rename the helper for all uses of the helper in the file but *only* if its imported and `--target ES2015`, but don't rename it if its emitted inline" seems kind of an esoteric rule that I'm not sure is 100% necessary.

**Comment by weswigham** [comment]
I'm just point out hat previously 
```ts
const x = {};
const __assign = {...x, x: 12};
export {};
```
with `importHelpers: true`, `target: es5`, and `module: es6` would work at runtime without error, while after the import style change, its behavior changes and now `__assign` mangles the import...

**Comment by rbuckton** [comment]
Fair enough. I'll look into it tomorrow.

**Comment by rbuckton** [comment]
I've added import aliases for cases where there are collisions.

**Pull request merged**
