### PR TITLE
Make createScanner external (fixes #4057)

### LINKED ISSUE #4057: createScanner function no longer exposed in typescriptServices.d.ts on latest build
createScanner was previously exposed in #3020, along with the Scanner class. However, in the latest master branch of typescript, the Scanner class is still there but createScanner is missing.

### PR DESCRIPTION
**Pull request by adidahiya**

### CODE REVIEW

**Comment by adidahiya** [comment]
forgot to update `lib/typescriptServices.d.ts`... fix coming

**Comment by yuit** [comment]
lgtm

**Comment by DanielRosenwasser** [comment]
@mhegazy shouldn't this trigger API test failures?

**Comment by mhegazy** [comment]
we disabled the API baseline as it was too noisy. it will only break now if you change an API that is used by the test in a way that would generate a compilation error in the test.

**Comment by mhegazy** [comment]
:+1:

**Pull request merged**
