### PR TITLE
Allow diag code specification in ts-expect-errors

### LINKED ISSUE #45937: Allow specifying diagnostic code in ts-expect-error
# Suggestion

## 🔍 Search Terms
ts-expect-error

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow @ts-expect-error to specify diagnostic codes to be more precise in expectations.
**Example:**
`// @ts-expect-error TS1234` 

Will only expect that diagnostic code. If the same line triggers a different diagnostic code, the expectation will error as if there was no error on the proceeding line.

## 📃 Motivating Example

This feature will be particularly useful when migrating code (1) between repositories with different TS configs, or even for (2) a slightly safer path when upgrading TS versions if all issues are not immediately fixed.

## 💻 Use Cases

The Teams Org is facing a code migration that I expect will benefit from this greatly. Please reach out to me (or I will come to office hours) and we can go through that example.

## Code

I have attached a PR which implements the change as an example. Let me know what you think!

### PR DESCRIPTION
**Pull request by markjm**
Fixes #45937

PR made at this point more for illustrative purposes, but it is working just fine as is

### CODE REVIEW

**Comment by Jack-Works** [comment]
Cool to see this feature! Does your PR support multiple error codes? It will be useful.

```ts
// @ts-expect-error TS1234,TS2345
```

**Comment by markjm** [comment]
> Cool to see this feature! Does your PR support multiple error codes? It will be useful.
> 
> ```ts
> // @ts-expect-error TS1234,TS2345
> ```

It doesn't right now, but should be pretty easy to extend! Is it common that 2 errors that you want to ignore are on the same line, though?

**Comment by Jack-Works** [comment]
> > Cool to see this feature! Does your PR support multiple error codes? It will be useful.
> > ```ts
> > // @ts-expect-error TS1234,TS2345
> > ```
> 
> It doesn't right now, but should be pretty easy to extend! Is it common that 2 errors that you want to ignore are on the same line, though?

It might happen when you deal with a very badly typed library 😂

**Comment by markjm** [comment]
Looks like I broke some tests, but will fix up the changes if yall are digging the change

**Comment by sandersn** [comment]
Note: I'm going to hold off reviewing this PR until the linked issue is accepted.

**Comment by markjm** [comment]
@typescript-bot  pack this

**Comment by sandersn** [comment]
@typescript-bot pack this

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this PR while it's still waiting on its bug to be accepted. If the code is still useful after the bug is accepted, we can re-open then.

**Pull request closed without merging**
