### PR TITLE
Add a GH Action to file a new issue if we go a week without seeing a typescript-error-deltas issue

### PR DESCRIPTION
**Pull request by amcasey**
Covers [NewErrors], [ServerErrors][TypeScript], and [ServerErrors][JavaScript].

### CODE REVIEW

**Comment by amcasey** [comment]
Sample output: https://github.com/amcasey/ActionScratch/issues/15

**Comment by amcasey** [comment]
image

**Comment by jakebailey** [comment]
In case you didn't know about it, another way to do this is with https://github.com/actions/github-script, if you prefer writing things in JS and having it all set up for you.

**Comment by amcasey** [comment]
@jakebailey I had zero knowledge of GH Actions when I started. 😆 

If you want to take this over and make it good, I would be thrilled.  Otherwise, I was going for the simplest thing that worked (at the expense of some code duplication 😢).

**Comment by jakebailey** [comment]
I don't mind how you've done it; it seems like it might have been more annoying to emulate github's search mechanism in a JS action anyhow (no idea if you can use that via the API or what).

**Comment by amcasey** [comment]
@jakebailey Is that a sign-off? 😛

**Review by jakebailey — APPROVED** [review]
It can be, I just assumed you wanted Ryan to look at it.

**Comment by amcasey** [comment]
I just picked him since I didn't expect anyone not being tagged to care. :wink:

**Pull request merged**
