### PR TITLE
Sync the dom.generated.d.ts files from TSJS repo

### PR DESCRIPTION
**Pull request by zhengbli**
Contains fixes for:
#5533 
#3583 
#1558 
#1253

### CODE REVIEW

**Comment by yuit** [comment]
lgtm

**Comment by mhegazy** [comment]
:+1:

**Comment by sparecycles** [comment]
@mhegazy 

Curious, what's the strategy for syncing up the other 4 files? In my PR I changed one declaration in 6 files, #5859, but only two of those files are covered in this PR.

**Comment by mhegazy** [comment]
there are sources (src\lib\*.d.ts), that are used to generate the output (build\local\*.d.ts and lib\*.d.ts), you only need to update the sources, the build (`jake lib`) will generate the outputs.
you can find more details at: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Pull request merged**
