### PR TITLE
Add state parameter to forEachChild(Recursively)

### LINKED ISSUE #42285: API: add parameter to ts.forEachChild, that is passed through to the callback
# Suggestion

## 🔍 Search Terms

forEachChild closure

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add an optional parameter to `ts.forEachChild` that is passed through to the callback.

```ts
export function forEachChild<T, S>(node: Node, cbNode: (node: Node, state: S) => T | undefined, cbNodes?: (nodes: NodeArray<Node>, state: S) => T | undefined, state: S): T | undefined;
export function forEachChild<T>(node: Node, cbNode: (node: Node) => T | undefined, cbNodes?: (nodes: NodeArray<Node>) => T | undefined): T | undefined;
```

There's already a similar pattern in `ts.forEach{Leading,Trailing}CommentRanges`: https://github.com/microsoft/TypeScript/blob/1ecf22884fcad201e8c13c269f2eb531a595dfab/src/compiler/scanner.ts#L834

## 📃 Motivating Example

This would help API users and the compiler codebase itself to avoid closures in many cases when using `forEachChild`.

## 💻 Use Cases

Before (needs closure):
```ts
function analyzeNode(node: ts.Node) {
  const children: ts.Node[] = [];
  // the following closure prevents some opimizations of the containing function
  // e.g. 'children' is "context-allocated", i.e. on the heap instead of the stack,
  // a new instance of the closure is created every time the containing function is called,
  // ...
  ts.forEachChild(node, (child) => void children.push(child));
  // now do stuff with children
}
```

After (without closure):
```ts
function collectChildren(node: ts.Node, children: ts.Node[]) {
  children.push(node);
}

function analyzeNode(node: ts.Node) {
  const children: ts.Node[] = [];
  ts.forEachChild(node, collectChildren, undefined, children);
  // now do stuff with children
}
```

There are several functions in the compiler codebase, that could benefit from this:
* forEachReturnStatement
* forEachYieldExpression
* forEachChildRecursively
* getNodeAtPosition
* ...

### PR DESCRIPTION
**Pull request by ajafff**
Fixes #42285

This changes `forEachChild` and `forEachChildRecursively` to accept a `state` parameter that is passed through to the callback.
This PR contains refactorings for uses within `src/compiler` that were easy to convert from a closure to a function declaration.

I extracted the refactoring and fixing of `forEachChildRecursively` into #42300 so that can be reviewed independently.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by amcasey** [comment]
The perf numbers don't appear to have changed, but our coverage isn't great.  @ajafff do you have a sample project where you expected/observed an improvement?

**Comment by ajafff** [comment]
@amcasey you're right. the performance is about the same.

I tested it with a naive recursive function that finds the deepest AST node at a given position:

```ts
function getAstNodeAtPosition(node: ts.Node, pos: number) {
    return (function recur(node: ts.Node) {
        if (node.pos > pos || node.end <= pos)
            return;
        return ts.forEachChild(node, recur) || node;
    })(node);
}

// vs

function getAstNodeAtPosition(node: ts.Node, pos: number) {
    if (node.pos > pos || node.end <= pos)
        return;
    return ts.forEachChild(node, getAstNodeAtPosition, undefined, pos) || node;
}
```

Running this function for every character in `checker.ts` (after a warmup) takes between 31 and 32 seconds for both implementations.
The runtime for the variant with the closure is not different before and after my change to `forEachChild`.

Since it doesn't bring the expected perf wins, I'll close this PR.

**Pull request closed without merging**
