### PR TITLE
Update lib types to mark Annex B as deprecated

### LINKED ISSUE #32191: escape() function not marked as deprecated in lib.es5.d.ts
**TypeScript Version:**  3.6.0-dev.20190701

**Search Terms:** escape, unescape, deprecated

**Code**

```ts
const text = escape('Does this need escaping?')
```

**Expected behavior:**
`escape` is marked as deprecated, as per MDN and w3schools documentation.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape
https://www.w3schools.com/jsref/jsref_escape.asp

**Actual behavior:**
`escape` is not marked as deprecated.

**Related Issues:** 
#18813 (closed), #8639 (not the same issue)

### LINKED ISSUE #43709: Mark properties defined in Annex B as deprecated
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `ES2020`.

## Missing / Incorrect Definition

No

## Sample Code

No

## Documentation Link

ES2022 (Draft) B.2 Additional ECMAScript Features for Web Browsers
https://tc39.es/ecma262/#sec-additional-ecmascript-features-for-web-browsers

> These features are not considered part of the core ECMAScript language. Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code. ECMAScript implementations are discouraged from implementing these features unless the implementation is part of a web browser or is required to run the same legacy ECMAScript code that web browsers encounter.

ES2022 (Draft) B.2 Additional Built-in Properties
https://tc39.es/ecma262/#sec-additional-built-in-properties

Related: #32191, #19299

### PR DESCRIPTION
**Pull request by petamoriken**
Fixes #43709
Fixes #32191

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
You probably have to update baselines.

If we do this, the first thing you'll see every time you request completions on a string is a bunch of crossed-out properties. @sandersn any idea how easy it would be to give them a lower sort order based on JSDoc tags?

**Comment by sandersn** [comment]
`@deprecated` has its own NodeFlags entry right now, so you just have to use the rules from the checker to decide if the signature as a whole should be considered deprecated (basically, whether all the signature's declarations are deprecated). I don't know the sort order code but I assume it would be easy.

**Comment by sandersn** [comment]
> If we do this, the first thing you'll see every time you request completions on a string is a bunch of crossed-out properties.

A quick grep of the baselines for `"big"` doesn't look like there's a test for this, so you should add one, something like

```ts
/// <reference path='fourslash.ts' />
//// var s = "foo"./*1*/
verify.baselineCompletions()
```

Which should make it obvious what order `"big"` et al have.

**Comment by DanielRosenwasser** [comment]
I think before this goes in, we need to add the sorting logic first. I'd like to discuss that at an upcoming editor sync with @mjbvz and others first.

**Comment by DanielRosenwasser** [comment]
#43796 tracks this.

**Comment by DanielRosenwasser** [comment]
CC @bterlson

**Comment by petamoriken** [comment]
@sandersn `verify.baselineCompletions` method is broken. Your code emits baseline as a global completion such that

```js
[
  {
    "marker": {
      "fileName": "/tests/cases/fourslash/completionsStringMethods.ts",
      "position": 6,
      "name": ""
    },
    "completionList": {
      "isGlobalCompletion": true,
      "isMemberCompletion": false,
      "isNewIdentifierLocation": false,
      "entries": [
        {
          "name": "globalThis",
          "kind": "module",
          "kindModifiers": "",
          "sortText": "5"
        },
        {
          "name": "eval",
          "kind": "function",
          "kindModifiers": "declare",
          "sortText": "5"
        },
        // ...,
      ]
    }
  }
}
```

I also found the following broken test.

https://github.com/microsoft/TypeScript/blob/a14b22718ab1bc7d395c981b0a8f95f4d6e361b6/tests/cases/fourslash/completionsJSDocTags.ts#L60-L62

https://github.com/microsoft/TypeScript/blob/a14b22718ab1bc7d395c981b0a8f95f4d6e361b6/tests/baselines/reference/completionsJSDocTags.baseline#L3-L11

**Comment by orta** [comment]
I'm a fan of this, and I think the sorting would make it shine 👍🏻

**Comment by orta** [comment]
Sorting PR: https://github.com/microsoft/TypeScript/pull/43880

**Comment by petamoriken** [comment]
Blocked by #45615

**Comment by petamoriken** [comment]
I found that `RegExp.$1` to `RegExp.$9` should also be deprecated.

**Comment by petamoriken** [comment]
This pull request can be reviewed. Thank you for your time.

**Review by orta — APPROVED** [review]
Looks good to me

**Pull request merged**
