### PR TITLE
Automatically enable `debugMode` when recording with Replay

### PR DESCRIPTION
**Pull request by Andarist**
I'm not sure if you have heard about Replay (https://www.replay.io/) and I will totally understand if you decide to reject this PR.

However, the cost is small and it would make my life way easier :p as I'm using Replay to debug TypeScript quite a bit lately. I also highly encourage anyone interested in trying it out as it makes diagnosing and exploring code much easier. For the context - it is a time travel debugger that actually works with arbitrary scripts 😉

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
It's a little annoying that we have to probe `process` like that. Is there any other signal?

**Comment by Andarist** [comment]
what kind of an automated signal could we probe? I mean - is there even any other way to accomplish this than to probe a global (either directly checking something on `process`, or similar, or `process.env`)? I think that the Replay team could be open to introducing something else - but I truly don't know what else can be used to signal this.

**Comment by RyanCavanaugh** [comment]
I was hoping for an environment variable 😅

**Comment by Andarist** [comment]
Is there any particular reason why you are more OK with env var than with a `process` property? For context - I originally asked them if there is any env var that could be used to detect this because that was intuitively what I was expecting to be exposed. That's how I've learned that there is this `process` property available.

So my intuition was kinda like yours - but I don't mind any of those ways to detect something. It seems that this global object (`process.recordreplay`) has some additional methods exposed on it (like you can get a predicted ID of the recording, the current "pause point" and stuff like that). So from their PoV, it makes sense that this is an object on the `process` as they wouldn't be able to expose methods using env vars alone. So exposing additional env var could be seen as somewhat redundant from their PoV here as this global object will exist anyway.

If you are strongly opposed to checking this global object then I can circle back to the Replay team and ask if there is any chance that they would add some env var but I wonder if that's truly necessary.

**Comment by Andarist** [comment]
@RyanCavanaugh any more thoughts on this one? If you think that it's not the right time for this kind of a thing and that we can revisit this in the future, when/if Replay gets more popular then I'm OK with closing this one.

**Comment by jakebailey** [comment]
I got pinged about this, so I'm taking a look. I personally don't see a problem with this, though I do think that it'd be nice to see some sort of documentation that implies that this is "the way" to detect Replay and that it's not going to disappear or change in the future.

**Comment by jakebailey** [comment]
I've been emailing the folks at Relay and while this is experimental and the docs aren't yet complete, it does seem like probing `process` is the thing to do.

That being said, I do wonder if we'd be better off defining:

```ts
declare global {
    namespace NodeJS {
        interface Process {
            recordreplay?: {
                currentPointURL?: (args: never) => void;
            }
        }
    }
}
```

In `sys.ts` then checking `typeof process.recordreplay?.currentPointURL === "function"`.

Or, maybe just `typeof (process as any).recordreplay?.currentPointURL === "function"`.

In any case, in lieu of official docs, I think this looks alright.

**Comment by jakebailey** [comment]
Realizing I misread and we could really just check `typeof (process as any).recordreplay !== "undefined"` or even `(process as any).recordreplay`.

**Comment by Andarist** [comment]
The `currentPointURL` check was just an extra bit of caution on my side - so this check wouldn't yield false positives. I think it's very unlikely that this would actually yield false positives even with a simplified check though. So I adjusted the condition as you suggested. I also chose the `as any` cast since with it the whole thing stays local to that one line of code.

**Review by jakebailey — APPROVED** [review]
This LGTM at this point, per conversation with Relay themselves.

**Pull request merged**
