### PR TITLE
fix(51301): Fixing an unused import at the end of a line removes the newline

### LINKED ISSUE #51301: Fixing an unused import at the end of a line removes the newline
Given this code, which roughly matches what the module-ified compiler will look like:

```ts
import {
    readFile, readFileSync, read, readSync,
    chmod, chmodSync,
} from "fs";


readFile;
readFileSync;
read;
// readSync;
chmod;
chmodSync;
```

Using the quick fix to remove the unused `readSync` leaves the code looking like this:

```ts
import {
    readFile, readFileSync, read, chmod, chmodSync,
} from "fs";


readFile;
readFileSync;
read;
// readSync;
chmod;
chmodSync;
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #51301

### CODE REVIEW

**Comment by jakebailey** [comment]
I think you're hitting exactly the problem I was when I tried to quick fix this 😅

**Comment by a-tarasyuk** [comment]
😇

**Comment by jakebailey** [comment]
I tried to fix this last night and you figured out that second hurdle (which is where I gave up). Nice!

This seems fine to me, but I have no idea what's good/bad for this part of the code.

**Comment by jakebailey** [comment]
FWIW this is a related case that I think is also this same bug:

```ts
function foo(
    a: number, b: number,
    c: number,
) {
    return a + c;
}
```

Removing `b` also behaves the same way. Should we be always preserving the newlines? Or are there cases where this turns out to matter?

**Review by jakebailey — APPROVED** [review]
This seems correct to me, but interested in what others think.

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
