### PR TITLE
Fix super/this capture for extends null

### LINKED ISSUE #13276: super/this capturing does not correctly handle `extends null`
We are not properly handling https://tc39.github.io/ecma262/#sec-runtime-semantics-classdefinitionevaluation with respect to `extends null` and our down-level constructor emit for ES5/3

This is easy to reproduce on [the playground](http://www.typescriptlang.org/play/index.html#src=class%20C%20extends%20null%20%7B%7D)

**TypeScript Version:**  2.1.1
**Code**
```ts
class C1 extends null { 
}
class C2 extends null {
  x = 1;
  constructor() { }
}
```

**Expected emit:**
```js
var C1 = (function (_super) {
    __extends(C, _super);
    function C1() {
      return _super !== null && _super.apply(this, arguments) || this;
    }
    return C1;
}(null));
var C2 = (function (_super) {
    __extends(C, _super);
    function C2() {
      var _this = this; // add default initializer
      _this.x = 1;
      return _this;
    }
    return C2;
}(null));
```

**Actual emit:**
```js
var C1 = (function (_super) {
    __extends(C1, _super);
    function C1() {
        return _super.apply(this, arguments) || this; // _super is null here
    }
    return C1;
}(null));
var C2 = (function (_super) {
    __extends(C2, _super);
    function C2() {
        var _this;
        _this.x = 1; // _this is undefined here
        return _this;
    }
    return C2;
}(null));
```

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #13276

### CODE REVIEW

**Comment by mhegazy** [comment]
We will need to port this to release-2.1 as well.

**Comment by DanielRosenwasser** [comment]
I would consider an additional check, which is that if the extends clause element is syntactically `null`, no capture should be performed at all.

**Comment by DanielRosenwasser** [comment]
Also, I'd consider just making it `_super &&` instead of `_super !== null &&`.

**Comment by rbuckton** [comment]
The spec is explicit about `null`. `undefined` should be an error/undefined behavior.

**Comment by mhegazy** [comment]
@rbuckton can you merge this and port it to release-2.1 as well.

**Comment by rbuckton** [comment]
Sure. I was just updating it based on Daniel's suggestion above.

**Comment by rbuckton** [comment]
I've merged this into release-2.1 as well.

**Pull request merged**
