### PR TITLE
Port Extract Method support for loose type parameters to release-2.5

### PR DESCRIPTION
**Pull request by amcasey**
I separated this from the raft of tiny bug fixes because it is larger and scarier.

### CODE REVIEW

**Comment by andy-ms** [comment]
Is there an original PR that this is a port of?

**Comment by amcasey** [comment]
@andy-ms This is a combination of three or so `master` PRs.  Let me know if you would like me to track them down.
One of the changes made an update to the extract method baseline generator, so all of the baselines had to be updated.

**Comment by amcasey** [comment]
My merge tool betrayed me and inserted tabs instead of spaces.

**Comment by andy-ms** [comment]
Yes please, especially the one introducing `symbolWalker`.

**Comment by mhegazy** [comment]
Do we need this fix in 2.5.3?

**Comment by amcasey** [comment]
@mhegazy I could be persuaded that it doesn't have to be in 2.5.3, but it would be nice to have and it would make merging the other fixes easier.

**Comment by amcasey** [comment]
@andy-ms It turns out that the PR numbers are in the individual commit names.

**Comment by amcasey** [comment]
I agree that this is not a patch-level fix.

**Pull request closed without merging**
