### PR TITLE
Change the type of window.orientation to number

### PR DESCRIPTION
**Pull request by zhengbli**
fix issue #3884

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Should it be `number` or `string | number`?

**Comment by zhengbli** [comment]
I didn't find anywhere except the IE spec that defines ``window.orientation`` as string, it seems that in most cases (iOS, Android) it is used as number. But I agree that as it is an unstable property, it might be better to use ``string | number``

**Comment by chocolatechipui** [comment]
I can confirm setting the value to ```string | number``` allows my orientation checks to compile without errors. Thank you. My problem now has nothing to do with you guys but with the Visual Studio Code team, who have their own lib.d.ts, etc. as resources in the app package instead of using TypeScript's versions. Atom seems fine. I'm just casting the orientation numbers to ```<any>``` for now until TypeScript 1.6 and VSCode 0.6 are released.
Finally, I'd like to say thank you for all the hard work you guys are putting in to making TypeScript so awesome. I absolutely love TypeScript :+1:

**Comment by DanielRosenwasser** [comment]
:+1: 

@chocolatechipui for the record, you can change your user settings in VS Code and set `"typescript.tsdk"` to a custom location. If you install our nightly (`npm install -g typescript@next`), you can point to that version of TypeScript's `bin` folder.

**Comment by mhegazy** [comment]
:+1:

**Comment by chocolatechipui** [comment]
@DanielRosenwasser Thanks. That tip for VSCode made my day :100:

**Pull request merged**
