### PR TITLE
Expand isEmptyIntersectionType to check for objects with mutually exclusive property types

### PR DESCRIPTION
**Pull request by weswigham**

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot run dt let's see if this breaks the world or not

**Comment by weswigham** [comment]
@typescript-bot run dt x6

**Comment by weswigham** [comment]
@typescript-bot run dt faster

**Comment by weswigham** [comment]
@typescript-bot run dt faster but again and with more gusto

**Comment by weswigham** [comment]
@typescript-bot run dt faster but again and with more gusto

**Comment by weswigham** [comment]
@typescript-bot run dt faster but again and with more gusto

**Comment by weswigham** [comment]
@typescript-bot run dt faster but again and with more gusto

**Comment by weswigham** [comment]
@typescript-bot run dt faster but again and with more gusto

**Comment by jack-williams** [comment]
> run dt faster but again and with more gusto

gif

**Comment by weswigham** [comment]
Hey, it ran the DT suite in 33 minutes, I think that's faster and with more gusto.

**Comment by weswigham** [comment]
We're now doing a rudimentary form of this using `getReducedType`. As such, It might be relevant to iport the type variable constraint checking logic (`checkForUnsatisfiedTypeVariableConstraint`) from this draft to `getReducedType` in `master` now. @ahejlsberg ? If I remember correctly, the motivation was so that `T & number` where `T extends string` becomes `never`, the (beneficial) effects of which you can see [here](https://github.com/microsoft/TypeScript/pull/30476/files#diff-c1801f8c0b8a4dcbdce0d3372cf2c22a).

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this draft PR. It's pretty old.

**Pull request closed without merging**
