### PR TITLE
Added support for the pipeline operator `|>`

### PR DESCRIPTION
**Pull request by SuperPaintman**
Greetings!

I have added support for the pipeline operator `|>`.

Since it's still on the `stage 1`, I made the `experimentalPipelineOperator` option for it

Also, I added several unit tests for different use cases (chaining / currying / async/await / arrow functions).

**Issue**: #17718
**Proposal repo** (Stage 1): https://github.com/tc39/proposal-pipeline-operator
**First presentation**: https://github.com/tc39/agendas/blob/master/2017/09.md
**Babel's implementation**: https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-pipeline-operator

## Usage

```ts
const doubleSay = (str: string) => `${str}, ${str}`;
const capitalize = (str: string) => str[0].toUpperCase() + str.substring(1);
const exclaim = (str: string) => str + '!';

const result = "hello"
  |> doubleSay
  |> capitalize
  |> exclaim;

console.log(result); // "Hello, hello!"
```

```ts
interface Newable {
  new (...args: any[]): any;
}

class Model {
  show() { }
}
const Editable = <T extends Newable>(superclass: T) => class extends superclass {
  edit() { }
};
const Sharable = <T extends Newable>(superclass: T) => class extends superclass {
  share() { }
};

class Comment extends (Model |> Editable |> Sharable) {
  comment() { }
}

const comment = new Comment();
comment.show(); // ok
comment.share(); // ok
comment.edit(); // ok
comment.comment(); // ok
```

### [ ] Arrow functions optimization

At the moment, arrow function translates in this way:

```ts
// test.ts
const result = 1337
  |> ((_: number) => _ * 8)
  |> ((_: number) => _ + '!!!');


// test.js
var result =
    (_ref_1 = (_ref_2 = 1337, (function(_) { return _ * 8; })(_ref_2)),
     (function(_) { return _ + '!!!'; })(_ref_1));
var _ref_1, _ref_2;
```

and it isn't the best way to transform "dummy" arrow functions. For example
we would extract the body from the arrow function, like this ([babel way](https://github.com/babel/babel/blob/master/packages/babel-plugin-proposal-pipeline-operator/src/index.js#L52)):

```js
var result = (_ref_1 = (_ref_2 = 1337, _ref_2 * 8), _ref_1 + '!!!');
var _ref_1, _ref_2;
```

unfortunately, I didn't find how to rename function's parameter node, like
babel's: `path.get("right").scope.rename(param.name, placeholder.name);`;

### [ ] Type inference for the first parameter (in arrow function)

So, at the moment we must explicitly specify the parameter's type:

```ts
const result = "hello"
  |> (_: string) => _ + _;
//       ^^^^^^
```

but I'm totally sure that we can get rid of it, I just didn't find how to propagate
type of the left operand to the parameter.

### [ ] Unit tests

I added a few `cases/compiler`'s unit test, but I'm not sure if that enough.

## Screenshots:

<details>
  <summary>OPEN ME!</summary>

image

image

image

image

image

image

</details>

--------

CC: @graingert, @AlexGalays, @aluanhaddad, @tycho01, @ddimaria, @AbubakerB

### CODE REVIEW

**Comment by SuperPaintman** [comment]
Is it my fault? > https://circleci.com/gh/Microsoft/TypeScript/1350?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by RyanCavanaugh** [comment]
We don't accept PRs for Stage 1 features. The pipeline operator is still very much in flux and there are a lot of open questions on even its basic syntax.

I can leave this open if you want to try to get the CI to pass, but we won't be merging this until the TC39 proposal gets much further along.

**Comment by DanielRosenwasser** [comment]
I also want to say that while the work here is appreciated and I share your enthusiasm for pipeline, I believe @rbuckton already has an (albeit on a slightly out of date branch) working implementation of the pipeline operator, so even if we have this around long enough, I can't guarantee it'll be merged in.

**Comment by mAAdhaTTah** [comment]
> But I pretty sure that current spec will remain as is because Babel and FireFox 58 already have implemented it.

We're debating three proposals currently, each with their own, potentially-incompatible, semantics. Be careful making this assumption about any proposal < Stage 3 or 4; pipeline is only Stage 1 at this point and will definitely undergoing major changes before it lands. If you want to get involved in that process, the proposal is here: https://github.com/tc39/proposal-pipeline-operator/ We'd love your feedback.

Not to sound harsh, but if you're pushing unspec'd code into production expecting it's going to land in the language the way it's currently designed, you're going to have a bad time.

**Comment by mhegazy** [comment]
> But I pretty sure that current spec will remain as is 

I do not think this is the case. Stages < 3 proposals are by definition going to change significantly, specially something as involved as pipeline. Precedence for this are class and module proposals, changed syntax and semantics a few times, and more recently the decorator proposal, stage 2 proposal is fundamentally different than that at stage 1.

> because Babel and FireFox 58 already have implemented it.

That is not the case either. implementors do change their implementations to match the spec, and not the other way around. Precedence fro this is const/let binding semantics, class inheritance semantics and map and set APIs were different in different engines, but all ended up implementing the standard once ratified.

The whole issue here is if we take a stage < 3 feature we are committing to break users when the committee changes the design. we have found that the cost of doing so to the community is higher than the value of a pre-stage 3 feature early release provides.  

> but could we leave this PR until "|>" becomes a Stage 3? 

we could, but that can be a long time. the PR will become stale fairly quickly. Once the feature reaches stage 3, we would be happy to accept your PR. but until then, closing this seems like the best option. thanks.

**Comment by lozandier** [comment]
@mhegazy @RyanCavanaugh  No objections to this being closed, but isn't it valid to be a experimental flag once pipeline operator(s) become a stage 2 proposal? 

That was done for decorators (`experimentalDecorators: true` in `tsconfig.json` files), so it seems confusing to me that @SuperPaintman &/or @rbuckton PRs (& future PRs related to this) wouldn't be considered until it's a stage 3 proposal.

Is that a policy enforced as a hard lesson learned from previously implementing stage 2 proposals other than decorators in TypeScript to the dismay of the community?

**Comment by mhegazy** [comment]
We have experimented with experimental flags in decorators; we have found that having the feature under a flag does not change the maintance liabilities nor does it ease the breaking changes effects. We have thus adopted a policy of waiting on standards-track features to reach stage 3 before adding them to the language.

**Pull request closed without merging**
