### PR TITLE
[Bot test] Relax the protocol (2)

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by cliffkoh** [comment]
test

**Comment by DanielRosenwasser** [comment]
test?

**Comment by amcasey** [comment]
Is there a way to add a blocking check that can be cleared with an assertion?  E.g. a way to block merging until you check a box saying "I've tested this with an old editor".

**Comment by DanielRosenwasser** [comment]
I think we just want to raise awareness in general. It's mostly for people on our team anyway.

**Pull request closed without merging**
