### PR TITLE
Revert "Revert #37106"

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Reverts microsoft/TypeScript#38172

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Chatted with @sandersn - it sounds like per discussion in https://github.com/microsoft/TypeScript/issues/38168, we need some special exemption for `globalThis`. We can merge and then have a follow-up issue, or we can have someone build on this branch.

**Comment by weswigham** [comment]
@sandersn is this waiting on work form you or @DanielRosenwasser ? I don't think there's much for me to review here right now (that I didn't already look over once when it was first merged before being reverted for want of less breakiness).

**Comment by DanielRosenwasser** [comment]
Might as well add a new PR, but worth reinvestigating if @sandersn remembers anything special that we need to re-introduce

**Comment by weswigham** [comment]
I think https://github.com/microsoft/TypeScript/pull/39637 superceded this.

**Pull request closed without merging**
