### PR TITLE
Fix equality narrowing with any

### LINKED ISSUE #10869: Long compilation time for complex narrwoing conditions.
Reported originally by @robwormald

Repro attached.

[app.ngfactory.txt](https://github.com/Microsoft/TypeScript/files/468189/app.ngfactory.txt)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #10869.

### CODE REVIEW

**Comment by mhegazy** [comment]
👍

**Comment by DanielRosenwasser** [comment]
If the tests had all used `instanceof` instead of equality, wouldn't you have the same problem?

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Probably. This is a targeted fix to unblock the Angular folks. In general we should also look to improve our caching strategy in the control flow analyzer to better handle very long chains of narrowing operations. But that'll be post-2.0.

**Comment by mhegazy** [comment]
ported to release-2.0 in https://github.com/Microsoft/TypeScript/commit/81c69b2a58a41d832ef3d0e825829bfe30968ebe

**Pull request merged**
