### PR TITLE
Propagate `intersectionState` in `typeRelatedToSomeType`

### LINKED ISSUE #53412: [5.0] Intersected array of intersection types with union field not compatible
# Bug Report

Basically I'm using `&` types as if subclassing. `BaseValue` has `items` array with fewer properties, `ExtendedValue` extends that with `items` with more properties.

### 🔎 Search Terms

intersection, ampersand, override, inheritance. Also looked at the titles of first 2 pages of open issues.

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.2
- There is an easy work-around, but I'm not sure if it should be necessary.

### ⏯ Playground Link

[TypeScript 5.0.2 (error)](https://www.typescriptlang.org/play?ts=5.0.2#code/C4TwDgpgBAQghgZwgSWBAtlAvFA3gWACgooBLAEwC4oA7AV3QCMIAnAbiIF8jRIoBRAB5oa5COVQZssRCjSYAZHiIkxCAMYtSYYKQD2NagmBaaAcygAfWnQA2trh0JEe4aPCQA1OLbrQcBMRQAPTBUMAAFqzQcCzQepGsUABmpBC25AgqZPII1B5yGADaALpO3IS80EIiYuTevv4yXj5+UEqBJKHhUXFQsfGJLClpGVlBpLnUNRCi4pLopeUuzoTqBsZQACr8AMpbAPqeAIIAMgCq-NPCs3UNbQHZkxh5UEVdYVsRpAhkvwByAHktv17HoAO7iKAAKlIyWS0Kg6FIgihVV+AygdCQ5DINCgAAM1JptLoDATsiRcBRqABGAA0UGJWh0+kMNnsnHplLwNKgACZGczSWzqABycGkMxmWwgYB0RiMWwQMVc7IlRwrbowOjAMjJQnC1nkqARRBYmhwvQsTDoxmJfGTP5QQEAaUoRHWNE2gP+pwAmgd9gAlZD-ADiu2utXE9yanRyL2oRR51KoUAZTIgGhZZPZYsYensIHBemlytV3KCVL5gqzOZFBnFkvLcoVSpVaqCGsInCcXp9fsD-3Op1OUYENzm9Va8aeUzeqb5maNeeo9E5VZINfTddXoo5ti7JB7faIQA) vs [4.9.5 (OK)](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBAQghgZwgSWBAtlAvFA3gWACgooBLAEwC4oA7AV3QCMIAnAbiIF8jRIoBRAB5oa5COVQZssRCjSYAZHiIkxCAMYtSYYKQD2NagmBaaAcygAfWnQA2trh0JEe4aPCQA1OLbrQcBMRQAPTBUMAAFqzQcCzQepGsUABmpBC25AgqZPII1B5yGADaALpO3IS80EIiYuTevv4yXj5+UEqBJKHhUXFQsfGJLClpGVlBpLnUNRCi4pLopeUuzoTqBsZQACr8AMpbAPqeAIIAMgCq-NPCs3UNbQHZkxh5UEVdYVsRpAhkvwByAHktv17HoAO7iKAAKlIyWS0Kg6FIgihVV+AygdCQ5DINCgAAM1JptLoDATsiRcBRqABGAA0UGJWh0+kMNnsnHplLwNKgACZGczSWzqABycGkMxmWwgYB0RiMWwQMVc7IlRwrbowOjAMjJQnC1nkqARRBYmhwvQsTDoxmJfGTP5QQEAaUoRHWNE2gP+pwAmgd9gAlZD-ADiu2utXE9yanRyL2oRR51KoUAZTIgGhZZPZYsYensIHBemlytV3KCVL5gqzOZFBnFkvLcoVSpVaqCGsInCcXp9fsD-3Op1OUYENzm9Va8aeUzeqb5maNeeo9E5VZINfTddXoo5ti7JB7faIQA)

### 💻 Code

```ts repro
type BaseItem = {
  id: number;
}
type ExtendedItem = BaseItem & {
  description: string | null
};


type BaseValue = {
  // there are other fields
  items: BaseItem[];
}
type ExtendedValue = BaseValue & {
  // there are other fields
  items: ExtendedItem[];
}


const TEST_VALUE: ExtendedValue = {
  items: [  // ❌ ERROR: This is NOT allowed *iff* mixed types are used in `description`
    {id: 1, description: null},
    {id: 2, description: 'wigglytubble'},
  ]
};
```

### 🙁 Actual behavior

Seems to me like they should be compatible. Also these examples are ✅ allowed in TS 5.0.2 if `description` only has uniform types, e.g.:

```ts
// ✅ Allowed: description has only strings
const ONLY_STRINGS: ExtendedValue = {
  items: [
    {id: 1, description: 'bollywoggle'},
    {id: 2, description: 'wigglytubble'},
  ]
};
// ✅ Allowed: description has only nulls
const ONLY_NULLS: ExtendedValue = {
  items: [
    {id: 1, description: null},
    {id: 2, description: null},
  ]
};
```

### 🙂 Expected behavior

Seems like it should be allowed.

### 🙄 Work-around

Typing `ExtendedValue` with `Omit<>` seems to fix the issue with no obvious downsides.

```ts
type ExtendedValue = Omit<BaseValue, 'items'> & {
  // there are other fields
  items: ExtendedItem[];
}
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53412.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by SimpleCreations** [comment]
I wonder if this PR fixes #55666 which was also bisected to #52392 👀

**Comment by ahejlsberg** [comment]
> I wonder if this PR fixes https://github.com/microsoft/TypeScript/issues/55666 which was also bisected to https://github.com/microsoft/TypeScript/pull/52392 👀

Unfortunately, it does not.

**Comment by jakebailey** [comment]
At this point, I wonder if we should just make `intersectionState` a required parameter just to be sure that it's propagated everywhere. I actually just tried that out locally and it didn't break any tests (which, makes sense as this PR only added tests).

**Comment by ahejlsberg** [comment]
> At this point, I wonder if we should just make intersectionState a required parameter just to be sure that it's propagated everywhere

Not sure that would help. There are plenty of cases where we don't want to propagate it, so we'd just have to add a bunch of `IntersectionState.None` parameters. Plus there are three optional parameters preceding it that would also have to be added.

**Comment by ahejlsberg** [comment]
Tests and performance look good. I think this one can be merged.

**Comment by jakebailey** [comment]
> > At this point, I wonder if we should just make intersectionState a required parameter just to be sure that it's propagated everywhere
> 
> Not sure that would help. There are plenty of cases where we don't want to propagate it, so we'd just have to add a bunch of `IntersectionState.None` arguments. Plus there are three optional parameters preceding it for which arguments would also have to be added.

https://github.com/microsoft/TypeScript/compare/main...jakebailey:TypeScript:required-intersection-state has the change (which did require moving it up, of course); there are quite a few places that it's not propagated and I didn't hit any places where I needed to add `.None` besides the very top of the stack.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
