### PR TITLE
Visit default export expressions in module visitor

### LINKED ISSUE #18968: Dynamic import not correctly in export assignments
From https://github.com/Microsoft/TypeScript/issues/17060#issuecomment-334372691

This is still an issue when the dynamic import is used when exporting a default object:
```js
export default {
    getInstance: function () {
        return import('./foo2');
    }
}
```
transpiles to 
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    getInstance: function () {
        return import('./foo2');
    }
};
```
whereas naming the export it works:
```js
export let defaultExport = {
    getInstance: function () {
        return import('./foo2');
    }
}

// transpiles to

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultExport = {
    getInstance: function () {
        return Promise.resolve().then(function () { return require('.foo2'); });
    }
};
```

**typescript version:** 2.5.3

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #18968

### CODE REVIEW

**Comment by mhegazy** [comment]
Can you do an audit on this file, and make sure we are transpiling imports in all places, this is the third issue we have had to deal with regarding this.

**Comment by weswigham** [comment]
@mhegazy I just grep'd the file for all `node.` instances, I found one more obvious issue involving nested imports (`await import(await import("foo"))`, opened #18982 - issue seems to actually be with the generator transform, but it may compound with the module transform), and then by chance also found #18981. Besides those, at this point it _looks_ like all remaining node references in the `module` transformer are either leaf nodes (modifiers, operators), or get visited.

**Comment by weswigham** [comment]
Also, @mhegazy does this need to be ported to the 2.6 branch?

**Comment by DanielRosenwasser** [comment]
@weswigham yup, it'll just go after the RC.

**Comment by weswigham** [comment]
Got it, won't port anything explicitly until then, then.

**Pull request merged**
