### PR TITLE
Make `hasCorrectArity` handle tuples properly

### LINKED ISSUE #32835: Error when use spread arguments twice
**TypeScript Version:** 3.5.1

**Search Terms:**

**Code**

```ts
declare function fn (a: string, b: string, ...c: string[]): void
declare const foo: [string, string, ...string[]]
declare const bar: string[]
fn(...foo) // ok
fn(...foo, ...bar) // error
fn(...foo, ...foo) // error
fn(...bar, ...foo) // error
```

**Expected behavior:**

No errors

**Actual behavior:**

```
Expected at least 2 arguments, but got 1 or more
```

**Playground Link:** [link](https://www.typescriptlang.org/play/?noImplicitThis=false#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVPwAooAueAZwxi1QHMAaeAIzMursYDpuxWqbaAbQC6ASjIA3HFmAAoUJFgIweSkhw4ygtgMY6O8bp31Dhw+eGhx4K1Gqaw+7U7MSpCRxBtHwA9L-gcAGtXd08NLm4HGB9-eBAYGBwYUI9uLxxIzgzYgISklLc0zmisnL88xOSgA)

**Related Issues:**

### PR DESCRIPTION
**Pull request by elibarzilay**
This completes the work that started in PR #33069, and fixes #32835.
(Includes that PR in a separate commit.)

There are probably two additional related changes that are needed to
make this more complete:

* Fix the code that composes the error message (see the first two
  `FIXME`s in `callWithSpread3.ts`).

* Fix the code that checks the argument types (second two `FIXME`s).

* There is also an error in `genericRestParameters1.ts` which changed
  but should not be an error in the first place.  Added a `FIXME` there
  too.  (Probably will work if the previous iterm is done.)

In addition, `getEffectiveCallArguments` munges the arguments in case of
a spread in the last argument which might be better to avoid.  (I think
that there are cases where it wouldn't work anyway, such as a spread of
an array followed by a spread of an empty array.)

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by elibarzilay** [comment]
(After this is merged, there should be two new issues for the `FIXME`s in the test, one for the bad error message on a bad arity, and one for checking the argument types.)

**Comment by sandersn** [comment]
I just looked at the user test failures and there's nothing new there.

**Comment by sandersn** [comment]
Nothing in the RWC failures either.

**Pull request merged**
