### PR TITLE
Move anonymous type instantiation cache from AST node to root type

### LINKED ISSUE #40995: typescript generic break filter after spreading object in map
**TypeScript Version:**  any, including 4.0.2 and v4.1.0-dev.20201008

**Search Terms:** typescript generic break filter after spreading object in map? O_o

**Code**

```ts
interface Success {
    isSuccess: true;
}

interface Fail {
    isSuccess: false;
}

type Item =
    | Success
    | Fail

// ok
function foo(a: Array<Item>): void {
    a
        .map((item) => ({...item}))
        .filter((value) => {
            console.log(value);
        });
}

// error
function bar<T extends any>(a: Array<Item>): void {
    a
        .map((item) => ({...item}))
        .filter((value) => {
            console.log(value);
        });
}
```

**Expected behavior:**

adding generic to function does not break the code

**Actual behavior:**

`.filter((value) => {` after `.map((item) => ({...item}))` when it inside function with generic trigger error.

**Playground Link:** https://www.typescriptlang.org/play?ts=4.0.2#code/JYOwLgpgTgZghgYwgAgMoFcFIM7eQbwChkTlhsMsJcAuZMKdCAbkIF9DDRJZEUAxOMAA2BYqXKUc2OvGHYW7TmACeABxQBJSAFtkAXnEkAPmkzSjyU4JGcA9HeQB7ANaEY6EAjDAnIZDBOTgAUcHQAglBQcCoAPNoQOgB8AJR0AG5OwAAmYqTIcJb5AHQ6cGrBwcC6KQZJyMH4xc3ViWwpKUWkxTAiPJXpcMJMtfr1RPmTpAh+2E7CEMXCTgDmwYPDECnMyA7IG0x0CTpdJO2sHIR70FBOUO6e3r7+AEZwULEAKsgQAB6QIGyeDgIBUSVCESiMXiulSGSyuQmpEKUxIpXKlVaOlG9UazWKWPanVRyB6fWgAyGIzqeRJ01m80WyzWBy2Oz2AH4OadkOclEA

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #40995.

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
Hmm, the performance here looks a little worse than #41003 on material-ui and monaco, but that makes me wonder if there were previously more _incorrect_ instantiations in material-ui that just went unnoticed 🤔. The difference is almost within the margin of error, so maybe not too bad...

**Comment by ahejlsberg** [comment]
It's possible the slowdown is just a result of reduced monomorphism in object layouts, but the numbers are higher enough that likely there are more type objects being allocated. Would be interesting to know where those extra allocations are coming from. I have a sense it isn't just spreads in object literals.

**Comment by andrewbranch** [comment]
I'll see if I can find out—in my first attempts I had some code that used the cache both the old way and the new way and hit a `debugger` statement any time the results differed. I'll bring that back and see what I can find.

**Comment by ahejlsberg** [comment]
I think I see what's causing the slowdown. The changes aren't quite right for deferred type references, we need to obtain the "root" deferred type reference (the one produced by `getTypeFromTypeNode`) and then store the cache there. As it currently stands the caching is spread out over multiple type objects when we're doing instantiations of instantiations. In material-ui this causes the type count to increase from 159.5K to 165K. I'll put up a fix shortly.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
Much better. Looks like we're now in the margin of error.

**Comment by ahejlsberg** [comment]
BTW, I have manually verified that this PR now doesn't affect the number of types created when compiling `material-ui`.

**Review by andrewbranch — APPROVED** [review]
Added the test case from #41003. Thanks for the help!

**Pull request merged**
