### PR TITLE
Add --indentStyle in the compile options

### PR DESCRIPTION
**Pull request by lucasmciruzzi**
With this option the developer will have the option to select one of three options:

- spaces4: Four spaces (default)
- spaces2: Two spaces
- tabs: Tabs.

This will work with the format in the tsserver, and in the compiler. This also solves issues like #2306

### CODE REVIEW

**Comment by mhegazy** [comment]
thanks @lucasmciruzzi for the pull request. Formatting output JavaScript is not something we see useful, it adds complexity and new compiler options for close to no value to customers; specially that there are other formatting parameters, like where to place curlies, spaces before parens, new lines withing function bodies.. We advice customers to use JavaScript code beautifiers if this is something they care about.

Supporting tabs in formatting is something different though. This adds value to customers looking to keep tabs in there TS code. For this we would be happy to accept PRs.

**Comment by lucasmciruzzi** [comment]
@mhegazy the parameter is optional, and the default is the same that is already implemented. Besides the main problem is not with the output, is with the formater in the tsserver. Plugins like this one: https://github.com/Microsoft/TypeScript-Sublime-Plugin don't let the users set the indentation because the server itself doesn't support this option. The formater ends up being an annoyance instead of a tool if it alters my code style while I'm writing it. Even that, or an option to disable the formater in the ts files when I'm running the tsserver. I (and I think, anyone in my position) prefer to don't have a formater, to have one that "uglify" my code.

**Comment by mhegazy** [comment]
@lucasmciruzzi, i agree we need to fix the formatting for the server. your change does not do that however. Your change is to the command line compiler to change the emitted JavaScript formatting. usually users do not look at formatting for the output JavaScript. 

The original issue was about formatting *TypeScript* files in editor (i.e. the language service) and not the formatting of *JavaScript* files generated by the command line compiler.

The server, language service and sublime text plugin are a different code path:

The server entry point that triggers the formatting is at: https://github.com/Microsoft/TypeScript/blob/master/src/server/session.ts#L464

This in terns calls the language service getFormattingEditsForRange routine in:
https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L6165

The options you want to change to support tabs would be the EditorOptions defined in : https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1090
you would want to add something like "ConvertTabsToSpaces" but make it "ConvertSpacesToTabs".

Changing the formatter to handle tabs correctly is a desired change. It allows sublime text plugin as well as other plugins to handle tabs in TypeScript files correctly. We would be happy to accept a PR to fix that. I would be more than happy to help answer any questions related to the formatting code.

**Comment by lucasmciruzzi** [comment]
I apologize, I thought that all the formatting used the same code. I'll check out the code you've linked and if I think in some good options to solve this, I'll be doing a new pull request.

Thanks!

**Comment by mhegazy** [comment]
Thanks @lucasmciruzzi. Please feel free to ping me if you have any questions.

**Pull request closed without merging**
