### PR TITLE
Don't run linter after tests runs

### PR DESCRIPTION
**Pull request by jakebailey**
From everything I've heard from the team, everyone either hits Ctrl+C once the tests pass, or explicitly passes `--lint=false`. Remove the post-test task that runs linting; in a previous PR I moved linting to a separate CI job, so failing to fix a lint won't break a PRs tests (and will fail fast otherwise).

### CODE REVIEW

**Comment by jakebailey** [comment]
I'm going to split this PR in two; the cleanups can be unrelated to not running the linter and I have noticed other eslint problems to fix in the meantime.

**Review by andrewbranch — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by jakebailey** [comment]
Coming back to this over the weekend, I think what I should actually do is default `lint` to false, and leave the code in place, so people can still pass `--lint=true` if they desire. Thoughts?

**Comment by sandersn** [comment]
I think you can build that yourself from `gulp runtests && gulp lint` if you want. (or the `npm run` equivalents)

**Comment by jakebailey** [comment]
Ah, duh, of course.

**Pull request merged**
