### PR TITLE
[Transforms] Revert to old emit for metadata. 

### LINKED ISSUE #7878: [Transforms] Decorator meta data property names, and shape have changed
As discussed offline, we should limit the breaking change for this iteration, and include these changes later on.

**Expected**:

```js
MyClass = __decorate([
    someDecorator, 
    __metadata('design:paramtypes', [db_1.default])
], MyClass);
exports.MyClass = MyClass;
```

**Actual**:

```js
MyClass = __decorate([
    someDecorator,
    __metadata("design:typeinfo", {
        paramTypes: function () { return [db_1.default]; }
    })
], MyClass);
```

Failed tests:
* tests\cases\compiler\decoratorMetadataWithImportDeclarationNameCollision6.ts

### PR DESCRIPTION
**Pull request by rbuckton**
Also adds baselines support for transpiler tests.

Fixes #7878.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Is this because we just want an easier time to compare baselines?

**Comment by mhegazy** [comment]
:+1:

**Comment by vladima** [comment]
:+1:

**Comment by rbuckton** [comment]
@DanielRosenwasser I discussed this with @mhegazy offline and he recommended we don't take this emit change until after the decorators proposal for ES6 has progressed further.

**Pull request merged**
