### PR TITLE
Issue repro: different vscode order in completion entries

### PR DESCRIPTION
**Pull request by gabritto**
Demonstration that completion entries appear in vscode in an order different than the order in which tsserver sent them, given that their score and sortText is the same.

Code to complete:
```ts
interface IFoo {
    bar(x: number): void;
    foo(y: string): string;
}

const obj: IFoo = {
    |
}
```
Order of entries in the tsserver logs:
- non-snippet `bar`
- snippet `bar`
- non-snippet `foo`
- snippet `foo`
JSON:
```json
"entries": [
        {
            "name": "bar",
            "kind": "method",
            "kindModifiers": "",
            "sortText": "11"
        },
        {
            "name": "bar",
            "kind": "method",
            "kindModifiers": "",
            "sortText": "11",
            "insertText": "bar(x: number): void {\r\n    $0\r\n},",
            "isSnippet": true,
            "source": "ObjectLiteralMethodSnippet/",
            "sourceDisplay": [
                {
                    "text": "bar",
                    "kind": "text"
                },
                {
                    "text": "(",
                    "kind": "punctuation"
                },
                {
                    "text": "x",
                    "kind": "parameterName"
                },
                {
                    "text": ":",
                    "kind": "punctuation"
                },
                {
                    "text": " ",
                    "kind": "space"
                },
                {
                    "text": "number",
                    "kind": "keyword"
                },
                {
                    "text": ")",
                    "kind": "punctuation"
                },
                {
                    "text": ":",
                    "kind": "punctuation"
                },
                {
                    "text": " ",
                    "kind": "space"
                },
                {
                    "text": "void",
                    "kind": "keyword"
                }
            ]
        },
        {
            "name": "foo",
            "kind": "method",
            "kindModifiers": "",
            "sortText": "11"
        },
        {
            "name": "foo",
            "kind": "method",
            "kindModifiers": "",
            "sortText": "11",
            "insertText": "foo(y: string): string {\r\n    $0\r\n},",
            "isSnippet": true,
            "source": "ObjectLiteralMethodSnippet/",
            "sourceDisplay": [
                {
                    "text": "foo",
                    "kind": "text"
                },
                {
                    "text": "(",
                    "kind": "punctuation"
                },
                {
                    "text": "y",
                    "kind": "parameterName"
                },
                {
                    "text": ":",
                    "kind": "punctuation"
                },
                {
                    "text": " ",
                    "kind": "space"
                },
                {
                    "text": "string",
                    "kind": "keyword"
                },
                {
                    "text": ")",
                    "kind": "punctuation"
                },
                {
                    "text": ":",
                    "kind": "punctuation"
                },
                {
                    "text": " ",
                    "kind": "space"
                },
                {
                    "text": "string",
                    "kind": "keyword"
                }
            ]
```
Order that vscode shows:
- snippet `bar`
- snippet `foo`
- non-snippet `bar`
- non-snippet `foo`

image

The entries all have the same score (-100) and same sortText ("11").
The snippet entries that appear first, however, have `insertText`, `sourceDisplay`, `source`, and `isSnippet` set, while the non-snippet ones do not have those fields.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot pack this

**Comment by mjbvz** [comment]
@jrieken Can you please help out with these questions? I'm not familiar enough with suggestion sorting to know what is going on here and if it's expected or not

**Comment by jrieken** [comment]
@gabritto What's the value of this setting `editor.snippetSuggestions`

**Comment by jrieken** [comment]
Oh, wait these aren't snippet of completion item kind `Snippet`, right? It is just using snippet strings?

**Comment by jrieken** [comment]
When you toggle explain mode (cmd+? while suggestion shows) what does that `index` read? If all scores are equals than that should be the effective sort order

**Comment by gabritto** [comment]
> Oh, wait these aren't snippets in the sense of `CompletionItemKind.Snippet`, right? It is just using snippet strings?

Yes, they're just using snippet strings (in `insertText`).

> When you toggle explain mode (cmd+? while suggestion shows) what does that index read? If all scores are equals than that should be the effective sort order

The indexes are 0 through 3, corresponding to the order of the completion entry. But where does that index come from? Does vscode compute it based on something? The text on the explain mode just says 'index: 0, based on sortText: "11"', but the sortText is the same, so it's hard to tell where the difference in the indexes is coming from.

To make it more clear what the problem is, we thought that if the score and sortText were equal for two entries, they would show up in vscode in the order in which they are sent from tsserver, and that is not the case.

**Comment by jrieken** [comment]
> To make it more clear what the problem is, we thought that if the score and sortText were equal for two entries, they would show up in vscode in the order in which they are sent from tsserver, and that is not the case

Yes, that's not the case. With equal sortText values we use the [label and kind](https://github.com/microsoft/vscode/blob/ffaae86a23eb601052c4c53be34d36fd73a356ca/src/vs/editor/contrib/suggest/browser/suggest.ts#L309) to find a difference between two items. We do this because the norm is that multiple extensions/providers contribute completions. We therefore need to establish one "global" order of all these results.

**Pull request closed without merging**
