### PR TITLE
Add @ts-ignore-enable @ts-ignore-disable

### LINKED ISSUE #19573: @ts-ignore for the block scope
currently @ts-ignore only mutes the errors from the line immediately below it

would be great to have the same for the whole next block

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #19573

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
0. Does user really need this function?
1. Should TS provide this function?
2. `@ts-ignore-enable` or `@ts-ignore-start` or something else, which name is more proper?
3. for now, `@ts-expect-error` would not work if it is in the region.

**Review by sandersn — CHANGES_REQUESTED** [review]
I think the reasons that @weswigham for *not* doing this are pretty good. I'm voting no unless we change our minds on the original bug.

**Comment by ShuiRuTian** [comment]
Yep, I strongly agree.

I give this PR because one comment is really interesting. https://github.com/microsoft/TypeScript/issues/19573#issuecomment-679370615

And maybe this PR could let community try giving more persuasive reasons, rather than just asking for it again and again.

**Comment by MathiasKandelborg** [comment]
I would like to reiterate [my comment](https://github.com/microsoft/TypeScript/issues/19573#issuecomment-674530042), that hasn't gotten a response from the team.

**Comment by kumar303** [comment]
In support of this PR (thank you), I'd like to mention that it's currently impossible to [selectively ignore styled-components errors](https://github.com/microsoft/TypeScript/issues/19573#issuecomment-695044678) since they are within template strings. This approach of `@ts-ignore-enable` + `@ts-ignore-disable` probably makes that possible but I did not confirm it.

**Comment by ShuiRuTian** [comment]
@kumar303 Auh, not sure whether I get the point. But I download styled-componets and \@type/styled-components and have following code 
``` ts
import styled, { css } from 'styled-components'

const Button = styled.button`
  ${props =>
    css`
      background: palevioletred;
      color: white;
    `};
`
```
I do not get any error(at least in my simple ts-config).

Now make a little change to add error:
``` ts
const Button = styled.button`
  ${props =>
    props.primary &&  // ts(2339) on text `primary`
    css`
      background: palevioletred;
      color: white;
    `};
`
```
Adding the new \@ts-ignore-enable directive at the start does make the error quiet, but this also work
``` ts
// adding @ts-ignore-enable here could work
const Button = styled.button`
  ${
    // @ts-ignore         this line is not needed, just remind that the prop could be ignored in this way too
    props =>
    // @ts-ignore
    props.primary &&  // no error message now!
    css`
      background: palevioletred;
      color: white;
    `};
`
```

Do I get your meaning correctly? If not, could you give  simple steps or a minimal repository to help me get it? Thanks!

**Comment by kumar303** [comment]
Aha! I stand corrected. The original code I was fighting with looked more like this (if memory serves):

```jsx
import React from "react";
import styled from "styled-components";

const Button: React.FC<{
  // Since this is missing className and style props, it is invalid.
  nope: string;
}> = () => <button />;

const Form = styled.form`
  ${Button} {
    color: rebeccapurple;
  }
`;
```

The error happens at `${Button}` but **I was able just now to successfully put** a `@ts-ignore` on top of that, like:

```jsx
const Form = styled.form`
  ${// @ts-ignore
  Button} {
    color: rebeccapurple;
  }
`;
```

As I recall, I was unable to put `@ts-ignore` on top of this before. Perhaps a bug was fixed in either TS or prettier since I last tried or I'm remembering it wrong 😀.

**Comment by ShuiRuTian** [comment]
Seems the issue is resolved.
I would not be so suprised if it is really due to the version of TS. TS might fix many small issues which would not be mentioned in the "new feature bolg" for each big version. 
Personally, I recommand updating TS in time. TS is always getting better and better!

**Comment by sandersn** [comment]
I remember seeing a PR for that fix in the last couple of months.

@ShuiRuTian do you want to keep working on this? If not, we can close it in its current state and restart work again later if something changes.

**Comment by ShuiRuTian** [comment]
@sandersn 

I would be glad to continue working on this again when TS team decides to have this feature someday.

**Pull request closed without merging**
