### PR TITLE
fix members decorator check with transformers

### LINKED ISSUE #17384: Transforming class member with decorators throws
**TypeScript Version:**  2.4.0 

**Code**

> Can't use something that runs from "tsc" since it does not support transformers

In a `PropertyDeclaration` visitor
```ts
return ts.updateProperty(
          node,
          node.decorators[0], // assume we have 2 or more decorators...
          node.modifiers,
          node.name,
          node.type,
          node.initializer
        );
```

**Expected behavior:**
Should compile.

**Actual behavior:**
Exception is thrown `TypeError: Cannot read property 'kind' of undefined`

The exception is throw from [here](https://github.com/Microsoft/TypeScript/blob/194c2bc2ca806f5f1014113329e33207f683037c/src/compiler/utilities.ts#L1121)

```ts
    export function nodeCanBeDecorated(node: Node): boolean {
        switch (node.kind) {
            case SyntaxKind.ClassDeclaration:
                // classes are valid targets
                return true;

            case SyntaxKind.PropertyDeclaration:
                // property declarations are valid if their parent is a class declaration.
                return node.parent.kind === SyntaxKind.ClassDeclaration;

            case SyntaxKind.GetAccessor:
            case SyntaxKind.SetAccessor:
            case SyntaxKind.MethodDeclaration:
                // if this method has a body and its parent is a class declaration, this is a valid target.
                return (<FunctionLikeDeclaration>node).body !== undefined
                    && node.parent.kind === SyntaxKind.ClassDeclaration;

            case SyntaxKind.Parameter:
                // if the parameter's parent has a body and its grandparent is a class declaration, this is a valid target;
                return (<FunctionLikeDeclaration>node.parent).body !== undefined
                    && (node.parent.kind === SyntaxKind.Constructor
                        || node.parent.kind === SyntaxKind.MethodDeclaration
                        || node.parent.kind === SyntaxKind.SetAccessor)
                    && node.parent.parent.kind === SyntaxKind.ClassDeclaration;
        }

        return false;
    }
```

Trying to reach `node.parent.kind` while `node.parent` is undefined, which is common to all "synthesized" nodes, i.e. transforming nodes.

### PR DESCRIPTION
**Pull request by shlomiassaf**
Fixes #17384

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Hey @shlomiassaf, thanks for the PR! @rbuckton can you review this? Do we have any specific API tests for something like this?

**Comment by shlomiassaf** [comment]
@DanielRosenwasser @rbuckton 

I didn't find a previous test case for this, but its probably there.

I think it should be a conformance test right?

**Comment by shlomiassaf** [comment]
@DanielRosenwasser 

It looks like there are a lot of logic that does not take into account applying transformers, in my case I see that when applying transformations on decorated nodes.

For example, in you run [this code](https://gist.github.com/shlomiassaf/fd1e3702b9336f6070cf9cd40089d15e#file-removeallclassparameterdecorators-ts) it will transpile a module with a simple transformer that remove all **decorators** for all **class parameters**

It will error with:
```
/node_modules/typescript/lib/typescript.js:27549
                        var moduleExports = getSymbolOfNode(location).exports;
                                                                     ^
TypeError: Cannot read property 'exports' of undefined
```

This happens since `resolveNameHelper` in `checker.ts` calls `getSymbolOfNode`:
```ts
        function getSymbolOfNode(node) {
            return getMergedSymbol(node.symbol);
        }

        function getMergedSymbol(symbol) {
            var merged;
            return symbol && symbol.mergeId && (merged = mergedSymbols[symbol.mergeId]) ? merged : symbol;
        }
```

Under the hood since we removed decorators, typescript updates the `ModuleDeclaration` (ts.updatesXXXX).

So, the **node** is synthetic which means it has no `symbol`, the symbol is in the `original` node.

**Comment by shlomiassaf** [comment]
Here's [another example](https://gist.github.com/shlomiassaf/fd1e3702b9336f6070cf9cd40089d15e#file-replaceallclassparameterdecoratorswithnotemitednodes-ts)

This time, instead of removing the decorators of class parameters I replaces them with `NotEmittedStatement`.

```ts
  function visitNode(node: ts.Node) {
    if (node.kind === ts.SyntaxKind.Decorator && node.parent.kind === 146) {
      return ts.createNotEmittedStatement(node);
    } else {
      return node;
    }
  }
```

The error now:
```
node_modules/typescript/lib/typescript.js:15388
        while (node.kind === 297 /* PartiallyEmittedExpression */) {
                   ^
TypeError: Cannot read property 'kind' of undefined

```

**Comment by shlomiassaf** [comment]
Another thing I run into, when removing/replacing some of the decorators the output for `   __metadata("design:paramtypes", [..... TYPES HERE ....]`

Will always be [Object, Object....]

This happens because of `resolver.getTypeReferenceSerializationKind(node.typeName, currentScope)`

The currentScope is the synthetic node which can't resolve the type properly.

Maybe I'm doing it all wrong maybe these are real issues, dont know... didn't want to spam the issue list so I put all of it here

**Comment by shlomiassaf** [comment]
After some more digging it looks like most issues are related to bindings and the type serializers in the typescript transformer (ts.ts) 

More precisely, synthetic nodes not having bindings set (Symbol, locals etc...).

Since each factory update (e.g. `ts.updateParameter`, `ts.updateProperty`...) produces a synthetic node it comes up.

For now the workaround I'v used is to manually assign `locals` and `symbols` to a visited (and replaced) symbol which is also a scope (usually `SourceFile`)

```
if (sourceFile['origin']) {
  sourceFile['symbol'] =  sourceFile['original']['symbol'];
  sourceFile['locals'] = sourceFile['original']['locals'];
}
```

This is a shady hack that seems to work at the moment but i'm not comfortable with it, who knows what logic in the native transformers might conflict with it.

That fact it works gives a clear direction on the problem...

**Comment by shlomiassaf** [comment]
Another one in the type checker

```ts
        function checkGrammarDisallowedModifiersOnObjectLiteralExpressionMethod(node: MethodDeclaration) {
            // We only disallow modifier on a method declaration if it is a property of object-literal-expression
            if (node.modifiers && node.parent.kind === SyntaxKind.ObjectLiteralExpression) {
                if (getFunctionFlags(node) & FunctionFlags.Async) {
                    if (node.modifiers.length > 1) {
                        return grammarErrorOnFirstToken(node, Diagnostics.Modifiers_cannot_appear_here);
                    }
                }
                else {
                    return grammarErrorOnFirstToken(node, Diagnostics.Modifiers_cannot_appear_here);
                }
            }
        }
```

Will fail upon running diagnostics.

node.modifiers && **node.parent.kind**

**Comment by rbuckton** [comment]
All of the built-in transformers with the exception of _ts.ts_ were written to avoid using parent pointers. However, _ts.ts_ has not been fully updated to avoid referencing `.parent`.

**Comment by shlomiassaf** [comment]
@rbuckton @DanielRosenwasser note that there are also some in the checker....

**Pull request closed without merging**
