### PR TITLE
Improve type inference for types like 'T | Promise<T>'

### LINKED ISSUE #32434: Suboptimal inference to unions like T | Promise<T>
**TypeScript Version:**  3.6.0-dev

**Code**

```ts
declare function foo<T>(x: T | Promise<T>): void;
declare let x: false | Promise<true>;
foo(x);  // Error, 'false | Promise<true>' not assignable to 'true | Promise<true>'

declare function bar<T>(x: T, y: string | T): T;
const y = bar(1, 2);  // Error, '2' not assignable to 'string | 1'
```

**Expected behavior:** No errors.

**Actual behavior:** Errors as noted above.

**Playground Link:** https://www.typescriptlang.org/play/index.html#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVAPgAoAPALnhPgB94AFGHAWywGcRSyAlHQBuOLMADcAWABQoSLAQQQGeLSRQIvJq3ZdeRDDGQgy0mYkLUBE+PAD09+AFEY7GLNnzocJGky4+ABGsPzUdCQANPAAnnTcRlioAOY6JEL05mB4CbHwALzwITAUAIzRAEw2do4ubjgeMkA

**Related Issues:** Discovered in #32386.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR improves type inference to union types that contain combinations of nested and naked type variables. Previously, we'd always give lower priority to inferences made to naked type variables in union types, but this produced sub-optimal results in some fairly basic scenarios (see #32434).

The improved algorithm for inferring from a single source type or a union of source types to a target union type is:

* First, infer from each source type to each target type that isn't a naked type parameter, tracking for each source whether any inferences are made from that type.
* Second, if there are source types from which no inferences were made in the first step, infer from a union of those source types to each naked type parameter in the target type. Give lower priority to these inferences only if the target contains more than one naked type parameter.

Some examples:

```ts
declare function foo<T>(x: T | Promise<T>): T;
declare let x: false | Promise<true>;
const y = foo(x);  // boolean

declare function bar<T>(x: T, y: string | T): T;
const z = bar(1, 2);  // 1 | 2
```

Previously both of the examples above caused errors.

This PR also fixes an inconsistency we've long had.

```ts
declare function baz1<T>(x: T | string): T;
declare const s: string;
const x1 = baz1(s);  // Was string, now unknown

declare function baz2<T>(x: T | string | number): T;
declare const sn: string | number;
const x2 = baz2(sn);  // Was never, now unknown
```

We now infer `unknown` for `T` in both cases above (because there is nothing left to infer from when the matching types are eliminated, and `T` has no constraint or default).

Fixes #32434.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
@typescript-bot test this

**Comment by ahejlsberg** [comment]
Latest commit fixes an issue where strangely we infer nothing for `T` in

```ts
declare function flatten<T>(array: ReadonlyArray<ReadonlyArray<T>>): T[];
declare let naa: number[][];
let na = flatten(naa);
```

Before the commit, `na` would have type `unknown[]`. We currently limit inference between two types with the same symbol to a single level, which causes the issue. This is fixed by #31633, but meanwhile this commit is takes care of the issue for array types.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
@typescript-bot test this

**Comment by timsuchanek** [comment]
@ahejlsberg you're probably very busy, but in case you find the time, it would be great if you could have a look at https://github.com/microsoft/TypeScript/pull/32100 🙏

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
@typescript-bot test this

**Comment by ahejlsberg** [comment]
RWC tests look good. Only one change in `vscode`, an error that shouldn't be is now gone.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@typescript-bot user test this

**Comment by ahejlsberg** [comment]
Verified that user test suite differences are all preexisting conditions.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
Two minor issues in DT tests are covered by DefinitelyTyped/DefinitelyTyped/pull/37057.

**Comment by ahejlsberg** [comment]
Merging this now. There are a few breaks in the RWC suites that I have reviewed with @RyanCavanaugh.

**Comment by weswigham** [comment]
I think this is significantly affecting `vscode` - there's no diff in the `user` PR because output is completely blocked by an issue during build (so the test outright fails with no diff) - https://github.com/microsoft/vscode/pull/77835 should resolve that, as it's just a lingering affect of some old generator type definitions. Once that's in place, though, `vscode` has _many_ new errors:
image

**Comment by weswigham** [comment]
Scratch that, it might be the node version bump itself that's breaking so much; or at least a fair part of it.

**Pull request merged**
