### PR TITLE
Add a type-guard overload of Array.every

### LINKED ISSUE #14963: Type guards in Array.prototype.every
**TypeScript Version:**  2.2.2

**Code**

```ts
function isNumber(x: any): x is number { return typeof(x) === "number"; }

let numbersOrStrings: (number | string)[] = [1, 2, 3, 4];

if(numbersOrStrings.every(isNumber)) {
    let _numbers: number[] = numbersOrStrings;
    // ...
}
```

**Expected behavior:**

When every member of `numberOfStrings` matches the `isNumber` type guard, the whole array should be inferred to be `numberOfStrings: number[]`; so, the above code should compile without error.

**Actual behavior:**

The above fails to compile, with the following error:

```
error TS2322: Type '(string | number)[]' is not assignable to type 'number[]'.
```

---

This issue is similar to #7657, and it can be solved by adding something like the following to `lib.d.ts`:

```ts
interface Array<T> {
    every<U extends T>(pred: (a: T) => a is U): this is U[];
}
```

(or, the above can be added locally to a project as a temporary workaround)

### PR DESCRIPTION
**Pull request by dmitri-gb**
This adds a type-guard aware overload of `Array.every`.

Fixes #14963.

### CODE REVIEW

**Comment by keithlayne** [comment]
I've wanted this feature too, but it was pointed out in another issue that `Array.prototype.every` differs from `Array.prototype.filter` in that it does not return a new array, and other references mutate the underlying array in an incompatible way.

However, TS has other unsound narrowings, so maybe this should be a pragmatic exception?  I'm not sure.  Seems easy enough to wrap if you need it in a more sound way.

**Comment by RyanCavanaugh** [comment]
Overall LGTM. Can you fix the merge conflict so we can run some user tests?

**Comment by sandersn** [comment]
@typescript-bot user test this
@typescript-bot run tests

**Comment by sandersn** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
@typescript-bot rwc test this

**Comment by sandersn** [comment]
@typescript-bot test this

**Comment by sandersn** [comment]
User tests are fine -- we caught vs code during a build break, but otherwise there's nothing there.

**Pull request merged**
