### PR TITLE
Fix narrowing of intersection with function type

### LINKED ISSUE #45801: Type narrowing based on function typeof is broken when function is intersected with a record
# Bug Report

### 🔎 Search Terms

type narrowing based on function typeof is broken when intersection with a record is used

### 🕗 Version & Regression Information

- Recent change in behaviour happened in version 4.3.5

### ⏯ Playground Link
 
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAshwEMoF4oG8oDMD22BcUAzsAE4CWAdgOZQC+AUJcBCZggMbQBi6UAFAEoCxctQb122CsSgAPFPwQE+PAGSx4CAVAA+RUpSrbkAPnT0olqGUz9QkbLaTIXUAESYArhXbAyUtwE0CytQgHowqGBCADoANxZCfwooE1QAFhiAZhiAVgIKCASSKABaUqhvCFlIXwgAExDQywio2OKkqSgAHgyYgCZsgjUNRDKK6trmRuarBABuJrooCAAbQmhg2ZbIyYg6+uEDaiXwyOj4xOTUvpz8-VEacpWa-enTq1aLjuveqEzBlkjo9dPwRnBENpnlVXgcPpYFksGLQgA)

### 💻 Code

```ts
type Meta = { foo: string }
interface F { (): string}
const x = (a: (F & Meta) | string) => {
    if (typeof a === "function"){
        // ts.version >= 4.3.5: never -- unexpected
        // ts.version <= 4.2.3: F & Meta -- expected
        a;
    } else {
        // expected: string
        // ts.version >= 4.3.5: string -- expected
        // ts.version <= 4.2.3: string | (F & Meta) -- unexpected
        a;
    }
}
```
### 🙁 Actual behavior

behavior was half correct from in TS versions  <= 4.2.3, but then it was changed in 4.3.5 which fixed the part that was wrong previously, but broke the other part that was correct. So we still have half broken behavior.

### 🙂 Expected behavior

It's expected to pick the correct parts from the both versions.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #45801.

Second attempt at a fix, first is in #47282 (along with some explanation of the issue).

### CODE REVIEW

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
I'm curious why you've included `TypeFacts.TypeofEQObject` and `TypeFacts.TypeofNEObject` in `TypeFacts.OrFactsMask`? I'd be inclined to think an intersection is an object only when every constituent is an object. Meaning the flags should be and-ed, not or-ed. For example:

```ts
function test(x: number & { _foo: string }) {
    if (typeof x === 'object') {
        x;  // Used to narrow to never, now doesn't
    }
}
```

It's fairly common to have tagged primitives like that, but they shouldn't appear to be objects.

**Comment by gabritto** [comment]
I think `TypeFacts.TypeofEQObject` was a mistake on my part, given that behavior. But `TypeofNEObject` still makes sense to me to be an `or` mask because of the interaction between objects and functions:
```ts
function f1(x: F & { foo: number }) {
    if (typeof x !== "object") {
        x; // Narrows to `never` if `TypeFacts.TypeofNEObject` is an `and` mask
    }
}
```

However, there's also a mistake on the `ignoreObjects` behavior: we should return the `AndMask` instead of falling back and returning `All`, since `All` is no longer the identity element for computing type facts of intersections.

Made the fixes here: https://github.com/microsoft/TypeScript/pull/47583

**Pull request merged**
