### PR TITLE
Concat declaration error so we report them

### LINKED ISSUE #7354: There should be an error when there is an error in emitting .d.ts
**TypeScript Version:** 

Built from "master" branch

**Code**

```ts
namespace V {
    interface Foo { }
    export function Bar(): Foo { return undefined; }
}
```
Compiler option: ` --declaration`

**Expected behavior:**
There should be an error indicating that there is an error in emitting .d.ts file.

**Actual behavior:** 
There is no error shown. Though it behavour correctly, not emitting .d.ts

### PR DESCRIPTION
**Pull request by yuit**
Fixes #7354 

TODO: Add tests

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Ensure that any tests that you add actually fail prior to the change.

**Comment by mhegazy** [comment]
we broke this a few times in the last few weeks. we should add a test.

**Comment by yuit** [comment]
@mhegazy  @DanielRosenwasser I agree with that. After brief looks into our harness, the mechanism to gather diagnostics is different from when users use command-line. So there will be some modification we need to do to fix that.

**Comment by mhegazy** [comment]
sure. https://github.com/Microsoft/TypeScript/issues/7379 is tracking that.

**Comment by mhegazy** [comment]
:+1:

**Pull request merged**
