### PR TITLE
:memo: document autocrlf needs to be off

### PR DESCRIPTION
**Pull request by basarat**
otherwise people will get test failures which are not immediately obvious

### CODE REVIEW

**Comment by basarat** [comment]
I've seen this come up enough to warrant this documentation

**Comment by DanielRosenwasser** [comment]
Not sure if we should be suggesting this be set *globally*.

**Comment by basarat** [comment]
> Not sure if we should be suggesting this be set globally.

Sure see : https://github.com/Microsoft/TypeScript/pull/3143

**Comment by DanielRosenwasser** [comment]
@basarat while I work on a real solution, can you just remove the `--global` flag from the step and move this to `CONTRIBUTING.md` since this is actually a guide on how to build TypeScript?

**Comment by basarat** [comment]
> move this to CONTRIBUTING.md since this is actually a guide on how to build TypeScript

I think it would be better here because otherwise `jake runtests` will fail otherwise : 

image

**Comment by DanielRosenwasser** [comment]
Good point; let's just add a step before "Install Jake tools and dev dependencies":

> Configure autocrlf settings for your clone:
```
git config core.autocrlf false
```

**Comment by basarat** [comment]
> let's just add a step before "Install Jake tools and dev dependencies":

I was just testing this workflow :) 

image

**Comment by DanielRosenwasser** [comment]
Ah...ah! That's going to be bad! Okay, I see. Point well-taken. :smile:

**Comment by basarat** [comment]
> I was just testing this workflow

Tested:
image


But didn't work: 
image


Seems it needs to be set (globally) before cloning ¯\\_(ツ)_/¯

**Comment by tinganho** [comment]
How does your .git/config look like?

Mine look like this:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
	autocrlf = false
[branch "master"]
[remote "origin"]
	url = git@github.com:tinganho/TypeScript.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
	url = git@github.com:Microsoft/TypeScript.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
[color "diff"]
	whitespace = red reverse
```

**Comment by basarat** [comment]
> autocrlf = false

@tinganho gets driven by `git config core.autocrlf <option>` (There is nothing there by default). However changing it *after* cloning doesn't get tests to pass.

**Comment by tinganho** [comment]
I always thought a `.gitattributes` file was more appropriate. But haven't got it worked before. 

Though I haven't tested this yet:

```
src/**/*     crlf
scripts/**/* crlf
tests/**/*   crlf=false
```

from http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by tinganho** [comment]
@basarat I just submitted a new PR https://github.com/Microsoft/TypeScript/pull/3174 with `.gitattributes` and `tests/**/* crlf=false` and it seem to have worked.

**Comment by mhegazy** [comment]
thanks!

**Comment by basarat** [comment]
:rose:

**Pull request merged**
