### PR TITLE
Always recreate the file watcher when rename event occurs

### LINKED ISSUE #47466: Persistent incorrect semantic diagnostic after large rebase or checkout: Module has no exported member
# Bug Report

When using tsserver in VSCode, I sometimes see persistent false error reports from diagnostics after a large rebase or checkout of the form, "Module '{}' has no exported member '{}'." The file mentioned in the error is a file that was updated in the checkout or rebase. Opening the file in question in VSCode loads the file and resolves the incorrect semantic diagnostic. Alternatively, restarting TSServer resolves the incorrect diagnostic

### 🔎 Search Terms

module has no exported member watch

### 🕗 Version & Regression Information
This has been happening as long as we can remember

### 🙁 Actual behavior

persistent incorrect ssemantic diagnostics

### 🙂 Expected behavior

No errors after a reasonable period of time

### PR DESCRIPTION
**Pull request by sheetalkamat**
Sometimes file appears before the callback is processed and that results in watching wrong inode.
So on every rename event we are recreating the file watcher (which was intention of the existing code by checking fileExists but now the presence check merely determines which kind of watcher is created)
Actual change is in 5dfdbdb136555efc9acfb376697b80956fbeaf87 and bb32906 

Apart from this it is also noticed that when files are edited with vim, the rename event occurs for `fileNameWithExtension~` so that is handled as if the event has occured for `fileNameWithExtension`. Fixed in 8e036e5

884678e808fc64ef95a0004aeacef2fb7ca93c37 converts all watch related tests to baselines so its easier to reason about
03fa5b3a9803e33e3a37807964a9bcd91e56d9ed adds inode watching test by refactoring how sys does fsWatch so that we can test that functionality
c7bbb97717e5287daa960393e482570c01a5cb79 allows to take map of files instead of array when creating test host for watch
189bbc22da1824794624844c796b42b98de30d43 test that shows the rename issue
5dfdbdb136555efc9acfb376697b80956fbeaf87 bb32906 8e036e5 Actual fix

Fixes  microsoft/TypeScript#47466 (Repro per https://github.com/microsoft/TypeScript/issues/47466#issuecomment-1013852588)

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@MarcCelani-at Can you try the result of build from https://github.com/microsoft/TypeScript/pull/48997#issuecomment-1119950565 Its modified version of #47482

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by MarcCelani-at** [comment]
I can't verify this change in our mono repo because we use yarn3, which patches typescript at fixed versions. But I will test this on a small project on mac.

**Comment by MarcCelani-at** [comment]
I'm working on trying to repro this. There's a lot changing in our environment lately (just upgraded from node 12 to node 16) so its taking longer than it should, I think.

**Comment by jakebailey** [comment]
FWIW you can definitely use the above package with yarn 3; it'll cook up a new patched version for whichever version of TS you install, even if it's not one of the stable release versions.

**Comment by jakebailey** [comment]
To install PRs, we ask the bot to "pack this", which gives you something you can put into your `package.json`:

```
"typescript": "npm:@typescript-deploys/pr-build@4.7.0-pr-48997-3"
```

See above: https://github.com/microsoft/TypeScript/pull/48997#issuecomment-1120079563

**Comment by MarcCelani-at** [comment]
Sorry, this is taking awhile. We are still on 4.5.4 so I first had to get 4.6.4 working. It turns out this is really difficult in our monorepo environment because of a change that broke tsserver-bridge, details in https://github.com/microsoft/TypeScript/issues/49067. I'm going to try to get this working without using tsserver-bridge in our monorepo.

**Comment by MarcCelani-at** [comment]
Okay, I have managed to repro the underlying issue on 4.6.4 in our monorepo without crashing the process from memory usage. Then, I upgraded to `npm:@typescript-deploys/pr-build@4.7.0-pr-48997-3`, and the issue still repros. I checked the logs and confirmed the correct version of typescript was running, and I confirmed that after the first FileWatcher trigger, it does not trigger again after that. I repro'd by...

1. Open a ts file in VSCode
2. Set the typescript version to workspace version
3. Open logs check version
4. Open a terminal
5. Open a file that is imported in vim. Change the class name of the class that is imported and write with ":wq"
6. Observe a correct error in VSCode on the open file
7. Check logs, verify FileWatcher trigger log line
8. Open the same file that is imported in vim. Change the class name back and write with ":wq"
9. Wait, observe that the error does not go away.
10. Check logs, verify FileWatcher did not trigger again

**Comment by MarcCelani-at** [comment]
ah it appears I need to test `npm:@typescript-deploys/pr-build@4.7.0-pr-48997-6`, my mistake. Let me try that now!

**Comment by MarcCelani-at** [comment]
Ok, tried it again on `npm:@typescript-deploys/pr-build@4.7.0-pr-48997-6` and it also doesn't fix the problem. :(

**Comment by sheetalkamat** [comment]
@MarcCelani-at did you see lines like: ``sysLog:: ${fileOrDirectory}:: Changing watcher to ...` what did they say.. Can you paste logs from that line by cleaning out private file paths to some random file paths

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@amcasey @andrewbranch @jakebailey this is ready for review as @MarcCelani-at confirmed offline that this is working

**Comment by jakebailey** [comment]
Okay, I had a change to review all of the commits individually; the first ones all are cleanups and move to baselines that look good to me.

The "actual fix" stuff at the end also looks reasonable, so I'm okay with this change (if everyone else is confident), pending my small questions above. I don't really know if I should be trying to reproduce the core issue or not here to really verify, or if we can just wait for feedback if this breaks people on nightly.

**Comment by sheetalkamat** [comment]
When i reproed the scenario - vim edit and save on ubuntu vm, i didnt get the `~`  for events .. i always received `relativeFileName` as `fileNameWithExtension`. Only in the logs that @MarcCelani-at sent i saw that there were events with suffix `~`. 

I think its reasonable to try it out and seek feedback, Our default is to watch files using polling and not using file system events.. So when we added `watchFile` option is when people could do this. We have already put caveat that `fsEvents` and file watching is not reliable with underlying issues so use at own risk.  Over years we have gotten reports of things not working as intended but very few people follow up issues with the logs and that that might explain why we haven't seen these kind of logs before.

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
