### PR TITLE
Ensure rest type for source parameter is readonly in relations

### LINKED ISSUE #53255: Parameters created from tuple are treated as mutable instead of immutable, unless written as "...args"
# Bug Report

### 🔎 Search Terms

const array tuple parameter spread

### 🕗 Version & Regression Information

- This is the behavior in every version I tried,.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.9.5#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxCjAAsAeAFQIA8MRVgBneAJUODwgE8BBGGKTqSipOAPlEAKMFAYgGALhZsOPPgIqiAlIomJUOgHRHYAcwXxym+AF5R8YZyu34ANxxZgAbgBQ3sHgYMeGlZJmt4AG1veBjIgEYAGngAcjjkgF0E6NiIgCYk5NyMrPT7Jn9UQJ8-AKDCEhAYGwIiYikZOU0fAHpu2NiAPQB+X174AFE+HBh5bzHeE2QAWzognER4DE4ABwRkiShFOPgAH3h8+AAjRQAiOJvT+Bvcm6c7Nw9k+CwmVBwgmQMLAmVBQS4QBAYHDwbawKArWhNdabHZ7CRGAymcxwKDsVBceJJO43UpnHF4gl5IkvdJvewiZIGOZ9CyopjI2H8BGNJjJKBfYTAFJYgVwb7oHBLWHYcEgJljWLkVEpckqQlPe6k+Cq-GcSIXZ4kr4-eB-AEMIEgsEQzbQra7FIRQ7wY5nC7XDUPM6G9KM5n9GLkYiQ5XJHWUxKe33fXnhzgC+jBYRmq4IQHA1AgIVQzbB+BLZAYa0hh3JJ1HR7u273R4+xkSXIAZgALABWTSjPoAdWIetgkLzpmWqyYsjoZXzheLI289WDMAkBySlzpAG9sjEoD0WcMN1dtzFdwBfLq+WetRqLjFYtd7hX9Xf9CqBSJQZelcJYnz9Lf++CP2JLgPf8RhPHwgA)

### 💻 Code

```ts
declare function each<T extends ReadonlyArray<any>>(cases: ReadonlyArray<T>): (fn: (...args: T) => any) => void;

const cases = [
    [1, '1'],
    [2, '2'],
] as const;

const eacher = each(cases);

// Error.
eacher((a, b) => {
});

// No error?
eacher((...args) => {
    const [a, b] = args;
});

```

### 🙁 Actual behavior

```
Argument of type '(a: 1 | 2, b: "1" | "2") => void' is not assignable to parameter of type '(...args: readonly [1, "1"] | readonly [2, "2"]) => any'.
  Types of parameters 'a' and 'args' are incompatible.
    Type 'readonly [1, "1"] | readonly [2, "2"]' is not assignable to type '[a: 1 | 2, b: "1" | "2"]'.
      The type 'readonly [1, "1"]' is 'readonly' and cannot be assigned to the mutable type '[a: 1 | 2, b: "1" | "2"]'.(2345)
```

Obviously they're not assignable, but why did we come up with `[a: 1 | 2, b: "1" | "2"]` and not `readonly [a: 1 | 2, b: "1" | "2"]`?

### 🙂 Expected behavior

No error, as though it had been expanded separately.

See also: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64739

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #53255
See also https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64739

Given:

```ts
declare function each<T extends ReadonlyArray<any>>(cases: ReadonlyArray<T>): (fn: (...args: T) => any) => void;

const cases = [
    [1, '1'],
    [2, '2'],
] as const;

const eacher = each(cases);

// Error.
eacher((a, b) => {
});

// No error?
eacher((...args) => {
    const [a, b] = args;
});
```

We used to say:

```
Argument of type '(a: 1 | 2, b: "1" | "2") => void' is not assignable to parameter of type '(...args: readonly [1, "1"] | readonly [2, "2"]) => any'.
  Types of parameters 'a' and 'args' are incompatible.
    Type 'readonly [1, "1"] | readonly [2, "2"]' is not assignable to type '[a: 1 | 2, b: "1" | "2"]'.
      The type 'readonly [1, "1"]' is 'readonly' and cannot be assigned to the mutable type '[a: 1 | 2, b: "1" | "2"]'.(2345)
```

Here, the "source" type is `[a: 1 | 2, b: "1" | "2"]`, but that can't be assigned to the target as the target is readonly. But, these are the rest arguments, so there's no way for this function to observe the read-only ness of the parameter. (Note: these are parameters, so directionality is swapped.)

I'm not sure if this is a perfect fix, but one way to "solve" this is to just ensure the tuple/array we cook up for the source is readonly, that way it's always compatible. This fixes the issue, but does change some error messages because they _do_ observe the intermediary type here.

Maybe the "better" thing to do here would be to strip readonly-ness from both `sourceType` and `targetType` if they were produced via `getRestTypeAtPosition`? I haven't exactly found "the way" to do that yet, e.g. no helper named "remove readonly from tuple or array".

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by jakebailey** [comment]
Yeah, this is just a case where inference is already right (the insides don't change).

Would my alternative suggestion of stripping `readonly` from rest types work better, if I can find the way to do that?

**Comment by jakebailey** [comment]
In general, I'm also having trouble seeing where anyone would ever want the result of `Parameters` to be readonly itself; it never matters what you pass into a function, the actual variadic parameters themselves are copied, so only individual parameters need to maintain readonly-ness (e.g. arrays).

**Comment by jakebailey** [comment]
Actually, I'm even more weirded out, because in my example above `args` is `readonly [1, '1'] | readonly [2, '2']`, but clearly mutating it will not mutate the input...

```
> const fn = (...args) => { args[0] = "oops" }
undefined
> const arr = ["some", "values"]
undefined
> fn(arr)
undefined
> arr
[ 'some', 'values' ]
```

So, shouldn't we be stripping readonly in every case from rest arrays?

**Comment by jakebailey** [comment]
I mean, maybe I guess this fix is okay just to get rid of the spurious relation error, and something that addresses my followup comments can come later?

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by jakebailey** [comment]
Followup is here: #53398

**Comment by sandersn** [comment]
Breaks ckeditor__ckeditor5-upload on DT. Didn't notice it until today because the overnight tests were blocked by the --legacy-peer-deps problem.

I'll file a bug when I get a smaller repro.

**Comment by jakebailey** [comment]
My fault for not retrying DT until I saw the results...

**Pull request merged**
