### PR TITLE
Add check for delete expression must be optional

### LINKED ISSUE #13783: deleting a prop doesn't invalidate the interface
**TypeScript Version:**  2.1? (Playground)

**Code**

```ts
interface Props {
    foo: string;
    bar: string;
}

const p: Props = {
    foo: 'hello',
    bar: 'world'
}

const say = (props: Props) => console.log(`${props.foo.length} ${props.bar.length}`);

say(p);

delete p.bar;
say(p); // works, but should throw
```

See [here](https://www.typescriptlang.org/play/index.html#src=interface%20Props%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20p%3A%20Props%20%3D%20%7B%0D%0A%20%20%20%20foo%3A%20'hello'%2C%0D%0A%20%20%20%20bar%3A%20'world'%0D%0A%7D%0D%0A%0D%0Aconst%20say%20%3D%20(props%3A%20Props)%20%3D%3E%20console.log(%60%24%7Bprops.foo.length%7D%20%24%7Bprops.bar.length%7D%60)%3B%0D%0A%0D%0Asay(p)%3B%0D%0A%0D%0Adelete%20p.bar%3B%0D%0Asay(p)%3B%20%2F%2F%20works%2C%20but%20should%20throw%0D%0A).

**Expected behavior:**

Don't compile, because we `delete` `bar` from `p`.

**Actual behavior:**

Compiles. Resulting in a runtime error: `Uncaught TypeError: Cannot read property 'length' of undefined`.

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #13783

### CODE REVIEW

**Comment by j-oliveras** [comment]
Is needed a test with an index type? Like:
```ts
interface Bar {
    [id: string]: string;
}

declare const a: Bar

delete a["a"];
delete a.b;
```

**Comment by Kingwl** [comment]
> Is needed a test with an index type? Like:

Good point.

@pack this.

**Comment by Kingwl** [comment]
Hey, How are you? @typescript-bot 

@typescript-bot pack this.

**Comment by DanielRosenwasser** [comment]
This is a breaking change that was added in post beta with no test run on it. I think we should have had more due diligence before pulling it in.

**Comment by simhnna** [comment]
What's the reasoning behind excluding `null` from this list?

> the operand must now be any, unknown, never, or be optional (in that it contains undefined in the type)

**Comment by DanielRosenwasser** [comment]
Because `delete` doesn't leave behind a `null`.

**Comment by rohitf** [comment]
Seeing a possible bug for this case - **even though TS recognizes that key in delete p[key] can be either 'foo' or 'bar', it does not error.**
```

interface Props {
    foo: string;
    bar: string;
}
const p: Props = {
    foo: 'hello',
    bar: 'world'
}

const keys = ['foo', 'bar'] as const;
keys.forEach(key => delete p[key]) // Should error since foo and bar are required props
```
[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgApQPYAcDOyDeAsAFDJnIwYYBcyOYUoA5gNwnnIBGcUt9jIViQC+JEggwh6yLLXTY8AXgLtylGsgDkACwgAbPRk0AaVWW68tAdwxQ9AE00ixxCVLDIA1hACeS5ADamuomWhaaALrIcHhu9GzE3n4AdJRQAKKI2gAUSciKAHzI9voQkDIBSREAlMgkAPT1yGA+WBAYMF6++VohyAA+YTyadcSNyAC0RQDK2hgArg7I0JhQdKBIFFTRIPZcPNFQKEcAjvPAR3tYmLgkQA)

**Pull request merged**
