### PR TITLE
Switch Debug.assertX functions to use asserts conditions

### PR DESCRIPTION
**Pull request by rbuckton**
This switches our internal `Debug.assertX` functions to use `asserts` conditions. This resulted in 36 cases where we no longer needed a type assertion now that a pre-existing `Debug.assertX` was properly narrowing the type.

I also found that our check for `shouldAssert` was happening too early and some of our assertions weren't triggering properly. However, these appeared to have been cases where the wrong node test function was passed to `Debug.assertNode`.

Finally, I renamed `Debug.assertDefined` and `Debug.assertEachDefined` to `Debug.checkDefined` and `Debug.checkEachDefined` (respectively) since they're not intended to be used as statements compared to all of the other `assertX` functions. I've left aliases for `assertDefined` to `checkDefined` and `assertEachDefined` to `checkEachDefined` with a `@deprecated` doc comment for now, since many on the team may still be using those functions.

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot perf test

**Comment by rbuckton** [comment]
I've updated the assertion functions to call a modified `shouldAssert` that caches the function and replaces it with `ts.noop` in a way that allows them to be restored when the assertion level changes.

**Comment by rbuckton** [comment]
@typescript-bot perf test

**Comment by rbuckton** [comment]
> I'm OK with this, but, like, I'm more interested in what effect this has on our local build time than the perf test time 

Unfortunately our benchmark suite isn't set up to be able to benchmark the *current* compiler (and in general that wouldn't make sense since build-to-build variations wouldn't be stable. I'll see what I can do to get a comparison between LKG and this locally though.

**Comment by weswigham** [comment]
> I'll see what I can do to get a comparison between LKG and this locally though.

That's all I was curious about~

**Comment by rbuckton** [comment]
I used LKG to benchmark this with the asserts and without the asserts (and going back to using casts) and there didn't seem to be any regression in perf. As I mentioned in the OP, we only had 36 cases where the assert had any impact on the type (allowing us to remove a cast), and none of those seemed to be likely to be a degenerate case involving a large union.

<table border="0" cellpadding="0" cellspacing="0" >
<thead>
<tr>
<th align=left><sub>Metric</sub></th>
<th align=right><sub>no assert conditions</sub></th>
<th align=right><sub>assert conditions</sub></th>
<th align=right><sub>Delta</sub></th>
<th align=right><sub>Best</sub></th>
<th align=right><sub>Worst</sub></th>
</tr>
</thead>
<tr class="group"><th align=left colspan="6">Compiler - node (v13.0.1, x64)</th></tr>
<tbody>
<tr class="measurement memory scenarioundefined host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>268,971k (± 0.12%)</sub></td>
<td align=right><sub>269,418k (± 0.01%)</sub></td>
<td align=right><sub>+447k (+ 0.17%)</sub></td>
<td align=right><sub>269,371k</sub></td>
<td align=right><sub>269,462k</sub></td>
</tr>
<tr class="measurement parse-time scenarioundefined host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>1.98s (± 2.58%)</sub></td>
<td align=right><sub>1.97s (± 1.45%)</sub></td>
<td align=right><sub>-0.01s (- 0.51%)</sub></td>
<td align=right><sub>1.95s</sub></td>
<td align=right><sub>2.01s</sub></td>
</tr>
<tr class="measurement bind-time scenarioundefined host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>1.41s (± 0.45%)</sub></td>
<td align=right><sub>1.44s (± 2.42%)</sub></td>
<td align=right><sub>+0.03s (+ 1.98%)</sub></td>
<td align=right><sub>1.42s</sub></td>
<td align=right><sub>1.48s</sub></td>
</tr>
<tr class="measurement check-time scenarioundefined host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>10.12s (± 2.68%)</sub></td>
<td align=right><sub>9.89s (± 0.32%)</sub></td>
<td align=right><sub>-0.23s (- 2.23%)</sub></td>
<td align=right><sub>9.86s</sub></td>
<td align=right><sub>9.93s</sub></td>
</tr>
<tr class="measurement emit-time scenarioundefined host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>7.40s (± 2.68%)</sub></td>
<td align=right><sub>7.39s (± 1.51%)</sub></td>
<td align=right><sub>-0.02s (- 0.24%)</sub></td>
<td align=right><sub>7.30s</sub></td>
<td align=right><sub>7.54s</sub></td>
</tr>
<tr class="measurement total scenarioundefined host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>20.91s (± 1.75%)</sub></td>
<td align=right><sub>20.68s (± 0.66%)</sub></td>
<td align=right><sub>-0.23s (- 1.11%)</sub></td>
<td align=right><sub>20.57s</sub></td>
<td align=right><sub>20.84s</sub></td>
</tr>
</tbody>
</table>

**Pull request merged**
