### PR TITLE
Support control flow analysis for tagged template calls

### LINKED ISSUE #51426: support control flow analysis of tagged template calls
# Suggestion

## 🔍 Search Terms

return never tagged template unreachable code

Related issues:
https://github.com/microsoft/TypeScript/pull/32695
https://github.com/microsoft/TypeScript/issues/50363

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Control flow analysis detecting unreachable code after a tagged template function call that throws.

## 📃 Motivating Example

It's a surprise that the same function call does not have control flow analysis when used as a tagged template:
```
function throws(opt?: any): never {
    throw new Error()
}

function testFn() {
    throws(`reason`);
    
    // @ts-expect-error unreachable
    console.log("is unreachable!")
}

function testTag() {
    throws`reason`;
    
    // ts does not detect that this is unreachable
    console.log("is unreachable!")
}
```
([playground](https://www.typescriptlang.org/play?target=99&noFallthroughCasesInSwitch=true&ts=4.8.4#code/GYVwdgxgLglg9mABFAFgJzgdwM4Ao4AOUA-AFyICGYAngJTlgCmAbo2ogN4BQivy6WRE0yIAomgxpctLgF8uXUJFgJkjbFABiYaZx59UGHLgAGaRhWwITtANz7eDxAHpniAAJRsAWkYAPAkZoXwk4dnBzCggUCgAjABtGJwgEK0SAOni4AHNcACIYbEQIi2i4xIBCPJl5RXBoeCQodSgAFQpc2j0+fiNsMwsrMBN7HqdXZCKAEzh1ITgoRCnGZuh+CkXUQsRtkqiYhKSelLA0xkyc-N2wSLLDqpquIA))

### Throwing an exception with a message

Normally this would be something like,
```js
assert(condition, 'explanation');
```
However for performance reasons we eschew the function call:
```
condition || Fail`explanation`;
```

The `asserts` works but the `Fail` doesn't. We could work around this by `Fail('explanation')` but we prefer to be consistent in use of the `Fail` function. So for our current work-around is to explicitly `throw` the tagged template.

### PR DESCRIPTION
**Pull request by 71**
Fixes #51426. Note that it's not on the `Backlog` milestone, but the issue hasn't had any activity for a month so I thought I'd try sending a PR for review anyway.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by 71** [comment]
I'm surprised that there are significant deltas with `main`. Is it perhaps because this branch is pretty outdated (or is the perf run rebasing with `main` before running everything)?

**Comment by jakebailey** [comment]
> I'm surprised that there are significant deltas with `main`. Is it perhaps because this branch is pretty outdated (or is the perf run rebasing with `main` before running everything)?

All CI runs on the merge-head, which is main + the PR. That being said, there inherent noise.

@typescript-bot perf test this faster

**Comment by sandersn** [comment]
The results look like noise. On the other hand, control flow changes can slow down the binder (more allocation) and the checker (more nodes to iterate over).

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this PR since it's pretty old now. We can reopen and merge with main if its bug gets accepted.

**Pull request closed without merging**
