### PR TITLE
Update README.md

### LINKED ISSUE #58162: Mistake in README file
### 🔎 Search Terms

Bug in README file.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______
- This resolves mistakes in the README file.

### PR DESCRIPTION
**Pull request by skanda890**
Fixes #58162

README mistakes.

### CODE REVIEW

**Comment by skanda890** [comment]
> This PR doesn't have any linked issues. Please open an issue that references this PR. From there we can discuss and prioritise.

Check again

**Comment by MartinJohns** [comment]
Your correction is not correct. The sentence is right as it is.

**Comment by skanda890** [comment]
It missed a word

**Comment by skanda890** [comment]
Check the Commits page.

**Comment by skanda890** [comment]
Remove 'For-UnCommitted-Bug'

**Comment by xiBread** [comment]
No, it didn't.

**Comment by MartinJohns** [comment]
> It missed a word

It doesn't.

> Remove 'For-Uncommitted-Bug'

But the team did not commit to the bug issue you created and linked. If the team commits to that issue the label will be removed.

**Comment by RyanCavanaugh** [comment]
The grammar as written is correct.

**Pull request closed without merging**
