### PR TITLE
narrow by instanceof: infer type parameters from original type

### LINKED ISSUE #28560: instanceof narrowing should preserve generic types from super to child type
## Search Terms

* instanceof generic 
*  narrow instanceof

## Suggestion

The following code has a rather unexpected behavior today:

```ts
class Parent<T> {
    x: T;
}
class Child<S> extends Parent<S> {
    y: S;
}

function example(obj: Parent<number>) {
    if (obj instanceof Child) {
        const child = obj;
    }
}
```

The narrowed type that `child` gets is `Child<any>`. 

I'm requesting that the type instead gets narrowed to `Child<number>`, which is what I originally assumed would happen.

My proposal is, in general, to infer the type arguments to the narrowed-to class type whenever they can be determined from the original type.

## Precise Behavior

Consider the following code today:

```ts
const x: P = ...;
if (x instanceof C) {
    x;
}
```

Today, if `C` is a generic class, `x` gets the narrowed type `C<any, any, any, ...>`; otherwise it just gets the type `C`.

My proposal is to consider the following piece of code, and use it to inform 

Imagine that `C` has a no-argument constructor. Then the following piece of code is valid today:

```ts
function onlyP(c: P) { ... }

onlyC(new C());
```
in order to make it valid, the compiler infers type arguments for `C` that make it into a subtype of `P`. My proposal is to use the same strategy to infer the type arguments for `C` in an `instanceof` narrowing.

Consider the following examples today, and their corresponding `instanceof` narrowings:

```ts
function ex1(x: Parent<string>) { }
ex1(new Child()); // inferred arguments: <string>

function ex2(x: Parent<number | string>) { }
ex2(new Child()); // inferred arguments: <number | string>

function ex3(x: Parent<number> | string) { }
ex3(new Child()); // inferred arguments: <number>

function ex4(x: Parent<number> | Parent<string>) { }
ex4(new Child()); // inferred arguments: Child<number | string>
// Note: the above errors, because it Child<number|string> actually fails to be a subtype of
// Parent<number> | Parent<string>.
// We can either choose to infer Child<any> in this case, or use the (incorrect, but more-precise)
// inference Child<number | string>.
```

## Examples

The original use-case I had in mind was roughly the following:

```ts
abstract class Obtainer<T> {
  __phantom: T = null as T;
}

abstract class Fetcher<T> extends Obtainer<T> {
  public abstract fetch(): Promise<T>;
}

abstract class Dependency<T, D> extends Obtainer<T> {
  public abstract dependencies(): Obtainer<D>;
  public abstract compute(got: D): T;
}

async function obtain<T>(obtainer: Obtainer<T>): Promise<T> {
  if (obtainer instanceof Fetcher) {
    // obtainer: Fetcher<T>
    // currently, it's a Fetcher<any>
    return await obtainer.fetch();
  }
  if (obtainer instanceof Dependency) {
    // obtainer: Dependency<T, any>
    // currently, it's a Dependency<any, any>
    const dependencies = obtainer.dependencies();
    return obtainer.compute(await obtain(dependencies));
  }
  throw new Error("not implemented");
}
```

(note: there's still one extraneous `any` in the above, since the `D` parameter cannot be inferred)

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
    * This *is* a breaking change. However, I *think* it could only really break code that was already broken. If really necessary, it could be put behind a new `--strictGenericNarrowing` flag. 
* [x] This wouldn't change the runtime behavior of existing JavaScript code
    * No change to runtime; just inferred generic types.
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ x This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
    * I think this is an easy win for a more sound type system without any negative impact

Also, I am interested in contributing this change if it's approved!

### PR DESCRIPTION
**Pull request by Nathan-Fenner**
```ts
class Parent<T> {
  item: T;
}

class Child<R> extends Parent<R> {
  other: R;
}

function narrow(p: Parent<number>) {
  if (p instanceof Child) {
    // what should p's type be?
    p;
    // before this change: Child<any>
    // after this change:  Child<number>
  }
}
```

This change fixes #28560 by inferring (where possible) the generic type parameters for a class when it's narrowed to by the `instanceof` operator.

The general process is to infer the parameters as though performing an assignability check of `new Child(...)` to the super type. This means that it handles e.g.

```ts
class Parent<A, B> { a: A; b: B }
class Child<B, A> extends Parent<A, B> { }
```

and anything else you might try to throw at it.

*This is a breaking change*. However, nothing in the test suite broke (the only changes would be in the newly-added test case that covers this behavior).

It therefore might be a good idea to put it behind a new strict flag, e.g. `--stricterInstanceofNarrowing`. However, depending on whether anyone out in the world breaks, that might not be needed.

Not all cases are fully covered (i.e. they still infer `any` for some/all type parameters), or otherwise behave in a (potentially) unexpected (albeit correct) manner:

```ts
class Parent<A, B> {
  a: A;
  b: C;
}

class Child<C> extends Parent<C, C> {
  c: C;
}

function example(p: Parent<string, number>) {
  if (p instanceof Child) {
    p; // Parent<string, number> & Child<string | number>
  }
}
```

the resulting type is the most-specific sound(ish) type. It's unlikely anyone deliberately will encounter this case (it *should* be the case that the `Child` type is uninhabited in that case).

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this new one

**Comment by RyanCavanaugh** [comment]
The bot lies; RWC is clean.

@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
@ahejlsberg take a look? Interesting change

**Comment by RyanCavanaugh** [comment]
@ahejlsberg take a look? Interesting change

**Comment by fatcerberus** [comment]
Will this also fix this case:
```ts
class Query<T> {}
function f<T>(q: T[] | Query<T>) {
    if (Array.isArray(q)) {
        q;  // T[], so far so good
    } else if (q instanceof Query) {
        q;  // Query<any>, wtpf
    }
}
```

In my case there's no inheritance.  I'm literally only checking if it's one of the types *already named* in the union and it goes and widens it from `T` to `any`. 🙁  I can work around it by moving the `Query<T>` case into an `else { }` but that's not ideal.

**Comment by Nathan-Fenner** [comment]
@fatcerberus I think that it should handle that case, but I'm not sure whether the custom type guard in `isArray` causes problems. I can add that to the test suite to find out.

**Comment by fatcerberus** [comment]
The `isArray` check actually doesn’t have anything to do with it - the issue is specifically when there’s an `instanceof C` check after the type has already been narrowed down to `C<T>`.  Then the `instanceof` widens it to `C<any>`.

**Comment by Nathan-Fenner** [comment]
This does fix the unnecessary widening issue.

**Comment by Nathan-Fenner** [comment]
I'm going to update the test to better organize the various facets of this feature that are being tested. Here are a few samples (commented annotations are taken mechanically from the generated `.types` file):

```ts
function dontWidenPointlessly() {
  class Query<T> {
    uses: T;
  }
  function f<T>(p: T[] | Query<T>) {
    if (Array.isArray(p)) {
      p; // p: T[]
    } else if (q instanceof Query) {
      p; // p: Query<T>
    }
  }
}
```

I've identified some bugs/limitations that need to be corrected before moving forward:

```ts
function union() {
  class Parent<A> {
    a: A;
  }
  class Child<B> extends Parent<B> {
    b: B;
  }
  function multipleParents(
    p: Parent<number> | Parent<string> | Parent<boolean> // p: Parent<number> | Parent<string> | Parent<boolean>
  ) {
    if (p instanceof Child) {
      p; // p: Child<number> | Child<string> | Child<boolean>
    } else {
      p; // p: Parent<number> | Parent<string> | Parent<boolean>
    }
  }
  function mixedChildren(p: Parent<number> | Child<string>) {
    if (p instanceof Child) {
      p; // p: Child<string>
    } else {
      p; // p: Parent<number>
    }
  }
  function imcompatibleOptions(
    p: Parent<number> | Parent<string> | { foo: boolean } // p: Parent<number> | Parent<string> | { foo: boolean; }
  ) {
    if (p instanceof Child) {
      p; // p: Child<any>
    } else {
      p; // p: Parent<number> | Parent<string> | { foo: boolean; }
    }
  }
}
```

There are several problems visible here:

- in `mixedChildren`, `Child<string>` is preserved but `Parent<number>` was thrown out entirely! We should expect to see `Child<number> | Child<string>` in the then-case
- in `incompatibleOptions` the presence of the `{foo: boolean}` object causes the current heuristic check to fail, and therefore the prior fallback behavior of using `Child<any>` occurs

**Comment by Nathan-Fenner** [comment]
It occurs to me that the theory behind the current implementation is not terribly sound. At the same time, it's not entirely obvious to me how this can be corrected.

When we have

```ts
let x: T;
if (x instanceof K) {
   ...
}
```

and `K` is some generic type e.g. `K<T1 extends C1, T2 extends C2>` then what we "really" know inside the `if` is that

```ts
x: T & (exists<t1 extends C1, t2 extends C2> in K<t1, t2>)
```

That is, we know that it's still a `T` and we *also* know that there are some parameters that make it into a `K<t1, t2>` (because otherwise, it's not a "real" `K`). The `exists<T> in S` syntax is a strawman for hypothetical existential types in TypeScript.

The trick is that in many (but not obviously all) cases we can simplify this to remove the existential, producing a type that can be expressed in TS today, and is functionally the same.

For example, `exists<S extends number> S` is functionally identical to `number`, since any value that could be read from it is a `number`, and any value that's already a `number` also satisfies that type trivially.

On the other hand, `exists<S extends number> {num: S}` is *not* the same as `{num: number}`, although it's close, and TS today currently blurs this concept. This is because TS usually types object assignability as though fields were `readonly` even when they're not. The following is legal today in TS, even though it's not sound:

```ts
const a: {f:1|2} = {f: 1};
const b: {f:number} = a;
b.f = 3;
```

The way this *could* be done soundly is by annotating every field with a `read` bound and a `write` bound; `{f: T}` can be treated as shorthand for `{readonly f: T} & {writeonly f: T}`. Then in the above we'd have:

```ts
const a: {readonly f : 1 | 2} & {writeonly f: 1 | 2} = {f: 1};
const b: {readonly f : number} & {writeonly f : 1 | 2} = a;
b.f = 3; // error, f is only writeonly with 1 | 2
```

`writeonly` fields are contravariant, so attempting to specify `b` as merely `{writeonly f: number}` would fail, since `number` is not a subtype of `1 | 2`.

Moving back to the original problem, we would like to say that `exists<S extends number> {num: S}` is the same thing as `{num: number}`. This is true in the same sense that `{num: 1 | 2}` is a subtype of `{num: number}`; it is, provided that we neglect writable values imposing contravariance constraints.

What this suggests as an alternative, sound(ish) procedure is to therefore consider the type `T & exists<S> K<S>`, and repeatedly simplify it until it can be expressed entirely in TypeScript without any `exists` operator (alternatively, add an `exists` type operator to TypeScript, and just perform simplification while doing the above).

This partly simplifies the view of what must be done- many easy cases fall out immediately. The main problem are object and intersection types (since they have fields, and those fields must be compared against the existential) whereas all other instances are either `never` or the most general value possible (i.e. what you get when you plug in `unknown` or the generic constraints for the type, assuming it's covariant, or `never` if it's contravariant).

**Comment by fatcerberus** [comment]
```ts
const a: {f:1|2} = {f: 1};
const b: {f:number} = a;
b.f = 3;
```

This kind of blew my mind.  Thinking about it, I guess enforcing the contravariance here might be too restrictive in practice; it would effectively make all objects invariant unless they consisted of nothing but `readonly` or `writeonly` properties—the latter of which doesn’t even exist in TS.

Still thought-provoking, though.

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
