### PR TITLE
Port #6769 to release-1.8

### PR DESCRIPTION
**Pull request by zhengbli**
(cherry picked from commit 064de382cf347bae70b5e998b9b094aaab0522eb)

Port PR #6769 to release-1.8

### CODE REVIEW

**Comment by mhegazy** [comment]
why are we porting this to 1.8?

**Comment by zhengbli** [comment]
Are there concerns not to do so? I thought the routine updates are ported as long as the release was not done yet.

**Comment by mhegazy** [comment]
we have forked 1.8 already, we should only port changes bound to the release. so i would leave this change in 2.0, but not port it to 1.8 unless there is a need for that (i.e. address a 1.8 issue).

**Comment by zhengbli** [comment]
Got it. Thanks!

**Pull request closed without merging**
