### PR TITLE
Make initial incremental/watch builds as fast normal builds

### LINKED ISSUE #34119: tsc --watch initial build 3x slower than tsc
**TypeScript Version:**  3.7.0-dev.20191011, 3.6.4, 3.5.2

**Search Terms:** 
DeepReadonly
slow watch mode

**Code**

The slowness occurs on a codebase of around 1000 files. I can't distill it into a repro, but I can show the type that causes the slowness and an alternate type that does not.

I noticed the slowness when I replaced our implementation of `DeepReadonly` with the one from `ts-essentials`. One thing I should note in case it is helpful, is that in our codebase `DeepReadonly` is only used about 80 times. It's also used nested in some instances, a DeepReadonly type is included as a property of another DeepReadonly type, for example.

Here is the type from `ts-essentials`:

```ts
export type Primitive = string | number | boolean | bigint | symbol | undefined | null;
/** Like Readonly but recursive */
export type DeepReadonly<T> = T extends Primitive
  ? T
  : T extends Function
  ? T
  : T extends Date
  ? T
  : T extends Map<infer K, infer V>
  ? ReadonlyMap<K, V>
  : T extends Set<infer U>
  ? ReadonlySet<U>
  : T extends {}
  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }
  : Readonly<T>;
interface ReadonlySet<ItemType> extends Set<DeepReadonly<ItemType>> {}
interface ReadonlyMap<KeyType, ValueType> extends Map<DeepReadonly<KeyType>, DeepReadonly<ValueType>> {}
```

Here is ours:

```ts
export type Primitive = number | boolean | string | symbol
export type DeepReadonly<T> = T extends ((...args: any[]) => any) | Primitive
  ? T
  : T extends _DeepReadonlyArray<infer U>
  ? _DeepReadonlyArray<U>
  : T extends _DeepReadonlyObject<infer V>
  ? _DeepReadonlyObject<V>
  : T
export interface _DeepReadonlyArray<T> extends ReadonlyArray<DeepReadonly<T>> {}
export type _DeepReadonlyObject<T> = {
  readonly [P in keyof T]: DeepReadonly<T[P]>
}
```

**Expected behavior:**

Both types, when used in our codebase would take a similar amount of time for both a `tsc` and the initial build of `tsc --watch`. 

**Actual behavior:**

Our original `DeepReadonly` takes about 47 seconds to build using `tsc`. The initial build with `tsc --watch` also takes a similar amount of time, around 49 seconds.

With the `ts-essentials` version, a `tsc` build takes around 48 seconds. The initial build with `tsc --watch` takes anywhere from 3-5 minutes.

**Playground Link:** 

N/A

**Related Issues:** 

None for sure.

### LINKED ISSUE #34916: [3.6.3] `tsc --watch` extremely slow (regular `tsc` compiles fine).
For my codebase, compilation with `--watch` is extremely slow and sometimes results in the out-of-memory segfault. Compilation w/o `--watch` take 4s.

Can be reproduced in this repo: https://github.com/bryntum/chronograph/ (publicly available, branch `quark_master`, revision c58bc18120021423c730c9c2287058066157b8fa).

I found a similar issue, #34119 and tried few recommendations from it. Notably, tried to enable
```
        "declaration"               : true,
        "emitDeclarationOnly"       : true,
```
which produced 251 compilation errors. W/o those options all compiles fine.

It seems the incremental compilation uses some different data structures, than normal compilation. Or, may be, the serialization format is incorrect.

### LINKED ISSUE #35729: Build watch takes 30x as long as cold build, high transformTime
**TypeScript Version:**  3.7.3 and 3.4.5

**Search Terms:** transformTime, Watch, Slow compilation

**Code**

When building our source code, we can do a cold build in about 25 seconds, but a watch build takes 15 minutes to start on Typescript 3.4.5. On Typescript 3.7.3, the watch time doubles to 30 minutes (60x as slow).

Running extended diagnostics shows that the vast majority of the time (96%) is spent on "transformTime". Is there any way to speed this up, as I do not consider our project too large on the grander scale (600k LOC). 

One thing that was causing slow builds that I already fixed and ruled out was the inlined type definitions bug mentioned in #34119, which cut my build time by a third. But even after this, I still get a very slow `transformTime`.

```
Files:                  3043
Lines:                637432
Nodes:               2372135
Identifiers:          850259
Symbols:             1167934
Types:                462989
Memory used:        2036527K
I/O Read time:         1.03s
Parse time:            2.81s
Program time:          6.12s
Bind time:             3.05s
Check time:           11.54s
transformTime time:  473.05s
commentTime time:      0.14s
I/O Write time:        0.43s
printTime time:      474.27s
Emit time:           474.27s
Total time:          494.99s
```

**Expected behavior:**

Watch build is slightly slower than cold build

**Actual behavior:**

Watch build is significantly slower

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by sokra**
Current just running `tsc` is much faster compared to `tsc --watch` or `tsc --incremental`. There are already multiple issues describing that problem (I didn't verify all of them if it's really the same problem):

* fixes #34119
* fixes #35729
* #32826
* fixes #34916
* #25023
* https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/463
* https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/506
* https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/453
* https://github.com/vercel/next.js/pull/13529
* VSCode language service performance is probably also affected

After digging in the source code for a while I think I found the cause of that:

For incremental or watch builds typescript need to compute 2 additional things for each module:
the "shape" and the "referenced modules".

These things are needed to calculate which modules need to be invalidated when a file has changed.
Where a file has changed typescript calculates a new "shape" and if the new shape differs from the old one, it will follow the graph of "referenced modules" upwards and invalidates these modules too (recursively).

Currently typescript uses "emit as declaration file" to calculate the "shape" and "referenced modules" and this is basically as expensive as doing a full "emit". Most time of the initial build is spend with that.

So the initial incremental/watch build is as slow as running tsc with emit.
But tsc --noEmit is very fast compared to that.

## Refactoring idea

I think we actually don't really need to compute the "shape" on initial build. The "shape" is only an optimization so that non-shape-affecting changes to the file don't invalidate importing modules.

I would propose to not compute the "shape" on initial build. When a change to the file happens use the module content (`version`) instead to check if we need to invalidate the parents. This will cause unnecessary invalidation if only internals has change, but that would be an acceptable trade-off (Keep in mind that typechecking is much faster than computing the shape).

In addition to that compute the "shape" when a module was invalidated in cause of a file change or an "shape"-change of an referenced module (only real "shape" changes, don't do that when we haven't computed the old shape. This avoids computing too many shapes during a watch rebuild)

Note: Due to not computing the shape we also don't have access to `exportedModulesFromDeclarationEmit` and have to use all references of the module instead. This will cause the module to be invalidated more often until the invalidation is triggered by a real shape change, which will cause it to compute its own shape and `exportedModulesFromDeclarationEmit`.

Summary: Lazy compute "shapes" and "exported modules" on first invalidation. Without old shape and exported modules: Invalidate referencing modules on file change instead of shape change. Invalidate module if any referenced modules changes instead of only exported ones.

So that's what I did.

## Benchmark

Running different test cases with a project with about 3000 files. Total time as reported by tsc. I did not do any averaging as the results are pretty clear:

with isolatedModules:

| Test case | master | This PR | Note |
|---|---|---|---|
| tsc | 23.34s | 23.01s | equal |
| tsc --incremental (initial) | 67.51s⚠️ | 24.15s | large improvement |
| (with cache, no change) | 6.79s | 6.75s | equal |
| (with cache, non shape affecting change) | 8.12s | 9.19s❗ | Initial shape computation, slower |
| (with cache, same file again) | 8.09s | 8.05s | shape is already computed, equal |
| (with fresh cache, shape affecting change) | 9.65s | 9.30s | Initial shape computation |
| (with cache, same file again) | 9.59s | 9.25s | shape is already computed |
| (with cache, same file again) | 9.58s | 9.29s | shape is already computed |
| tsc --watch (startup) | 70.98s⚠️ | 26.24s | large improvement |
| (save without change) | 0.03s | 0.03s | equal |
| (non shape affecting change) | 0.36s | 1.47s❗ | Initial shape computation, slower |
| (same file again) | 0.31s | 0.21s | shape is already computed, equal |
| (with fresh watcher, shape affecting change) | 2.11s | 1.40s | Initial shape computation |
| (same file again) | 1.49s | 1.21s | shape is already computed |
| (same file again) | 1.45s | 1.07s | shape is already computed |
| tsc --watch --incremental (initial) | 71.34s⚠️ | 26.84s | large improvement |
| (from cache) | 9.78s | 9.69s | equal |

without isolatedModules

| Test case | master | This PR | Note |
|---|---|---|---|
| tsc | 23.50s | 23.03s |
| tsc --incremental (initial) | 67.68s⚠️ | 24.02s | large improvement |
| (with cache, no change) | 6.89s | 6.77s | equal |
| (with cache, non shape affecting change) | 7.87s | 9.34s❗ | Initial shape computation, slower |
| (with cache, same file again) | 7.92s | 8.04s | equal |
| (with fresh cache, shape affecting change) | 9.55s | 9.27s | Initial shape computation, ironially faster as shapes of referencing files are not computed |
| (with cache, same file again) | 9.56s | 10.37s❗ | Initial shape computation of referencing files, slower |
| (with cache, same file again) | 9.55s | 9.70s | equal |
| tsc --watch (startup) | 71.30s⚠️ | 26.27s | large improvement |
| (save without change) | 0.03s | 0.03s | equal |
| (non shape affecting change) | 0.34s | 1.42s❗ | Initial shape computation, slower |
| (same file again) | 0.26s | 0.21s | equal |
| (with fresh watcher, shape affecting change) | 1.91s | 1.38s | Initial shape computation, ironially faster as shapes of referencing files are not computed |
| (same file again) | 1.55s | 2.15s❗ | Initial shape computation of referencing files, slower |
| (same file again) | 1.52s | 1.47s | equal |
| tsc --watch --incremental (initial) | 73.30s⚠️ | 26.99s | large improvement |
| (from cache) | 9.93s | 9.57s | equal |

[Raw data](https://gist.github.com/sokra/7fb2cb991498d6aa4d1ee3fcccaad1fc)

Summary: `tsc --incremental` and `tsc --watch` is now as fast a pure `tsc` (see ⚠️), first time changing a file in watch/incremental mode takes a small hit (see ❗).

## Test suite

All tests are passing. I updated a lot baselines as signatures are now missing from tsbuildinfo (they are `0` as marked for lazy computed), but there is no functional change.

I needed to change some tests that verify that clean build and incremental build result in the same build info, which is no longer true when signatures are lazily computed.

I disabled lazy shape computation for `unittests:: tsserver:: compileOnSave`, `unittests:: tsc-watch:: emit file --incremental` for some `compileOnSave` tests and for 8 tests using `assumeChangesOnlyAffectDirectDependencies` as the tests expect certain behavior that lazy shape computation would change. Note that the behavior is not wrong, but it doesn't fit to the test cases.

## Edge cases

There are a few edge cases one might run into:

### A

Do a non shape affecting change to file that affects the global scope (and is not a declaration file). 

Since we don't know it's non shape affecting on this first change this will need to typecheck all files.

The second change will no longer have this behavior since shape is then computed.

~Note that all CommonJS files are currently considered as "affecting global scope", so this might be a problem for commonjs projects. I guess this is a bug and CommonJS modules should probably not flagged in this way.~ Note: I fixed that.

### B

Do a shape affecting change to a file that is referenced by many other modules.

On second change this will trigger a shape computation on all referencing modules, which might cause a extra delay (similar to the initial shape computation before this PR).

We could a limit in how many shapes should be computed at maximum during a single build to avoid this. But in worst case this would make it have the performance like the current initial builds have.

## 🔍 Search Terms

slow, incremental, watch

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Please verify that:
* [ ] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `gulp runtests` locally
* [x] There are new or updated unit tests validating the change

## 📃 Motivating Example

Incremental build are unattractive compared to full builds when using typescript for typechecking with `noEmit: true`.

## 💻 Use Cases

> What do you want to use this for?

next.js

> What shortcomings exist with current approaches?

Incremental builds are too slow. So you have to choose between:

* slow uncached, but super fast cached builds (`--incremental`)
* fast uncached and cached builds (not `--incremental`)

> What workarounds are you using in the meantime?

Not using `--incremental` at all

## PS: tsbuildinfo reference list optimization

As a little extra I changed to serialization of tsbuildinfo a little bit so that duplicate lists of references are deduplicated (this is the first commit). This isn't strictly necessary, but in an intermediate version of this refactoring I just used all modules as fallback references and this resulted in an huge slowdown due to writing tsbuildinfo, so I optimized it a bit. I left it here, because it will decrease the tsbuildinfo size, which is good when it has to be transferred e. g. between CI builds.

### CODE REVIEW

**Comment by sokra** [comment]
Update:

* shape update propagation didn't work as intended. That's fixed now.
* fixed a bug where CommonJS modules were flagged as affecting the global scope. They no longer do that.
* I noticed that isolatedModules will affect the behavior, so I benchmarked that and added the results.

**Comment by sokra** [comment]
@sheetalkamat @weswigham I guess that's pretty difficult to review, since there are many changed files. If it helps we can hop on a call to walk through together. Or if there is anything else I can help with, just let me know.

**Comment by sheetalkamat** [comment]
We will be discussing this in design meeting on whether this should be default or opt in behavior. After that i will review the changes. But looking at the change, I feel like we don't need to populate signature at all just mark in state if all source files are changed files (because there was no oldState and some other conditions that mark all files as need emit or invalidate semantic cache etc) then we shouldn't compute the signature otherwise compute it. That seems like simpler and correct implementation. Again I haven't reviewed it at all, which I will do after the design meeting so that I have all inputs to review it.

**Comment by sheetalkamat** [comment]
https://github.com/microsoft/TypeScript/compare/lazySignatureCompute .. i just created commit with what meant when i said we can simplify this, obviously I haven't spent time looking at the test failures or change in deep to see if its correct and satisfies 0what you propose, 

Note that as part of design meeting #43069 we discussed that we will make this default without any option to disable this behavior. Add flag later if people ask for it.

**Comment by sokra** [comment]
> [`lazySignatureCompute` (compare)](https://github.com/microsoft/TypeScript/compare/lazySignatureCompute) .. i just created commit with what meant when i said we can simplify this, obviously I haven't spent time looking at the test failures or change in deep to see if its correct and satisfies 0what you propose,

I see what you mean. That's probably a better way to solve that, compared to my added `NOT_COMPUTED_YET` values for the signature. With that we could use `undefined` as not computed value and skip the initial compilation with the additional flag you added.

> we will make this default without any option to disable this behavior

That's great. My PR currently adds a `disableLazyShapeComputation` option which is `/*@internal*/`. Won't that be enough or should we get rid of that too. In this case we might need to change some test cases a little bit.

**Comment by sheetalkamat** [comment]
> I guess I can integrate that into the PR.

Please do

> disableLazyShapeComputation

Please remove the option and fix test cases .. you may want to add more scenarios if they were testing initial local change, then add another local change as next step to ensure that still works correctly from then on 


Also can you please pull out deduplication part in separate PR and add test that shows it for easier review and maintenance. 

Thank you for great idea and work

**Comment by sokra** [comment]
Should I also move [fix CommonJs modules no longer affecting the global scope `b7c2161` (#42960)](https://github.com/microsoft/TypeScript/pull/42960/commits/b7c2161f7157f6f6777b7837346d52b23bd61ee8) into a separate PR?

**Comment by sheetalkamat** [comment]
That would be great. Thanks.

**Comment by cnshenj** [comment]
There is one case not fully covered by the benchmark. In our project, we can easily repro the slow initial pass of watch/incremental. We also have another case that is very slow, may not be as slow as the initial pass, but slower than those benchmark test cases (those that take 8-9 seconds with or without the fix). The case is:
In VSCode, modify several files (I guess multiple files have shape affecting changes), then save them all with <kbd>Ctrl</kbd>+<kbd>K</kbd>, followed by <kbd>S</kbd>.

**Comment by sokra** [comment]
> There is one case not fully covered by the benchmark. In our project, we can easily repro the slow initial pass of watch/incremental. We also have another case that is very slow, may not be as slow as the initial pass, but slower than those benchmark test cases (those that take 8-9 seconds with or without the fix). The case is:
> In VSCode, modify several files (I guess multiple files have shape affecting changes), then save them all with Ctrl+K, followed by S.

That sounds like these files are referenced by many other files, which will all have their shape recomputed.

This PR tries to lazy compute shape to avoid to large cost on initial build. Once lazy computed, performance will be equal to eager computation.

Currently once a shape is computed it will keep computing it, to keep it up-to-date. Technically it's possible to throw the old shape away and go back to lazy mode. E. g. once the shapes that need to be computed grows over a certain threshold. But I guess that's something for a follow-up PR.

**Comment by sokra** [comment]
> [`lazySignatureCompute` (compare)](https://github.com/microsoft/TypeScript/compare/lazySignatureCompute) .. i just created commit with what meant when i said we can simplify this, obviously I haven't spent time looking at the test failures or change in deep to see if its correct and satisfies 0what you propose,

I made a few changes to this for the following reasons:

* Once a signature have been computed we can't ignore it as it would get out of date. So I renamed the flag to `avoidInitializingSignatures`
* When changing files or adding new files, this would eagerly compute the signature of them. That's fine when it's only a single file, but it would affect performance heavily when changing/adding many files.
  * e. g. switching branches
  * This also happens when the config file has errors that get fixed (see tests/baselines/reference/tsbuild/watchMode/noEmitOnError/does-not-emit-any-files-on-error-with-incremental.js). In that case there are a lot unprocessed files in `changedFilesSet` in the oldState.
  * I added a threshold for these cases (`> 3` changed/new files will avoid shape computation).

**Comment by sokra** [comment]
> Technically it's possible to throw the old shape away and go back to lazy mode. E. g. once the shapes that need to be computed grow over a certain threshold.

@cnshenj Actually this is quite easy to implement:

Could you try this branch? https://github.com/sokra/TypeScript/tree/performance/lazy-shape-fallback

It has this additional commit: https://github.com/sokra/TypeScript/commit/faee29ff8333ce0efb33aef1efa5124fce1a890b

**Comment by sokra** [comment]
> > I guess I can integrate that into the PR.
> 
> Please do

done

> 
> > disableLazyShapeComputation
> 
> Please remove the option and fix test cases .. you may want to add more scenarios if they were testing initial local change, then add another local change as next step to ensure that still works correctly from then on

It was hard, but done

**Comment by sokra** [comment]
> Also can you please pull out deduplication part in separate PR and add test that shows it for easier review and maintenance.

https://github.com/microsoft/TypeScript/pull/43079

> Should I also move [fix CommonJs modules no longer affecting the global scope `b7c2161` (#42960)](https://github.com/microsoft/TypeScript/pull/42960/commits/b7c2161f7157f6f6777b7837346d52b23bd61ee8) into a separate PR?

https://github.com/microsoft/TypeScript/pull/43090

**Comment by sokra** [comment]
@sheetalkamat rebased

**Comment by sokra** [comment]
> Will be reviewing this today sometime later after I manage DT queue and some other PR reviews.

Awesome. Just tell me if there is anything I can help you with.

**Comment by sheetalkamat** [comment]
@sokra please dont bother updating the PR with conflicts, i am looking into simplifying this change and will update you once i have some results. Meanwhile i am using this branch for the tests you have already taken efforts to update.

**Comment by sokra** [comment]
> please dont bother updating the PR with conflicts

ok. It's a little bit hard to look at these conflicts and don't wanting to fix them...

Maybe you could look at the baselines of `when global file is added, the signatures are updated`? I think the test case may no longer test that signatures are updated, since they are not even computed with this change.

**Comment by sokra** [comment]
The major change of this PR has been merged as #43314

**Comment by piotr-oles** [comment]
Is it released?

**Comment by sokra** [comment]
The latest beta version includes the fix

**Comment by ndr47** [comment]
I vote for having this feature optional.

I am encountering some errors after these release.
The errors appear only on `--watch` and not when I build the project.

**Comment by amcasey** [comment]
@ndr47 Can you provide more details?  What functionality would you like to be optional?  This PR has evolved quite a bit since it was created, but I believe the intention was to make some watch mode functionality lazier, which I wouldn't to expect non-watch builds at all (or affect the errors produced by watch builds - just the speed at which they are produced).

I believe the most common reason for seeing different errors in different build modes is that compilation depends on input file ordering (e.g. because the same type is provided by two different files, possible versions of the same library).

**Comment by sokra** [comment]
Another part merged here: https://github.com/microsoft/TypeScript/pull/44090

**Comment by sandersn** [comment]
Coming back to this after a long time -- are there any parts left over that haven't been merged as other PRs?

**Comment by stwlam** [comment]
@sandersn I wonder: is your question answerable at this point?

**Comment by sandersn** [comment]
I had forgotten about this PR. Regardless of whether its features have been included piecemeal over the past couple of years, it's so old that it would need to be restarted anyway. I'm going to close it.

**Pull request closed without merging**
