### PR TITLE
Move .js/.ts content of the npm package to lib folder

### LINKED ISSUE #3408: Error loading file from typescript package in bin folder due to IIS restriction (404s)
This issue came to light while trying to use this plugin for SystemJS... I filed an issue there and they suggested I also make one over here.

https://github.com/frankwallis/plugin-typescript/issues/22#issuecomment-109778529

The bin folder is blocked in IIS out of box so when installing your typescript plugin I got 404s when it attempted to download the typescript.js file from the bin folder of the typescript package... I'm not sure who publishes that or if you can work around it but it is a blocker for using this on IIS. Whoever maintains the typescript package you use should add a web.config allowing browsing of the bin folder or rename the bin folder something else that isn't blocked (preferred).

web.config contents to fix it below:

```xml
<configuration>
  <system.webServer>
   <security>
     <requestFiltering>
        <hiddenSegments applyToWebDAV="false">
           <remove segment="Bin" />
        </hiddenSegments>
     </requestFiltering>
   </security>
  </system.webServer>
</configuration>
```

### PR DESCRIPTION
**Pull request by vladima**
Fixes #3408

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
@billti can you take a look

**Comment by vladima** [comment]
pinging @billti, can you please take a look?

**Comment by billti** [comment]
:+1:

**Pull request merged**
