### PR TITLE
Add VSTS Build status badge to README

### PR DESCRIPTION
**Pull request by weswigham**
With this, VSTS should have everything enabled that we use Travis for (including cron jobs) - and it looks like it's reliably finishing (much) faster than travis.

@mhegazy Should I add a windows build to VSTS to make up for no longer using jenkins (which AFAIK built on windows)?

### CODE REVIEW

**Comment by mhegazy** [comment]
Most of the team are on windows. i think we catch these locally. better save some trees and only run the tests on one platform

**Comment by weswigham** [comment]
🤷‍♀️

**Comment by mhegazy** [comment]
why do we need the extra badge anyways, is not travis enough?

**Comment by weswigham** [comment]
@mhegazy It's more like "this was the last thing VSTS was missing from our repo, and once it's in we can safely remove travis without loss of functionality".

**Pull request merged**
