### PR TITLE
Weaken the definition of PromiseLike to allow 'T | awaited T'

### PR DESCRIPTION
**Pull request by rbuckton**
This weakens the definition of `PromiseLike` to allow the `value` argument to be `T | awaited T`. This is necessary because `PromiseLike` represents *any* promise-like value that can be *adopted* by a native `Promise`. This includes Promise definitions that are *not* Promise/A+ compatible, such as JQuery's `Deferred`. As a result, the `value` argument may or not be recursively unwrapped depending on the implementation.

This is intended to work in conjunction with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43337 to address errors in DefinitelyTyped and other projects following the introduction of `awaited`.

NOTE: this means that unlike with `Promise`, a `PromiseLike<Promise<number>>` will *not* be assignable to `PromiseLike<number>`, as the value may not be recursively unwrapped and therefore we cannot guarantee they are relatable.

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by falsandtru** [comment]
Can you explain some actual problems caused by the current correct definition? If you weaken the definition, I have to define my correct PromiseLike interface to strictly check the types.

**Comment by sandersn** [comment]
The user tests look pretty bad with this change. But I don't know what they were like before. Have they been this broken since first merging `awaited` ?

**Comment by falsandtru** [comment]
See also my first fix https://github.com/falsandtru/spica/commit/c569afd65410a8f5538f38aef617fae9657b7d20

We need `strictAwaitedTypes: false` by default (probably even when strict flag is enabled for a while). And strictAwaitedTypes must always be disabled in the dependencies as the other stricter checking flags has been. Currently I can't use the latest nightly build because it can't compile @types/jquery.

**Comment by rbuckton** [comment]
Closing in favor of #37610 while we continue to investigate the impact of `awaited`.

**Pull request closed without merging**
