### PR TITLE
Show the index of a tuple member when hovering on it

### PR DESCRIPTION
**Pull request by orta**
```ts
export type /*1*/Segment = [/*2*/length: number, /*3*/count: number];

verify.quickInfoAt("1", "type Segment = [length: number, count: number]");
verify.quickInfoAt("2", "(index: 0) number");
verify.quickInfoAt("3", "(index: 1) number");
```

For those of us lucky enough to be working with the occasional triple digit tuples. Instead of writing comments next to every 5 indexes, it allows TypeScript to inline that info in the hover. 

Follows the design pattern established in symbolDisplay e.g. `(enum member) SymbolFlags.Enum = 384`

### CODE REVIEW

**Comment by fatcerberus** [comment]
> triple digit tuples

👀

**Comment by ahejlsberg** [comment]
@orta Whatever you're doing with those triple digit tuples, it better be good!

**Comment by orta** [comment]
Hah, yeah, only 1 at three digits right now - it's a pretty tightly packed data structure for all different stats which might affect one user across many types of games (which each have their own solid 2 digit tuples), so I codegen a mega-tuple to describe what is happening when they all combine and the client has to try make some sense of it

**Review by jakebailey — COMMENTED** [review]
Code LGTM, though I have absolutely no idea if this is an accepted feature or not in general (absent a linked issue saying one way or another) 😅

**Review by iisaduan — APPROVED** [review]
This feature looks good to me, although I will note that there are no indices when using the tuple type. For example, in

``` 
type t = [x:string];
const s : string = "hi";

const a : t = [/**/s]; 
const b : t = [/**/"hello"]; 
```
both of the indicated locations do not show indices in quickInfo.

**Comment by RyanCavanaugh** [comment]
I'm really not understanding the use case here - if this type is codegend then you can generate the index numbers, or make the index part of the name, and it's not clear to me why you'd need to know that something is at index 153. Let's follow the process on getting the change approved first please.

**Pull request closed without merging**
