### PR TITLE
Fixed inferred const rest types in signatures

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/55033

### CODE REVIEW

**Comment by ssalbdivad** [comment]
Pretty hyped for this one. I've run into so many issues trying to constraint narrowed array types without breaking inference. Couldn't really tell from the linked issue if this will fix a lot of them, but I have faith 🙏

**Comment by jakebailey** [comment]
After messing with this same code for #53255, #53258 (note a similar `getRestTypeAtPosition` change), #53398, I'm like 50% afraid of this 😄 

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by Andarist** [comment]
> After messing with this same code for https://github.com/microsoft/TypeScript/issues/53255, https://github.com/microsoft/TypeScript/pull/53258 (note a similar getRestTypeAtPosition change), https://github.com/microsoft/TypeScript/issues/53398, I'm like 50% afraid of this 😄

When learning about this issue I immediately opened your PR to check out if it's related anyhow to this issue. I think that at the end of the day, it isn't and that this PR shouldn't actually impact anybody negatively. This only makes those rests readonly when the type variable is `const` - given that `const` is pretty new I don't expect any accidental breakage here.

**Comment by sandersn** [comment]
The bug is marked Working As Intended now, so should we close this PR?

**Comment by Andarist** [comment]
The reported issue had some issues in it (it didnt use a readonly constraint). So im not sure if „working as intended” was applied to only what was oroginally reported or if it was applied to everything that was discussed there. I think that this particular thing that I fixed here still has some merit so i’d appreciate if this would get reviewed

**Comment by ahejlsberg** [comment]
I like where this is going, but I think we also need the changes in #55229. For example, the following is broken by this PR without the additional changes:

```ts
declare function invoke<const T extends unknown[]>(f: (...args: T) => void, ...args: T): T;

invoke((a: string, b: number) => {}, "hello", 123);
```

I know this isn't a particularly likely break, but the inference failure because of non-readonly constraints is just confounding to most users and hard to justify (even if I've tried).

**Comment by Andarist** [comment]
> I know this isn't a particularly likely break, but the inference failure because of non-readonly constraints is just confounding to most users and hard to justify (even if I've tried).

ye, this tends to be pretty confusing - would it be worth adding some diagnostics that would prompt users to add the `reaodnly` modifier to their constraints? Might not be feasible when constraints are defined using aliases but catching common cases when they are declared directly in the signature could still help a lot 🤔

**Comment by ahejlsberg** [comment]
> would it be worth adding some diagnostics that would prompt users to add the reaodnly modifier to their constraints?

I'm hoping there's no need for that with #55229 since inference now adjusts itself based on constraints.

**Pull request closed without merging**
