### PR TITLE
Avoid removing indentation on a new line as trailing white spaces

### LINKED ISSUE #7022: 0.10.8 Salsa Intellisense does not keep indentation level on new lines
_From @lionpants on February 10, 2016 21:6_

I've followed the setup instructions found on https://code.visualstudio.com/updates#vscode to get the Salsa preview working.

Upon enabling Salsa, when pressing Enter to go to a new line; the cursor will always jump to the beginning of the line instead of keeping the indentation level of the line before it, this happens in JavaScript files.

I'm not sure if this was caused solely by Salsa or a combination of other settings. But when turning Salsa off, the indentation works properly again.

Here is my config before adding the Salsa config path.

```
// Place your settings in this file to overwrite the default settings
{
    // Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
    "editor.tabSize": 4,
    // Controls if the editor will insert spaces for tabs. Accepted values:  "auto", true, false. If set to "auto", the value will be guessed when a file is opened.
    "editor.insertSpaces": true,
    // Controls after how many characters the editor will wrap to the next line. Setting this to 0 turns on viewport width wrapping
    "editor.wrappingColumn": 0,
    // Controls if the editor should automatically format the line after typing
    "editor.formatOnType": true,
    // Complete functions with their parameter signature.
    "javascript.suggest.useCodeSnippetsOnMethodSuggest": false,
    // When enabled, will trim trailing whitespace when you save a file.
    "files.trimTrailingWhitespace": true
}
```

_Copied from original issue: Microsoft/vscode#2907_

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #7022 and #6700.

[Review on Reviewable](https://reviewable.io/reviews/microsoft/typescript/7307)

### CODE REVIEW

**Comment by zhengbli** [comment]
pinging @vladima

**Comment by billti** [comment]
:+1:  Can you port to `release-1.8` also? Thanks!

**Comment by mihailik** [comment]
Shouldn't it have tests?

**Comment by zhengbli** [comment]
@mihailik normally it should. Though in this case turns out it is hard to test the behavior, as VSCode indents first and then send the buffer content to the server for formatting; while VS formats first, and then ask the language service about the indentation; and our fourslash tests mimic's VS' behavior. So there is no way to know if a inserted indentation would be removed, as the test suite doesn't insert indentation. I've tested on VS and VSCode to make sure it solves the issue.

**Comment by mihailik** [comment]
I'm not doubting it works, just for the sake of preventing regressions.

Wouldn't fourslash work for this case? I've found this example of testing indentation:

https://github.com/Microsoft/TypeScript/blob/master/tests/cases/fourslash/alignmentAfterFormattingOnMultilineExpressionAndParametersList.ts

**Comment by zhengbli** [comment]
You are right verifying indentation is possible. Though the issue here is to verify the indentation after the "format on enter", which is different from formatting the whole document. For example:

```ts
function test() { // hit enter here
    | // cursor location afterwards
}
```

In this case, if you are in the "format on enter" case, the indentation in the current line shouldn't be removed, as you are typing. However if you are formatting the whole document, it should be removed because these are trailing whiltespaces, and formatting the whole document shouldn't be affected be cursor location. I'm saying that testing the former one is difficulty for now.

**Comment by mccreeker** [comment]
This seems really overly-complicated for determining whether a line should have an indent or the spacing be removed... I don't think other editors check with servers and go through multiple checks and edits like this.

By the way, the problem is happening in .php files with PHP or HTML code, so I'm not sure how TypeScript is involved.

**Pull request merged**
