### PR TITLE
Improve zh-cn and zh-tw diagnostic messages

### PR DESCRIPTION
**Pull request by kidonng**
Fix typo and ambiguous diagnostic messages in zh-cn and zh-tw.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
These are generated (as the names imply) but @Pdostalek might be able to help bring in this work. @PDostalek, can these suggestions be recommended to the appropriate translators?

**Comment by kidonng** [comment]
@DanielRosenwasser Sorry for the inconvenience, but I couldn't find the proper place to submit these translation and submitted a PR instead. It would be helpful if you can suggest these changes to the translators.

**Comment by danyeh** [comment]
It is true that translation change only can be made in loc platform, then export to repo. Change outside this process will be overwritten.
The suggested change has been implemented in loc platform and exported. For example, https://github.com/microsoft/TypeScript/blob/master/src/loc/lcl/chs/diagnosticMessages/diagnosticMessages.generated.json.lcl#L6805
Thank you for your feedback. This PR can be closed.

**Comment by DanielRosenwasser** [comment]
Thanks @danyeh!

**Pull request closed without merging**
