### PR TITLE
feat(25758): Computed properties no throws if there is a duplicate

### LINKED ISSUE #25758: Computed properties no throws if there is a duplicate
**TypeScript Version:**  3.0.0-dev.20180712

**Search Terms:**

**Code**

```ts
const A = 'a';
const x = {[A]: 1, [A]: 'b'} // x is {[A]: string}
```

**Expected behavior:**
Duplicate declaration error

**Actual behavior:**
No error

**Playground Link:** https://www.typescriptlang.org/play/#src=const%20A%20%3D%20'a'%3B%0D%0Aconst%20x%20%3D%20%7B%5BA%5D%3A%201%2C%20%5BA%5D%3A%201%7D%0D%0A

**Related Issues:**

### LINKED ISSUE #43186: Duplicate object keys not caught when using variables
# Bug Report

### 🔎 Search Terms

duplicate string identifiers 
duplicate keys in object

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about duplicate/keys/properties
- In the playground 3.3.3 doesn't have any support for duplicate keys and 3.5.1 has support for ids but this bug exists

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUAk6Ca0hmVABeUACINZPQG5Fy+KprjdAb0WgHoANp6AZvHh6AugC5QARl57Rxd3T19QACYgx2dDCIBmGJD4vwAWIIBfYyA)

### 💻 Code

```ts
const bar = "bar";

const a = {
    ["foo"]: 1,
    ["foo"]: 2, // Error
    [bar]: 3,
    [bar]: 4, // Not Error
};
```

### 🙁 Actual behavior

The second instance of `bar` is allowed.

### 🙂 Expected behavior

The second instance of `bar` as an input should not be allowed.

### Additional

When you introduce `bar` as a key in any other form it causes the error I would expect with just the variables.

[Playground link to this scenario](https://www.typescriptlang.org/play?ts=4.2.3&ssl=10&ssc=3&pln=9&pc=5#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUAk6Ca0hmVABeUACINZPQG5Fy+KprjdAb0WgHoANp6AZvHh6AugC5QARl57Rxd3T19QACYgx2dDCIBmGJD4vwAWZIdDPwBWIIBfYyA)

```ts
const bar = "bar";

const a = {
    ["foo"]: 1,
    ["foo"]: 2, // Error
    [bar]: 3,
    [bar]: 4, // Error
    bar: 5, // Error
};
```

### LINKED ISSUE #49666: Object literals allow duplicate `[Enum.member]: ...` keys
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDA3gWAFA2zA2gRgF0AuGAJgBpMc8jTLMB6R7APXZgFEAlbgeW6kAgmBggARgCsApsFgAbAJZRpAJwCG8mMHVgwIWAAt1AN2kwAtgFd5URQAd55+6pD21d6RBgB3ZYZgoQ3MIdQtzMDDpADoYAAp8RIB2AEpMAF8AbkxMaTArCy58wpQYADMQECQYfAoYdJyMUEhYAE9q9CwcXE5i6IqQEnIqLuwevoGhhgxmNnZ5hZgAOSrOVVdVDMygA)
    
### 💻 Code

```ts
const x = {
    [1]: 2,
    [1]: 2,
//  ^^^ ERROR: An object literal cannot have multiple properties with the same name. (1117)
};

enum Enum { foo = 1, }

const y = {
    [Enum.foo]: 2,
    [Enum.foo]: 2,
//  ^^^^^^^^^^ No Error
};
```

### 🙁 Actual behavior

Defining an object literal with duplicate keys throws an error for literal `1` but not for enum member `Enum.foo`

### 🙂 Expected behavior

Defining an object with duplicate keys from enum members throws an error
```ts
    [Enum.foo]: 2,
    [Enum.foo]: 2,
//  ^^^^^^^^^^ An object literal cannot have multiple properties with the same name
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #25758
Fixes #43186
Fixes #49666

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test top100

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this but maybe work this time?

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Performance doesn't seem to have changed significantly., I used a similar approach that https://github.com/microsoft/TypeScript/pull/45974 used before - not sure if it's acceptable in this case.

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
Checking https://github.com/microsoft/TypeScript/pull/49848/files?w=1 this feels okay to me. This has been in review for a while. Are there any other concerns here?

**Comment by a-tarasyuk** [comment]
@weswigham, could you review this PR when you have a chance?

**Comment by a-tarasyuk** [comment]
@weswigham, could you review this PR when you have a chance?

**Comment by a-tarasyuk** [comment]
@weswigham Thanks

**Pull request merged**
