### PR TITLE
add Array.prototype.filter signature with type guard

### PR DESCRIPTION
**Pull request by maiermic**
> # 10027 also didn't add the overload to Array#filter, only to ReadOnlyArray#filter. @mhegazy could you reopen this issue?
> 
> -- [Arnavion's comment](https://github.com/Microsoft/TypeScript/issues/7657#issuecomment-246149971)

> This only adds it to ReadOnlyArray though. Also need it for regular Array.
> -- [Arnavion's comment](https://github.com/Microsoft/TypeScript/pull/10027#issuecomment-246149856)

See #7657 and #10027

### CODE REVIEW

**Comment by mhegazy** [comment]
thanks @maiermic, some baslines changed, you will need to do a `gulp baseline-accept`

**Comment by maiermic** [comment]
@mhegazy Thanks, I appreciate your help.

**Comment by mhegazy** [comment]
waiting on the CI.

**Comment by maiermic** [comment]
@mhegazy Two tests failed on my machine. I ran `gulp baseline-accept` a second time and it modified two more files. I guess all tests will pass now, but this time I wait until my local test runner is done.

**Comment by bcherny** [comment]
@mhegazy Is it possible to merge this?

**Comment by mhegazy** [comment]
Sorry this fell off my list for a while. one more comment, we need to update the filter method on ReadOnlyArray, and the TypedArray varients, e.g. Int32Array (all in the same file).

**Comment by maiermic** [comment]
@mhegazy This pull request only updates `filter` on `Array`. I updated `filter` on `ReadOnlyArray` in #10027 (already merged). TypedArray varients cann't use a type guard. They are not generic and contain always the same type. No update possible. So it should be possible to merge this.

**Comment by ikokostya** [comment]
Any updates here?

**Comment by ikokostya** [comment]
@mhegazy Could you review again taking into account latest comment https://github.com/Microsoft/TypeScript/pull/10916#issuecomment-273578660?

**Comment by teppeis** [comment]
@maiermic @mhegazy any updates? I could resolve the conflicts and create new pr if you need.

**Comment by maiermic** [comment]
@teppeis Conflicts are resolved by my latest update. I'm waiting for @mhegazy to merge.

**Comment by NaridaL** [comment]
What's the status on this?

**Comment by mysticatea** [comment]
@mhegazy @maiermic What is happening with this?

**Comment by maiermic** [comment]
This has been solved by #16223 in the meantime.

**Pull request closed without merging**
