### PR TITLE
Add undefined to JSON.stringify return type

### LINKED ISSUE #18879: Type signature for JSON.stringify does not include undefined in the return type
Although calling `JSON.stringify` may return undefined (as documented here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description), it is not included in the type signature provided with TypeScript.

### PR DESCRIPTION
**Pull request by ronyhe**
Add undefined to JSON.stringify return type when input value is Function | Symbol | undefined
Fixes #18879

### CODE REVIEW

**Comment by polkovnikov-ph** [comment]
Even though this is kind of better than it was before, there's still a variety of cases when this typing fails.

```typescript
JSON.stringify({toJSON: () => undefined})
```

**Comment by ronyhe** [comment]
> Even though this is kind of better than it was before, there's still a variety of cases when this typing fails.
> 
> ```ts
> JSON.stringify({toJSON: () => undefined})
> ```

Do you have a suggestion as to how to approach this?

**Comment by ronyhe** [comment]
I see that some test are failing, but when I run them on my machine the only diffs I see are carriage returns removals (^M).
The `--ignore-cr-at-eol` flag doesn't seem to help.
Any ideas?

**Comment by ronyhe** [comment]
> 

@microsoft-github-policy-service agree [company="Wix.com"]

**Comment by polkovnikov-ph** [comment]
> Do you have a suggestion as to how to approach this?

[Something like this.](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgzgKTgewHYB4AqA+KBeAWACgpSpMoIAPYCVAEzijmACcBLVAcygB8pUAVwC2AIwis+UUcmQAbCAENUUoXLlQA-OSgAuYmR3VaDJgApOAMwlQAGgEoA2gF0tsRCgy3sLvQbIUxnSMUMiiAFYQAMbAWv6GpADkwMgIAMoA8gByiZQ0wUwA1hAgyJbk8QmG2qgQAG4SlVWkulAA3lCOANJQnFDFpeWYzq3wSGhY3c64AL6VrbUNrMTE9NFyiqzQUWgsUJatWAA02GbhnqMeEzj2+LgsHNwA3CtElmaObQAWEOrIrYkAO7IVhyeiJGbOewvN5mNopdLZVoARhm0KAA)

Once I wrote down "correct" types for JSON methods, and those were utterly dreadful. Correct approach is to reexport them somewhere in your project with types tightened as much as possible (without any replacers and overloads).

**Comment by ronyhe** [comment]
Do you think this might work?
```ts
declare function stringify<T>(value: T): 
    T extends {toJSON(): (infer X)} ? X 
    : T extends Function | Symbol | undefined ? undefined 
    : string;
```

**Comment by ronyhe** [comment]
>  It doesn't pay off.

Then let's leave the `toJSON` issue alone. We can add the changes from this PR to improve the current state of affairs without solving everything.
According to the issue people have been tripped up by this

**Comment by ronyhe** [comment]
I'm considering extracting out the replacer type:
```ts
type JsonReplacer = number[] | string[] | ((this: any, key: string, value: any) => any)

interface JSON {
    /**
     * Converts a JavaScript Object Notation (JSON) string into an object.
     * @param text A valid JSON string.
     * @param reviver A function that transforms the results. This function is called for each member of the object.
     * If a member contains nested objects, the nested objects are transformed before the parent object is.
     */
    parse(text: string, reviver?: (this: any, key: string, value: any) => any): any;
    /**
     * Converts a JavaScript value to a JavaScript Object Notation (JSON) string.
     * @param value A JavaScript value, usually an object or array, to be converted.
     * @param replacer An array of strings and numbers that acts as an approved list for selecting the object properties that will be stringified.
     * @param space Adds indentation, white space, and line break characters to the return-value JSON text to make it easier to read.
     */
    stringify(value: Function | Symbol | undefined, replacer?: JsonReplacer | null, space?: string | number): undefined;
    /**
     * Converts a JavaScript value to a JavaScript Object Notation (JSON) string.
     * @param value A JavaScript value, usually an object or array, to be converted.
     * @param replacer A function that transforms the results.
     * @param space Adds indentation, white space, and line break characters to the return-value JSON text to make it easier to read.
     */
    stringify(value: any, replacer?: JsonReplacer | null, space?: string | number): string;
}
```
Any thoughts?

**Comment by MartinJohns** [comment]
@ronyhe What for? It's only used twice, and moving it to a dedicated type is yet another potential break (if someone has such a type defined). Also, the TypeScript team generally doesn't want to add more utility types:

https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes

**Comment by ronyhe** [comment]
> @ronyhe What for?
The original replacer type has two options (not including `null`). I suppose that's the reason for the existing overload.
In order to make this complete I'll need to add another overload with the second option or use a (less readable, IMO) union type.
So the options here are:
- Extract to utility type
- Union type
- Another overload
WDYT?

**Comment by MartinJohns** [comment]
> So the options here are:
> 
> * Extract to utility type
> * Union type
> * Another overload

I don't understand this. Extracting it to a utility type it's still a union. And overloads are not interchangeably with unions, they behave very much different.

**Comment by ronyhe** [comment]
@MartinJohns Yes, I suppose you're right.
The further I think about, the more I'm coming to the conclusion that the PR should simply remain as-is.
Achieving completeness might prove problematic since the replacer function may actually handle the cases that lead to an `undefined` result.
I think that the PR in its current state is quite helpful, it will help others avoid a pitfall without adding too much complexity.
As far as I'm concerned this PR is ready for review and for merging.
WDYT?

**Comment by sandersn** [comment]
This looks reasonable to me and I can't think of ways for it to break existing code. I'm going to run some user tests on it to double-check.

@typescript-bot user test this
@typescript-bot test top100
@typescript-bot run dt

**Review by sandersn — APPROVED** [review]

**Comment by polkovnikov-ph** [comment]
That was totally unexpected.

Great job, @ronyhe!

**Comment by ronyhe** [comment]
Thanks @polkovnikov-ph and thank you @MartinJohns and @sandersn for the help!

**Pull request merged**
