### PR TITLE
Fix tests changed by #11309

### PR DESCRIPTION
**Pull request by andy-ms**
Re: #11309

### CODE REVIEW

**Comment by andy-ms** [comment]
Tested this on a completely clean checkout and the test is failing in master, but works in this branch. Travis is probably caching the `built/local` directory, so it hasn't changed on travis since #11309. However, our `.travis.yml` lists `node_modules` as the only cached directory.

**Comment by mhegazy** [comment]
Do not think this is needed any linger. can we close it?

**Comment by sandersn** [comment]
It still fails with gulp. @andy-ms figured out that it was a mismatch between the Gulpfile and the Jakefile, so I added the newlines to the Jakefile and it's now working. I'll push the commit with the Jakefile change to this PR.

**Comment by andy-ms** [comment]
:+1:

**Pull request merged**
