### PR TITLE
fix(39373): const {} = require import causes Debug Failure

### LINKED ISSUE #39373: const {} = require import causes Debug Failure
**TypeScript Version:** 3.8.3, 4.0.0-dev.20200701 (tested on both versions)

**Search Terms:** typescrpt importing problem (Error. Debug Failure.)

**Code**

```ts
// H is a exported class in a file called test.ts in the same directory.

// when using this line, the error is shown
const { H } = require('./test');

// when using this line, the error is gone
// import { H } from './test';

```

**Expected behavior:** When running `tsc -b`, tsc builds the project. 

**Actual behavior:** `tsc -b` returns an error.
```sh
$ tsc -b
/usr/share/nodejs/typescript/lib/tsc.js:81040
                throw e;
                ^

Error: Debug Failure.
    at Object.assertDefined (/usr/share/nodejs/typescript/lib/tsc.js:1724:24)
    at /usr/share/nodejs/typescript/lib/tsc.js:13692:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/usr/share/nodejs/typescript/lib/tsc.js:13692:21)
    at createFileDiagnostic (/usr/share/nodejs/typescript/lib/tsc.js:13712:20)
    at createDiagnosticForNodeInSourceFile (/usr/share/nodejs/typescript/lib/tsc.js:10181:16)
    at Object.createDiagnosticForNode (/usr/share/nodejs/typescript/lib/tsc.js:10171:16)
    at handleSymbolAccessibilityError (/usr/share/nodejs/typescript/lib/tsc.js:73879:50)
    at checkEntityNameVisibility (/usr/share/nodejs/typescript/lib/tsc.js:74252:13)
    at visitDeclarationSubtree (/usr/share/nodejs/typescript/lib/tsc.js:74389:29)
```

**Playground Link:** This is a problem related to importing. I don't know where can I do that.

**Related Issues:** I didn't find any related issues

**To Reproduce:** Clone this [repo](https://github.com/KSahithyan/ts-bug) to reproduce

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39373

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Generally we use `getNameOfDeclaration` or something like that to avoid duplicating the diagnostic. It'll fill it in with something like `(anonymous)` or `(default)`.

**Comment by a-tarasyuk** [comment]
Actually, `getHeritageClauseVisibilityError` uses it 
https://github.com/microsoft/TypeScript/blob/17022388bde8d37bd98ad98f8b3ed733ab7684f6/src/compiler/transformers/declarations/diagnostics.ts#L464

and it returns `undefined` for the case 
```ts
export default class extends Foo {}
```
Based on the type definition, a `name` can be `undefined`, however, that case was not handled in `getHeritageClauseVisibilityError`.

https://github.com/microsoft/TypeScript/blob/17022388bde8d37bd98ad98f8b3ed733ab7684f6/src/compiler/types.ts#L2780-L2781

For that reason, TS crashes because it uses diagnostic messages with two arguments, however, receive only one. 
https://github.com/microsoft/TypeScript/blob/17022388bde8d37bd98ad98f8b3ed733ab7684f6/src/compiler/transformers/declarations.ts#L141-L144

@DanielRosenwasser Do you propose to replace the missed `name` by creating `Identifier` with the`(anonymous)` name instead of using a new diagnostic message? I think we can do it, just need to create a new Identifier and change the logic to getting text because a new `Identifier` will not be present in the source file. 
https://github.com/microsoft/TypeScript/blob/17022388bde8d37bd98ad98f8b3ed733ab7684f6/src/compiler/transformers/declarations.ts#L134-L136

**Comment by DanielRosenwasser** [comment]
Actually I think it's fine, especially since functions have the same diagnostic.

**Comment by DanielRosenwasser** [comment]
I actually realized that the test might need to be changed to use at least one `.js` file because of #39617...

**Pull request merged**
