### PR TITLE
allow PrivateIdentifier in QualifiedName

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes https://github.com/microsoft/TypeScript/pull/47696#discussion_r846981685

### CODE REVIEW

**Comment by jakebailey** [comment]
This seems like an API change that has to happen thanks to the cast noted in: https://github.com/microsoft/TypeScript/pull/47696#discussion_r846981685

**Review by jakebailey — CHANGES_REQUESTED** [review]
We looked at this in the design meeting, and we think that it's the case that the right change is to instead make `TypeQueryNode['exprName']` be `PropertyAccessEntityNameExpression` instead of `EntityName`.

**Comment by a-tarasyuk** [comment]
@jakebailey As I understand your last comment, need to do the following list of items 

1. Change the `name` type from `Identifier` to `MemberName`

https://github.com/microsoft/TypeScript/blob/45faac7e70174d3738c9b5e290a76a4ebb67d518/src/compiler/types.ts#L2354-L2358

2. Add `PrivateIdentifier` parsing support to `parsePropertyAccessEntityNameExpression`

https://github.com/microsoft/TypeScript/blob/45faac7e70174d3738c9b5e290a76a4ebb67d518/src/compiler/parser.ts#L8449-L8457

3. Change `parseEntityName ` to `parsePropertyAccessEntityNameExpression` https://github.com/microsoft/TypeScript/blob/45faac7e70174d3738c9b5e290a76a4ebb67d518/src/compiler/parser.ts#L3191

4. Change `exprName: EntityName` to `expression: PropertyAccessEntityNameExpression` and `node.exprName = exprName;` to `node.expression = expression; ` 

https://github.com/microsoft/TypeScript/blob/45faac7e70174d3738c9b5e290a76a4ebb67d518/src/compiler/factory/nodeFactory.ts#L1885-L1891

Am I right?

**Comment by jakebailey** [comment]
I think there may have been a miscommunication when I read the notes, because maybe it's `PropertyAccessExpression` that is the one to be using here, or similar. @rbuckton @andrewbranch

**Comment by a-tarasyuk** [comment]
@jakebailey I think we can try to change `TypeQuery` from `entityName` to an expression. It will even resolve this issue https://github.com/microsoft/TypeScript/issues/19707.

**Comment by jakebailey** [comment]
Maybe; I can see that coming up in #48763.

**Comment by andrewbranch** [comment]
I think we shouldn’t change the behavior of #19707 at this point post-beta. My suggestion would be (for now) to parse only a dotted name still, and pick whatever legal type for the API makes sense. `Expression` would let us change #19707 in the future without changing the type again, but I’m not too concerned about widening the type of `TypeQuery['exprName']` more in the future if we need to.

(Note: changing `PropertyAccessEntityNameExpression` might make sense in order to make the narrowest possible type for what we will parse here, but its parsing functions and most of its existing uses are JSDoc-specific. I’m not sure it’s worth it to mess with that.)

**Comment by jakebailey** [comment]
I'm looking at this currently, and the trouble I'm seeing is that TypeQuery contains an `EntityName`, which is recursive with `QualifiedName`:

```ts
    export interface QualifiedName extends Node {
        readonly kind: SyntaxKind.QualifiedName;
        readonly left: EntityName;
        readonly right: Identifier;
        /*@internal*/ jsdocDotPos?: number;                      // QualifiedName occurs in JSDoc-style generic: Id1.Id2.<T>
    }

    export type EntityName = Identifier | QualifiedName;
```

What was broken about #47696 was that there was a cast to `Identifier` that hid the fact that while parsing entity names we now could get `PrivateIdentifier` too and add it to the chain of things in the qualified name.

So if we make `TypeQuery` have a plain `Expresssion` rather than an `EntityName`, that wouldn't change the fact that the new behavior allows `PrivateIdentifier` in a qualified name, which people in the design meeting didn't seem to like.

I almost think we should revert #47696 (then approach #19707 in a later release), unless you're seeing a more reasonable parser change here than I am. It seems like the options are:

- Make qualified name allow a private identifier in the chain (people didn't like this)
- Parse out a `PropertyAccessExpression` instead, which is a chain that allows it and is similar, but that expression could technically be something like `this.foo['xyz'].bar` which is more than a dotted name.
- Parse out `EntityNameOrEntityNameExpression` by adding private identifiers to `PropertyAccessEntityNameExpression`, somehow, but as mentioned, that's all JSDoc stuff. But, `EntityName`/`QualifiedName` are already also very weird too and aren't really reachable via normal expressions?

I do think making it `Expression` is the "right" thing long term, at least on my view of the operator being "the type of what you get when you write out this expression".

**Comment by a-tarasyuk** [comment]
> I almost think we should revert https://github.com/microsoft/TypeScript/pull/47696 (then approach https://github.com/microsoft/TypeScript/issues/19707 in a later release),

Oke, I'll add changes to revert #47696

**Comment by andrewbranch** [comment]
The plan for what the tree actually looks like will follow directly from what we choose for the API type:

- `Expression`, `PropertyAccessExpression`, or new type that is recursive `PropertyAccessExpression` allowing only itself and `MemberName`: tree looks like a `PropertyAccessExpression`
- New type that looks like `QualifiedName` but allows `MemberName`: tree looks like it does now

There’s not so much a problem with the shape of the tree as there is a disagreement between the type and reality.

**Comment by jakebailey** [comment]
We decided to revert this; I'll be sending a PR shortly to do it.

**Comment by rbuckton** [comment]
I think a better approach would have been to allow `#name` in an indexed access type, rather than in a type query, i.e.:

```ts
class C {
  #x: Foo;
  private _x: Foo;

  method() {
    const p1: this[#x] = this.#x;
    const p2: this["_x"] = this._x;

    const obj = this;
    const p3: typeof obj[#x] = this.#x; // parsed as `(typeof obj)[#x]`
    const p4: typeof obj["_x"] = this._x; // parsed as `(typeof obj)["_x"]`
  }
}
```

This would mean adding a `PrivateNameTypeNode` and we could then avoid changing `TypeQueryNode` or `QualifiedName` in any way. I would also expect that `#x` in a type is only legal *inside* of the class body, just like how a runtime private name is scoped. 

If you need to access the type of a private named class member *outside* of the class, you would need to introduce a type alias or interface for it. If a class makes a private-named index access type public, our declaration emit would also need to synthesize a type for it outside of the class. This means that the type `import("foo").Bar[#baz]` would only be legal inside of a class body that declares `#baz`.

**Comment by jakebailey** [comment]
@rbuckton can you stick that on #47595? I think Ryan there was arguing against it, so good to note in case we actually do have this feature.

**Comment by a-tarasyuk** [comment]
> I think a better approach would have been to allow #name in an indexed access type, rather than in a type query

@rbuckton, should `indexType` be extended to a `TypeNode | PrivateNameTypeNode`?

https://github.com/microsoft/TypeScript/blob/15392346d05045742e653eab5c87538ff2a3c863/src/compiler/types.ts#L2336-L2340

**Comment by jakebailey** [comment]
I think the answer is yes?

**Pull request closed without merging**
