### PR TITLE
dogfooding

### PR DESCRIPTION
**Pull request by tycho01**
I just discovered this cool TS feature called "annotating your code with types", so I figured I'd ~~artificially inflate the compiler size~~ contribute to safety by adding some types, so you can check types while you check types.
I've ~~probably~~ left many untyped ~~cuz I'm lazy~~ as an exercise for the reader.

Doesn't fix any issue whatsoever.

### CODE REVIEW

**Comment by andy-ms** [comment]
I do prefer the style of annotating function return types. I don't know the other team members' opinions though.
The tslint rule [typedef](https://palantir.github.io/tslint/rules/typedef/) with the "call-signature" option would enforce this.

**Comment by RyanCavanaugh** [comment]
I very much like this change as well. Anyone object?

**Comment by andy-ms** [comment]
@sandersn wasn't a fan

**Comment by RyanCavanaugh** [comment]
😠 ⚔️ 😠

**Comment by tycho01** [comment]
I'll concede most function names are quite descriptive, making the return types for them somewhat evident. I'll also admit the explicit annotations are slightly more verbose still.

As a relative newcomer to the code-base though, every now and then I find myself doing regex searches across the project for function signatures with given inputs and outputs.
For that purpose at least, I'd personally considered the explicit return types somewhat helpful -- such searches would be limited to find what is explicitly reflected in the code.

I agree inferred return types are great -- in fact, on occasion the inferred return types may even be more specific than the manually annotated ones.
I imagine there might be a way to achieve some best of both worlds there. It would be great if we could somehow ask TS to explicitly annotate our functions with the inferred return types, or suggest narrowing down existing annotations to more specific inferred types where possible.

I think these are considerations relevant for all TS projects out there, and I hope with these discoverability and self-documentation could improve just a little further. Incidental behavior mismatches uncovered this way, like that `isClassDerivedFromDeclaringClasses`, are just icing on the cake.

**Comment by weswigham** [comment]
@tycho01 Your title is also a little wrong, since if we started annotating all our return types, we would no longer be dogfooding our return type inference... I'm with @mhegazy, I like our types inferred where possible; I am the one who originally made and then enabled the `no-inferrable-types` tslint rule. If it was possible to _efficiently_ check every annotation everywhere for redundancy, I probably would.

**Pull request closed without merging**
