### PR TITLE
Don't lose the this reference for compilerHost methods.

### LINKED ISSUE #1545: ts.createEmitHostFromProgram doesn't bind compilerHost methods to the compilerHost instance
Starting from 5a2fb94, the EmitHost returned from ts.createEmitHostFromProgram() returns functions on the compilerHost like so:

```javascript
        return {
            getCanonicalFileName: compilerHost.getCanonicalFileName,
            getCurrentDirectory: compilerHost.getCurrentDirectory,
            getNewLine: compilerHost.getNewLine,
            writeFile: compilerHost.writeFile,
        };
```

Because of this, the implementations of those functions do not have access to the compilerHost object via `this`.

This doesn't matter for the default WScript and node.js compiler hosts because they use closures to capture their references, but it's a problem for custom compiler hosts that are implemented as classes, and worked before this change.

### PR DESCRIPTION
**Pull request by Arnavion**
Fixes #1545

### CODE REVIEW

**Comment by basarat** [comment]
:+1:

**Comment by Arnavion** [comment]
Rebased onto latest master (no changes).

**Comment by mhegazy** [comment]
Sorry this totally fell off the radar. @Arnavion sorry for the delay, but can you update this PR

**Comment by Arnavion** [comment]
I've updated it, but I'm not in a position to test it works right now.

I've also undone the change for the program methods, since now the program is internally generated by both tsc and services. (In the original change the program was a parameter to createEmitHostFromProgram, so there was the possibility a user could pass in their own instance).

I see that EmitHost.writeFile and CompilerHost.writeFile are now typed to the same interface, so there'd be no potential breakage in using bind() instead of writing the parameters explicitly (no possibility of updating one and forgetting to update the other, and then not catching it because the converter uses bind). Do you want me to do that?

**Comment by mhegazy** [comment]
yeah you are right. I will close the issue then. thanks! and sorry for the delay.

**Comment by Arnavion** [comment]
Err, why?

**Comment by mhegazy** [comment]
Sorry. I think i need more coffee. I personally like your change now better than bind.

**Comment by jasonwilliams200OK** [comment]
Would be nice to see PRs get merged rather quickly, if there are no issues. It encourages community to contribute to the project.

**Comment by DanielRosenwasser** [comment]
@jasonwilliams200OK agreed; sorry about the delay @Arnavion.

**Pull request merged**
