### PR TITLE
Update project on PackageInstalledResponse

### LINKED ISSUE #20084: NodeTypingsInstaller.handleMessage should treat PackageInstalledResponse roughly the same as SetTypings
In particular, `PackageInstalledResponse` should probably be a `ProjectResponse` and `handleMessage` should call 

```ts
                    this.projectService.updateTypingsForProject(response);

                    if (this.socket) {
                        this.sendEvent(0, "setTypings", response);
                    }
```

I'll leave it to the implementer to decide whether the event name should be different - VS doesn't need to distinguish.

### PR DESCRIPTION
**Pull request by amcasey**
As with `SetTypings`, new typings have been installed so the project should be updated and the client should be notified (via event).
    
Changed PackageInstalledResponse from "event" to "action" for the sake of explicitness.
    
Fixes #20084.

### CODE REVIEW

**Comment by amcasey** [comment]
Pulled out https://github.com/Microsoft/TypeScript/pull/20212 for the first commit, since it's more urgent.

**Comment by mhegazy** [comment]
Do we need to port this to release-2.6?

**Comment by andy-ms** [comment]
Shouldn't we be watching `node_modules` anyway, causing us to update when npm finishes? @sheetalkamat

**Comment by amcasey** [comment]
@andy-ms I believe the server watches that folder but the client does not.  The event is for the client.

**Pull request merged**
