### PR TITLE
Prefer parameter types inferred from initializers over their contextual types within `satisfies` expressions

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/53780

### CODE REVIEW

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
This fix seems overspecific. I'd like to see what this does if the logic is just unconditional, i.e.
 * Remove the `Satisfying` checkmode
 * Remove the `checkMode` param from `assignContextualParameterTypes`
 * Use the widened from of the initializer in lieu of the parameter type from the contextual type

If that turns out to be a big break we should rethink what the right logic is.

**Comment by Andarist** [comment]
@RyanCavanaugh I believe that this would be too breaking **and** unexpected:
```ts
const obj: Record<string, (arg: string | number) => void> = {
  foo: (param = "default") => {
    param;
    // ^? string | number
  },
};

obj["a"](100);
```

If we'd **always** prefer the type of the initializer over the parameter type from the contextual type then `param` inside this callback then we'd end up with an error like:
```
Type '(param?: string) => void' is not assignable to type '(arg: string | number) => void'.
  Types of parameters 'param' and 'arg' are incompatible.
    Type 'string | number' is not assignable to type 'string | undefined'.
      Type 'number' is not assignable to type 'string'.(2322)
```

I deliberately chose to only do this for `satisfies` because its goal is to "not change the type of the expression". So if the inferred type of this expression is `(param?: string) => void` I tried to preserve just that here. I think about `satisfies` as of an operator that allows us to contextually type an expression in the most **narrow** way, it helps to avoid widening etc while preserving type compatibility between the inferred expression.

However, I recall that you mentioned elsewhere that the additional goal of `satisfies` is to avoid a situation in which the inferred expression type would *negatively* affected the rest of the program. If I recall correctly then... this PR unfortuantely does exactly that:
```ts
type Cb = (arg: string | number) => void;

function acceptCb(cb: Cb) {}

const obj: Record<string, Cb> = {
  foo: (param = "default") => {},
};

acceptCb(obj["a"]);

const satisfiedObj = {
  foo: (param = "default") => {},
} satisfies Record<string, Cb>;

acceptCb(satisfiedObj.foo); // currently OK
acceptCb(satisfiedObj.foo as (param?: string) => void); // with this PR it would be an error
```

**Comment by RyanCavanaugh** [comment]
Great analysis. I guess the crux is what this example "should" do
```ts
const fn = ((x = "ok") => null) satisfies (x: string | number) => any;
fn(32); // currently OK
```
and whether it's even desirable to have that be different from
```ts
const fn: (x: string | number) => any = (x = "ok") => {
    x
//  ^? string | number
};
```

I think the `any` in the issue OP biases the analysis a bit. Inferring to `any` *in the presence of another type hint* is arguably the problem here, not anything with `satisfies`:
```ts
const fn: (x: any) => any = (x = "ok") => {
    x
//  ^? any
};
```
It feels like `x` should just be `string` here, not `any`, but I'm not really sure.

**Comment by Andarist** [comment]
> I think the any in the issue OP biases the analysis a bit. Inferring to any in the presence of another type hint is arguably the problem here, not anything with satisfies

Yeah, that crossed my mind as well when I figured out that this PR introduces a problem with negatively affecting the rest of the problem.

> It feels like x should just be string here, not any, **but I'm not really sure.**

Same here 😂 And even if we gonna specialcase `any` anyhow... how OK would this be to change this in all cases then another type hint is present? I'm not exactly sure what are the guiding principles related to `any` in such a case but wouldn't for example this be a problem?
```ts
const fn: (x: any) => any = (x = "ok") => {
    x
    //  ^? today: any, potentially changed: string
};

fn(100)
```

Isn't it **safer** to type `x` in the callback as `any` (however that sounds)? That being said - this doesn't report an implicit any so it can still be left unnoticed but yet if somebody notices it then it would at least point them into fixing this somehow. OTOH, this is always the problem today anyway as any *annotated* function can be assigned to such "any function". 

On top of that, shouldn't this at least report an implicit any?
```ts
const obj = {
   foo: (param) => param, // we have contextual type for `param`, but that's `any`, would be nice to be warned about this
} satisfies {
   [key: string]: (...params: any) => any;
};
```

**Comment by RyanCavanaugh** [comment]
> On top of that, shouldn't this at least report an implicit any?

It's longstanding behavior that a contextual parameter type of `any` is sufficient to not be an "implicit" any. The motivating example is
```ts
const arr: any[] = [whatever].
arr.forEach(x => x.sth);
```
This doesn't look spooky when the `any` is lexically near `x` but does look spooky when it's far away (especially in e.g. another .d.ts file).

**Comment by RyanCavanaugh** [comment]
Yep

**Pull request closed without merging**
