### PR TITLE
Try emitting an error when export would be emitted with different unwidened type

### PR DESCRIPTION
**Pull request by jakebailey**
This is a very very bad attempt at making the problems we've found in #55445 into check errors. I guarantee that this PR is wrong, you can see very strange things happening because observing `isDeclarationVisible` of each declaration passed to `checkVariableLikeDeclaration` seems to cause a side effect (???), and my check is poorly copied from `declarations.ts` so has some improper edge cases.

In any case, it still catches everything we mentioned in #55445 so it's somewhat interesting.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test top200
@typescript-bot user test this

**Comment by jakebailey** [comment]
Reading live logs, this seems to be firing on `private` things, probably because those are "preserved" in `d.ts` emit but with types removed (but this test PR doesn't model that).

**Comment by jakebailey** [comment]
@typescript-bot test top100
@typescript-bot user test this

**Comment by jakebailey** [comment]
A bunch of the above declarations are still ones that shouldn't be visible, so I've clearly still done something wrong.

**Comment by jakebailey** [comment]
@typescript-bot test top100
@typescript-bot user test this

**Comment by jakebailey** [comment]
@typescript-bot test top200
@typescript-bot user test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@jakebailey you mentioned examples where this doesn't just solve a divergence of declaration emit, and maybe I missed the specifics in the design meeting. Can you write up/show what this solves more explicitly?

**Comment by jakebailey** [comment]
Yes, I am building an example repo now!

**Comment by jakebailey** [comment]
Example: https://github.com/jakebailey/dts-emit-widened-unwidened-examples

Just to summarize @weswigham, this is arguably a limitation of declaration emit, and we could alternatively fix this by introducing syntax into `d.ts` emit that emulates ternaries, destructuring, `??`, etc, which all have this problem. This is the method we currently take via emitting initializers (and why this PR skips those as they are already handled). Fixing it in declaration emit is somewhat preferable because it doesn't shift this problem off to users.

**Comment by fatcerberus** [comment]
Just guessing based on the title of this PR, but is https://github.com/microsoft/TypeScript/issues/55832 related? (it's a case where declaration emit produces a different type--in particular `any` (!)--than what's inferred locally)

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
> Just guessing based on the title of this PR, but is #55832 related? (it's a case where declaration emit produces a different type--in particular `any` (!)--than what's inferred locally)

In a way, yes, it's similar to this and #55901.

**Pull request closed without merging**
