### PR TITLE
Fix crash from missing valueDeclaration on intersection property

### LINKED ISSUE #37015: "Debug failure" without any details when upgrading to 3.8.2.
**TypeScript Version:**  3.8.2

**Search Terms:** `debug failure`.

**Code**: nothing specific. Happens in an Ember app.

**Expected behavior:**
My app builds successfully on TypeScript 3.7.5. I expect that upgrading to 3.8.2 does not break the build or at least crashes with a meaningful error.

**Actual behavior:**
Build crashes with:

```
C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:98632
                throw e;
                ^

Error: Debug Failure.
    at Object.assertDefined (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:2227:24)
    at C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:39435:34
    at Object.filter (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:513:31)
    at serializeAsClass (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:39433:48)
    at serializeSymbolWorker (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:39164:29)
    at serializeSymbol (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:39105:38)
    at C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:39080:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:39079:33)
    at symbolTableToDeclarationStatements (C:\Code\kaliber5\tujspk-frontend\node_modules\typescript\lib\typescript.js:38950:17)
```

**Related Issues:**
There are numerous issues with `Debug failure`, but all of them have some additional error message such as:

> Error: Debug Failure. in 'Object.assertDefined' during 'completionEntryDetails'

Mine doesn't. 😔

***

**tsconfig.json**:

```json
{
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "skipLibCheck": true,
    "paths": {
      "uni-frontend/tests/*": [
        "tests/*"
      ],
      "uni-frontend/mirage/*": [
        "mirage/*"
      ],
      "uni-frontend/*": [
        "app/*",
        "lib/ember-cli-yadda-steps/app/*",
        "lib/ember-kaliber5-loading/app/*"
      ],
      "ember-cli-yadda-steps": [
        "lib/ember-cli-yadda-steps/addon"
      ],
      "ember-cli-yadda-steps/*": [
        "lib/ember-cli-yadda-steps/addon/*"
      ],
      "ember-cli-yadda-steps/test-support": [
        "lib/ember-cli-yadda-steps/addon-test-support"
      ],
      "ember-cli-yadda-steps/test-support/*": [
        "lib/ember-cli-yadda-steps/addon-test-support/*"
      ],
      "ember-kaliber5-loading": [
        "lib/ember-kaliber5-loading/addon"
      ],
      "ember-kaliber5-loading/*": [
        "lib/ember-kaliber5-loading/addon/*"
      ],
      "ember-kaliber5-loading/test-support": [
        "lib/ember-kaliber5-loading/addon-test-support"
      ],
      "ember-kaliber5-loading/test-support/*": [
        "lib/ember-kaliber5-loading/addon-test-support/*"
      ],
      "fetch": [
        "node_modules/ember-fetch"
      ],
      "*": [
        "types/*"
      ]
    },
    "experimentalDecorators": true
  },
  "include": [
    "app/**/*",
    "tests/**/*",
    "types/**/*",
    "lib/ember-cli-yadda-steps/**/*",
    "lib/ember-kaliber5-loading/**/*",
    "mirage/**/*"
  ]
}
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37015

The error was occurring when trying to serialize a JS symbol into a class declaration, because one of its inherited property symbols was missing a `valueDeclaration`, which was the target of a `Debug.assertIsDefined`.

When two object types were unioned/intersectioned, the order of types was having an observable effect on whether the resulting property symbol had a `valueDeclaration` set. If the first type’s property didn’t have a `valueDeclaration` but a later type’s property did, we’d take the later one. But in the inverse case, we’d say that there was a non-uniform value declaration so we wouldn’t attach one at all.

Fixing this fixed the real-world repro at #37015 and improved one types baseline, but my minimal repro was still failing because the intersection property for `toString` had two different _defined_ declarations, which seemed like a legitimate violation of the assertion’s assumption, so I removed the assertion. My understanding of this code is that inherited properties could _all_ be filtered out, and if `valueDeclaration` is undefined, the property _must_ be inherited.

### CODE REVIEW

**Comment by sandersn** [comment]
We still want to serialise properties that come from an intersection but only have one source property, right? If I understand correctly, `{ a } & { b }` should always produce `a` and `b` -- whereas `{ a: number } & { a: string }` is the dual-defined case, and is OK to skip `a`. Is that correct? Is that what this PR does?

**Comment by sandersn** [comment]
I thought there was a reliable way to differentiate between properties that are just passed through an intersection vs those that combine two source properties. It might be having a defined `containingType`, but I thought there was something else.

Combined, these two statements:
> But in the inverse case, we’d say that there was a non-uniform value declaration so we wouldn’t attach one at all.

>  my minimal repro was still failing because the intersection property for toString had two different defined declarations

make me think that the rules for setting valueDeclaration on intersection properties should change first and then the serialisation code can change if there's still a need.

**Comment by andrewbranch** [comment]
> We still want to serialise properties that come from an intersection but only have one source property, right? If I understand correctly, { a } & { b } should always produce a and b -- whereas { a: number } & { a: string } is the dual-defined case, and is OK to skip a. Is that correct? Is that what this PR does?

Yep, that’s what this PR does. But in my test case, the inherited `toString` property still came from an intersection of `Object` and `CoreObject`, each with their own `toString` declaration, so the serialization had to change too.

**Comment by andrewbranch** [comment]
I should also be more clear that I think my change to `createUnionOrIntersectionProperty` was just fixing a mistake, not changing the rules. It was dependent on the order of types in the union/intersection, which seems like it must have been unintentional.

**Pull request merged**
