### PR TITLE
Improve error message when compiling a .js file

### LINKED ISSUE #33585: Poor error message when compiling a `.js` file
```
> tsc .\sample.js
error TS6054: File 'sample.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
```

Two things:

1. The error message is grammatically incorrect. It should be "has **an** unsupported  extension."
2. The `.js` extension **is** supported when a user uses `allowJs`! We should suggest that with

   > Did you mean to enable the 'allowJs' option?

### PR DESCRIPTION
**Pull request by lukahartwig**
Fixes #33585

I noticed this grammar error and saw that there already was an issue for it so I implemented the suggested changes.

### CODE REVIEW

**Comment by orta** [comment]
Hi @lukahartwig  - I really like this idea, I'm open to getting this in 👍 . 

Is it possible that for the last part of the sentence, you first check whether we are looking at a JavaScript or JSON file first? (It might need two error messages then)

**Comment by lukahartwig** [comment]
Good point, I try to make it work.

**Comment by lukahartwig** [comment]
Okay, so I added two error messages for JS and JSON files. For other extensions, it will fall back to the old message. I might need some help with the wording since I'm not a native speaker.

I also wasn't able to reproduce the JSON file case with the baseline tests because apparently`resolveJsonModule` is already handled at an earlier stage. I'm not super familiar with the codebase though so maybe I missed something.

**Comment by orta** [comment]
This is great @lukahartwig - the messages read good to me, let's get this in.

**Comment by lukahartwig** [comment]
Cool, I removed the JSON error message. Thanks for your help :)

**Comment by orta** [comment]
Thanks for contributing!

**Pull request merged**
