### PR TITLE
Another try to not use namespace

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Fixes #

### CODE REVIEW

**Comment by ShuiRuTian** [comment]
Question1: 
```
namespace ts{
        export const enum SyntaxKind {
        Unknown,
        EndOfFileToken,
        SingleLineCommentTrivia,
        MultiLineCommentTrivia,
        NewLineTrivia,
        }
}

var q = (ts as any).SyntaxKind;

const enum SyntaxKind {
    Unknown,
    EndOfFileToken,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,
    NewLineTrivia,
}

// How to get SyntaxKind like under namespace?
```
For now I generate a new file and copy everything expect the "const" keyword.

**Comment by ShuiRuTian** [comment]
Some aim:
1. remove all "ts" namespace, keep others for temp. (ts.XX keeps too)
2. use script to do heavy work, but manually check all again and fix error.

Some sequelae caused by this branch:
1. some variable are renamed, they are usually added "NameSpaceLocal" suffix.

**Comment by weswigham** [comment]
@ShuiRuTian FYI, https://github.com/microsoft/TypeScript/pull/35561 already does this and is (re)generated by script. We're mostly just blocked on an API Extractor feature so we can preserve the same file layout in our API as today.

**Comment by ShuiRuTian** [comment]
whoops, glad to know that!

**Pull request closed without merging**
