### PR TITLE
Test making the in-discussion `strictInstanceOfTypeParameters` flag to always be true

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Experimentally always enables https://github.com/microsoft/TypeScript/pull/49863

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by DanielRosenwasser** [comment]
I think it already ran DT?

https://github.com/microsoft/TypeScript/pull/53300#issuecomment-1472771069

**Comment by jakebailey** [comment]
With the new DT diff, "failed" means something timed out and it couldn't make a diff

**Comment by DanielRosenwasser** [comment]
The real PR already does this.

**Pull request closed without merging**
