### PR TITLE
Support for experimental ".mjs" output

### LINKED ISSUE #18442: Support `.mjs` output
Experimental support for ES modules just landed in Node 8.5 ([changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.5.0), [PR](https://github.com/nodejs/node/pull/14369)).
Since ES modules have some parsing and semantic differences, Node decided to use the `mjs` extension for ES modules (while `js` is for the "script" target and commonjs modules).

The current Typescript version (`2.5.2`) supports ES modules emission but uses the `js` extension by default. It means that to use it with Node, a post-compilation step is required to change the extension from `js` to `mjs`. This adds undesirable complexity to use native ES modules support with Node.

A solution would be to add a compiler option to output `*.mjs` files when emitting  ES modules.

**Edit (2018-03-22)**: The propositions below are a bit outdated. I recommend reading the issue to see the progression. See [this comment](https://github.com/Microsoft/TypeScript/issues/18442#issuecomment-365691593) for my current proposition.

Notes:
- It is possible that new parse goals will be added in the next versions of the ES spec. Letting the user provide the extension explicitly (as opposed to a boolean switch) would allow to be forward compatible with other new extension.
- It should still be possible to emit ES modules with the `*.js` extension, many tools rely on the `js` extension.
- Another solution would be to have a different extension for the source files: `*.mts` files would compile to `*.mjs`, this would be similar to `*.tsx` and `*.jsx`.

### PR DESCRIPTION
**Pull request by SMotaal**
Partially Fixes #18442 

This PR addresses two aspects of supporting the actual ".mjs" extension:

1. It allows TypeScript to resolve bare specifiers for a file when a respective ".mjs" file can be found, by first looking for a ".mjs" immediately before looking for a ".js" (without affecting any other order).

2. It allows TypeScript to output to ".mjs" only under the following very restrictive config:

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "esnext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```

Aside from changes to the source, both harness and baselines have changed to accommodate those two changes, with all current tests passings.

Thanks

### CODE REVIEW

**Comment by smotaal** [comment]
Here are some notes if you are interested in using this PR meanwhile:

https://gist.github.com/smotaal/4f9458cf43cd7a55a12d5c476c15400e

**Comment by mhegazy** [comment]
We are waiting on node to formalize their support for ES6 modules. I do not think we know if you want .mjs to be the default output (as in this PR) as of yet. 
There is also issues with what you can import from and what you can can not, and using which import forms. there are issues with what the declaration file from a .mjs file source should look like, and ultimately we do not know if the solution would be a `.mts` and ` .d.mts` extension. 
Thanks for the PR, but there are many open issues that have not been resolved at the moment, and that is why we have not added this yet.

**Comment by smotaal** [comment]
@mhegazy This is intended as a highly experimental step to allow the rest of us in this space to at least explore and experiment, if not to actually be able to do our part in uncovering other less popular edge cases. I realize TypeScript is working hard, but without this very minimal-no-promises-and-just-temporary feature, you are loosing out on all the far more significant potential that other TypeScript users out there could have been bringing to the table (and this is my little contribution)

**Comment by smotaal** [comment]
@mhegazy and yeah, I'm a much bigger fan of MJS music thank you (but the alternative is custom loader and so far this needs to be a CLI flag 😱)

**Comment by mhegazy** [comment]
> but without this very minimal-no-promises-and-just-temporary feature,

:D i wish there was that kind of feature.. if a feature is part of the product, ppl will use it and expect it to work, and will be unhappy when their build breaks.

**Comment by mhegazy** [comment]
Just to be clear, if .mjs ends up the default for node, we will support it.

The node implementation details are not finalized at the moment. and we do not think we should be making any changes until node plans are stable and clear. 

We have two team members on the [node modules working group](https://github.com/nodejs/modules), and we are closely following the development of node module implementation.

**Comment by smotaal** [comment]
So let me pick your brain on a temporary workaround for the following:

What would be the most ideal way today to be able to augment my TypeScript development experience in Visual Studio Code so that it would allow me to work with `.mjs` files interchangeably as it would for other ES2015+`.js` files (aside from manual .d.ts and to keep it fun, let's assume I can't transpile)

Honestly, I've been racking my brain and others' to solve this, without adding a new layer of the very likely to cause even more incompatibility tomorrow but works today stuff that got us in this desperate  mess we are in today.

**Comment by mhegazy** [comment]
The feature is not supported, that is what  #18442 tracks. As i mentioned earlier, we continue to monitor developments on the node side, and we will be adding support as that node module implementation materializes.

**Pull request closed without merging**
