### PR TITLE
Assignment operator is definite assignment

### LINKED ISSUE #39088: Logical Assignment Operator should be a definite assignment kind
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
assignment operator, type
**Code**
https://github.com/microsoft/TypeScript/issues/37255#issuecomment-644502419
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
let x: { a?: boolean } = {};

x.a ??= true;
x.a &&= false;
^^^ Type 'false' is not assignable to type 'true'.(2322)
```

**Expected behavior:**
Works

**Actual behavior:**
Type 'false' is not assignable to type 'true'.(2322)

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #39088

### CODE REVIEW

**Comment by Kingwl** [comment]
@aminpakk Fix available here.

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
Ci is broken, but not my fault.

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
What exactly is the difference? Does a definite assignment widen to the base primitive type?

**Comment by Kingwl** [comment]
> What exactly is the difference? Does a definite assignment widen to the base primitive type?

Basically yes.

**Comment by orta** [comment]
Confirmed the fix in the playground, looks good to me 👍

**Pull request merged**
