### PR TITLE
Propagate object flags related to object and array literals onto `module.exports` types

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/57460

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot test it

**Review by gabritto — CHANGES_REQUESTED** [review]
(1) I don't exactly understand how the code change is related to the observed behavior in the repro, if you could provide an explanation that would be very helpful.
(2) There were test changes that I also don't know how they relate to the code change, so would be nice to get an explanation for those too (even if they're bugs). Thanks!

**Comment by Andarist** [comment]
1. IIRC those flags affect `isPerformingExcessPropertyChecks` 
2. the in-repo change looks like being related to [type inference for object literals](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#improved-type-inference-for-object-literals). It looks like a correct change to me - it now benefits from this since we are correctly propagating those literal flags. As to the `webpack`'s change from [this comment](https://github.com/microsoft/TypeScript/pull/57467#issuecomment-2040374361) - I'm not sure yet. I just synced with `main`, could we rerun those tests to get a confirmation that nothing wonky is happening with that report (I'm not sure how likely that is with the current infra)? If it comes back with this error again then I'll happily investigate this (cc @jakebailey )

**Comment by gabritto** [comment]
According to Jake, the extended tests use the latest main, so the not-synced PR shouldn't be a problem, but I can try running again.

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by jakebailey** [comment]
My impression at the moment is that the CFA change introduced some non-determinism; that same error went away in that change and is now back again.

**Comment by Andarist** [comment]
Something weird is happening with those tests but I think it's fair to say that it's not related to this PR 😉

**Review by gabritto — APPROVED** [review]

**Comment by jakebailey** [comment]
This PR was out of date and broke main.

**Comment by gabritto** [comment]
> This PR was out of date and broke main.

I'll fix it now

**Pull request merged**
