### PR TITLE
Use Partial types for Object.assign

### LINKED ISSUE #11100: Object.assign not type checking
TS 2.0.3

Given:

``` ts
(() => {
    type State = { foo: string };
    const state: State = { foo: 'bar' };
    const newState: State = Object.assign({}, state, { foo: 1 }) // I expect this to error
})();
```

I swear this used to work!

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #11100

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
IMHO, let's waiting for rest type (#10727) is a better choice.


http://www.typescriptlang.org/play/index.html#src=declare%20function%20assign%3CT%3E(target%3A%20Partial%3CT%3E%2C%20...sources%3A%20Partial%3CT%3E%5B%5D)%3A%20T%3B%0Aassign(%7Ba%3A%20123%7D%2C%20%7Bb%3A%20345%7D)

**Comment by falsandtru** [comment]
Yep, reverted my deletions. These problems (by my deletions) will be resolved by rest type. However as I said in #11100, I think partial type is needed too. So this pr can merge without waiting to merge #10727.

**Comment by sandersn** [comment]
The partial type is not right for `assign` for a couple of reasons.

1. It's not a useful inference source. So `function f<T>(pt: Partial<T>): T` is essentially equivalent to `function f<T>(t: T): T` unless the type argument is given explicitly.
2. It's too strict; see @HerringtonDarkholme's example.

Also, the variadic overload should come last, right? Otherwise it will preclude matching other overloads.

I can see three options:

1. Do nothing. Variadic `Object.assign` continues to be illegal in Typescript, although (hard-coded) variadic spread is now legal.
2. Punt. Make variadic assign take and return any.
3. Be strict. Use `T` as the type parameter instead of `Partial<T>`.

**Comment by falsandtru** [comment]
I see, thanks for your explanation!

**Pull request closed without merging**
