### PR TITLE
28911 - change Diagnostic.code to 'string | number'

### LINKED ISSUE #28911: Change Diagnostic.code to 'string | number'
I'm writing a LanguageService plugin for TypeScript that returns custom diagnostics. A `Diagnostic` needs to have a `code` property of type number.

I don't have a number. Instead I can provide a string that represents the name of the rule producing the diagnostic. In addition a random number I would choose looks quite ugly in the tooltip VSCode displays for the Diagnostic.

I know TypeScript only ever creates Diagnostics with numeric `code`, but it's too limiting for plugins.
I looked it up and the LanguageServer protocol specifies it as `code?: number | string`.

My current workaround is to use a type assertion. Until now nothing bad has happened.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #28911

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@ajaff ok, will add changes to DiagnosticWithLinePosition, DiagnosticRelatedInformation.

**Comment by DanielRosenwasser** [comment]
The unfortunate thing here is that we're going to cause so many bugs where people create a `Set<number | string>`  and end up using `.has` on the wrong type.

**Comment by DanielRosenwasser** [comment]
Hey @amcasey, can VS handle non-numeric diagnostic codes?

**Comment by amcasey** [comment]
@DanielRosenwasser, I believe so, but I'll confirm.

**Comment by amcasey** [comment]
@DanielRosenwasser I misspoke - Roslyn can accept strings but TS deserializes them as int so old versions of VS will break (probably by dropping these diagnostics).

**Comment by DanielRosenwasser** [comment]
Sounds like this API would also need to support a new option on configuration to say that the client can support string error codes. Even if we decided to add this functionality, we would need to keep numeric error codes around f o r e v e r.

As terrible as it sounds, it might be better to return a new property on `Diagnostic` objects.

**Comment by DanielRosenwasser** [comment]
@weswigham

**Comment by sheetalkamat** [comment]
@DanielRosenwasser Your suggestion doesnt sound terrible. Infact i like having optional friendlyName property sounds good. That way even we could add the names to error codes (instead of numbers) and editors can decide to use them over number if present to displayed. We should keep errorCode required so that editors not handling the additional optional property can show something that user can search about.

**Comment by weswigham** [comment]
_Friendly human readable short names are good_. Although question, if we go there: Can multiple messages share a short name (so, eg, we can group all the excess property variant messages under one "name")? I don't really see why not.

**Comment by a-tarasyuk** [comment]
I think this PR has to be closed.

**Comment by minestarks** [comment]
@DanielRosenwasser just to clarify on https://github.com/Microsoft/TypeScript/pull/28959#issuecomment-447091812  I feel like a configuration option isn't necessary if we simply add a new optional `friendlyName` field - errors that support friendly names would always populate the friendlyName and old editors would just ignore it.

**Pull request closed without merging**
