### PR TITLE
fix type lookup rule

### LINKED ISSUE #22825: Surprising behavior with `typeof` in signatures
**TypeScript Version:**  2.9.0-dev.20180323

**Search Terms:** 

**Code**

```ts
declare let foo: number;

// bar is of type string
// return type is string
declare function test(foo: string, bar: typeof foo): typeof foo;
// bar is of type string
// return type is number
declare function test({foo}: {foo: string}, bar: typeof foo): typeof foo;
```

**Expected behavior:**

`typeof foo` should reference the same declaration regardless of where it's used in the signature.

**Actual behavior:**

`typeof foo` in return type refers to the outer variable if `foo` comes from a destructured parameter. `typeof foo` inside the type annotation of another parameter refers to the parameter as expected.

This becomes even more visible if you remove the outer `declare let foo: number;` which will result in a compile error: `Cannot find name 'foo'.`

**Playground Link:** http://www.typescriptlang.org/play/#src=declare%20let%20foo%3A%20number%3B%0A%0Adeclare%20function%20test(foo%3A%20string%2C%20bar%3A%20typeof%20foo)%3A%20typeof%20foo%3B%0Adeclare%20function%20test(%7Bfoo%7D%3A%20%7Bfoo%3A%20string%7D%2C%20bar%3A%20typeof%20foo)%3A%20typeof%20foo%3B

**Related Issues:**
#22769 possibly related issue where the parameter initializer refers to the wrong variable.

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #22825 . 

BTW: there are many pr that required review too(

### CODE REVIEW

**Comment by ajafff** [comment]
Does this also fix the example code snippet in the first comment of the linked issue?

**Comment by Kingwl** [comment]
ahhh, i'm not sure that linked issue accept pr and i ignored it

**Comment by ajafff** [comment]
According to the comment of @andy-ms that should also be accepted:

> I'll still mark this as a bug because I would expect the second example to have the same behavior regardless of whether you write `var foo` or `let foo` inside the function.

**Comment by mhegazy** [comment]
@ajafff I think the issue in https://github.com/Microsoft/TypeScript/issues/22769 should be handled separately. we should condition the error reporting, and the resolution together.

**Pull request merged**
