### PR TITLE
Fix incorrect formatting in fluent API call

### LINKED ISSUE #14675: Incorrect formatting in fluent API call
**TypeScript Version:**  2.2.1

**Code**

Format the following code snippet using VS Code or typescript-formatter:
```ts
someVar
  .chain(
    'arg1',
    'arg2',
  )
  .chain(
    3,
    4,
  );
```

**Expected behavior:**
```ts
someVar
  .chain(
    'arg1',
    'arg2',
  )
  .chain(
    3,
    4,
  );
```

**Actual behavior:**
```ts
someVar
  .chain(
  'arg1',
  'arg2',
)
  .chain(
  3,
  4,
);
```

This is a common occurrence with fluent APIs (test frameworks, ORMs, etc) and tslint rules requiring trailing comma.

### PR DESCRIPTION
**Pull request by magnushiie**
Also add test cases (2nd test case with comma is currently commented out)

Partially fixes #14675

### CODE REVIEW

**Comment by magnushiie** [comment]
It's a bit hard to understand the indentation architecture, and this change might be the wrong place to fix it. Specifically, it's hard to understand how indentation and delta apply to multi-line nodes and the individual tokens belonging to them.

**Comment by magnushiie** [comment]
The behavior in smartIndentOnUnclosedFunctionDeclaration04 baffles me, have to study it some more. The obviously incorrect fix to that test would be for the last 3 lines:
```patch
-verifyIndentationAfterNewLine("4", 8);
-verifyIndentationAfterNewLine("5", 4);
-verifyIndentationAfterNewLine("6", 4);
+verifyIndentationAfterNewLine("4", 12);
+verifyIndentationAfterNewLine("5", 8);^
+verifyIndentationAfterNewLine("6", 8);
```

On the other hand, if you type in the example in #14675, it's clear the smart indentation and re-formatting are out of sync already today.

**Comment by zhengbli** [comment]
The fix is pretty trickey. The issue is that previously we consider two cases:
1. the child node starts at the same line with the parent node;
In this case, the indentation should be
- if that line was not indented already -> the same as the parent's indentation;
- if that line was indented -> the indentation of that line

2. the child node does not start at the same line with the parent node:
In this case, the indentation should be the same as the parent's indentation + delta;

Consider a similar case with the issue at hand:
```ts
Promise
    .then(foo => {
        console.log(foo);
    })
```
Here the indentation of function block is the same as the `.then` line, because the block node starts at the same line with the parent node (the arrow expression node), then it inherits indentation from that line.

However in our case, 
```ts
Promise
    .then(
        foo
    )
```
The `foo` node does not starts from the same line with its parent node (the entire `Promise.then ...` call expression node), so it does not use the indentation from that line, which caused the issue.

I'm thinking about a more comprehensive way to fix this.

**Comment by zhengbli** [comment]
Hi I submitted a new PR at https://github.com/Microsoft/TypeScript/pull/14955
Can you help check if it solves the issue? Thanks

**Comment by magnushiie** [comment]
Closing this in favor of #14955

**Pull request closed without merging**
