### PR TITLE
Fix typo in copyright notice

### PR DESCRIPTION
**Pull request by stefanpl**

### CODE REVIEW

**Comment by stefanpl** [comment]
Not sure what do to, does not make a lot of sense to me that the builds were failing.
It's just a typo after all :shrug:

**Comment by RyanCavanaugh** [comment]
The build is failing because necessary baseline files weren't updated. Please run the tests per the repo instructions and follow the CONTRIBUTING guide on how to update baselines.

**Comment by sandersn** [comment]
@stefanpl I'm circling back to older PRs, do you want to keep working on this?

**Comment by stefanpl** [comment]
@sandersn I just wanted to fix a typo, but honestly didn't take the time to go through the contributing guidelines, so the automatic tests were failing. Maybe you can just fix the typo within some other PR and close this one.

**Pull request closed without merging**
