### PR TITLE
【Test】Deprecated perf test

### PR DESCRIPTION
**Pull request by Kingwl**
Just perf test for #38523. Please Ignore this one.

### CODE REVIEW

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by sandersn** [comment]
This shows that my suggestions (1) and (3) are not the cause of the slowdown; to test (2) you need to remove the new call to getJSDocDeprecatedTagNoCache inside getJSDocModifierFlagsNoCache. defaf11 doesn't really do this.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by sandersn** [comment]
Removing the check from modifier flags got the regression down to 1.5-2%. What happens if you revert the modifier flags change entirely and just use getJSDocDeprecatedTag everywhere?

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by sandersn** [comment]
I'm not sure why this latest change slows down the binder, since the flag is set in the parser. There may be some subtle de-optimisation going on.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@sandersn I don't know why bind time increased. :XD But It's still about 1% regression. It that ok for you.

**Comment by sandersn** [comment]
No, a feature like this is not worth a noticeable slowdown, especially when the cause is still unknown. =(

**Comment by DanielRosenwasser** [comment]
For what it's worth, shipping editor functionality can go in post-beta, so there's time to iterate on this.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
Oh I got it.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
Is this acceptable?

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
[this](https://github.com/Kingwl/TypeScript/pull/3) is the changes to original branch.

**Comment by Kingwl** [comment]
Seems nearly no overhead

**Comment by sandersn** [comment]
Looks pretty good! If you can get the commits back to the PR branch by Monday I think it will be OK for 4.0.

**Pull request closed without merging**
