### PR TITLE
Allow input intersection for `Array.includes`

### LINKED ISSUE #36275: .includes or .indexOf does not narrow the type
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** `.includes type narrowing`, `.indexOf type narrowing`

**Code**

```ts
interface TextMessage {
    type: 'text',
    text: string
}

interface ImageMessage {
    type: 'image',
    url: string
}

type Message = TextMessage | ImageMessage;

// This is an example to reproduce the error in Playground.
// In practice, assume this message comes from outside our control (e.g. HTTP request)
const message: Message = JSON.parse(prompt('') as string) as Message;

if (message.type === 'text') {
    // No error here
    message.text = message.text.trim();
}

// Same for ['text'].includes(message.type)
if (['text'].indexOf(message.type) > -1) {
    // Error: Property 'text' does not exist on type 'ImageMessage'
    message.text = message.text.trim();
}
```

**Expected behavior:**
I expect `message` to narrow its type to `TextMessage` inside `if (['text'].indexOf(message.type) > -1)`.

Same way it does inside `if (message.type === 'text')`

**Actual behavior:**
`message` is typed as `TextMessage | ImageMessage` inside the `if` block
```ts
if (['text'].indexOf(message.type) > -1) {
    // Error: Property 'text' does not exist on type 'ImageMessage'
    message.text = message.text.trim();
}
```

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?target=1&module=5#code/JYOwLgpgTgZghgYwgAgCoQB5gLIQM55wDmKA3gFDJXJgCeADhAFzIDkkWrANJdR2CzxgooIuQC+5cqEixEKAJIBbYhFwFVyCtRoNmbYCpLdeVAK5QANoOGiJUuo2TrCJZAF40mHPlcoAPsjKqi6qANxSAPSRaAAWwHjICchwIMiYcEr0lihgAPbIUBD0UHkAJmZINLEo0KVQSWkACpZwtESlZiBlAHTk0UFpJYhgwEhcKQRmSrnxiTMabgh5C8gwpUrIeWZgeMBlKNsNy+CllsgAFBA9RD3IABKoqE2FEACOZvhgAJTkJ0LIBZ+FihNyeABSAGUAPIAOR69DgUDwEAuJRW9DAF1YrG+k2QQhEICIeLgiVBEAi0hglyBqh6jhQ7mZbH4uK0pmQA1hBTqeQaNSKnLpJAZ3g8gN89P4DJESgu3wikn6MUhmRQMH5yAA2uxvKwALo9UAISxmA54C4i66M37AGkXXVso2gA4YaEwK1S0W25AAPmQAFoAIx47TUAYAUSg9RYTVKjCgdFZ+uQZTy+GQIDyYHSGASubyaUZbGCJAprGF3pt4s81rFWFlhgVSqAA)

**Related Issues:** https://github.com/microsoft/TypeScript/issues/9842

My argument is that `if (message.type === 'text')` should be considered equivalent to `if (['text'].includes(message.type))`.

It might seem irrelevant on a small example like this, but if the array (`['text']`) is large, the workaround is difficult to maintain.

### PR DESCRIPTION
**Pull request by johnsoncodehk**
Fixes https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/973, related to #36275

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
Thanks for the reply, there's not much to explain, we judge if `T extends K`, then make `searchElement` become unknown because we already know that the type passed in is legal.

Here is the playground link: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJSnAngHgCoB8yA3gFDLIgQDuAkiAgDYCuAJhAM44DSyEAHpBCsOyABR4+giMNG8A-MmYgA1iAD21EMgBcyPAEoCYjhDhQEACwCijCAFsZYPdwA0yGFHX367fvL0QZnsAI2gDPRD1dTs4EABuUgBfUlJ2JnMUBHUQDjBkPKhUYQA5YPQoPRMwKFAAc2QAH0pgsKgDAG0AXUT0xkzkbNz8wtpIez1C+t6IDKgsnLyCmoB5KAAhaMYxh0ma+qbkKJizBLTZ-vnBxfzj7fHIrdPE0gB6V+RAUHJKdT4MdUqyAABlMQHUgchgKI4AVmCFTPl1DBgaCGs0gqFoED3KAmGxOJDRAA3OCMYCsZCMdR1YAIUiFYqsMr2CoAOlxLHYHGqUB29gMiXeyEAMuR-LyAkH7MGHO6nCFxCmS2rS9GtLHISxwUSgSBQUwIMDAHI4hicglQ5AkskUqk0ukM0rlDDs0347mFNabGJ8gVvD7faDivRKg7NWVxeXCFFStEtTFQCGa0QaSHgaD6w3G1N4rmE1NW8mU6m0+k1RnMtkct1iO4+l5C74aQMA0tFR0s51UOiurk8ut+r4-ZtQVvlp1QVld+g5zg8z1bfsNsUth1M8eTmjTs3c2vjX1AA

**Comment by johnsoncodehk** [comment]
Sorry I found out that the above explanation is actually wrong (due to the past train of thought I've forgotten).
What `T extends K ? unknown : T` does is make `string | boolean` become `unknown | T` -> `unknown`, to subtly make union types containing `string` legal.

**Comment by sandersn** [comment]
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot user test this

**Comment by sandersn** [comment]
Re-reading the linked bugs, they're not the same. Please do create a new bug for this PR, because it needs a separate explanation of the problem as well as your solution. In the meantime we can see whether existing projects work with this new type.

**Comment by sandersn** [comment]
The user test failures are in packages with complex types like xstate, fp-ts and ember. @johnsoncodehk when you open a bug, it would help to look at this failures when considering how to address backward compatibility.

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this PR since it's pretty old now.

**Comment by johnsoncodehk** [comment]
No problem, and sorry I totally forgot about this!

**Comment by ssalbdivad** [comment]
Just noticed this. Maybe it would be too exotic for TypeScript's builtin types but ideally `includes` would perform a disjoint check. That could be achieved via a signature like this:

```ts
declare global {
	interface Array<T> {
		includes<U>(
			searchElement: [U & T] extends [never] ? T : U,
			fromIndex?: number
		): boolean
	}
}

declare const s: string[]

// overlaps with T, okay
declare const overlappingInput: number | string
const a = s.includes(overlappingInput)

// disjoint with T, fails
declare const disjointInput: boolean | number
const b = s.includes(disjointInput)
```

@sandersn If this is something the team would consider I'd be happy to open another issue. I know it's been a long-standing pain point, though I don't know how receptive the team would be to a solution like this.

**Comment by sandersn** [comment]
Fancy types are hard to put into the standard library. They often mess up worse than the dumb solution on corner cases, and more importantly they usually break existing code in some way -- even if it's exactly the desired breaks caused by the new solution, we can't break too much code in a single release.

**Comment by sandersn** [comment]
Typescript allows overrides of the standard library now. You could test it by compiling a bunch of existing code from github or some other place with the stricter type and see what happens.

**Pull request closed without merging**
