### PR TITLE
Fix #7224, #7441 - Replace TypeFlags.Narrowable

### LINKED ISSUE #7224: type guards strangeness
**TypeScript Version:** 

1.8.0

**Code**

```ts
const enum AsNonBlank {}
export function isNonBlank(value: string) : value is string & AsNonBlank {
    return !/^\s*$/g.test(value);
}
let value: string;
if (isNonBlank(value)) {
    doThis(value); // expected value to be string & AsNonBlank, actual: string
} else {
    doThat(value);
}
function doThis(value: string & AsNonBlank): void {
}
function doThat(value: string) : void {
}
```

**Expected behavior:**
value should either be `string & AsNonBlank`
or there must be a message saying that the type guard is invalid or something
**Actual behavior:** 
value is a `string`

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #7224, #7441 

Previously we would only narrow object types, union types, type parameters, and any.

I looked through the history of the area - this check had been here since the inception of type guards (not even user-defined ones), but I'm going to guess that as they evolved nobody ever really noticed that it would need to be removed with the advent of intersection types - given them, we can potentially need to narrow everything (since anything can be intersected with and therefore can have a subtype to narrow to).

I've replaced `TypeFlags.Narrowable` with `TypeFlags.NotNarrowable` - to make narrowing of a type class opt-out, rather than opt-in, as literally any type can be narrowed to an intersection with that type unless we've expressly choosen to forbid it. I've added `Void` to this list, as it's in-line with how we already treat void.

In essence, `TypeFlags.NotNarrowable` holds the set of types for which this function:
```ts
declare function isTagged<T>(x: T): x is (T & {__tagged: any});
```
does not narrow as expected, which, as far as I can tell, should only be `void`.

### CODE REVIEW

**Comment by tinganho** [comment]
@weswigham I believe that check was there too limit the narrowing logic for perf reasons. I guess when your removed it, it will walk up the branches and narrow it on all types?

**Comment by DanielRosenwasser** [comment]
This will end up fixing #7441, so if we take this in, we'll need two small tests (in separate files) - one for narrowing a `string` to a string literal, and the other from a `string` to a union of string literals.

**Comment by DanielRosenwasser** [comment]
As @tinganho mentioned, we'll need to check what the impact is here in terms of perf, but I imagine long term we'll need to do this anyway.

**Comment by weswigham** [comment]
@DanielRosenwasser I've reconciled the change with master and added the test you've asked for (and updated the OP to reflect the changes as they now stand).

**Comment by sandersn** [comment]
:+1:

**Comment by sandersn** [comment]
Looks like @weswigham doesn't have his commit rights back yet. So I went ahead and merged it.

**Comment by aleksey-bykov** [comment]
Thanks!

**Comment by ahejlsberg** [comment]
:-1: Whoa! I'd like to review this before we merge it.

**Comment by aleksey-bykov** [comment]
oh no

**Comment by ahejlsberg** [comment]
As was already mentioned in the discussion here this potentially has negative performance impact. Specifically, this causes us to do a full walk of the control flow graph even for primtive type variables, which are very common and obviously can't be narrowed. We used to not do this and I definitely don't want this code merged until we know what the impact is.

@sandersn Please revert the merge and let's dicuss how to proceed.

@mhegazy FYI.

**Comment by sandersn** [comment]
I'll revert it. But I did test the performance on RWC and observed no significant difference for TFS and a small but statistically significant speedup for Monaco -- about 1.5%.

**Comment by sandersn** [comment]
Here's the summary:

| Project                    |         Baseline |          Current |  Delta |   Best |  Worst |
|----------------------------|------------------|------------------|--------|--------|--------|
| Monaco - node - Parse Time |  7.65s (± 1.69%) |  7.53s (± 1.55%) | -1.69% |  7.21s |  8.10s |
| Monaco - node - Bind Time  |  1.45s (± 3.49%) |  1.42s (± 2.68%) | -1.52% |  1.31s |  1.65s |
| Monaco - node - Check Time |  9.48s (± 1.39%) |  9.34s (± 1.26%) | -1.53% |  8.81s |  9.74s |
| Monaco - node - Emit Time  |  1.94s (± 2.52%) |  1.88s (± 1.64%) | -3.17% |  1.80s |  2.00s |
| Monaco - node - Total Time | 20.52s (± 1.19%) | 20.16s (± 1.00%) | -1.75% | 19.39s | 21.11s |
| TFS - node - Parse Time    |  3.57s (± 3.42%) |  3.56s (± 3.64%) | -0.22% |  3.19s |  4.00s |
| TFS - node - Bind Time     |  1.29s (± 2.91%) |  1.26s (± 3.42%) | -2.74% |  1.13s |  1.49s |
| TFS - node - Check Time    |  7.25s (± 0.81%) |  7.28s (± 0.72%) | +0.41% |  7.14s |  7.48s |
| TFS - node - Emit Time     |  1.96s (± 0.75%) |  1.99s (± 1.31%) | +1.48% |  1.91s |  2.16s |
| TFS - node - Total Time    | 14.07s (± 1.27%) | 14.08s (± 1.14%) | +0.12% | 13.48s | 14.95s |

**Comment by ahejlsberg** [comment]
Hmm, I'm seeing a 2-3% slowdown in check time with Monaco on node.js v6.2 (Windows, 32-bit) which is more in line with what I expected (though not as much as I had feared). There's no doubt we're doing more work so I'm puzzled about your measured speed up.

I do agree that #7441 ought to be fixed.

**Comment by sandersn** [comment]
I measured on node.js 6.2 (Linux, x64). I'm using @rbuckton's new performance measurement code which I believe is quite close to the existing perf measurement (but with better benchmark-saving capability and the ability to run remotely on Linux).

**Comment by weswigham** [comment]
Is it possible to reopen this PR so it can be un-reverted at some point?

**Comment by sandersn** [comment]
This code (slightly modified) is now merged in #8993.

**Pull request merged**
