### PR TITLE
Emit 'export as namespace ts' in our bundled d.ts output

### PR DESCRIPTION
**Pull request by jakebailey**
I was reading https://johnnyreilly.com/definitely-typed-the-movie and saw the `export as namespace` syntax, which triggered a memory that made me remember that we used to have this in our output pre-modules, but I did not preserve it.

Before, we had:

- `typescript.d.ts`, which only had `export = ts`
- `tsserverlibrary.d.ts`, which had both `export = ts` and `export as namespace ts`.
- `typescriptServices.d.ts`, which just declared the `ts` namespace without exporting it.

Given we still let `ts` be loaded on the globals if not in CJS, this seems like it's correct to say that there's a global `ts` namespace when not imported.

### CODE REVIEW

**Comment by fatcerberus** [comment]
Wait, `typescript.d.ts` and `typescriptServices.d.ts` were different despite that the corresponding `.js` files were identical?

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
@DanielRosenwasser I stuck this in 5.0.3 as this feels like something we should backport for the patch release?

**Comment by DanielRosenwasser** [comment]
I'm confused, didn't we say these files shouldn't contain an `export as namespace` in chat?

**Comment by jakebailey** [comment]
I think we started with "nobody's complaining, so why bother", but Andrew (and I, originally) seemed to think that if the output file would put itself into the globals when not loaded via an import that it should have this to declare so.

**Review by weswigham — APPROVED** [review]

**Comment by jakebailey** [comment]
We're like 10 months post-module migration; given nobody has complained about this I'm just going to close this. If we ever want to change that, we can still revive this, but I really suspect anyone who wants us in a browser is just bundling anyhow.

**Pull request closed without merging**
