### PR TITLE
Ignore template literal types which contain intersections in removeStringLiteralsMatchedByTemplateLiterals

### LINKED ISSUE #52345: Performance regression from #48044
# Bug Report

It seems like a fairly significant performance regression was introduced in this https://github.com/microsoft/TypeScript/pull/48044, which was shipped in TS 4.7. In TS 4.6, it takes ~30 seconds to run `yarn tsc` in our repo, and the reported strict subtype cache size is 24_011. In TS 4.7, it takes 75+ seconds to run `yarn tsc` (~2.5x longer than previous), and the reported strict subtype cache size is 122_778 (~5x larger than previous).

I verified that it was that specific PR that regressed the performance by taking a locally-installed 4.6.4 and applying the changes from that PR directly.

Another symptom is that several types (mostly spreads of objects into others) are now reporting as "Expression produces a union type that is too complex to represent."

### 🔎 Search Terms

`Expression produces a union type that is too complex to represent`, `strict subtype cache size`

### 🕗 Version & Regression Information

- Regressed in https://github.com/microsoft/TypeScript/pull/48044
- This changed between versions 4.6.4 and 4.7.3

|Version|Time|Strict Subtype Cache Size|
|-------|-----|--------------------------|
|4.6.4  | 33s | 24011                                  |
|4.7.3  | 75s | 122778                                 |
|4.9.4  | 77s | 122869                                |
|5.0.0-dev.20230120 | 78s | 122869 |

### 💻 Code

I haven't been able to narrow down a minimal reproduction of this issue, but if someone points me in the right direction I'm happy to work on it.

### 🙁 Actual behavior

Running `yarn tsc --noEmit --extendedDiagnostics` takes ~75 seconds in our repo, with a Strict subtype cache size of 122778.

### 🙂 Expected behavior

Running `yarn tsc --noEmit --extendedDiagnostics` takes ~30 seconds in our repo, with a Strict subtype cache size of 24011.

### PR DESCRIPTION
**Pull request by jakebailey**
For #52345

There's no reason to waste time checking template literal types which contain intersections in `removeStringLiteralsMatchedByTemplateLiterals`; the only thing that these can match are other template literals with intersections too.

e.g., `"foo"` will not match `` `fo${"o" & { _brand: any}}` ``.

Before:

image

After:

image

Maybe there's still something to do to speed up `removeSubtypes` for this case; will have to look harder. But, I want feedback on this PR first.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt

**Review by weswigham — COMMENTED** [review]
Eeeeeyes and no. I think I just found a bug in `main` thinking about this (though there was also a different bug in 5.0.2). Consider:

```ts
type MaybeCat = `c${string}` & `${string}t`;
type MaybeScats = `s${MaybeCat}s`;

declare var x: MaybeScats;

x = "scats"; // should be OK
x = "scas"; // should error

```

On 5.0.2, this works, but `MaybeScats` simplifies to `sc${string}s` - the `t` requirement is silently dropped, which isn't right. But the first assignment technically works. Right now in the nightly, we've broken that - it more correctly stays as `s${MaybeCat}s` now (since the intersection is left well enough alone), but we're not chopping the string up correctly to handle comparison to the nested intersection of template literals, and as-is this would exacerbate that.

While in the above example, you could see us inlining the intersection to produce `sc${string}ts`, a more complex intersection like `a${string}b${string}c & ${string}-${string}-${string}` doesn't have an obvious non-intersected form that I can see, so I don't think we can use just intersections as an indicator that we can skip comparing against it. Intersections containing object/anonymous types (or generics constrained only to such), however, would seem to be good.

**Comment by weswigham** [comment]
Yes, I believe so. Though the example I gave was broken (albeit differently) in 5.0.2, too.

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Pull request closed without merging**
