### PR TITLE
Adds support for not duplicating trailing trivia when extracting a type

### LINKED ISSUE #31629: Extract type refactoring duplicates nearby comments
https://github.com/microsoft/vscode/issues/74310

image

image

### PR DESCRIPTION
**Pull request by orta**
Fixes #31629

```ts
type a = { x: string } /* foo */ | string /* bar */
```

The trailing trivia `bar` wasn't being included in the replace node of an when creating the type alias, and would get left behind and effectively duped. This change means that any trailing comments will be correctly deleted from the selection source.

### CODE REVIEW

**Comment by fatcerberus** [comment]
> Adds support for not duplicating trailing trivia

I love this implies it's a feature and not actually a bug. :smile:

**Comment by orta** [comment]
Haha - good point, no more features only bug fixes for 3.6!

**Comment by orta** [comment]
I just started up a debate internally about whether the trailing comment should attach itself to `a` or the `string` internally. The AST says `a` but conceptually it feels like it should be the closest node.

**Comment by orta** [comment]
After chatting about this, the summary was that in

```
type a = /*a*/{ x: string } /* foo */ | string /* bar */;
```

It should probably turn into:

```
type NewType = { x: string;	} /* foo */ | string ;
	
type a = NewType; /* bar */`
```

Which isn't what this PR does yet

**Comment by orta** [comment]
I've come back to this, and I don't think I agree with the idea of unattaching the bar in the above examples. I think this is what it looks like if you want to attach a comment to the union as a whole:

```ts
type a = ({ x: string } /* foo */ | string /* bar */) /* zap */;
```

Otherwise when doing this:

```ts
type a = { x: string } /* foo */ | string /* bar */;
```

You would not be able to attach a comment to the last part of the union (which in this case might not need one but it's still important).

I'll give it a day or two to see if others disagree ( /cc @RyanCavanaugh ) but otherwise I'll get this rebased, green and merged this week.

**Comment by sandersn** [comment]
@orta It sounds like this PR still needs some work from you to match your original spec. Did I read the history right?

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.

**Pull request closed without merging**
