### PR TITLE
Move comparer types to public namespace

### LINKED ISSUE #16782: tsserverlibrary.d.ts throws error TS2304: Cannot find name 'Comparison'
**TypeScript Version:**  2.4.1

**Code**

```ts
import * as ts from "typescript/lib/tsserverlibrary";
let factory: ts.server.PluginModuleFactory;
```

Compiling the above code, a compilation error, `error TS2304: Cannot find name 'Comparison'`, occurs.

And my tsconfig.json is the following :
(It's just generated one by `tsc --init`) 

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true
  }
}
```

**Expected behavior:**

No compilation error.

**Actual behavior:**

tsc throws the following error:

```txt
node_modules/typescript/lib/tsserverlibrary.d.ts(3845,181): error TS2304: Cannot find name 'Comparison'.
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #16782

TSServer exports some functions which take in `comparer` functions - functions whose return value is an instance of our `Comparison` enum. Both `Comparer<T>` and `Comparison` were in our internal namespace in `core.ts` (and thus elided from our `.d.ts`), but they must be public to create a valid `.d.ts` for `tsserverlibrary`, which uses these in its exported signatures.

### CODE REVIEW

**Comment by andy-ms** [comment]
Should those server utilities be public in the first place?

**Comment by weswigham** [comment]
@andy-ms `toSortedArray`, `insertSorted`, and `removeSorted` are public. Given that we require `SortedArray<T>` and `SortedReadonlyArray<T>` in a few places on the server, I'd say they're required.

**Comment by andy-ms** [comment]
I don't think there's a need to allow third-parties to call those, so they could be made internal.

**Comment by weswigham** [comment]
@andy-ms @chuckjaz Added the `enumerateInsertsAndDeletes` function in #15308, and you factored `insertSorted` and `removeSorted` out of inline-in-the-builder into utilities. So what was his and your intent? And `combineProjectOutput` has been public for a year, so if that were to be moved to use the `Comparer<T>` type, it would definitely need to be public.

Considering these are helpers for working with `SortedArray`s, which are on our public interface, I think these can stay public.

**Comment by andy-ms** [comment]
I didn't have any intents with regards to public APIs since I didn't realize I was changing them. It doesn't sound like `removeSorted` should be a public API since it's just an implementation detail.

**Comment by sheetalkamat** [comment]
I agree with @andy-ms as to not have these server utility functions public but to have them as internal instead.

**Comment by weswigham** [comment]
@andy-ms @sheetalkamat done. I've moved the offending types into an internal half of the namespace.

**Pull request merged**
