### PR TITLE
Fixed type narrowing in switch statements with parenthesized expressions

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/56030

### CODE REVIEW

**Comment by JoostK** [comment]
Ah, you beat me to it :) I would have thought it was something like this. Thanks for providing the fix (and the _incredible_ work you do for TypeScript, really)

**Comment by Andarist** [comment]
Thanks :)

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
I merged this, but I should have run the tests. In light of #56020, is there a problem here in JS code which casts the argument to a `switch`, e.g.:

```js
switch (/** @type { "a" | "b" } */ (foo)) {
	case "a":
		return;
	default: {
		const x: "b": foo
	}
}
```

**Comment by jakebailey** [comment]
Ah, yes, you should be using:

```
skipParentheses(node, /*excludeJSDocTypeAssertions*/ true)
```

**Comment by jakebailey** [comment]
Hm, I can't seem to make a test case where this fails. I thought this would show a difference but it does not:

```ts
// @strict: true
// @noEmit: true
// @checkJs: true
// @allowJs: true

// @filename: index.js

let value = "";

switch (/** @type {"foo" | "bar"} */ (value)) {
  case "bar":
    value;
    break;

  case "foo":
    value;
    break;

  case "invalid":
    value;
    break;
}
```

**Pull request merged**
