### PR TITLE
Adding an example for 6.4

### PR DESCRIPTION
**Pull request by Thomas-P**
Fixes #

I added an example for the usage of array parameters in destructuring parameter declarations.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Check out https://github.com/Microsoft/TypeScript/blob/master/doc/README.md

Please file an issue for changes to the spec.

**Comment by RyanCavanaugh** [comment]
People *keep doing this*. What can we do?

**Comment by mhegazy** [comment]
the .md format is more contributor friendly than the word format. we could just keep the md, and abandon the other two.

**Comment by DanielRosenwasser** [comment]
In the mean time, I'm going to start using https://github.com/notwaldorf/github-canned-responses.

**Pull request closed without merging**
