### PR TITLE
Fix object.assign first param constraint

### LINKED ISSUE #35621: ObjectConstructor.assign
**TypeScript Version:**  3.7.2

**Search Terms:**
ObjectConstructor, Object, assign, target, null

**Code**
```
Object.assign(null, {a:1})
```

this works because 
```
    assign<T, U>(target: T, source: U): T & U;
```
but T can't be null

**Expected behavior:**
type error is risen ts and reported by typescript-eslint

**Actual behavior:**
type error in js
```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
```

**Playground Link:** 
http://www.typescriptlang.org/play/?ssl=1&ssc=26&pln=1&pc=21#code/PIIwVgpgxgLgdAQwM5IJYHMB2AKTBXAGwIBoACAbwQC4BGAXwEog

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/3429

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #35621 
Follow-up to #36768

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by sandersn** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
@typescript-bot test this

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by sandersn** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
DT is clean.

**Comment by sandersn** [comment]
One more time:
@typescript-bot user test this

**Comment by sandersn** [comment]
User tests are clean.

**Comment by sandersn** [comment]
I'm not going to put this into 4.3 since it's a lib change.

**Review by weswigham — APPROVED** [review]

**Pull request merged**
