### PR TITLE
Revert #50757 - Object type literal with string literal property in contextual typing position causes language service error on all literal type references

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Reverts #50757
https://github.com/microsoft/TypeScript/pull/51055#discussion_r993514527

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I think the in-place fix is fine. I'm going to try to fix this with @sandersn in https://github.com/microsoft/TypeScript/pull/51066.

**Comment by sandersn** [comment]
@DanielRosenwasser As I understand your comment, you want to keep the code as-is until #51066 (or something similar) is done, right? I guess that #51066 will revert #50757 when it's ready.

If that's the case, let's close this PR.

**Comment by DanielRosenwasser** [comment]
Yup, sounds good.

**Pull request closed without merging**
