### PR TITLE
Fix running bin script for es modules with node resolution

### PR DESCRIPTION
**Pull request by tsapko3628**
Fixes [Issue #44342](https://github.com/microsoft/TypeScript/issues/44342)

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Technically a breaking change if we have people who relied on `typescript/bin/tsc` as being extensionless - but it's unclear who relied on that.

**Comment by tsapko3628** [comment]
Fixed breaking changes. Now it works correctly for
* `yarn tsc`
* `yarn run tsc`
* `yarn exec tsc`
* `npx tsc`
* `node_modules/.bin/tsc`
* running tsc in package.json scripts

Also add old tsserver for IDEs who use `node_modules/.bin/tsserver`

**Comment by tsapko3628** [comment]
I fixed it, but then I realized what it wasn't breaking changes. When you install typescript package, package manager will create symlink like this `node_modules/.bin/tsc -> node_modules/typescript/bin/tsc.js`. So, it wasn't backing changes. I can remove `bin/tsc` and `bin/tsserver` if you agree with me

**Comment by tsapko3628** [comment]
` but it's unclear who relied on that` so you know, a lot of people rely on it. I saw `node node_modules/.bin/tsc` in many projects scripts. Some people do that for adding nodejs cli options, but they also can do it via NODE_OPTIONS env.

**Comment by tsapko3628** [comment]
Could somebody review this pr? @rbuckton @RyanCavanaugh @weswigham.
It will take less than 5 minutes.

**Comment by weswigham** [comment]
You've found a bug in node's `--experimental-specifier-resolution=node` flag, not in TS. (It's not supposed to affect existing cjs code at all, after all!) You should probably report it in the `node` repo.

**Comment by tsapko3628** [comment]
Might be, but it happening because of file without extensions. You can solve it just by adding extension without any braking changes at all.

**Comment by tsapko3628** [comment]
https://github.com/nodejs/node/issues/35518
So, because of this, it's a bug for es modules

**Comment by sandersn** [comment]
@weswigham is it worth taking this fix or should we wait for a fix from node? I'm not clear on whether that will address the original bug.

**Comment by tsapko3628** [comment]
So, what about this? Nodejs major release doesn't fix problem and it maybe won't fix in next release too.
No braking changes, work with flag and without it. Looks like it'll be good for 'flag' users and won't make troubles for other users

**Comment by weswigham** [comment]
Yeah, we're not changing anything for this. Anything nonfunctional is a bug in an experimental feature in node, which we'll not bend over backwards to support ♥ - our bin file is a cjs file in a cjs package; any configuration of node that breaks that is a problem in node itself, of that I'm confident.

**Pull request closed without merging**
