### PR TITLE
Save jsdoc comments in string, not array

### PR DESCRIPTION
**Pull request by sandersn**
A cleanup of the first commit in https://github.com/microsoft/TypeScript/pull/53007, after I realised that the next good target for improvement is the scanner, and changes there might obviate the ones in #53007 

First step toward addressing #52959

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Since the perf runner is overloaded with code from main, here's the result from my perf runner with `--predictable` (which I'm playing with):

<details>
<summary>Details</summary>

Loading benchmark and comparing to baseline.
<b>Comparison Report - main..HEAD</b>
<table border="0" cellpadding="0" cellspacing="0" >
<thead>
<tr>
<th align=left><sub>Metric</sub></th>
<th align=right><sub>main</sub></th>
<th align=right><sub>HEAD</sub></th>
<th align=right><sub>Delta</sub></th>
<th align=right><sub>Best</sub></th>
<th align=right><sub>Worst</sub></th>
<th align=right><sub>p-value</sub></th>
</tr>
</thead>
<tr class="group"><th align=left colspan="7"><sub>Angular - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>292,225k (± 0.00%)</sub></td>
<td align=right><sub>292,830k (± 0.00%)</sub></td>
<td align=right><sub>+605k (+ 0.21%)</sub></td>
<td align=right><sub>292,830k</sub></td>
<td align=right><sub>292,830k</sub></td>
<td align=right><sub>p=0.001 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>3.33s (± 0.12%)</sub></td>
<td align=right><sub>3.34s (± 0.15%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>3.33s</sub></td>
<td align=right><sub>3.34s</sub></td>
<td align=right><sub>p=0.112 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>1.29s (± 0.32%)</sub></td>
<td align=right><sub>1.29s (± 0.32%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>1.28s</sub></td>
<td align=right><sub>1.29s</sub></td>
<td align=right><sub>p=1.000 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>10.30s (± 0.07%)</sub></td>
<td align=right><sub>10.32s (± 0.12%)</sub></td>
<td align=right><sub>+0.02s (+ 0.15%)</sub></td>
<td align=right><sub>10.30s</sub></td>
<td align=right><sub>10.33s</sub></td>
<td align=right><sub>p=0.046 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>8.66s (± 0.17%)</sub></td>
<td align=right><sub>8.67s (± 0.10%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>8.66s</sub></td>
<td align=right><sub>8.68s</sub></td>
<td align=right><sub>p=0.284 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>23.58s (± 0.07%)</sub></td>
<td align=right><sub>23.61s (± 0.09%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>23.59s</sub></td>
<td align=right><sub>23.65s</sub></td>
<td align=right><sub>p=0.051 n=6</sub></td>
</tr>
</tbody>
<tr class="group"><th align=left colspan="7"><sub>Compiler - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>173,592k (± 0.01%)</sub></td>
<td align=right><sub>173,637k (± 0.01%)</sub></td>
<td align=right><sub>+45k (+ 0.03%)</sub></td>
<td align=right><sub>173,632k</sub></td>
<td align=right><sub>173,659k</sub></td>
<td align=right><sub>p=0.003 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>2.00s (± 0.38%)</sub></td>
<td align=right><sub>1.99s (± 0.41%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>1.99s</sub></td>
<td align=right><sub>2.01s</sub></td>
<td align=right><sub>p=0.206 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>0.93s (± 0.00%)</sub></td>
<td align=right><sub>0.93s (± 0.56%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.92s</sub></td>
<td align=right><sub>0.93s</sub></td>
<td align=right><sub>p=0.174 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>8.97s (± 0.06%)</sub></td>
<td align=right><sub>8.99s (± 0.09%)</sub></td>
<td align=right><sub>+0.02s (+ 0.22%)</sub></td>
<td align=right><sub>8.98s</sub></td>
<td align=right><sub>9.00s</sub></td>
<td align=right><sub>p=0.004 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>3.78s (± 0.40%)</sub></td>
<td align=right><sub>3.80s (± 0.40%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>3.78s</sub></td>
<td align=right><sub>3.82s</sub></td>
<td align=right><sub>p=0.117 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>15.67s (± 0.13%)</sub></td>
<td align=right><sub>15.70s (± 0.12%)</sub></td>
<td align=right><sub>+0.03s (+ 0.18%)</sub></td>
<td align=right><sub>15.68s</sub></td>
<td align=right><sub>15.73s</sub></td>
<td align=right><sub>p=0.036 n=6</sub></td>
</tr>
</tbody>
<tr class="group"><th align=left colspan="7"><sub>Compiler-Unions - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>191,298k (± 0.01%)</sub></td>
<td align=right><sub>191,309k (± 0.01%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>191,255k</sub></td>
<td align=right><sub>191,320k</sub></td>
<td align=right><sub>p=0.262 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>1.77s (± 0.36%)</sub></td>
<td align=right><sub>1.76s (± 0.23%)</sub></td>
<td align=right><sub>-0.01s (- 0.47%)</sub></td>
<td align=right><sub>1.76s</sub></td>
<td align=right><sub>1.77s</sub></td>
<td align=right><sub>p=0.033 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>0.91s (± 0.00%)</sub></td>
<td align=right><sub>0.91s (± 0.45%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.91s</sub></td>
<td align=right><sub>0.92s</sub></td>
<td align=right><sub>p=0.405 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>10.92s (± 0.06%)</sub></td>
<td align=right><sub>10.93s (± 0.07%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>10.92s</sub></td>
<td align=right><sub>10.94s</sub></td>
<td align=right><sub>p=0.177 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>3.75s (± 0.17%)</sub></td>
<td align=right><sub>3.75s (± 0.11%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>3.75s</sub></td>
<td align=right><sub>3.76s</sub></td>
<td align=right><sub>p=0.673 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>17.35s (± 0.09%)</sub></td>
<td align=right><sub>17.35s (± 0.05%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>17.34s</sub></td>
<td align=right><sub>17.36s</sub></td>
<td align=right><sub>p=0.774 n=6</sub></td>
</tr>
</tbody>
<tr class="group"><th align=left colspan="7"><sub>Monaco - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>343,033k (± 0.00%)</sub></td>
<td align=right><sub>343,106k (± 0.00%)</sub></td>
<td align=right><sub>+73k (+ 0.02%)</sub></td>
<td align=right><sub>343,106k</sub></td>
<td align=right><sub>343,106k</sub></td>
<td align=right><sub>p=0.001 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>2.99s (± 0.28%)</sub></td>
<td align=right><sub>2.96s (± 0.35%)</sub></td>
<td align=right><sub>-0.04s (- 1.28%)</sub></td>
<td align=right><sub>2.94s</sub></td>
<td align=right><sub>2.97s</sub></td>
<td align=right><sub>p=0.004 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>1.48s (± 0.00%)</sub></td>
<td align=right><sub>1.48s (± 0.00%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>1.48s</sub></td>
<td align=right><sub>1.48s</sub></td>
<td align=right><sub>p=1.000 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>8.70s (± 0.05%)</sub></td>
<td align=right><sub>8.71s (± 0.10%)</sub></td>
<td align=right><sub>+0.02s (+ 0.19%)</sub></td>
<td align=right><sub>8.70s</sub></td>
<td align=right><sub>8.72s</sub></td>
<td align=right><sub>p=0.009 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>4.99s (± 0.10%)</sub></td>
<td align=right><sub>4.99s (± 0.11%)</sub></td>
<td align=right><sub>-0.01s (- 0.17%)</sub></td>
<td align=right><sub>4.98s</sub></td>
<td align=right><sub>4.99s</sub></td>
<td align=right><sub>p=0.038 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>18.16s (± 0.07%)</sub></td>
<td align=right><sub>18.14s (± 0.11%)</sub></td>
<td align=right><sub>-0.03s (- 0.15%)</sub></td>
<td align=right><sub>18.10s</sub></td>
<td align=right><sub>18.16s</sub></td>
<td align=right><sub>p=0.023 n=6</sub></td>
</tr>
</tbody>
<tr class="group"><th align=left colspan="7"><sub>TFS - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>298,797k (± 0.01%)</sub></td>
<td align=right><sub>298,873k (± 0.00%)</sub></td>
<td align=right><sub>+76k (+ 0.03%)</sub></td>
<td align=right><sub>298,869k</sub></td>
<td align=right><sub>298,884k</sub></td>
<td align=right><sub>p=0.003 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>2.56s (± 0.20%)</sub></td>
<td align=right><sub>2.55s (± 0.29%)</sub></td>
<td align=right><sub>-0.01s (- 0.46%)</sub></td>
<td align=right><sub>2.54s</sub></td>
<td align=right><sub>2.56s</sub></td>
<td align=right><sub>p=0.020 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>1.11s (± 0.00%)</sub></td>
<td align=right><sub>1.11s (± 0.37%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>1.11s</sub></td>
<td align=right><sub>1.12s</sub></td>
<td align=right><sub>p=0.405 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>8.51s (± 0.12%)</sub></td>
<td align=right><sub>8.49s (± 0.14%)</sub></td>
<td align=right><sub>-0.02s (- 0.24%)</sub></td>
<td align=right><sub>8.47s</sub></td>
<td align=right><sub>8.50s</sub></td>
<td align=right><sub>p=0.016 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>5.44s (± 0.12%)</sub></td>
<td align=right><sub>5.44s (± 0.18%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>5.43s</sub></td>
<td align=right><sub>5.45s</sub></td>
<td align=right><sub>p=0.733 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>17.62s (± 0.11%)</sub></td>
<td align=right><sub>17.59s (± 0.10%)</sub></td>
<td align=right><sub>-0.03s (- 0.20%)</sub></td>
<td align=right><sub>17.57s</sub></td>
<td align=right><sub>17.62s</sub></td>
<td align=right><sub>p=0.019 n=6</sub></td>
</tr>
</tbody>
<tr class="group"><th align=left colspan="7"><sub>material-ui - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>472,141k (± 0.00%)</sub></td>
<td align=right><sub>472,670k (± 0.00%)</sub></td>
<td align=right><sub>+529k (+ 0.11%)</sub></td>
<td align=right><sub>472,670k</sub></td>
<td align=right><sub>472,670k</sub></td>
<td align=right><sub>p=0.001 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>3.47s (± 0.15%)</sub></td>
<td align=right><sub>3.42s (± 0.12%)</sub></td>
<td align=right><sub>-0.04s (- 1.30%)</sub></td>
<td align=right><sub>3.42s</sub></td>
<td align=right><sub>3.43s</sub></td>
<td align=right><sub>p=0.003 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>1.18s (± 0.44%)</sub></td>
<td align=right><sub>1.14s (± 0.00%)</sub></td>
<td align=right><sub>🟩-0.04s (- 3.66%)</sub></td>
<td align=right><sub>1.14s</sub></td>
<td align=right><sub>1.14s</sub></td>
<td align=right><sub>p=0.002 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>20.77s (± 0.04%)</sub></td>
<td align=right><sub>20.75s (± 0.16%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>20.72s</sub></td>
<td align=right><sub>20.80s</sub></td>
<td align=right><sub>p=0.250 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>0.00s (± 0.00%)</sub></td>
<td align=right><sub>0.00s (± 0.00%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>0.00s</sub></td>
<td align=right><sub>0.00s</sub></td>
<td align=right><sub>p=1.000 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>25.42s (± 0.03%)</sub></td>
<td align=right><sub>25.31s (± 0.12%)</sub></td>
<td align=right><sub>-0.11s (- 0.43%)</sub></td>
<td align=right><sub>25.28s</sub></td>
<td align=right><sub>25.36s</sub></td>
<td align=right><sub>p=0.005 n=6</sub></td>
</tr>
</tbody>
<tr class="group"><th align=left colspan="7"><sub>xstate - node (v16.17.1, x64)</sub></th></tr>
<tbody>
<tr class="measurement memory scenario0 host0">
<td align=left><sub>Memory used</sub></td>
<td align=right><sub>526,111k (± 0.00%)</sub></td>
<td align=right><sub>528,020k (± 0.00%)</sub></td>
<td align=right><sub>+1,909k (+ 0.36%)</sub></td>
<td align=right><sub>528,020k</sub></td>
<td align=right><sub>528,020k</sub></td>
<td align=right><sub>p=0.001 n=6</sub></td>
</tr>
<tr class="measurement parse-time scenario0 host0">
<td align=left><sub>Parse Time</sub></td>
<td align=right><sub>4.71s (± 0.11%)</sub></td>
<td align=right><sub>4.61s (± 0.11%)</sub></td>
<td align=right><sub>-0.10s (- 2.12%)</sub></td>
<td align=right><sub>4.60s</sub></td>
<td align=right><sub>4.61s</sub></td>
<td align=right><sub>p=0.004 n=6</sub></td>
</tr>
<tr class="measurement bind-time scenario0 host0">
<td align=left><sub>Bind Time</sub></td>
<td align=right><sub>1.59s (± 0.00%)</sub></td>
<td align=right><sub>1.59s (± 0.26%)</sub></td>
<td align=right><sub>~</sub></td>
<td align=right><sub>1.59s</sub></td>
<td align=right><sub>1.60s</sub></td>
<td align=right><sub>p=0.405 n=6</sub></td>
</tr>
<tr class="measurement check-time scenario0 host0">
<td align=left><sub>Check Time</sub></td>
<td align=right><sub>3.48s (± 0.15%)</sub></td>
<td align=right><sub>3.53s (± 0.21%)</sub></td>
<td align=right><sub>+0.05s (+ 1.29%)</sub></td>
<td align=right><sub>3.52s</sub></td>
<td align=right><sub>3.54s</sub></td>
<td align=right><sub>p=0.004 n=6</sub></td>
</tr>
<tr class="measurement emit-time scenario0 host0">
<td align=left><sub>Emit Time</sub></td>
<td align=right><sub>0.09s (± 0.00%)</sub></td>
<td align=right><sub>0.12s (± 0.00%)</sub></td>
<td align=right><sub>🔻+0.03s (+33.33%)</sub></td>
<td align=right><sub>0.12s</sub></td>
<td align=right><sub>0.12s</sub></td>
<td align=right><sub>p=0.001 n=6</sub></td>
</tr>
<tr class="measurement total scenario0 host0">
<td align=left><sub>Total Time</sub></td>
<td align=right><sub>9.87s (± 0.05%)</sub></td>
<td align=right><sub>9.85s (± 0.13%)</sub></td>
<td align=right><sub>-0.03s (- 0.25%)</sub></td>
<td align=right><sub>9.83s</sub></td>
<td align=right><sub>9.87s</sub></td>
<td align=right><sub>p=0.009 n=6</sub></td>
</tr>
</tbody>
</table>
<div>
<b>System</b>
<table cellpadding="0" cellspacing="0" border="0" >
<tr><th align=right><sub>Machine Name</sub></th><td><sub>elcheapo</sub></td></tr>
<tr><th align=right><sub>Platform</sub></th><td><sub>linux 6.2.1-arch1-1</sub></td></tr>
<tr><th align=right><sub>Architecture</sub></th><td><sub>x64</sub></td></tr>
<tr><th align=right><sub>Available Memory</sub></th><td><sub>8 GB</sub></td></tr>
<tr><th align=right><sub>Available Memory</sub></th><td><sub>7 GB</sub></td></tr>
<tr><th align=right><sub>CPUs</sub></th><td><sub>6 × Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz</sub></td></tr>
</table>
</div>
<div>
<b>Hosts</b>
<ul>
<li>node (v16.17.1, x64)</li>
</ul>
</div>
<div>
<b>Scenarios</b>
<ul>
<li>Angular - node (v16.17.1, x64)</li>
<li>Compiler - node (v16.17.1, x64)</li>
<li>Compiler-Unions - node (v16.17.1, x64)</li>
<li>Monaco - node (v16.17.1, x64)</li>
<li>TFS - node (v16.17.1, x64)</li>
<li>material-ui - node (v16.17.1, x64)</li>
<li>xstate - node (v16.17.1, x64)</li>
</ul>
</div>
<div>
<table cellspacing="0" cellpadding="0" border="0" >
<tr>
<th align=left><sub>Benchmark</sub></th>
<th align=left><sub>Name</sub></th>
<th align=left><sub>Iterations</sub></th>
</tr>
<tr>
<td><sub>Current</sub></td>
<td><sub>HEAD</sub></td>
<td><sub>6</sub></td>
</tr>
<tr>
<td><sub>Baseline</sub></td>
<td><sub>main</sub></td>
<td><sub>6</sub></td>
</tr>
</table>
</div>


</details>

**Comment by jakebailey** [comment]
So, seems to be a little better, but worse in memory usage? I guess I'll be curious what the real runner says, for comparison.

**Comment by sandersn** [comment]
wellll, it mostly looks like it's shuffling the GC around, because total time hardly changes. Since memory also increases a little, I guess this one is a dead end, and I should definitely start profiling with `--predictable`. Too bad, because the code is clearer this way.

**Pull request closed without merging**
