### PR TITLE
Checking RWC/DT impact of disallowing 'keyof T' where T is known primitive

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
From #31620

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

**Comment by weswigham** [comment]
I think rarely do people ever write `keyof string` (why would you want that) - moreso they write `keyof T` and later on `T` becomes `string | {x: whatever}` or somesuch.

**Comment by fatcerberus** [comment]
How would this affect cases where a primitive is intersected with a structural type to create branded primitives, e.g. `number & { special_number: true }`?  I suppose it doesn't make any more sense to apply `keyof` to that than to `number` itself, but I'm still curious.

**Comment by RyanCavanaugh** [comment]
No RWC impact as expected. User Tests build has gone missing

**Pull request closed without merging**
