### PR TITLE
Add function names for code fixes.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
This PR gives code actions a name so we can tell which code fix is causing issues from a glance at a stack trace [in telemetry issues](https://github.com/microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3A%22Source%3A+Telemetry%22).

### CODE REVIEW

**Comment by amcasey** [comment]
I can't say for certain that the stack frame reconstructor will actually pick up these names, but it seems plausible.  @armanio123 can probably show you how to test it locally.

**Review by amcasey — APPROVED** [review]
No objections, but tooling changes might be required (or, less likely, might be impossible).

**Comment by orta** [comment]
@typescript-bot pack this

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@orta any reason you wanted to pack this?

**Comment by orta** [comment]
I was just testing the pack command, and thought it would be s are candidate

**Comment by DanielRosenwasser** [comment]
Would it make sense to cherry-pick this in for `4.5.3`? Otherwise we won't start seeing these until March or so.

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.5

**Pull request merged**
