### PR TITLE
Delete unused code in object literal binding

### PR DESCRIPTION
**Pull request by sandersn**
It doesn't do anything anymore. I'm not sure what it used to do; it's been there basically forever.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
This looks like code that just wasn't deleted in https://github.com/microsoft/TypeScript/commit/2cf51e4639af6722dbb8e41525c97a6fef5c4dde / #1423 or something. The same comment appears in `checker.ts`.

**Comment by sandersn** [comment]
Performance looks the same as before, which is not too surprising. There might be a small improvement in the case where the GC is repeatedly running out of room, but none of our tests do that.

**Review by sheetalkamat — APPROVED** [review]

**Pull request merged**
