### PR TITLE
Wrap classes with decorators or static properties in an IIFE, even for ES2015+

### PR DESCRIPTION
**Pull request by clydin**
Currently only script targets less than or equal to ES5 will wrap classes with decorators and/or static properties.  However, the wrapping is also crucial to file size optimizations for ES2015+ as well.  Without the IIFE wrapper, minification tools do not elide the class.  This is due to references to the class being present within the downlevelled decorator and static property code.
This change represents the full completion of issue #15857

### CODE REVIEW

**Comment by clydin** [comment]
@sandersn Issue #15857 was only partially fixed by #16120.  That PR only fixed the issue when the tsconfig target was ES5.  It did not fix the issue when the target was ES2015 or higher.

**Comment by rbuckton** [comment]
For ES5, we were asked to mark the IIFE with a `/** @class */` leading comment for some minifiers. Should we do this here too?

https://github.com/microsoft/TypeScript/blob/2e97918d43c089da85dcd070dc6465ea5e849825/src/compiler/transformers/es2015.ts#L790

**Comment by clydin** [comment]
Good question.  I think that makes sense considering that the IIFE represents the totality of the Typescript class definition.

**Comment by clydin** [comment]
Updated to add the `@class` comment.

**Pull request merged**
