### PR TITLE
Support rich compile on save emit reponse so we can report diagnostics

### LINKED ISSUE #30739: compileOnSaveEmitFile silently failing
I believe this behavior is by-design but it's very surprising and the user experience is poor.  The original context was Visual Studio, but I wouldn't be surprised to learn that VS Code is also affected.

tsconfig.json
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "test",
    "noEmitOnError": true,
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

(I've left the properties as originally reported in the VS bug, but moved the important ones to the top - `compileOnSave`, `outDir`, `noEmitOnError`, and `declaration`.)

file1.ts
```ts
const x = 1;
```

file2.ts
```ts
const y = 2;
```

If you edit and save `file2.ts` (e.g. 2 -> 3), VS sends `compileOnSaveAffectedFileList` and the response indicates that both files need to be emitted (since everything is global).

There are some guesses in this next bit.

First, VS sends a `compileOnSaveEmitFile` request for `file1.ts`.  It succeeds and `test\file1.js`, `test\file1.js.map` and `test\file1.d.ts` are emitted.  (Possibly, file2.ts is also supposed to be emitted?)

Once `test\file1.d.ts` exists, it becomes part of the configured project.  From this point on, any attempt to emit `file1.ts` (even for `file2.ts`) will fail, since `file1.d.ts` is both an input and an output.  Since `noEmitOnError` is true, the emit will be skipped.  At this point, compile-on-save is effectively broken and the set of output files will depend on the exact sequence of edits and saves.

The smallest possible mitigation would be to surface the/a diagnostic that caused emit to be skipped.  A better mitigation would be to alert the user that their configuration is invalid, ideally, before emitting anything.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #30739

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@uniqueiniquity can you please try it out and see if this works. Would like to get this in for 3.9

**Comment by uniqueiniquity** [comment]
@sheetalkamat trying it out now

**Comment by uniqueiniquity** [comment]
@sheetalkamat, I've validated that compile on save still works when running with these changes in VS.

**Comment by uniqueiniquity** [comment]
FWIW, just validated that if VS is updated to provide the new flag and handle the return type, diagnostics are returned in the scenario from #30739

**Pull request merged**
