### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by mhegazy**
updates the version in master to 3.0.0

@andy-ms we will need to run the tagging script on Definitely Typed

### CODE REVIEW

**Comment by mhegazy** [comment]
note to self, need to update the version on the VS branches as well.

**Comment by alfaproject** [comment]
No `2.10`? o:

**Comment by weswigham** [comment]
@alfaproject See [here](https://github.com/Microsoft/TypeScript/issues/14116#issuecomment-292581018) and [here](https://github.com/Microsoft/TypeScript/issues/14116#issuecomment-280592571)

**Comment by andy-ms** [comment]
DefinitelyTyped packages are tagged.

**Comment by alfaproject** [comment]
@weswigham I know and that's why I asked. Bumping to 3 sounds like something big is going to happen (due to the fact that you guys don't care about semver and the bumps are connected to marketing). Can't wait (:

**Pull request merged**
