### PR TITLE
Adding Diagnostic message for missing ']' and ')' in Array literal and conditional statements

### LINKED ISSUE #35597: Generalize missing token hints to more constructs
@Toxyxer recently fixed #34870. As mentioned:

_____

A great follow-up would be to make this work for

* `}` braces in
    * [ ] object literals
    * [ ] interfaces and object type literals
    * [ ] namespaces and augmentations
    * [ ] jsx expressions
* Parentheses in
    * [ ] parenthesized expressions
    * [ ] parenthesized types
    * [ ] argument lists
    * [ ] parameter lists
* Square brackets for
    * [ ] arrays
    * [ ] element accesses
    * [ ] indexed access types
    * [ ] tuple types
* Angle brackets for
    * [ ] type parameter lists
    * [ ] type argument lists
    * [ ] jsx tags
* [ ] For the `:` in ternaries, eg `a ? b : c` (maybe?)

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/34870#issuecomment-563504462_

### PR DESCRIPTION
**Pull request by keerthana1212**
Fixes #35597

### CODE REVIEW

**Review by orta — CHANGES_REQUESTED** [review]
👋🏻  this is solid work @keerthana1212 - I think it's probably time to reduce the duplication though as this logic is repeated 5 times in the codebase (if merged) (the fifth is in https://github.com/microsoft/TypeScript/pull/35586 )

I think you probably want a helper function like: 

```ts
function parseExpectedWithRecovery(openKind: SyntaxKind, closeKind: SyntaxKind, openPosition: number) {
  if (!parseExpected(openKind)) {
    const lastError = lastOrUndefined(parseDiagnostics);
    if (lastError && lastError.code === Diagnostics._0_expected.code) {
      addRelatedInfo(
        lastError,
        createDetachedDiagnostic(fileName, openBracketPosition, 1, Diagnostics.The_parser_expected_to_find_a_1_to_match_the_0_token_here, tokenToString(openKind), tokenToString(closeKind))
      );
    }
    return false;
  }
  return true;
}
```

and to call that instead of `parseExpected` in the `parseX` functions

**Comment by sandersn** [comment]
@keerthana1212 do you want to keep working on this? If not, one of us may finish it up.

**Comment by keerthana1212** [comment]
I wouldn't be able to make progress with this change. Feel free to complete
this change.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
So, undo #35586 as well?

**Comment by sandersn** [comment]
I looked closer at the code. There are 3 places that look at the last error on the stack.

1. parseErrorAtPosition. This is a longstanding, context-free check to avoid many errors on the same location. It's fine, if ad-hoc. It's the one causing the other problems.
2. parseExpectedMatchingBrackets. I think this has the same problem that you pointed out in #37497.
3. parseTypedefTag. This probably has the same problem, but I'm not sure if I could create a repro for it. And it's `@typedef`, which is a syntactic dumpster fire anyway.

I don't think a revert is the best solution here.
There are couple of other fixes I thought of:

1. Make parseErrorAtPosition and friends return `DiagnosticWithDetactedLocation | true | undefined` where `true` means a dupe and `undefined` means no error. This is the best fix as long as it isn't too slow.
2. Make parseErrorAtPosition overwrite dupes so that it keeps the last instead of the first.

**Comment by sandersn** [comment]
I tried (2) since it's a simple change and the errors are either the same or worse. They're worse in places where the parser hasn't gone too far off the rails, so it's not a good fix.

**Comment by sandersn** [comment]
(1) makes a lot of improvements to baselines. I'll put it up and run the perf tests on it.

**Pull request merged**
