### PR TITLE
Add outlining spans for call expression or arrow body

### LINKED ISSUE #38597: Support fold regions for lambda without block
## Search Terms

VSCode, Language Service

## Suggestion

Support fold regions for lambda without block

```ts
const fooBar$ = pageList$.pipe(
  map(pageList =>
    pageList.map(
      page =>
        page.pageConfig.find(
          config =>
            config.key.orgId === KeyOrgId.MyOrg &&
            config.key.Id === KeytId.MyKey,
        ).data ?? {},
    ),
  ),
  shareReplay(1),
)
```

This TypeScript code can't fold unless we change all `x=>y` to `x=>{ return y; }`

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## Related issue

https://github.com/microsoft/vscode/issues/97415

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #38597

### CODE REVIEW

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
The play together problem also existed in not only call but also other syntax. For example tagged template. And I don't think we have something to handle them.

**Comment by CyrusNajmabadi** [comment]
Nested outlining spans are the normal case (think about a call, inside a method, inside a class, inside a namespace).  So it just falls out naturally.

**Pull request merged**
