### PR TITLE
Add JSX codefix if available

### LINKED ISSUE #31938: Add a fixit for adding "jsx: true" to the tsconfig
## Search Terms

fixit quick fix jsx flag tsconfig

## Suggestion

Hitting "Quick Fix" in this error could offer to add the flag for you
{8446CBC8-3BA3-4F37-89F9-BD81DAEE9B26} png

## Use Cases

Anyone starting a reactproject

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by hoangpham95**
Verified:
* [x] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `gulp runtests` locally
* [x] There are new or updated unit tests validating the change

Fixes #31938

### CODE REVIEW

**Comment by orta** [comment]
I think `"react"` makes the most sense, `"preserve"` feels like a setting that was much more useful before people could run TypeScript through babel and now is a bit more edge-casey.

**Comment by andrewbranch** [comment]
In DefinitelyTyped:

`"jsx": "preserve"`: 49 results
`"jsx": "react"`: 505 results

That matches my intuition as well.

**Comment by hoangpham95** [comment]
Thanks @RyanCavanaugh for the feedback. Fixed `jsx: “react”` and updated test.

**Comment by DanielRosenwasser** [comment]
Verifying `"react"` because https://github.com/microsoft/TypeScript/issues/8529

**Pull request merged**
