### PR TITLE
Don't error on missing `Symbol` in `getApparentType`

### LINKED ISSUE #18893: Hard-to-diagnose "Cannot find global type 'Symbol'." error
**TypeScript Version:**  nightly (2.6.0-dev.20170930)

**Code**

```ts
interface A {
    m(x: string): void;
}

declare class B {
    m(x: string | symbol): void;
}

declare class C extends B implements A {}
```

Compile with `--lib es5 --target es6`.

**Expected behavior:**

A useful error message, containing a location of the error, and a suggestion of how to fix it.
Alternately, no error, since this code is correct.

**Actual behavior:**

```
error TS2318: Cannot find global type 'Symbol'.
```

It looks like this will be hard to fix because the error happens in type comparison; but this error was very difficult to track down so it would be nice to get an error location.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #18893

This is basically @begincalendar's suggestion.

### CODE REVIEW

**Comment by mhegazy** [comment]
>  I dislike not reporting an error at all and 

I am with @rbuckton on that..

> if we should always report the error for ScriptTarget.ES2015 and above in initChecker (which is something we used to do).

 I can not seem to remember why we changed that.

**Comment by begincalendar** [comment]
What does `initChecker` refer to?
I can't find any reference to it in the current codebase.

Is the concern regarding the use of the `Symbol()` call?
If so, wouldn't that be covered by global name checking?

**Comment by mhegazy** [comment]
> What does initChecker refer to?

the intializaiton code that happens in `createTypeChecker`, e.g. https://github.com/Microsoft/TypeScript/blob/728d2a92ce2f3771ce726f4f6094eba094113ef9/src/compiler/checker.ts#L279

**Comment by begincalendar** [comment]
>> if we should always report the error for ScriptTarget.ES2015 and above in initChecker (which is something we used to do).

> I can not seem to remember why we changed that.

Does it have anything to do with this comment:
https://github.com/Microsoft/TypeScript/blob/728d2a92ce2f3771ce726f4f6094eba094113ef9/src/compiler/checker.ts#L320-L322

i.e. that the global symbol type was made to be deferred?

**Comment by mhegazy** [comment]
closing for now. feel free to reopen if you plan on perusing a different approach as noted in my comments, and @rbuckton's.

**Pull request closed without merging**
