### PR TITLE
Emits safe value for import.

### LINKED ISSUE #4354: Invalid identifiers generated when importing files with leading numbers
Targeting commonjs, when importing files with leading numbers in their names results in invalid js emitted.

Given these inputs:

### 10_lib.ts
```
export function Foo(){};
```

### main.ts
```typescript
import { Foo } from './10_lib';

Foo();
```

Compiling with

```
$ tsc --modules commonjs main.ts
```

Generates

### main.js
```
var 10_lib_1 = require('./10_lib');
10_lib_1.Foo();
```

Which is invalid, and when run errors with:

```
$ node main.js
.../main.js:1
(function (exports, require, module, __filename, __dirname) { var 10_lib_1 = r
                                                                  ^^
SyntaxError: Unexpected token ILLEGAL
```

### PR DESCRIPTION
**Pull request by DavidSouther**
Fixes #4354

### CODE REVIEW

**Comment by DavidSouther** [comment]
Working on adding some tests now.

**Comment by mhegazy** [comment]
Thanks!

**Comment by DavidSouther** [comment]
No, thank *you*! What's the lag time on bugfix released to npm?

**Comment by DanielRosenwasser** [comment]
@DavidSouther you can get our nightly with `npm install -g typescript@next`. Should be up by ~midnight Pacific time.

**Comment by DanielRosenwasser** [comment]
@mhegazy this doesn't ensure uniqueness, and in fact, the old function didn't either.

**Comment by mhegazy** [comment]
@DanielRosenwasser, this is just the basename, we then call `makeUniqueName` with the basename as a seed. this makes sure it is unique.

**Pull request merged**
