### PR TITLE
Fix __importDefault when used on typescript libraries

### LINKED ISSUE #51473: __esModule in ts cause breaking change
In https://github.com/microsoft/TypeScript/pull/51387 the codebase changed to use ESBuild. And now `require('typescript')` will include `__esModule: true` and that is a breaking change.

```
> require("typescript").version
'4.9.2-rc'
> require("typescript").__esModule
undefined
>
```

```
> require('typescript').version
'5.0.0-dev.20221109'
> require('typescript').__esModule
true
>
```

This crashes https://github.com/hipstersmoothie/react-docgen-typescript-plugin

```
TypeError: Cannot read properties of undefined (reading 'JsxEmit')
    at DocgenPlugin.getOptions (node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js:246:39)
```

It's output code uses `tslib.importDefault` to import typescript.

```ts
const typescript_1 = tslib_1.__importDefault(require("typescript"));
let compilerOptions = {
    jsx: typescript_1.default.JsxEmit.React,
    //   ~~~~~~~~~~~~~~~~~~~~ ts namespace before, undefined after
    module: typescript_1.default.ModuleKind.CommonJS,
    target: typescript_1.default.ScriptTarget.Latest,
};
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #51473

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
This does fix the issue, but, I'm not 100% sure this is good or not. `default` and `__esModule` really are a mess.

**Comment by AlCalzone** [comment]
Not sure if this is any help, but esbuild mention this in their docs
https://esbuild.github.io/content-types/#default-interop

**Comment by jakebailey** [comment]
Yeah, I've seen that, and https://github.com/evanw/bundler-esm-cjs-tests. Unfortunately it seems like in addition to this other stuff, tslib / TS's helpers are another aspect that need to be considered, so I don't know if I can extract a decision out of that. I'll just have to test a bunch of cases, I guess.

**Comment by jakebailey** [comment]
A table of behaviors:

Testing with `const ts = require("typescript")`:
| test | 4.8.4 | main | this PR |
| - | - | - | - |
| `ts.version` | ✅ | ✅ | ✅ |
| `ts.default.version` | ❌ | ❌ | ✅ |
| `__importDefault(ts).version` | ❌ | ✅ | ✅ |
| `__importDefault(ts).default.version` | ✅ | ❌ | ✅ |
| `__importStar(ts).version` | ✅ | ✅ | ✅ |
| `__importStar(ts).default.version` | ✅ | ❌ | ✅ |

**Comment by jakebailey** [comment]
Maybe @weswigham or @rbuckton have some insight here? (See also the issue in question, #51473.)

**Comment by weswigham** [comment]
I'm not a huge fan - we tell people _not_ to do this _all the time_. Since we only want this for compat, I imagine manipulating the marker may be better. Which, on that note, can't we make the marker not be emitted by using `export = ts` instead of `export *`?

**Comment by jakebailey** [comment]
I haven't found a way yet. esbuild's `toCommonJS` helper always adds it and I haven't been able to get to do what I want.

Also, `export = ts` is a d.ts feature only, so that wouldn't be the solution. I have tried `module.exports = ts` (the equivalent outside of declarations) and that doens't work.

I guess I can just hack it...

**Comment by jakebailey** [comment]
Hm, but that only helps the bundler. It breaks everything else :(

**Comment by weswigham** [comment]
> Also, export = ts is a d.ts feature only, so that wouldn't be the solution

Wot? It's definitely a runtime feature we transpile to `module.exports = ts`, we just only allow it for cjs module targets.

**Comment by jakebailey** [comment]
With a hack in place to drop this helper:

| test | 4.8.4 | main | #51474 |
| - | - | - | - |
| `ts.version` | ✅ | ✅ | ✅ |
| `ts.default.version` | ❌ | ❌ | ❌ |
| `__importDefault(ts).version` | ❌ | ✅ | ❌ |
| `__importDefault(ts).default.version` | ✅ | ❌ | ✅ |
| `__importStar(ts).version` | ✅ | ✅ | ✅ |
| `__importStar(ts).default.version` | ✅ | ❌ | ✅ |

So, that restores the status quo.

See also https://github.com/evanw/esbuild/issues/1971 but this does seem to be exactly the thing the esbuild docs refer to. I was unable to get the suggestions there to work; neither `mts` nor `"type": "module"` changed this behavior. So I think we're stuck with this hack.

**Comment by jakebailey** [comment]
> Wot? It's definitely a runtime feature we transpile to module.exports = ts, we just only allow it for cjs module targets.

Huh, you're right. I must have tested and gotten an error for this a while ago and then assumed it was because `export =` was d.ts only. I could have sworn I read that...

**Comment by jakebailey** [comment]
Okay, changed to `export =`. This leaves us with this state:

| test | 4.8.4 | main | main --no-bundle | this PR | this PR --no-bundle |
| - | - | - | - | - | - |
| `ts.version` | ✅ | ✅ | ✅ | ✅ | ✅ |
| `ts.default.version` | ❌ | ❌ | ❌ | ❌ | ❌ |
| `__importDefault(ts).version` | ❌ | ✅ | ✅ | ❌ | ✅ |
| `__importDefault(ts).default.version` | ✅ | ❌ | ❌ | ✅ | ❌ |
| `__importStar(ts).version` | ✅ | ✅ | ✅ | ✅ | ✅ |
| `__importStar(ts).default.version` | ✅ | ❌ | ❌ | ✅ | ❌ |

So, this makes us match old TS when bundled, which was the goal. `--no-bundle` doesn't work quite the same, but this PR doesn't seem to change that behavior, so that's fine.

**Comment by jakebailey** [comment]
Wait, what, it's broken again. Ugh. Bear with me :(

**Comment by jakebailey** [comment]
This should be final now, if you wanted to take another look. I plan to add smoke tests for this to #51464.

**Review by weswigham — APPROVED** [review]

**Comment by rbuckton** [comment]
Why not use `export *` and add a default export?

**Pull request merged**
