### PR TITLE
[WIP] Server shared resolutions

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot user test tsserver
@typescript-bot test tsserver top256

**Comment by sheetalkamat** [comment]
@DanielRosenwasser this is not yet done.. infact i am pushing a commit at a time so i can run all incremental tests to verify each change is ok..

**Comment by Elimuhub-coder** [comment]
Taps_Saved

**Comment by Elimuhub-coder** [comment]
Words_Completed
document’s readability and level statistics by selecting the Home tab, choosing Editor, and then going to Document stats[1](https://support.microsoft.com/en-us/office/get-your-document-s-readability-and-level-statistics-85b4969e-e80a-4777-8dd3-f7fc3c8b3fd2). [You can also view document statistics by clicking the File tab in the Ribbon, selecting Info, and then looking under Properties](https://www.avantixlearning.ca/microsoft-word/how-to-view-document-statistics-in-microsoft-word/)[2](https://www.avantixlearning.ca/microsoft-word/how-to-view-document-statistics-in-microsoft-word/). Is this what you

**Comment by sheetalkamat** [comment]
@typescript-bot user test tsserver
@typescript-bot test tsserver top256

**Pull request closed without merging**
