### PR TITLE
[Experiment] feat(18497): New Feature Requesting for const Parameter

### LINKED ISSUE #18497: New Feature Requesting for `const` Parameter
I have a small **new feature** to request. Let say we have this piece of code:
```ts
function setButton(button: Button | undefined) {
    if (button) {
        button.onclick = () => {
            // tsc complains button might be undefined(well done!), 
            // because it might be set to undefined later on,
            // as you can see below `button = undefined;`. 
            button.setAttribute('disabled', 'true'); //error
        }
    }
    // some other code goes here...
    // and eventually, button is set to undefined.
    button = undefined;
}
```
Fortunately, there is a way to fix this:
```ts
function setButton(button: Button | undefined) {
    const constButton = button;
    if (constButton) {
        constButton.onclick = () => {
            // now tsc is satisfied.
            constButton.setAttribute('disabled', 'true'); 
        }
    }
    
    // impossible to assign to a const variable.
    // constButton = undefined;
}
```
But can we twist the code a little bit, which is what I asking for? Something like this:
```ts
function setButton(const button: Button | undefined) {
    if (button) {
        button.onclick = () => {
            button.setAttribute('disabled', 'true'); 
        }
    }
}
```
So you can see there really are some cases a `const` parameter might come to handy. Thank you.

P.S. Just for demonstrating the point, here's a full demo:
```ts
class Button {
    onclick?: () => void;
    performClick() {
        if (this.onclick) this.onclick();
    }
    setAttribute(key: string, value: string) {
        //set attribute to this button
    }
}

function setButton(button: Button | undefined) {
    if (button) {
        button.onclick = () => {
            button.setAttribute('disabled', 'true');
        }
    }
    button = undefined;
}

const button = new Button();
setButton(button);
button.performClick();
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #18497
> The thing we've discussed (offline?) is just having a setting for "all parameters are always const", since in practice it isn't much of a burden to always write code that way. Introducing an actual inline const keyword is unlikely to happen due to this being an area clearly in TC39's domain. https://github.com/microsoft/TypeScript/issues/18497#issuecomment-738941020

### CODE REVIEW

**Comment by Andarist** [comment]
One concern related to the name of this setting - there are proposals for "const contexts" of parameters and this name can easily clash with those potential features.

A const context~ would allow literals to be inferred for schema-like arguments:
```ts
declare function constIdentity<const T>(a: T): T 

const result = constIdentity({ type: 'test' })
//    ^? const result: { type: 'test' }
// whereas without this feature this currently gets inferred to { type: string }
```

Note that I've obviously just invented some syntax and perhaps this feature would look completely differently (if it ever becomes a thing in the first place) but we can see how it's not that unlikely that `const` keyword could potentially be somehow involved in such a feature (as it would relate nicely to existing `as const`)

**Comment by fatcerberus** [comment]
True, but there’s also `const foo = 42;` which this is analogous to (prevents reassignment, vs. normal parameter semantics which act like `let`).  So that potentially confusing overloading of the meaning of `const` already exists in TS.

**Comment by sandersn** [comment]
I like this idea, but it feels a bit like a lint rule in that I would want to disable it on purpose about 2% of the time. It's a lot like noUnusedParameters or noUnusedLocals, which I also wish were lint rules.

**Comment by a-tarasyuk** [comment]
> It's a lot like noUnusedParameters or noUnusedLocals, which I also wish were lint rules.

@sandersn Do you think avoiding adding _lint-like_ options would be better? It's just an experiment (_from time to time I create experiments to get feedback from the TypeScript team or community)_, so I'm okay with closing it to reduce the number of PRs.

**Comment by sandersn** [comment]
I'd prefer to close the PR and keep the issue open until we decide on something final there. The semantics of a suggestion often change and the compiler code changes often, meaning that early work usually has to be redone.

**Pull request closed without merging**
