### PR TITLE
Disable JSX recovery hack when in unary expression context

### LINKED ISSUE #53114: TS Server fatal error:  Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.1.0-dev.20230304

**Steps to reproduce crash**

1. Open up visual studio
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.
    at cast (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:3440:16)
    at Object.parenthesizeOperandOfPrefixUnary (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:21770:50)
    at Object.createPrefixUnaryExpression (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:23899:41)
    at parsePrefixUnaryExpression (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:33504:32)
    at parseSimpleUnaryExpression (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:33556:16)
    at parseUnaryExpressionOrHigher (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:33538:35)
    at parseBinaryExpressionOrHigher (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:33456:25)
    at parseAssignmentExpressionOrHigher (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:33129:18)
    at parseExpression (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:33095:16)
    at doOutsideOfContext (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:30792:12)
    at allowInAnd (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:30813:12)
    at parseExpressionOrLabeledStatement (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:34607:24)
    at parseStatement (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:34839:12)
    at parseListElement (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:31563:12)
    at parseList (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:31548:19)
    at parseSourceFileWorker (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:30608:24)
    at Object.parseSourceFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:30441:20)
    at createSourceFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:30274:21)
    at createLanguageServiceSourceFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:135181:22)
    at acquireOrUpdateDocument (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:132099:26)
    at Object.acquireDocumentWithKey (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:132024:12)
    at getOrCreateSourceFileByPath (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:135505:31)
    at Object.getOrCreateSourceFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:135485:14)
    at c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:135417:42
    at Object.getSourceFileWithCache [as getSourceFile] (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:117176:24)
    at findSourceFileWorker (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:119508:23)
    at findSourceFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:119428:20)
    at c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:119377:22
    at getSourceFileFromReferenceWorker (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:119346:26)
    at processSourceFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:119375:5)
    at processRootFile (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:119171:5)
    at c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:117956:41
    at forEach (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:2307:22)
    at createProgram (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:117956:5)
    at synchronizeHostData (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:135441:15)
    at Object.getProgram (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:135513:5)
    at ConfiguredProject2.updateGraphWorker (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:172332:41)
    at ConfiguredProject2.updateGraph (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:172269:32)
    at ConfiguredProject2.updateGraph (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:173487:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:175098:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:176189:26)
    at c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:176469:64
    at flatMap (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:2555:17)
    at _ProjectService.applyChangesInOpenFiles (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:176469:24)
    at updateOpen (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:177617:29)
    at c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:180167:69
    at IpcIOSession.executeWithRequestId (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:180159:14)
    at IpcIOSession.executeCommand (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:180167:29)
    at IpcIOSession.onMessage (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:180209:51)
    at process.<anonymous> (c:\Users\Bruger\.vscode\extensions\ms-vscode.vscode-typescript-next-5.1.20230304\node_modules\typescript\lib\tsserver.js:181777:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.80GB free)|
|Process Argv|--folder-uri file:///c%3A/Coding/MadegoConsumerApp --crash-reporter-id 0751c08f-edc1-48a4-8acc-5ac0ff5a8c75|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-color|ans|0.4.5
heroicons-preview|BBu|1.0.0
vscode-intelephense-client|bme|1.9.5
vscode-tailwindcss|bra|0.9.7
multi-cursor-case-preserve|Car|1.0.5
json-tree-view|Cha|2.6.0
path-intellisense|chr|2.8.4
javascript-ejs-support|Dig|1.3.3
netcore-snippets|dog|3.15.2
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.3.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.4
auto-rename-tag|for|0.1.10
vscode-mysql|for|0.4.1
vscode-chatgpt|gen|3.9.4
copilot|Git|1.77.9225
vscode-pull-request-github|Git|0.58.2
bootstrap5-snippets|Han|1.2.5
rest-client|hum|0.25.1
mysql-syntax|jak|1.3.1
dupchecker|jia|0.1.7
sequelize-snippets|kvc|1.0.0
font-awesome-codes-css|med|0.1.1
vscode-typescript-next|ms-|5.1.20230304
vsliveshare|ms-|1.0.5832
sftp|Nat|1.16.2
material-icon-theme|PKi|4.24.0
vscode-css-peek|pra|4.2.0
tpl-lang|qiq|0.0.1
vscode-thunder-client|ran|2.5.0
asp-classic-support-v2|SUR|0.7.1
Web-VSCode-Extensions|Syn|20.4.48
msbuild-project-tools|tin|0.4.9
vscode-import-cost|wix|3.3.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849

```

</details>

### LINKED ISSUE #53637: TS Server fatal error:  Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.0.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**

Server: `semantic`

```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isUnaryExpression'.
    at cast (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:3443:16)
    at Object.parenthesizeOperandOfPrefixUnary (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:21786:50)
    at Object.createPrefixUnaryExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:23915:41)
    at parsePrefixUnaryExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33520:32)
    at parseSimpleUnaryExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33572:16)
    at parseUnaryExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33554:35)
    at parseBinaryExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33472:25)
    at parseAssignmentExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33145:18)
    at parseArgumentOrArrayLiteralElement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34228:170)
    at parseListElement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31579:12)
    at parseDelimitedList (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31818:24)
    at parseArrayLiteralExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34241:22)
    at parsePrimaryExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34178:16)
    at parseMemberExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33655:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33649:82)
    at parseUpdateExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33624:24)
    at parseUnaryExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33550:32)
    at parseBinaryExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33472:25)
    at parseAssignmentExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33145:18)
    at parseArgumentOrArrayLiteralElement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34228:170)
    at parseListElement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31579:12)
    at parseDelimitedList (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31818:24)
    at parseArrayLiteralExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34241:22)
    at parsePrimaryExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34178:16)
    at parseMemberExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33655:24)
    at parseLeftHandSideExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33649:82)
    at parseUpdateExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33624:24)
    at parseUnaryExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33550:32)
    at parseBinaryExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33472:25)
    at parseAssignmentExpressionOrHigher (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33145:18)
    at parseExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33111:16)
    at doOutsideOfContext (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30808:12)
    at allowInAnd (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30829:12)
    at parseExpressionOrLabeledStatement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34623:24)
    at parseStatement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:34855:12)
    at parseListElement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31579:12)
    at parseList (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31564:19)
    at parseSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30624:24)
    at Object.parseSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30457:20)
    at createSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30290:21)
    at createLanguageServiceSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135139:22)
    at acquireOrUpdateDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:132053:26)
    at Object.acquireDocumentWithKey (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:131978:12)
    at getOrCreateSourceFileByPath (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135464:31)
    at Object.getOrCreateSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135444:14)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135376:42
    at Object.getSourceFileWithCache [as getSourceFile] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117127:24)
    at findSourceFileWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119460:23)
    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119380:20)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119329:22
    at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119298:26)
    at processSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119327:5)
    at processRootFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119123:5)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117908:41
    at forEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2307:22)
    at createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117908:5)
    at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135400:15)
    at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135472:5)
    at ConfiguredProject2.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172153:41)
    at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:172090:32)
    at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:173272:24)
    at _ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174879:13)
    at _ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175970:26)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176250:64
    at flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2555:17)
    at _ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176250:24)
    at updateOpen (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177395:29)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179962:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179954:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179962:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:180004:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:181571:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|27, 19, 14|
|Memory (System)|32.00GB (3.18GB free)|
|Process Argv|--crash-reporter-id 2e515fa3-9ac9-427f-b4e8-572c4c6c77ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-expo|byC|0.9.2
path-intellisense|chr|2.8.4
gitignore|cod|0.9.0
vscode-eslint|dba|2.4.0
xml|Dot|2.5.1
gitlens|eam|13.4.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
codespaces|Git|1.14.2
remotehub|Git|0.54.0
vscode-pull-request-github|Git|0.62.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.24.0
remote-repositories|ms-|0.32.0
vscode-react-native|msj|1.10.2
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.25.0
vscode-xml|red|0.24.0
vscode-yaml|red|1.12.2
code-spell-checker|str|2.20.3
code-spell-checker-portuguese-brazilian|str|2.0.12
markdown-all-in-one|yzh|3.5.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30677850
vscodeenable:30660116
pythonb192:30669360
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #53114
Fixes #53637

I broke this in #52667 by adding a new call to the JSX element parser. That element parser has a unique recovery method which returns a `BinaryExpression`, but, this is incompatible with unary expressions, which cannot contain binary expressions.

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]

**Review by DanielRosenwasser — APPROVED** [review]
I guess the fix here is okay - it seems overly-targeted to a specific code path though. My feeling is the right thing to do is to only do the recovery step when everything prior to the `<` had no errors.

**Review by DanielRosenwasser — COMMENTED** [review]
also using "crash" in the test name - I'm not huge on it

**Comment by jakebailey** [comment]
> I guess the fix here is okay - it seems overly-targeted to a specific code path though. My feeling is the right thing to do is to only do the recovery step when everything prior to the < had no errors.

If that were the implementation, then I think we'd end up crashing on this code too: `~<></> <`, or the code that the comment above this code mentions, `<div></div><div></div>`. So I feel like the fix in this PR is correct.

> also using "crash" in the test name - I'm not huge on it

I feel like we've somewhat consistently done this:

```
$ ls tests/cases/compiler | grep -i crash | wc -l
63
```

If it were me I'd call this test case `issue53637.ts`!

**Comment by DanielRosenwasser** [comment]
Duh - good point. Could you add that case though?

**Comment by jakebailey** [comment]
Yes, will do.

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.0

**Pull request merged**
