### PR TITLE
Stop considering symbol names when checking type parameter identity

### LINKED ISSUE #5378: Identity comparisons of type parameters with different names
From spec, 3.11.2:
> Two call or construct signatures are considered identical when they have the same number of type
parameters with identical type parameter constraints and, after substituting type Any for the type
parameters introduced by the signatures, identical number of parameters with identical kind (required, optional or rest) and types, and identical return types

Nowhere does it say that type parameters should have identical names.

But this code is highlighted with error in playground:
```ts
class c {
	get x(): <T>(a: T) => T { return null; }
	set x(p: <U>(a: U) => U) {}
}
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #5378.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by vladima** [comment]
:+1:

**Comment by mhegazy** [comment]
did you run the perf tests?

**Comment by weswigham** [comment]
Ran perf tests - I don't see a perf difference with this patch applied.

**Pull request merged**
