### PR TITLE
Fix for #2971, adds missing logic in checkFunctionExpressionBodies

### PR DESCRIPTION
**Pull request by rbuckton**

### CODE REVIEW

**Comment by mhegazy** [comment]
can you add a test as well.

**Comment by rbuckton** [comment]
@mhegazy, added.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
Please note that his needs to be ported to release-1.5 branch

**Comment by rbuckton** [comment]
This has been merged into release-1.5 as well.

**Pull request merged**
