### PR TITLE
Fix `export as namespace` error when compiling with declarations

### LINKED ISSUE #10933: Referencing an exported namespace causes compilation error when using --declaration flag
**TypeScript Version:**  2.0.2

**Code**

moduleA.d.ts
```ts
export interface A {
    b: number;
}
export as namespace moduleA;
```

moduleB.ts
```ts
module moduleB {
    export interface ILoveMom {
        math: moduleA.A;
    }
}
```

Compiled with `declaration: true`

**Expected behavior:**
No error
**Actual behavior:** 
an error is given
```
src/moduleB.ts(3,15): error TS4033: Property 'math' of exported interface has or is using private name 'moduleA'.
```

You can download the code from here: https://github.com/nchen63/typescriptRepro

### PR DESCRIPTION
**Pull request by nchen63**
Fixes #10933

### CODE REVIEW

**Comment by nchen63** [comment]
@mhegazy

**Comment by nchen63** [comment]
I didn't think this warranted a unit test, but I can add a simple one under test/cases/projects

**Comment by nchen63** [comment]
ok, added tests

**Comment by mhegazy** [comment]
you did not need a project test. a unit test with `@declaration: true` at the top would have done the job.

**Pull request merged**
