### PR TITLE
Remove superCallShouldBeFirst error

### LINKED ISSUE #37371: Cannot compile when derived class has at least one #private field and constructor has statements before super()
**TypeScript Version:**  3.8.3

**Search Terms:**
super(), #private field, derived class, overload constructor

**Code**
```ts
export class A {
    constructor() {

    }
}

export class B extends A {
    #field: any;

    constructor() {
        1;
        super()
        this.#field = "any";
    }
}
```

**Expected behavior:**
should compile

**Actual behavior:**
compiler complains with 
"A 'super' call must be the first statement in the constructor when a class contains initialized properties, parameter properties, or private identifiers.(2376)"

whereas if I use the "private" keyword instead of "#" it works perfectly fine

```ts
export class B extends A {
    private field: any;

    constructor() {
        1;
        super()
        this.field = "any"; // no complaints
    }
}
```

**Playground Link:** 
http://www.typescriptlang.org/play/?ts=3.9.0-dev.20200311#

**Related Issues:**

### PR DESCRIPTION
**Pull request by sandersn**
It seems redundant since TS gives an error on any use of `this` before super, and non-`this` uses before `super` should be fine.

Fixes #37371

### CODE REVIEW

**Comment by sandersn** [comment]
https://github.com/microsoft/TypeScript/pull/5833#discussion_r50729856 from the original PR of the `this` error implies that it does make the blanket error redundant.

**Comment by rbuckton** [comment]
Wasn't this error due to how our transform for properties works? If you allow any non-`this` statement before `super` in a class with property initializers then we could have issues:

```ts
// ts
class D {
    constructor(f: number) { }
}

class C extends D {
  x = 1;
  constructor(f: boolean) {
   if (f) { super(1); } else { super(2); }
  }
}

// es2015
"use strict";
class D {
    constructor(f) { }
}
class C extends D {
    constructor(f) {
        this.x = 1; // oops?!
        if (f) {
            super(1);
        }
        else {
            super(2);
        }
    }
}

```

**Comment by rbuckton** [comment]
We would need to completely rewrite our class field emit transforms before we could remove this error.

**Comment by weswigham** [comment]
We can remove this error when target is `esnext` though, right?

**Comment by sandersn** [comment]
@weswigham `esNext` + `useDefineForClassFields`

**Comment by sandersn** [comment]
All right, the change now just removes the error for esnext+useDefineForClassFields.

**Comment by sandersn** [comment]
ping @weswigham @rbuckton to look at the reduced change.

**Pull request merged**
