### PR TITLE
fix: formatting for chaining methods

### LINKED ISSUE #20996: Formatting with Language service for chaining methods
**TypeScript Version:**  2.7.0-dev.20180104

I am using `VScode` which uses `typescript-formatter` which uses `TypeScript  Language Service` and it looks like formatting chaining methods is not yet supported. 

**Code**
```ts
@Effect()
getMarket$: Observable<Action> = this.actions$
  .ofType(MARKET_ACTION_TYPE.getAll)
  .pipe(
    switchMap(() =>
      this.service
        .getAll()
        .pipe(
          map(result => this.action.getSuccess(result)),
          catchError((response: AppError) => of(this.action.getFail(response)))
        )
    )
  );
```

**Expected behavior:**
That the formatting is retained, or when it's wrong it's formatted correct.

**Actual behavior:**
```ts
@Effect()
  getMarket$: Observable<Action> = this.actions$
    .ofType(MARKET_ACTION_TYPE.getAll)
    .pipe(
    switchMap(() =>
      this.service
        .getAll()
        .pipe(
        map(result => this.action.getSuccess(result)),
        catchError((response: AppError) => of(this.action.getFail(response)))
        )
    )
    );
```

### PR DESCRIPTION
**Pull request by alan-agius4**
Support formatting on chaining methods

Fixes #20996

### CODE REVIEW

**Comment by alan-agius4** [comment]
@IgorNovozhilov

**Comment by alan-agius4** [comment]
@mhegazy

**Comment by alan-agius4** [comment]
@mhegazy bump.

**Comment by mhegazy** [comment]
@andy-ms mind reviewing this change

**Comment by andy-ms** [comment]
I tested out the test file and it already passes in `master`. The test doesn't have any `OpenBracketToken`s so it makes sense that it's not affected by the change.

**Comment by alan-agius4** [comment]
I just got `typescript@next` still the formatting is not correct unless I add this piece of code.

Can you explain why this`(`  Isn't a `OpenBracketToken`? I from the debug I can see that there the kind is `19` which AFAIK is `OpenBracketToken`.

Maybe I did something wrong with the test case? Cause I can see that my code is fixing the bug. I did a GIF demonstrating the issue and fix maybe I am missing something ;/ 

jan-10-2018 21-03-55p

**Comment by andy-ms** [comment]
You might want to test with `format.document(); verify.currentFileContentIs(`...`);` in addition to `verify.indentationAtPositionIs` tests.

**Comment by alan-agius4** [comment]
Okay thnaks, I'll have a look tomorrow as also with my change now I broke 2 test haha.

**Comment by alan-agius4** [comment]
hey @andy-ms I might need some help here please, Can you point me to where should I be looking? I tried to look a bit on how to solve the 2 tests failing however I didn't have any success.

**Comment by alan-agius4** [comment]
Hey @andy-ms I think I finally figured it out. I pushed some changes. Can you please review it again?

Thanks!

**Comment by alan-agius4** [comment]
@andy-ms reminder.

**Pull request merged**
