### PR TITLE
feat(eslint): consistent-type-assertions

### PR DESCRIPTION
**Pull request by a-tarasyuk**
[`consistent-type-assertions`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-assertions.md#enforces-consistent-usage-of-type-assertions-consistent-type-assertions) - Enforces consistent usage of type assertions

/cc @sandersn

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
cc @sandersn

**Comment by sandersn** [comment]
I think this is a good idea. Adding a couple more people who have had style- or lint-related opinions to review.

**Comment by sandersn** [comment]
@a-tarasyuk I'm not going to merge this until the end of 4.3's beta, so you may not want to spend a lot of time merging from master until then.

**Review by sandersn — APPROVED** [review]
Bring this up to date with master and I'll merge it.

**Pull request merged**
