### PR TITLE
`in` operator shouldn't narrow `{}` originating in `unknown`

### LINKED ISSUE #50531: Different behavior for {} and unknown narrowed to {}
# Bug Report

I found a curious situation in Typescript 4.8 where a variable of type `unknown` narrowed down to `{}` behaves differently than a variable of type `{}` from the beginning.

### 🔎 Search Terms

4.8, narrow, in
Not sure if it is related to #50527.

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it relies on a new 4.8 feature.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta&ssl=18&ssc=2&pln=1&pc=1#code/MYewdgzgLgBAZjAvDAFADwFwwN4F8A0MAnlgK5gDWYIA7mAJRIB8OAUAJACWCKAhCgCIAhgJicwMNPUbYO7AE4BTKKXlgA3B1wdQkEABtFAOn0gA5unqb2AehuSY0IUQg5cqTq+qwwQ+fNpFABN6Qm8YEAAHKE4AWyF9GAAjUlghWEMhaBhwmgCwM1YOblReIhk5JRU1a21beyIxLz8AmmCYKBA3Iq4efmFRcWJpNnYFZVUNLR1wCANjUwty6ztiJpyWwKCOrrBFADdFeUIaAAtOYFP14Ez5fUbxUH9FYChCITBtyKqoRuh5D5mRTJF5CUgQYGcWCnITbKCnYEQISxYG-SLArIOJKKOAgJQwD7bNoweTkDoIxzI4FmUh+IKsXBAA)

### 💻 Code

```typescript
const f = (x: {}, y: unknown) => {
  if (!("a" in x)) {
    return;
  }
  console.log(x);
  // x stays {} (is not narrowed), not optimal but at least not wrong

  if (!y) {
    return;
  }
  // y is narrowed to {}

  if (!("a" in y)) {
    return;
  }
  console.log(y);
  // y is narrowed to never, which is clearly incorrect, and pretty strange because
  // it had the same type as x before and we run the same guard
}
```

### 🙁 Actual behavior

Narrowing `unknown` to `{}` and then using the `in` operator results in an incorrect type, whereas it doesn’t happen when starting with a variable of type `{}`.

### 🙂 Expected behavior

Narrowing should behave the same way whether we start with the type `{}` or narrow `unknown` down to `{}`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #50531.

This is a targeted fix for the exact issue in #50531. It doesn't address other known issues with the `in` operator.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.8

**Comment by fatcerberus** [comment]
What was the cause of #50531?  It’s weird that `unknown -> {}` got narrowed by `in` but a directly-typed `{}` didn’t.

**Comment by andrewbranch** [comment]
It’s that weird `declaredType !== type` condition—we discussed rewriting that whole set of conditions for 4.9 such that `in` only filters object types out of unions by property when there’s more than one object-like type in the declared type. There was also some discussion about whether to do anything if the property tested by `in` doesn’t exist in any of the object-like types in the union. (@ahejlsberg can probably better explain where we landed.)

**Pull request merged**
