### PR TITLE
Revert 'awaited' type

### LINKED ISSUE #37511: Introduction of the `awaited` operator makes a lot of breaks
@rbuckton @DanielRosenwasser 

Because of the `awaited` operator, today's build makes a lot of breaks in https://github.com/falsandtru/spica. I believe the other projects will also get many breaks. Can you really release this breaking change? I'm not sure whether I should fix the breaks.

### LINKED ISSUE #37512: awaited operator doesn't work with type guards
@rbuckton 

**TypeScript Version:**  master

**Search Terms:**

**Code**

```ts
declare function isAwaited(value: any): value is awaited unknown;
function f<a>(a: a): void {
  isAwaited(a) && a;
}
```

**Expected behavior:**
The narrowed type of a is awaited a.
**Actual behavior:**
The narrowed type of a is a.

**Playground Link:** 

**Related Issues:**

### LINKED ISSUE #37526: Can't infer T from awaited T
Looks like resolving this problem by type inference is difficult. We may need unawaited operator.

**TypeScript Version:**  3.9.0-dev.20200322

**Search Terms:**

**Expected behavior:**
pass
**Actual behavior:**
```
Argument of type 'T' is not assignable to parameter of type 'awaited T | PromiseLike<awaited T> | undefined'.
  Type 'T' is not assignable to type 'PromiseLike<awaited T>'.(2345)
```

**Related Issues:**

**Code**
```ts
function f<T>(a: T): Promise<awaited T> {
    return new Promise(r => r(a));
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function f(a) {
    return new Promise(r => r(a));
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/en/play?ts=3.9.0-dev.20200322&ssl=1&ssc=1&pln=3&pc=2#code/GYVwdgxgLglg9mABMAPAFQHwAoCGAuRNASgIAUAnOAWxgGcBTFHAdxxinoBNCNEBvAFCJhicvSghySMPWaIK1OvSzlEAXl7lcRIgG4BAXyA)

### LINKED ISSUE #37528: awaited operator is not introduced to async generators
@rbuckton Can you?

**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
```ts
interface AsyncGenerator<T = unknown, TReturn = any, TNext = unknown> extends AsyncIterator<T, TReturn, TNext> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): Promise<IteratorResult<awaited T, awaited TReturn>>;
    return(value: TReturn | PromiseLike<TReturn>): Promise<IteratorResult<awaited T, awaited TReturn>>;
    throw(e: any): Promise<IteratorResult<awaited T, awaited TReturn>>;
    [Symbol.asyncIterator](): AsyncGenerator<awaited T, awaited TReturn, TNext>;
}
interface AsyncIterator<T, TReturn = any, TNext = undefined> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): Promise<IteratorResult<awaited T, awaited TReturn>>;
    return?(value?: TReturn | PromiseLike<TReturn>): Promise<IteratorResult<awaited T, awaited TReturn>>;
    throw?(e?: any): Promise<IteratorResult<awaited T, awaited TReturn>>;
}
```
**Actual behavior:**
```ts
interface AsyncGenerator<T = unknown, TReturn = any, TNext = unknown> extends AsyncIterator<T, TReturn, TNext> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): Promise<IteratorResult<T, TReturn>>;
    return(value: TReturn | PromiseLike<TReturn>): Promise<IteratorResult<T, TReturn>>;
    throw(e: any): Promise<IteratorResult<T, TReturn>>;
    [Symbol.asyncIterator](): AsyncGenerator<T, TReturn, TNext>;
}
interface AsyncIterator<T, TReturn = any, TNext = undefined> {
    // NOTE: 'next' is defined using a tuple to ensure we report the correct assignability errors in all places.
    next(...args: [] | [TNext]): Promise<IteratorResult<T, TReturn>>;
    return?(value?: TReturn | PromiseLike<TReturn>): Promise<IteratorResult<T, TReturn>>;
    throw?(e?: any): Promise<IteratorResult<T, TReturn>>;
}
```
**Playground Link:** 

**Related Issues:**

### LINKED ISSUE #37534: Regression: Argument of type 'awaited T' is not assignable to parameter of type 'T'
**TypeScript Version:**  3.9.0-dev.20200322

**Search Terms:**
`awaited`

**Code**

```ts
async function runSequentially<T>(
  executors: Array<() => Promise<T>>,
): Promise<Array<T>> {
  const result: Array<T> = [];

  for (const executor of executors) {
    result.push(await executor());
  }

  return result;
}
```

**Expected behavior:**
The above code should compile. The types area reasonable and it did compile in previous versions without awaited.

**Actual behavior:**
Type error on `await executor()`:
```
Argument of type 'awaited T' is not assignable to parameter of type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.ts(2345)
```

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=Nightly)

**Related Issues:** #37526

### LINKED ISSUE #37551: False-positive void-return in dtslint after adding awaited
**TypeScript Version:**  from 3.9.0-dev.20200321 to 3.9.0-dev.20200324 

**Code**

```ts
declare namespace gapi.client {
    function load(name: "abusiveexperiencereport", version: "v1"): PromiseLike<void>;
    function load(name: "abusiveexperiencereport", version: "v1", callback: () => any): void;
}
```

**Expected behavior:**
[`dtslint`](https://github.com/microsoft/dtslint) uses rule [`void-return`](https://github.com/microsoft/dtslint/blob/master/docs/void-return.md) which didn't fail for the above code and shouldn't fail.

**Actual behavior:**
When `dtslint` is paired with `typescript` version since this commit: https://github.com/microsoft/TypeScript/commit/e3ec7b18b82d28f796ec635267907ff9014c4c5b which was merged in https://github.com/microsoft/TypeScript/pull/35998 - it fails:
```
ERROR: 17:80  void-return  Use the `void` type for return types only. Otherwise, use `undefined`. See: https://github.com/Microsoft/dtslint/blob/master/docs/void-return.md
ERROR: 18:89  void-return  Use the `void` type for return types only. Otherwise, use `undefined`. See: https://github.com/Microsoft/dtslint/blob/master/docs/void-return.md
```

----

Related to https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/101

### LINKED ISSUE #37556: VS Code codebase compile errors with 3.9.0-dev.20200324
**TypeScript Version:**  3.9.0-dev.20200324

**Repro**
1. Try using 3.9.0-dev.20200324 to build VS Code

**Problem**
I see ~30 errors (after fixing a few simple ones). Many of these are related to awaited. I'll start splitting out individual issues when I can create small repos

```
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/services/search/node/rawSearchService.ts(382,3): Type '(Anonymous class)' is not assignable to type 'CancelablePromise<C>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = C, TResult2 = never>(resolve?: ((value: C) => TResult1 | Promise<TResult1>) | null | undefined, reject?: ((reason: any) => TResult2 | Promise<TResult2>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = C, TResult2 = never>(onfulfilled?: ((value: awaited C) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>'.
      Types of parameters 'resolve' and 'onfulfilled' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'C' is not assignable to type 'awaited C'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/services/search/node/rawSearchService.ts(387,4): Property 'then' in type '(Anonymous class)' is not assignable to the same property in base type 'CancelablePromise<C>'.
  Type '<TResult1 = C, TResult2 = never>(resolve?: ((value: C) => TResult1 | Promise<TResult1>) | null | undefined, reject?: ((reason: any) => TResult2 | Promise<TResult2>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = C, TResult2 = never>(onfulfilled?: ((value: awaited C) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>'.
    Types of parameters 'resolve' and 'onfulfilled' are incompatible.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'C' is not assignable to type 'awaited C'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/services/search/node/rawSearchService.ts(388,25): Argument of type '((value: C) => TResult1 | Promise<TResult1>) | null | undefined' is not assignable to parameter of type '((value: awaited C) => TResult1 | awaited TResult1 | PromiseLike<TResult1 | awaited TResult1>) | null | undefined'.
  Type '(value: C) => TResult1 | Promise<TResult1>' is not assignable to type '(value: awaited C) => TResult1 | awaited TResult1 | PromiseLike<TResult1 | awaited TResult1>'.
    Types of parameters 'value' and 'value' are incompatible.
      Type 'awaited C' is not assignable to type 'C'.
        'C' could be instantiated with an arbitrary type which could be unrelated to 'awaited C'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/services/history/browser/history.ts(342,49): Argument of type '() => boolean' is not assignable to parameter of type '() => void | PromiseLike<void>'.
  Type 'boolean' is not assignable to type 'void | PromiseLike<void>'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/contrib/search/common/searchModel.ts(609,21): Type 'FileMatch | FileMatch[]' must have a '[Symbol.iterator]()' method that returns an iterator.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/base/browser/ui/list/listPaging.ts(58,53): Argument of type 'awaited TElement' is not assignable to parameter of type 'TElement'.
  'TElement' could be instantiated with an arbitrary type which could be unrelated to 'awaited TElement'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/platform/extensionManagement/node/extensionManagementService.ts(89,42): Type '{ [x: string]: any; }' must have a '[Symbol.iterator]()' method that returns an iterator.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTreeViews.ts(336,43): Argument of type 'awaited T' is not assignable to parameter of type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTreeViews.ts(337,43): Argument of type 'awaited T' is not assignable to parameter of type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostCommands.ts(230,67): Argument of type '<R>(...args: any[]) => Promise<R>' is not assignable to parameter of type '<T>(...args: any[]) => T | Thenable<T>'.
  Type 'Promise<T>' is not assignable to type 'T | Thenable<T>'.
    Type 'Promise<T>' is not assignable to type 'Thenable<T>'.
      Types of property 'then' are incompatible.
        Type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: awaited T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>' is not assignable to type '{ <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thenable<...>; <T...'.
          Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
            Type '((value: T) => any) | undefined' is not assignable to type '((value: awaited T) => any) | null | undefined'.
              Type '(value: T) => any' is not assignable to type '(value: awaited T) => any'.
                Types of parameters 'value' and 'value' are incompatible.
                  Type 'awaited T' is not assignable to type 'T'.
                    'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHost.api.impl.ts(246,5): Type 'Promise<T>' is not assignable to type 'Thenable<T>'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHost.api.impl.ts(1076,3): Type 'Promise<awaited T>' is not assignable to type 'Thenable<T>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = awaited T, TResult2 = never>(onfulfilled?: ((value: awaited T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>' is not assignable to type '{ <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thenable<...>; <T...'.
      Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
        Type '((value: T) => any) | undefined' is not assignable to type '((value: awaited T) => any) | null | undefined'.
          Type '(value: T) => any' is not assignable to type '(value: awaited T) => any'.
            Types of parameters 'value' and 'value' are incompatible.
              Type 'awaited T' is not assignable to type 'T'.
                'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/editor/contrib/hover/hoverOperation.ts(104,39): Argument of type '(asyncResult: Result) => void' is not assignable to parameter of type '(value: awaited Result) => void | PromiseLike<void>'.
  Types of parameters 'asyncResult' and 'value' are incompatible.
    Type 'awaited Result' is not assignable to type 'Result'.
      'Result' could be instantiated with an arbitrary type which could be unrelated to 'awaited Result'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/base/common/async.ts(37,9): Conversion of type '(Anonymous class)' to type 'CancelablePromise<T>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property '[Symbol.toStringTag]' is missing in type '(Anonymous class)' but required in type 'CancelablePromise<T>'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/base/common/async.ts(42,24): Argument of type '((value: T) => TResult1 | Promise<TResult1>) | null | undefined' is not assignable to parameter of type '((value: awaited T) => TResult1 | awaited TResult1 | PromiseLike<TResult1 | awaited TResult1>) | null | undefined'.
  Type '(value: T) => TResult1 | Promise<TResult1>' is not assignable to type '(value: awaited T) => TResult1 | awaited TResult1 | PromiseLike<TResult1 | awaited TResult1>'.
    Types of parameters 'value' and 'value' are incompatible.
      Type 'awaited T' is not assignable to type 'T'.
        'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/base/common/async.ts(79,12): Argument of type 'T | Thenable<T>' is not assignable to parameter of type 'T | awaited T | PromiseLike<T> | undefined'.
  Type 'Thenable<T>' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
    Type 'Thenable<T>' is not assignable to type 'PromiseLike<T>'.
      Types of property 'then' are incompatible.
        Type '{ <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thenable<...>; <T...' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: awaited T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
          Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
            Type '((value: awaited T) => any) | null | undefined' is not assignable to type '((value: T) => any) | undefined'.
              Type 'null' is not assignable to type '((value: T) => any) | undefined'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/base/common/async.ts(403,19): Argument of type 'awaited T' is not assignable to parameter of type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/base/common/async.ts(463,17): Argument of type '(value?: T | Promise<T> | undefined) => void' is not assignable to parameter of type '(value: awaited T) => void | PromiseLike<void>'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'awaited T' is not assignable to type 'T | Promise<T> | undefined'.
      Type 'awaited T' is not assignable to type 'Promise<T>'.
[14:16:40] Error: /Users/matb/projects/vscode/src/vs/workbench/workbench.web.api.ts(249,25): Type 'readonly ICommand[] | undefined' must have a '[Symbol.iterator]()' method that returns an iterator.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/merge-conflict/src/delayer.ts(34,5): Type '(value?: T | awaited T | PromiseLike<T> | undefined) => void' is not assignable to type '(value?: T | Thenable<T> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'T | Thenable<T> | undefined' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
      Type 'Thenable<T>' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
        Type 'Thenable<T>' is not assignable to type 'PromiseLike<T>'.
          Types of property 'then' are incompatible.
            Type '{ <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thenable<...>; }' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: awaited T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
              Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                Type '((value: awaited T) => any) | null | undefined' is not assignable to type '((value: T) => any) | undefined'.
                  Type 'null' is not assignable to type '((value: T) => any) | undefined'.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/github-authentication/src/common/utils.ts(64,3): Argument of type '(result: U) => U' is not assignable to parameter of type '(value: awaited U) => U | PromiseLike<U>'.
  Types of parameters 'result' and 'value' are incompatible.
    Type 'awaited U' is not assignable to type 'U'.
      'U' could be instantiated with an arbitrary type which could be unrelated to 'awaited U'.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/git/src/util.ts(390,17): Argument of type '(value?: T | Promise<T> | undefined) => void' is not assignable to parameter of type '(value: awaited T) => void | PromiseLike<void>'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'awaited T' is not assignable to type 'T | Promise<T> | undefined'.
      Type 'awaited T' is not assignable to type 'Promise<T>'.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/git/src/commands.ts(2567,3): Type '(awaited T)[]' is not assignable to type 'T[]'.
  Type 'awaited T' is not assignable to type 'T'.
    'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/typescript-language-features/src/utils/async.ts(34,5): Type '(value?: T | awaited T | PromiseLike<T> | undefined) => void' is not assignable to type '(value?: T | Thenable<T> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'T | Thenable<T> | undefined' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
      Type 'Thenable<T>' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
        Type 'Thenable<T>' is not assignable to type 'PromiseLike<T>'.
          Types of property 'then' are incompatible.
            Type '{ <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thenable<...>; }' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: awaited T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
              Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                Type '((value: awaited T) => any) | null | undefined' is not assignable to type '((value: T) => any) | undefined'.
                  Type 'null' is not assignable to type '((value: T) => any) | undefined'.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/php-language-features/src/features/utils/async.ts(69,29): Argument of type '(result: T) => void' is not assignable to parameter of type '(value: awaited T) => void | PromiseLike<void>'.
  Types of parameters 'result' and 'value' are incompatible.
    Type 'awaited T' is not assignable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.
[14:16:40] Error: /Users/matb/projects/vscode/extensions/php-language-features/src/features/utils/async.ts(125,5): Type '(value?: T | awaited T | PromiseLike<T> | undefined) => void' is not assignable to type '(value: T | Thenable<T> | undefined) => void'.
  Types of parameters 'value' and 'value' are incompatible.
    Type 'T | Thenable<T> | undefined' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
      Type 'Thenable<T>' is not assignable to type 'T | awaited T | PromiseLike<T> | undefined'.
        Type 'Thenable<T>' is not assignable to type 'PromiseLike<T>'.
          Types of property 'then' are incompatible.
            Type '{ <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<TResult>) | undefined, onrejected?: ((reason: any) => TResult | Thenable<TResult>) | undefined): Thenable<...>; <TResult>(onfulfilled?: ((value: T) => TResult | Thenable<...>) | undefined, onrejected?: ((reason: any) => void) | undefined): Thenable<...>; }' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: awaited T) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => PromiseLike<...>'.
              Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
                Type '((value: awaited T) => any) | null | undefined' is not assignable to type '((value: T) => any) | undefined'.
                  Type 'null' is not assignable to type '((value: T) => any) | undefined'.
```

### LINKED ISSUE #37564: New error: Type 'awaited T' is not assignable to type 'T'.
https://github.com/conventional-changelog/commitlint/blob/0f0f95affc1c350fdb3e3c58eda48f9a845dfb27/@commitlint/execute-rule/src/index.ts#L20

```
@commitlint/execute-rule/src/index.ts:20:16 - error TS2322: Type 'awaited T' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.

20  return [name, await fn()];
                  ~~~~~~~~~~
```

To repro:
1) `yarn`
2) `yarn run build`
3) `tsc -b -f`

### LINKED ISSUE #37566: New error: Argument of type '(result: Result) => void' is not assignable to parameter of type '(value: awaited Result) => void | PromiseLike<void>'
https://github.com/linkedin/css-blocks/blob/6023475e9ab9a01cda6daa71986a9b4932c16ecd/packages/@css-blocks/core/src/util/PromiseQueue.ts#L35

```
packages/@css-blocks/core/src/util/PromiseQueue.ts:35:7 - error TS2345: Argument of type '(result: Result) => void' is not assignable to parameter of type '(value: awaited Result) => void | PromiseLike<void>'.
  Types of parameters 'result' and 'value' are incompatible.
    Type 'awaited Result' is not assignable to type 'Result'.
      'Result' could be instantiated with an arbitrary type which could be unrelated to 'awaited Result'.

35       (result: Result) => {
         ~~~~~~~~~~~~~~~~~~~~~
```

To repro:
1) `yarn`
2) `tsc -b -f packages`

### LINKED ISSUE #37567: New error: Argument of type 'awaited T' is not assignable to parameter of type 'T'.
https://github.com/linkedin/css-blocks/blob/6023475e9ab9a01cda6daa71986a9b4932c16ecd/packages/@css-blocks/core/src/util/allDone.ts#L17

```
packages/@css-blocks/core/src/util/allDone.ts:17:20 - error TS2345: Argument of type 'awaited T' is not assignable to parameter of type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'awaited T'.

17       results.push(await p);
                      ~~~~~~~
```

To repro:
1) `yarn`
2) `tsc -b -f packages`

### LINKED ISSUE #37572: New error: type not assignable
https://github.com/jupyter-widgets/ipywidgets/blob/b91a6d9844d1e4e2571f1e7d2fa5416abf468106/packages/base/src/utils.ts#L70

```
src/utils.ts:70:7 - error TS2322: Type 'awaited V' is not assignable to type 'V'.
  'V' could be instantiated with an arbitrary type which could be unrelated to 'awaited V'.

70       d[keys[i]] = v[i];
         ~~~~~~~~~~
```

https://github.com/jupyter-widgets/ipywidgets/blob/b91a6d9844d1e4e2571f1e7d2fa5416abf468106/packages/base/src/viewlist.ts#L83

```
src/viewlist.ts:83:5 - error TS2322: Type 'Promise<(awaited T)[]>' is not assignable to type 'Promise<T[]>'.
  Types of property 'then' are incompatible.
    Type '<TResult1 = (awaited T)[], TResult2 = never>(onfulfilled?: ((value: (awaited T)[]) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<...>) | null | undefined) => Promise<...>' is not assignable to type '<TResult1 = T[], TResult2 = never>(onfulfilled?: ((value: T[]) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => Promise<...>'.
      Types of parameters 'onfulfilled' and 'onfulfilled' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '(awaited T)[]' is not assignable to type 'T[]'.

83     return Promise.all(this.views);
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

To repro:
1) `yarn`
2) `tsc -b -f packages/base`

### LINKED ISSUE #37592: awaited operator is not added to the return types of async functions
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
async function f<T>(a: T): Promise<T> {
    return a;
}
async function g<T>(a: T) {
    return a;
}
g(Promise.resolve(0));
```

**Expected behavior:**
Return type of f is invalid because the correct type is `Promise<awaited T>`.
Return types of g are `Promise<awaited T>` and `Promise<number>`.
**Actual behavior:**
Return type of f is valid although the correct type is `Promise<awaited T>`.
Return types of g are `Promise<T>` and `Promise<Promise<number>>`.

**Playground Link:** https://www.typescriptlang.org/play/index.html?ts=3.9.0-dev.20200324&ssl=1&ssc=1&pln=7&pc=23#code/IYZwngdgxgBAZgV2gFwJYHsLwDwBUB8AFMAFwy4CUZACgE7oC2qIApnvjAN4BQMfMtFsgS0swANzcAvt1CRYiFBiwBzdsTKUuvfoOGiYE6dxWE6jZiwB0gkOgA2ANxaEADBQrigA

**Related Issues:**

### LINKED ISSUE #37602: Async generators don't accept unawaited return types
**TypeScript Version:**  3.7.x-dev.20200324

**Search Terms:**

**Code**

```ts
function g<a>(a: a) {
  return async function* (): AsyncGenerator<awaited a, awaited a> {
    yield a;
    return a;
  };
}
```

**Expected behavior:**
pass
**Actual behavior:**
Type 'a' is not assignable to type 'awaited a'.ts(2322)
**Playground Link:** 

**Related Issues:**

### LINKED ISSUE #37603: Type 'AsyncGenerator<awaited a, awaited a, unknown>' is not assignable to type 'AsyncGenerator<a, a, unknown>'.
**TypeScript Version:**  3.7.x-dev.20200324

**Search Terms:**

**Code**

```ts
function g<a>(a: a): AsyncGenerator<a, a> {
  return async function* (): AsyncGenerator<awaited a, awaited a> {
    yield a;
    return a;
  }();
}
```

**Expected behavior:**
pass
**Actual behavior:**
Type 'AsyncGenerator<awaited a, awaited a, unknown>' is not assignable to type 'AsyncGenerator<a, a, unknown>'.
**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
The new `awaited` type is currently causing too many breaks to be considered stable for TS 3.9. This PR reverts the `awaited` type for this release while we continue to investigate the impact of the change.

Closes #37511
Closes #37512
Closes #37526
Closes #37528
Closes #37534
Closes #37551
Closes #37556
Closes #37564
Closes #37566
Closes #37567
Closes #37572
Closes #37592
Closes #37602
Closes #37603

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
I found a few more stragglers, will update shortly.

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
- RWC changes look good
- user/docker changes look good except for some errors in vscode that look to be due to https://github.com/microsoft/TypeScript/pull/36539, not this PR.
- DT changes look good

**Comment by rbuckton** [comment]
@typescript-bot cherry-pick this to release-3.9

**Comment by Luxcium** [comment]
oops... I was relying on this solution because I have a `Promise<MaybeList<Promise<ISymbolSearchResult[]>>>`
where `MaybeList` is an array abstraction so I am using promise.all to remove the inner `Promise` I don't know what to do now to avoid using `as unknown as MaybeList<ISymbolSearchResult[]>` inside of my `async` function (which should be returning the `Promise<MaybeList<ISymbolSearchResult[]>>` instead of the `Promise<MaybeList<Promise<ISymbolSearchResult[]>>>`)

**Pull request merged**
