### PR TITLE
Added follow on Twitter button in the README file.

### PR DESCRIPTION
**Pull request by Prashoon123**
Fixes #
Added follow on Twitter button in the README file.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This is already linked from the "Community" section that lands at https://www.typescriptlang.org/community

**Comment by Prashoon123** [comment]
@RyanCavanaugh but I also added it in the README.md file!! In my opinion, this will increase the traffic to the TypeScript Twitter handle! Thank you!!

**Comment by Prashoon123** [comment]
@RyanCavanaugh are you planning to merge this PR?

**Comment by sandersn** [comment]
I think the link on the community page is enough -- especially since there's a link to the community page in the README already.

**Comment by Prashoon123** [comment]
OK

**Pull request closed without merging**
