### PR TITLE
Improve 'Cannot compile modules unless the '--module' flag is provided.' message

### LINKED ISSUE #4448: Improve 'Cannot compile modules unless the '--module' flag is provided.' message
I'm fairly new to TypeScript, having been working with it a few days to create d.ts files, in VSCode, for some Node components.
I'd been persistently seeing this message in VSCode for my d.ts files:
  `Cannot compile modules unless the '--module' flag is provided.`
That threw me, at least as a noob, as I wasn't using tsc at all--I was just using IntelliSense.   How was I supposed to provide a --module flag?  Is IntelliSense just buggy?
Later after googling for the error I first learned about the tsconfig.json file--something I didn't learn about previously reading the TypeScript docs.
Anyway, my recommendation would be to update to the message to say something like:
`Cannot compile modules unless the '--module' flag is provided.  Do you need to provide a tsconfig.json file?`
That would have been a big help for noobs like myself, cluing us into the existence of tsconfig.json and it being the way to fix this up.  Thanks.

### PR DESCRIPTION
**Pull request by plantain-00**
to fix #4448.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
I would somewhat prefer if this was done with a diagnostic elaboration (i.e. use a diagnostic message chain and then flatten that).

What do you think @mhegazy?

**Comment by mhegazy** [comment]
We have used the "consider" pattern in some other cases as well:

```ts
   "Import assignment cannot be used when targeting ECMAScript 6 modules. Consider using 'import * as ns from \"mod\"', 'import {a} from \"mod\"', 'import d from \"mod\"', or another module format instead."
  
```

so i would say it is fine.

**Comment by sparecycles** [comment]
Why are we putting Visual Studio Code help text inside the TypeScript language?

**Comment by mhegazy** [comment]
@sparecycles it is not just VSCode, it is all IDEs, we got reports for this in VS, and in Sublime text.

**Comment by mhegazy** [comment]
@plantain-00 do you mind updating this PR?

**Comment by plantain-00** [comment]
@mhegazy It is in #5981 now. This pull request can be closed.

**Comment by sparecycles** [comment]
@mhegazy And now I understand now why putting ```tsconfig.json``` inside ```.vscode/``` wasn't working!

**Pull request closed without merging**
