### PR TITLE
Cherry-picked fixes for processDiagnosticMessages

### LINKED ISSUE #3587: processDiagnosticMessages.ts collision handling doesn't actually work
Background:

The build does a preprocessing step to build the `Diagnostics` map, which contains items naming tsc error codes and their corresponding human-readable messages.  The generate-diagnostics target runs before the actual compilation step for tsc.  It takes the diagnostic message from a JSON source and mangles it to create a suitable property name for the `Diagnostics` object.

For example, given the 1100 diagnostic ("Invalid use of '{0}' in strict mode."), we create `Diagnostic.Invalid_use_of_0_in_strict_mode`.

Because we're mangling these, processDiagnosticMessages.ts tries to go through some effort to avoid collisions in the generated property names.  See `ts.buildUniqueNameMap`, `ts.NameGenerator.handleCollisions`, and others.

For example, when dealing with two hypothetical diagnostic messages "Found '{0}'" and "Found 0", we wouldn't want the name-mangling to produce colliding `Found_0` keys for both messages.

Problem:

processDiagnosticMessages.ts does not succeed in its goal to properly deal with collisions.

Analysis and Cause:

During a visual audit of the code, before actually performing any tests against different inputs, I originally fingered the following line as problematic while eyeballing processDiagnosticMessages.ts:

```
    nameMap[names[i]] = uniqueNames[i];
```

This is in the context of having just produced the `uniqueNames` from the orginal elements of `names` (where `names` actually contains elements whose values are the diagnostic messages).  The use of the two arrays are inverted.

```
    nameMap[uniqueNames[i]] = names[i];
```

(Again, `names[i]` is a bit of a misnomer.  It actually contains the human-readable text of the diagnostic.)

However, this does not resolve the problem.  We can process Example Input 1 (adapted from the example above) and it will produce identical `Found_0` keys both before and after making the change above.  There are actually several other problems in processDiagnosticMessages.ts wrt collision handling.

The use of `buildUniqueNameMap` actually happens before the name-mangling (`convertPropertyName`) occurs, so the only time we would ever encounter a collision is if the _diagnostic messages_ are exactly the same (rather than their _would-be mangled names_ being the same as in Example Input).  But in fact, it's not even possible for the messages to be the same, because they come from a JSON source keyed off that message, so they're already guaranteed to be unique.  (Side note: add build preconditions to make sure there are no duplicate messages in the source JSON?)

There's also a problem with the `isFixed` parameter in `handleCollisions`, but I will file a separate issue about that, for various reasons.

Example Input:

```
{
    "Found '{0}'.": {
        "category": "Error",
        "code": 9999
    },
    "Found 0.": {
        "category": "Error",
        "code": 9998
    }
}
```

### PR DESCRIPTION
**Pull request by Eyas**
Fixes #3587, #3588, #3589.

I'm not sure how fine this is-- I'm submitting a PR for changes that I have cherry-picked from @colbyrussell. See the above issues for more context-- the summary is that the original author wouldn't mind others picking these up, and is uninterested in directly submitting a PR over grips with GitHub workflow issues.

I'm submitting the PR for all three commits at once as it seems like too much overhead otherwise. Let me know if you disagree.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Did @colbyrussell sign a CLA?

**Comment by colbyrussell** [comment]
> Did @colbyrussell sign a CLA

No, but I can.

I want to point out, though, that since my changes are already available under Apache 2.0, your CLA doesn't require @Eyas to get my signature, although he should write in a comment here "Submission containing materials of a third party:", followed by my name and something like "Code is already available under an appropriate license (Apache License, version 2.0)".

> is he okay with this PR?

Yes.

**Comment by Eyas** [comment]
It should be noted that I'm preserving commit history, so unless I am to squash these later, @colbyrussell is still listed as a contributor. I was planning to only include PR feedback as my own commits.

**Comment by mhegazy** [comment]
@colbyrussell, we would appreciate it if you can sign the CLA (you can sign it digitally through: https://cla.microsoft.com).

**Comment by colbyrussell** [comment]
> @colbyrussell, we would appreciate it if you can sign the CLA

As I mentioned before, I can sign it.

However, I want to point out again that Eyas is submitting code from my fork, and so whether you have my CLA on file means nothing.  It doesn't matter that I authored the code; the CLA grants Microsoft no additional rights since I'm not submitting anything.  The CLA is totally benign here.  It has no side effects.  That is, even if I sign and you integrate the changes, it will be exactly the same as if I hadn't signed at all.

**Comment by mhegazy** [comment]
thanks @colbyrussell, but we would appreciate it if you can sign the CLA in addition to the notice above.

**Comment by mhegazy** [comment]
For legal purposes i do not think we can accept this. sorry for the delay.

**Pull request closed without merging**
