### PR TITLE
Allow `|`, `&`, and `^` operators to have null/undefined inputs

### LINKED ISSUE #22230: Allow bitwise test on `undefined`
**TypeScript Version:**  2.8.0-dev.20180228

**Search Terms:** undefined strictNullChecks bitwise and or

(ref: https://github.com/Microsoft/TypeScript/pull/22088#issuecomment-367531430)

**Code**

```ts
const enum Flags { A = 2 ** 1, B = 2 ** 2 }
function f(flags?: Flags) {
    if (flags & Flags.B) {
    }
}
```

**Expected behavior:**

No error. `&` and `|` work well on undefined values: `undefined | 2` is `2`, `undefined & 2` is `0`. Contrast with `undefined + 2` which is `NaN`.

**Actual behavior:**

```ts
src/a.ts(3,9): error TS2532: Object is possibly 'undefined'.
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #22230 
Would make #22088 simpler

### CODE REVIEW

**Comment by weswigham** [comment]
I like this change, ofc. @rbuckton you're a real fan of the undefined-is-implicitly-bitwise-zero pattern; you agree with this?

**Comment by RyanCavanaugh** [comment]
TIL

I'm hesitant on this because (a) you could just use `!` and (b) this reasoning applies equally to e.g. `"foo" | 0` (which is `0`). If the logic is "It doesn't return `NaN`" then `[3] | { }` should be legal too, because the binary bitwise operators *always* return an int. I'm strawmanning of course, but what about e.g. `string | number` as an operand? Probably most codebases with a flag value would treat `null`/`undefined` as `0` but I'm not convinced that it's all of them.

**Comment by weswigham** [comment]
Ofc, the reason _we_ want it is because we use the fact that null/undefined are effectively zero in bitwise ops extensively inside our codebase. Tbqh, I think the question to ask, is how often does forcing you to handle null/undefined explicitly here find an error, versus just forcing you to write (and slowly become blind to) nonnull assertions.

**Comment by andy-ms** [comment]
Note: `"1" | 2` is 3, as is `({ toString() { return "1" } }) | 2`, so not a good idea to rely on anything else being treated as `0`.

**Pull request closed without merging**
