### PR TITLE
Reinterpret a type parameter constrained to any as an upper bound constraint

### LINKED ISSUE #29509: Missing error after spreading generic props into JSX
**TypeScript Version:**  3.2.2

**Search Terms:**

**Code**

```ts
type Component<P> = (props: P) => any;

const myHof = <ComposedComponentProps extends any>(
    ComposedComponent: Component<ComposedComponentProps>,
) => {
    type WrapperComponentProps = ComposedComponentProps & { myProp: string };
    declare const WrapperComponent: Component<WrapperComponentProps>;

    declare const props: ComposedComponentProps;

    // Expected no error, got none - good
    WrapperComponent({ ...props, myProp: '1000000' });
    // Expected error, got one - good
    WrapperComponent({ ...props, myProp: 1000000 });
}
```

However, when I try to do the same with React (`.tsx`):

``` tsx
import React from 'react';

const myHoc = <ComposedComponentProps extends any>(
    ComposedComponent: React.ComponentClass<ComposedComponentProps>,
) => {
    type WrapperComponentProps = ComposedComponentProps & { myProp: string };
    declare const WrapperComponent: React.ComponentClass<WrapperComponentProps>;

    declare const props: ComposedComponentProps;

    // Expected no error, got none - good
    <WrapperComponent {...props} myProp={'1000000'} />;
    // Expected error, but got none - bad!
    <WrapperComponent {...props} myProp={1000000} />;
};
```

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #29509

Note, that we have a test that asserts that a type parameter explicitly extending `any` behaves like `any` when accessing its members (which IMO is strange). This would be a break to that behavior.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
Also run on DT

**Comment by weswigham** [comment]
@typescript-bot run dt

**Comment by weswigham** [comment]
Updated the test that needed changing to a constraint that actually typechecks, and looked at DT - failures are in `ramda` (and are also failing in `master` due to the recent function generic inference changes) and in a package callec `victory` - the diff in `victory` appears unrelated and already fixed, given that a local `dtslint` on it run doesn't show any errors.

So this seems pretty good - if anything, like the tests I just changed, it's going to identify places we were silently allowing unsafe operations.

**Comment by RyanCavanaugh** [comment]
@weswigham let's merge for 3.5

**Comment by sandersn** [comment]
@weswigham this sounds like it's ready to go, right?

**Comment by weswigham** [comment]
Probably. The change itself is small, so barring merge conflicts, should still be OK.

**Comment by sandersn** [comment]
After a merge from master: toString is now available on type parameters that extend any. That's the only difference I can see.

**Comment by sandersn** [comment]
Let's wait until @RyanCavanaugh is back to merge this.

**Comment by sandersn** [comment]
I talked to @RyanCavanaugh about this just now, so I'm going to merge it.

**Comment by sandersn** [comment]
@weswigham this causes a failure in DT on wordpress__block-editor-tests.tsx. Can you try to fix it? It looks like the offending signature is this:

```ts
declare function withColorContext<
    ProvidedProps extends Partial<withColorContext.Props>,
    OwnProps extends any,
    T extends ComponentType<ProvidedProps & OwnProps>
>(component: T):
    T extends ComponentType<infer U> ? ComponentType<
        Omit<U, 'colors' | 'disableCustomColors' | 'hasColorsToChoose'> &
        Omit<ProvidedProps, 'hasColorsToChoose'>> :
    never;
```

Previously the second type argument was inferred `OwnProps=any`; now it's `OwnProps=unknown` (as expected).

If there's a mechanical fix to update existing code, it'd worthwhile to have that in the release notes for 3.9.

**Comment by weswigham** [comment]
> If there's a mechanical fix to update existing code, it'd worthwhile to have that in the release notes for 3.9.

Write an `Extract` everywhere we now (correctly) flag as a type error, `(or, better yet, write types that actually check out without contortions). It's the typesystem equivalent of a typecast, but it's much more explicit.

eg,
```ts
type GetClass<T extends any> = T["class"];

// could be
type GetClass<T> = Extract<T, {class: any}>["class"];
```
obviously, you can replace `Extract` with a helper that provides a more reasonable default on failure than `never` for your given situation, too. 

> this causes a failure in DT on wordpress__block-editor-tests.tsx. Can you try to fix it? It looks like the offending signature is this:

What's broken about it? the signature itself has nothing wrong as far as I can tell, so you're talking about a specific usage, right?

**Comment by weswigham** [comment]
> What's broken about it?

 If the answer is "we now infer `unknown` instead of `any` because we never make inferences", adding `= any` will silence the error and change the default only back to `any`. But I'd still consider an `any`-defaulting inference questionable, myself. You _probably_ shouldn't have type parameters you can never infer...

**Comment by sandersn** [comment]
Yes, line 142 of the tests. Probably `= any` to silence the error is good enough really.

**Pull request merged**
