### PR TITLE
Better typings for promise.race based on conditional types

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Following the feature - Mapped tuple types #25947 - it is now possible to have better typings for Promise.race

From @dubzzz before I messed up his fork

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
This is thanks to conditional types, not mapped types.

It'd be nice to have a test of some sort (I'm sure we don't). Something simple like

```ts
let a = Promise.race([
    Promise.resolve(10),
    Promise.resolve("hello")
]);
```

**Comment by dubzzz** [comment]
@DanielRosenwasser You're right. I think my first commit was really using mapped types but I changed it following reviews 🤔

**Comment by RyanCavanaugh** [comment]
@typescript-bot test thsi

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by buu700** [comment]
@RyanCavanaugh, I'm seeing some odd behavior from this new signature:

```
// This example also behaves the same way if `maybePromise` is changed to just `T`
function balls<T> (maybePromise: T|Promise<T>) {
    const t = await Promise.race([
        maybePromise
    ]);

    // Argument of type 'T extends PromiseLike<infer U> ? U : T' is not assignable to parameter of type 'T'.
    //   Type 'unknown' is not assignable to type 'T'.
    doSomethingWithAT(n);
}

function doSomethingWithAT (t: T) { . . . }
```

I can work around it by passing in `Promise.resolve(maybePromise)`, but this issue aside is there a reason to prefer that style?

**Pull request merged**
