### PR TITLE
Always build project irrespective of errors in dependency with tsc -b

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot test it

**Comment by jakebailey** [comment]
This is going to be awesome for benchmarking and extended testing, since we'll actually be able to build build-mode projects without them short circuiting, right?

**Comment by sheetalkamat** [comment]
> This is going to be awesome for benchmarking and extended testing, since we'll actually be able to build build-mode projects without them short circuiting, right?

Yes. While debugging you could just build without having to block on errors

**Comment by sheetalkamat** [comment]
https://github.com/microsoft/TypeScript/pull/58854#issuecomment-2166816302  shows how more packages are being built and errors are reported

**Review by weswigham — APPROVED** [review]
Since we don't do project concatenation anymore, there's not even a reason to block when `noEmitOnError` is set, neat.

**Review by jakebailey — APPROVED** [review]
So excited for this one.

Are there any issues that this closes? I assume that docs will have to be updated too (surely we document the short circuiting somewhere...).

I also assume that nobody's hard depending on this behavior and we don't need some sort of flag to ask build mode to bail early on failures?

**Comment by sheetalkamat** [comment]
I am hoping we dont need a flag. If the need arises we should evaluate adding the flag at that point.

**Comment by DanielRosenwasser** [comment]
Could that flag be `--noEmitOnError`?

**Comment by sheetalkamat** [comment]
@DanielRosenwasser when i was working on this, i tried that option already and it has no effect, because "d.ts" files from referenced projects will not have errors and blocking project build just because its dependency had error means nothing really. its really whether d.ts file from referenced project has changed or not.

**Comment by stavalfi** [comment]
@sheetalkamat Does this PR means that if project1 depends on project2, if project 2 has an error, I would eventually see compilation errors in both projects?
if yes, this is such an awasome PR!!!!!

**Comment by sheetalkamat** [comment]
> @sheetalkamat Does this PR means that if project1 depends on project2, if project 2 has an error, I would eventually see compilation errors in both projects? if yes, this is such an awasome PR!!!!!

Yes

**Pull request merged**
