### PR TITLE
Improve parsing in await and yield context

### LINKED ISSUE #44415: TS Server fatal error:  Cannot read property 'length' of undefined
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.4.0-dev.20210528

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `syntax`
```
TypeError: Cannot read property 'length' of undefined
    at Object.escapeLeadingUnderscores (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:12126:28)
    at createBaseIdentifier (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:21640:35)
    at Object.createIdentifier (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:21652:24)
    at createIdentifier (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30526:43)
    at createIdentifier (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30530:24)
    at parseIdentifier (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30550:20)
    at parsePrimaryExpression (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:33790:20)
    at parseMemberExpressionOrHigher (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:33259:30)
    at parseLeftHandSideExpressionOrHigher (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:33203:92)
    at parseUpdateExpression (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:33138:30)
    at parseUnaryExpressionOrHigher (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:33013:40)
    at parseBinaryExpressionOrHigher (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:32890:31)
    at parseAssignmentExpressionOrHigher (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:32523:24)
    at parseExpression (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:32470:24)
    at doOutsideOfContext (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30180:20)
    at allowInAnd (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30202:20)
    at parseExpressionOrLabeledStatement (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:34210:30)
    at parseStatement (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:34451:20)
    at parseListElement (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30906:20)
    at parseList (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:30891:31)
    at parseSourceFileWorker (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:29983:30)
    at Object.parseSourceFile (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:29817:26)
    at Object.createSourceFile (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:29615:29)
    at Object.createLanguageServiceSourceFile (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:153373:29)
    at acquireOrUpdateDocument (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:126657:37)
    at Object.acquireDocumentWithKey (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:126623:20)
    at getOrCreateSourceFileByPath (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:153776:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:153723:24)
    at findSourceFileWorker (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:111263:29)
    at findSourceFile (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:111173:26)
    at /Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:111125:85
    at getSourceFileFromReferenceWorker (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:111092:34)
    at processSourceFile (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:111125:13)
    at processRootFile (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:110935:13)
    at /Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:109803:67
    at Object.forEach (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:190:30)
    at Object.createProgram (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:109803:16)
    at synchronizeHostData (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:153653:26)
    at Proxy.getProgram (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:153785:13)
    at InferredProject.Project.updateGraphWorker (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:158733:53)
    at InferredProject.Project.updateGraph (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:158661:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:160806:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:162450:26)
    at /Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:162724:97
    at Object.flatMap (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:515:25)
    at ProjectService.applyChangesInOpenFiles (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:162724:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:163779:46)
    at /Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:165696:88
    at IOSession.Session.executeWithRequestId (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:165687:28)
    at IOSession.Session.executeCommand (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:165696:33)
    at IOSession.Session.onMessage (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:165722:35)
    at Interface.<anonymous> (/Users/ronney/.vscode/extensions/ms-vscode.vscode-typescript-next-4.4.20210528/node_modules/typescript/lib/tsserver.js:168324:31)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
    at Interface._normalWrite (readline.js:482:12)
    at Socket.ondata (readline.js:194:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:06:21.189Z)
OS version: Darwin x64 17.7.0

### LINKED ISSUE #44459: Binding identifier should care about await/yield context
# Bug Report

### 🔎 Search Terms
parsing, await, yield

### 🕗 Version & Regression Information

- This changed between versions 3.9.7 and now

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?ts=4.0.5#code/IYZwngdgxgBAZgV2gFwJYHsL3emAKAShgG8AoGGAN2ACcZgB3YVZGAXhgEYBucmKTCHQAbAKYA6YegDmeRs2QFeAX1KlEKDFgBU2dJ0Ik+1OmFSjhAE3ZdeFARCFjJMvGYuWCpVaVCRYGlBomDAARrT4RGQUYqzyLDYATHb8giISUrLxiipqgcE6YbQGUXyxMO5WSSkOThmulZ5qykA)

### 💻 Code

```ts
async function foo () {
  var await = 1; // should be an error, but not
}

async function bar () {
  let await = 2; // error
}

function * foo1() {
  var yield = 1; // should be an error, but not
}

function * bar1() {
  let yield = 2; // error
}
```

### 🙁 Actual behavior

BindingIdentifier in await/yield with `var` keyword does not throw errors.

### 🙂 Expected behavior
It should.

Related: 
- https://github.com/microsoft/TypeScript/pull/43370#issuecomment-855389589
- https://github.com/microsoft/TypeScript/pull/39216 (/cc: @rbuckton )

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #44459

It works. But I don't know why 🤷‍♂️.

### CODE REVIEW

**Comment by sandersn** [comment]
I need to run through it in the debugger to understand it myself, but my *guess* is that isBindingIdentifier accepts `await` and `yield` as keywords where isIdentifier doesn't (when not in an await/yeild context). Then something in parseVarExpression explicitly rejects await/yield. Not sure why it incorrectly works today.

**Comment by sandersn** [comment]
Well, I was sort of right. It's actually an error in the binder, from `checkContextualIdentifier`, not `parseVarExpression`. A better fix would be to change the definition of `inYieldContext` and `inAwaitContext` in `isIdentifier` to skip `let await`/`let yield` as well.

**Comment by sandersn** [comment]
Now that I've checked how to clear Yield/AwaitContext, I see that isBindingIdentifier is the same as isIdentifier without the special cases for yield/await.

I'd like to see two things:

1. Check whether the special case for yield/await is even needed. Try deleting it from isIdentifier and report back how baselines change. It could be that the binder has better error messages in *all* cases.
2. If that doesn't work out, put a small comment above `isBindingIdentifier` saying `// let await/let yield are allowed here and disallowed in the binder` (or something similar)

I think it's probably fine to call isBindingIdentifier instead of isIdentifier; isIdentifier hasn't changed for 5 years, and I assume @rbuckton created a isBindingIdentifier last year instead of passing a boolean to isIdentifier for performance reasons.

**Review by sandersn — CHANGES_REQUESTED** [review]
See comments above.

**Comment by Kingwl** [comment]
Moved to #44680.

**Pull request closed without merging**
