### PR TITLE
Fixed distributive conditional types with never intersections

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/57343

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top200
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Review by ahejlsberg — APPROVED** [review]
Not sure what to make of the premature exit [here](https://github.com/microsoft/TypeScript/pull/57345#issuecomment-1935103290), but otherwise looks good.

**Comment by Andarist** [comment]
> Not sure what to make of the premature exit https://github.com/microsoft/TypeScript/pull/57345#issuecomment-1935103290, but otherwise looks good.

I don't think this is related, we can see the same failure reported 4 days ago [here](https://github.com/microsoft/TypeScript/issues/57294#issuecomment-1925947878)

**Comment by RyanCavanaugh** [comment]
How long before the first "I can't get this repro shorter than 60 lines" bug bisects to this PR? 😅

**Comment by Andarist** [comment]
The time will tell 😅  If that happens you can count on me doing some quality investigation on what and why has happened 😉

**Comment by RyanCavanaugh** [comment]
A little under 3 months, as it turns out

**Pull request merged**
