### PR TITLE
Early couldContainTypeVariables check in instantiateType

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR revises `instantiateType` to perform an early check of `couldContainTypeVariables`. Previously this check was performed in multiple places. This change also means that we don't count instantiations of types that don't contain type variables (which are basically no-ops).

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@weswigham With my latest commit, `couldContainTypeVariables` returns false for types that are aliased by a non-generic top-level type alias. That would address the issue you point out about when `OtherReallyBigObjectTypeUnion` is a union with a top-level type alias.

**Comment by weswigham** [comment]
Nothing that properly tests it since we started deferring mapped type member type instantiation.

**Pull request merged**
