### PR TITLE
Super inside inner class crashes

### PR DESCRIPTION
**Pull request by sandersn**
**Fixes issue:** #6859

	super's containing class doesn't require base node

In a class nested inside a constructor, `super` refers to the outer
class' `super`, but when resolving a super call its containing class is
identified as the immediately containing class. Previously, the compiler
crashed, preventing the error from being reported correctly. Now it
handles this disparity and correctly reports the error.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by yuit** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
Any idea why GitHub thinks the testcase is binary?

**Comment by sandersn** [comment]
Emacs says it's UTF-16. I think the normal encoding is UTF-8. I'll reencode as UTF8 and see what happens.

The reason it's UTF16 is that I was trying to make an equivalent of `touch` in powershell, which (I forgot) communicates in UTF16.

**Comment by sandersn** [comment]
Yep. I guess git doesn't like UTF16.

**Pull request merged**
