### PR TITLE
Bump version to 5.5.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Note that this breaks all the deprecations from 5.0. Unfortunately, I cannot look into that.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I don't feel like making the bot smarter...

I do like being reminded how important the bot thinks I am though!

**Comment by DanielRosenwasser** [comment]
@sheetalkamat last commit edits a test for project references with prepend to permit errors.

**Comment by ghiscoding** [comment]
image

nice!!! I assume that a build size comparison will be made available when the v5.5 release blog post comes out!? Removing ES3 is long overdue 😄

**Comment by jakebailey** [comment]
Those are all test changes; the removal of ES3 is not likely to reduce the size of the package too much.

**Comment by ghiscoding** [comment]
oh ok thanks for the info @jakebailey

**Pull request merged**
