### PR TITLE
Allow self referential type aliases

### LINKED ISSUE #32967: Recursively-typed array with nth-element typing
## Search Terms

• recursive (tuple|array) of varying length
• differently-typed array elements
• tuple of (generic|unknown) size

## Suggestion

Ability to recursively type the elements of varying-length arrays

## Use Cases

I'm attempting to create a type for hypertext nodes. Consider the following representation of some HTML:

```json
["div", {"id": "parent"},
  ["div", {"id": "first-child"}, "I'm the first child"],
  ["div", {"id": "second-child"}, "I'm the second child"]
]
```

This is similar to the arguments of React's `createElement`. While it's possible to type the arguments array of a function and account for rest spread type... this doesn't seem doable in a standalone array. Meanwhile, tuples must be of fixed length. One solution would be to define this hypertext within call expressions:

```ts
h("div", {id: "parent"},
  h("div", {id: "first-child"}, "I'm the first child"),
  h("div", {id: "second-child"}, "I'm the second child"),
)
```

However, this format is more bloated. It doesn't convey the most minimal format for the data. My sense is that I should––for the time being––make use of `any[]`.

By the way, apologies if this is currently possible and I just did not find it! Looked for quite a while & no approach seemed to do the trick.

## Examples

```ts
export type HypertextNodeStructure<T, P, C> = [T, P, ...C[]];
export interface HypertextNode
  extends HypertextNodeStructure<string, {[key: string]: any}, HypertextNode> {}

const hypertextNode: HypertextNode =
  ["div", {id: "parent"},
    ["div", {id: "first-child"}, "I'm the first child"],
    ["div", {id: "second-child"}, "I'm the second child"]
  ]
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #32967

I talked about this in [the linked issue](https://github.com/microsoft/TypeScript/issues/32967#issuecomment-523299071), but I think we already have pretty close to what we need in place to handle recursive type aliases - so this PR adds the parts we were missing.

With this you can now write:
```ts
type HypertextNode = string | [string, { [key: string]: any }, ...HypertextNode[]];
```
and it will check like one may expect:
```ts
const hypertextNode: HypertextNode =
    ["div", { id: "parent" },
        ["div", { id: "first-child" }, "I'm the first child"],
        ["div", { id: "second-child" }, "I'm the second child"]
    ];
```

How it works
--------------
When we're creating a type reference, if we're looking to get a reference to a type alias type, we peek the circularity stack - if we see that we're already resolving that type, we return a (cached) "deferred substitution type". These substitution types can be handled exactly like any other substitution, the difference is in their implementation - their `substitute` field is not calculated until it is first accessed. (If this cuteness is a little over the top, a new type kind that functions like this could be added, but then we'd lose the free handling that already exists and would need to replumb a lot). So long as that substitute isn't immediately unwrapped, it can serve as a (reinstantiable!) placeholder for the type alias, functioning as a self-reference position.

I'm opening this mostly to advance the discussion from #32967. Much of what we saw as blockers on recursive type aliases has, at this point, been handled in some way already (since conditionals and indexed accesses have inadvertently allowed some of the same mechanics, over time). Provided we want to commit to it, I think it's certainly reasonable for us to handle circular type aliases without substantial architectural change.

### CODE REVIEW

**Comment by weswigham** [comment]
cc @ahejlsberg so you can get an idea of what I've been going on about it not being that bad of a change if we don't want it to be.

Oh, and @typescript-bot pack this because why not

And @typescript-bot run dt while I'm at it - considering this only affects what were error cases before....

**Comment by weswigham** [comment]
Oh, and @typescript-bot pack this because why not

And @typescript-bot run dt while I'm at it - considering this only affects what were error cases before....

**Comment by RyanCavanaugh** [comment]
<sub>https://twitter.com/SeaRyanC/status/1128332816163278853</sub>

**Comment by weswigham** [comment]
DT looks like master's DT, as expected, this has no change in any extant non-erroring code~

**Comment by isiahmeadows** [comment]
How does this deal with conditional types? https://github.com/microsoft/TypeScript/issues/26980

**Comment by weswigham** [comment]
Well, I mean, I already have a test in the PR that uses one _inside_ of a tuple in an alias.... So...maybe? Haven't tried yet - so long as we're not immediately unwrapping the substitute before we manufacture the type (which we may do sometimes for conditionals to facilitate simplification), it might work.

**Comment by fatcerberus** [comment]
Recursive conditional types would be great and make it possible to model, e.g. `Array.prototype.flat` with infinite depth:

```ts
// note: might not be 100% correct
type Flattened<T>= T extends (infer U)[][] ? Flattened<U[]> : T;
```

**Comment by isiahmeadows** [comment]
@fatcerberus If you're trying to model actually performing it at the type level, that'd be how you would do it (assuming this even handles that). But it does beg the question, if combined with #29317: Given the following type `Flatten<T>`:

```ts
type Flatten<T extends any[]> =
	{[P in keyof T]: T[P] extends Array<infer U> ? U : T[P]};
```

Would either or both of these be valid?

```ts
// 1. covariant
const flat1: Array<not Array<any>> = 

// Helper
```

**Comment by fatcerberus** [comment]
@isiahmeadows Yeah, I was trying to model the return type of `[...].flat(Infinity)`.  It's currently not possible to do so because of the ban on recursive type aliases.

**Comment by isiahmeadows** [comment]
@fatcerberus I know.


@weswigham Sorry, I forgot to mention you [with my question](https://github.com/microsoft/TypeScript/pull/33018#issuecomment-524529473).

**Comment by weswigham** [comment]
We'll be building this feature off of #33050 now which includes some parts of this~

**Pull request closed without merging**
