### PR TITLE
Weak type errors on signature-only types

### LINKED ISSUE #17656: Weak type detection only works with object literals being passed
**TypeScript Version:**  2.4.0

**Code**

```ts
interface ITest {
    optional?: string;
}

function test(param: ITest): void {

}

class Test {

}

test({ whatever: 0, optional: "" }); //<-- compiler doesn't allow this
test(test); //<-- compiler allows this
test(Test); //<-- compiler allows this
test(new Test()); //<-- compiler allows this
```

**Expected behavior:**
Passing any object of any type that doesn't match with at least one of the properties defined in the weak type, should fail.

**Actual behavior:**
Only object literals that don't at least partially much are not allowed to be passed.

### PR DESCRIPTION
**Pull request by sandersn**
Now source types that only have a call signature (like functions) or construct signature will get a weak type error too. This is really good for catching uncalled functions:

```ts
functionTakingWeakType(returnWeakType);
// OOPS. Forgot to call `returnWeakType()`. That's an error!
```

Fixes #17656 

Previously I didn't think enough about these types and assumed that we couldn't catch errors like this without breaking something else. Nothing breaks in our test suite, though, so I'm going to run it on DefinitelyTyped and see what breaks.

### CODE REVIEW

**Comment by sandersn** [comment]
Definitely Typed didn't turn up any new breaks. That's good, although a little surprising that it didn't find *any* mistakes in the tests anywhere.

**Comment by sandersn** [comment]
"Did you forget to call this?"

Sure, I can do that.

**Comment by sandersn** [comment]
I think I'll merge without a quick fix. I don't think it's high-value when it only applies to nullary functions, and quick fixes are quite finicky to get right. I can do it after the 2.5 release if we decide it's worth it.

**Comment by weswigham** [comment]
Alright, sounds fine.

**Comment by sandersn** [comment]
I thought about that and decided I'd rather make the implementation a little simpler and the error slightly less accurate.

**Pull request merged**
