### PR TITLE
Port 8369: Support module.exports.name = expr format for JavaScript m…

### PR DESCRIPTION
**Pull request by paulvanbrenk**
Fixes https://github.com/Microsoft/nodejstools/issues/1049 for TypeScript 1.8

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
@mhegazy Can you take a look

**Comment by mhegazy** [comment]
can we also port the tests please.

**Comment by mhegazy** [comment]
👍 after the tests has passed.

**Comment by billti** [comment]
:+1:

**Pull request merged**
