### PR TITLE
Improve logic that chooses co- vs. contra-variant inferences

### LINKED ISSUE #52111: Sub-optimal type parameter inference with strictFunctionTypes enabled
These are cases I've extracted from #49929; they are cases where if you don't specify the type parameters yourself, the inference isn't good.

This is potentially a full duplicate of #49924, however, the fix suggested in that issue does not work properly in our codebase. To test these, it may be easiest to just clone https://github.com/microsoft/TypeScript/pull/49929 with the explicit type parameters removed and see what works and what doesn't.

```ts
enum SyntaxKind {
    Block,
    Identifier,
    CaseClause,
    FunctionExpression,
    FunctionDeclaration,
}

interface Node { kind: SyntaxKind; }
interface Expression extends Node { _expressionBrand: any; }
interface Declaration extends Node { _declarationBrand: any; }
interface Block extends Node { kind: SyntaxKind.Block; }
interface Identifier extends Expression, Declaration { kind: SyntaxKind.Identifier; }
interface CaseClause extends Node { kind: SyntaxKind.CaseClause; }
interface FunctionDeclaration extends Declaration { kind: SyntaxKind.FunctionDeclaration; }

type HasLocals = Block | FunctionDeclaration;
declare function canHaveLocals(node: Node): node is HasLocals;

declare function assertNode<T extends Node, U extends T>(node: T | undefined, test: (node: T) => node is U): asserts node is U;
declare function assertNode(node: Node | undefined, test: ((node: Node) => boolean) | undefined): void;

function foo(node: FunctionDeclaration | CaseClause) {
    assertNode(node, canHaveLocals)

    node;
    // ^?

    assertNode<Node, HasLocals>(node, canHaveLocals)

    node;
    // ^?
}


declare function isExpression(node: Node): node is Expression;

declare function cast<TOut extends TIn, TIn = any>(value: TIn | undefined, test: (value: TIn) => value is TOut): TOut;

function bar(node: Identifier | FunctionDeclaration) {
    const a = cast(node, isExpression);
    //    ^?

    const b = cast<Expression>(node, isExpression);
    //    ^?
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var SyntaxKind;
(function (SyntaxKind) {
    SyntaxKind[SyntaxKind["Block"] = 0] = "Block";
    SyntaxKind[SyntaxKind["Identifier"] = 1] = "Identifier";
    SyntaxKind[SyntaxKind["CaseClause"] = 2] = "CaseClause";
    SyntaxKind[SyntaxKind["FunctionExpression"] = 3] = "FunctionExpression";
    SyntaxKind[SyntaxKind["FunctionDeclaration"] = 4] = "FunctionDeclaration";
})(SyntaxKind || (SyntaxKind = {}));
function foo(node) {
    assertNode(node, canHaveLocals);
    node;
    // ^?
    assertNode(node, canHaveLocals);
    node;
    // ^?
}
function bar(node) {
    const a = cast(node, isExpression);
    //    ^?
    const b = cast(node, isExpression);
    //    ^?
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/KYOwrgtgBAygniALgQwB4GkCWIAmUDeAUFCVAEIA2A9gMYDWANMaQJI6iKYBmmwATk1JQAwsgDOwYRWRgJg0gDEwIGpyogAoqgAOfYGLGZ18kkpVqQAEWA1pfZBaYBfQoWyJ+XZDWBQAclTsBFB02DgAXLAIKBhhANxQLu6e3r5auvqG6lDAqB64Yv6BvvhQAPq5GQZGIGT2uJHIIHAJSUgpPlDWtsj2Fjl5oDiFAUGlZew9fTV1TRFQTS2Jbu18Xp2UtHQD+cNFYyFhkfBIaFi4AHSb9K0rHmupUGwc3Lx8O0OF6XrVxl02dgcNWCoQaUVOsUuzyQr34t2SD06ogkUhkEg+BX2JUOYJOMXOOAuyMk0lkwHhq3WvjMqhq3UB-Vyu0K9N6QOypVB8zxZzCFxpFlZ03Ut0IiDg2l8AAlxAAZWjICiFAC85Go9CgAB8oAK6QC2RY4oRJnZfFxlLTsjQmjKAG7AeXWpUAChAxUio2AAEpIm6gphCjKxI7FWIjcb9XooObzMDxBI+IhPQAeAAqGL2noYUAAqhnCqmAHyu91QdPa5TsHggYA4bMeMSISIl9iRVNeqDKwtQP2+AO5n0LAz8RCFXtQfs5o0m3pmi39eMjz0t4Ae4paqCV4DV2v1-RNqDOldr9gdrtQABGVCoFGATQ7Fdw2+wtcHtqomBw4ZjlpA0evx46vOepTOyf7asSqJkh2RBCIuibLr22bWiAdoOgqSpeq4Qi9kaQgAPT4VAAB6AD82GkPBSbFMmWZQEGIZKsWSFQChaGMWIWHMCQuHcVAhEkeRLiuDOUY-v0AbfJkNSAZ6g7jv2Um-CA4aiXOsZWuIiBpgA8mAiD5mWLAgNmqbGZ2CzNMWtqKmAq5GeBm5PjudZQA2B7OjZFB2W2xlnt2Xl2ROBZ6Ygg6pqF37AdkF69IB0KcDw-Abrq6hCmBMF8TQ6iNgsFnWo2K7ZpJOg-FkIBenhpACaQZEUSQ2UgLlF75VpyZKeVzHFMVYgdTUlV8TVJB1U4QA)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #52111.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
I can confirm that this fixes all of my cast/assert issues on the SFT branch. Wonderful!

**Review by RyanCavanaugh — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Another example that I didn't realize was affected is this:

```ts
interface A {
    a: string;
}
interface B extends A {
    b: string;
}
interface C extends A {
    c: string
}
```

Then:

```ts
declare function isC(x: A): x is C;

declare function every<T, U extends T>(array: readonly T[], callback: (element: T, index: number) => element is U): array is readonly U[];
declare function every<T, U extends T>(array: readonly T[] | undefined, callback: (element: T, index: number) => element is U): array is readonly U[] | undefined;
declare function every<T>(array: readonly T[] | undefined, callback: (element: T, index: number) => boolean): boolean;

function foo(arr: readonly B[] | readonly C[] | undefined) {
    if (every(arr, isC)) {
        arr;
    }
}
```

In TS 4.9, this code errors because it picks `every<B, B>`, but now, it picks `every<A, C>`, and we get `arr` narrowed to `readonly C[]`. This comes up quite a bit on the SFT branch.

(I may send a PR for this test case too.)

**Comment by jakebailey** [comment]
I have another followup case that turned out to not be fixed (I also didn't catch it in the SFT branch in the same way as the above fixed case); I'll file a new issue.

**Pull request merged**
