### PR TITLE
Fix assertion functions accessed via wildcard imports

### LINKED ISSUE #35004: Assertion functions don't work with wildcard imports
**TypeScript Version:**  3.7.2

**Search Terms:**

assert function import export

**Code**

```ts
// Module asserts.ts
function isNonNullable<T>(obj: T): asserts obj is NonNullable<T> {
    if(obj === undefined || obj === null) {
        throw new Error('Must not be a nullable value');
    }
}

export {
    isNonNullable
};

// Module test.ts
import * as asserts from './asserts.ts';

function test(obj: string | null): void {
    asserts.isNonNullable(obj);
    obj.trim();
}
```

**Expected behavior:**
Everything works as expected

**Actual behavior:**
Error: Assertions require every name in the call target to be declared with an explicit type annotation.

If I rewrite test.ts with:
```ts
// Module test.ts
import { isNonNullable } from './asserts.ts';

function test(obj: string | null): void {
    isNonNullable(obj);
    obj.trim();
}
```
then everything compiles without any error

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #35004

This comes down to us resolving the symbol in some conditions but not others, which led to an inconsistent experience; these assertions were legal so long as the leftmost symbol wasn't a namespace import. If you imported a wildcard import _via_ another module's named exports, it was legal, but using a wildcard import to access that same export was not.

Hoping to get this in to 4.9 so it can in be our LKG for 5.0; this will allow me to convert the Debug namespace into a module (which will then enable scope hoisting and perf boosts).

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot test top100

**Comment by DanielRosenwasser** [comment]
Hm.

@typescript-bot perf test this

**Comment by jakebailey** [comment]
Seems like the perf difference was just noise.

**Comment by jakebailey** [comment]
Of course, I am left wondering why our deltas don't have error bars, only the raw numbers.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by jakebailey** [comment]
Using this PR to test my new benchmark.

@typescript-bot perf test this

**Comment by jakebailey** [comment]
I oopsed.

@typescript-bot perf test this

**Comment by jakebailey** [comment]
Well, I give up on that benchmark for now. Will fix it later. Merging.

**Pull request merged**
