### PR TITLE
Make never rest type top-like

### LINKED ISSUE #33495: never rest type not assignable to complex rest type
**TypeScript Version:**  3.5.1

**Search Terms:**

**Code**

```ts
function foo<T extends any[]>() {
    const fn1: (x: string, ...rest: T) => unknown = (x, ..._) => x;
    const fn2: (...args: never) => unknown = fn1 // error
}
```

**Expected behavior:**

Assignment of `fn1` to `fn2` should pass.

**Actual behavior:**

Assignment of `fn1` to `fn2` should fails.

**Playground Link:** [link](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdEBDMATwG0BdAPgAoBKRAbwChEfEIESUZGACMALkRNcEwQCcYYAOYAaRADoNs7IIkY2AXgaJwAazBwA7kn2TcqjWoD6Bo7gDc3XvzCDhAJgkmB3JZRRIJMGwAN2xZF2MwM0trYRFOAF8gA)

**Related Issues:** 
#33457

### PR DESCRIPTION
**Pull request by jack-williams**
_Not an actual fix as the issue is still under discussion. Figured I’d put up and implementation though._

Fixes #33495

### CODE REVIEW

**Comment by jack-williams** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by jack-williams** [comment]
> which should error, I believe?

Yep, added!

**Comment by jack-williams** [comment]
Thanks for powering through all these PR's @sandersn and @weswigham!

**Comment by jack-williams** [comment]
Short answer: no. That function type should not be callable.

Longer answer: After looking through this again last night and trying to fix it, I do vaguely remember looking at that behaviour before. I think the code to trigger the error was move involved and touched a couple of the signature checking functions. I guess I never got around to resolving that and when the PR was revived, I had forgotten.

I started working on a fix yesterday. Haven't run it through perf and regression test. I do think it is a big chage.

**Comment by andrewbranch** [comment]
Thanks @jack-williams, wasn’t expecting you to pick up a fix, just searching for info, but appreciate it!

**Pull request merged**
