### PR TITLE
Discourage typo fixes in PR template

### PR DESCRIPTION
**Pull request by tjjfvi**
Wording taken from [this comment](https://github.com/microsoft/TypeScript/pull/45834#issuecomment-919606286).

There have been a number of rejected typo fix PRs lately; hopefully this can reduce the amount of typo-fix-rejecting work for the team.

### CODE REVIEW

**Review by orta — APPROVED** [review]
I'll green it, but IMO we should remove:

>  The same generally applies to other projects. 

Because almost all advice for people getting started with OSS is to do this sort of change ( I've given that advice, and I'd give it again in the future ) as it's normally a cheap way to get used to the process

**Comment by RyanCavanaugh** [comment]
I like the spirit but feel the text is a bit strong. How about
```
** Typo Fixes **
Please don't send a PR solely for the purpose of fixing a typo, unless that typo truly hurts understanding of the text. Each PR represents work for the maintainers, and that work should provide commensurate value.

If you're interested in sending a PR, the issue tracker has many issues marked `help wanted`.
```

**Comment by DanielRosenwasser** [comment]
Maybe a mash-up?

> ```md
> We understand that typo fixes are nice, but when unless these typos
> truly make the text harder to read, these typo fixes often ust
> add work to the core team without providing much value. If you're interested in
> sending a PR, the issue tracker has many issues marked `help wanted`.
> ```

Go with Ryan's version unless he likes this one better.

**Comment by tjjfvi** [comment]
Edited to Ryan's version; I can change it to Daniel's if desired.

**Comment by orta** [comment]
Yeah, lets do this 👍🏻

**Pull request merged**
