### PR TITLE
WIP: in narrowing with record types

### PR DESCRIPTION
**Pull request by jack-williams**
Fixes #

### CODE REVIEW

**Comment by jack-williams** [comment]
@typescript-bot perf test this
@typescript-bot user test this
@typescript-bot test this

**Comment by jack-williams** [comment]
@typescript-bot perf test this
@typescript-bot user test this
@typescript-bot test this

**Comment by jcalz** [comment]
Fixes #21732?

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
