### PR TITLE
Fix getRecursionIdentity function to always return some identity

### LINKED ISSUE #43493: "Excessive stack depth comparing types 'FlatArray<Arr, ?>' and 'FlatArray<Arr, ?>'" false positive
# Bug Report

seems to be a very similar issue to #43249, where #43435 didn't seem to fix it

### 🔎 Search Terms
Excessive stack depth comparing types 'FlatArray<Arr, ?>' and 'FlatArray<Arr, ?>

### 🕗 Version & Regression Information
4.2.3-dev.20210401

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=6&ts=4.3.0-dev.20210401#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAK4oDWKSA7igNoC6AUMulgEazwC8OeAdNtAwBZKAAcAFOxhcAfPCnwoaeADE8ASngB6LQFEAHmBBo0ASwBuCTFDCl4oURgAWiJAFtRsUygDm8DACeosbwAOQqggCCMDBQAQA80TAANPAA-DKhiijAYRFQGElxiTGpGaG84gBMAMxVAIzqDAzeGCAw2DYIakjwIPptOcpFCZgw3j5yAN4AvkA)

### 💻 Code

```ts
declare const foo: unknown[]
const bar = foo.flatMap(bar => bar as Foo) //Excessive stack depth comparing types 'FlatArray<Arr, ?>' and 'FlatArray<Arr, ?>'.(2321)

interface Foo extends Array<string> {}
```

### 🙁 Actual behavior
`Excessive stack depth comparing types 'FlatArray<Arr, ?>' and 'FlatArray<Arr, ?>` error

### 🙂 Expected behavior
no error

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #43493.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
This PR implements the fix I describe [here](https://github.com/microsoft/TypeScript/issues/43493#issuecomment-812931910). Basically, `getRecursionIdentity` now always returns *some* identity, which by default is the type itself.

The PR reverts the changes from #43435 (since they're no longer required and don't fix the core issue). However, I'm keeping the tests from that PR.

Regarding the baseline changes, two tests that previously failed now succeed--as they did when they were originally created.

The `mappedTypeRecursiveInference.ts` test would previously fail with an `Excessive stack depth comparing types...` error. That error no longer occurs, which is good. However, instead the test involving `XMLHttpRequest` ultimately fails with `Type_instantiation_is_excessively_deep_and_possibly_infinite`, which is expected but takes about twice as long as our test timeout limit. For that reason, I've deleted that particular test.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
Tests all look good, performance is unaffected.

**Review by andrewbranch — DISMISSED** [review]
Makes sense 👍

**Comment by weswigham** [comment]
> which is expected but takes about twice as long as our test timeout limit. For that reason, I've deleted that particular test.

That doesn't seem like a good outcome - a  reverse mapped type over something with a pointer to a deep type hierarchy adding 40s to a compilation seems unacceptable to me? I just tested it out - https://github.com/microsoft/TypeScript/pull/42485 can bring the runtime of that test down from 27s to 3s. Still not _great_ (3s for a single call on a beefy machine?), but fixes it by an order of magnitude and definitely makes it keepable as a test.

**Comment by ahejlsberg** [comment]
I'm not sure I understand how #42485 helps. Before the fix in this PR we'd end up hitting the panic limit at 100 recursive invocations and output an `Excessive stack depth comparing types...` diagnostic, which prints the two types. This happed relatively quickly, but it is nonetheless wrong behavior.

With the PR we keep successfully relating types until we get to 50 levels of instantiations and then stop--but without printing any types, so #42485 wouldn't affect anything. It takes longer for this to occur but that isn't surprising given the very large number of types `XMLHpptRequest` touches if you recursively iterate over all of its properties.

**Comment by weswigham** [comment]
This test (from 7bd6eafc1747372fe5537167d1f50ee9e12f0b10):
```ts
let xhr: XMLHttpRequest;
const out2 = foo(xhr);
out2.responseXML
out2.responseXML.activeElement.className.length
```
you said you removed from this PR because after this PR, it takes an excessive time to typecheck. I can see that - on my machine it typechecks in 27s and issues a (bogus! The tree of possible reverse-mapped types is in fact finite!) `error TS2589: Type instantiation is excessively deep and possibly infinite.`. If you merge this PR and https://github.com/microsoft/TypeScript/pull/42485 (which caches reverse mapped types _much_ better than we do today via two means: 1. actually caching the lazily inferred property types (today we repeat inference on every property lookup!) and 2. identifying that repeated indexing on the template of a reverse mapped type is that same as the base and transforming the type as such [as explained in this comment](https://github.com/microsoft/TypeScript/pull/42485/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R10921), allowing caching to be shared as inference descends into a tree of types), the erroneous error goes away and typecheck time gets reduced by an order of magnitude.

**Comment by ahejlsberg** [comment]
@weswigham I thought #42485 was just about fixing type printback, but great that it also improves performance. Let's get it merged before this PR and then we can keep the test.

**Pull request merged**
