### PR TITLE
Routine update of dom libs

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes:

#10992 
#10457 
#10059
#4400

### CODE REVIEW

**Comment by errorx666** [comment]
<del>-    addEventListener(type: "error", listener: (this: this, ev: ErrorEvent) => any, useCapture?: boolean): void;</del>
<ins>+    addEventListener(type: "error", listener: (this: this, ev: ProgressEvent) => any, useCapture?: boolean): void;</ins>


Is that right?

**Comment by mhegazy** [comment]
Why not?

**Comment by mhegazy** [comment]
Here is the change that brought this in: https://github.com/Microsoft/TSJS-lib-generator/pull/144

**Comment by errorx666** [comment]
@mhegazy It just seemed odd that the event object type of the `error` event changed from `ErrorEvent` to `ProgressEvent`.  I didn't bother checking whether or not it was actually correct.

**Comment by zhengbli** [comment]
@errorx666 the spec said so: https://xhr.spec.whatwg.org/#events

**Pull request merged**
