### PR TITLE
Please ignore: dotnet jenkins CI WIP

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Doing some setup work on the .net Jenkins CI since Travis seems to be :ghost:

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by dilijev** [comment]
@mmitche Does the initial commit of the configuration script need to be merged in before it's possible to request a CI test, or is something else wrong here?

**Comment by mmitche** [comment]
No it should work, let me check on this.

**Comment by mmitche** [comment]
DId you put the webhooks in from https://github.com/dotnet/dotnet-ci/blob/master/docs/CI-SETUP.md?

**Comment by RyanCavanaugh** [comment]
I had the wrong Webhook set up (didn't realize I needed to change it when the config file changed to CI2). Updating now

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
Ahh sorry.  So you added both yes?  Anyway you can add me as an admin quick and I'll take a look?  It looks like you have the right stuff

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
Why does the bot ignore me? :slightly_frowning_face:

**Comment by dilijev** [comment]
It's not ignoring you, you're just asking for a test that doesn't exist yet :P
"test this please" is a trigger that only works once the Jenkins config is merged in, whereas what I typed tests the CI configuration in the current PR.

**Comment by RyanCavanaugh** [comment]
When Matt wrote it, it triggered an actual test run. Or do the commands need to be invoked serially?

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by dilijev** [comment]
No, they are independent. I would think @mmitche request for "test this please" didn't actually do anything but he might have done something in the backend to wake @dotnet-bot up and pay attention to your request, and set that off with a "test this please"... or maybe there was a delay for a few minutes, but honestly I don't know.

You should try again! (No worried about the extra requests, this is a drop in the bucket.)

**Comment by mmitche** [comment]
Oh, I had disabled the generated jobs agian.

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test this please (enabled jobs for testing)

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
Closing in favor of #11763

**Pull request closed without merging**
