### PR TITLE
Add nullability into signature

### LINKED ISSUE #7810: Modularization reverted adding nullability annotations to es6.d.ts
#7715 reverted the ES6 part of #7650

Eg: Array.findIndex:

Before: https://github.com/Microsoft/TypeScript/blob/9705c89/src/lib/es6.d.ts#L334

After: https://github.com/Microsoft/TypeScript/blob/68bdbe0/src/lib/es2015.array.d.ts#L22

cc @yuit

### PR DESCRIPTION
**Pull request by yuit**
Fix #7810

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1: 

@Arnavion can you take a look.

**Comment by Arnavion** [comment]
Missing changes to es2015.symbol.wellknown.d.ts for https://github.com/Microsoft/TypeScript/pull/7650/files#diff-51388ac7d7d5066f71748cd419d6dca0R456 and https://github.com/Microsoft/TypeScript/pull/7650/files#diff-51388ac7d7d5066f71748cd419d6dca0R726

**Comment by yuit** [comment]
Thanks @Arnavion . Address the comment

**Comment by Arnavion** [comment]
LGTM

**Pull request merged**
