### PR TITLE
Properly handle control flows from returns in try/catch within IIFE

### LINKED ISSUE #36828: Flow analysis fails when using try catch block in IIFEs
**TypeScript Version:**  3.8.0-beta onwards

**Search Terms:** return, iife, error, flow anaylsis, try catch

**Code**

```ts
const x = (() => {
  try { return 'x'; } catch (e) {
    return null;
  }
})();

// any code here is unreachable according to TS
```

**Expected behavior:**
Typescript marks code as reachable

**Actual behavior:**
Typescript wrongfully assumes that any code after the block is unreachable

**Playground Link:** 
https://www.typescriptlang.org/play/?ts=3.8-Beta&ssl=11&ssc=14&pln=17&pc=4#code/DYUwLgBAngXBBGB7RoCGA7A3AWAFB4DMBXdAYzAEtF0IBnRAW3AAsL0BzAFWdTAGFERYABMAYqgrAAFAEo4tMACc27CAG88ECBQIQpUGes1aIYZosQB3COhDWAooouKpAchBPEi1zJy4tAL7GiuBEijSuCsocrn5B+LjEZJTUEATIsvJKKkb+EKTUChAAHhAAvHqy5QB8uSamilB19RAhYGE09ExmKty8AkJiEtK+xoH5vKTMeiCGGnn1bR02QsB+9fGBMrJ+xjp6pWVHK8DAhkvhEK4EqKfwqKQA1rF4waGXxXFAA

**Related Issues:** 
None found

**Some more info:**
I initially found this issue in version `3.9.0-dev.2000215` but found it to also be present in `3.8.0-beta`. It it not present in the current stable version (`3.7.5`).

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #36828.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-3.8

@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
RWC is clean. Everything else has failures (why?), but it all looks like preexisting conditions.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@weswigham The PR had the correct types, but we weren't consistently reporting the unreachable error following the try statement. I have fixed that, plus I have added your test case.

**Pull request merged**
