### PR TITLE
Always fully compute variance structurally

### LINKED ISSUE #44572: Check order dependence with mutually-recursive non-unary generics
# Bug Report

Adding an implementation of an interface allows an invalid assignability check of the interface to pass

### 🔎 Search Terms

assignability, unnecessary implementation

### 🕗 Version & Regression Information

- This changed between versions 3.7.5 and 3.8.3

It's still present in all versions including nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.2&strict=true#code/JYOwLgpgTgZghgYwgAgApyhcAeAggGmQCEA+ZAbwChlkBzCMAYQAtgAbAEwAoBKALmQt2HPIVIBuStWTBIUXgICScuACM2EbOkw4CxEiUkBfKaDnwkg1p1H7pEAB6QQHAM5oMWMLdIVpmOA4AexA2AE9kOAFcSRoA4NCI1QEiYykENjhXd0UAWwAHNh8yYAKNXK93bS9ivxoEENcwKABXBDAg+XiQ8OQEaw4BIRs9Uh465BNpeiYBhSthWqoaOIYWqBBkMFZXADp+4VjJqRoAKlloeeVoNQ0tT10xAwn6xrBkXLh85ABeZBAIAB3ZAAWS+2GGIhaIAA1iAgoCQIRoXCESASIRIcUANoAXRIvEk0hoMGh7WAIVOdCwXGJK1A+SGA2KdP4yGuUFumixo2eyxWNDCwAgnCpn3yuxmXAZ4wAPrLkHijjQTCrKFMGiAmsgHAJqjgUfDEcjYUb0b8KEZIu44CAwpJNdqAPp6h7eEAtNhsE2oxFkP4OcRAA)

Thanks @MartinJohns for the link

### 💻 Code

```ts
interface Parent<A, B> {
  getChild(): Child<A, B>;

  iter(): Iterable<Parent<A, B>>;
}

interface Child<A, B>
  extends Parent<A, B> {
  readonly a: A;
  readonly b: B;
}

class Impl<A, B> implements Parent<A, B> {
  constructor(readonly child: Child<A, B>) {
  }

  getChild(): Child<A, B> {
    return this.child;
  }

  *iter(): Iterable<Parent<A, B>> {
    const map = new Map<Child<unknown, unknown>, Child<A, B>[]>();

    function* gen(
      inp: Child<A, B>
    ): Iterable<Child<A, B>> {
      yield* map.get(inp) || [];
    }
  }
}

const x: Parent<unknown, unknown> = {} as any;
const _: Parent<null, unknown> = x; // should not pass
```

The final assignment should not pass. It accurately errors in 3.7.5,  if the `Impl` class is removed (or any aspect of the `iter` implementation is modified), or by adding a sentinel type like `sentinel?: A` to the `Parent` interface to aid in type checking.

### 🙁 Actual behavior

No error is thrown in the final assignment.

### 🙂 Expected behavior

A n error is throw:
```
Type 'Parent<unknown, unknown>' is not assignable to type 'Parent<null, unknown>'.
  Type 'unknown' is not assignable to type 'null'.
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #44572.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
Tests are clean. Performance is slightly impacted in `xstate` but otherwise improved. I think this is an acceptable fix.

**Review by weswigham — APPROVED** [review]
This looks good, but I wonder if the `inconpleteVariancesObserved` flag needs to be saved and restored from the cached relation result similarly to variance markers themselves.

**Comment by ahejlsberg** [comment]
> This looks good, but I wonder if the `incompleteVariancesObserved` flag needs to be saved and restored from the cached relation result similarly to variance markers themselves.

That shouldn't be necessary because we don't cache relations that observed incomplete variances (they result in `Ternary.Unknown`, and those never get cached).

**Comment by Andarist** [comment]
This PR doesn't fix the problem reported [here](https://github.com/microsoft/TypeScript/issues/44572#issuecomment-1042915921) while the previous PR was fixing this.

**Comment by ahejlsberg** [comment]
Sadly there are still issues with the fix in this PR as well as the fix in (the now closed) #45628. The core issue looks to be mutually recursive types in which variance is flipped by one of the types. For example:

```ts
type Foo<T> = {
  x: T;
  f: FooFn<T>;
}

type FooFn<T> = (foo: Foo<T>) => void;

declare let foo1: Foo<string>;
declare let foo2: Foo<unknown>;

declare let fn1: FooFn<string>;
declare let fn2: FooFn<unknown>;

foo1 = foo2;  // Error
foo2 = foo1;  // Error

fn1 = fn2;  // Error
fn2 = fn1;  // Error
```

Above, the `x` property in `Foo<T>` witnesses `T` co-variantly and the `f` property witnesses `T` recursively and contra-variantly. The combination should cause `T` to be considered invariant, and it is in the example above. But with a small change to `FooFn<T>` things fall apart:

```ts
type FooFn<T> = (foo: Foo<T[]) => void;
```

Now, because `T` isn't referenced as a "naked" type parameter, we don't examine the `Foo<T[]>` reference structurally, but rather attempt to rely on the computed variance--which is in the process of being computed. So, results come out wrong and are potentially sensitive to order of computation. For example, with this PR we get the following behavior:

```ts
foo1 = foo2;  // Error
foo2 = foo1;

fn1 = fn2;
fn2 = fn1;
```

meaning that co-variance for `Foo<T>` and no witnessing in `FooFn<T>`. With #45628 we get

```ts
foo1 = foo2;  // Error
foo2 = foo1;

fn1 = fn2;
fn2 = fn1;  // Error
```

i.e. contra-variance for `FooFn<T>` which is slightly more consistent, but still wrong.

The tricky aspect of this example (and others like it) is that invariance isn't revealed unless we examine multiple circular type references structurally and in-depth. Which of course is exactly what we're trying to avoid with the variance computation in the first place.

**Comment by Andarist** [comment]
> Now, because T isn't referenced as a "naked" type parameter, we don't examine the Foo<T[]> reference structurally, but rather attempt to rely on the computed variance

Why is this making a difference? Is it purely an optimization for the most common case or something like that? I don't quite understand why naked and not-naked type parameters go through a different code path here 🤔

**Comment by ahejlsberg** [comment]
With the last commit we now always fully compute variances structurally. This simplifies our logic and fixes all known issues related to incomplete and/or order dependent variance computation (which means all issues mentioned in this thread), but it does have an adverse effect on the `xstate` performance suite. Other than possibly supporting variance assertions (as some form of annotations on type parameters) it's not clear how we can do better here. I'll run the full test suites to get a full picture of the effects of the changes.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by Andarist** [comment]
As mentioned - I'm very open to revisiting XState types to see if we can improve the situation anyhow there. I know that this is just a single library whereas this PR potentially impacts a lot more than that though. However, as a dev, I would always take a slower compilation over random errors - so this PR is a big improvement from my point of view.

Is there any rough description for the overall algorithm of how the variance is computed? If I understand correctly then:
- each type parameter has its own variance type
- to compute it we may need to traverse the whole type structurally, because if `T` is passed down through multiple layers then any layer can impact the variance type of the associated type parameter at the root level (and on each level in between)
- potentially when assessing that a type param is invariant you can return early from the algorithm since nothing else can change that
- this information can mostly be cached per uninstantiated type unless conditional types/mapped types do some weird-ish transformations under the hood (not saying that you are caching it, but that such a heuristic could potentially be used, I have no idea if it would be worth it - this is just me trying to understand the problem space better)

I wonder if there is any type construct that makes it impossible for you to take the associated "slot" into consideration? Like - I see how "makes" type params are taken into consideration, even when a type is "boxed" using some other type I can see how the relation gets transitive etc But when I think about crazy conditional & mapped types... I'm getting lost.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
@Andarist Here's a quick overview of the variance computation logic.

For a generic type `T<A, B>`, we determine the variance of `A` by structurally relating instantiations `T<Sub, B>` and `T<Super, B>`, where `Sub` and `Super` are internal marker types that have a known type relationship (i.e. `Sub` is a subtype of `Super`). Then

* if `T<Sub, B>` is related to `T<Super, B>`, but not vice versa, we know `A` to be covariant,
* if `T<Super, B>` is related to `T<Sub, B>`, but not vice versa, we know `A` to be contravariant,
* if neither is related to the other, we know `A` to be invariant, and
* if both are related to the other, we know `A` to be bivariant.

To determine the variance of `B`, we similarly structurally relate instantiations `T<A, Sub>` and `T<A, Super>`.

As we're relating these marker type instantiations, we may come upon other type instantiations for which we need to know the variance. If so, we recursively start a variance computation and use the results of that to relate the type arguments. We may also come upon a circular reference to an instantiation of a type for which we are already computing variance information. If so, we again structurally relate the instantiations, but only if some of the type arguments contain marker types. Ultimately, we stop relating after three levels of recursion.

In other to understand where time is spent in the variance computation logic you can use the `--generateTrace` compiler option. See [instructions here](https://github.com/microsoft/TypeScript-wiki/blob/main/Performance-Tracing.md). The `xstate` types appear to have a _very_ deep dependency graph (some 35 levels), which generates quite a lot of work. Anything you can do to simplify that will likely help greatly.

This is what the recursive invocation tree looks like for `getVariancesWorker` when compiling `xstate`:

```ts
StateSchema [
  Partial [
  ]
]
StatesConfig [
  StateNodeConfig [
    InvokeConfig [
      InvokeCreator [
        InvokeCallback [
        ]
        PromiseLike [
        ]
        StateMachine [
          StateNodesConfig [
            StateNode [
              ActionObject [
                ActionFunction [
                  ActionMeta [
                    State [
                      Mapper [
                      ]
                      PropertyMapper [
                      ]
                      MachineOptions [
                        Record [
                        ]
                        ConditionPredicate [
                          GuardMeta [
                            GuardPredicate [
                              ActivityDefinition [
                                InvokeDefinition [
                                  ActionFunctionMap [
                                    ActivityConfig [
                                      DelayFunctionMap [
                                        DelayExpr [
                                          SCXMLEventMeta [
                                            Event [
                                            ]
                                          ]
                                        ]
                                      ]
                                      MachineSchema [
                                      ]
                                      Map [
                                        IterableIterator [
                                          IteratorYieldResult [
                                          ]
                                        ]
                                      ]
                                      TransitionDefinition [
                                        IteratorResult [
                                          IteratorReturnResult [
                                          ]
                                        ]
                                        Omit [
                                          Exclude [
                                          ]
                                        ]
                                        TransitionDefinitionMap [
                                          TransitionConfig [
                                            DelayedTransitionDefinition [
                                              SendAction [
                                                ExprWithMeta [
                                                ]
                                                SendExpr [
                                                ]
                                                AssignAction [
                                                  Assigner [
                                                    AssignMeta [
                                                      PropertyAssigner [
                                                        PartialAssigner [
                                                          LogAction [
                                                            LogExpr [
                                                            ]
                                                            StopAction [
                                                              Expr [
                                                              ]
                                                              ChooseAction [
                                                                ChooseConditon [
                                                                  Readonly [
                                                                  ]
                                                                  StateNodeDefinition [
                                                                    StatesDefinition [
                                                                      StateTransition [
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
    SimpleActionsFrom [
    ]
  ]
]
Model [
  MachineConfig [
  ]
  ExtractEvent [
  ]
  Prop [
  ]
]
Typestate [
]
RaiseAction [
]
Guard [
]
RaiseActionObject [
]
Action [
]
Interpreter [
  Set [
  ]
  StateListener [
  ]
  ContextListener [
  ]
  Observer [
  ]
  SendActionObject [
  ]
  Subscribable [
  ]
]
BaseActorRef [
]
ActorRef [
  Sender [
  ]
]
Extract [
]
Event [
]
EventListener [
]
Promise [
]
Behavior [
  ActorContext [
  ]
]
Iterable [
  Iterator [
  ]
]
AdjList [
]
StateConfig [
]
ServiceConfig [
]
DelayConfig [
]
InvokeActionObject [
]
SingleOrArray [
]
AtomicStateNodeConfig [
]
```

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Comment by Andarist** [comment]
I can confirm that both of my issues related to this are being fixed with the latest build of this PR. However, I don't see an explicit test case for this being introduced here. The minimal repro created by me can be found [here](https://github.com/microsoft/TypeScript/issues/44572#issuecomment-1042915921). From what I understand this has been fixed within [this diff](https://github.com/microsoft/TypeScript/pull/48080/files/d05979172859c0968efa0bd5c99cfe0fffcae65a..367ef6d3c47121fc720ca4b9143c712596b3cfed) but as we can see there - no new tests have been added as part of this.

**Comment by ahejlsberg** [comment]
Sadly we won't be able to merge this PR. While it improves accuracy of variance measurement, the adverse effects on type checking performance are simply too great. For example, the check time for the fairly popular `immutable.js` framework degrades by 50x with this PR in its current form. For now, we'll have to accept that variance measurement for circular types is sometimes inaccurate and/or dependent on declaration order. However, with #48240 it becomes possible to add variance annotations to establish the correct variance in such cases.

**Pull request closed without merging**
