### PR TITLE
Update more diagnostic messages ES6->2015

### LINKED ISSUE #8996: Update diagnostic messages to ES2015 instead of ES6
Also the messages for `generator` and `async` have slightly different wording:

> **1220:** Generators are only available when targeting ECMAScript 6 _or_ higher.
> **1311:** Async functions are only available when targeting ECMAScript 6 _and_ higher.

I only noticed trying to search the phrase <q>EcmaScript 6 or higher</q>.

### PR DESCRIPTION
**Pull request by AppShipIt**
Fix #8996 CC @mhegazy.

### CODE REVIEW

**Comment by AppShipIt** [comment]
Hmm…passed locally?

**Comment by mhegazy** [comment]
thanks!

**Comment by mhegazy** [comment]
For future references, files under `lib\` are generated by `jake LKG`, and not updated in PRs.

**Comment by AppShipIt** [comment]
Huh I was curious because they looked generated. So they're not intended to be versioned?

**Comment by mhegazy** [comment]
We refresh them regularly. but off master.

**Comment by AppShipIt** [comment]
Makes sense thanks!

**Pull request merged**
