### PR TITLE
On windows handle the long paths in realpathSync.native

### LINKED ISSUE #49470: `forceConsistentCasingInFileNames` doesn't work for modules in `node_modules`
# Bug Report

### 🔎 Search Terms

- `forceConsistentCasingInFileNames`
- `node_modules`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `forceConsistentCasingInFileNames`

### ⏯ Playground Link

Not available—requires `node_modules` folder

### 💻 Code

With `forceConsistentCasingInFileNames` enabled and `fp-ts` installed in `node_modules`:

`src/struct.d.ts`:
```ts
export const foo = 1;

```

```ts
// Expected error, but got none ❌
import * as xs1 from "fp-ts/lib/Struct";
// Expected error, but got none ❌
import * as xs2 from "fp-ts/lib/struct";
// Error as expected ✅
import * as xs3 from "./Struct";
// Error as expected ✅
import * as xs4 from "./struct";
```

### 🙁 Actual behavior

See code comments above.

### 🙂 Expected behavior

See code comments above.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #49470

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Review by andrewbranch — APPROVED** [review]

**Comment by amcasey** [comment]
Gross

LGTM

**Comment by sheetalkamat** [comment]
@DanielRosenwasser @amcasey do we need to port this to 4.8 ? 4.7 potentially if we are going to have patch for 4.7 at all?

**Comment by amcasey** [comment]
@sheetalkamat The issue linked in the description doesn't have a lot of upvotes.  Have we been hearing about a lot of people hitting this issue?  I'm not sure I'd backport to 4.7 based on the information I have now.

**Comment by sheetalkamat** [comment]
@amcasey its not even the issue linked.. My bad that i assumed the debugging information we received from @fwienber was for that issue. 

@typescript-bot cherry pick this to release-4.8

**Comment by sheetalkamat** [comment]
@typescript-bot cherry-pick this to release-4.8

**Pull request merged**
