### PR TITLE
make splice `deleteCount` required in es5.d.ts

### LINKED ISSUE #32638: `deleteCount` param to `splice()` is not optional in es5 types
**TypeScript Version:**  3.5.1

**Search Terms:** splice deleteCount

**Code**
Set the target to ES5 then

```ts
[1, 2, 3].splice(0); // should error. deleteCount missing
[1, 2, 3].splice(0, 3); // ok
```

**Expected behavior:**
`[1, 2, 3].splice(0);` not allowed

**Actual behavior:**
`[1, 2, 3].splice(0);` allowed

**Playground Link:** [this](https://www.typescriptlang.org/play/?target=1#code/NoRgNABATJDMC6A6AzgBwDYEsDGBTAFAAwCUA3BAPQUTIAWA9gK7oAmEuATh-R4hC7nS4ALrgDCTAHbCIAW0zJkmSQHMAUKEgwICFBhwFCcMpWr0A1kA)

`deleteCount` only become optional in ES6

ES5: https://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.12
ES6: https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.splice

### PR DESCRIPTION
**Pull request by tjenkinson**
In ES5 `deleteCount` is not an optional argument. If it is not provided it defaults to 0 as a side effect of `undefined` being converted to an integer.
https://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.12

In ES6 `deleleteCount` is optional, and it defaults to the length of the array minus the start index.
https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.splice

If you are targeting ES5 but don't provide `deleteCount` the behaviour will be different depending on the environment your build is running in.

This PR makes the `deleteCount` required when targeting ES5 but should allow it to be optional for ES6.

fixes #32638

### When running in ES5
```ts
const input = [1, 2, 3];
const out = in.splice(0);
console.log(input); // [1, 2, 3]
console.log(out); // []
```

### When running in ES6
```ts
const input = [1, 2, 3];
const out = in.splice(0);
console.log(input); // []
console.log(out); // [1, 2, 3]
```

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by RyanCavanaugh** [comment]
@weswigham looks like some noise in the user suite diff - can you check in on it?

**Comment by weswigham** [comment]
I opened #32610 to fix the chrome devtools changes awhile ago, the other [changes](https://github.com/microsoft/TypeScript/pull/32606) (to the azure sdk which is happily updating rush and such under us, and to zone.js which seems to be broken slightly (no ides if that's our fault)) just need to be accepted.

**Comment by sandersn** [comment]
Thanks for your patience on this!

**Comment by RyanCavanaugh** [comment]
This caused a break
```ts
const arr: string[] = [];
const boundSplice = arr.splice.bind(arr, 0, 0);
const items: string[] = [];
// Used to be OK, now an error
boundSplice.apply(arr, items);
```

**Comment by ljharb** [comment]
@RyanCavanaugh it's OK in ES6, it's not OK in ES5 (altho there may have been pre-ES6 browsers that considered it optional). is that a type error when targeting ES6?

**Comment by RyanCavanaugh** [comment]
It's incorrectly a type error right now against ES6

**Comment by ljharb** [comment]
@RyanCavanaugh so does that mean this PR needed to also override it in ES6 to make it optional?

**Comment by DanielRosenwasser** [comment]
@tjenkinson I believe it's because under `strictBindCallApply`, we try to infer the types from the signature, but overloads don't play well with that functionality. So @ljharb, if you had ES6 as the target, that extra overload caused issues. We believe that the most reasonable solution is to just say it's optional.

**Comment by ljharb** [comment]
@DanielRosenwasser it seems like fixing the underlying flaws with overloads is a pretty important thing to address :-/

**Comment by DanielRosenwasser** [comment]
I agree, but I don't think we have anything concrete that we feel good about yet.

**Pull request merged**
