### PR TITLE
Go 5 levels deep when determining if an object type is deeply nested

### LINKED ISSUE #56138: TypeScript ignoring checks for deeply nested computed object types
### 🔎 Search Terms

inference, deeply nested, no error, type evaluation, typebox, hkt

### 🕗 Version & Regression Information

Hi, 

I've come across some unusual behavior where TypeScript seems to be skipping checks for certain kinds of computed types. This seems to be specific to deeply nested object types that are computed via intersection.  I note that the language service is reporting the correct type information in editor, however the compiler seems to be skipping checks on the reported type. This behavior can be observed using the TypeBox library, specifically for object types at least 2 levels deep.

- This is the behavior in every version I tried (5.1.6 onwards)

### ⏯ Playground Link

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4Yp8BQJQHkBOBLA5jgHYCGANqAMqE4AONApgC5pjJvsefQr0AeNAeyyNQjAJ4NQASUI0AriIC8lRsUY4AxgB5xDAQDNpshQD4e-ISI0DCAZxEz5S0ABUJ9AHQYARgCt6GowAFADeKKCgpPQAbvSkAIwAXK7uXn4BwWEREVGxpABMyW4Maf6BoeHZEfoCAkWpFIy4hHhBAJQANJURAL5tlX0og+aCwqLumApOoMqNapo67gaTjE5mfKNWNvYr08rFnj5lmZW5cUkpJUcZFVVnBfVX6eVZVaA1dZeejc2tnd3ZbzELCPb5NIh-LpVQa9frDFiuAAW9HeAlIpAEAHcIe85IRAjhtqBbIiBHJSAATUBkchYeibUD0LBYIS2VFYUTI0B0xhyLCEUDRMhyegdUCkzExJmclH6HBYHYUgT0NmEASMDwoFD6PEEmygGgs7xRAC28w0ADFdeobPEgqzko4FABtAC6bWSGCmLtdoFePL5AtZAG5QOgtJBOTg2UqVaA1SImSyOUMtTr8TaBYaBMb6Gb1JbrYTCPktC5GbxGPRCBS2V7Vj6TPaFY7jIw3R7XH7KgH+aAQ2GwBHwKAPGPQN4FFGY8rbKntUX9dnc-nNFaM8WAMzN2zJIK6ejLJ0a+zmtodz3e9u+-1MQP9hWh8ORsceak14kCUCxtmMRHR+cES4YCQNAhEDgAIQEXgjFIIh6CpCC4ixIDQLQ9DEC1dAMJw3DIARABVdQ4PEVC8PIkCRkscZJAAUSFUg5DUegyxMGYuz4KsazZIh9GlDBQAAfj9UBnQAaVAIhQAAa3oMRlgwV1PXE30elAZJCClLAyIo3T2ARCgxBNbw0TnbC9Is5AqLGCkAlIYEUWsOwRAAJXoYglUIUgxGSPEcAARxFYkjJM0hg2skRbI0ey6VAJydgwGhMzIXzqEClFbBCtFwo2aiopixzthEAAJIhGFSgKgsy4zsoi787IcuKitAMSiApCr0uCmqwp0yy+pgcCKA0ZEzV6-rxrqsqmX0YgNBRFxWo-V5xLapTiXBFpU1ysYpqwGa5tcIaRuICsuNrVxFqpZa3I8mxvNdQTknsX5KmdRLktIB6no2vBXtKwhGC+9aXoiGhgWIE1d1APFpLVTFCDdSpTwLVLYaxQhU3M8bsfABEAFkBApHA5SZMzWBx7G6oPVwbs87z3uLMgy1O6tzpcI682INj9gZmwmZcNiADIafcumxFYqmJhcWm7vF8tONZtl2eGznua7YWQlEmWvLENaAHJte8vXQB6SXJBcXmSFIZmFe4w6VbNNXyw10TLbIfW3dIY3Taxim+vA65AjGv3dMmgHptm+afhxW22Y5s1uwiFaa316OWj18KImRzRvt+TOaPoZI9eeiEM8x8mQ8sgPnmYX3K9D7aRGpw2xE9gAFFkGGEMQxLk2wbcrRXXA7gQu-UFU1c18TJIFWT5MMFw1pcFSWbt6XRdlst465oTQCCZexN9WOlc9ssVLY4SJI0rS2nU+MtJN505+WRezZRFuR7Hnu+4Hs6lc-pk49bCT1EhJKSz8F5LxXsfEWt0dZbwdjvYS+9oGDzXqfA+roL731iByZIYlb7X1wY-CBrhXRv0wElRmpAAHd17mIfu8s0Fs1oUAkB09wFyRflAw+q82YYO3tglBvCYHrzgd5M+h9sGaWIfgwhODpQ9CflwyBFC3KBXlAhVh38GG-yHi4VhOAJ7sVIRgE0OBGBljFC3dundAE6MYWxAAPqAD+di6E-wFqAFxtjR72PoY49YFgxjU0MSqNyFI5BzSwHoteYTbDWL4WyNy1gsAUi0KQ4ghAxBihhnDQgJg1b0WFMxLQQRKgty0G3YE6gmZt00NJLQLlrEbx1r4r+ATWKFKFhU1pEj6kaEac01xfSxDaM6QLQpoBBaVGqcIHAdSGlNLFO0-xnjunTN6Rouk6SBlDJadsrR7jxATO6SgNoQSGShOOUY2wESoksSYX-YeNyVRijbkk6GhA0bwzdGreJ9zolWMTqAmeMkVFkOSHMAskjXTvLMD0S51FqYGOOTo9iJcWjePjHIYyTIKGor8fMuMygUlCHSYSjpckxTK2Okina4c9qR1cIHSxTz9HxPYpSwBty2KiO3iC5OFIPY1z1kjVQKNQAAoQg84Ff5ozOj1mDLAENbB6ywZUA8RcczHDFaDV5UMXDlwgPXCyBkJULAFsHU1OEKHQstZ82lnN3mfLyejN07E-nsX3tMkSyrVXJDbqGPoirs4aHVdam16FwITAAHIQxVGDOakao1gXyo1EgJpE3MoOCC9MeoBSstiSwg1TYdUZCKJ2C2NcJbVEXAKNOfwiiNtTEAA)

### 💻 Code

```ts
import { Static, Type } from "@sinclair/typebox"

export type Input = Static<typeof Input>
export const Input = Type.Object({
  level1: Type.Object({
    level2: Type.Object({
      foo: Type.String(),
    })
  })
})

export type Output = Static<typeof Output>
export const Output = Type.Object({
  level1: Type.Object({
    level2: Type.Object({
      foo: Type.String(),
      bar: Type.String(),
    })
  })
})

// The following functions should all report errors for the return value, however the first does not.

function problematicFunction1(ors: Input[]): Output[] {
  return ors; // <-- this does not error 
}

function problematicFunction2<T extends Output[]>(ors: Input[]): T {
  return ors; // <-- ... but this does
}

function problematicFunction3(ors: (typeof Input.static)[]): Output[] {
  return ors; // <-- ... and so does this
}
```

### 🙁 Actual behavior

First function does not report an error

### 🙂 Expected behavior

All functions should report errors

### Additional information about the issue

I get the feeling this may have something to do with TypeBox's implementation of `Static<T>` and where TypeScript may be implementing some optimizations around certain forms of computed / evaluated types (but not sure). TypeBox currently implements `Static<T>` as follows.

```ts
type Static<T extends TSchema, P extends unknown[] = []> = (T & { params: P; })["static"]
```
By removing the intersection of P, TypeScript correctly asserts the `problematicFunction1` return type.
```ts
type Static<T extends TSchema, P extends unknown[] = []> = T["static"] // this is fine
```

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #56138, but at what cost?

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
FWIW DT failed because it ran before we could merge the big refactor there (not sure if that was a factor in you dropping this)

**Comment by RyanCavanaugh** [comment]
xstate perf 🫠

**Comment by jakebailey** [comment]
oh eek

well, that's xstate vOld so maybe it'd be better later (new perf when, @jakebailey)

**Pull request closed without merging**
