### PR TITLE
Port 5275 and 5461 into release-1.7

### PR DESCRIPTION
**Pull request by vladima**
ports #5275 and #5461 into release-1.7

### CODE REVIEW

**Comment by sandersn** [comment]
:+1:

**Comment by mhegazy** [comment]
does not look like we need this. closing.

**Comment by erykwarren** [comment]
@mhegazy TS 1.7 is really not playing well with npm (see #6424). I was hoping for this patch... :frowning:

**Comment by mhegazy** [comment]
1.8 is in stabilization at this point. we should have it out in the next few weeks. is using typescript@next a possibility?

**Comment by erykwarren** [comment]
Didn't realize 1.8 was so close!  We'll wait for it then and use this patch manually until then. Thanks for the reply!

**Comment by mhegazy** [comment]
thanks for that. appreciate your patience.

**Pull request closed without merging**
