### PR TITLE
Resolve alias of target symbol in mergeSymbol

### PR DESCRIPTION
**Pull request by sandersn**
Resolve the alias of the target symbol in mergeSymbol, then use the resolved flags to determine if the merge is allowed.

This disallows UMD export merges with declarations in the global namespace.

This is a better fix for #33006 than #35443, although it's a much riskier change that should be in nightly for a while. I deleted a couple of fourslash tests because they verified that UMD-global merges behave correctly, but this merge is disallowed now.

### CODE REVIEW

**Comment by sandersn** [comment]
I don't know *what* is going on in declareVariableCollision. I accepted baselines so we could look at the diff.

**Comment by weswigham** [comment]
Can we make those umd merges an error? They're tested because we know of folk who've come to rely on them. We may also need to poke at symbol excludes to allow the merge, while we're at it.

**Comment by sandersn** [comment]
I looked again at the UMD merges and they look like they all get the error "Cannot redeclare block-scoped variable 'React'". Do you want a more specific error? 

I was thinking "UMD declarations can't merge with a global because they are already global. Use --allowUmdGlobalAccess to access UMD declarations inside a module."

I'm working from the assumption that the reason people do this is so that they can refer to UMD globals even inside modules. Do you know another reason?

**Comment by weswigham** [comment]
Some consumers, like angular, have certain modules that actually just unconditionally make a thing that would otherwise conditionally global into a global, unconditionally. From what I understand, anyway.

**Comment by sandersn** [comment]
So, not UMD things?

**Comment by sandersn** [comment]
@typescript-bot test this

**Comment by sandersn** [comment]
@typescript-bot user test this

**Comment by sandersn** [comment]
Some things from in-person discussions:

1. @RyanCavanaugh and @weswigham described why we want to keep UMD/global merges: it allows somebody to use angular globally, but not anything else in their compilation. --allowUmdGlobalAccess allows everything. (I think this means that --allowUmdGlobalAccess is only suitable in a few cases.)

2. @weswigham and I discussed how to handle UMD/global merges in a principled way. The problem is that 
`getTypeOfSymbol` is a top-down dispatch on symbol flags that doesn't handle the weird merges that often happen today. So there's fallback code littered throughout its branches.

Instead we should mark weird-merge symbol in the binder (and checker where this is not possible, eg in mergeSymbol) and handle weird merges first in getTypeOfSymbol. The merge handling in getTypeOfFuncClassEnumModule[Worker] is a good first target.

I'll try this when I have time.

**Comment by sandersn** [comment]
I'm cleaning up our PR backlog, and the eventual fix for this PR will look quite different from this one, so I'm going to close this one.

**Pull request closed without merging**
