### PR TITLE
Reverts #39277 removing bundledPackageName

### PR DESCRIPTION
**Pull request by orta**
Re: #39277 - note that there is https://github.com/microsoft/TypeScript/pull/41510 which instead turns this into a suggestion instead of a compiler error.

It's looking like we don't want to ship 4.1 with `bundledPackageName` included as-is, this PR reverts those changes and tests.

### CODE REVIEW

**Comment by weswigham** [comment]
@orta rather than reverting the whole thing, why not just remove the new error on program construction if the break is too undesirable...? The flag definitely allows you to get _better_ declaration file output.

**Comment by orta** [comment]
Yeah, I'm totally open to this instead. Does that work for you @DanielRosenwasser  / @RyanCavanaugh? 

Will take a fresh stab at that tomorrow 👍🏻

**Comment by orta** [comment]
I'll make a PR to release-4.1 cherry-picking either this PR or #41510 when this is merged

**Comment by DanielRosenwasser** [comment]
Even if we want to keep the feature, I'm not sold on the name and there isn't much time to bikeshed that.

@typescript-bot cherry-pick this to release-4.1

**Comment by weswigham** [comment]
> Even if we want to keep the feature, I'm not sold on the name and there isn't much time to bikeshed that.

Whoa, we've had the flag shipped in the whole beta process - we've _already_ bikeshedded the name. Removing just the error is way less disruptive than stripping the whole feature, and lower risk to the release as a whole.

**Comment by sandersn** [comment]
@orta Since #41510 is less disruptive, do you want to keep this PR around?

**Comment by orta** [comment]
When this came up in a design meeting, the consensus was still to remove this option, but I'd like to give it one last discussion before dropping completely.

**Comment by orta** [comment]
OK, dropping this flag from 4.2 also.

**Comment by menduz** [comment]
Oh no! Decentraland was really relying on this feature. 

Help me with the planning for our tooling: is this completely removed from the plans or it is a temporary thing?

Thanks

**Comment by weswigham** [comment]
We have plans to bring it back, but with a different name, and without the error requiring its use - some contention was had that the name `bundledPackageName` potentially implied that we were some kind of full service bundler, rather than a relatively dumb concatenator.

**Comment by arose** [comment]
> We have plans to bring it back, but with a different name, and without the error requiring its us

Any update on this?

**Pull request merged**
