### PR TITLE
fix for issue #14363

### PR DESCRIPTION
**Pull request by ffMathy**

### CODE REVIEW

**Comment by ffMathy** [comment]
This fixes #14363.

**Comment by jamesots** [comment]
The readme in src/lib says that .generated.d.ts files shouldn't be edited by hand and that TSJS-lib-generator should be modified instead. (Not sure if I'm right about this though).

**Comment by ffMathy** [comment]
Well in that case @jamesots I undid that change. Does it look better now?

**Comment by mhegazy** [comment]
Thanks for your PR. these files are not manually edited, they are auto-generatd from a script in . You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TSJS-lib-generator. 

Changes should be done in https://github.com/Microsoft/TSJS-lib-generator instead.

Please find more information at: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Pull request closed without merging**
