### PR TITLE
lib: remove `length` field from SharedArrayBuffer

### LINKED ISSUE #40857: lib: SharedArrayBuffer shouldn't have a `length` instance field
**TypeScript Version:**  Nightly

**Search Terms:**

SharedArrayBuffer

**Code**

With `"compilerOptions": { "target": "ES2017" }` or above.

```ts
new SharedArrayBuffer(10).length.toString();
```

**Expected behavior:**

Error on `length`, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) SharedArrayBuffer doesn't have a `length` instance field.

**Actual behavior:**

Type check passed, runtime error `Cannot read property 'toString' of undefined`

**Playground Link:** 

https://www.typescriptlang.org/play?ts=4.1.0-dev.20200930#code/HYUw7gBAygFghgJxAEwIIIXAngIQK4BmBICAFAIwAMAlAHQA2IwA5gC4y2sD2UrCAli1LUA3EA

**Related Issues:**

### PR DESCRIPTION
**Pull request by yume-chan**
Fixes #40857

I didn't find instructions on adding tests for lib, if a test is required please give me some code pointer, thanks.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
It looks like this was intended to go in `SharedArrayBufferConstructor`, can you please move the declaration down to the next interface? Thanks!

**Comment by yume-chan** [comment]
@RyanCavanaugh Looks like if an interface has a `new(): T` declaration, it will automatically inherits `Function` can get all `Function`'s properties.


```ts
interface Foo {
  value: string;
}

interface FooConstructor {
  new(value: string): Foo;
}

declare const Foo: FooConstructor;
Foo.length; // number
```
[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIBucANgK4QBcyAzmFKAOYDcuAvrrqJLIihugDC6EHShkEYdFBz5kICAHcAFMXJVa9JgEpqA1h1wATCAhJwoKBCLppMezMNH0JUqKwEA6EhBCMwABbMyAD0IfJkALYARtBAA)

If you need I can type it as `1` to reflect its real value.

**Comment by sandersn** [comment]
@yume-chan can you create a test in tests/cases/compiler/?

You'll need `// @lib: es2017` as the first line I think.

Then just use `length` in the incorrect way and make sure it the baseline generates an .errors.txt file, or if the inherited property means that there's no error, make sure that the .types file has the type you expect.

**Review by sandersn — CHANGES_REQUESTED** [review]
Need a test (see previous comment)

**Comment by yume-chan** [comment]
I found some already existed tests for SharedArrayBuffer in "tests/cases/conformance/es2017/" folder, and strangely, "useSharedArrayBuffer5.ts" and "useSharedArrayBuffer6.ts" have exactly same content.

So I just edited "useSharedArrayBuffer6.ts" to be some new tests.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
