### PR TITLE
Throw syntax error for `}` and `>` in JSX text

### LINKED ISSUE #36341: Proposal: throw syntax error for `}` and `>` in JSX text.
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**
jsx children child

**Code**

```ts
import * as React from 'react';

const a = <div>}</div>;
const b = <div>></div>;
```

**Expected behavior:**

Typescript throws a syntax error, as `}` and `>` are not valid JSX text characters, as per the JSX spec:

https://facebook.github.io/jsx/

> JSXTextCharacter :
> - SourceCharacter but not one of {, <, > or }

**Actual behavior:**

No errors.

Related - typescript errors on `{` and `<`, but not because they are invalid characters; it instead errors due to the ambiguity in the syntax and it treating them as an unterminated expression and an incorrect tag respectively.

**Playground Link:** https://www.typescriptlang.org/play/?jsx=2&ssl=1&ssc=1&pln=5&pc=1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvMnALxwA8AJsABuAPgC+PAPQCR9Jq3gAjLr2nDhk1fSA

**Related Issues:** 
https://github.com/facebook/flow/blob/master/Changelog.md#01160
https://github.com/facebook/flow/commit/e1d0038042c2cba942ece36f96a0e1bd7fb138bd
https://github.com/babel/babel/issues/11042
https://github.com/acornjs/acorn-jsx/issues/106

I'm bringing this up because flow just made this change, and it seems like a logical one. 

Considering it's almost always going to be a UI bug caused due to typos, it seems like a good idea to error on it. Those that want those characters can be explicit and wrap the character as an expression (`{'>'}`, which is the same thing you do if you want an end of line space).

For reference, this is what now happens when you attempt to parse `}` or `>` in flow:

This code:
```js
function F() {
  return <div>></div>;
}

function G() {
  return <div>{1}}</div>;
}
```
produces the following flow errors:
```
4:   return <div>></div>;
                 ^ Unexpected token `>`. Did you mean `{'>'}`?
8:   return <div>{1}}</div>;
                    ^ Unexpected token `}`. Did you mean `{'}'}`?
```
[flow.org repl](https://flow.org/try/#0MYewdgzgLgBASgUwIbFgXhgJwQRwK4CW2AFAOTYpSkCUA3AFD0BmeYqB4MAYsdTAN70YWBFDyYwMADwATAgDcAfIqkB6OUoYBfRizZQOkgOK8BQkWInSNi-gEYtWtTe1A)

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #36341

This is my first PR for typescript, so please LMK if there's a better way to do this.

### CODE REVIEW

**Comment by orta** [comment]
This is great, I don't have any code recommendations (given the simplicity of the implementation) and the tests look good. I went to check babels implementation details only to find my way back to the linked issue. 

My only question is do you want to add a codefix for these too?

**Comment by bradzacher** [comment]
> only to find my way back to the linked issue

Yeah sorry, I raised issues in acorn, babel and typescript together (and PR'd it into babel) 😄 

> My only question is do you want to add a codefix for these too?

Sure, I'd love to!
Just triple checking my understanding of the codebase is right - is this the correct place to learn about, and add code fixes?
https://github.com/microsoft/TypeScript/tree/master/src/services/codefixes

**Comment by a-tarasyuk** [comment]
> is this the correct place to learn about, and add code fixes?

Yes, it is the right place (:

**Comment by bradzacher** [comment]
Took me a minute to figure everything out, but I got there in the end.
LMK if the codefix implementation looks good.

**Comment by orta** [comment]
This looks perfect, thanks @bradzacher :+1:

**Comment by alloy** [comment]
Nice one, immediately [caught an error](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42279#issuecomment-585263300) in a DT test case 👌

**Pull request merged**
