### PR TITLE
Revert assignability cases in getNarrowedType

### PR DESCRIPTION
**Pull request by orta**
Added in https://github.com/microsoft/TypeScript/pull/39258 - which caused too many breaks to ship, then skipped in https://github.com/microsoft/TypeScript/pull/41849 as the assignability narrowing might still be valuable. However, we've got enough reports that this is probably worth dropping too.

re: https://github.com/microsoft/TypeScript/issues/42225 - https://github.com/microsoft/TypeScript/issues/41808 https://github.com/microsoft/TypeScript/issues/41984

### CODE REVIEW

**Comment by weswigham** [comment]
All of those reports seem to involve `Array.isArray` which was already reverted? Do we have a new test that can demonstrate what the desired behavior that motivates this change is? Since there's no new test with this PR?

**Comment by orta** [comment]
I think this still triggers odd outcomes: 

- all of https://github.com/microsoft/TypeScript/issues/42225 occurred after the revert had happened - this may be because I sent this PR to them prior https://github.com/microsoft/vscode/pull/102413 (I'm gonna check that now)
- https://github.com/microsoft/TypeScript/issues/41984 has a case which seems specific to this assignability change

**Comment by orta** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Review by DanielRosenwasser — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by orta** [comment]
I'm heading out for the night, not sure if getting Anders' sign off is a blocker, if it's not can one of you two merge?

**Comment by DanielRosenwasser** [comment]
Thanks @orta!

**Pull request merged**
