### PR TITLE
Harden Extract Symbol against symbols without declarations

### LINKED ISSUE #21793: TypeError: Cannot read property 'length' of undefined in 'Object.find' during 'getApplicableRefactors'
This issue comes from crash dumps in telemetry. We've tried to de-duplicate issues on a best-effort basis, comparing the sequence of methods called and the command requested while ignoring line numbers.
**TypeScript Version Prefix**: 2.7.1
**VSCode Version** 1.20.0-insider
**command requested**: getApplicableRefactors
**hitting sessions**: 3195
**proportion of all sessions**: 0.01192729390420087
**stack**
```
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:1523:34)
    at recordUsagebySymbol (tsserver.js:81559:41)
    at recordUsage (tsserver.js:81528:36)
    at collectUsages (tsserver.js:81521:25)
    at visitNode (tsserver.js:12595:24)
    at Object.forEachChild (tsserver.js:12958:24)
    at collectUsages (tsserver.js:81524:28)
    at visitNode (tsserver.js:12595:24)
    at Object.forEachChild (tsserver.js:12949:24)
    at collectUsages (tsserver.js:81524:28)
    at visitNode (tsserver.js:12595:24)
    at Object.forEachChild (tsserver.js:12776:24)
    at collectUsages (tsserver.js:81524:28)
    at visitNode (tsserver.js:12595:24)
    at Object.forEachChild (tsserver.js:12807:24)
    at collectUsages (tsserver.js:81524:28)
    at visitNodes (tsserver.js:12604:30)
    at Object.forEachChild (tsserver.js:12796:24)
    at collectUsages (tsserver.js:81524:28)
    at collectReadsAndWrites (tsserver.js:81397:17)
    at getPossibleExtractionsWorker (tsserver.js:80843:38)
    at getPossibleExtractions (tsserver.js:80800:26)
    at Object.getAvailableActions (tsserver.js:80399:35)
    at unknown (tsserver.js:77085:128)
    at getIterator (tsserver.js:1733:23)
    at Object.next (tsserver.js:1728:35)
    at Object.arrayFrom (tsserver.js:2267:32)
    at Object.getApplicableRefactors (tsserver.js:77084:23)
    at Object.getApplicableRefactors (tsserver.js:83299:32)
    at IOSession.Session.getApplicableRefactors (tsserver.js:90156:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:89112:61)
    at unknown (tsserver.js:90355:88)
    at IOSession.Session.executeWithRequestId (tsserver.js:90346:28)
    at IOSession.Session.executeCommand (tsserver.js:90355:33)
    at IOSession.Session.onMessage (tsserver.js:90375:35)
    at Interface.<anonymous> (tsserver.js:91576:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by amcasey**
Fixes #21793

### CODE REVIEW

**Comment by andy-ms** [comment]
Maybe `find` should just handle undefined, as in #21300.

**Comment by amcasey** [comment]
@RyanCavanaugh suggested it would be prudent not to change `find`.

**Comment by amcasey** [comment]
@mhegazy Shall I port this to 2.7?

**Comment by mhegazy** [comment]
We have kept all the telemetry crash report fixes to 2.8. so no need.

**Pull request merged**
