### PR TITLE
Allow null as first argument in JSON.parse method

### LINKED ISSUE #29807: JSON.parse interface should accept null as first argument
JSON.parse() accepts null as valid first argument (null is returned in that case), but TypeScript shows an error, because currently it expects string value to be provided as first argument.

**Search Terms:**
JSON parse null typings

**Code**

```ts
JSON.parse(null);
```

**Expected behavior:**
No linting error is shown

**Actual behavior:**
[ts] Argument of type 'null' is not assignable to parameter of type 'string'. [2345]

**Playground Link:**
https://www.typescriptlang.org/play/#src=console.log(JSON.parse(null)%20%3D%3D%3D%20null)%3B%0D%0A

**Related Issues:**
https://github.com/Microsoft/TypeScript/issues/11842

### PR DESCRIPTION
**Pull request by Yiin**
Fixes #29807

### CODE REVIEW

**Comment by AnyhowStep** [comment]
Wouldn't it be better to add an overload?

**Comment by Yiin** [comment]
Fair enough, even though thats gonna take few more lines and additional variable...
It looks like browsers (only tested Chrome & Firefox) and Node.js are not exactly following the standard.

**Comment by AnyhowStep** [comment]
It's not that they're following the standard. You can call `JSON.parse(null)` and expect to get `null`.

But it's just that, *most of the time*, that's probably not what you want to actually do.

**Comment by sahin52** [comment]
"So, while you can pass non-strings, (except symbol), you really shouldn't."
"You really shouldn't" does not change the language. JS accepts JSON.parse(null) and returns null, typescript should also support that.
For example JSON.parse(undefined) gives error, typescript should not support JSON.parse(undefined) since it really gives error, but null case does not give error.

**Pull request closed without merging**
