### PR TITLE
Adds the TypeScript transformer

### PR DESCRIPTION
**Pull request by rbuckton**
The TypeScript transformer is designed to remove or transform most TypeScript-specific syntax.

This transformer elides TypeScript-specific nodes such as:

* Interfaces
* Type Aliases
* Type Annotations
* Ambient Declarations
* TypeScript-specific modifiers (e.g. `abstract`, `public`, `private`, etc.)
* `implements` heritage clauses on classes
* Type assertions
* Type parameter lists
* Type argument lists

In addition, it transforms TypeScript-specific syntax into compatible down-level syntax, including:

* Decorators
* Async Functions
* Property Declarations
* Parameter property initializers
* Enums
* Namespaces
* Exported declarations inside of a Namespace.

Some TypeScript-specific syntax will remain, specifically import and export declarations that will be handled directly by a later module transformation.

**Related Pull Requests:**
* #6892 - Adds the visitor API foundation for tree transformations.
* #6983 - Adds the Transform Flags concept for tree transformations.
* #6986 - Adds the transformFiles API for tree transformations.
* #6987 - Adds a simplified pretty printer for tree transformations.
* #7191 - **Adds the TypeScript transformer.**
* #7192 - Adds the JSX transformer.
* #7193 - Adds the ES7 transformer.
* #7194 - Adds the ES6 transformer.
* #7206 - Adds the Module transformer.

[Review on Reviewable](https://reviewable.io/reviews/microsoft/typescript/7191)

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/compiler/transformers/destructuring.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBnfbvH-und4f2B15w:-KBBnfbzcAE0K9wOxUpa:399214109) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L23)):*
"highlight" is vague, I can't tell if this is for a future correspondence between transformations or sourcemaps or something else

---

*[src/compiler/transformers/destructuring.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBn_NRyIJ6vLXpmJ96:-KBBn_NRyIJ6vLXpmJ97:2062185107) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L28)):*
This gets a little hard to read. Please use complete sentences.

---

*[src/compiler/transformers/destructuring.ts, line 40 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBo4JQVvbffihcCODh:-KBBo4JQVvbffihcCODi:-2056321548) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L40)):*
I don't see the definition of `inlineExpressions`.

---

*[src/compiler/transformers/destructuring.ts, line 231 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBpMA8zTh0ww25bTN3:-KBBpMA8zTh0ww25bTN4:2130026203) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L231)):*
Cache length, use below

---

*[src/compiler/transformers/destructuring.ts, line 267 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBpaUp510KYI2jlxdb:-KBBpaUp510KYI2jlxdc:1342330262) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L267)):*
You already have `numElements` above

---

*[src/compiler/transformers/destructuring.ts, line 279 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBpf2HWuzYQneCQKEN:-KBBpf2HWuzYQneCQKEO:-768944930) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L279)):*
`numElements`

---

*[src/compiler/transformers/destructuring.ts, line 300 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBthefCsjHfuQ4UoHr:-KBBthefCsjHfuQ4UoHs:-476148923) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L300)):*
These are getting somewhat difficult to reason about. The variable is named `object`, but that's vague enough that I though this was an object literal or binding pattern for whatever reason. 

---

*[src/compiler/sourcemap.ts, line 70 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBqeJSRTFeao0Nh7y6:-KBBqeJSRTFeao0Nh7y7:-1582139307) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/sourcemap.ts#L70)):*
I don't know what this is, leave a hefty comment on what it is and why I need it.

---

*[src/compiler/transformer.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBqx0D1NKBC6eLlA-X:-KBBqx0D1NKBC6eLlA-Y:-138507910) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformer.ts#L29)):*
Should we conditionally transform modules? Or is it better to unconditionally transform just in case?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/typescript/7191)*

**Comment by DanielRosenwasser** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/compiler/transformers/ts.ts, line 210 \[r4\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBxF9xvJ9sZIkOb0iA:-KBBxF9xvJ9sZIkOb0iB:-86851306) ([raw file](https://github.com/microsoft/typescript/blob/0a325ee04c93bc7c505171073937b3b2931ebb20/src/compiler/transformers/ts.ts#L210)):*
Just write "they will be emitted as part of \`transformClassDeclaration\`"

If these constructs are taken care of by `transformClassDeclaration`, shouldn't these branches be unreachable?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/typescript/7191)*

**Comment by rbuckton** [comment]
Review status: 0 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/compiler/transformers/destructuring.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBnfbvH-und4f2B15w:-KBFP2H-_C5KfiJuXo1O:331610400) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L23)):*
This comment originally came from `emitter.ts`. I will update it.

---

*[src/compiler/transformers/destructuring.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBn_NRyIJ6vLXpmJ96:-KBFP7BOJWELWu2ln9lw:331610400) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L28)):*
This comment originally came from `emitter.ts`. I will update it.

---

*[src/compiler/transformers/destructuring.ts, line 40 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBo4JQVvbffihcCODh:-KBFQ4pNn5Rgl6MG7NeH:470355657) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L40)):*
`inlineExpressions` is in `factory.ts`

---

*[src/compiler/transformers/ts.ts, line 210 \[r4\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBxF9xvJ9sZIkOb0iA:-KBFSFbqynhiZOIAgABY:715526554) ([raw file](https://github.com/microsoft/typescript/blob/0a325ee04c93bc7c505171073937b3b2931ebb20/src/compiler/transformers/ts.ts#L210)):*
The members of the class are visited in `transformClassDeclaration`, which includes the constructor. This indicates that the constructor should be elided.

---

*[src/compiler/transformer.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBqx0D1NKBC6eLlA-X:-KBFNsrBbB_B7in5oHSL:-399405719) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformer.ts#L29)):*
We always need to run *some* module transform, even if the transform itself does nothing. This is due to the fact that we fall back to CommonJS if the module kind is unspecified (except when our target is ES6).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/typescript/7191)*

**Comment by rbuckton** [comment]
Review status: 0 of 13 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/compiler/sourcemap.ts, line 70 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBqeJSRTFeao0Nh7y6:-KBiyJe9ag9HP5Jix4hq:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/sourcemap.ts#L70)):*
Done.

---

*[src/compiler/transformer.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBqx0D1NKBC6eLlA-X:-KBiye0VrFx_40XrYC7V:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformer.ts#L29)):*
Done.

---

*[src/compiler/transformers/destructuring.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBnfbvH-und4f2B15w:-KBiyiClBRGVLLD9Dcmf:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L23)):*
Done.

---

*[src/compiler/transformers/destructuring.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBn_NRyIJ6vLXpmJ96:-KBiyiolYq5h6B5xu68v:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L28)):*
Done.

---

*[src/compiler/transformers/destructuring.ts, line 231 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBpMA8zTh0ww25bTN3:-KBiymLPcS6y15VlafNh:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L231)):*
Done.

---

*[src/compiler/transformers/destructuring.ts, line 267 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBpaUp510KYI2jlxdb:-KBiynHrXt3vlVQW3EiB:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L267)):*
Done.

---

*[src/compiler/transformers/destructuring.ts, line 279 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBpf2HWuzYQneCQKEN:-KBiynlKAI4KNZbNnqNq:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L279)):*
Done.

---

*[src/compiler/transformers/destructuring.ts, line 300 \[r1\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBthefCsjHfuQ4UoHr:-KBiypQ0vvIZzdOfuvBC:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/49d2d933796c2a8bdfa55d5e2830a97b3766c9a8/src/compiler/transformers/destructuring.ts#L300)):*
Done.

---

*[src/compiler/transformers/ts.ts, line 210 \[r4\]](https://reviewable.io:443/reviews/microsoft/typescript/7191#-KBBxF9xvJ9sZIkOb0iA:-KBiyt9p3DrEK1EZOon6:-499146009) ([raw file](https://github.com/microsoft/typescript/blob/0a325ee04c93bc7c505171073937b3b2931ebb20/src/compiler/transformers/ts.ts#L210)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/microsoft/typescript/7191)*

**Pull request merged**
