### PR TITLE
Properly handle private/protected members in unions of object types

### LINKED ISSUE #38236: Unexpected intersection type constraint error related to union, generic type and private field
**TypeScript Version:**  3.9.1-rc/4.0.0-dev.20200428

3.9.0-beta seems to be fine.

**Search Terms:** intersection,private,generic,constraint,union

**Code**

```ts
type Type = {foo: string} | {bar: number};

class SyncableObject {
  private foo: unknown;
}

interface SyncableRef<T extends ISyncableObject> {
}

interface ISyncableObject<T = object> extends SyncableObject {
}

type __ValueDescriptorType<
  T extends Type | undefined
> = T extends ISyncableObject
  ? SyncableRef<T>
  : T;
```

**Expected behavior:** No error

**Actual behavior:**

```
Type 'ISyncableObject<object> & T' does not satisfy the constraint 'ISyncableObject<object>'.
  Property 'foo' is missing in type 'ISyncableObject<object> & T' but required in type 'ISyncableObject<object>'.(2344)
```

**Playground Link:** [Playground](https://www.typescriptlang.org/play/index.html?ts=4.0.0-dev.20200429&ssl=1&ssc=1&pln=18&pc=1#code/C4TwDgpgBAKu0F4oG8BmB7dAuKBnYATgJYB2A5gL5QA+KARgIYE4kCuAtnRARQNwBQ-AMYAbBrlxQAyiBJCGdERADydAFYQhwFPyhQwxAG4Ng0DNiisSAaxLoA7iQEVBpUwVQMh0GXIVKAJQhUAB4YKAgAD1MSABNJAElfeUUVdU1gAD4dF343bk9vKCTZFKVVDS0wqCR0dK1sqJj46VL-NMrtZH5c0EgoAH0BgDUGEVYIABEIXCFiMGB0AjhIEN1YCOiIOMkV6ForWODSCFj+bKRwpu2Wkr9Uioz1gH5W+8DgsMz1nBgBIA)

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #38236.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.9

**Comment by DanielRosenwasser** [comment]
@ahejlsberg I guess we shouldn't pull in before cherry-picking, the bot doesn't seem to like that. @weswigham any way to fix this that isn't manual?

**Comment by DanielRosenwasser** [comment]
Ugh, it was a merge conflict...

**Comment by weswigham** [comment]
Pulling in berfore cherry-picking is usually fine so long as the branch wasn't deleted (and then restored) in the meantime, as I think Github  removes the merge reference when the branch is deleted (and has no reason to restore it alongside the branch, as the "new branch" has no active PR).

**Pull request merged**
