### PR TITLE
Feature/add k flag

### PR DESCRIPTION
**Pull request by timothyAgevi**
Fixes #

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
What is kiboko?

**Comment by timothyAgevi** [comment]
> What is kiboko?

tech slack referring to someone/something who/which  adds great value to a technical ecosystem,inspired by Kiboko DAO a dev focused community.(in Swahili  its a homonym refers to hippo or a stick)

**Comment by timothyAgevi** [comment]
plese ellaborate on import mod from "pkg";
mod.default()

**Comment by RyanCavanaugh** [comment]
This feature isn't approved. Closing.

**Pull request closed without merging**
