### PR TITLE
Harden telemetryOnOpenFile

### LINKED ISSUE #36984: TypeError: Cannot read property 'checkJsDirective' of undefined
From https://github.com/microsoft/vscode/issues/91247

**TypeScript Version:**  3.8.2

**Search Terms:**
- updateOpened
- applyChangesInOpenFiles

**Crash**
We saw a user report this crash in VS Code:

```
TypeError: Cannot read property 'checkJsDirective' of undefined
    at ProjectService.telemetryOnOpenFile (tsserver.js:143789:79)
    at tsserver.js:143868:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143868:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144722:46)
    at tsserver.js:146465:88
    at IOSession.Session.executeWithRequestId (tsserver.js:146456:28)
    at IOSession.Session.executeCommand (tsserver.js:146465:33)
    at IOSession.Session.onMessage (tsserver.js:146489:35)
    at Interface.<anonymous> (tsserver.js:147804:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #36984, which we don't have a repro for but the root cause is straightforward enough

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-3.8

**Comment by amcasey** [comment]
I couldn't find an event handler that actually consumes that event - the default one doesn't and I'm pretty sure that's what VS uses.  VS also doesn't act on events with that name.

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-3.8

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-3.8

**Comment by RyanCavanaugh** [comment]
@typescript-bot cherry-pick this to release-3.8

**Pull request merged**
