### PR TITLE
Add support for enum completions

### LINKED ISSUE #40129: Completions: Suggest enum member or literal union Inside switch statement
## Search Terms
suggestions

## Examples
````ts
enum E {
    A,
    B,
}
declare const e: E
switch (e) {
    case /*1*/
}
````

Expected:
Suggest E.A, E.B

## Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #40129

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack-this

**Comment by DanielRosenwasser** [comment]
If I recall correctly, we always prioritize enum declarations in situations like

```ts
enum E { A }

function foo(x: E) {
  if (x == /**/)
}
```

Here, we'll prioritize completions for `E`. Does that logic need to be adjusted at all?

**Comment by Kingwl** [comment]
> src\services\completions.ts 
`getRecommendedCompletion` I guess.

**Comment by Kingwl** [comment]
I think this implementation is terrible. Need more investigate and discussion.

Thank you for your review.
Sorry again

**Pull request closed without merging**
