### PR TITLE
Add NullKeyword to isPartOfTypeNode, mirroring UndefinedKeyword

### PR DESCRIPTION
**Pull request by jakebailey**
While reviewing #52960, I noticed that we have a bunch of lines like `>null : null`, and yet, none like `>undefined : undefined`.

It turns out that we forgot to add `NullKeyword` to `isPartOfTypeNode`. Oops.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Of course, I am now confused about this function in general. We use it like it always traverses parents, but, it short circuits at keywords?

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by jakebailey** [comment]
I'll wait for #52960 before I merge this just to avoid it immediately breaking. Not sure any other outstanding PRs really deal with null, but that one sure does.

**Comment by jakebailey** [comment]
#52984 also has `null : null` in a baseline, I guess we'll see if that gets merged post-design meeting or what.

**Pull request merged**
