### PR TITLE
Don't run scheduled GitHub actions on forks

### LINKED ISSUE #48694: Don't run scheduled GitHub actions on forks
# Suggestion

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Hi,
this repo contains several GitHub actions that run on a schedule. This probably isn't needed on forks and just consumes resources (and energy) needlessly. Moreover, some of the actions need some secrets present and fail on forks, generating daily notifications for everyone trying to open an external PR.

I'd like for the actions not to run on forks.

### PR DESCRIPTION
**Pull request by marekdedic**
Hi,
all the GitHub actions which are run on a schedule probably don't need to run on forks. Some of them even fail to run due to missing secrets. This PR disables all scheduled actions on forks.

Please verify that:
* [ ] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `main` branch
* [x] You've successfully run `gulp runtests` locally
* [ ] There are new or updated unit tests validating the change

Fixes #48694

### CODE REVIEW

**Comment by jakebailey** [comment]
Do we need these tasks on typescript-bot's fork?

**Comment by weswigham** [comment]
Nah, don't think so. It's fork is just a safe place for it to push branches to.

**Review by sandersn — APPROVED** [review]
Good idea. Let's merge this on Monday instead of right before the weekend.

**Comment by andrewbranch** [comment]
This is a syntax error ☹️ https://github.com/microsoft/TypeScript/actions/runs/2222447002

**Comment by jakebailey** [comment]
I think it's because there are two if blocks.

**Comment by marekdedic** [comment]
Ah, sorry, didn't notice the other if block :/

**Comment by andrewbranch** [comment]
No worries, at first I thought something was wrong with all of them. How does GH not automatically check PRs to their own workflow files??

**Pull request merged**
