### PR TITLE
Handle the watch when folders are added/removed/renamed in wild card folder

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes https://developercommunity.visualstudio.com/content/problem/143055/renaming-a-folder-in-a-vs-2017-project-causes-type.html

Multiple changes are needed here to work correctly:
- During watch trigger, do not ignore folders just because they don't have extension
- Its easier to just clear the cache if folder is added/removed instead of going through whole cache and updating the filesystem entries
- Schedule file names update for the configured project instead of doing it right away to process the triggers together
- Opening #19785 to reconsider if directory structure caching

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
Seems good to me, though I don't know this part of the codebase at all. It certainly fixes the issue that was reported.

**Comment by mhegazy** [comment]
@NoelAbrahams can you give tomorrow's `typescript@next` a try, and let us know if u are still seeing issues?

**Comment by NoelAbrahams** [comment]
@mhegazy, happy to do that. How do I do install `typescript@next` in Visual Studio 2017? I see some instructions for VS 2013 and 2015 [here](https://github.com/Microsoft/TypeScript/wiki/Nightly-drops)

**Comment by uniqueiniquity** [comment]
@NoelAbrahams Unfortunately, we haven't kept that page (or that script) up to date for VS 2017.

I think the best approach would be to temporarily make a backup of `C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.6\tsserver.js` and replace it with a copy of `tsserver.js` that you get from running `npm install typescript@next` in some throwaway folder. Wherever you decide to run the npm install, the correct file is at `node_modules\typescript\lib\tsserver.js`.

**Comment by NoelAbrahams** [comment]
@uniqueiniquity, thanks for the tip (great name BTW 😄)

@mhegazy @sheetalkamat using the latest `tsserver.js` I'm no longer able to reproduce the bug. So that appears to be fixed.

I'm still having a problem with the language service with inter-project references. Basicaly, the links in `_references.ts` are not being refreshed when a referenced folder is deleted and regenerated.

Not sure if it's related to this issue.

**Comment by NoelAbrahams** [comment]
I'll try to see if I can reproduce the bug "Cross-project references fail when a folder/referenced `.d.ts` file is deleted, until `_references.ts`  is manually updated".

**Pull request merged**
