### PR TITLE
#13890 Implementing JSX.ElementType support

### PR DESCRIPTION
**Pull request by antanas-arvasevicius**
Implementing  #13890. Code now for review and will add tests if this will be accepted at all.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by antanas-arvasevicius** [comment]
Hi, I've added conformance tests for all scenarios of JSX.ElementType declarations.

**Comment by RyanCavanaugh** [comment]
Per comments in #13890 and offline discussion, I think we want to go in the direction of #14729 as the next step here. I appreciate the work here but #14729 will be a broader solution to the problem, so hopefully we can take action on that at some point based on feedback and use cases.

**Comment by antanas-arvasevicius** [comment]
No problem. Had a good time in exploring typescript internals and it's hard to believe that compiler's code can be read so nicely. It can be used as a teaching literature :-)

**Pull request closed without merging**
