### PR TITLE
Fix incorrect options type to WatchOptions in API

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
We have API usage tests, right? Maybe we should add one?

**Comment by amcasey** [comment]
Have we shipped the incorrect types?  Is this a breaking API change?  Otherwise, LGTM.

**Comment by sheetalkamat** [comment]
This is breaking API change .. Since we did ship this incorrectly from the start

**Comment by sheetalkamat** [comment]
But my limited search doesnt show anyone actually using it

**Comment by sheetalkamat** [comment]
> We have API usage tests, right? Maybe we should add one?

I mean we have baseline tests which do show the fix. I dont think we need more test.

**Comment by sheetalkamat** [comment]
@DanielRosenwasser ok to get this to merge for RC ?

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request merged**
