### PR TITLE
Fix #33732 Consistent relation checking for property symbols with error reporting.

### LINKED ISSUE #33732: Error: Debug Failure. False expression: parameter should have errors when reporting errors
**TypeScript Version:** 3dd7b84ef82f5985d15b20ac0c150302bcdc49d9

**Code**

```ts
interface I1 {
    prop1: string;
}

interface I2 {
    prop2: string;
}

interface I3 extends Record<string, string> {
    prop3: string;
}

type Properties =
    | { [key: string]: never }
    | I1
    | I2
    | I3
    ;


declare const prop1: string;
declare const prop2: string | undefined;

// Error: Debug Failure. False expression: parameter should have errors when reporting errors
function F1(_arg: { props: Properties }) { }
F1({
    props: {
        prop1,
        prop2,
    },
});

// Error: Debug Failure. No error for last overload signature
function F2(_props: Properties) { }
F2({
    prop1,
    prop2,
});
```

**Expected behavior:** Compiles successfully in strict mode

**Actual behavior:** Asserts in strict mode (different asserts for F1 and F2)

Edit: current best guess is that checkRelatedTo should be true and that's why there's no error message.  This seems to be related to excess-property checking (related to the fresh object literal at the call site and the index signature in the union).

### PR DESCRIPTION
**Pull request by jack-williams**
Fixes #33732

### CODE REVIEW

**Comment by jack-williams** [comment]
@typescript-bot perf test this

**Comment by jack-williams** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by jack-williams** [comment]
@typescript-bot perf test this

**Comment by jack-williams** [comment]
Community tests failures are noise.

**Comment by arcanis** [comment]
Fwiw our codebase also exhibits this problem, and I can confirm this commit fixes it.

**Comment by arcanis** [comment]
Do you know if the fix will reach master in time for the stable 3.7?

**Comment by jack-williams** [comment]
> Do you know if the fix will reach master in time for the stable 3.7?

ping'ing @RyanCavanaugh to answer that one

**Comment by weswigham** [comment]
1. This change is super low risk. Because
2. You could replace the _entire body_ of `isPropertySymbolTypeRelated` with the `isRelatedTo(source, addOptionality(getTypeOfSymbol(targetProp), targetIsOptional), reportErrors)` fallback path and have a "correct" answer. The point of the function, and deferral, generally, is to avoid the execution of that fallback path unless absolutely needed, as calling `getTypeOfSymbol` on a `DeferredType` is what is capable of causing the `DeferredType` to blow up for being too large, which we want to avoid as much as possible~
3. Which is why a _much better_ fix is attempting to extract whatever non-error-case logic that yields a different result from the base `isRelatedTo` and have it operate on the un-simplified union/intersection type constituents, or at least minimizing how often that fallbacks needs to be invoked, as those are the cases for which the compiler will be unable to handle large union-within-intersection types.

So while this _works_ it's certainly not what I'd like to see, if at all possible. Specifically, deleting the `undefinedType` case from target seems very wrong - we're iterating over every other type in the deferred union to see if the source is individually assignable to it, and since the target is optional, we need to add `undefined` to that list, which is all that branch (`unionParent && !result && targetIsOptional`) does (and should be unrelated to any reportErrors true/false discrepencies).

If anything, I think, since we added the union coverage union assignment rule that requires the fallback (as extracting that to here is probably a bit hairy), I think a more succinct change may just be
```patch
- if (unionParent && !result && reportErrors) {
+ if (unionParent && !result && source.flags & TypeFlags.Union) {
```

**Comment by jack-williams** [comment]
@typescript-bot perf test this

**Comment by jack-williams** [comment]
Thanks for the detailed write-up @weswigham!

**Comment by bene-starzengruber** [comment]
Hello :)
Is there already a release target for this fix or a known workaround we could take?
This error happens for our reporting to sonar - which sends our coverage straight to zero

**Comment by jack-williams** [comment]
@weswigham @RyanCavanaugh I got the commit history in abit of a pickle so I opened up a new PR with a clean commit here: #36077.

**Pull request closed without merging**
