### PR TITLE
Reset type resolution stack when starting to compute variance

### LINKED ISSUE #53470: Computing variance causes circularity error
# Bug Report

Sometimes we start to compute variances while we're in the middle of computing the types for e.g. a property, and then during variance computation, we try to compute the type for the same property again, so we error on that circularity. However, those circularity errors could be avoided if we were to "restart" when we start computing variances, i.e. for purposes of circularity detection, ignore the types we were previously computing. This becomes a larger problem when the error is or not present depending on the order in which things are declared, as in the example below.

This is a fork of issue #52813, which was fixed for the specific case where the thing that triggers a variance computation is a type assertion, and the fix implemented (#53261) was to defer the type comparability done for type assertions, to delay triggering variance computations that aren't immediately needed.
However, in scenarios where variance computation is triggered in other ways, the circularity error is still present and could be avoided:

### 🔎 Search Terms

variance circularity

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/MYGwhgzhAEBCYCcA8AVAfNA3gWAFDQOgDsBXAWwEIAuY8gIwFMEBuQ6AenegGUB3MAA7QALgHtoCBmVEA3BtCYJRCPGwBqYECXkBeaME0gyDABTCAFgEsIASgB0pMs1WEAYpYYgAJjUeME0HoGIEamFtb2js64AL54XgygiPIAZiREwMKWokT6hsYmAB408MhgRACeaDYliEjlVdEJSZLQaRlZOXkhBcXQonQAVonCNdAQwgiWRADmzEA)

### 💻 Code

```ts
class Bar<T> {
    num!: number;    // Swap to remove error
    Value = callme(this).num;
    Field: number = callme(this).num;
}
declare function callme(x: Bar<any>): Bar<any>;
declare function callme(x: object): string;
```

### 🙁 Actual behavior

Error:  'Value' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)

### 🙂 Expected behavior

No error.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #53470

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot test this
@typescript-bot run DT
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test top100
@typescript-bot test tsserver top100
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Huh, does the previous comment imply that 5.0 is hanging in this repo?

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
So, testing, this seems to _almost_ fix #52892. Compare:

- Before: [Playground Link](https://www.typescriptlang.org/play?jsx=0&ts=4.9.5#code/MYGwhgzhAECCA8AVaBeaA7ArgWwEYFMAnAPmgG8Aoaa6AeluggBcwmBLYc6JgTwAd80APpJo+AB5N86ACYxYqOKTQAGaAF8qNegD1oAdzYgQBgPaEA1gYAW06JnTBT2bNKYB+CluoA3MCEx8AEIALmhEAG5vaGBrIxlQ6ABJdGYwR3xEfnx4XgFTADM4ADoAIXgERGJqrxpGFnZOUsVQSBhy5AkpWXlFWFJKOrq+MEI3RMjo9WgKTQo-QmgwRXR8fTgKMGLY+OKRsfQmYr8A-Ap6IcuaHXcgA)
- After: [Playground Link](https://www.staging-typescript.org/play?ts=5.1.0-pr-53549-16#code/MYGwhgzhAECCA8AVaBeaA7ArgWwEYFMAnAPmgG8BYAKGlugHp6IAXMZgS2HOmYE8AHfNAD6SaPgAezfOgAmMWKjik0ABmgBfanQb0AetADu7ECCMB7QgGsjACxnRM6YOezYZzAPzVtdAG5gIJj4AIQAXNCIANy+tMC2JrLh0ACS6CxgzviIAvjwfILmAGZwAHQAQvAIiMS1PjR0GRxc5UqgkDCVyJLScgpKsKSUDTq0-GCEHsnRsZrQ1FpU1AGE0GBK6PiGcNRgpfGJpeOT6MylAUH41Iyjt3R6nkA)

Some of the errors go away, which is good, but uncommenting that code still seems to change the result. Not sure why but it's an improvement.

**Comment by ye76746483** [comment]
good good

**Comment by vj39995847** [comment]
The results of the perf run you requested are in!

**Comment by gabritto** [comment]
> So, testing, this seems to _almost_ fix #52892. Compare:
> 
> * Before: [Playground Link](https://www.typescriptlang.org/play?jsx=0&ts=4.9.5#code/MYGwhgzhAECCA8AVaBeaA7ArgWwEYFMAnAPmgG8Aoaa6AeluggBcwmBLYc6JgTwAd80APpJo+AB5N86ACYxYqOKTQAGaAF8qNegD1oAdzYgQBgPaEA1gYAW06JnTBT2bNKYB+CluoA3MCEx8AEIALmhEAG5vaGBrIxlQ6ABJdGYwR3xEfnx4XgFTADM4ADoAIXgERGJqrxpGFnZOUsVQSBhy5AkpWXlFWFJKOrq+MEI3RMjo9WgKTQo-QmgwRXR8fTgKMGLY+OKRsfQmYr8A-Ap6IcuaHXcgA)
> * After: [Playground Link](https://www.staging-typescript.org/play?ts=5.1.0-pr-53549-16#code/MYGwhgzhAECCA8AVaBeaA7ArgWwEYFMAnAPmgG8BYAKGlugHp6IAXMZgS2HOmYE8AHfNAD6SaPgAezfOgAmMWKjik0ABmgBfanQb0AetADu7ECCMB7QgGsjACxnRM6YOezYZzAPzVtdAG5gIJj4AIQAXNCIANy+tMC2JrLh0ACS6CxgzviIAvjwfILmAGZwAHQAQvAIiMS1PjR0GRxc5UqgkDCVyJLScgpKsKSUDTq0-GCEHsnRsZrQ1FpU1AGE0GBK6PiGcNRgpfGJpeOT6MylAUH41Iyjt3R6nkA)
> 
> Some of the errors go away, which is good, but uncommenting that `static` block still seems to change the result. Not sure why exactly, but it at least an improvement.

That is intriguing. But the correct behavior is to have the one error at `A.B<A<T>>`, no?

**Comment by jakebailey** [comment]
I don't think so; uncomment the `static` block and note that the error goes away. But, it could be two issues in one.

**Comment by gabritto** [comment]
> I don't think so; uncomment the `static` block and note that the error goes away. But, it could be two issues in one.

I meant to say I think the leftover bug is the fact that the error goes away in the presence of the static block, when it shouldn't go away.

**Comment by jakebailey** [comment]
Ah, yes, correct.

**Review by weswigham — APPROVED** [review]

**Pull request merged**
