### PR TITLE
Update DOM and baselines

### LINKED ISSUE #51361: `lib.d.ts` Updates for TypeScript 5.0
Including

* https://github.com/microsoft/TSJS-lib-generator/
* Outstanding `lib.d.ts` PRs to TS

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #51361

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by DanielRosenwasser** [comment]
Only removals I really saw were:

* https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints
  * `latency`
  * `suppressLocalAudioPlayback` (experimental)
* `oncopy`/`oncut`/`onpaste` and `addEventListener` overloads
  * Seems like these might still be around indirectly

I don't know who will run into these.

I expect some breakages around the more-specific constant values though.

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]
The changes around `copy`/`cut`/`paste` are regressions in that they now map to a more loose `Event` type compared to the original `ClipboardEvent`

**Comment by sandersn** [comment]
Here are the DT failures so far (still waiting on the fourth shard to finish):

### From literal types:
- eventsource
- three
- css-font-loading-module
- webgl2 (but this is a shim which needs to be updated anyway)
- webxr (same)
- event-source-polyfill (same)
- webgl-ext

### deleted types
- react-codemirror (DocumentAndElementEventHandlersMap)
- codemirror

Where are the cut/copy/paste regressions happening?

**Comment by sandersn** [comment]
codemirror's types special-cased DocumentAndElementEventHandlersMap, which is no longer needed.

**Comment by sandersn** [comment]
@DanielRosenwasser the latest commit fixes the type of cut/copy/paste events (but does not move them back into a separate type; I think moving them with the other events was a good thing).

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by DanielRosenwasser** [comment]
webxr has breaks due to every property using numeric literal types, and `blessed` is OOMing, but I can't tell why.

**Comment by sandersn** [comment]
webxr is a shim for exactly the types that are now literal, so it's expected. We'll need to update the shim to match 5.0 types.

I noticed overnight that fhir also OOMed on the nightly. Neither blessed nor fhir are AWS dependents, but fhir has about 4.5 MB of source and blessed 100K + depends on node. That might be enough; our memory usage has definitely increased in 5.0.

**Review by DanielRosenwasser — APPROVED** [review]
We may need to back out the changes to the constants. But let's see how it goes.

**Comment by sandersn** [comment]
If DT/RWC results are indicative, it'll be a big change for a small proportion of people.

**Pull request merged**
