### PR TITLE
Revert changes for template literal types, keeping tests.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
We have reservations about inferring template string types by default, so this PR applies the revert for work discussed at https://github.com/microsoft/TypeScript/issues/42589.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Will probably merge in an hour or two

**Comment by jcalz** [comment]
So #42588 undoes #41891, right?  Just cross-linking them.

**Comment by pedrodurek** [comment]
I hope you can bring it back at some point 🙏

**Comment by DanielRosenwasser** [comment]
Yeah, we had a lot of mixed feedback. I will say about half the team really wanted this and another half felt uneasy about it. We got feedback from existing projects that inferring template literal types by default was questionable at best.

Even though the original concern was about combinatoric explosions of string types, I think in the future we might be open to inferring literal strings when they can be constructed, but not necessarily template string types.

For example

```ts
function foo(x: "a" | "b")
  const str = `hello ${x}`; // "a" | "b"
}
```

but not


```ts
function foo(x: string)
  const str = `hello ${x}`; // `hello ${string}`
}
```

**Pull request merged**
