### PR TITLE
#30697 - Confusing error message for definite assignment assertion without type annotation

### LINKED ISSUE #30697: Confusing error message for definite assignment assertion without type annotation
The following code:

```ts
let foo!;
```

is not valid, because definite assignment assertions only make sense when the declaration actually has a type associated with it. For example:

```ts
let foo!: string | number;
```

Unfortunately the error message is ***bad***

```
A definite assignment assertion '!' is not permitted in this context.
```

because it implies something about where the variable was declared.

Something better might be

```
A definite assignment assertion ('!') cannot be used here because its binding lacks a type annotation.
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #30697

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
cc @DanielRosenwasser 

`binding` is really confusing terminology here IMO. Can we be more directed?

> Definite assignment assertions can only be used along with a type annotation

**Comment by DanielRosenwasser** [comment]
Sure :+1:

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh @DanielRosenwasser 👍

**Comment by RyanCavanaugh** [comment]
Thanks!

**Pull request merged**
