### PR TITLE
fix: also respect compilerOptions.moduleResolution for ending preferences

### LINKED ISSUE #52886: Refactor "Move to a new file" does not honor explicit file extensions
Type: <b>Bug</b>

When working on a ESM project, file extensions of imported paths need to be "explicit". In other words you need to write e.g. `import * from "./somefile.js"` (notice the `.js` at the end).

When the cursor is at a type or class, open the refactor menu (Ctrl+Shift+R) and select "Move to a new file".

image

Notice how the file then is automatically imported:

image

This will only be a valid import if the `--moduleResolution` is **not** set to `node16` or `nodenext`. When you are working on a ESM project, you'll get the following compiler error:

> Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './MyClass.js'?

System info (generated from "Report Issue" button in VSCode):

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 6.0.12-76060006-generic
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-131-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics (16 x 1085)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.05GB (3.39GB free)|
|Process Argv|dipai.code-workspace --crash-reporter-id 736a46a2-ea8f-4a41-bf49-9aa168b1e111|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: server.dipai.no|
|OS|Linux x64 5.4.0-131-generic|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (12 x 2099)|
|Memory (System)|47.06GB (31.80GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-backtix|adi|2.1.0
tsco|alj|1.0.24
vscode-tailwindcss|bra|0.9.7
vscode-toggle-quotes|Bri|0.3.6
vscode-eslint|dba|2.4.0
prettier-vscode|esb|9.10.4
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.96.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.2.0
sqltools|mtx|0.27.1
sqltools-driver-pg|mtx|0.5.1
multi-command|ryu|1.6.0
errorlens|use|3.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30660300
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
The root issue was that TypeScript only looks for user preferences or a `package.json` `"type": "module"` when determining whether to add `.js` to extensions. Some projects don't have either of those set, but still use `"compilerOptions": "node16"` or similar in their TSConfig.

Fixes #52886

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Build failures will be fixed by #53243.

**Comment by Andarist** [comment]
@JoshuaKGoldberg that PR landed shortly after you opened this one, you can sync with main to resolve the issue :)

**Review by andrewbranch — CHANGES_REQUESTED** [review]
`--moduleResolution nodenext` doesn’t mean that extensions are required; it just means that extensions are required in ESM files. What you have in your test are CJS files, where extensions are _not_ required. The refactor should infer from the _existing code_ that extensions are preferred, but it’s incorrect to infer that preference purely based on the module resolution setting. I’m not sure what the issue is in #53244, but most likely the refactor isn’t passing the `resolutionMode` correctly.

**Comment by JoshuaKGoldberg** [comment]
TIL, thanks for the explanation!

> The refactor should infer from the _existing code_ that extensions are preferred

Interesting - looks from 3505fb9 that TypeScript already is.

> most likely the refactor isn’t passing the `resolutionMode` correctly

Hmm, looking through the `SourceFile` type it looks like `impliedNodeFormat?: ResolutionMode` is parsed & set separately from the refactor. So maybe the issue is no longer valid, and since fixed? I can't reproduce bad behavior in the test cases...

**Comment by andrewbranch** [comment]
Looks like the bug was a duplicate of #50710 and already fixed by https://github.com/microsoft/TypeScript/pull/51702.

> Edit: actually, I'm confused - why is this not the case? I thought with moduleResolution: "bundler", it would be expected that Node16/Nodenext compiler options are expected to be .js?

I’m confused about what you’re confused about 😆 `bundler` didn’t change anything about `node16`/`nodenext`. Module resolution strategies that support extensionless paths include:

- Node `require`
- Most bundlers and non-Node runtimes (even in `import`)

In these scenarios, you’re allowed to have an aesthetic preference as to whether you include file extensions on your relative module specifiers, since they work either way. This is what the VS Code preference controls (and what we’ll try to infer from existing usage).

In Node ESM imports, you’re not allowed to omit extensions, so the _preference_ doesn’t come into play. You just have to have extensions, no matter what the VS Code preference says, and if auto-imports or whatever fails to add it, that’s a bug.

Does that clear things up?

**Comment by JoshuaKGoldberg** [comment]
Got it, thanks - that's very helpful!

**Pull request closed without merging**
