### PR TITLE
check initialization of exported block scoped variables

### LINKED ISSUE #5221: Leak let and const declaration check when declarating with export
```ts
const foo = foo; // compile error
export const bar = bar; // should be compile error
function f() {
  const bar = bar; // compile error
}
namespace NS {
  export const bar = bar; // should be compile error
}
```

```ts
let foo = foo; // compile error
export let bar = bar; // should be compile error
function f() {
  let bar = bar; // compile error
}
namespace NS {
  export let bar = bar; // should be compile error
}
```

### PR DESCRIPTION
**Pull request by vladima**
fixes #5221

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by falsandtru** [comment]
Thanks for your fix! :beer::sparkles: 
I change issue #5221. Please also fix let declaration.

**Comment by vladima** [comment]
Fix should already cover all block scoped declaration. I'll test for `let` declaration

**Comment by falsandtru** [comment]
Thanks very much! :rose:

**Pull request merged**
