### PR TITLE
DOM update 2023-03-07

### PR DESCRIPTION
**Pull request by sandersn**
Adds many things that are now available in Safari, but were previously Chrome-only. Unlikely to break anybody except those using shim packages from DT, and I'll update those after merging this.

Since there is a lot of new stuff here, I wanted to get it into 5.1 as early as possible.

### CODE REVIEW

**Comment by sandersn** [comment]
Looks like the shims that are broken are:

- dom-screen-wake-lock
-  w3c-css-typed-object-model-level-1
- dom-webcodecs
- dom-mediacapture-record
- web-animations-js
- webappsec-credential-management

Plus an $ExpectType in use-color-scheme's tests changes order because a type alias to a union of strings changes order.

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot perf test this

**Comment by sandersn** [comment]
Since this is additive-only, I doubt there will be any unexpected breaks. I think it's more effective to estimate the size of the break by looking at number of downloads per month for the packages:

- dom-screen-wake-lock: 36,825
- w3c-css-typed-object-model-level-1: 6,090
- dom-webcodecs: 410,281
- dom-mediacapture-record: 295,838
- web-animations-js: 30,075
- webappsec-credential-management: 506,854

Anybody that upgrades to 5.1 will also need to update these packages. That's a lot of downloads put all together. 

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot perf test this

(I predict that we'll be disappointed with the perf results, since adding this much code is a visible drag on performance.)

**Comment by jakebailey** [comment]
RWC was broken until just now; I'll rerun it.

@typescript-bot test this

**Comment by sandersn** [comment]
user test suite failures: puppeteer has a ts-expect-error where they wanted to use a Chrome-only feature that is now available in Safari.

**Comment by jakebailey** [comment]
Still broken, now actually fixed, I swear

@typescript-bot test this

**Comment by sandersn** [comment]
xstate check time gets 1% better on a change that should not affect checking at all.

**Comment by jakebailey** [comment]
Random noise is still possible, I'm afraid :(

@typescript-bot test this

**Comment by jakebailey** [comment]
@typescript-bot test this

**Comment by jakebailey** [comment]
@typescript-bot test this

**Comment by sandersn** [comment]
RWC tests are fine -- no new failures, just some messages about missing *even more properties*.

**Comment by sandersn** [comment]
@saschanaz Thanks so much for your work in making these types available to Typescript.

**Comment by saschanaz** [comment]
Yay, and also thanks to the people who maintain the data in BCD! @queengooborg @gsnedders

**Pull request merged**
