### PR TITLE
completions: Add "arrow-head" as possible value for isNewIdentifierLocation

### LINKED ISSUE #25691: isNewIdentifierLocation is always set to true inside function call
**TypeScript Version:**  3.0.0-dev.20180713

**Search Terms:** 
- isNewIdentifierLocation
- completions
- suggest

**Bug**
The `completionInfo` request seems to always return `isNewIdentifierLocation` when inside a function call such as:

```ts
console.log(c|)
```

**Expected behavior:**
I believe that `isNewIdentifierLocation` should only be returned when the user is starting to write a arrow function with a parenthesized parameter list, such as:

```ts
(c|)
```

or

```ts
console.log((c|)
```

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #25691
@amcasey Is there any chance that receiving a non-boolean here would break Visual Studio?

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
I think this is quite likely to break VS

**Comment by amcasey** [comment]
Nope, looks like you'd get no completion when a non-Boolean was returned.

**Comment by andy-ms** [comment]
Maybe we should create a new field that's always a string and deprecate the old one?

**Comment by andy-ms** [comment]
@amcasey @mhegazy Opinions on how to expose this?

**Comment by amcasey** [comment]
Adding a new field seems reasonable.  A couple questions:
1) Old versions of VS are going to continue to consume the old field.  Do I understand correctly that the old behavior basically treats `arrow-head` as `true` and that we'll continue to set it that way in the future?
2) I don't think "arrow-head" clearly conveys the meaning given in the jsdoc comment.  Is it even important to callers that the special case is for arrow functions?  Would it be clearer to describe the context (e.g. declaration (currently, `true`), reference (current, `false`), expression (i.e. unknown))?

**Pull request closed without merging**
