### PR TITLE
Ensure moduleType is structured during cloneTypeAsModuleType

### LINKED ISSUE #51099: Namespace import in esm for cjs module described by `any` type leads to debug failure
# Bug Report

Namespace importing a cjs module described with an `any` type from an es module leads to a debug failure.

### 🔎 Search Terms

Debug Failure. Unhandled type 1

### 🕗 Version & Regression Information

- This is a crash in 4.9.0-dev.20221007 and 4.8.4

### ⏯ Playground Link

Can't because it's multiple files.

### 💻 Code

*package.json*

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "module": "index.mjs",
  "dependencies": {
    "typescript": "^4.9.0-dev.20221007"
  }
}
```

*tsconfig.json*

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "strict": true
  }
}
```

*index.mts*

```ts
import * as namespaceImport from "./other.cjs";
console.log(namespaceImport);
```

*other.cjs*

```js
// note: this is described by other.d.cts
module.exports.test = () => 5;
```

*other.d.cts*

```ts
declare const __: any;
export = __;
```

### 🙁 Actual behavior

Running `tsc`:

```
V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:99472
                throw e;
                ^

Error: Debug Failure. Unhandled type 1
    at resolveStructuredTypeMembers (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:49660:30)
    at cloneTypeAsModuleType (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:43230:38)
    at resolveESModuleSymbol (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:43209:36)
    at getTargetOfNamespaceImport (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:42412:28)
    at getTargetOfAliasDeclaration (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:42640:28)
    at resolveAlias (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:42681:30)
    at checkAliasSymbol (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:72981:26)
    at checkImportBinding (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:73096:13)
    at checkImportDeclaration (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:73147:29)
    at checkSourceElementWorker (V:\any-cjs-tsc\node_modules\typescript\lib\tsc.js:73614:28)
```

Note: type 1 is `TypeFlags.Any`

### 🙂 Expected behavior

Should pass type checking.

### Why?

We use the file with `declare const __: any; export = __` in Deno in order to give certain modules an any type. Now when adding `impliedNodeFormat` when creating a source file in order to allow importing npm packages, I had to make this module CJS because it has `export =` and that surfaced this issue.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #51099

### CODE REVIEW

**Comment by weswigham** [comment]
We should probably just `getApparentType` on the module type, to resolve primitives to the structured object type backing them - that way you can pull out `toString` if you really wanted to for some reason.

**Comment by jakebailey** [comment]
That does change:

```diff
import * as exportSymbol from "./exportSymbol.cjs";
->exportSymbol : symbol
+>exportSymbol : { toString(): string; valueOf(): symbol; readonly description: string | undefined; [Symbol.toPrimitive](hint: string): symbol; readonly [Symbol.toStringTag]: string; }
```

But it unfortunately still makes `any` and `unknown` (maybe others I'm not thinking of?) crash unless I keep the structured if/else.

**Comment by weswigham** [comment]
Hm. Yeah, makes sense I guess, since `any` and `unknown` are their own apparent type (while `symbol` and the like have global interface types). Seeing the `ns` in `import * as ns` be of type primitive `string` directly feels wrong given how namespace member hoisting works, while "an object with all the members of a `string` primitive" seems more allowable. Also, honestly, we're doing this to strip signature-y-ness, stripping primitive-y-ness at the same time makes sense. How about something like `const resolvedModuleType = getApparentType(moduleType).flags & StructuredType ? resolveStructuredTypeMembers(getApparentType(moduleType) as StructuredType) : emptyObjectType;`? `export = any` case aside, I think that'd definitely do what we'd want, and I'm not sure I like any other way we could handle the `export = any` case.

**Comment by andrewbranch** [comment]
> In https://github.com/microsoft/TypeScript/issues/51099 the goal is to actually make the import `any`

If that’s the goal, I don’t think it’s a goal we should support. Whatever is the target of `module.exports` (or `export =` in TS syntax) will be the `default` module record when you `import *` that module:

image

So I think it stands to reason if you `export =` something that’s `any`, if you `import *` it you should get something like `{ default: any }`

**Comment by andrewbranch** [comment]
Aside from the crash, our checking for this appears to be super wrong right now.

**Comment by jakebailey** [comment]
Yeah. I'm not super familiar, but it seemed suspect. I just don't know quite what the intended behavior is here.

I could reasonably remove the debug check and allow this code to proceed as it did before, if the answer isn't obvious.

Maybe we need the real example to provide an alternative? @dsherret

**Comment by dsherret** [comment]
It seems doing `var x: any; export = x` is sometimes used to make a module have an `any` type (https://stackoverflow.com/a/31729755/188246 -- though, in this scenario since they're using an ambient module, they could do `declare module 'Foo';`... answer is old, but it's the top SO result on google for "any module typescript"). It's been used for some time in Deno when the types of a module can't be resolved in certain cases in order to have an `any` type, which can be a nice experience for our users to just not worry about typescript in that case. The problem though, is now with our upcomming support for npm packages, we get these errors when resolving to `deno:///missing_dependency.d.ts` as a `.d.ts` file, which has the text `declare const __: any; export = __;`:

```ts
error: TS1259 [ERROR]: Module '"deno:///missing_dependency.d.ts"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
import esmDefault from "npm:@denotest/esm-import-cjs-default"; // note: this is not a real npm package
       ~~~~~~~~~~
    at file:///V:/deno/cli/tests/testdata/npm/esm_import_cjs_default/main.ts:6:8

TS2594 [ERROR]:     This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
    export = __;
    ~~~~~~~~~~~~
        at deno:///missing_dependency.d.ts:2:1
```

Resolving that to instead a `.d.cts` file makes those diagnostics go away, but then surfaces that debug assert. It would be nice if when we can't resolve the types of an npm package (or some other module) we could tell it to resolve to an `any` module type. Perhaps getting rid of those diagnostics would solve it (maybe I could just not surface them)?

> So I think it stands to reason if you `export =` something that’s any, if you `import *` it you should get something like `{ default: any }`

That makes sense to me.

**Comment by jakebailey** [comment]
> It's been used for some time in Deno when the types of a module can't be resolved in certain cases in order to have an any type,

> Edit: For now what I've done is ignored these diagnostics.

Out of curiosity, is it possible to instead ignore the "missing types" error on the module, rather than hiding the errors in the library itself?

**Comment by dsherret** [comment]
> So I think it stands to reason if you export = something that’s any, if you import * it you should get something like { default: any }

@andrewbranch actually, I think this should be the `any` type because if the `any` is an object then then there could be named exports?

image

**Comment by andrewbranch** [comment]
I mean, sure, you can’t prove that `any` for the whole module type is wrong, but that value still conforms to `{ default: any }`. It represents the most specific type we can infer about the module if all we know is there is a `module.exports` of type `any`.

**Comment by dsherret** [comment]
@andrewbranch it could be defined that way, but I think it would be nice if an `any` type were used that it could be anything since using a namespace import property or named import might be valid at runtime. To me, it seems to be more in line with the spirit of `any` for that to not be restrictive.

I also can't think of another way that typescript could be used to allow anything to be used on an import declaration, or is there?

**Comment by andrewbranch** [comment]
I guess you’d have to assign or cast to `any` or a record of `any`. Or, of course, access them off `.default`

**Comment by dsherret** [comment]
I mean, without affecting the importing code (which would solve our case in Deno where we don't have control over the user's code). For another example, someone might be migrating some mixed esm/cjs code to TypeScript and as part of that, they want to mark a cjs module as `any` and they have many modules that import it using namespace and named imports. They might want to keep most of the code as-is, but I don't believe there would be a way to do this unless an `any` type exported from the cjs module allowed for anything to be imported from it.

Anyway, it seems inconsistent for `any` to be a constrained set here, but I'm not too familar with all the edge cases of everything. In my opinion, it being `any` aligns with how `module.export = ...` works where different values have different impacts on the imports and aren't constrained to just `{ default: any }`. I think the `any` type is useful at opting out of TypeScript's type checking and I think it could be useful here for allowing anything to be imported.

**Comment by dsherret** [comment]
Actually, I've discovered that #51321 is actually our main issue in Deno (related to the diagnostics I was getting earlier, but didn't investigate until now), so I don't really mind whatever is decided here for `ModuleKind.ESM` importing `ModuleKind.CJS`.

**Comment by jakebailey** [comment]
I've revied this PR, with the approach suggested in https://github.com/microsoft/TypeScript/pull/51136#issuecomment-1284653262, which makes the type match what we get at runtime; see [`e7aed81` (#51136)](https://github.com/microsoft/TypeScript/pull/51136/commits/e7aed81d331f488633f800839e63b26d01fee7d2#diff-0e0991d13cf86798393bd7d724e6f29d04fa468afaa1e30727147992fcbd8b31).

**Review by weswigham — APPROVED** [review]

**Pull request merged**
