### PR TITLE
forceConsistentCasingInFileNames affects module resolution

### PR DESCRIPTION
**Pull request by ajafff**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Does it? It definitely affects diagnostics, but does it actually change our resolution process?

**Comment by ajafff** [comment]
Actually it doesn't affect resolution, it only affects semantic diagnostics.
I tried `affectsSemanticDiagnostics` and `affectsBindDiagnostics` but that didn't work. `affectsModuleResolution` is the only option that invalidates the cached state of the Program so that these diagnostics are evaluated again.

**Comment by DanielRosenwasser** [comment]
Maybe we should just rename the flag - though, I guess diagnostics are part of the resolution process? @sheetalkamat can give better guidance here, though leaving a comment is cheap and worthwhile.

**Comment by sheetalkamat** [comment]
I think we do want to do module resolution again to ensure the correct file names are picked up so `affectsModuleResolution` seems like correct thing.

**Pull request merged**
