### PR TITLE
use namespaces instead of modules in the codebase

### PR DESCRIPTION
**Pull request by mhegazy**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
@mhegazy does this affect the way the Jakefile needs to patch up the API's .d.ts?

**Comment by mhegazy** [comment]
@DanielRosenwasser, no but that should be the next change.

**Comment by DanielRosenwasser** [comment]
@mhegazy one would think so, but fortunately we have bugs like #3544 to keep everything working.

**Pull request merged**
