### PR TITLE
Enable eslint rules prefer-rest-params and prefer-spread

### PR DESCRIPTION
**Pull request by jakebailey**
This is somewhat involved as our diagnostic handling was all `arguments` based.

I somewhat recently tried to make this consistent in #53193 but apparently didn't go all the way down to the bottom, which this PR necessarily has to do.

There are some places where I chose to just ignore things. I'm unsure if there are better ways to write things but most of those uses also already disabled a lint for using non-arrow functions.

It's possible that there's a perf factor here but I can't seem to observe one, and the callers to the diagnostics stuff already use spread.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Review by sandersn — APPROVED** [review]
Seems good as long as there's no performance difference.

**Comment by jakebailey** [comment]
@typescript-bot new perf test this faster

**Comment by jakebailey** [comment]
Now that I think harder, I wonder if this was written this way to work around #498, which no longer applies given our emit target is no longer ancient.

**Comment by jakebailey** [comment]
> Now that I think harder, I wonder if this was written this way to work around #498, which no longer applies given our emit target is no longer ancient.

Aha, yes, I think I'm on the right track in that thinking: [Playground Link](https://www.typescriptlang.org/play?target=1#code/CYUwxgNghgTiAEYD2A7AzgF3gMyTAtlBgLIhppQDmIAXPFCgJ4DcAUK6JLAhowA4JiSYAFcIIAEpkkEERgCWqABJJM8ALz0mbTtDjxeA+ABF5VFKoVhS5Kgk0MW7EAA8+eLNhEowC1AZgoMBAACgALSzohUXEpNBk5RRQVTAAaeHwyCmo6U3NLeWssu3SAOnLYSjQ6RwBtAF0ASjoANyR5YDZXdxhPb18kgKDQiMwo4TFJaVk-ZMtm+DaO+ABvVngN+FGMUoxA4IBCENwCIhtskFKoPj4IRhDvUGx5FBBgdMqRTJQMNEbGtgAX2cbg8OH6syGwQATOFIvBopM4glZikMOlMrYciYzJQLJhCucSvBylcYFUakwGgslsBVutNttdvsQEcToQSMVqCFMRcyhVyX8AaxAUA)

```ts
export function trace(host: ModuleResolutionHost, message: DiagnosticMessage, ...args: any[]): void;
export function trace(host: ModuleResolutionHost): void {
    host.trace!(formatMessage.apply(undefined, arguments));
}

export function trace2(host: ModuleResolutionHost, message: DiagnosticMessage, ...args: any[]): void {
    host.trace!(formatMessage(message, ...args));
}
```

is in ES5

```ts
export function trace(host) {
    host.trace(formatMessage.apply(undefined, arguments));
}
export function trace2(host, message) {
    var args = [];
    for (var _i = 2; _i < arguments.length; _i++) {
        args[_i - 2] = arguments[_i];
    }
    host.trace(formatMessage.apply(void 0, __spreadArray([message], args, false)));
}
```

But post-modules, we're not emitting in ES5 anymore. This gives me more confidence in this change.

**Comment by jakebailey** [comment]
And, perf is nice and clean.

**Pull request merged**
