### PR TITLE
Reuse type reference directive resolutions

### PR DESCRIPTION
**Pull request by sheetalkamat**
Builds on top of #49738 to reuse type reference directive resolutions

### CODE REVIEW

**Comment by weswigham** [comment]
@sheetalkamat think this needs a sync now that the other PR is merged~

**Comment by sheetalkamat** [comment]
@weswigham yes working on it.

**Comment by sheetalkamat** [comment]
@weswigham done. Ready to review again

**Review by weswigham — APPROVED** [review]
We at least document the parameters to this function in our API, since which types for which parameters are "modern" and "preferred" probably isn't immediately obvious anymore at this point.

**Pull request merged**
