### PR TITLE
suggest fix when using value as type argument

### LINKED ISSUE #28975: Suggest `Did you mean 'typeof Foo'` when using value Foo as a type
```ts
type Foo<T> = {}

const Something = []

type FooSomething = Foo<Something>
//                      ^
//                      Can not find name "Something"               
```

Instead, suggest that `Something` is in the value space and user possibly meant `typeof Something`.
## Search Terms

Error messages, type space, generics 

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by john-patterson**
Fixes #28975.

As discussed in the body of the issue, this only makes a new suggestion when a value appears with as a type argument, like <T>.

So, given the setup from #28975:
`type Foo<T> = {};
const Something = [];`,

This generates the new "error TS2774: 'Something' refers to a value, but is being used as a type argument here. Did you mean 'typeof Something'?" error:

`type SomeFoo = Foo<Something>;`

but a simple aliasing,

`type SomeBar = Something;`

generates the old "error TS2749: 'Something' refers to a value, but is being used as a type here." error.

I couldn't figure out a cleaner way to write the `isIdentifierATypeArgument` function. Currently, I'm checking the failing node's grandparent to see if the current node is in that node's `typeArguments`. This involves some casting and a findIndex, so if there's a better way to divine that with either `meaning` or `node.kind`, that would be preferrable.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
So the original issue outline in the issue showed this:
```ts
type Foo<T> = {}

const Something = []

type FooSomething = Foo<Something>
//                      ^
//                      Can not find name "Something"   
```
The error has since been updated to
```
//                      ^
//                      "Something" refers to a value, but is being used as a type here
```

The validity of suggesting to use `typeof` doesn't seem at all specific to a type argument position. The error message can just universally offer that as a potential idea and the developer can decide whether or not that's what they meant. IMO this should just be an update to the error message text without any conditionalizing based on the position of the identifier.

@weswigham What were your concrete concerns here? It wasn't clear from Daniel's comments

**Comment by weswigham** [comment]
@RyanCavanaugh just that suggesting `typeof X` when `X` refers to a function value isn't likely correct - it's more often you mean the return type of `X`, especially if `X` is being used in a class-like way.

**Comment by john-patterson** [comment]
@weswigham I'm still a little unsure of what you mean.

What I'm understanding as your argument is:

```
class Foo {}
function Bar(): Foo { return {}; }
type Baz = Bar;
```

it's more likely a user wants `Baz` to be equivalent to `Foo` instead of `typeof Bar`?

**Comment by john-patterson** [comment]
As a side-note, it might be useful (on this PR or some other) to add an actual code fix operation for to go along with this error message change. Any objections?

**Comment by weswigham** [comment]
@john-patterson yep, that was my premise. Its probably not _too_ important, it was just a scenario to think about while this was implemented.

**Comment by john-patterson** [comment]
Sorry to have orphaned this PR. To be clear, the issue is now just changing this message:

`"Something" refers to a value, but is being used as a type here`

To be something like:

`"Something" refers to a value, but is being used as a type here. Did you mean 'typeof Something'?`

**Comment by amcasey** [comment]
Closing in favor of #37359.

**Pull request closed without merging**
