### PR TITLE
Make baselines faster by not writing out unneeded files

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Two changes here

The first is to not write out baseline files to `/local` when the content is already identical to what's in `/reference`. Instead, we write out new files when they've changed, and write `.delete` files when the file exists in `/reference` but not in `/local`

The second is to update the `baseline-accept` tasks to simply copy with overwrite, plus treat `.delete` files specially so they delete the destination file. These are now basically "soft by default" so you can run arbitrary subsets of tests and `baseline-accept` without having to worry about nuking your `reference` folder.

Locally, these brought the total time to run the 'conformance' suite from 1m33s to 0m54s. Might even be a bigger gain on non-SSD machines (not sure what travis is using).

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
:bell:

**Comment by weswigham** [comment]
:+1: if you're satisfied with it. I don't see any issues. We could probably do even better if we just wrote all the files-to-delete out to a single manifest file all at once (rather than a smattering of `.delete` files), but that needn't be considered in this PR.

**Comment by mhegazy** [comment]
👍

**Comment by HerringtonDarkholme** [comment]
I have run `jake rutests` locally and cannot get diff by `jake diff`. It seems jake will always remove local baseline and no diff can be produced.

**Pull request merged**
