### PR TITLE
Correct the type of return value of FinalizationRegistry.unregister

### LINKED ISSUE #57919: FinalizationRegistry.unregister should return boolean instead of void
### ⚙ Compilation target

ES2021

### ⚙ Library

es2021.weakref.d.ts

### Missing / Incorrect Definition

`FinalizationRegistry.unregister` is now defined as:

```typescript
    unregister(unregisterToken: WeakKey): void;
```

But it should return a boolean value that is `true` if at least one cell was unregistered and `false` if no cell was unregistered.

### Sample Code

```TypeScript
const obj = {};
const registry = new FinalizationRegistry(() => {});
registry.register(obj, obj, obj);
const removed = registry.unregister(obj); // failed compilation here
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/unregister

### PR DESCRIPTION
**Pull request by jameslan**
Fixes #57919

### CODE REVIEW

**Comment by jameslan** [comment]
@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by jameslan** [comment]
@jakebailey Merge conflicts were solved, please review. Thanks!

**Review by jakebailey — APPROVED** [review]
This seems correct to me, but curious if @sandersn can see anything that may break here. Probably nothing based on the testing.

**Comment by sandersn** [comment]
1. I can't think of anything that would break here except, *maybe* passing unregister itself around.
2. I doubt unregister is used that widely, so it's even less likely to cause a break.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
