### PR TITLE
Enforce keyword order between override and static/async

### LINKED ISSUE #43606: Require either `async override` or `override async` (don't allow both)
# Bug Report

### 🔎 Search Terms

class async override

### 🕗 Version & Regression Information

- This changed between versions __4.2.0__ and __nightly__

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.0-dev.20210408&ssl=1&ssc=1&pln=2&pc=1#code/MYGwhgzhAEBCkFNoG8CwAoaXoFsEBcALAewBMBGACgEoUBfDbXAk0gJhvowfQ1EhgAVBBHzQEAD3wIAdqRjwISNJmwAHAK4AjEAEtg0YgDcEAJ1O7SSSAE8ZBvETJVaKpk1MENpmdAAKpsQ4ukoAdJ4QxCAmlOTUANyM2DxJWJo6+tC29oYm5pZIjqwcrqnunvjevgFBIQjhIlExcYmqWDw8QA)

### 💻 Code

```ts
class Base {
    method1() {}
    method2() {}
}

class Test extends Base {
    public override async method1() {
        return Promise.resolve(1);
    }

    public async override method2() {
        return Promise.resolve(1);
    }
}
```

### 🙁 Actual behavior

No errors

### 🙂 Expected behavior

Possibly error on either `override async` or `async override`.

My understanding (from #43533) is that you prefer requiring a specific modifier order. If that's the case, I would have expected an error here.

### PR DESCRIPTION
**Pull request by andrewbranch**
The order is `static override async`.

Fixes #43606

### CODE REVIEW

**Comment by andrewbranch** [comment]
Some tests were already using `override static`. I have literally no opinion on this, aside from that we should enforce an order, since pretty much everything else has an order enforced.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by Kingwl** [comment]
The current check of modifier order is painful. Are there any possible to map modifiers into some priority. And we just check the order of priority value.

**Comment by andrewbranch** [comment]
I agree @Kingwl, looking at that function, it’s begging to be refactored into something more declarative. Personally I would love to see something like that implemented.

**Comment by DanielRosenwasser** [comment]
@dsherret

**Comment by DanielRosenwasser** [comment]
@nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
Thanks for the heads up @DanielRosenwasser!

**Comment by nicolo-ribaudo** [comment]
Should there also be an order for abstract/override?

https://www.typescriptlang.org/play?ts=4.3.0-dev.20210426#code/IYIwzgLgTsDGEAJYBthjAgQmgpgYVXQQG8AoBBUSGeBAWwEYAKASgC4FqBLAOwHMA3OUrhocRHQBMrDt35CAvqVJUxtFGgwBZAJ4FNAVgQ4AHhBw8AJhmxh8hDGQoB7AG44oULpZwjq4+mZ2TmheQWFVGkQ3Dy8femlguXClIA

**Comment by andrewbranch** [comment]
Yes 🤦

**Comment by Kingwl** [comment]
🤦

**Pull request merged**
