### PR TITLE
Export `getOutputJavaScriptFileName` from tsbuild

### LINKED ISSUE #26410: Expose `getOutputJavaScriptFileName` from tsbuild
## Suggestion

As discussed with @RyanCavanaugh in https://github.com/TypeStrong/ts-loader/issues/815, export the currently internal function `getOutputJavaScriptFileName` from `src/compiler/tsbuild.ts`: https://github.com/Microsoft/TypeScript/blob/fe387cc7f0739256337771e62398a565fbcf82c1/src/compiler/tsbuild.ts#L291-L297

For symmetry, maybe it would make sense also to export `getOutputDeclarationFileName` and possibly `getOutputFileNames`, but those aren’t needed immediately.

## Use Cases

TL;DR: support https://github.com/TypeStrong/ts-loader/issues/815 without duplicating logic from the TS compiler.

When using `program.getSourceFile()` on a `*.ts` file that's part of a project reference, the result describes the `*.d.ts` file built by the composite project (if it’s built). Because there are several compiler options which change where files get emitted (e.g. `declarationDir`), it’s not quite trivial to figure out where the corresponding `*.js` file is. In the issue linked above, we need to read that plain JavaScript file into Webpack in order to take advantage of the fact that project references have already been built.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

---

I'm happy to make the accompanying PR if it sounds good to you all. Since the function will become public, should there be a unit test added for it, or does coverage by existing tsbuild tests suffice?

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #26410 

Waiting to hear:

- Since the function will become public, should there be a unit test added for it, or does coverage by existing tsbuild tests suffice?
- Should we also export `getOutputDeclarationFileName` for symmetry? What about `getOutputFileNames`?
- Any other feedback about implementation, e.g. is `tsbuild.ts` still the right place for this now that it's being exported, should we add JSDoc comments to it (some exported functions have it, others don't)?

### CODE REVIEW

**Comment by andrewbranch** [comment]
Interesting that when I first opened this PR, it generated baselines in `tests/baselines/reference/api/*.d.ts`, and after rebasing against master, the change no longer affects those baselines. Just want to make sure that's intended.

**Comment by sheetalkamat** [comment]
tsbuild API is internal right now and we would want to make sure to expose it right way after reworking on it.
cc: @RyanCavanaugh @DanielRosenwasser

**Comment by weswigham** [comment]
It no longer affects the API baselines because the entire `tsbuild` namespace got marked `@internal` because we didn't intend to expose it, I believe.

**Comment by johnnyreilly** [comment]
I'd much rather rely on TypeScript APIs than duplicate logic in ts-loader if possible. That said, we'll try and be pragmatic; if it's a simple function that's unlikely to change then it's not the end of the world if we duplicate. But that's very much second preference.

**Comment by andrewbranch** [comment]
We need to make a decision for ts-loader (TypeStrong/ts-loader#815) in the next couple days, so any update here from the team would be greatly appreciated. Thanks!

**Comment by andrewbranch** [comment]
Ok, thanks for the update. Feel free to close this if it doesn't make sense.

**Pull request closed without merging**
