### PR TITLE
Revert "Revert "Fixed an issue with contextual type for intersection …

### PR DESCRIPTION
**Pull request by amcasey**
…properties (#48668)" (#50279)"

This reverts commit adf26ffa4b00bda9b35b048b4f1083836451463e.

I'd like to see what the on-demand user tests report for this

### CODE REVIEW

**Comment by amcasey** [comment]
@typescript-bot user test this inline

**Comment by Andarist** [comment]
Is there any other extended test suite that we could run against this? Those `[NewErrors]` issues created by the @typescript-bot have to run against more things, right? 🤔

**Comment by amcasey** [comment]
@Andarist Sorry for the noise - I'm not actually investigating your change specifically - I'm just messing with the infrastructure and wanted to do some validation.

But, yes, it's possible to run individual PRs against the NewErrors infrastructure.  I'll give that a shot once I get some more basic things working.

**Comment by Andarist** [comment]
> @Andarist Sorry for the noise - I'm not actually investigating your change specifically

oh… that’s a bummer… for me 😜

> But, yes, it's possible to run individual PRs against the NewErrors infrastructure. I'll give that a shot once I get some more basic things working.

that’s pretty cool! If u ever get to it - please ping me, i’d be interested in those results

**Comment by amcasey** [comment]
@typescript-bot user test this inline

**Comment by amcasey** [comment]
@typescript-bot test top100

**Comment by amcasey** [comment]
@typescript-bot test top100

**Comment by amcasey** [comment]
@typescript-bot test top100

**Comment by amcasey** [comment]
@Andarist the testing infrastructure is still in flux, but I think the bot comment I didn't delete shows the problem that necessitated the revert.

**Comment by Andarist** [comment]
@amcasey yes, the Redux types were the reason behind the revert - so this is expected. It's good to know though that "only" Redux was affected by this change.

**Comment by amcasey** [comment]
@Andarist Nope, no new information, but you sounded curious. :smile:

The PR-specific tests only cover the top 100 GH repos (by star count) but the next 100 show many more breaks (though most/all related to their consumption of redux, as far as I know).  Mostly, I'm pleased to know that we have a system in place now that could have caught the issue.

**Pull request closed without merging**
