### PR TITLE
Allow to access `exports` from inside a commonjs module

### LINKED ISSUE #15809: Salsa works for imported module members but not within the exporting module
**TypeScript Version:**  2.3.2

**Code**

```js
// ==== main.js ====

const foobar = require('./module');

foobar.foo
foobar.bar

// ==== module.js ====

/** @type {{ spacing: number, perLine: number }} */
const defaults = {
  spacing: 2,
  perLine: 6,
};

/**
 * @param {{ spacing: number, perLine: number }} options
 * @returns {{ spacing: number, perLine: number }}
 */
exports.foo = (options) => Object.assign({}, defaults, options);

/**
 * @param {string} name
 * @param {number} age
 */
exports.bar = (name, age) => {
  return `The person named "${name}" is ${age} years old!`;
};
```

I emulated the expected behavior by adding this at the bottom of `module.js`:
```js
/** @type {{ foo(options: { spacing: number, perLine: number }): { spacing: number, perLine: number }, bar(name: string, age: number): string }} */
const exports = module.exports;
```

#### IntelliSense in `main.js`

Autocomplete should work
image

Hovering over references should work
image

#### IntelliSense in `module.js`
Hovering over the definitions should work
image

Autocomplete should work
image

Hovering over references should work
image

#### IntelliSense in `main.js`

Works just fine in autocomplete
image

Or when hovering over references to imports
image

#### Failing IntelliSense in `module.js`

It works when hovering over the members themselves
image

But doesn't work when trying to get autocompletes
image

Nor when hovering over other references to exports
image

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #15809

Note: The following will no longer work as a constructor function:

```js
exports.f = function() {
    this.x = 1;
}
```

because we expect that `this` will be `exports`, and we get a "property 'x' does not exist" error.

### CODE REVIEW

**Comment by rbuckton** [comment]
> Note: The following will no longer work as a constructor function:
>
>```js
>exports.f = function() {
>    this.x = 1;
>}
>```

Do we think this will be an issue for adoption?

// CC: @DanielRosenwasser, @mhegazy, @bowdenk7

**Comment by andy-ms** [comment]
Bump @DanielRosenwasser, @mhegazy, @bowdenk7

**Comment by mhegazy** [comment]
> Note: The following will no longer work as a constructor function:

I am not sure i understand the issue here.

**Comment by andy-ms** [comment]
Fixed the issue by changing `getContextualThisParameterType` to never contextually type `this` to the source file symbol.

**Pull request merged**
