### PR TITLE
Fix double error on invalid delete of readonly property

### LINKED ISSUE #53082: Double error on invalid delete of readonly property
# Bug Report

### 🔎 Search Terms

operand delete operator double diagnostic error

### 🕗 Version & Regression Information

- This changed between versions 3.9 and 4.0

Before 4.0, we only gave one error here. In 4.0 and above, we give two errors.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.9.5#code/MYGwhgzhAEBiD29oG8C+AoAJgUxNgLtnIgHQB2YAttgNxA)

### 💻 Code

```ts
class Foo {}
delete Foo.name;
```

### 🙁 Actual behavior

Two errors

### 🙂 Expected behavior

One error

### PR DESCRIPTION
**Pull request by galabra**
Fixes #53082

Whenever we detect there's an error of type `The_operand_of_a_delete_operator_cannot_be_a_read_only_property`, we don't need to check for the `The_operand_of_a_delete_operator_must_be_optional` error.

### CODE REVIEW

**Comment by jakebailey** [comment]
This seems reasonable, but, it still needs some sort of test. Potentially one like those in `inconsistentErrorInEditor.ts`?

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Pls add test

**Comment by jakebailey** [comment]
#53082 was fixed by #55449, so this PR is no longer neeeded.

**Pull request closed without merging**
