### PR TITLE
More did-you-mean errors on classes in plain JS

### LINKED ISSUE #45479: No suggestion diagnostic for unchecked JS files in method from class
```js
class Person {
    getFavoriteColor() {

    }
}

const person = new Person();
person.getFavoriteColour();
```

**Expected**

A suggestion diagnostic:

```
Property 'getFavoriteColour' may not exist on type 'Person'. Did you mean 'getFavoriteColor'?
```

**Actual**

No suggestion diagnostic.

In contrast, see this example:

```js
const person = {
    getFavoriteColor() {

    }
}

person.getFavoriteColour();
```

### PR DESCRIPTION
**Pull request by sandersn**
Classes
- that are declared with class declarations or expressions, but not
  constructor functions
- and which have nothing in their heritage clauses

Now provide spelling suggestions on misspelled property accesses.

Because of JS support for assignment-as-declaration, it's still easy to mistakenly declare a property with a typo and not get any suggestions.

I'm not sure this is a great idea; I'm going to run user tests and see how they look.

Fixes #45479

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot test top100
@typescript-bot user test this

**Comment by sandersn** [comment]
I think this is ready to review, but unless I can think of a better way to test it, I don't want to put it in 5.2 beta; right now my testing plan is to have real people to use and complain if the errors are too much.

Any other ideas? I guess I could artificially turn this on for more file types, but I don't know of *any* good source of code with typos in it. Maybe I could download random npm packages.

**Review by andrewbranch — APPROVED** [review]
This seems fairly conservative, and I can’t think of a great way to test it on real code, since typos tend to get fixed eventually.

**Comment by sandersn** [comment]
Yeah, I agree. I'll merge it when 5.3 development starts.

**Comment by sandersn** [comment]
Later: Or, it turns out, just before it ends.

**Pull request merged**
