### PR TITLE
Add node6 to ci

### PR DESCRIPTION
**Pull request by chicoxyzzy**
- Add Node.js 6 LTS to CI
- Drop unmaintained versions of Node.js from package.json

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test ci please

**Comment by chicoxyzzy** [comment]
Is it ok that there is no tests for Node 6 on .NET CI?

**Comment by RyanCavanaugh** [comment]
@dotnet-bot test this please

**Comment by RyanCavanaugh** [comment]
The jobs have to be manually enabled after they're created - figuring out how to get that rolling here. Is there an issue tracking this PR?

**Comment by chicoxyzzy** [comment]
I didn't find any.

Also I've singed CLA. Should I call some bot to check it?

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Pull request merged**
