### PR TITLE
chore: add dateStyle to DateTimeFormatOptions

### LINKED ISSUE #40806: Type '{ dateStyle: string; }' has no properties in common with type 'DateTimeFormatOptions'.ts(2559)
"typescript": "^4.0.3"

How do I resolve the above mentioned typescript error I'm receiving on the following code?:

components/OrderListItem.tsx
```
const newedate = (_date) => {
  const options = {dateStyle: 'medium'}; //{ weekday: 'long', hour: 'numeric'};
  const dateT = new Intl.DateTimeFormat('en-UK', options).format(_date);
  return dateT;
}
```

[![enter image description here][1]][1]

My partial repo is here: https://github.com/TheoMer/next_apollo

  [1]: https://i.stack.imgur.com/1sZb3.jpg

### PR DESCRIPTION
**Pull request by hoop71**
Fixes #40806

This PR adds support for `dateStyle` on [DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

### CODE REVIEW

**Comment by orta** [comment]
This proposal just made it to stage 4, https://github.com/tc39/proposal-intl-datetime-style#status -- which means it's likely to make it into ES2021 spec - adding it to es5 is probably a bad call (because that spec is ~10 years old), I think this should probably live as an interface extension in [`es2020.intl.d.ts`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2020.intl.d.ts)

So I think it's good for us to take it, but I feel like it should probably live in a place which shows just how modern it is 👍🏻

**Comment by hoop71** [comment]
> This proposal just made it to stage 4, https://github.com/tc39/proposal-intl-datetime-style#status -- which means it's likely to make it into ES2021 spec - adding it to es5 is probably a bad call (because that spec is ~10 years old), I think this should probably live as an interface extension in [`es2020.intl.d.ts`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2020.intl.d.ts)
> 
> So I think it's good for us to take it, but I feel like it should probably live in a place which shows just how modern it is 👍🏻

Great! Thanks for all that great information.

**Comment by orta** [comment]
Thanks for the PR @hoop71 - I know it's been a while, I've jsut merged https://github.com/microsoft/TypeScript/pull/41880 which builds on your PR and is a bit more accurate to the full types. This should be available in the next release!

**Comment by hoop71** [comment]
> Thanks for the PR @hoop71 - I know it's been a while, I've jsut merged #41880 which builds on your PR and is a bit more accurate to the full types. This should be available in the next release!

Sweet! Thanks for the solve!

**Pull request closed without merging**
