### PR TITLE
Handle failure to properly resolve type reference directives

### PR DESCRIPTION
**Pull request by uniqueiniquity**
Adding small null check.

Customer reported an issue whereby `file` was undefined or null in a CI scenario but not in a local build. 
The solution for the customer was to set `preserveSymlinks: true`, but this was not clear from the error message.
This change intends to make the error clearer. Suggestions regarding whether this is the proper way to report this error are welcome.

### CODE REVIEW

**Comment by uniqueiniquity** [comment]
@andy-ms  as far as I can tell, `realpath` cannot return `undefined`. So what seems to be happening is that when the symlink is resolved, the file it points to is not present in `Program.filesByName` (forgive the abuse of notation here), and therefore `host.getSourceFile` returns undefined. I've changed the type here to reflect this possibility of returning undefined. What do you think is the best way to handle the scenario?

**Comment by mhegazy** [comment]
@andy-ms can you take a look. we have seen this happen in realworld case, i am not sure i understand the repro, but can you help @uniqueiniquity to get a repro crafted?

**Comment by uniqueiniquity** [comment]
@andy-ms Any updates? Last we spoke, you said you were going to look into this.

**Comment by uniqueiniquity** [comment]
Rebased to pick up changes.

**Comment by uniqueiniquity** [comment]
@andy-ms is this what you thought made sense?

**Comment by mhegazy** [comment]
@uniqueiniquity is this good to go?

**Pull request merged**
