### PR TITLE
Fix string literal object member completions with union contextual type

### LINKED ISSUE #40568: Property completions with quoted names
**TypeScript Version:**  nightly, 4.0.2, 3.9.7 and more

**Search Terms:** completions with quoted property names

**Code**
```ts
interface test {
    id: number;
    propx?: number;
}
interface test2 {
    id: number;
    propy?: string;
}
let a: test = {"id": 4, p}; // typing the letter p gives completions as expected
let b: test = {"id": 4, "p"}; // typing the letter p inside quotes gives completions as expected
let c: test | test2 = {"id": 4, p}; // typing the letter p gives completions as expected
let d: test | test2 = {"id": 4, "p"}; // <--- typing the letter p inside quotes gives no completions, unexpected

// Repeating the same tests without the required property yields different behavior in the last case
interface test3 {
    propa?: number;
}
interface test4 {
    propb?: string;
}
let e: test3 = {p}; // typing the letter p gives completions as expected
let f: test3 = {"p"}; // typing the letter p inside quotes gives completions as expected
let g: test3 | test4 = {p}; // typing the letter p gives completions as expected
let h: test3 | test4 = {"p"}; // <--- typing the letter p inside quotes gives no completions, BUT it does give suggestions based on whatever else exists in the file, unexpected
```

**Expected behavior:**
Completions to be given in the two final places (d & h) and preferably no suggestions

**Actual behavior:**
No completions are given at 'd' and suggestions are given at 'h'

**Comments**
I tried creating a good title and searching for similar ones but I'm not the best at the syntax-lingo.
By completions I mean after I write the first letter, it should probably behave the same when triggering it with a key-combination too though.
Also note the difference between completion and suggestion, in the related issue this seemed to be a confusion.

**Playground Link:**
[Playground Link](https://www.typescriptlang.org/play?ts=4.0.2&ssl=14&ssc=66&pln=14&pc=75#code/JYOwLgpgTgZghgYwgAkgZzMg3gKGf5YAEwC5kQBXAWwCNoBuPAgBygHtmAPAfjMtoY4AvjlCRYiFOjAAmbE3zE+1OlEYFkrDgE9eyDFFABzRiIA2ETHDLTkAXmwAiYo7IAWADSah9ZAHo-VG1mY1QACxQLMHFNZCNgADcINGQENipmKOA2EBS4FIhOZggESCIcKOQaG2TMByxnIldkT2RHZkcff0CwYNCwCOQomOZCXOIUAEcKNnQ4xOTU9MzLbNzkfORC4tKIcsqEGoxkAB9UWrl6xubW5i6AoJCQI3DIyxH5pJS0jKycvIKRRKZQqlmQpHOxzO0kuThc7i87U6vgeAB4ALSYx79QbDaCxUBoCbIaazRbxL7kNhLX6rf5eCggbbAvY4HAPABKEGKcDAOJQaDgVCktRSAHdgAM2BRMAMUFAINNgAqiJp2MUoL1kNpgBAzEQUkRgDAYNAIOAqhAwnAEtkoGNXkN8pgEPkIKJwNB4EhIWAAMzyDRaZhwPT8VSmD3ib0ijBuQMsdU0PQGYyRyoQI7++zYO4onp9Z6OvH20YUxY-FZ8-4bQE7EGVGBZgNXDr3AtPF5yobvfGjQnE0lzcvfZZ-dabZm7fZgozN06++P1PPdbFF7sl2IjmlVtYArZA6egzBhefQ2pLpxt-PIDFY3qd4u90tjIlEKYzYcLFIgamV8doF4ABCACqAAqhCYEQbDkgs+gUEYRi1HuVRuqqOTIGK1qQEk9p6mgKCFMAGApKAjowMAFgMkyh4gkAA)

**Related Issues:** 
Possibly the same
https://github.com/microsoft/TypeScript/issues/35180

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #40568

Done as part of the Pursuit Fellowship workshop 🥳 

Thanks @jenama and @kwong0419!

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Review by sandersn — APPROVED** [review]

**Pull request merged**
