### PR TITLE
Add node_modules cache to travis

### PR DESCRIPTION
**Pull request by weswigham**
This could speed up CI builds a little bit.

See https://docs.travis-ci.com/user/caching/ for more information.

### CODE REVIEW

**Comment by vladima** [comment]
is it possible to explicitly force cache invalidation in cases if our dependencies really should be updated?

**Comment by kitsonk** [comment]
Those authorised on the Travis account can [clear the cache](https://travis-ci.org/Microsoft/TypeScript/caches).

**Comment by weswigham** [comment]
It looks like this cuts about a minute and a half off our travis builds. I think this is good.

**Comment by weswigham** [comment]
@vladima 

We *should* only have to run `npm update` to make sure our deps are updated in the cache.... _however_ since we transitively depend on ourselves,  `npm update` refuses to run. This can be worked around by changing the name in our package.json before running `npm update`, then changing it back... but this still has a downside: only our top-level dependencies get checked. If we add the argument `--depth 999`, theoretically we could catch everything, but when we use depth at all we hit [this npm bug](https://github.com/npm/npm/issues/9473).

If the partial solution is okay (despite the circular dependency hack) I can add it to this PR.

**Comment by weswigham** [comment]
@vladima Look like my new strategy for cache busting works! (Which is "don't cache packages npm has trouble with", like `typescript` or `tslint`). This shaves > 1 minutes off of our builds - should we merge with master now?

**Comment by sandersn** [comment]
:+1:

**Pull request merged**
