### PR TITLE
Reduce rest parameter if not referenced

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes  part of #19182

### CODE REVIEW

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
Friendly Ping @rbuckton 

I notice that there is some node what do not have `original` node even it has been transformed.
Is that expected?

**Comment by Kingwl** [comment]
There's about 170 files. And I have a quick review about 100files.
Basically the problem is the class-related feature.

**Comment by Kingwl** [comment]
Should this behind a flag?

**Comment by DanielRosenwasser** [comment]
Maybe worth mentioning #498

**Comment by Kingwl** [comment]
I have checked more than 130 files. Seems ok but I'm not pretty sure.

**Comment by Kingwl** [comment]
Friendly ping @rbuckton .

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
