### PR TITLE
Do not resolve apparent type of mapped types with a tuple constraint

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/52650

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by weswigham** [comment]
@typescript-bot run dt but new and improved with more response post-backs

**Comment by Andarist** [comment]
How can I see those failures?

**Comment by jakebailey** [comment]
It's nothing you did; just a timeout.

@typescript-bot run dt

**Review by weswigham — APPROVED** [review]
Since DT says this is good, I'm inclined to take it. Since we just shipped 5.0, we have a full release cycle to see if this has any unintended consequences (though I can't think of any offhand, and obvious our tests don't either). :)

**Pull request merged**
