### PR TITLE
Fix ghost errors resulting from out-of-order type checking

### LINKED ISSUE #57429: Incorrect ts7022 error emitted by tsserver (not by tsc)
### 🔎 Search Terms

incorrect ts7022, wrong ts7022, tsserver only error ts7022

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about 'Type System Behavior'.

Summary: `tsserver` emits incorrect TS7022 error, meanwhile `tsc` and `TS Playground` behave as expected.

Steps to Reproduce (NOTE: the error is NOT reproducible in TS Playground):

1. Clone [https://github.com/cleric-sh/repro/tree/phantom-ts7022-error-in-vscode](https://github.com/cleric-sh/repro/tree/phantom-ts7022-error-in-vscode)
2. Ensure switched to branch `phantom-ts7022-error-in-vscode`
3. `npm i`
4. `npm run compile` --> observe no compiler errors
5. Open `index.ts` (in VSCode or another editor utilizing `tsserver`)
6. Error may or may not appear on line 26 on `value` (depending on whether analysis is on first pass or not)
7. Make a change to the file (e.g. add a space) to trigger tsserver to re-analyse the file.
8. Error should definitely be visible now.
9. Restart the TS Language Server and error disappears. Make a change, and error re-appears.

The code in this repro emits an error that is only visible in VSCode whose intellisense is server by `tsserver`.

To compare, the same error is not emitted by `tsc` for the same source and configuration.

I have attempted to raise this issue at:
- https://github.com/microsoft/vscode/issues/195075, and
- https://github.com/typescript-language-server/typescript-language-server/issues/766

In `typescript-language-server` I was informed that the error is actually produced in `tsserver` and so I should raise this with the `typescript` team, so here I am!

### ⏯ Playground Link

https://tsplay.dev/WkqM2N

### 💻 Code

```ts
function Builder<I>(def: I) {

  return def;
}

interface IThing {
  doThing: (args: { value: object }) => string
  doAnotherThing: () => void
}

Builder<IThing>({

  doThing(args: { value: object }) {
    /**
     * ts7022 is shown on 'value' below.
     * 
     * Only shown when func param 'arg' type is declared. Removing the declaration resolves the error.
     * Only shown in vscode. tsc compiles without errors.
     * Only shown on second pass, after a change has been made to the file. Initial type check on load shows no errors.
     * Only shown when noImplicitAny: true
     * 
     * In a more complex file, declaring this function
     * after 'doAnotherThing' prevents the error being
     * displayed.
     */
    const { value } = this.args
    return `${value}`
  },

  doAnotherThing() { },  

})
```

### 🙁 Actual behavior

Error is shown on Line 26: 
```
'value' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

### 🙂 Expected behavior

Behaviour in `tsserver` to match `tsc` (which does not emit the error).

Not sure exactly what *should* happen.... I would imagine one of:
- `this` resolves to `any`, since `ThisType` isn't used, and thus `value` should also be `any`.
- `this` resolve to `IThing`.

But the `ts7022` error shouldn't be displayed.

### Additional information about the issue

The error appears with all extensions disabled.

The error appears with all versions of `typescript` (I have checked all versions since `5.2.2`), including `5.4.0-beta`.

The error does NOT appear in TS Playground: https://tsplay.dev/WkqM2N

I've noted that the error is:

- Only shown when func param 'arg' type is declared. Removing the declaration resolves the error.
- Only shown in vscode. tsc compiles without errors.
- Only shown on second pass, after a change has been made to the file. Initial type check on load shows no errors.
- Only shown when noImplicitAny: true

Also, in a more complex file, declaring this function after doAnotherThing prevents the error being displayed.

There is generally a lot of strange behaviour in this scenario of using 'this' in a non-class context. The repro is non-sensical, but is the simplest reproduction of the same error I could find. 

At least this repro demonstrates:
- the error doesn't seem to make sense. e.g. why wouldn't `value` just be `any` since `this` isn't typed?
- the error is inconsistent:
  - disappearing if (for example) the returned object from `Builder` is assigned to a variable.
  - not emitted by TSC or visible in TS Playground

### LINKED ISSUE #57585: TypeScript Language Server False Positive Error Reporting
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Clone the project `git clone https://github.com/DScheglov/res-test.git`
2. Open the VS Code: `code res-test`
3. Install dependencies (in terminal): `npm i`
4. Open file `./src/index.ts`

The following errors are shown:
image

These errors are false positive:
1. project is configured to use the same typescript compiler as a project. See `.vscode/settings.json`
2. project is compiled successfully via terminal: `npx tsc` (no errors)
3. errors are gone after TS Language Server is restared (`Ctrl + Shift + P` , TypeScript: Restart TS Server)
4. errors go back after any touch of the file (just add a space).

There is not such problem in WebStorm
image
(Sorry, I have to check)

Errors are not displayed in the TS Playground as well:
[Playground](https://www.typescriptlang.org/play?jsx=0&module=1#code/JYWwDg9gTgLgBAbzgJQKYGcCuAbGAaOCAawNSigIBEI4BfOAMyghDgHIABAYwEMoATVNmzAAdsAD0MdAFooGHDDYBuAFCqYATzCo4ABTLoIouAF5EquHFE8QqAFxx0MKGIDmaqzzcPrmEABGZGq0ahraugBSRqIA8gEAVqhc8OZoXND8ADzOrqJuBJiiRKIQAO6iAHxhGaLOhEQAkgzxSSlmcAAUAG482Ji+RSXlogCUjmhYuFnRxq3J+OwAosjIAPoAcrEAKmsAghtrsQBCkUsAwttslWaVlnBaOhAMcL39uqaf7BCJC2xwADIAa8+gM4ABCL6iHDYe5WAD8DR6oN0PHQcFmcV+KVGcLgjjIUE6bBW6y2uwOR1OFyuoxqxnqxGajVEqS6bwGjiGpQq4xQCmm0MCZAIJNWmx2+0OjQ2VxupjuVg2-iCUAAdMB0CyYKgfESOahcVYEUiDXA0X5hVAjcaCeRiaSJRTpbK2HT1LVGU0GHoIOhgDBgN0PuyUY4haq+ZNFFkIyLluLyWs9LEAMqNbaNABqS2ut3uZpuAAY4IjiMj3qN8XBCQ7E5KU+nMzm3fS6vAmQwNhAYEtwFpUy4OhXOXBuSMowKYFl7rl3Hh7mKyZK9mtU9tkDKAOL-AA+CfWSwAsnptgBNNcb7dsVTyxUPCLPEHvCFfNhz-L-RG1pdO-aXzcNh3Kt7ALFE1WwVB8hgAALMwvhLb97V-Y9TwvddAOA-F7nLA13XCHQ4CzPpgH4HhA2MJZyGgLIlhrAAPHVRH4dEPzceVEDgMByJgxw2IAbQAXWUOAMkERwlhE0IPQZeA3lI8jgEo6ioA6WiGKYlinBcdxKk6e5uNgvidPyISCDE3wllUPliJEMiKNEKjmCgWi7y6JBDJg8yIEEOh8MeXQDCgGJbIUhynOgDpQvspTHJUmcrH3X8k0pE4zkuG9EoPP9KRlK57iSx0k0bDNs1zArspSgDrwqlCT3PaqgJvap1FQejIFgUTZIaZogpiABGYcDS5YoeTGfMrGoToGCKFJYoAKk6KsEDxT0O2xNlNGAIR+HmnqWg2kdDTVEAeDAJz9ONY1CUihVnzC2KIqJMyaxUm0rHwq61usWwQy2na9s7bte37TRByJH42hgNUbDsUYTrOi68SsG7VLu+SYuU5zOn4thYdQNhBNIN68U+41vu8P7tuwXb9u1TpIYWNVKfhrgYJ4MQGe9X1-UDYN4dO877WR17nNue7Mbi7Hccpwniec964DJqx5BgTAoBMJB8YISm6E8Pywjajr4G+zs+uMAAmYcwPeEbhgqBcrE84y8jcISOlxnRguMOXrImuAppm0Q5uMQHucMYxIh+JaLC+7rIY6f6abD5p5hSI7FasBGhaJVHxYxxSsegTpPPl6BRmVrr2x+uxE+p2mgZ7PswAHFwGcSGHfszuBs4uvP0ZIyWnpxtVR9L9h8bl0Xy8rimfDrgG6dZduEmZnxWfZzmzb9AMg0NEXe-tfubgL8KVJHseeNFWWien61K9V9XNZr1Adfn6SrFofDTfD72THMM2EdRAWzbEYSCEEIBuC5r1IBnQta-UcGwKOMFRBsDfr4AALFbL+7oJASDgLEIgnFhqcXxog5BqD0GOCwXQOgMk6gQHAdgSB0CfSwPgXYchEAUFoPND4RwMgaE4LUHguATlOKo0cB5Hijh+LsFlnAW+FlEFFQbGmUqLZaG0HoWA1AECoGAL-nAl+iDeGU2odgiuIj8HiKQJIzizs4ByLxr9f4SifK+DqmhRqO4tE6MYXo5hBjf4xGMWQuAWCqERMsbgmx5AJEqSkVxGRTiJ6uMUd5cSlUVw+P+PQbRqhPQBP0aw82ogwkIPYBQvJVjVCiNsXfJJjjnEKPcVk5KK4XRXD8YUhkxSgmlPYXwzBMTrFiPiXYxJDiUnOMnhkrq7TVEUlyT0opTCWGGNCWwN0sTxmqUmc5JpMy2meKWVKKk6Vun5P8es4JMCjHQmELU+pEzGnTKMk4k5Kj6zOguTSPJdDekMNuYMoxRRBAMDEKgfgzy4n7LedIj5L1lHZN+Wlf5PTVBAA)

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR introduces logic that suppresses ghost errors resulting from "inverted" type checking situations where, for example, an API client asks for the type of a symbol in the middle of a section of code, causing type resolution to occur in a different order than when the code is checked from top to bottom in a regular compilation.

Some context on the fix in this PR. In this example

```ts
function builder(def: IThing) {
  return def;
}

interface IThing {
  doThing: (args: { value: object }) => string
  args: { value: number }
}

builder({
  doThing(args: { value: object }) {
    const { value } = this.args;  // Ghost circularity error on "value"
    return `${value}`
  },
  args: { value: 42 }
});
```

a circularity error is reported in the VS Code IDE, but no error is reported with the command-line compiler. The issue is that the IDE language service requests type information on identifiers in the code (likely for semantic classification, but doesn't really matter) _before_ it requests the full list of diagnostics for the code. Specifically, a request is initially made for `getTypeOfSymbol` for the symbol of the `value` identifier. This causes resolution of `this.args`, and to resolve the type of `this`, a request is made for the contextual type of the object literal passed as an argument in the `builder({...})` call. That in turn means we need to resolve the signature for the call, which in turn means resolving the type of the arguments, which in turn means obtaining the type of the `{...}` object literal argument, which further requires resolving the return type of `doThing`, which gets us back to a second `getTypeOfSymbol` call for `value`. And we have a circularity.

However, in the regular top-to-bottom sweep to produce diagnostics, we request resolving the signature of the `builder({...})` call first, which eventually gets us to a `getTypeOfSymbol` for `value`, which in turn requests the contextual type for the object literal. We then see that we're in the process of resolving the signature of the containing `builder({...})` call, and therefore we simply report that there is no contextual type. And thus no circularity.

With the fix in this PR, we temporarily reset the resolution stack during `getResolvedSignature` calls. In the IDE scenario this means that the first call to `getTypeOfSymbol` is no longer reflected on the resolution stack, so resolution can proceed in the same manner as the regular case. Following that, the outer `getTypeOfSymbol` call notices that a resolved type has already been recorded, so it simply proceeds with that. No circularity, and all is well.

Fixes #57429.
Fixes #57585.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test it

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
You should be able to pull the tests from Andarist's comments, i.e. copy these ones: https://github.com/microsoft/TypeScript/pull/58323/files#diff-8814cff6472937bf39f151270b038e16552d0896cc67cb5c5382aa432c909acf

I tested locally by pulling this code into my branch and it seemed to work!

**Comment by DanielRosenwasser** [comment]
Those webpack breaks are kind of weird.

@typescript-bot test top800

**Comment by ahejlsberg** [comment]
@typescript-bot test it

**Comment by ahejlsberg** [comment]
> Those webpack breaks are kind of weird

With the temporary resetting of the resolution stack, it is now possible for `getReturnTypeOfSignature` to resolve the same signature twice in a nested manner. When that happens we should always keep the result of the first resolution to complete, and that's now happening with the latest commit.

**Comment by Andarist** [comment]
Could you also create a playground for this one?

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
The new `redux` error is another example of a ghost error. Without this PR, the error doesn't show in command line builds, but comes and goes when viewing/editing the file in the IDE. With this PR, the error is consistently reported in command line builds and the IDE.

**Comment by ahejlsberg** [comment]
The new `webpack` [error[(https://github.com/microsoft/TypeScript/pull/58337#issuecomment-2080879375) looks legit, the `internalApply` function has no type annotation and is indirectly recursively called in a `return` statement.

**Comment by Andarist** [comment]
I verified that this fixes the other repro that I posted in #57585 (see [here](https://github.com/microsoft/TypeScript/issues/57585#issuecomment-1975323778)). To be honest, it's kinda the same repro as the one that you already have here as [tests/cases/fourslash/issue57585.ts](https://github.com/microsoft/TypeScript/pull/58337/files#diff-aab989aac4782ac6953ca0fc86402767155e06bcdb47cbafb4d87196b0a684e0)  - it just excercices a different path leading to a problem. 

I also checked `effect`'s case reported in #57585 and this **doesn't** fix that problem as far as I was able to verify it manually (cc @mikearnaldi ). So after all... it was worth digging into it :D (cc @jakebailey ). I'll reduce this to a minimal repro case over the weekend and post here.

**Comment by mikearnaldi** [comment]
> I verified that this fixes the other repro that I posted in #57585 (see [here](https://github.com/microsoft/TypeScript/issues/57585#issuecomment-1975323778)). To be honest, it's kinda the same repro as the one that you already have here as [tests/cases/fourslash/issue57585.ts](https://github.com/microsoft/TypeScript/pull/58337/files#diff-aab989aac4782ac6953ca0fc86402767155e06bcdb47cbafb4d87196b0a684e0) - it just excercices a different path leading to a problem.
> 
> I also checked `effect`'s case reported in #57585 and this **doesn't** fix that problem as far as I was able to verify it manually (cc @mikearnaldi ). So after all... it was worth digging into it :D (cc @jakebailey ). I'll reduce this to a minimal repro case over the weekend and post here.

I don't seem to be able to reproduce the same issue anymore, but given it was sporadic I believe you :) hope you'll manage to get a repro which is minimal enough

**Comment by ahejlsberg** [comment]
> I don't seem to be able to reproduce the same issue anymore

FWIW, I haven't been able to reproduce it either.

**Comment by Andarist** [comment]
I could try to minimize this further if requested - I think it's pretty minimal already though (given the complexity of the original: Effect's codebase 😉 ):
```ts
/// <reference path="fourslash.ts" />

// @strict: true
// @target: esnext
// @lib: esnext

//// declare const EffectTypeId: unique symbol;
////
//// type Covariant<A> = (_: never) => A;
////
//// interface VarianceStruct<out A, out E, out R> {
////   readonly _V: string;
////   readonly _A: Covariant<A>;
////   readonly _E: Covariant<E>;
////   readonly _R: Covariant<R>;
//// }
////
//// interface Variance<out A, out E, out R> {
////   readonly [EffectTypeId]: VarianceStruct<A, E, R>;
//// }
////
//// type Success<T extends Effect<any, any, any>> = [T] extends [
////   Effect<infer _A, infer _E, infer _R>,
//// ]
////   ? _A
////   : never;
////
//// declare const YieldWrapTypeId: unique symbol;
////
//// class YieldWrap<T> {
////   readonly #value: T;
////   constructor(value: T) {
////     this.#value = value;
////   }
////   [YieldWrapTypeId](): T {
////     return this.#value;
////   }
//// }
////
//// interface EffectGenerator<T extends Effect<any, any, any>> {
////   next(...args: ReadonlyArray<any>): IteratorResult<YieldWrap<T>, Success<T>>;
//// }
////
//// interface Effect<out A, out E = never, out R = never>
////   extends Variance<A, E, R> {
////   [Symbol.iterator](): EffectGenerator<Effect<A, E, R>>;
//// }
////
//// declare const gen: {
////   <Eff extends YieldWrap<Effect<any, any, any>>, AEff>(
////     f: () => Generator<Eff, AEff, never>,
////   ): Effect<
////     AEff,
////     [Eff] extends [never]
////       ? never
////       : [Eff] extends [YieldWrap<Effect<infer _A, infer E, infer _R>>]
////       ? E
////       : never,
////     [Eff] extends [never]
////       ? never
////       : [Eff] extends [YieldWrap<Effect<infer _A, infer _E, infer R>>]
////       ? R
////       : never
////   >;
//// };
////
//// declare const succeed: <A>(value: A) => Effect<A>;
////
//// gen(function* () {
////   const a = yield* succeed(1);
////   const b/*1*/ = yield* succeed(2);
////   return a + b;
//// });

verify.quickInfoAt("1", "const b: number");
verify.getSemanticDiagnostics([]);
```

**Comment by ahejlsberg** [comment]
I can confirm that @Andarist's Effect repro [here](https://github.com/microsoft/TypeScript/pull/58337#issuecomment-2081164425) reproduces for me and is fixed by this PR.

**Comment by Andarist** [comment]
I'm confused. I posted this repro after testing it on this very branch - it doesn't pass:
```
  1) fourslash tests
       tests/cases/fourslash/issue57585-2.ts
         fourslash test issue57585-2.ts runs correctly:

      AssertionError: At marker '1': quick info text: expected 'const b: any' to equal 'const b: number'
      + expected - actual

      -const b: any
      +const b: number
      
      at _TestState.verifyQuickInfoString (src/harness/fourslashImpl.ts:1863:16)
      at _TestState.verifyQuickInfoAt (src/harness/fourslashImpl.ts:1835:14)
      at Verify.quickInfoAt (src/harness/fourslashInterfaceImpl.ts:272:20)
      at eval (issue57585-2.js:72:8)
      at runCode (src/harness/fourslashImpl.ts:4613:9)
      at runFourSlashTestContent (src/harness/fourslashImpl.ts:4571:5)
      at runFourSlashTest (src/harness/fourslashImpl.ts:4554:5)
      at Context.<anonymous> (src/testRunner/fourslashRunner.ts:59:39)
      at processImmediate (node:internal/timers:478:21)
```

I confirmed now that I am at the correct commit and all, rerun it and it still doesn't pass 😅 

```
> git rev-parse HEAD
abf40126d08dd8cdd1821273fdf0a258a2ec4cfe
```

**Comment by mikearnaldi** [comment]
After fiddling for a while I can confirm this still occurs, more reliably when you specify a return type

Screenshot 2024-04-28 at 10 39 38

**Comment by Andarist** [comment]
@ahejlsberg thanks ❤️

**Comment by ahejlsberg** [comment]
Ok, _now_ it fixes the Effect repro. Sorry for the confusion.

**Comment by ahejlsberg** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot test it

**Comment by mikearnaldi** [comment]
> Ok, _now_ it fixes the Effect repro. Sorry for the confusion.

Thank you immensely!! This makes a lot of difference for Effect, I will test this tomorrow just to double check that in the large codebase nothing wierd happens.

**Comment by adrian-gierakowski** [comment]
Will this land in 5.4.x or do we need to wait for 5.5 to benefit from it? Thanks!

**Comment by Andarist** [comment]
I doubt it. TS usually only backports fixes for recent regressions or other critical things. 

You don’t have to wait till 5.5 though. Once this gets landed a nightly version will be released within 24h from the merge and you can start using it almost immediately

**Comment by jakebailey** [comment]
Looking at the breaks, the webpack one does look like a preexisting circularity, but the redux example doesn't look like one. Any clue what's going on there?

**Review by weswigham — APPROVED** [review]
Looks like we're generalizing a mechanism we already used for this issue in variance annotations to signature resolution (and handling the nested calls better by using `??=` instead of `=` at the cache assignments). Seems OK, but maybe we should abstract this concept into a helper like `doOutsideOfCurrentResolutionContext` so it's easier to apply to more entrypoints as-needed? Part of me doubts that signature resolution and variance annotations are the only two places we'd ultimately like to start checking "from the top" regardless of entrypoint (class base type calculations? decorator resolution? apparent member lookup?).

**Comment by ahejlsberg** [comment]
@jakebailey See my comment about the Redux change [here](https://github.com/microsoft/TypeScript/pull/58337#issuecomment-2081113290).

**Comment by jakebailey** [comment]
Oops, missed both in the comment noise, though I can't say I see what the circularity is in that particular line...

**Comment by ahejlsberg** [comment]
> Seems OK, but maybe we should abstract this concept into a helper like `doOutsideOfCurrentResolutionContext`...

Hmm, not so sure about that. We have just two places where we do it and all that needs to be saved/restored is the `resolutionStart` variable. Also, the saving/restoring is conditional, so doesn't lend itself all that well to a function with a callback.

**Comment by ahejlsberg** [comment]
> Oops, missed both in the comment noise, though I can't say I see what the circularity is in that particular line...

I'm not sure, but it's really an orthogonal issue. It was an error before as well, just not consistently so. If there's something we can do to not make it an error, then that's probably a different feature request.

**Review by jakebailey — APPROVED** [review]

**Comment by ssalbdivad** [comment]
So with some help from @Andarist and @jakebailey, it seems like it was this change that was responsible for the performance hit in https://github.com/arktypeio/arktype?

```ts
{
    "checkTime": 9.68,
    "types": 483415,
    "instantiations": 2629152
}

devDependencies:
- typescript 5.5.0-dev.20240429
+ typescript 5.5.0-dev.20240430

{
    "checkTime": 12.2,
    "types": 514846,
    "instantiations": 2819487
}
```

**Pull request merged**
