### PR TITLE
Update LKG to 4.8.4

### PR DESCRIPTION
**Pull request by jakebailey**
Created by doing:

```
git fetch upstream
git checkout v4.8.4 -- lib
```

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Why 4.8.4 instead of just the current one?

**Comment by jakebailey** [comment]
What do you mean? That is the current stable, right?

I'm just keeping up with having LKG and node_modules match.

**Comment by DanielRosenwasser** [comment]
You can create an LKG from any snapshot in time - we can make it just whatever's in `main` today. But 4.8.4 is fine I suppose.

**Comment by jakebailey** [comment]
The last time that we updated LKG, it was to TS 4.5, after then, it's just been me doing stable releases and matching node_modules. I personally don't think it's a great idea to bump LKG up past a stable release unless we really have to. If we only compile with a prerelease version of TS, that makes it frustrating for me to build the project for the module transform where I have to either use the version of TS shipped with ts-morph, or patch it and assume that the AST hasn't changed in an incompatible way, which I already had to deal with for 4.8.

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
