### PR TITLE
[Experiment] Direct imports

### PR DESCRIPTION
**Pull request by a-tarasyuk**
@jakebailey https://github.com/microsoft/TypeScript/issues/51443#issuecomment-1312005087 Curious about how direct imports impact performance

### CODE REVIEW

**Comment by jakebailey** [comment]
Impressive; this one is definitely tricky as there are still cycles. There is tooling to help with that.

FWIW you can just start using Object.entries unconditionally; the new target is ES2018 so a lot more is fair game, though I haven't made an issue for that and we will need to performance test as we suspect that our hand written ones are faster.

**Comment by a-tarasyuk** [comment]
> this one is definitely tricky as there are still cycles. 

Yep :(. I decided to start by converting to direct imports, the second step should be to resolve the circular dependencies.

> There is tooling to help with that.

I know about madge, maybe there is a better tool...

**Comment by jakebailey** [comment]
Madge is the one I had tried, but I forgot the name and while searching I found https://github.com/Soontao/cycle-import-check

Funnily, the most reliable one I found was running rollup on the codebase, since it complains about it too.

Maybe using type imports would help the tooling as well.

**Comment by jakebailey** [comment]
But seriously, you further than I did. I'm really shocked you got the tests to pass and tsc to run. I gave up and started working on other stuff instead...

**Comment by a-tarasyuk** [comment]
`Debug` has several circular uses

`core.ts <-> debug.ts`
`debug.ts <-> version.ts`

Can we move _`asserts`_ to a new `assert.ts` module? 

https://github.com/microsoft/TypeScript/blob/b553affd5cd58df10dae461091efb97b9a829aea/src/compiler/debug.ts#L135-L142

https://github.com/microsoft/TypeScript/blob/b553affd5cd58df10dae461091efb97b9a829aea/src/compiler/debug.ts#L150-L208

**Comment by jakebailey** [comment]
My Debug PR (#51455) does mend some of this, though it's not final at all.

I'm not really sure how far we want to stretch debug; I think that for now the best we should try to do is to make `debug` come first and then ensure it doesn't call anything. My other PR pulls deprecation code out into the deprecation compat file, which I think is the main blocker and I'll just go pull that into its own PR instead.

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
If this is to be trusted, then it's a tiny win. I was expecting roughly no change since esbuild devirtualizes everything already in the current bundle. But maybe there's more being done and we can diff the two tsc.js files.

**Comment by a-tarasyuk** [comment]
> then it's a tiny win

Yep, `-1%` is not a big win. That's what I wanted to check. Maybe using _`_namespaces`_ is cleaner and without significant performance loss.

**Comment by jakebailey** [comment]
My general feeling (and I think this is shared) is that the namespace stuff is really just a temporary hack and we'd like to have direct imports anyhow.

**Comment by jakebailey** [comment]
Are you planning on reopening this again somewhere else? I am wanting this change, though I don't know when we will "click the button" so I understand that it'd be a maintenance pain until then.

**Comment by a-tarasyuk** [comment]
Honestly, I just wanted to check the performance impact. These changes are difficult to maintain and after merging this PR https://github.com/microsoft/TypeScript/pull/51565, these changes will be completely useless as they will affect all imports in all files. I think it would take less time to make all the changes from scratch than to fix merge conflicts :).

**Comment by jakebailey** [comment]
No problem! I appreciate that you showed it was possible, at least.

**Comment by a-tarasyuk** [comment]
@jakebailey Write me when you decide to do this migration and I'll try to restore these changes.

**Pull request closed without merging**
