### PR TITLE
Fix WeakSet interface

### LINKED ISSUE #14840: WeakSet<T> should be WeakSet<T extends object>
**TypeScript Version:**  nightly (2.3.0-dev.20170324)

**Code**

```ts
const s = new WeakSet<string>();
s.add("foo");
```

**Expected behavior:**

An error, since this will fail at runtime.

**Actual behavior:**

No error.

### PR DESCRIPTION
**Pull request by falsandtru**
Fixes #14840 

cc @andy-ms

### CODE REVIEW

**Comment by falsandtru** [comment]
cc @andy-ms

**Comment by andy-ms** [comment]
@mhegazy @rbuckton Any idea what PR fixed it so you could have a one declaration one a type parameter and one without?

**Comment by falsandtru** [comment]
You mean lodash definitions?

**Comment by andy-ms** [comment]
I meant a pull request to the TypeScript compiler, that would allow the `lib.d.ts` definition to use `WeakSet<T extends object>` and lodash to use `WeakSet<T>`. Just making sure we've officially fixed this.

**Comment by falsandtru** [comment]
Sorry, I missed to find `WeakSet` because page loading is not complete. I'll fix lodash definitions.

**Comment by andy-ms** [comment]
That may cause errors for people using lodash with earlier TypeScript versions though. We have no way of changing these both at the same time unfortunately.

**Comment by falsandtru** [comment]
I made https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21273. This patch don't have unfavorite incompatibility.

**Comment by mhegazy** [comment]
I think we need a fix to allow defaults on only one declaration as @andy-ms noted in https://github.com/Microsoft/TypeScript/pull/19756#issuecomment-342173087

**Comment by falsandtru** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21273 is merged. So we can merge this PR.

**Comment by andy-ms** [comment]
The problem is with `interface WeakSet<T> { }` at the bottom of `lodash/index.d.ts`. If you change that to `interface WeakSet<T extends object> { }` right now you'll get a compile error. But if this PR went in then it would *have* to be written that way to stay compatible, but then it wouldn't work on old TypeScript versions.

**Comment by falsandtru** [comment]
Ah, I missed it. I'll fix it too. Thanks.

**Comment by falsandtru** [comment]
That definition specifies TypeScript 2.2: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts#L13. So it should make no error.

**Comment by falsandtru** [comment]
Ah not correct. I got an error: `All declarations of 'WeakSet' must have identical type parameters.` This is difficult.

**Comment by falsandtru** [comment]
Seems like it is impossible to fix WeakSet interface without breaking changes. We can never fix WeakSet?

**Comment by mhegazy** [comment]
We need a fix for https://github.com/Microsoft/TypeScript/issues/20018 first.

**Comment by falsandtru** [comment]
Now can you merge?

**Pull request merged**
