### PR TITLE
fix(58584): formatJSDocLink shouldn't introduce a trailing space when non link text.

### LINKED ISSUE #58584: `getTextOfJSDocComment` introduces a space in JSDoc comments
### 🔎 Search Terms

getJSDocTags
getTextOfJSDocComment

### 🕗 Version & Regression Information

5.5.0-beta and previous.

### ⏯ Playground Link

https://stackblitz.com/edit/gettextofjsdoccomment-dbm6rj?file=main.ts,package.json

### 💻 Code

```
import ts from 'typescript';

const filename = 'example.ts';
const code = `

/** 
 * 
 * @see {@link entry}
 */
class Foo  {};
`;

const sourceFile = ts.createSourceFile(
  filename,
  code,
  ts.ScriptTarget.ESNext,
  true
);

const visitNode = (node: ts.Node) => {
  ts.forEachChild(node, visitNode);
  const tags = ts.getJSDocTags(node);
  if (tags.length) {
    tags.forEach((tag) => {
      console.log('> ', ts.getTextOfJSDocComment(tag.comment));
    });
  }
};

ts.forEachChild(sourceFile, visitNode);
```

### 🙁 Actual behavior

`getTextOfJSDocComment` returns `{@link entry }`. Notice the trailing space. 

### 🙂 Expected behavior

`getTextOfJSDocComment` should return `{@link entry}`, without introducing a space. 

### Additional information about the issue

_No response_

### PR DESCRIPTION
**Pull request by JeanMeche**
fixes #58584

### CODE REVIEW

**Comment by JeanMeche** [comment]
@microsoft-github-policy-service agree

**Comment by JeanMeche** [comment]
If anyone come over here, I'd appreciate some help to fix the formating of `tests/baselines/reference/linkTagEmit1.js`, thank you in advance.

**Comment by jakebailey** [comment]
> If anyone come over here, I'd appreciate some help to fix the formating of `tests/baselines/reference/linkTagEmit1.js`, thank you in advance.

Looks like a line ending problem. Did you use the baseline-accept task or did you manually modify the baseline?

**Comment by JeanMeche** [comment]
I changed the file manually.

**Comment by jakebailey** [comment]
Yeah, you shouldn't do that. Run the tests then run `hereby baseline-accept`. https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#managing-the-baselines

**Comment by JeanMeche** [comment]
@jakebailey Thanks, it looks better now !

**Review by jakebailey — APPROVED** [review]
This seems correct to me. @sandersn may have a thought here.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
I was briefly worried about the treatment of spaces with http:// but there are lots of tests of that already.

**Pull request merged**
