### PR TITLE
Allow inlined-value usage of type-only const enums

### LINKED ISSUE #40344: Allow to import both type entity and value entity by `import type { ConstEnumType } from ..`
## Search Terms

const enum, import, importsNotUsedAsValues

## Scenario

I am a library developer, and there is a really large `types.ts` file in my project, which contains many `interface`, `type`, and `const enum`, defining a large part of types of the project, just like you do (`typescript/src/compiler/types.ts`).

Recently I turned on the compiler option `importsNotUsedAsValues`, and found some problems about `const enum`.

```ts
Original fileA.ts

import {
    TypeA, TypeB, TypeC,
    ConstEnumD, ConstEnumE,
} from './types.ts';

------------------

Current fileA.ts

import type {
    TypeA, TypeB, TypeC,
} from './types.ts';
import {
    ConstEnumD, ConstEnumE,
} from './types.ts';
```

Because the entities of `enum` belong to both type scope and value scope, I have to import them separately if I want to use them as values.

Now I have to separate the import of type `const enum` from a lot of names file by file, which is really a lot of work.

What's worse, after turning on `importsNotUsedAsValues`, TypeSciprt unnecessarily write `require('./types.js')` into `fileA.js` though the generated code did not access any property of `require('./types.js')`. In other words, it makes `types.ts` seems to have side effects. And this feature may affect the file reference relation of the project and lead to incorrect Rollup order.

In my mind, accessing the `const enum` entity in value scope is a kind of special behavior and is something that will be replaced in compile-time. There should be a way to import both type entity and value entity of `const enum` from a file without really requiring the file, especially when the file really has side effects.

## Solution

There are 2 ways to solve this problem:

1. import both type and value for `const enum` using `import type`

```ts
import type { ConstEnumA } from './types';
//       Type↓        Value↓
const a: ConstEnumA = ConstEnumA.propA;

// ts not emit "  require('./types')  "
```
I prefer this method because I will not need to greatly change my code.

## Breaking change?

Name conflicts may occur if there was already a name in value scope which was same with 'ConstEnumA',
but I think this is very very rare and will be prevented by linter usually. An extra compiler option can be provided to solve this.

2. check `const enum` in value-import

```ts
// importsNotUsedAsValues is still on

import { ConstEnumA } from './types';
//       Type↓        Value↓
const a: ConstEnumA = ConstEnumA.propA;

// ts find just "ConstEnumA" is used and it is `const enum`
// not emit "  require('./types')  "
```

## Breaking change?

Yes. Now TS do not emit `require('...')` though value-import exists in the code.

## Examples

A complete example of Solution 1:

```ts
import type {
    TypeA,
    TypeB,
    TypeC,
    ConstEnumA,
    TypeD,
    TypeE,
    TypeF,
    ConstEnumB,
    TypeG,
    TypeH,
    TypeI,
    ConstEnumC,
    ConstEnumD,
    TypeJ,
    TypeK,
} from './types';

const b: ConstEnumB = ConstEnumB.propA;
// compiler: OK, 0 error(s)
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by jablko**
Allow, e.g.
```ts
// @filename value-usage-of-type-only-const-enum.ts
import type { Direction } from "./direction";

const direction = Direction.Up;
```
if isolatedModules is false.

### Motivation

[eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) checks whether import statements are resolvable, so wants to know whether an import statement will be elided (by TypeScript) or not. Even if it could predict which imports were candidates for elision, that behavior is configurable (importsNotUsedAsValues), so the plugin takes the conservative view that all imports except type-only imports might or might not be elided.

This is a problem if type-only const enums can't be used as values:
- User declares `export const enum Direction { Up, Down, Left, Right }` in `direction.d.ts`
- If they don't type-only `import { Direction } from "./direction"`, eslint-plugin-import warns that the import might not be resolvable (at runtime, assuming there's no `direction.js` to match `direction.d.ts`)
- If they do type-only import it (it's a .d.ts without a .js, after all), TypeScript complains that it can't be used as a value (it's a type-only import, after all) https://github.com/import-js/eslint-plugin-import/issues/2267#issuecomment-952871674

The same problem as #40344.

I understand that type-only means type-only, and a type-only import on the right-hand side of an assignment looks really unexpected: https://github.com/microsoft/TypeScript/issues/36003#issuecomment-571265501

On the other hand going back to the motivation for type-only imports, my impression is that the whole deal was predictable import elision? https://github.com/microsoft/TypeScript/pull/35200

If isolatedModules is false:
- Const enum values are compile-time only
- Whether or not they're used as values, const enum imports are elided (good, because they can be declared in .d.ts -- what's there to import at runtime, if there's no .js?)

For these reasons, I'd like to allow value usage of type-only const enums if isolatedModules is false.

### Before

isolatedModules **false**:
```sh
$ tsc value-usage-of-type-only-const-enum.ts
value-usage-of-type-only-const-enum.ts:3:19 - error TS1361: 'Direction' cannot be used as a value because it was imported using 'import type'.

3 const direction = Direction.Up;
                    ~~~~~~~~~

  value-usage-of-type-only-const-enum.ts:1:15
    1 import type { Direction } from "./direction";
                    ~~~~~~~~~
    'Direction' was imported here.


Found 1 error.
```
isolatedModules **true**:
```sh
$ tsc --isolatedModules value-usage-of-type-only-const-enum.ts
value-usage-of-type-only-const-enum.ts:3:19 - error TS1361: 'Direction' cannot be used as a value because it was imported using 'import type'.

3 const direction = Direction.Up;
                    ~~~~~~~~~

  value-usage-of-type-only-const-enum.ts:1:15
    1 import type { Direction } from "./direction";
                    ~~~~~~~~~
    'Direction' was imported here.

value-usage-of-type-only-const-enum.ts:3:19 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

3 const direction = Direction.Up;
                    ~~~~~~~~~


Found 2 errors.
```

### After

isolatedModules **false** (error no more):
```sh
$ tsc value-usage-of-type-only-const-enum.ts
```
isolatedModules **true** (same as before):
```sh
$ tsc --isolatedModules value-usage-of-type-only-const-enum.ts
value-usage-of-type-only-const-enum.ts:3:19 - error TS1361: 'Direction' cannot be used as a value because it was imported using 'import type'.

3 const direction = Direction.Up;
                    ~~~~~~~~~

  value-usage-of-type-only-const-enum.ts:1:15
    1 import type { Direction } from "./direction";
                    ~~~~~~~~~
    'Direction' was imported here.

value-usage-of-type-only-const-enum.ts:3:19 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

3 const direction = Direction.Up;
                    ~~~~~~~~~


Found 2 errors.
```

Fixes #40344

### CODE REVIEW

**Comment by sandersn** [comment]
@andrewbranch this PR is pretty small. From the issue discussion, it sounds like you'd be interested in a fix if it was simple. What do you think about this?

**Comment by andrewbranch** [comment]
We’ve always known this change would be dead simple, but the issue is “Awaiting More Feedback.” The fairly low amount of feedback we’ve received on it has been positive, and I’ve been cautiously open to this change from the beginning. I think the downside is just adding to the confusion/complexity around what `import type` and `isolatedModules` each mean. I think we possibly need to have a broader conversation about the interaction between `isolatedModules` and const enums now that esbuild can inline them. If that becomes the norm for transpiling/minifying TS, then `isolatedModules` may be the wrong flag to toggle this behavior. At any rate, I don’t think I can unilaterally approve this PR.

**Comment by jablko** [comment]
I'm still stuck on, you e.g. `import { AcBrowseToObjectType } from "activex-access"` ([pretend it's a module](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/activex-access/index.d.ts)) with either `importsNotUsedAsValues: "preserve"` or `preserveValueImports: true`:
- TS can't elide the import or named import because the runtime `.js` might have side effects (`importsNotUsedAsValues`) or you might subsequently have [`eval("console.log(AcBrowseToObjectType.acBrowseToForm)")`](https://www.typescriptlang.org/tsconfig#preserveValueImports) (`preserveValueImports`),
- but preserving the import/named import is problematic because there might _not_ be any runtime `.js` or runtime named export.
- Currently, if you explicitly elide the import (`import type { AcBrowseToObjectType }`) or named import (`import { type AcBrowseToObjectType }`) you get an error (which this PR suppresses) if you try to use its (inlined) value (unless you `eval("AcBrowseToObjectType.acBrowseToForm")` ... or `// @ts-expect-error`).

On the other hand I'm cool waiting for more feedback :+1:, in case a better solution can be found, or you can sidestep it entirely, or I'm missing the bigger picture, or there are developments on the horizon ...

> If that becomes the norm for transpiling/minifying TS, then `isolatedModules` may be the wrong flag to toggle this behavior.

Instead of "if isolatedModules is false" I should have said "if inlined", whether by `isolatedModules: false` or, in future, some other condition. (I've edited the PR title accordingly.)

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this PR while it's still waiting on its bug to be accepted.

**Pull request closed without merging**
