### PR TITLE
Strip literal freshness when contextually typed by instantiable type that has return mapper constraint inferences

### LINKED ISSUE #50635: Regression in 4.8 where string union type widens to string
# Bug Report

### 🔎 Search Terms

`string union widening`, `string union regression`, `union widening`

### 🕗 Version & Regression Information

This regression occurred in 4.8.0, and can be reproduced with the `4.8.0-beta`, and nightly (`4.9.0-dev.20220904`) tag in TS Playground. This works with `4.7.4`.

- This changed between versions 4.7.4 and 4.8.0-beta

I feel like this might be related to the [Improved inference from binding patterns](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#improved-inference-from-binding-patterns) change

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgOIFc5QCYB4AqAfMgN4BQylyAFAG5wA2AXMuiANYgD2A7iAJQt6DZMADOyfAG4yAXzJkwATwAOKAPIAjAFYQEYDFjxFkAXlIUqAbXYQlokMltKuMSQF0WhnARt33hDKyMmQwbPrAXI7iWrr6dIwsbJy8AkKMohIASnpcPmJgUKAA5gA0rBzcfMTkVMhQEGDoUI7CyACEpuZs2BAwoBDYyABkw8htneYg6Awio8jKaq7jGV3mAORcOnpg6yNj7QCCUFBwSgB04senSgkM-EEKYSARUZmxO+owAMoAFnBqAiEaiWSjCdAQJKVVKlUHIMT-NQsD76bzGQiwwQrBgQzKSCx1YBuajtGLbeLgiD8fgEupUBpNFrIeAMMQQGR1eR1BiNbHAbB-AEocyFCEhOowPI0BBRApOOwOeGIqm0unIGUgOXFTA4MxKoV+JTuDlq0TE7VGfYdC04O4Qw3uamq02UBnNRwstkmtVcqjyOFupnCfmCtSPULhMCRRwIBpwSAogw69HUG3YZHkpNGIE02r0xrumjCKEpPhYtrifGmYhkuJgL6hiB3cpph5yJ6R6PIOBiAAywEgpwYBGQEAAHpAQNgJNQCkUQMVkAAfZCaLhcHlwRwr6YAW000H4VgC1HOZ4YA+gjDELHwuYDBaZdxLVTS2Lx+Cse4PUHcZhqcJ1IGjgXoO16XC8OK9GIdzdhIn7ftAjresgwTtmQAD0GHIN8EAoIsKDLAABuIADqeTsCURHIAAtEqXAzEMoAIFB+G-PhqgoM4cHdhUXbLHOJRiGQGpymRFElHqsYQPGECJmi1B5pQBEsD2-ZgQw1DrGA7Fsus5TrAiDEMNg+nIOsB5mescBWWw0brPwsKyG2QA)

To reproduce, hover over the "isWorking" variable to see that the type definition includes a union of the strings. Switch to 4.8.0-beta, and note that the type definition is now just `string`.

### 💻 Code

```ts repro
interface Guard<T> {
    (val: unknown): val is T;
}

type ObjectGuard<T> = {
    [key in keyof T]: Guard<T[key]>;
};

function isObject(val: unknown): val is Record<string, unknown> {
    return val !== undefined && val !== null && typeof val === 'object' && !Array.isArray(val);
}

function isObjectOfShape<T>(
    value: unknown,
    shape: ObjectGuard<T>,
): value is T {
    if (!isObject(value)) {
        return false;
    }
    let validShape = true;

    for (const key in shape) {
        const guard = shape[key];
        if (guard && !guard(value[key])) {
            return false;
        }
    }

    return validShape;
}

function createObjectGuard<T>(guard: ObjectGuard<T>) {
    return (val: unknown): val is T => isObjectOfShape(val, guard);
}

function asLiteral<T extends (string | boolean | number)[]>(...literals: T) {
    return (val: unknown): val is T[number] => {
        return literals.includes(val as T[number]);
    };
}

// See type of `isWorking` - should include the type key as a union of strings
const isWorking = createObjectGuard({
//    ^?
    type: asLiteral('these', 'should', 'be', 'a', 'union'),
});
```

### 🙁 Actual behavior

String union type is widened to `string`.

### 🙂 Expected behavior

String union type remains a union, rather than widening

### LINKED ISSUE #50787: Literal strings with generics are inconsistant when strictNullChecks is false
# Bug Report

### 🔎 Search Terms

- string literal
- strictNullChecks
- keyof

### 🕗 Version & Regression Information

It works properly on v4.7.4 but is failing on v4.8.2 and with the nightly build.
It also works normally when `strictNullChecks` is `true`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strictNullChecks=false&ts=4.8.2#code/C4TwDgpgBAsg9gEwgGygXigbygZwFy7ABOAlgHYDmA3FAEYG1xzIQCGZUAvgFAvBRgSAYwDWBADwBpCCBxQIAD2AQyCOSJlwAZrEQoAfAAowROJCLASEfFCJsEcMshBRpsgNoBdAJTp9UAAVhEXF4JGQAGlcZHH1eCH5idhwtOCIAWwkAFSM4WgArAizfNH8s7m4hRxx+OxwAV2RgAEZ0KCSyFLT042DDdwAiHAGfbwqqzv5yZQyIBBJWZTbBUX6hkbGJmttrRuAAJjaOrozDaYhZ+cWIbyA)

### 💻 Code

```ts
type Model = { s: string; b: boolean }
let pick: <Keys extends keyof Model>(properties: readonly Keys[]) => Pick<Model, Keys>
let transform: <T>(obj: T) => T

const result1 = transform(pick(["s"]))

const intermediate = pick(["s"])
const result2 = transform(intermediate)
```

### 🙁 Actual behavior

`result1` has a type of `Pick<Model, keyof Model>` and `result2` as a type of `Pick<Model, "s">`

### 🙂 Expected behavior

`result1` and `result2` should have the same type `Pick<Model, "s">`.

### PR DESCRIPTION
**Pull request by andrewbranch**
From the test:

```ts
interface Guard<T> {
  (val: unknown): val is T;
}

type ObjectGuard<T> = {
  [key in keyof T]: Guard<T[key]>;
};

declare function createObjectGuard<T>(guard: ObjectGuard<T>): (val: unknown) => val is T;

declare function asLiteral<T extends (string | boolean | number)[]>(...literals: T): (val: unknown) => val is T[number]

// See type of `isWorking` - should include the type key as a union of strings
const isWorking = createObjectGuard({
  type: asLiteral('these', 'should', 'be', 'a', 'union'),
});
```

When inferring `T` for `asLiteral(...)`, we get the type of each argument (starting with `"these"`) with the contextual type `T[0]`, `T[1]`, and so on. We use the contextual type to determine whether to widen or strip freshness from literal types, but we try to instantiate it first, using inferences made from the return type. The return type inference turns out to map the `T` of `asLiteral` to the `T` of `createObjectGuard` (which, uh, seems wrong, but doesn’t actually matter here), and since the former is not assignable to the latter, the inference goes to the constraint, `(string | boolean | number)[]`. So the contextual type `T[0]` is instantiated to `string | number` (through some special unrelated logic to filter booleans out of union contextual types). That type is not a literal type, so `"these"` remains fresh, allowing it to widen to `string` as the spread argument. The weird thing is, if we had just asked whether `"these"` was a literal type of the contextual type `T[0]` where `T extends (string | boolean | number)[]` instead of eagerly instantiating that type, we would have said yes; when an instantiable type is constrained to a primitive, we want to preserve the literalness of arguments it contextually types. So, this PR asks whether a literal type could be a literal of its contextual type, instantiated _or_ uninstantiated.

I think a possible alternative would be to discard contextual type instantiations where the return type mapper simply produces an inference to the constraint of the type parameter it’s inferring, indicating that nothing useful came from trying to infer from the return type.

Fixes #50635
Fixes #50787

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
@typescript-bot user test inline
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
Hmm, I'm not sure about this one. The thing that strikes me is the convoluted use of generics in `asLiteral`. It constrains `T` to an array type, when really all the function cares about is the element type, as demonstrated by `T[number]` in the return type. When I simplify it to make the type variable as specific as possible, it all works just fine:

```ts
declare function asLiteral<T extends string | boolean | number>(...literals: T[]): (val: unknown) => val is T;
```

I'm not sure I think we need to do anything other than recommend this rewrite.

**Comment by andrewbranch** [comment]
@ahejlsberg what about the other issue this fixes? https://github.com/microsoft/TypeScript/issues/50787

```ts
type Model = { s: string; b: boolean }
let pick: <Keys extends keyof Model>(properties: readonly Keys[]) => Pick<Model, Keys>
let transform: <T>(obj: T) => T

const result1 = transform(pick(["s"]))
// 4.7: Pick<Model, "s">
// 4.8: Pick<Model, keyof Model>
```

**Comment by ahejlsberg** [comment]
@andrewbranch The root cause of #50787 is that we consider the apparent type of an unconstrained type parameter to be `{}` in non-strictNullChecks mode. This then gets us in trouble when we use the return type mapper to infer from `T` to `Pick<Model, Keys>` because `T` turns into `{}` causing us to infer `never` for `Keys`. It works in strictNullChecks mode because the apparent type of `T` is `unknown` from which we make no inferences.

I'd suggest changing these lines in `inferTypes`

```ts
                    source = getReducedType(source);
                    if (!(priority & InferencePriority.NoConstraints && source.flags & (TypeFlags.Intersection | TypeFlags.Instantiable))) {
                        const apparentSource = getApparentType(source);
```

to this

```ts
                    source = getReducedType(source);
                    if (!(priority & InferencePriority.NoConstraints && source.flags & (TypeFlags.Intersection | TypeFlags.Instantiable)) &&
                        !(source.flags & TypeFlags.Instantiable && !getBaseConstraintOfType(source))) {
                        const apparentSource = getApparentType(source);
```

i.e. skip making inferences where there is no constraint, regardless of mode. It fixes the issue with no changes in the test suite. But of course it may affect some of the extended test suites.

**Comment by andrewbranch** [comment]
It’s not clear though why specifying a very wide constraint like `unknown` or `{}` should behave differently than not specifying a constraint. In 4.7, and in this PR, this form also produces `Pick<Model, "s">`:

```ts
type Model = { s: string; b: boolean }
declare let pick: <Keys extends keyof Model>(properties: readonly Keys[]) => Pick<Model, Keys>
declare let transform2: <T extends {}>(obj: T) => T
const result2 = transform2(pick(["s"]))
// 4.7:              Pick<Model, "s">
// 4.8:              Pick<Model, keyof Model>
// This PR:          Pick<Model, "s">
// Suggested change: Pick<Model, keyof Model>
```

I don’t see a good reason why `extends {}` (a reasonable constraint to add for `T`!) should compromise the narrow inference for `Keys`.

**Comment by Andarist** [comment]
This would also fix https://github.com/microsoft/TypeScript/issues/56912 . So in that sense, it's competing with https://github.com/microsoft/TypeScript/pull/56953 - which also fixes one of the issues referenced by this PR (but it doesn't fix the other one).

**Pull request closed without merging**
