### PR TITLE
Disallow primitive assignability to indexer of type any

### LINKED ISSUE #4588: String type matching on index signature
As of the latest nightly build (8/31/2015), the following code compiles:

```
interface Bob { [key: string]: any; }
var x: Bob = "something";
```

With TSC 1.5.3, I got the error message `Index signature is missing in type 'String'.` Can someone clarify if this is intended behavior? It seems like it might be (https://github.com/Microsoft/TypeScript/pull/4074), but it also seems a bit weird to be able to assign a string to what is probably intended to be a basic hash map.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #4588.

`string/numberIndexTypesRelatedTo` needs to prevent primitives from being
assignable to an indexer of type 'any'. However, these two functions take
an apparent type, which no longer has the primitive flag set. I thought of
three ways to provide this information:

1. Pass the original type into `string/numberIndexTypesRelatedTo` and
check its flag.
2. Record a boolean `isPrimitive` before converting to the apparent type,
and pass it to `string/numberIndexTypesRelatedTo`.
3. Create a helper function `isPrimitive` that takes the apparent type and
compares it to globalString/Number/Boolean/ESSymbolType.

I decided on (1) because it seems like the simplest and safest. But none
of the options are elegant. Please suggest improvements.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Is there a bug tracking this change? I'd like to have more context on what we're saying is desirable/non-desirable

**Comment by sandersn** [comment]
Yes, I'll remember someday to add a link to the bug number: #4588. And it's an improvement to #4074 which was a little too permissive.

**Comment by RyanCavanaugh** [comment]
FWIW I was interested in the status of this code
```ts
interface X {
	[n: number]: any;
}

var x: X;
x = 'hello';
```
which seems to still compile under this branch, which is what I'd expect.

**Comment by sandersn** [comment]
The test I added in `assignmentCompat1.ts` has this case, but I didn't think about it enough and expected it to fail (I forgot that strings *do* support numeric indexing in typescript). I'll add another test case like 

```ts
var x: { [n: number]: any } = false
```

which should (and does) fail.

**Comment by sandersn** [comment]
Ping @RyanCavanaugh -- can you take another look now that I added more test cases?

**Comment by RyanCavanaugh** [comment]
:+1:

**Pull request merged**
