### PR TITLE
Remove the check that if base file name starts with ^ is dynamic file name since those files can exist

### LINKED ISSUE #35734: Debug Failure. False expression:  in openExternalProjects  in getOrCreateScriptInfoWorker
This is a high hitter from VS telemetry and impacts a wide range of TS versions, at least 2.7-3.7

Command: `openExternalProjects`

Message: `Error processing request. Debug Failure. False expression: `

Stack:
 
 ```
ProjectService.getOrCreateScriptInfoWorker(tsserver.js:137708:30)
ProjectService.getOrCreateScriptInfoNotOpenedByClientForNormalizedPath(tsserver.js:137681:33)
ProjectService.updateNonInferredProjectFiles(tsserver.js:137368:43)
ProjectService.addFilesToNonInferredProject(tsserver.js:137259:22)
ProjectService.createExternalProject(tsserver.js:137210:22)
ProjectService.openExternalProject(tsserver.js:138654:40)
ProjectService.openExternalProjects(tsserver.js:138406:26)
Session.handlers.ts.createMapFromTemplate._a.(tsserver.js:139167:46)
unknown_function(tsserver.js:140854:88)
IOSession.Session.executeWithRequestId(tsserver.js:140845:28)
IOSession.Session.executeCommand(tsserver.js:140854:33)
IOSession.Session.onMessage(tsserver.js:140877:35)
Interface.(tsserver.js:142192:27)
```

VS bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1044433

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #35734

### CODE REVIEW

**Comment by sheetalkamat** [comment]
> do we lose any ability to detect or create dynamic file names since real files can use carat now?

We already have tests for all the scenarios that use dynamic file names and they work, (I think work to retain projectRootPath for open files has rendered this not needed any more)

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@uniqueiniquity @jessetrinity @amcasey can you try our the drop here to see the debugging scenarios are working ok. 
I tried creating bunch of dynamic files in VS but I might not have covered all scenarios. (file is created dynamic when debugging in ie and clicking files from solution explorer and script documents list if there is not matching file found on disk.. eg you compile ts with `--inlineSources` and then delete the ts files)

**Comment by uniqueiniquity** [comment]
@sheetalkamat sure thing - I actually just built it locally a few moments ago.

**Comment by uniqueiniquity** [comment]
@sheetalkamat Looks good to me. Tried naming normal files with a leading ^, tried using dynamic files, and tried using dynamic files that start with a leading ^. All seems fine.

**Pull request merged**
