### PR TITLE
Faster exit from isTypeRelatedTo with identityRelation

### LINKED ISSUE #36564: Performance regression in #33252
The extra work done in #33252 is valuable, but maybe it doesn't need to be so expensive.

Setup: 

1. Clone https://github.com/amcasey/material-ui.git
2. Check out Benchmark
3. `yarn` to restore packages
4. `yarn typescript` to prebuild and run some TS tests

Repro

1. `tsc -p docs`

On a random Mac Mini:

- 10-run avg on https://github.com/microsoft/TypeScript/commit/72bb4c2bdcb0cb245c397cd9a8f1f0d1158c6a5d: 30,872ms
- 10-run avg on https://github.com/microsoft/TypeScript/commit/c5e6d95e930048a033868d72440a9296904a33ec: 33,268ms (8% slower)

_Note_: to build old TS commits, you probably need to change `const { default: chalk }` to `const chalk` in `scripts/build/utils.js`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Reduces the total compile time of the test in #36564 by about 6%.

Fixes #36564.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
@typescript-bot perf test this

**Comment by amcasey** [comment]
@typescript-bot pack this

**Comment by amcasey** [comment]
10-run average from the original machine shows a 7% improvement.  Very nice!

**Comment by sandersn** [comment]
This change fixes a failure in checking in `@types/mongoose` of the form:

```ts
interface E {
    stack: string;
}
declare var y: E | undefined
declare var x: E;
var x = y; // error expected here, but none given
x.stack
```

It's very surprising to me that we didn't give an error here before. Note that we *did* give an error for `number | undefined`.

**Comment by sandersn** [comment]
Maybe it's because we weren't strictly checking duplicate declaration sites before. Normal code like `var x: E | undefined = y` gives the error before this change.

**Pull request merged**
