### PR TITLE
Evaluate simple template expressions

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/53888

This PR builds on top of the simple fix available in https://github.com/microsoft/TypeScript/pull/53903 . Since I think that it's not that unlikely that this other PR might be desirable while this one here might not be, I decided to open an extra PR with this change.

I don't think that the case presented in #53888 warrants the change but I can imagine that it's a simplification for the purpose of creating a minimal repro case. A more sane case could look smth like this:
```ts
const someCategory = 'main'
const someSubcategory = 'sub'

foo({ d: `${someCategory}-${someSubcategory}`, cb: x => {} });
```

Given that we are able to "evaluate" some constant values this PR would allow for simple variable reuse and composition of template expressions without losing the ability to discriminate objects etc

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by gabritto** [comment]
I think in theory this is a good change (assuming the tests come back passing), the question is if it's worth the perf cost.

**Comment by gabritto** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by gabritto** [comment]
I'm now also wondering if someone might be relying on things like `const x = `${"a"}` having type `string` and not type `"a"`. Let's see when the tests finish running, I guess.

**Review by gabritto — APPROVED** [review]

**Comment by gabritto** [comment]
@weswigham do we have concerns with merging this?

**Comment by DanielRosenwasser** [comment]
Sorry, how is this different from #41891 which we had to back out?

Refs:

* https://github.com/microsoft/TypeScript/issues/42416
* https://github.com/microsoft/TypeScript/issues/42589
* https://github.com/microsoft/TypeScript/pull/43376

**Comment by Andarist** [comment]
This PR is much smaller in scope. It doesn't infer template literal types for template literal expressions. Only string literals can be inferred from template literal expressions. If the evaluation ends up being impossible then evaluation just returns `undefined` and every code that follows that continues to work as before.

I looked through all the linked issues/PRs and I think that most of the concerns raised there were about template literal types.

For example, second bullet point from the bottom in https://github.com/microsoft/TypeScript/issues/42416:
```ts
const x = `somestring`; // this is a literal type
const str = "string";
const y = `some${str}`; // and this is too! (but wasn't)
```

Inferring a template literal type here wouldn't be OK since it's not uncommon to push new items to the resulting array:
```ts
declare var srcSvgData: SvgData[];
interface SvgData {
  fileName: string;
  iconName: string;
}

const c = srcSvgData.map(
  (svgData) =>
    `<a href="./svg/${svgData.fileName}"><svg><use href="#${svgData.iconName}" xlink:href="#${svgData.iconName}"/></svg></a>`
);

// https://github.com/ionic-team/ionicons/blob/1543daa0103c9065805f7075b5dc6abd1c2dd9c1/scripts/build.ts#L262
c.push("somestring"); // should be ok
```

And the last one:
```ts
function usePxValue(px: `${string}px`) {}

let a = 12;
const lit = `${a}px`;
usePxValue(lit); // error, this makes sense though since `a` is mutable binding with a `number` type


const b = 12;
const lit2 = `${b}px`;
usePxValue(lit2); // this works though, it seems like a good thing
```

There is also an argument about `makePx` - that it would behave differently. This is true but then the argument wouldn't be generic so the input type wouldn't be preserved. Even if we make it generic - the return type would still be `string` since the generic signature can't determine how it will evaluate and if literal types are the only inputs given to this function. 

This works though since the programmer encoded the specific intent for the return type and the argument is generic: 
```ts
function makePx1<T extends string>(a: T) {
  return `${a}px` as const;
}
```

Maybe there is an argument to be made here that constness could propagate to this return expression automatically:
```ts
function makePx2<const T extends string>(a: T) {
  return `${a}px`; // this isn't const
}
```

I'm not precluding that there might be some edge cases here around widening but I don't know all of its intricate/delicate rules so it's hard for me to comment on that.

**Pull request merged**
