### PR TITLE
Avoid uses of ES6 Set, use Array instead

### PR DESCRIPTION
**Pull request by ajafff**
Fixes: #28918

/cc @andy-ms

### CODE REVIEW

**Comment by arktronic** [comment]
This looks like a step in the right direction for fixing #28918, but I believe more needs to be done for that issue. For example, `inspectValue.ts` also uses `String.prototype.startsWith`, which is another function introduced in ES6. I'm unsure of how many other ES5 incompatibilities exist in this and/or in other files.

**Comment by NN---** [comment]
Why just not use core-js or any other polyfill ?

**Comment by arktronic** [comment]
Given the fact that functions like `ts.startsWith` exist in the codebase, it would appear that TypeScript is intended to run in a pre-ES6 environment without polyfills. Official guidance on this from project maintainers would be helpful, of course.

**Comment by j-oliveras** [comment]
I opened #28932 to solve the `String.prototype.startsWith` and some others.

**Comment by weswigham** [comment]
We probably used `Set` because we assumed we had self-polyfilled it like we do `Map` - it's probably best to write out the polyfill instead.

**Comment by ajafff** [comment]
> it's probably best to write out the polyfill instead.

What's the benefit of that? There are still other ES6 features without a polyfill that could easily be used by accident (see #28933).
Also note that `Set` doesn't give any additional performance and isn't easier to use in these cases.

**Comment by weswigham** [comment]
> What's the benefit of that?

Using the platform `Set` when it's available, mostly (which normally has better memory characteristics, at least). Like [what we do with `Map`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/core.ts#L115) would be ideal.

**Pull request merged**
