### PR TITLE
fix(55168): Computed properties do not respect setter signatures

### LINKED ISSUE #55168: Computed properties do not respect setter signatures
# Bug Report

Computed property assignments do not respect corresponding setter signatures.

### 🔎 Search Terms

variant accessors, setter, computed properties, write type

### 🕗 Version & Regression Information

- Affected versions: 4.3 to 5.1.6 (current stable).

### ⏯ Playground Link

[Playground Link (5.1.6)](https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgzgLgBA1jAvDAygTwLYCMQBsAUAlANwBQpoksApmAK4YwAKATiAA4QwDepM-8JDADkcYQBpSAX3IBLMFGosAZgENg1GADEQIHnwEBzarDhEAXKhMAeaC3mGAfGQEwIJ+PgBulgJKKWVSxcalsoezAnEnJXY1gAbTgAXQsrKDCIpxcBdwTk7z8AoJCMh0domVIAE2pgXFUWTUpoGGVdSx0QcgB6bpgAeQBpc1I2kAA6BFcBZHjhWSgJEQB3EBY4CGEkslJemABRFjYWCBGxubEk6dnhCAALEDpcKqXhVfWtsnPWDghJq5uWDoi3EInUUDoqlwuDQn1GukSV2mQjmVRA1E2oOEYBAiySPT6AHETAEuO8EKouNQAB7sWqKKojZqwLxQugYlFjSag86iLY8hE-Tj-AUgRFXSkwZlkPYCAB6AH5SEA)

### 💻 Code

```ts
const k = Symbol();

const enum Props {
    k = 'k',
}

interface Foo {
    get k(): Set<string>;
    set k(v: Iterable<string>);

    get [k](): Set<string>;
    set [k](v: Iterable<string>);
}

declare const foo: Foo

// OK:
foo.k        = ['it', 'works'];

// Errors:
foo['k']     = ['should', 'work'];
foo[Props.k] = ['but', 'actually'];
foo[k]       = ['does', 'not']

// Getters work as expected:
const values = [foo.k, foo['k'], foo[Props.k], foo[k]] as const;
//    ^? const values: readonly [Set<string>, Set<string>, Set<string>, Set<string>]
```

### 🙁 Actual behavior

Getter type is used at the LHS of an indexed/computed property assignment.

### 🙂 Expected behavior

Setters should accept their declared types.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #55168

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by jakebailey** [comment]
Taking the tests should be fine, though it'd be nice to know which PR actually fixed this...

**Comment by a-tarasyuk** [comment]
@jakebailey It looks like [this one](https://github.com/microsoft/TypeScript/pull/55585/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R17709)

**Comment by jakebailey** [comment]
Aha, yep. I knew I read that somewhere.

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
