### PR TITLE
Fix Get/Set being enumerable

### LINKED ISSUE #3610: Why are TS get/set definedProperties in a class transpiled as enumerable/writable?
I just confirmed in the TS Playground that the following TS:

```
class Foo {
    get bar() { return true;}
}
```

Produces this JS:

```
var Foo = (function () {
    function Foo() {
    }
    Object.defineProperty(Foo.prototype, "bar", {
        get: function () { return true; },
        enumerable: true,
        configurable: true
    });
    return Foo;
})();
```

This [MDN link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) confirms that, for `Object.definedProperty` accessors:
• enumerable: Defaults to false.
• configurable: Defaults to false.

Clearly the generated code is overriding the default values for these keys.

Plowing through the ES6 spec is not something I do. So  I’m not sure that ES6 hasn’t changed the defaults. But I’d be surprised.

Now one of the things I miss in TS/ES6 class definitions is the ability to control these keys. It is also not easy to embellish a class with defined properties later … properties that might have non-default definitions

But that’s not my point or my question … which is, why is TS deviating from the defaults? 

I get why I’d want the property to be enumerable most of the time – strange that the spec defaults to false. I don’t understand why I should want it to be configurable (maybe because I don't like something about the property TS generated for me?).

In any case, I don’t get how TS (or ES6) gets away with changing the ES5 defaults.

### PR DESCRIPTION
**Pull request by pathurs**
Fixes #3610

### CODE REVIEW

**Comment by pathurs** [comment]
Note: I just followed the normal convention of setting `enumerable: false`, however it *may* be better to not set enumerable at all, which *should* default to false on it's own. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)

@sheetalkamat Let me know what you think, seeing as you have already approved these changes.

**Comment by RyanCavanaugh** [comment]
@sandersn let's bundle this in with the rest of the class field changes when we document what's happening

@pathurs can you fix the merge conflicts please? Sorry for the delay in getting this in

**Comment by sandersn** [comment]
I missed this in 3.7 when I was adding ES-compliant class field emit. However, I think it's better to put it into 3.9 now than to wait any longer.

**Comment by pathurs** [comment]
@sandersn Thanks for merging from master, I don't know how I missed the notifications on this

**Comment by sandersn** [comment]
Travis fails because it still thinks that we're using submodules for the user tests. Not sure why.

**Comment by sandersn** [comment]
Thanks for your patience on this @pathurs

**Comment by ntucker** [comment]
Does this affect the types for keyof T when T has getters?

**Comment by DanielRosenwasser** [comment]
No, this affects emit, not the type system.

**Comment by benpetermorris** [comment]
This is a significant breaking change in our case. The UI library we use (Telerik's Kendo) uses property enumerability to convert "plain" objects to the Observable variant it uses within its UI classes. 

With this change, property definitions are excluded from the conversion and the associated properties are no longer present on objects retrieved from Kendo's containers.

I support standards, of course, but it would be nice if there was an option to keep the old behavior. I'd be surprised if the new behavior is as innocuous as its low profile in the changelog seems to suggest.

**Comment by deltakosh** [comment]
I agree with @benpetermorris 
https://github.com/microsoft/TypeScript/issues/38958

**Comment by iMarv** [comment]
We have been struggling with this breaking change aswell as we were relying on being able to enumerate over getters.
Our solution now is to use the following decorator on all getters that shall be included when enumerating the objects:

```typescript
function Enumerable(
    target: unknown,
    propertyKey: string,
    descriptor: PropertyDescriptor
) {
    descriptor.enumerable = true;
};
```

```typescript
class Testi {
    @Enumrable
    get prop(): string {
        return 'moin';
    }
}
```

I guess this is a bit hacky, but the cleanest solution we could come up with.

**Pull request merged**
