### PR TITLE
Fix commas in JSON

### PR DESCRIPTION
**Pull request by amcasey**
Some missing, some extra.

### CODE REVIEW

**Comment by amcasey** [comment]
I can see how the trailing commas might have been ignored, but not how the missing comma could have worked.

**Comment by RyanCavanaugh** [comment]
`tsc -b` seems to not catch syntax errors in tsconfigs

**Comment by weswigham** [comment]
Huh, I don't get how the missing comma worked, but I get why the extra commas worked (do we just fail to report the error on config parse and use the json AST anyway? Is that a bug we should fix?) - we just reuse our normal parser for json parsing, and js allows trailing commas (and comments, that part being intentional), and we don't special case it.

**Comment by sheetalkamat** [comment]
tsconfig is not true json and it tolerates non trivial errors..

**Pull request merged**
