### PR TITLE
Add exported members of all project files in the global completion list

### LINKED ISSUE #7849: [ES6] Auto imports with completion
It should really fantastic if tsserver completion command could support auto import with completion like WebStorm provides:

See http://blog.jetbrains.com/webstorm/2016/04/angular-2-workflow-in-webstorm/#ng2-imports for more information.

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #7849

This PR adds several things:
1. It adds the exported members of all project files in the global completion list, no matter if the file was imported by the current file or not; 
2. however, for members coming from not-yet-imported file, the returned `CompletionEntry` now has a new property `hasAction`, indicating if the user commits it, additional code actions will be needed to avoid errors;
3. after emitting a completion entry with `hasAction` set to `true`, the editor can send a `CommitCompletionWithCodeAction` request to the server to get the corresponding code actions, and then apply them just like other code actions.

### CODE REVIEW

**Comment by zhengbli** [comment]
@mhegazy @vladima comments?

**Comment by thekalinga** [comment]
@zhengbli Does this include files under `node_modules` aswell?

**Comment by zhengbli** [comment]
Yes as long as they have been used in the project at least once

**Comment by thekalinga** [comment]
Will the first time import of a class work (this class has not been imported into my source, but the `node_modules` contains the definition file for this class I'm trying to import)?

**Comment by zhengbli** [comment]
No you have to import that module at least once anywhere in your project, so that module becomes part of your project. Otherwise it would be too expensive to search all the folders all the time.

**Comment by thekalinga** [comment]
@zhengbli The sheer mention of a dependency in `package.json` & the presence of the dependency in `node_modules` implies that the user is wanting to use the module. Most of the time (~99%) user does not modify any file under `node_modules` manually.

Only `npm` (or) `yarn` would trigger a change to the `node_modules` directory structure, which user would not trigger very frequently in the project.

So the amount of change cycles that trigger autocomplete index to change are relatively limited from the point of view of the files under `node_modules`.

Unless I'm missing something, forcing user to import at least once in the project is an arbitrary expectation.

Please let me know if I've missed something

**Comment by zhengbli** [comment]
I agree parsing `package.json` is a good estimate. Though that belongs to a bigger question: whether we should eagerly include modules listed in `package.json` into the program, which would have impacts on not only completion list, also other features like navigate-to. The changes made in this PR serves as the first step towards and is building based on how the program is currently constructed. That proposed changes to make the program bigger eagerly may go to a separate PR later.

**Comment by thekalinga** [comment]
@zhengbli Is it planned for 2.3?

**Comment by zhengbli** [comment]
@thekalinga at this point I'm not sure, depends on if the team has the time to review the changes

**Comment by zhengbli** [comment]
Updated with the feature embedded in the "CompletionEntryDetails" API call.

**Comment by mjbvz** [comment]
The API looks good to me for VSCode. Looking forward to picking up this change

**Comment by angelozerr** [comment]
I'm looking for too for this great feature to integrate it inside Eclipse. Do you know when you think you could merge this issue to master to consume it with typescript@dev ?

**Comment by angelozerr** [comment]
@mhegazy do you know when this PR will be accepted? The auto import feature is not in the [RoadMap](https://github.com/Microsoft/TypeScript/wiki/Roadmap) Do you know for which version of TypeScript, it will be available? Thanks!

**Comment by minestarks** [comment]
This is redone in #17851

**Comment by mhegazy** [comment]
Merged in #19069. thanks @zhengbli !

**Pull request closed without merging**
