### PR TITLE
Fixed an issue with top function type being callable with no arguments

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/48840
reverts a part of https://github.com/microsoft/TypeScript/pull/35438/files (the tests added there still pass)

### CODE REVIEW

**Comment by Andarist** [comment]
This has been labeled as "For Uncommitted Bug" **but** the associated issue is labeled with "Bug". This perhaps indicates a bug in the bot.

**Comment by fatcerberus** [comment]
I always thought “For Uncommitted Bug” was literal: the issue has a `Bug` label but not a `Committed` label (note: not the same thing as “commit” in git terminology)

**Comment by Andarist** [comment]
Hm, i think it also gets For Uncommitted Bug if the issue has no label - and that’s what i assumed to be the main differentiator here. U might be right though - maybe it has to be assigned to a milestone (specific TS version or Backlog) for this label to not be added to the PR

**Comment by jakebailey** [comment]
My understanding is that this particular label is mainly about whether or not it has been assigned to a milestone.

**Comment by sandersn** [comment]
@DanielRosenwasser or @jakebailey can you figure out if #48840 *should* be moved into the backlog or a specific milestone? I know the bug came up in the recent design meeting, but I don't think we decided whether the bug was worth fixing.

**Comment by jakebailey** [comment]
I think I'd like to see @ahejlsberg take a look at this in context of #52282 too, lest we end up with a surprising relation behavior.

**Comment by jakebailey** [comment]
I would merge main since this predates the other function PRs but otherwise LGTM given we check the usual suspects.

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by Andarist** [comment]
> I would merge main since this predates the other function PRs but otherwise LGTM given we check the usual suspects.

Synced this with `main` 👍

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
