### PR TITLE
Propagate nonInferrableType in &&, || and ?? operators

### LINKED ISSUE #37974: Compiler crashes with generics
**TypeScript Version:**  "^3.8.3"

"No error for last overload signature" error

**Code**
I could narrow it down to this repository:

https://github.com/mohsen1/TS-No-error-for-last-overload-signature

https://github.com/mohsen1/TS-No-error-for-last-overload-signature/blob/fbd33f9aad6b3fd1f914b6bfe23cebc5db1dd12f/src/index.ts#L22-L23
```
wrapResolver( resolver(AModel) || [])
```
**Expected behavior:**
Type error, `wrapResolver` is not suppose to get an array
**Actual behavior:**
Compiler crash

**Related Issues:** 
https://github.com/microsoft/TypeScript/issues/33133
https://github.com/microsoft/TypeScript/issues/33732
https://github.com/microsoft/TypeScript/issues/35186

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #37974.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
Tests all look clean (DT errors are preexisting conditions).

**Comment by weswigham** [comment]
Do ternaries also need a fix at all? They union two branches, and `a ? a : b` scans a lot like `a || b`.

**Comment by ahejlsberg** [comment]
Thought about it some more and realized the real issue here is that `getTypeFacts` should return `TypeFacts.None` for `never`. Right now it returns `TypeFacts.All`, similar to what we return for `any` and `unknown`, and that's definitely not right. Once we return `TypeFacts.None` there is no need to modify the logic for the operators because `never` then propagates naturally.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by andrewbranch** [comment]
> Thought about it some more and realized the real issue here is that `getTypeFacts` should return `TypeFacts.None` for `never`.

In one of my experiments, I actually tried doing this specifically for `nonInferrableType` instead of for all `never`. If I recall correctly, it caused a bunch of baseline errors, so I abandoned that approach. Nice to know I was on the right track after all.

**Pull request merged**
