### PR TITLE
During inference discriminate the target type before falling back to close-matching types

### LINKED ISSUE #43753: Some regression with union of classes in TS4.2
# Bug Report

_I apologize for the name of issue, I was not able to correctly formulate the problem._

### 🔎 Search Terms

4.2, regression, class, extends, union

### 🕗 Version & Regression Information

This changed between versions 4.1.5 and 4.2.2 
(if we take dev then between versions 4.2.0-dev.20210209 and 4.2.0-insiders.20210210)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhAIGcHsFsFNwBN4GMA2BDATvJ4AXATwAd5JwRgAoalDHRTAI0gO01QPAcgoHF00ZpnQBhaADt20dOnjYAPAAUANOADK6jRoB84AN7VwJ8AEtIAGWipRALnAAzUZHgBuY6ZZsOXcAHN4AmVsaBJIAAo2aFwNAkwCeAcddRJQ8Ic1KHjE5IBKBwA3aDMkDwBfWnosXHBvdk5uXgprW3EpGTkFFW19I1NzKxt7QmwAV3dPE3rfbkDg9Mi0sMhM9TYEpM0C8GLSitozaQVnVERBYVEJaVCu7DEsPh7NbT1DKfBJeAB3CJ2LkTtG6yeRKLJaTR6A7UI6JbCnRCtK4dW6gh6YJ7gvofL6-HZIoGdUHPKHUSrUYhkcDXIkKdGY7SvcAAXkM5X0rIByOBd3pkBJr30AB9wASaai6Y9+ViPHQ0DVEKgpGweLhNgBRSQAC0wkjO2AcAshLN2JSQugiAHUOCQyAbqSiQZKMdLGZDdHkWfpdURZdRQBAxpBMIFKDQKaREOKndg4psTf1TCJ7T6ybLKVHHXcQisEx8RAAvByp8p+gNOUToKBHM7gAAqGgALAA6ABM4AiLYAjABacDfGIAawojiO8E9VFozXAADFMGZ0JazAQtQ3G+34AAPRKSJAtYaEiVKaPZxbqE+guOJbEDeY58IRZYZB080H3yDrHJbC8KK-jtlklOaqJJqOp6goERzguS4rmurZ5GWYD9tAg44NAYy7uAXYOGYjjgEQ6F1Eg+AEWM2DgNA3ySOACArtA+AENAhBaoqUrgPAhQKEQK5HP4yHYMOPAxLgXDoEQYZTmxlpDmhGFIAAqpIQZ4AAskEWr0ex27wLu+5tD+x5Zm+Z4vrSsZfjepgAPoYcpSB-ABHx3osj6LA4Bnvp+mzuUZv5fp6BiVOSqDAfAoG6vqVoyaEcmKXZal0UgCG0P6SEDqhMWYa2OF4c5uaQGY-iSAkZGIEg0DkJ80BNB087USuiCuEqmEkDgmC0Qo7Gcdg3Farx-GCUq2AiQQYkSdQ07SQJsm7mIYGBBohXFQQpVaTue6igeBmKB5JkGX+lkmHlD5PqsplHu+AVBUB8AatqEUQVNGXobN83wItRUlbgCFAA)

### 💻 Code

_I apologize again, I have shortened the example as much as I can._

```ts
/** some declared types */

declare abstract class GlobalController<P, S, SS> {
    isLocal: false;
    abstract getProps(storeState: SS, props: P, state: S): void;
}

declare abstract class LocalController<P, S> {
    isLocal: true;
    abstract getProps(props: P, state: S): void;
}

interface GlobalControllerClass<P, S, SS> {
    new(): GlobalController<P, S, SS>;
}

interface LocalControllerClass<P, S> {
    new(): LocalController<P, S>;
}

type ControllerClass<P, S, SS = {}> = GlobalControllerClass<P, S, SS> | LocalControllerClass<P, S>;

declare const createEnhancer: <P, S, SS = void>(Wrapper: ControllerClass<P, S, SS>) => any;


/** usage */

type ControllerState = {
    bar: any
};

type ControllerProps = {
    baz: any
};


/** fall since TS4.2 (4.1- works fine) */

class FailWithTS42 extends LocalController<ControllerProps, ControllerState> {
    getProps(props: ControllerProps, state: ControllerState) {}
}

createEnhancer(FailWithTS42);
```

_in the sandbox above the same code plus some workarounds that might suggest something_

### 🙁 Actual behavior

`createEnhancer(FailWithTS42)` in the last line shows the error:

```
Argument of type 'typeof FailWithTS42' is not assignable to parameter of type 'ControllerClass<ControllerState, ControllerState, ControllerProps>'.
  Type 'typeof FailWithTS42' is not assignable to type 'GlobalControllerClass<ControllerState, ControllerState, ControllerProps>'.
    Construct signature return types 'FailWithTS42' and 'GlobalController<ControllerState, ControllerState, ControllerProps>' are incompatible.
      The types of 'isLocal' are incompatible between these types.
        Type 'true' is not assignable to type 'false'.
```

### 🙂 Expected behavior

I can call createEnhancer with class FailWithTS42

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #43753

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this
@typescript-bot pack this

**Comment by weswigham** [comment]
*looks at performance results* OK. Definitely needs better perf before this is a viable route to fix the linked issue. Union discrimination is expensive.

**Comment by sandersn** [comment]
I vote to close this since it sounds too slow to use as-is. Is that OK @weswigham ?

**Comment by weswigham** [comment]
Yeah, you're not wrong; I just can't immediately think of another way to fix the original issue (at least not one that doesn't totally overhaul inference, anyway), so trying to make this performant sounds like the best avenue to pursue.

**Pull request closed without merging**
