### PR TITLE
Fix error when exporting const enums (#33060)

### LINKED ISSUE #33060: Cannot export const enum in Export Declaration
**TypeScript Version:**  3.6.1-rc

**Search Terms:** const enum export declaration TS2475

**Code**

```ts
// test.ts
const enum Test {}
export { Test };
```

**Expected behavior:**
The above code compiles without errors.

**Actual behavior:**
> test.ts:2:10 - error TS2475: 'const' enums can only be used in property or index access expressions or the right hand side of an import declaration or export assignment or type query.

**Playground Link:** 
http://www.typescriptlang.org/play/#code/MYewdgzgLgBApmArgWxgFTtGBvAvgKDgA8AHEAJ1m3U1lwG4g

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by EvanCahill**
Const enums should be allowed to be exported using an export declaration. The fix is to remove an incorrect check that restricts exporting const enums in export declarations to work only when `--preserveConstEnums` is true.

Fixes #33060

### CODE REVIEW

**Comment by weswigham** [comment]
Actually, you do _need_ `preserveConstEnums` on. If you don't, the enum declaration will be erased, but the export declaration will still emit something along the lines of
```js
exports.MyConstEnum = MyConstEnum;
```
which is going to throw at runtime.

**Comment by EvanCahill** [comment]
I don't see that as the behavior currently. It is correctly eliding the const enum export.

**Comment by weswigham** [comment]
Oh, hum. I guess if we're already eliding the export then it's not so bad.

**Comment by EvanCahill** [comment]
I'm happy to add another test case to explicitly test that const enums are not emitted on re-export without `preserveConstEnums`.

Also I'd really love this to go into 3.7 if everything looks good since this behavior is a regression from 3.5.

**Comment by weswigham** [comment]
A new test'd be great, yeah.

**Comment by EvanCahill** [comment]
Done.

**Comment by weswigham** [comment]
cc @RyanCavanaugh do we wanna do anything with this for 3.7?

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to `release-3.7` and LKG

**Comment by DanielRosenwasser** [comment]
Ugh, come on, ignore the backticks you jerk robot.

@typescript-bot cherry-pick this to release-3.7 and LKG

**Pull request merged**
