### PR TITLE
Remove duplication from transformers

### LINKED ISSUE #28310: API: Make public internal chainBundle
**TypeScript Version:**  3.2.0-dev.201xxxxx

Currently we can't work with bundles in transformers, but built-in transformers use `chainBundle` to iterate over sourceFiles inside them

```
return chainBundle(transformSourceFile);
```

So, we need something similar or opened `chainBundle` to use in the custom transformers

### PR DESCRIPTION
**Pull request by danielbodart**
Fixes #28310, #24459, cevek/ttypescript#29

This pull requests removes duplication (chainBundle) from all the transformer functions and moves it to a single place (getTransformers). 

This will then fix custom transformers so they work with single outFile compiler option (Bundle being passed) and gets rid of the need for chainBundle to be exposed.

This pull request is a refactoring to remove duplication and increase consistence by having a single way all transformers are used.

### CODE REVIEW

**Comment by danielbodart** [comment]
I think this might also fix #24459

**Comment by danielbodart** [comment]
Also replaced createBundle in chainBundle with version from transformTypeScript so it correctly handles source maps. Then removed from transformTypeScript so no duplication

**Comment by weswigham** [comment]
It's worth noting that declaration after-transformers still won't be auto-chained (they don't use `getTransformers`, ofc) - this also precludes the ability for any custom transformer to specifically handle bundles (potentially by unbundling or by adding prepends).

**Comment by weswigham** [comment]
(I think the other option proposed in the linked issue:
> 1. leave everything as it is and write in the documentation that the transformer developer should support Bundle nodes.

Is probably better - we should update the docs to say that a custom transformer should handle bundle nodes and then expose `chainBundle` for use)

**Comment by danielbodart** [comment]
@weswigham I'm not sure I agree. You are making the normal use case suffer for the exception. Every single custom transformer that I have come across in the wild (mainly from the https://github.com/cevek/ttypescript home page) would need to be updated rather than they just work as expected. 

I would argue it would be better to have a separate interface/contract for bundle transformers (if anyone actually wanted to do that). I'd probably make the method take a Bundle and return a Bundle, rather than this passing the complexity down with union types.

**Comment by danielbodart** [comment]
On the subject of declaration after-transformers, they already have a different type signature so it's probably too late to fix them but if it was my code I would simplify them and separate Bundle transformation as I mentioned previously.

**Comment by weswigham** [comment]
Except the declaration transformer meaningfully transforms bundles, so it actually cares about them (quite a lot). I'm simply stating that it's not unlikely that a set of other transforms may exist which also care about weather or not files are being bundled and would like to manipulate that bundle.

**Comment by rbuckton** [comment]
> this also precludes the ability for any custom transformer to specifically handle bundles 

This is a very good point. This could potentially be a breaking change for custom transforms.

**Comment by danielbodart** [comment]
Hmmm I don't think that's correct, right now customer transformers (excluding decorators as they have a different contact) can't transform bundles at all. They are broken when bundles are used. If you changed the signature for them you would break every single one out there.

This change is backward compatible, fixes them so they all work with bundles correctly with zero change and gets rid of a bunch of duplication.

I would argue creating bundle transformers should be a spare separate method on custom transformers but it's out of scope for this change.

**Comment by danielbodart** [comment]
@rbuckton Any more thoughts on this?

**Comment by weswigham** [comment]
Like, if we're currently passing bundles to transformers, the type declaration is what's wrong, IMO - it should reflect that we're passing bundles.

**Comment by rbuckton** [comment]
Ideally a custom transformer *should* be able to take a bundle, but I agree that adding `Bundle` to a union is problematic. Instead of the changes mentioned in this PR, we should consider wrapping the custom transformers to handle bundles, since our API today only allows custom `before` and `after` transformers for `SourceFile`:

```ts
    export interface CustomTransformers {
        /** Custom transformers to evaluate before built-in .js transformations. */
        before?: TransformerFactory<SourceFile>[];
        /** Custom transformers to evaluate after built-in .js transformations. */
        after?: TransformerFactory<SourceFile>[];
        /** Custom transformers to evaluate after built-in .d.ts transformations. */
        afterDeclarations?: TransformerFactory<Bundle | SourceFile>[];
    }
```

We would need to consider a different mechanism to indicate whether a custom transformer supports `Bundle`, perhaps by modifying the definition as follows:

```ts
export type TransformerFactory<T extends Node> = (context: TransformationContext) => Transformer<T>;

export type Transformer<T extends Node> = (node: T) => T;

export type CustomTransformerMapFactory = (context: TransformationContext) => CustomTransformerMap;

export interface CustomTransformerMap {
  // custom transformers *must* support SourceFile transformation at a minimum
  [SyntaxKind.SourceFile](node: SourceFile): SourceFile; 
  // custom transformers *may* support Bundle transformation
  [SyntaxKind.Bundle]?(node: Bundle): Bundle;
  // other future opt-in transformations...
}

export type CustomDeclarationTransformerMapFactory = (context: TransformationContext) => CustomDeclarationTransformerMap;

export interface CustomDeclarationTransformerMap {
  // custom declaration transformers *must* support SourceFile transformation at a minimum
  [SyntaxKind.SourceFile](node: SourceFile): SourceFile; 
  // custom declaration transformers *must* support Bundle transformation
  [SyntaxKind.Bundle](node: Bundle): Bundle;
  // other future opt-in transformations...
}

export interface CustomTransformers {
    before?: (TransformerFactory<SourceFile> | CustomTransformerMapFactory)[];
    /** Custom transformers to evaluate after built-in .js transformations. */
    after?: (TransformerFactory<SourceFile> | CustomTransformerMapFactory)[];
    /** Custom transformers to evaluate after built-in .d.ts transformations. */
    afterDeclarations?: (TransformerFactory<Bundle | SourceFile> | CustomDeclarationTransformerMapFactory)[];
}
```

**Comment by rbuckton** [comment]
I've submitted #31301 as an alternative to this approach.

**Comment by rbuckton** [comment]
Closing this PR as #31301 has been merged

**Pull request closed without merging**
