### PR TITLE
fix(39245): Weird related diagnostic for missing rest parameter arguments

### LINKED ISSUE #39245: Weird related diagnostic for missing rest parameter arguments
```ts
function partialCall<T extends Arr, U extends Arr, R>(f: (...args: [...T, ...U]) => R, ...headArgs: T) {
    return (...b: U) => f(...headArgs, ...b)
}

const foo = (x: string, y: number, z: boolean) => {}

const f3 = partialCall(foo, "hello");

f3();
```

We get an error like

```ts
Expected 2 arguments, but got 0.
(related): An argument for 'b' was not provided.
```

`b` refers to the rest parameter of the arrow function in `partialCall`. This behavior is misleading or incorrect. Any of the following would be improvements.

1. Switch to a diagnostic that reflects a more appropriate actual parameter name "An argument for 'y' was not provided."
1. Switch to a new diagnostic: "Arguments for the rest parameter 'b' were not provided."
1. Remove the related diagnostic in this case.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #39245

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Part of me is unsure about this because in some places these paramerters aren't explicitly declared (like in the original sample).

But let's try it out!

@typescript-bot pack this

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Ok, will wait for your feedback.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I've merged master, you can try to pack it

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I'm not sure why @typescript-bot failed to pack these changes :confused:.

**Comment by sandersn** [comment]
@DanielRosenwasser this looks fine to me. Do you still want to play with it interactively before I merge it?

**Comment by sandersn** [comment]
I'm going to update from master and then merge this.

**Pull request merged**
