### PR TITLE
Node.insertBefore() requires 2 arguments

### LINKED ISSUE #8320: Node.insertBefore() second parameter is not optional
This is in the definition of a DOM `Node`, from `lib.d.ts`:

    insertBefore(newChild: Node, refChild?: Node): Node;

According to it, `refChild` is optional, which is not true according to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore) and certainly causes a runtime error in Google Chrome.

### PR DESCRIPTION
**Pull request by ntrrgc**
Fixes #8320

### CODE REVIEW

**Comment by kitsonk** [comment]
As @mhegazy stated in #8320 by [pointing you to the documentation](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes), PRs to `lib.d.ts` don't go here, they go in into [Microsoft/TSJS-lib-generator](/Microsoft/TSJS-lib-generator)

**Comment by ntrrgc** [comment]
I don't know how to use that repository. I have edited `overridingTypes.json` like this:
```
diff --git a/inputfiles/overridingTypes.json b/inputfiles/overridingTypes.json
index 4e01ad3..0750126 100644
--- a/inputfiles/overridingTypes.json
+++ b/inputfiles/overridingTypes.json
@@ -1,6 +1,12 @@
  [
     {
         "kind": "method",
+        "interface": "Node",
+        "name": "insertBefore",
+        "signatures": ["insertBefore(newChild: Node, refChild: Node): Node"]
+    },
+    {
+        "kind": "method",
         "interface": "HTMLCollection",
         "name": "item",
         "signatures": ["item(index: number): Element"]
```

Then I have run `./build.sh`. This is what I get.
```
No version specified. Downloading latest stable.
Paket.exe 2.63.2 is up to date.
Paket version 2.63.2.0
0 seconds - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target Test:
<== Test
   <== Run

The resulting target order is:
 - Run
 - Test
Starting Target: Run 
Finished Target: Run
Starting Target: Test (==> Run)
Running build failed.
Error:
System.Exception: 
Test failed: dom.generated.d.ts is different from baseline file.
  at FSI_0001.Build+clo@24-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) <0x41c76000 + 0x0021f> in <filename unknown>:0 
  at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x41c2d810 + 0x00023> in <filename unknown>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) <0x41c23360 + 0x000ca> in <filename unknown>:0 

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Run        00:00:15.1863338
Total:     00:00:15.2422872
Status:    Failure
---------------------------------------------------------------------
  1) System.Exception: 
Test failed: dom.generated.d.ts is different from baseline file.
  at FSI_0001.Build+clo@24-1.Invoke (Microsoft.FSharp.Core.Unit _arg1) <0x41c76000 + 0x0021f> in <filename unknown>:0 
  at Fake.TargetHelper+targetFromTemplate@195[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) <0x41c2d810 + 0x00023> in <filename unknown>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetTemplate`1 target) <0x41c23360 + 0x000ca> in <filename unknown>:0 
---------------------------------------------------------------------

```

**Comment by mhegazy** [comment]
@zhengbli can you @ntrrgc getting his PR in

**Comment by mhegazy** [comment]
as @kitsonk mentioned, these files are autogenarated and are not hand edited. please submit your PR to https://github.com/Microsoft/TSJS-lib-generator/pulls and @zhengbli can help you with any issue you run into.

**Comment by zhengbli** [comment]
@ntrrgc you see the error because the baseline is different from your new generated lib files, which is what you want. Now you can go to the `generated` folder in the same directory, and view the diff between the baseline and your generated results. If things look right, update the baseline files and send a PR to that repo. Let me know if you have other questions.

**Comment by ntrrgc** [comment]
Here it's the new PR, I hope it's fine this time. https://github.com/Microsoft/TSJS-lib-generator/pull/95

Editing the baseline fine was a bit painful, as it had no ending newline (which many editors automatically add), which apparently is significant to the build script. I had to remove it with `git checkout -p -- baselines/dom.generated.d.ts`

**Pull request closed without merging**
