### PR TITLE
Drop support for defunct Chakra host

### PR DESCRIPTION
**Pull request by amcasey**
I'm experimenting with some host changes, so this seems like a good time to tidy up (rather than update) the Chakra host.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Don't merge this until post-RC please.

**Comment by amcasey** [comment]
@DanielRosenwasser It's not an experiment - this code is dead.  It came up because I would have had to update it in my experiment. :smile:  I'm happy to wait though.

**Comment by weswigham** [comment]
The code is "dead" except we've heard of non-chakra consumers in, eg, the browser, providing the `ChakraHost` global to our spec in order to provide `sys` in the past, so removing it is still probably a break.

**Comment by amcasey** [comment]
@weswigham I'll close this then?

**Comment by weswigham** [comment]
I dunno - we might be able to remove it, we just have to be aware that it's a break.

**Comment by amcasey** [comment]
@DanielRosenwasser @weswigham How do we feel about this?

**Comment by RyanCavanaugh** [comment]
I'm pretty comfortable removing it at this point.

@mihailik FYI in case this is how you were shimming

**Pull request merged**
