### PR TITLE
DOM update 2024-04-16

### PR DESCRIPTION
**Pull request by sandersn**
For 5.5 beta

- dom.asyncIterable adds `[Symbol.asyncIterator]` and `values`
- Some additions in Visibility types
- Minor changes to gamepad types.
- New ReadableStream iterator options
- Some properties flip between optional/required
- Add `AbortSignal.any` method
- Add new CSS\*Rules
- Add `Document.parseHTMLUnsafe`, `ShadowRoot.setHTMLUnsafe`
- Minor changes to documentation.
- HTMLSelectElement.type is now `"select-one" | "select-multiple"` instead of `string`
- new performance type `LargestContentfulPaint`

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by sandersn** [comment]
Requires slightly more memory presumably because it adds a few more types and properties.

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by jakebailey** [comment]
Ah, webrtc, our old friend

**Comment by sandersn** [comment]
Yeah, that's expected, since types/webrtc is supposed to be a superset of whatever's in the DOM.

I'll merge this tomorrow after I merge all the test baseline conflicts. Is this the result of the new performance stats? Or maybe it's the generated-type spans.

**Comment by jakebailey** [comment]
> Is this the result of the new performance stats? Or maybe it's the generated-type spans.

Both, probably.

**Pull request merged**
