### PR TITLE
Removing some unnecessary methods from host and function parameters

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]
LGTM if you're okay with the API break. Yay 5.0.

**Comment by sheetalkamat** [comment]
I think its ok to break the API because its removal of methods that builder no longer needs so should be ok i think. Also havent found any usage that directly use this.

**Comment by sheetalkamat** [comment]
cc: @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Would you be able to document this in https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes ? If you need a review, we have https://github.com/microsoft/TypeScript-wiki

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
