### PR TITLE
lib Fix Part 6/6 – Array.isArray

### LINKED ISSUE #17002: Array.isArray type narrows to any[] for ReadonlyArray<T>
**TypeScript Version:**  2.4.1

**Code**

```ts
declare interface T {
  foo: string;
}

const immutable: T | ReadonlyArray<T> = [];

if (Array.isArray(immutable)) {
  const x = immutable; // Any[]  - Should be ReadonlyArray<T>
} 

const mutable: T | Array<T> = [];

if (Array.isArray(mutable)) {
  const x = mutable; // T[]
} 
```

**Expected behavior:** Should type narrow to ```ReadonlyArray<T>```, or at the very least ```T[]```.

**Actual behavior:** Narrows to ```any[]```.  Doesn't trigger warnings in noImplicitAny mode either.

### LINKED ISSUE #32497: Array.isArray refinement loses the array's type
I realize there are  a number of related issues. However, some where about ReadonlyArray, some didn't see directly related at all even though it was pointed there.

Also, this is a much smaller example, just a single line of code really:

[Playground link](http://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAEwKYFs4AoZQFyICSUqATgIYBGANqgDxgjqVkB8AlAY82QNoC6iAN4AoROMQQEAZyiJypCgE9EAXkQBBReSUA6GNK3KcUdogD8iXIgK9d93PwDcIsRID07xABFU1GCwUJFy6tGAA5lAAFlbS8oiypDARiOio0XDIADSIlCByYHCIZKRwpLmoEOQg0qiIcMCIUEoADnUARORgSu2IwGWIYG7ipOkgpEgKyrro5C1YSKqsg6GoEdHsLgC+IkA)

```js
function demo(it: Iterable<number>): number[] {
    // THIS LINE: "array" is any[]
    const array = Array.isArray(it) ? it : [...it];
    // Deliberate: n.length is a string method, but no error because of type "any" for n
    return array.map(n => n.length);
}
```

I know people will point to this ir that implementation or design decision detail &mdash; honestly guys, you got it REVERSED. The tool should serve the purpose, not the other way around!

That the array loses all it's type information in such a simple example is A BUG.

And **it is possible** to do much better: [See here!](https://flow.org/try/#0GYVwdgxgLglg9mABAEwKYFs4AoZQFyICSUqATgIYBGANqgDxgjqVkB8AlAY82QNoC6iAN4AoROMQQEAZyiJypCgE9EAXkQBBReSUA6GNK3KcUdogD8iXIgK9d93PwDcYiQHo3iACKpqMFhQkXLq0YADmUAAWVtLyiLKkMOGI6KhRcMgANIiUIHJgcIhkpHCkOagQ5CDSqIhwwIhQSgAOtQBE5GBKbYjApYhgruKkaSCkSArKuujkzVhIqqwDIajhUewuAL4iQA) I'm only pointing this out because at times the responses sound like "We tried everything but it is just not possible" when the competition shows that it *is* actually quite possible.

### LINKED ISSUE #33700: Array.isArray refinement loses the array's type
I realize there are a number of related issues. However, some where about ReadonlyArray, some didn't see directly related at all even though it was pointed there.

Also, this is a much smaller example, just a single line of code really:

[Playground link](http://www.typescriptlang.org/play/index.html#code/GYVwdgxgLglg9mABAEwKYFs4AoZQFyICSUqATgIYBGANqgDxgjqVkB8AlAY82QNoC6iAN4AoROMQQEAZyiJypCgE9EAXkQBBReSUA6GNK3KcUdogD8iXIgK9d93PwDcIsRID07xABFU1GCwUJFy6tGAA5lAAFlbS8oiypDARiOio0XDIADSIlCByYHCIZKRwpLmoEOQg0qiIcMCIUEoADnUARORgSu2IwGWIYG7ipOkgpEgKyrro5C1YSKqsg6GoEdHsLgC+IkA)

I know people will point to this ir that implementation or design decision detail — honestly guys, you got it REVERSED. The tool should serve the purpose, not the other way around!

That the array loses all it's type information in such a simple example is A BUG.

And it is possible to do much better: See here! I'm only pointing this out because at times the responses sound like "We tried everything but it is just not possible" when the competition shows that it is actually quite possible.

Related(?): #17002

### LINKED ISSUE #41808: 4.1 Array.isArray breaking change review
Categorizing breaks we've seen from this

#41658
```ts
type Comparable = string | undefined | Array<string>;
export function check<T extends Comparable>(a: T) {
	if (Array.isArray(a)) {
		// 4.0: m: string
		// 4.1: Error, cannot index
		const m = a[0];
	}
}
```
#41610, #41714
```ts
const aggregatedResults: (number[] | null | 'loading')[] = [[1, 2], null, [3, 4], 'loading', [5, 6]]
// 4.0: onlyTheArrays: number[][]
// 4:1 Error, no overload matches this
const onlyTheArrays = aggregatedResults.filter<number[]>(Array.isArray) // number[][]
```

### LINKED ISSUE #43247: Array.isArray works bad with ReadonlyArray
**TypeScript Version:**  4.3.0-dev.20210315

**Search Terms:** array isArray readonly

The first problem is that `Array.isArray` lets us violate `readonly` modifier and push values to `ReadonlyArray`:

```ts
declare const data: ReadonlyArray<any>

if (Array.isArray(data)) {
  // Expected: Error
  data.push(123)
}
```

The second problem is that `Array.isArray` doesn't filter out `ReadonlyArray` type:

```ts
declare const data: Record<string, any> | ReadonlyArray<any>

if (!Array.isArray(data)) {
  // now: readonly any[] | Record<string, any>
  // expected: Record<string, any>
  const alias = data
}
```

### LINKED ISSUE #49773: A list of suggested update to TypeScript's lib
## lib Update Request

While working on [uhyo/better-typescript-lib](https://github.com/uhyo/better-typescript-lib), I've found couples of issues in the built-in lib. While reflecting some of the changes there will cause compatibility issues and they are not included in the list below, others are worth reporting because either they are serious or they are not breaking changes. Here is the list:

### es2015.collection.d.ts
- [x] `WeakMapConstructor`: The type of `entries` should change from `readonly [K, V][] | null` to `readonly (readonly [K, V])[] | null` to keep it consistent with `MapConstructor`

### es2015.core.d.ts
- [x] `{Array<T>, ReadonlyArray<T>}.find`:
  - The `this` parameter of the first parameter in the first overload is incorrectly typed `void`, which should be removed
  - Missing documentation for the second overload
- [x] `ArrayConstructor.from`: The first parameter should be renamed `source` to keep consistency across multiple overloads from other lib files. In `es2015.iterable.d.ts` it's written `iterable: Iterable<T> | ArrayLike<T>` and that's misleading. It's also named `source` in the [spec text](https://tc39.es/ecma262/#sec-array.from). (The documentation should be modify to `an array-like or iterable object` too to keep it the same across all files)
- [ ] ~`NumberConstructor.{isFinite, isInteger, isNaN, isSafeInteger}`: Per the [spec](https://tc39.es/ecma262/#sec-properties-of-the-number-constructor), the return type can be changed to the type predicate `number is number`~ (Excluded unless https://github.com/microsoft/TypeScript/issues/15048 resolves)
- [x] `ObjectConstructor.assign`: All parameters but the first should be made writable (`{ -readonly [P in keyof T]: T[P] }`).
- [x] `ObjectConstructor.{getOwnPropertySymbols, setPrototypeOf}`: 🟠 The first parameter should extends `{}`. See the **es2017.object.d.ts** section below
- [x] `String.normalize`: 🟠 Per the [spec](https://tc39.es/ecma262/#sec-string.prototype.normalize), the second overload should be removed to prevent a runtime error. The first parameter should then be made optional because it's defaulted to `"NFC"`.

### es2015.iterable.d.ts
- [x] `{ArrayConstructor, %TypedArray%Constructor}.from`: See the **es2015.core.d.ts** section above

### es2015.reflect.d.ts
Crossed out unless @uhyo thinks them worth changing and gives some illustrations.
- [ ] ~`Reflect.construct`: `newTarget` can be widen to `any`~
- [ ] ~`Reflect.getPrototypeOf`: The return type can be narrowed to `object`. It's impractical to get a `null` here~
- [ ] ~`Reflect.setPrototypeOf`: `proto` can be widen to `any`~

### es2015.symbol.wellknown.d.ts
- [ ] ~`Array<T>[Symbol.unscopables]`: Should be a record.~ (Fix already available in https://github.com/microsoft/TypeScript/pull/42566)

### es2017.object.d.ts
- [x] `Object.getOwnPropertyDescriptors`: 🟠 Per the [spec](https://tc39.es/ecma262/#sec-object-constructor), these methods start with either a `ToObject` or `RequireObjectCoercible` operation, which throws a `TypeError` with a nullish value. Starting from TypeScript 4.8 with https://github.com/microsoft/TypeScript/pull/49119, `{}` now precisely represents any nullish value. Thus, the first parameter of these methods should now be typed `{}` to prevent runtime errors.

### es2019.array.d.ts
- [x] `{Array<T>, ReadonlyArray<T>}.flatMap`: The `This` type parameter should be removed to keep consistency with other array prototype methods in the current library

### es2020.bigint.d.ts
- [x] `%TypedArray%.{every, find, findIndex, some}`: The return type of the first parameter can be widen to `any` to keep consistency with other array prototype methods
- [x] `%TypedArray%Constructor.from`: Missing documentation for the second overload. Also see the **es2015.core.d.ts** section above

### es2021.string.d.ts
- [x] `String.replaceAll`: missing `{ [Symbol.replace] }` overloads. It should be defined exactly the same as `String.replace` (The documentation should be modify to `A string or RegExp search value` too to keep it the same across all files)

### es2022.object.d.ts
- [x] `Object.hasOwn`: Per the [spec](https://tc39.es/ecma262/#sec-object.hasown), `o` can be widen to `{}`

### es5.d.ts
- [x] `ObjectConstructor.{getPrototypeOf, getOwnPropertyDescriptor, getOwnPropertyNames}`: 🟠 The first parameter should extends `{}`. See the **es2017.object.d.ts** section above
- [x] `{CallableFunction, NewableFunction}.apply`: Missing documentation for the second overload
- [x] `{CallableFunction, NewableFunction}.bind`: Consider rewrite it like [what we've done](https://github.com/uhyo/better-typescript-lib/blob/2bcb3179c255f50443ac437ed888a696b0adb98a/lib/lib.es5.d.ts#L157-L183)
- [ ] `{Array<T>, ReadonlyArray<T>}.every`: 🟠 The return type of the first overload can be typed `this is { [K in keyof this]: S }` to support tuples. ~Unlike other solutions, this change is small enough that it should not break anything.~ **It does affect some important tests, so a separate PR will be opened.**
- [ ] `ReadonlyArray<T>.map`: 🟠 The return type can be typed `{ -readonly [K in keyof this]: U }` to support tuples. **Will be in the follow-up PR**
- [ ] `Array<T>.map`: 🟠 The return type can be typed `{ [K in keyof this]: U }` to support tuples. **Will be in the follow-up PR**
- [x] `{Array<T>, ReadonlyArray<T>}.{reduce, reduceRight}`: Missing documentation for the second overload
- [x] `%TypedArray%.{find, findIndex}`: The return type of the first parameter can be widen to `any` to keep consistency with other array prototype methods
- [x] `%TypedArray%Constructor.from`: See the **es2015.core.d.ts** section above

##### 🟠 Breaking Changes (non-exhaustive)

If the TypeScript Team is fine with certain of these changes, I am happy to open a PR for it.

Thanks for reading till the end. That is all.

---

_P.S._ I am not sure if I shouldn't put all of the above into a single issue, but opening numerous issues to reflect all of these suggestions will be too many for me. I wonder how many PRs would be comfortable to the Team and how should I split it if I'm gonna work on this.

### PR DESCRIPTION
**Pull request by graphemecluster**
## General Information
PR separated out from #49855, because there might be some members expecting smaller PRs. As mentioned in the comments from the big PR, whether to review a single, large PR or 6 smaller PRs is up to the TypeScript Team to decide. I couldn't have found a better way for this; hopefully this will not bring any trouble to the Team.

This PR partially fixes #49773.
For details and the track list about the changes, please see #49773.

## Part 6/6, Array.isArray

Fix #17002
Actually fix #32497
Fix #33700
Fix #41808
Actually fix #43247

This PR supersedes #48228 as it fails to address `readonly number[]`.
~I am confident to this solution.~
**Edit: I guess I must retract this. See the results below. 😔**

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot user test this

**Comment by sandersn** [comment]
We tried this a couple of years ago; I don't remember what problems it ran into but I don't think #48228 was the only attempt.

**Comment by graphemecluster** [comment]
That's bad; it seems that the checker really hate `T extends readonly any[] ? T` that line.

**Comment by graphemecluster** [comment]
Can I use the TypeScript bot?
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot user test this

**Comment by graphemecluster** [comment]
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot user test this

**Comment by sandersn** [comment]
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot perf test this faster

**Comment by graphemecluster** [comment]
Heck no. It seems that without making it looser it won’t be a solution.

**Comment by graphemecluster** [comment]
I've just tinkered with it a bit. @sandersn Could you please give it another try?

**Comment by graphemecluster** [comment]
Actually most of the cases above just work by adding an `extends any` constraint on the generic parameter (see the test cases I added). Perhaps it’s a separated but related problem. @sandersn, or perhaps @RyanCavanaugh, sorry to bother you again, but could you please inspect this?

**Comment by sandersn** [comment]
@graphemecluster can you explain what the failures are like that would have been fixed by adding `extends any`? 4.8 did make unconstrained type parameters implicitly extend `unknown` instead of `{}`, and a common workaround was to add an explicit `extends any`. Maybe that's related.

Could you also add a detailed explanation of the new type of `isArray`? I read the type and couldn't understand the reason for almost any of its intricacies.

**Comment by graphemecluster** [comment]
@sandersn
A rough explanation looks like:
```ts
type ToArray<T> =
    // Distribute it
    T extends any ?
        (
            // if T == any, return any[]
            true extends false & T ? Extract<any[], T> : 
            // if T is an array-like or iterable object but not string or array, return U[]
            T extends string | readonly any[] ? never :
            T extends ArrayLike<infer U> | Iterable<infer U> ? Extract<U[], T> :
            // fallback to the bottom cases
            never
        ) | (
            // T == any has been covered above, so skip it
            true extends false & T ? never : 
            // if T is any Record-like object (object with only index signature),
            // intersect it with any array (this case should be rare, but a use
            // case was found in test suite and being added to the test case file)
            {} extends Required<T> ? T & any[] :
            // otherwise, for cases not being covered by the above, extract all
            // the arrays and readonly arrays out and dispose the remaining
            Extract<T, readonly any[]>
        )
    : never;
```
There are no special reasons to separate the cases into two, but without this TypeScript may not think the result type is an array and fires error on test cases `fc` and `fe` (also see the earlier test suite result).
The use of `Extract` is to make sure that the predicate is assignable to the parameter type. (Using intersection instead, the result would be awful.)

Actually using `extends unknown` instead of `extends any` in test cases `ff` and `fg` does not affect the result at all, but it's not the case when the constraint is removed. That means there must be some problems with generic parameters without constraint in TypeScript.

**Comment by graphemecluster** [comment]
I just noticed that replacing `Extract<T, readonly any[]>` with `T extends readonly any[] ? T : never` will make test cases `fc` and `fe` fail. I can hardly understand why.

**Comment by sandersn** [comment]
My feeling is that this problem is too complex to have a fix that I'm comfortable shipping in the standard lib. At least one that doesn't break existing code. 

If you can show that there aren't going to be many breaks across the ecosystem of packages, and that compilation won't slow down, it would still be worthwhile. But I think that's too much effort for this.

**Comment by graphemecluster** [comment]
@sandersn If possible, might you try running the test suite in 4.7.4 before #51242 is solved?

**Comment by sandersn** [comment]
I talked with Ryan about this again, and we don't think there's any way that a conditional return type will work. Specifically, it won't be usable in higher-order, generic uses. But it's complex enough that there are likely other corner-case failures I haven't thought of. I think this PR should be closed.

However, we want to work on the other lib fix PRs and bring them to the Typescript design meeting after finding out how well they work on existing code. I'll start with the smallest one and start user tests, etc.

**Comment by graphemecluster** [comment]
Thanks for picking this up. Now that I agree eventually all solutions tinkering with the lib won’t be perfect, I am going to root around in the compiler for a better way out. Let’s close this PR until then.

**Pull request closed without merging**
