### PR TITLE
feat(37458): @ts-ignore quick fix should be switched to @ts-expect-error

### LINKED ISSUE #37458: `@ts-ignore` quick fix should be switched to `@ts-expect-error`
Today we provide a quick fix in JavaScript files (e.g. `.js`, `.jsx`) under `// @ts-check` and `checkJs` to suppress errors by adding a

```js
// @ts-ignore
```

comment. Now that we have `// @ts-expect-error` which errors in the presence of no errors, we should probably switch the quick fix over to use that instead.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #37458

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@a-tarasyuk thanks for jumping on this so quickly! We had some second thoughts about this and would like to get more user feedback on this before changing things -- it's not immediately obvious which is actually better, and `ts-expect-error` will cause a bit more churn/confusion than `ts-ignore` so we're going to hold off on this for the time being. Sorry for the confusion from our side.

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Thanks for the update.

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Thanks for the update 👍. Is there a label that helps to understand if an issue can be taken to work on?

**Comment by RyanCavanaugh** [comment]
@a-tarasyuk You were correct to open this PR because the bug was in Backlog. We just tagged it that way before actually agreeing on it - that was a metadata error on our part

**Pull request closed without merging**
