### PR TITLE
Improve inference for Promise.all of 'never[]'

### LINKED ISSUE #37856: `Promise.all` not removing `never[]` in catch narrowing
**TypeScript Version:**  3.8.3

**Search Terms:**

**Expected behavior:**
`broken` should have the same type as `working`.

**Actual behavior:**
`broken` has an added `never[]` type.

**Related Issues:**

**Code**

```ts
const gotoThen = Promise.resolve(123);
const gotoCatch = Promise.reject();

// const working: Promise<number[]>
const working = Promise.all([
    gotoThen
]).catch(() => [123]);

// const broken: Promise<never[] | number[]>
const broken = Promise.all([
    gotoCatch
]).catch(() => [456]);

// Promise { [ 123 ] } Promise { [ 456 ] }
console.log(working, broken);
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
const gotoThen = Promise.resolve(123);
const gotoCatch = Promise.reject();
// const working: Promise<number[]>
const working = Promise.all([
    gotoThen
]).catch(() => [123]);
// const broken: Promise<never[] | number[]>
const broken = Promise.all([
    gotoCatch
]).catch(() => [456]);
// Promise { [ 123 ] } Promise { [ 456 ] }
console.log(working, broken);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=15&pc=30#code/MYewdgzgLgBA5iKIAqALApmGBeGAFAJxAFsBLCdAOgPQhABsA3dACgEYAmAZgEoBuAFChIsBEgDCAQyjBUOfETIVq6AFbpgUFvwECA9HpjDoMAO4gCAa1Jg4ALgUly6ADxgArsQBG6AgG0AXQA+IXATcysbOHlCJ2VJenoWPwEYNPhEFAwwAQCeSmBpWRZtHCCYP04uPMF9Q2NYLyJLTAdYpVcwdGZ-AJgAHxgPb19AkIaYJpAWrFx250oEpJT0jIki1Fz8wplUEp4yioAWAFYANhrdA0cOmABvCpgqmD6AXxvne8fTs5eYV9CkAYVHoIDgLAi1lsABpJs1MPwgA)

### PR DESCRIPTION
**Pull request by rbuckton**
This adds overloads to `Promise.all` to improve treat a `Promise.all` for an array of type `never[]` as a `Promise<never>` rather than a `Promise<never[]>`.

Fixes #37856

### CODE REVIEW

**Comment by andrewbranch** [comment]
Makes sense to me, but should we run user tests?

@typescript-bot user test this

**Comment by andrewbranch** [comment]
There’s one relevant change: https://github.com/typescript-bot/TypeScript/pull/54/files#diff-ce8b151b649148d02935b814380073d7

**Comment by rbuckton** [comment]
Yeah, looking at this a little bit more, there really isn't a way to craft the overload list to get the correct result here.

**Comment by rbuckton** [comment]
Actually, I *may* have found a solution. I'll try that first before giving up on this line of thought...

**Comment by rbuckton** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
Even this doesn't work because it collides with `Promise.all<T>` in vscode for cases like `Promise.all<string[]>(...)` when the intended return type is `Promise<string[][]>`

**Comment by rbuckton** [comment]
I'm switching this to a draft PR for the time being while I consider other alternatives.

**Pull request closed without merging**
