### PR TITLE
Disallow --module with --out

### PR DESCRIPTION
**Pull request by weswigham**
In #1544 this has been discussed for awhile. The changes to make the basics of it happen are easy, but the repercussions are fairly large for our own code. Our own compiler and `projects` tests in particular both used `--out` with `--module`. Changing the `Jakefile` to fix our compiler was easy, changes to our projects tests are also complete. @DanielRosenwasser asked me to include this error in #4754, but it impacts our own infrastructure enough in a breaking-change kinda way that it warrants its own PR.

### CODE REVIEW

**Comment by weswigham** [comment]
@mhegazy:
> If we do not allow --out with --module, then all non-module files (i.e. no top level import/export) should be coerced in a module output. see #2937 for more details.

This has a curious interaction with how ES6 implicitly has modules sometimes, and may require either a breaking change in our parser API or a breaking change in our tsconfig spec or a breaking change in our behavior regarding ES6 and modules. One of them, depending on what we'd rather do. I think that part of this, specifically, should probably be filed as a seperate bug, after looking into it.

**Comment by weswigham** [comment]
Ping @DanielRosenwasser - I think this is complete as far as this PR is concerned. We'll need to file followup issues regarding implementation of @mhegazy's change and how it interacts with `--target es6`.

**Comment by mhegazy** [comment]
I would say let's do `--module` and `--out` working instead.

**Comment by mhegazy** [comment]
as discussed offline, let's close this and support --module and --out combination.

**Pull request closed without merging**
