### PR TITLE
conditional typing of resolve() in promise constructor

### LINKED ISSUE #11094: Promise can be resolved with undefined but not reflected in type
TS 2.0.3

``` ts
    new Promise<string>(resolve => {
        true ? resolve('foo') :  resolve()
    })
```

This returns a `Promise<string>`, however it is possible to call `resolve` with no value, meaning the return type is actually `Promise<string | undefined>` at runtime.

I'm not sure whether the return type should in fact be inferred as `Promise<string | undefined>` or whether the empty `resolve()` call should throw a compile error.

### PR DESCRIPTION
**Pull request by tvald**
Fixes #11094, #3356. Replaces the approach in #19633 with a conditional typing of `resolve()`:
```ts
resolve: T extends void
  ? (value?: PromiseLike<void>) => void
  : (value: T | PromiseLike<T>) => void
```

Much thanks to @ahejlsberg and @mhegazy for resolving #21756 and #21823 to make this possible!

### CODE REVIEW

**Comment by mhegazy** [comment]
@rbuckton can you take a look

**Comment by falsandtru** [comment]
@tvald When `Promise<void | T>`, `resolve` function won't be callable. You have to do just as follows.

```ts
    new <T extends void>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
    new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
```

**Comment by falsandtru** [comment]
My previous code is not extensible for classes in the current compiler. Fixed as follows.

```ts
    new <T>(executor: (resolve: [T] extends [void] ? (value?: T | PromiseLike<T>) => void : (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
```

**Comment by mhegazy** [comment]
Should be addressed by https://github.com/Microsoft/TypeScript/pull/22772

**Pull request closed without merging**
