### PR TITLE
Remove duplicate `emptyArray`s

### PR DESCRIPTION
**Pull request by andy-ms**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Where's the root one now? `core.ts`?

**Comment by weswigham** [comment]
@DanielRosenwasser There's one in `utilities` still.

**Comment by mihailik** [comment]
What's the rationale? It may be noticeably bad for performance, is the upside worth it?

Before the change:
```typescript
(function (ts) {
    var emptyArray = [];

    // ... use emptyArray as local variable

})(ts || (ts = {}));
var ts;
```

After the change:
```typescript
var ts;
(function (ts) {
    ts.emptyArray = [];
})(ts || (ts = {}));

(function (ts) {

    // use ts.emptyArray via 2 lookup from global namespace

})(ts || (ts = {}));

```

Each `emptyArray` use now adds 2 lookups starting from **global scope lookup**. Ouch!

`emptyArray` exists to improve performance over clean and simple `[]`. This change may have reverted much of that gain.

---

This looks similar to another well-meaning change in the name of technicality, that may end up harmful when considered in bigger context: <a href="https://github.com/Microsoft/TypeScript/pull/16646#pullrequestreview-47396091">ts.version should remain easily parseable</a> and <a href="https://github.com/Microsoft/TypeScript/pull/17014#discussion_r128501959">complexity that simplification caused</a>.

**Comment by andy-ms** [comment]
We alreay have such lookups for every other function in the codebase; we wouldn't copy the other contents from `utilities.ts` to the files where they're used just to avoid `ts.`.

**Comment by mihailik** [comment]
I'm sorry, can you please elaborate: what is the rationale here?

Even if you believe the downsides here are small, that's not a convincing reason to make an apparently arbitrary change.

**Comment by andy-ms** [comment]
The same thing appeared in multiple places. That always leads to problems. For example, the type of `emptyArray` should really be `ReadonlyArray<never>`, but a few of the declarations had it as `any[]`, which is definitely not safe. Life is easier if we can fix these things in only one place.

**Pull request merged**
