### PR TITLE
Revert "fix(45501): VS Code removes spaces between empty object literals even if insertSpaceAfterOpeningAndBeforeClosingEmptyBraces is true"

### PR DESCRIPTION
**Pull request by andrewbranch**
Reverts microsoft/TypeScript#45514

Decided we need two settings for this if we’re going to fix it, but also want to gauge demand for #45501 before doing anything.

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
My fault :confused:. What should be the name of the option for this case?

**Comment by andrewbranch** [comment]
Not your fault! Part of the problem is this option was just poorly named. We would probably want to deprecate it in favor of two new settings, probably something like `insertSpaceInEmptyObjects` and `insertSpaceInEmptyBlocks`.

**Comment by andrewbranch** [comment]
@mjbvz do you want us to pick this into 4.4.3?

**Comment by mjbvz** [comment]
Thanks @andrewbranch! Did this make it into 4.4? If so, yes I think we should included the revert in 4.4.3

**Comment by andrewbranch** [comment]
I’m sorry, I was confused, the change was not in 4.4. No cherry-pick needed then 👍

**Pull request merged**
