### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
moved gitter below , so readme looks good

Fixes #

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@ebbypeter

**Comment by vyaspranjal33** [comment]
@ahejlsberg

**Comment by vyaspranjal33** [comment]
@sandersn

**Comment by sandersn** [comment]
I don't think this is an improvement. The gitter badge is unobtrusive and the gitter channel is quite useful.

**Pull request closed without merging**
