### PR TITLE
spelling fixes (round 3)

### PR DESCRIPTION
**Pull request by jsoref**
(see commit message for list of changes)

### CODE REVIEW

**Comment by jsoref** [comment]
fwiw, these files are dirty (on master, even w/o my changes):
```
lib/lib.core.d.ts
lib/lib.core.es6.d.ts
lib/lib.core.es7.d.ts (this file isn't tracked)
lib/lib.dom.d.ts
lib/lib.d.ts
lib/lib.es6.d.ts
lib/lib.es7.d.ts (this file isn't tracked)
lib/lib.webworker.d.ts
lib/tsc.js
lib/tsserver.js
lib/typescript.d.ts
lib/typescript.js
lib/typescriptServices.d.ts
lib/typescriptServices.js
```

**Comment by DanielRosenwasser** [comment]
Hey @jsoref, do you mean that the files in `lib` have spelling issues? I think @yuit will be doing some work on modularizing `src/lib` so we should hold off on that to avoid any merge pains for both of you. :smile:

**Comment by DanielRosenwasser** [comment]
Also thanks, these bite-sized PRs are much easier to work with!

**Comment by jsoref** [comment]
@DanielRosenwasser I mean that when you run the build system, it overwrites files that are part of the repository with versions that aren't equivalent to the version under version control.

Normally, I'd expect the generated content to match the versioned content, or for it not to be versioned.

**Pull request merged**
