### PR TITLE
[Master] Do not emit ESModule marker if file is not external module

### PR DESCRIPTION
**Pull request by yuit**

### CODE REVIEW

**Comment by Kovensky** [comment]
What is an "external module"; a file that has `import` / `export`?

**Comment by mhegazy** [comment]
> What is an "external module"; a file that has `import` / `export`?

correct.

**Comment by brian428** [comment]
Just wondering if there's an ETA or target version for this fix?

**Comment by mhegazy** [comment]
this should be already in `typescript@next`. currently it is planned to be in TS 2.3

**Pull request merged**
