### PR TITLE
Do not hoist ambient declarations in System.js emit

### LINKED ISSUE #3106: Compiling to ES5 with module type system breaks declare.
ts
```
declare class Promise { }
export var foo = Promise;
```
js
```
System.register([], function(exports_1) {
	var Promise, foo;
	return {
		setters:[],
		execute: function() {
			exports_1("foo", foo = Promise);
		}
	}	
});
```
The important bit is the `var Promise`.  This hides the global `Promise` which makes code that tries to use it fail.
image
image

### PR DESCRIPTION
**Pull request by vladima**
fixes #3106

### CODE REVIEW

**Comment by vladima** [comment]
I think this fix should go into 1.5

**Comment by DanielRosenwasser** [comment]
Does #3110 cover cases for semi-ambient entities like const enums?

**Comment by vladima** [comment]
Yes, const enums should be handed by #3110

**Comment by DanielRosenwasser** [comment]
:+1:

**Pull request merged**
