### PR TITLE
Use 'Omit' instead of 'Pick<Exclude<...>>' for object rest

### LINKED ISSUE #30948: Use 'Omit' instead of 'Pick<Exclude<...>>' for object rest
```ts
function f<T extends { a, b }>(x: T) {
    let { a, b, ...rest } = x;
}
```

Today, we type `rest` as `Pick<T, Exclude<keyof T, "a" | "b">>`. We should try to type this as `Omit<T, "a" | "b">` if `Omit` is defined.

### PR DESCRIPTION
**Pull request by rpgeeganage**
Trying to deliver the Modification mentioned in https://github.com/Microsoft/TypeScript/issues/30948

Fixes #30948

### CODE REVIEW

**Comment by rpgeeganage** [comment]
@sandersn ,
This is the PR for https://github.com/Microsoft/TypeScript/issues/30948.
Please give me feedback, regarding the modification. 
Thank you.

**Comment by DanielRosenwasser** [comment]
Seems like the change is probably good. Now run `gulp baseline-accept` to update the test outputs.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser , 
Thanks a lot for the feedback. I'll run it and update PR.

**Comment by DanielRosenwasser** [comment]
Actually, I don't know if the change *is* appropriate because it will error if `Omit` isn't present. It's not clear if it should. There is a `getGlobalTypeOrUndefined`.

**Comment by DanielRosenwasser** [comment]
Mm, team seems to think that maybe we shouldn't even have the fallback.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
I'm sorry that I'm not clear about your comment. Can you please elaborate little bit if possible?

**Comment by rpgeeganage** [comment]
Ok, I can modify the code as follows.
```js
if (! omitTypeAlias) {
  return errorType;
}
return getTypeAliasInstantiation(omitTypeAlias, [source, omitKeyType]);
```
and get rid of the code from line `4949` to `4955`.

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
I changed the code. How can I fix the tests?
A sample error message is as follows.
```
The baseline file genericObjectRest.types has changed.
Error: The baseline file genericObjectRest.types has changed
```

**Comment by DanielRosenwasser** [comment]
Check out https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md

**Comment by rpgeeganage** [comment]
@DanielRosenwasser ,
Thanks. I fixed the `tests\baselines\reference`.

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Pull request merged**
