### PR TITLE
Use 1 consistent word for the same concept in diagnosticMessages.generated.json in ko locale

### LINKED ISSUE #51237: Use 1 consistent word for the same concept in diagnosticMessages.generated.json
# Suggestion

## 🔍 Search Terms

translation, korean, ko, consistent, concept

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ V ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ V ] This wouldn't change the runtime behavior of existing JavaScript code
* [ V ] This could be implemented without emitting different JS based on the types of the expressions
* [ V ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ V ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In 'lib/ko/diagnosticMessages.generated.json', "computed" is translated into either "계산된" or "컴퓨팅된".

I think it's better to use one consistent word for the same concept rather than using multiple similar words for it.

### PR DESCRIPTION
**Pull request by changwoolab**
Fixes #51237

Updated ko translation.

### CODE REVIEW

**Comment by jakebailey** [comment]
The source of these translations is actually in https://github.com/microsoft/TypeScript/tree/main/src/loc/lcl, which is what should be edited.

Though, I don't quite know what the policy is here (these are produced by a localization team as far as I'm aware).

**Comment by sandersn** [comment]
Last I checked, we are required to open an issue on an internal microsoft localisation team and copy changes there. I'll see if I can find it.

**Comment by sandersn** [comment]
https://ceapex.visualstudio.com/CEINTL/_workitems/edit/741815 tracks this internally, although it sounds like the translation budget is cut enough that it may not be fixed if it's not deemed high priority.

**Comment by sandersn** [comment]
Unfortunately, the internal bug was declined by the localization team on 15 November 2022.

**Pull request closed without merging**
