### PR TITLE
Make Iterable Map constructor argument optional

### LINKED ISSUE #37779: Type error for new Map from undefined Iterable
**TypeScript Version:**  3.8.3

**Search Terms:** Map MapConstructor Iterable Iterator

**Code**

```ts
let undefinedArray: [string, string][] | undefined;
const map1 = new Map(undefinedArray);

let definedInterable: IterableIterator<[string, string]> = new Set<string>().entries();
const map2 = new Map(definedInterable);

let undefinedIterable: IterableIterator<[string, string]> | undefined;
const map3 = new Map(undefinedIterable); // Type error here
```

**Expected behavior:**
Passes type check because `new Map(undefined)` is a valid call to the Map constructor.
**Actual behavior:**
```
No overload matches this call.
  Overload 1 of 4, '(iterable: Iterable<readonly [string, string]>): Map<string, string>', gave the following error.
    Argument of type 'IterableIterator<[string, string]> | undefined' is not assignable to parameter of type 'Iterable<readonly [string, string]>'.
      Type 'undefined' is not assignable to type 'Iterable<readonly [string, string]>'.
  Overload 2 of 4, '(iterable: Iterable<readonly [string, string]>): Map<string, string>', gave the following error.
    Argument of type 'IterableIterator<[string, string]> | undefined' is not assignable to parameter of type 'Iterable<readonly [string, string]>'.
      Type 'undefined' is not assignable to type 'Iterable<readonly [string, string]>'.
  Overload 3 of 4, '(entries?: readonly (readonly [unknown, unknown])[] | null | undefined): Map<unknown, unknown>', gave the following error.
    Argument of type 'IterableIterator<[string, string]> | undefined' is not assignable to parameter of type 'readonly (readonly [unknown, unknown])[] | null | undefined'.
      Type 'IterableIterator<[string, string]>' is missing the following properties from type 'readonly (readonly [unknown, unknown])[]': length, concat, join, slice, and 14 more.(2769)
```
**Playground Link:** https://www.typescriptlang.org/play/#code/DYUwLgBArgdgJiAZgSxiOBBATlghgTwC4IBtAZzC1QHMAaCCqmagXRJYgB9p4lV0A3ACgAxgHsYFCAFtcABwCMEALwQ0AdwgBZeQApYCFGkw4CASmFDQkQ-zgBJGGBB4ARqGL3nb0F5e4wMSwAHnJKGnpGGhYAPhU1EE0AZXBgqOYY3TMAOhAnKhAyLOFxSUhZOQAmeI1tPVtjR29cdxALIStwHgb0Px8QT2bWvoCg0PS6BnDmWK5uvmMSiSkKgGYaxLq5fV4jXqHQdqA

**Related Issues:** None

**Suggested Fix:**
The [`MapConstructor` interface in `es2015.iterable.d.ts`](https://github.com/microsoft/TypeScript/blob/15aff05ff6c18af36ab1d247a1f9412b7d7e5b16/src/lib/es2015.iterable.d.ts#L139) should accept a single optional argument.
```diff
diff --git a/src/lib/es2015.iterable.d.ts b/src/lib/es2015.iterable.d.ts
index 374aad9322..6f9b786c1d 100644
--- a/src/lib/es2015.iterable.d.ts
+++ b/src/lib/es2015.iterable.d.ts
@@ -137,7 +137,7 @@ interface ReadonlyMap<K, V> {
 }
 
 interface MapConstructor {
-    new <K, V>(iterable: Iterable<readonly [K, V]>): Map<K, V>;
+    new <K, V>(iterable?: Iterable<readonly [K, V]>): Map<K, V>;
 }
 
 interface WeakMap<K extends object, V> { }
```

### PR DESCRIPTION
**Pull request by JaredNeil**
Fixes #37779

### CODE REVIEW

**Comment by JaredNeil** [comment]
Anything needed to get this merged?

**Comment by sandersn** [comment]
@typescript-bot user test this
@typescript-bot test this
@typescript-bot run dt

**Comment by sandersn** [comment]
Looks like VS Code and Puppeteer fail to compile with this change.

**Comment by JaredNeil** [comment]
Is this possibly because this PR is now a couple months old? Should I try to rebase my changes on `master` first? If that's not likely to be the issue, are there instructions for running those tests myself to reproduce the issue?

**Comment by sandersn** [comment]
For VS Code, I just followed their instructions to clone and get started developing. Then I opened the file with the error. For puppeteer, you can probably skip that by running `gulp runtests --ru=user --t=puppeteer`, then opening the puppeteer repo at tests/cases/user/puppeteer/puppeteer/

**Comment by sandersn** [comment]
Puppeteer's error is of the form

```ts
const m = new Map();
const v = m.get('k')
v.push // 'push' not found on 'unknown'
```

Previously `m: Map<any, any>` and `v: any`, but now `m: Map<unknown, unknown>` and `v: unknown`. Overload resolution chooses a stricter overload now.

**Comment by sandersn** [comment]
It could be that `lib.es2015.iterable.d.ts` is loaded before `lib.es2015.collection.d.ts`, so the nullary overload matches first. You can try adding `new (): Map<any,any>` to es2015.iterable.d.ts as the first entry too.

**Comment by sandersn** [comment]
@JaredNeil did you want to keep working on this?

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.

**Pull request closed without merging**
