### PR TITLE
Use bright white for gutter foreground in pretty mode

### LINKED ISSUE #16567: Colored output looks bad on black-on-white terminals
TypeScript's `--pretty` output produces line numbers that show up as black-on-dark-gray when run on a terminal that is black-on-white.  See the number on the left here.  (Sorry for the giant picture, I run a hidpi screen.)

image

Suggested fix: if you set the background color in the output, also force the foreground color.  I guess here you want to force white.

Also note that the special colors 38 and 48 are available for "the terminal's default foreground/background color":
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

### PR DESCRIPTION
**Pull request by seanbright**
Fixes #16567

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Can you provide a screenshot of a light and dark theme please?

**Comment by seanbright** [comment]
@DanielRosenwasser, did some testing over the weekend and the background gray is different intensities on different terminals. In some case the foreground is readable and in other cases it is not. Going to put more thought into this.

**Comment by alexeagle** [comment]
@seanbright did you try Evan's suggestion:
Also note that the special colors 38 and 48 are available for "the terminal's default foreground/background color":
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by seanbright** [comment]
@alexeagle I don't see that information on the linked page. Even if it was there, I'm not sure what that would buy us. It might be better to just turn on reverse mode for the gutter but I haven't had a chance to experiment yet.

**Comment by seanbright** [comment]
Apologies, I won't have time to work on this in the near future.

**Comment by DanielRosenwasser** [comment]
No worries, thanks for the PR all the same.

**Pull request closed without merging**
