### PR TITLE
Fix definition of `Array.prototype[Symbol.unscopables]`

### PR DESCRIPTION
**Pull request by ExE-Boss**
<https://github.com/microsoft/TypeScript/pull/36540> was incorrectly applied to `lib/es2015.symbol.wellknown.d.ts` and thus got overwritten once the next **TypeScript** LKG lib was rebuilt.

<https://github.com/microsoft/TypeScript/pull/42566#issuecomment-781751656>:
> The second change is simply copying the `Symbol.unscopables` definition to `ReadonlyArray`, and making it so that it doesn’t need to be updated in the future, since when new methods get added to `%Array.prototype%`, they almost always also have to be added to `%Array.prototype[Symbol.unscopables]%` for compatibility with legacy code using the sloppy mode‑only `with` statement.

---

Actually fixes <https://github.com/microsoft/TypeScript/issues/34610>
Fixes <https://github.com/microsoft/TypeScript/issues/46616>

---

review?(@sandersn, @rbuckton)

### CODE REVIEW

**Review by sandersn — CHANGES_REQUESTED** [review]
Wait a minute. This changes more than #36540 does. What do the additional changes do?

**Comment by ExE-Boss** [comment]
@sandersn The second change is simply copying the `Symbol.unscopables` definition to `ReadonlyArray`, and making it so that it doesn’t need to be updated in the future, since when new methods get added to `%Array.prototype%`, they almost always also have to be added to `%Array.prototype[Symbol.unscopables]%` for compatibility with legacy code using the sloppy mode‑only `with` statement.

**Comment by sandersn** [comment]
I'd be happy to take the first two changes immediately: removing the extraneous `()`, and copying `unscopeables`' definition to ReadonlyArray. But I don't know enough about array method changes to evaluate the third. I'd recommend splitting the third change into a separate PR so @rbuckton can review it.

**Comment by MartinJohns** [comment]
Related: #46616

**Comment by graphemecluster** [comment]
Why it is still not merged? If not I am going to put this change in #49855.
@sandersn `[Symbol.unscopables]` is mutable – try adding and deleting properties in the devtools console.
And I don't think such a small change is worth 2 PRs.

**Comment by ExE-Boss** [comment]
@graphemecluster Probably because there are merge conflicts (again).

**Comment by graphemecluster** [comment]
Conflicts again :(

**Pull request merged**
