### PR TITLE
Baseline some watch related path determinations so its easy to track changes

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Comment by jakebailey** [comment]
That 25K line file is 5 MB; is there a more compact representation that could be used?

**Comment by sheetalkamat** [comment]
Tried to keep it readable but it helps i can split the tests further per osRoot?

**Comment by sheetalkamat** [comment]
Btw this should help me make saner changes so that i know i am doing right stuff  or not.
Going to use for #53591

**Review by jakebailey — APPROVED** [review]
Thanks for reducing the size; it turns out to matter over time since big blobs may not encode well (just like how just `lib` was inflating the checkout size by a lot).

**Comment by sheetalkamat** [comment]
And i can reduce it further by removing white spaces but it doesnt read well in BC when comparing diffs so ...

**Comment by jakebailey** [comment]
Ah, yeah, that would gain it all back. Would render identically in markdown anyhow!

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
