### PR TITLE
Fixed regression in generic signature instantiation with default type args

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/59490

complements the fix from https://github.com/microsoft/TypeScript/pull/59121 so the correct cloned type parameter is used as the inference target

cc @weswigham

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test it

**Review by weswigham — APPROVED** [review]
Needs a merge conflict resolved before it can be merged - but I'm starting to think it'd be nice to pull `sameMap(signature.typeParameters!, tp => tp.mapper ? instantiateType(tp, tp.mapper) : tp)` into a helper function like `getTypeParametersForMapper(signature)` for the two locations we use it (an inference context is a type mapper).

**Comment by Andarist** [comment]
done and done :)

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick to release-5.5

This is the same fix as #59121 which we also backported to 5.5.

**Comment by Bongdautay** [comment]
quaroibn1@gmail.com

**Pull request merged**
