### PR TITLE
Narrow references within optional chains in for-in loops

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/51941

### CODE REVIEW

**Comment by lazytype** [comment]
Can you add a test that the narrowing can be invalidated by an assignment?

```tsx
function f51(obj: Test5) {
   for (const key in obj.main?.childs) {
      if (obj.main.childs[key] === obj) {
        return obj;
      }
      obj.main = undefined;  // should invalidate narrowing
   }
   return null;
}
```

**Comment by Andarist** [comment]
@lazytype great catch! I don't know how to invalidate this properly though and currently, it's not invalidated. But it's also not invalidated for simpler cases that don't involve the optional chaining at all:
```ts
interface Test6 {
  a: number;
  b: string;
}

function f52(obj: Test6 | undefined) {
  obj.a; // error
  for (const _key in obj) {
    obj.a; // no error despite the invalidation on the line below
    obj = undefined;
  }
  return null;
}
```

A new issue about this should be raised (if there is no existing issue about it).

**Comment by lazytype** [comment]
Here's a case where invalidation works that might be helpful in uncovering how it works
```tsx
function f53(obj: Test) {
    if (obj.main) {
        for (let i = 0; i < 10; i++) {
            obj.main.childs
            obj.main = undefined;
        }
    }
   return null;
}
```

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Review by sandersn — APPROVED** [review]

**Pull request merged**
