### PR TITLE
Optimize eagerly calculating `CouldContainTypeVariables` during object type instantiation

### PR DESCRIPTION
**Pull request by weswigham**
Basically, this conditionalizes the carrying-forward of type variable containment checks within `getObjectTypeInstantiation` more. The existing check pulls the flags forward onto primitives/unions/intersections which may result from `instantiateMappedType` unconditionally. This means we may mark unions and intersections as possibly containing type parameters when they in fact cannot.

Noticed this while rereviewing #53246 while reviewing #54507

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Review by jakebailey — APPROVED** [review]
This looks good to me.

Should we backport this fix instead of #54507 to 5.1? Or does that feel too unsafe for a bugfix? (Mainly, are there actually performance _regressions_ in 5.1 due to the previous optimization sometimes being too conservative?)

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot test top100

Juuuust in case

**Comment by weswigham** [comment]
> Mainly, are there actually performance regressions in 5.1 due to the previous optimization sometimes being too conservative?

Probably, but the effect is small, as you can see.

**Comment by Jolg42** [comment]
@weswigham @jakebailey I wanted to mention here that it could be beneficial to backport this to 5.1, see for more details the following issue https://github.com/microsoft/TypeScript/issues/54549#issuecomment-1590852712

I'm trying to connect the dots, I hope this helps
Thanks for the good work 💚

**Pull request merged**
