### PR TITLE
Introduce .gitattributes file

### PR DESCRIPTION
**Pull request by jedmao**
PR https://github.com/Microsoft/TypeScript/pull/962 was reverted in commit https://github.com/Microsoft/TypeScript/commit/e179e0565cfb90c30dc219e49599547948bb2e10. This PR aims to fix the reported issues.

Refer to GitHub's [dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/) article for more information how to properly treat line endings in a project.

Ping @mhegazy

### CODE REVIEW

**Comment by csnover** [comment]
It would be swell for this to be committed. There are a ton of mixed line endings in the TS source, which my code editor helpfully corrects, making it a real pain to submit patches since they always have hundreds of line ending changes.

**Comment by DanielRosenwasser** [comment]
So the thing is, the only thing I'm willing to accept line ending normalization on is `src` and `scripts`.

Otherwise
* There are line endings in `tests` that are intentionally not normalized.
* `doc` will not be touched by anyone outside the team anyway, so it shouldn't be normalized.
* I don't believe we take in updated LKGs, so `bin` will not need to be normalized.

Everything on the top level seems to be fine too. This includes:

* .gitignore
* .npmignore
* .travis.yml
* CONTRIBUTING.md
* CopyrightNotice.txt
* Jakefile
* LICENSE.txt
* README.md
* ThirdPartyNoticeText.txt
* package.json

and if we introduce it,

* .gitattributes

To make sure this is optimal behavior, @mhegazy and I may try working out of our own branches for a bit with the appropriate `.gitattributes`

**Comment by jasonwilliams200OK** [comment]
This PR is outdated now. The repo already has .gitattributes. 

To the TypeScript team, please close the outdated PRs and issues. This brings clarity to the outsider about the status of project and probably encourage them to contribute.

More opened issues on a GitHub is usually considered as a sign of questionable software or unmaintained repository. You are doing good job tagging the issues, but unattended issues/PRs brings negative impact.

**Comment by jasonwilliams200OK** [comment]
Also, quite many opened issues in tracker are basically questions or confusions which have been addressed..

**Comment by danquirk** [comment]
The repo already has .gitattributes but not for the purposes in this PR. 

re:open issues we do try to stay on top of what should and shouldn't remain open. When we were on Codeplex there was an actual discussion forum which GitHub lacks. We've allowed people to use the issue tracker for some questions/discussions in lieu of that. Some are worth closing since they're simple questions with simple answers. Likewise some PRs are truly outdated and should be closed (and we may have missed some). Others are more open ended. The labels afford us the ability to triage as necessary. We generally just do this cleanup incrementally but we probably will get to the point where we need to set aside some time for a larger scale housecleaning effort.

**Pull request closed without merging**
