### PR TITLE
Remove doc folder (old archived spec and assets), word2md script

### PR DESCRIPTION
**Pull request by jakebailey**
Removed in this PR:

- The archived spec, in doc/PDF formats and associated images.
- The build scripts / task that convert from the word doc to markdown. I have no idea if this actually works post-mjs conversion.
- An old redirect for the handbook, which has long since been moved to the website.
- An old redirect for the wiki, which these days is right in the navbar of the repo.
- `logo.svg`, which appears to be unreferenced.

The only thing I'm actually worried about is `logo.svg` as maybe this is the canonical source for this file.

If we want these back, they're in the git history forever, so we can grab them if needed (and link to `release-4.9` if really required).

### CODE REVIEW

**Review by ahejlsberg — APPROVED** [review]
Feeling a bit nostalgic seeing this go, but as long as there is _some_ way to find the files again, I'm fine with it.

BTW, looks like our branding assets are kept [here](https://www.typescriptlang.org/branding/), so not too worried about `logo.svg`.

**Comment by jakebailey** [comment]
Funnily, `logo.svg` is used in one place... webpack's readme. Guess they'll have to move that somewhere else. `logo.svg` here is barely a logo, it's just the text "TypeScript".

**Comment by fatcerberus** [comment]
> An old redirect for the wiki, which these days is right in the navbar of the repo.

TIL there's a "Wiki" button in the navbar. 😄

**Comment by sandersn** [comment]
@jakebailey do you still need Daniel's review to merge this?

**Comment by jakebailey** [comment]
I'd prefer to have consensus that I'm not hurting anything/anyone by doing this; I have the deletion itch and this was one I sent as it removes a bunch of build code and a whole top-level directory.

**Comment by DanielRosenwasser** [comment]
I feel the same as Anders, but ultimately we can remove it.

**Review by DanielRosenwasser — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by yuhuung** [comment]
May I ask why these files like `doc/spec-ARCHIVED.md` are removed?

**Comment by jakebailey** [comment]
The spec was inaccurate, being asked about (even though it was inaccurate), and also meant we had to have and maintain some extra goofy build tasks to convert it from a word doc (!) to markdown.

**Pull request merged**
