### PR TITLE
Add fallback logic for generating signatures for unions of array members

### LINKED ISSUE #44373: .every() .find() .filter() methods fail with "This expression is not callable." error on union of array types
# Bug Report

### 🔎 Search Terms

- This expression is not callable
- none of those signatures are compatible with each other

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union types. I also reviewed previous related issues.

### ⏯ Playground Link

- .every() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdBAA3aABPC2BIOmQAXgA+Ugjfcm9mZCA)
- .filter() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJwAbaQtgSDpkAF4APlIw33JvZmQgA)
- .find() [does not work](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGLAF4eQbwLABQyxywAJgFzIgCuAtgEbQDchJyMmGVAzmFKADmrAgF9ChUJFiIUAIRpZcbEuSq1GLFcQaLuyPgJDDC4goQAUAbQC6yODzRdbyAD7IFWWwEoAdJxAyC2BIOmQAXgA+UlDfcm9mZCA)
- .reduce() also doesn't work, but there is already an [issue](https://github.com/microsoft/TypeScript/issues/44063) for that one. (Perhaps we should merge it into this?)

### 💻 Code

```ts
interface Fizz {
    id: number;
    fizz: string;
}

interface Buzz {
    id: number;
    buzz: string;
}

([] as Fizz[] | Buzz[]).filter(item => item.id < 5); 
```

### 🙁 Actual behavior

Compilation fails with the following error:
```
This expression is not callable.
  Each member of the union type '{ <S extends Fizz>(predicate: (value: Fizz, index: number, array: Fizz[]) => value is S, thisArg?: any): S[]; (predicate: (value: Fizz, index: number, array: Fizz[]) => unknown, thisArg?: any): Fizz[]; } | { ...; }' has signatures, but none of those signatures are compatible with each other.
```

### 🙂 Expected behavior

Compilation succeeds, as it does for [map and several other array functions](https://github.com/microsoft/TypeScript/issues/36390#issuecomment-852533093).

### 🔖 Useful links
- [Original issue](https://github.com/microsoft/TypeScript/issues/36390)
- [PR that closed original issue](https://github.com/microsoft/TypeScript/pull/31023)

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #44373

With this PR, when we see a type like `(A[] | B[])["member"]` and look for signatures on it, and find none, we reconstruct `(A | B)[]["member"]` and instead look up signatures on that. This _only_ applies to array and tuple types because, well, arrays are special. We treat them as covariant when they're not, and we know their collection-like behavior is consistent. This logic does not apply to any custom subtypes of arrays or array-similar things, like `UInt8Array` - those may have less or more type parameters that both make the reconstruction difficult and potentially break our expectations on how collection-element-like the type parameters are.

This allows things like this:
```ts
// @target: es6
interface Fizz {
    id: number;
    fizz: string;
}

interface Buzz {
    id: number;
    buzz: string;
}

([] as Fizz[] | Buzz[]).filter(item => item.id < 5);
([] as Fizz[] | readonly Buzz[]).filter(item => item.id < 5); 

([] as Fizz[] | Buzz[]).find(item => item);
declare function isFizz(x: unknown): x is Fizz;
([] as Fizz[] | Buzz[]).find(isFizz);
declare function isBuzz(x: unknown): x is Buzz;
([] as Fizz[] | Buzz[]).find(isBuzz);

([] as Fizz[] | Buzz[]).every(item => item.id < 5);

([] as Fizz[] | Buzz[]).reduce(item => item);

([] as [Fizz] | readonly [Buzz?]).filter(item => item?.id < 5);
```
to all work mostly like you'd expect (with maybe the caveat that output arrays are unions of elements within a single array rather than unions of array types).

I'd say that it's _possible_ to broaden this logic to other types using variance measurement logic and some hearty assumptions about how types behave based on their variance, but I feel much better about it making this an array-only change, at least right now.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this
@typescript-bot pack this

**Comment by ericbf** [comment]
> with maybe the caveat that output arrays are unions of elements within a single array rather than unions of array types

This is kind of a bug caveat, don’t you think? Filter, for example, never changes the type of the array, so for it to convert `A[] | B[]` to `(A | B)[]` is very weird and could be classified as a bug if merged as is, imo.

**Comment by weswigham** [comment]
@typescript-bot pack this

**Review by gabritto — APPROVED** [review]

**Comment by weswigham** [comment]
@andrewbranch @ahejlsberg I'm pinging more people for a second review :)

**Review by andrewbranch — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ialexryan** [comment]
Hurray! Thank you so much @weswigham 🎉 🙇🏻

**Comment by thorn0** [comment]
Seems to fix #42646

**Comment by craigphicks** [comment]
> > I'm not sure what the proposed alternative is. If you're writing filter, you're probably writing `arr.filter(x => expr)`, and we can't _iteratively_ assign a type to `x` -- it needs to be a single type, ideally `A | B`.
> 
> For `filter` (and even if only for `filter`), I’d expect the type to be something like:
> 
> ```ts
> // Assuming the array is `A[] | B[]`
> (predicate: (item: A | B, index: number, array: A[] | B[]) => boolean) => A[] | B[]
> ```

That functional definition of `filter` is not correct, it should be union of function definitions, one for each component type `A` and `B`.  Otherwise a valid predicate like `(item: A, index: number, array: A[])` will fail, and in fact in 5.2.2 it is failing - see #55777.

**Comment by ericbf** [comment]
> > > I'm not sure what the proposed alternative is. If you're writing filter, you're probably writing `arr.filter(x => expr)`, and we can't _iteratively_ assign a type to `x` -- it needs to be a single type, ideally `A | B`.
> > 
> > 
> > For `filter` (and even if only for `filter`), I’d expect the type to be something like:
> > ```ts
> > // Assuming the array is `A[] | B[]`
> > (predicate: (item: A | B, index: number, array: A[] | B[]) => boolean) => A[] | B[]
> > ```
> 
> That functional definition of `filter` is not correct, it should be union of function definitions, one for each component type `A` and `B`. Otherwise a valid predicate like `(item: A, index: number, array: A[])` will fail, and in fact in 5.2.2 it is failing - see #55777.

The way I see it, that value predicate _should_ fail. There is no guarantee from a type system perspective that item is an `A`, so a predicate of `(item: A...)` isn’t compatible. That was why I suggested at least the proper return type (there is no situation under which filter would _ever_ turn an `A[]` into an `(A | B)[]`).

**Pull request merged**
