### PR TITLE
Fix assignment of intersections to objects with optional properties

### LINKED ISSUE #36604: Can assign types even though interface field overriden using Omit
**TypeScript Version:**  3.7.5

**Search Terms:**

Omit field override intersection assign missing error

**Expected behavior:**

If I use Omit and an intersection to override a field within an interface, when I assign an object of new type to original type I am expecting that typescript would give an error.

For example, in the example below, I expect to see a compile error in the line ` x = v; `
But unfortunately there isn't.

However, assigning the field explicitly between the 2 types does give an error.

**Playground Link:** [Provided](https://www.typescriptlang.org/play/#code/LAKAlgdgLgpgTgMwIYGMYAIAqB7dBvUddBMGAGwBMB+ALnQgFcBbAI3gG5D0kJsoALeADFSlOgGcocSAHNOIAL6hQUAJ4AHDELjYm6ALxE8xURTqMyZdAvQAydAHkmYKAB4cAGnQByEuQreAHzKIAgMEChQYNgQxNjYABQAbnTaugCU+FxkMFDoAB50OPJE+QboSexEAPTV6DD5mpHoULj8SEkYPPVwOnDoLAx5AvDoYOIQ3lBc+QB0fpTlSfOmVbVYGhjeFmTeY+L0fNzi4mAyEEgsOS24apo+jKyjAD7o4RQwJBAwAaBKIKAgA)

**Actual behavior:**

**Code**
```ts

interface To {
  field?: number;
  anotherField: string;
}

type From =  { field: null } & Omit<To, 'field'>

function foo(v: From) {
  let x: To;
  x = v;  // expect to have an error but there isn't
  x.field = v.field; // Type 'null' is not assignable to type 'number | undefined'
}


```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by ahejlsberg**
We consider any intersection `A & B` assignable to a type `T` if either `A` or `B` is assignable to `T`. This can be problematic when `T` is an object type with optional properties. For example:

```ts
declare let x: { a?: number, b: string };
declare let y: { a: null, b: string };
declare let z: { a: null } & { b: string };

x = y;  // Error
x = z;  // No error!
```

The issue here is that because `{ b: string }` is assignable to `{ a?: number, b: string }` we also consider *any* intersection that includes `{ b: string }` to be assignable--even if the intersection includes another type that conflicts with the optional `a` property.

With this PR we now require intersections of object types *as a whole* to be assignable to the target type. In other words, we treat `{ a: null } & { b: string}` identically to `{ a: null, b: string }` in relationships.

Fixes #36604.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by weswigham** [comment]
So, notably, this does _not_ fix https://github.com/microsoft/TypeScript/issues/36637 because that has a generic `T` involved, right?

**Comment by ahejlsberg** [comment]
> So, notably, this does not fix #36637 because that has a generic T involved, right?

That's right.

**Comment by ahejlsberg** [comment]
@weswigham Can you take a look at the last user test suite run and tell me which of those are preexisting conditions, or how I might find out? The `office-ui-fabric-react` is for sure a new issue, but I don't know about the rest.

**Comment by weswigham** [comment]
> Can you take a look at the last user test suite run and tell me which of those are preexisting conditions, or how I might find out? The office-ui-fabric-react is for sure a new issue, but I don't know about the rest.

Looking over https://github.com/microsoft/TypeScript/pull/37219 and https://github.com/microsoft/TypeScript/pull/37203 , looks like just the `office-ui-fabric-react` ones are new.

**Comment by ahejlsberg** [comment]
Summarizing test runs: No change in RWC and DT and no appreciable perf impact. New errors in the `office-ui-fabric-react` user test project are indeed legitimate errors that we didn't catch before.

So, this PR is technically a breaking change because we find new issues.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
CC @dzearing @jasongore, it looks like this change will cause issues for Fabric. It looks like tightening the declarations of

https://github.com/OfficeDev/office-ui-fabric-react/blob/e5c9f2bea83a4b9b0a82d303682c2ea093036c83/packages/fluentui/react-proptypes/src/index.ts#L436-L463

to use `PropTypes.oneOf([...])` with the appropriate literal types on `design` will fix it. To try it out, I'd recommend using the above build.

**Pull request merged**
