### PR TITLE
fix constructors for DateTimeFormat, NumberFormat

### PR DESCRIPTION
**Pull request by bavardage**
they were incorrectly producing a Collator

### CODE REVIEW

**Comment by mhegazy** [comment]
Fixes #1911.

**Comment by mhegazy** [comment]
:+1: 

@zhengbli can you take a look

**Comment by zhengbli** [comment]
Looks good to me. 
However, how do we generate the ``intl.d.ts``? We should change the script of that too to avoid reverting it back in the future.

**Comment by mhegazy** [comment]
This is hand edited, and not generated.

**Comment by mhegazy** [comment]
thanks @bavardage !

**Pull request merged**
