### PR TITLE
Re-order reduce overloads

### PR DESCRIPTION
**Pull request by okmttdhr**
Fixes https://github.com/microsoft/TypeScript/issues/7014

### CODE REVIEW

**Comment by SCWR** [comment]
why is it stagnant?

**Comment by SCWR** [comment]
Has the version 4.x been fixed?

**Comment by sandersn** [comment]
Unfortunately, too much time has passed since we accepted #7014, and any single change to Array methods is likely to be a breaking change whose cost outweighs its benefits. We should only consider fixing it with all the other Array methods in https://github.com/microsoft/TypeScript/issues/36554.

This PR should be closed since it's likely that the full Array method overhaul will look somewhat different. @okmttdhr does that sound OK to you?

**Comment by okmttdhr** [comment]
No problem, and I agree with that we should consider fixing it with all the other Array methods. I’m closing this PR

**Pull request closed without merging**
