### PR TITLE
Fix subtype reduction involving type variables with union constraints

### LINKED ISSUE #53311: [5.0.2 regression] unused type guard result erroneously changing inferred type of variable
# Bug Report

### 🔎 Search Terms

control flow analysis type guard narrowing widening no-op

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.2

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.0.2#code/C4TwDgpgBAYg9nAcnAJtAvFA3gKCvqAawEsA7FALigHIAzBagbjwIGMALYgGxQCcJSVZGgDaAXWYBfZjlCQoAIQCGvYRmwt8JclWoAjFUxyScs8NDVRM8JKmgAfRSrUy50ACJxWAVwC2A4CsNAiIyShoULz8AoxCObj4BITtxKRk0Vi4VaFpvUlZgYjhSKGIAZzUAClI7KjzCGoB3UgBKKhq0UrKoFxwMrP4oXPzC4q7lXmranrs2qA7ocqdVOxkIAA8wOF5A4YKikoA3cuJgNTKAHgAVKA3gARRutQA+SpYFqk8ff1JAxzUADQsMD8FDEVhKe5USr3MpnaZqFpWZ5QWHwzpLK5AuaHODEFDBKAAeiJUAAyls4IQQFAlPsxpDaVAwXClPkIFRgJxujUALRwMBQVn3H6BCHeMoQbpc6CsOC+MDcCC8VFwKD8ABWEAKqPY0CUZTKxAA5qRRSwSVBjd4VGgCXoaTKoHLyKcDkouACoHoIFw4I0AHRQADC8tFpUCcG8gWAatoxHWupySm43n4AZY5SqCyRADJc1AQRAwRD7lM0C0ZPhiLQoJUAIRZuzliBI+yORtlCYtlpI3AhS1XblQLhkaBldhRnjO+WKrg5Mf1zQz0hw+Z2MrJURiIILAPxHj8UjMfAmSRAA)

### 💻 Code

```ts
type FooNode = {
    kind: 'foo';
    children: Node[];
};

type BarNode = {
    kind: 'bar';
}

type Node = FooNode | BarNode;

type Document = {
    kind: 'document';
    children: Node[];
};

declare function isNode(node: unknown): node is Node;
declare function isBar(node: Node): node is BarNode;

export function visitNodes<T extends Node>(
  node: Document | Node,
  predicate: (testNode: Node) => testNode is T,
): void {
  // Spooky action at a distance: this no-op statement causes the compiler to reject the assignment
  // guarded by the conditional, below. Comment it out to fix the failure.
  isNode(node) && predicate(node);

  if (!isNode(node) || !isBar(node)) {
    // This line should compile fine!
    const nodes: Node[] = node.children;
  }
}
```

The original code that turned this issue up was a bit more indirect and looked like:

```ts
const shouldYield = isNode(node) && predicate(node);
if (shouldYield) {
  yield node;
}

const hasChildren = !isNode(node) || !isBar(node);
if (hasChildren) {
  yield* yieldAll(node.children);
}
```

I was able to work around the issue by inlining the guards directly into the `if` rather than using an intermediate value.

### 🙁 Actual behavior

The assignment `const nodes: Node[] = node.children;` fails, complaining that

```
Property 'children' does not exist on type 'FooNode | Document | T'.
  Property 'children' does not exist on type 'T'.(2339)
```

but only if the unused type guard at the beginning of the function is present. Commenting the dead code out fixes the issue, and the compiler correctly narrows the type of `node` to just `FooNode | Document`.

### 🙂 Expected behavior

The unused type guard/dead code has no effect on the inferred type of the value.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53311.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
Tests and performance are unchanged. This one is good to go.

**Review by jakebailey — APPROVED** [review]
Do we need to backport this to 5.0?

**Comment by ahejlsberg** [comment]
> Do we need to backport this to 5.0?

I could go either way on that. The underlying issue has been present for years, but the combination of that and an unrelated change in 5.0 caused a regression.

**Comment by jakebailey** [comment]
I'll trigger it anyway, and we can discuss it at a meeting.

@typescript-bot cherry-pick this to release-5.0

**Pull request merged**
