### PR TITLE
Check if the file added is emitted file after validating extensions

### LINKED ISSUE #21274: tsserver maxing out CPU "WatchType: Directory of Failed lookup locations in module resolution"
**TypeScript Version:**  2.7.0-insiders.20180117

**Search Terms:** directorywatcher

Today's VS Code Insider seeings tsserver maxing out the CPU after a few minutes (under Microsoft/vscode codebase). Verbose logs are just pages and pages of this:

```
Info 27855[10:7:22.843] DirectoryWatcher recursive:: Elapsed: 24ms Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/workbench/parts/welcome/walkThrough/electron-browser/editor PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27856[10:7:22.843] DirectoryWatcher recursive:: Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/workbench/parts/welcome/walkThrough/electron-browser/walkThroughPart.css PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27857[10:7:22.869] DirectoryWatcher recursive:: Elapsed: 26ms Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/workbench/parts/welcome/walkThrough/electron-browser/walkThroughPart.css PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27858[10:7:22.869] DirectoryWatcher recursive:: Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/base/test/node/extfs/fixtures/examples/company.jxs PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27859[10:7:22.896] DirectoryWatcher recursive:: Elapsed: 27ms Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/base/test/node/extfs/fixtures/examples/company.jxs PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27860[10:7:22.896] DirectoryWatcher recursive:: Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/base/test/node/extfs/fixtures/examples/conway.jxs PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27861[10:7:22.920] DirectoryWatcher recursive:: Elapsed: 24ms Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/base/test/node/extfs/fixtures/examples/conway.jxs PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
Info 27862[10:7:22.920] DirectoryWatcher recursive:: Trigger: /Users/daimms/dev/Microsoft/vscode/out/vs/base/test/node/extfs/fixtures/examples/employee.jxs PathInfo: /Users/daimms/dev/Microsoft/vscode Project: /Users/daimms/dev/Microsoft/vscode/src/tsconfig.json WatchType: Directory of Failed lookup locations in module resolution
```

screen shot 2018-01-18 at 10 07 41 am

### PR DESCRIPTION
**Pull request by sheetalkamat**
May fix #21274

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@mjbvz @Tyriar could you please try out this branch to see if it helps with #21274

**Comment by mjbvz** [comment]
@Tyriar I'm actually not seeing the perf issue on my Mac. Could you please test out this branch:

1. Check out this branch from the ts repo
2. In the folder, run `npm install` and then `gulp local` to build a local ts version
3. In VS Code, set add a user setting pointing to the tsdk build location, for example:`"typescript.tsdk": "/Users/matb/projects/TypeScript/built/local"`
4. Restart vscode and make sure you are using the built-in version of TS

We can also take a look at this together tomorrow

**Comment by Tyriar** [comment]
I just set up the local build, will report back soon.

**Comment by Tyriar** [comment]
Nothing happened so far, so I guess it's fixed. The repro I had before happened about 5 minutes into opening VS Code, this happened 3 times in a row fairly consistently. Will ping back if I see it but I think this fixes the problem.

**Comment by sheetalkamat** [comment]
@mhegazy  can you please review this change, so we can take this in.

**Pull request merged**
