### PR TITLE
Run ESLint over our JS files, fix all lints

### PR DESCRIPTION
**Pull request by jakebailey**
In prep for adding copyright headers to all of our source files, make our lint task run ESLint on our JS files too (which will need the headers, and I want ESLint to enforce that).

Our `.eslintignore` already covers ignoring the js files we don't care about, e.g. build artifacts and baselines.

### CODE REVIEW

**Review by ProKashif — APPROVED** [review]

**Comment by jakebailey** [comment]
I'm still waiting on guidance as to the copyright comments, but regardless I think this is a good change as it fixes a load of lint problems and type errors in our scripts.

**Review by amcasey — APPROVED** [review]
Seems fine.  How long does it take?

**Comment by jakebailey** [comment]
That's a great question. It's 4x faster for some reason, which then made me notice that the gulp task is not working properly without the flag because eslint doesn't scan anything other than `.js` files by default, and it's typically the typescript-eslint recommended config that changes that. Oops. Will fix.

**Comment by jakebailey** [comment]
Hm, no, ts-eslint's config doesn't do this. I don't know who does; if use ESLint on my own projects, it does the right thing, but it does the wrong thing on the TS repo.

**Comment by jakebailey** [comment]
The reality is weirder; [apparently the ESLint CLI](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#specifying-target-files-to-lint) will look at `.js` files _and_ files that happen to be a part of an `overrides` config. Most tseslint users never know that ESLint normally only looks at `.js` files at the CLI because they extend the recommended config, which just so happens to override a couple of default rules.

**Comment by jakebailey** [comment]
So, to re-answer with the fix, the new lint time is maybe about 1s longer than the old one, give or take, but it's already a 40s run uncached.

Cached, it's about 3s on my machine before/after.

**Pull request merged**
