### PR TITLE
importFixes: Skip alias when testing isTypeOnlySymbol

### LINKED ISSUE #27317: Auto File Imports Inline Rather than at the Top of the File.
_From @cgen01 on September 22, 2018 10:11_

### Description

There seems to be an issue with importing files. When I start to type a file to add to my component, VSCode used to import it to the top of the file. Now it imports it inline. Is there a setting for this that I'm not aware of? Or is this a bug?

### Example

screencast 2018-09-22 05-58-10

### Information

- VSCode Version: 1.28.0-insider
- OS Version: macOS 10.13.6
- Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#59149_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #27317

### CODE REVIEW

**Comment by andy-ms** [comment]
@RyanCavanaugh Should port to ts3.1?

**Comment by morrisondavid** [comment]
When will this fix be released?

**Comment by andy-ms** [comment]
@morrisondavid It's already available in `typescript@next`. It should also be included in the next `typescript@3.1` release.

**Comment by MarcoScabbiolo** [comment]
Typescript 3.2.2 still haves this issue in the latest version of VS Code, @andy-ms please reopen related issue/s or provide a link to the TS issue/PR/release

**Pull request merged**
