### PR TITLE
 Fixes #8657: Handles union typed React component.

### LINKED ISSUE #8657: JSX: Typing both stateless component and component class in react component property gives error
I need to type both stateless component and classic component in single component property:

**TypeScript Version:** 
1.8.10/1.9.0-dev.20160518-1.0

**Code**

```ts
// A self-contained demonstration of the problem follows...
// Ideally:
interface ComponentProps {
   ButtonComponent: React.StatelessComponent<any> | React.ComponentClass<any>;
  ...
}

class MyComponent extends React.Component<ComponentProps, {}> {
  render() {
    const { ButtonComponent } = this.props;
    const someProps = {};
    const button = <ButtonComponent {...someProps}/>
    return (<div>{button}</div>);
  }
}

// Ideal usage

<MyComponent ButtonComponent={() => <button>test</button>}/>

class MyButtonComponent extends React.Component<{},{}> {
...
}

<MyComponent ButtonComponent={MyButtonComponent} />
```

**Expected behavior:**
Compiles successfully

**Actual behavior:** 
Throws error: "JSX Element type ButtonComponent doesn't have any construct or call signatures"
It works If i change definition of ButtonComponent to just solo React.StatelessComponent<ContractProps> or 
React.ComponentClass<ContractProps>

### PR DESCRIPTION
**Pull request by evansb**
- [x] There is an associated issue that is labelled
  'Bug' or 'Accepting PRs' or is in the Community milestone
- [x] Code is up-to-date with the `master` branch
- [x] You've successfully run `jake runtests` locally
- [x] You've signed the CLA
- [x] There are new or updated unit tests validating the change

Fixes #8657 

This pull request handles special case of union typed React component, namely `type U = React.StatelessComponent<any> | React.ComponentClass<any>`. Since `StatelessComponent` has call but no signature and `ComponentClass` has no call signature but no construct signature, the union between these two will result in a type with no call or construct signature.

Previously `<U />` will fail because the type checker cannot find any call/construct signature on it, which is a false negative.

This patch handles union typed React component separately: we first unfold the type of `U` and apply the old construct/call signature + return type check.

This involves refactoring JSX Element type resolver to a new function `getResolvedJsxType` so that it can be applied recursively to each member of the union types.

Evan Sebastian.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
This doesn't seem like the right approach. What if you had a property of type `string | ComponentClass` ? It shouldn't be legal to use that as a React component.

**Comment by evansb** [comment]
You are right, I should've raised the error as soon as a type doesn't have constructor/call signature instead.

Anyway this is still pretty much WIP and doesn't solve the issue quite yet, we will have another problem with the different return type of `StatelessComponent` call and `ComponentClass` constructor.

At the moment `StatelessComponent` return type is `React.Element`. It isn't related with the current `ElementClass`, which fails to type check when you try to render it with JSX tags.

**Comment by evansb** [comment]
I think I'm done, would you mind reviewing it? @RyanCavanaugh 

Patch summary:

For JSX Element construction `<Component />`, if `Component` is a union type, recursively apply the old method for checking for a valid JSX constructor.

This involves factoring out JSX resolving to a new function `getResolvedJsxType` so that it can be applied recursively to union types.

**Comment by RyanCavanaugh** [comment]
Can you split out the test so there's a non-erroring test that shows the behavior you're trying to enable? When there's an error we don't generate a type baseline so it's harder to confirm the right thing is happening.

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by mhegazy** [comment]
thanks!

**Pull request merged**
