### PR TITLE
Readonly in declaration files (part 2)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Augments #6697 to emit `readonly` modifier in declaration file for get-only accessors in classes.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by JKillian** [comment]
I'm concerned that this creates `.d.ts` files that are non-backwards compatible with versions of `tsc` introduced before `readonly` support.

As an example, we had a class with some get-only accessors as part of a library we use internally, and we started compiling the library with `typescript@next`. This broke usage by internal applications that were still using the TS 1.8.x line, because they couldn't consume the new typings.

**Comment by mhegazy** [comment]
@JKillian would adding an empty setter to the source class be a problem?

**Comment by JKillian** [comment]
@mhegazy That could be a good work around, or just changing the accessor to a regular method could work for us as well.

Really, just wanted to mention this because it was a surprising back-compat issue and I wasn't sure if it was intended or not.

**Comment by mhegazy** [comment]
Thanks @JKillian, this is not the first time we got this feedback, I will bring this up in the next design meeting.

**Comment by JKillian** [comment]
Sounds good. I think this case would be solved nicely in a way [similar to that mentioned here](https://github.com/Microsoft/TypeScript/issues/7573#issuecomment-207685140): that is, a "typingsTarget" option of some sort that lets you emit typings that will be compatible with older versions of the compiler. Of course, I don't know the complexity or difficulties of that, I'll happily work with whatever you all decide.

**Comment by mhegazy** [comment]
looping back, we are sorry we did not catch this issue as part of implementing the readonly properties. moving forward we will be more cognizant of adding new syntax to generated .d.ts files for new features.

it seems there is no clean solution for this issue, that does not involve yet another compiler flag. we would recommend either adding an empty setter or using a post build script to remove the reference to readonly for now. again sorry for the inconvenience, and we will add dts compat to our new feature checklist in the feature.

**Pull request merged**
