### PR TITLE
Add a fastpath for comparing common mapped types like `Pick` which avoids manufacturing intermediate type identities

### LINKED ISSUE #39678: Slow compilation likely caused by too many types
**TypeScript Version:**  >= 3.7.5 (reproduceable in @latest and @next)

**Search Terms:** slow compilation typecheck types typecount 

After refactoring the model of our project to rely more heavily in classes we found a very significant increase in the typecheck time. Using the `--diagnostics` flag we noticed that our project seems to be producing over **2 million** types (which takes around 37s to check). Half of those types came from our model definition, although that sounded like way too much, since we only have around 30 classes with little to none methods each. 

Weirdest part is that the issue seems to mainly be cause by two particular method definitions. Removing these methods reduces the produced types from +900K to around 52K (around 1/6 of the original time). I'm not sure if we are doing something we are not supposed to in these methods or there is something else going on, but I would very much appreciate your insights.

I tried to purge our codebase so I could show you the smallest demo possible. You can find the trimmed example [here](https://www.typescriptlang.org/play/#code/PTAEgVSSunb+GKclqEFgBQJQBUCaACgKKgAixAYgJIBy1u1A8rQMpY5pfc+98aYsAUwAeABwD2AJwAuoGQE8xQ0LQCGAWxUBeUAGcZUgJYA7AObDx0uYuWhqAE1C6Dx85cmz5SlQBkjBgA8uAB8zqAASkJqDhImADYKAIJSUmoKwSEe1t52AMJqAMYAFjqgALJqYoGupmYANKBqJgpZgpi2KkkyhkYARgCuMkIA0kIKepnhAN6gANojoKagANbjEgBmeAC6ALQA-ABceAvboKLDJg56oJQDJoUyRnGg+6AmQgBuQlKgx4sAXzmawUmx2WE6oCYYiecTU8TGEymulmCyWJlW6y2uD2R1A9wcQg2piETguQiuN1wp1eoEWxw+31+QJBYJx2S8kMI6XiEhiyKhGiMMkCWFAoEIRkKK2CjWIIkK8QGhMC3V6g2GiMmoUa0NhJnhWsyITCADIxRK1LIjPDApLpbLQGrjBrRuNtWaoTDngaEe7jSF6haAOQrUwOYOgAA+oGDAH0DGozEJg1g2hybD5QKwZEmyhE1AB3aO3IzxeKkkv+ExrBwZpp9VxFOSKtR6G4F4uzMRSCTDR6VqTRWIJBSgNKF3BJ8LBzuRgH1tSNwzN0Ct9ul8uV8mUyJF0Dd3v94ZOIcxOKJUDErcOKdmGeUMsViOgBeYUSeORLpuPNfxNs3NWtbnCIlzXJuz4HqAPZ9kIA6nsOF5jvEpi1neM5AaS871pCj6+uEmF1u0H45LhT5LhWgSsCBYE3DmeaNKE4TUTu4GPjetK4H8eAlgSRIkkRJGclmQEUUIVE0RS4H0cmjFhLoLGgVJgGoZWbxcccXExnxxIfEROFZkwJgyeJtCNIptHZrmybyaokm7rQEiEkwGwjOGgSmBsPx0o0nneXGYRvI5zmue5IzmWEDJfD8WAGXYblXOEwVCHMobhsG2xxSoCUOC5gS0PZ4HJYEzStLZtCpWGVwZVloAFMMZjSGOujBsQJhPIokYxsG5ROQMFZdbGrAUpchQpiWrXiEO7Y+oNwbJam75WMJdjJS5OWBIsrE3Dl5mFXR1lCLZ8oro8+VOeJrCBlBVUOP8r7pktn65Coa0bPVQiNVIGR5PtdVqA1TV7dtVl5vJFq-SDrXtcKCiRm8bUdRkV1-BDf09X1A20r1Dj9ZdkVo1Dw3tRSY3w9mI2k-jqOYOKkNKbuk09kIM1xOT8rM6zJhUQTtN1ejC20sVKOHBajIxcRy2ZqtF3reGTBSB9X0ZAAin9OUlkrQPZn9Jng3zasgxrQWy6FVyBCrEU0+KhsM+BWvfULpsO6rVui3z4tSLFT2kVmrCFBIdi6FEAdSA4+WaEIjSOG0QnS69F0SSDJnhHh8K2dyaRaMMUg8yW6haA4KRmAMWjtXnMbUBon4V6AABCTnI2EMb1SUteI7DtdkCzhQukI5RCBofQ-LXeT-u2A9DyPKMxsTo3UzGbWfEYvYmGXIpXbVHeKEndsHXmqemOn4TctKea14QvZmFnte4CzG-N+QPd97XON47XABqVo2n0lGbz7K0VBvz-rrQ6h9fS2THgBWurA6gVhkHEV+RgRCmB5rVJgfQABWcEZCT2HrnCyylQbJnAcfXQj4hDxHDjPCoQgZDFCcmggB8c6rjz0Hg6eoCD7kKPvESBcRXADEeNIWuGDsGPA4QQ2OUsXpPz0L3fo-dB74N3pZFOPCIHhC-sYMStdHygQGEOW+99X50IYdQ6Rz1IRzypqooh6jSyaN0Non+f9H5RBkIY7mNCkgzTMGvEa7cposz0D6JhcdZEc2mqExBhDdwOLTnw8IUQvJDgeAvCm8QNi138DnW0rBGi5J+PCL+Sp8aP2JhYksrABjKCkfnIQhZa7UGyTQ3AxRexNLad9cJMjIRFLSPEUpAxLpcJIRosh7xS74JLLUcwJY+gSAkBWZoJYTD9XiA0rpFS4F0NiY9Tg-AjnHJOccjgYAkgAFUAAatxLm0DyIwFg7BsBgFOe8j5nz4DewDiYAwSw9DJXCHY+Jh0QgAAoJBYOOKVAAlMcKFmCAWqETijbQYQACEGLIVYNAKaU0oBEUADpbqwp+QIuQIIbi6DETgkl7omg3EyJCzSsLnBhHBSdNIZ1WTYkaHMswIRYVzEynzcUWBfn-I0FUWlv5dCOgiOEUqEKZAiGOOCz48IRmaWBFiHYjQQTHF5XgNl6LIiNERay44qJFjLGNTiY4iqATsoPBaSVchpqSD+WUaYzq2xQTRHavVDrIivgtBsaQoBwXusxGOMEVKcWYNhWy6YFpxSeoESlEEZxdCqsTbqhQ2wDXjDJXzN86a6FePHCzL1eghBYDfOciAXyW2trOa81QTAKAvMOW2vt-aUDe2-KdFsbDQAABJhZjKOq6vmMFjyDkQqOUACZDp4heRaYd3KPVLsvLdf44ZvYVvPMuowDgMXHFEr-S60cHBtGPSOS88jA5CAvaAK9f9zIB2UPe6tJ6n0SEMWNPEAqLRnkfWOH4vYpB6DxP4IIxBUjSF-eBpCK7ChFFKMcAoJQygfGLJUMQ4LS1uopVIIRCCpDgrEDyPkd1IhwWkOHAVjR7grBMBIQsJghWzvFOKWVMgiUASMP48F9CAiNBowoXkMRS3inLaRsQChwWEniLmY4mcni2m5NJujgRxN6BNPC+QxQAi8b40OTxUgMT4ajQZol7ryPCN+P6uF4LZhEs8wZxonmiWqdzK+OTYb2jihXH8iNUgNCBEVcnMBCkVVqqjRxwkxxioRB42atLQrUuJ3S+Z8UMaqhiESLgNI4XpAaHCBqrVQgYUtGM6VF1qaxV8aMFsMTPgwSarKc4bQLUNj3EeLNNllmq3dZGWm1r7WUhpAUESgIM30jVbKcm6tVmMTjaEES6VRGislbK3oCLGggt8aWO1gIwsIWbdW6N6zoBNsOcDspnbAnwV7YUKV5oh2KuNDzZtxlTR6vJsm+KNrUb-umETOksEAmRuVruy9rBOC3tiGKx9g7R3GjXZB2tsbNXJvlos-DjE73Pvlci2J0zegguNswLT3tA7GdM6gE2+5ERiC+GIB-JItAuK0C7aQPIvgkisFYMQHtbzmdS8Z97CJ64biZ0jjnEF0k4uOOPiDSdqKwjNYfWh26M5FfZx+ItPXy6DRaDfQXetfNUOnr0No4ub7FnLOiCYUjfzDAUekNR2jMQNN+-Dkbuh08jNQT0LUn4vvdOyeC7TuXY7rdFykCXdeKv97jPV0kzXl3zN273eGGcSfi6lxGqbv9EH3iRyt5HMDu6xybbfVEkJYT-4FbI97qjUmZP0Z0z3iOhcS9p6ujx2YEe6nR572yt88eZHy-sNXaw6fiFlESWEHP2u8-19WIXlqVdPzl-z5BmGig30pJ+LYtvFe0MBAAOIUh+FKZ3SyVnu75o5zvk+6MB5j+HffS+R8U19BI8u9A9p8G1Zc58x0G4HBkZp1SFs894J1c9ddr9l0DcWoYC4Y69-0xw60SZ0k9A314MN5KZ0keZf0P9nMv9-dLRf9AgsCKCgDx8o9u86NwC6dIDnp59T4Vhz44lVduEs918kCtcVQUZUCj8d9EoWpeC8xD9t8LdX1Uta9bdt8jBF9ZAiDL0AgRR-9ZAKCcDK8tAp4YNiDdDAht4m5KCO9qCHAAY1Af9+85DkwmDw8QCVMHCODZ9uCx1L4JBr5NBl8EleERDLIxDqZJDt8MDYx-DAiNAFDcCq9LcVCtAjC0NFlYC31GCr8qDKNPD1M6DnCr4b5AD3CJ97DcxvCuCch5874ggBCM9V9Qi-oIi84oikiYjgx6iZBEjK8lCa80i1CkjMiFBsjG4mF29PcnN8jKjHCii9Mei3Cx8PC5jqjJZfCAI5EFFh5gi1c19WiUD0j0Dd9Yxu55E+4+i0MBjUibczdLwTD8FtD30LDzidilFTDDD39bDZiHCnC9M3iX4yiViKivC48aivB58XFdFGiV8ECwiiE2iJDjiC8ZDYxoTr0rjzdq9biUSxwAgogYgjJEhn9Xdmg8T7sas312J-xr0qI5RgkuYvipjBE7C-iFj+QMS3FR9gDQSqjwSNjaix0oF2w9ihCDiN9xCdcKSuiRS9AsTLwbjVBVD7ixwhQUE-lzCghz80kxpmS0CHjlEfhniSDAg5TJF9SpCWCpB5cUlqTyI6SCkGNUlL9H51lywbDpjP85j-j+Q5TljeSo81iBT6x59YFzB4FYl4CJlEDwijjhjK8ujwyzBIyTAFSxwlDbjeIrh+I9IKT1TIctSRQdTXSUNt9HjjSizAgBMLSR8KTrSChyx7TywYTGhUDxRrTbSiRHUiQL9yCrogwWsrQzA9AdCENGSYlvETQqwLDi8U9S9y46yy1PTWTfjCi+89NkzUyAzrSCi1B1jQyx1yhkFUFYSQjNFJTIiZTTieoTy0yKSlTrd8y7yTSLCSz+yTR8yjSzCxyRQazvz9S8ifcfSOTw5jyNSdzViwSZ8ITR0tiKEqExTM8JTRD4zVTpCnAWoEKIwHycTlShj0KCThxiSxjjgXdX8KSAh-C6lT8yKX83cKTG9jgaTWzQBm8mSlyWSvc2T1zA9AhsLIK+T9yQzmE-wtiB56FGEzz9iWjLz2jry0SeozEnJ0zkjlD8K7iDT8S9AmAmRjBCRSSKKEy0MaMs4Q8fyXighg9ldOKtLQBRi8QcjH5gwDQnhvhy8gKqMQKNz+QJLzFBKgzoKIDBTIThSfiRFpLxTZLULN8OjEyby8hwqpBVLTKldKzfy7QrQ0qpEyyRjG5xjYDJi7K+g2whBGz4g8RZgMNyw9Aak6k6KySTBGhhzRzLKRR2LJyKDgsuKZjgL2SfLw5EqvTnMAqvKgrOCQq4KNx9ErNRlYsoqLyYqpSt9OibyZrDEUwKTRiCqm4PdVy+reL6D1qjFgTAyxr+SYLJqxKNwPEvEkLmjFq4zYqFLMLYxbrrNVLNs8QOrW8VzuK1z5iBrotidRq9yDzRL59fFQl-Fh9ozhDDjnrjKTjFKoaRMAl2pPrv4xIz9ezdT8ZGKqTjgfr9k9r-qDrAa+LUaYbAlTrdzgzLrDytj3y9TIrkLoqnrlq4r9cbzmbNqkbFS8KnzvjhqAbfTw5ebQb6bgrGaNxhosl7r4SEbOaXqZw5aNgPKkq9yxaqJKFWkw8QTAqLrpaIax0Bl8k4bElGI-ozahkas85dAbbhlyklarz+axwuibbMayk31cBSberzqKb6Cbb6S8B9azqwaRKE8tjKkFaYyETdwkTpS3aMLVapJVKhwxojAmQm8Jzfqvz2w8xBjNKpCWqqziapy-r-atbQKdbzZaaoKjaJqZa6IQDY74a5LkTk6kyQDVLS6Mry7ALNbvK+K6rQ8eS6bxqfChStjaBGk26UKObXb0KujZ7CxVLIdcwYYAZSQcaXSPyKS+62rLDc79lH5TS5zU8abPzhb9qA7tbV7JbJ7YLrqbgWl572bES0K7KuiWlVLfkHBhQfQc7OZOqr8pD6EKQsCdqiqpDKE60oHmKHTP164JjbLPLq6ga3766hLwao6Nx2lOl37HrP7Ebl6byCHONVLRAxpvQ4hgHok86b6ya76a6KHtlx6G7hKGaTatjSs4D5q2biGE6v6pCui+HVLtrjgnKKSMMZBcNXyghW5ihLTt94RCx0hniWLHTGgnLK7vT+q+K+HH7G6p7QqtilGiGNclql7v6EqAYSgUqsrjcpA31rLQ8tr8qpHUHcrK9UrnHcAfBmzaTkGJa0Gh6DH6CLHsHDauHja8Gbgl4V44hYaBGHqrHF75Ku6bzEnV515VKKyLKP0b0j6XDyk9GeLA7+8cnkmr6OGcG48gA).

The impact of the issue is, of course, less impressive, but commenting the `copy` method reduces the type count from 521K to arun 24K:

**Code**
```ts
abstract class $Node<S extends Stage> {

  ...
  
  // DELETE ME 
  copy(delta: Partial<Payload<this>>): this {
    return new (this.constructor as any)({ ...this, ...delta })
  }

  transform<R extends Stage = S>(tx: (node: Node<R>) => Node<R>): Node<R> {
    const applyTransform = (value: any): any => {
      if (typeof value === 'function') return value
      if (Array.isArray(value)) return value.map(applyTransform)
      // COMMENT THIS LINE SO THE CODE COMPILES AGAIN
      if (isNode<S>(value)) return value.copy(mapObject(applyTransform, tx(value as any)))
      if (value instanceof Object) return mapObject(applyTransform, value)
      return value
    }
    return applyTransform(this)
  }

}
```
**Output WITH `copy` method**
```bash
> tsc --noEmit --diagnostics

Files:            96
Lines:         32232
Nodes:        119346
Identifiers:   43635
Symbols:       48073
Types:        521712
Memory used: 260840K
I/O read:      0.01s
I/O write:     0.00s
Parse time:    0.50s
Bind time:     0.26s
Check time:    5.96s
Emit time:     0.00s
Total time:    6.72s
```

**Output WITHOUT `copy` method**
```bash
> tsc --noEmit --diagnostics

Files:           96
Lines:        32228
Nodes:       119301
Identifiers:  43620
Symbols:      44377
Types:        24409
Memory used: 90363K
I/O read:     0.01s
I/O write:    0.00s
Parse time:   0.41s
Bind time:    0.21s
Check time:   0.98s
Emit time:    0.00s
Total time:   1.60s
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "outDir": "dist/temp",
    "lib": [
      "es2020"
    ],
    "declaration": true,
    "strict": true,
    "removeComments": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "experimentalDecorators": true
  },
  "files": [
    "src/model_demo.ts"
  ],
  "exclude": [
    "node_modules/**/*"
  ]
}
```

Despite my best efforts the issue still requires a couple dozens of subclasses to clearly manifest so please excuse the lengthy example.

**Expected behavior:** A less time consuming compilation

**Actual behavior:** Lots of types cause lots of check delay

**Playground Link:** [Here](https://www.typescriptlang.org/play/#code/PTAEgVSSunb+GKclqEFgBQJQBUCaACgKKgAixAYgJIBy1u1A8rQMpY5pfc+98aYsAUwAeABwD2AJwAuoGQE8xQ0LQCGAWxUBeUAGcZUgJYA7AObDx0uYuWhqAE1C6Dx85cmz5SlQBkjBgA8uAB8zqAASkJqDhImADYKAIJSUmoKwSEe1t52AMJqAMYAFjqgALJqYoGupmYANKBqJgpZgpi2KkkyhkYARgCuMkIA0kIKepnhAN6gANojoKagANbjEgBmeAC6ALQA-ABceAvboKLDJg56oJQDJoUyRnGg+6AmQgBuQlKgx4sAXzmawUmx2WE6oCYYiecTU8TGEymulmCyWJlW6y2uD2R1A9wcQg2piETguQiuN1wp1eoEWxw+31+QJBYJx2S8kMI6XiEhiyKhGiMMkCWFAoEIRkKK2CjWIIkK8QGhMC3V6g2GiMmoUa0NhJnhWsyITCADIxRK1LIjPDApLpbLQGrjBrRuNtWaoTDngaEe7jSF6haAOQrUwOYOgAA+oGDAH0DGozEJg1g2hybD5QKwZEmyhE1AB3aO3IzxeKkkv+ExrBwZpp9VxFOSKtR6G4F4uzMRSCTDR6VqTRWIJBSgNKF3BJ8LBzuRgH1tSNwzN0Ct9ul8uV8mUyJF0Dd3v94ZOIcxOKJUDErcOKdmGeUMsViOgBeYUSeORLpuPNfxNs3NWtbnCIlzXJuz4HqAPZ9kIA6nsOF5jvEpi1neM5AaS871pCj6+uEmF1u0H45LhT5LhWgSsCBYE3DmeaNKE4TUTu4GPjetK4H8eAlgSRIkkRJGclmQEUUIVE0RS4H0cmjFhLoLGgVJgGoZWbxcccXExnxxIfEROFZkwJgyeJtCNIptHZrmybyaokm7rQEiEkwGwjOGgSmBsPx0o0nneXGYRvI5zmue5IzmWEDJfD8WAGXYblXOEwVCHMobhsG2xxSoCUOC5gS0PZ4HJYEzStLZtCpWGVwZVloAFMMZjSGOujBsQJhPIokYxsG5ROQMFZdbGrAUpchQpiWrXiEO7Y+oNwbJam75WMJdjJS5OWBIsrE3Dl5mFXR1lCLZ8oro8+VOeJrCBlBVUOP8r7pktn65Coa0bPVQiNVIGR5PtdVqA1TV7dtVl5vJFq-SDrXtcKCiRm8bUdRkV1-BDf09X1A20r1Dj9ZdkVo1Dw3tRSY3w9mI2k-jqOYOKkNKbuk09kIM1xOT8rM6zJhUQTtN1ejC20sVKOHBajIxcRy2ZqtF3reGTBSB9X0ZAAin9OUlkrQPZn9Jng3zasgxrQWy6FVyBCrEU0+KhsM+BWvfULpsO6rVui3z4tSLFT2kVmrCFBIdi6FEAdSA4+WaEIjSOG0QnS69F0SSDJnhHh8K2dyaRaMMUg8yW6haA4KRmAMWjtXnMbUBon4V6AABCTnI2EMb1SUteI7DtdkCzhQukI5RCBofQ-LXeT-u2A9DyPKMxsTo3UzGbWfEYvYmGXIpXbVHeKEndsHXmqemOn4TctKea14QvZmFnte4CzG-N+QPd97XON47XABqVo2n0lGbz7K0VBvz-rrQ6h9fS2THgBWurA6gVhkHEV+RgRCmB5rVJgfQABWcEZCT2HrnCyylQbJnAcfXQj4hDxHDjPCoQgZDFCcmggB8c6rjz0Hg6eoCD7kKPvESBcRXADEeNIWuGDsGPA4QQ2OUsXpPz0L3fo-dB74N3pZFOPCIHhC-sYMStdHygQGEOW+99X50IYdQ6Rz1IRzypqooh6jSyaN0Non+f9H5RBkIY7mNCkgzTMGvEa7cposz0D6JhcdZEc2mqExBhDdwOLTnw8IUQvJDgeAvCm8QNi138DnW0rBGi5J+PCL+Sp8aP2JhYksrABjKCkfnIQhZa7UGyTQ3AxRexNLad9cJMjIRFLSPEUpAxLpcJIRosh7xS74JLLUcwJY+gSAkBWZoJYTD9XiA0rpFS4F0NiY9Tg-AjnHJOccjgYAkgAFUAAatxLm0DyIwFg7BsBgFOe8j5nz4DewDiYAwSw9DJXCHY+Jh0QgAAoJBYOOKVAAlMcKFmCAWqETijbQYQACEGLIVYNAKaU0oBEUADpbqwp+QIuQIIbi6DETgkl7omg3EyJCzSsLnBhHBSdNIZ1WTYkaHMswIRYVzEynzcUWBfn-I0FUWlv5dCOgiOEUqEKZAiGOOCz48IRmaWBFiHYjQQTHF5XgNl6LIiNERay44qJFjLGNTiY4iqATsoPBaSVchpqSD+WUaYzq2xQTRHavVDrIivgtBsaQoBwXusxGOMEVKcWYNhWy6YFpxSeoESlEEZxdCqsTbqhQ2wDXjDJXzN86a6FePHCzL1eghBYDfOciAXyW2trOa81QTAKAvMOW2vt-aUDe2-KdFsbDQAABJhZjKOq6vmMFjyDkQqOUACZDp4heRaYd3KPVLsvLdf44ZvYVvPMuowDgMXHFEr-S60cHBtGPSOS88jA5CAvaAK9f9zIB2UPe6tJ6n0SEMWNPEAqLRnkfWOH4vYpB6DxP4IIxBUjSF-eBpCK7ChFFKMcAoJQygfGLJUMQ4LS1uopVIIRCCpDgrEDyPkd1IhwWkOHAVjR7grBMBIQsJghWzvFOKWVMgiUASMP48F9CAiNBowoXkMRS3inLaRsQChwWEniLmY4mcni2m5NJujgRxN6BNPC+QxQAi8b40OTxUgMT4ajQZol7ryPCN+P6uF4LZhEs8wZxonmiWqdzK+OTYb2jihXH8iNUgNCBEVcnMBCkVVqqjRxwkxxioRB42atLQrUuJ3S+Z8UMaqhiESLgNI4XpAaHCBqrVQgYUtGM6VF1qaxV8aMFsMTPgwSarKc4bQLUNj3EeLNNllmq3dZGWm1r7WUhpAUESgIM30jVbKcm6tVmMTjaEES6VRGislbK3oCLGggt8aWO1gIwsIWbdW6N6zoBNsOcDspnbAnwV7YUKV5oh2KuNDzZtxlTR6vJsm+KNrUb-umETOksEAmRuVruy9rBOC3tiGKx9g7R3GjXZB2tsbNXJvlos-DjE73Pvlci2J0zegguNswLT3tA7GdM6gE2+5ERiC+GIB-JItAuK0C7aQPIvgkisFYMQHtbzmdS8Z97CJ64biZ0jjnEF0k4uOOPiDSdqKwjNYfWh26M5FfZx+ItPXy6DRaDfQXetfNUOnr0No4ub7FnLOiCYUjfzDAUekNR2jMQNN+-Dkbuh08jNQT0LUn4vvdOyeC7TuXY7rdFykCXdeKv97jPV0kzXl3zN273eGGcSfi6lxGqbv9EH3iRyt5HMDu6xybbfVEkJYT-4FbI97qjUmZP0Z0z3iOhcS9p6ujx2YEe6nR572yt88eZHy-sNXaw6fiFlESWEHP2u8-19WIXlqVdPzl-z5BmGig30pJ+LYtvFe0MBAAOIUh+FKZ3SyVnu75o5zvk+6MB5j+HffS+R8U19BI8u9A9p8G1Zc58x0G4HBkZp1SFs894J1c9ddr9l0DcWoYC4Y69-0xw60SZ0k9A314MN5KZ0keZf0P9nMv9-dLRf9AgsCKCgDx8o9u86NwC6dIDnp59T4Vhz44lVduEs918kCtcVQUZUCj8d9EoWpeC8xD9t8LdX1Uta9bdt8jBF9ZAiDL0AgRR-9ZAKCcDK8tAp4YNiDdDAht4m5KCO9qCHAAY1Af9+85DkwmDw8QCVMHCODZ9uCx1L4JBr5NBl8EleERDLIxDqZJDt8MDYx-DAiNAFDcCq9LcVCtAjC0NFlYC31GCr8qDKNPD1M6DnCr4b5AD3CJ97DcxvCuCch5874ggBCM9V9Qi-oIi84oikiYjgx6iZBEjK8lCa80i1CkjMiFBsjG4mF29PcnN8jKjHCii9Mei3Cx8PC5jqjJZfCAI5EFFh5gi1c19WiUD0j0Dd9Yxu55E+4+i0MBjUibczdLwTD8FtD30LDzidilFTDDD39bDZiHCnC9M3iX4yiViKivC48aivB58XFdFGiV8ECwiiE2iJDjiC8ZDYxoTr0rjzdq9biUSxwAgogYgjJEhn9Xdmg8T7sas312J-xr0qI5RgkuYvipjBE7C-iFj+QMS3FR9gDQSqjwSNjaix0oF2w9ihCDiN9xCdcKSuiRS9AsTLwbjVBVD7ixwhQUE-lzCghz80kxpmS0CHjlEfhniSDAg5TJF9SpCWCpB5cUlqTyI6SCkGNUlL9H51lywbDpjP85j-j+Q5TljeSo81iBT6x59YFzB4FYl4CJlEDwijjhjK8ujwyzBIyTAFSxwlDbjeIrh+I9IKT1TIctSRQdTXSUNt9HjjSizAgBMLSR8KTrSChyx7TywYTGhUDxRrTbSiRHUiQL9yCrogwWsrQzA9AdCENGSYlvETQqwLDi8U9S9y46yy1PTWTfjCi+89NkzUyAzrSCi1B1jQyx1yhkFUFYSQjNFJTIiZTTieoTy0yKSlTrd8y7yTSLCSz+yTR8yjSzCxyRQazvz9S8ifcfSOTw5jyNSdzViwSZ8ITR0tiKEqExTM8JTRD4zVTpCnAWoEKIwHycTlShj0KCThxiSxjjgXdX8KSAh-C6lT8yKX83cKTG9jgaTWzQBm8mSlyWSvc2T1zA9AhsLIK+T9yQzmE-wtiB56FGEzz9iWjLz2jry0SeozEnJ0zkjlD8K7iDT8S9AmAmRjBCRSSKKEy0MaMs4Q8fyXighg9ldOKtLQBRi8QcjH5gwDQnhvhy8gKqMQKNz+QJLzFBKgzoKIDBTIThSfiRFpLxTZLULN8OjEyby8hwqpBVLTKldKzfy7QrQ0qpEyyRjG5xjYDJi7K+g2whBGz4g8RZgMNyw9Aak6k6KySTBGhhzRzLKRR2LJyKDgsuKZjgL2SfLw5EqvTnMAqvKgrOCQq4KNx9ErNRlYsoqLyYqpSt9OibyZrDEUwKTRiCqm4PdVy+reL6D1qjFgTAyxr+SYLJqxKNwPEvEkLmjFq4zYqFLMLYxbrrNVLNs8QOrW8VzuK1z5iBrotidRq9yDzRL59fFQl-Fh9ozhDDjnrjKTjFKoaRMAl2pPrv4xIz9ezdT8ZGKqTjgfr9k9r-qDrAa+LUaYbAlTrdzgzLrDytj3y9TIrkLoqnrlq4r9cbzmbNqkbFS8KnzvjhqAbfTw5ebQb6bgrGaNxhosl7r4SEbOaXqZw5aNgPKkq9yxaqJKFWkw8QTAqLrpaIax0Bl8k4bElGI-ozahkas85dAbbhlyklarz+axwuibbMayk31cBSberzqKb6Cbb6S8B9azqwaRKE8tjKkFaYyETdwkTpS3aMLVapJVKhwxojAmQm8Jzfqvz2w8xBjNKpCWqqziapy-r-atbQKdbzZaaoKjaJqZa6IQDY74a5LkTk6kyQDVLS6Mry7ALNbvK+K6rQ8eS6bxqfChStjaBGk26UKObXb0KujZ7CxVLIdcwYYAZSQcaXSPyKS+62rLDc79lH5TS5zU8abPzhb9qA7tbV7JbJ7YLrqbgWl572bES0K7KuiWlVLfkHBhQfQc7OZOqr8pD6EKQsCdqiqpDKE60oHmKHTP164JjbLPLq6ga3766hLwao6Nx2lOl37HrP7Ebl6byCHONVLRAxpvQ4hgHok86b6ya76a6KHtlx6G7hKGaTatjSs4D5q2biGE6v6pCui+HVLtrjgnKKSMMZBcNXyghW5ihLTt94RCx0hniWLHTGgnLK7vT+q+K+HH7G6p7QqtilGiGNclql7v6EqAYSgUqsrjcpA31rLQ8tr8qpHUHcrK9UrnHcAfBmzaTkGJa0Gh6DH6CLHsHDauHja8Gbgl4V44hYaBGHqrHF75Ku6bzEnV515VKKyLKP0b0j6XDyk9GeLA7+8cnkmr6OGcG48gA)

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #39678

This reduces the cost of the `copy` method in #39678 from 3s to 0.3s (on my machine, at least). In harder numbers, the fastpath brings the type count in the example given in #39678 from 402k types manufactured during compilation down to 27k types (compared to 19k types without the `copy` method at all).

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by weswigham** [comment]
Perf looks good (potentially a small gain in material ui). Other suites are either passing or existing diffs.

@typescript-bot pack this

**Comment by weswigham** [comment]
@nscarcella you wanna try this PR build to verify that if fixes your actual code?

**Comment by nscarcella** [comment]
> @nscarcella you wanna try this PR build to verify that if fixes your actual code?

For the simplified model described in #39678 these changes reduce the amount of types from 521712(6.59s) to 404755(4.60s).

Can't currently test it on the whole model because we can't update the TypeScript version due to [this other issue](https://github.com/microsoft/TypeScript/issues/39059).

**Pull request merged**
