### PR TITLE
Allow trailing commas after non-rest elements in destructuring

### LINKED ISSUE #24628: A binding pattern without rest element can have a trailing comma
**TypeScript Version:**  2.9.1/3.0.0-dev.20180602

**Search Terms:** 
- trailing comma
- binding pattern
- A rest parameter or binding pattern may not have a trailing comma.

**Code**

```ts
declare const anything: any[];

let a;

[
  a,
] = anything;

let [
  b,
] = anything;

```

**Expected behavior:**
no error

**Actual behavior:**
```
test.ts:6:4 - error TS1013: A rest parameter or binding pattern may not have a trailing comma.

6   a,
     ~
```

Per [ECMAScript Spec](https://tc39.github.io/ecma262/#prod-ArrayBindingPattern), the trailing comma is allowed in a binding pattern without rest element.

> image

**Playground Link:**  
[link](http://www.typescriptlang.org/play/index.html#src=declare%20const%20anything%3A%20any%5B%5D%3B%0D%0A%0D%0Alet%20a%3B%0D%0A%0D%0A%5B%0D%0A%20%20a%2C%0D%0A%5D%20%3D%20anything%3B%0D%0A%0D%0Alet%20%5B%0D%0A%20%20b%2C%0D%0A%5D%20%3D%20anything%3B%0D%0A)

**Related Issues:** 

(from prettier/prettier#4624)

### PR DESCRIPTION
**Pull request by bakkot**
Fixes #24628.

cc @andy-ms for the original change in #22262.

### CODE REVIEW

**Comment by mhegazy** [comment]
thanks @bakkot!

**Comment by swar30** [comment]
Will this be in 2.9.3 ?

**Comment by mhegazy** [comment]
No. TS 3.0, should be out next week.

**Comment by JeromeLin** [comment]
This problem still exists in the 3.0.1

**Comment by JeromeLin** [comment]
@andy-ms in React component

`
import React, { PureComponent } from 'react';

export interface ButtonProps {
  size?: 'large' | 'normal' | 'small';
}

export default class Button extends PureComponent<ButtonProps, {}> {
  render() {
    const {
      size,
      children,
      ...others,     // error line
    } = this.props;
    return <a {...others}>{children}</a>
  }
}
`

**Comment by JeromeLin** [comment]
@bakkot thanks. this problem has been solved.
I remove that comma，and add `esSpecCompliant` option in tslint config.

**Pull request merged**
