### PR TITLE
Explicitly Omit unspreadable properties from rest type in the generic case

### LINKED ISSUE #46967: Using rest destructing on class objects seems to include getters in the resulting type
# Bug Report

If you have a class along the lines of:

````ts
class User {
    constructor(
        public uid: number,
        public password: string // sensitive info
    ) { }
	
    get score(): number {
        return 10; // example code - imagine having to fetch something a little more complex
    }
}
````

If we then want to destructure a `User` object (e.g. returning a client-friendly basic object from a server), we first declare a type:

````ts
type UserClient = Omit<User, 'password' | 'score'>;
````

We pass `score` to the `Omit` here because, as we're using destructing, only basic properties will be returned, not any getters. We can then create our method:

````ts
toClient(): UserClient {
    const { password, ...client } = this;
    return client;
}
````

However, `score` is something that we want to return, so we change our `UserClient` type to:

````ts
type UserClient = Omit<User, 'password' | 'score'> | { score: number };
````

and our `toClient()` method now becomes:

````ts
toClient(): UserClient {
    const { password, ...client } = this;
    return {
        score: this.score,
        ...client
    }
}
````

This, however, gives the error `'score' is specified more than once, so this usage will be overwritten`, even though when we destructure an object, it doesn't give us the getters - it seems like the inferred type from this line:

````ts
const { password, ...client } = this;
````

is wrong (specifically, it's `Omit<this, 'password'>` for `client`). In order to fix it, I need to change that line to 

````ts
const { password, score, ...client } = this;
````

This doesn't really have any effect on the underlying JavaScript code, so it's a minor bug (I think)

### 🔎 Search Terms

- `rest`
- `destructuring`

### 🕗 Version & Regression Information

I'm currently on `4.4.3` though running in TypeScript Playground, `3.9.7` is when it first seems to show up.

In that version, the inferred type is `Pick<this, Exclude<keyof this, "password">>`

In 3.8.3 the inferred type is the same, though the error isn't present, so there must have been a change to the underlying `Pick` code (perhaps to include getters?)

- This changed between versions 3.8.3 and 3.9.7

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.4#code/MYGwhgzhAECqEFMBO0DeAoAkMA9gOwgBckBXYQnJACi0wAcSAjEAS2GhJYBMAuaPEgFtGyADS0GzNtDqQIAd0q9oRJCzwBzaAHptKhARaEWANwTR1AMxxYAlGmgBfLFg0JCK3EgRVbfAcLIaLTehCRIeNAAjAAMANw6eggAHmCCdCDmuFzmALQWgmAa6uYAFmAm6loU0JbuwKUqOILupVXQYNCshISZ0IKUWc0ZKVjO6NCT0BQAwqwGhL588MhzLAvBU1vQuAQeqDJyikhcotAAdJeg63gejtAAvNNtEHET25Oh4ZEYHx8QXgQfEIL3OAMG4j+20u52uC3eH2cW2czkIAE86OYVkg1hsngB5QRGAA82LOAHJZFBjlxydAAD7Qcng7zkgB8DIcLKB-CEIhQjjiQA

### 💻 Code

```ts
class User {
    constructor(
        public uid: number,
        public password: string // sensitive info
    ) { }
	
    get score(): number {
        return 10; // example code - imagine having to fetch something a little more complex
    }

    toClient(): UserClient {
        const { password, ...client } = this;
        return {
            score: this.score, // ERROR: 'score' is specified more than once, so this usage will be overwritten
            ...client
        }
    }
}
type UserClient = Omit<User, 'password' | 'score'> | { score: number };
```

### 🙁 Actual behavior

The inferred type on `client` seems to include getters

### 🙂 Expected behavior

The inferred type on `client` to only include basic properties as it's created through destructuring

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #46967

In the non-generic case, we'd produce a concrete type that consisted only of the spreadable properties, excluding already destructured and unspreadable properties. This is good.

However, in the generic case (including `this`, as it's an implicit type parameter), we instead produced an `Omit` type, but only omitted the already destructured keys. This left a type where all of the unspreadable properties (e.g. properties with getters, methods) where left accessible.

Make the generic case match the behavior of the non-generic case by also adding the unspreadable items to the omitted set of keys.

This might get pretty hairy for types with lots of getters/setters/methods, though, but the alternative (making a concrete type instead if it looks like `Omit` can't handle it) appears to break a few tests in even more undesirable ways. Hopefully destructuring `this` with a rest is not all that common (the user tests imply it is not).

Additionally, I don't know if the behavior on non-public properties is correct; it seems weird that destructuring `this` within the class would only keep the public properties, even though at runtime they are there. They're dropped in the `T extends SomeClass` case because that's a use where those symbols are not intended to be visible, but internally, maybe it's not right to drop them.

Before: [Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XWAewHYQC4CcBXYXDfAChTWoAdCAjEAS2GjsZYAV8MaAuaHnxMsAcwA0VaqhrCAbmFwBTNvMVLuvAUJESp0AJSIAvkn2iluaBdzKKBgVkIBbekvyJ91fJcL4s0ACMANz6pvoQloKWduQA+nKOLm74Rgjh1M6WABYYACbkaV5omDhWCNKVlQB0tT54gdDG0AC80LjZTBChVdAA9H29Q70AegD8xaileIjDVbXV9bgATE2t7Z0wkHA9VQNzB6jjk+jYMxXszMCa-NBxgeLQC0sAzGttHV27lfuHc8e9ablNgMK43ARxZaPZ5KPAAFneGy60G2sG+0l+fyGxxOS0C1UuXB4NHR3lhKwJoKJvFJaFelI412JtNQSzhDLBzLMvTxBLUyhuLOgS2WfKYCgFXJ55JeYolGilVTZcvUgu5SvJ+JsdiFIuq2vcupl+pihtx5PZBvwoXNDWqkVsZuleFFDp1ttwsrdTo18Ptput6sqvKyHXyRpd1VDuTyEc9UZy4Y97OjSeopnCADNCFgSExsNA8uSiCQ-EoADwAFWgSgAHsosHkYLAAHzkWsCStFahA2ZYp51TWI2vozH9yoAkpnYH9mEu4co5ujwbjqqTqbT2aEplaO4PAeLGXD5ertcTHubi5Une3SHQwfwheok+n6Q4sl27dqj8Ur+K1nGn+NL6MqQEkkGwqaiqkrAT+oqyOKqr-pBeCygh8rfnSFrQQqwEgVBVronqhH4ahJqOoGP6WgGNo-vi3qUVhkYMURxosaRuDsuxHH4qmsYcaKfGsWRQkcSmib8cYQA)

After: [Playground Link](https://www.staging-typescript.org/play?ts=4.6.0-pr-47078-3#code/MYGwhgzhAECC0G8BQ1XWAewHYQC4CcBXYXDfAChTWoAdCAjEAS2GjsZYAV8MaAuaHnxMsAcwA0VaqhrCAbmFwBTNvMVLuvAUJESp0AJSIAvkn2iluaBdzKKBgVkIBbekvyJ91fJcL4s0ACMANz6pvoQloKWduQA+nKOLm74Rgjh1M6WABYYACbkaV5omDhWCNKVlQB0tT54gdDG0AC80LjZTBChVdAA9H29Q70AegD8xaileIjDVbXV9bgATE2t7Z0wkHA9VQNzB6jjk+jYMxXszMCa-NBxgeLQC0sAzGttHV27lfuHc8e9ablNgMK43ARxZaPZ5KPAAFneGy60G2sG+0l+fyGxxOS0C1UuXB4NHR3lhKwJoKJvFJaFelI412JtNQSzhDLBzLMvTxBLUyhuLOgS2WfKYCgFXJ55JeYolGilVTZcvUgu5SvJ+JsdiFIuq2vcupl+pihtx5PZBvwoXNDWqkVsZuleFFDp1ttwsrdTo18Ptput6sqvKyHXyRpd1VDuTyEc9UZy4Y97OjSeopnCADNCFgSExsNA8uSiCQ-EoADwAFWgSgAHsosHkYLAAHzkWsCStFahA2ZYp51TWI2vozH9yoAkpnYH9mEu4co5ujwbjqqTqbT2aEplaO4PAeLGXD5ertcTHubi5Une3SHQwfwheok+n6Q4sl27dqj8Ur+K1nGn+NL6MqQEkkGwqaiqkrAT+oqyOKqr-pBeCygh8rfnSFrQQqwEgVBVronqhH4ahJqOoGP6WgGNo-vi3qUVhkYMURxosaRuDsuxHH4qmsYcaKfGsWRQkcSmib8cYQA)

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot pack this
@typescript-bot user test this

**Comment by RyanCavanaugh** [comment]
> Additionally, I don't know if the behavior on non-public properties is correct; it seems weird that destructuring this within the class would only keep the public properties, even though at runtime they are there.

This is good; we're "allowed" to have types which don't represent the full list of properties present at runtime (this is the same logic by which `A` is assignable to `Record<keyof A, unknown>`, and access to those members is only supposed to be allowed through references of the actual class type from within the class (whereas these object types can "leak" out in a bunch of ways). Having a spread inside the class work the same as a spread outside the class (and not have properties which aren't there) is the more important bit.

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by jakebailey** [comment]
> Having a spread inside the class work the same as a spread outside the class (and not have properties which aren't there) is the more important bit.

Good, less work for me! 😄

**Comment by jakebailey** [comment]
Updated the PR to also test `protected`, now that I know that my behavior is correct.

**Comment by DanielRosenwasser** [comment]
This is less about `Omit` and more about all mapped object types right?

**Comment by jakebailey** [comment]
Yes, this is related to property spreading of a value with unspreadable properties; `Omit` is just the method we use when the thing being spread is generic (when concrete, we just make a new object type).

**Comment by kasperpeulen** [comment]
@jakebailey But this still breaks on runtime if you uses interface that are implemented with a class, right?


```ts

interface Thing {
  someProperty: number;

  someMethod(): void;
}

function foo<T extends Thing>(x: T) {
  let { someProperty, ...rest } = x;

  // Not an error, but will break on runtime with: foo(new MyThing());
  rest.someMethod();
}

class MyThing implements Thing {

    someProperty = 42;

    someMethod() {
        // ...
    }

}

// fine
foo({ someProperty: 1, someMethod: () => { } });

// breaks on runtime
foo(new MyThing());
```

**Comment by jakebailey** [comment]
Sure, but that's code doesn't error before this PR too. I'd file a new issue for that (though there's probably an issue somewhere about how these sorts of own property semantics aren't fully modeled).

**Comment by Beraliv** [comment]
Hello!

Thank you for your changes, I really appreciate it!

I have one question out of curiosity: if I have a constructor where I bind methods, they should be allowed for the rest type, right? At the moment I see error that `Property 'someMethod' does not exist on type 'Omit<T, "someProperty" | "someMethod">'`

Playground – https://tsplay.dev/mMMebm

<details>
  <summary>Example</summary>
  
  ```typescript
class Thing {
    someProperty = 42;

    constructor() {
        this.someMethod = this.someMethod.bind(this);
    }

    someMethod() {
        // ...
    }
}

function foo<T extends Thing>(x: T) {
    let { someProperty, ...rest } = x;

    // Used to work, is now an error!
    // Property 'someMethod' does not exist on type 'Omit<T, "someProperty" | "someMethod">'.
    rest.someMethod();
}
  ```
  
</details>

Should I create an issue for it? @RyanCavanaugh

**Comment by jakebailey** [comment]
I would file a new issue (as this is the wrong place to discuss it), but I'm not sure that we do anything special for a method bound like that. Check out the `d.ts` file output given in your example; the method's type is identical whether or not the constructor reassigns it.

This is no different than how we've always behaved in the non-generic case: [Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqAWBLAdgc2gbwFDV9CA9gLYCmACgE4EAOJFALgJ7QC80ALAEwDcWOewAsgj0KAV2D0CFABQBKTPzx56SCADpCpALIlVBACatoqxBq0ld+g+oBGKAzNMQ5vZQF8+yi1fiH5isrKgsIEICTqIASoMgBEABKI0ABmVET4xJZ6fgaxckrQnp5YyWLIkohCKQQEMgAeAFxwSGgK2Mrh9JgZpJQ0dEwANNDqoxQkIoXGdbwFAPRz0ACqECRGUtAA7tIA1sNm0MgEm9BgyNB0VBQAhPOLfbQMzADkPtmGz9AGBBOHBF0kOpmLpVJi0aDPADyREQ9AAPLBhrELA8BoxYtAAD7QZGZXyGWIAPme6gK4xEmjx70criwxWSNRkyBIJwQKBiclcQA)

This PR made things consistent between the two.

**Pull request merged**
