### PR TITLE
Mapped symbol

### LINKED ISSUE #25607: Services for non-homomorphic mapped type
**TypeScript Version:**  3.0.0-dev.20180712

**Code**

```ts
interface I {
 a: number;
 b: number;
}
type J = { [K in "b"]: I[K] };
declare const j: J;
j.b; // Go-to-definition does not work
```

**Expected behavior:**

Since the type we're getting is `I[K]`, the mapped property symbol should have a reference back to the corresponding property in `I`.

**Actual behavior:**

The mapped type creates an unrelated property symbol and services don't work.

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #25607

### CODE REVIEW

**Comment by w0nche0l** [comment]
This would be amazing to have for refactoring purposes, is there anything specifically blocking this? or is it just that people haven't gotten around to looking at it yet?

**Comment by Kingwl** [comment]
@typescript-bot test this

**Comment by Kingwl** [comment]
This is the latest 2 (maybe only one soon) issues of Community milestone...

**Comment by xiaoxiangmoe** [comment]
@Kingwl can you pack this？

**Comment by xiaoxiangmoe** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
This PR is outdated and I'm even cannot merge master....

**Pull request closed without merging**
