### PR TITLE
Add jsdoc to all js statements

### LINKED ISSUE #39516: jsdocs typedef doesn't work when declared before `if`
*TS Template added by @mjbvz*

**TypeScript Version**: 4.0.0-dev.20200702

**Search Terms**
- jsdoc
- typedef

---

- VSCode Version: 1.46.1
- OS Version: OSX Mojave 10.14.6

It seems that typedef are skipped if the code has some "conditional" unreachable code.
Have a look at the code examples with screenshots.

Steps to Reproduce:

Here are two versions of the code, one where jsdocs fails, and one when it works.

### a. Buggy version, when typedef is declared before conditional / unreachable code 
```js

/**
 * @typedef {{id: string}} SomeType
 */

if (true) {
  throw new Error('Unreachable')
 // could be process.exit()
}

/**
 * @param {SomeType} someType
 */
function doSomething (someType) {
}

```

Result: no types

Screenshot 2020-07-08 at 12 42 32

### b. Working version, when typedef is declared after conditional / unreachable code 
```js

if (true) {
  throw new Error('Unreachable')
 // could be process.exit()
}

/**
 * @typedef {{id: string}} SomeType
 */

/**
 * @param {SomeType} someType
 */
function doSomething (someType) {
}

```

Result: we have types
Screenshot 2020-07-08 at 12 42 54

Does this issue occur when all extensions are disabled?: Yes/No
(I don't know how to pass arguments to vs code on OSX)

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #39516

This is the simplest solution -- just add jsdoc to all statements if it's there, but it doesn't seems to cause a performance problem, so I think it's fine.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
Perf tests look fine.

**Comment by andrewbranch** [comment]
Change seems relatively small; can you think of any other areas that are likely to see unintended consequences of this that we should pay attention to?

**Comment by sandersn** [comment]
No, this is strictly additive, which is why I was concerned about performance the most.

Two minor issues:

1. In theory almost any node could have a typedef in front of it. But I think we can fix that lazily just like this time. It's rare enough that it may never be a problem.
2. The function that tries to find a name for an anonymous typedef will not find one from any of these statements. I *guess* you could look inside a `for`'s initialisation step to get a name, but it seems like a huge reach.

**Comment by sandersn** [comment]
Test is added and sure enough I missed one of the cases in `parseBlock`.

**Review by andrewbranch — APPROVED** [review]
Yeah, I can’t imagine needing to look for typedefs on non-statements.

**Pull request merged**
