### PR TITLE
fix(46611): Typescript may not recognize jsdoc @type on class method

### LINKED ISSUE #46611: Typescript may not recognize jsdoc `@type` on class method
# Bug Report
Typescript may not recognize jsdoc `@type` on class method

### 🔎 Search Terms
`jsdoc` `@type` `@typedef` `class method` `strict` `@ts-check`

### 🕗 Version & Regression Information
Version 4.4.4
Version 4.5.0-dev.20211028

### Reproduce Repo
https://github.com/loynoir/reproduce-typescript-46611.js

### 🙁 Actual behavior
```js
  // TS7006: Parameter 'a' implicitly has an 'any' type.
  // TS7006: Parameter 'b' implicitly has an 'any' type.
  /**
   * @type {bar}
   */
  bar1(a, b) {
    void a;
    void b;
    return false;
  }


  // a is typed as string, and b is typed as number
  /**
   * @type {(...args:Parameters<bar>)=>ReturnType<bar>}
   */
  bar2(a, b) {
    void a;
    void b;
    return true;
  }
```

### 🙂 Expected behavior
```js
  // a is typed as string, and b is typed as number
  /**
   * @type {bar}
   */
  bar1(a, b) {
    void a;
    void b;
    return false;
  }


  // a is typed as string, and b is typed as number
  /**
   * @type {(...args:Parameters<bar>)=>ReturnType<bar>}
   */
  bar2(a, b) {
    void a;
    void b;
    return true;
  }
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #46611

### CODE REVIEW

**Review by sandersn — CHANGES_REQUESTED** [review]
Making all methods context-sensitive so that `@type` works on JS methods seems incorrect. Do function declarations use the contextual type to get their type from `@type`? I don't think they do.

If this does turn out to be the best way, we need some new tests for method contextual type now that they're context-sensitive. Maybe tests like

```ts
class C { m(n: number) { return n } }
const D: typeof C = class { m(n) { return n } }
```

**Comment by a-tarasyuk** [comment]
@sandersn Thanks for the feedback. This is only allowed in JS, similar to `FunctionDeclaration`. 

```ts
return (isInJSFile(func) && isFunctionDeclaration(func) || isFunctionExpressionOrArrowFunction(func) || isMethodDeclaration(func)) && ...
```

**Comment by sandersn** [comment]
Yes. Looking around the code, it seems like it *might* use contextual typing.

Looking at the original bug again, it's strange that `@type` on methods works for a object type with a signature, but not for a type reference. I guess that could be a breakdown caused by contextual typing?

**Comment by a-tarasyuk** [comment]
@sandersn Do I need to investigate contextual type resolutions for a type reference to fix this issue?

**Comment by sandersn** [comment]
Well, *return* types are checked without contextual typing: the following example has an error:

```ts
/** @typedef {(a: 1, b: 2) => boolean} Foo */
class C {
  /** @type {Foo} */ one (a,b) { return 1 }
}
```

That's from `checkReturnStatement`, which uses `getSignatureFromDeclaration >> getReturnTypeOfSignature`.

I'll see what goes wrong with parameters.

**Comment by sandersn** [comment]
The code in `getTypeForVariableLikeDeclaration` has a check that requires its type annotation to be a function type, syntactically. I believe that the code should actually be

```ts
                    const typeTag = getJSDocType(func);
                    if (typeTag) {
                        const signature = getSignatureFromDeclaration(func);
```

not

```ts
                    const typeTag = getJSDocType(func);
                    if (typeTag && isFunctionTypeNode(typeTag)) {
                        const signature = getSignatureFromDeclaration(typeTag);
```

Or something similar -- that doesn't seem to work when I test it.

**Comment by sandersn** [comment]
Nope, try this instead:

Underneath getReturnTypeOfTypeTag:

```ts
        function getParameterTypeOfTypeTag(func: FunctionLikeDeclaration, parameter: ParameterDeclaration) {
            const signature = getSignatureOfTypeTag(func);
            const pos = func.parameters.indexOf(parameter);
            return !signature ? undefined
                : parameter.dotDotDotToken ? getRestTypeAtPosition(signature, pos)
                : getTypeAtPosition(signature, pos);
        }
```

and in `if (isJSFile(declaration))` in getTypeForVariableLikeDeclaration:

```ts
                    const type = getParameterTypeOfTypeTag(func, declaration)
                    if (type) {
                        return type;
                    }
```

**Comment by a-tarasyuk** [comment]
@sandersn I added the requested changes.

**Pull request merged**
