### PR TITLE
CI Against Node 4.1

### PR DESCRIPTION
**Pull request by weswigham**
Perf isn't as bad as 0.12, and it's the new LTS release series. TBH, we should probably also CI against `'node'` for the latest public version.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
actually 4.2 will be LTS release https://github.com/nodejs/node/issues/3000#issuecomment-144894835

**Comment by weswigham** [comment]
Good to know.

**Comment by mzgol** [comment]
It's better to add "4" instead of "4.1" or "4.2".

**Comment by weswigham** [comment]
@mhegazy node 4.2 LTS has been released and the 4.x series is now slated to be supported for the next 30 months... maybe we should turn this on?

**Comment by mhegazy** [comment]
:+1:

**Pull request merged**
