### PR TITLE
Allow discrimination to identical object types when discriminating contextual types

### LINKED ISSUE #37231: Type inference with map & (otherMap | otherMap2) fails
**TypeScript Version:**  Nightly

**Search Terms:** None (I couldn't come up with any, please excuse me)

**Code**

```ts
type Entity = {
  someDate: Date | null;
} & ({ id: string; } | { id: number; })

type RowRendererMeta<TInput extends {}> = {
  [key in keyof TInput]: { key: key; caption: string; formatter?: (value: TInput[key]) => string; };
}
type RowRenderer<TInput extends {}> = RowRendererMeta<TInput>[keyof RowRendererMeta<TInput>];

const test: RowRenderer<Entity> = {
  key: 'someDate',
  caption: 'My Date',
  formatter: (value) => value ? value.toString() : '-' // value: any
}

const thisIsNotTheIssue: Partial<RowRendererMeta<Entity>> = {
  someDate: {
    key: 'someDate',
    caption: 'My Date',
    formatter: (value) => value ? value.toString() : '-' // value: Date | null
  }
}
```

**Expected behavior:**
TypeScript inferes the argument of `formatter` to be `Date | null`.

**Actual behavior:**
When removing the ` & ({ id: string; } | { id: number; })` part of the `Entity` type definition, everything works as expected. However including it breaks type inference, resulting in an implicit any error/warning (depending on configuration), though it does not break the `RowRendererMeta<...>` type, as shown in the second `const` declaration.

**Playground Link:** [Playground Link](https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200304&ssl=22&ssc=2&pln=1&pc=1#code/C4TwDgpgBAogdsAlqKBeKBvAsAKClAZwHsBbCAEQENgIAuKKmqAHyjgFcAbTgblwF8oAMigAKDFEQATegWAAnRHADmPKINYTp9DiQBGEeWv4BKXLlCQoAJSIB3axDhTDhgLIRglADwAVAJJwYOzAUBAAHjTOBJj8AHxomLj4ANoA1hAgknBQGSBEAGZQAUEhALr0Enn0eWoAxpRgSERwsgpKqlAFRPIk1DTyAPz0ogBulJzsdMWBwcDpmWUmaAlyiirGfDj8FuDQtg5OLvKGfrMhYZFHMRjxiQeOzq7yHl5npcBxC-lFD0fPrx8JTmcTKW1wdRacigNDk9D+TxO8m88CQoAS6GweFymXoAHJiGRGBA8QAaZJQBpNRAtfFuLLEskU7q9fqGEbjSYQZaoBKcqZQQZQfkQAB0wCIAGV2ipRMt8QBaPFQAD0KuFEym9EocBAAnMOEhcGhwAAFogCP4CAA5IjAXymiBWghaqAABUo8iQE28COO7k8PlRyBAcQxSWxhIo1GmWPw+GqUAJpGjNCZ2PwVOarST9IYMfT8a6PT6wAGHM13JWGq5gprU3FUplyjlUEVyrV9emxJYbC4nApO22QA)

**Related Issues:** None found.

**Edit:** Inference for `id` sadly does not seem to work at all.

**Edit 2:** Even though TS seems not to infer the type of the function argument, it complains when you try to use an invalid type (in this example `string` to name one).

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #37231

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Comment by weswigham** [comment]
> 🔻+33.75s (+251.55%)

_what the heck_

**Comment by ahejlsberg** [comment]
I'm not surprised. `material-ui` has some _very_ large types that are _very_ similar, and the identical object types check is an O^2 structural check that quickly generates lots of work.

**Comment by weswigham** [comment]
But in this case we're only invoking it when a literal position has possibly discriminating fields, to reduce the types we're discriminating against... which I'd hoped would limit how often it's invoked quite a bit. And yet still the check time _nearly tripled_, ack. Well, the root cause of the original issue is there being two structurally identical discriminable types in a union - maybe I can tweak the contextual type discrimination rules a bit to allow structurally identical members, instead?

**Comment by ahejlsberg** [comment]
> maybe I can tweak the contextual type discrimination rules a bit to allow structurally identical members, instead?

Definitely think you're better off with that strategy.

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Comment by weswigham** [comment]
Much better - perf diffs mostly within the variance measurements. @ahejlsberg @sandersn wanna give this a review?

**Review by sandersn — APPROVED** [review]

**Pull request merged**
