### PR TITLE
Detangle unittests to reference helpers directly

### PR DESCRIPTION
**Pull request by sheetalkamat**
Also moved some of the functions to local files and deleted a few that are no longer needed.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
The tests passed locally so i thought this should be ok.. But i will see whats going on.. Basically in my big PRs i am getting completely confused when fixing merge conflicts which import i am suppose to use for unittests that i am adding as there are so many ways to reference say TestServerHost

**Comment by jakebailey** [comment]
> But i will see whats going on.

Basically, the code might work under a bundler, but if we are unbundled (--bundle=false), things can break because the cycles start to matter there. This is the main reason why we need to untangle things, but we have to make it work in both scenarios.

This is the nightmare I've been dealing with and why I gave up on direct imports for the first iteration of the modules change. It's going to be fun to untangle this and make our code a DAG.

**Comment by jakebailey** [comment]
This LGTM but I know @andrewbranch is working on stuff which modifies a lot of unittests, so he might want to look and see.

**Comment by andrewbranch** [comment]
My upcoming changes are mostly just going to touch trace baselines. Thanks for the heads up though!

**Pull request merged**
