### PR TITLE
Added caches to tsc's CompilerHost

### PR DESCRIPTION
**Pull request by timocov**
Related issues: https://github.com/Microsoft/TypeScript/issues/26871, https://github.com/TypeStrong/ts-loader/issues/825.

After debugging the compiler I have been noticed that some functions are called multiple times with the same arguments (for example, in our project `tsc` tried to check that `tslib` file exists almost 3k times).

Quite possibly that such behavior is related to set `baseUrl` compiler option.

For example, I have observe the following situation in our project (I don't understand what exactly affects on this):

Let's say that some file is placed `/project/src/sub-folder` folder, `baseUrl` option is set to `./src`, `importHelpers` option is enabled, and the file needs to import helpers from `tslib`.
In our case we get the next requests in `tryFile` function:

```
/project/src/tslib.ts
/project/src/tslib.tsx
/project/src/tslib.d.ts
/project/src/tslib/index.ts
/project/src/tslib/index.tsx
/project/src/tslib/index.d.ts
/project/src/sub-folder/node_modules/tslib.ts
/project/src/sub-folder/node_modules/tslib.tsx
/project/src/sub-folder/node_modules/tslib.d.ts
/project/src/sub-folder/node_modules/tslib/index.ts
/project/src/sub-folder/node_modules/tslib/index.tsx
/project/src/sub-folder/node_modules/tslib/index.d.ts
/project/src/sub-folder/node_modules/@types/tslib.d.ts
/project/src/sub-folder/node_modules/@types/tslib/index.d.ts
```

This requests are made before `tslib` is resolved from `/project/node_modules` folder.

`tsc` makes at least 14 extra syscalls. But yeah, we can have local `tslib` and then resolving will stop.

The same resolving will be performed for all other files from `/project/src/sub-folder` folder.

Perhaps this example is related to `tslib` only, and for other imported modules the compiler makes less requests.

This PR adds caches for some CompilerHost's functions while compiling via `tsc`.

Below are some diagnostics for our project (average of 3 runs).

_(our project is not compiled with `master` branch yet due https://github.com/Microsoft/TypeScript/issues/26978, but I believe the differences will be very similar)_

**typescript@3.0.1 (from npm):**

```
Files:            1777
Lines:          227581
Nodes:         1042040
Identifiers:    316854
Symbols:        422329
Types:          158437
Memory used:   530938K (550667K, 491876K, 550273K)
I/O Read time:   1.91s (1.95s, 1.88s, 1.89s)
Parse time:      2.29s (2.34s, 2.22s, 2.30s)
Program time:    11.3s (11.26s, 11.32s, 11.32s)
Bind time:       1.98s (2.00s, 1.94s, 1.99s)
Check time:     14.22s (14.39s, 14.23s, 14.04s)
Total time:     27.39s (27.65s, 27.16s, 27.36s)
```

**release-3.0 branch with applied fixes:**

```
Files:                                 1777
Lines:                               227581
Nodes:                              1042040
Identifiers:                         316854
Symbols:                             422329
Types:                               158437
Memory used:                        535512K (531989K, 534535K, 540012K)
I/O Read time:                        2.06s (2.27s, 1.87s, 2.03s)
Parse time:                           2.42s (2.40s, 2.45s, 2.42s)
Program time:                         7.37s (7.46s, 7.30s, 7.36s)
Bind time:                            2.03s (1.99s, 2.05s, 2.05s)
Check time:                          14.88s (14.65s, 15.94s, 14.04s)
fileExists cache hits count:           9310
fileExists cache misses count:         6126
directoryExists cache hits count:     28806
directoryExists cache misses count:    2381
Total time:                          24.27s (24.09s, 25.28s, 23.45s)
```

**Difference:**

```
Memory used:   -4574K (-0.8%)
I/O Read time: -0.15s (-7.8%)
Parse time:    -0.13s (-5.7%)
Program time:  -3.93s (-35.0%)
Bind time:     -0.04s (-2.5%)
Check time:    -0.66s (-4.5%)
Total time:    -3.12s (-11.4%)
```

I believe that here only `Program time` and `Total time` are valuable.

I hope this fix can help someone improve its build speed.

Open questions:

1. Perhaps we need to put these caches inside `createCompilerHost` function instead? If so, what about `createSolutionBuilderHost` in `tsbuild.ts` - it seems that it uses `createCompilerHost` as host for watch mode?
1. Do we need to have performance marks for caches and output them with diagnostics?
1. What about `createWatchCompilerHost`? It is possible that we can use caches while compilation and clear it right before compilation start.
1. Do we need to cache any other function from compiler host?

### CODE REVIEW

**Comment by timocov** [comment]
@sheetalkamat you marked this PR as "requested changes", but can you please say what kind of changed I need to do? Or it means that this PR never will merged?

**Comment by timocov** [comment]
@RyanCavanaugh @DanielRosenwasser anybody? 🙁

**Comment by timocov** [comment]
@RyanCavanaugh Any updates?

**Comment by sheetalkamat** [comment]
@timocov closing this in favor of #28629

**Pull request closed without merging**
