### PR TITLE
Support template literals in preProcess (fixes #33680)

### LINKED ISSUE #33680: ts.getPreProcessedFileInfo doesn't detect imported files from import(`template`) and require(`tempalte`)
**TypeScript Version:**  3.6.3, 3.7.0-dev.20190928

**Search Terms:**

**Code**

```ts
const ts = require('typescript');

const lines = [
    'const rs = require("rs.ts");',
    'const rt = require(`rt.ts`);',
    'const is = import("is.ts");',
    'const it = import(`it.ts`);',
].join('\n')

console.log(ts.preProcessFile(lines, true, true));
```

**Expected behavior:**

```js
{
    referencedFiles: [],
    typeReferenceDirectives: [],
    libReferenceDirectives: [],
    importedFiles: [
        { fileName: 'rs.ts', pos: 19, end: 24 },
        { fileName: 'rt.ts', pos: 48, end: 53 },
        { fileName: 'is.ts', pos: 76, end: 81 },
        { fileName: 'it.ts', pos: 104, end: 109 }
    ],
    isLibFile: false,
    ambientExternalModules: undefined
}
```

**Actual behavior:**

```js
{
    referencedFiles: [],
    typeReferenceDirectives: [],
    libReferenceDirectives: [],
    importedFiles: [
        { fileName: 'rs.ts', pos: 19, end: 24 },
        { fileName: 'is.ts', pos: 76, end: 81 }
    ],
    isLibFile: false,
    ambientExternalModules: undefined
}
```

Because `src/services/preProcess.ts` only checks for `StringLiteral`'s bun not for `NoSubstitutionTemplateLiteral`'s which were allowed there for a long time.

**Playground Link:** N/A

**Related Issues:** found during implementing #32064 , but this syntax and type checked worked long before this PR

### PR DESCRIPTION
**Pull request by IllusionMH**
Fixes #33680

Should process template literals in all positions where TS support them. Should correctly return full list when `ts.preProcessFile` is called.

I also tried to write test like https://github.com/microsoft/TypeScript/blob/98cf317005d62a9b275e1f1b37a18b7f5b457e74/tests/cases/fourslash/shims-pp/getPreProcessedFile.ts
but when I use dynamic imports
```ts
/// <reference path="fourslash.ts" />
// @module: esnext
// @target: esnext

// @Filename: main.ts
// @ResolveReference: true
//// const a = import(/*1*/`wrong`/*2*/);

goTo.file("main.ts");
verify.numberOfErrorsInCurrentFile(1);
verify.errorExistsBetweenMarkers("1", "2");
```

I receive 3 errors
```
Unexpected error(s) found.  Error list is:
  global, message: Cannot find global value 'Promise'.

  from: 0:10, to: 0:25, message: A dynamic import call in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

  from: 0:17, to: 0:24, message: Cannot find module 'wrong'.

Actual number of errors (3) does not match expected number (1)
```
Where only 3rd error was expected.

Setting module to `commonjs` or target to `es2015` doesn't help.

Do I need to add tests for error reporting on wrong references (3rd error)? Any suggestions how to avoid unexpected errors?

### CODE REVIEW

**Comment by joscha** [comment]
references #36546

**Comment by sandersn** [comment]
I closed/re-opened the PR to re-run tests, just to see whether tests still pass after sitting for 6 months.

**Comment by IllusionMH** [comment]
Should I rebase on top of `master`?

**Comment by sandersn** [comment]
It would be nice -- I didn't know you were still paying attention to this PR @IllusionMH!

**Comment by IllusionMH** [comment]
Rebased. Sorry for delay - local test/lint took 28mins

> I didn't know you were still paying attention to this PR @IllusionMH!

I didn't know when/if it will be reviewed/merged, so decided to avoid unnecessary notification spam on pushes.
Unfortunately there are no notifications for project board moves and I've missed changes few days ago.

**Comment by sandersn** [comment]
(I treat no-notifications as a feature so I can move things around all over the place without spamming people.)

**Comment by sandersn** [comment]
Everything but node 10 and node 8 on Travis is done, so I'm going to merge this.

**Comment by IllusionMH** [comment]
Thanks!

Yeah, it's great that there are no labels/project spam all the time for sure :)

**Pull request merged**
