### PR TITLE
Handle browserify-ignored module result for etw logger

### LINKED ISSUE #33224: Browserify require('typescript) error on windows
I do not know how to make a self-contained report of this bug, because I don't really know what's causing it. The code below is the *javascript* I'm using that is creating the bug.

```js
let ts = require("typescript");
...
let tsAnswer = ts.transpile(answer);
```

**Expected behavior:**
I can transpile code for an online playground-type thing (specifically a typescript version of CodingJS from https://github.com/the-winter/codingjs
**Actual behavior:**
I get an error and can't even open the page. The error is:
`TypeError: ts.perfLogger.logInfoEvent is not a function`

**Platform** Windows 10

I was able to solve this problem by downgrading typescript in the project to version 3.5.3. I suspect the issue comes from #32612 . It's possible I need to add a new package, but the code is not working as is, which is a bug.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #33224

### CODE REVIEW

**Comment by weswigham** [comment]
cc @DanielRosenwasser we'll need to port this patch to 3.6 to fix browserifying TS 3.6 🤦‍♂

**Comment by DanielRosenwasser** [comment]
Tell the bot, that's what they're here for! 😁

**Comment by weswigham** [comment]
Hey, I just wanted you to know before we cut a release @DanielRosenwasser

@typescript-bot cherry-pick this into release-3.6

**Comment by weswigham** [comment]
@DanielRosenwasser wanna actually 👍 this?

**Comment by AviVahl** [comment]
@weswigham while at it, mind also adding `"source-map-support": false` to the "browser" field of `package.json`? this would make typescript bundle with `webpack` as well. the line requiring this library is inside a try/catch, so it's safe.

I could open an issue though, if you want that issue addressed separately.

**Comment by weswigham** [comment]
Feel free to open - I didn't realize we required that outside the test harness.

**Pull request merged**
