### PR TITLE
Remove implicit tests/cases/compiler path prefix from VFS test files

### PR DESCRIPTION
**Pull request by andrewbranch**
Related to #54556 and #54506. Checked the diff patch with a regex to confirm that changes are either 1:1 path changes or removed lines from module resolution since there are fewer ancestor directories to look for node_modules in. One test file changed to use absolute paths with `// @out:` since `out` is super broken.

### CODE REVIEW

**Review by sandersn — APPROVED** [review]

**Comment by jakebailey** [comment]
Viewing the diff without the baseline changes, it seems good; we will probably need to be extra vigilant in the next few weeks to ensure that we rerun CI on any outstanding PRs lest they change.

Just to clarify, what is the motivation to remove the prefix? Just that it's weird that we include it? (Which, I agree with, but, confirming).

**Comment by andrewbranch** [comment]
Before #54556, the prefix was applied inconsistently; e.g. it was prepended to filenames, but not file paths in compiler options like `// @outDir: out`. Consequently, if you were writing a test that required on a relationship between input and output files, you had to know to include a magical prefix on `// @outDir: tests/cases/compiler/out`, but not on the `// @Filename` comments. I believe #54556 fixed this, but it still felt very fragile to me. In #54556, some baselines _added_ the `tests/cases/compiler` prefix to certain reported filenames, but this PR removes them from _many_ more, which seems to imply that the prefixing logic has always been applied inconsistently, in a way that I still don’t understand after spending a miserable few days in the code.

**Comment by rbuckton** [comment]
I think we should have the path prefix in the test output in _some_ way, since it helps you find the actual test when comparing diffs since our compiler and performance baselines are just dumped to a single folder. If we're going to make a sweeping change to our test outputs anyways, perhaps we should add a header line to the baseline to indicate the test source location relative to the repo.

**Comment by andrewbranch** [comment]
I can add that. Maybe there’s a VS Code extension that would recognize file paths in plain text / unrecognized language modes and let you ⌘-click to go to them. That would be nice.

**Comment by andrewbranch** [comment]
> Maybe there’s a VS Code extension that would recognize file paths in plain text / unrecognized language modes and let you ⌘-click to go to them

I added the header, but I’ve yet to find an extension like this.

**Comment by andrewbranch** [comment]
No baselines have changed in `main` since opening this. I’m going to go ahead and merge.

**Pull request merged**
