### PR TITLE
Fix mixin logic to preserve at least one constructor type even when the intersection also contains non-constructor types.

### LINKED ISSUE #17388: Cannot use 'new' error on intersection type with constructor
tsc: 2.4.2

```ts
class X { }
declare interface ConstructorAnyArgs<TClass> {
    new (...args: any[]): TClass
}


function foo(): ConstructorAnyArgs<X> { return }
function boo(): ConstructorAnyArgs<X> & { superclass: any } { return }

let Y = foo()
let y = new Y()

let Z = boo()
let z = new Z() // Cannot use 'new' with an expression whose type lacks a call or construct signature.
```

http://www.typescriptlang.org/play/index.html#src=class%20X%20%7B%20%7D%0D%0Adeclare%20interface%20ConstructorAnyArgs%3CTClass%3E%20%7B%0D%0A%20%20%20%20new%20(...args%3A%20any%5B%5D)%3A%20TClass%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20foo()%3A%20ConstructorAnyArgs%3CX%3E%20%7B%20return%20%7D%0D%0Afunction%20boo()%3A%20ConstructorAnyArgs%3CX%3E%20%26%20%7B%20superclass%3A%20any%20%7D%20%7B%20return%20%7D%0D%0A%0D%0Alet%20Y%20%3D%20foo()%0D%0Alet%20y%20%3D%20new%20Y()%0D%0A%0D%0Alet%20Z%20%3D%20boo()%0D%0Alet%20z%20%3D%20new%20Z()%20%2F%2F%20Cannot%20use%20'new'%20with%20an%20expression%20whose%20type%20lacks%20a%20call%20or%20construct%20signature.%0D%0A

### PR DESCRIPTION
**Pull request by mattmccutchen**
Fixes #17388.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
Willing to merge this if RWC is green or greenish

**Comment by RyanCavanaugh** [comment]
@weswigham the RWC PR doesn't match this at all - definitely a bunch of unrelated changes. Can you investigate?

**Comment by weswigham** [comment]
@ryancavanaugh you need to merge master into this PR - the RWC runner runs with the PR head, not the merge result

**Comment by mattmccutchen** [comment]
Updated to master.  Please try the RWC again.

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
Noice, RWC's clean, time to merge

**Pull request merged**
