### PR TITLE
Attempt to apply noUnusedLocals and noUnusedParameter flags to the compiler

### PR DESCRIPTION
**Pull request by yuit**
Trying to apply `noUnusedParameter` and `noUnusedLocals`, I can't always turn the noUnusedparameter on because ~~there are many cases when we create function with empty body and swap it in place of the other.~~

Will be easier to see per commit

### CODE REVIEW

**Comment by weswigham** [comment]
Shouldn't `function () { }` be assignable to `(pos: number) => void`?

**Comment by yuit** [comment]
@weswigham  you are right. I miss one that. I will update the PR. thanks!

**Comment by weswigham** [comment]
@yuit Is this only turning it on for the compiler layer, not services and tsserver?

**Comment by yuit** [comment]
@weswigham it is on for all including services and tsserver

**Comment by weswigham** [comment]
@yuit I don't see any changes to any of their `tsconfig.json`s.

**Comment by mhegazy** [comment]
@yuit can you elaborate on the issues you see with `noUnusedParameter `?

**Comment by mhegazy** [comment]
looks good otherwise. thanks.

**Comment by yuit** [comment]
@mhegazy I will update the comment but the issue is no longer true. I misunderstood empty function type.

**Comment by mhegazy** [comment]
👍

**Comment by mhegazy** [comment]
@yuit can you refresh this PR.

**Pull request closed without merging**
