### PR TITLE
Removes optional in scroll, scrollTo and scrollBy

### PR DESCRIPTION
**Pull request by tinganho**
x and y should not be optional:

[MDN — scrollBy](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy)
[MDN — scrollTo](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo)
[MDN — scroll](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll)

### CODE REVIEW

**Comment by tinganho** [comment]
This PR also fixes a lot of white space issues.

**Comment by mhegazy** [comment]
@tinganho this file is auto generated from src\lib\*.d.ts; this change is in the portion coming from src\lib\dom.generated.d.ts which itself is auto generated from the IE DOM definitions. we are looking in open sourcing this part as well. 

Please log issues for the changes for now, and @zhengbli can port the changes.

**Comment by tinganho** [comment]
Maybe good to check the other `x` and `y` parameters as well, since I don't think they are optional too.

**Comment by tinganho** [comment]
@mhegazy is there docs on what files are generated? Or why not put an extension on them like diagnostics?

**Comment by mhegazy** [comment]
@tinganho we are light on documentation on this part.

The library creation is driven by the jake file, see https://github.com/Microsoft/TypeScript/blob/master/Jakefile.js#L159-L171

The files come from src\lib\*.d.ts as sepcified in the jake file. most of the files are hand generated, there are two that are automatically gnerated by a script (dom.generated.d.ts and webworkers.generated.d.ts). 

we generate them from IE's DOM specification to make it easy to update and maintain. we are talking to the IE team about releasing these files, but since we do not own the files, we need their permission, and we have not gotten it yet. releasing the script without the specificaiton would not be helpful though. 

Sorry for the inconvenience, and hopefully we have update on this soon.

**Pull request closed without merging**
