### PR TITLE
Remove outdated deprecations

### PR DESCRIPTION
**Pull request by rbuckton**
This removes a number of outdated deprecations in the `deprecatedCompat` project. I've left some of the unused deprecation logic in that project as we are likely to need to use it for future deprecations.

### CODE REVIEW

**Comment by jakebailey** [comment]
My first impression is that the change looks god, but I am a little terrified about removing some of this like the global factories as they seem to unfortunately still be getting used? (https://sourcegraph.com/search?q=context:global+ts%5C.createIdentifier%5C%28+lang:typescript&patternType=regexp&sm=1&groupBy=repo)

**Comment by DanielRosenwasser** [comment]
Out of curioisity

@typescript-bot perf test this

**Comment by jakebailey** [comment]
My expectation is that tsc won't change but tsserver should get faster as it has to include these compat things (but, those benchmarks are still wonky until I merge my PR on ts-perf; been focusing on other things).

**Comment by rbuckton** [comment]
> My first impression is that the change looks good, but I am a little terrified about removing some of this like the global factories as they seem to unfortunately still be getting used? (https://sourcegraph.com/search?q=context:global+ts%5C.createIdentifier%5C%28+lang:typescript&patternType=regexp&sm=1&groupBy=repo)

The global factories have been deprecated since 4.0, I should think we've given plenty of time for users to migrate who aren't already using a pinned version of TypeScript.

**Comment by rbuckton** [comment]
While this might have a minor benefit to perf for tsserver operations, the real benefit is in the reduced startup time for tsserver/typescriptServices. None of the tsc perf tests are relevant, because nothing in `deprecatedCompat` is included in `tsc.js`.

**Review by sheetalkamat — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
Fair enough!

**Comment by sheetalkamat** [comment]
Should we do this for other APIs and server protocol commands too ?

**Comment by jakebailey** [comment]
It is 5.0... 😄

**Pull request merged**
