### PR TITLE
Put AMD dependency list inline with define call in UMD modules

### LINKED ISSUE #4952: UMD output does not work with require.js optimizer
When using the UMD module output, the require.js optimizer is not able to trace dependencies. My first impulse was to fix it there (see https://github.com/jrburke/r.js/pull/857), but their feedback was that it would probably be easier to change the output to something like this:

```javascript
(function (factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(['require', 'exports', 'lib'], factory);
    }
})(function (require, exports) {
    var lib = require('lib');
});
```

### PR DESCRIPTION
**Pull request by csnover**
Fixes #4952.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
@xi can you give this a try?

**Comment by vladima** [comment]
:+1:

**Comment by xi** [comment]
This indeed works with my project. Great!

**Comment by vladima** [comment]
thanks @csnover !

**Pull request merged**
