### PR TITLE
Fix duplicated import suggestions

### LINKED ISSUE #57368: Duplicate import path completions when multiple root directories are present
### 🔎 Search Terms

autocomplete, duplicate suggestions, duplicate imports, root dirs

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, but was made worse after https://github.com/microsoft/TypeScript/pull/55233 (v5.3-beta and later)

### 💻 Code

When rootDirs are `src/` and `build/dts`, and the directory structure is following:
```
app/
  src/
    index.ts
    dir/
      a.module.scss
  build/
    dts/
      index.d.ts
      dir/
        a.module.scss.d.ts
```

### 🙁 Actual behavior

Import completions when invoked from `index.ts` (using `import {} from "./`) have a duplicate entry for `dir`

Screenshot 2024-02-10 at 21 42 14

### 🙂 Expected behavior

Only a single entry for `dir` is present.

### Additional information about the issue

The bug occurs because when we're combining completions from the point of view of each root dir, we're not deduplicating the entries.

This issue has existed for a long time, but it was made more obvious after https://github.com/microsoft/TypeScript/pull/55233 fixed a related bug.

### PR DESCRIPTION
**Pull request by PhoebeSzmucer**
Fixes #57368

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by PhoebeSzmucer** [comment]
Thank you @andrewbranch! Is there any chance this can still make it to 5.4?

My workplace is about to upgrade TypeScript and we rely heavily on multiple root dirs, so many of our frontend developers will hit this papercut with duplicate completions (which only manifests on 5.3+).

No worries if not though :)

**Comment by andrewbranch** [comment]
There is a 100% chance this will make it into 5.4 😄

**Comment by PhoebeSzmucer** [comment]
I like those odds

**Pull request merged**
