### PR TITLE
Make {create/update}TypeAliasDeclaration API consistent (closes #15918)

### LINKED ISSUE #15918: Should createTypeAliasDeclaration have decorators/modifiers arguments?
**TypeScript Version:**  nightly (2.4.0-dev.20170517)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...

// Unable to add `export` this Type Alias
var typeDef = ts.createTypeAliasDeclaration(
  'myType',
  ts.createKeywordTypeNode(ts.SyntaxKind.StringKeyword)
);
```

**Expected behavior:**
Should be able to add an export modifier to the node.

**Actual behavior:**
This API doesn't seem to have the same signature as `createInterfaceDeclaration` or `createEnumDeclaration`, etc.  Should it have `decorators` and `modifiers` parameters like the other APIs?

I'm willing to send a PR if so.

### PR DESCRIPTION
**Pull request by phated**
Fixes #15918

### CODE REVIEW

**Comment by sandersn** [comment]
@phated can you fix the build break before I merge this? Callers of `updateTypeAliasDeclaration` need to be updated.

**Comment by phated** [comment]
No problem.  I didn't realize it was being used internally already.

**Comment by phated** [comment]
Alright, based on the travis run, I think I've updated this properly.

**Comment by sandersn** [comment]
Thanks @phated!

**Pull request merged**
