### PR TITLE
Always error on overshifts

### PR DESCRIPTION
**Pull request by weswigham**
To see if making it always an error instead of a suggestion is viable.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot user test this
@typescript-bot test top600

**Comment by weswigham** [comment]
Hm, unsure if those are legitimate errors in webpack or funky
AssemblyScript-isms that hint how to handle the numbers to the
runtime/compiler.

**Comment by RyanCavanaugh** [comment]
Seems idiomatic in asm? It's declared
```js
let result: u64;
```
so presumably you can 32-shift it

**Comment by weswigham** [comment]
Well, not breaking AssemblyScript `u64` idioms is probably as good a reason as any to leave it as a suggestion only outside enums.

**Pull request closed without merging**
