### PR TITLE
Delete generated file, add to gitignore

### PR DESCRIPTION
**Pull request by weswigham**
Implements #4909

Our build was already setup to handle building the process messages script and processing the messages before building the compiler. `jake` with none of the generated files present will create them all correctly.

Removing the generated code form the repo should reduce merge conflicts in PRs and hopefully now provide a build failure warning when IDs clash in the json file.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
I think the original reason that we did this was because of some intermingling between sys and diagnostics. I think this should be fine now.

**Comment by DanielRosenwasser** [comment]
This serves a very sub-par editing experience if I haven't performed a `jake generate-diagnostics`. Do either of you have objections to me reverting that portion of the change?

**Comment by weswigham** [comment]
Yes. We mentioned that in #4909. It's pretty much the only downside, but reduces merge issues.

**Comment by weswigham** [comment]
I recommend a [post-checkout hook](http://git-scm.com/docs/githooks) to build the file, if you like having a reliable editing experience.

**Pull request merged**
