### PR TITLE
fix(40640) add missing notApplicableReason in protocol

### LINKED ISSUE #40640: notApplicableReason not included in protocol.d.ts
Looks like `RefactorActionInfo.notApplicableReason` never made it into `protocol.d.ts`. This property does seem to be sent along by the TS Server, it is just the typings for the property that is missing

Confirmed with TS 4.0.3

### PR DESCRIPTION
**Pull request by jessetrinity**
Fixes #40640

protocol changes were missed in #37871

We will need to cherry pick this to `release-4.0`

### CODE REVIEW

**Comment by jessetrinity** [comment]
Is there a protocol baseline that needs to be updated?

**Review by sheetalkamat — APPROVED** [review]

**Comment by jessetrinity** [comment]
@typescript-bot cherry-pick this to release-4.0

**Comment by DanielRosenwasser** [comment]
For annoying reasons, the bot doesn't cherry-pick merged PRs

**Comment by jessetrinity** [comment]
but... I've seen it do it...

**Comment by DanielRosenwasser** [comment]
Same! I have no idea how anything works. Maybe @weswigham knows.

**Comment by weswigham** [comment]
Github GC's the ref if you take too long (and deleted the source branch), and once the ref is gone, it can't be picked anymore.

**Comment by DanielRosenwasser** [comment]
So I guess try not to delete the source branch immediately in the future and give that a shot - thanks @weswigham!

**Comment by jessetrinity** [comment]
image
I don't believe I have 🤔

**Comment by DanielRosenwasser** [comment]
Maybe it's a difficulty across repos too.

**Comment by weswigham** [comment]
That's usually fine... it looks like the pipeline never even triggered, so it seems like the comment didn't even get picked up. Lemme try...

@typescript-bot cherrypick this into release-4.0

**Comment by weswigham** [comment]
🤷 github dropped the webhook, maybe? I dunno. Definitely triggered for me, and the accompanying logs seem fine, too (though maybe I should update the code for the latest octokit - there's some deprecation warnings).

**Pull request merged**
