### PR TITLE
Array.prototype.filter.not.forcing.boolean

### PR DESCRIPTION
**Pull request by NimaZahedi**
Fixes #
Changed the return value of Array.prototype.filter, use any instead of boolean!
based on this issue: #5850

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Missing baseline file... run these commands:
* `jake runtests`
* `jake baseline-accept`
* `git add -A .`
* `git commit -m "Add baselines"`
* `git push`

**Comment by NimaZahedi** [comment]
@RyanCavanaugh Ok, but isn't the same as https://github.com/Microsoft/TypeScript/pull/7776? :confused:

**Comment by DanielRosenwasser** [comment]
@NimaZahedi Ryan means that we shouldn't even have generated an error baseline given your change.

@yuit does the test harness use the LKG's libs?

**Comment by RyanCavanaugh** [comment]
Ping @yuit - which files are the correct ones to edit?

**Comment by NimaZahedi** [comment]
@RyanCavanaugh @DanielRosenwasser 
I've tried these two set of commands:
* First
 * Make my changes (writing test and fix issue)
 * jake (updating built/local/ files d.ts)
 * jake runtests
 * jake baseline-accept 
 * jake runtests

* Second
 * Writing test
 * jake runtests
 * jake baseline-accept 
 * Fix issue
 * jake (updating built/local/ files d.ts)
 * jake runtests

**Comment by yuit** [comment]
@DanielRosenwasser the harness will pick up lib files built to `built\local`. @NimaZahedithe issue here is that there are multiple interface of Array (`ReadonlyArray`, `Array`, `Int8Array` etc.), and you will want to update them all.

**Comment by NimaZahedi** [comment]
@yuit I'll do, sure. thanks :)

**Comment by NimaZahedi** [comment]
@yuit Should I write test case for every single of those types? (I mean the interfaces whose filter method was changed)

**Comment by RyanCavanaugh** [comment]
:+1:

No need to write a test for every overload

**Comment by mhegazy** [comment]
:+1:

**Comment by yuit** [comment]
@NimaZahedi look goods :) Thanks!

**Pull request merged**
