### PR TITLE
feat(lib): define TypedArray interface

### LINKED ISSUE #15402: Suggestion: a built-in TypedArray interface
I would have expected a [`TypedArray`][ecma-typed-array] interface to exist in
the built-in declaration libraries. Instead, there are independent types for
[`Int8Array`][lib-int8-array], etc, with no common base type.

```ts
interface Int8Array { /* ... */ }
interface Int8ArrayConstructor { /* ... */ }
declare const Int8Array: Int8ArrayConstructor;

interface Uint8Array { /* ... */ }
interface Uint8ArrayConstructor { /* ... */ }
declare const Uint8Array: Uint8ArrayConstructor;

// ...
```

It seems sensible that there should be a common `TypedArray` type, both because

  - a TypeScript user might want to declare a variable as a `TypedArray`, and
  - it would reduce repetition in the built-in declaration files

```ts
interface TypedArray { /* ... */ }

interface Int8Array extends TypedArray { }
interface Int8ArrayConstructor { /* ... */ }
declare const Int8Array: Int8ArrayConstructor;

interface Uint8Array extends TypedArray { }
interface Uint8ArrayConstructor { /* ... */ }
declare const Uint8Array: Uint8ArrayConstructor;

// ...
```

Is there a good reason why there is no `TypedArray` type? If not, I can submit a PR.

## Use case

Consider the [`isTypedArray()`][lodash-is-typed-array] function from lodash.
Currently, it is declared as follows:

```ts
function isTypedArray(value: any): boolean;
```

This proposal would enable an appropriate type-guard, without declaring
a convoluted union type:

```ts
function isTypedArray(value: any): value is TypedArray;
```

[ecma-typed-array]: http://www.ecma-international.org/ecma-262/6.0/#sec-typedarray-objects
[lib-int8-array]: https://github.com/Microsoft/TypeScript/blob/6756e3e44c3b21d021a7542b63f2de84b65695c4/src/lib/es5.d.ts#L1550
[lodash-is-typed-array]: https://lodash.com/docs/4.17.4#isTypedArray

### LINKED ISSUE #45198: Big(Int|Uint)64ArrayConstructor: missing from Iterable
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `the default`.

## Missing / Incorrect Definition

`BigInt64Array.from` is missing an iterable overload (same for BigUint64Array).

## Sample Code

```ts
console.log(
  Int32Array.from(new Set([1, 2, 3]), (value) => Number(value) ** 2).join(", ")
);
console.log(
  BigInt64Array.from(new Set([1n, 2n, 3n]), (value) => value ** 2n).join(", ")
);
```

```stderr
Argument of type 'Set<bigint>' is not assignable to parameter of type 'ArrayLike<unknown>'.
  Property 'length' is missing in type 'Set<bigint>' but required in type 'ArrayLike<unknown>'.
```

## Documentation Link

[TypedArray.from() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from)

### PR DESCRIPTION
**Pull request by mfulton26**
Each concrete typed array type and constructor share common interfaces.

Library types can be defined extending base interfaces:

1. higher code reuse
2. less duplication
3. easier maintenance (less error prone)

Closes #15402
Fixes #45198

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot test it

**Comment by mfulton26** [comment]
> This PR does partly the same I think, #58188 - but is less breaking?

This PR does address #45198, I'm not sure if it addresses #45199 though. Oh, on second look though, this might address it too. I can try grabbing the test changes from https://github.com/microsoft/TypeScript/pull/58188/files#diff-259a5a5be5d9d2b11bd636646375791a0d37a60f80c1871b6b97c9f1cde672ee to confirm.

**Comment by mfulton26** [comment]
> This PR does partly the same I think, #58188 - but is less breaking?

The main objective of this PR is more to create a common interface for all `TypedArray` prototypes and constructors for use in code that acts on any `TypedArray` instance (and to reduce duplication in the lib d.ts files.

**Comment by mfulton26** [comment]
@typescript-bot test it

**Comment by mfulton26** [comment]
> @typescript-bot test it

@DanielRosenwasser, I've pushed a potential fix for `Buffer extends Uint8Array`. Can we re-test?

**Comment by sandersn** [comment]
@typescript-bot test it

**Comment by sandersn** [comment]
I'm also interested to see what performance looks like with a second sample.

**Comment by jakebailey** [comment]
There are merge conflicts, so the bot can't run anything.

**Comment by jakebailey** [comment]
That and there's an Azure DevOps outage....

**Comment by mfulton26** [comment]
> There are merge conflicts, so the bot can't run anything.

merge conflicts resolved; this branch is now up to date with `main`

> @typescript-bot test it

can we try again @sandersn?

**Comment by jakebailey** [comment]
@typescript-bot test it

**Comment by mfulton26** [comment]
What do you think of these changes @sandersn? This branch is currently up to date with `main`. I've noticed various changes to iterators, iterables, and typed arrays (e.g. bug fixes) that would have been easier/avoided with root `TypedArray` and `TypedArrayConstructor` types.

**Comment by DanielRosenwasser** [comment]
@rbuckton How much of this intersects with the work at #58573?

**Comment by rbuckton** [comment]
> @rbuckton How much of this intersects with the work at #58573?

They are essentially the same, except for the generic `Buffer` type argument.

**Comment by mfulton26** [comment]
Should this PR be closed in favor of #59407? My main goal is to get a common `TypedArray` and `TypedArrayConstructor` to reference, extend, etc. Both PRs do this but #59407 does more.

**Comment by rbuckton** [comment]
> Should this PR be closed in favor of #59407? My main goal is to get a common `TypedArray` and `TypedArrayConstructor` to reference, extend, etc. Both PRs do this but #59407 does more.

Possibly, but I'm not certain #59407 is the best solution either. While I'd like to introduce `TypedArray`/`TypedArrayConstructor`, `TypedArrayConstructor` needs a higher-kinded types mechanism to be defined cleanly. It's more likely that we'll end up taking #59417 in the near term (5.7 or later) and will need to postpone `TypedArray`/`TypedArrayConstructor` for now.

**Pull request closed without merging**
