### PR TITLE
Type the result property on IDBRequest

### LINKED ISSUE #25547: IDBRequest result attribute typed as any
**TypeScript Version:**  master

**Search Terms:** IDBRequest

**Code**

```ts
new Promise((resolve, reject) => {
  const req = indexedDB.open(name, 1)
  req.onerror = () => reject(req.error)
  req.onsuccess = () => resolve(req.result)

  req.onupgradeneeded = () => {
    req.result.createObjectStore('keyval', { notValidKey: false })
  }
})
```

**Expected behavior:** `notValidKey` should not be accepted in the second argument to `createObjectStore`

**Actual behavior:** Since `req.result` is typed as `any`, anything goes

**Playground Link:** [link](https://www.typescriptlang.org/play/#src=new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0D%0A%20%20const%20req%20%3D%20indexedDB.open(name%2C%201)%0D%0A%20%20req.onerror%20%3D%20()%20%3D%3E%20reject(req.error)%0D%0A%20%20req.onsuccess%20%3D%20()%20%3D%3E%20resolve(req.result)%0D%0A%0D%0A%20%20req.onupgradeneeded%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20req.result.createObjectStore('keyval'%2C%20%7B%20notValidKey%3A%20false%20%7D)%0D%0A%20%20%7D%0D%0A%7D))

**Related Issues:** none

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #25547

### CODE REVIEW

**Comment by j-oliveras** [comment]
You should edit this into [TSJS-lib-generator](https://github.com/Microsoft/TSJS-lib-generator) repository.

Please read: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by LinusU** [comment]
Hmm, I thought that was for `src/lib/dom.generated.d.ts` and `src/lib/webworker.generated.d.ts`? But this is touching `lib/dom.d.ts` and `lib/lib.webworker.d.ts` 🤔 

I'm probably missing something though 😄

**Comment by j-oliveras** [comment]
`lib/dom.d.ts` and `lib/lib.webworker.d.ts` are generated from `src/lib/dom.generated.d.ts` and `src/lib/webworker.generated.d.ts` (and other files). And these are generated from TSJS-lib-generator.

**Comment by LinusU** [comment]
Got it 👍 

Closed in favour of https://github.com/Microsoft/TSJS-lib-generator/pull/530

**Pull request closed without merging**
