### PR TITLE
Refactor findAllReferences. Now supports renamed exports and imports.

### LINKED ISSUE #10894: Renaming import alias with the same name renames the origin
**Code**

``` ts
// File: test1.ts
export class Test {
}

// File: test2.ts
import { Test as Test } from './test1'

const test = new Test()
```

If you rename left or right side of `Test as Test` - both sides are renamed at the same time - it should only rename source or alias separately

### LINKED ISSUE #13663: Don't allow rename of '.default' property of import
**TypeScript Version:**  nightly (2.2.0-dev.20170124)

**Code**

```ts
/// <reference path='fourslash.ts' />

// @Filename: a.ts
////export default function f() {}

// @Filename: b.ts
////import * as a from "./a";
////a./**/default;

goTo.marker();
verify.renameInfoFailed("!!!");
```

**Expected behavior:**

Rename fails.

**Actual behavior:**

Rename succeeds.

### LINKED ISSUE #14103: TSServer References Exception for Exported Default Class
TS Version: 2.2.1-insiders.20170209

```ts
export default class Xyz { 
     
}
```

Execute `references` at position `22` in the file

**Expected**
```
[Trace - 4:52:08 PM] Sending request: references (14). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bar.ts",
    "line": 1,
    "offset": 22
}
[Trace - 4:52:08 PM] Response received: references (14). Request took 81 ms. Success: true 
Result: {
    "refs": [
        {
            "file": "/Users/matb/projects/sand/bar.ts",
            "start": {
                "line": 1,
                "offset": 22
            },
            "lineText": "export default class Xyz { ",
            "end": {
                "line": 1,
                "offset": 25
            },
            "isWriteAccess": true,
            "isDefinition": true
        }
    ],
    "symbolName": "Xyz",
    "symbolStartOffset": 22,
    "symbolDisplayString": "class Xyz"
}
```

**Actual**
```
[Trace - 4:52:33 PM] Sending request: references (31). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/sand/bar.ts",
    "line": 1,
    "offset": 22
}
[Trace - 4:52:33 PM] Response received: references (31). Request took 20 ms. Success: false . Message: Error processing request. Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.getSymbolAtLocation (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:35547:21)
    at getDefaultImportName (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:57428:80)
    at getReferencedSymbolsForNode (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:57370:51)
    at Object.findReferencedSymbols (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:57324:20)
    at findReferencedSymbols (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:65846:41)
    at Object.getReferencesAtPosition (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:65837:37)
    at /Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:70784:71
    at /Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:68882:105
    at Array.reduce (native)
    at Object.combineProjectOutput (/Users/matb/projects/vscode/extensions/typescript/node_modules/typescript/lib/tsserver.js:68882:35)
```

### PR DESCRIPTION
**Pull request by andy-ms**
Don't think there was an issue for this but was mentioned here: https://github.com/Microsoft/TypeScript/pull/13643#issuecomment-274975010.
Fixes #13663.
**Update**: Now also fixes #10894.
**Update**: Fixes #14103.
We now use an algorithm to search for imports of a given export. This is in the new `importTracker.ts`. Previously we would just globally search for identifiers with the same name.

Note: This breaks find-all-refs for untyped modules since we want to match the symbol and not just the name. See #14002.

### CODE REVIEW

**Comment by mhegazy** [comment]
Some comments:

- getReferencesForStringLiteral, why does it use type
- getReferencesInContainer, consider passing in the containig sourceFile
- searchForImportsOfExport, consider changing the switch in the IIFE to just set a variable
- sourceFileHasName, consider inlining this at use site
- getSymbolScope, consider making the comment more detailed for `export as namespace`
- getDirectImportsMap, I would change the map to use a Map object instead
- export assignment handling, `export = foo`, `export default foo`
- consider renaming `isProperImportEquals` to `isExternalModuleImportEqual`
- forEachImport, consider storing the `require` calls on the sourceFile like we do with the imports
 this makes `forEachPossibleImportOrExportStatement` jsut a walk over ambient modules

- getImportOrExportSymbol, consider changing the return expression to `return comingFromExport ? getExport() : getExport() || getImport();`
- getExport, make sure to check comingFromExport before return an import
- isNodeImport, in case for ImportEqualsDeclaration, check for is it an `import .. = require` or just an `import .. = X`
- nodeIsEligibleForRename, check the parent of the node to make sure it is an import or export specifier, and worth adding a test of `x.default` vs a case of `import * as ns from "mod"; ns.default;`

**Comment by mhegazy** [comment]
@andy-ms can you also validate that this change addresses https://github.com/Microsoft/TypeScript/issues/14346 and

**Comment by andy-ms** [comment]
@mhegazy Should all be done except for #14880, which I assigned to myself.

**Comment by mhegazy** [comment]
@andy-ms i still do not see #14346 with this change..

**Comment by andy-ms** [comment]
Should be in https://github.com/Microsoft/TypeScript/pull/14001/commits/28a3604714f110eb6680f785b9a4759171a53aa2

**Pull request merged**
