### PR TITLE
Fix js initializer merging

### LINKED ISSUE #24015: Symbol table corruption leads to runaway memory usage
**TypeScript Version:**  2.8

**Search Terms:** symbol corrupt

**Code**

**Note**: This only repros in VS (verified in an external project but have not verified in an inferred project yet). I have not yet determined why this is the case.

You will need three files

file1.js
```ts
blah.prototype = {
    m: "q"
};
```
file2.d.ts
```ts
declare class blah { }
```
file3.js
```
/* do editing here */
```

Make about 70 edits in file3.js without changing file1.js or file2.d.ts

**Expected behavior:** Stable memory usage

**Actual behavior:** Eventually, memory usage climbs exponentially

Root cause here is that in this code:
```ts
                if ((source.flags | target.flags) & SymbolFlags.JSContainer) {
                    const sourceInitializer = getJSInitializerSymbol(source);
                    const targetInitializer = getJSInitializerSymbol(target);
```
`sourceInitializer` and `targetInitializer` are the same object and we end up copying the same declarations array into itself, pushing more objects into the (supposedly immutable!) 
symbol tables from the SourceFiles and doubling the array length the next time around.

You can verify this hypothesis by stopping before the process OOMs, editing file2.d.ts and file1.js - node will quickly GC back down to the baseline memory consumption because we create a fresh symbol table when the file is edited.

I also can't get this to repro via commandline means, so possibly something else fishy is going on.

@sandersn - I applied the bail-out patch we discussed earlier but the problem is that we still grow the array *linearly* during the top level of each global merging pass (since we're still doing *some* writing to the original symbol table). This isn't *as* bad but is still going to cause problems in longer editing sessions.

**Playground Link:** n/a

### PR DESCRIPTION
**Pull request by sandersn**
Fixes exponential merging behaviour of special js initialisers. Some baselines change because it fixes some previously incorrect merged symbol structure. 

I have *not* tested it with Visual Studio, but it's basically the same as the fix we had working this afternoon, except that it doesn't break any of our existing tests.

Fixes #24015

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Porting to 2.8

**Comment by sandersn** [comment]
I added a test case and an assert that immediately catches the problem (1) in compilation (2) in fourslash (3) in interactive VS Code usage, so I think this is ready to go.

**Comment by RyanCavanaugh** [comment]
Looks good. Can you add another fourslash test for the other repro we got?

**Comment by sandersn** [comment]
@RyanCavanaugh can you send me the other minified repro? Since we didn't change the definition of getJSInitializerSymbol, and the binder code that creates symbols based on getJSInitializer is a single code path, I don't think it will prove anything new, but the cost of adding a second test is low.

Note that without the fix the assert fires for existing tests too: to wit, the ones that had changed baselines.

**Comment by RyanCavanaugh** [comment]
The two repros I have are
```
// file1.js
blah.prototype = {
    m: "q"
};

// file2.d.ts
declare class blah { }
```
and
```
// file1.js
var N = {};
N.X = function() { };

// file2.d.ts
declare namespace N {
    class X { }
}
```

**Pull request merged**
