### PR TITLE
Fix blocking of recursive dependencies in getNarrowedTypeOfSymbol

### LINKED ISSUE #48902: Perf regression in object destructuring with default values referencing other destructured members
VS Code Version: 
- Version: 1.66.2 (user setup)
- Version: 1.67.0-insider (user setup)

OS: 
- Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Open this code

```javascript
class GLTexture {
  constructor({
    gl,
    width,
    height,
    target = gl.TEXTURE_2D,
    internalFormat = gl.RGBA8 || gl.RGBA,
    format = gl.RGBA,
    type = gl.UNSIGNED_BYTE,
    autoGenerateMipmap = false,
    minFilter = autoGenerateMipmap ? gl.LINEAR_MIPMAP_LINEAR : gl.LINEAR,
    magFilter = gl.LINEAR,
    wrapS = gl.REPEAT,
    wrapT = gl.REPEAT,
  }) {
  }
}
```

2. See that after switching tabs or hovering on a property that IntelliSense isn't working and `Loading IntelliSense Status` in status bar starts spinning forever

Code_cb8oof7A1o
Code_k3e8RGnq39

I tried to isolate the issue that seems to be related to operators in constructor, but not always. Sometimes, it appears by commenting/uncommenting other lines.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #48902.

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Thanks!

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-4.6

**Comment by DanielRosenwasser** [comment]
Really? You couldn't cherry-pick a one-line change? 🙄

**Comment by DanielRosenwasser** [comment]
I'll cherry-pick the squash commit manually.

**Comment by ahejlsberg** [comment]
Tests and perf all look fine.

**Pull request merged**
