### PR TITLE
Lookup non-local element factory for reference marking when marking fragment references

### LINKED ISSUE #60459: jsxFactory import showing as unused when TSX is configured via tsconfig and only contains fragments
### 🔎 Search Terms

TSX unused fragment jsxFactory

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "jsx"

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?noUnusedLocals=true&jsxFactory=element&jsxFragmentFactory=fragment#code/PTAEAECsGcA8C5QCcCmBDAxgFwFAgjLAGKZYD2SAnoigDYoC2KAdrvlHEUmgOZOslsFaqABm3PizZhwzMgFVmAV2goAJgBkyGNLWg48M0QEt6zNE0THmalLAB0WODmMMADhSygA3nUZSAGjEJfiwAX2CyBlAAcntgQhiAbgMMMmZoMnp7WjIeAAoAHgA+Ll5QwuBigEoUwwgTMwsUREJHfTsPJC9RJWZsY3TQP1D86p8wg07PMT6BofFyqTGJ0CA

### 💻 Code

```ts repro
// @jsx: react
// @jsxFactory: element
// @jsxFragmentFactory: fragment
// @noUnusedLocals

// @filename: index.tsx
import {element, fragment} from './jsx';

console.log(&lt;>Fragment&lt;/>);

// @filename: jsx.ts
export function element() {}

export function fragment() {} 
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?noUnusedLocals=true&jsxFactory=element&jsxFragmentFactory=fragment#code/PTAEAECsGcA8C5QCcCmBDAxgFwFAgjLAGKZYD2SAnoigDYoC2KAdrvlHEUmgOZOslsFaqABm3PizZhwzMgFVmAV2goAJgBkyGNLWg48M0QEt6zNE0THmalLAB0WODmMMADhSygA3nUZSAGjEJfiwAX2CyBlAAcntgQhiAbgMMMmZoMnp7WjIeAAoAHgA+Ll5QwuBigEoUwwgTMwsUREJHfTsPJC9RJWZsY3TQP1D86p8wg07PMT6BofFyqTGJ0CA)

### 🙁 Actual behavior

```
'element' is declared but its value is never read.
```

### 🙂 Expected behavior

`element` is used in the generated output so should not be found as unused.

Generated output:
```
console.log(element(fragment, null, "Fragment"));
```

### Additional information about the issue

Using pragmas instead of tsconfig works as expected so hopefully it's not a big gap to align these
```ts repro
// @jsx: react
// @noUnusedLocals

// @filename: index.tsx
/**
 * @jsx element
 * @jsxFrag fragment
 */
import {element, fragment} from './jsx';

console.log(&lt;>Fragment&lt;/>);

// @filename: jsx.ts
export function element() {}

export function fragment() {} 
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?noUnusedLocals=true&jsxFactory=element&jsxFragmentFactory=fragment#code/PTAEAECsGcA8C5QCcCmBDAxgFwFAggHYD2AqgQK7QoAmAMkRmgDbQ55jgBmAlkygWgC2KRNwLUUsAHRY4eAFTycoeRBixQKPsIK4VauADEkaAOahOJ0zr3zgOboIAORJFlABvLShsAaC1Y2AL4BRIKgAORSwOoRANxsGEQE0ER8UkxEpgAUADwAfMZmNrnA+QCUCewQPHwCwojqMqySLm4W5ATY3Mma2vxY2eWeQWytru6cnd29lsUDQyOgQA)

### PR DESCRIPTION
**Pull request by weswigham**
In addition to the local name.

Fixes #60459

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test it

**Comment by jakebailey** [comment]
@typescript-bot test top400
@typescript-bot user test this

Rerunning this because I'm in the middle of fixing these pipelines

**Comment by jakebailey** [comment]
@typescript-bot test top400
@typescript-bot user test this

Rerunning this because I forgot to actually merge my fix before the last rerun 😅

**Review by iisaduan — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot test top400
@typescript-bot user test this

**Pull request merged**
