### PR TITLE
Flatten immediately nested conditional types in the false position

### LINKED ISSUE #28663: Long conditional type resolves to any
**TypeScript Version:**  3.3.0-dev.20181122

**Search Terms:** conditional type resolves any

**Code**

After adding exactly this many conditions, the type of `WrappedJsxNodeType` will be `any`.

```ts
import * as ts from "typescript";

type WrappedNodeType = CompilerNodeToWrappedType<ts.JsxExpression>;

type CompilerNodeToWrappedType<T extends ts.Node> = T extends ts.ArrayBindingPattern ? ArrayBindingPattern :
    T extends ts.BindingElement ? BindingElement :
    T extends ts.ObjectBindingPattern ? ObjectBindingPattern :
    T extends ts.ClassDeclaration ? ClassDeclaration :
    T extends ts.ClassExpression ? ClassExpression :
    T extends ts.ConstructorDeclaration ? ConstructorDeclaration :
    T extends ts.GetAccessorDeclaration ? GetAccessorDeclaration :
    T extends ts.MethodDeclaration ? MethodDeclaration :
    T extends ts.PropertyDeclaration ? PropertyDeclaration :
    T extends ts.SetAccessorDeclaration ? SetAccessorDeclaration :
    T extends ts.ComputedPropertyName ? ComputedPropertyName :
    T extends ts.Identifier ? Identifier :
    T extends ts.QualifiedName ? QualifiedName :
    T extends ts.SyntaxList ? SyntaxList :
    T extends ts.Decorator ? Decorator :
    T extends ts.JSDoc ? JSDoc :
    T extends ts.JSDocAugmentsTag ? JSDocAugmentsTag :
    T extends ts.JSDocClassTag ? JSDocClassTag :
    T extends ts.JSDocParameterTag ? JSDocParameterTag :
    T extends ts.JSDocPropertyTag ? JSDocPropertyTag :
    T extends ts.JSDocReturnTag ? JSDocReturnTag :
    T extends ts.JSDocTypedefTag ? JSDocTypedefTag :
    T extends ts.JSDocTypeTag ? JSDocTypeTag :
    T extends ts.JSDocUnknownTag ? JSDocUnknownTag :
    T extends ts.EnumDeclaration ? EnumDeclaration :
    T extends ts.EnumMember ? EnumMember :
    T extends ts.AsExpression ? AsExpression :
    T extends ts.AwaitExpression ? AwaitExpression :
    T extends ts.CallExpression ? CallExpression :
    T extends ts.CommaListExpression ? CommaListExpression :
    T extends ts.ConditionalExpression ? ConditionalExpression :
    T extends ts.DeleteExpression ? DeleteExpression :
    T extends ts.ImportExpression ? ImportExpression :
    T extends ts.MetaProperty ? MetaProperty :
    T extends ts.NewExpression ? NewExpression :
    T extends ts.NonNullExpression ? NonNullExpression :
    T extends ts.OmittedExpression ? OmittedExpression :
    T extends ts.ParenthesizedExpression ? ParenthesizedExpression :
    T extends ts.PartiallyEmittedExpression ? PartiallyEmittedExpression :
    T extends ts.PostfixUnaryExpression ? PostfixUnaryExpression :
    T extends ts.PrefixUnaryExpression ? PrefixUnaryExpression :
    T extends ts.SpreadElement ? SpreadElement :
    T extends ts.SuperElementAccessExpression ? SuperElementAccessExpression :
    T extends ts.SuperExpression ? SuperExpression :
    T extends ts.SuperPropertyAccessExpression ? SuperPropertyAccessExpression :
    T extends ts.ThisExpression ? ThisExpression :
    T extends ts.TypeAssertion ? TypeAssertion :
    T extends ts.TypeOfExpression ? TypeOfExpression :
    T extends ts.VoidExpression ? VoidExpression :
    T extends ts.JsxExpression ? JsxExpression : Node<T>;

class Node<NodeType extends ts.Node = ts.Node> {
    compilerNode!: NodeType;
}

class JsxExpression extends Node<ts.JsxExpression> {}
class ArrayBindingPattern extends Node<ts.ArrayBindingPattern> {}
class BindingElement extends Node<ts.BindingElement> {}
class ObjectBindingPattern extends Node<ts.ObjectBindingPattern> {}
class ClassDeclaration extends Node<ts.ClassDeclaration> {}
class ClassExpression extends Node<ts.ClassExpression> {}
class ConstructorDeclaration extends Node<ts.ConstructorDeclaration> {}
class GetAccessorDeclaration extends Node<ts.GetAccessorDeclaration> {}
class MethodDeclaration extends Node<ts.MethodDeclaration> {}
class PropertyDeclaration extends Node<ts.PropertyDeclaration> {}
class SetAccessorDeclaration extends Node<ts.SetAccessorDeclaration> {}
class ComputedPropertyName extends Node<ts.ComputedPropertyName> {}
class Identifier extends Node<ts.Identifier> {}
class QualifiedName extends Node<ts.QualifiedName> {}
class SyntaxList extends Node<ts.SyntaxList> {}
class Decorator extends Node<ts.Decorator> {}
class JSDoc extends Node<ts.JSDoc> {}
class JSDocAugmentsTag extends Node<ts.JSDocAugmentsTag> {}
class JSDocClassTag extends Node<ts.JSDocClassTag> {}
class JSDocParameterTag extends Node<ts.JSDocParameterTag> {}
class JSDocPropertyTag extends Node<ts.JSDocPropertyTag> {}
class JSDocReturnTag extends Node<ts.JSDocReturnTag> {}
class JSDocTypedefTag extends Node<ts.JSDocTypedefTag> {}
class JSDocTypeTag extends Node<ts.JSDocTypeTag> {}
class JSDocUnknownTag extends Node<ts.JSDocUnknownTag> {}
class EnumDeclaration extends Node<ts.EnumDeclaration> {}
class EnumMember extends Node<ts.EnumMember> {}
class AsExpression extends Node<ts.AsExpression> {}
class AwaitExpression extends Node<ts.AwaitExpression> {}
class CallExpression extends Node<ts.CallExpression> {}
class CommaListExpression extends Node<ts.CommaListExpression> {}
class ConditionalExpression extends Node<ts.ConditionalExpression> {}
class DeleteExpression extends Node<ts.DeleteExpression> {}
class ImportExpression extends Node<ts.ImportExpression> {}
class MetaProperty extends Node<ts.MetaProperty> {}
class NewExpression extends Node<ts.NewExpression> {}
class NonNullExpression extends Node<ts.NonNullExpression> {}
class OmittedExpression extends Node<ts.OmittedExpression> {}
class ParenthesizedExpression extends Node<ts.ParenthesizedExpression> {}
class PartiallyEmittedExpression extends Node<ts.PartiallyEmittedExpression> {}
class PostfixUnaryExpression extends Node<ts.PostfixUnaryExpression> {}
class PrefixUnaryExpression extends Node<ts.PrefixUnaryExpression> {}
class SpreadElement extends Node<ts.SpreadElement> {}
class SuperElementAccessExpression extends Node<ts.SuperElementAccessExpression> {}
class SuperExpression extends Node<ts.SuperExpression> {}
class SuperPropertyAccessExpression extends Node<ts.SuperPropertyAccessExpression> {}
class ThisExpression extends Node<ts.ThisExpression> {}
class TypeAssertion extends Node<ts.TypeAssertion> {}
class TypeOfExpression extends Node<ts.TypeOfExpression> {}
class VoidExpression extends Node<ts.VoidExpression> {}
```

If you remove the first condition in the type alias (`T extends ts.ArrayBindingPattern ? ArrayBindingPattern :`) you will see it correctly resolve to `JsxExpression`.

**Expected behavior:** Resolves to `JsxExpression`

**Actual behavior:** Resolves to `any`.

I was code generating all this with ts-simple-ast until it failed ([see here](https://gist.github.com/dsherret/499c61da33570f9ba8efda924e49ec64)), so I tried randomly shuffling the array of type names I was generating it with to see if what was in the conditions mattered, but it always seemed to fail after 51 classes. (Edit: Updated example to step through the array of nodes and they all fail at 51 classes. Actually, in some cases when shuffling it would differ, but that was just because it happened to match a base type.)

My declaration files keep being generated with `any` types and occasionally objects I use internally are typed as `any` because of this issue. Perhaps there's a better way I can do this mapping? Thanks!

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we flatten immediately nested conditional types in the false position, effectively treating types of the form

```ts
type Foo<...> =
    A extends B ? X :
    C extends D ? Y :
    E extends F ? Z :
    ...;
```

as a single construct for purposes of resolution. This should meaningfully improve the cost of resolving such types, plus it means they aren't subject to the instatiation depth limiter (they basically count as a single level).

Fixes #28663.

### CODE REVIEW

**Comment by ajafff** [comment]
> I'm pretty sure we have bug for this somewhere

#28663

**Comment by weswigham** [comment]
I've thrown up #36584 as a much simpler alternative - there's no hard syntactic requirements (so it will take effect much more often than this change), it doesn't contort conditional instantiation with an inner loop, and allows the same usecases. In the cases where we would flatten here, we already don't create anything intermediate that isn't used to determine simplifyability (at least once distributivity is handled/bailed appropriately); so beyond acting as a trampoline to reduce stack depth in certain scenarios, I don't think the extra structure here serves much purpose, other than to greatly complicate the code. Ergo, I think the onus is really on this change to demonstrate a case where the extra structure _actually_ saves us from a pathological performance cliff.

**Comment by ahejlsberg** [comment]
@weswigham Beyond fixing the depth limiter issue on large conditional types, the PR makes resolution faster by virtue of its shortened code path and reduces memory consumption by not storing resolved types in the caches associated with the each nested type's `ConditionalRoot`. The effects are not dramatic, but every little bit counts. I disagree that the loop greatly complicates the code. I think it is perfectly meaningful to think of a series of immediately nested conditionals as a single construct, and the loop reflects that.

**Comment by weswigham** [comment]
I think that unless this pattern is super-widespread (and it's not because we made it an error), it's really not worth giving this treatment to. I'd get giving this treatment to, like, nested object instantiation somehow, but syntactically nested conditionals are few and far between. There's a grand total of _one_ type in the react .d.ts which would save _one_ callstack depth for this. I feel a change like this change is just way too narrow to justify, at least without very concrete cases that it fixes and the effect it has on them.

**Comment by sandersn** [comment]
I don't think this change is that complicated. Disregarding whitespace changes and new comments, it's the same length as #36584 -- about 10 lines.
Both solutions seem a bit ad-hoc to me, although special-casing immediately nested conditionals *seems* safer and more sensible than temporarily blinding the instantiation depth limiter. I agree that it needs a bit more justification, either:

1. Example uses: (a) important packages with deeply immediately nested conditional types, or (b) a count of all immediately nested conditional types in some corpus like Definitely Typed or the user tests.
2. Performance benefit: by measuring some important package (or packages) before and after the change.

**Comment by weswigham** [comment]
@ahejlsberg I've finished merging #36584 into this PR, and also merged with `master` for you (it had conflicts). This should be good to go once CI checks all come back OK, so:

@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by sandersn** [comment]
@ahejlsberg This looks ready to merge, right?

**Comment by sandersn** [comment]
@ahejlsberg can you update this PR and then merge it?

**Pull request merged**
