### PR TITLE
noop in setTypeAcquisiton for undefined

### PR DESCRIPTION
**Pull request by jessetrinity**
#40952 mistakenly sets `typeAcquisition` to `{}` if it isn't explicitly set by the editor, disabling type acquisition in inferred projects. This reverts the changes made to `removeLocalTypingsFromTypeAcquisition` in that PR and noops in `setTypeAcquisition` when `newTypeAcquisition` is `undefined`.

Issue was caught in VS nightly integration tests.

### CODE REVIEW

**Review by sheetalkamat — COMMENTED** [review]
The change looks correct but i am surprised we dont have test. can you add one please so we dont regress this in future. Thanks

**Review by minestarks — APPROVED** [review]
Looks good. +1 to adding test if possible

**Comment by minestarks** [comment]
@DanielRosenwasser  heads up - we want this for 4.1 RC, looks like it's almost ready to go. Thanks!

**Comment by jessetrinity** [comment]
@sheetalkamat I've been looking at the tests for a while and I can't figure out what we should actually have as a regression test. Should there be a unit test for the compilerOptions/watchOptions/typeAcquisition setters to make sure they noop on undefined?

**Comment by jessetrinity** [comment]
To clarify - inferred projects infer `typeAcquisition` when it is undefined, so my previous change caused the inference to never happen (the getter started returning `{}`). A minimal test would basically be:
```ts
project.setTypeAcquisition(undefined);
assert.isTrue(project.getTypeAcquisition().enable, true)
```

**Comment by sheetalkamat** [comment]
`assert.deepEqual(project.getTypeAcquisition(), expected)` is what i think better test.

**Review by sheetalkamat — APPROVED** [review]

**Pull request merged**
