### PR TITLE
Fix extensions for noDtsResolution in node16/nodenext

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes 🙃 https://github.com/microsoft/TypeScript/issues/49003#issuecomment-1136355374

### CODE REVIEW

**Comment by andrewbranch** [comment]
@DanielRosenwasser can we put this into the next patch, whenever it goes out?

**Comment by DanielRosenwasser** [comment]
Sure!

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test this

**Review by weswigham — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.7

**Pull request merged**
