### PR TITLE
organizeImports: Preserve comments of deleted ImportDeclarations

### LINKED ISSUE #22723: Organize imports removes file header comment
**TypeScript Version:**  2.8.0-dev20180320

**Search Terms:** 
- Organize imports

**Code**
For the js:

```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as fs from 'fs'

function foo() {
    this.x = 1;
}
```

Run organize imports.

**Expected behavior:**

Only import is removed

**Actual behavior:**

Import plus the header comment are removed, leaving:

```js

function foo() {
    this.x = 1;
}
```

Trace:

```
[Trace  - 10:41:32 AM] Response received: organizeImports (34). Request took 3 ms. Success: true 
Result: [
    {
        "fileName": "/Users/matb/projects/san/index.js",
        "textChanges": [
            {
                "start": {
                    "line": 1,
                    "offset": 1
                },
                "end": {
                    "line": 7,
                    "offset": 1
                },
                "newText": ""
            }
        ]
    }
]
```

**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #22723

### CODE REVIEW

**Comment by amcasey** [comment]
Does this also address https://github.com/Microsoft/TypeScript/issues/22731?  If not, do you want to work on it or shall I?

**Comment by amcasey** [comment]
I would have expected something more like this https://github.com/amcasey/TypeScript/tree/ScratchGH22731.  It doesn't actually work (now the header comment is duplicated), but I haven't had a chance to investigate.

**Comment by andy-ms** [comment]
@amcasey I'll wait to see if your branch fixes this since that looks simpler.

**Comment by andy-ms** [comment]
Closing in favor of #22836

**Pull request closed without merging**
