### PR TITLE
Cache complex union and intersection relations

### PR DESCRIPTION
**Pull request by ahejlsberg**
We've discussed caching union and intersection relations before, but had concerns about the increased memory usage. This PR introduces caching for _complex_ union and intersection relations, specifically those than have a combined number of constituents of at least 4. This ideally strikes a balance between time and memory.

This PR improves check time for our "compiler with unions" code base by about 12%.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
Not much effect on our perf test suites, so not clear how valuable this is. But it definitely has a pretty positive effect on the compiler with unions code base.

**Comment by ahejlsberg** [comment]
@weswigham @RyanCavanaugh FYI

**Comment by DanielRosenwasser** [comment]
I'm surprised there's not a more pronounced effect on Material UI but I guess it makes sense

**Comment by weswigham** [comment]
@rbuckton know if we can go about enabling that perf test at some point (and get some historical data for it)?

@ahejlsberg we going to merge this at some point? Should it have a milestone? It looks like it needs a merge for a baseline update.

**Pull request merged**
