### PR TITLE
feat: refine .split() return type

### PR DESCRIPTION
**Pull request by castarco**
Work in Progress:
- [ ] Searching if there is an appropriate related issue
  - [ ] If not, prepare a properly described issue to describe the problem
- [ ] Prepare new specific tests

### CODE REVIEW

**Comment by castarco** [comment]
@microsoft-github-policy-service agree

**Comment by fatcerberus** [comment]
> Searching if there is an appropriate related issue

I found two:
* https://github.com/microsoft/TypeScript/issues/53362
* https://github.com/microsoft/TypeScript/issues/49635

**Comment by MartinJohns** [comment]
Your changed type definitions fail with `"".split("")`.

**Comment by castarco** [comment]
@MartinJohns 
> Your changed type definitions fail with "".split("").

Yes, I noticed some time later 😞 . I was thinking if it was possible to cover those corner cases with some extra function overrides... but that won't work, because there's a more generic case:

```typescript
const strValue = 'whatever'
const a = strValue
const b = strValue

// I don't know any way to assert (via the type system) a == b
// In this particular case, it is conceivable that TS would be able to
// perform some smart inferences... but sadly, a and b could be completely
// opaque in some contexts.
a.split(b)
```

So I guess I'll have to close this one.

**Comment by castarco** [comment]
My new attempt: #56841 .

**Pull request closed without merging**
