### PR TITLE
Remove error on redundant isolatedModules/verbatimModuleSyntax combination

### LINKED ISSUE #53601: When verbatimModuleSyntax: true, allow an explicit isolatedModules: true
# Bug Report

The new `verbatimModuleSyntax` implies `isolatedModules`, which is fine. However, it also prevents us from specifying `isolatedModules: true` explicitly, which should also be fine.

This is an issue in a [Next.js](https://nextjs.org/) app because its build process will force "isolatedModules: true" to be present. [This issue has been reported on their side as well](https://github.com/vercel/next.js/issues/46509).

So it is currently impossible to upgrade a Next.js app to TypeScript 5.

### Existing bug reports

This issue was not taken into consideration:

https://github.com/microsoft/TypeScript/issues/53374
https://github.com/microsoft/TypeScript/issues/53160

### 🕗 Version & Regression Information

TypeScript 5.0

### 🙁 Actual behavior

`
Type error: Option 'isolatedModules' is redundant and cannot be specified with option 'verbatimModuleSyntax'.
`
### 🙂 Expected behavior

`verbatimModuleSyntax: true` should allow `isolatedModules: true`.

### PR DESCRIPTION
**Pull request by andrewbranch**
This was intended to drive clarity, but doesn’t seem worth it since it’s caused a few problems.

Fixes #53601

### CODE REVIEW

**Review by sheetalkamat — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick to release-5.0

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Was there any code in transformModule that can now go away re: unsetting bad combos?

**Comment by fatcerberus** [comment]
Just for posterity, does this error also break the case I mentioned [here](https://github.com/microsoft/TypeScript/pull/53240#issuecomment-1467285767)? (base config with isolatedModules, extending config sets verbatimModuleSyntax)  Because if so, there would be no workaround in the absence of this PR.

**Comment by fatcerberus** [comment]
> That was never an error, IIUC.

thanks, I wouldn’t have suspected there was asymmetry in the implementation between the “base” options and “extended” options - I figured the two configs were just merged to get the effective config, since that seems the most obvious implementation.

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
