### PR TITLE
Fix nested parameter destructuring

### LINKED ISSUE #5389: "Cannot read property 'flags' of undefined" error when compiling nested array destruction
Hi,

I found `tsc` crashes when compiling nested array destruction in function parameter (example below).

## TypeScript version

1.8.0-dev.20151024 (installed via `npm install typescript@next`)

## Example Source

```js
const nestedArray = [[[1, 2]], [[3, 4]]];

nestedArray.forEach(([[a, b]]) => {
  console.log(a, b);
});
```

## Command

```
tsc index.ts
```

## Trace

```
/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:30338
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at getSymbolLinks (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:10715:23)
    at assignBindingElementTypes (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17679:25)
    at assignTypeToParameterAndFixTypeParameters (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17689:17)
    at assignContextualParameterTypes (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17666:17)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17860:29)
    at checkExpressionWorker (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:18503:28)
    at checkExpression (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:18445:42)
    at checkExpressionWithContextualType (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:18399:26)
    at checkApplicableSignature (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17162:31)
    at chooseOverload (/Users/seanchas116/Repos/seanchas116/typescript-destructuring-test/node_modules/typescript/lib/tsc.js:17448:30)
```

### PR DESCRIPTION
**Pull request by seanchas116**
This pull request fixes #5389 , by skipping assigning types for non-identifier binding patterns in `assignBindingElementTypes`.

### CODE REVIEW

**Comment by yuit** [comment]
could you also add test into compiler folder?

**Comment by mhegazy** [comment]
Actually i would not add a fourslash test. this is not a language service issue. i would just move the test to the compiler.

**Comment by DanielRosenwasser** [comment]
Hey @seanchas116, keep the fourslash test, but add the original issue in `tests/cases/compiler/bindingPatternInParameter01.ts`.

Also, it's no big deal, but try to give a heads up next time you decide to work on a bug. That way we can avoid duplicating effort. :smiley:

**Comment by seanchas116** [comment]
@DanielRosenwasser thanks! Added original issue source in `tests/cases/compiler/bindingPatternInParameter01.ts`.

> but try to give a heads up next time you decide to work on a bug.

Oh sorry, I'll do it next time.

**Comment by mhegazy** [comment]
thanks

**Comment by mhegazy** [comment]
manually merged in release-1.7

**Pull request merged**
