### PR TITLE
enhancement ts-ignore

### LINKED ISSUE #31147: make @ts-ignore available when using {/* @ts-ignore */}.
## Search Terms

@ts-ignore annotation

## Suggestion

Hi, I apologize if it is already discussed. However, I believe we need this feature for `@ts-ignore`. 
Currently `@ts-ignore` only mutes the errors only using with `// @ts-ignore`.
I believe we also need to make `@ts-ignore` available when using `{/* @ts-ignore */}`.

I've already founded [this issue](https://github.com/Microsoft/TypeScript/issues/19573). It's a similar issue but not the same and I think this is easier to implement.

I think this feature only need to change this code.
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L2

## Use Cases

I'd like to use this in the html structures in the TSX file.

## Examples

This is implementation for `amp-script`. We have to use `onclick` instead of `onClick` and it's not supported for now.
```
const App = () => {
  return (
    <div>
      ...
      {/* @ts-ignore */}
      <button onclick={() => setCount(count + 1)}>Click me</button> // this line should be ignored
      ...
    </div>
  );
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by sottar**
Fixes #31147

### CODE REVIEW

**Comment by sottar** [comment]
I'm not sure why the test is failed...Could someone help me?

**Comment by IllusionMH** [comment]
@sottar looks like your changes affect test in `tests/cases/compiler/checkJsFiles_skipDiagnostics.ts`
See [Managing the baselines section in CONTRIBUTING.md](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#managing-the-baselines)

You should review files under `tests/baselines/local` with simalar files in `tests/baselines/reference`. In [your case](https://github.com/Microsoft/TypeScript/pull/31168/checks?check_run_id=114636441) you can expand Raw output to see that there is reported diff in `checkJsFiles_skipDiagnostics.types` and `checkJsFiles_skipDiagnostics.symbols`. Thise files were affected since you've added new test cases to `tests/cases/compiler/checkJsFiles_skipDiagnostics.ts`

You should compare them and if changes are expected - use `gulp baseline-accept` command to accept changes.

If this will help to understand - principle is similar to one used in Jest snapshot testing.

**Comment by sottar** [comment]
@IllusionMH  I applied `gulp baseline-accept` command, and it passed the test. Thank you for your comment!

**Comment by RyanCavanaugh** [comment]
We're not able to review PRs that don't have approved issues associated with them. Please consult the PR template:
```
Please verify that:
* [ ] There is an associated issue in the `Backlog` milestone (**required**)
```

**Pull request closed without merging**
