### PR TITLE
Adjustmodularize lib

### PR DESCRIPTION
**Pull request by yuit**
Merging some modularize library files.

Add Node.d.ts

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Any specific reason you changed the name back to `lib.es6.d.ts`?

**Comment by yuit** [comment]
@DanielRosenwasser it is mainly to keep it consistent with older modularize library file as the two versions (with DOM or w/o DOM no longer conflict)

**Comment by mhegazy** [comment]
:+1:

**Comment by yuit** [comment]
@mhegazy. I will wait for the legal approval before merging it in

**Comment by basarat** [comment]
I suspect DefinitelyTyped should no longer have a `node.d.ts` (deleted) and the compile there should be adjusted (using `tscparams` to add `--lib node` and remove all `<reference`s to `node.d.ts`). Future PRs to modify `node.d.ts` should come here.

**Comment by yuit** [comment]
@basarat we are still weight in on adding the node.d.ts in as part of the default library. if we do that, we will have to update thing as you listed. I will still send PR to definitely-type to update part of node.d.ts still.

**Comment by alexeagle** [comment]
Any update on including a `node.d.ts` in the `lib` directory?

**Pull request merged**
