### PR TITLE
Improve support for numeric string types

### PR DESCRIPTION
**Pull request by ahejlsberg**
TypeScript represents numeric strings using the type `` `${number}` ``. This PR improves support for numeric string types to more accurately reflect that elements of arrays and tuples have numeric string property names. Specifically:

* Numeric index signatures apply when the index type is `${number}`. For example `` `Foo[][`${number}`]`` resolves to `Foo` instead of being an error. This is consistent with our existing rule that index signatures apply when the index type is a numeric string literal. For example `Foo[]['0']` already resolves to `Foo`.
* In a homomorphic mapped type `{ [K in keyof T]: XXX }`, where `T` is constrained to an array or tuple type, `K` has an implied constraint of `` number | `${number}` ``.
* Intersections of type `string` and a template literal type reduce to just the template literal type. For example, `` string & `${number}` `` now reduces to just `` `${number}` ``.

Some examples:

```ts
function f1(a: boolean[], x: `${number}`) {
    let s = a[x];  // boolean
}

function f2(a: boolean[], x: number | `${number}`) {
    let s = a[x];  // boolean
}

type T1 = boolean[][`${number}`];  // boolean
type T2 = boolean[][number | `${number}`];  // boolean

type Container<T> = {
    value: T
}

type UnwrapContainers<T extends Container<unknown>[]> = {
    [K in keyof T]: T[K]['value']  // Ok, but used to be error
};

declare function createContainer<T extends unknown>(value: T): Container<T>;

declare function f<T extends Container<unknown>[]>(containers: [...T], callback: (...values: UnwrapContainers<T>) => void): void;

const container1 = createContainer('hi')
const container2 = createContainer(2)

f([container1, container2], (value1, value2) => {
    value1;  // string
    value2;  // number
});
```

For further context, see discussion in #48599.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by Andarist** [comment]
I believe that this will close https://github.com/microsoft/TypeScript/issues/48739

**Comment by ahejlsberg** [comment]
Tests and perf all look to be unaffected.

**Review by weswigham — APPROVED** [review]

**Comment by jcalz** [comment]
Could someone revisit #41893 and explain what's going on here and how it either meshes with or supersedes it?  The argument there that is that `array["-0.0e123"]` is not going to be the same as `array[0]` and so `` `${number}` `` cannot be used to into numeric index signatures because there's no requirement that the numeric strings in question round trip back to themselves:

```ts
const arr: string[] = [];
const x: `${number}` = "-0.0e123";
arr[x] = "oopsie"; // <-- is this supposed to be okay or an error?
``` 

Personally I'd *love* it if  such a requirement existed and that `` `${number}` `` would reject `"-0.0e123"` because the plain reading of `` `${number}` `` is "what you get if you serialize a number via a template literal string".  And it agrees with what happens if you put a numeric literal or union of literals instead of `number` there.  `` `${0}` `` is not "any string which yields `0` when coerced to a number", it's just `"0"`.  I had given up all hope of this happening, because [democracy](https://github.com/microsoft/TypeScript/issues/41893#issuecomment-889237299). 

But but now if you're doing this, it means that you agree that arrays and tuples have keys of type `` `${number}` ``, which means that there's a chance of revisiting this and making everything consistent, right?  R...right?  Sigh.  Assuming that this will *not* change, then can we hear some authoritative words about it so I can at least parrot them back when people ask what's going on with this?

**Comment by ahejlsberg** [comment]
> Could someone revisit https://github.com/microsoft/TypeScript/issues/41893 and explain what's going on here and how it either meshes with or supersedes it?

Yes, see [here](https://github.com/microsoft/TypeScript/issues/41893#issuecomment-1111056408).

**Pull request merged**
