### PR TITLE
Reduce away intersections that aren't assignable to constituents in CFA

### LINKED ISSUE #37659: [3.9.0-beta] OR'd types seem to get ANDed because of assertions
**TypeScript Version:**  3.9.0-dev.20200327

**Search Terms:**

**Expected behavior:**
No error -- this worked fine in 3.8 (and should)

**Actual behavior:**
Error:
```
Argument of type 'CommitFileNode | ResultsFileNode | (ResultsFileNode & StashFileNode)' is not assignable to parameter of type 'CommitFileNode | ResultsFileNode | StashFileNode | StatusFileNode'.
  Type 'ResultsFileNode & StashFileNode' is not assignable to type 'CommitFileNode | ResultsFileNode | StashFileNode | StatusFileNode'.
    Type 'ResultsFileNode & StashFileNode' is not assignable to type 'StashFileNode'.
      Property '_foo1' has conflicting declarations and is inaccessible in type 'ResultsFileNode & StashFileNode'.(2345)
```

**Related Issues:**

**Code**
```ts
abstract class ViewNode { }
abstract class ViewRefNode extends ViewNode { }
abstract class ViewRefFileNode extends ViewRefNode { }

class CommitFileNode extends ViewRefFileNode {
  private _id: any;
}

class ResultsFileNode extends ViewRefFileNode {
  private _id: any;
}

class StashFileNode extends CommitFileNode { 
  private _id2: any;
}

class StatusFileNode extends ViewNode {
  private _id: any;
}

class Foo {
  private async foo(node: CommitFileNode | ResultsFileNode | StashFileNode) {
		if (
			!(node instanceof CommitFileNode) &&
			!(node instanceof StashFileNode) &&
			!(node instanceof ResultsFileNode)
		) {
			return;
		}

		await this.bar(node);
	}

  private async bar(node: CommitFileNode | ResultsFileNode | StashFileNode | StatusFileNode, options?: {}) {
    return Promise.resolve(undefined);
  }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class ViewNode {
}
class ViewRefNode extends ViewNode {
}
class ViewRefFileNode extends ViewRefNode {
}
class CommitFileNode extends ViewRefFileNode {
}
class ResultsFileNode extends ViewRefFileNode {
}
class StashFileNode extends CommitFileNode {
}
class StatusFileNode extends ViewNode {
}
class Foo {
    async foo(node) {
        if (!(node instanceof CommitFileNode) &&
            !(node instanceof StashFileNode) &&
            !(node instanceof ResultsFileNode)) {
            return;
        }
        await this.bar(node);
    }
    async bar(node, options) {
        return Promise.resolve(undefined);
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": 2,
    "target": "ES2017",
    "jsx": "React",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/v2/en/play?ts=3.9.0-dev.20200327#code/IYIwzgLgTsDGEAJYBthjAgagSwKYHcA5AewBNcEBvBAXwChRIZ4lV0s98AlXAMxPIJcADwi4AdqQw4CAitXqNocRCjTTOPXgDFsyXHKGiJUjgS2GFdOmvYBhYgFtH2CLv2GRYyRvN93BmTydAgIAA5Q2ABuwGIIAPrYpABcCMDiAJ4A3HT0NmwYPGAArsgQYAGexj5m3P56gYKUIeGRMXGJKWmZOXm2GADKEGgAFpVBRt6mDs6u400ILRHRsRSdAEyp6dm51v0IQ7HFFQ1VU75EE82hy+1rSVs9u-nqCNrExFRLbatpYBniWAIXgfAAU4iCqRmLjcpwmAB8EEVSuV5hREYcwGM4eQAJRfACQBOwvAQoLoRIJAEJwRNsOJIOlYLhiKToXMcbh8QAybkUok0iGCemMwEs0mY7EeII8vmUwV0hnDMWspG4EplE7SvH8-HNSlQXAQYpQcQ5Il5InAfDAVwICAjbBgAB0IGAUFpePNeRuPziaABQLdHqFuChThhaIQiORmqjGOGWPjB2Gxq1jVwABoEMQwhBsMQGQB+VKUGh6lqhQ3G00IAAKUCcTtwzsNYGIyCiuFBxUkfHpuFIuJyoXoNCAA)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #37659.

### CODE REVIEW

**Comment by weswigham** [comment]
@ahejelsberg shouldn't `A & B` be assignable to `A` in this case? `A & B` by definition has all of `A`'s private fields, no?

**Comment by ahejlsberg** [comment]
@weswigham Well, yes, but `A` and `B` also have a conflicting private member `x` and we consider it an error to access conflicting members (introduced years ago in #13990). The access happens as we're checking the properties from the whole intersection against the properties of each of `A` and `B`, a check that was introduced recently in #37195.

**Comment by ahejlsberg** [comment]
@weswigham We're basically trying to have it both ways. It would seem reasonable for `A & B` to be assignable to `A` and `B` even with the conflicting private properties, yet we rely on an error being issued in the link below as an early warning that a mixin produced an invalid type.

https://github.com/microsoft/TypeScript/pull/13990/files#diff-4b0cabe62740b5899b9a7850e502007aR95

**Comment by ahejlsberg** [comment]
Superceded by #37762.

**Pull request closed without merging**
