### PR TITLE
Structural `tag type` brands

### PR DESCRIPTION
**Pull request by weswigham**
Consider this a competitor to (or at least consideration for) #33038.

This makes explicit the current patterns of structural branding and reserves their functionality with special syntax. The newly introduced syntax is the new keyword type operator `tag T`, where `T` can be any type. It is used like so:
```ts
type NormalizedPath = string & tag {NormalizedPath: void};
type AbsolutePath = string & tag {AbsolutePath: void};
type NormalizedAbsolutePath = NormalizedPath & AbsolutePath;

declare function isNormalizedPath(x: string): x is NormalizedPath;
declare function isAbsolutePath(x: string): x is AbsolutePath;
declare function consumeNormalizedAbsolutePath(x: NormalizedAbsolutePath): void;


const p = "/a/b/c";
if (isNormalizedPath(p)) {
    if (isAbsolutePath(p)) {
        consumeNormalizedAbsolutePath(p);
    }
}
```
This PR also now adds a global  `type Tag<T extends string> = tag {[K in T]: void};` for convenience, which means instead of the above, you can write:
```ts
type NormalizedPath = string & Tag<"NormalizedPath">;
type AbsolutePath = string & Tag<"AbsolutePath">;
type NormalizedAbsolutePath = NormalizedPath & AbsolutePath;
```
which gives a simple way to get a nice string-based pseudo-unique tag.

The operand type does not contribute to the visible structure of the type in any way (a `tag` still looks like `unknown` when queried), however `tag` types are related with one another based on their argument type to ensure tag compatibility.

Compared with nominal tags, this has some upsides:
* Identical tags across files are assignable to one another, as they are structurally related
* It works like structural brands do today, but prevents the tags from contributing to the object's visible structure (with respect to completions and the like)
* It enshrines structural tagging patterns with special syntax (which can then be recognized and optimized)

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this just cuz

**Comment by weswigham** [comment]
@typescript-bot pack this just cuz

**Comment by AnyhowStep** [comment]
If one wanted the same behavior as the other PR (nominally typed, different libraries are incompatible, different versions of same library are incompatible), would it be done like this?

```ts
type NormalizedPath = string & tag unique symbol;
type AbsolutePath = string & tag unique symbol;
```

**Comment by weswigham** [comment]
>If one wanted the same behavior as the other PR (nominally typed, different libraries are incompatible, different versions of same library are incompatible), would it be done like this?

Not quite - `unique symbol` has to appear directly on a declaration, so it'd need to look like so:
```ts
declare var normalizedSym: unique symbol;
type NormalizedPathBrand = tag { [normalizedSym]: void; };
type NormalizedPath = string & NormalizedPathBrand;
declare var absoluteSym: unique symbol;
type AbsolutePathBrand = tag { [absoluteSym]: void; };
type AbsolutePath = string & AbsolutePathBrand;
```

**Comment by AnyhowStep** [comment]
I was under the impression that this would work,

```ts
declare var normalizedSym: unique symbol;
type NormalizedPath = string & tag typeof normalizedSym;
```

Since,
> `T` can be any type

**Comment by fatcerberus** [comment]
So after my initial knee-jerk reaction favoring `unique`, I actually end up preferring this *greatly* over #33038.  Issues with `unique`:

* Not referentially transparent: two individual utterances of `unique` are different types.  This is actually why I ended up hating `unique & Type` (looks like a type expression but is secretly a type operator), but didn’t realize it at the time.
* Difficult to explain to newbies why `unique string` is not assignable to `unique string`.
* Antithetical to structural typing, which is otherwise pervasive.

`tag` on the other hand, *is* referentially transparent (`string & tag { foo: void }` is always the same type everywhere it occurs), is always assignable to itself, and is based on the familiar structural typing rules so no surprises there either.  It checks all the boxes that `unique` doesn’t!

My one concern is, do we need the `: void`?  The types of the tag properties don’t matter (they don’t type any actual data) so seems like it could just be left off to avoid some unnecessary complexity/cognitive overhead.  No reason to make the end-user write types they don’t actually need to care about.

**Comment by fatcerberus** [comment]
> The types of the tag properties don’t matter 

On the other hand, if the type if the tag properties is not artificially limited to `void` then I think this feature could be used to implement phantom types/GADTs; that is hard today because if you don’t use a generic type parameter in the type then it doesn’t affect assignability.  But if you can use it in a *tag* that doesn’t actually type real data... that changes things!

So in case it wasn’t obvious: I retract my previous suggestion of dropping the types from the tag literal. :wink:

**Comment by leemhenson** [comment]
One of the rough edges with existing branding techniques like this is that the printed type is pretty noisy once you have multiple brands assigned at the same time. For example, using `brand` in `io-ts` (https://github.com/gcanti/io-ts/blob/master/src/index.ts#L478-L507) you end up with nested `Branded`: 

```ts
id: t.Branded<t.Branded<string, NonEmptyStringBrand>, UuidBrand>
```

When you use a lot of these sorts of types, you can end up with compound types that are difficult to read. Would this PRs approach help in this regard? The other PR intuitively seems to suggest that if I create a nominal type along the lines of 

```ts
type NonEmptyString = unique string;
tUserId = string & NonEmptyString
``` 

then I'd just see 

```ts
id: UserId
```

**Comment by AnyhowStep** [comment]
They can "fix" that nesting by changing the definition of `Branded` to be,
```ts

export type Branded<A, B> = [A & Brand<B>][0]

```

This should then give you,
```ts
id: string & Brand<NonEmptyStringBrand> & Brand<UuidBrand>
```

**Comment by jack-williams** [comment]
Small Q: What is the planned behaviour of the following?
```ts
type GetTag<T> = T extends tag infer U ? U : never
```
Right now I don't think it was working, but is the plan for it to infer the tag as one would expect?

----

Is there strong motivation for having tags be in the domain of types, beyond implementation? Clearly you get a huge amount of the implementation for free, but I wonder if the user experience in the most general case is negatively impacted. As an example, it would seem natural, or at least satisfy most requirements, to write :
```ts
type NormalizedPath = string & tag "NormalizedPath";
type AbsolutePath = string & tag "AbsolutePath";
type NormalizedAbsolutePath = NormalizedPath & AbsolutePath;

declare function isNormalizedPath(x: string): x is NormalizedPath;
declare function isAbsolutePath(x: string): x is AbsolutePath;
declare function consumeNormalizedAbsolutePath(x: NormalizedAbsolutePath): void;

const p = "/a/b/c";
if (isNormalizedPath(p)) {
    if (isAbsolutePath(p)) {
        consumeNormalizedAbsolutePath(p);
    }
}
```
however here the tag of `p` in the inner branch is `tag never`. I might ask _why?_, and the answer is because no value satisfies the types `"NormalizedPath"` and `"AbsolutePath"`. That answer doesn't seem particularly satisfactory because you are asking users to reason about structural properties of types in a context that is largely non-structural, or at least, the structure is completely independent to the values you are trying to reason about.

The intended way to write this: `string & tag { NormalizedPath: void }`, feels like it is only motivated by the fact that object types compose under intersection, but I have a hard time connecting this to my intuition of branded types.

Are there use-cases where having tags be a type is either very intuitive, or capable of expressing some clearly desirable pattern? I'm not yet convinced GADT's fallout of this nicely, but I'm more than happy to be corrected. I'm sure someone will come along with an incredibly detailed implementation of units-of-measure, but these complicated conditional types are really hard to debug and understand.

So I guess my point is here: if we are assuming a blank slate to implement a new feature with new syntax, is this approach the best approach for most cases most of the time? Or as an open challenge:
- What are examples where you want to be parametric in the tag, other than defining `Tag`?
- What are examples where having the tag be a type provides a significant boost in _Simplicity, Usability and Soundness_ (to quote the design goals). I have no doubt there are very complex examples, but they should provide benefit to mere mortals!

I'm not really sure what is better right now, I'm just curious to understand the design space more and see how people would use it.

**Comment by AnyhowStep** [comment]
I hadn't considered the `tag never` thing. Now it makes sense why he had,
```
type Tag<T> = /*snip object*/
```

**Comment by weswigham** [comment]
> What is the planned behaviour of the following?

Yeah, that _should_ work (at least I don't see why it would not). Thanks for the report - I think because I have `StructuralTag` types marked as `Instantiable`, the conditional is never resolving. I'll need to fix that.

> Are there use-cases where having tags be a type is either very intuitive, or capable of expressing some clearly desirable pattern?

Phantom types, mostly. Much like with our implementation of mapped types and conditional types, I think having a general underlying mechanism that enables multiple usecases, but also presents with a simple interface for common cases (like `Partial`), is a good compromise. That's why I also mention adding a `type Tag<T extends string> = tag {[K in T]: void};` to the standard library, this way you _can_  just write `string & Tag<"AbsolutePath">`. Also, this syntax lends itself well to migration of tag-like objects that exist today. If anywhere in your code, you, today, have a `string & {__myBrand: void}`, you can _trivially_ upgrade your experience (no more ghost completion members from brands!) by just dropping a `tag` keyword in front of the branding object type.

> incredibly detailed implementation of units-of-measure

Most certainly not possible. A key feature of units of measure is composition over algebraic operators (imo), which this does not enable. So while you could track units, you can't manipulate them easily, so... eh.

> What are examples where you want to be parametric in the tag

Some of the functional utility libraries I've read (`rxjs`, I think, is one) occasionally have "fake" structural members, whose existence is solely to traffic type information around to be used in assignability checking (the type stored in the brand establishes relationships between instances) and extracted later. A phantom type, if you will. Honestly, this feature, as written, while written to satisfy branding, is moreso an implementation of storage for phantom types (since we're structural, even a "phantom" type parameter needs to appear _somewhere_ to indicate how it should be compared), which as it happens can be used for branding.

**Comment by jack-williams** [comment]
They are fair points, but just to debate the point<sup>for the sake of it</sup>:

I think solving multiple use cases is only one aspect: it's probably worth evaluating it against the distribution of uses cases and how well each one is addressed.

What is the magnitude of the improvement for the phantom type use case? Not having ghost members is useful, as is an optimised representation, but if you're doing anything non-trivial you'll still be doing complex type logic or relying on casts to push through generic constraints that are hard to verify. Not to mention that phantom types are never really going to be _that_ useful unless you have the associated constraints discharged on 'pattern matching', IMO.

Conversely, it seems like the majority of users really do want branding (at least from the examples in associated issues) and there is the opportunity to deliver first-class support for that feature.

Though, if I'm being honest, if there was new logic added for type display such that `NormalizedPath & AbsolutePath` printed as:
```ts
string & Tag<"NormalizedPath" | "AbsolutePath">
```
rather than:
```ts
string & tag ({ NormalizedPath: void } & { AbsolutePath: void })
```
it would probably be fine.

And FWIW, I prefer this to `unique`.


----

This was the units-of-measure implementation I was thinking of: https://github.com/jscheiny/safe-units.

**Comment by weswigham** [comment]
> Though, if I'm being honest, if there was new logic added for type display such that NormalizedPath & AbsolutePath printed as:

@jack-williams I've done one better - not only are instances of the global `Tag` (which I've now added to the lib) preserved, tags which are references to _any_ accessible alias are preserved. So you can use whatever funky `Tag`-like alias your heart desires, and so long as individual intersection members within the tag type when individually looked at inside of a `tag` have an associated alias.

Also tags now distribute over unions, because I neglected that in the first pass, and it _really_ doesn't seem to make as much sense if they don't. This means `tag (A | B)` `===` `(tag A) | (tag B)`, and we use the second representation internally. Technically, they already distributed over intersections, so `tag (A & B)` `===` `(tag A) & (tag B)`, however I've chosen the _first_ to be the canonical representation in the compiler (`tag (A & B)`) simply because while that makes construction a bit more interesting (tags within intersections are combined upon construction), it makes doing comparisons later much simpler (we just match the source tag component to the target tag component and unwrap).

**Comment by weswigham** [comment]
@typescript-bot pack this again now that we do inference, unions, and aliases better

**Comment by joshburgess** [comment]
This looks interesting and syntactically reminds me of how the library `newtype-ts` works. A type with a phantom type as implemented in this PR,

```typescript
type Key<A> = string & tag { Key: A };
```

is currently implemented like the following in `newtype-ts`:

```typescript
interface Key<A> extends Newtype<
    { readonly Key: unique symbol, readonly phantom: A },
    string
  > {}
```

While this gives you the power to express phantom types by altering the nominal type via a structural means, I do think it sort of leaks implementation details that the user shouldn't necessarily need to care about.

It's definitely better than not being able to do this at all, but I think it would be nicer if such structural modification was done behind the scenes without the user needing to explicitly modify the structure of a tag.

**Comment by fatcerberus** [comment]
> Phantom types, mostly.

🎉 🎊 

YES!  I was starting to think I was the only one who saw the value of these...

**Comment by jack-williams** [comment]
@weswigham Those baselines look really nice now.

Would it be possible for an interface to extend a tag type?
```ts
interface Parent extends Tag<"A"> { }

interface Child1 extends Parent, Tag<"B"> { }

interface Child2 extends Parent, Tag<"C"> { }
```

**Comment by chriskrycho** [comment]
I tried pulling that tgz and using it locally and it failed… did I do something wrong?

**Comment by weswigham** [comment]
Moat slashes have some kind of meaning in a shell, so `npm i <url>` is prone to not working - that's why the instructions give you a package.json block.

**Comment by SamHH** [comment]
Can't most shells handle URLs appropriately if they're wrapped in quotes, or have I been living in fish-land for too long?

**Comment by weswigham** [comment]
> Can't most shells handle URLs appropriately if they're wrapped in quotes, or have I been living in fish-land for too long?

You'd think so, but I had issues with both bash and powershell last I checked. :woman_shrugging:

**Comment by ProdigySim** [comment]
The latest bundle does not seem to work for me either. Upon compiling (in a `--strict` environment) I get errors parsing `lib..es5.d.ts`:

```
node_modules/typescript/lib/lib.es5.d.ts:1504:37 - error TS1005: ';' expected.

1504 type Tag<K extends keyof any> = tag {
                                         ~

node_modules/typescript/lib/lib.es5.d.ts:1505:11 - error TS1005: ';' expected.

1505   [_ in K]: void;
               ~

node_modules/typescript/lib/lib.es5.d.ts:1505:17 - error TS1109: Expression expected.

1505   [_ in K]: void;
```

`tsc --version` reports: `Version 3.6.0-dev`. 

Tried on both a clean project w/ no tsconfig  & an existing one that uses --strict.

**Comment by weswigham** [comment]
Hmmm, the last tarball was bundled as version `3.7.0-insiders.20190909`, but, yeah, I see that issue, too, when I actually install the tarball, rather than using the version I've built locally. I'll rebase and rebuild the package, something wonky must have happened.

**Comment by weswigham** [comment]
@typescript-bot pack this again

**Comment by weswigham** [comment]
@typescript-bot pack this again

**Comment by weswigham** [comment]
@typescript-bot pack this again again now that the linter's off in CI while it's broken

**Comment by weswigham** [comment]
@typescript-bot pack this again

**Comment by weswigham** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@typescript-bot pack this one last time just to check if lints and scripts do work now

**Comment by weswigham** [comment]
Alright, sorry for the spam for anyone watching - I had to debug a small issue with the build, but the tarball should be functional again.

**Comment by chriskrycho** [comment]
Thanks for getting it straightened out!

**Comment by ProdigySim** [comment]
Would it be possible to support Record/index types with either of these proposals?

A common pattern in redux involves creating a ["normalized" store of objects](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape#designing-a-normalized-state). Since redux stores are POJOs, we can't simply use `Map<K,V>` for these, preferring instead `Record<K, V>`. I'm using DIY tag types today, and we have to fall back to `Record<string, T>` for these.

Here's some simple test code that currently errors on the experimental build:
```ts
type UserId = string & Tag<'unique-userid'>;
const userRec: Record<UserId, string> = {};
const userMap: {
  [idx: UserId]: string;
} = {};

declare const userId: UserId;
userRec[userId] = 'bob';
console.log(userRec[userId]);
userMap[userId] = 'bob';
console.log(userMap[userId]);
```

It seems like if the `tag` types are truly phantom we might be able to use these as index types.

**Comment by weswigham** [comment]
> Would it be possible to support Record/index types with either of these proposals?

You'd just need #26797 (with either)

**Comment by ProdigySim** [comment]
Another minor difference I thought of today while debugging an issue with a manual `Opaque<T,K>` solution: These "official" tag types do not extend `object`.

You can try this code against the test build the bot created:
```ts
// Experimental Tag Types from this PR
type Builtin = string & Tag<'builtin'>;

// true
type yy = Builtin extends string ? true : false;
// false
type zz = Builtin extends object ? true : false;

// DIY tag type solution
type RetroTag<T, K> = T & { __tag: K }
type Retro = string & RetroTag<string, 'retro'>;

// true
type aa = Retro extends string ? true : false;
// true
type bb = Retro extends object ? true : false;
```

In my case, today I had to special case a type conditional to avoid having my tag types be treated as objects. With the new behavior exhibited by the builtin implementation here, I wouldn't have had to. 

So, I'd consider this an improvement over the DIY solution. But probably worth noting for anyone trying to convert from DIY to builtin.

**Comment by sandersn** [comment]
This experiment is pretty old, so I'm going to close it to reduce the number of open PRs.

**Comment by shicks** [comment]
Would the authors consider revisiting this work?  There seem to be quite a few people interested in the feature (see the recent comments on #33038), though this approach seems to be the better approach.

**Comment by RyanCavanaugh** [comment]
This is effectively an implementation sketch for #202. We'd prefer people interact with the suggestion issues than the PRs, since the implementation of a feature is mechanical once the design has been worked out, and nominal types are still very much under discussion

**Pull request closed without merging**
