### PR TITLE
Revert #57896

### PR DESCRIPTION
**Pull request by andrewbranch**
My attempt (#58831) to just disable #57896 was incomplete, so this is the full revert instead.

### CODE REVIEW

**Comment by jakebailey** [comment]
Does this also undo Wesley's change? Or does that still work?

**Comment by andrewbranch** [comment]
The only interaction between my work and #58176 is how often package.jsons that one of us is doing a lookup for is already cached because of a lookup that the other is doing.

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick to release-5.5

**Review by jakebailey — APPROVED** [review]
😢

**Pull request merged**
