### PR TITLE
Delete IoSessionOptions

### PR DESCRIPTION
**Pull request by amcasey**
Many of the options were unused because the values were being accessed directly from the enclosing scope.

The first commit is #22590.

### CODE REVIEW

**Comment by amcasey** [comment]
Alternatively, we could actually use the properties of IoSessionOptions, but that has the disadvantage of being error-prone (as demonstrated by the current state).

**Comment by amcasey** [comment]
@sheetalkamat Correct, I will not merge this until #22590 is sorted out.

**Comment by sheetalkamat** [comment]
can you please fix #22607 as well as part of this. Thank you.

**Comment by amcasey** [comment]
@sheetalkamat, I created https://github.com/Microsoft/TypeScript/pull/22776 for #22607.

**Pull request merged**
