### PR TITLE
Fix: handle absent crypto, fixes #19100

### LINKED ISSUE #19100: Handle absent 'crypto' as per nodejs docs
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

TypeScript compiler relies on node's 'crypto' module unconditionally:

https://github.com/Microsoft/TypeScript/blob/6997e9b7316b081f8731d131139c7d7f1bba9092/src/compiler/sys.ts#L132

Whereas node's <a href="https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable">documentation for crypto module</a> explicitly states:

<blockquote>
<h3>Determining if crypto support is unavailable</h3>
It is possible for Node.js to be built without including support for the crypto module. In such cases, calling require('crypto') will result in an error being thrown.

```javascript
let crypto;
try {
  crypto = require('crypto');
} catch (err) {
  console.log('crypto support is disabled!');
}
```
</blockquote>

That means on a reduced node environment the compiler crashes unnecessarily. By unnecessarily I mean the support for crypto is already optional in the compiler:

https://github.com/Microsoft/TypeScript/blob/6997e9b7316b081f8731d131139c7d7f1bba9092/src/compiler/sys.ts#L67

https://github.com/Microsoft/TypeScript/blob/d7269f1386bb1ad4351a6f6d5f749e89cb14c2b7/src/compiler/watch.ts#L635

https://github.com/Microsoft/TypeScript/blob/67a6a9477f90d61955f92fb33e7b11491dbd17a5/src/compiler/program.ts#L165

**Expected behavior:**

TSC to work without 'crypto'

**Actual behavior:**

TSC fails without 'crypto'

### PR DESCRIPTION
**Pull request by mihailik**
Fixes #19100

### CODE REVIEW

**Comment by sheetalkamat** [comment]
I am assuming we dont want to make it optional in tsserver. 
(checkout  https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts#L408)

**Comment by mihailik** [comment]
@sheetalkamat do you think it's a good idea to allow running tsserver without crypto too?

**Comment by mhegazy** [comment]
We have too many assumptions that if `--watch` is allowed we can use hashes. just checking here is not sufficient i am afraid.

**Comment by mihailik** [comment]
@mhegazy let's calculate a weak hash in code

**Comment by mhegazy** [comment]
sure

**Comment by mihailik** [comment]
@mhegazy just to check: collisions due to weak hash are only affecting performance, cannot cause incorrect behaviour, is that right?

**Comment by mhegazy** [comment]
that is my expectation as well.

**Comment by mhegazy** [comment]
closing for now. please reopen with a default implementation for a weak hash function.

**Pull request closed without merging**
