### PR TITLE
Update dom.generated.d.ts

### PR DESCRIPTION
**Pull request by yukulele**
add SVG elements cast

### CODE REVIEW

**Comment by Arnavion** [comment]
I guess the qualifiedName should all be lower-case to be consistent with createElement() ?

**Comment by yukulele** [comment]
SVG is case sensitive.
example for `foreignObject`: https://stackoverflow.com/questions/26174412/creating-foreignobject-in-svg-using-javascript

But I'm not sure all my `qualifiedName` strings are ok

**Comment by yukulele** [comment]
Changed according to dart source code: https://github.com/dart-lang/bleeding_edge-DEPRECATED-USE-SDK-INSTEAD/blob/master/dart/sdk/lib/svg/dart2js/svg_dart2js.dart#L90

(by search all `/factory \S+Element.*;$/` regexp lines)

**Comment by mhegazy** [comment]
@zhengbli how easy is it to include these in your script?

**Comment by mhegazy** [comment]
@yukulele this file is auto generated. we do not manually change it. @zhengbli is working on sharing the  script that generates this file; but we can not make changes directly to the file. 

One alternative is to put these definitions in a new file in `src\lib\domExtensions.d.ts`,  then add it to lib.d.ts generation in JakeFile: https://github.com/Microsoft/TypeScript/blob/master/Jakefile.js#L160-L168

**Comment by mhegazy** [comment]
@zhengbli has incorporated this in the script, so the next update to dom.generated.d.ts will have it. thanks!

**Pull request closed without merging**
