### PR TITLE
Improve identifier check

### LINKED ISSUE #24482: Mis-parsing of variables named `enum`
**TypeScript Version:**  2.8.3

**Search Terms:** 
- enum variable name

**Code**

```ts
interface Foo {
    enum: string;
}

function bar({ enum }: Foo) {
    if (enum) {
        //
    }
}
```

**Expected behavior:**

Code compiles without issue.

**Actual behavior:**

Error at 5: `Enum declarations can only merge with namespace or other enum declarations.`
Error at 5: `':' expected.`
Error at 6: `Enum declarations can only merge with namespace or other enum declarations.`
Error at 6: `Expression expected.`
Error at 6: `Identifier expected.`

**Playground Link:**
[Playground](https://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20enum%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20bar(%7B%20enum%20%7D%3A%20Foo)%20%7B%0D%0A%20%20%20%20if%20(enum)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A)

### LINKED ISSUE #28648: ts error should better explain that import is a reserved keyword for a function name
**TypeScript Version:**  3.1.6

**Search Terms:**
import
import keyword
keyword
**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

given the following code with a function named `import` :disappointed: :    
```ts
export function	import(pad_id: number, config: Config, csvRows: string[][], externalCallback: (err?: Error | null, data?: string[]) => void) {
...
```

image

**Expected behavior:**

A clear error message explaining that import is a reserved keyword

**Actual behavior:**

A cryptic error message telling that there's a missing semicolumn :  

image

**Playground Link:** 

**Related Issues:** 

didn't found any

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #28648 
Will be Fixes #24482 

This pr has made as little changes as possible. 
Change the specified identifier node check in checker rather than in parser.
That could improve the parser error

- [x] function expression or object literal method
- [x] continue or break statement
- [x] function declaration or method declaration
- [x] type parameters
- [x] interface declarations
- [x] type alias declarations
- [x] enums declarations
- [ ] parameter declaration
- [ ] binding pattern

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
(Running DT tests on this PR just to make sure that it still works after a recent change to dtslint. Please ignore the results.)

**Comment by Kingwl** [comment]
@typescript-bot test perf

**Comment by Kingwl** [comment]
@typescript-bot perf test

**Comment by Kingwl** [comment]
@typescript-bot run dt

**Comment by Kingwl** [comment]
i can't believe that dt is still work😂

**Comment by RyanCavanaugh** [comment]
@Kingwl what's the status on this? Still WIP?

**Comment by Kingwl** [comment]
Yes, I'll take a look soon

**Comment by RyanCavanaugh** [comment]
@kingwl please unassign yourself when you're ready for us to take a look. Thanks!

**Comment by Kingwl** [comment]
Too many conflicts. I'd like to send these changes in another pr.

**Pull request closed without merging**
