### PR TITLE
Add support of spread enum member

### LINKED ISSUE #17592: Extending string-based enums
Before string based enums, many would fall back to objects. Using objects also allows extending of types. For example:
```ts
const BasicEvents = {
    Start: "Start",
    Finish: "Finish"
};

const AdvEvents = {
    ...BasicEvents,
    Pause: "Pause",
    Resume: "Resume"
};
```

When switching over to string enums, it"s impossible to achieve this without re-defining the enum.

I would be very useful to be able to do something like this:

```ts
enum BasicEvents {
    Start = "Start",
    Finish = "Finish"
};

// extend enum using "extends" keyword
enum AdvEvents extends BasicEvents {
    Pause = "Pause",
    Resume = "Resume"
};
```

Considering that the produced enums are objects, this won"t be too horrible either:
```ts
// extend enum using spread
enum AdvEvents {
    ...BasicEvents,
    Pause = "Pause",
    Resume = "Resume"
};
```

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #17592

### CODE REVIEW

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by Kingwl** [comment]
Well.... It's WIP

**Comment by TrejGun** [comment]
thanks man! really usefull

this supports ... syntax

```
enum BasicEvents {
  Start = "Start",
  Finish = "Finish"
}
enum AdvEvents {
  ...BasicEvents,
  Pause = "Pause",
  Resume = "Resume"
}
```

which is usefull for multiple extensions like

can I suggest to add a support of `extend` syntax for single extension?
```
enum BasicEvents {
  Start = "Start",
  Finish = "Finish"
}
enum AdvEvents extends BasicEvents {
  Pause = "Pause",
  Resume = "Resume"
}
```

also what happens in case of overlaping
```
enum Basic1Events {
  Start = "Start",
  Finish = "Finish"
}
enum Basic2Events {
  Start = "Start",
  Finish = "Finish"
}
enum AdvEvents {
  ...Basic1Events,
  ...Basic2Events,
  Pause = "Pause",
  Resume = "Resume"
}
```

will AdvEvents.Start === Basic1Events.Start ?

**Comment by Kingwl** [comment]
@TrejGun 

You can see the [comment](https://github.com/microsoft/TypeScript/issues/17592#issuecomment-705109882) and [design notes](https://github.com/microsoft/TypeScript/issues/40963)

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
@andrewbranch @DanielRosenwasser @sandersn 

I have some confused.

Enum can be merge from many positions.

```ts
enum A {
    f = 'f'
}

console.log(A.ff) // [LOG]: undefined

enum B {
    ...A,
    b = 'b'
}

enum A {
    ff = 'ff'
}

console.log(A.f, A.ff, B.f, B.ff, B.b)

console.log(A.f, A.ff, B.f, B.ff, B.b) // [LOG]: "f",  "ff",  "f",  undefined,  "b" 

```

The enum `A` has been merged by two declarations. But the spread happened before the second declaration.
As the result. B does not has 'ff' in runtime.
BTW: access enum member before the second declaration is also `undefined`. 

I don't have background about that. So is that expected behavior?

If not. I'd like to propose disallow spread if any enum declaration below of the current one.

**Comment by Kingwl** [comment]
Well. It's seems incorrect implements. 

It's maybe should be handled as `lateBound`?

**Comment by Kingwl** [comment]
Passed all tests in my pc so.

@typescript-bot pack this.
@typescript-bot perf test.

**Comment by Kingwl** [comment]
seems basicly works.

It's time to add some additional check.

**Comment by Kingwl** [comment]
There's another issue: 
What should we do in d.ts?

If we downgrade into enum member. It's will not assignable for each other.

**Comment by Kingwl** [comment]
We need better diagnostics for overlap member or self reference.

**Comment by Kingwl** [comment]
@typescript-bot pack this.
@typescript-bot perf this.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
@typescript-bot pack this.
@typescript-bot perf test.

**Comment by nraskoti92** [comment]
Hi, any plans on merging this PR soon?

**Comment by Kingwl** [comment]
> Hi, any plans on merging this PR soon?

Nope.

**Comment by sandersn** [comment]
This experiment is pretty old, so I'm going to close it to reduce the number of open PRs.

**Comment by onevetka** [comment]
The problem is still relevant

**Pull request closed without merging**
