### PR TITLE
lint all files before reporting a failure

### LINKED ISSUE #5873: Make linter report errors on all files instead of one file at a time
That way you don't have to run the linter until you hit a fixed point.

@weswigham

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #5873

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
:+1: once Travis signs off

**Comment by mhegazy** [comment]
:+1:

**Comment by vladima** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
Have to award @weswigham :100: :trophy: for setting the record for "Least time between when Ryan complained about something and when a PR was submitted"

**Pull request merged**
