### PR TITLE
fix(lib): Loosen `Array` predicate return types

### LINKED ISSUE #27496: Array functions taking predicates should not have to return boolean.
## Search Terms

predicate find force boolean

## Suggestion

As per #5850 `array.prototype.filter` doesn't enforce `boolean` as a return type anymore. I want to propose the same behavior for wherever a predicate is needed. This means not only `filter`, but `find`, `some`, `every `and maybe others. These functions should not enforce boolean as return type of the predicate passed to them.

## Use Cases

This will be useful wherever the developer is looking for a result that is not missing some value(s).

## Examples

Say I want to find the first `parkSpace` that has `position`. This works in TypeScript 3.1.1:
`this.selectedParkSpace = this.parkSpaces.filter(o => o.position)[0] || null;`

but this doesn't:
`this.selectedParkSpace = this.parkSpaces.find(o => o.position) || null;`

For the latter, TypeScript complains:
> Type 'undefined' is not assignable to type 'boolean'.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

### PR DESCRIPTION
**Pull request by ExE-Boss**
Note that most `ReadonlyArray` predicates are already defined to return `unknown`:
https://github.com/Microsoft/TypeScript/blob/6487d1ffe0d903b1e55a187ddeb973fe0d445a2f/src/lib/es5.d.ts#L1117 https://github.com/Microsoft/TypeScript/blob/6487d1ffe0d903b1e55a187ddeb973fe0d445a2f/src/lib/es5.d.ts#L1123 https://github.com/Microsoft/TypeScript/blob/6487d1ffe0d903b1e55a187ddeb973fe0d445a2f/src/lib/es5.d.ts#L1147

Fixes #27496

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
RWC looks good, this just needs baseline updates

**Comment by RyanCavanaugh** [comment]
@typescript-bot run dt

**Comment by ExE-Boss** [comment]
Well, I can’t reproduce the Travis failure locally and it’s related to type generation, which was just removed in #31075.

**Pull request merged**
