### PR TITLE
Run eslint at root, rather than on src and scripts individually

### PR DESCRIPTION
**Pull request by jakebailey**
This is slightly faster (a few seconds) in my testing (average of 5 runs, without cache).

It'd probably be best to delete the individual tasks, but I don't know who depends on those directly besides our `package.json` scripts.

### CODE REVIEW

**Comment by jakebailey** [comment]
Thinking about it, I can't imagine anyone calls the other tasks; I could just make all of them call the one `lint` task instead.

**Comment by andrewbranch** [comment]
I have a vague recollection that maybe these were separated in order to have separate cache files? But it seems like separating scripts (very small) from compiler (very large) would have minimal utility on that front. I might be thinking of something else. @weswigham probably remembers.

**Comment by weswigham** [comment]
🤷‍♀️ That's the best answer I have, too. Iirc, I think they had different rules enabled, too, since we didn't have most semantic lints enabled for scripts, but did for the compiler at some point.

**Comment by jakebailey** [comment]
They do have different rules enabled, but as far as I can tell, eslint fully understands nested configurations by looking up the file system tree; I tested things out by introducing lint errors in both places, and it behaved as expected.

**Review by sheetalkamat — APPROVED** [review]

**Review by weswigham — APPROVED** [review]
Probably also still separate tasks from when it was tslint, which, afaik, only supported one config per invocation.

**Comment by jakebailey** [comment]
Ah, makes sense. 

Any opinions on whether or not I just delete the old tasks? I'm not sure anyone is running them directly.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by weswigham** [comment]
I only run `gulp lint`, personally.

**Comment by DanielRosenwasser** [comment]
I run `gulp runtests-parallel` and when the tests start passing I stage my changes, commit, push, and then see lint failures immediately after pushing or in CI, personally.

**Comment by jakebailey** [comment]
Cool. I'll just delete the other sub-tasks and if someone ends up wanting them, they are easy enough to restore.

**Pull request merged**
