### PR TITLE
DOM update 2023-04-23

### LINKED ISSUE #52956: `lib.d.ts` Updates for TypeScript 5.1
Including

* https://github.com/microsoft/TSJS-lib-generator/
* Outstanding `lib.d.ts` PRs to TS

### PR DESCRIPTION
**Pull request by sandersn**
Addresses #52956, at least for the DOM part.

I'm scrolling through all 10,000 lines of additions, but so far there are only or two minor changes besides the addition of MDN links to everything.
After seeing how slow jsdoc parsing is, I'm not 100% happy about this, but I think we should (1) run perf tests (2) take this for the beta (3) if the perf tests are horrendous or we think of some other reason, consider reverting the typescript-dom-lib-generator PR.

The most interesting non-comment change is the removal of `type BitrateMode = "constant" | "variable";` in favour of VideoEncoderBitrateMode. A couple of new types/interfaces got added as well.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot run dt
@typescript-bot user test this

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
You'll want to drop the "fixed" from the description as GitHub will close the issue on merge.

**Comment by sandersn** [comment]
Swapped in a highfalutin' substitute.

**Comment by sandersn** [comment]
xstate/material-ui getting only 1% slower is a pretty good outcome actually. I guess my optimisation of parsing of comment text paid off.

**Pull request merged**
