### PR TITLE
Add restrictions to IsGlobalCompletion

### PR DESCRIPTION
**Pull request by jramsay**
JS/TS snippets are showing up in undesirable locations in VS
ex:  import { | } from "./files1"

Restrict IsGlobalCompletion to:
- SourceFile
- Template Expression
- Statements

### CODE REVIEW

**Comment by jramsay** [comment]
// cc: @mhegazy, @vladima , @billti

**Comment by billti** [comment]
Looks good. 👍 

What's the behavior on JSX elements and expressions? The tests only cover attributes? (Is this covered elsewhere?)

**Comment by DanielRosenwasser** [comment]
Why `TemplateExpression`?

**Comment by jramsay** [comment]
@DanielRosenwasser: the completion list for template expressions is the global completion list so thought it made sense to insert snippets here as well.

**Comment by DanielRosenwasser** [comment]
@jramsay in the textual contents itself it makes sense to provide something like, let's say, an Angular template - but in those cases, you don't have a `TemplateExpression`, you have a `NoSubstitutionTemplateLiteral`. A `TemplateExpression` is a template string with embedded expression.

**Comment by jramsay** [comment]
As per discussion with @DanielRosenwasser & @billti — keeping TemplateExpression and adding JsxExpression

**Pull request merged**
