### PR TITLE
Don’t mix in base constraint completions on indexed access types with type parameter index types

### LINKED ISSUE #35702: Properties in object literal key completion list aren't filtered when a prior argument supplies a mapped type key
- VSCode Version: 1.41.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

\>\> [Playground Link](https://www.typescriptlang.org/play/index.html?ssl=23&ssc=1&pln=19&pc=1#code/JYOwLgpgTgZghgYwgAgMIFcDOYD2BbAUQBsI8JxNkBvAWAChlHkByBfABxxHLAFouIzAFzV6Tcchg4cAfhHYooAOYBuMUwC+AGnWNWHAeF5gA7jmGiGExgCM4UOcgXK1Vxhvoe69UJFiIUAHl2MGAuTAAeABVkCAAPSBAAE0oAawgATxwYNCxcQhIyCgA+S3F2KBx2TBEMbHxiUh5MAG0ogF1XL3oYdBAEUK5kBCgIOEho2ITyFOR0rJy6-MaisExigAoQODIRKK1kKsGQGuRg48io4oBKMqZRsHQoEGpkbbIDo7CT5A0u+noIzGkA2+jwnG4RgEzAOVGQFSqpzhv1+11cgPCYEOIVO52+kTBEJ4-G4zFKAF47owEdURMivF4gA)

```ts
interface CustomElements {
    'component-one': {
        foo?: string;
    },
    'component-two': {
        bar?: string;
    }
}

interface Options<T extends keyof CustomElements> {
    props: CustomElements[T];
}

function create<T extends keyof CustomElements>(name: T, options: Options<T>) {
    return { name, options };
}

create('component-one', { props: { /* trigger intellisense here */ } });

const opts: Options<'component-one'> = {
    props: { /* and here */ }
}
```

The type of `props` in the `create` call is correctly narrowed down to `CustomElements['component-one']` by the type system, however Intellisense suggests the props of all fields of `CustomElements`:

This does not happen when creating an object of that type:

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by andrewbranch**
Recall #30507, trying to get completions at a position like:

```ts
function f<T extends { x?: string }>(p: T) {}

f({ /**/ });
```

Since an empty object satisfies the constraint `{ x?: string }`, `T` is inferred as an empty object, and therefore getting members of the contextual type at that position yields an empty list. So in #32100, #33937, and #34855, we started instantiating `f`’s call signature with its constraint, getting the type of the argument in that signature, and mixing in properties from that type into the completions list.

Unfortunately, that had some unintended side effects when the signature’s parameter types have a non-linear relationship with a type parameter included in the signature, like conditional types and indexed access types that reference one of the type parameters. In real-world complaints from users, every case I’ve seen has been an indexed access type where the index type is a type parameter:

```ts
type Colors = {
  rgb: { r: number, g: number, b: number };
  hsl: { h: number, s: number, l: number }
};

function createColor<T extends keyof Colors>(kind: T, values: Colors[T]) {}

createColor('rgb', {
  /* oh nooo, I get completions for r, g, b, h, s, and l! */
});
```

In these cases, having more options is wrong and annoying.

This PR special-cases indexed access types where the index type is a type parameter of the contextual-type-providing signature (with some wiggle room to look past unions and intersections and conditional types).

It’s a band-aid fix, but a) I have spent several days trying to think of something better that’s not wildly expensive, and b) it covers the only failure case that people have actually complained about. That said, I don’t love this and am open to suggestions.

Fixes #35702, #36025

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
> It’s a band-aid fix

Not convinced that it is "wrong" to do 😄

**Comment by andrewbranch** [comment]
Nor am I; I just suspect that a being with 5x my intelligence and 10x my time could probably find a better way.

**Comment by weswigham** [comment]
Hrmmm, so hear me out here - our primary consideration is contextually typed object literal completions; specifically `f({/**/})` when `f<T extends {x?: number}>(x: T)`, while _not_ mucking up `f('a', {/**/})` when `f<T extends 'a' | 'b'>(x: T, y: { a: {a}, b: {b} }[T])`. What if we had a mode where if the instantiated type is a subtype of the uninstantiated apparent type (so in the second case, we'd check if `{}` is a subtype of `{a} | {b}`, which it isn't.), we pick the uninstantiated apparent type, otherwise we take the instantiated type? Inference is going to select either an assignable parameter or the base constraint, so if the parameter is assignable, but _not_ a subtype of the base constraint, then it seems reasonable to use the base constraint for completions instead (since the assignable parameter type is likely missing members).

**Comment by andrewbranch** [comment]
@weswigham I looked into either an assignability- or subtype-based approach several months ago, and IIRC, it didn’t work because of how either optional properties or excess properties are treated... but it’s been too long for me to remember specifically why it didn’t pan out.

**Comment by weswigham** [comment]
Ofc, there's still the possibility of something even more complicated like
```
f<T extends 'a' | 'b', U extends {a?: string}, V extends {b?: string}>(x: T, y: { a: U, b: V }[T]);
```
where the desired completions for `f('a', {/**/})` is `a`, from `{a?: string}` which is neither the inferred type at that position, nor the base constraint of the parameter at that position.

So, thinking out loud here, maybe the problem is attempting to do this with instantiated vs base constraint - with the example above, it seems more like we want to do inference to produce an instantiated signature, but ignoring the parameter we're editing...

**Comment by andrewbranch** [comment]
I also think that by the nature of completions, you might get too many false negatives to use type relations—e.g., inference picks the best candidate, but you haven’t yet typed some remaining required members, so the object as it stands now is not assignable/subtype of _anything_ relevant.

**Comment by andrewbranch** [comment]
The best way I’ve been able to think about when you _want_ base constraint completions on an object literal is _when the object literal affects the inference of its own type_. But, that reasoning may still not be quite right, and moreover I couldn’t find a way to _know_ that.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by weswigham** [comment]
@andrewbranch try out my build [here](https://github.com/weswigham/TypeScript/commit/d08ae97ae0db20f84a813c41bcdc2ff390dd3677). It seems to do what we want and isn't too jank about it.

**Comment by andrewbranch** [comment]
@weswigham it doesn’t work when the type parameter has already been inferred because of a different property on the same object argument:

image

**Comment by weswigham** [comment]
Hm, yeah, eliding the whole argument while looking for the properties of a nested literal would have that effect. I think the targeted thing we want is eliding _just_ the `{}` we're looking for the contextual type of from the inference process.

**Comment by andrewbranch** [comment]
I’m not sure that’s sufficient either. My example is trivially changed to

```ts
type X = { a: { a }, b: { b } }

function f<T extends 'a' | 'b'>(p: { kind: T } & X[T]) {}

f({
  kind: "a",
  /**/
})
```

**Comment by weswigham** [comment]
@andrewbranch Or rather, we want to block making inferences to the targeted `{}` as a whole, not to individual members.

**Comment by weswigham** [comment]
@andrewbranch I have a prototype of the idea [here](https://github.com/weswigham/TypeScript/commit/d4848aa4dfd19bd7bf900c6629955ab8d936a0b8). It needs to cache a little bit more safely (probably by cloning node trees like my prior attempt did), but directly forbidding inference from occurring on exactly the target expression seems to do the trick.

**Comment by andrewbranch** [comment]
@weswigham I tried out that commit. There are a couple failing tests, and I’m a little lost as to what’s happening in `inferTypes`. The simplest of the failures is this:

```ts
interface MyOptions {
    hello?: boolean;
    world?: boolean;
}
declare function bar<T extends MyOptions>(options?: Partial<T>): void;
bar({ hello: true, /*1*/ });
```

When you have an empty object at the call site `bar({ /**/ })`, both `hello` and `world` are offered 👍. But once the object has either `hello` or `world`, no more completions are shown 👎. I debugged these cases, and neither one hits `inferTypes` when `isFromInferenceBlockedSource` returns true, so I’m a little confused why one works and the other doesn’t.

There’s a more complicated one with some _really_ strange behavior:

```ts
interface Test {
  keyPath?: string;
  autoIncrement?: boolean;
}

function test<T extends Record<string, Test>>(opt: T) { }

test({
  a: {
    keyPath: 'x.y',
    autoIncrement: true
  },
  b: {
    /**/
  }
})
```

As written, you get no completions inside `b`. If you comment out `a`’s contents or the property declaration of `a` entirely, you still get no completions. _But_, if you make `a`’s type an _error_, by e.g. changing `keyPath` to a number, completions appear in `b`. 🤔

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by weswigham** [comment]
> The simplest of the failures is this

I looked over it; it's because we don't do a direct inference from the object literal type to `Readonly<T>`, since it's a mapped type - we construct a reverse mapped type around the object literal and the infer _that_ to `T`. We just need to carry the flag from the literal into the reverse-mapped type we construct (or just check for the flag before we even bother making the reverse mapping).

> There’s a more complicated one with some really strange behavior:

Ahh, neat; looks like we need to block inference to all object (and array) literals up the spine between the expression under inspection and the surrounding call like expression, too. (Since if we lock in one of their types, we'll lock in the type of the child expression we want to ignore)

> I tried out that commit. There are a couple failing tests

I hadn't looked at any yet, since I was just sketching how we might be able to solve the problem, but with the latest revision on that branch, I have, and they now all pass (seems like they just needed the fixes for the two things you brought up, I guess). I've taken the liberty of adding fourslash tests to that branch, too (since debugging a fourslash test is way easier than an editor).

**Comment by andrewbranch** [comment]
Superceded by #36556

**Pull request closed without merging**
