### PR TITLE
Fix devtools test

### PR DESCRIPTION
**Pull request by weswigham**
https://github.com/Microsoft/TypeScript/pull/20706 Made the declaration kinds handled by `getSymbolAtLocation` more explicit, but didn't include `Identifier`, which we have no normal tests covering. It being missing caused the test to trigger an assertion. Additionally, we made a change to the lib that slightly affects the baseline file.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
❤️

**Comment by leilaniwebcreation** [comment]
Fork me

**Comment by leilaniwebcreation** [comment]
Fork me

**Comment by leilaniwebcreation** [comment]
Fork me

**Pull request merged**
