### PR TITLE
Don't report unused diagnostics when the unused node has a parse error

### LINKED ISSUE #25591: Extra reportsUnnecessary suggestions for syntactically invalid file
From https://github.com/Microsoft/vscode/issues/52346

**TypeScript Version:**  3.0.0-dev.20180706

**Search Terms:** 
- reportsUnnecessary
- diagnostics 
- suggestions

**Code**
For the invalid code: 

```ts
export const _ = 1;

const a = 1 d;
```

**Bug**
See a suggestion diagnostic: 

```
  {
            "start": {
                "line": 3,
                "offset": 1
            },
            "end": {
                "line": 3,
                "offset": 15
            },
            "text": "All variables are unused.",
            "code": 6199,
            "category": "suggestion",
            "reportsUnnecessary": true
        }
```

This causes the entire line to become faded out. I do not believe we should report these errors when there are syntax errors

### PR DESCRIPTION
**Pull request by ghost**
Fixes #25591

### CODE REVIEW

**Comment by andy-ms** [comment]
Waiting for @mjbvz to verify

**Comment by mjbvz** [comment]
@andy-ms I'm still see the diagnostics when using the TS version from this PR, at least for the cases in #25591

**Comment by andy-ms** [comment]
Here's what it looks like to me:

`typescript@next`:
next

`jake local` on the `noSuggestionDiagnosticsOnParseError` branch:
branch

**Comment by mjbvz** [comment]
@andy-ms You're right. I ran the wrong build command. Seems to be working well. I haven't notice any flickering or other odd behavior in my testing

**Pull request merged**
