### PR TITLE
doc: fix typo 'BankAccount'

### PR DESCRIPTION
**Pull request by zhongsp**
Fix a typo in TypeScript Language Specification word docs. Regenerate the spec.md file.

### CODE REVIEW

**Comment by mhegazy** [comment]
thanks @zhongsp. this file is generated from the word doc. can you update that one and run `jake generate-spec`

**Comment by zhongsp** [comment]
@mhegazy Thanks for your review. I've updated the code as your introduction.

**Comment by DanielRosenwasser** [comment]
@mhegazy did we confirm that running the markdown converter yields the same document?

**Comment by mhegazy** [comment]
yup.

**Pull request merged**
