### PR TITLE
Optimize deferred type references

### LINKED ISSUE #36566: Performance regressions from recursive type reference support
The extra work done in #33050 and follow-up PR #33678 is valuable, but maybe it doesn't need to be so expensive.

Setup: 

1. Clone https://github.com/amcasey/material-ui.git
2. Check out Benchmark
3. `yarn` to restore packages
4. `yarn typescript` to prebuild and run some TS tests

Repro

1. `tsc -p docs`

On a random Mac Mini:

For #33050
- 10-run avg on https://github.com/microsoft/TypeScript/commit/4ee251b053eb2d419ce5304b309c5e4e1cd7ad1c: 33,685ms
- 10-run avg on https://github.com/microsoft/TypeScript/commit/250d5a8229e17342f36fe52545bb68140db96a2e: 34,223ms (2% slower)

For #33678 
- 10-run avg on https://github.com/microsoft/TypeScript/commit/7f3c03d4414939bb48758c0f957babed830df48c: 34,403ms
- 10-run avg on https://github.com/microsoft/TypeScript/commit/7ce793c5b8c621af5ce50af0ca3958c7bd6541bf: 35,488ms (3% slower)

_Note_: to build old TS commits, you probably need to change `const { default: chalk }` to `const chalk` in `scripts/build/utils.js`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR improves our reasoning about when to (and, more importantly, when not to) create deferred type references. We now create fewer deferred type references which improves overall compile times for the repro in #36566 by around 4%.

Fixes #36566.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
Tests look clean. Only change is a minor type ordering difference in a few error messages in RWC.

**Comment by amcasey** [comment]
10-run average from the original machine shows a 5% improvement. Very nice!

**Pull request merged**
