### PR TITLE
Don’t auto-import paths that are in a referenced project’s outDir

### LINKED ISSUE #38856: auto-import favors import from target instead of source
**TypeScript Version:**  4.0.0-dev.20200529
Verify no issue with vs code version 1.45.1 + typescript vsrion: 3.8
Verify issue with vs code + typescript 3.9.3
still have issue with vs code + typescript 4.0.0-dev20200529

**Search Terms:** 
import / auto import
**Code**
we have project configure as
```
|
|-- sharedlib
       | -- src
       | -- dist
|-- package1
       | -- src
       | -- dist
|-- package2
       | -- src
       | -- dist
```
where src is *.ts source code, dist is where compiled *.js files

sharedlib/tsconfig.json

```json
{"compilerOptions": {
    "rootDir": "./",
    "baseUrl": ".",
    "outDir": "dist",
    "paths": {
      "*": [
        "types/*"
      ]
    },
    "composite": true
  },
  "include": [
    "src/**/*.ts",
  ]
}
```
package1/tsconfig.json

```json
{"compilerOptions": {
    "baseUrl": ".",
    "outDir": "dist",
    "rootDir": "./",
    "paths": {
      "*": [
        "../sharedlib/types/*"
      ],
      "sharedlib": [
        "../sharedlib"
      ]
    },
  },
}
```

sharedlib/src/foo.ts
```ts
export const foo = 1
```
package1/src/bar.ts
```ts
console.log(foo)
```
**Expected behavior:**
When in visual studio code + typescript 3.8
auto import will prompt me to import as 
```ts
import foo from 'sharedlib/src/foo'

console.log(foo)
```

**Actual behavior:**
On typescript 3.9.3+
first, before compile sharedlib, it can't recognize foo, thus no auto import
after compile, it auto import the js from
```ts
import foo from 'sharedlib/dist/src/foo'

console.log(foo)
```

the problem are 
1.  now when I add new exportable in sharedlib, I have to compile the package first before I am write reference code from other packages
2.  Because code write before/after ts 3.9 are import from different path even for same module, javascript will treat they as different modules, thus breaks states/singleton, if I didn't manually remove /dist from import

**Playground Link:**  

**Related Issues:**

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #38856 

We started getting auto-imports from referenced project `outDir`s due to #37482. We _do_ potentially need to look in `outDir` because the result could be the `typings` or `main` entry of the project’s `package.json` (which would be referenced in symlinked monorepo setups), in which case the resulting module specifier would be the bare non-relative package name. But if that file does _not_ match the `typings` or `main` entry (or cannot be referenced through node_modules), we don’t want to use that file as a possible path to import, and we certainly don’t want it to crowd out the non-redirect source file.

### CODE REVIEW

**Comment by andrewbranch** [comment]
The failing unit tests make me want to refactor this further. We throw away too much info in `getAllModulePaths` and `forEachFileNameOfModule`. Converting this to draft, don’t bother reviewing yet.

**Comment by sheetalkamat** [comment]
But is this really intended behaviour? In real scenario (non editing) the package will still use outDir and not source.. And normal build will use `.d.ts` files instead of source files(source files from project reference are used only to give better editing experience) so why is `ref/src/a` better than `ref/dist/a`

**Comment by andrewbranch** [comment]
Really, it depends on the referenced project’s `rootDir` _and_ what folder they plan to publish to a package registry. We can’t know the latter, so the truth is that we don’t know for sure what path will be correct at runtime. My own conventions would lead me never to create a system where I explicitly import from `dist`, but probably not everyone shares those conventions. We could offer both paths as suggestions, but that could get frustrating, as people will consistently want only one of the two suggestions, and the presence of the other will slow them down and _feel_ like a bug.

**Comment by sheetalkamat** [comment]
Well from package point that may be true but from project references stand point the output is what matters (since you dont want to include the source file in your build) and hence i am not sure offering "src" vs "dist" is improvement.

**Comment by andrewbranch** [comment]
That depends on the relationship between the `outDir` of the importing file and the `outDir` of the imported file. Consider this non-monorepo project references scenario:

```
src/
  a/
    tsconfig.json - outDir: ../../out/a
    index.ts
  b/
    tsconfig.json - outDir: ../../out/b
    index.ts

out/
  a/
    index.js
    index.d.ts
  b/
    index.js
    index.d.ts
```

Because the `outDir`s of the two projects have the same relationship as the `rootDir`s, it’s safe and conventional to write imports from `a` to `b` as `import { B } from "../b";`. But as of #37482, you get two suggestions:

image

I can’t see any reason why you would ever want the latter. It’s not wrong on disk now, but what happens if you use `out` as the context for a Docker build, copying files to a container image? That image will be broken unless the working directory on the container is also named `out`. These module specifiers aren’t portable.

**Comment by bradennapier** [comment]
Running into this as well - https://github.com/microsoft/vscode/issues/103087

https://github.com/bradennapier/typescript-auto-import-bug

auto import completely broken

**Comment by andrewbranch** [comment]
This is superseded by #40253

**Comment by dko-slapdash** [comment]
@andrewbranch So this is like a broken change in comparison to v3.9 if I understand correctly, right?

In monorepo setup (e.g. lerna & yarn workspaces), e.g. packages/shared is auto-symlinked to node_modules/shared. So in src+dist configuration, it's actually desired that IntelliSense suggests importing from shared/dist/ and not from shared/src/ - otherwise the paths won't just work at runtime.

I posted some details here: https://github.com/microsoft/TypeScript/issues/34677#issuecomment-732756179

The screenshot with an illustration on when it's desired to import from outDir packages/shared/dist/ is following:

image

**Comment by andrewbranch** [comment]
This didn’t get merged, so I would say it’s not a breaking change?

**Comment by dko-slapdash** [comment]
> This didn’t get merged, so I would say it’s not a breaking change?

This effect is reproducible on v4.x (e.g. on 4.0, on 4.0-beta etc.) too. So it's here for quite some time.

**Comment by andrewbranch** [comment]
The effect of this PR is _not_ reproducible in _any_ TypeScript version because it is not part of TypeScript. It was an experiment that failed and did not get merged. You may need to set up `paths` to ensure the auto-import behavior you’re looking for. Please read the description of #40253 (beginning at the “Background” heading) for more info. Feel free to ask follow-up questions on that PR, since that one was actually merged.

**Pull request closed without merging**
