### PR TITLE
feat(16656): `as tuple` type assertion

### LINKED ISSUE #16656: suggestion: explicit "tuple" syntax
### Problem

I'm writing this after encountering (what I think is) #3369.  I'm a noob to TS, so I apologize for any misunderstandings on my part.  The behavior the lack of type inference here:

```typescript
interface Foo {
  bar: [number, number];
}

interface McBean {
  baz: Foo;
}

// error: McMonkey does not implement McBean
class McMonkey implements McBean {
  baz = {
    bar: [0, 1]
  };
}

// vs

// no error
class McMonkey implements McBean {
  baz: Foo = {
    bar: [0, 1]
  };
}
```

Because array literals are (correctly) inferred to be arrays, TS is limited in what it can infer.  This means there's an added overhead to working with tuples, and discourages use.  

As I see it, the problem is that a tuple is defined using array literal notation.

### A Conservative Solution

Adding a type query (?) such as `tuple` (.e.g `tuple`) would be better than nothing:

```typescript
class McMonkey implements McBean {
  baz = {
    bar: <tuple [number,number]> [0, 1]
  };
}
```

...but this is still clunky, because you'd have to use  it just as much as you'd have to explicitly declare the type.

### A Radical Solution

There's a precedent (Python) for a tuple syntax of `(x, y)`.  Use it:

```typescript
interface Foo {
  bar: (number, number);
}

interface McBean {
  baz: Foo;
}

class McMonkey implements McBean {
  baz = {
    bar: (0, 1)
  };
}
```

#### Obvious Problem

The [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator) is a thing, so `const oops = 0, 1` is valid JavaScript.  `0` is just a noop, and the value of `oops` will be `1`.  Python does not have a comma operator (which is meaningful in itself).  

I've occasionally used the comma operator in a `for` loop, similar to the MDN article.  Declaring `var`'s at the top of a function is/was common:

```js
function () {
  var a, b, c;
}
```

Parens are of course used in the syntax of loops and conditionals, as well as a means of grouping expressions.

A nuance of Python's tuples are that they *must* contain at one or more commas, which *could* help: 

```python
foo = (0) # syntax error
foo = (0,) # valid tuple
```

...or it could actually make matters worse, because `(0, )` is an unterminated statement in JavaScript.

That all being said, using the suggested Python-like syntax, it seems *difficult* but *possible* for the compiler to understand when the code means "tuple" vs. when it doesn't.  

* * *

I'd be behind any other idea that'd achieve the same end.  I don't know how far TS is willing to diverge from JS, and I imagine significant diversions such as the above are not taken lightly.

(I apologize if something like this has been proposed before; I searched suggestions but didn't find what I was looking for)

### LINKED ISSUE #27179: Add a way to prefer narrowing array to tuple if possible
## Search Terms

tuple narrow, prefer tuple

## Suggestion

This is a meta-suggestion over the top of some of the cases in #16896 and #26113, basically at current it's quite repetitive to specify overloads for tuple types and we tend to wind up things like this:

```ts
// etc up to how ever many overloads might be needed
function zipLongest<T1, T2, T3, T4>(
  iterables: [Iterable<T1>, Iterable<T2>, Iterable<T3>, Iterable<T4>]
): Iterable<[T1, T2, T3, T4]>

function zipLongest([]): []
function zipLongest<T>(iterables: Array<Iterable<T>>): Iterable<Array<T>>
```

We can already specify the type if we know only tuples are going to be input e.g.:

```ts
type Unwrap<T> = T extends Iterable<infer R> ? R : never
type ZipUnwrapped<T> = { [P in keyof T]: Unwrap<T[P]> }

declare function zipLongest<Ts extends Array<Iterable<any>>>(iterables: Ts): Iterable<ZipUnwrapped<Ts>>

const strs = ['foo', 'bar', 'baz', 'boz']
const nums = [1, 2, 3, 4]
const zipPair: [string[], number[]] = [strs, nums]
const z = zipLongest(zipPair)
```

In this case the type of `z` is correctly inferred to be `Iterable<[string, number]>`, but if we remove the type declaration on `zipPair` then we get that the inferred type of `z` is `Iterable<(number | string)[]>`.

Basically what I propose is adding some way to specify that an array should be narrowed to the most precise tuple possible if we can.

There's a couple approaches that might be used:

###### Approach 1

Use the `[...TupleParam]` spread syntax already mentioned in #26113 and when this syntax is seen narrow to the best tuple we could get. So the above declaration would become:

```ts
// The only difference is iterables: Ts has become iterables: [...Ts]
declare function zipLongest<Ts extends Array<Iterable<any>>>(iterables: Ts): Iterable<ZipUnwrapped<Ts>>
```

This has the downside that it might for any `Ts` in `[Some, Tuple, Params, ...Ts]` to be narrowed even when the wider type was what was intended.

##### Approach 2

Add some new syntax that specifies that if a certain value can be narrowed into a tuple then we should do so:

```ts
// Arbitrary syntax 1
declare function zipLongest(
  iterables: [...tuple Ts]
): Iterable<ZipUnwrapped<Ts>>

// Arbitrary syntax 2
declare function zipLongest<Ts extends [!...Iterable<any>]>(
  iterables: Ts
): Iterable<ZipUnwrapped<Ts>>
```

The syntax isn't really all that important. The main downside of this approach is that we need two overloads, one for the narrowed tuple and one for the non-narrowed tuple. Additionally extra syntax would need to be supported and maintained.

## Examples

Other than the above example another example that would benefit is the builtin `lib.promise.d.ts` which specifies overloads in this repetitive overloading pattern.

We could write something like `Promise.all` like so:

```ts
type UnwrapMaybePromiseLike<T>
= T extends PromiseLike<infer R> ? R : T

type UnwrappedArray<T extends Array<any>> = {
    [P in keyof T]: UnwrapMaybePromiseLike<T[P]>
}

interface PromiseConstructor {
    all<Ts extends Array<any>>(
        promises: [...Ts]
    ): UnwrappedArray<Ts>
}
```

And inference would just work.

```ts
// a would inferred to be [number, number]
const a = Promise.all([1, 2])

// b would be inferred to be [string, number]
const b = Promise.all(['foo', Promise.resolve(12)])
```

## Checklist

My suggestion meets these guidelines:
* [?] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [✔] This wouldn't change the runtime behavior of existing JavaScript code
* [✔] This could be implemented without emitting different JS based on the types of the expressions
* [✔] This isn't a runtime feature (e.g. new expression-level syntax)

EDIT: Realized `Promise.race` was supposed to be `Promise.all` oops.

### LINKED ISSUE #29163: Array Type Inference
**TypeScript Version:**  3.3.0-dev.20181222

**Search Terms:**
- array
- type
- inference
- index

**Code**
[Playground Link](http://www.typescriptlang.org/play/#src=const%20typed%20%3D%20%5B'a'%2C%201%5D%20as%20%5Bstring%2C%20number%5D%3B%0D%0Atyped%5B0%5D.length%3B%20%2F%2F%20Works%0D%0Atyped%5B1%5D.toPrecision()%3B%20%2F%2F%20Works%0D%0Atyped%5B2%5D%3B%20%2F%2F%20Errors%20as%20expected%0D%0A%0D%0Aconst%20array%20%3D%20%5B'a'%2C%201%5D%3B%0D%0Aarray%5B0%5D.length%3B%20%2F%2F%20Error%0D%0Aarray%5B1%5D.toPrecision%3B%20%2F%2F%20Error%0D%0Aarray%5B2%5D%3B%20%2F%2F%20Should%20error)
```ts
const typed = ['a', 1] as [string, number];
typed[0].length; // Works
typed[1].toPrecision; // Works
typed[2]; // Errors as expected

const array = ['a', 1];
array[0].length; // Error
array[1].toPrecision; // Error
array[2]; // Should error
```

**Expected behavior:**

TypeScript infers type of `array` as `[string, number]`.

**Actual behavior:**

TypeScript infers type of `array` as `(string | number)[]`.

**Related Issues:** 
#25516

### LINKED ISSUE #48052: Syntax for explicit tuple literal type
# Suggestion

Though closely related to #10195 and #16656, I am opening this issue because the proposed syntax, purpose and demonstration are different.

## Motivation

Previously I wrote [a library](https://www.npmjs.com/package/ndarray-methods) that manipulates nested arrays:
```ts
import NDArray from "ndarray-methods";

NDArray.buildShape([2, 3], 0) // [[0, 0, 0], [0, 0, 0]]
// Works like Python’s numpy.zeros()
```
But without tuple its type is being inferred as `NDArray<number>`, of which `NDArray` is defined as
```ts
type NDArray<T> = (T | NDArray<T>)[]
```

## The Problem
I know there are at least 3 ways to cast it as a tuple:
```ts
/* 1 */ NDArray.buildShape([2, 3] as const, 0)            // constant tuple
/* 2 */ NDArray.buildShape([2, 3] as [number, number], 0) // number tuple
/* 3 */ NDArray.buildShape(tuple(2, 3), 0)                // utility function
```
of which the `tuple` function is defined as
```ts
function tuple<T extends unknown[]>(...args: T) { return args; }
```
In these 3 cases, the program correctly infers the type of the results as `number[][]`.

But these 3 ways all have their problems:

For 1, it is not necessary to make the numbers constants.

For 2, we will have to write `number,` many times for higher-dimensional arrays (I know we can use a utility type, but I don’t think it’s desirable).

For 3, there are considerable runtime effects and it might cause serious performance problems, especially when it is transpiled down to something like
```ts
function tuple() {
  for (var a = [], i = 0; i < arguments.length; i++) a.push(arguments[i]);
  return a;
}
```
Also, in a module-based application, this utility function will have to be defined or imported before using, which pollutes the namespace.

Most importantly, for 1 and 2, we are using the `as` keywords, which is not favorable for TypeScript codes in general (and **ESLint gets angry** too).

I also know the existence of the [Record & Tuple Proposal](https://github.com/tc39/proposal-record-tuple), but since there will be compatibility problems in the near future, and people might not want to refactor the existing codes, the current tuple-like array will still be used by a significant amount of projects.

## Solution

In my opinion, a syntax without `as` like `tuple [2, 3]` should be created, or we should at least provide a way to let TypeScript infer a literal array as tuple for a certain function parameter.

## Prior Use

The tuple utility function is included in many repositories, and even in the release note:

- [Sourcegraph Search](https://sourcegraph.com/search?q=context:global+function+tuple%3CT+extends+any%5B%5D%3E&patternType=literal)
- [TypeScript 3.0 Release Note](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/release-notes/TypeScript%203.0.md#rest-elements-in-tuple-types)

### LINKED ISSUE #49414: `as tuple` type assertion modifier
# Suggestion

## 🔍 Search Terms

tuple casting assertion as modifier

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'm requesting to add an `as tuple` type assertion, similar to `as const`. I'm not sure about the syntax yet, since `tuple` isn't a reserved word and could break existing code, so I'm hoping someone has a better idea for naming. Additionally, we could add a property to `tsconfig` to allow `as tuple` assertions instead of enabling it by default.

`as const` doesn't work because that specifies too many declarations, makes arrays readonly, and locks the types of literal elements such as `23`.

## 📃 Motivating Example

Sometimes I store several variables in an array, but TypeScript infers an array type whereas I want a tuple type. To fix this, we could use the `as tuple` modifier.

```typescript
let mousePosition = [23, 56];
// The type here is `number[]`, not a tuple.

let mousePosition: [number, number] = [23, 56];
// Now we have the correct type, but too much code.

let mousePosition = [23, 56] as tuple;
// Beautiful!
```

Another example might be storing user data in an array because you don't want to use an object. In these cases, `as tuple` syntax could save time spent writing complex type declarations.

```typescript
let user = ["Steve", 45, "test@example.com"];
// No TypeScript, I don't want an (string | number)[].

let user = ["Steve", 45, "test@example.com"] as tuple;
// Amazing!
```

A `readonly` keyword could also be added to allow easier syntax for readonly tuples.

```typescript
let user: readonly [string, number, string] = ["Steve", 45, "test@example.com"];
// There isn't even a shortcut for this; you have to type everything.

let user = ["Steve", 45, "test@example.com"] as readonly tuple;
// Amazing!
```

This is also out of scope a bit, but named tuples would be nice, but I'm not sure how the syntax would work.

```typescript
let user = ["Steve", 45, "test@example.com"] as tuple of [name, age, email];
// The type of `user` is [name: string, age: number, email: string].

let user: [name: string, age: number, email: string] = ["Steve", 45, "test@example.com"];
// Too verbose!
```

## 💻 Use Cases

Currently, I manually specify types for these tuples, but it feels like it could be shorter at times. Here's an example from my [zSnout](https://github.com/zsnout/zsnout.com) project where I need to store the last two points the user touched.

```typescript
let lastTouchPointA: [number, number] = [NaN, NaN];
let lastTouchPointB: [number, number] = [NaN, NaN];
```

While writing this, I felt that there should be an easier way to write these tuples, but the current workarounds feel to verbose when I only need them for simple tasks.

### PR DESCRIPTION
**Pull request by graphemecluster**
Fix #16656
Fix #27179
Fix #29163
Fix #48052
Fix #49414

### CODE REVIEW

**Comment by Jack-Works** [comment]
I expect `tuple` used as the primitive type for tc39 proposal https://github.com/tc39/proposal-record-tuple

**Comment by graphemecluster** [comment]
@Jack-Works Yea but I can’t think of a word better than this. After all, at least for the time being, the term `tuple` is used exclusively to mean array with length boundary or mixed types in the current TypeScript codebase.

And there are actually no conflicts at all:
```ts
const a = ["foo", 42, true] as tuple; // [string, number, boolean]
const b = #["foo", 42, true]; // ESTuple<["foo", 42, true]>
```

**Comment by jakebailey** [comment]
There's no conflict as of now, but if `tuple` is defined as a primitive type, it would need to be able to be written in type assertions like `foo as unknown as tuple`, and that is definitely a conflict.

**Comment by graphemecluster** [comment]
@jakebailey But I guess you need some type parameters for the tuple type right?

… Anyway I’d like to ask what keyword would the Team prefer then?

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this PR since there's still design work to be done on the original issue.

**Pull request closed without merging**
