### PR TITLE
Fix import order

### PR DESCRIPTION
**Pull request by falsandtru**
Separated from #36368

### CODE REVIEW

**Comment by falsandtru** [comment]
```
/// <reference lib="es2015.promise" />
/// <reference lib="es2015.iterable" />

**Comment by falsandtru** [comment]
Note that the problem is that the order of overloads wrongly looks like

```ts
    race<T>(values: Iterable<T | PromiseLike<T>>): Promise<awaited T>;
    race<T>(values: readonly (T | PromiseLike<T>)[]): Promise<awaited T>;
```

from the current definition

```
/// <reference lib="es2015.generator" />
/// <reference lib="es2015.promise" />
/// <reference lib="es2015.iterable" />
```

but actually

```ts
    race<T>(values: readonly (T | PromiseLike<T>)[]): Promise<awaited T>;
    race<T>(values: Iterable<T | PromiseLike<T>>): Promise<awaited T>;
```

because es2015.generator loads es2015.iterable. This misleading confuses us.

**Comment by rbuckton** [comment]
This won't affect the resolution order, as the order is explicitly specified in commandLineParser.ts

**Comment by falsandtru** [comment]
This fix the definition order which doesn't match the resolution order.

**Comment by rbuckton** [comment]
The order they are specified in the lib files shouldn't matter in the slightest. The order they are loaded (and the order of the definitions) should come from the `libEntries` array in commandLineParser.ts. We did this explicitly so that it didn't matter what order you specify them in your `"libs"` or via `/// <reference />` directives so that we would preserve the correct ordering of overloads.

**Comment by falsandtru** [comment]
The current definition order sometimes confuses us as I mentioned at https://github.com/microsoft/TypeScript/pull/37510#issuecomment-602545912. And as you said "This won't affect the resolution order", you have no reason to keep the current definition order which doesn't match the resolution order.

**Comment by DanielRosenwasser** [comment]
I think we need this for the playground to generate a reasonable `lib.d.ts`.

@typescript-bot pack this
@typescript-bot cherry-pick this to release-3.9 and LKG

**Comment by DanielRosenwasser** [comment]
I agree that this list should at least strive to match the one that we reorder automatically. Not doing so has caused issues. Maybe the list should start with a leading comment.

**Comment by DanielRosenwasser** [comment]
It definitely matters. Just annoying that I have to redo the VS-side syncing now.

**Comment by DanielRosenwasser** [comment]
Thanks @falsandtru!

**Pull request merged**
