### PR TITLE
Switch imports back to case sensitive sorting

### LINKED ISSUE #51617: Restore case-sensitive import sorting
In #51579, I switched our sorting to be case insensitive, as sensitive sorting appeared to cause auto-imports to break.

This appears to be caused by #51616 (at least). After that's fixed, we could revert things.

Also, #51615, if we wanted to use `organize imports`, however that would be a problem regardless, but less of one given auto-imports should be able to put things in the right place. (Though, I'd rather just let a formatter do this for us.)

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #51617

As of the latest nightly VS Code TypeScript extension, we seem to handle things correctly.

### CODE REVIEW

**Comment by jakebailey** [comment]
If we also want Organize Imports to work, I can add in the necessary newlines or changes + eslint rule to enforce that, I was just trying to do more of a revert. But, I think people just want their editors to work better, so I can just add that change in here.

**Comment by jakebailey** [comment]
Ugh, can't even enable declaration sorting in ESLint because it requires you to also be picky about the _kinds_ of imports themselves:

image

Which, organize imports has no idea about. Would really just like to be using dprint to do this and leave eslint out of the picture.

**Comment by jakebailey** [comment]
eslint-plugin-import can do this, but, it also doesn't match organize imports.

**Comment by rbuckton** [comment]
Maybe we need an `eslint-plugin-organize-imports` that uses our logic.

**Comment by jakebailey** [comment]
At this point I am strongly preferring #52090.

**Pull request closed without merging**
