### PR TITLE
Fix indent

### PR DESCRIPTION
**Pull request by andy-ms**
Should be 4 spaces, not 3.

### CODE REVIEW

**Comment by mhegazy** [comment]
do we need to run [tsfmt](https://github.com/vvakame/typescript-formatter) on the whole code base? or just run it as a lint rule and ensure no edits result?

**Comment by alan-agius4** [comment]
I’d add ‘4’ in here https://github.com/Microsoft/TypeScript/blob/master/tslint.json

**Comment by andy-ms** [comment]
@alan-agius4 From https://palantir.github.io/tslint/rules/indent/ :
> Indentation size is required for auto-fixing, but not for rule checking.

So, it doesn't actually check for indentation amount.

**Comment by alan-agius4** [comment]
Thanks @andy-ms for the info😁

**Pull request closed without merging**
