### PR TITLE
Allow custom switch-case indentation in formatting

### LINKED ISSUE #18682: formatter: allow custom switch-case indentation
**TypeScript Version:**  2.5.2

**Code**

Format the following

```ts
switch (foo) {
case 'bar':
  break;
}
```

**Expected behavior:**

Keep it the same.

**Actual behavior:**

`case` is indented.

```ts
switch (foo) {
  case 'bar':
    break;
}
```

This becomes more problematic when used with tslint or javascript code with eslint, because on different systems we can see one winning over the other randomly i.e. sometimes the case is indented, sometimes it's not (eslint rule says do not indent).

### PR DESCRIPTION
**Pull request by donaldnevermore**
* [x] There is an associated issue in the `Backlog` milestone (**required**)
* [x] Code is up-to-date with the `main` branch
* [x] You've successfully run `hereby runtests` locally
* [x] There are new or updated unit tests validating the change

Added a new option `indentSwitchCase` in `FormatCodeSettings`.
Closes #18682

### CODE REVIEW

**Comment by donaldnevermore** [comment]
@microsoft-github-policy-service agree

**Comment by andrewbranch** [comment]
@donaldnevermore thank you! For tests, look at `tests/cases/fourslash/formatting*` and it should be fairly clear what to do.

**Comment by andrewbranch** [comment]
Awesome! The only thing left to do here is update the copy of `FormatCodeSettings` in `src/server/protocol.ts`.

After that, would you be up for opening the corresponding VS Code pull request similar to https://github.com/microsoft/vscode/pull/80828?

**Comment by donaldnevermore** [comment]
Done. But why are there 2 duplicate `FormatCodeSettings`?

**Comment by andrewbranch** [comment]
Looks like you need to update an API baseline again.

> But why are there 2 duplicate FormatCodeSettings?

protocol.ts is meant to be a standalone definition file for TS Server consumers (VS and VS Code build scripts copy it into their build, I think), so it has some tsserver-specific types and lacks a lot of compiler/LS types, but there is also a little bit of overlap that requires duplication. Probably these days we could find a smarter way to generate it, but nobody has touched it in ages.

**Pull request merged**
