### PR TITLE
fix-suggestions-ordering

### LINKED ISSUE #38743: "Import" suggestions should be before "Change spelling" suggestions
I face the following situation multiple times per day.
- Type some code.
- Variable is not defined/imported.
- Press ctrl+enter to trigger the quick fixes menu.
- "Change spelling" is always the first suggestion.
- Press down arrow and select the import suggestion.

image

**TypeScript Version:**  3.9.2, 4.0.0-dev

**Search Terms:**
Import, suggestion, spelling

I tried to google it, but I couldn't find any solutions.

**Code**

See the screenshot above.

**Expected behavior:**
The import suggestion should be the first entry in quick fixes.

**Actual behavior:**
The import suggestion is the last entry in quick fixes.

**Related Issues:** 
#23258 I think it broke it. Also please see the last comment, @krryan mentions the same problem.

### PR DESCRIPTION
**Pull request by snigui**
Fixes #38743

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Appears to be a fix for #38743?

You shouldn't need to change the error codes for this - the suggestion order, I believe, is the order they come back from the code, so the file ordering change alone should be enough.

**Comment by snigui** [comment]
okay! i did change "codefixes/importFixes.ts" to appear before "codefixes/fixSpelling.ts" in the services tsconfig.json. Would that be enough?

**Review by sandersn — CHANGES_REQUESTED** [review]
Did the change not make any existing tests fail? If so, can you make a test the fails before the change and passes after it?

**Comment by snigui** [comment]
there is no issue with ordering from typescript i think. tests\cases\fourslash\codeFixSpellingVsImport.ts passes the test where import comes before change spelling

**Comment by sandersn** [comment]
Thanks for checking this out for us. I manually reproduced that test case in emacs, which doesn't reorder codefixes, and import comes before changing spelling there too.

**Pull request closed without merging**
