### PR TITLE
Make lower priority inference when source is completely matched in target

### LINKED ISSUE #33131: RxJS type inference fails in 3.6.2
**TypeScript Version:**  3.6.2

**Search Terms:** type inference 3.6

**Code**
```ts
function asObservable(input: string | ObservableInput<string>): Observable<string> {
    return typeof input === 'string' ? of(input) : from(input)
}
```

**Expected behavior:**
This function managed to compile correctly in 3.5 with RxJS 6.5.2

**Actual behavior:**
In 3.6, it fails with 
```
Type 'Observable<unknown>' is not assignable to type 'Observable<string>'.
  Type 'unknown' is not assignable to type 'string'.ts(2322)
```
the type of `from()` does not get inferred anymore.
It is declared as
```ts
function from<O extends ObservableInput<any>>(input: O): Observable<ObservedValueOf<O>>
```
Specifically, the `ObservedValueOf<T>` type fails now with `ObservableInput<T>`:
```ts
type ObservedValueOf<O> = O extends ObservableInput<infer T> ? T : never;

type ObservableInput<T> = SubscribableOrPromise<T> | ArrayLike<T> | Iterable<T>;
```
which worked before.

**Related Issues:** Filed at https://github.com/ReactiveX/rxjs/issues/4992

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #33131.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot tets this
@typescript-bot user test this
@typescript-bot pack this for our more ravenous users :V

**Comment by weswigham** [comment]
@typescript-bot test this because "tets this" isn't a command

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by weswigham** [comment]
Ack, a single lint failure. The user baselines look ok, though.

**Comment by fatcerberus** [comment]
> pack this for our more ravenous users :V

🐽

**Comment by ericanderson** [comment]
@typescript-bot cherry-pick this into release-3.6

**Comment by sandersn** [comment]
sudo @typescript-bot cherry-pick this into release-3.6

**Comment by sandersn** [comment]
(Thanks for the attempt @ericanderson, but typescript-bot has a hardcoded list of people it listens to.)

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this into release-3.6

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this to release-3.6

**Comment by sandersn** [comment]
Whew! @typescript-bot, I thought you were dead!

(Hooray for bad natural language parsers.)

**Comment by sandersn** [comment]
Fine, I cherry-picked it myself, *@typescript-bot*. It's in release-3.6 now.

**Comment by fatcerberus** [comment]
typescript-bot seems to be glitchy lately.  Delayed reactions to commands, not closing issues it claims to have closed, etc.

**Pull request merged**
