### PR TITLE
Use system line ending in services compiler host

### LINKED ISSUE #1653: Language services hard-codes newline to \r\n
services/services.ts `createCompilerHost` function hardcodes `getNewLine` to "\r\n" instead of providing a way for the LanguageServiceHost to define it (or at least using ts.sys.newLine).

Refs #372.

### PR DESCRIPTION
**Pull request by csnover**
Fixes #1653.

Let me know where you want tests to go for the language services and I can add some if you’d like.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
`services.ts` isn't supposed to depend on `sys.ts` as far as I understand. Might be better to parameterize `createCompilerHost` but that's kind of ugly. @mhegazy might be able to guide you better.

**Comment by Arnavion** [comment]
Wouldn't it be better to add a getNewLine() method to LanguageServiceHost (just like CompilerHost) and let the implementation provide it? You can continue defaulting to "\r\n" for backward-compat if the LanguageServiceHost implementation doesn't have a getNewLine()

**Comment by mhegazy** [comment]
The problem is that sys may not be defined, e.g. In a web page. I like @arnavion idea. But I would make the new method optional in the interface and call it to initialize the value of the newline in createlamguageservice.

**Comment by csnover** [comment]
OK, that was the first option in the original bug. I will try to change this over the weekend to add an optional host method if someone else doesn’t get to it first.

**Comment by csnover** [comment]
The PR is updated for language service hosts to provide a `getNewLine` method instead.

**Comment by mhegazy** [comment]
Thanks!

**Pull request merged**
