### PR TITLE
Fix import fix on react or react dev

### LINKED ISSUE #41920: Bug: react-jsxdev support for `add all missing imports`
- VSCode Version: 1.51.1
- OS Version: Darwin x64 20.1.0

Steps to Reproduce:

1.`mkdir vscode-react-import && cd vscode-react-import`
2.`yarn add react @types/react typescript`
3. modify files as bellow

`tsconfig.json`
```json
{
  "compilerOptions": {
    "module": "es2020",
    "moduleResolution": "node",
    "jsx": "react-jsxdev"
  }
}
```

`.vscode/settings.json`
```json
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```
`foo.tsx`

```tsx
export default function Foo(){
  return <></>
}
```

`bar.tsx`
```tsx
export default function Bar(){
  return <Foo></Foo>
}
```

4.Select TypeScript version, Use workspace version 4.1.2
5. Move cursor to Foo, see error `Cannot find name 'Foo'.ts(2304)`
image
6. type `⌘` + `.`
image
7. Add all missing imports, then result:
```tsx
import * as React from "react";

export default function Bar(){
  return <Foo></Foo>
}
```
8. Move cursor to Foo, type `⌘` + `.`
image
9. Add all missing imports, then result

```tsx
import * as React from "react";
import Foo from "./foo";

export default function Bar(){
  return <Foo></Foo>
}
```

---

We should not add `import * as React from "react";` when tsconfig has `"jsx": "react-jsxdev"` or `"jsx": "react-jsx"` 

---

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #41920

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@RyanCavanaugh Any update on this?

**Comment by Kingwl** [comment]
@xiaoxiangmoe No.

**Review by andrewbranch — APPROVED** [review]
Thanks @Kingwl!

**Comment by gabro** [comment]
I'm sorry to be *that guy*, but this PR has been approved almost two months ago. Is there any plan to include it in the next TypeScript release?

This bug makes it very hard when working with the new jsx factory trasform, since auto-import code actions basically just stop working and you end up with a lot of spurious (and unused) imports from 'react'.

**Comment by gabro** [comment]
Thank you @andrewbranch for the merge! 🙏

**Comment by andrewbranch** [comment]
Sorry @gabro, I wanted to give others a chance to review, and it just slipped through the cracks. This will be released in 4.3 proper, or in the nightly starting tomorrow.

**Comment by gabro** [comment]
No worries, thanks and keep up with the great work!

**Pull request merged**
