### PR TITLE
Add RegExp indices

### LINKED ISSUE #44227: Node now supports Regexp hasIndices -- typescript does not.
# Bug Report

### 🔎 hasIndices

Node 16 supports indices, TypeScript does not.

### 🕗 Version & Regression Information

When I discovered the feature in Node 16

### ⏯ Playground Link

```
 /(a)/d.exec('a').indices
```

### 🙁 Actual behavior

In Node it works

WIth Typescript, it is flagged as an error

### 🙂 Expected behavior

New features. await support in ESNext.

### PR DESCRIPTION
**Pull request by xiBread**
Fixes #44227

### CODE REVIEW

**Review by rbuckton — CHANGES_REQUESTED** [review]
I'm not sure if we should be more pedantic here or not. `[number, number] | undefined` is a more accurate type, since a failed capture in an alternative can produce undefined:

```js
const match = /(a)|(b)/d.exec("b")
match.indices[1]; // undefined
match.indices[2]; // [0, 1]
```

However, we use `string` instead of `string | undefined` in `RegExpExecArray`, so maybe this is fine.

**Comment by ImUrX** [comment]
any news?

**Comment by pagoru** [comment]
Come on...

**Comment by rbuckton** [comment]
Superseded by #52085

**Pull request closed without merging**
