### PR TITLE
Handles creating a reasonable AST when destructuring into a parens'd expresssion

### LINKED ISSUE #39192: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isLeftHandSideExpression'.
**Repo Name**: https://github.com/facebook/react.git

**Revision**: 6ba25b96df5d4179bf8aba3c3fe1ace3dce28234

**TypeScript Version**: 4.0.0-dev.20200622

**Commands**: 

```
{"responseRequired":false}
{"command":"quickinfo-full","arguments":{"position":1023,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":7}
{"response":{"kind":"method","kindModifiers":"declare","textSpan":{"start":1014,"length":11},"displayParts":[{"text":"(","kind":"punctuation"},{"text":"method","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"Date","kind":"localName"},{"text":".","kind":"punctuation"},{"text":"toISOString","kind":"methodName"},{"text":"(","kind":"punctuation"},{"text":")","kind":"punctuation"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"string","kind":"keyword"}],"documentation":[{"text":"Returns a date as a string value in ISO format.","kind":"text"}]},"responseRequired":true}
{"command":"quickinfo-full","arguments":{"position":471,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":8}
{"response":{"kind":"","kindModifiers":"","textSpan":{"start":471,"length":1},"displayParts":[{"text":"any","kind":"keyword"}]},"responseRequired":true}
{"command":"definition-full","arguments":{"position":1023,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":9}
{"response":[{"fileName":"D:/home/site/wwwroot/node_modules/typescript/lib/lib.es5.d.ts","textSpan":{"start":37072,"length":11},"kind":"method","name":"toISOString","containerName":"Date","contextSpan":{"start":37072,"length":22},"isLocal":false}],"responseRequired":true}
{"command":"definition-full","arguments":{"position":471,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":10}
{"response":[],"responseRequired":true}
{"command":"references-full","arguments":{"position":1023,"file":"D:/local/Temp/fuzzerWorkingDir/react/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js"},"type":"request","seq":11}
(Showing last 10 of 499 commands)
```

**Code** ([`fixtures\dom\src\components\fixtures\date-inputs\switch-date-test-case.js`](https://github.com/facebook/react/blob/6ba25b96df5d4179bf8aba3c3fe1ace3dce28234/fixtures/dom/src/components/fixtures/date-inputs/switch-date-test-case.js)):

```js
        return {
          type: 'datetime-local',
          value: this.state.date.toISOString().replace(/\..*Z/, ''),
//                                        ^
        };
      } else {
```

**Hash**: b5872fd7b1bdd15e2a1ef4359314b5b3
**Stack trace**: 
```
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isLeftHandSideExpression'.
    at Object.cast (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:1554:25)
    at Object.parenthesizeLeftSideOfAccess (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:19311:73)
    at Object.createElementAccessExpression (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:21125:52)
    at getSyntheticElementAccess (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48818:70)
    at getFlowTypeOfDestructuring (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48809:29)
    at getTypeForBindingElement (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48892:28)
    at getTypeForVariableLikeDeclaration (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:48967:24)
    at getWidenedTypeForVariableLikeDeclaration (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:49419:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:49551:24)
    at getTypeOfVariableOrParameterOrProperty (D:\home\site\wwwroot\node_modules\typescript\lib\tsserverlibrary.js:49456:28)
```

_Originally posted by @typescript-bot in https://github.com/microsoft/tsserverfuzzer/issues/238#issuecomment-647426426_

### PR DESCRIPTION
**Pull request by orta**
Fixes #39192 - the actual call wasn't the issue, but that it triggered lading a particular test file into memory. This repo with the crash  [uses flow](https://github.com/facebook/react/blob/23595ff593b2e53ddfec2a08e848704d15d84b51/packages/react-devtools-shared/src/__tests__/inspectedElementContext-test.js#L638), where this is legal syntax, but you can also have legal syntax from it in JS. If a little abstract.

Roughly, this should not crash TS

```ts
const {
  date,
} = (inspectedElement: any) => 0;

date.toISOString();
```

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I'm so confused - how is this legal JS?

**Review by weswigham — APPROVED** [review]
But I kinda helped write this so maybe another pair of eyes is pertinent~

**Review by elibarzilay — APPROVED** [review]
Looks reasonable to me, but I didn't do much syntax tweaking so some soy sauce needed.

**Comment by noglik** [comment]
@orta Hello, recently I bumped in the error mentioned in [#39192](https://github.com/microsoft/TypeScript/issues/39192). 
The cause is different:
```
const { constructor } = async () => {};
```
Is it related to your fix?
I checked with typescript@4.0.3 and your branch, both throws an error :disappointed: 
I created a small [repo](https://github.com/noglik/ts-invalid-cast) to reproduce the error.

**Comment by orta** [comment]
I added your async example to the test suite and it doesn't crash, so I think this is fixed with this PR

**Pull request merged**
