### PR TITLE
Don't set NodeFlags.JavaScriptFile on JSON, avoid asking for JSDoc outside of JS

### PR DESCRIPTION
**Pull request by jakebailey**
I found this with #52640 as we ask for JSDoc tags on something that isn't a JS file without first checking, which _could_ be a bug, but in this particular case is just a waste of CPU time.

I also noticed that we check that the node isn't also JSON, which seemed weird, because how can something be both JSON and JS? It turns out that JSON files get _both_ context flags set, and so this extra condition is required (the only use of `isInJsonFile` in the checker!). But, nothing fails if we just make the two `NodeFlags` mutually exclusive, so I've done that.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
Do we need to better-harden these at all?

https://github.com/microsoft/TypeScript/blob/6b43f8277494149c93a482eb1b12b09e9b42b869/src/compiler/binder.ts#L3287

https://github.com/microsoft/TypeScript/blob/6b43f8277494149c93a482eb1b12b09e9b42b869/src/services/codefixes/disableJsDiagnostics.ts#L37

**Comment by jakebailey** [comment]
Probably, I guess all of those (there are other checks sorta like it) may be doing more work than needed. Clearly nothing actually fails...

We could also harden `getJSDocTagsWorker` to say "don't try and ask for JSDoc on JSON"; `getJsDocTagsFromDeclarations` would actually immediately fail because of this.

**Comment by jakebailey** [comment]
Maybe it's not worth changing the flag thing at all, if it makes those sort of "is outside of TS" checks harder. Or maybe we need to do the opposite and instead have a helper which says "if in TS".

**Comment by jakebailey** [comment]
Seems like no change in performance, but, a little bit of a memory improvement? Hard to say if that's specifically not setting the flag or the jsdoc change itself. I guess I can split this PR in two.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Hm, hard to say if that's actually better.

I guess the only question I have is if it's worth it to change the flags; I think the checker change is totally fine as it reduces the work we do, and I can do that without changing this flags behavior (though I don't think the flag being on there is a good idea in general).

**Pull request closed without merging**
