### PR TITLE
This types for all methods

### PR DESCRIPTION
**Pull request by sandersn**
Just an experiment to see how slow it is.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
Would fix #44513 if it worked and weren't too slow.

**Comment by andrewbranch** [comment]
Yeah. That seems expected.

**Comment by sandersn** [comment]
Check time is 6-7% slower on class-heavy code bases.

It's possible that issuing bogus errors takes that much time &mdash; and this PR does issue bogus errors; the code isn't correct. But I doubt it.

**Pull request closed without merging**
