### PR TITLE
Defer processing of nested generic calls that return constructor types

### PR DESCRIPTION
**Pull request by Andarist**
I'm trying a lot of things to benefit from contextual inference like this for nested calls. The only thing that works is if the nested call returns a function **but** at that position in our library regular functions can also one received.

We need a way between differentiating them at runtime so I tried to return a constructable type from our factories instead - that didn't pan out. It didn't help my inference problems but I was quickly able to find out why... so I tried this as an experiment and since all tests pass, I think it's worth proposing this.

### CODE REVIEW

**Review by weswigham — APPROVED** [review]
IMO, what's good for the generic function is good for the generic constructor - it being missing was probably just an oversight.

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this

**Comment by sandersn** [comment]
@tyescript-bot run dt

**Comment by sandersn** [comment]
@typescript-bot run dt

**Pull request merged**
