### PR TITLE
Always respect preserveSymlinks

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Comment by sheetalkamat** [comment]
@typescript-bot perf test this

**Comment by sheetalkamat** [comment]
@typescript-bot perf test this

**Comment by sheetalkamat** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
I think this is a good change, but I think we should try to gather more perf data as it’s a bit hard to tell from the run what’s noise and what’s real. We should try running this on VS Code’s codebase, because they use a ton of baseUrl/paths so a huge amount of their module specifiers are non-relative.

**Comment by sheetalkamat** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/shkamat/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/shkamat/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



  | main | PR | Delta
-- | -- | -- | --
ResolveModule time | 3.98 | 3.84 | -0.14
ResolveTypeReference time | 0.04 | 0.05 | 0.01
Program time | 31.68 | 30.95 | -0.72
Total time | 302.11 | 279.20 | -22.91



</body>

</html>

**Comment by andrewbranch** [comment]
That’s good news I guess, but it’s very surprising. Aren’t we doing _way_ more `realpath` calls in this PR? I thought those were supposed to be slow? And they’re basically free?

**Comment by sheetalkamat** [comment]
@andrewbranch This change is making the behaviour more deterministic irrespective of "amd" or "node like" resolutions. But it isnt changing the fact tha we are doing synlinks only for `node_modules` resolutions. Refer https://github.com/microsoft/TypeScript/pull/51842/files#diff-0dea9ce163bfdd2ae3e20ed8b975a3b42b930794db19b2e7dfebf9a4bf958f57R220 . We do it only if resolution is from node_modules, module name is "non relative". So from vscode perspective and most users' perspective there shouldn't be any change. This change just removes discrepancy and is very much needed for my buildInfo storing resolutions work so that i can make decisions. (so I don't have to store originalPath and realPath both)

**Review by andrewbranch — APPROVED** [review]
I think I missed the condition on `isExternalLibraryImport` in my earlier review, which is why I thought non-relative resolutions depending on `baseUrl` and `paths` would be impacted. This makes sense 👍

**Pull request merged**
