### PR TITLE
Completion list for JSON files imported using CommonJS require

### LINKED ISSUE #7071: In JS, importing JSON should not give an error
Make a json file

```
{
    "season": 1
}
```

Code

```
var test = require("test.json");
```

result

untitled-1

expect

untitled-2

### PR DESCRIPTION
**Pull request by vojtechhabarta**
Fixes #7071

This change provides completion lists for JSON files that are loaded using CommonJS `require` function.
For example for `json1.json` file

``` json
{
    "foo": "foo",
    "bar": "bar"
}
```

and `test.ts` file

``` typescript
var json1 = require("./json1");
json1. // <---
```

TypeScript compiler now provides completion list with `foo` and `bar` items.
### Implementation

It is implemented as proposed in https://github.com/Microsoft/TypeScript/issues/7071#issuecomment-196653264 comment.
- JSON files are parsed using TypeScript parser `parseObjectLiteralExpression()` function
- node module resolver is extended to support `.json` extension
- added `ScriptKind.JSON`

EDIT: removed description of my problem with tests (solved by updating dependencies using `npm install`)

### CODE REVIEW

**Comment by mhegazy** [comment]
//cc @DanielRosenwasser who was looking into this earlier.

**Comment by piotrwitek** [comment]
+1

**Comment by mhegazy** [comment]
@vojtechhabarta sorry for the delay. I am a bit busy with TS 2.0 release at the moment, but i would love to get this change in once that is out.

**Comment by aluanhaddad** [comment]
It would be nice if this could be generalized. If the user writes an import statement like
```ts
import * as json1 from './json1';
```
or
```ts
import json1 from './json1'; // iff "allowSyntheticDefaultImports": true
```
it should work just as well. @mhegazy what do you think?

**Comment by vojtechhabarta** [comment]
I wanted to resubmit this PR based on current master but I don't know how to solve one thing.

Recently #11370 was merged which adds following change: _"Return type of require call is from external module resolution only if it doesn't resolve to local module"_ (checker.ts:12797 - https://github.com/Microsoft/TypeScript/pull/11370/files).
However this resolution is also used when there is **node.d.ts** in compilation so in this example test:
``` typescript
// @allowjs: true
// @outDir: dist
// @Filename: m1.js
export var a = 42;

// @Filename: m2.js
const m1 = require("./m1");
const a = m1.a;

// @Filename: node.d.ts
interface NodeRequireFunction {
    (id: string): any;
}
interface NodeRequire extends NodeRequireFunction {
}
declare var require: NodeRequire;
```
type of `m1.a` in `any` instead of `number` as it was before #11370.

Same applies for `require` with JSON file. I don't know how to distinguish between `require` from node.d.ts and other `require` cases.

@mhegazy, @sheetalkamat do you have any idea how this could be improved so it works also with node.d.ts?

**Comment by sheetalkamat** [comment]
Checkout this #11819

**Comment by vojtechhabarta** [comment]
Thanks @sheetalkamat for the link, that's exactly what I needed.

@mhegazy I rebased this PR on current master branch.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/pull/13665

**Pull request closed without merging**
