### PR TITLE
Add generic type parameter to startsWith/endsWith

### LINKED ISSUE #46958: Using startsWith & endsWith to narrow type
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `ES2020`.

## Missing / Incorrect Definition

`startsWith` & `endsWith` doesn't narrow the the type, it just returns a boolean.

## Sample Code

```typescript
interface BuiltinPaymentMethod {
  id: `builtin-${string}`
  // ...
}

// ...

declare const id: string

if (id.startsWith('builtin-')) {
  // Here I want `id` to be typed as `builtin-${string}`
}
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

## Pull Request

https://github.com/microsoft/TypeScript/pull/46959 🚀

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #46958

Sorry for being a bit quick to open this PR, I started by editing the code and then later found out about the proper process. I figured it would be good to open this one anyways a suggestion on how to fix the issue I opened.

I also had a hard time figuring out _where_ to add tests for this. It's not under ["Contributing lib.d.ts fixes"](https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#contributing-libdts-fixes) and ["Adding a Test"](https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#adding-a-test) seems to be for compiler tests cases. Any help appreciated!

### CODE REVIEW

**Comment by xiBread** [comment]
This wouldn't handle cases where a `position` is passed.

**Comment by LinusU** [comment]
@xiBread you are very right, don't know how I missed that 😅 

Will push a commit addressing this asap

**Comment by LinusU** [comment]
Amended the commit to account for the `position` parameter.

Here are some preliminary tests in a playground: [link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMpiqA5sg3gKGSOQHoAqMw45M5AJQjAFcoQBnZDJlYGTgCxRsIAR24gkyAPZ8IAGwgBbCOA4zkwuFAT90mEDgRSQAN2iQAJpynI4aDNmTAOYQVWK02cZbZeDkRlBQEGwADsYWjvJKKmBqfK7O0gBGAFYQCGDIABRGpuYQVmA2dnrYAJQaYFpgjnBg7kS0KhYAClJswLXGyIDIBMgKBq7ZiWzlAHTIAPKu0ADuzijBzKwc8HLC4400JI0tbADqXfwAPAAqyBAAHpAgFhxsDgYAfNma2rpPWABcyGcANJc7u1Ot0QAB+X5MO4QGCgQrlX6jJwcAAGABJcI99FgAL6Ys641EAbj2d0OxzeEC0OjKBl+2OwgJaIK6wGMkOQICYimS0ERyGSUikCjgIFJjXIlGoNHojBY7E4UG4TgS-mEYhUknU0WUqmkfHetK+AWMZiglmstnsOJRAgg2083hQcD8KECwTCESiCj1cQNAiSUjSGSyuTNBSKJRtFSqNTqDRltHCoPZIEmM0EUAWwmQywVazgGwgWyTu2ojxqFNc50uN32VRxryNnxxvwByBTbI5vwADALkUkMbhCZjGQYiaSK9ULdX+FSaa3sAyvoCu2DOdzefzfkKRdTxfhcfh8BYMnItO7jI9OCEwCucSfeDlII9xpXZ0dhgByV9gb-lJUeRsPu4xyFIWAjHe5T4M+UFvh+cRfvOv53t+gLQmecIgAiQHXqB4GQX+MFwX+74zkhlKoY86HIP2eHsAREHwWAJF8Cx5FVsh2TUf+gIAIyAaajEKGBzHEbB7FkYhc48X+tG9r4XI8nyUBCcBTFEdBkkvnenGflR8kCUpW6qep+GiYRLEwTpHH7NxvEAQxIGWeJ2mkXp9mGWhGEwthuHCS5JZWRJHlvl5P5GXR5kicFbmPGxunheSDlRYJzmadZtlkRFKFRYprrKduakZa5WkJdlnkpd5NHGYVpn8qVcXlaxQA)

Would still like to add these as proper tests as soon as I know where to put them!

**Comment by LinusU** [comment]
I've added tests, but they might be in the wrong place 😅

**Comment by LinusU** [comment]
Closing per discussion in #46958

**Pull request closed without merging**
