### PR TITLE
error on set accessor without get accessor

### PR DESCRIPTION
**Pull request by ajafff**
Fixes: #11596

### CODE REVIEW

**Comment by ajafff** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
@ajafff Indeed - it is limited to repo owners and MS org members right now. @RyanCavanaugh I imagine you want to monitor the result, since you suggested it.

@typescript-bot test this

**Comment by weswigham** [comment]
So this introduces errors into 10 of our RWC projects, with little added value - the setter-only objects mostly look like they're clearly written to actually be setter only - mostly membranes that do a little extra work on write. TBH, I personally have no problem with most of the usages in our RWC suite - they make a good argument for properly recognizing `writeonly` props.

**Comment by RyanCavanaugh** [comment]
Sounds like this needs to block on #21759 then?

**Comment by weswigham** [comment]
I'd say so, yeah. I don't think we can make it an error reasonably when people can't yet express the state in which a setter-only property is correct.

**Comment by RyanCavanaugh** [comment]
Closing because this can't be merged unless #21759 happens (which is quite unlikely in the near future)

**Pull request closed without merging**
