### PR TITLE
Check for strict subtypes and then regular subtypes in getNarrowedType

### LINKED ISSUE #52827: Improvement to getNarrowedType changes lodash's isArray
```ts
declare function isArrayLike(value: any): value is { length: number };
declare const value: { [index: number]: boolean, length: number } | undefined;

if (isArrayLike(value)) {
    const result: { length: number } = value;

} else {
    const result: undefined = value;
}
```

Before #52282: `value: undefined` in the false branch.
After #52282: `value: { [index: number]: boolean, length: number } | undefined` in the false branch.

This is *more* consistent, although the full repro at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64406 seems *less* consistent than the 4.9 semantics.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Experiment to see the effects of first checking for strict subtypes and then checking for regular subtypes in `getNarrowedType`, and picking the asserted type only when it is a pure subtype of the original type.

First experiment checked only using the strict subtype relationship, but that introduces too many breaking changes (specifically caused by strict checking of signature arity and readonly properties).

Fixes #52827.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot test top100

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by Andarist** [comment]
FYI, [a new issue](https://github.com/microsoft/TypeScript/issues/53063) related to this has been opened and this PR fixes it

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
> First experiment checked only using the strict subtype relationship, but that introduces too many breaking changes (specifically caused by strict checking of signature arity and readonly properties).

I am curious about what breaks these would have been; are they listed somewhere or did you only find them during testing?

**Comment by jakebailey** [comment]
And, the answer is probably no (because it's risky), but, given the 5.0 regressions people are reporting, I'm somewhat curious if this is something we should backport before stable 5.0. But, I assume not.

**Comment by ahejlsberg** [comment]
@jakebailey You can see some of them [here](https://github.com/microsoft/TypeScript/pull/52984#issuecomment-1445432195).

**Comment by ahejlsberg** [comment]
I think we should consider bringing this one into 5.0.

**Comment by MichaelMitchell-at** [comment]
> I think we should consider bringing this one into 5.0.

Original reporter of https://github.com/microsoft/TypeScript/issues/50916 here. I tried out https://github.com/microsoft/TypeScript/pull/52282 again in our codebase and while it does address the original issue, it introduced a regression elsewhere so this would still block us from upgrading to TS 5.0. I've tried out the fix in this PR locally and it seems to fix resolve both issues, so it'd be great if this could make it into TS 5.0.

The new regression if curious

```ts
type Foo = {value: {type: 'A'}; a?: number} | {value: {type: 'B'}; b?: number};

const isB = (arg: unknown): arg is 'B' => arg === 'B';

const foo = upcast<Foo>({value: {type: 'A'}});

if (doesValueAtDeepPathSatisfy(foo, ['value', 'type'], isB)) {
  foo2 // should be `{value: {type: 'A'}; a?: number}`, is now `Foo` with the regression
}
```

**Comment by ahejlsberg** [comment]
@MichaelMitchell-at Good to hear this PR fixes the issues. Meanwhile, would you mind updating the regression code above with the definitions of the missing functions so we can have an additional repro.

**Comment by chriskrycho** [comment]
This also fixes a regression in Ember's internal type test suite for TS 5.1 (no issue on 5.0) shaped like this:

```ts
function example(vals: Array<unknown> | MyCollection<unknown>): number {
  if (Array.isArray(vals)) {
    return vals.length;
    //     ^^^^ has type `Array<any>`
  } else {
    // ❌ type error (erroneous!)
    return vals.collectionSize;
    //     ^^^^ has type `Array<unknown> | MyCollection<unknown>`
  }
}
```

With this PR, this is back to behaving the way it did in v5.0 and earlier. 👍🏼

**Comment by MichaelMitchell-at** [comment]
@ahejlsberg updated

**Comment by ahejlsberg** [comment]
@MichaelMitchell-at Much appreciated. Will add as a test case.

**Comment by ahejlsberg** [comment]
@chriskrycho I take it you mean this PR brings it back to behaving like **4.9** and earlier, right?

**Comment by ahejlsberg** [comment]
Additional repro added in latest commit.

**Comment by chriskrycho** [comment]
@ahejlsberg Possibly I missed up my bisection, but in my testing, the 5.0 RC worked and 5.1 did not. I can dig further (though not till Monday at the earliest).

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-5.0

**Pull request merged**
