### PR TITLE
fix(52828): No signature help in parameter declaration before , and )

### LINKED ISSUE #52828: No signature help in parameter declaration before `,` and `)`
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230217#code/C4TwDgpgBAKu0F4oAoCGAaKAjTBjAlFAgHxQBuA9gJYAmAsAFCO4UB2AzsFKgFyzxEUGbIRJQA3gF8gA)

### 💻 Code

```ts
type Type = (a, b, c) => void

const a: Type = (a/*1*/, b/*2*/) => {}
```

(CTRL+SHIFT+SPACE) in following locations

### 🙁 Actual behavior

Signature help disappears in markers `/*1*/` and `/*2*/`

### 🙂 Expected behavior

Should not disappear in these locations, just like if we would write `a(a, b)`. It doesn't appear even on invoke trigger

But I wonder if it was done on purpose. This is really annoying in some cases as you need to move cursor to just read jsdoc or to figure out wether it accepts additional arguments.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #52828

### CODE REVIEW

**Comment by zardoy** [comment]
The fix is narrowed to only one specific case, but this code would still lack of signature help:

```ts
type Type = (a, b, ...c) => void

const a1: Type = ({a: { b }} = {}, [b], ...c) => {}
// no help in almost in all positions
```

**Comment by zardoy** [comment]
Maybe this would work?:

```ts
function getAdjustedStartNode(node: Node) {
    switch (node.kind) {
        case SyntaxKind.OpenParenToken:
        case SyntaxKind.CommaToken:
            return node;
        default:
            return findAncestor(node, (node) => isParameter(node));
    }
}
```

**Comment by gabritto** [comment]
@typescript-bot pack this

**Review by gabritto — CHANGES_REQUESTED** [review]
~On a second look, this PR doesn't seem to fix the issue based on my testing it on vscode. I think the machinery we have to get parameter info already works for the given positions (before a comma and parenthesis), but we must be choosing to not show it or trigger it for *implementations* elsewhere in the code or on vscode. Signature help seems to work fine for *function calls* already.~

Ok, I was testing it wrong, my bad. But I'm still curious as to why signature help works at those positions when you're in a function call, but doesn't work in a function implementation. Is it that we're calling into a different code path?

**Comment by zardoy** [comment]
Hi @gabritto, I'm extremely interested in your feedback. Can expand it?

> On a second look, this PR doesn't seem to fix the issue based on my testing it on vscode. I think the machinery we have to get parameter info already works for the given positions

Just an example of what it fixes https://github.com/microsoft/TypeScript/pull/52840#issuecomment-1435704468 (sighelp available in any positions only with this pr)

> but we must be choosing to not show it or trigger it for _implementations_ elsewhere in the code or on vscode

Did you mean that sig help should be disabled in these positions? Wouldn't that be a disruptive change? Additionally, it seems unrelated to this PR as the focus here is on displaying sighelp correctly in all positions.

(Please let me know if I misunderstood your point.)

**Comment by gabritto** [comment]
@zardoy I updated my comment above, sorry about the confusion 😅

**Comment by a-tarasyuk** [comment]
> But I'm still curious as to why signature help works at those positions when you're in a function call, but doesn't work in a function implementation. Is it that we're calling into a different code path?

It seems yes, with one general helper

> when you're in a function call
https://github.com/microsoft/TypeScript/blob/710e7d914ddb2c48c4187f1eab5a43de3a116294/src/services/signatureHelp.ts#L293

> in a function implementation
https://github.com/microsoft/TypeScript/blob/710e7d914ddb2c48c4187f1eab5a43de3a116294/src/services/signatureHelp.ts#L389

----

https://github.com/microsoft/TypeScript/blob/710e7d914ddb2c48c4187f1eab5a43de3a116294/src/services/signatureHelp.ts#L377-L379

**Review by gabritto — APPROVED** [review]

**Pull request merged**
