### PR TITLE
Load js config file

### LINKED ISSUE #30400: Allow javascript (or typescript) config file
## Suggestion

I suggest allowing a tsconfig.js or tsconfig.ts as an optional alternative to tsconfig.json.

## Use Cases

What do you want to use this for? Primarily to add comments to the tsconfig file. 
What shortcomings exist with current approaches? JSON does not allow comments. You can't even hack in comments by adding fake fields like `"_explanationOfTypeRoots"`, as the build complains about unknown compiler options and stops.

## Examples

Many tools and frameworks allow javascript config files. Jest, for example. `jest --init` produces a heavily commented config file, which is very useful for beginners.

### LINKED ISSUE #39441: Javascript tsconfig file (tsconfig.js)
## Search Terms

config
tsconfig.json

## Suggestion

It would be very helpful if typescript followed the conventions of pretty much every other JS-stack tool and allowed the configuration to be done as a javascript file so they can more easily be manipulated.
For example all these tools (and many more) already accept configuration files to be javascript:

Prettier -> .prettierrc.js
Jest -> jest.config.js
Webpack -> webpack.config.js
eslint -> .eslintrc.js
styleling -> .stylelintrc.js
lint-staged -> lint-staged.config.js

My suggestion is for typescript tsconfig resolver to look for a `tsconfig.js` file if available, if so `require()` it and use the exported values as configuration. If that file is not available then follow the current resolver rules for tsconfig.json.

## Use Cases

- Filesystem introspection
- Better environment variable toggling of options
- Easier extensibility of configurations
- Easier building of tools that include typescript

## Examples

```js
module.exports = {
  "includes": [path.resolve(__dirname, process.env.SOURCE_DIR)],
  ...
}
```

```js
const config = { ... }
if (NODE_ENV === 'development') config.compilerOptions.noUnusedLocals = false
module.exports = config
```

Right now it is impossible to merge arrays when using the "extends" option of tsconfig.json. If the configuration were javascript files this would be feasible:

```js
const originalConfig = require('some-dep/config/tsconfig.json')
const path = require('path')
module.exports = {
  ...originalConfig,
  includes: [...originalConfig.includes,  path.resolve(__dirname, './mytypes/')]
} 
```

## Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by ANFADEV**
Fixes #30400 , #39441 and potentially #37884

I was coding a helper for [Prebuilder](https://github.com/prebuilderjs/prebuilder) like [this one for Rollup](https://github.com/prebuilderjs/rollup),
It needs a javascript config file, in order to let Prebuilder control the compilation process with dynamic paths.
I was surprised to see that it's still not possible in typescript, so i dug in this repo this weekend, and came up with this solution, that apparently satisfies some of the points expressed in #30400:
- it's fairly secure, the js config is obtained by converting the tsconfig.js' default import to a json string, and then treated the same as a tsconfig.json
  - So no function will be used by the compiler, just raw json-like data
  - Any config error handling already in place for a .json config works for the .js one too (i tested, putting an inexistant compiler option)
- it's not complicated, as it only adds one step to the process
- in order to use a js config file, tsc will need it to be specified using the -p parameter, so the default behavior is preserved

## Testing
I tried writing a test, but it has not been easy, i spent more time trying to do this, than the actual implementation...
I would leave this task to any willing person, as i couldn't figure where to put the .js config file

I have tested manually like this:
- built with `npm run build`
- tested with `npm run test` (✔)
- prepared with `npx hereby LKG`
- published the package to my local registry
- created a test project with two .ts scripts and the tsconfig.js (below) and without a tsconfig.json file in the project
- ensured that the test project ran tsc using the local typescript package i published

And it worked perfectly, transpiling to the 'dist' folder.✔
Config extensibility (`extends: "./tsconfig.js",`) works with js config files too ✔

## Usage

```sh
tsc -p tsconfig.js
```
tsconfig.js :
```js
module.exports = {
    compilerOptions: {
      declaration: true,
      target: "es5",
      module: "commonjs",
      strict: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noImplicitReturns: true,
      noFallthroughCasesInSwitch: true,
      composite: true,
  
      outDir: "dist/prod",
    },
    include: [ "./src/" ]
}
```

Also:
Dynamically adding a path ✔
And extending with a .js config ✔
```sh
SET NODE_ENV=dev&& tsc -p tsconfig-extended.js
```
```js
const path = require('path');

module.exports = {
    extends: "./tsconfig.js",
    compilerOptions: {
        // transpiles to the 'dist/dev' folder
        outDir: path.join("dist", process.env.NODE_ENV),
    }
}
```

### CODE REVIEW

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/issues/30400#issuecomment-536350685

> We are not accepting PRs to turn config into an executable thing.

**Comment by ANFADEV** [comment]
Plenty of people want this feature, it's one of the reasons the issue was reopened
see [comment](https://github.com/microsoft/TypeScript/issues/30400#issuecomment-1205836287):
> I am reopening since this has so much interest. I closed it initially out of respect for the maintainer’s statements that they didn’t want to support it.

It's incredibly useful, please reconsider...

As for the "can of worms" problem, there isn't any really.. typescript only treats the import as a json object, if it fails at converting it to json it falls back, and reports an error to the user.

A lot of other dev tools like Webpack, Rollup, Vite etc.. even support config plugins, which would be more "hazardous" than this implementation.
So i don't see an imperative reason to worry about this

**Comment by MartinJohns** [comment]
> It's incredibly useful, please reconsider...

It's up to the team, I just quoted them.

> As for the "can of worms" problem, there isn't any really.. typescript would only treat the import as a json object, if it fails at converting it to json it falls back, and reports an error to the user.

It **executes** the JavaScript. So what happens if there are imports in the js file? Or if someone accesses `process`? If this feature is supported, people will expect these things to work as well (at least the import), and the team would have to support it.

**Comment by ANFADEV** [comment]
> So what happens if there are imports in the js file? Or if someone accesses process? If this feature is supported, people will expect these things to work as well

Imports in the js file will be executed as the developer wants, like in my latest example:

> ```shell
> SET NODE_ENV=dev&& tsc -p tsconfig-extended.js
> ```
> 
> ```js
> const path = require('path');
> module.exports = {
>     compilerOptions: {
>         outDir: path.join("dist", process.env.NODE_ENV),
>     }
> }
> ```

which is read as:
```json
{
    "compilerOptions":{
         "outDir": "dist/dev",
     }
}
```
Imports and anything else, can't have a way into typescript's process, as the read output of the js file is a json string

> when you open a project in VS Code it reads your configuration. With this change it means you open your workspace and it executes JavaScript

Well yes, VS Code prompts the user a modal to check if the user trusts the content of the project already,

Devs put only what's needed in config files, see how rollup & webpack configs have been used til now by the dev community.
A developer is responsible for his .js config file, just as he is for coding a script an putting it in the package.json

Denying this control to his configuration process, isn't gonna stop him from putting malicious code in his own project, if he wills to

**Comment by ANFADEV** [comment]
This could also solve #37884

**Comment by sandersn** [comment]
I would much prefer to design this feature in an issue instead of a PR. The code is pretty simple, but the design is complicated. Since the original issue is still open, let's discuss there. Although I personally still agree with @RyanCavanaugh 's hesitation to have an executable config.

In the meantime, to help with PR housekeeping, I'm going to close this PR.

**Pull request closed without merging**
