### PR TITLE
Use identity with the permissive instantation to detect nongenric instances and disable variance probing on nongeneric instances

### PR DESCRIPTION
**Pull request by weswigham**
Previously @ahejlsberg had mentioned disabling variance probing for generic mapped types - that's not good enough. In the examples given by, eg `varianceProblingAndZeroOrderIndexSignatureRelationsAlign` (which come from user code - see #29817), the mapped types are within something else which we're still doing variance calculations for. The real "heuristic" as it were, is simply that if we know we're not relating generic types, then we should compare structurally rather than with variances (since we know the structural comparison will yield the correct result and likely be more permissive than any pessimistic higher order relationship may have been). Since we can't directly check if a type still contains generics or not, I proxy the check by seeing if the permissive instantiation of the type and the type itself are identical. If they are, then either A. we're looking at a permissive instantiation of a type (which is by definition non-generic, since all generics have been mapped out), or B. we're looking at a type which is unaffected by instantiation of all generics in it (so contains no generics).

### CODE REVIEW

**Comment by weswigham** [comment]
cc @ahejlsberg this was the PR for the thing I was just talking to you about.

@typescript-bot test this & @typescript-bot run dt

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt

**Comment by sandersn** [comment]
Note from DT: In its current state, this should fix the failure in `@types/jasmine`. (That's where the test case nongenericPartialInstantiationsRelatedInBothDirections.ts comes from.)

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
This undoes the pair of RWC errors introduced by the merge of #29817, so the [RWC diff](https://mseng.visualstudio.com/DefaultCollection/_git/Typescript/pullrequest/438325?_a=files) looks pretty good to me.

**Comment by sandersn** [comment]
I looked at the DT diff. Most of the ember errors are gone, so I guess that the ones remaining have strictFunctionTypes: true. Jasmine is also fixed. However, the process ran out of memory before finishing, so I'm not sure it finished yargs successfully.

Worse, mithril overflows the stack now. You should probably take a look.

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt

**Comment by weswigham** [comment]
Remaining DT changes just look to be some minor changes in ember that @sandersn already has a PR up on DT to fix, so this looks good now ❤️

**Comment by weswigham** [comment]
After some soul searching on how to best fix the depth crash found via specced, i swapped from using the restrictive instantiation to the permissive instantiation as an identity target - both map all type parameters, but since permissive maps type parameters into wildcard, repeated instantiations don't chain (and the wildcard type often bails out of identity checking way faster than a type parameter when it doesn't match as an added bonus).

**Comment by weswigham** [comment]
@typescript-bot test this & @typescript-bot run dt

**Comment by sandersn** [comment]
The DT run is all clean except for the remaining ember failures, which I have a fix for, and *another* project URL change, which I just updated.

**Comment by weswigham** [comment]
Is the project url failure just only reporting one failure at a time or something?

**Comment by sandersn** [comment]
@weswigham That is unlikely because dtslint issues the error, and it's being run in parallel by dtslint-runner.

It's much more likely that of the 5200+ npm packages that DT tracks, one or two per day change their urls.

**Comment by sandersn** [comment]
Update from #30133: Reverting the invariance of conditional types shows that this PR still fixes errors in

1. jasmine (which is a test case of this PR)
2. ember and ember__object

I'm not sure of the exact cause of ember's problem, but it's still going through their `UnwrapComputedPropertyGetters` conditional type.

However, spected, mithril and yargs no longer error on master, so this PR doesn't need to address those errors.

**Comment by weswigham** [comment]
@typescript-bot run dt

**Pull request merged**
