### PR TITLE
Transforms april merge from master

### PR DESCRIPTION
**Pull request by sandersn**
Last merge was 3/18.
There are 17 new failures. I'll take a look and either file bugs or open a PR to accept baselines.

```
not ok conformance tests compiler tests for tests/cases/conformance/expressions/unaryOperators/logicalNotOperator/logicalNotOperatorInvalidOperations.ts "before all" hook
  Error: Debug Failure. False expression: 
      at Object.assert (built/local/typescriptServices.js:1957:23)
      at parseIncrementExpression (built/local/typescriptServices.js:13091:22)
      at parseUnaryExpressionOrHigher (built/local/typescriptServices.js:12981:43)
      at parseBinaryExpressionOrHigher (built/local/typescriptServices.js:12804:31)
      at parseAssignmentExpressionOrHigher (built/local/typescriptServices.js:12508:24)
      at parseInitializer (built/local/typescriptServices.js:12475:20)
      at parseVariableDeclaration (built/local/typescriptServices.js:14278:36)
      at parseListElement (built/local/typescriptServices.js:11392:20)
      at parseDelimitedList (built/local/typescriptServices.js:11673:33)
      at parseVariableDeclarationList (built/local/typescriptServices.js:14312:37)
not ok conformance tests compiler tests for tests/cases/conformance/jsx/tsxExternalModuleEmit2.tsx Correct JS output for tests/cases/conformance/jsx/tsxExternalModuleEmit2.tsx
  Error: The baseline file tsxExternalModuleEmit2.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok conformance tests compiler tests for tests/cases/conformance/jsx/tsxReactEmit2.tsx Correct JS output for tests/cases/conformance/jsx/tsxReactEmit2.tsx
  Error: The baseline file tsxReactEmit2.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)

not ok conformance tests compiler tests for tests/cases/conformance/jsx/tsxReactEmit4.tsx Correct JS output for tests/cases/conformance/jsx/tsxReactEmit4.tsx
  Error: The baseline file tsxReactEmit4.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok conformance tests compiler tests for tests/cases/conformance/jsx/tsxReactEmit5.tsx Correct JS output for tests/cases/conformance/jsx/tsxReactEmit5.tsx
  Error: The baseline file tsxReactEmit5.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok conformance tests compiler tests for tests/cases/conformance/jsx/tsxReactEmit6.tsx Correct JS output for tests/cases/conformance/jsx/tsxReactEmit6.tsx
  Error: The baseline file tsxReactEmit6.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok conformance tests compiler tests for tests/cases/conformance/types/thisType/looseThisTypeInFunctions.ts Correct JS output for tests/cases/conformance/types/thisType/looseThisTypeInFunctions.ts
  Error: The baseline file looseThisTypeInFunctions.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok conformance tests compiler tests for tests/cases/conformance/types/thisType/thisTypeInFunctions.ts Correct JS output for tests/cases/conformance/types/thisType/thisTypeInFunctions.ts
  Error: The baseline file thisTypeInFunctions.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok conformance tests compiler tests for tests/cases/conformance/types/thisType/thisTypeInFunctionsNegative.ts Correct JS output for tests/cases/conformance/types/thisType/thisTypeInFunctionsNegative.ts
  Error: The baseline file thisTypeInFunctionsNegative.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok compiler tests compiler tests for tests/cases/compiler/contextualTyping24.ts Correct JS output for tests/cases/compiler/contextualTyping24.ts
  Error: The baseline file contextualTyping24.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok compiler tests compiler tests for tests/cases/compiler/declarationEmitDefaultExportWithTempVarName.ts Correct JS output for tests/cases/compiler/declarationEmitDefaultExportWithTempVarName.ts
  Error: The baseline file declarationEmitDefaultExportWithTempVarName.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok compiler tests compiler tests for tests/cases/compiler/declarationEmitDefaultExportWithTempVarNameWithBundling.ts Correct JS output for tests/cases/compiler/declarationEmitDefaultExportWithTempVarNameWithBundling.ts
  Error: The baseline file declarationEmitDefaultExportWithTempVarNameWithBundling.js has changed.
not ok compiler tests compiler tests for tests/cases/compiler/inferenceLimit.ts Correct JS output for tests/cases/compiler/inferenceLimit.ts
  Error: The baseline file inferenceLimit.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok compiler tests compiler tests for tests/cases/compiler/reactNamespaceJSXEmit.tsx Correct JS output for tests/cases/compiler/reactNamespaceJSXEmit.tsx
  Error: The baseline file reactNamespaceJSXEmit.js has changed.
  
      at writeComparison (built/local/run.js:76559:23)
not ok compiler tests compiler tests for tests/cases/compiler/typeReferenceDirectives11.ts Correct JS output for tests/cases/compiler/typeReferenceDirectives11.ts
  Error: Expected at least one js file to be emitted or at least one error to be created.
      at Context.<anonymous> (built/local/run.js:80256:31)
not ok compiler tests compiler tests for tests/cases/compiler/typeReferenceDirectives12.ts Correct JS output for tests/cases/compiler/typeReferenceDirectives12.ts
  Error: Expected at least one js file to be emitted or at least one error to be created.
      at Context.<anonymous> (built/local/run.js:80256:31)
not ok JSDocParsing TypeExpressions parseCorrectly keyword3
  Error: The baseline file JSDocParsing/TypeExpressions.parsesCorrectly.keyword3.json has changed.
  
      at writeComparison (built/local/run.js:76559:23)
```

### CODE REVIEW

**Comment by mhegazy** [comment]
code changes look good to me. :+1:

**Comment by sandersn** [comment]
0. Assert in services layer: logicalNotOperatorInvalidOperations
1. Need to port `__assign` polyfill that replaces `React.__spread`. (tsxReactEmit* and tsxExternalModule2, reactNamespaceJSXEmit)
2. Should not emit `this` function parameters. (looseThisTypeInFunctions, thisTypeInFunctions, thisTypeInFunctionsNegative, contextualTyping24)
3. Missing output (typeReferenceDirectives 11 and 12)

New baselines:

3. `System.register` is cleaned up with better style (declarationEmitDefaultExportWithTempVarName[WithBundling])
4. More faithful formatting: inferenceLimit
5. JSON output has one less newline (JSDocParsing/TypeExpressions.parsesCorrectly.keyword3.json)

**Comment by mhegazy** [comment]
@sandersn do you mind creating issues for these. here is the transforms issue template i have used:

https://github.com/microsoft/typescript/issues/new?title=%5BTransforms%5D%20&body=**Expected**%3A%0A%0A%60%60%60js%0A%60%60%60%0A%0A**Actual**%3A%0A%0A%60%60%60js%0A%60%60%60%0A%0AFailed%20tests%3A%0A*%20%20&labels[]=Bug&labels[]=Domain:%20Transforms

**Comment by sandersn** [comment]
Yep, working on it

**Comment by sandersn** [comment]
Done, filed 4 bugs.

**Pull request merged**
