### PR TITLE
Remove the unused text buffer(content) from ScriptInfo

### PR DESCRIPTION
**Pull request by sheetalkamat**
This removes the reference to source text from ScriptInfo

### CODE REVIEW

**Comment by mhegazy** [comment]
👍

**Comment by vladima** [comment]
:+1: 
also to mention that matching change was already made in [tsserver](https://github.com/Microsoft/TypeScript/blob/tsserverVS-WIP/src/server/scriptInfo.ts#L19) migration work

**Comment by mhegazy** [comment]
@sheetalkamat can you port this to the release-2.0 branch?

**Comment by sheetalkamat** [comment]
@mhegazy  done as 28938fbc303b2cb2c44b417f8939403b07faf91b

**Pull request merged**
