### PR TITLE
Fix regression of generic T assignability to Partial<T>

### LINKED ISSUE #32340: Investigate new RWC failures
We haven't merged our RWC failures from the last 9 days and they've _really_ added up (which is, I assume, why nobody is looking at them or merging them). _Most_ of them are benign - error span/message changes for the new overload errors, some expected duplicate definition errors related to the `Generator` types change and older `node` declaration files. _However_, there's one pattern of changes alone these lines (mostly within s4l):
```
        protected _buildState(props: P, initialBuild: boolean): Partial<S> {
            const newState = {
                optionToPresent: this._getOptionFromConf()
            } as S;
            return newState;
            ~~~~~~~~~~~~~~~~
!!! error TS2322: Type 'S' is not assignable to type 'Partial<S>'.
!!! error TS2322:   Type 'ILayoutExperimentState' is not assignable to type 'Partial<S>'.
        }
```
that's suuuuuper concerning, since a `T` is pretty much always supposed to be assignable to a `Partial<T>`, meaning we've broken something pretty important ❤️ 

I've merged the current baselines so we can actually browse thru the diffs again, but this particular regression needs to be seriously investigated and addressed. Best guess is that #32071 interacted poorly with another change added to `master` (or the other failure in `master` hid this one) over the same period, but I dunno.

### PR DESCRIPTION
**Pull request by andrewbranch**
I think this fixes #32340.

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot test this

**Comment by andrewbranch** [comment]
@weswigham yup, looks like the RWC baselines went back to normal

**Comment by andrewbranch** [comment]
@weswigham after I merge this, do I just merge the baseline PR on mseng?

**Comment by andrewbranch** [comment]
@typescript-bot run dt

**Comment by andrewbranch** [comment]
DT shows two instances of something like

```
1> No overload matches this call.
1>   Overload 1 of 2, '(props: Readonly<ProviderProps<AnyAction>>): Provider<AnyAction>', gave the following error.
1>     Property '[Symbol.observable]' is missing in type 'Store<IntlState>' but required in type 'Store<any, AnyAction>'.
1>   Overload 2 of 2, '(props: ProviderProps<AnyAction>, context?: any): Provider<AnyAction>', gave the following error.
1>     Type 'Store<IntlState>' is not assignable to type 'Store<any, AnyAction>'.
```

which coouuuld be related 😐

**Comment by andrewbranch** [comment]
[Same error occurs on current master](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=36134).

[Now running on master before #32071 was merged.](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=36134)

**Comment by andrewbranch** [comment]
Yeah, #32370 indicates that the DT failures here are completely unrelated. This PR only improves things.

**Comment by sandersn** [comment]
I haven't figured out what causes the two DT errors on master AND can't reproduce them locally. I'm not sure what is going on.

**Pull request merged**
