### PR TITLE
fix(49149): remove unneeded array overload to Object.freeze

### LINKED ISSUE #49149: Object.freeze overloads force the type to be recognized as an array (by the order of overloads)
# lib Update Request

## Configuration Check

My compilation *target* is `es5` and my *lib* is `["dom", "dom.iterable", "esnext"]`.
(Which I believe does not matter in this context as the definition of `freeze` is inside `lib.es5.d.ts` solely.)

## Missing / Incorrect Definition

`Object.freeze`
image
It is defined in a way that in IDEs it is always supposed the input is an array.
image

## Sample Code

```ts
Object.freeze<{someKey: 'someValue'}>({/* the problem is with autocomplete here (in IDEs) */});
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

---

I believe the overload that forces arrays is defined in this PR:
https://github.com/microsoft/TypeScript/pull/12434/files

And I believe just removing it will suffice (and the user of Object.freeze needs to specify its an array in case its an array)

---

If it is confirmed, I would be happy to create the PR for it.

### PR DESCRIPTION
**Pull request by nicolas377**
Fixes #49149

### CODE REVIEW

**Comment by andrewbranch** [comment]
You just need to [commit the baseline changes](https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#managing-the-baselines), assuming they look ok. If you’re not sure if they look ok, commit them anyway so we can take a look.

**Comment by nicolas377** [comment]
Thanks for that pointer! I'll take a look at those baselines and commit them (i might throw some questions in there if i have any i cant figure out).

**Comment by andrewbranch** [comment]
Chances are most/all of them are just position changes of symbols defined after Object.freeze in lib.es5.d.ts since they will have moved up a few lines.

**Comment by andrewbranch** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt

**Comment by andrewbranch** [comment]
@DanielRosenwasser I’m fairly convinced this is right, but maybe we should plan to merge this for 4.9?

**Comment by DanielRosenwasser** [comment]
Early 4.9 seems appropriate.

**Comment by andrewbranch** [comment]
Thanks @nicolas377!

**Comment by aghArdeshir** [comment]
Very nice :+1: 
I learned a lot through this PR. Thanks guys :+1: \

**Pull request merged**
