### PR TITLE
Show dts errors with --noEmit, fix some of the incremental noEmit issues and support dts diagnostics and fix the caching diagnostics in program

### LINKED ISSUE #59024: `isolatedDeclarations` not giving related errors under `noEmit`
### 🔎 Search Terms

"isolated declarations", "isolated declarations noEmit"

### 🕗 Version & Regression Information

- This changed in commit or PR e62418e8689738b93b627aac1116e02a48b0f9d1 (before that commit TS didn't recognize the option on tsconfig)

### ⏯ Playground Link

_No response_

### 💻 Code

```ts
// must have a return type, should give error
function thingThatShouldErrorOnIsolatedDeclarations() {
  return 0;
}
```

### 🙁 Actual behavior

`tsc --noEmit --isolatedDeclarations` doesn't report any error, even though `tsc --isolatedDeclarations` does (vscode does too)

### 🙂 Expected behavior

`tsc --noEmit --isolatedDeclarations` reports the error, just like it does without the `--noEmit` flag

### Additional information about the issue

tsconfig used:
```json
{
  "compilerOptions": {
    "target": "es2022",
    "lib": ["esnext"],

    "module": "esnext",
    "moduleResolution": "bundler",

    "outDir": "dist",
    "esModuleInterop": true,
    "verbatimModuleSyntax": true,

    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "noEmitOnError": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "declaration": true,

    "strict": true
  }
}
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
- Enable displaying dts errors if declarations are enabled with `noEmit` 8b6cc163ada14e154b91765ec592bae7a7c37ce3
- Store the dts errors in the buildInfo in incremental mode so we dont have to query them again just like if we had done emit 8b6cc163ada14e154b91765ec592bae7a7c37ce3
- Fixed issue with syntax errors in incremental mode with `noEmit` where it didn't record the `changeSet` and resulted in incorrect state 61b1933
- Fixed d.ts diagnostics caching in the program since they are anyways queried one file at a time 32a807519fb96b8caab52603bf2931369d536ff6

Fixes #59024

### CODE REVIEW

**Comment by jakebailey** [comment]
Is this something we should consider backporting to 5.5?

**Comment by sheetalkamat** [comment]
> Is this something we should consider backporting to 5.5?

Dont think so. Its not a regression and this depends on other changes that are already in main but not in 5.6 and porting to 5.5 wont be easy and will need more rework to ensure things are working

**Comment by sheetalkamat** [comment]
@typescript-bot test it

**Comment by jakebailey** [comment]
@typescript-bot test it

GH outage made this not work.

**Review by weswigham — COMMENTED** [review]
Hm, I guess we can also remove the restriction forbidding `--noEmit` and `--noCheck` together since with this if you do `--noEmit` and `--noCheck` you can still get declaration emit errors.

**Review by weswigham — APPROVED** [review]

**Comment by jakebailey** [comment]
Hm, how did self-compiler get faster?

**Comment by sheetalkamat** [comment]
huh lint!!!

**Comment by sheetalkamat** [comment]
> Hm, how did self-compiler get faster?

I think because we have `noEmitOnError` and now the caching works for the declaration diagnostics much better so they arent recalculated again when emitting file.

**Comment by robpalme** [comment]
These are excellent fixes. Thank you, Sheetal!

**Pull request merged**
