### PR TITLE
Remove the extension.d.ts and move the content to core.d.ts

### LINKED ISSUE #3979: Incorrect type definition for TypedArray `set(array, offset)` functions
TypeScript 1.5.3 defines the following type signature for `Uint8Array#set(array, offset)`:

```ts
interface Uint8Array {
    set(array: Uint8Array, offset?: number): void;
}
```

And for `Uint16Array#set(array, offset)`:

```ts
interface Uint16Array {
    set(array: Uint16Array, offset?: number): void;
}
```

Similar type signatures are defined for the other TypedArray view types.

These definitions match neither ES6 nor the obsolete Kronos TypedArray spec.

For the `array` argument, ES6 accepts any TypedArray view type, or any object with a `length` property (in other words, an array, or something that acts like an array).

My reading of the Kronos Spec is that it is intended to match ES6, although it is a bit more ambiguous. In practice browsers seem to follow ES6.

The main difficulty for me is that TypeScript 1.5.3 doesn’t accept a `number[]` as the `array` argument. This is different from TypeScript 1.4.x where `number[]` was the *only* permitted type for the `array` argument. As a consequence I have to either cast to `any` or write inefficient loops to copy data from ordinary arrays into typed arrays.

I think the type definition should be:

```ts
interface Uint8Array {
    set(array: ArrayLike<number>, offset?: number): void;
}

// and so on for the other types.
```

In practice this will accept anything ES6 accepts, including any of the TypedArray view types.

At the very least please add `number[]` as a valid type for the `array` argument :).

### PR DESCRIPTION
**Pull request by zhengbli**
Also change the set function parameter type in TypedArrays.

Fix #3979

### CODE REVIEW

**Comment by zhengbli** [comment]
@mhegazy could you take a look? As it is a fairly big change

**Comment by mhegazy** [comment]
i tried, but @github interface was not very helpful. will pull it locally and take a look.

**Comment by mhegazy** [comment]
can you remove the banner 
```ts
/////////////////////////////
/// IE10 ECMAScript Extensions
/////////////////////////////

```

**Comment by mhegazy** [comment]
also what about the constructor, should it have an overload with ArrayLike<number>?

**Comment by mhegazy** [comment]
you missed `Uint8ClampedArray`, it was defined in es6.d.ts but not in extensions. when you add it, please put it after Uint8Array to make the diff easier to follow.

**Comment by zhengbli** [comment]
I updated the aforementioned spots, and I'll update the baselines once the code is settled.

**Comment by mhegazy** [comment]
:+1: 
you will need to update your baselines one more time though.

**Pull request merged**
