### PR TITLE
Fix JSX inference with excess properties

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/53789

it's basically the same fix as the one [here](https://github.com/microsoft/TypeScript/pull/17430), just applied to JSX

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]
This feels accurate but @weswigham probably knows better

**Comment by Andarist** [comment]
@jakebailey any chance of landing this into the just started 5.2? :)

**Comment by jakebailey** [comment]
This PR is 100 commits behind main at this point, but let me close/reopen just to recheck CI. That and

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
FWIW back when I reviewed this last month, I did go do the git history checking to verify, and it is effectively the same fix and the new flag that's used instead now (compared to that old PR) would have been updated too, so, this to me seems sound (but I've already said that).

**Pull request merged**
