### PR TITLE
Pick PR #54450 into release-5.0: Resolve tslib re-exports before checking arity

### PR DESCRIPTION
**Pull request by andrewbranch**
PR #54450

### CODE REVIEW

**Comment by andrewbranch** [comment]
Related: https://github.com/microsoft/TypeScript/pull/54328 (will probably conflict since change overlaps)

**Comment by jakebailey** [comment]
I need to go fix up the browser integration test to do things a little differently; right now it npm installs a new package and that means that we get unexpected versions of other deps on old release branches like this one, which as you've seen can cause problems.

**Comment by sandersn** [comment]
@andrewbranch Is this still needed?

**Comment by andrewbranch** [comment]
It would be nice but it’s up to @DanielRosenwasser if he wants to do an older patch for this.

**Pull request closed without merging**
