### PR TITLE
Try using runtests-parallel for CI

### PR DESCRIPTION
**Pull request by weswigham**
Changes `npm test` to run `jake runtests-parallel` rather than `jake runtests`.

### CODE REVIEW

**Comment by sandersn** [comment]
So it looks like the Linux machines are reporting 32 cores, which causes some tests to time out. Probably we should explicitly specify 2 threads, because the Mac machine ran the tests fine that way.

**Comment by weswigham** [comment]
I've added `workerCount=2` to travis's environment configuration and rerun the build. Let's see how it goes.

**Comment by weswigham** [comment]
@sandersn This looks like it's getting us some nice gains on test times on CI. I'm going to experiment with running 4 and 6 workers to see if we can get better numbers, but I think definitely 2 should happen.

**Comment by weswigham** [comment]
It seems like the mac worker benefits from this less than the linux workers (or rather, doesn't see any benefit at all); but 4 workers may or may not be better than two:
image
On linux it looks worse on stable, but better on 4 and 0.10. I think I can set this per-matrix-entry in the `.travis.yml`, so it's possible to use a different optimal value for each version if need be.

**Comment by sandersn** [comment]
:+1:

**Comment by sandersn** [comment]
Do you want to merge this now? It sounds like you've done enough experimenting to find the best number of workers.

**Comment by weswigham** [comment]
I'm satisfied with the results on 'nix, but on OSX I'm still really disappointed with our performance numbers. Still. This is an improvement, so I'll merge it. (Can always revert it or modify it if we have problems)

**Pull request merged**
