### PR TITLE
Remove extra checkDefined in visitEachChildOfJsxExpression

### LINKED ISSUE #52479: JSX comments break Transformer API in TS 5.0 beta
# Bug Report

### 🔎 Search Terms

transformer jsx comment 5.0

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.9.4 and 5.0.0-beta
- Still present in @next

### ⏯ Playground Link

Not available because Playground has not transformer options

### 💻 Code

Given the following file:

```typescript
// src/index.tsx
function test () {
  return <>
    {/* This comment breaks the transformer */}
  </>
}
```

and the following transformer

```javascript
// transformer.js
const ts = require('typescript');

// noop transformer
module.exports = (context) => {
  function visitor(node) {
    return ts.visitEachChild(node, visitor, context);
  }
  return (node) => {
    return ts.visitNode(node, visitor, context);
  };
}
```

TypeScript throws this Error when compiling

```
Error: Debug Failure.
    at visitEachChildOfJsxExpression (/.../node_modules/typescript/lib/typescript.js:85838:19)
    at Object.visitEachChild (/.../node_modules/typescript/lib/typescript.js:84879:35)
    at visitor (/.../transformer.js:6:13)
    [...]
```

To run this I used this setup with Webpack and ts-loader: (I tried to keep it as short as possible)

```javascript
// package.json
{
  "name": "ts-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^18.2.0",
    "ts-loader": "^9.4.2",
    "typescript": "^5.0.0-beta",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1"
  }
}
```

```javascript
// webpack.config.js
const transformer = require('./transformer');

module.exports = {
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  module: {
    rules: [{
      test: /\.tsx?$/,
      use: {
        loader: 'ts-loader',
        options: {
          getCustomTransformers: (program) => ({
            before: [transformer],
          }),
        },
      },
    }]
  },
}
```

```javascript
// tsconfig.json
{
    "compilerOptions": {
        "jsx": "react-jsx"
    }
}
```

### 🙁 Actual behavior

Running `npm run build` throws the described error

### 🙂 Expected behavior

No error is thrown

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #52479

### CODE REVIEW

**Comment by jakebailey** [comment]
Checked all of the other `checkDefined`s in this section; this was the only wrong one. I'll have to look into something we can do to `checkDefined` that makes it fail if you give it something that's definitely defined.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
we would need something which checks whether or not a result of a checkDefined is used only in a place which already accepts undefined.

[Would this fit the bill?](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzAAtwBrAERES1RGAB4AVAGngFV4QAPDEVYAZ3gN4AH3ipkECKPhpQVGsAB8ACgCwAKHjb4ANygRkIAFxCZEqTLmVqtTQEpT7Ljz6CAcnneToAIwggdKxK8AD8bPCmaCSoOADuqADcmpoBGPCcpvwYMNQA5vAAvATEYOQ2iioARACMAEwAzFXwUILZuagFYtYKtPbJGmnwAJ5ZOflWfBW0RSWkFL3A1fVNLW3jnZPytsD9qSDpAF5RU4uzRPPTS7WNza3w7RPdpzv9QA)

```ts
export function checkDefined<T, U extends T | null | undefined>(
    value: T | null | undefined,
    message?: string,
    stackCrawlMark?: AnyFunction
): U extends NonNullable<U> ? U : unknown {
    assertIsDefined(value, message, stackCrawlMark || checkDefined);
    return (value satisfies NonNullable<T> as any);
}
```

**Comment by DanielRosenwasser** [comment]
FWIW, if I do that, here are the errors I see in `visitorPublic.ts`:

```
src/compiler/visitorPublic.ts:655:13 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | BindingName'.

655             Debug.checkDefined(nodeVisitor(node.name, visitor, isBindingName)),
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/compiler/visitorPublic.ts:678:13 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string | PropertyName'.

678             Debug.checkDefined(nodeVisitor(node.name, visitor, isPropertyName)),
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/compiler/visitorPublic.ts:1055:13 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'BinaryOperator | BinaryOperatorToken'.

1055             tokenVisitor ? Debug.checkDefined(nodeVisitor(node.operatorToken, tokenVisitor, isBinaryOperatorToken)) : node.operatorToken,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/compiler/visitorPublic.ts:1457:13 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'Expression | undefined'.

1457             Debug.checkDefined(nodeVisitor(node.expression, visitor, isExpression)));
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jakebailey** [comment]
The first three appear to be cases where our factories accept string or `SyntaxKind` for convenience (but can't actually appear during visit), so there's something weird happening with that signature, I think.

The last one is this bug, so it did catch that at least. But I'm guessing if there were more, it would have caught them too (with the false positives present).

**Comment by jakebailey** [comment]
Another way to do this would be to transform all `Debug.checkDefined` calls to `!` and then see if eslint complains, but that is of course a bit more work.

**Comment by jakebailey** [comment]
I wrote the above transform and then ran eslint; this is in fact the only place we use checkDefined on a definitely defined value. Good to know that we don't have any more of these kinds of potential bugs.

**Pull request merged**
