### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by TarunavBA**
Updated readme

Fixes #

### CODE REVIEW

**Comment by TarunavBA** [comment]
@typescript-bot approve it! :)

**Comment by tjjfvi** [comment]
Using a comma there creates a comma splice / run-on sentence. It could be changed to a semicolon, but the original, with its em dash, is already correct.

**Comment by orta** [comment]
Thanks for the PR, but I agree with @tjjfvi - thanks for giving a PR to TypeScript a shot!

**Comment by TarunavBA** [comment]
> Using a comma there creates a comma splice / run-on sentence. It could be changed to a semicolon, but the original, with its em dash, is already correct.

Ok @tjjfvi I learned something new today! 😃

**Pull request closed without merging**
