### PR TITLE
Make the falsy part of any/unknown any/unknown

### LINKED ISSUE #39113: Using && with spread operator causes "overridden" error if one of the types is "any"
We are having problems with TypeScript 3.9 upgrade for our repositories and the spread operator and "&&" with any types. TypeScript compiler says the value will be always overridden even though an any type isn't 100% always null/undefined.

**TypeScript Version:**  3.9.5
**Search Terms:**
- specified more than once, so this usage will be overwritten.
- any type and spread operator

**Code**

Doesn't work
```ts
let isTreeHeader : any = null!;
function foo(){
    return {
        display: "block",
        ...(isTreeHeader && {
          display: "flex",
        })
    }
}
foo()
```

Works
```ts
let isTreeHeader : number = null!;
function foo(){
    return {
        display: "block",
        ...(isTreeHeader && {
          display: "flex",
        })
    }
}
foo()
```

**Expected behavior:**

`any` type can be undefined or can have a non nullable value so we shouldn't get an error with the spread operator

**Actual behavior:**

'display' is specified more than once, so this usage will be overwritten.ts(2783)

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=2&pc=22#code/DYUwLgBAlgzgKgJxCAEiAhgExAiAuCdAOwE8IBeCIgV2GAEIBuAKADNqiBjMKAeyIitevABQBKAN7MISMNQQCpETLAAOwdCQIAiAEbBenANbaANNIB0VkbETI0WHBABkziEpUx1mna1AAPM2kAXzEQ5mC2YXEgA

**Related Issues:**

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #39113

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
We're debating 4.0 vs 4.1 so please hold on merging for now

**Comment by DanielRosenwasser** [comment]
Perf numbers seem reasonable, but someone should take another look.

Office UI Fabric seems to have some existing issues I can't tease out.

Here's a few user test changes

Uglify Type Differences

https://github.com/typescript-bot/TypeScript/pull/58/files#diff-515e686b9c133473b3091193f6519572L138

```diff
- node_modules/uglify-js/lib/compress.js(6307,25): error TS2403: Subsequent variable declarations must have the same type.  Variable 'code' must be of type 'string', but here has type '{ get: () => string; toString: () => string; indent: (half: any) => void; indentation: () => number; current_width: () => number; should_break: () => boolean; has_parens: () => boolean; newline: () => void; print: (str: any) => void; ... 23 more ...; parent: (n: any) => any; }'.
+ node_modules/uglify-js/lib/compress.js(6307,25): error TS2403: Subsequent variable declarations must have the same type.  Variable 'code' must be of type 'string', but here has type '{ get: () => string; toString: () => string; indent: (half: any) => void; indentation: () => number; current_width: () => number; should_break: () => any; has_parens: () => boolean; newline: () => void; print: (str: any) => void; ... 23 more ...; parent: (n: any) => any; }'.
```

https://github.com/typescript-bot/TypeScript/pull/58/files#diff-515e686b9c133473b3091193f6519572L150

```diff
- node_modules/uglify-js/lib/compress.js(7635,29): error TS2367: This condition will always return 'false' since the types 'boolean' and 'string' have no overlap.
```

This one seems questionable, but I can't figure out what the file looked like at that point.
____

VS Code had some breaks though:

https://github.com/typescript-bot/TypeScript/pull/58/files#diff-0e62d568d28b82cee9e66b2b8fafd290R7-R12

```diff
+ [XX:XX:XX] Error: /vscode/src/vs/platform/workspace/common/workspace.ts(85,3): Type 'unknown' is not assignable to type 'boolean'.
+ [XX:XX:XX] Error: /vscode/src/vs/platform/workspace/common/workspace.ts(130,3): Type 'unknown' is not assignable to type 'boolean'.
+ [XX:XX:XX] Error: /vscode/src/vs/workbench/common/editor/editorGroup.ts(53,2): Type 'unknown' is not assignable to type 'boolean'.
+ [XX:XX:XX] Error: /vscode/src/vs/platform/workspace/common/workspace.ts(85,3): Type 'unknown' is not assignable to type 'boolean'.
+ [XX:XX:XX] Error: /vscode/src/vs/platform/workspace/common/workspace.ts(130,3): Type 'unknown' is not assignable to type 'boolean'.
+ [XX:XX:XX] Error: /vscode/src/vs/workbench/common/editor/editorGroup.ts(53,2): Type 'unknown' is not assignable to type 'boolean'.
```

Note there are really 3 breaks, I'm not sure why the diff repeats itself. Some of these are technically correct. Kind of an obvious pattern around defining type predicates.

https://github.com/microsoft/vscode/blob/182db07de2745fe3a6369f4ad80ae930e006a99b/src/vs/workbench/common/editor/editorGroup.ts#L50-L54

https://github.com/microsoft/vscode/blob/182db07de2745fe3a6369f4ad80ae930e006a99b/src/vs/platform/workspace/common/workspace.ts#L84-L87

https://github.com/microsoft/vscode/blob/182db07de2745fe3a6369f4ad80ae930e006a99b/src/vs/platform/workspace/common/workspace.ts#L129-L134

**Comment by andrewbranch** [comment]
I think the VS Code ones are good breaks. It’s not unique to type predicates, though they may be a common manifestation since the input is usually `any` or `unknown`. You’d get the same error if the return type was just `boolean`:

```ts
function isThing(x: any): boolean {
    return x && typeof x === 'object' && x.blah === 'foo';
}
```

This passes checking today but shouldn’t, since the actual domain of the return expression includes `""`, `0`, `null`, and `undefined`. Savvy users already know to deal with this kind of error by prefixing the first `x` with `!!`, since you’d have to do that if the input type included falsy components but wasn’t `any` or `unknown`:

```ts
function isThing(x: string | number | Record<string, any>): boolean {
    return x && typeof x === 'object' && x.blah === 'foo';
}
```

[[Playground]](https://www.typescriptlang.org/play/#code/GYVwdgxgLglg9mABDAzgFQBYzAcwBQAeAXIilAE7Y6IA+iYIAtgEYCm5tiASqxHOQBMAPGUq4ANIgCGYAJ4A+AJQlmcOABtWMxAG8AUIkOJyrKCHJICiAGTXEUWQAdWcYIisBeL4gDkcZgBWvFA+NnYEAHTM6lIYiF4evsBqPgDcegC+QA)

**Comment by DanielRosenwasser** [comment]
Yeah, if you're using `unknown`, you sort of *want* to know about these breaks. If you're using `any`, well, you won't get a break in those cases.

**Comment by andrewbranch** [comment]
I also don’t know how to see the uglify source either, but I can give you a simplified example of how this change would correctly remove that error you said looks questionable: [playground](https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEA3W8BGB7dEBcbMRCgDsBuAKAIBd4APXYgT3gF54AiN8sgSwDN4AFAJrwAZKLxYAlC2asOMgN5l4q+AHp18AIJhKAVygQIDADTxKAC24BneGHRFg3St0fxb8IwHcoDO5Qw+gjYAD5kAL5kQA)

**Comment by DanielRosenwasser** [comment]
(also, I don't know how to look at the other diffs, DevOps is too confusing)

**Comment by DanielRosenwasser** [comment]
DefinitelyTyped tests

```
Error: /home/vsts/work/1/s/dtslint-runner/DefinitelyTyped/types/knockout/test/index.ts:710:5
ERROR: 710:5  expect  TypeScript@local expected type to be:
  KnockoutObservable<number>
got:
  KnockoutObservable<number | null>
```

```
Error: /home/vsts/work/1/s/dtslint-runner/DefinitelyTyped/types/testing-library__vue/testing-library__vue-tests.ts:69:21
ERROR: 69:21  expect  TypeScript@local compile error: 
Argument of type 'RegExp' is not assignable to parameter of type 'ARIARole'.
  Type 'RegExp' is not assignable to type '"alertdialog"'.
```

```
Subsequent property declarations must have the same type.  Property 'data' must be of type 'T | undefined', but here has type 'any'.
ERROR: 79:12  expect  TypeScript@local compile error: 
Subsequent property declarations must have the same type.  Property 'data' must be of type 'T', but here has type 'any'.
ERROR: 90:13  expect  TypeScript@local compile error: 
Subsequent variable declarations must have the same type.  Variable 'MessageEvent' must be of type '{ new <T>(type: string, eventInitDict?: MessageEventInit<T> | undefined): MessageEvent<T>; prototype: MessageEvent<any>; }', but here has type '{ new (type: string, eventInitDict?: MessageEventInit<any> | undefined): MessageEvent<any>; prototype: MessageEvent<any>; }'.
```

**Comment by DanielRosenwasser** [comment]
I think RWC came back unaffected?

**Comment by andrewbranch** [comment]
The DefinitelyTyped failures are all unrelated; they exist in the nightly dtslint run against master.

**Comment by orta** [comment]
@typescript-bot pack this

**Comment by andrewbranch** [comment]
From design meeting:

- Explore propagating a better assignability error for a falsy-unknown source
- Merge in 4.1

**Comment by andrewbranch** [comment]
> Explore propagating a better assignability error for a falsy-unknown source

This turns out to be a little bit difficult for two reasons:

1. Doing the right thing with `falsyUnknownType` in a union requires tracking more info about constituent types than we currently do. If you union a falsy unknown with other definitely falsy types, the result should be falsy unknown. Otherwise, it should just be `unknown`. We don’t currently compute falsy flags for union constituents so I’m concerned about what this could do to performance.
2. Even if we successfully propagate the falsy unknown type, I think a specialized error message isn’t very useful without being able to identify where the falsy unknown came from, and I’m not sure how best to walk back to that point. Example [[playground]](https://www.typescriptlang.org/play?ts=4.0.0-pr-39529-22#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwGccBbEAeQwAsQYBhGLDGrKACgA8AueKVATwCU3AEY4cEELwDcAKFCRYCFOmx4eqHFRq08wRrlSsh8UeMmpZM5ZgPwsBACqUsqAOYduaANYaA7qmNTCV54AG8ZeHgwPAIMeDgCZAg4gF54dngAMkz4DD4ABxAcRHT4FPL4ACIcYQArcAxKrJyiUgpqOgYmBjZ2AVlIuAxkGHxeTQ6dVD1VQwF4AH54kETk+G5EKAgCEFkAXxkgA):
   
    ```ts
    function isThing(x: unknown): boolean {
      const result = x && typeof x === "object" && someOtherCriteria(x);
      return anotherCondition() ? result : false;
    }
    ```

    Ideally, you want the error elaboration / related info to highlight the `x` in `x && typeof x ...`, and I’m not sure the best way to propagate that through to or walk back from the assignability check.

**Comment by andrewbranch** [comment]
Talked to @RyanCavanaugh and decided to merge this now—there may be no worthwhile way to track the falsy unknown back to the expression where it originated, and it’s better to get this in 4.1 sooner rather than later.

**Comment by DanielRosenwasser** [comment]
Can you add this to https://github.com/microsoft/TypeScript/wiki/Breaking-Changes @andrewbranch?

**Comment by andrewbranch** [comment]
Done 👍

**Comment by DanielRosenwasser** [comment]
Thank you!

**Pull request merged**
