### PR TITLE
Fix indexed access relation

### LINKED ISSUE #21185: Spurious "A type predicate's type must be assignable to its parameter's type"
**TypeScript Version:**  2.7.0-dev.20180113

**Code**

This type operator from the [Unionize](https://github.com/pelotom/unionize) library:

```ts
type Predicates<TaggedRecord> = {
  [T in keyof TaggedRecord]: (variant: TaggedRecord[keyof TaggedRecord]) => variant is TaggedRecord[T]
}
```

**Expected behavior:**

Should compile, and does in `typescript@2.6.2`.

**Actual behavior:**

Fails to compile in `typescript@next` with

```
A type predicate's type must be assignable to its parameter's type.
  Type 'TaggedRecord[T]' is not assignable to type 'TaggedRecord[keyof TaggedRecord]'.
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #21185 

Previously, `structuredTypeRelatedTo` only checked the object types of an index access type, and only if the index types were identical. Now both checks call `isRelatedTo` recursively. Before #17912 this was not a big problem because the preceding constraint check often erroneously used `any` as the constraint.

### CODE REVIEW

**Comment by sandersn** [comment]
I tested Definitely Typed with this change, since I expect master to be *more* broken after #17912. I didn't see any breaks -- the only failures were a result of the test automation.

However, at least one test timed out just before the tests finished running. There has been some performance regression recently since @weswigham observed this for the RWC tests and there have been a couple of bugs about slow compilation recently.

**Comment by weswigham** [comment]
This now seems to mimic what inference takes for granted, which is nice. I do wonder if we can tell if it'd be faster to check the index types or object types first, though. My intuition says that the index types are likely to be less complicated, so maybe we should compare those first; but I have no real data backing that.

**Comment by sandersn** [comment]
@weswigham I plan to investigate performance today, although if there is any impact from this change, it’s probably a result of #17912 getting rid of the erroneous anys, which just means more checking overall. Still, I should test both orders.

**Comment by sandersn** [comment]
The definitely typed and user tests that were timing out appear to be a result of npm slowness. I'll start looking at the bugs about compiler slowness instead.

**Pull request merged**
