### PR TITLE
feat(#48863): Split ES5 lib into individual parts

### PR DESCRIPTION
**Pull request by iainjreid**
This PR hopes to address #48863, the scale of the changes is small, and non breaking, but the impact on the tests is pretty huge. More context can be found in the linked issue explaining the changes in more depth.

### CODE REVIEW

**Comment by iainjreid** [comment]
Some backstory and a lesson learned whilst implementing these changes...

I originally tried to exclude the new `es2009.x` library files by passing `["lib.*"]` as the `exclude` argument to [`tryReadDirectory`](https://github.com/microsoft/TypeScript/blob/162224763681465b417274383317ca9a0a573835/src/services/stringCompletions.ts#L510) to reduce the impact on the tests, but I found that doing so actually added more complexity than it would have otherwise solved...

**Comment by sandersn** [comment]
@typescript-bot perf test this

(though I'm not sure how well the perf tests measure startup time)

**Comment by sandersn** [comment]
I feel like this is something we need to discuss in a design meeting before reviewing since the code change is fairly simple but also hugely susceptible to going stale. Let's see what performance is like and then I'd vote to close the PR until the design is finalised.

**Comment by iainjreid** [comment]
@sandersn thanks for the update, I made a comment in [my initial issue](https://github.com/microsoft/TypeScript/issues/48863)   outlining a liking better solution to the functionality I'm looking for, but I still think that splitting up the ES5 library will be hugely beneficial to the end goal!

**Comment by sandersn** [comment]
No significant performance difference that I noticed.

**Comment by sandersn** [comment]
To help with PR housekeeping, I'm going to close this until its bug is ready.

**Comment by iainjreid** [comment]
For future reference, what could I have done differently to get this one pushed through @sandersn? I understand that a lot of files were changed, and reviewing this would have taken some time, but the overall impact was very low, almost negligible.

I'm still keen to champion this improvement if you're accepting contributions from outside collaborators 👍

**Comment by sandersn** [comment]
That's a tricky one. The state Awaiting More Feedback on the issue tracker means that we're waiting for more people to chime in with reasons why they want this feature. Sometimes that's to know whether more than one person wants it, sometimes that's to find out the variety of things that could be done, and to decide which should be done.

We get so many bugs and PRs that we generally don't review any outside PR until there's an accepted bug for it.

Finally, for this particular feature: changing the lib, even in obviously non-breaking ways, somehow ends up breaking people. So merging this PR would make us commit to finding and fixing breaks in important libraries before the next release.

**Pull request closed without merging**
