### PR TITLE
Normalize paths in GetEditsForFileRename

### PR DESCRIPTION
**Pull request by amcasey**

### CODE REVIEW

**Comment by amcasey** [comment]
@mhegazy Does this need to be ported anywhere?

**Comment by mhegazy** [comment]
Do we have a bug? what is the severity of the issue?

**Comment by amcasey** [comment]
No, I just noticed it while trying to implement semantic rename in VS.  Without this fix, VS will have to do its own normalization (to the server's preferred format) for this request to succeed.

**Comment by mhegazy** [comment]
let's leave it in master then for now.

**Pull request merged**
