### PR TITLE
Exclude parameters of non-inferrable signatures from inference

### LINKED ISSUE #53748: Cannot infer generics through n>=2 functions of an argument
# Bug Report

### 🔎 Search Terms

arguments, generics, inference, two or more, variance

### 🕗 Version & Regression Information

- This changed between versions 4.7 and 4.8+ (stopped working on 4.8+)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAXAngBwQYShCAjKYA1gDwCCMA5gM7wgAeiIAdsDVE8gNoC6ANPAHkAron4AlAHzwAvPAAUAOiWxqALnjlqAShlS5wKIijrhiHdKliA3AChQkWAgBmQpmEQBLAPZN4TgoheMMjEphJyWupklDT0jCxsHDzi4WDYeASE6lg4+ETR1PymKeZ6SgoqVOqaVKXw1jY2YD5UiPAAtlCECLL+7kEhAN4ewOqtMB5MFPxQFCDqTELtuCAwAL484Vq2TS1tQlSrVAIAbqukczIdXSBycrPz8IvLq3UGRrrwgzbwv-BwiCEMF87ygCicHggjBgcgOq0+cJgFUuElkD22NjWGN2TFa8CgwCEUJoskRxzOMAutwAjAAODFAA)

### 💻 Code

```ts
declare type Callback<Args extends any[], Out, R> = (...args: Args) => (data: Out) => R;
declare function factory<Out>(): <Args extends any[], R>(callback: Callback<Args, Out, R>) => (...args: Args) => R;

const make = factory<{id: string, age: number}[]>();

// Errors here
const usersOverAge = make((age: number) => data => {
    return data.filter(user => user.age >= age);
});
```

### 🙁 Actual behavior

The code errors with a function not being assignable to a signature, and generics not being inferred correctly.

### 🙂 Expected behavior

The function definition is passed as expected and generics are correctly inferred

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53748.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by jakebailey** [comment]
@typescript-bot run dt

npm timeout :(

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Review by jakebailey — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request merged**
