### PR TITLE
[Experiment] Enum annotation sugar

### LINKED ISSUE #16464: Sugar String Enum identifier
# Sugar String Enum identifier

It would be great to actually be able to specify that you are using a string enum, and then you'd only have to write out the 'value' once, and it would be automatically made into a string matching the enum code.

`stringenum Action {
   LOAD_PROFILE,
   ADD_TASK,
   REMOVE_TASK
}`

instead of 

`enum Action {
   LOAD_PROFILE = "LOAD_PROFILE",
   ADD_TASK = "ADD_TASK",
   REMOVE_TASK = "REMOVE_TASK"
}
`

Thanks for all the great work!

### PR DESCRIPTION
**Pull request by Kingwl**
Seems not a big feature(2-4 lines for core), but a nice sugar.

Fixes #16464

### CODE REVIEW

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by Kingwl** [comment]
Thanks!

**Comment by wangziling** [comment]
Thanks @Kingwl, very helpful.

In additional, maybe this scenario need to be supported.

```js
const enum A: string {
    a,
    b,
    c = 'deded',
    e
}
```

**Comment by sandersn** [comment]
This experiment is pretty old, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
