### PR TITLE
fix(41176): Missing Compiler API predicate function: isTemplateLiteralTypeNode

### LINKED ISSUE #41176: Missing Compiler API predicate functions: isTemplateLiteralTypeNode
## Search Terms

isTemplateLiteralTypeNode

## Suggestion

TypeScript's Compiler APIs include `is` functions for all kinds of Nodes. For example, `isClassDeclaration`, `isBigIntLiteral`, and so on.

In TypeScript 4.1.0-beta, a new kind of node is introduced: `TemplateLiteralTypeNode`, but no `isTemplateLiteralTypeNode` predicate function is exposed. For consistency with other kinds of Nodes, TypeScript should arguably also expose such a predicate function.

## Use Cases

- Custom Transformers (visiting and transforming Nodes in an AST)
- Working with the Compiler APIs
- etc

## Examples

```typescript
function visitNode (node: TS.Node, context: TS.TransformationContext, typescript: typeof TS): TS.VisitResult<TS.Node> {
    if (typescript.isTemplateLiteralTypeNode(node) {
        return visitTemplateLiteralTypeNode(node, context, typescript);
    }

    else if (...) {
        ....
    }
}
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #41176

### CODE REVIEW

**Comment by wessberg** [comment]
Thanks! You'll also need `isTemplateLiteralTypeSpan` to fix the issue :-)

**Comment by a-tarasyuk** [comment]
@wessberg `isTemplateLiteralTypeSpan` exists

https://github.com/microsoft/TypeScript/blob/cd43b3b588dc9add91a1a6f411eadd25c7baba2e/src/compiler/factory/nodeTests.ts#L236-L238

**Comment by wessberg** [comment]
Ah, I missed that one. LGTM.

**Comment by orta** [comment]
This seems reasonable to me 👍🏻

**Pull request merged**
