### PR TITLE
redo #28564

### PR DESCRIPTION
**Pull request by sandersn**
Redo #28564

I haven't looked at the baseline changes; maybe they're horrible.

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot perf test this

**Comment by sandersn** [comment]
No impact to check time, but it doesn't mean much without knowing how many overload errors are in the perf test suite. That's the next thing I need to look at.

**Comment by weswigham** [comment]
Hey, it at least means that the hypothesis of "this should only affect compilations with errors" is probably true~

**Comment by sandersn** [comment]
So, uh, here are the numbers of getCandidateForOverloadFailure calls. They are small. The number in parenthesis is the total number of resolveErrorCalls; that function is called a number of places.

||Before |    After|
|-------|-------|-------|
| Angular | 0 (4415) |  8  (4407)|
| TFS    | 0 (25)   |   0 (25) |
| Monaco | 0 (17)   |  2  (14) |

I'm still leaning toward yes since it appears (1) to be pay-to-use (2) angular, the project that uses it *a little*, on the whole checks at the same speed.

@weswigham if you agree, sign off and you or I can merge this.

**Comment by sandersn** [comment]
Actually, I want to look over the baseline changes before I sign off. So far the look benign, but there are a lot of them.

**Comment by sandersn** [comment]
Note: breaks jest types in the following call:

```ts
const spy3Mock = spy3
    .mockImplementation(() => '')
    .mockImplementation()
    // $ExpectError
    .mockImplementation((arg: {}) => arg)
    .mockImplementation((...args: string[]) => args.join(''))
    .mockImplementationOnce(() => '')
    .mockName('name')
    .mockReturnThis()
    .mockReturnValue('value')
    .mockReturnValueOnce('value')
    .mockResolvedValue('value')
    .mockResolvedValueOnce('value')
    .mockRejectedValue('value')
    .mockRejectedValueOnce('value');
```

The last four calls expect an argument of type `never` now instead of `string`. This seems wrong, or at least unintended.

**Comment by sandersn** [comment]
Oh, the tests were ALWAYS an error, it's just the we now report downstream errors after the expected error on `mockImplemention((arg: {}) => arg)`.
If you move the `mockResolveValue` calls above that line, you get the error even before this change.

The test *should* be passing a promise to those calls, so that's probably the right fix.

**Comment by weswigham** [comment]
@sandersn _Somehow_ this has caused some concerning regressions in `rwc` (lol we didn't run rwc) to do with elided imports (namely we're failing to mark some imports as used and they're mistakenly elided). I don't think it's a fundamental flaw with this, but it's definitely something we need to look into. The affected projects include `Azure_FrameworkTests` and `immutable`. (You can see the diffs on the rwc diff PRs)

The immutable case is something like
```
//@filename: Traversable.ts
export interface ITraversable<T> {}

export function isTraversable(a: any): boolean {
    return isList(a) || isOption(a);
}

export function isList(a: any) {
    return (a instanceof _list.Cons) || (a instanceof _list.Nil);
}

export function isOption(a: any) {
    return (a instanceof _option.Some) || (a instanceof _option.None);
}
// @filename: List.ts
import _tr = require('./Traversable');
export class Cons<T> extends IList<T> {

    flatten<U>(): IList<U> {
        return this.foldLeft<IList<U>>(new Nil<U>(), (acc, t) => {
            if(_tr.isList(t)) { // usage here
                var l = <IList<U>><any> t;
                return acc.append(l);
            } else if(_tr.isOption(t)) { // and here
                var o = <_option.IOption<U>><any> t;
                if(o.isDefined()) {
                    return acc.appendOne(o.get());
                } else return acc;
            } else {
                return acc.appendOne(<U><any> t);
            }
        });
    }

}
```
I think we're failing to check a child function body or something?

**Comment by sandersn** [comment]
Probably when there is an error in the parent call expression. I observed this in the user tests too.

**Comment by sandersn** [comment]
Makes sense that we wouldn't have noticed this since our test coverage of the language service is so much worse, and getCandidateForOverloadFailure was only called from there.

**Comment by sandersn** [comment]
After discussion with @weswigham, the fix is to make getCandidateForOverloadFailure call resolveUntypedCall the way resolveErrorCall does. resolveUntypedCall is just a barebones set of `check*` calls.

**Pull request merged**
