### PR TITLE
Make Map constructor argument optional and nullable

### LINKED ISSUE #37779: Type error for new Map from undefined Iterable
**TypeScript Version:**  3.8.3

**Search Terms:** Map MapConstructor Iterable Iterator

**Code**

```ts
let undefinedArray: [string, string][] | undefined;
const map1 = new Map(undefinedArray);

let definedInterable: IterableIterator<[string, string]> = new Set<string>().entries();
const map2 = new Map(definedInterable);

let undefinedIterable: IterableIterator<[string, string]> | undefined;
const map3 = new Map(undefinedIterable); // Type error here
```

**Expected behavior:**
Passes type check because `new Map(undefined)` is a valid call to the Map constructor.
**Actual behavior:**
```
No overload matches this call.
  Overload 1 of 4, '(iterable: Iterable<readonly [string, string]>): Map<string, string>', gave the following error.
    Argument of type 'IterableIterator<[string, string]> | undefined' is not assignable to parameter of type 'Iterable<readonly [string, string]>'.
      Type 'undefined' is not assignable to type 'Iterable<readonly [string, string]>'.
  Overload 2 of 4, '(iterable: Iterable<readonly [string, string]>): Map<string, string>', gave the following error.
    Argument of type 'IterableIterator<[string, string]> | undefined' is not assignable to parameter of type 'Iterable<readonly [string, string]>'.
      Type 'undefined' is not assignable to type 'Iterable<readonly [string, string]>'.
  Overload 3 of 4, '(entries?: readonly (readonly [unknown, unknown])[] | null | undefined): Map<unknown, unknown>', gave the following error.
    Argument of type 'IterableIterator<[string, string]> | undefined' is not assignable to parameter of type 'readonly (readonly [unknown, unknown])[] | null | undefined'.
      Type 'IterableIterator<[string, string]>' is missing the following properties from type 'readonly (readonly [unknown, unknown])[]': length, concat, join, slice, and 14 more.(2769)
```
**Playground Link:** https://www.typescriptlang.org/play/#code/DYUwLgBArgdgJiAZgSxiOBBATlghgTwC4IBtAZzC1QHMAaCCqmagXRJYgB9p4lV0A3ACgAxgHsYFCAFtcABwCMEALwQ0AdwgBZeQApYCFGkw4CASmFDQkQ-zgBJGGBB4ARqGL3nb0F5e4wMSwAHnJKGnpGGhYAPhU1EE0AZXBgqOYY3TMAOhAnKhAyLOFxSUhZOQAmeI1tPVtjR29cdxALIStwHgb0Px8QT2bWvoCg0PS6BnDmWK5uvmMSiSkKgGYaxLq5fV4jXqHQdqA

**Related Issues:** None

**Suggested Fix:**
The [`MapConstructor` interface in `es2015.iterable.d.ts`](https://github.com/microsoft/TypeScript/blob/15aff05ff6c18af36ab1d247a1f9412b7d7e5b16/src/lib/es2015.iterable.d.ts#L139) should accept a single optional argument.
```diff
diff --git a/src/lib/es2015.iterable.d.ts b/src/lib/es2015.iterable.d.ts
index 374aad9322..6f9b786c1d 100644
--- a/src/lib/es2015.iterable.d.ts
+++ b/src/lib/es2015.iterable.d.ts
@@ -137,7 +137,7 @@ interface ReadonlyMap<K, V> {
 }
 
 interface MapConstructor {
-    new <K, V>(iterable: Iterable<readonly [K, V]>): Map<K, V>;
+    new <K, V>(iterable?: Iterable<readonly [K, V]>): Map<K, V>;
 }
 
 interface WeakMap<K extends object, V> { }
```

### PR DESCRIPTION
**Pull request by Pimm**
Fixes #37779.

This PR is based on #38153 by @JaredNeil.

As demonstrated by the change in the baseline file, this affects the typing of `new Map<string>`. I don't quite understand why that is the case. I also don't know whether this is an issue, as `new Map<string>` (note the sole type argument) does not compile anyway. If this is no good, please point me in the right direction.

### CODE REVIEW

**Comment by Pimm** [comment]
With this patch applied and strictNullChecks on:
```javascript
const potentiallyUndefinedIterable = [['1', 1], ['2', 2]] as Iterable<[string, number]> | undefined;
new Map(potentiallyUndefinedIterable); // Map<string, number> ✔️
```
```javascript
new Map(undefined); // Map<unknown, unknown> ❓
```
```javascript
new Map(null); // Map<unknown, unknown> ❓
```
This behaviour ‒ where `undefined` and `null` lead to `Map<unknown, unknown>` seems consistent with non-strictNullCheck behaviour. However, perhaps `Map<any, any>` is preferred. What are your thoughts?

**Review by orta — APPROVED** [review]
Yeah, seems reasonable to me, this implementation also matches how we do it in `lib.es2015.collection.d.ts`

```
interface MapConstructor {
    new(): Map<any, any>;
    new<K, V>(entries?: readonly (readonly [K, V])[] | null): Map<K, V>;
    readonly prototype: Map<any, any>;
}
declare var Map: MapConstructor;
```

**Comment by sandersn** [comment]
@orta this looks ready to go. Were you holding it for 4.4?

**Comment by ElvisWang27** [comment]
I have the same issue, Is this problem has resolve?

**Comment by Pimm** [comment]
Until this lands in TypeScript, you can use `?? []` as a workaround. Like so:
```javascript
const potentiallyUndefinedIterable = [['1', 1], ['2', 2]] as Iterable<[string, number]> | undefined;
new Map(potentiallyUndefinedIterable ?? []);
```

**Comment by orta** [comment]
I think this is good to go 👍🏻

**Pull request merged**
