### PR TITLE
Fix Headers interface

### LINKED ISSUE #14412: lib.es6.d.ts does not include typings for Headers.prototype.entries
**TypeScript Version:**  2.2.1

**Code**

```ts
$ cat test.ts
const h = new Headers();

h.entries();
$ tsc test.ts
test.ts(3,3): error TS2339: Property 'entries' does not exist on type 'Headers'.
```

**Expected behavior:**

TypeScript does not complain about the `entries` property, since it is [part of the spec](https://developer.mozilla.org/en-US/docs/Web/API/Headers) and implemented by Firefox and Chrome.

**Actual behavior:**

TypeScript complains that the `entries` property does not exist.

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
Fixes #14412

### CODE REVIEW

**Comment by SaschaNaz** [comment]
[`[Symbol.iterator]: IterableIterator<[String, String]>` is required too](https://heycam.github.io/webidl/#es-iterators).

**Comment by YuichiNukiyama** [comment]
@SaschaNaz 
Thanks for your advise. I add Symbol.iterator.

**Comment by SaschaNaz** [comment]
Uh, sorry for case issue, it should be `string` instead of `String`.

**Comment by YuichiNukiyama** [comment]
oops. i make careless miss.

**Pull request merged**
