### PR TITLE
Fix isProgramUptoDate when changing rootFileNames

### LINKED ISSUE #36010: isProgramUptoDate wrongfully returns true
**TypeScript Version:**  On `master` (commit `d6c05a135840dc3045ec8f3bbec1da5ffabb6593`)

**Search Terms:** `isProgramUptoDate`, `synchronize program` `update program`.

**Code**

I was playing around with the TypeScript API and I noticed that if you update the root files of a watcher program with the same number of root files, the source files are not updated.

```ts
import * as ts from 'typescript';

const watchHost = ts.createWatchCompilerHost(['path/to/foo']);
const program = ts.createWatchProgram(watchHost);
console.log(const program.getProgram().getSourceFiles()); // <- This has the expected sources
program.updateRootFileNames(['/path/to/bar']);
console.log(const program.getProgram().getSourceFiles()); // <- This has the same source, but it shouldn't
```

**Expected behavior:**

The source files should be the expected ones (so include `/path/to/bar`).

**Actual behavior:**

The source files didn't change.

**Playground Link:**  Can't reproduce in the playground as it's an API bug.

**Related Issues:**  Didn't find any related issues.

----

This is the culprit: https://github.com/microsoft/TypeScript/blob/3b396e6124d6a0382c4ab5b2d846a9c4b65a4ea3/src/compiler/program.ts#L575

It should check for array equality, not just array length. I'll make a PR real soon.

### PR DESCRIPTION
**Pull request by yacinehmito**
Fixes #36010

**I don't know what tests to write to validate that fix**

I'll try to see if the current tests run that codepath. In the meantime the fix is there and maybe it's good enough to be merged as-is.

### CODE REVIEW

**Comment by sheetalkamat** [comment]
please add test similar to https://github.com/microsoft/TypeScript/blob/master/src/testRunner/unittests/reuseProgramStructure.ts#L229 where rootNames change but the number of root names don't change.

**Comment by yacinehmito** [comment]
Hello. I don't understand what is expected. The test highlighted doesn't seem to involve `isProgramUptoDate`. It checks whether the program is reused but the logic doesn't rely on `isProgramUpToDate`.

**Comment by yacinehmito** [comment]
I found which test to update. It was in the same file. Sorry.
https://github.com/microsoft/TypeScript/blob/236012e47b26fee210caa9cbd2e072ef9e99f9ae/src/testRunner/unittests/reuseProgramStructure.ts#L908

**Comment by sheetalkamat** [comment]
@yacinehmito can you please update the test case so we can take this in. Thanks

**Comment by yacinehmito** [comment]
Yes. I'm swamped at work so I didn't have time to go back to this. Will do so before Monday. Thanks for the patience!

**Comment by yacinehmito** [comment]
@sheetalkamat I have added the tests. Thank you for your patience.

**Pull request merged**
