### PR TITLE
Update tslint to `latest` (`next` is still on 4.3) and lint for BOM

### PR DESCRIPTION
**Pull request by andy-ms**
BOM was causing `^M` to show up in edited files.
`tslint@next` hasn't been updated in a while, so perhaps we should use `latest` instead?

### CODE REVIEW

**Comment by mhegazy** [comment]
there was a reason why we used @next. @vladima and @DanielRosenwasser do you recall why?

**Comment by mhegazy** [comment]
node v4 seems to be failing, can not seem to see the logs, possibly `npm update`..

**Comment by vladima** [comment]
AFAIR the problem was that `peerDependencies` in `tslint@next` were updated to work with the latest TypeScript however `latest` [one](https://github.com/palantir/tslint/blob/4.5.1/package.json#L50) only works with `>= 2.0.0`

**Comment by adidahiya** [comment]
Just published tslint v4.5.1-dev.0 and v5.0.0-dev.0 with the `next` dist-tag ([changelog](https://github.com/palantir/tslint/blob/next/CHANGELOG.md)). Let me know if still have issues with those.

**Comment by mhegazy** [comment]
👍

**Pull request merged**
