### PR TITLE
 Improve error message when comparing non-comparable types

### LINKED ISSUE #27910: TS2367: This condition will always return 'false' since the types 'Constructor<T>' and 'typeof Child' have no overlap.
**TypeScript Version:**   3.2.0-dev.20181011

**Search Terms:** TS2367

**Code**

```ts
abstract class Base<T> {
    get Item(): T { return null }
}

class Child extends Base<Item> {
    constructor(public data: any) { super() }
}

interface Item { }
declare type Constructor<T> = new (data: any) => Base<T>

function func<T>(constructor: Constructor<T>): void {
    // TS2367: This condition will always return 'false' since the types 'Constructor<T>' and 'typeof Child' have no overlap.
    if (constructor === Child) {
        // do something
    }
    new constructor(null)
}

func(Child) // No errors
```

**Expected behavior:**

Compiles without errors.

**Actual behavior:**
```
test.ts:14:9 - error TS2367: This condition will always return 'false' since the types 'Constructor<T>' and 'typeof Child' have no overlap.

14     if (constructor === Child) {
           ~~~~~~~~~~~~~~~~~~~~~
```

[**Playground Link** ](https://www.typescriptlang.org/play/#src=abstract%20class%20Base<T>%20%7B%0D%0A%20%20%20%20get%20Item()%3A%20T%20%7B%20return%20null%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20Child%20extends%20Base<Item>%20%7B%0D%0A%20%20%20%20constructor(public%20data%3A%20any)%20%7B%20super()%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20Item%20%7B%20%7D%0D%0Adeclare%20type%20Constructor<T>%20%3D%20new%20(data%3A%20any)%20%3D>%20Base<T>%0D%0A%0D%0Afunction%20func<T>(constructor%3A%20Constructor<T>)%3A%20void%20%7B%0D%0A%20%20%20%20if%20(constructor%20%3D%3D%3D%20Child)%20%7B%20%2F%2F%20TS2367%3A%20This%20condition%20will%20always%20return%20'false'%20since%20the%20types%20'new%20(data%3A%20any)%20%3D>%20Base<T>'%20and%20'typeof%20Child'%20have%20no%20overlap.%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20do%20something%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20new%20constructor(null)%0D%0A%7D%0D%0A%0D%0Afunc(Child)%20%2F%2F%20No%20errors%0D%0A)

**Related Issues:** #25642

### PR DESCRIPTION
**Pull request by tony-ho**
Fixes #27910

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@DanielRosenwasser are you good with this verbiage as-is?

**Comment by RyanCavanaugh** [comment]
I'll rebase this. We also decided to not explicitly recommend `unknown` since a tighter lower bound (such as `string` or `boolean`) is often more appropriate.

**Comment by sandersn** [comment]
@RyanCavanaugh do you just want that sentence removed from the error?

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
