### PR TITLE
Do not emit names and name index mapping in source map

### PR DESCRIPTION
**Pull request by sheetalkamat**
Since source map spec isn't clear about use of names, removing names entry all together. We can look at the symbol mapping once there is update to the spec about it.

### CODE REVIEW

**Comment by develar** [comment]
Hi, what do you mean?  Spec is clear and IntelliJ Platform uses it. Please don't break debug! 

1) Find mapping entry.
2) Get mapping entry name
3) Name is missed (unnamed entry)  - use generated element name. name is presented - use it.

 Please don't break existing funcitonality and fix #5224. I will answer to any question and can provide closed source code (partially opened - see https://github.com/JetBrains/intellij-community/blob/master/platform/script-debugger/debugger-ui/src/com/jetbrains/javascript/debugger/NameMapper.kt) As you can see in the provided NameMapper, there is a flag js.debugger.name.mappings.by.source.code as a workaround of 5224.

Our users happy to use TypeScript and debug it.

**Comment by asvetliakov** [comment]
Please do not merge this at least until implementing another solution for debugging
Thanks

**Comment by sheetalkamat** [comment]
@develar we have never emitted variable names in the source map. We were emitting the callstack name it belonged too.. So your functionality is anyways broken and unsupported without this change.

**Comment by develar** [comment]
@sheetalkamat So, if you don't mangle names, it is ok (nothing to map). Thanks for clarification.

**Comment by mhegazy** [comment]
can you coordinate this with #5780

**Comment by mhegazy** [comment]
The easiest is to wait for @rbuckton to merge #5780 and then apply the change on top, the tests should be unchanged.

**Comment by rbuckton** [comment]
@sheetalkamat Do you have a preference?

**Comment by sheetalkamat** [comment]
@rbuckton, Probably you should go first as my changes are small, I think it would be easier if I have to merge.

**Comment by rbuckton** [comment]
@sheetalkamat: Alright, I've gone ahead and merged my change.

**Comment by mhegazy** [comment]
@sheetalkamat can you add a blurb on this change in https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-18

**Comment by develar** [comment]
Without name mappings it is not possible to debug `this` in the lambdas — https://youtrack.jetbrains.com/issue/WEB-20340#comment=27-1372090

`_this` is generated but TS sourcemap doesn't contain name mappings and, obviously, IDEA cannot remap it to real `this`...

screen shot 2016-03-26 at 15 50 03

`{"version":3,"file":"myclass1_spec.js","sourceRoot":"","sources":["../../src/__tests__/myclass1_spec.ts"],"names":[],"mappings":"AAAA,IAAI,GAAG,GAAG,EAET,CAAA;AAED;IAAA;QACE,QAAG,GAAG,IAAI,CAAA;IAOZ,CAAC;IALC,oBAAG,GAAH;QAAA,iBAIC;QAHC,UAAU,CAAC;YACT,OAAO,CAAC,GAAG,CAAC,KAAI,CAAC,GAAG,CAAC,CAAA;QACvB,CAAC,EAAE,EAAE,CAAC,CAAA;IACR,CAAC;IACH,aAAC;AAAD,CAAC,AARD,IAQC;AAED,IAAI,MAAM,EAAE,CAAC,GAAG,EAAE,CAAA"}`

**Comment by born2net** [comment]
+1

**Pull request merged**
