### PR TITLE
Porting #9528 to release 2.0 branch

### PR DESCRIPTION
**Pull request by riknoll**
Porting #9528 to release 2.0 branch

I squashed the commits from that branch to a single commit and cherry-picked the results to make this PR cleaner, but the original PR included several commits

### CODE REVIEW

**Comment by weswigham** [comment]
This need to include commit 8cbbcd03f09984a45a3b04b66d4f6b078aaabe23 as well.

**Comment by riknoll** [comment]
@weswigham Thanks, cherry picked the commit.

**Comment by riknoll** [comment]
@weswigham am I good to merge this?

**Comment by weswigham** [comment]
Probably? But I'm not a formal gakekeeper of the `2.0` branch - cc: @RyanCavanaugh

**Pull request merged**
