### PR TITLE
Fix recording sourcemap in human-readable form

### PR DESCRIPTION
**Pull request by yuit**
Fix outputing sourcemap for test262

### CODE REVIEW

**Comment by mhegazy** [comment]
I do not think I understand the problem this change is fixing.

**Comment by yuit** [comment]
So there is a bug in visualizing source map in normal text form when trying to verify correctness inside rwcrunner. So this change is to fix that bug. @sheetalkamat has made the fix when I was working on the rwc but I think it may be helpful to keep it our codebase

**Comment by sheetalkamat** [comment]
@mhegazy  the order of js files recorded was different from the ts files, resulting in we picking wrong js file resulting in incorrect mapping shown even though the mapping was technically correctly emitted

**Comment by sheetalkamat** [comment]
@yuit  the travis build seems to have failed. Either you can investigate or I can do it to.. let me know.

**Comment by yuit** [comment]
I am going to close this for now since we are implementing new CI-Server

**Pull request closed without merging**
