### PR TITLE
Add Jake task to update the Sublime plugin

### PR DESCRIPTION
**Pull request by RyanCavanaugh**

### CODE REVIEW

**Comment by danquirk** [comment]
Assumes your repos are side by side but :+1:

**Comment by DanielRosenwasser** [comment]
Can you actually have Sublime use a plugin that isn't in its plugin directory? Is the user intended to have created a symlink of their repo in the plugin directory?

**Comment by RyanCavanaugh** [comment]
Symlinking your repo to the plugin directory is what we tell people to do in the dev setup instructions (https://github.com/Microsoft/TypeScript-Sublime-Plugin/wiki/Dev-notes). It's very convenient.

**Comment by DanielRosenwasser** [comment]
Ah nice - maybe it'd be helpful to note that in the task description. :+1:

**Pull request merged**
