### PR TITLE
change error message for assigning from object

### LINKED ISSUE #10462: Give a better error message for assigning from Object to anything else
Test code

```ts
declare var x: Object;
declare var y: RegExp;
y = x;
```

A lot of people misunderstand what `Object` is. We should consider trying to elaborate the issue in some way.

```
Type 'Object' is not assignable to type 'RegExp'.
  The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
```

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
Fixes #10462

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
The results look positive overall - @sandersn @RyanCavanaugh care to take a look?

**Comment by YuichiNukiyama** [comment]
Thanks. I fix file name typo.

**Comment by sandersn** [comment]
You also need to delete the original, typoed baselines.

The baselines passed even without deleting them though, I'm not sure why.

**Comment by YuichiNukiyama** [comment]
I remove extra files.

> The baselines passed even without deleting them though, I'm not sure why.

If I have a time, try to investigate.

**Comment by sandersn** [comment]
Looks good. Thanks again @YuichiNukiyama !

**Pull request merged**
