### PR TITLE
Clone questionMark and dotdotdot token

### PR DESCRIPTION
**Pull request by armanio123**
Fixes https://github.com/microsoft/TypeScript/issues/57924#issuecomment-2016963508

`CompletionInfo` is failing due to a synthetic `propertySignature` using an incorrect `questionToken` position which cause the Assert to fail. 

The positions are incorrect due to the checker reusing the synthetic node for the `questionToken`. When assigning positions the value gets overwritten by the latest position update this generating a node that is "not contained" on the parent.

The PR fixes this by always cloning a synthetic `questionToken` instead of reusing it.

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by armanio123** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
This makes sense; `getSynthesizedDeepCloneWorker` is similar and passes in the token visitor. Makes me wonder if we should try and make the visitor required and see where else we've missed this.

But, this does need a test; the linked issue should come with one that can be minimized.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Review by andrewbranch — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Tested, and the test does actually test the crash, nice.

**Pull request merged**
