### PR TITLE
Support `export type *`

### LINKED ISSUE #37238: [request] allow `export type * from`
## Search Terms

export type

## Suggestion

> TS1383: Only named exports may use 'export type'.

allow `export type * from`

## Use Cases

https://github.com/bluelovers/ws-ts-type/blob/master/packages/ts-type/index.ts

```ts
export type * from './lib';
export type * from 'typedarray-dts';
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #37238

Adds support for `export type * from "mod"` and `export type * as ns from "mod"`.

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot perf test this
@typescript-bot test top100

**Review by jakebailey — APPROVED** [review]
I can't say I saw anything surprising in the checker (looked as I would guess), but I think the baselines say it all and look good to me; all of the edge cases I was coming up with appear to be tested.

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Review by sandersn — APPROVED** [review]

**Review by weswigham — CHANGES_REQUESTED** [review]
Unless I'm mistaken, it looks like this needs some (error-free) `.d.ts` emit tests to ensure we preserve the `export type`y-ness of these declarations when doing declaration emit (and probably some emitter/declaration emitter code to match). A test with an `export type` declaration in a js file with js declaration emit on would also be relevant, despite (I assume) being an error.

**Comment by andrewbranch** [comment]
Good call. I suspect it already works since this form is not actually new syntax, just newly not a grammar error, but it definitely needs to be tested.

**Comment by andrewbranch** [comment]
As I predicted, declaration emit does work. It did drop the `type` from declaration emit when the source file was JS, but that seems ok?

**Review by weswigham — APPROVED** [review]
It'd be nice if the js declaration emit preserved the `type` modifier, just in case someone uses the (admittedly internal) node builder APIs on typescript code (which is why it knows how to emit interfaces and such), but since it's an error it's non-critical.

**Comment by andrewbranch** [comment]
On second thought, having consistent declaration emit is also required to make errors consistent between referenced projects in the editor and on the CLI, so I went ahead and fixed it.

**Pull request merged**
