### PR TITLE
WIP: Fix "go to implementation" for node modules

### PR DESCRIPTION
**Pull request by sheerun**
Here are failing tests for issue #37777 The issue is with "go to implementation" and "go to definition" which doesn't work for node modules without .ts files (it points to type definition in d.ts file of `@types` instead)

I cannot figure out how to fix them in code. Maybe someone can help?

### CODE REVIEW

**Comment by sb-bilal-dev** [comment]
Any updates on fixing failing tests?

**Comment by sheerun** [comment]
@sb-bilal-dev As mentioned, I've left it for TypeScript team

**Comment by sheerun** [comment]
btw. you can run failing test shown here by `gulp runtests --tests="with type definitions of commonjs module"`

**Comment by sandersn** [comment]
Thanks for the tests @sheerun. Were you able to figure out how to make progress? Unfortunately, we can't give one-on-one help, but you can probably find some knowledgeable people at discord.gg/typescript.

If you're still stuck on this, I may close it to keep the number of open PRs down, and so that people won't be deterred from trying to fix this issue by seeing an open PR on it.

**Comment by sheerun** [comment]
OK thank please close it

**Comment by fabriziobertoglio1987** [comment]
@sandersn can we have this issue fixed? Please. It is important for opensource contributors to navigate to the implementation in node-modules

**Pull request closed without merging**
