### PR TITLE
Support higher order inferences for constructor functions

### LINKED ISSUE #30650: Higher order type inference from generic React component
**TypeScript Version:**  3.4.1

**Search Terms:**

**Code**

```ts
interface Component<P> {
  (props: P): unknown;
  // Comment this out and it works
  defaultProps?: Partial<P>;
}
declare function myHoc<Props>(C: Component<Props>): Component<Props>;

{
  type Props<T> = { t: T; foo: number };
  declare function MyComponent<T>(props: Props<T>): unknown;
  // Expected type: <T>(props: Props<T>) => unknown
  // Actual type: Component<Props<{}>>
  const MyComponent2 = myHoc(MyComponent);
}
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR expands on #30215 to support higher order inferences for constructor functions and to permit function type arguments to higher order composition functions to have other members in addition to their single call signature.

Some examples:

```ts
declare class Point {
    constructor(x: number, y: number);
    readonly x: number;
    readonly y: number;
}

declare class Bag<T> {
    constructor(...args: T[]);
    contains(value: T): boolean;
    static foo: string;
}

function asFunction<A extends any[], B>(cf: new (...args: A) => B) {
    return (...args: A) => new cf(...args);
}

const newPoint = asFunction(Point);  // (x: number, y: number) => Point
const newBag = asFunction(Bag);      // <T>(...args: T[]) => Bag<T>
const p1 = new Point(10, 20);        // Point
const p2 = newPoint(10, 20);         // Point
const bag1 = new Bag(1, 2, 3);       // Bag<number>
const bag2 = newBag('a', 'b', 'c');  // Bag<string>

declare class Component<P> {
    props: P;
    constructor(props: P);
}

type ComponentClass<P> = new (props: P) => Component<P>;

declare function myHoc<P>(C: ComponentClass<P>): ComponentClass<P>;

type GenericProps<T> = { foo: number, stuff: T };

declare class GenericComponent<T> extends Component<GenericProps<T>> {}

// const GenericComponent2: new <T>(props: GenericProps<T>) => Component<GenericProps<T>>
const GenericComponent2 = myHoc(GenericComponent);
```

The rules for determining when higher order inferences occur are revised as follows. Given a generic function `f` of type `<…>(…, x: P, …) => R`, and an argument expression `a` of a generic function type `A`, in a call expression `f(…, a, …)` the type parameters of `A` are propagated onto the inferred result type of the function call if:

* `P` is a function type with no type arguments, a single call or construct signature, and no other members, and
* `R` is a function type with no type arguments, a single call or construct signature, and no other members, and
* `A` is function type with type arguments and a single call or construct signature that matches `P` (note that `A` is permitted to have other members), and
* in the left-to-right processing of the function call arguments, no inferences have been made for any of the type parameters referenced in `P`.

Fixes #30650.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by weswigham** [comment]
The `react-test-renderer` failure is in `master`, so I think DT is clean.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by guykr-stratoscale** [comment]
Hi @RyanCavanaugh @ahejlsberg,
when trying to use this new mechanism with React's `ComponentClass` I noticed this does not actually work.

Please find below an adapted example from the one in this PR:
```
declare class Point {
  constructor(x: number, y: number)
  readonly x: number
  readonly y: number
}

declare class Bag<T> {
  constructor(...args: T[])
  contains(value: T): boolean
  static foo: string
}

function asFunction<A extends any[], B>(cf: new (...args: A) => B) {
  return (...args: A) => new cf(...args)
}

const newPoint = asFunction(Point) // (x: number, y: number) => Point
const newBag = asFunction(Bag) // <T>(...args: T[]) => Bag<T>
const p1 = new Point(10, 20) // Point
const p2 = newPoint(10, 20) // Point
const bag1 = new Bag(1, 2, 3) // Bag<number>
const bag2 = newBag('a', 'b', 'c') // Bag<string>

declare class Component<P> {
  props: P
  constructor(props: P)
}

interface ComponentClass<P> {
  new (props: P): Component<P>
  thisWillBreakGenericInference?: boolean // <--- this is breaking the type inference
}

declare function myHoc<P>(C: ComponentClass<P>): ComponentClass<P>

type GenericProps<T> = { foo: number; stuff: T }

declare class GenericComponent<T> extends Component<GenericProps<T>> {}

// Should be:
// const GenericComponent2: new <T>(props: GenericProps<T>) => Component<GenericProps<T>>
// Actually: 
// const GenericComponent2: ComponentClass<GenericProps<unknown>>

const GenericComponent2 = myHoc(GenericComponent)
```

Link to [playground](https://typescript-play.js.org/#code/CYUwxgNghgTiAEkoGdnwAoHsCWA7ALvAN4BQ8imuy+MArmPpjABQAeAXPLrQLYBGIGABp4AT07d+ggJRl4cKMEoRR8Dl14CYchUtwqxEzYJIBfEiVBI4iaKngAhKAHMAPABUAfMTlhK1OgYmZgA6MNhnZE53AG0AXVlyPwIoPGRmADcoCFoQaOlOPkxMCBAoXDlqKHxsMHgAM2LOALxnMwt62lwGbEp4FAAxLp7KVwBBeBBWfBBcYDRy0XiRB09mMHqJEAB3eFDwmEjOMel4AF5vB1PScjh8WhhcPbCQiKj4E-PvXB3Eev3XodkLJzCRktQuDssHhCGd+sght0apRmNCCKcAPQYvbqSRaETiDRSGCnC4YHAEMH+Qg-bZOZzneGIka4Zj0zHYjxrF5vaLxUmXFxcqlUQgABwAjIzaeSYcwJQAGEQAJgVHNllPB4uV0qhFPw8qV8FV6rR+BFEL4LilcJl9PlKpEAGZ1fTXHjBJ4LYQrc4dbadvaAORQIMiIN8MPwINgIOuoUtXDOL2WcDQGxIewAYUwPDFlFm+Fc6G8N3gYpgmDF73QvmpgUYLArVZrIIsMME9SgYAQObzBYIWbsyGLpbkMuYzernHQBXgffzPwIo7k+AAFthkAB1bAQCAOBQAawA4rNBLUAJK4eqCWY9gD8hWKpXK8Cx8FcAFpv-B15v4P+fBHq0v5rgg+CiGKCB4DecDdCA7SptYCCdEivRPDwogABKYGAo7MFmnALgO+BDigI4lnOxFLqRw4riQEFQfAp4-DAtToJW1ZcoyRANE0RJaAA3PA1C0PUmzwO48CglY6YIJmaAseeYDUYW3FTDMcxoKpy5KWxYAcS2XKlqC74AMprpgtAQMA8ACOwJDvlqzFnvpOn4MqWy7Fyk6ce8ensX5XICvOuaLmpAUGUFXheu+YwMLQ2QqJwjnYs5kXuZ5oX9jRZGoK4kWGVxXSHrgmDbLgngpulrm1JljKYThYDMBlYUkbIQA):  
The change I made is in line 31. 

The issue here is that React's ComponentClass interface has a few optional members defined.

**Comment by ahejlsberg** [comment]
@guykr-stratoscale That's a known limitation. See discussion in https://github.com/microsoft/TypeScript/issues/30650#issuecomment-486680485.

**Comment by RichardForrester** [comment]
It's really encouraging that TS is getting some more support for functional programmers. Keep up the good work!

Small critique on the [announcement](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html) docs. The function you guys are showing off as `compose` is backwards and without currying is not really a realistic implementation.

```typescript
function compose<T, U, V>(
    f: (x: T) => U, g: (y: U) => V): (x: T) => V {
    
    return x => g(f(x))
}
```

Based on all of the below resources:

```haskell
-- Haskell
(.) :: (b -> c) -> (a -> b) -> a -> c
```
```typescript
// Sanctuary.js
compose :: Semigroupoid s => s b c -> s a b -> s a c

// fp-ts
export interface Semigroupoid<F> {
  readonly URI: F
  readonly compose: <E, A, B>(ab: HKT2<F, A, B>, la: HKT2<F, E, A>) => HKT2<F, E, B>
}

// Ramda
(b -> c) -> (a -> b) -> a -> c

// Crocks
composeB :: (b -> c) -> (a -> b) -> a -> c
```

I understand the the announcement docs are just for simple illustration, and it's great. I'm thrilled about the attention to the functional side of javascript. But it would be nice to have simple **and** correct code for the docs, maybe something like:

```typescript
type fn1<I, O> = (i: I) => O
type compose = <T extends any, U, V>(f: fn1<U, V>) => (g: fn1<T, U>) => fn1<T, V>
const compose: compose = f => g => a => f (g (a))
```

**Comment by Luxcium** [comment]
@RichardForrester   in JavaScript/TypeScript everything is backward compatible 

> In some libraries this function is named sequence. (as per Ramda pipe)


``` TypeScript
const pipe = compose
const ƒ = pipe(
    (ns: string): number => +ns,
    (num: number): number[] => [num]
  );
  console.log(ƒ('4')); // -> [4]
```

it's working perfectly `console.log` prints `[4]` I don't understand what was wrong in the example ...

**Pull request merged**
