### PR TITLE
Adds ability to optionalize class getters

### LINKED ISSUE #14417: Cannot Optionalize Class Getters
**TypeScript Version:**  2.2.1

**Code**

```ts
class Person {
  firstName: string;
  lastName: string;

  get fullName?() {
    return this.firstName + ' ' + this.lastName;
  }
}
```

**Expected behavior:**

Since `fullName` is optional the following should work:

```
const Me: Person = {
  firstName: 'Foo',
  lastName: 'Bar'
}
```

**Actual behavior:**

A syntax error occurs on this line `get fullName?() {`

I'm not sure if omitting the ability to optionalize getters was by design or not. If it was by design, I'd love to know the reasoning behind it.

### PR DESCRIPTION
**Pull request by bradenhs**
Fixes #14417

This PR makes it to possible to optionalize class getters in the same way class methods can be marked optional:

```typescript
class Person {
    firstName: string;
    lastName: string;

    get fullName?() {
        return this.firstName + " " + this.lastName;
    }
}

const me: Person = {
    firstName: "foo",
    lastName: "bar"
}
```

The above code should now work whereas before there was a syntax error. This is my first TypeScript PR so I hope I covered everything. This PR should handle:

- Updating the declaration emit
- Ensuring `strictNullChecks` works as expected with optional class getters
- Ability to omit optional class getter body

Hopefully I didn't miss anything, but I am of course more than happy to fix any issues.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Hey @bradenhs thanks for the PR! One thing that I'd like to ask is whether you could break your tests into multiple files. It seems like there's a lot of stuff you're trying to test (including intentional syntax errors), so I think it'd be a good idea to break that into multiple granular tests.

**Comment by bradenhs** [comment]
No problem. I'm traveling now but should have some time within the next week or so to make that change. I would love any other feedback in the meantime.

**Comment by Dashue** [comment]
Would love to see this functionality as well, any updates?

**Comment by bradenhs** [comment]
Started first post-college job this summer. Don't have as much coding free time as I once had :) But I have plans to get back to this again before the year is out.

**Comment by jeanpfs** [comment]
Any updates?

**Comment by mhegazy** [comment]
@andy-ms can you please review

**Comment by bradenhs** [comment]
So I've been putting off crossing the finish line with this for a while but would definitely love any additional reviews! It might give me the motivation to finish this up.

**Comment by andy-ms** [comment]
Why only `get`? Seems like `set` should be optional as well.

**Comment by bradenhs** [comment]
So bear with me as I try to remember my thinking on this. I believe there are two reasonable choices for how to implement this:

1. Whenever `get` is optional `set` must be marked optional as well. `set` cannot be marked optional if `get` is not marked optional.
2. Only allow marking `get` as optional. `set` can never be marked optional.

I went with the second of those choices because marking `set` as optional seemed weird. I wasn't sure what `set someProperty?(value) { ...` really communicates. The only advantage of option 1 in my eyes is that if someone sees that `set` is optional they'll know for sure that the corresponding `get` is optional as well. To be honest, I don't have a strong opinion on this either way.

**Comment by andy-ms** [comment]
If I understand the PR correctly, its effect is that when a class is used as an interface, the implementer doesn't have to provide a getter. So, what if you have:
```ts
class C {
    get x?() { return 0; }
    set x(value: number) { ... }
}
const impl: C = { };
```

Shouldn't I need both the getter and setter to be optional for compilation to succeed? After all, the following is a compile error today:

```ts
class C {
    set x(value: number) { }
}
const impl: C = {}; // Needs a setter for 'x'
```

**Comment by bradenhs** [comment]
FYI: I probably won't get to this within the next couple weeks. I still want to finish it up but it'll be slow going.

**Comment by RyanCavanaugh** [comment]
@bradenhs thanks for the work so far! Will let someone else pick this up if they're able to.

**Comment by ericcarino** [comment]
Thanks for the work @bradenhs .  It sucks that no one has the time to finish this off (like myself).  This feature would have come in handy for me.

**Comment by bigzoo** [comment]
@RyanCavanaugh could you put down what needs to be added to get this work completed? Willing to take it up

**Comment by dapug** [comment]
How can this possibly have been abandoned?  Seems absolutely fundamental, essential.  What is the work-around?

**Comment by artem-v-shamsutdinov** [comment]
Here is what I did to get around this:
class Example {

  constructor() {
    delete this.val
    Object.defineProperty(this, 'val', {
      get() {
        return whatever
      },
      set(
        val: string
      ) {
        // do whatever
      }
    });
  }

  val?: string
}

**Comment by DougSPol** [comment]
Ping - too bad this wasn't merged, super want this ability

**Comment by abhinandan-chakraborty** [comment]
when will this get solved?

**Comment by pishangujeniya** [comment]
Don't know why this was not prioritized. 😞

**Comment by MnariMohamed** [comment]
2024 and this is still not fixed

**Pull request closed without merging**
