### PR TITLE
Search for `node_modules` in parent directories when getting type roots.

### LINKED ISSUE #10617: Include node_module of containing folders in the automatic @types discovery
```shell
c:\test>tree /f
│   package.json
│
├───node_modules
│   └───@types
│       └───node
│
└───src
        index.ts
        tsconfig.json

c:\test>cd src

c:\test\src>type index.ts
import * as fs from "fs";

c:\test\src>npm install @types/node
test@1.0.0 c:\test
`-- @types/node@6.0.38

c:\test\src>tsc
index.ts(1,21): error TS2307: Cannot find module 'fs'.
```

The issue here is that we only including node_modules in the current folder for automatic type discovery. this causes a lot of confusion for users trying to use the new `@types` package, specially if they are global. ppl do not usually associate the location of their tsconfig.json with it not working, all they see is that sometimes it does and sometimes it does not.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #10617
Note that this only gets the nearest `node_modules`. It would be easy to modify this code to search for as many as possible rather than just taking the first one; would we want that?
Also, this does *not* get globally installed node_modules. This has a different location on different people's machines, although we could just include all possible locations and check of the ones that don't exist.
Also, @vladima is there a reason we have `directoryExists` optional but `fileExists` mandatory?

### CODE REVIEW

**Comment by yortus** [comment]
@andy-ms could we make the behaviour consistent with the compiler's existing `moduleResulution: node` implementation? That's already present in the compiler and it searches up multiple levels (if neccessary) which matches runtime behaviour (except I think it doesn't look for global `node_modules`).

The existing 'searching up' implementation is in `program.ts` [here](https://github.com/Microsoft/TypeScript/blob/0041d5ce7907f9ee974693ace54efd64afa1971a/src/compiler/program.ts#L767).

I understand this is a slightly different thing, because you are not searching for a specific module, but looking for whatever you can find in a `@types` directory. But it's more consistent with runtime behaviour if you keep searching up and accumulate all the `@types/X` typings you find.

If the compiler does *not* search up multiple levels for `@types`, there are two problems that would be surprising for users:

1. it will fail to compile programs that are valid/work fine at runtime. 
2. it will be internally inconsistent in that something like `import * as ts from 'typescript'` will search up multiple levels to find the tsc typings, but `import * as fs from 'fs'` will *not* search up multiple levels for the node typings.

**Comment by mhegazy** [comment]
👍

**Comment by mhegazy** [comment]
please port these to release-2.0 branch as well.

**Comment by fletchsod-developer** [comment]
Since this is fixed in 2.0 branch.  Question is which release version at the earliest contain this fix?

**Comment by andy-ms** [comment]
@fletchsod-developer Works for me in `2.0.3`. This isn't in `2.0.2` as that was published in before this change was made.

**Pull request merged**
