### PR TITLE
Fix Awaited<T> for onfulfilled callbacks with more than one argument

### LINKED ISSUE #46934: Awaited has issues with custom Promise subtype
Hello everyone,

Not sure if this is the correct place to bring this up but the `Awaited<T>` type as-is broke our build after upgrading from typescript 4.4.3 to 4.5.2.

For reference, here is what `Awaited<T>` looks like:

```ts
/**
 * Recursively unwraps the "awaited type" of a type. Non-promise "thenables" should resolve to `never`. This emulates the behavior of `await`.
 */
type Awaited<T> =
    T extends null | undefined ? T : // special case for `null | undefined` when not in `--strictNullChecks` mode
        T extends object & { then(onfulfilled: infer F): any } ? // `await` only unwraps object types with a callable `then`. Non-object types are not unwrapped
            F extends ((value: infer V) => any) ? // if the argument to `then` is callable, extracts the argument
                Awaited<V> : // recursively unwrap the value
                never : // the argument to `then` was not callable
        T; // non-object or non-thenable
```

The problem is that we have a custom Promise class (`AbortablePromise`) and its `then` function accepts a `onfulfilled` callback that do not exactly match the condition `F extends ((value: infer V) => any)`.

Our `then` is declared like this:

```ts
  public then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T, abortController: AbortController) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): AbortablePromise<TResult1 | TResult2>;
```

So `onfulfilled` in our case is `(value: T, abortController: AbortController) => TResult1 | PromiseLike<TResult1>)` which does not match `(value: infer V) => any`

Hence, `Awaited<T>` where `T` is an `AbortablePromise` always returns `never`.

Would it be possible to make the type condition more flexible in `Awaited<T>` to enable these promise extensions and still have the type be compatible with `Promise.all`, `Promise.race`, etc?

_Originally posted by @julienavert in https://github.com/microsoft/TypeScript/issues/45350#issuecomment-980096719_

### PR DESCRIPTION
**Pull request by rbuckton**
This adds a rest argument to the inference for the `onfulfilled` callback to support `Promise` subtypes that provide more than one argument.

Fixes #46934

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by rbuckton** [comment]
@typescript-bot perf test

**Comment by rbuckton** [comment]
@typescript-bot user test this

**Review by weswigham — APPROVED** [review]

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5

**Comment by DanielRosenwasser** [comment]
Made this 4.5-bound.

**Pull request merged**
