### PR TITLE
No `this` type arguments in base constraints

### LINKED ISSUE #54491: TS 5.1.3 Regression: TSC Compiler throws FATAL ERROR: Reached heap limit Allocation failed
# Bug Report

### 🔎 Search Terms

tsc, compiler, heap limit, crash, memory

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0.4 and 5.1.3

### ⏯ Repository Link

https://github.com/virtuallyunknown/tsc-error

### 💻 Code

To reproduce the error, clone the repository and run the build script or just `npx tsc`.

```
git clone https://github.com/virtuallyunknown/tsc-error.git && cd tsc-error
npm install
npx tsc
```

### 🙁 Actual behavior

Running the typescript compiler (`tsc`) from project root causes the build to fail and produce this error:

```
<--- Last few GCs --->

[43355:0x6bd0ae0]     9563 ms: Scavenge 4038.1 (4116.6) -> 4037.2 (4117.8) MB, 4.5 / 0.0 ms  (average mu = 0.538, current mu = 0.113) allocation failure; 
[43355:0x6bd0ae0]     9572 ms: Scavenge 4039.0 (4117.8) -> 4038.2 (4138.6) MB, 8.4 / 0.0 ms  (average mu = 0.538, current mu = 0.113) allocation failure; 
[43355:0x6bd0ae0]    10371 ms: Mark-Compact 4052.2 (4138.6) -> 4048.8 (4152.1) MB, 794.9 / 0.0 ms  (average mu = 0.390, current mu = 0.040) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xbf9890 node::Abort() [node]
 2: 0xaf6859  [node]
 3: 0xddaf80 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0xddb336 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 5: 0xfd9db5  [node]
 6: 0xfed4e5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xfc924f v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xfca297 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xfa99fa v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x13bd76f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x18443f9  [node]
Aborted (core dumped)
```

I also tried `typescript@next`, but that doesn't fix it. I also tried this command:

`NODE_OPTIONS=--max-old-space-size=28000 npx tsc --noEmit  --diagnostics --extendedDiagnostics --incremental false`

but it crashes with a different error after a while.

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

### 🙂 Expected behavior

Running the typescript compiler (`tsc`) command compiles the build successfully after 1-2 seconds, just like it did in `5.0.4`.

### LINKED ISSUE #54495: 5.1 regression: constraints of generic tuple types are sometimes order-sensitive
# Bug Report

### 🔎 Search Terms

- 5.1
- tuple
- array
- spread

Possibly related:
- https://github.com/microsoft/TypeScript/issues/54048
- https://github.com/microsoft/TypeScript/issues/54302

### 🕗 Version & Regression Information

- This changed between versions v5.0.4 and v5.1.3

### ⏯ Playground Link

I was unable to reproduce: if you could please steer me in the right direction I'm happy to dig more, but I'm a bit stuck on how to debug this

### 💻 Code

We have an issue using [`io-ts`](https://github.com/gcanti/io-ts). If this is a bug with that library, I'll close this here, but I don't *think* it is.

The TypeScript compiler is complaining about a number of excerpts from the `d.ts` file, where the compiler doesn't seem to be making sense.

Here's an example error:

```
node_modules/io-ts/lib/index.d.ts:1151:24 - error TS2344: Type 'CS' does not satisfy the constraint '[Mixed, Mixed, Mixed[]]'.
  Type '[Mixed, Mixed, ...Mixed[]]' is not assignable to type '[Mixed, Mixed, Mixed[]]'.
    Target allows only 3 element(s) but source may have more.

1151 ) => TaggedUnionC<Tag, CS>
```

The code it's referring to is here:

```ts
export interface TaggedUnionC<Tag extends string, CS extends [Mixed, Mixed, ...Array<Mixed>]>
  extends TaggedUnionType<Tag, CS, TypeOf<CS[number]>, OutputOf<CS[number]>, unknown> {}

export declare const taggedUnion: <Tag extends string, CS extends [Mixed, Mixed, ...Mixed[]]>(
  tag: Tag,
  codecs: CS,
  name?: string
) => TaggedUnionC<Tag, CS>
```

As you can see, the compiler seems to be collapsing the `[Mixed, Mixed, ...Array<Mixed>]` to `[Mixed, Mixed, Mixed[]]`, which is incorrect. It then doesn't like `CS` extending `[Mixed, Mixed, ...Mixed[]]`, which it considers incompatible with its incorrect collapsing.

Weirdly, if I tweak the `d.ts` file by hand, the error goes away:

```diff
- export interface TaggedUnionC<Tag extends string, CS extends [Mixed, Mixed, ...Array<Mixed>]>
+ export interface TaggedUnionC<Tag extends string, CS extends [Mixed, Mixed, ...Mixed[]]>
```

### 🙁 Actual behavior

Compilation errors

### 🙂 Expected behavior

Successful compilation

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements the following:

* When a base constraint resolves to a type reference, we no longer add a `this` type argument to the reference. Instead, `this` type arguments are only added when obtaining apparent types.
* When the target side of a type relation check is a conditional type, we ignore instantiations of the same conditional type on the source side (as we may otherwise generate a lot of useless work during variance computation).
* When obtaining constraints for tuple types, we only perform substitutions for variadic elements only when the element references a type parameter (as opposed to an arbitrary generic type). This reduces instances of deeply recursive constraints.

With these changes, the repros in #54491 now type check faster than in 5.0.

Fixes #54491.
Fixes #54495.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by Andarist** [comment]
This PR also fixes https://github.com/microsoft/TypeScript/issues/54495 , cc @alecgibson

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
@typescript-bot user test tsserver
@typescript-bot test tsserver top100

**Comment by jakebailey** [comment]
Apparently this is blocking ts-eslint from upgrading to 5.1; this is intended to be cherry-picked, right? @DanielRosenwasser

**Comment by jakebailey** [comment]
Scratch that, it's actually https://github.com/microsoft/TypeScript/issues/54542#issuecomment-1584003833

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.1

**Pull request merged**
