### PR TITLE
Fix assigned type of assignment nested in literals

### LINKED ISSUE #12946: Infinite recursion when assigning to a variable of evolving type inside an array
**TypeScript Version:**  2.0.0 / nightly

**Code**

```ts
I am getting the below error while integrating the plotly.js(v1.21.2) with typescript(2.0.0):

C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:36920
                throw e;
                ^
TypeError: Cannot read property 'id' of undefined
    at getNodeId (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13014:18)
    at getNodeLinks (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13402:26)
    at checkExpressionCached (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:22848:25)
    at C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:15426:94
    at Object.map (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:199:29)
    at getTypeOfVariableOrParameterOrProperty (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:15426:44)
    at getTypeOfSymbol (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:15561:24)
    at checkPropertyAccessExpressionOrQualifiedName (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21042:28)
    at checkPropertyAccessExpression (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:21007:20)
    at checkExpressionWorker (C:\Users\hemendra\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:22937:28) 

Please find the attached zip containing the code,  Just extract the zip and run the below commands:
[TS_Plotly.zip](https://github.com/Microsoft/TypeScript/files/654959/TS_Plotly.zip)

npm i
tsc --sourceMap

While running tsc command i am getting error as specified above. Also i have tried with typescript@next but getting the same error.

```

**Expected behavior:**
It should integrate the plotly js and compile successful.

**Actual behavior:**
Getting error while including plotly.js.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #12946

Previously, this code would cause the compiler to recur infinitely:

```ts
// @noImplicitAny: true
var target, x, y;
target = [x = 1, y = x];
```

That's because the assigned type of an assignment that is nested in an array literal includes the type of the array literal itself. In other words, to get the assigned type of `x=1`, the compiler will union the type of `1` and `[x=1, y=x]`. This cause infinite recursion.

The union code is intended to support destructuring assignment defaults, so this change makes the recursion only happen when the array literal is on the left-hand side of an assignment.

Note that it also applies to object literals, and to the initializer of for-of loops.

### CODE REVIEW

**Comment by yuit** [comment]
@sandersn  could you add test for object literal? and initializer of for-of loops

**Comment by sandersn** [comment]
@yuit Lines 5 and 6 in assignmentNestedInLiterals test object literals.

I tried to make a test for for-of and couldn't get the same untyped behaviour. However, there is a negative test in `conformance/es6/for-ofStatements/for-of45`

```ts
var k: string, v: boolean;
var map = new Map([["", true]]);
for ([k = "", v = false] of map) {
    k;
    v;
}
```

If you leave off the for-of check in `isDestructuringAssignmentTarget`, then `v=false` ignores the type of `map` and incorrectly narrows `v: false` instead of `v: boolean`.

Here's what I tried:

```ts
var target, x, y;
target = [x = 1, y = x];
// compare to
var i, a, b;
for (i of [a = 1, b = a]) {
  foo;
}
```

**Comment by sandersn** [comment]
Never mind, I got it to fail this time. I'll update the test case.

**Comment by yuit** [comment]
thanks @sandersn !

**Pull request merged**
