### PR TITLE
Check detected default npm path is really existing

### LINKED ISSUE #23924: tsserver shows 'No such file or directory' error for npm path
**TypeScript Version:**  2.8.3

**Search Terms:** `npm "No such file or directory"`

**Code**

Run following command from terminal:

```sh
$ tsserver
```

**Expected behavior:**

`tsserver` starts without any errors or warnings.

**Actual behavior:**

Following error is shown in stderr:

```
/bin/sh: /usr/local/Cellar/node/9.4.0/bin/npm: No such file or directory
```

**Playground Link:** N/A

**Related Issues:** None

This is a problem related to detecting default `npm` path in `tsserver`. At least Node v9.4.0 does not install `npm` to the same directory as `node` command. It is installed in `/usr/local/lib/node_modules/npm` like other normal npm packages.

### PR DESCRIPTION
**Pull request by rhysd**
Fixes #23924

### CODE REVIEW

**Comment by mhegazy** [comment]
@sheetalkamat and @andy-ms can you please review.

**Comment by sheetalkamat** [comment]
Why do we look in "node" folder at all? Why not always use it as "npm" so that we use default npm location and users wanting to use custom npm location can use the ```--npmLocation```

**Comment by mhegazy** [comment]
> Why do we look in "node" folder at all?

VS does not have npm installed globally, it is installed in a local folder, next to `node`.

> Why not always use it as "npm" so that we use default npm location and users wanting to use custom npm location can use the --npmLocation

we could, but that would break existing users of the server. and back then we did not have the npm location flag.

**Comment by rhysd** [comment]
You mean we should also check the file has executable permission? Maybe. But is there any case where `npm` file is not executable in the same directory as `node` command?

**Comment by mhegazy** [comment]
The check checks for the existence of a file called `npm` which never exists, it is an executable file though, so either `npm.exe` or `npm.cmd` or `npm.bat`.. so this ends up breaking VS. 

Reverted in https://github.com/Microsoft/TypeScript/pull/24425.

We need a better fix for the original issue.

**Comment by mhegazy** [comment]
I think we should list the directory and see if an npm file exist.

**Comment by rhysd** [comment]
@mhegazy I see. Actually I'm not a Windows user. So I don't know the list of possible installation directories for `npm` command...

**Comment by mhegazy** [comment]
this is not a windows thing. it is a VS thing. VS ships `node` and `npm` in-box but in some custom folders.  the only thing we know is that there is an `npm` (likely `npm.bat`) next to `node.exe` that is used to run the server.

**Pull request merged**
