### PR TITLE
Error on excessive relation complexity

### LINKED ISSUE #55630: Compiler crash with `RangeError: Map maximum size exceeded`
### 🔎 Search Terms

RangeError: Map maximum size exceeded
RangeError: Value undefined out of range for undefined options property undefined (node 16)
react types
antd types
fontawesome types

### 🕗 Version & Regression Information

- This is a crash
- I've tested this with the latest nightly (5.3.0-dev.20230904), 5.2.2 and 5.1.6
- I was unable to test this on prior versions because I've converted my code to ts and it started to occur

### ⏯ Playground Link

_No response_

### 💻 Code

Simple file:
```tsx
import React from 'react';
import {Menu} from 'antd';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';

type IconProp = React.ComponentProps<typeof FontAwesomeIcon>['icon'];

type Props =
  & React.PropsWithChildren<{ icon: IconProp }>
  & React.ComponentProps<typeof Menu.Item>

export const Item = ({icon}: Props) => {
  return <FontAwesomeIcon icon={icon}/>;
};
```

package.json
```json
{
  "name": "ts-compiler-crash",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@types/react": "^18.2.21",
    "typescript": "^5.2.2",
    "antd": "~4.2.0"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2019", "es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6",
    "jsx": "react",
    "noEmit": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noFallthroughCasesInSwitch": true
  }
}
```

### 🙁 Actual behavior

Compiler crashes with

```
yarn tsc
yarn run v1.22.19
$ /Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/.bin/tsc
/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:116479
      throw e;
      ^

RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at recursiveTypeRelatedTo (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60782:18)
    at isRelatedTo (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60199:122)
    at typeRelatedToSomeType (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60460:25)
    at unionOrIntersectionRelatedTo (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60380:16)
    at structuredTypeRelatedToWorker (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60959:23)
    at structuredTypeRelatedTo (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60801:21)
    at recursiveTypeRelatedTo (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60754:19)
    at isRelatedTo (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60199:122)
    at eachTypeRelatedToType (/Users/gabrielrohden/Desktop/Projects/Personal/ts-compiler-crash/node_modules/typescript/lib/tsc.js:60555:25)

Node.js v18.17.1
error Command failed with exit code 1.
```

### 🙂 Expected behavior

The compiler to at least not crash :/

### Additional information about the issue

There's a related issue https://github.com/microsoft/TypeScript/issues/50290

But its closed, so I'm opening a new one since that one wasn't really [fixed but workarounded](https://github.com/microsoft/TypeScript/issues/50290#issuecomment-1228824018)

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we now error when computing a relation is excessively complex. Specifically, when computing a relation results in adding more relation cache entries than 1/8th of the current capacity of that relation, we issue an error. Relation caches use JavaScript maps, which in Node.js are limited  to 2^24 (~16M) entries.

An example of a relation computation that is excessively complex is the following:

```ts
type Digits = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
type T1 = `${Digits}${Digits}${Digits}${Digits}` | undefined;
type T2 = { a: string } | { b: number };

function f1(x: T1 | null, y: T1 & T2) {
    x = y;  // Excessive complexity error
}
```

Above, `T1` is a union with 10,001 members, and `T2` normalizes to a union with 20,002 members.

This PR further implements an optimization outlined [here](https://github.com/microsoft/TypeScript/issues/55630#issuecomment-1731740610). For example, the following example doesn't cause an excessive complexity error because we now have a fast path when relating a union resulting from normalizing an intersection of large unions to one of those same unions.

```ts
function f2(x: T1, y: T1 & T2) {
    x = y;  // Ok
}
```

Fixes #55630.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Review by gabritto — APPROVED** [review]

**Comment by gabritto** [comment]
On PR https://github.com/microsoft/TypeScript/pull/50329, @weswigham had proposed a more general form of the optimization found on this PR. What's the reasoning behind picking this simpler form of the optimization instead?

**Comment by ahejlsberg** [comment]
> What's the reasoning behind picking this simpler form of the optimization instead?

I hadn't seen #50329, but certainly the optimization in this PR removes far more work when the fast path is available. There's no reason the two couldn't co-exist.

**Comment by ahejlsberg** [comment]
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Pull request merged**
