### PR TITLE
Mark indexed access object type comparisons as unreliable

### LINKED ISSUE #52096: Uncomputed generic type does not follow structural typing
# Bug Report

### 🔎 Search Terms

generic
unassignable type
uncomputed type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about:
  - [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs)
  - [Type System Behavior](https://github.com/Microsoft/TypeScript/wiki/FAQ#type-system-behavior)
  - [Generics](https://github.com/Microsoft/TypeScript/wiki/FAQ#generics)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?pretty=true&ts=4.8.4#code/MYGwhgzhAECC0G8CwAoa7oA8Bc0IBcAnASwDsBzaAXmgHJZaBuVDaAT11IFcBbAIwCmhatAAMzFAF9UqUJBgAhRCww48RMpRq0FTFegBeuPgHsTIAWFIiiXAROkpU+NgAcB0ACoAeABrQBTHwBUgATGAQsXCs2aEkAPhEABWJgAGs-ABo6TFp4iWc3DwBhER9YfML3aAARMu8FSqcUF2rigH1A4LCIdrqaUq6Q8NroAH5oWw9cADMwEAh7VmWV1bXWAHoNycI7Ko8U9NhOoOHew7SlGgvvWGzaXMShnugbhXvH8Z27aFn5xcYm22U32XmOz3C7U8Vy8tyepxePkaXymv2gcwWS3W2JWW3R-w8AAoxgBKGQoUICOSEDwWfDQMC4cpNSnU2kCel8JkNFlU8A06B06DAXDFCSs-ns+mhXA1AooPgiMCA5Z4oSEEzCAAWQiJpNkIlCjCAA)

### 💻 Code

```ts
class A {
    x: string = 'A';
    y: number = 0;
}

class B {
    x: string = 'B';
    z: boolean = true;
}

type T<X extends { x: any }> = Pick<X, 'x'>;

type C = T<A>;
type D = T<B>;

type C_extends_D = C extends D ? true : false;                                  // true
type PickA_extends_PickB = Pick<A, 'x'> extends Pick<B, 'x'> ? true : false;    // true
type TA_extends_TB = T<A> extends T<B> ? true : false;                          // false (?)

declare let a: T<A>;
declare let b: T<B>;
declare let c: C;
declare let d: D;

b = a;      // error here (?)
c = d;
```

### 🙁 Actual behavior

- Type `TA_extends_TB` is `false`.
- `a` is not assignable to `b`.

### 🙂 Expected behavior

- All types `TA_extends_TB` should be `true`, the same way as `C_extends_D` and `PickA_extends_PickB`.
- `a` should be assignable to `b` and vice-versa, the same way as `c` and `d`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #52096

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
Anything that messes with variance-based vs. structural relations has me worried. Let's see what the test suites uncover.

**Comment by fatcerberus** [comment]
I’m confused - there don’t appear to be any indexed accesses in #52096?

**Comment by RyanCavanaugh** [comment]
`Pick`'s definition uses indexed access types

**Comment by weswigham** [comment]
All the suites and perf look fine, nice~

**Comment by RyanCavanaugh** [comment]
@ahejlsberg any remaining concerns?

**Comment by sandersn** [comment]
@ahejlsberg @weswigham should this go in for 5.0 beta?

**Comment by sandersn** [comment]
@weswigham I think we can get enough coverage by merging this at the beginning of 5.1, so I vote to merge it now.

**Pull request merged**
