### PR TITLE
Tweak co/contra inference logic from #52123 

### LINKED ISSUE #52179: Type parameter on ts.some/ts.find is too narrow when called on union of arrays, works with explicit instantiation
This is a follow-up to #52111 and #52123.

In the below code, `every` works as expected, which is new as of #52123. However, the `some` function can't be called on the array type at all, even though reasonably there's a top type which works (`A`), just like it works for `every`.

```ts
interface A           { a: string; }
interface B extends A { b: string; }
interface C extends A { c: string; }

declare function isC(x: A): x is C;

declare function every<T, U extends T>(array: readonly T[], callback: (element: T, index: number) => element is U): array is readonly U[];
declare function every<T, U extends T>(array: readonly T[] | undefined, callback: (element: T, index: number) => element is U): array is readonly U[] | undefined;
declare function every<T>(array: readonly T[] | undefined, callback: (element: T, index: number) => boolean): boolean;

declare function some<T>(array: readonly T[] | undefined): array is readonly T[];
declare function some<T>(array: readonly T[] | undefined, predicate: (value: T) => boolean): boolean;

function foo(array: readonly B[] | readonly C[] | undefined) {
    if (every(array, isC)) {
        array;
        // ^?
    }

    if (some(array)) {
        array;
        // ^?
    }

    if (some(array, isC)) {
        array;
        // ^?
    }
    
    if (some<A>(array)) {
        array;
        // ^?
    }

    if (some<A>(array, isC)) {
        array;
        // ^?
    }
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function foo(array) {
    if (every(array, isC)) {
        array;
        // ^?
    }
    if (some(array)) {
        array;
        // ^?
    }
    if (some(array, isC)) {
        array;
        // ^?
    }
    if (some(array)) {
        array;
        // ^?
    }
    if (some(array, isC)) {
        array;
        // ^?
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230109#code/JYOwLgpgTgZghgYwgAgILI5ryDey4BcyAzmFKAOYDcyAvgFCiSyIoBCyEAHpCACbE0uZACMipciGp1G4aPCTIAwpx4R+g9HgTiylGg3p8ICADZwoKGAFcQCMMAD2IZMGJKAFFyKoAlES5XQSUqeiMTc0tkGzsHZ04AN2gATwAeABUAGmQAVVVeAWR0gD4PCyg4ZKJLOD5nU2SigG0AXWyEOFNTEUQAayIPCFMIAFt1MCIs135uIhBrEZFoX2QAXmLOYbHwINz-fCgKxrdkGrqQBtzW0OMzCytbeycXCCSoNKm87gLBErLDyrVCC1eqNdKtZAAH2QtmMMFAED47U63T6AyGo3Gk2yoGM3mQ80WyzWGwx2zAuxy+3KlV2Z1BVxaUJhM3hIERNwi92ijziLzeH1KNKqp2B50u4KZ0NhEDZiORXR6CH6yEGWyxRRxM3xhKWUBW61EjkcwzgIH2ImNppAoXCdyiMSe8WIjjGGSFAJF9IuYIh0tZCL41M9dLFDMlnPtD1izxIrog7v+RyBIJ9zSlLLhgeyAAdLHxgB1IAMEp1rBBJgaNpaTcDzUQa9bbY6+dFjUnAaLU5c2H6u+LGko+zK5UHcPQsMAYKrXikO8kce5fCscBPsBhhaF1xgAPQ75AAPQA-GuMIZJ9OPC6xvPl+Ptwcjlvt3vDyesOfMFPVdeIPPF0od6rg+m6ntgr7HmBDBYGB35XvGqSoB6RxAWBWCgQ+EHvpgn4YHBv6IchlQAahIGes+65YVB9AMEAA)

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #52179

In the case of `coAndContraVariantInferences4`, we end up with `Modifier` as the covariant type, but that isn't a subtype of both `Modifier` and `Decorator`, so it shouldn't be chosen; we instead want `Node`, the contravariant inference. But, if you flip things and test for `Decorator` instead, `Modifier` is _still_ the covariant inference, but now it doesn't match `Decorator`, so we get the desired result, `Node`.

This tweaks the logic from #52123 by ensuring that even the _current_ inference's candidates are checked against the inferred covariant type; this effectively removes the problematic choice for the covariant type produced via union ordering.

I'm not an expert; maybe the better win is to change `getCovariantInference` somehow. I just tried this and was surprised that it fixed all of my examples and broke no other test.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
This PR turns out to only fixe some of the examples in the linked issue.

- [Playground Link](https://www.staging-typescript.org/play?ts=5.0.0-pr-52180-7#code/JYOwLgpgTgZghgYwgAgILI5ryDey4BcyAzmFKAOYDcyAvgFCiSyIoBCyEAHpCACbE0uZACMipciGp1G4aPCTIAwpx4R+g9HgTiylGg3p8ICADZwoKGAFcQCMMAD2IZMGJKAFFyKoAlES5XQSUqeiMTc0tkGzsHZ04AN2gATwAeABUAGmQAVVVeAWR0gD4PCyg4ZKJLOD5nU2SigG0AXWyEOFNTEUQAayIPCFMIAFt1MCIs135uIhBrEZFoX2QAXmLOYbHwINz-fCgKxrdkGrqQBtzW0OMzCytbeycXCCSoNKm87gLBErLDyrVCC1eqNdKtZAAH2QtmMMFAED47U63T6AyGo3Gk2yoGM3mQ80WyzWGwx2zAuxy+3KlV2Z1BVxaUJhM3hIERNwi92ijziLzeH1KNKqp2B50u4KZ0NhEDZiORXR6CH6yEGWyxRRxM3xhKWUBW61EjkcwzgIH2ImNppAoXCdyiMSe8WIjjGGSFAJF9IuYIh0tZCL41M9dLFDMlnPtD1izxIrog7v+RyBIJ9zSlLLhgeyAAdLHxgB1IAMEp1rBBJgaNpaTcDzUQa9bbY6+dFjUnAaLU5c2H6u+LGko+zK5UHcPQsMAYKrXikO8kce5fCscBPsBhhaF1xgAPQ75AAPQA-GuMIZJ9OPC6xvPl+Ptwcjlvt3vDyesOfMFPVdeIPPF0od6rg+m6ntgr7HmBDBYGB35XvGqSoB6RxAWBWCgQ+EHvpgn4YHBv6IchlQAahIGes+65YVB9AMEAA)
  - All fixed but one, which can be worked around by changing `some`.
- [Playground Link](https://www.staging-typescript.org/play?ts=5.0.0-pr-52180-7#code/KYOwrgtgBAygniALgQwB4GkCWIAmUDeAUFCVAEIA2A9gMYDWANMaQJI6iKYBmmwATk1JQAwsgDOwYRWRgJg0gDEwIGpyogAoqgAOfYGLGZ18kkpVqQAEWA1pfZBaYBfQoWyJ+XZDWBQAclTsBFB02DgAXLAIKBhhANxQLu6e3r5auvqG6lDAqB64Yv6BvvhQAPq5GQZGIGT2uJHIIHAJSUgpPlDWtsj2Fjl5oDiFAUGlZew9fTV1TRFQTS2Jbu18Xp2UtHQD+cNFYyFhkfBIaFi4AHSb9K2uk3a+XMqqNVA8uAA8ACoMUACqOyGhS+AD4ABS9exwSJ6ZA4dQUOBQL4AbQAulAAD5QZTsd7AHC-DI4TA0BzASJg4AUYAQDiRH5QMK5SLgCAAI34AEooABeEE5Gl0pBMwp-X5iFB8RAsXC5AD8rMgnL4XMiAOxuOA+JwcUI916j2e-XeOG+4MhyGhUFh8JAiOR6KxOLlOqJehJZI8lOptPpyN+zNQSo53L5AvZVCoNKaEqlMrlqEVUDZKrVyOdWp1esIT3Mry4UYhfChMOAcIRSO6dgcNSd2NtlfI1Ho9ZdeOwBJ5RCENHUkoWfLeYWLUN+YJAxR5-KgiD4YGAXISAHplzkS1Q+ABCZgkVdCAB68tcu6gfZAA-ZQ9NH2rvVr2Wx1zoFpLVvHk-Y04Fc4XS9P+6kEeri9v2iBnteYQfKMwCvmOUATlO4azvOi56kIgEkMBThAA)
  - Not fixed at all.
- [Playground Link](https://www.staging-typescript.org/play?ts=5.0.0-pr-52180-7#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoHiB7AOxlCyIwFtQBlATyOgEMAPAaXiIBNQBvHUINABZAl3gAzeFlgAaAUIAiWQrCbQCcnAF88naDIlNEWUADkxp-kNABrTlzT1GrDtwDcOvY0PHTo8SkZMhYDbkhzSz47BycGZnYHADoAyWlYd1BdfV8TUGVVdU0QsK4Iiy4rGO44l0TuJILNIoysvErEABsmWFMJDCJkeGJQeEhUoNgACiJLNAqsAEo0WcrRiIn0zw7u3tB+wehhonWmtQ1p1ax5y2XQK-X8lWaLzxwdnr6BoZGsADcZHQADwAFVkoAAqiVyGVQCCAHxTHpqOhoXpMLjETp0OEAbQAuuDEExOp0AEbGWxoKZYTpYSjkVBwxagAC88LIdIZjEeELuyKYOLGoHRmKI2MhBLeHz2hBI0FAlDEaRkkDRWAxWJxmxkBNAAB8RRqxRKzi0pXgDj8ThICAQpizrEJ-oCpkrAulIOCxjrYItMiAyLBYJoAPygKYDSqQeC9LiLBSCF2wOhu5WTL2nZ7nTT+0CB2ZBkOwCPR2NYeM6IA)
  - Fixed.

**Comment by ahejlsberg** [comment]
Interesting situation... Co-variant inferences have no common supertype, so we pick the first in anticipation of an error being issued as a result. However, we could have succeeded by picking the contra-variant inference. Yup, we could do better here. I like your proposed fix.

**Review by ahejlsberg — APPROVED** [review]
Approved assuming performance is unaffected and tests are clean.

**Comment by jakebailey** [comment]
All user/top100/etc tests are clean; waiting on perf tests though since I have to merge a fix to main first to unblock it.

**Comment by jakebailey** [comment]
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
Just tested this on #49929 and it works really well; even more cases I didn't notice are fixed, including inference I worked around with this:

```ts
function castToNodeArray<T extends Node>(nodes: readonly T[]): NodeArray<T> {
    return cast<NodeArray<T>, readonly T[]>(nodes, isNodeArray);
}
```

I'll add these newly found examples as test cases here.

**Comment by jakebailey** [comment]
Nah, nevermind; forgot that it was to do with the fact that I had to change cast's signature until #52123, so the above code was already not needed even before this PR, which is more about the union thing when there's ambiguity.

**Comment by jakebailey** [comment]
Perf looks the same (normal noise). Thanks for the review!

**Pull request merged**
