### PR TITLE
Only collect outermost intra expression inference sites

### PR DESCRIPTION
**Pull request by Andarist**
It's a potential perf improvement. However, I don't expect this to yield significant gains in the automated tests - this can probably only show in more pathological cases with big objects used as arguments. It happens that in XState we deal with such so maybe I would be able to gather some more concrete data based on that. 

At the moment, in a case like this:
```ts
declare function fn<T>(args: {
  foo: {
    bar: {
      baz: {
        producer: (arg: unknown) => T;
      };
    };
  };
  consumer: (val: T) => unknown;
}): T;

fn({
  foo: { // 4
    bar: { // 3
      baz: { // 2
        producer: (arg) => 1, // 1 (function itself)
      },
    },
  },
  consumer: (val) => {},
});
```

we collect **four** intra expression inference sites. The innermost function (site 1) "taints" all the objects containing it (minus the root one). This is because `isContextSensitive` is recursive. 

This means that `isContextSensitive` has to be computed at all of those levels **and** that we end up inferring from all of those levels separately within `inferFromIntraExpressionSites`. Most of that work is more than duplicated here since the outermost expression contains all of the information that can be found in the expressions contained in it.

### CODE REVIEW

**Comment by jakebailey** [comment]
The perf machine is currently offline but I'll run that once it's back again and caught up. If you can show a diff before/after in your xstate case that'd be helpful!

@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

**Review by weswigham — APPROVED** [review]
IMO, it'd be nice if we had a pathlogical test that this fixes in our test suite, eg, a constructed examples this takes from 50s (timing out) down to 5s (since, unless I'm mistaken, this is the category of change that, in constructed examples, takes something from exponential time to linear time). While this is good, since it doesn't show much change in the perf suites, without anything benching the improvement, this might get lost in a future update without such a test.

**Comment by Andarist** [comment]
I see that for some reason `main` is failing after merging this -> I'm investigating this.

**Comment by jakebailey** [comment]
Probably just that the branch was out of date when it was merged.

**Comment by Andarist** [comment]
Ye, right - I narrowed it down to a silent conflict with: https://github.com/microsoft/TypeScript/pull/54380 , looking now if I can make it work in a reasonable time.

**Pull request merged**
