### PR TITLE
Use fileExists check for file system case sensitivity instead of relying on the platform

### LINKED ISSUE #7154: Broken intellisense for mounted filesystem
I've got a broken intellisense for a mounted file system for VSCode. Though it works in older versions of TypeScript. Any thoughts on what is wrong?

Please check out:
https://github.com/Microsoft/vscode/issues/3160

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #7154

### CODE REVIEW

**Comment by billti** [comment]
I don't see how this helps in the commonly reported case where folks are opening projects off mapped drives. This checks `__filename`, which is the currently executing file (i.e. `tsserver.ts`), which is likely installed locally with the editor (or plugin), not on the mapped drive where a project may live.

**Comment by vladima** [comment]
agree with @billti - the issue here is that case-sensitivity can vary between mounted volumes.

**Comment by zhengbli** [comment]
Maybe it makes more sense for the `useCaseSensitivity` value to be a project property instead of a host property, because as pointed out it may vary from project to project.

**Comment by billti** [comment]
Agree it makes more sense per project. I would test whatever the first file loaded for a project is (whether that be a .ts/.js file or the tsconfig.json file), as I doubt one project would be spread across volumes with different case sensitivity (and if they are... too bad).

**Comment by zhengbli** [comment]
Close in light of #7658

**Pull request closed without merging**
