### PR TITLE
fix: string.replace `any[]` => `(string | number)[]`

### PR DESCRIPTION
**Pull request by bluelovers**
Fixes #

### CODE REVIEW

**Comment by acid-chicken** [comment]
Type of the second argument of the replacer from the last is `number`, so `string[]` seems invalid. How about `(number | string)[]`?

FYI: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_function_as_a_parameter

**Comment by sandersn** [comment]
@bluelovers can you please open a bug for this. Changes to the lib are *really* *really* hard to make without breaking somebody by mistake. We need to come up with as many examples as possible to decide if this change is the right one.

**Comment by sandersn** [comment]
@bluelovers Checking up on older PRs: do you want to keep working on this?

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.

**Pull request closed without merging**
