### PR TITLE
Fix bug: normalize path after combining

### LINKED ISSUE #19113: Import path quick suggestions - jsconfig aliases not recognised
_From @mudrz on October 10, 2017 7:58_

- VSCode Version: 1.17.0
- OS Version: macOS High Sierra 10.13

Reproduces without extensions: Yes

Doesn't work properly with aliases added in `jsconfig.json` https://code.visualstudio.com/docs/languages/jsconfig

Sample `jsconfig.json`
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "ClientApp/*": ["./ClientApp/*"]
    }
  }
}
```
Expected behaviour
```js
import Something from 'ClientApp/...'
```
will pull path intellisense for folder `ClientApp`

Existing extension [path-intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) for example can also be configured with aliases in `settings.json`
```json
"path-intellisense.mappings": {
    "ClientApp": "${workspaceRoot}/MvcProject/ClientApp",
  }
```

_Copied from original issue: Microsoft/vscode#35970_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #19113 (the one remaining bug as far as I can tell)
(Continuation of #21072)

### CODE REVIEW

**Comment by web-dave** [comment]
Is this fix in the released version? Face the issue: build is OK but vscode says error.

**Comment by andy-ms** [comment]
@web-dave It's possible that vscode is using a different TypeScript version than your build. Could you check that both are using `typescript@next` (in vscode it should tell you the TS version in the lower-right -- instructions [here](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)), and file a new issue if there is one?

**Comment by baflo** [comment]
@andy-ms I'm running 2.71 in my workspace and with vscode. But I don't get code completion running as expected (it would work with `app/...` though): 

image

**Comment by andy-ms** [comment]
@baflo I was able to get completions in `2.7.1` using:

**tsconfig.json**:
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@app/*": ["./app/*"]
    }
  }
}
```

**src/a.ts**: `import {} from "@app";` (type a `/` after `@app` to get completions)

**src/app/b.ts**: `export const x = 0;`

Does this work for you? If so, could you try and get a simplified version of your situation that doesn't have the completions?

**Comment by baflo** [comment]
Hey @about-code, I played a bit with your config. And I _kind of_ get positive results. But not continuously. 

Say I have your structure, but additionally a folder __src/c__ with files __src/c/c.ts__ and __src/c/index.ts__, then I _can_ resolve __b.ts__ but not files in __src/c__ (only when I manually add the `c/`):

image


image

With the `baseUrl` setting it works well, however:

image

**Comment by andy-ms** [comment]
@baflo Thanks, looks like that was a bug that didn't show up in tests due to our test host differing from the real one.

**Comment by pie6k** [comment]
I've set VS Code ts version to 2.7 and I'm still have issue with paths not working properly

image

image


image

**Comment by andy-ms** [comment]
@pie6k Thanks, fixed in #21704

**Pull request merged**
