### PR TITLE
Disallow `Infinity`, `-Infinity` and `NaN` as an enum key name

### LINKED ISSUE #48956: Enum with special numbers overwrites own value
# Bug Report

### 🔎 Search Terms

Enum number computed overwrite Infinity NaN

### 🕗 Version & Regression Information

I noticed on 4.6.2, but using TS Playground am able to reproduce on earliest possible version (3.3.3). Also still occurs on nightly build.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/PQKhCgAIUgVALAlgZ0gUwHYFcC2kDuA9gE4DWqAhqmgB4AOaAxgC5oAmUIw4mukAovSas2kAN5RIUgGIB5WZAC8kAOQAzQoRUAaSVIBCAQQBKSyAEZdUqSsgBFAKqzY-ACKqzKx87crwAX3BwRkIMZEIAGzQAOgjCAHMACkEGFnZouQVFbNUNLQBKAG5IYGBIZmIsNGDQ8KjYhOShNLZoo1Ns5XMikrKKqpqwyJi4pJThdgBtW28XdxUAXSUcryc5lR7S8srqwbqRxvGWjPll5RUAZUIcNEhCZng0YkhkCsQMeI3irbUKCOQ0NpIBQMKJmABPBjIRjERB0ZgECjEMJ7YYNMbNERtExnSAAJk2ZV+-0BwNB5UhaGhsPhiORyCCoAg0DgSGo2DwbEIVMgGHuBBIpGB1Ex7CsMBBogoLCwfwi4LuADcnvhYaxUIhmKhCPgMJBFX8qshopxuCEwgjCAAjABWwgAMpqnn8zGJ-IUeBzIABha50LAicSSACSGDU701CuUofDGEjVkgADkKImzMnEwmVABaPHRPF4gAMABYiwA2YsATjxAFYCwBmcx1tBZ8yl2zKXP54tlys1+uN5uthNbWAXSAAdSRYUgGmeDxQ+qeyEQoUgiStAd5-NnwIiEUXxGXtWA5vD8WQ+SBG4Rr0Qe8gIRwdDvVMkW19OBuGEtm+YhEgxBoDghDKnScYfJIKiTNadosJAsi2sICztnciEsI6rDEH8CbYPeyi4REASovUoyJB+-pYjGEYQriVFxhC+S9DOfwAsRBxJORAbpHRka4ioPEQhsTH9LciRoMqeoPIQWDxPAkCag+foRBQ7wXkE5r7OiZF+lxrTpri6aMT8LHVBpaKkZxWL6Z0qjpkJWwiWu4mYOU8DSbJ8kIo+dDKap+TqbU5mNJZUxQTBwjwWhzDIUsNnhehTpYRERlEiZbFaSFbDTNBUWRbB0WLFINlhblCH5chKXbFUTkSa57lyQp3m+WE-npRZOlYgRuIEZVxKsWZJHBR16RdcVBH2X0Ow1S5UkyQ1XlKSpLVAA)

### 💻 Code

```ts
enum Computed {
  Infinity = Infinity,
  NaN = NaN
}
```

### 🙁 Actual behavior

Typescript generates the following code for that enum using a "lookup object":
```ts
var Computed;
(function (Computed) {
    Computed[Computed["Infinity"] = Infinity] = "Infinity";
    Computed[Computed["NaN"] = NaN] = "NaN";
})(Computed || (Computed = {}));
```

As a result, the Computed enum actually has values of Strings, rather than the "computed" numbers as expected
```ts
console.log(Computed);
// { Infinity: 'Infinity', NaN: 'NaN' }
```

Note the "lookup object" behavior itself is not unexpected, but the side effect of overwriting keys is unexpected.

### 🙂 Expected behavior

Typescript should not overwrite an existing key with a new value. Most likely that would mean disabling the "lookup values" for computed.

```ts
console.log(Computed);
// { Infinity: Infinity, NaN: NaN }
```

### Extra Discussion

This does not impact `const enum` because values like `Infinity` are considered "computed".

It is also possible to do something like
```ts
enum Computed {
  '[object Object]' = {},
  null = null
}
```
with similar results. 
The latest versions of typescript warn at this behavior, but it is possible to compile and I don't think it warns on _all_ versions. But I omitted from core issue for that reason.

Similarly
```ts
enum Overwrite {
  123 = 'FOO',
  BAR = 123,
}
```
has similar behavior (when compiled) but TS does warn about numeric names (I believe this warning occurs in all versions).

It does not occur when using string enums, as those never write "lookup objects"
```ts
enum NoOverwrite {
  FOO = 'SOME VAL',
  BAR = 'FOO',
  BAZ = 123
}
console.log(NoOverwrite);
// { 123: "BAZ", FOO: "SOME VAL", BAR: "FOO", BAZ: 123 }
```

Effectively this issue happens whenever the `String(val)` (generally `.toString()` internally) returns a key in the Enum.

Possible solutions:
* Don't emit "lookup object"
  * I'm going to assume the lookup object behavior is intentional/beneficial for literal numbers, but perhaps not for computed... Although values like `1 + 2` are "computed" but are resolved at compile time. So maybe "computed" where the value is anything but a number literal.
* Forbid special "numeric" names
  * Don't allow `NaN`, `Infinity` or `-Infinity` as an enum key name. There may be others I am not aware of right now... but I was not able to reproduce error with exponential notation like `Number.EPSILON` ("An enum member cannot have a numeric name.")
* Don't allow computed values that are non numeric literals
  * Throw compile-time error when value is something like Infinity, but allow literals.
    ```ts
    enum Allowed {
        FOO = 1 + 2
    }
    enum NotAllowed {
        BAR = 1 / 0
    }
    ```

### PR DESCRIPTION
**Pull request by magic-akari**
- Fixes #48956

### CODE REVIEW

**Review by sandersn — APPROVED** [review]

**Comment by jakebailey** [comment]
I can't recall; was banning this actually something we wanted? Can't remember what we said in the design meeting, or maybe we didn't talk about it at all?

**Comment by sandersn** [comment]
My memory is that we briefly discussed this and said "yes of course you can't do that because of the lookup object", but I could be wrong.

We did discuss Infinity *types* a couple of weeks after your comment, but that's the only mention of Infinity and NaN in the design notes. And then a couple of days after that, we discussed enum assignability. So it sounds like my memory smudged the two discussions together and in fact we never did.

I still think this is a good thing to forbid since the emit is bad and it's unlikely to be something people want to write.

**Comment by jakebailey** [comment]
My impression was that this PR was good, as they're not good enum names, but that the recent `infinity` chat was about the whole `1e999` thing allowing a half-functional backdoor into gaining an infinity type, which we banned but then backed out and decided that we were instead going to look into introducing those literal types into the type system instead.

**Review by jakebailey — APPROVED** [review]
Yep.

**Comment by JoostK** [comment]
@DanielRosenwasser This change  is missing from breaking changes section in the [the blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#breaking-changes), perhaps it can be included.

**Comment by DanielRosenwasser** [comment]
I'm surprised we merged this because the logic was explicitly there, and was added 8ish years ago

- https://github.com/microsoft/TypeScript/issues/6153
- https://github.com/microsoft/TypeScript/issues/6347
- https://github.com/microsoft/TypeScript/pull/10749

Given that there's no linked design meeting notes, in the future let's have a more intentional discussion before merging a change like this.

**Pull request merged**
