### PR TITLE
Fix missing narrow with assignment

### LINKED ISSUE #37883: Assignment expression fails to narrow
**TypeScript Version:**  3.8.3

**Search Terms:** method type guard, return value, assignment expression

**Code**

```ts
type AorB = A | B;

class A {
    isA(): this is A { return true; }
    doA() { }
}
  
class B {
    isA(): this is A { return false; }
}

function f(): AorB { return new B(); }

// compiles
let aorb: AorB = f();
if (aorb.isA()) {
    aorb.doA();
}

/* does not compile:
  Property 'doA' does not exist on type 'AorB'.
    Property 'doA' does not exist on type 'B'.(2339)
*/

if ((aorb = f()).isA()) {
    aorb.doA();
}
```

**Expected behavior:**

```ts
let aorb: AorB = f();
if ((aorb).isA()) {
    aorb.doA();
}
```

to be equivalent to 

```ts
let aorb: AorB;
if ((aorb = f()).isA()) {
    aorb.doA();
}
```

**Actual behavior:**

the later fails to compile with 

> Property 'doA' does not exist on type 'AorB'.
>   Property 'doA' does not exist on type 'B'.(2339)

**Playground Link:** 

https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=100&pc=1#code/C4TwDgpgBAgg9gJwEJQLyygHykg3AKHwGMAbAQwGcKMBvfKBqASwpgAoBKALimAAsWzajCg0oCCMACuCAHa8EUiLigBfeowAmcdh1Fr86hsXJUcojQxa6e-QYJFiJ0uVABmZEhWUH1+N1KyRMBMcPJunDzwyPrOMvKyEADuOJwqfgD0GVBEcAC2YEwkEBT4xcBQZIgARlGIKOgRHARMblBsVQjVAHTWnHp0jJU13dq6BJkAVFDaJVCycBW5BUUQXBoACghwkAigUADkYwczcHMLFRAAHiwVYbzg0AfRSAfdllBbOxB7IIfHp3Oiyg11uUHuoEgh1e3TYACYAMwIgCcHHwkwyhFa7Q6NTQ7n6vVY-QsQ06PTGaUMQA

**Related Issues:**

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #37883

### CODE REVIEW

**Comment by Kingwl** [comment]
cc: @sandersn @DanielRosenwasser 
Maybe it's better to merge before rc?

**Comment by sandersn** [comment]
It's not a regression, so I don't think it's super urgent. @ahejlsberg or @weswigham can you review this so we can get it into 4.1?

**Comment by Kingwl** [comment]
Up. Why this does not included at 4.0.....

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
Wow! I'm glad I ran that. A lot of results seem to regress by several seconds (though some strangely speed up). Maybe one more just for kicks.

@typescript-bot perf test this

**Comment by Kingwl** [comment]
Maybe after merge master again? Hold on...

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by weswigham** [comment]
@DanielRosenwasser  ?

**Comment by Kingwl** [comment]
@typescript-bot pack this.

**Comment by sandersn** [comment]
@DanielRosenwasser sounds like we never got a straight answer on performance. Let's not merge this until we do.

**Comment by Kingwl** [comment]
Seems already fixed? (https://github.com/microsoft/TypeScript/issues/37883). So. Close this.

**Pull request closed without merging**
