### PR TITLE
Reduce stack depth during emit

### LINKED ISSUE #13549: using non-recursive walks over the AST
**TypeScript Version:**  nightly (2.2.0-dev.201xxxxx)

**Code**

```ts
'' + (repeats 2000 times) + '';
```

**Expected behavior:**
Accept as valid TS.

**Actual behavior:**
`RangeError: Maximum call stack size exceeded`

Not sure if this is feasible (so feel free to close), but we did reach this error during some code generation from html to ts. We resolved it by using `['', '', ...., ''].join()` (could have also added some parens), which generates a flat AST, vs the deep AST coming from multiple '+' expressions.

//cc @mprobst, @evmar, @calebegg

### LINKED ISSUE #21720: Very deep ASTs crash the compiler
Very deep ASTs crash the compiler. Illustrated in this issue by an impressively long chain of functions calls. (Actually happened in our code base.) Bug #13549 talks about this but related to many successive addition operators. I would like to suggest that instead of crashing, the AST depth is measured and a descriptive error is displayed when it exceeds a limit. In this example on my environment the limit is 235 chained function calls.

**TypeScript Version:**  2.8.0-dev.20180206

**Search Terms:** Maximum call stack size exceeded, chained, method chaining, function chaining

**Code**
```ts
class Example {
    public chained(): Example {
        return this;
    }
}

const instance = new Example();

instance
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained() // 64
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained() // 128
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained() // 192
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained()
    .chained().chained().chained().chained().chained().chained().chained().chained();// 256
```

**Expected behavior:**
It compiles.

**Actual behavior:**
Compiler crashes:
```
$ tsc chains.ts 
/.../typescript/lib/tsc.js:60398
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at emitNodeWithNotification (/.../typescript/lib/tsc.js:54158:42)
    at pipelineEmitWithNotification (/.../typescript/lib/tsc.js:56913:17)
    at emitExpression (/.../typescript/lib/tsc.js:56909:13)
    at emitCallExpression (/.../typescript/lib/tsc.js:57660:13)
    at pipelineEmitExpression (/.../typescript/lib/tsc.js:57219:28)
    at pipelineEmitWithHint (/.../typescript/lib/tsc.js:56940:32)
    at emitNodeWithSourceMap (/.../typescript/lib/tsc.js:54432:24)
    at pipelineEmitWithSourceMap (/.../typescript/lib/tsc.js:56930:17)
    at emitNodeWithNestedComments (/.../typescript/lib/tsc.js:54702:17)
    at emitNodeWithSynthesizedComments (/.../typescript/lib/tsc.js:54652:13)
```

**Playground Link:** Does not reproduce at https://www.typescriptlang.org/play/

**Related Issues:** #13549 describes the same problem but caused by successive addition operators and suggesting a different solution.

### PR DESCRIPTION
**Pull request by rbuckton**
This reduces the overall call stack depth of the emitter for very large ASTs. Its still possible to exhaust the call stack, but not before we also would exhaust the call stack in the checker.

Fixes #21720
Fixes #13549

### CODE REVIEW

**Review by mhegazy — APPROVED** [review]
Do you see any perf gains form this change?

**Comment by rbuckton** [comment]
No, unfortunately. It seems like the emitter is about 8% slower with this change. I need to investigate further.

**Comment by sheetalkamat** [comment]
If it helps, I had noticed that using f = noop or actual function instead of doing checks of if (f) { f()} was faster and hence old emitter used that more.

**Comment by mhegazy** [comment]
@rbuckton is this still something you are pursuing, or should we close this PR?

**Comment by rbuckton** [comment]
It is, but I ran into perf issues I haven't been able to track down yet.

**Pull request closed without merging**
