### PR TITLE
BigInt constructor should not accept any type

### LINKED ISSUE #38980: BigInt constructor should not accept any type
**TypeScript Version:**  3.9.3

**Search Terms:**

**Code**

**Expected behavior:**

```ts
interface BigIntConstructor {
    (value: string | number | bigint | boolean | object): bigint;
}
```

**Actual behavior:**

```ts
interface BigIntConstructor {
    (value?: any): bigint;
}
```

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by LongTengDao**
Fixes #38980

### CODE REVIEW

**Comment by InExtremaRes** [comment]
Why is `boolean` and `object` allowed? Just compatibility? `BigInt` promotes every object to `string` before convertion and unlike `Number` (that returns `NaN`) it throws if the string doesn't represent a valid integer. I guess most of the time passing and object will be a mistake and for valid cases there is always the possibility of converting to `string` beforehand. Also `object` is very "loose" since it allows everything but a primitive, and I feel that most likely pass a function will be non intended, as opposed to call that function an pass the result for instance.

Wouldn't be better allowing only `string | number` first and hope the world doesn't break with the change?

**Comment by DanielRosenwasser** [comment]
When called, this thing is just a conversion function from another type, so it should be somewhat permissive. The only thing that doesn't work is `null` and `undefined` which we're removing.

@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by InExtremaRes** [comment]
> This thing is just a conversion function from another type, so it should be somewhat permissive. 

Yeah, but other "primitive boxes" when called as a function does give a valid value of the primitive type:

```js
Number({})  // -> NaN, a number
Boolean({}) // -> true, a boolean
String({})  // -> '[object Object]', an string
Symbol({})  // -> a new symbol
BigInt({})  // throws :(
```

Those maybe are just a side effect of the convertion to primitive and could or not be useful, but the type declaration doesn't lie. With `BigInt` most of the time an object will throw and in other cases TypeScript already prevents a "this is probably a mistake" scenario, even if the ES spec allows a value of any type; IMO this is a good opportunity of doing it as well to obtain a compile-time error instead of a runtime one, a dev can always call `BigInt(anObject.toString())` or something like that if that is really the intention.

BTW I think `Number()` explicitly disallow `symbol`s but it is typed as `any` as well.

**Comment by LongTengDao** [comment]
In consideration of below code makes a TS error, maybe what InExtremaRes said is right?

```ts
const keyObj = {
	[Symbol.toPrimitive] () :'key' { return 'key'; },
	toString () :'key' { return 'key'; },
	valueOf () :'key' { return 'key'; },
};

( { 'key': 'value' } )[keyObj];
```

**Comment by sandersn** [comment]
@LongTengDao sorry for letting this get stale. The next step is to see how much (if any) of Definitely Typed packages and our user tests break with this change. I don't see PRs from the last run so I'm going to re-run:

@typescript-bot user test this
@typescript-bot run dt

**Comment by fubar** [comment]
@sandersn what's the status on this? We have bugs go into production because null and undefined are not rejected.

As for accepted values, `BigInt({})` throws an error so `object` should not be included. The specs on accepted values are clear so I'm not sure why this is being discussed in the first place: https://tc39.es/ecma262/#sec-bigint-constructor and https://tc39.es/ecma262/#sec-tobigint @LongTengDao what's the reason you kept `object` in the list of accepted values? It sounded like the discussion concluded that it should be removed.

**Comment by LongTengDao** [comment]
@fubar One check fails after the commit which removed the `object` type, and I can't see why by the message (you can visit the red `X` to read it):

```
  Error: The configuration file "/home/runner/work/TypeScript/TypeScript/.github/codeql/codeql-configuration.yml" does not exist
      at getLocalConfig (/home/runner/work/_actions/github/codeql-action/v1/lib/config-utils.js:547:15)
      at loadConfig (/home/runner/work/_actions/github/codeql-action/v1/lib/config-utils.js:419:22)
      at Object.initConfig (/home/runner/work/_actions/github/codeql-action/v1/lib/config-utils.js:526:24)
      at Object.initConfig (/home/runner/work/_actions/github/codeql-action/v1/lib/init.js:29:38)
      at run (/home/runner/work/_actions/github/codeql-action/v1/lib/init-action.js:75:31)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/init-action.js:123:9)
```

**Comment by fubar** [comment]
@LongTengDao your fork is well behind upstream, the file exists in upstream but not in your fork. Try pulling latest.

**Comment by fubar** [comment]
@sandersn can we get another look at this? Do those tests need to run again? The previous test runs don't have their output anymore, looks like they're too old. Thanks!

**Comment by sandersn** [comment]
@typescript-bot user test this
@typescript-bot run dt

**Comment by sandersn** [comment]
@typescript-bot run dt

**Comment by sandersn** [comment]
DT doesn't have any new errors (although I need to go and clean up the existing errors). The user tests were also clean back in September so I doubt anything has changed.

**Review by sandersn — APPROVED** [review]

**Comment by sandersn** [comment]
This is now merged in #43204

**Comment by fubar** [comment]
Thank you @sandersn and @LongTengDao

**Pull request closed without merging**
