### PR TITLE
Updates to type reference directive resolution and module resolution when failed

### LINKED ISSUE #37708: typeRoots and types not working
**TypeScript Version:**  3.8.3

**Search Terms:**

**Code**
This is my `tsconfig.json`

```json
{
	"compilerOptions": {
        "typeRoots": [
            "./typings"
        ],
        "types": ["Phaser"]  
    }    
}
```

In my project root, I got `package.json, package-lock.json, main.ts(empty one), tsconfig.json`. `tsconfig.json` contains the above code.  `typings` folder which I wrote in `typeRoots` is empty. After that, I run the following command in terminal:`tsc --traceResolution`

**Expected behavior:**

What should happen is `Phaser` shouldn't get resolved because compiler should start looking into my custom folder `typings`.  

**Actual behavior:**
Somehow it still gets resolved. And this is what it prints: `Type reference directive 'Phaser' was successfully resolved to '/Applications/XAMPP/xamppfiles/htdocs/phaser-test/node_modules/Phaser/types/phaser.d.ts' with Pac
kage ID 'phaser/types/phaser.d.ts@3.22.0', primary: false.` . I don't know how it finds it since in my `typeRoots`, I don't have `node_modules` specified.

### PR DESCRIPTION
**Pull request by sheetalkamat**
- When user has supplied `typeRoots` resolve the typeReference as file or directory instead of just directory resolution as before.
 1c2318d92e2e93c99b8ed87419470ddfd7719796 This is fix for issue `Bug 2` reported in #37708
- If configuration has supplied `typeRoots` stop looking into `node_modules/@types` containing file's ancestor directories to resolve type reference as secondary lookup.
40bb75c8f5273d5cd379c97cb683f08a04947b58 This is fix for issue `Bug 1` reported in #37708
- When resolving modules, if resolution fails, try resolving it from `typeRoots` if user has supplied. This helps solve the issues with module augmentation etc if when types are included through typeRoots. 
a6fed14f5bb2279bac45f348f49ee984baa3512d This is fix for #39691 and #37958

Fixes #37708, #39691, #37958, #44270

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Since this is technically a breaking change, we should discuss whether we think we can get it in 5.0 or wait until 5.1.

**Comment by andrewbranch** [comment]
@typescript-bot run dt
@typescript-bot test top100

**Comment by sandersn** [comment]
@sheetalkamat  I'm going through all the ready-to-merge PRs, and this one was intended either for 5.0 or 5.1, so I vote to merge it now that 5.1 development has started.

**Comment by sisiea** [comment]
I still confuse with the usage of "typeRoots" under Typescript 5.1-beta.
Here is my simple example.
My project structure:
```
typescript1
 ┣ @types
 ┃ ┗ mypackage
 ┃   ┗ index.d.ts
 ┣ node_modules
 ┣ src
 ┃ ┗ 5-1-main.ts
 ┣ package.json
 ┗ tsconfig.json
```
my package.json:
```
{
  "name": "typescript1",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "tsc": "tsc ./src/5-1-main.ts",
    "tsct": "tsc ./src/5-1-main.ts --traceResolution",
    "tscv": "tsc -v"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "dependencies": {
    "typescript": "beta"
  }
}
```
my tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "esnext",
    "typeRoots": ["./@types"]
  },
}
```
my custom type defined file:
```
// ./@types/mypackage/index.d.ts
interface MyObject {
    name: string;
}
```
my source code:
```typescript
// ./src/5-1-main.ts
var a: MyObject = {
    name: '12',
}
```
Before I run the script `npm run tsc`, I run `tscv` to ensure my typescript version is 5.1-beta.
image

Then I run script `npm run tsc`.I got  the error:
```
src/5-1-main.ts:1:8 - error TS2552: Cannot find name 'MyObject'. Did you mean 'Object'?

1 var a: MyObject = {
         ~~~~~~~~

  node_modules/_typescript@5.1.0-beta@typescript/lib/lib.es5.d.ts:270:13
    270 declare var Object: ObjectConstructor;
                    ~~~~~~
    'Object' is declared here.


Found 1 error in src/5-1-main.ts:1
```
I specified the `typeRoots` in `tsconfig.json`, but `MyObject` defined in file `./@types/mypackage/index.d.ts` not worked.

Then I added the file `@types/mypackage2/index.d.ts` into the dir `./node_modules`.
```
typescript1
 ┣ @types
 ┃ ┗ mypackage
 ┃   ┗ index.d.ts
 ┣ node_modules
 ┃ ┗ @types
 ┃      ┗ mypackage2
 ┃          ┗ index.d.ts
 ┣ src
 ┃ ┗ 5-1-main.ts
 ┣ package.json
 ┗ tsconfig.json
```
And I run the script `npm run tsct` ( `tsc` command with `--traceResolution`), typescript could compile success.According to the log, `MyObject` defined in file `./node_modules/@types/mypackage2/index.d.ts` was involed into the compilation.

That was so weird！！

```
> typescript1@1.0.0 tsct /Users/sisiea/Documents/playground/typescript1
> tsc ./src/5-1-main.ts --traceResolution

======== Resolving type reference directive 'mypackage2', containing file '/Users/sisiea/Documents/playground/typescript1/__inferred type names__.ts', root directory '/Users/sisiea/Documents/playground/typescript1/node_modules/@types,/Users/sisiea/Documents/playground/node_modules/@types,/Users/sisiea/Documents/node_modules/@types,/Users/sisiea/node_modules/@types,/Users/node_modules/@types,/node_modules/@types'. ========
Resolving with primary search path '/Users/sisiea/Documents/playground/typescript1/node_modules/@types, /Users/sisiea/Documents/playground/node_modules/@types, /Users/sisiea/Documents/node_modules/@types, /Users/sisiea/node_modules/@types, /Users/node_modules/@types, /node_modules/@types'.
File '/Users/sisiea/Documents/playground/typescript1/node_modules/@types/mypackage2/package.json' does not exist.
File '/Users/sisiea/Documents/playground/typescript1/node_modules/@types/mypackage2/index.d.ts' exists - use it as a name resolution result.
Resolving real path for '/Users/sisiea/Documents/playground/typescript1/node_modules/@types/mypackage2/index.d.ts', result '/Users/sisiea/Documents/playground/typescript1/node_modules/@types/mypackage2/index.d.ts'.
======== Type reference directive 'mypackage2' was successfully resolved to '/Users/sisiea/Documents/playground/typescript1/node_modules/@types/mypackage2/index.d.ts', primary: true. ========
```

**Comment by ehoogeveen-medweb** [comment]
Yes, it's mentioned in the [Announcing TypeScript 5.1 blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types).

**Comment by RyanCavanaugh** [comment]
@loick can you log a fresh issue please? Thanks!

**Comment by Abrarhaj** [comment]
ok

**Pull request merged**
