### PR TITLE
Allow Infinity and NaN to be used as an Enum property identifier

### LINKED ISSUE #6153: const enum should allow "Infinity" as a valid name
```typescript
	declare const enum CameraDeviceFocusMode {
		Normal = 0,
		TriggerAuto = 1,
		ContinuousAuto = 2,
		Infinity = 3, // <- error: An enum cannot have a numeric name
		Macro = 4
	}
```

### PR DESCRIPTION
**Pull request by fabiancook**
Fixes #6153

### CODE REVIEW

**Comment by sandersn** [comment]
It doesn't look like this works for `-Infinity` as requested in the bug. Otherwise looks good.

**Comment by fabiancook** [comment]
FYI to use `-Infinity` you will need to enclose it in a string

image

**Comment by sandersn** [comment]
To get the Travis build passing, can you merge from master? We had a break when we merged the new transforms code yesterday.

**Comment by sandersn** [comment]
Never mind, if you can get it to pass without the merge, don't worry about it.

**Comment by fabiancook** [comment]
Looks like its good to go, tried a rebase off master and didn't resolve it, thought I would just try with Travis again, surprised it passes.

**Comment by sandersn** [comment]
Me too. But I'll go ahead and merge it. :+1:

**Comment by fabiancook** [comment]
Hold up, is this not meant to be _just_ `const enum`?

**Comment by fabiancook** [comment]
Ahh sorry, everything is good

> Approved even for non-const enums.

**Pull request merged**
