### PR TITLE
[DO NOT REVIEW] Perf testing module-ified TypeScript compiler

### PR DESCRIPTION
**Pull request by jakebailey**
See #49332 for more info.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
That's very good, but I even forgot to disable let and const... So maybe it'll be even faster?

**Comment by jakebailey** [comment]
No, unfortunately esbuild doesn't support lowering let/const. I only though it did because I saw `var` at the top of the file.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
@typescript-bot perf test this

One last time to see if we get any boost from downleveling let/const via tsc.

**Comment by jakebailey** [comment]
Wow, yeah, running on the emitted output is very bad.

**Comment by Andarist** [comment]
@jakebailey this is very interesting work! I'm very curious about what is exactly going on here and what exact approaches you have been testing etc. Would you mind sharing what strategy was used by [this perf run](https://github.com/microsoft/TypeScript/pull/50765#issuecomment-1246092782)? Are the main gains here from ditching the property lookups involving `ts` object in favor of a plain closure?

**Comment by jakebailey** [comment]
I'd recommend looking at #49332, https://github.com/jakebailey/typeformer, and the stack starting at https://github.com/jakebailey/TypeScript/pull/1 (though not up to date yet).

Effectively, there's a big transform that converts the codebase from namespaces into modules, using "barrel" files to export what used to be in those namespaces, so consumers see the same API. Since these are all regular imports, a bundler like esbuild can transform the code as needed, and so in this case, all of the code turns out to be brought to the top level, so no indirection, and then the big barrels are retained as objects that are exported.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

This one's on the CJS output, no bundling, i.e. what we get if we just use or output as is, 500 files and all.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

Retrying; the bot picked up the version before my commit.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

Retrying CJS...

**Comment by jakebailey** [comment]
I screwed up the server build for this case (the correct path to tsserver is `tsserver/server.js` not `tsserver/tsserver.js`), but given how slow the compiler is, I expect it to be really slow too.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

One more CJS test, with a working server.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

One more CJS test, with a working server, redux...

**Comment by jakebailey** [comment]
@typescript-bot perf test this

Retry CJS again... I forgot to add my changes 😢

**Comment by jakebailey** [comment]
@typescript-bot perf test this

This time, for a hacky Node16 emit.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

The perf runner wasn't able to build things, I have no idea why.

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

Node 10 and 12 don't seem to work, for unrelated reasons.

**Comment by jakebailey** [comment]
Nice; ESM specifically gives us a 3-9% speedup, which should correspond to the benefit of directly accessing functions (as they have been imported into each module's scope, versus being fully qualified).

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

One last test; this time esbuilding the emitted ESM from tsc.

**Comment by jakebailey** [comment]
I'm going to close this PR; the patches that I used for this have been saved in https://github.com/jakebailey/typeformer/tree/master/old/patches-after-perftesting, but I'd like to continue working (and I don't want to continue to spam this PR with my force pushes as I continue to rebase my stack).

**Pull request closed without merging**
