### PR TITLE
Require module/moduleResolution to match when either is node16/nodenext

### PR DESCRIPTION
**Pull request by andrewbranch**
TODO: document why we’re doing this. For now, see #54735.

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot test top200

**Comment by andrewbranch** [comment]
@typescript-bot test top100

**Comment by andrewbranch** [comment]
I could have sworn top200 was a thing

**Comment by jakebailey** [comment]
It is, but IIRC can't be run via the bot. I think only @DanielRosenwasser knows how to do it.

**Comment by andrewbranch** [comment]
Daniel showed me one time, but if I have to open Azure Dev Ops, it’s probably not going to happen 😄

**Comment by DanielRosenwasser** [comment]
[It's not that bad](https://github.com/microsoft/typescript-error-deltas/tree/ba619701a0647459967d5fa4ee36afbd7b8b8da6#running)

But that one doesn't run against PRs. If you click on the link that the bot posted above, [you can go into the pipeline you just triggered](https://typescript.visualstudio.com/TypeScript/_build?definitionId=47&_a=summary).

I think the parameters are pretty easy to set up, with the exception that the dumb thing expects a comment ID to update. I got that via the GraphQL API - but I think you can always use gibberish and it will post a new comment but fail to update the old one.

Field | Value
------|------
Old Typscript Repo Url | https://github.com/microsoft/TypeScript.git
Old head reference | main
User to tag when the results are ready (Required) | andrewbranch
PR ID in github (Required) | 54567
Typescript-bot comment ID indicating that the run started (Required) | IC_kwDOAT9aAc5eRY10
Machine Count | 4 
TypeScript entrypoint | (tsc/tsserver)
```

**Comment by fatcerberus** [comment]
What's with all the projects that "failed to build with the old tsc and were ignored"? 😮

**Comment by andrewbranch** [comment]
Probably stuff that needs build steps or configuration that couldn’t be inferred by the runner. Keep in mind the only input this gets is a repo... how many times have you cloned somebody else’s project and not gotten a successful build on the first try? 😄

**Comment by DanielRosenwasser** [comment]
I just realized from what I said, it's not parameterized by the count/start index. [It's currently hard-coded to 100 and you can definitely change that if you want](https://github.com/microsoft/typescript-error-deltas/blob/ba619701a0647459967d5fa4ee36afbd7b8b8da6/azure-pipelines-userTests.yml#L69).

**Comment by fatcerberus** [comment]
@andrewbranch Ah, thanks, that makes sense.  I had assumed top100 was a curated list (as in, “the top 100 repos we know we can build”) so I got worried there was a recent massive breaking change that snuck under the radar or something.

**Comment by DanielRosenwasser** [comment]
Thanks to https://github.com/microsoft/typescript-error-deltas/pull/120 and https://github.com/weswigham/typescript-bot-test-triggerer/pull/24, we can now run:

@typescript-bot test top200

**Comment by andrewbranch** [comment]
I don’t remember if this is fully done or not but

@typescript-bot test top200

**Comment by andrewbranch** [comment]
@DanielRosenwasser you are the best 🌟

**Comment by andrewbranch** [comment]
Should `--moduleResolution node16` now imply `--module node16` if that’s the only valid combo?

**Review by sheetalkamat — APPROVED** [review]

**Comment by AlessioGr** [comment]
@andrewbranch since this change, I'm no longer able to use "module": "CommonJS" together with "moduleResolution": "Node16".

Is there a new way to do this?

I need the module to be CommonJS because I'm using CommonJS. I also need moduleResolution to be Node16 because that's needed for the package.json#exports property to work.

**Comment by thynson** [comment]
> I need the module to be CommonJS because I'm using CommonJS. I also need moduleResolution to be Node16 because that's needed for the package.json#exports property to work.

Same situation, this change breaks my code badly.

**Comment by lmk123** [comment]
> @andrewbranch since this change, I'm no longer able to use "module": "CommonJS" together with "moduleResolution": "Node16".
> 
> Is there a new way to do this?
> 
> I need the module to be CommonJS because I'm using CommonJS. I also need moduleResolution to be Node16 because that's needed for the package.json#exports property to work.

Same here. I need my package to emit ESM **and** CommonJS, but it seems that I can't emit CommonJS after upgrade to typescript 2.2.0

**Comment by badeball** [comment]
If I as a library developer, want to emit CJS, but consume dependencies that are using the [`exports` field](https://nodejs.org/api/packages.html#exports), how would I go about doing that? Prevously I have had a tsconfig of `moduleResolution: node16` and `module: commonjs`, but this now seems to be unsupported.

**Comment by andrewbranch** [comment]
`--module nodenext --moduleResolution nodenext` emits CommonJS by default.

**Comment by thynson** [comment]
> `--module nodenext --moduleResolution nodenext` emits CommonJS by default.

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "esModuleInterop": true,
    "module":"nodenext",
    "moduleResolution": "nodenext",
    "outDir": "lib/",
    "lib": ["ES2022"],
    "baseUrl": "."
  },
  "include": ["src/**/*.ts"]

}
```
It emits ECMA module code, with Typescript v5.2.2. Is the above configuration wrong?

**Comment by thynson** [comment]
Please revert this, at least before we have a way to emit CommonJS code despite `package.json#type` is set to `"module"`

**Comment by lyswhut** [comment]
The same problem, I use webpack to build Electron, because webpack needs `import.meta.url` when [building workers](https://webpack.js.org/guides/web-workers/#nodejs), so I can't set `"module": "nodenext"`, I need to set `"moduleResolution": "nodenext"` with `"module": " esnext"`

**Comment by SebastienGllmt** [comment]
I'm reading the FAQ and it's not clear to me what `just` means in the following

> If you’re running your code in Node.js, or writing a library where someone might run it in Node.js, **just** use module: nodenext, and either write .mts files, or ensure your package.json contains "type": "module". ESM is emitted for .mts files and for .ts files whose nearest ancestor package.json contains "type": "module".

Does it means I should remove `moduleResolution` from the tsconfig and let it be whatever the default value is? If it's the case, could the FAQ be update to explicitly clarify that `moduleResolution` should be removed from your tsconfig in this case or some other behavior that is clearer than `just`?

**Comment by andrewbranch** [comment]
Updated.

**Comment by RyanCavanaugh** [comment]
@b1rdex If I just take your code as JS and run it, it doesn't work. What transpilation (i.e. changes from TS) are you wanting to have happen here?
```
D:\Throwaway\test54567>node foo.js
file:///D:/Throwaway/test54567/foo.js:4
  fetch: require('node-fetch'),
         ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'D:\Throwaway\test54567\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///D:/Throwaway/test54567/foo.js:4:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:518:24)
    at async loadESM (node:internal/process/esm_loader:102:5)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v19.0.0

D:\Throwaway\test54567>node foo.js
(node:15596) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
D:\Throwaway\test54567\foo.js:1
import wretch from 'wretch';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by b1rdex** [comment]
Well, that’s strange. The only guess I have - we don’t specify “type” in package.json at all. I can create minimal reproduction if you want to see the build . 24 окт. 2023 г., в 23:24, Ryan Cavanaugh ***@***.***> написал(а):﻿
@b1rdex If I just take your code as JS and run it, it doesn't work. What transpilation (i.e. changes from TS) are you wanting to have happen here?
D:\Throwaway\test54567>node foo.js
file:///D:/Throwaway/test54567/foo.js:4
  fetch: require('node-fetch'),
         ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'D:\Throwaway\test54567\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///D:/Throwaway/test54567/foo.js:4:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:518:24)
    at async loadESM (node:internal/process/esm_loader:102:5)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v19.0.0

D:\Throwaway\test54567>node foo.js
(node:15596) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
D:\Throwaway\test54567\foo.js:1
import wretch from 'wretch';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

**Comment by RyanCavanaugh** [comment]
The default is `"commonjs"` if you don't specify

**Comment by b1rdex** [comment]
@RyanCavanaugh

test.ts
```ts
import wretch from 'wretch';
wretch.polyfills({
  fetch: require('node-fetch'),
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  URLSearchParams: require('url').URLSearchParams,
});

export async function foo() {
  // am I supposed to replace all usages like this to `await import('wretch')` + importing+awaiting polyfills here?
  const result = await wretch('https://example.com').get().json();
}
```

compiles to test.js
```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
const wretch_1 = __importDefault(require("wretch"));
wretch_1.default.polyfills({
    fetch: require('node-fetch'),
    URLSearchParams: require('url').URLSearchParams,
});
async function foo() {
    const result = await (0, wretch_1.default)('https://example.com').get().json();
}
exports.foo = foo;
```

**Comment by b1rdex** [comment]
@RyanCavanaugh second example. Sorry, code in examples had some little problems, fixed now.

test.ts
```ts
import dayjs from 'dayjs';
import dayjsUTC from 'dayjs/plugin/utc';
import dayjsTimezone from 'dayjs/plugin/timezone';
dayjs.extend(dayjsUTC);
dayjs.extend(dayjsTimezone);

export function date(input: string) {
  // the same question...
  return dayjs(input).tz('Some/TZ').format('DD.MM.YYYY HH:mm');
}
```

compiles to test.js
```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.date = void 0;
const dayjs_1 = __importDefault(require("dayjs"));
const utc_1 = __importDefault(require("dayjs/plugin/utc"));
const timezone_1 = __importDefault(require("dayjs/plugin/timezone"));
dayjs_1.default.extend(utc_1.default);
dayjs_1.default.extend(timezone_1.default);
function date(input) {
    return (0, dayjs_1.default)(input).tz('Some/TZ').format('DD.MM.YYYY HH:mm');
}
exports.date = date;
```

**Comment by RyanCavanaugh** [comment]
@b1rdex so set `"module": "CommonJS", "moduleResolution": "Node10"`. No config errors, and produces that output.

**Comment by jacoblee93** [comment]
> @andrewbranch since this change, I'm no longer able to use "module": "CommonJS" together with "moduleResolution": "Node16".
> 
> Is there a new way to do this?
> 
> I need the module to be CommonJS because I'm using CommonJS. I also need moduleResolution to be Node16 because that's needed for the package.json#exports property to work.

Anyone figure out a way around this issue? Would love to not have to lock our TypeScript dep below 5.2.

**Comment by andrewbranch** [comment]
- The next comment from me answers the question
- I updated the PR description with an FAQ at the top that answers the question

**Comment by jacoblee93** [comment]
> * The next comment from me answers the question
> * I updated the PR description with an FAQ at the top that answers the question

I unfortunately fall into the dual-emit ESM + CJS library developer bucket where my nearest ancestor package.json contains `"type": "module"`. Sounds like best thing to do is try updating our build script with a second `package.json` then?

**Comment by andrewbranch** [comment]
I recommend looking at https://github.com/isaacs/tshy, which is basically a way to automate that

**Comment by jacoblee93** [comment]
Thanks!

**Comment by alexandersorokin** [comment]
I am developing a math library that should work both in Node and browsers natively (i.e., without bundling). The library is ESM only. It should support Chrome 70 (there is no top-level await feature).

Before TypeScript 5.2 I used `module=ES2020` and `moduleResolution=Node16` simultaneously.  So TypeScript 5.1 ensured that module imports work both in browsers and Node (it requires adding `.js` extensions to import statements) and it ensured that there are no top-level awaits in code.

With TypeScript 5.2 if I choose to use `module=ES2020` and `moduleResolution=bundler` it allows extensionless imports that do not work in browsers and Node. If I choose to use `module=Node16` and `moduleResolution=Node16` it allows top-level awaits that do not work in Chrome 70. And it's ugly to use the `Node16` module option for browsers because it can output `commonjs` (at least theoretically).

Is there a good way to require imports with extensions and not allow top-level awaits? So the library can work both in Node and browsers natively (without bundling).

**Comment by andrewbranch** [comment]
Not in TypeScript currently—maybe a lint rule?

What’s the name of your library / is it open source somewhere? I’d like to collect a list of examples of TS projects that build unbundled ESM for browsers.

**Comment by alexandersorokin** [comment]
@andrewbranch thank you for the clarification. For now, I have decided to use `Node16` mode for both `module` and `moduleResolution` and ban top-level awaits using third-party ways. If `browser` or `esm only` output mode is added to TypeScript, it will be helpful to me. So I will be able to use output results in browsers and Node (and in bundlers too, as a consequence).

But the library I mentioned has not been released yet and is internal. So currently, I can't share it as an example.

**Pull request merged**
