### PR TITLE
Consistently error on circular constraints

### LINKED ISSUE #29992: Breaking changes for types with union/recursive/generic when upgrading from v2.9.2 to v3.4.0
**TypeScript Version:**  3.4.0-dev.201xxxxx

The latest version 3.4.0-dev.20190220 still has this issue.

image

**Search Terms:**
Sorry. I do not even know any keyword that can describe my problem. I am not that good at compiler jargons.

**Code**

```ts
export interface WidgetBase {
    title?: string,
    widgetKey: string,
}

type NonOptionalKeys<T> = { [k in keyof T]-?: undefined extends T[k] ? never : k }[keyof T];

type Child<T extends WidgetBase> = { [P in NonOptionalKeys<T>]: T[P] }

export interface NumberWidget extends WidgetBase {
    type: "number",
    minimum: number,
    maximum: number,
}
export interface ListWidget extends WidgetBase {
    "type": "list",
    "minimum_count": number,
    "maximum_count": number,
    "each": ChildWidget //MARK1
}

export type PrimitiveWidget = | NumberWidget

export type ChildWidget =
    | Child<NumberWidget>
    | Child<ListWidget> //MARK2

type ListChild = Child<ListWidget>

```

**Expected behavior:**

`ListChild` should be equivalent to (exactly as it behaves in v2.9.2)

```
 {
    type: "list";
    minimum_count: number;
    maximum_count: number;
    each: ChildWidget;
    widgetKey: string;
}
```
image

**Actual behavior:**
```
type ListChild = {
    [x: string]: any;
}
```

**DO NOTE** that, if you comment out either the line containing **MARK1** or the line containing **MARK2**, the type inference works correctly.

image

**Playground Link:** 

[Playground Link](https://www.typescriptlang.org/play/#src=export%20interface%20WidgetBase%20%7B%0D%0A%20%20%20%20title%3F%3A%20string%2C%0D%0A%20%20%20%20widgetKey%3A%20string%2C%0D%0A%7D%0D%0A%0D%0Atype%20NonOptionalKeys%3CT%3E%20%3D%20%7B%20%5Bk%20in%20keyof%20T%5D-%3F%3A%20undefined%20extends%20T%5Bk%5D%20%3F%20never%20%3A%20k%20%7D%5Bkeyof%20T%5D%3B%0D%0A%0D%0Atype%20Child%3CT%20extends%20WidgetBase%3E%20%3D%20%7B%20%5BP%20in%20NonOptionalKeys%3CT%3E%5D%3A%20T%5BP%5D%20%7D%0D%0A%0D%0Aexport%20interface%20BooleanWidget%20extends%20WidgetBase%20%7B%0D%0A%20%20%20%20type%3A%20%22boolean%22%2C%0D%0A%20%20%20%20trueTitle%3F%3A%20string%0D%0A%20%20%20%20falseTitle%3F%3A%20string%0D%0A%7D%0D%0A%0D%0Aexport%20interface%20ListWidget%20extends%20WidgetBase%20%7B%0D%0A%20%20%20%20%22type%22%3A%20%22list%22%2C%0D%0A%20%20%20%20%22minimum_count%22%3A%20number%2C%0D%0A%20%20%20%20%22maximum_count%22%3A%20number%2C%0D%0A%20%20%20%20%22collapsable%22%3F%3A%20boolean%2C%20%2F%2Fdefault%20to%20false%2C%20means%20all%20expanded%0D%0A%20%20%20%20%22each%22%3A%20ChildWidget%20%2F%2FMARK%201%0D%0A%7D%0D%0A%0D%0Aexport%20type%20PrimitiveWidget%20%3D%20%7C%20BooleanWidget%0D%0A%0D%0Aexport%20type%20ChildWidget%20%3D%0D%0A%20%20%20%20%7C%20Child%3CBooleanWidget%3E%0D%0A%20%20%20%20%7C%20Child%3CListWidget%3E%20%2F%2FMARK%202%0D%0A%0D%0Atype%20ListChild%20%3D%20Child%3CListWidget%3E%0D%0A)

**Related Issues:**

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we consistently error when detecting circular constraints. In particular, we now report errors when circularities occur during instantiation but not when checking the original declaration. When the node currently being checked (the node referenced by `currentNode`) is neither a descendant nor an ancestor of the constraint type node, we also report the current node as the associated source location in which the circularity originates.

Fixes #29992.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
I'm guessing this will have some DT breaks

**Comment by ahejlsberg** [comment]
@typescript-bot test this & @typescript-bot run dt

**Comment by ahejlsberg** [comment]
@RyanCavanaugh Best I can tell, none of the RWC and DT failures are related to this PR. And really, the only new failures this could cause are new circularity errors and there are none of those.

**Comment by weswigham** [comment]
The DT failures look like the ones from `master` two days ago, so I think you're fine, too.

**Pull request merged**
