### PR TITLE
No assert is needed for oldProgram.structureIsReused since the reuse starts right there and we do initialize that field.

### LINKED ISSUE #20561: Debug Failure. False expression. in `synchronizeHostData` during `getApplicableRefactors`
tsserver version:
hits: at least 538137
stack:
```
Error: Debug Failure. False expression.
    at tryReuseStructureFromOldProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59129:22)
    at Object.createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:58930:34)
    at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79707:26)
    at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79742:13)
    at ConfiguredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83016:53)
    at ConfiguredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82966:39)
    at ConfiguredProject.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83248:53)
    at ConfiguredProject.Project.getLanguageService (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82702:26)
    at IOSession.Session.getApplicableRefactors (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86474:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85436:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86660:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86669:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86689:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87881:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #20561

### CODE REVIEW

**Comment by ajafff** [comment]
Does it still throw if I try to reuse the same program twice? I couldn't find an assertion for that in the source.

**Comment by mhegazy** [comment]
Can you elaborate on why removing the assert is correct? i am not sure i see that from just looking at the code.

**Comment by sheetalkamat** [comment]
This is valid: 
```typescript
const program2 = createProgram(rootNames, options, host, program1);
const program3 = createProgram(rootNames, options, host, program1);
```

That is earlier it was validating if the program passed in was not set with ```structureResued``` property with ```Completely``` or ```SafeModules``` which is incorrect since it doesn't matter how the program was reused earlier.

**Comment by sheetalkamat** [comment]
ping @mhegazy

**Comment by mhegazy** [comment]
The issue is the source files. we did not want callers to send a program whose source files have been reused, and expect that to work..

**Comment by sheetalkamat** [comment]
Source files can be reused.. Thats the whole purpose of creating program and checking if source files can be reused... Source files do not change from Program version 1 to program version 2  if they dont have any change (and there are no changes in compiler options that need new source file)

**Comment by mhegazy** [comment]
I meant the reason why we have this flag, is to make sure no one is looking at an old program. an old program can be holding on to sourceFile objects that have been incrementally parsed, and used to generate a new file, and the old sourceFile is now invalid. so asking things form this program, like errors, or emit would be unsafe..

**Comment by sheetalkamat** [comment]
Closing this since the original behavior is by design

**Pull request closed without merging**
