### PR TITLE
Invalid this emit in contextual object

### LINKED ISSUE #7212: TS 1.8.x: invalid this reference inside arrow function
**TypeScript Version:** 
1.8.0 (through npm), 1.8.2 (visual studio)

**Code**

```ts
namespace Bug {

    export interface IDef {
        test2: () => any;
        test: (e:any) => any;
    }

    class TestController {
        protected from: number;

        public prepareDefinition(def: IDef) {
            return def;
        }

        public prepared = this.prepareDefinition({
            test2: () => {
                var q = this.from; // uses _this;
                var helper = () => {
                    var q2 = this.from; // uses _this
                };
                return {
                    fn1: (v) => {
                        var q3 = this.from; //uses this
                    },
                    fn2: helper
                }
            },
            test: (e) => { }
        } 
        );


    }

}
```
The code is compiled to ES5
**Expected behavior:**
All the 3 assignments (q, q2, q3) should compile to using _this

**Actual behavior:** 
The q3 assignment refers to "this". The code above (with the exception of the helper(), which I kept for comparison) seems to be the minimal code to trigger the issue - even removing test() or its parameters (or parameter of fn1) results in what I believe is the correct code (using _this). The code also compiles correctly in 1.7.x

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #7212

When we check context sensitive functions inside an object literal we short-circuit checking of the return type because it might be circular. But the short-circuit means that the checker doesn't go back to check the function later (because it's in a call to checkExpressionCached), which means that this doesn't get marked as needing the _this = this emit.

Thanks @vladima for the psychic debugging here. We came up with two fixes with two variants:

1. Call checkNodeDeferred in the short-circuit logic in checkFunctionExpressionOrObjectLiteralMethod, same as it is for the non-short-circuit path.
2. When aggregating return types, call checkExpression instead of checkExpressionCached.

1a. Only call checkNodeDeferred in checkFunctionExpressionOrObjectLiteralMethod if the node hasn't already been added to the deferred node list. Maybe using a nodeflags or something.
2a. Only call checkExpression when the contextual mapper is identityMapper.

This PR goes with (1) since it's the simplest. @ahejlsberg, can you take a look?

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
Orthogonal to the fix itself, I will note that again we have a high-severity bug caused by failing to typecheck every expression node in a program.

Is there anything stopping us from a) setting a flag on a node during typecheck and b) throwing during emit of that node if we don't see that flag? This could at least be enabled for nightly or debug builds.

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
please port this to release-1.8 as well.

**Pull request merged**
