### PR TITLE
Allow return type in conditional if body is followed by a colon

### LINKED ISSUE #48733: [4.7-beta] Parsing failure for arrow function expr in conditional expr
# Bug Report

### 🔎 Search Terms

- `conditional`
- `4.7 beta`
- `syntax error`

### 🕗 Version & Regression Information

- ~~This is a crash~~
- This changed between versions 4.6.3 and 4.7.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220416#code/BQMwhgNgzgpgBAfjsADmATmAtgSgFxxQAu6AlgHYDmcAvAHxxqZZwFzkCuEEOA3AFBA)

### 💻 Code

```ts
(false ? (param): string => param :  null);
```

### 🙁 Actual behavior

Parsing failure for arrow function expr that has type annotations for return type, but doesn't have type annotations for parameters, in conditional expression.

### 🙂 Expected behavior

Parsing successfull.

### PR DESCRIPTION
**Pull request by jakebailey**
This modifies my logic in #47550 allow an arrow function with a return type so long as that arrow function is immediately followed by another colon, which is instead chosen to terminate the conditional expression.

Fixes #48733

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot pack this

**Comment by jakebailey** [comment]
Demo: [Playground Link](https://www.staging-typescript.org/play?noImplicitAny=false&target=1&ts=4.7.0-pr-48788-2&filetype=ts#code/CYUwxgNghgTiAEYD2A7AzgF3lAXNlAngDTwBGeUhJYFV8wtx8IjJAZq-AOacAWjAbgBQGAgAcEUeAF58BAfFESyMuQqUIwqyvMXiEwbYXX7mR3RvhtzJ5Vxt7lvG0KEB6N-F4YMYtDg8uAEsMXgBXUgA6ZABbNxigsBgkNCQ2DDcAFX0AZSSgsQyxMIgINwAWAA4AdkrK1w94TN4QNAQMVow0LygANwRSEBAUeAB3GBCOkbC0IJR7WfmIBGWfEBh4FCgY1vxgd08QAA8MGCk0MSgwXYwkeDE4fpQsW7uYsLBnUiCobrmvJCjRQtAjYODwOBQYCRVxSAD88AAFKQAJTwPBaaQAPnowiE8KRqPRiBkOMRwDReAQ2KseIJpHgCK0eHJlLMNLYdMZhLRNMRYDZhhpIC5CMRvJxDPFxOlGNJuNhSLRYvIiBIwDhVJReGsNPssq8op5xMxOMMVKNDLFAuJQpxCB1xK4AiAA)

**Comment by sandersn** [comment]
This change is intended for 4.8, right?
At least, I thought we decided to revert the original change at a design meeting (or you recommended and we've been waiting to talk about it there).

**Comment by jakebailey** [comment]
Yes, 4.8, given we took too long to make a decision. There's a revert PR for the original fix I made (#48940) and I'll rebase these three PRs to make them correct again.

**Review by sandersn — APPROVED** [review]
This looks like it does what it says, although I recall that we wanted to parse JS in a spec-compliant way. Does this need a follow-up PR for that?

**Comment by jakebailey** [comment]
Sorry, yes, I don't have the final fix yet. Likely this PR does what we want, but I need to really check.

**Pull request closed without merging**
