### PR TITLE
Add support for class static block

### LINKED ISSUE #43012: Proposal class static block
# Suggestion

## 🔍 Search Terms
esnext, class

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

https://github.com/tc39/proposal-class-static-block is stage-3 。

I'm happy to implement this one if no one has already started the work(/cc: @rbuckton ).

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #43012

- [x] type definitions
- [x] factory
- [x] parser
- [x] binder
- [ ] checker
  - [ ] grammar
  - [ ] use before assignment
- [ ] transformer
- [x] emitter
- [x] visitor
- [ ] tests

### CODE REVIEW

**Comment by Kingwl** [comment]
Well.... I think this one is depends on https://github.com/microsoft/TypeScript/pull/42986 too....

It's seems a dependency chains...

**Comment by Kingwl** [comment]
https://github.com/tc39/proposal-class-static-block/issues/27

**Comment by rbuckton** [comment]
I'm still reviewing #42458, and we've been discussing the fact that `this` in static fields is currently disallowed, which would effect the order of emit. Also, the static block proposal itself is layered on the static features and class private proposal, so its important that evaluation order is correct:

```js
class C {
  static #x;
  static {
    this.#x; // ok
    this.#y; // error, #y not yet initialized
  }
  static #y;
  static {
    this.#x; // ok
    this.#y; // ok
  }
}
```
Either way, I'll still be happy to review when you think this is ready.

**Comment by Kingwl** [comment]
Okay, thanks a lot.

BTW, there's another PR to allow this in static contrxt.

Actually, I'm confused with the function boundary(as i said in class static block repo).

**Comment by Kingwl** [comment]
> https://github.com/tc39/proposal-class-static-block/issues/27

This one.( Sorry I'm on mobile phone )

**Comment by rbuckton** [comment]
I addressed your comment in that issue. The TL;DR is this:

- Class bodies *are not* function boundaries (_ClassHeritage_ and _ComputedPropertyName_ are evaluated in the class's containing scope), so an `await` in either position in a class static block would be an error.
- _FormalParameters_, _ArrowFormalParameters_, and _AsyncArrowBindingIdentifier_ *are* function boundaries, since parameter initializers are evaluated when the function is called.
- _FunctionBody_, _GeneratorBody_, _AsyncGeneratorBody_, _AsyncFunctionBody_, _ConciseBody_, and _AsyncConciseBody_ *are* function boundaries.
- A _ClassStaticBlock_ *is* a function boundary, but is also a class static block (so `await` as an identifier would be an error).
- Static/instance field initializers *are* function boundaries, as an implicit function is created that wraps the initializer to provide the correct `this` binding and access the lexical class binding.

**Comment by Kingwl** [comment]
I think I'd better to work based #42458. Even It's not been merged.

**Comment by Kingwl** [comment]
Close for #43308.

**Pull request closed without merging**
