### PR TITLE
Improved union type guards

### LINKED ISSUE #1587: Type Guard syntax for array
Perhaps a bug, the following does not work although I think its the right syntax: 

```ts
class Message {
    value: string;
}

function saySize(message: Message | Message[]) {
    if (message instanceof Array) {
        return message.length; // test.ts(7,24): error TS2339: Property 'length' does not exist on type 'Message | Message[]'.
    }
}
```

However, the following does work. 

```ts
class Message {
}

function saySize(message: Message | Message[]) {
    if (message instanceof Array) {
        return message.length; // Okay
    }
}
```

Note to team: Feel free to edit this query to increase its life. original report: https://github.com/Microsoft/TypeScript/issues/805#issuecomment-68615662.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #1587.

This PR improves handing of union types in type guards. Specifically, when a type guard of the form `x instanceof C` is true, the type of `x` is narrowed as follows:

* If `C` is a subtype of the type of `x`, the type of `x` is narrowed to `C`.
* Otherwise, if `x` is of a union type, all types that are not subtypes of `C` are removed from the type of `x`.

In the example
```typescript
class Message {
    value: string;
}

function saySize(message: Message | Message[]) {
    if (message instanceof Array) {
        return message.length;  // message of type Message[] here
    }
}
```
the `Message` type is removed under the type guard because it is not a subtype of `Array`.

### CODE REVIEW

**Comment by JsonFreeman** [comment]
:+1:

**Comment by danielearwicker** [comment]
Note that (x instanceof Array) !== Array.isArray(x) in cross-window situations, though not that common these days.

**Comment by battmanz** [comment]
If I modify the code as follows and add an `else` block, why does the compiler think that the type of `message` inside that `else` block is `Message | Message[]`? Shouldn't it only be `Message`?

```typescript
class Message {
    value: string;
}

interface MessageHandler {
	handle(message: Message): void;
}

function saySize(message: Message | Message[], handler: MessageHandler) {
    if (message instanceof Array) {
		message.forEach(m => handler.handle(m));
    }
	else {
		handler.handle(message); // Argument of type 'Message | Message[]' is not assignable to parameter of type 'Message'.
	}
}
```

**Comment by danquirk** [comment]
@battmanz see https://github.com/Microsoft/TypeScript/issues/1719

**Comment by mhegazy** [comment]
@battmanz this is tracked by #1719

**Pull request merged**
