### PR TITLE
Allow property declarations in .js files

### LINKED ISSUE #6997: static class properties invalid
_From @nwehrle on February 9, 2016 21:17_

I use eslint to lint my jsx files. Before I switched to salsa, the linting inside the editor worked fine. After switching to salsa the linting fails inside the editor.
bildschirmfoto 2016-02-09 um 22 00 18

Salsa is enabled:
bildschirmfoto 2016-02-09 um 22 13 44

Linting from the shell still works without any errors or warnings.
I expect vscode to not show any linting errors.

System:
OSX 10.11.2
vscode 0.10.8
db71ac615ddf9f33b133ff2536f5d33a77d4774e

jsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "system",
    "experimentalDecorators": true
  },

  "exclude": [
    "node_modules"
  ]
}
```

User settings:
```
{
  "javascript.validate.enable": false,
  "editor.tabSize": 2,
  "files.trimTrailingWhitespace": true,
  // Migrated from previous "File | Auto Save" setting:
  "files.autoSave": "onFocusChange"
}
```

Partial eslintrc:
```
 "rules": {
    "func-names": 0,
    "no-unused-expressions": 0,
    "id-length": 0,
    "no-multi-spaces": 0,
    "no-mixed-spaces-and-tabs": 2,

    "no-unused-vars": [1, {"vars": "all", "args": "none"}],
    "react/jsx-uses-react": 1,
    "react/prop-types": 0,
    "no-console": 0
  },
  "plugins": [
    "react"
  ]
```

_Copied from original issue: Microsoft/vscode#2866_

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #6997

### CODE REVIEW

**Comment by mhegazy** [comment]
👍

**Comment by jefflindholm** [comment]
So how do I get this to work in VSCode since it certainly is not working for me today with 1.3.1

**Comment by jayphelps** [comment]
@jefflindholm it has not yet landed in a stable release. You can see what tags a commit has made it into by clicking on the merge commit

image

See where it says `v2.0.0-beta`? No other tags are listed there, so that's the only one it's made it into.

**Comment by ctrlaltdel121** [comment]
Hi, I ran `npm install typescript@next` and I still had this issue within VSCode. Is there a version of typescript I can install to fix this in vscode now?

**Comment by andy-ms** [comment]
@ctrlaltdel121 By default vscode uses its own typescript version, but this is easy to change. See http://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions.

**Pull request merged**
