### PR TITLE
Avoid subtype reduction when creating a union result in `discriminateTypeByDiscriminableItems`

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/54048 (which is a **recent** regression from https://github.com/microsoft/TypeScript/pull/53709/files , cc @ahejlsberg )

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

**Comment by Andarist** [comment]
this is for 5.1 regression, is there any chance to get some eyes on it before the stable release?

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
In general I think this is a good change, we really shouldn't be subtype reducing contextual types (elsewhere we specifically avoid it). Seems like there's a slight performance regression in `material-ui`, but may just be that we're giving back the slight gain we got in #53709. Plus, TBH I'm not sure what we're really measuring with that old snapshot at this point.

**Comment by Andarist** [comment]
It seems that this PR got preliminary approval from @ahejlsberg . I wonder if it could land before 5.1 (and be cherry-picked into it) since its due date was supposed to be... yesterday 😅  (according to [the 5.1 iteration plan](https://github.com/microsoft/TypeScript/issues/53031))

**Comment by DanielRosenwasser** [comment]
> It seems that this PR got preliminary approval from @ahejlsberg . 

Sorry, can you link back to where? @weswigham can you take a look?

**Comment by Andarist** [comment]
@DanielRosenwasser [here](https://github.com/microsoft/TypeScript/pull/54052#issuecomment-1565024140):
> In general I think this is a good change, we really shouldn't be subtype reducing contextual types (elsewhere we specifically avoid it)

I called it preliminary since it didnt come with a more formal ✅ :P

**Comment by DanielRosenwasser** [comment]
Just documenting this one as a consistent 0.3-0.4 second regression.

image

**Comment by jakebailey** [comment]
Original PR which this PR fixes up shows an improvement, so it may be a wash maybe but not entirely :\

image

**Pull request merged**
