### PR TITLE
Let and const support

### PR DESCRIPTION
**Pull request by mhegazy**
This change adds support for ES6-style block-scoped variable declarations. these are only available when targeting ES6. the change also adds a new target for ES6.

There are two variants, let and const. Generaly let and const behave like a var declarations with the following exceptions:
- Both let and const can not be re-declared:

``` TypeScript
let a = 0;
a = 1;
let a; // Error: redeclaration
```
- It is an error to re-declare a block-scoped variable as 'var' in the same scope:

``` TypeScript
let a = 0;
{
     var a; // Error: redeclaration, as var is hoisted to the top of the scope, and re-declares a
}
```
- Let and const can not be declared in a non-guarded statements

``` TypeScript
if (true) {
    let a = 0; // OK
}

if (false) 
   let b = 0; // Error

for (let i = 0; i< 10; i++)  // OK
    console.log(i); 
```
- Let and const declarations are block scoped, and not hoisted to the top of the function like other JS declarations:

``` TypeScript
let a = 0;
{
    let a = "local";
    console.log(a) // local
}
console.log(a); // 0
```
- Let and const can not be used before they are defined, to avoid the lexical dead zone of vars.

``` TypeScript
v = 2; // ok
var v;

a = 2;
let a; // Error, used before initialization
```
- Const declarations must have an initializer, unless in ambient context
- It is an error to write to a Const

``` TypeScript
const c = 0;
console.log(c); // OK: 0

c = 2; // Error
c++; // Error

{
    const c2 = 0;
    var c2 = 0; // not a redeclaration, as the var is hoisted out, but still a write to c2
}
```
- Let and const can not be exported, only vars are allowed to.

What is left:
- Block emit if any of the let/const errors are reported, these may be syntactic, binding, or semantic errors
- Wire in Test262 for parser verification to ensure we are ES6 complaint

### CODE REVIEW

**Comment by nickie** [comment]
[TypeScript's specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#53-let-and-const-declarations) seems to allow a missing initializer for destructuring lexical bindings, whereas the [EC262 specification](http://tc39.github.io/ecma262/#sec-let-and-const-declarations) does not.  Is this intentional?  In that case, I believe it should only be allowed in the case that a type annotation is present, e.g., in `let [x, y]: number[];`  The current playground implementation seems to disallow this.

**Comment by sandersn** [comment]
@nickie, can you report a new bug for this, with the label Spec?

**Comment by nickie** [comment]
@sandersn, done ([6785](https://github.com/Microsoft/TypeScript/issues/6785)) but I don't know how to add the label.  Please add it, or advise me how to.  Thanks.

**Comment by RyanCavanaugh** [comment]
@sandersn FYI only Owners (i.e. us) can add Labels

**Pull request merged**
