### PR TITLE
Issue better error when unresolvable package in `--moduleResolution node10` resolves with `--moduleResolution bundler`

### LINKED ISSUE #55104: Better error message for using outdated moduleResolution: node(10)
# Suggestion

## 🔍 Search Terms

moduleResolution node node10 eol esm commonjs cannot find types

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When a TSConfig is using `"moduleResolution": "node"` or `"node10"` and an import resolves to an npm package whose types declarations that doesn't support Node < 16, the error message in `tsc` is very general:

```plaintext
Cannot find module '...' or its corresponding type declarations.
```

Same in VS Code:

Screenshot in VS Code of 'Cannot find module '@typescript-eslint/utils' or its corresponding type declarations. ts(2307)' in a hover box

Could we please have a secondary message added suggesting that the project be switched to using a more modern `"moduleResolution"`? 

This message needs bikeshedding, but a starting proposal:

```plaintext
Cannot find module '...' or its corresponding type declarations.
    Consider upgrading your "moduleResolution" compiler option. See aka.ms/tsconfig#moduleResolution for details.
```

## 📃 Motivating Example

This has been a point of confusion in at least https://github.com/typescript-eslint/typescript-eslint/issues/7284. We've gotten a few duplicate reports. 

## 💻 Use Cases

Same as ☝️, I think. I can't think of anything more specific.

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #55104

### CODE REVIEW

**Comment by andrewbranch** [comment]
@sheetalkamat I'm not sure whether this is safe with the existing `repopulateInfo` infrastructure. Could you take a look?

**Comment by andrewbranch** [comment]
@typescript-bot perf test

**Comment by andrewbranch** [comment]
@typescript-bot perf test

**Comment by andrewbranch** [comment]
@typescript-bot perf test public

**Comment by andrewbranch** [comment]
@typescript-bot perf test
@typescript-bot perf test public

**Review by sheetalkamat — APPROVED** [review]

**Pull request merged**
