### PR TITLE
feat(lib/es2021): Add type parameter to `FinalizationRegistry`

### PR DESCRIPTION
**Pull request by ExE-Boss**
Refs <https://github.com/microsoft/TypeScript/issues/32393>
Fixes <https://github.com/microsoft/TypeScript/pull/38232#discussion_r554554314>
Fixes <https://github.com/microsoft/TypeScript/pull/38232#pullrequestreview-564855277>

---

review?(@orta, @sandersn)

### CODE REVIEW

**Comment by sandersn** [comment]
There's a lot of discussion on that issue and the linked PR. Can you add an explanation of why the type parameter is important?

**Comment by ExE-Boss** [comment]
Because it makes the <code><var>heldValue</var></code> that’s passed to the <code><var>cleanupCallback</var></code> correctly typed instead of using `any`.

**Comment by sandersn** [comment]
Is typical usage going to allow the type parameter to be inferred? I think it is, but it would be nice to have a test.

**Comment by ExE-Boss** [comment]
@sandersn I’ve added a test case based on `IterableWeakMap` from [the TC39 `WeakRef` proposal](https://github.com/tc39/proposal-weakrefs/blob/master/README.md#iterable-weakmaps) with the fixes from <https://github.com/tc39/proposal-weakrefs/pull/216>.

**Review by sandersn — APPROVED** [review]

**Pull request merged**
