### PR TITLE
fix issue #49000: Distributed keyof over union leads to erroneous indexed access

### LINKED ISSUE #49000: Distributed keyof over union leads to erroneous indexed access
# Bug Report

### 🕗 Version & Regression Information

This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.7.0-dev.20220506#code/C4TwDgpgBA0hIHkBmAeAKgPigXimqEAHsBAHYAmAzlAK6kDWpA9gO6lQD8U98TSeUAFxRSEAG4QATgChpoSFADqkpqQDm6LLgDeUANowoAS3ZxEqTAF1haA5agBfWfOglKwXMtUbdYFWAAGYXdJEzVHKAAfKF9-AEZhUhoAWwAjKQBuKD8mMAAmYVSmJgAbCABDdgcomOz-AGZg4FD1PXsHDGkAei6oPr6APQ4gA)

### 💻 Code

```ts
type KeyOf<T> = T extends unknown ? keyof T : never

type Wrong<T> = { [K in KeyOf<T>]: T[K] }
```

### 🙁 Actual behavior

It is accepted by the type checker, but it shouldn't be allowed because `T` could be a union of objects with unrelated properties. The computed type doesn't even have any sense:

```ts
type test= Wrong<{ prop0: string } | { prop1: number; prop2: boolean } | { prop3: string[] }>
//   { prop0: unknown; prop1: unknown; prop2: unknown; prop3: unknown; }
```

### 🙂 Expected behavior

`K` shouldn't be allowed to index type `T`.

### PR DESCRIPTION
**Pull request by bentongxyz**
Fixes #49000

### CODE REVIEW

**Review by RyanCavanaugh — CHANGES_REQUESTED** [review]
I'm not sure what the correct fix is here (if I did, the bug would already be fixed), but this isn't it. There are at least two problems.

In general it's not valid, when computing type results, to be looking at the syntax form of the type's declaration once you've already computed the type (as we have here). Doing this leads to asymmetries where extracting a type into a type alias causes different behavior, which is never correct behavior. This kind of detection is also overspecific; it would fail to catch other cases.

The particular function `getTrueTypeFromConditionalType` is only supposed to do a type computation and memoize the result; it should not have any additional logic.

**Comment by bentongxyz** [comment]
Thank you, I'll take a look.

**Comment by sandersn** [comment]
@bentongxyz Do you want to keep working on this? Unless I misread the github history, @RyanCavanaugh's review still applies to the current state of the PR, right?

**Comment by bentongxyz** [comment]
@sandersn Yes, @RyanCavanaugh's review still applies. I think I could not find the solution to this issue. Should I close it?

**Comment by sandersn** [comment]
Yes, I'd prefer to close stuck PRs since they're easy enough to open later.

**Pull request closed without merging**
