### PR TITLE
Fix handling of string enums on LHS of `+=`

### LINKED ISSUE #35824: Assigning to a string fails if it was previously compared to an enum
**TypeScript Version:**  What is installed on the TypeScript playground

**Assigning to a string fails if it was previously compared to an enum**

If you run the code below in the TypeScript playground, line `widgetName += 'AddSomething'` errors out with `Type 'string' cannot be assigned to type 'Widgets'`.

However, if I cast the enum on the previous line to string (`widgetName == <string> Widgets.ComparableHomeSales`), everything compiles fine. 

In addition, if I replace `widgetName += 'AddSomething';` with `widgetName = widgetName  + 'AddSomething';`, it also compiles fine.

**Code**

```ts
enum Widgets {
    ComparableHomeSales = 'ComparableHomeSales',
    PriceHistory = 'PriceHistory'
}

class WidgetDescription {
    private name: Widgets;

    constructor(name: Widgets) {
        this.name = name;
    }

    get Name(): Widgets {
        return this.name;
    }
}

// code implementation
let widgetDescription: WidgetDescription = new WidgetDescription(Widgets.ComparableHomeSales);
let widgetName: string = widgetDescription.Name;

if (widgetName == Widgets.ComparableHomeSales) {
    widgetName += 'AddSomething'; // <-- ERROR
}

```

**Expected behavior:**

`widgetName += 'AddSomething'; ` should work

**Actual behavior:**

`widgetName += 'AddSomething'; ` does not work

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/?ssl=24&ssc=6&pln=1&pc=1#code/AQ4UwOwVwW2B1AlgEwOZgC4GdgG8BQowAwgPYwAOAhgE5UBGANmABLlgDKVzOAvMAHIylWg2ZsYnbmCwCANIVAAFGogDGrRFgykaAT2D8BK9Zu269AxSAC++a8DWMqWHEjSYAIjLWqKGRFIIPAciClUANyoMMGAIKkkALgQUdGwAbnsiIjUg7RooNR0aAAp4pJSPbABKEOz64AwACy0AOnLY-g7MhuA7UNA04AA5BLAS6uT3NJwCXqIaTCgaYOa27oHbB36iAHpdx1JkWMRKZkkIDGjAiAdmDGAAd1SvHz8AoKmXjG8sX0R-DdDHEwI9Kmlfv9AUEStNMFhWsJqHQmKx2FweNUeqB7k9vqMKvlEBBUMDnlVIe8bq0CWBMg5EAAzYAlclpWmGfhw7CI8jIsRoyQYmS1OYNNmYDkAaiMAEFkMgOOw1iSBNitvZ8EA)

### PR DESCRIPTION
**Pull request by elibarzilay**
See comment for details.

Fixes #35824

### CODE REVIEW

**Comment by elibarzilay** [comment]
@typescript-bot perf test this

**Review by weswigham — CHANGES_REQUESTED** [review]
I don't think the current changes are the correct place/way to fix this. Rather than modifying the base types of string enums (which should be fine - the current assignability rules between string enums and other literals is very intentional), the logic in `checkAssignmentOperator` just needs to better account for the narrowed types of compound assignments. Specifically, the `leftType` referenced in `checkAssignmentOperator` is currently the control-flow-narrowed type of the LHS expression. This is likely incorrect. `checkAssignmentOperator` probably needs to get the resolved symbol of the LHS reference, and get the _declared_ type of that reference to perform the check with, instead.

**Comment by sandersn** [comment]
@elibarzilay do you want to come back to this? It sounds like @weswigham suggested an alternate fix.

**Comment by sandersn** [comment]
I'm going to close this and let somebody else try @weswigham's suggestion.

**Pull request closed without merging**
