### PR TITLE
fix(36909): wrong error message when trying to named-import an export

### LINKED ISSUE #36909: Wrong error message when trying to named-import an export= (or CJS) export
**TypeScript Version:**  3.8 RC – nightly

**Search Terms:** declares locally but not exported

**Code**

```ts
// a.ts
class Foo {}
export = Foo;

// b.ts
import { Foo } from './a';
```

**Expected behavior:**
`Module "./a" has no exported member 'Foo'` (pre-3.8 message), or better yet, using context to pick between one of these specialized messages:

- TS, module kind < es2015, allowSynthetic off: `'Foo' can only be imported by using 'import Foo = require(...)' or by turning on the 'allowSyntheticDefaultImports' flag and using a default import.`
- TS, module kind < es2015, allowSynthetic on: `'Foo' can only be imported by using 'import Foo = require(...)' or a default import.`
- TS or JS, module kind >= es2015, allowSynthetic off: `'Foo' can only be imported by turning on the 'allowSyntheticDefaultImports' flag and using a default import.`
- TS or JS, module kind >= es2015, allowSynthetic on: `'Foo' can only be imported by using a default import.`
- JS, module kind < es2015, allowSynthetic off: `'Foo' can only be imported by using a 'require' call or by turning on the 'allowSyntheticDefaultImports' flag and using a default import.`
- JS, module kind < es2015, allowSynthetic on: `'Foo' can only be imported by using a 'require' call or by using a default import.'

**Actual behavior:**

`Module '"./a"' declares 'Foo' locally, but it is not exported.`

**Playground Link:**  https://www.typescriptlang.org/play/?ts=Nightly#code/CYUwxgNghgTiAEBbA9sArhBByKX4G8AoASBAA8AHZGAFwPgF8TIoBnV+AMWWXqdMrU6AXi48A3ISaFQLOElQZsAIzxFiAeg3wAsoszwsAIihG8s6HA5ZuyPBGRgoECAE8ANPGVo6ASz8cAHbIdORUtCDAAHQkvojhdPhivAzwAGYwyIiGuJJMQA

**Related Issues:** PR: #36187

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #36909

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@andrewbranch Sure, I opened PR to start the discussion.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Could you check the proposed error messages?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Could you check these changes?

**Comment by andrewbranch** [comment]
@a-tarasyuk can you take this out of draft state?

**Comment by DanielRosenwasser** [comment]
My thinking is to always suggest `esModuleInterop` because

* it disables namespace imports from becoming callable/constructable
* it will work for other module formats too

Thoughts @weswigham?

One thing that I'm not totally sure about whether this error message is "fine" for plain objects and namespaces - we're effectively nudging people to import it as a default, but arguably

```ts
import * as x from "./x`;
```

is reasonable for most TypeScript users importing from

```ts
// x.d.ts
declare let x: { foo(): x.Foo }
namespace x {
  export interface Foo {
    blah: number;
  }
}
export = x;

```

**Comment by andrewbranch** [comment]
`TS9423: 'Foo' can be imported literally any way except the way have it now.`

**Comment by DanielRosenwasser** [comment]
I need a "laughing but crying" reaction on GitHub 😅😂😭

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser 
> My thinking is to always suggest esModuleInterop because

Do you mean that just need to check if the option `esModuleInterop` is negative then show the message with the suggestion to enable it and avoid all other suggestions?

**Comment by sandersn** [comment]
@DanielRosenwasser does this need to go into 3.9? If so, can you reply to @a-tarasyuk's question?

**Comment by a-tarasyuk** [comment]
For the upcoming release, we can use the message - `Module "./a" has no exported member 'Foo' (pre-3.8 message)`. For suggested changes, we can make a new _feature_ and continue the discussion there. What do you @DanielRosenwasser, @andrewbranch think?

**Comment by DanielRosenwasser** [comment]
This can go into 3.9.1 (RC).

@a-tarasyuk No I just meant that instead of `allowSyntheticDefaultImports` we might be better off suggesting `esModuleInterop` in these new error messages instead - though I might be missing something.

**Comment by andrewbranch** [comment]
My suggestion was to use the same logic as here to populate the option name (`getTargetOfImportClause`, currently line 2365 of checker.ts):

image

But, I’m not totally sure the module target is actually a good heuristic, given that Webpack and other bundlers are going to do their own thing with modules—in other words, saying your module target is es2015+ doesn’t necessarily mean you’re ultimately going to run with es2015 modules at the end of your pipeline, and you may still need interop. Personally, I’ve _never_ been in a situation where `allowSyntheticDefaultExports` was correct.

**Comment by a-tarasyuk** [comment]
Thanks for the detailed feedback :). Maybe we can simplify messages something like this 

```
if there is exportedEqualsSymbol
    check option = moduleKind >= ModuleKind.ES2015 ? "allowSyntheticDefaultImports" : "esModuleInterop"
    show message 
        error = {value} can only be imported by using a default import
        add related info to error
            This module is declared with using export= and can only be used with the {option} flag
otherwise 
   show message `Module has no exported member` 
```

 What do you @DanielRosenwasser, @andrewbranch think?

**Comment by andrewbranch** [comment]
> {value} can only be imported by using a default import

>This module is declared with using export= and can only be used with the {option} flag

If the module kind is < es2015, these statements aren’t true 😄 because it can be imported using an ImportEqualsDeclaration.

Also, I only just now noticed the existing message I screenshot (emphasis mine):

> This module is **declared with using** 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

Declared with using?! Either “with” or ”using” needs to be deleted. What a mess.

@a-tarasyuk I think the best approach is just to keep what you have, but replace `allowSyntheticDefaultImports` with `esModuleInterop` unconditionally in the diagnostic messages. Does that sound good to everyone?

**Comment by a-tarasyuk** [comment]
>  I think the best approach is just to keep what you have, but replace allowSyntheticDefaultImports with esModuleInterop unconditionally in the diagnostic messages.

@andrewbranch ok, changed.

**Comment by DanielRosenwasser** [comment]
I think the question is still whether we should ever recommend `allowSyntheticDefaultImports` in the `module >= es2015` case - the benefit of `esModuleInterop is that it disallows code like

```
// foo.d.ts
declare namespace foo {}
declare function foo(): void;

export = foo;
```

```ts
// bar.ts
import * as foo from "foo";

foo(); // error in esModuleInterop, not in allowSyntheticDefaultImports
```

Is that accurate @weswigham?

**Comment by weswigham** [comment]
Yeah, that's the difference for that target.

**Comment by andrewbranch** [comment]
Sure, but none of these error messages recommend a namespace import. They recommend esModuleInterop + a _default_ import. The _benefit_ of esModuleInterop is you can use a default import on a CommonJS export and actually expect it to work at runtime.

I’m honestly confused about what `allowSyntheticDefaultImports` is for, because I’ve never used a runtime where it works. I just searched for it in release notes, and it was added in 1.8 for interop with SystemJS, which is a term that I probably read on a blog post in 2014, and otherwise have only seen on our tsconfig reference page.

So yeah, I don’t really see any reason to recommend `allowSyntheticDefaultImports`.

**Comment by DanielRosenwasser** [comment]
> I’m honestly confused about what `allowSyntheticDefaultImports` is for

It was to recognize the behavior of Webpack (and eventually Babel once it could understand TS code) during type-checking. We didn't want to change our own emit, and eventually we recognized that it would be useful.

`esModuleInterop`:

* provides that specific behavior when you're targeting `commonjs`
* basically acts as `allowSyntheticDefaultImports` when your module is `es2015`+
* yells at you for calling/constructing namespace imports because you have an alternative that will work in every module target

**Comment by a-tarasyuk** [comment]
> It's just a better newer version of the flag.

@DanielRosenwasser It seems that we need to leave `esModuleInterop` suggestion as is. Is it true?

cc @andrewbranch @weswigham

**Pull request merged**
