### PR TITLE
Update LKG.

### PR DESCRIPTION
**Pull request by DanielRosenwasser**

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
The build failed because of a timeout

```
  1) fourslash tests tests/cases/fourslash/getEmitOutputDeclarationMultiFiles.ts fourslash test getEmitOutputDeclarationMultiFiles.ts runs correctly:

     Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
```

I'll trigger a re-test, but this is likely a problem. @mhegazy

**Comment by mhegazy** [comment]
do they locally pass?

**Comment by DanielRosenwasser** [comment]
Yes, they all pass, it just took longer than 20 seconds for the latest version of Node.

**Comment by mhegazy** [comment]
The last test that @vladima ran Tuesday showed that we have better perf on node v5 than v4. So something does not add up here. Can you get more info?

**Comment by DanielRosenwasser** [comment]
I think it might've been an anomaly on Travis. The push build was consistent. https://travis-ci.org/Microsoft/TypeScript/builds/101112874

**Pull request merged**
