### PR TITLE
Add missing mapped type indexed access constraint

### LINKED ISSUE #47368: Mapped type indexed access issue
# Bug Report

An indexed access type `{ [P in K]: E }[X]` should be assignable to an instantiation of `E` with `X` substituted for `P`.

This issue was originally reported [here](https://github.com/microsoft/TypeScript/pull/47109#issuecomment-1003580482).

### 🔎 Search Terms

Mapped type indexed access.

### 🕗 Version & Regression Information

Nightly build

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220110#code/C4TwDgpgBAggTgcwLIEMxQLxQN5RQLigDsBXAWwCMI4AaKCwgZ2DgEsiEoBfAbgChQkKADESRAMYAeANJQIAD2AQiAE0ZQA1hBAB7AGaxEqMAD5MUABTzC8ZGgDa0gLoBKTGYBuO1iv6DoohLqWLiOUOya2vqGdmBOhIFS0ma8fHx6YuLArDpEUHoAjDJyispqkboGtsYmFhlBCZmMdFoghNJ0KIg2Rg7Obth8UMP5TfatThZdCC78XGn1WTl5egBMxQpKquqt0dVotYuMjUEt2u2d3THGjq44QyPiucyjEuZH49pO-COv4lOIWZ8ebpTLZXL5ADMG1K2wqe16pjqTRO4maFQueCu+zAtwGD2GTyIL0WqJkZiwHwmPGGAHpaVAAKJwOA6Wj0EjAKCMAAWOhIABsVEQAORcqgEv4AmZzPhAA)

### 💻 Code

```ts
type ArgMap = { a: number, b: string };
type Func<K extends keyof ArgMap> = (x: ArgMap[K]) => void;
type Funcs = { [K in keyof ArgMap]: Func<K> };

function f1<K extends keyof ArgMap>(funcs: Funcs, key: K, arg: ArgMap[K]) {
    funcs[key](arg);
}

function f2<K extends keyof ArgMap>(funcs: Funcs, key: K, arg: ArgMap[K]) {
    const func = funcs[key];  // Type Funcs[K]
    func(arg);
}

function f3<K extends keyof ArgMap>(funcs: Funcs, key: K, arg: ArgMap[K]) {
    const func: Func<K> = funcs[key];  // Error, Funcs[K] not assignable to Func<K>
    func(arg);
}
```

### 🙁 Actual behavior

Unexpected error in example above.

### 🙂 Expected behavior

No errors in example above.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #47368.

### CODE REVIEW

**Review by weswigham — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
So, one issue I'm seeing with the new constraint rules is this:

```ts
type ArgMap = { a: { x: number }, b: { y: string } };
type Func<K extends keyof ArgMap> = (x: ArgMap[K]) => void;
type Funcs = { [K in keyof ArgMap]: Func<K> };

function ff<K extends keyof ArgMap>(x: Funcs[K], y: Funcs[keyof ArgMap]) {
    x = y;  // Error
    y = x;  // Was ok, now errors
}
```

This is because for type `Funcs[K]` we used to explore the constraint `Funcs[keyof ArgMap]` where we now explore the constraints `Func<K>` and then `Func<keyof ArgMap>`. We may have to explore both possibilities.

**Comment by ahejlsberg** [comment]
Latest commits fix the issue I mentioned above. We know explore both possible constraints.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster
@typescript-bot test this
@typescript-bot user test inline
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
@typescript-bot user test this inline

**Comment by ahejlsberg** [comment]
@typescript-bot user test this

**Comment by ahejlsberg** [comment]
Tests and performance look good. I'm going to merge this.

**Pull request merged**
