### PR TITLE
Rename "append" to "appendMany" to avoid confusion with "ts.append"

### PR DESCRIPTION
**Pull request by andy-ms**

### CODE REVIEW

**Comment by rbuckton** [comment]
Could callers be switched to using `addRange` or `concatenate`?

**Comment by andy-ms** [comment]
`addRange` would work although that function unnecessarily checks for undefined values in `from`.

**Comment by mhegazy** [comment]
@andy-ms can you refresh the PR and address @sandersn 's comments

**Comment by andy-ms** [comment]
Looks like this is now irrelevant, since the code has been refactored to not have `append`.

**Pull request closed without merging**
