### PR TITLE
es5.d.ts isNan argument type unknown

### PR DESCRIPTION
**Pull request by MayCXC**
Fixes #

### CODE REVIEW

**Comment by jakebailey** [comment]
Not sure if you searched before proposing this, but this change is incorrect.

- https://github.com/microsoft/TypeScript/issues/52041#issuecomment-1371181542
- https://github.com/microsoft/TypeScript/issues/37449#issuecomment-600551704
- https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean

**Comment by RyanCavanaugh** [comment]
Closing PR with no approved issue

**Comment by MayCXC** [comment]
Ah, I was using issues search incorrectly, as were some of the others. However, I do think that both the issue reporters and issue closers are making misinterpretations of the ECMA spec. Number.isNaN and isNaN are both intended to be used on non-number values and should be typed accordingly, for the same reason that both === and == are valid operators in typescript. An example/counterexample is that isNan("NaN") is true while Number.isNan("NaN") is false, not because isNan is coercing "NaN" incorrectly, but because it is meant to coerce "NaN" as per the spec. I can see the benefit to code clarity of making ts users do isNaN(Number("NaN")) rather than rely on ECMA's ToNumber algorithm, but it would be more appropriate to make your own standard library to address those concerns rather than misrepresent ECMA's.

**Comment by RyanCavanaugh** [comment]
It's extremely intentional that the lib doesn't 1-to-1 match the spec. See ["what does all JS is TS mean?"](https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean)

**Pull request closed without merging**
