### PR TITLE
create outlining span for JsxFragment

### LINKED ISSUE #31631: React fragments cannot be folded with shorthand syntax
Issue Type: <b>Bug</b>

Create a React component using JSX and wrap the element in a fragment using the `<></>` shorthand.

The element cannot be folded when using the shorthand. Using the longer `<Fragment>` component, the folding works as expected.

react-fragment-folding

react-fragment-folding2

react-fragment-folding3

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by gb714us**
Fixes #31631

### CODE REVIEW

**Comment by dragomirtitian** [comment]
Just a suggestion, maybe add some tests for this? This file `tests\cases\fourslash\getJSXOutliningSpans.tsx` contains tests for jsx outlines, maybe you could add it in there ?

**Comment by gb714us** [comment]
Added test case for this change.

**Comment by erikphansen** [comment]
Is there a reason that this cannot be merged yet?

**Comment by gb714us** [comment]
> Is there a reason that this cannot be merged yet?

I was assuming they were waiting for their next release.

**Pull request merged**
