### PR TITLE
Fix narrowing with constrained type parameter

### LINKED ISSUE #10811: Generic type erased after type guard with strictNullChecks
**TypeScript Version:**  2.0.2

**Code**

```ts
interface Pet {
    name: string;
}

function isPet(pet: any): pet is Pet {
    return typeof pet.name === "string";
}

export function speak<TPet extends Pet>(pet: TPet, voice: (pet: TPet) => string): string {
    if (!isPet(pet)) {
        throw new Error("Expected \"pet\" to be a Pet");
    }

    return voice(pet); // line 14
}
```

**Expected behavior:**
Module compiles without error when `--strictNullChecks` is enabled OR disabled.

**Actual behavior:** 
- Module compiles without error when `--strictNullChecks` is _disabled_.
- The following error is produced when `--strictNullChecks` is _enabled_

    ```
    bug.ts(14,18): error TS2345: Argument of type 'Pet' is not assignable to parameter of type 'TPet'.
    ```

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #10811.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@mhegazy We should consider cherry picking this for 2.0.

**Comment by sandersn** [comment]
:+1:

**Comment by mhegazy** [comment]
👍

**Comment by mhegazy** [comment]
ported to release-2.0 in https://github.com/Microsoft/TypeScript/commit/9986f81981d56e47957ca436b69384d026c14eda

**Comment by rbuckton** [comment]
@mhegazy, the Travis CI build is now failing due to a change in the "narrowingConstrainedTypeParameter.types" basline.

**Comment by mhegazy** [comment]
@rbuckton pushed an update to master. sorry about that. the new test was added before the literal types PR was applied so the baseline needed updates.

**Pull request merged**
