### PR TITLE
Add 'T | PromiseLike<T>' inference from awaited types

### PR DESCRIPTION
**Pull request by rbuckton**
This re-introduces the `T | PromiseLike<T>` inference heuristic previously added in the `awaited` type PR. This heuristic improves type inference for cases where we are inferring to a union consisting of a single type variable `T` and one or more `Promise`-like types whose "promised type" (i.e., the type of the `value` parameter to the `onfulfilled` callback) is precisely `T`. This primarily impacts inference for cases like `Promise.resolve` and `Promise#then`:

```ts
declare const p4: Promise<number> | Promise<string>;

// infers `number | string`
const p5 = Promise.resolve(p4);
```

One minor change vs. the implementation in the `awaited` types implementation is that this version detects unions with more than two constituents (i.e., `T | PromiseLike<T> | Promise<T>`) as long as all of the constituents are essentially promises for `T`.

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
Hmm. The failing JQuery tests are falling afoul of union subtype reduction. The `then` method is declared with something like this:
```ts
then<ARD = never, AJD = never, ...>(
  doneFilter: (t: TR, u: UR, v: VR, ...s: SR[]) => PromiseBase<ARD, AJD, ...> | Thenable<ARD> | ARD,
  failFilter: (t: TJ, u: UJ, v: VJ, ...s: SJ[]) => PromiseBase<ARF, ...> | Thenable<ARF> | ARF,
  progressFilter: (t: TN, u: UN, v: VN, ...s: SN[]) => PromiseBase<ARP, ...> | Thenable<ANP> | ANP
): PromiseBase<ARD | ARF | ARP, AJD | AJF | AJP, ...>;
```

Since `PromiseBase<ARD, AJD, ...>` is assignable to `Thenable<ARD>`, we drop `PromiseBase` during subtype reduction, so its not available as a candidate for inference.

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
@typescript-bot user test this

**Comment by rbuckton** [comment]
* RWC Baselines look good.
* User test baselines look good
* DT baselines are clean.

@ahejlsberg, @weswigham I'd appreciate if you could take a look.

**Comment by sandersn** [comment]
@rbuckton is this for 3.9 or 4.0?

**Comment by rbuckton** [comment]
I was hoping for 3.9, as this was initially part of `awaited` and does fix some inference-related errors in RWC, but I'd defer to @DanielRosenwasser to weigh on on this. I'll have to dig through our issues list for related issues though.

**Comment by DanielRosenwasser** [comment]
I think we should take this as an item in the design meeting to understand whether it goes in regardless of awaited. It's way too late in the game to add it to 3.9 IMO.

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
