### PR TITLE
Fixes #16255: DOM lib is missing Intersection Observer API on window …

### LINKED ISSUE #16255: DOM lib is missing Intersection Observer API on window global
**TypeScript Version:**  2.3.4

**Code**

The browser Intersection Observer API defines these on the window:

```ts
window.IntersectionObserver
window.IntersectionObserverEntry
```

**Expected behavior:**
These should be defined in the DOM lib typings.

**Actual behavior:**
They are not defined, so I get type errors.

### PR DESCRIPTION
**Pull request by johan-gorter**
Fixes #16255

### CODE REVIEW

**Comment by ikatyang** [comment]
> **These files are not meant to be edited by hand.** If you need to make modifications, the respective files should be changed within the repository's top-level `src` directory. Running `jake LKG` will then appropriately update the files in this directory. (https://github.com/Microsoft/TypeScript/tree/master/lib#readme)

-> https://github.com/Microsoft/TypeScript/tree/master/src/lib#readme

**Comment by mhegazy** [comment]
what @ikatyang said.

**Comment by johan-gorter** [comment]
I tried to understand where the change should be made and I found the TSJS-lib-generator project. But from there I do not know where I need to make the changes. Giving up.

**Comment by kitsonk** [comment]
@johan-gorter I believe it just needs to be added to the JSON structure in [addedTypes](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/addedTypes.json).

**Pull request closed without merging**
