### PR TITLE
feat(47698): Detect uncalled function statements

### LINKED ISSUE #47698: Detect uncalled function statements
# Suggestion

## 🔍 Search Terms
- uncalled function
- check
- statement

## ⭐ Suggestion

Today TS can detect uncalled functions that appear in conditionals. I propose also extending this to uncalled functions that appear as statements

## 📃 Motivating Example

```ts
function doImportantStuff() { }

doImportantStuff;  // Mistake here. The user forgot to call the func

if (doImportantStuff) { // This one is detected today

}
```

## 💻 Use Cases

This can help catch a common programming mistake. As long as the function being checked has a `const` binding and is always a function type, I don't think there are cases where you actually want to write `doImportantStuff;` as a statement

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47698

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
Curious
@typescript-bot test this
@typescript-bot user test this

**Comment by RyanCavanaugh** [comment]
👀👀👀
https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/utilities/src/object.test.ts#L49

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Looks like a bug in `fluentui` tests. `toBeFalsy` is defined as a function https://github.com/DefinitelyTyped/DefinitelyTyped/blob/96638237e21d6817acfed9feff0a99de412fb003/types/jest/index.d.ts#L825

**Comment by jakebailey** [comment]
@typescript-bot user test this inline

**Comment by jakebailey** [comment]
This seems great, though I have no clue where the above code is in fp-ts to check that user test diff; AFAIK the user tests pull whatever's latest in their git repo and line 12 is a comment.

**Comment by a-tarasyuk** [comment]
@jakebailey I think the error is related to [this uncalled function](https://github.com/gcanti/fp-ts/blob/2d70be4785fec90aed119d2ec075faef36116321/dtslint/ts3.5/Applicative.ts#L12)

**Comment by jakebailey** [comment]
Oh, duh, I was in the wrong folder.

I guess that would turn into a message now, even though they are using it just for checking expected types. I wonder if this will cause oddities for the DT tests?

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by jakebailey** [comment]
DT run finished, and it does seem like this causes loads of issues with the DT tests, like:

```
Error in validator
Error: /home/vsts/work/1/s/DefinitelyTyped-tools/packages/dtslint-runner/DefinitelyTyped/types/validator/validator-tests.ts:126:5
ERROR: 126:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 127:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 133:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 134:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 169:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 170:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 226:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
ERROR: 227:5  expect  TypeScript@local compile error: 
This expression refers to function. Did you mean to call it instead?
```

**Comment by jakebailey** [comment]
Also, if merged, I think this PR also closes #47699, right?

**Comment by a-tarasyuk** [comment]
> DT run finished, and it does seem like this causes loads of issues with the DT tests, like:

All errors seem to be related to uncalled functions and located in tests, not in `.d` files [1](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a8b3aa317d044b07429eeef497096ec842f1737/types/validator/validator-tests.ts#L126-L127) [2](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a8b3aa317d044b07429eeef497096ec842f1737/types/validator/validator-tests.ts#L133-L134) [3](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a8b3aa317d044b07429eeef497096ec842f1737/types/validator/validator-tests.ts#L169-L170) [4](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a8b3aa317d044b07429eeef497096ec842f1737/types/validator/validator-tests.ts#L226-L227) [5](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a8b3aa317d044b07429eeef497096ec842f1737/types/cssstyle/cssstyle-tests.ts#L11-L16) [6](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a8b3aa317d044b07429eeef497096ec842f1737/types/cjson/cjson-tests.ts#L30). Another question is that in the _DefinitelyTyped_ it is ok to check the type without calling a function ([expectRule](https://github.com/microsoft/dtslint/blob/master/src/rules/expectRule.ts)) 😄

**Comment by jakebailey** [comment]
If we're going to accept this, I'm assuming we'll need some sort of change in dtslint to ignore it (since ExpectType is clearly not going away any time soon). Is that doable, given this check isn't a compiler option (so we may read the build as "failing"?). I'm also sort of wary of the change where someone's using ExpectType externally, since now their build will end up failing too.

**Comment by a-tarasyuk** [comment]
What about adding a new `strictUncalledFunctions` option to control this check?

**Comment by RyanCavanaugh** [comment]
Discussed at the design meeting and we'd prefer to leave this Awaiting More Feedback for now -- the sorts of errors this can detect can be equally picked up by a non-type-aware linter, this interacts quite badly with dts-lint, and more annoyingly it would bring up a lot of false errors as you're typing.

**Pull request closed without merging**
