### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### LINKED ISSUE #44898: To add `cache` support for GitHub Actions using `setup-node`
# Suggestion

To add `cache` support for GitHub Actions using `setup-node`

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

`cache`, `setup-node`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

## 💻 Use Cases
See https://github.com/microsoft/TypeScript/pull/44897

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

Fix #44898

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
@weswigham I reviewed this and didn't see anything suspicious. Please merge if you like it.

**Comment by weswigham** [comment]
First - it'd be super nice if you could split the formatting differences into a separate PR - I can't tell if the whitespace changes are good or bad.

Second - the GH actions build is currently a bit simpler than the DevOps one because it lacked caching - while caching _most_ dependencies is fine, `tslint` (probably `eslint` and ts-related plugins nowadays) and `typescript` in the tree need to be cache-busted explicitly, so we always get the latest nightly of them. The DevOps build (which has caching) accomplishes this by explicitly uninstalling and reinstalling those dependencies after the initial (cached) install. I'm not sure if the node setup action's caching strategy is amenable to this, but we'd want it to do the same if it caches (since if we stop building against nightly tslint/eslint/typescript, we're liable to break the combination of them and not know when).

**Review by weswigham — CHANGES_REQUESTED** [review]
(see above comment)

**Comment by oscard0m** [comment]
> First - it'd be super nice if you could split the formatting differences into a separate PR - I can't tell if the whitespace changes are good or bad.
>
> Second - the GH actions build is currently a bit simpler than the DevOps one because it lacked caching - while caching _most_ dependencies is fine, `tslint` (probably `eslint` and ts-related plugins nowadays) and `typescript` in the tree need to be cache-busted explicitly, so we always get the latest nightly of them. The DevOps build (which has caching) accomplishes this by explicitly uninstalling and reinstalling those dependencies after the initial (cached) install. I'm not sure if the node setup action's caching strategy is amenable to this, but we'd want it to do the same if it caches (since if we stop building against nightly tslint/eslint/typescript, we're liable to break the combination of them and not know when).

If I'm understanding correctly:
- `ci.yml` and ``

---

GitHub was messing up the indentation differences and I had to create a new PR from scratch... Sorry for the mess but I hope is not a problem 🙏🏽 🙏🏽 🙏🏽 🙏🏽 . This is the new PR: https://github.com/microsoft/TypeScript/pull/44924

**Pull request closed without merging**
