### PR TITLE
Fixed braceless type tags with types starting with an open parenthesis

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/TypeScript/issues/57166

### CODE REVIEW

**Comment by sandersn** [comment]
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by sandersn** [comment]
@jakebailey do you remember if jsdoc parsing shows up in perf results anymore?

Having a lot of tokens was a significant cause of slowdown in JS comment parsing when I profiled. So I don't want to add tokens unless it's for a good reason.

Is there a lot of un-braced usage of types? It's only supported in TS for compatibility, since the braces are supposed to be required.

**Comment by jakebailey** [comment]
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
> @jakebailey do you remember if jsdoc parsing shows up in perf results anymore?

No, not really.

**Comment by Andarist** [comment]
> Is there a lot of un-braced usage of types? It's only supported in TS for compatibility, since the braces are supposed to be required.

Right. But since they are optional in this context I'd expect this to work (there is an explicit boolean set here that allows it). I don't want this for myself - I'm not using JSDoc types anyway. It's just a problem I noticed when working on https://github.com/microsoft/TypeScript/pull/57110 and such a braceless type came there (in the original issue) from the real-world code.

**Review by sandersn — APPROVED** [review]
I'm not convinced that this is very valuable, but it does fix an inconsistency, and it shouldn't hurt the fast path for scanning jsdoc comment text.

**Comment by sandersn** [comment]
Can you update this PR from main before I merge? There has been a lot of churn in baselines recently.

**Comment by Andarist** [comment]
@sandersn done

**Pull request merged**
