### PR TITLE
Handle undefined `location.parent` when getting completionEntryDetails

### LINKED ISSUE #54106: Error from completionEntryDetails on entry before definition of merged variable and type alias
Minimal repro:

```ts
/**/
type lolol = any;
declare const lolol: any;
```

Request completions and view completion entry details on `lolol`.

**Expected:**

Something like

```
type lolol = any;
var lolol: any;
```

**Actual:**

```
Response received: completionEntryDetails (486). Request took 4 ms. Success: false . Message: Error processing request. Cannot read properties of undefined (reading 'kind')
TypeError: Cannot read properties of undefined (reading 'kind')
    at isTypeReferenceNode (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:28145:15)
    at isConstTypeReference (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:14193:10)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:164362:60)
    at /home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:150803:44
    at Object.runWithCancellationToken (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:47691:16)
    at createCompletionDetailsForSymbol (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:150801:69)
    at Object.getCompletionEntryDetails (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:150749:14)
    at Object.getCompletionEntryDetails2 [as getCompletionEntryDetails] (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:136309:35)
    at /home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:180769:43
    at mapDefined (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:2638:22)
    at IpcIOSession.getCompletionEntryDetails (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:180767:20)
    at completionEntryDetails (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:179120:43)
    at /home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:181457:69
    at IpcIOSession.executeWithRequestId (/home/codespace/.vscode-remote/extensions/ms-vscode.vscode-typescript-next-5.1.20230416/node_modules/typescript/lib/tsserver.js:181449:14)
```

<h2>TypeError: Cannot read properties of undefined (reading 'kind')</h2>

```
Req #1304 - completionEntryDetails
    at isTypeReferenceNode (/typescript-5.1.0-dev.20230430/lib/tsserver.js:28152:15)
    at isConstTypeReference (/typescript-5.1.0-dev.20230430/lib/tsserver.js:14196:10)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (/typescript-5.1.0-dev.20230430/lib/tsserver.js:165036:60)
    at /typescript-5.1.0-dev.20230430/lib/tsserver.js:156395:44
    at Object.runWithCancellationToken (/typescript-5.1.0-dev.20230430/lib/tsserver.js:47706:16)
    at createCompletionDetailsForSymbol (/typescript-5.1.0-dev.20230430/lib/tsserver.js:156393:69)
    at Object.getCompletionEntryDetails (/typescript-5.1.0-dev.20230430/lib/tsserver.js:156341:14)
    at Object.getCompletionEntryDetails2 [as getCompletionEntryDetails] (/typescript-5.1.0-dev.20230430/lib/tsserver.js:141881:35)
    at /typescript-5.1.0-dev.20230430/lib/tsserver.js:181470:43
    at mapDefined (/typescript-5.1.0-dev.20230430/lib/tsserver.js:2643:22)
    at IOSession.getCompletionEntryDetails (/typescript-5.1.0-dev.20230430/lib/tsserver.js:181468:20)
    at completionEntryDetails (/typescript-5.1.0-dev.20230430/lib/tsserver.js:179818:43)
    at /typescript-5.1.0-dev.20230430/lib/tsserver.js:182167:69
    at IOSession.executeWithRequestId (/typescript-5.1.0-dev.20230430/lib/tsserver.js:182159:14)
    at IOSession.executeCommand (/typescript-5.1.0-dev.20230430/lib/tsserver.js:182167:29)
    at IOSession.onMessage (/typescript-5.1.0-dev.20230430/lib/tsserver.js:182209:51)
    at Interface.<anonymous> (/typescript-5.1.0-dev.20230430/lib/tsserver.js:183765:14)
```

<h4>Affected repos</h4>
<details>
<summary><a href="https://github.com/withastro/astro">withastro/astro</a></summary>
Raw error text: <code>RepoResults2/withastro.astro.rawError.txt</code> in the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=153577&view=artifacts&type=publishedArtifacts">artifact folder</a>
<h4>Last few requests</h4>

```json
{"seq":1301,"type":"request","command":"organizeImports","arguments":{"scope":{"type":"file","args":{"file":"@PROJECT_ROOT@/packages/astro/env.d.ts"}},"skipDestructiveCodeActions":true}}
{"seq":1302,"type":"request","command":"getOutliningSpans","arguments":{"file":"@PROJECT_ROOT@/packages/astro/env.d.ts"}}
{"seq":1303,"type":"request","command":"completionInfo","arguments":{"file":"@PROJECT_ROOT@/packages/astro/env.d.ts","line":3,"offset":1,"includeExternalModuleExports":false,"triggerKind":1}}
{"seq":1304,"type":"request","command":"completionEntryDetails","arguments":{"file":"@PROJECT_ROOT@/packages/astro/env.d.ts","line":3,"offset":1,"entryNames":["Astro"]}}

```

<h4>Repro steps</h4>
<ol>
<li><code>git clone https://github.com/withastro/astro --recurse-submodules</code></li>
<li>In dir <code>astro</code>, run <code>git reset --hard 2dca81bf2174cd5c27cb63cb0ae081ea2a1ac771</code></li>
  <li>In dir <code>astro</code>, run <code>pnpm install --no-frozen-lockfile --prefer-offline --ignore-scripts --reporter=silent</code></li>
<li>Back in the initial folder, download <code>RepoResults2/withastro.astro.replay.txt</code> from the <a href="https://typescript.visualstudio.com/TypeScript/_build/results?buildId=153577&view=artifacts&type=publishedArtifacts">artifact folder</a></li>
<li><code>npm install --no-save @typescript/server-replay</code></li>
<li><code>npx tsreplay ./astro ./withastro.astro.replay.txt path/to/tsserver.js</code></li>
<li><code>npx tsreplay --help</code> to learn about helpful switches for debugging, logging, etc</li>
</ol>
</details>

_Originally posted by @typescript-bot in https://github.com/microsoft/TypeScript/issues/54077#issuecomment-1529160827_

### PR DESCRIPTION
**Pull request by MariaSolOs**
Fixes #54106

### CODE REVIEW

**Comment by MariaSolOs** [comment]
Tests are pending because I don't know how to test `completionEntryDetails`. `verify.completions` seems to only check `completionInfo`, and I cannot use the resulting `andApplyCodeAction` because the entry I want to test doesn't have a description or source (which are needed in the parameter options).

**Comment by jakebailey** [comment]
Where is this location coming from? All source files should be bound and have parents, so is this location the SourceFile itself?

**Comment by MariaSolOs** [comment]
> Where is this location coming from? All source files should be bound and have parents, so is this location the SourceFile itself?

Correct. So with the example from the bug:
```
/**/
type lolol = any;
declare const lolol: any;
```
When explicitly requesting completions in `/**/`, `location` will be the source file itself, which causes the error in the line I'm changing.

**Comment by MariaSolOs** [comment]
@jakebailey @DanielRosenwasser @andrewbranch any hints on how I can test this with fourslash?

**Comment by jakebailey** [comment]
Are the details in https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/completionsObjectLiteralMethod2.ts what you're trying to get at?

**Comment by MariaSolOs** [comment]
> Are the details in https://github.com/microsoft/TypeScript/blob/main/tests/cases/fourslash/completionsObjectLiteralMethod2.ts what you're trying to get at?

Hmm no this isn't helping me here. The completion entry remains the same with and without my change, like I need to simulate selecting the actual completion to trigger the failure.

**Comment by MariaSolOs** [comment]
Okay I was able to test this with `verify.baselineCompletions()`. You were right @iisaduan!

**Review by DanielRosenwasser — APPROVED** [review]

**Pull request merged**
