### PR TITLE
Emit unused identifier suggestion diagnostics in declaration files and ambient nodes

### LINKED ISSUE #33121: VS Code: "editor.showUnused": true not working in `*.d.ts` files
I was asked by the VS Code team to move this bug report upstream to the TypeScript project.

- [x] searched existing issues to avoid creating duplicates
- [x] tested using the latest insiders build to make sure issue has not already been fixed
- [x] issue occurs when all extensions are disabled

- VSCode Version: 1.37.1
- VSCode Insiders Version: 1.38.0-insider
- OS Version: MacOS Mojave 10.14.6
- **TypeScript Version:**  3.7.0-dev.20190828

**Search Terms:**
"VS Code", "d.ts", "unused", "editor.showUnused"

Steps to Reproduce:

1. Ensure `editor.showUnused` is set to `true` for user, workspace, and folder.
1. Create a file with extension `.d.ts`
1. Add valid import statement such as
```import { User } from 'types/users';```

**Actual behavior**: Import statement is not faded even though it hasn't been used.
**Expected behavior**: Import statement should be faded out as per setting.

Additional steps:

1. convert filename to have only the `.ts` extension (drop the `.d`)
Note: import line is dimmed as expected. The issue appears to only be affected by `.d.ts` files.

**Related Issues:**
Possibly:
https://github.com/microsoft/TypeScript/issues/32196
https://github.com/microsoft/TypeScript/issues/30260

### PR DESCRIPTION
**Pull request by andrewbranch**
Need to perf test this and get feedback on whether there could be weird unintended consequences of this. Might want to consider only doing this from the language service, not via tsc?

Closes #33121

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
Perf looks fine

**Comment by andrewbranch** [comment]
We don’t by default, but I don’t know if there might be some flag to enable it? I think I might be thinking of a suggested feature, `--suggestionsAreErrors` or something? Does that ring a bell?

**Comment by sheetalkamat** [comment]
Would recommend checking with @DanielRosenwasser before merging to confirm this change is desired

**Comment by DanielRosenwasser** [comment]
I understand that users will get suggestion diagnostics, and that seems fine. Presumably our logic is good enough here and it's not intrusive.

However, will we start erroring when a user runs with `noUnusedLocals`? Is that a breaking change?

**Comment by andrewbranch** [comment]
> will we start erroring when a user runs with `noUnusedLocals`?

@DanielRosenwasser no, I added special logic such that these new suggestion diagnostics never become errors, even under `noUnusedLocals`. I added tests demonstrating this by setting those options to true and doing `verify.getSemanticDiagnostics([])`.

**Pull request merged**
