### PR TITLE
Consistently avoid pulling on the source return type when the target return type is any

### LINKED ISSUE #47108: Inconsistent return type widening
Reported [on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57563#discussion_r766357595).

Why would these two declarations produce different types?

```ts
declare function useState1<S>(initialState: (S extends (() => any) ? never : S) | (() => S)): S; // No args
declare function useState2<S>(initialState: (S extends ((...args: any[]) => any) ? never : S) | (() => S)): S; // Any args

const func1 = useState1(() => () => 0); // () => number
const func2 = useState2(() => () => 0); // () => 0
```

[Playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211210#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQBlDKDEARgB4SA+ACi1S2ygjIpAC55GS8EAA9KqYIX6MAlPAC89eFFQBPWQH54qEADcQMeHxKyAPlNkL4x6UYDc8APQP4AORxKYAc0IAoUJFgEFHRsPAJiLkoAJjomFjYsDkjefkERMQkpADoc2G8+ZRUAbQBdC0VCjS1dfUMrU3N5RWs7R2cAQVUPbx8fMDxCDCQ0MCp5cNJySipGGSb+cvgABml7JwX51GQAWwAjfT6BoeCwKPGiSe4o2cW5yxW15zvFJaA)

It seems to have been like this since 3.6, so not urgent - just perplexing.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #47108

### CODE REVIEW

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
@typescript-bot perf test this

**Comment by andrewbranch** [comment]
As you note in the issue discussion, this is a breaking change.

**Comment by andrewbranch** [comment]
Looking at it more, I don’t quite understand where the circularity is or why either of those signatures should have different widening behavior from

```ts
declare function f<S>(fn: () => S): S;
f(() => 0); // S -> number
```

Maybe it’s worth investigating the additional change you mentioned, or if that too is very breaky, maybe this isn’t worth fixing right now?

**Comment by weswigham** [comment]
So, as far as the additional change goes, It's _technically_ breaky because we no longer return literal types in some locations, but it's not *that* breaky, because those are locations where other information isn't present to indicate that we _need_ to return literal types. As to weather to take it or just this - we should take one or both, because that'll make us consistent; weather we take the additional change or not is just weather we'd prefer to return base types in the affected cases (as with the additional change linked in the issue)  or literal types (as in this PR).

**Comment by andrewbranch** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt

**Review by andrewbranch — APPROVED** [review]

**Pull request merged**
