### PR TITLE
Disable evolving types with implicit any

### LINKED ISSUE #11839: Compiler should allow assignment of new property in empty object
**TypeScript Version:**  built from master

**Code**

``` ts
var range;
range = {} 
range.newProp = 10;  // error

var obj;
obj = {
   propx: 10
}
obj.propy = 20;  // error
```

**Expected behavior:**
No error here `range.newProp = 10;` or `obj.propy = 20;`

**Actual behavior:** 
Error   TS2339  Property 'newProp' does not exist .... or Property 'propy' does not exist ...

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #11839

### CODE REVIEW

**Comment by sandersn** [comment]
@mhegazy @ahejlsberg I disabled evolving types when `--noImplicitAny` isn't on.

**Comment by sandersn** [comment]
@mhegazy thanks for the reminder to always leave evolving types on for Javascript files.

**Comment by mhegazy** [comment]
We will need to port this to release-2.1 as well.

**Comment by sandersn** [comment]
Done

**Pull request merged**
