### PR TITLE
Trim empty line whitespaces

### LINKED ISSUE #4984: Trailing whitespace is not removed by formatter on 'empty' lines
The following test fails:

```typescript
/// <reference path='fourslash.ts' />

////    /*1*/
////	/*2*/

format.document();
verify.currentFileContentIs("\n");
````

_(where the contents before marker 2 are a `\t` character)_

I notice trailing whitespace is not removed from comments; whilst I would argue trailing whitespace should be removed across the board, I think it should at least be removed from lines only containing whitespace. 

Thoughts?

### PR DESCRIPTION
**Pull request by SaschaNaz**
Fixes #4984

- [x] Fix duplication
- [x] Add tests

### CODE REVIEW

**Comment by SaschaNaz** [comment]
Runs well on Visual Studio but keeps failing on tests with "destroyed non-whitespace content". I have no idea. Hmm.

**Comment by RyanCavanaugh** [comment]
> keeps failing on tests with "destroyed non-whitespace content"

This is an assertion in the fourslash harness that ensures our formatting edits only ever remove whitespace (we kept having bugs where you'd format e.g. `var foo   = 3;` and get something bad like `var fo = 3;`).

**Comment by SaschaNaz** [comment]
@RyanCavanaugh Yes, I understand what the test does but I have no idea why the results in test set and Visual Studio are different. Copy-pasting the failing test on VS shows no bug.

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
@vladima can you take a look when you get the chance?

**Comment by SaschaNaz** [comment]
Replaced by #5983.

**Pull request closed without merging**
