### PR TITLE
At `<div x=/**/`, completion insertText should be wrapped in braces

### LINKED ISSUE #21341: Don't provide completions after `=` in JSX
**TypeScript Version:**  2.7.0-dev.20180122

**Code**

```ts
<div foo=
```

**Expected behavior:**

No completions. This is not a valid location for an identifier, only a string literal, jsx expression, or `{}`.

**Actual behavior:**

Get global completions.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #21341

Includes a fix from #21330 but I would prefer #21342, so must wait on that to merge before merging this.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
How does this work with string literal completions in these locations?

**Comment by andy-ms** [comment]
`getStringLiteralCompletionEntries` goes through a different code path since it doesn't use symbols, so it won't be affected by this. I'd write a test for that, but due to #21374 we will crash when trying to get details for the completion.

**Comment by mhegazy** [comment]
@andy-ms can you also port this to release-2.7 as well.

**Comment by andy-ms** [comment]
Waiting on #21342

**Pull request merged**
