### PR TITLE
Fix find-all-refs crashing in some project references scenarios

### LINKED ISSUE #41971: Auto-import crash in find all references
An internal user is hitting this when running find all references.  They're using a forked version of 4.1.2 but I'm 99% sure the code changes do not affect the repro (though they might affect the line numbers).

```
Error: AutoImportProviderProject language service should never be used. To get the program, use `project.getCurrentProgram()`.
    at AutoImportProviderProject.getLanguageService (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:152355:23)
    at isLocationProjectReferenceRedirect (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156266:35)
    at callbackProjectAndLocation (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156283:17)
    at combineProjectOutputWorker (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156248:24)
    at combineProjectOutputForReferences (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156176:13)
    at IOSession.Session.getReferences (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:157478:34)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:156513:61)
    at D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158331:88
    at IOSession.Session.executeWithRequestId (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158322:28)
    at IOSession.Session.executeCommand (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158331:33)
    at IOSession.Session.onMessage (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:158355:35)
    at Interface.<anonymous> (D:\code\Midgard\node_modules\typescript\lib\tsserver.js:160565:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #41971 

Thanks @amcasey for the repro help. This is one of those bugs that took 3 minutes to diagnose and fix, and 3 hours to come up with a failing test.

### CODE REVIEW

**Review by amcasey — APPROVED** [review]
I hacked your fix into the original repro and things look good now.  Kudos on finding a compact repro!

**Comment by KEMBL** [comment]
Guys, it occurs again when I put the cursor on Interface name and press F2 in Vs Code 1.52.1. 
Initially, I've got that problem with typescript 4.1.2, after I found this thread and replaced TS version `c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript` to 4.1.3, restarted PC, it starts to show the same error but now with 4.1.3 typescript version.

look: v 4.1.2 error
image

 v 4.1.3 error

image

**Comment by andrewbranch** [comment]
@KEMBL, the circumstances that could cause this to happen are pretty complicated, so it would be helpful if you could provide a full codebase where this happens. Is this an open source project I can clone, or could you upload a reduced case somewhere?

**Comment by KEMBL** [comment]
@andrewbranch thank you for your attention, I will see what I can do, could take time. The project is not open-source but I will try to catch that in other open-source projects.

**Comment by scottbessler** [comment]
> @KEMBL, the circumstances that could cause this to happen are pretty complicated, so it would be helpful if you could provide a full codebase where this happens. Is this an open source project I can clone, or could you upload a reduced case somewhere?

We also are seeing this with Typescript 4.1.3 in a fairly large monorepo with ~70 projects and many references

**Pull request merged**
