### PR TITLE
Allow operators and indexing with intersections involving primtive types

### LINKED ISSUE #5599: Intersection types are not valid index signature types
For example, a variable of type
```ts
type Path = string & { __pathBrand: any };
```
cannot be used as an indexer type, and cannot be used to index an object with a `string` type indexer (despite being safely usable as a `string` in all other locations).

If an intersection type contains types which are valid for use in an index signature, then the intersection type itself should probably be valid as an index signature.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #5599.

This PR allows operators and indexing to work with intersection types that include primitive types, making it easier to create and use "tagged" primitive types. For example:

```typescript
type Guid = string & { $Guid };          // Tagged string type
type SerialNo = number & { $SerialNo };  // Tagged number type

function createGuid() {
    return "21EC2020-3AEA-4069-A2DD-08002B30309D" as Guid;
}

function createSerialNo() {
    return 12345 as SerialNo;
}

let map1: { [x: string]: number } = {};
let guid = createGuid();
map1[guid] = 123;  // Can index with tagged string

let map2: { [x: number]: string } = {};
let serialNo = createSerialNo();
map2[serialNo] = "hello";  // Can index with tagged number

// Operators treat tagged primitives as regular primitives
const s1 = "{" + guid + "}";
const s2 = guid.toLowerCase();
const s3 = guid + guid;
const s4 = guid + serialNo;
const s5 = serialNo.toPrecision(0);
const n1 = serialNo * 3;
const n2 = serialNo + serialNo;
const b1 = guid === "";
const b2 = guid === guid;
const b3 = serialNo === 0;
const b4 = serialNo === serialNo;
```

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
:+1:

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
What about `someConstituentsHaveKind` instead of `maybeTypeOfKind`?

**Comment by Arnavion** [comment]
I wonder why `Guid` itself is not allowed to be in the signature still? That is, why does `map1` still need to be indexed by a `string` key instead of `Guid` ?

**Pull request merged**
