### PR TITLE
Use binding pattern for type inference result `{}`

### LINKED ISSUE #7679: Inline callback destructuring does not work with generics
**TypeScript Version:** 

1.8.0

**Code**

```ts
function transform<T>(func: (stuff: T) => any) {
	return null;
}

let f = ({a}) => 'foo';
transform(f); // success 
transform(({a}) => 'bar'); // error
```

**Expected behavior:**
Both cases should inference `T` as `{ a: any }`. 

**Actual behavior:** 
If `func` is defined as a variable, it works fine. But if it is inlined, it doesn't work. 

Might be a duplicate of #1729, but this use case has no overload.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #7679.

The binding pattern provides additional information when the contextual type is not found and would otherwise fix a type parameter to `{}`. I'm not sure this fix is worth it. It's ad-hoc and doesn't provide too much value. But it does squash another difference between contextual typing vs separate declaration of arrows.

### CODE REVIEW

**Comment by sandersn** [comment]
@mhegazy, I think you were interested in how easy this would be.

**Comment by DanielRosenwasser** [comment]
What do you get if you have something like

```ts
declare function trans<T>(f: (x: T) => string): number;
trans(({a, b = 10}) => a);
```

**Comment by sandersn** [comment]
Good idea. `getTypeFromBindingPattern` is smart enough to infer `b?: number`. I added the test case.

**Comment by DanielRosenwasser** [comment]
:+1:

**Pull request merged**
