### PR TITLE
Self-referencing spread recursive loop

### LINKED ISSUE #11424: Weird interaction between default arguments and strict-null
**TypeScript Version:**  Version 2.0.5

**Code**

(with `--strictNullChecks` on)

``` ts
function x(y = 'a', z: number) {}
function x1(y: string, z: number) {}

// Construct error messages to reveal the type of these functions:
let test1: void = x;
let test2: void = x1;
// They have the same type:
// ERROR: Type '(y: string, z: number) => void' is not assignable to type 'void'.
// ERROR: Type '(y: string, z: number) => void' is not assignable to type 'void'.

// However, they have different observable behaviors:
x(undefined, 1);  // OK
x1(undefined, 1);  // ERROR
// ERROR: Argument of type 'undefined' is not assignable to parameter of type 'string'.
```

Note that the second parameter (`z`) is necessary to trigger this behavior; if you drop `z` from this example, then the first param `x` has a `?` as you'd expect.

(So it's even possible this is just a bug in how the function type is printed...?)

### LINKED ISSUE #12735: RangeError: Maximum call stack size exceeded in TS 2.1.4
**TypeScript Version:**  2.1.4

The project used to compile without any issues on TS 2.0, but it fails after upgrading to TS 2.1.4 without changing any code. I would be happy to give access to the repo if it would help.

**Expected behavior:**
The code compiles without issues

**Actual behavior:**
RangeError: Maximum call stack size exceeded

```

ERROR in ./src/store/reducers/workspace/analysis/index.ts
Module build failed: RangeError: Maximum call stack size exceeded
    at checkExpressionWorker (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37911:39)
    at checkExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37894:42)
    at checkExpressionCached (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37793:38)
    at checkSpreadExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:34449:39)
    at checkExpressionWorker (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37974:28)
    at checkExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37894:42)
    at checkExpressionForMutableLocation (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37825:24)
    at checkArrayLiteral (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:34484:32)
    at checkExpressionWorker (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37933:28)
    at checkExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37894:42)
    at getTypeOfExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37879:20)
    at getAssignedTypeOfBinaryExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32532:17)
    at getAssignedType (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32554:28)
    at getInitialOrAssignedType (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32605:17)
    at getTypeAtFlowAssignment (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32904:69)
    at getTypeAtFlowNode (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32839:32)
    at getTypeAtFlowLoopLabel (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:33050:36)
    at getTypeAtFlowNode (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32858:29)
    at getFlowTypeOfReference (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:32814:51)
    at checkIdentifier (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:33538:28)
    at checkExpressionWorker (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37914:28)
    at checkExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37894:42)
    at checkExpressionCached (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37793:38)
    at checkSpreadExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:34449:39)
    at checkExpressionWorker (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37974:28)
    at checkExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37894:42)
    at checkExpressionForMutableLocation (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37825:24)
    at checkArrayLiteral (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:34484:32)
    at checkExpressionWorker (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37933:28)
    at checkExpression (/home/f/Projects/WebCeph/node_modules/typescript/lib/typescript.js:37894:42)
 @ ./src/store/reducers/workspace/index.ts 13:0-113
 @ ./src/index.tsx
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #12735 

Use `checkExpression` in `checkSpreadExpression`, not `checkExpressionCached`. `checkExpressionCached` ignores ongoing control flow analysis, which causes the following loop to make the compiler recur infinitely:

```ts
// @noImplicitAny: true
let a = []
for (const x of []) {
    a = [...a]
}
```

An alternate fix would make `checkExpressionCached` not ignore control flow analysis in some situations, but that's a much more complicated fix, I think. @ahejlsberg, do you have an opinion on whether that or some other fix is feasible?

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Does `checkExpressionCached` document that it doesn't respect control flow analysis? Maybe it should be renamed so that other people don't incorrectly use it?

**Comment by sandersn** [comment]
`checkExpressionCached` also interacts with contextual typing. Both interactions are documented in the function's comments, but not in its name. I can't think of a good name anyway ... `checkExpressionCachedWithContextualTypingAndFreshControlFlow`?

**Comment by sandersn** [comment]
Oops, this fixes #12735. I got the bug number wrong initially.

**Comment by mhegazy** [comment]
@sandersn please port this change to release-2.1 as well.

**Comment by sandersn** [comment]
Ok, I ported it.

**Comment by mhegazy** [comment]
never mind. i have a port already up: https://github.com/Microsoft/TypeScript/pull/12864

**Comment by sandersn** [comment]
Sorry, I didn't see it until after I pushed . I wondered why I did t have merge conflicts with the new commits...

**Pull request merged**
