### PR TITLE
Sort @deprecated completions lower than others

### LINKED ISSUE #43796: Sort @deprecated completions lower than others
If we do #43710, the first thing you'll see every time you request completions on a string is a bunch of crossed-out properties. Ideally, we never would've shown these properties anyway, but we traditionally had to have them there because ES6.

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/43710#issuecomment-821708524_

__

`@deprecated` has its own NodeFlags entry right now, so you just have to use the rules from the checker to decide if the signature as a whole should be considered deprecated (basically, whether all the signature's declarations are deprecated). I don't know the sort order code but I assume it would be easy.

_Originally posted by @sandersn in https://github.com/microsoft/TypeScript/issues/43710#issuecomment-821708524_

### PR DESCRIPTION
**Pull request by hantatsang**
Fixes #43796

### CODE REVIEW

**Review by hantatsang — COMMENTED** [review]
Sorry, where can I write tests for the session?

I've tried `verify.completions` but it's not testing this method in `Session`.

**Comment by hantatsang** [comment]
There's "something" in VSCode that's still re-ordering the suggestions. Debugging https://github.com/microsoft/vscode/tree/main/extensions/typescript-language-features shows that the server response looks correct:



But the suggestions shown to the UI differs, `b` is not at bottom:

2021-04-25 21_39_47-deprecated ts - 43172-generator-destructuring-no-error-implicit-any-type - Code

**Comment by Kingwl** [comment]
May we add more behavior about the order of completion item? 

We have https://github.com/microsoft/TypeScript/pull/40079 sometime ago. 

It's seems very helpful for user experience.

BTW: No need to do in this PR.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
If the issue is committed (its still suggestion and not scheduled for milestone nor in backlog), this isn't right way to fix but instead to update sortText property with new enum value.

**Comment by DanielRosenwasser** [comment]
CC @uniqueiniquity @jessetrinity

**Comment by sheetalkamat** [comment]
There seems to be another PR #43880 doing this same thing

**Comment by hantatsang** [comment]
Ah, do we just create overriding PRs like that 😬

**Pull request closed without merging**
