### PR TITLE
Display write type for property accesses in write locations

### PR DESCRIPTION
**Pull request by Andarist**
closes https://github.com/microsoft/TypeScript/issues/53305

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Comment by jakebailey** [comment]
Generally speaking I think I probably need to have @RyanCavanaugh / @DanielRosenwasser give the resulting setup a once over to make sure it lines up with their mental models; I think it matches Ryan's comment in the linked issue, but I'm also a little unsure that I like the end result either.

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by jakebailey** [comment]
Just going to do a quick close/open since this is 151 commits behind main.

**Comment by karlhorky** [comment]
Thanks for the PR, review and merge @Andarist @DanielRosenwasser @jakebailey 🙌

**Pull request merged**
