### PR TITLE
feat(36048): Apply uncalled function checks to ternaries

### LINKED ISSUE #36048: Apply uncalled function checks to ternaries
## Search Terms

ts2774 ternary condition error function called uncalled

## Suggestion

TS2774 (implemented in https://github.com/microsoft/TypeScript/pull/32802), i.e. the ```"This condition will always return true since the function is always defined. Did you mean to call it instead?"``` error, provides a helpful hint for developers referencing a function in an if statement without calling it. However, the same check doesn't apply to ternaries, which is missing an opportunity to save some debug time and counterintuitive for devs who know about TS2774. I propose reusing TS2774 for developers who forget to call a function in a ternary.

## Examples

Now:

```ts
const isString = (value: unknown) => typeof value === "string"

// Error (TS2774)
if (isString) {
}
// No error
isString ? true : false
```
If this suggestion is adopted:

```ts
const isString = (value: unknown) => typeof value === "string"

// Error (TS2774)
if (isString) {
}
// Error(TS2774)
isString ? true : false
```

## Checklist

My suggestion meets these guidelines:

* [✔️] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [✔️] This wouldn't change the runtime behavior of existing JavaScript code
* [✔️] This could be implemented without emitting different JS based on the types of the expressions
* [✔️] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [✔️] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #36048

### CODE REVIEW

**Comment by sandersn** [comment]
@weswigham and @DanielRosenwasser are probably the best reviewers for this.

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by sandersn** [comment]
With 3.8 leaving beta at end of week, let's hold this until 3.9.

**Comment by a-tarasyuk** [comment]
The following lines cause the error 

https://github.com/microsoft/TypeScript/blob/fa3173f8f6443307739fc7c41f2bdd680f56a844/src/server/project.ts#L1382


https://github.com/microsoft/TypeScript/blob/fa3173f8f6443307739fc7c41f2bdd680f56a844/src/server/project.ts#L1312


Is it the right condition in this case?

cc @sandersn @DanielRosenwasser @weswigham

**Comment by sandersn** [comment]
Yes, those errors are correct, and they should be fixed before merging this PR. I asked @uniqueiniquity to investigate.

**Comment by sandersn** [comment]
Fix is https://github.com/microsoft/TypeScript/pull/36885, thanks @uniqueiniquity for figuring it out.

**Comment by a-tarasyuk** [comment]
@sandersn Oke, I'll wait to merge PR #36885.

**Comment by sandersn** [comment]
OK, @a-tarasyuk can you merge from master and I'll re-run the user tests to make sure they're still good.

**Comment by sandersn** [comment]
@typescript-bot test this
@typescript-bot user test this

**Comment by sandersn** [comment]
user and RWC tests look clean

**Pull request merged**
