### PR TITLE
Add es2020 transformation

### LINKED ISSUE #35509: Support nullish coalescing for target: es2020
## Search Terms

es2020, nullish

## Suggestion

Nullish Coalescing [just hit Stage 4](https://github.com/tc39/proposals/commit/6020b6f383152f92a491f9e2cc365cf6e2ef17d5), time to support it for es2020 🎉

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### LINKED ISSUE #35510: Support optional chaining for target: es2020
## Search Terms

es2020, chaining

## Suggestion

Optional Chaining [just hit Stage 4](https://github.com/tc39/proposals/commit/34c4f061bc4d1ca143621aaec78fa7f8585241a7), time to support it for es2020 🎉

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #35509 , fixes #35510

### CODE REVIEW

**Comment by Kingwl** [comment]
and https://github.com/microsoft/TypeScript/pull/34903

**Comment by saschanaz** [comment]
>and #34903

Probably #33893?

**Comment by DanielRosenwasser** [comment]
I merged in from `master` to this branch - only conflict was the new `ContainsAwait` flag due to top-level `await`.

**Comment by DanielRosenwasser** [comment]
Thanks @saschanaz!

**Pull request merged**
