### PR TITLE
[For testing only]: Redirect node to bundler

### PR DESCRIPTION
**Pull request by andrewbranch**

### CODE REVIEW

**Comment by andrewbranch** [comment]
@typescript-bot run top200

**Comment by andrewbranch** [comment]
@typescript-bot run top 200 ?

**Comment by andrewbranch** [comment]
@typescript-bot run top 100

**Comment by andrewbranch** [comment]
@typescript-bot is this how I find out I’ve been fired?

**Comment by andrewbranch** [comment]
@typescript-bot test top100

**Comment by andrewbranch** [comment]
@typescript-bot test top 100

**Comment by DanielRosenwasser** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
Re: https://github.com/microsoft/TypeScript/pull/51973#issuecomment-1360108924

- Puppeteer: I guess JS now resolves first because `@types/ws` is no longer resolved before `ws`.
- TypeScript-Node-Starter: The same issue @andrewbranch described to me off GitHub with path mappings and `node_modules/*` coming before `types/*`: https://github.com/microsoft/TypeScript-Node-Starter/blob/1e15e8b4bf6136ee181a8d46ccda9d5b3ed4e479/tsconfig.json#L12C5-L16
- TypeScript-WeChat-Starter: `import = require` is disallowed in this mode.

**Comment by andrewbranch** [comment]
I haven’t looked at Puppeteer yet, but I’m looking at `react-bootstrap` and it turns out there’s a pretty significant bug that has always existed in `node16` and `nodenext` that `bundler` inherited around nested package.jsons. I’m trying to clean it up, and I think `typesVersions` has been bizarrely busted forever.

**Comment by andrewbranch** [comment]
> The fix is to also specify `@types/ws` in the respective package instead of relying on the monorepo root.

That doesn’t sound intentional. I intentionally backed out some changes that would have required this when I realized that it negatively impacts monorepos.

**Comment by andrewbranch** [comment]
Brought in #51995

**Comment by andrewbranch** [comment]
@typescript-bot test top 100

**Comment by andrewbranch** [comment]
@typescript-bot test top100

**Comment by andrewbranch** [comment]
@typescript-bot test top100

**Comment by andrewbranch** [comment]
@typescript-bot test top100

**Pull request closed without merging**
