### PR TITLE
Check combined node flag for deprecated

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes a part of #39374

Related: https://github.com/microsoft/TypeScript/pull/39323

### CODE REVIEW

**Comment by Kingwl** [comment]
@typescript-bot perf test.

**Comment by Kingwl** [comment]
What's up

**Comment by sandersn** [comment]
I'm not sure? Maybe because I mentioned it in #39323?

**Comment by sandersn** [comment]
oh. nope. it's because it's based on the branch node-based-deprecated-checks. It needs to be rebased from master if that's possible or else cherry-picked over there.

**Comment by Kingwl** [comment]
Never mind. I have another PR.

**Pull request closed without merging**
