### PR TITLE
Remove comments from tsconfig.json generated by 'tsc --init'

### LINKED ISSUE #46150: tsc --init-basic
# Suggestion

As a professional TypeScript developer, I start new TS projects all the time. I use `tsc --init` sometimes, but more often than not I copy `tsconfig.json` files from other projects because I find the `tsconfig.json` file that is generated to be horribly spammy.

Having a `tsc --init` command *is* valuable to me, because quite often I want to bootstrap a project quickly, but the comments get in my way, as they make it harder to read what the actual config of a project is, and generally look really messy. If I ever run `tsc --init` the first thing I do is strip out these comments.

I'd really appreciate a `tsc --init-basic` (or something like it) that provides the same basic configuration set but without any comments.

* Note; I suspect this would be super simple to implement, and I'm looking for opportunities to start contributing, so if anyone can point me towards the appropriate area in the codebase, I'd be happy to submit this change myself.

## 🔍 Search Terms

tsconfig comments init 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### PR DESCRIPTION
**Pull request by System233**
Fixes #46150 
Fix the issue where the `tsconfig.json` generated by `tsc --init` is unreadable for humans.

## A few questions for all before discussion.

- Have you actually used `tsc --init` before?
- How many of your projects have `tsconfig.json` files with a significant number of comments?
- In the projects you have encountered, how many of them had `tsconfig.json` files with a significant number of comments?
- What screen resolution do you use, or how many pages do you need to scroll through to view the entire `tsconfig.json`?
- How much time do you spend searching for the actual effective configuration among a large number of comments in your `tsconfig.json`?
- If your project's tsconfig.json is heavily commented, do you remove the comments?
- If you dislike comments, how much time and effort do you spend removing them?
- If you like the comments generated by `tsc --init`, how likely is it for the comments' indentation to become disordered when you edit the `tsconfig.json` configuration?
- Does your development environment support formatting `tsconfig.json` and ensure that comment alignment remains undisturbed?
- When formatting `tsconfig.json`, can you tolerate a misaligned configuration file if the comments' alignment becomes disrupted?

## Before
```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig to read more about this file */

    /* Projects */
    // "incremental": true,                              /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
    // "composite": true,                                /* Enable constraints that allow a TypeScript project to be used with project references. */
    // "tsBuildInfoFile": "./.tsbuildinfo",              /* Specify the path to .tsbuildinfo incremental compilation file. */
    // "disableSourceOfProjectReferenceRedirect": true,  /* Disable preferring source files instead of declaration files when referencing composite projects. */
    // "disableSolutionSearching": true,                 /* Opt a project out of multi-project reference checking when editing. */
    // "disableReferencedProjectLoad": true,             /* Reduce the number of projects loaded automatically by TypeScript. */

    /* Language and Environment */
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    // "lib": [],                                        /* Specify a set of bundled library declaration files that describe the target runtime environment. */
    // "jsx": "preserve",                                /* Specify what JSX code is generated. */
    // "experimentalDecorators": true,                   /* Enable experimental support for legacy experimental decorators. */
    // "emitDecoratorMetadata": true,                    /* Emit design-type metadata for decorated declarations in source files. */
    // "jsxFactory": "",                                 /* Specify the JSX factory function used when targeting React JSX emit, e.g. 'React.createElement' or 'h'. */
    // "jsxFragmentFactory": "",                         /* Specify the JSX Fragment reference used for fragments when targeting React JSX emit e.g. 'React.Fragment' or 'Fragment'. */
    // "jsxImportSource": "",                            /* Specify module specifier used to import the JSX factory functions when using 'jsx: react-jsx*'. */
    // "reactNamespace": "",                             /* Specify the object invoked for 'createElement'. This only applies when targeting 'react' JSX emit. */
    // "noLib": true,                                    /* Disable including any library files, including the default lib.d.ts. */
    // "useDefineForClassFields": true,                  /* Emit ECMAScript-standard-compliant class fields. */
    // "moduleDetection": "auto",                        /* Control what method is used to detect module-format JS files. */

    /* Modules */
    "module": "commonjs",                                /* Specify what module code is generated. */
    // "rootDir": "./",                                  /* Specify the root folder within your source files. */
    // "moduleResolution": "node10",                     /* Specify how TypeScript looks up a file from a given module specifier. */
    // "baseUrl": "./",                                  /* Specify the base directory to resolve non-relative module names. */
    // "paths": {},                                      /* Specify a set of entries that re-map imports to additional lookup locations. */
    // "rootDirs": [],                                   /* Allow multiple folders to be treated as one when resolving modules. */
    // "typeRoots": [],                                  /* Specify multiple folders that act like './node_modules/@types'. */
    // "types": [],                                      /* Specify type package names to be included without being referenced in a source file. */
    // "allowUmdGlobalAccess": true,                     /* Allow accessing UMD globals from modules. */
    // "moduleSuffixes": [],                             /* List of file name suffixes to search when resolving a module. */
    // "allowImportingTsExtensions": true,               /* Allow imports to include TypeScript file extensions. Requires '--moduleResolution bundler' and either '--noEmit' or '--emitDeclarationOnly' to be set. */
    // "resolvePackageJsonExports": true,                /* Use the package.json 'exports' field when resolving package imports. */
    // "resolvePackageJsonImports": true,                /* Use the package.json 'imports' field when resolving imports. */
    // "customConditions": [],                           /* Conditions to set in addition to the resolver-specific defaults when resolving imports. */
    // "resolveJsonModule": true,                        /* Enable importing .json files. */
    // "allowArbitraryExtensions": true,                 /* Enable importing files with any extension, provided a declaration file is present. */
    // "noResolve": true,                                /* Disallow 'import's, 'require's or '<reference>'s from expanding the number of files TypeScript should add to a project. */

    /* JavaScript Support */
    // "allowJs": true,                                  /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get errors from these files. */
    // "checkJs": true,                                  /* Enable error reporting in type-checked JavaScript files. */
    // "maxNodeModuleJsDepth": 1,                        /* Specify the maximum folder depth used for checking JavaScript files from 'node_modules'. Only applicable with 'allowJs'. */

    /* Emit */
    // "declaration": true,                              /* Generate .d.ts files from TypeScript and JavaScript files in your project. */
    // "declarationMap": true,                           /* Create sourcemaps for d.ts files. */
    // "emitDeclarationOnly": true,                      /* Only output d.ts files and not JavaScript files. */
    // "sourceMap": true,                                /* Create source map files for emitted JavaScript files. */
    // "inlineSourceMap": true,                          /* Include sourcemap files inside the emitted JavaScript. */
    // "outFile": "./",                                  /* Specify a file that bundles all outputs into one JavaScript file. If 'declaration' is true, also designates a file that bundles all .d.ts output. */
    // "outDir": "./",                                   /* Specify an output folder for all emitted files. */
    // "removeComments": true,                           /* Disable emitting comments. */
    // "noEmit": true,                                   /* Disable emitting files from a compilation. */
    // "importHelpers": true,                            /* Allow importing helper functions from tslib once per project, instead of including them per-file. */
    // "importsNotUsedAsValues": "remove",               /* Specify emit/checking behavior for imports that are only used for types. */
    // "downlevelIteration": true,                       /* Emit more compliant, but verbose and less performant JavaScript for iteration. */
    // "sourceRoot": "",                                 /* Specify the root path for debuggers to find the reference source code. */
    // "mapRoot": "",                                    /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSources": true,                            /* Include source code in the sourcemaps inside the emitted JavaScript. */
    // "emitBOM": true,                                  /* Emit a UTF-8 Byte Order Mark (BOM) in the beginning of output files. */
    // "newLine": "crlf",                                /* Set the newline character for emitting files. */
    // "stripInternal": true,                            /* Disable emitting declarations that have '@internal' in their JSDoc comments. */
    // "noEmitHelpers": true,                            /* Disable generating custom helper functions like '__extends' in compiled output. */
    // "noEmitOnError": true,                            /* Disable emitting files if any type checking errors are reported. */
    // "preserveConstEnums": true,                       /* Disable erasing 'const enum' declarations in generated code. */
    // "declarationDir": "./",                           /* Specify the output directory for generated declaration files. */
    // "preserveValueImports": true,                     /* Preserve unused imported values in the JavaScript output that would otherwise be removed. */

    /* Interop Constraints */
    // "isolatedModules": true,                          /* Ensure that each file can be safely transpiled without relying on other imports. */
    // "verbatimModuleSyntax": true,                     /* Do not transform or elide any imports or exports not marked as type-only, ensuring they are written in the output file's format based on the 'module' setting. */
    // "allowSyntheticDefaultImports": true,             /* Allow 'import x from y' when a module doesn't have a default export. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    // "preserveSymlinks": true,                         /* Disable resolving symlinks to their realpath. This correlates to the same flag in node. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */

    /* Type Checking */
    "strict": true,                                      /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                            /* Enable error reporting for expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,                         /* When type checking, take into account 'null' and 'undefined'. */
    // "strictFunctionTypes": true,                      /* When assigning functions, check to ensure parameters and the return values are subtype-compatible. */
    // "strictBindCallApply": true,                      /* Check that the arguments for 'bind', 'call', and 'apply' methods match the original function. */
    // "strictPropertyInitialization": true,             /* Check for class properties that are declared but not set in the constructor. */
    // "noImplicitThis": true,                           /* Enable error reporting when 'this' is given the type 'any'. */
    // "useUnknownInCatchVariables": true,               /* Default catch clause variables as 'unknown' instead of 'any'. */
    // "alwaysStrict": true,                             /* Ensure 'use strict' is always emitted. */
    // "noUnusedLocals": true,                           /* Enable error reporting when local variables aren't read. */
    // "noUnusedParameters": true,                       /* Raise an error when a function parameter isn't read. */
    // "exactOptionalPropertyTypes": true,               /* Interpret optional property types as written, rather than adding 'undefined'. */
    // "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
    // "noFallthroughCasesInSwitch": true,               /* Enable error reporting for fallthrough cases in switch statements. */
    // "noUncheckedIndexedAccess": true,                 /* Add 'undefined' to a type when accessed using an index. */
    // "noImplicitOverride": true,                       /* Ensure overriding members in derived classes are marked with an override modifier. */
    // "noPropertyAccessFromIndexSignature": true,       /* Enforces using indexed accessors for keys declared using an indexed type. */
    // "allowUnusedLabels": true,                        /* Disable error reporting for unused labels. */
    // "allowUnreachableCode": true,                     /* Disable error reporting for unreachable code. */

    /* Completeness */
    // "skipDefaultLibCheck": true,                      /* Skip type checking .d.ts files that are included with TypeScript. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```

## After
```jsonc
/* Visit https://aka.ms/tsconfig to read more about this file */
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2016",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true
  }
}
```

### CODE REVIEW

**Comment by System233** [comment]
@microsoft-github-policy-service agree

**Comment by orta** [comment]
I don't think this should happen, I think it's pretty valuable to have a reference when you use `tsc --init`

**Comment by System233** [comment]
> I don't think this should happen, I think it's pretty valuable to have a reference when you use `tsc --init`

Yes, it's very valuable, but only for the first time.

The `tsconfig.json` is not an API reference. Maybe you can try creating a project with `tsc --init` every day. I believe you will spend a lot of time deleting comments because a large number of comments seriously affect the readability of the actual configuration of the project. 
The best documentation is code, not comments.
If you do need documentation, as mentioned in the comments, please visit https://aka.ms/tsconfig.

**Comment by System233** [comment]
Let’s see if there are a lot of comments in various configuration files in popular repositories
## microsoft/VSCode
[tsconfig.json](https://github.com/microsoft/vscode/blob/4dce9d5ad442f96e805a8e1542cc8bd54998417f/src/tsconfig.json#L1-L34)
[tsconfig.base.json](https://github.com/microsoft/vscode/blob/main/src/tsconfig.base.json)
[tsconfig.monaco.json](https://github.com/microsoft/vscode/blob/main/src/tsconfig.monaco.json)
[tsconfig.tsec.json](https://github.com/microsoft/vscode/blob/main/src/tsconfig.tsec.json)
[tsconfig.vscode-dts.json](https://github.com/microsoft/vscode/blob/main/src/tsconfig.vscode-dts.json)

## microsoft/fluentui
[tsconfig.json](https://github.com/microsoft/fluentui/blob/3b8a86445f185e19ec9b0fc4ee4943a0867bab23/tsconfig.json#L1-L8)
[tsconfig.base.all.json](https://github.com/microsoft/fluentui/blob/3b8a86445f185e19ec9b0fc4ee4943a0867bab23/tsconfig.base.all.json)
[tsconfig.base.json](https://github.com/microsoft/fluentui/blob/3b8a86445f185e19ec9b0fc4ee4943a0867bab23/tsconfig.base.json)
[tsconfig.base.v0.json](https://github.com/microsoft/fluentui/blob/3b8a86445f185e19ec9b0fc4ee4943a0867bab23/tsconfig.base.v0.json)
[tsconfig.base.v8.json](https://github.com/microsoft/fluentui/blob/3b8a86445f185e19ec9b0fc4ee4943a0867bab23/tsconfig.base.v8.json)

## microsoft/playwright
[tsconfig.json](https://github.com/microsoft/playwright/blob/8595a6c25fa68d6978c9e35d436bdbe6b5d393ec/tsconfig.json)

## DefinitelyTyped
[tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/tsconfig.json)
[types/*/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types)
- [types/webpack/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webpack/tsconfig.json)
- [types/react/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/tsconfig.json)
- [types/node/tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/tsconfig.json)

## Nest
[tsconfig.json](https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/tsconfig.json#L1-L39)
[tsconfig.spec.json](https://github.com/nestjs/nest/blob/ecdd86f688462ae717a621ee2c7be7b7ef53797d/tsconfig.spec.json#L1-L39)

## Vue
[tsconfig.json](https://github.com/vuejs/vue/blob/49b6bd4264c25ea41408f066a1835f38bf6fe9f1/tsconfig.json#L1-L38)
[types/tsconfig.json](https://github.com/vuejs/vue/blob/49b6bd4264c25ea41408f066a1835f38bf6fe9f1/types/tsconfig.json)

## angular/angular

[tsconfig.json](https://github.com/angular/angular/blob/c2b1a242e8db0ef8e03f7ee85ffa1f82562fd735/tsconfig.json)
[*/tsconfig.json](https://github.com/angular/angular/blob/c2b1a242e8db0ef8e03f7ee85ffa1f82562fd735)
- [aio/tsconfig.json](https://github.com/angular/angular/blob/c2b1a242e8db0ef8e03f7ee85ffa1f82562fd735/aio/tsconfig.json#L4)
- [aio/tsconfig.app.json](https://github.com/angular/angular/blob/c2b1a242e8db0ef8e03f7ee85ffa1f82562fd735/aio/tsconfig.app.json)
- [aio/tsconfig.spec.json](https://github.com/angular/angular/blob/c2b1a242e8db0ef8e03f7ee85ffa1f82562fd735/aio/tsconfig.spec.json)
- [devtools/tsconfig.json](https://github.com/angular/angular/blob/c2b1a242e8db0ef8e03f7ee85ffa1f82562fd735/devtools/tsconfig.spec.json)

There are too many cases to support this PR, even Microsoft itself doesn't like writing a lot of comments in `tsconfig.json` 👍 .

**Comment by System233** [comment]
Next, let's check if there are a significant number of comments in the template configuration file located in [tsconfig/bases](https://github.com/tsconfig/bases).
## tsconfig/bases
- [bases/bun.json](https://github.com/tsconfig/bases/blob/main/bases/bun.json)
- [bases/bun.json](https://github.com/tsconfig/bases/blob/main/bases/bun.json)
- [bases/create-react-app.json](https://github.com/tsconfig/bases/blob/main/bases/create-react-app.json)
- [bases/create-react-app.json](https://github.com/tsconfig/bases/blob/main/bases/create-react-app.json)
- [bases/cypress.json](https://github.com/tsconfig/bases/blob/main/bases/cypress.json)
- [bases/cypress.json](https://github.com/tsconfig/bases/blob/main/bases/cypress.json)
- [bases/deno.json](https://github.com/tsconfig/bases/blob/main/bases/deno.json)
- [bases/deno.json](https://github.com/tsconfig/bases/blob/main/bases/deno.json)
- [bases/docusaurus.json](https://github.com/tsconfig/bases/blob/main/bases/docusaurus.json)
- [bases/docusaurus.json](https://github.com/tsconfig/bases/blob/main/bases/docusaurus.json)
- [bases/ember.json](https://github.com/tsconfig/bases/blob/main/bases/ember.json)
- [bases/ember.json](https://github.com/tsconfig/bases/blob/main/bases/ember.json)
- [bases/next.json](https://github.com/tsconfig/bases/blob/main/bases/next.json)
- [bases/next.json](https://github.com/tsconfig/bases/blob/main/bases/next.json)
- [bases/node-lts.json](https://github.com/tsconfig/bases/blob/main/bases/node-lts.json)
- [bases/node-lts.json](https://github.com/tsconfig/bases/blob/main/bases/node-lts.json)
- [bases/node10.json](https://github.com/tsconfig/bases/blob/main/bases/node10.json)
- [bases/node10.json](https://github.com/tsconfig/bases/blob/main/bases/node10.json)
- [bases/node12.json](https://github.com/tsconfig/bases/blob/main/bases/node12.json)
- [bases/node12.json](https://github.com/tsconfig/bases/blob/main/bases/node12.json)
- [bases/node14.json](https://github.com/tsconfig/bases/blob/main/bases/node14.json)
- [bases/node14.json](https://github.com/tsconfig/bases/blob/main/bases/node14.json)
- [bases/node16.json](https://github.com/tsconfig/bases/blob/main/bases/node16.json)
- [bases/node16.json](https://github.com/tsconfig/bases/blob/main/bases/node16.json)
- [bases/node17.json](https://github.com/tsconfig/bases/blob/main/bases/node17.json)
- [bases/node17.json](https://github.com/tsconfig/bases/blob/main/bases/node17.json)
- [bases/node18.json](https://github.com/tsconfig/bases/blob/main/bases/node18.json)
- [bases/node18.json](https://github.com/tsconfig/bases/blob/main/bases/node18.json)
- [bases/node19.json](https://github.com/tsconfig/bases/blob/main/bases/node19.json)
- [bases/node19.json](https://github.com/tsconfig/bases/blob/main/bases/node19.json)
- [bases/node20.json](https://github.com/tsconfig/bases/blob/main/bases/node20.json)
- [bases/node20.json](https://github.com/tsconfig/bases/blob/main/bases/node20.json)
- [bases/nuxt.json](https://github.com/tsconfig/bases/blob/main/bases/nuxt.json)
- [bases/nuxt.json](https://github.com/tsconfig/bases/blob/main/bases/nuxt.json)
- [bases/react-native.json](https://github.com/tsconfig/bases/blob/main/bases/react-native.json)
- [bases/react-native.json](https://github.com/tsconfig/bases/blob/main/bases/react-native.json)
- [bases/recommended.json](https://github.com/tsconfig/bases/blob/main/bases/recommended.json)
- [bases/recommended.json](https://github.com/tsconfig/bases/blob/main/bases/recommended.json)
- [bases/remix.json](https://github.com/tsconfig/bases/blob/main/bases/remix.json)
- [bases/remix.json](https://github.com/tsconfig/bases/blob/main/bases/remix.json)
- [bases/strictest.json](https://github.com/tsconfig/bases/blob/main/bases/strictest.json)
- [bases/strictest.json](https://github.com/tsconfig/bases/blob/main/bases/strictest.json)
- [bases/svelte.json](https://github.com/tsconfig/bases/blob/main/bases/svelte.json)
- [bases/svelte.json](https://github.com/tsconfig/bases/blob/main/bases/svelte.json)
- [bases/taro.json](https://github.com/tsconfig/bases/blob/main/bases/taro.json)
- [bases/taro.json](https://github.com/tsconfig/bases/blob/main/bases/taro.json)
- [bases/vite-react.json](https://github.com/tsconfig/bases/blob/main/bases/vite-react.json)
- [bases/vite-react.json](https://github.com/tsconfig/bases/blob/main/bases/vite-react.json)

It can be seen that an excellent `tsconfig.json` should be clean and tidy, without an abundance of unnecessary comments. However, if comments are considered valuable, they should be added to the [tsconfig/bases](https://github.com/tsconfig/bases) template configuration. Please consider adding comments there rather than removing them 😭.

**Comment by RyanCavanaugh** [comment]
Pull requests are for implementing approved features. Please discuss whether or not you think the feature is a good idea in the feature issue.

**Pull request closed without merging**
