### PR TITLE
Housekeeping formatting rules 

### PR DESCRIPTION
**Pull request by SaschaNaz**
(Separated from #4609)

- [x] Merge `SpaceAfterAwaitKeyword` and `SpaceAfterTypeKeyword` into  `SpaceAfterCertainKeywords` and  `SpaceAfterCertainTypeScriptKeywords` respectively.
- [x] Remove needless `NoSpace` rules
- [x] Remove type operation rules and instead add their types to `IsBinaryOpContext`

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by mhegazy** [comment]
We need a formatting test for intersection and union though.

**Comment by SaschaNaz** [comment]
@mhegazy We have https://github.com/Microsoft/TypeScript/blob/master/tests/cases/fourslash/formatTypeOperation.ts currently.

**Comment by mhegazy** [comment]
Ok then. never mind.

**Pull request merged**
