### PR TITLE
fix #33427

### LINKED ISSUE #33427: Union index signature parameter type has unclear / incorrect error
**TypeScript Version:**  3.7.0-dev.20190913

**Search Terms:**

* index signature parameter type 
* index signature union 

**Code**

```ts
interface A {
  [id : string | number] : boolean;
};
```

**Expected behavior:**

Either the following error message is displayed, or the error message makes it clear that **only one of** `string` xor `number` is permissible as an index signature parameter type. 

https://github.com/microsoft/TypeScript/blob/038d95144d8b93c2799d1732181c89c3d84362d5/src/compiler/diagnosticMessages.json#L962-L965

**Actual behavior:**

```
error TS1023: An index signature parameter type must be 'string' or 'number'.
```
To me, the expression `string | number` is equivalent to the phrase "'string' or 'number'", but the phrasing is not precise.

Either the wrong error is being thrown, or this TS1023 should be clarified to say "...must be **one of** 'string' or 'number'." or "...must be **either** 'string' or 'number'."

https://github.com/microsoft/TypeScript/blob/038d95144d8b93c2799d1732181c89c3d84362d5/src/compiler/diagnosticMessages.json#L74-L77

**Playground Link:** 
(error not shown in Playground)

**Related Issues:** 

https://github.com/microsoft/TypeScript/issues/2611
https://github.com/microsoft/TypeScript/issues/2049
https://github.com/microsoft/TypeScript/issues/8711 
https://github.com/microsoft/TypeScript/issues/18759

I will fix this in a PR if you tell me whether TS1023 is the right error with a fixed message, or if TS1337 should be thrown instead of TS1023.

### PR DESCRIPTION
**Pull request by TroyTae**
Fixes #33427

### CODE REVIEW

**Comment by TroyTae** [comment]
@typescript-bot 
I remove commit with force-push!

**Comment by TroyTae** [comment]
@catb0t
Can you check if it's fixed as you intended??
@DanielRosenwasser 
I wanna get some feedback!

**Comment by sploders101** [comment]
I don't speak for the typescript staff, but I still think the error is too vague.
I read "either string or number", and still think `string | number`, because that type can be either a string, or a number.
As suggested in #33427, I would like to see a suggestion as to what the dev is trying to do, like a `Record`.
I'm not sure how using a union as a key would result in a mapped type, but maybe somebody can clear that up, and we could potentially have that suggestion there too.

**Comment by TroyTae** [comment]
Hmmm I think two messages mean:

either string | number -> you need to
use Record -> recommend you instead of union

How about thought of others?
Feel free to leave message :)

**Comment by TroyTae** [comment]
@DanielRosenwasser
Can you check this please?
New PRs are stacked and this PR came second page :)

**Comment by TroyTae** [comment]
@DanielRosenwasser
Can you check this please?

@ahejlsberg @rictic sheetalkamat @weswigham
If he is busy now.
Can other maintainers confirm this?
Thank you :)

**Comment by DanielRosenwasser** [comment]
Thoughts @fatcerberus?

**Comment by fatcerberus** [comment]
I agree with @sploders101 that the addition of "either" does next to nothing to improve clarity compared to the current message.  My preference was always for the message that was suggested under Expected Behavior:

> An index signature parameter type cannot be a union type. Consider using a mapped object type instead.

"Mapped object type" can be replaced with whatever is the name of the construct `Record` is defined in terms of.  Alternatively, just suggest using `Record` since it's built in.

**Comment by TroyTae** [comment]
@fatcerberus 
No worries :)
I didn't change only message.
I fixed the condition like this:
```
if (type.flags & TypeFlags.Union && allTypesAssignableToKind(type, TypeFlags.StringOrNumberLiteral, /*strict*/ true))
```

So we can see the error log that shows what you want :)
image

**Pull request merged**
