### PR TITLE
This parameters in lib

### LINKED ISSUE #9654: String methods should have `this` parameters in `lib.d.ts`
``` ts
// @noImplicitThis: true
String.prototype.indexOf = function(substr, start) {
    this./**/
}
```

Expected: Method suggestions. No error.
Actual: Nothing. `this: any` error.

Other types in lib.d.ts should probably also have `this` added too.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #9654

Adds parameters for all the primitives, not just String.

Unfortunately, 376 additions, 373 deletions is too many for github to show. So you can't actually see the changes themselves in the web UI.

### CODE REVIEW

**Comment by sandersn** [comment]
Looks like Codeflow will work for the Microsoft-internal folks. You just have to install the Codeflow chrome extension.

**Comment by weswigham** [comment]
@sandersn Shouldn't all the subclassable interfaces (ie, `Array<T>`) have `this` function types of `this: this`? Array is already generic, so there's minimal opportunity cost to it.

**Comment by sandersn** [comment]
Unfortunately, switching to `this: this` exposes a bug with assignability checking for (I believe) types that have lots of methods with `this: this`. I don't think it is specific to `Array` necessarily.

I'll open an issue on it when I get a minimal repro. Until then I'll leave the PR the way it is.

**Comment by sandersn** [comment]
I opened #9707, but I didn't get the bug much smaller.

**Comment by mhegazy** [comment]
@sandersn i would say let's close this one until we figure out  #9707. i do agree we need to fix that one.

**Comment by sandersn** [comment]
#9707 is actually fixed. I just didn't have time to come back to this PR.

**Comment by mhegazy** [comment]
Ah. i actually was thinking of https://github.com/Microsoft/TypeScript/issues/10288, sorry about that.

but now that i am looking at the right bug, I assume no harm comes from this change.

**Comment by sandersn** [comment]
Unfortunately, it's not done. @weswigham pointed out that `Array<T>` should have `this: this`, so I still need to do that before it's finished.

**Comment by sandersn** [comment]
Actually, I think I misunderstood. Yes, even without fixing #10288, adding more `this` annotations is useful. (It would be more useful if we could fix #10288.)

**Comment by sandersn** [comment]
@mhegazy this change is finished now that I added `this: this` for Array and Object. There's no performance impact, as measured by running the Monaco and TFS performance baselines.

**Comment by mhegazy** [comment]
Based on conversation with @sandersn, this change has little value, but introduces a new set of complexities to the library and checking the library. value does not offset the cost.

**Pull request closed without merging**
