### PR TITLE
Fix 10505: Fix typo of missing node.kind

### LINKED ISSUE #10505: Typo in function emitExternalImportDeclaration?
const isNakedImport = SyntaxKind.ImportDeclaration && !(<ImportDeclaration>node).importClause;

https://github.com/Microsoft/TypeScript/blob/ddb5a00410d695d35b55c5482876a16f7c696c4b/src/compiler/emitter.ts#L6590

Possibly missing `node.kind ===` before `SyntaxKind.ImportDeclaration` ?

Noticed it when running `uglifyjs lib/tsc.js -c`
```
WARN: Condition left of && always true [lib/tsc.js:34409,48]
```
```
 34409	                            var isNakedImport = 230 && !node.importClause;
```

### PR DESCRIPTION
**Pull request by yuit**
Fixes #10505

### CODE REVIEW

**Comment by sandersn** [comment]
:+1: 

are we allowed to use 'naked' in our variable names? I've worked on code bases before where we had to change any names containing strings on a list of blocked words.

**Comment by yuit** [comment]
hmmm the conversation on block words has been brought up before. I don't know what is the conclusion there though @DanielRosenwasser   @RyanCavanaugh  @mhegazy  would it matter?

**Comment by RyanCavanaugh** [comment]
We used to have to run Policheck, but I don't think anyone's done that in years. It would probably be good to run that tool once just to make sure nothing crazy has snuck in; I imagine this one would have been flagged.

**Comment by mhegazy** [comment]
> We used to have to run Policheck, but I don't think anyone's done that in years. It would probably be good to run that tool once just to make sure nothing crazy has snuck in; I imagine this one would have been flagged.

I still do this once every release :) usually it flags `foo`, `ns`, `naked`, ..., and my name :D

**Pull request merged**
