### PR TITLE
Remove diagnostic dependent output in `structuredTypeRelatedTo`

### LINKED ISSUE #29393: Regression: Unrelated line causes complex type check error to disappear
**TypeScript Version:**  No issue in 3.0.3, broken in both 3.2.2 and 3.3.0-dev.20190112 (using tsconfig from `tsc --init`)

**Search Terms:** unrelated, nondeterministic, mapped type, generic

**Code**

I'm sorry, I couldn't manage to reduce this further since it disappears when the code is too simple (probably some checking depth limitation?)

```ts
// when I replace this import by just inlining the corresponding types,
// the error disappears
import { TypeOf, Type } from "io-ts";

type ToB<S extends any> = { [k in keyof S]: TypeOf<S[k]> };
type ToA<S> = { [k in keyof S]: Type<S[k]> };

type NeededInfo<MyNamespaceSchema = {}> = {
  ASchema: ToA<MyNamespaceSchema>;
};

export const ASchema = {
  initialize: null as any
};

export type MyInfo = NeededInfo<ToB<typeof ASchema>>;

const tmp1: MyInfo = null!;
function tmp2<N extends NeededInfo>(n: N) {}
// tmp2(tmp1); // uncommenting this line removes a type error from a completely unrelated line ??

class Server<X extends NeededInfo> {}
export class MyServer extends Server<MyInfo> {} // not assignable error at `MyInfo`
```

**Expected behavior:** No type error regardless of whether the line `//tmp2(tmp1)` is commented or not.

**Actual behavior:**

When that line is commented out, I get a type error in the `export class` line, which is completely unrelated:

```
[ts]
Type 'NeededInfo<ToB<{ initialize: any; }>>' does not satisfy the constraint 'NeededInfo<{}>'.
  Types of property 'ASchema' are incompatible.
    Type 'ToA<ToB<{ initialize: any; }>>' is not assignable to type 'ToA<{}>'.
      Type '{}' is not assignable to type 'ToB<{ initialize: any; }>'. [2344]
```

**Playground Link:** Impossible because it stops happening when Type and TypeOf are inlined.

I know the above code looks dumb, but trust me this is causing weird breakage in a large code base.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #29393

Also unified the special-case (void covariant param) handling between aliases and interfaces, and removed the early bail on no `strictFunctionTypes` from `getVariances` so we can still measure independent type parameters when `strictFunctionTypes` isn't on (as now that the variance result is always consistently reported, this flaw was pretty obvious).

### CODE REVIEW

**Comment by phiresky** [comment]
Just tried this, and it does not seem to fix my issue (#29393) (same error as before)

here's a clonable example: https://gist.github.com/phiresky/4584e5d36d5fbae37e6afb07e3076536

**Comment by RyanCavanaugh** [comment]
@weswigham please check if this fixes #29901 as well

**Comment by weswigham** [comment]
#29901 seems to be an unrelated issue to do with our subtype relationship.

**Comment by weswigham** [comment]
> Just tried this, and it does not seem to fix my issue

By that I assume you mean "now no matter what I try there's a type error"? #29698 tracks altering the change that makes that `ToA` comparison an error. I was focused on making the result consistent here (since adding an "unrelated" line of code should never change the error result of another line). 😄

**Comment by phiresky** [comment]
> @phiresky
> 
> > Just tried this, and it does not seem to fix my issue
> 
> By that I assume you mean "now no matter what I try there's a type error"? #29698 tracks altering the change that makes that `ToA` comparison an error. I was focused on making the result consistent here (since adding an "unrelated" line of code should never change the error result of another line).

Not that that would be good for me either (since then I'm still stuck on 3.0), but no I actually mean that with this branch, it's still exactly the same as before, it shows an error only whencommenting that other line.

**Comment by weswigham** [comment]
@phiresky I'm not seeing it?:
deletecomment

You sure you have the `typescript.tsdk` workspace setting set up correctly to point at the new version you build off this PR?

**Comment by phiresky** [comment]
I actually tried it from the command line not VSCode, just like I did the bisect

(git clone https://github.com/Microsoft/TypeScript; cd TypeScript; g fetch origin pull/29817/head:zz; git checkout zz; yarn; `gulp tsc`; cd ..; git clone https://gist.github.com/phiresky/4584e5d36d5fbae37e6afb07e3076536; cd 45*; `node ../TypeScript/lib/tsc.js`)

but i'm not 100% confident I did it correctly

**Comment by phiresky** [comment]
Nevermind, I used `../TypeScript/lib/tsc.js` instead of `../TypeScript/built/local/tsc.js` which I guess is a stable version of the compiler.

So regarding my actual issue, should I open a new one or is that maybe the same as https://github.com/Microsoft/TypeScript/issues/29698?

Here's my library that is broken by these changes btw: https://github.com/phiresky/typed-socket.io (errors in [this file](https://github.com/phiresky/typed-socket.io/blob/master/example/chat-with-runtime-checks/server.ts) in TS>3.0)

**Comment by weswigham** [comment]
Actually, the error is in some respects correct... `io-ts`'s `Type` type is _invariant_ in it's first argument - meaning `Type<A>` is never related to `Type<B>` (and vice-versa) if `A` !== `B`. This is the case because that type parameter is, used in both an argument position (`encode`) and an output position (`validate`) (also, once [this PR is in, it is used in _a type predicate_ (`is`)](https://github.com/Microsoft/TypeScript/pull/27686), which forces it to be invariant). This invariance is transferred to `T` in your `ToA` helper by the usage of `T` in `T[K]` in `Type<T[K]>`.

Long story short, a `Type<A>` and a `Type<B>` don't share the same relationship `A` and `B` have because of all the helper callbacks on `Type`, which, in turn, means a `ToA<A>` and a `ToA<B>` are also unrelated.

`"strictFunctionTypes": false` can silence the issue; but it _is_ an issue - a `NeededInfo<ToB<typeof ASchema>>` can't be assignable to a `NeededInfo<{}>`, since as two different instantiations of the internal `ToA` are necessarily unrelated, two differing instantiations of `NeededInfo` are unrelated.

And that's why the error is "correct".

Now, I say that, but the mapped type assignability rules in higher order aren't keen on one case: mapping over the empty object always produces the empty object (so the variances of the type parameters no longer matter once the key set being mapped over is empty). This simplification/decomposition isn't reflected in mapped type higher order relationships (this would require expressing a dependent variance of some kind), so ends up not being reflected by variance measures. At it's heart, that is the same underlying issue as #29698 (though admittedly slightly different, since it relies on an edgecase around `{}`, rather than the behavior of index signature assignability). We talked about it a bit internally last week, I think, and we're thinking that what we'll probably end up doing is excluding generic mapped types from variance-based comparisons, since there are so many cases where they don't match up with the concrete structural results you can find upon instantiation.

**Comment by phiresky** [comment]
@weswigham 


> Actually, the error is in some respects correct... `io-ts`'s `Type` type is _invariant_ in it's first argument - meaning `Type<A>` is never related to `Type<B>` (and vice-versa) if `A` !== `B`. This is the case because that type parameter is, used in both an argument position (`encode`) and an output position (`validate`) 
 
You are right. I managed to solve my problem by [replacing instances of where I had `{[name: string]: any}` (which were {} in the minimal example because it gives the same results) with any](https://github.com/phiresky/typed-socket.io/commit/bb88d8759a09d2be2d39cf9c420faeea2960c645), and [replacing my generics defaults with `any` instead of empty objects](https://github.com/phiresky/typed-socket.io/commit/438e9a4d8d526d103dc3a1c0048824ea70252986). Then the inference works as expected on the current TypeScript version. Pretty hard to find that solution [1], but it does make sense in the end.

I reason I wrote them as `{[name: string]: any}` in the first place is to avoid any as much as possible, because `any` loves to propagate everywhere when making a tiny mistake in this kind of type soup. But i guess TS now (correctly) knows that those generics need to be invariant not just covariant, and the only type TS accepts as invariant to any generic is `any`.




---
[1] because this is the error message i get on the actual instance of the problem:

```
Type 'NeededInfo<MyServerDefinition, SimpleNamespace<ToCompiletime<{ ServerMessages: { chatMessage: Type<ChatMessage, ChatMessage, unknown>; history: Type<ChatMessage[], ChatMessage[], unknown>; }; ClientRPCs: { postMessage: { request: ExactC<...>; response: Type<...>; }; }; ClientMessages: {}; }>>>' does not satisfy the constraint 'NeededInfo<ServerDefinition, FullNamespaceSchema>'.
  Types of property 'RuntimeSchema' are incompatible.
    Type 'FromCompiletime<SimpleNamespace<ToCompiletime<{ ServerMessages: { chatMessage: Type<ChatMessage, ChatMessage, unknown>; history: Type<ChatMessage[], ChatMessage[], unknown>; }; ClientRPCs: { postMessage: { request: ExactC<TypeC<{ message: StringC; channel: UnionC<...>; }>>; response: Type<...>; }; }; ClientMessages:...' is not assignable to type 'FromCompiletime<FullNamespaceSchema>'.
      Type 'FullNamespaceSchema' is not assignable to type 'SimpleNamespace<ToCompiletime<{ ServerMessages: { chatMessage: Type<ChatMessage, ChatMessage, unknown>; history: Type<ChatMessage[], ChatMessage[], unknown>; }; ClientRPCs: { postMessage: { request: ExactC<TypeC<{ message: StringC; channel: UnionC<...>; }>>; response: Type<...>; }; }; ClientMessages: {}; }>>'.ts(2344)
```

**Comment by sandersn** [comment]
This breaks ember's types on DT in a very confusing way (which may be correct!). Go to ~/DefinitelyTyped/types/ember__application and run tsc. I'll provide a repro shortly once I understand the problem better.

**Comment by sandersn** [comment]
ember wants to do the unsound thing where they have:

```ts
class Base {
  resolver: BaseResolver
}
class Derived extends Base {
  resolver: DerivedResolver
}
```

where `DerivedResolver` extends `BaseResolver`. But resolver is now invariant.

Here's a minified repro. I'm not sure how interesting it is:

```ts
declare class ComputedProperty<Get, Set=Get> {
    // Necessary in order to avoid losing type information
    //    see: https://github.com/typed-ember/ember-cli-typescript/issues/246#issuecomment-414812013
    private ______getType: Get;
    private ______setType: Set;
}

type UnwrapComputedPropertyGetter<T> = T extends ComputedProperty<infer U, any> ? U : T;
type UnwrapComputedPropertyGetters<T> = { [P in keyof T]: UnwrapComputedPropertyGetter<T[P]> };

type UnwrapComputedPropertySetter<T> = T extends ComputedProperty<any, infer V> ? V : T;
type UnwrapComputedPropertySetters<T> = {[P in keyof T]: UnwrapComputedPropertySetter<T[P]>};

interface Observable {
    /**
     * To get the values of multiple properties at once, call `getProperties`
     * with a list of strings or an array:
     */
    getProperties<K extends keyof this>(list: K[]): Pick<UnwrapComputedPropertyGetters<this>, K>;
    setProperties<K extends keyof this>(hash: Pick<this, K>): Pick<UnwrapComputedPropertySetters<this>, K>;
}

type Ctor<T> = new (...args: any[]) => T;
declare class Mixin<T> { }
declare function ext<T>(arg1: Mixin<T>): Ctor<T>;

declare const MixedO: Mixin<Observable>;
declare class Base extends ext(MixedO) {}
declare class Derived extends Base {
    p: number;
}
declare let r: Base
declare let dr: Derived
r = dr // unexpected error here
```

**Comment by sandersn** [comment]
jasmine is also broken because of this, with code

```ts
interface Foo {
    a: number;
    b: number;
    bar: string;
}
interface ObjectContaining<T> {
  new (sample: Partial<T>): Partial<T>
}
declare let cafoo: ObjectContaining<{ a: number, foo: number }>;
declare let cfoo: ObjectContaining<Foo>;
cfoo = cafoo;
cafoo = cfoo;
```

I'm not sure why this worked before.

**Comment by weswigham** [comment]
As for the ember bit I'm pretty sure it's because `UnwrapComputedPropertyGetter` is invariant on its parameter type as we now require check and extends types to be identical. That bubbles up to `Observable`, and since `Observable` uses a this type and is then used as the mixin base, affects the classes. As for "why wasn't this an error before" - because an instantiation inside an extends clause and subsequent constraint comparison caused us to perform the comparison with diagnostic reporting off, producing an incorrect result that didn't rely on variances an cacheing it (in effect triggering this bug, exactly).

**Comment by weswigham** [comment]
> I'm not sure why this worked before

Same. Shouldn't weak type checking have at least forbidden the one direction of that? `T` is obviously invariant, since it's in both an argument and return position. I think I can understand how it triggered this bug tho - assignments are a place where we do the assignment check with no error reporting first (so we can decompose the expression for a better error), so that'd definitely be why it cached a structural result and ignored variances.

**Comment by sandersn** [comment]
Some other DT breaks:

* material-ui
* react-jss
* recompose

I haven't investigated these, but they fail at exactly the same bisected commit.

**Comment by chriskrycho** [comment]
I'm not positive, but this *may* be the same issue I've seen in a library, [reproduction here][repro]. If it's *not* the same, it's another thing hit by changes in variance—but the symptoms are very similar, and the issue definitely one of invariance. I can see how minimal the definitions for [True Myth's `Maybe`][maybe] have to be to trigger this, if that's helpful: it's definitely not triggered with a minimal subset of that `Maybe` type.

[repro]: https://github.com/chriskrycho/ts-variance-regression
[maybe]: https://github.com/true-myth/true-myth/blob/6f018526e538fda4285ee6b55c1c711fb7c7ce08/src/maybe.ts

**Comment by fictitious** [comment]
Here is another example, similar to https://github.com/Microsoft/TypeScript/issues/29698

```typescript
type Base = Record<string, {}>;

interface Wrapper<B extends Base> {
    b: B;
    f(): keyof B; // makes Wrapper covariant in keyof B
//    in reality it was map: Map<Extract<keyof B, string>, {}>;
}

declare function createWrapper<B extends Base>(b: B): Wrapper<B>;

declare function acceptRecordOfWrappers<R extends Record<string, Wrapper<Base>>>(r: R): void;

acceptRecordOfWrappers({
    w: createWrapper({a: {}})
});

// Type 'Wrapper<{ a: {}; }>' is not assignable to type 'Wrapper<Record<string, {}>>'.
//  Property 'a' is missing in type 'Record<string, {}>' but required in type '{ a: {}; }'.

```
Some notes:

1. I'm getting this error even with `--strictFunctionTypes` turned off

2. When I started getting this error, it would be helpful if the message said `this error happened while trying to uphold the variance for keyof B as stated in Wrapper` or something like that

3. Checking assignability to `Wrapper<Record<string, {}>>` is not really what I want, because when I say

`R extends Record<string, Wrapper<Base>>`

I actually mean `R extends Record<string, Something that extends Wrapper<Base>>` where `Something` is going to be different type extending `Wrapper` with different `B` for different keys, and I want TypeScript to infer strict types for `keyof R` and actual value types from the argument passed to `acceptRecordOfWrappers`.

**Comment by sandersn** [comment]
Pretty sure yargs has the problem too:

```ts
declare let yb: yargs.Argv<{ b: number }>
declare let yab: yargs.Argv<{ a: string, b: number }>
yb = yab // seems fine...
```

...Except that one of Argv's methods uses `T` in a contravariant position.

**Comment by sandersn** [comment]
Poking at material-ui, the break there is on React's ComponentClass. I'm not sure why no other react tests break -- it's hard to believe that all other uses are invariant.

**Pull request merged**
