### PR TITLE
Add script for posting perf results back to GH

### PR DESCRIPTION
**Pull request by weswigham**
And now to test~

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot perf test

**Comment by weswigham** [comment]
@typescript-bot perf test

**Comment by weswigham** [comment]
@typescript-bot perf test

**Comment by weswigham** [comment]
@typescript-bot perf test

**Comment by weswigham** [comment]
@typescript-bot perf test

**Comment by rbuckton** [comment]
Yeah... that didn't format very well.

**Comment by weswigham** [comment]
@typescript-bot perf test

**Comment by weswigham** [comment]
@typescript-bot perf test

**Pull request merged**
