### PR TITLE
Update dprint-typescript to 0.88.1, reformat

### PR DESCRIPTION
**Pull request by jakebailey**
This fixes a formatting bug when using multi-line strings.

### CODE REVIEW

**Review by sheetalkamat — APPROVED** [review]
Why is this update not auto like other dependencies ?

**Comment by jakebailey** [comment]
I could make the update job do that, yeah. It'd just have to also commit the new formatting, and I was not sure if that was desirable or not given there _could_ be dprint bugs that come up.

**Comment by sheetalkamat** [comment]
It could do auto update when no change is needed in code and create PR with update of dprint and code  otherwise?

**Comment by jakebailey** [comment]
Yeah, I'll see what I can do there. That should be possible.

**Comment by jakebailey** [comment]
I think I'll be able to reuse the workflow code from my WIP cherry-pick pipeline replacement workflow (hopefully done soon, doing like 50 things at once) Both workflows are situations where we want to push to a specific branch and then send a PR if there isn't one yet.

For now though, I'm just going to merge this.

**Pull request merged**
