### PR TITLE
Accept generics for defineProperty

### PR DESCRIPTION
**Pull request by sirlancelot**
Both `Object.defineProperty()` and `Object.defineProperties()` return their
first argument. Use a generic so that typings can be passed through.

### CODE REVIEW

**Comment by sirlancelot** [comment]
Updated baselines.

**Review by sandersn — APPROVED** [review]
I'm cautiously optimistic that this won't break anything, since there wasn't much churn in the test baselines. However, I'd like a second opinion. @orta do you think this is a good idea?

**Comment by ExE-Boss** [comment]
Arguably, for maximum correctness, it should be:

```ts
interface ObjectConstructor {
	defineProperty<
		T extends object,
		P extends PropertyKey,
		V = P extends keyof T ? T[P] : unknown,
		W = P extends keyof T ? true : false
	>(
		target: T,
		property: P,
		descriptor: TypedPropertyDescriptor<V> & { readonly writable?: W },
	): (T &
		{ readonly [K in P as W extends false ? K : never]: V } &
		{ -readonly [K in P as W extends true ? K : never]: V })
		// Needs https://github.com/microsoft/TypeScript/issues/40562:
		// & (asserts target is T &
		//	{ readonly [K in P as W extends false ? K : never]: V } &
		//	{ -readonly [K in P as W extends true ? K : never]: V });

	defineProperties<
		T extends object,
		M extends Record<string | symbol, PropertyDescriptor & { readonly __proto__?: object | null }>
	>(
		target: T,
		properties: M & ThisType<T>,
	): ({} extends M ? T : T & {
			readonly [K in keyof M as M[K] extends { readonly writable: false } ? K : (K extends keyof T ? never : K)]:
				M[K] extends Readonly<TypedPropertyDescriptor<infer V>> ? V : any;
		} & {
			-readonly [K in keyof M as M[K] extends { readonly writable: true } ? K : (K extends keyof T ? K : never)]:
				M[K] extends Readonly<TypedPropertyDescriptor<infer V>> ? V : any;
		})
		// Needs https://github.com/microsoft/TypeScript/issues/40562:
		// & (asserts target is ({} extends M ? T : T & {
		//	readonly [K in keyof M as M[K] extends { readonly writable: false } ? K : (K extends keyof T ? never : K)]:
		//		M[K] extends Readonly<TypedPropertyDescriptor<infer V>> ? V : any;
		// } & {
		//	-readonly [K in keyof M as M[K] extends { readonly writable: true } ? K : (K extends keyof T ? K : never)]:
		//		M[K] extends Readonly<TypedPropertyDescriptor<infer V>> ? V : any;
		// }))
}
```

## See also:
- <https://github.com/microsoft/TypeScript/issues/39882>
- <https://github.com/microsoft/TypeScript/issues/42919>

**Comment by sirlancelot** [comment]
> Arguably, for maximum correctness, it should be what I posted in [#41424 (comment)](https://github.com/microsoft/TypeScript/issues/41424#issuecomment-723064626), but that might have compatibility issues and be overkill.

Wow, that's really cool! Regrettably, I'm not as well-versed in TypeScript annotations but I know just enough to be able to appreciate that one. :+1:

**Review by orta — APPROVED** [review]
Yeah, this generally seems reasonable to me  ( hah, Exe-boss that version is wild)

I feel like it's a little strange because the object you pass it would always be modified by going through the function so in theory the `T` wouldn't _necessarily_ match on in the `return` position. But I think this is what you'd pragmatically expect from the function.

**Pull request merged**
