### PR TITLE
Exclude identity relation from mapped type relation check

### LINKED ISSUE #46631: Excessive stack depth error in type identity check
### 🕗 Version & Regression Information

Nightly build. For an example, see the `typeorm` error in #46610.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.5.0-dev.20211101#code/JYOwLgpgTgZghgYwgAgGKgCYHkAO05gD2UAPACoB8yA3gLABQyTyMhhAXMmQNwMC+DBmACeeNJgDChEBmBhg0gM7kqAXhoNmyANoAFZKGQBrCMMIwuAXQD8ndDKky5CkMrJ7LVAD7iZufESk9hiOsvJK5B4UFLz0fLEMMACuIAjhICxsJACi4HLCFAAUAJQajMwAbnBQyAAedpLSYS7KcCAFsVpVNfW+IU3OEbnyIjFMAPTjyNm1SIqKwBUoimCIRsgYEDhgABbI0FDE-AxAA

### 💻 Code

```ts
interface FindOperator<T> {
    foo: T;
}

type FindConditions<T> = {
    [P in keyof T]?: FindConditions<T[P]> | FindOperator<FindConditions<T[P]>>;
};

function foo<Entity>() {
    var x: FindConditions<any>;
    var x: FindConditions<Entity>;  // Excessive stack depth error
}
```

### 🙁 Actual behavior

Excessive stack depth error.

### 🙂 Expected behavior

No excessive stack depth error (but still an error about the two declarations having different types).

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #46631.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@DanielRosenwasser @andrewbranch We should cherry pick this for 4.5.

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5

**Review by andrewbranch — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
> ```
> git remote add nonlocal git://github.com/microsoft/TypeScript.git
> 
> git fetch nonlocal main
> Error: git fetch nonlocal main failed: stderr: fatal: remote error: 
>   The unauthenticated git protocol on port 9418 is no longer supported.
> Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
> ```

😕

**Comment by DanielRosenwasser** [comment]
Cherry-pick over at #46635. I'm considering bringing it into the RC.

**Pull request merged**
