### PR TITLE
Remove redundant 'reduce' overloads

### LINKED ISSUE #25454: Poor type inference for `reduce`
**TypeScript Version:**  3.0.0-dev.20180705

**Code**

```ts
function toStrings(arr: ReadonlyArray<object>): string[] {
	return arr.reduce((acc, obj) => {
		acc.push(obj.toString());
		return acc;
	}, [] as string[]);
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts:2:2 - error TS2322: Type 'object' is not assignable to type 'string[]'.
  Property 'length' is missing in type '{}'.

2  return arr.reduce((acc, obj) => {
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3  	acc.push(obj.toString());
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
4  	return acc;
  ~~~~~~~~~~~~~
5  }, [] as string[]);
  ~~~~~~~~~~~~~~~~~~~~

src/a.ts:3:7 - error TS2339: Property 'push' does not exist on type 'object'.

3  	acc.push(obj.toString());
```

No error if I explicitly specify `arr.reduce<string[]>`.
No error if I remove the first two overloads to `reduce`, which are non-generic.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #25454

### CODE REVIEW

**Comment by sandersn** [comment]
The contextual type would be incorrect anyway in the case that `U !== T`, wouldn't it? And I don't think   `initialValue` will commonly be context sensitive. Except in the case of tuples, maybe.

**Comment by andy-ms** [comment]
I did come up with a test case that's broken by this, see the bottom of `arrayReduce.ts`. Probably not a common situation though... I don't think there's a way we can support `initialValue` having an arbitrary type, and also give it a contextual type based on the assumption that it's the same type as the array elements (which may be a supertype of what you wanted `initialValue` to be, which caused the original issue).

**Comment by andy-ms** [comment]
@mhegazy @sandersn @rbuckton @DanielRosenwasser @weswigham Could you review?

**Comment by andy-ms** [comment]
@mhegazy @sandersn @rbuckton @DanielRosenwasser @weswigham Could you review?

**Comment by RyanCavanaugh** [comment]
@andy-ms let's get this up to date and then see what the RWC run turns up

**Comment by RyanCavanaugh** [comment]
@typescript-bot test this

**Comment by RyanCavanaugh** [comment]
Nontrivial RWC breaks occurred

**Pull request closed without merging**
