### PR TITLE
JSX namespace names should not be considered expressions

### PR DESCRIPTION
**Pull request by weswigham**
Fixes the regression in [this comment](https://github.com/microsoft/TypeScript/issues/53974#issuecomment-1519152756), which was regressed by #47356 (and followup #53799), which mistakenly classified `JsxNamespacedName` nodes as `Expression`s, which masked a _ton_ of locations where they were effectively unhandled - the relevant location in the case of the regression being `getLiteralTypeFromPropertyName`, which started returning `errorType` for all jsx namespace names (which perviously were correctly the `a:b` string, thanks to the funky identifier we used to use).

As an aside, `checkExpressionWorker` currently silently returns `errorType` for all unknown expression types - shouldn't this be a hard `Debug.fail` calling out the unhandled case? This may have been more obvious had that been the case.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot run dt
@typescript-bot test top100
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
> As an aside, checkExpressionWorker currently silently returns errorType for all unknown expression types - shouldn't this be a hard Debug.fail calling out the unhandled case? This may have been more obvious had that been the case.

Good point - let's try that out in a follow-up PR on the top 100.

**Review by DanielRosenwasser — APPROVED** [review]
Looks good but get another review.

Also, might be good to have a test with an index signature like `` `ns:do-${string}` ``

**Comment by andrewbranch** [comment]
Perf run _almost_ looks like this is visible in parse time, but it’s pretty noisy, and the only real addition is a `isJsxNamespacedName(initialExpression)` call 🤔

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this faster

**Review by jakebailey — APPROVED** [review]

**Pull request merged**
