### PR TITLE
Defer switch exhaustiveness checks

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes the issue reported here: https://github.com/microsoft/TypeScript/pull/34840#issuecomment-551283936.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@RyanCavanaugh @weswigham We might consider cherry picking this for 3.7.3.

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by RyanCavanaugh** [comment]
@ahejlsberg does this also fix #34960?

**Comment by weswigham** [comment]
Based on this [exchange](https://github.com/microsoft/TypeScript/pull/34840#issuecomment-551906830) in the other PR, I'm guessing yes?

**Comment by ahejlsberg** [comment]
Yes, this fixes #34960.

**Pull request merged**
