### PR TITLE
Transform arrow function in variable declaration to named function

### PR DESCRIPTION
**Pull request by mpodlasin**
This is a work-in-progress for https://github.com/Microsoft/TypeScript/issues/6433.

I wanted to start with the simplest case of transforming 

```ts
const x = () => {}
```
into 

```js
var x = function x() {}; // currently it emits "var x = function() {}" (note lack of function name)
```
I was able to get desired result in baselines, but many tests fail with
```
Error: Debug Failure. False expression: position cannot precede the beginning of the file
```

I imagine this is a problem with position of synthesized identifier for function name, but I have no idea how should I fix it. Many transforms create nodes (for example object literal transform creates many assignments) and yet they do not have to manipulate positions of synthesized nodes.

I am super confused. Help! I need some pointers how to proceed. @rbuckton @mhegazy 

Thanks in advance!

### CODE REVIEW

**Comment by mhegazy** [comment]
@rbuckton can you take a look.

**Comment by Podlas29** [comment]
Ok. It seems I have figured it out. Tests should pass now.
I however still need confirmation that general direction of changes is ok. :)

**Comment by kpreisser** [comment]
Hi,

I think there needs to be a special treatment for unnamed functions that reference the variable in which they stored:

```typescript
var x = recursive => {
    if (!recursive)
        return x(true);
    else
        return 1;
}
var y = x;

x = () => {
    return 2;
};

console.log(y(false));
```

Expected output (when running without this PR or running the code directly in Node):
```
2
```

Actual output with this PR:
```
1
```

Maybe in this case the `x` variable needs to be renamed, e.g. to `x_1`.

Thanks!

**Comment by mhegazy** [comment]
I am afraid the fix here is not as simple as just adding a name. As @kpreisser noted, the name could be changed outside the function.. moreover, adding the name may shadow another variable that was visible otherwise.. e.g. `var a; var o = { a: () => { a } }`. 

Looking at this again, i am not sure this is the right solution. The other solution is setting the name using `object.defineProperty`, but that too, not sure we want to litter the generated code with such calls.. It may be better to just do nothing on this issue in the time being.

**Comment by mhegazy** [comment]
closing for now, as this has grown stale, and it is an incomplete fix in the first place.

**Pull request closed without merging**
