### PR TITLE
Set '.declarations' on a property of a homomorphic mapped type

### LINKED ISSUE #15821: Homomorphic mapped types do not adopt documentation comments
**TypeScript Version:**  2.3.0

Homomorphic mapped types do not adopt documentation comments, as shown in the following example:
**Code**
```ts
interface Foo {
	/** Gets the bar. */
	bar: any;
}

let t: Foo = null!;
t.bar; // Has the comment "Gets the bar" associated with it.

let t2: { [TKey in keyof Foo]: any } = null!;
t2.bar; // Has no comment associated with it.
```

Even though the type of the propery changes, mapped properties are still very related to the property they originate from and thus adopting the doc comments from the originating property should be reasonable.

## Use Case
Mixin classes together with mapped types provide a much more sophisticated alternative to decorators:
```ts
class MyService {
	queryData() { return "Data"; }
}

class MyClass extends annotate(Object,
	{
		/**
		 * All services. (This comment is lost)
		 */
		myServices: injectMany(MyService, "MyService1")
	})
{
	public doSth() {
		return this.myServices.map(s => s.queryData()).join(",");
	}
}

function injectMany<T>(clazz: new() => T, name: string): { _type: T[] } {
	throw "todo";
}

type Constructable<T> = new (...args: any[]) => T;

function annotate<TBC extends Constructable<object>, TProps extends { [name: string]: { _type: any } }>
	(base: TBC, props: TProps): Constructable<{[TKey in keyof TProps]: TProps[TKey]["_type"]}> & TBC {

	return class extends base {
		constructor(...args: any[]) {
			super(args);
		}
	} as any;
}
```
In contrast to decorators, this approach allows to infer the type of the property from its annotation.

However, not being able to specify documentation comments for the properties that are introduced by `annotate` is a show-stopper.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #15821

### CODE REVIEW

**Comment by sandersn** [comment]
The change looks good but I'll wait to approve it until after the test failures are fixed to make sure there aren't any big changes that result.

**Comment by andy-ms** [comment]
The bug in `findAllRefsMappedType.ts` was due to `getSymbolScope` not recognizing the mapped type property as a property. (Previously we would see `symbol.declarations === undefined` and immediately give up on getting a scope.) I changed it to always return `undefined` as soon as it sees that a symbol is a property or method -- I don't see why this wasn't done before.

**Comment by sandersn** [comment]
I'm not fluent with findAllRefs, so there may be an obvious answer: if a property or method is public, wouldn't it still need to be part of an exported type to be visible anywhere?

**Comment by andy-ms** [comment]
True, but that would be hard to detect. `getSymbolScope` definitely isn't looking for that right now.

**Pull request merged**
