### PR TITLE
Don't inferFromIndexTypes() twice

### LINKED ISSUE #33559: new readonly modifiers on Promise.all break lyricist in DT
Broken by #33057 

1. clone dt
2. cd ~/dt/types/lyricist
3. tsl
4. error on `const songsByArtist: SongByArtist[] = results[5];

```ts
Promise
    .all([
        lyricist.album(1, { fetchTracklist: true, textFormat: LyricistTextFormat.PLAIN }),
        lyricist.artist(1, { textFormat: LyricistTextFormat.PLAIN }),
        lyricist.artistByName('any_artist', { textFormat: LyricistTextFormat.PLAIN }),
        lyricist.search('any_song'),
        lyricist.song(1, { fetchLyrics: true, textFormat: LyricistTextFormat.PLAIN }),
        lyricist.songsByArtist(1, { page: 1, perPage: 10, sort: 'asc' }),
    ])
    .then((results) => {
        const album: Album = results[0];
        const artist: Artist = results[1];
        const artistByName: Artist = results[2];
        const searchResult: SearchResult[] = results[3];
        const song: Song = results[4];
        const songsByArtist: SongByArtist[] = results[5];

        console.log('album', album.name);
        console.log('artist', artist.name);
        console.log('artistByName', artistByName.name);
        console.log('searchResult length', searchResult.length);
        console.log('song', song.title);
        console.log('songsByArtist length', songsByArtist.length);
    });
```

**Expected behavior:**
No error, and `results[5]: SongByArtist[]`

**Actual behavior:**
Error, and `results[5]: SearchResult[]`

The two types are VERY similar, although I'm not sure that's relevant. My guess is that it's a very subtle inference problem.

### LINKED ISSUE #33752: 3.7-beta regression: Promise.all wrongly adds `undefined` type
**TypeScript Version:**  3.7.0-beta

**Search Terms:**

promise all

**Code**

```ts
interface A {
  a: string
}
interface B {
  b: string
}
async function main(): Promise<A> {
  const [a, b] = await Promise.all([
    Promise.resolve({a: "a"} as A),
    Promise.resolve({b: "b"} as B | undefined), // <- the `| undefined` here is the problem
  ]);
  return a; // <- a has type `A | undefined`, but should be `A`
}
```

**Expected behavior:**

This is a regression from 3.6.3, where the return tuple of `Promise.all` is correctly inferred.

**Actual behavior:**

A `| undefined` bound of a different tuple member also adds a `| undefined` bound on a different unrelated return value of `Promise.all`.

**Playground Link:** 

https://www.typescriptlang.org/play/?ts=3.7-Beta#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmQGcwpQBzLAXy1ElkRQCFMdkAjQkskSmuIgE8QCZDACuIsMAD2IZAFs4oABQBKQgAUoMhcCIQAPKgB8rXAjklkAbTgAaDgF1kAXjwB3ZWGTbd+iAA6OAAbEJUbNlw-PQNAqAgiGRCANwgVDAJkACI4bKo8IjQ1eyjfHVighKTU9IxOHPZ8wuQWAB9kSQATCBhQCC6S5AB6YeRDAFpkMAALFAADDu7e-q755DmE5H1pueQABx12EIgFNic1AG42BLBxKHk4S5GxybwNgWnBfYX0JZAen0QAN5o52OIfEQZjJxCEuhxfvNqEA

**Related Issues:** 

Maybe https://github.com/microsoft/TypeScript/pull/33707 ?

### LINKED ISSUE #34925: Promise.all not correctly inferring types.
**TypeScript Version:**  3.7.2, also nightly

**Search Terms:**
Promise.all
Wrong type

**Code**

```ts
const f1 = async (): Promise<string> => {
    return '';
}

const f2 = async (): Promise<number> => {
    return 0;
}

const f3 = async (): Promise<Object> => {
    return {};
}

const res = Promise.all([f1(), f2(), f3()]);
```

**Expected behavior:**
`res` has type `[string, number, Object]`.

**Actual behavior:**
`res` has type `Object[]`.

**Playground Link:** 
http://www.typescriptlang.org/play/?ts=3.8.0-dev.20191102&ssl=2&ssc=1&pln=5&pc=1#code/MYewdgzgLgBAZgRhgXhgQwgTzMGAKASgC4YAFAJxAFsBLCAUwB5pyawBzAPhW4G8AoGEJjl6UAK7kwMAOQyA3PwC+-fqEiw4AJhTosOfMTKVaDRmHFUARvXLdkfQcNESpMAAyKVa8NHgBmXQxsXEISCmo6JgB5KwAremAoe0dhETFJaV4lL1V1P1EIXQjTegA6NAAbSrwAbURCABp4LSaAwgBdAnkgA

**Related Issues:**

### LINKED ISSUE #34937: 3.7.2 Promise.all does infers base type of interfaces rather than actual interface
**TypeScript 3.7.2**
[Playground link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgIoFcD2kBiwA2kUyA3gFDKXID6wAJgFzIDOYUoA5gNxkC+ZZUEXhI0WXASIBBOgDc4IJHWQQAHpBB1mY7BDyFopClRBwAthCat2IbnwEx0isMEwhkHCGAy79RZgAUAJRMAApQmGbAzBAAPD4SBlAA2gC6AHxGVMhQXuhQ7iAQAO7I4ZHRcQl6ktBp6QHG2ZQBucyY+LIQADQ5EABWEAhgQcgAvJnkzdN97Z0QAclNM80kNPRMAOQAKhCsm8j8K9mpQTwrvGf2ZI7Oru6e3uI1Scwy8ooQdMFhEVEx8Wefmg7wUSnqWSouTA+UKJTKf0qgN8tSgoM+dHqjRWrT2HS6vVyg2GowmkOOs3xCyWFNW60YyB2ezAm16pgsW12+0OyxWp3OM0uPH4ZDgzAAnopguNJssEG5WMhkjBUcxenA5GCvqlxsg4MU4MAwAiKjEAHRwfD4Ra8qiParAqCBILdW2Ue1A1XopTBZb8vhAA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
interface QuoteFilter {
    _id: string;
}

interface QuoteFilterAdvanced extends QuoteFilter {
    name: string;
}

function getQuoteFilters(): Promise<QuoteFilter[]> {
    return new Promise<QuoteFilter[]>(
        (resolve, reject) => {
            resolve([
               { _id: 'Test' }
            ]);
        });
}

function getQuoteFiltersAdvanced(): Promise<QuoteFilterAdvanced[]> {
    return new Promise<QuoteFilterAdvanced[]>(
        (resolve, reject) => {
            resolve([
               { _id: 'Test', name: 'Test' }
            ]);
        });
}

async() => {
    const [filters, advanced] = await Promise.all([
        getQuoteFilters(),
        getQuoteFiltersAdvanced()
    ]);
}
```

**Output:**
```javascript
"use strict";
function getQuoteFilters() {
    return new Promise((resolve, reject) => {
        resolve([
            { _id: 'Test' }
        ]);
    });
}
function getQuoteFiltersAdvanced() {
    return new Promise((resolve, reject) => {
        resolve([
            { _id: 'Test', name: 'Test' }
        ]);
    });
}
async () => {
    const [filters, advanced] = await Promise.all([
        getQuoteFilters(),
        getQuoteFiltersAdvanced()
    ]);
};

```

**Expected behavior:**
I am expecting the advanced variable to be an array of QuoteFilterAdvanced rather than QuoteFilter.

This was correctly inferred in Typescript 3.6.3

### PR DESCRIPTION
**Pull request by jablko**
Fixes #33559
Fixes #33752
Fixes ~#34924~
Fixes #34925
Fixes #34937
Fixes ~#35136~
Fixes ~#35258~

```TypeScript
interface I<T> {}
declare function f1<T1, T2>(values: [I<T1>, I<T2>]): T1;
declare function f2<T1, T2>(values: readonly [I<T1>, I<T2>]): T1;

declare const values: [I<1>, I<number>];
let one: 1;
one = f1(values); // ✓ 1
one = f2(values); // ✗ number
```

Currently `f2(values)` is `number` while `f1(values)` is `1`.

There are three cases in `inferFromProperties()`
1. Source and target are both tuples: infers types element-wise
2. Target is an array: calls `inferFromIndexTypes()`
3. Otherwise: iterates over properties

But then `inferFromObjectTypesWorker()` calls `inferFromIndexTypes()` again, in all cases
```TypeScript
                if (!typesDefinitelyUnrelated(source, target)) {
                    inferFromProperties(source, target);
                    inferFromSignatures(source, target, SignatureKind.Call);
                    inferFromSignatures(source, target, SignatureKind.Construct);
                    inferFromIndexTypes(source, target);
                }
```

This PR moves that call from `inferFromObjectTypesWorker()` to the third case. Consequently
1. `inferFromIndexTypes()` isn't called twice in the second (array) case
2. it isn't called at all in the first (tuple) case, so `f2(values)` is `1` like `f1(values)`

FYI `f1(values)` is currently `1` unlike `f2(values)` because parameter and argument are the same generic type (tuple) and handled by
```TypeScript
                if (getObjectFlags(source) & ObjectFlags.Reference && getObjectFlags(target) & ObjectFlags.Reference && (
                    (<TypeReference>source).target === (<TypeReference>target).target || isArrayType(source) && isArrayType(target)) &&
                    !((<TypeReference>source).node && (<TypeReference>target).node)) {
                    // If source and target are references to the same generic type, infer from type arguments
                    inferFromTypeArguments(getTypeArguments(<TypeReference>source), getTypeArguments(<TypeReference>target), getVariances((<TypeReference>source).target));
                }
```
whereas `f2(values)` parameter (readonly tuple) and argument (tuple) aren't.

### CODE REVIEW

**Comment by jablko** [comment]
@typescript-bot user test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot user test this
@typescript-bot test this

**Comment by weswigham** [comment]
@jablko rather than the other changes in `checker.ts`, could you just delete
```ts
                    if (isArrayType(target)) {
                        inferFromIndexTypes(source, target);
                        return;
                    }
```
from `inferFromProperties`? That way the single unconditional `inferFromIndexTypes` is still easy to track.

**Comment by jablko** [comment]
@weswigham Thanks a lot for taking a look at this! What you describe would call `inferFromIndexTypes()` just once, however it would still call it in the tuple case, so I assume it wouldn't resolve the test case included in this issue: Inferring an array type instead of a tuple type.

`inferFromProperties()` infers a tuple type element-wise, but then `inferFromObjectTypesWorker()` calls `inferFromIndexTypes()` which re-infers an array type. :x:

**Comment by weswigham** [comment]
> however it would still call it in the tuple case, so I assume it wouldn't resolve the test case included in this issue: Inferring an array type instead of a tuple type

Hm, if that's the case, can we copy the tuple check into the `inferFromObjectTypesWorker` instead of shifting `inferFromIndexSignatures` into `inferFromProperties`? I don't like the implicit linkage of index inference to property inference caused by the current layering.

**Comment by jablko** [comment]
:heavy_check_mark: Yup, that works. Done.

**Comment by sandersn** [comment]
@weswigham are you happy with this change now? It's been a while, but the inference code hasn't changed much in the last few months.

**Review by StefanXhunga — COMMENTED** [review]
Thank you for your assistance, please change the nesessery scedares!

**Pull request merged**
