### PR TITLE
Replace all ors with nullish coalescing

### PR DESCRIPTION
**Pull request by jakebailey**
Benchmarking suggests that this is faster (even when downleveled) than `||`, i.e. the boolean conversion is more expensive than explicit `null` and `undefined` checks. https://jsbench.me/2xl1mre9kv/1

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
Well, that's no smoking gun. Ugh

**Comment by ritschwumm** [comment]
it's still an improvement in code quality, isn't it?

**Comment by jakebailey** [comment]
In some cases, yes, but it appears to have a negative runtime impact. I suspect I should retry with a lint rule like this but which finds boolean conversions where an `=== undefined` or `!== undefined` would be more performant.

**Pull request closed without merging**
