### PR TITLE
extract declaration emitter to a separate file

### PR DESCRIPTION
**Pull request by vladima**
I've tried to keep the code intact, all changes are basically just moving functions around. Code that is shared between declaration emitter and emitter is placed in 'utilities.ts'

### CODE REVIEW

**Comment by yuit** [comment]
:+1:

**Comment by mhegazy** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by JsonFreeman** [comment]
:

**Comment by vladima** [comment]
Closing this PR in favor of #2417

**Pull request closed without merging**
