### PR TITLE
fix(47946): Literal types cannot be used in JSDoc export default { } syntax

### LINKED ISSUE #47946: Literal types cannot be used in JSDoc `export default { }` syntax
# Bug Report

There seems to be an issue with regards to literal types and JSDoc when using `export default {}`  syntax.

### 🔎 Search Terms

"jsdoc" and "export default"

Found this related issue: #45233, and [Ryan asked me to create a new issue](https://github.com/microsoft/TypeScript/issues/45233#issuecomment-1043663716)

### 🕗 Version & Regression Information

It seems to have been introduced in TS@4.5. I don't think TS 4.4 had support for typed `export default {}` with JSDoc.

- This changed between versions 4.4 and 4.5

### ⏯ Playground Link

Not possible I think (playground doesn't have plain "js" support?)

### 💻 Code

In a file "foo.js":

```js
// @ts-check
/**
 * @typedef Foo
 * @property {string} bar
 * @property {'qux'} baz
 */

/** @type {Foo} */
export default {
    bar: '42',
    baz: 'qux' // 👈 This is NOT ok
      // ^^^^^  Type 'string' is not assignable to type '"qux"'
}

/** @type {Foo} */
export const foo = {
    bar: '42',
    baz: 'qux' // 👈 This is OK
}
```

### 🙁 Actual behavior

> Type 'string' is not assignable to type '"qux"'

### 🙂 Expected behavior

> _no compile error_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47946

### CODE REVIEW

**Review by sandersn — CHANGES_REQUESTED** [review]
I'll leave a comment on the issue laying out some design questions, but for now I'm assuming that the semantics of `/** @type {T} */ export default { ... }` are like

`export const default: T = { ... }`

I suspect that contextual typing isn't going to work here, and that getTypeofVariableOrParameterOrProperty is the only way to do this right.

**Comment by a-tarasyuk** [comment]
`checkObjectLiteral` uses `checkExpressionForMutableLocation`/`checkPropertyAssignment` which depends on `getContextualType` (`isLiteralOfContextualType(type, contextualType))`) to set `prop.type`. Do we need to continue to use _widened_ type for props in this case?

**Comment by sandersn** [comment]
I had forgotten about your work in #45342. Now that I re-read that, I see that you *already* wrote the code in getTypeOfVariableOrParameterOrProperty. Thanks for your follow-up explanation pointing out the source of the bug. It cleared up my confusion.

**Review by sandersn — APPROVED** [review]

**Comment by nicojs** [comment]
Thanks a lot for fixing!

**Pull request merged**
