### PR TITLE
do not crash when variable and function declarations collide

### LINKED ISSUE #5160: Compiler crash when variable has same name as a function with overloads
```TypeScript
var f = 10;

export function f();
export function f() {
}
```

```
Description:

getSemanticDiagnostics('C:\Users\drosen\AppData\Local\Temp\~vs212F.ts')

StackTrace:

Error: Debug Failure. False expression: 
   at assert (:1559:17)
   at reportImplementationExpectedError (:22811:29)
   at checkFunctionOrConstructorSymbol (:22902:17)
   at checkFunctionLikeDeclaration (:23399:21)
   at checkFunctionDeclaration (:23366:17)
   at checkSourceElement (:25187:21)
   at forEach (:866:17)
   at checkSourceFileWorker (:25380:17)
   at checkSourceFile (:25362:13)
   at getDiagnosticsWorker (:25422:17)
   at getDiagnostics (:25413:17)
   at Anonymous function (:35824:17)
   at runWithCancellationToken (:35800:17)
   at getSemanticDiagnosticsForFile (:35820:13)
   at getDiagnosticsHelper (:35775:17)
   at getSemanticDiagnostics (:35790:13)
   at getSemanticDiagnostics (:43916:13)
   at Anonymous function (:49157:17)
   at simpleForwardCall (:49016:9)
   at forwardJSONCall (:49032:13)
   at forwardJSONCall (:49078:13)
   at getSemanticDiagnostics (:49156:13)


---------------------------
Abort   Retry   Ignore   
---------------------------

### PR DESCRIPTION
**Pull request by vladima**
fixes #5160

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by paulvanbrenk** [comment]
Can you create a PR to cherry pick this into release 1.7?

**Comment by vladima** [comment]
this new PR will conflict with #5664 since they change the same part of the code. Can we just include this change as another commit to #5664

**Comment by paulvanbrenk** [comment]
Sure

**Comment by mhegazy** [comment]
Lets get this in 1.7 as well

**Pull request merged**
