### PR TITLE
Consider all union types matching discriminator for excess property checks

### LINKED ISSUE #51873: Unions with overlapping discriminator property do not perform internal excess property checks
# Bug Report

[Discriminating unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) provide a means for type narrowing based on a discriminator property. The first property common to all union constituents is taken as the discriminator property.

If object literals provide a discriminator value, their expected shape gets narrowed to the corresponding union constituent. Excess properties from other constituents (or completely unrelated properties) raise an excess property check (EPC) error.

At present this only works if there is a single matching candidate constituent for the object literal being tested. If two or more types within the union match the provided discriminator value, EPC accepts properties from the _entire_ union - even though only a subset actually matched.

EPC should continue to work with the subset of matching constituents, not the entire union.

---------------

The use-case I have in mind for overlapping discriminators is to specify optional properties that may (only) be present in the object literal for specific discriminator values.

```ts
interface Common {
    type: "A" | "B" | "C" | "D" | [...many];
    n: number;
}
interface A {
    type: "A";
    a?: number;
}
interface B {
    type: "B";
    b?: number;
}

type CommonWithOptionals = Common | (Common & A) | (Common & B);
```

Because of the above issue, `{ type: "a", n: 1, a: 1, b: 1 }` does not raise an EPC error, even though it is clearly invalid.

The alternative is to specify something along the lines of `(Common & { type: "C" | "D" | [...many]> })`(?), or the [StrictUnion<> approach](https://github.com/microsoft/TypeScript/issues/20863#issuecomment-520551758), but this is quite cumbersome. It may also be the case that `Common` is a class rather than an interface, or is otherwise an important type of its own, so subtracting from it may not be suitable.

It is worth noting that `if (obj.type === "A") obj.a` still throws `TS(2339): Property 'a' does not exist on type 'Common | (Common & A)'`. While this might seem to defeat the purpose of a discriminating union, the goal is merely to ensure correct EPC. We are still explicitly accepting both types, independently of each other. Type guards and `in` checks can then be used to access `A` as intended.

------

### 🔎 Search Terms

discriminator 
union
overlap
excess property check

Similar but subtly different to #20863.

### 🕗 Version Information

v5.0-next
v4.9.4

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unions and discriminators.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&isolatedModules=true&exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgApyhcyDeAoZQ5MATwAcIAuZAIhgHt6bkAfWgIw2bZs4C8aAbgJEE9ALbj6IAPzUQAV3HtowgL548oSLEQoAQhlwjCpCtV5dhRZJyhzki5arwat4aPCTJDfYzbMqDjgBayJ+BycVKHVNQOQAVRBgaWQAXjQMLDBWZAAKdExsADIfDABKXIKskrK+cuE8GAUQBDAUkGIIAGcwPJaO6iSOypw3SF68-ADyILpGGlcGvAm+6aJAiwYmABoTWwxqAEZkAHpT5EBQcmQAFQBlPIAmAGYAFgBWcuoAeXYAKwgbWQABtgDo4MDkOI4CRkNJgbDuhQEMAYLCANYgegAd06ZCg9AoUHaPR2yDgIAAJsgAOR2GnISn0HqOeg5CAAD2AvWQoGIs1phWyNIAdEthKspvtNsEoDQ9jY7MdxSsemtpbMLHZ5fslcgjgrwiFjmcLoAZcmQADl6MhoAT7CrJetTJrZTrFYd9YbCPwLEdmOdkIBlcluD0eL0eX1uAppvSgoAA5gzuaycnBut1gAmQHB2MCUGAbfEaVFoKLHWqpTNzG7vQcoMc676vabkBbrbaoPaZPsWqDehBKSbA9d7k83p8fv9ATlQeDIdDYfDEcjURisbjkPjCdASd0yRTqTS+9zIJSGUyWVj2VyeXzi8NpOW1Ms8JyyPRibg1IIgA)

### 💻 Code

```ts
interface Parent {
    type: "foo" | "bar" | "baz";
}

interface Bar {
    type: "bar";
    bar?: number;
}

interface Baz {
    type: "baz";
    baz?: number;
}

type Union = Parent | Bar | Baz;

function test(union: Union) {}

test({
    type: "foo",
    bar: 1 // ✅ TS(2345): Object literal may only specify known properties, and 'bar' does not exist in type 'Parent'.
});
test({
    type: "bar",
    bar: 1,
    baz: 1 // ❌ No error?
});
```

### 🙁 Actual behavior

EPC error raised for single matching discriminated type (`Parent`), no error raised for combined matching types (`Parent | Bar`).

### 🙂 Expected behavior

EPC error raised in both cases, because `{ baz: number }` should only be present for `Baz` interface, which would have required `{type: "baz" }`.

### PR DESCRIPTION
**Pull request by nebkat**
[Discriminating unions](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) provide a means for type narrowing based on a discriminator property. The first property common to all union constituents is taken as the discriminator property.

If object literals provide a discriminator value, their expected shape gets narrowed to the corresponding union constituent. Excess properties from other constituents (or completely unrelated properties) raise an excess property check (EPC) error.

Previously this only worked if there was a single matching candidate constituent for the object literal being tested. If two or more types within the union matched the provided discriminator value, EPC accepted properties from the _entire_ union - even though only a subset actually matched.

This PR improves on this behavior to correctly consider only the matching subset.

Fixes #51873

### CODE REVIEW

**Comment by nebkat** [comment]
@microsoft-github-policy-service agree

**Comment by jakebailey** [comment]
@typescript-bot test this
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot test tsserver top100
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

**Review by weswigham — APPROVED** [review]
I think this approach is pretty reasonable, and, moreover, removing the `isTypeIdenticalTo` check is very performance positive. I need to run DT on this, but we should take it provided there's no unforseen breaks.

**Comment by weswigham** [comment]
@typescript-bot run dt

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
I hit "rerun" on the above; want to see if that works to fix the problem temporarily rather than rerunning from scratch.

**Comment by jakebailey** [comment]
@typescript-bot run dt

**Comment by jakebailey** [comment]
That DT error looks correct, but, it's a little weird: [Playground Link](https://www.staging-typescript.org/play?ts=4.9.5&ssl=16&ssc=1&pln=15&pc=3#code/KYDwDg9gTgLgBDAnmYcBCBDAzsAgjGKASwCMBXGYAHgBUA+OAXjgG8BYAKDm4WWAH4AXHCyEiAOwDmcAD5wy4gCbAAZhOCKA3Jx5wowAI5ki+xULgkIEADbAM42fKWr1WnT2UqMZazCw0IcxpHBU9XbQ4AXwjOUEhYXhQ4fDFySiZ3bjlRYilMxwBlMSkU4jTgfLkAOTIAWxJgKFLSCgquHjkAeXFgAO68AjLWzljwaHgkJKLcyWbypnRsAdTWqhyJSQYAMlZ8yeBhAHJ1qUOI6JGOOPHE1Br6xrnWhcwcJ8oqcTqGqG3d9u4+yOXweUDO+W8MAgAElxABjfS1YDiGDmSw2OwOOShFw9NxRGJXMYJfZwfp9HrvVDMV7LIYfeyIP7sAFwWoQZTWYQnSTnQlwiDiURwDCDFqULDCKkLFm6IFwY7FSSHAA0EIoMPhiORMGEhDIwDVrP0RhMGj1UANRouHCAA)

Comment out `| OneToOneAttribute` and the error above appears in stable. So, I guess it's correct and I can just update the DT test?

**Review by jakebailey — APPROVED** [review]
LGTM but maybe we should add the above as a test case?

**Comment by weswigham** [comment]
@jakebailey do we just want to make a followup PR that adds the test case?

**Comment by jakebailey** [comment]
Sure, if the author isn't available to do it. I can send it or you can if you have the time. DT has to be fixed too.

**Comment by jakebailey** [comment]
We can also push to this PR too.

**Comment by jakebailey** [comment]
I just pushed the test onto the PR, so we should be good to merge this. I'll send the PR to DT.

**Comment by weswigham** [comment]
Solid, I just figured since it was 4 months since the author opened the PR, and we didn't see any engagement while we were probing the PR, we maybe shouldn't expect prompt implementation of a nice-to-have 😆

**Comment by jakebailey** [comment]
Well, good thing we didn't merge, baseline differs from main. Also, I think I put the test in the wrong place.

**Pull request merged**
