### PR TITLE
port 5662 into release-1.7

### PR DESCRIPTION
**Pull request by vladima**
ports #5662

### CODE REVIEW

**Comment by vladima** [comment]
pinging @mhegazy

**Comment by DanielRosenwasser** [comment]
Does this fix #5160 as well?

**Comment by mhegazy** [comment]
:+1:

**Comment by vladima** [comment]
no this PR does not fix #5160, I've submitted the fix to master in #5670 and I can also cherry-pick it into this PR since this is the same bits in the codebase (/cc @mhegazy)

**Pull request merged**
