### PR TITLE
Fix parameter destructuring issues

### LINKED ISSUE #4937: Can't use destructuring parameter with inferred generic type
```typescript
class GenericClass<T> {
  payload: T;
}

var genericObject = new GenericClass<{greeting: string}>();

function genericFunction<T>(object: GenericClass<T>, callback: (payload: T) => void) {
  callback(object.payload);
}

// Works
genericFunction(genericObject, (payload) => {
  // Here TS understands that payload have a property greeting
  // and that payload.greeting is a string.
});

// Fails to compile with "Type 'T' has no property 'greeting' and no index signature.".
// Type of greeting is any
genericFunction(genericObject, ({greeting}) => {

});
```

### LINKED ISSUE #4949: Type inference when destructuring a lambda parameter doesn't work
Paste this snippet in the [playground](http://www.typescriptlang.org/Playground):

```typescript
const result = [{ foo: 'hello' }]
	.map(({ foo }) => foo)
	.map(foo => foo);
```

If you hover over `foo` in the first `map()` call, you'll notice that its type is `any` (should be `string`).

The type of `result` is correctly inferred to be `string[]`, though. It just seems that there is no type information for destructured function parameters.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #4937.
Fixes #4949.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@vladima Would be good if you could look this over.

**Comment by DanielRosenwasser** [comment]
@ahejlsberg does this fix #4818 as well? Can you add a test if so?

**Comment by vladima** [comment]
:+1:

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Yes, this is the same issue. Will add example from #4818 to my test.

**Comment by DanielRosenwasser** [comment]
:+1:

**Pull request merged**
