### PR TITLE
Rest type

### PR DESCRIPTION
**Pull request by sandersn**
Add rest types. They implement the semantics of object rest as detailed in the second part of the proposal #10727. I have copied and updated that proposal here.

Notes:
1.  Rest types are *not* difference types and are *not* usable as the constraint of a mapped type.
2. The nested rest-type relationships are not implemented yet because I'm not sure if they are worthwhile.

# Rest types

The rest type is the opposite of the spread type. It types the TC39 stage 3 object-rest destructuring operator.  The rest type `rest(T, 'a' | 'b' | 'c')` represents the type `T` after the properties `a`, `b` and `c` have been removed, as well as call signatures and construct signatures. 

A short example illustrates the way this type is used:

``` ts
/** JavaScript version */
function removeX(o) {
  let { x, ...rest } = o;
  return rest;
}

/** Typescript version */
function removeX<T extends { x: number, y: number }>(o: T): rest(T, 'x') {
  let { x, ...rest }: T = o;
  return rest;
}
```

## Syntax

The syntax is `rest(T, U)` where `T` is any type and `U` is `string` or a union of string literals (including `never` and single string literals).

## Type Relationships
- `rest(A, never)` is not equivalent to `A` because it is missing call and construct signatures. 
- `rest(A | B, 'a')` is equivalent to `rest(A, 'a') | rest(B, 'a')`.
- `rest(A, string)` is equivalent to `{}`.
- `rest(rest(A, 'a'), 'b')` is equivalent to `rest(A, 'a' | 'b')` and therefore also to `rest(rest(A, 'b'), 'a')`.

## Assignment compatibility
- `rest(T, 'x')` is not assignable to `T`.
- `T` is assignable to `rest(T, 'x')` because `T` has more properties and signatures.
- `rest(T, V)` is assignable to `rest(U, W)` if `T` is assignable to `U` and `V` is assignable to `W`.

## Properties and index signatures

The type `rest(A, P)` removes `P` from `A` if it exists. Otherwise, it does nothing. `A` retains its index signatures unless `P` is `string`.

## Call and Construct signatures

`rest(A)` does not have call or construct signatures.

## Precedence

Rest types are just below the keyof operator in precedence.

### CODE REVIEW

**Comment by Igorbek** [comment]
Suggestion:
- `rest(T, keyof U)` is equivalent to `{}` when `U` is assignable to `T`

**Comment by tinganho** [comment]
Doesn't this break some design consistency?

All value argument lists are now delimited with braces `()`.  And all type argument lists are now delimited with brackets `<>`.

This PR adds a `rest` keyword and a type argument list delimited with `()`.

Since, I regard `Pick<T>`, `Partial<T>`, `Readonly<T>`as type operators. I would rather see Rest<T, 'x', 'y'>.

**Comment by sandersn** [comment]
@Igorbek I didn't call it out sufficiently in the proposal text above, but the second argument of `rest(T, U)` can *not* be generic. It has to be a string or string literal union [1]. So there's no way to construct a generic `rest(T, keyof U)`. And there's no other way to construct a string union that covers all possible properties of `T`.

[1] The reason that the second argument is not generic is that it's impossible to produce a generic object rest &mdash; you have to hard-code the names of properties that will be removed in the object destructuring/binding.

@tinganho I don't have a strong design opinion one way or another on the syntax. The only constraint is that we expect rest and spread types to be used rarely, especially rest types, so I don't want to use `T - U` as the syntax, because we'll probably want to use that for something else some day. 

How about we gauge the community's preference by using :+1: to your comment to indicate `Rest<T, 'x' | 'y'>`, :-1: to indicate `rest(T, 'x' | 'y')` and :confused: to indicate something else. I see we already have 2 more votes for `Rest`.

**Comment by rozzzly** [comment]
```typescript
interface FooBar {
    foo: string;
    bar: string;
}
interface Foo {
    foo: string;
}
interface Bar {
    bar: string;
}
```
would `Rest<FooBar, keyof Foo>` be equivalent to `Bar`?

**Comment by tinganho** [comment]
@sandersn thanks for your comment. Sorry, that I didn't discovered your initial proposal earlier(I just read the spread part).

I think, I understand why you use lowercase `rest` here. I guess, it is to indicate an intrinsic type operator. Though, I don't really, like the special casing of the type system here. Even if we use capitalized `Rest<T, 'x', 'y'>`. May I suggest something more of a generic solution that might cover this special case? I have thought about it for months, but haven't had the time to submit it yet.

**Comment by Igorbek** [comment]
@sandersn I see what you mean. But isn't that the case for computed properties?
Currently this works, however is not properly typed:
```ts
const b = "b";
let c = { [b]: b, a: 10 }; // c is { [x: string]: string | number, a: number; }
let { [b]: b1, a: a1 } = c; // b1 is any; a1 is number
```
so should this be restricted then?
```ts
const b = "b";
let rest = { a: 10 };
let c = { [b]: b, ...rest };
let { [b]: b1, ...rest1 } = c; // BTW, this is allowed by the spec and Babel supports it
```
and generic case:
```ts
function destructure<T, U extends keyof T>(src: T, name: U): { value: T[U]; rest: rest(T, U); } {
  const { [name]: value, ...rest } = src;
  return { value, rest };
}
```
just thinking out loud

**Comment by sandersn** [comment]
@rozzzly Yes.

@tinganho I would much prefer a general solution too; I tried to make something work with mapped types already. Maybe you can use these problems that I ran into to come up with something:

1. There are too many quirks in rest's semantics to use it as a real basis for generalisation. (Why drop methods and call signatures? Because the definition is based on `Object.assign`, of course!) But the general solution still has to work for rest.
2. Set difference of literal unions is the obvious general candidate, but doesn't really solve any compelling problems besides rest. At least I couldn't think of any.

**Comment by aluanhaddad** [comment]
Although I don't love the proposed rest syntax I don't really care for the generic type syntax either in this case. The advantage of not introducing new syntax is just that it would allow a better syntax to be introduced, preferably one that covered more type operators, in the future without causing confusion because it would be a shorthand or sugar as opposed to an alternate manifest form.

**Comment by tinganho** [comment]
@sandersn So I submitted my idea to the issue tracker, though it is very rough. Though my initial idea was to solve typings for ORMs, but it seems it can apply to `Rest<T, 'x', 'y'>` as well. Please checkout #13500.
```ts
type Rest<T, ...S extends string[]> => {
    type Type;
    for (KT in T) {
        type IsInS = false;
        for (KS of S) {
            if (S[KT] != undefined) {
                IsInS = true;
            }
        }
        if (!IsInS) {
            Type[KT] = T[KT]
        }
    }
    return Type;
}
```

**Comment by sandersn** [comment]
@Igorbek 
1. Even with a call to `destructure`, the compiler can't know what the *value* of the thing is, just the type, which is just some set of string literal types:

```ts
function concrete(tricky: keyof (typeof c)) {
  return destructure(c, tricky)
}
```

This might remove `a` and it might remove `b` from `c: { a: number, b: string }`. Should `concrete` return `{}`? There is no useful way to avoid hard-coding the field names in a rest type.

2. The spec, babel and the typescript emitter all support computed properties with rest &mdash; check your examples in the playground to see that it handles computed properties correctly. 

The typescript checker should be compared to flow, which doesn't support the generic case either and defaults to returning `any` (or probably an object with a string indexer, because flow doesn't produce `any` as readily as typescript). Even in the non-generic case, flow and typescript both fail to remove the computed property from the rest type if it's not a simple constant.

I will add an error instead. I don't like silently failing to remove properties that people asked to remove.

@aluanhaddad I hoped that introducing new, *bad* syntax would have nearly the same benefits as not introducing new syntax at all, with the added benefit that the syntax for generic types stays consistent.

**Comment by PyroVortex** [comment]
So, does the rest operator finally allow the strict typing of applying `map` to a homogenous tuple type of arbitrary length without a large number of overloads?
```ts
declare function map<A extends Array<T>, T, U>(input: A | [void], operator: (t: T) => U): Array<U> & { [P in keyof rest(A, keyof Array<T>)]: U };

const x = map([1,2,3], (x: number) => x.toString()); // x should have type [string, string, string], or at least one that has all the same semantics
```

Alternatively, if you want to generate invariant tuples:
```ts
function asInvariantTuple<A extends Array<any>>(input: A | [void]): rest(A, keyof []) & { readonly length: A['length'] } {
    return input;
}

const y = asInvariantTuple([1, 2, 3]); // y has type { 0: number, 1: number, 2: number, length: number }
```

**Comment by raveclassic** [comment]
Can't wait for this to land! 
I feel helpless everytime I try to type a React HOC which reduces child props. :)

**Comment by sandersn** [comment]
@raveclassic do you mind giving a miniature example that I can turn into a test case? I would like to make sure that scenario works.

**Comment by mkusher** [comment]
@sandersn the most common example is https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

let's say we have a component:
```typescript
type Props = {
   a: number;
   b: number;
   c: number;
};

function Component(props: Props) {
  return (<div>{props.a}{props.b}{props.c}</div>);
}
```

the simplest example for HOC is:
```typescript
function pass5AsA<P>(Decorated: ComponentClass<P>): ComponentClass<rest(P, "a")>;
```
but it's not very common, I think. Usually it would be something like:
```typescript
type DecoratedComponent<DecoratorProps> = <InternalProps>(component: ComponentClass<InternalProps>): ComponentClass<rest(InternalProps, keyof DecoratorProps)>;
function decorateWithProps<P>(someProps: P): DecoratedComponent<P>;
```

**Comment by raveclassic** [comment]
@sandersn Sure, here's another example. I've omitted React for simplicity:
```typescript
type TControlledProps<TValue> = {
  value: TValue | undefined,
  onChange: ((value?: TValue) => void) | undefined
}

type TStatefulProps<TValue> = {
  defaultValue?: TValue,
  value: never,
  onChange?: TControlledProps<TValue>['onChange']
}

class Component<TProps> {
  constructor(props: TProps) {

  }
}

function stateful() {
  return function decorate<V, P extends TControlledProps<V>>(Target: Component<P>): Component<Rest<P, keyof TControlledProps<V>> & TStatefulProps<V>> {
    
  }
}

type TControlledComponentProps = TControlledProps<string> & {
  //smth more
  foo: string
}
class Controlled extends Component<TControlledComponentProps> {

}

const controlled = new Controlled({
  //structure is valid (both value and onChange are explicitly required although can be undefined)
  value: '123',
  onChange: undefined,
  foo: '123' //required param
})

const Stateful = stateful()(Controlled);
const foo = new Stateful({
  value: '123' //value is restricted here by 'never',
  defaultValue: '123', //defaultValue and onChange are not required but may be present
  onChange() {
  },
  foo: '123' //still required param
})
```

@mkusher's example is still absolutely correct

**Comment by sandersn** [comment]
Thanks @mkusher and @raveclassic. I also found the simple example at https://facebook.github.io/react/docs/higher-order-components.html to be useful:

```js
render() {
  // Filter out extra props that are specific to this HOC and shouldn't be
  // passed through
  const { extraProp, ...passThroughProps } = this.props;

  // Inject props into the wrapped component. These are usually state values or
  // instance methods.
  const injectedProp = someStateOrInstanceMethod;

  // Pass props to wrapped component
  return (
    <WrappedComponent
      injectedProp={injectedProp}
      {...passThroughProps}
    />
  );
}
```

**Comment by Igorbek** [comment]
@sandersn I also just yesterday reviewed [a PR to `styled-components`](https://github.com/styled-components/styled-components/pull/521#discussion_r102071835) where I pointed to this very awaited feature.

Please also note from the examples provided by @mkusher and @raveclassic, that people are expecting to use it with generics on a right-hand side. You were against it, weren't you?

**Comment by raveclassic** [comment]
@Igorbek That's why I expect to use `Rest` with `keyof` on the right side which returns a string literal union.
@mkusher also used just a string literal.

@sandersn According to your words: 
> [1] The reason that the second argument is not generic is that it's impossible to produce a generic object rest — you have to hard-code the names of properties that will be removed in the object destructuring/binding.

I'm very far from TS internals so I don't get the problem with generic - is it impossible to resolve string literal union via `keyof` when generic is on the right side of `Rest`? Because in all other cases typesystem is able to resolve it.

**Comment by sandersn** [comment]
@raveclassic your example uses `keyof` with a type parameter as its argument, which isn't supported by the current PR. Currently, this PR only supports actual strings or string unions, which of course can be produced by `keyof`, but only when its argument is an object type. That's because (1) I couldn't think of a way to strip off arbitrary properties using object rest destructuring and (2) the rest type is *much* simpler without a generic right side. 

What is the body of `decorate`? Does it use object rest destructuring?

**Comment by raveclassic** [comment]
@sandersn Ahh, I see the difference now.
Yes, it uses destructuring. My example is too simplified and is incorrect due to class constructors (because of omitted React) but it reflects the idea that a HOC wrapper provides some required values to its child but does not require them itself. Your example from official facebook doc fits much more.

Still I've tried to adopt `decorate` to react:
```typescript
type TStatefulState<TValue> = {
	value?: TValue
};
export function stateful() {
	return function decorate<V, P extends TControlProps<V>>(Target: React.ComponentClass<P>): React.ComponentClass<Rest<P, keyof TControlProps<V>> & TStatefulProps<V>> {

		class Stateful extends React.Component<Rest<P, keyof TControlProps<V>> & TStatefulProps<V>, TStatefulState<V>> {
			componentWillMount() {
				this.setState({
					value: this.props.defaultValue
				});
			}

			render() {
				//destructuring here
				const {onValueChange, defaultValue, ...rest} = this.props;

				return React.createElement(Target, { //tsx... :(
					...rest,
					value: this.state.value,
					onValueChange: this.onValueChange
				});
			}

			protected onValueChange = (value?: V): void => {
				this.setState({
					value
				});
				const {onValueChange} = this.props;
				onValueChange && onValueChange(value);
			}
		}

		return Stateful;
	};
}
```

The key point is to be able to use original `Controlled` that requires `TControlledProps` along with its `Stateful` version that injects that props and does not require them.
I ses that this PR is only about object types then if I coould manually specify keys like `Rest<P, 'onChange' | 'value'>` - that would be enough. However supporting generics would be much more helpful.

**Comment by sandersn** [comment]
@raveclassic I misread your example &mdash; it's more complex than I thought at first. `decorate` *will* work with the current implementation of rest types because the right side is `keyof TControlProps<V>`, which is known to be `"value" | "onChange"`, unlike something like `keyof V`, which is unknown.

But in this case, couldn't `Stateful` extend `React.Component<TStatefulProps<V>>` ? The definitions of `TControlProps` and `TStatefulProps` is so similar that it seems superfluous to remove one via `rest` and add the other via `&`. If you use `TStatefulProps`, then you just have to make sure that it's a subclass of `TControlProps` by making `onChange` optional in both. (`onChange` already allows `undefined` in `TControlProps`, which is almost equivalent.)

**Comment by Igorbek** [comment]
@sandersn You claimed that the reason for restriction of using generic types here is that you do not know any possible way to produce an instance of `rest(T, U)` by having an instance of `T` without explicitly enumerating fields to remove. But that is not the only use case. The type itself has more useful properties, such as what can be used in the React HOCs.
The most important property of the rest type is this (which you didn't mention in the proposal):
- `rest(T, keyof U) ... U` is assignable to `T`
- however `U ... rest(T, keyof U)` is **not** assignable to `T`, because `rest(T, keyof U)` can have conflicting properties with `U`

By having this property, we can prove this:
```ts
declare const r: rest(T, keyof U);
declare const u: U;
const t: T = { r, ...u }; // this is proven now
```

That is exactly what we need for React HOC generalization.

**Comment by sandersn** [comment]
You are right that I claimed that the only useful way to produce a rest type is from an object rest destructuring. The reason is that the ES spec defines both object rest and object spread as removing call signatures and non-own, non-enumerable properties, which Typescript approximates as class methods. 

That means that basic identities just break down:

1. `{} ... T` is not assignable to `T`.
2. `rest(T, never)` is not assignable to `T`.

I considered adding a non-ES-based type similar to the intersection type called the difference type and then defining `rest` in terms of difference. But [in January I arrived at the conclusion that it required too many additional features](https://github.com/Microsoft/TypeScript/pull/13470#issuecomment-272663004) and that I couldn't find examples of any additional problems that difference solves on its own. In particular, I'm waiting to see existing Javascript code that can't be typed in Typescript right now.

**Comment by Igorbek** [comment]
Ah, yes, you're right. This rules are breaking basic identities.
We can still have some type relations in this form:
- `rest(T, keyof U) ... U` is assignable to `{} ... T` (_at least we removed redundant `U` type_)

As an example of generic HOC could be:

```ts
const withProps =
  <P>(props: P) =>
    <T /* missing constraint that P extends T */>(Component: Component<T>) =>
      (innerProps: rest(T, keyof P)) =>
        <Component {...{innerProps, ...props}} />

const Sample = (props: { a: string; b: string; }) => <div>{a + b)</div>;
<Sample a='hello, ' b='world' />

const HelloSample = withProps({ a: 'hello, '})(Sample);
<HelloSample b='world' />
```

An alternative approach could be using something like _Mapped conditional types_ #12424 where properties could be filtered out or replaced with some other type (like, make some members optional).

**Comment by Igorbek** [comment]
And one more alternative:

```ts
const withProps =
  <P>(props: P) =>
    <T>(Component: Component<{...T, ...P}>) =>
      (innerProps: T) =>
        <Component {...{innerProps, ...props}} />
```

This is perfect typing, but the issue here is that type is not inferred (I'd like it would).

**Comment by raveclassic** [comment]
@sandersn Maybe I should have not included ` | undefined` in my example - it's a bit confusing, so let's omit it.
`TStatefulProps` cannot inherit `TControlledProps` because then `ComponentClass<TStatefulProps>` would require passing `value` each time to `Stateful` components while they hold this value inside their state and should not accept any. 
So generally a HOC _injects_ some required props to its child and also makes it possible to render this wrapped child without specifying these props like it's shown in @Igorbek's example with `Sample` and `HelloSample`.

**Comment by raveclassic** [comment]
Is there any way of seeing this merged at least without support of generics?

**Comment by panuhorsmalahti** [comment]
How about using `\` (inspired by the complement of a set) for the syntax? e.g.:

```
function removeX<T extends { x: number, y: number }>(o: T): T \ 'x' {
```

**Comment by tycho01** [comment]
Perhaps this could be solved with a syntax closer matching JS (avoids syntax clash, keeps learning curve low) with the type-level destructuring explored in #10727: `type { a, ...Rest } = { a: 1, b: 2 };`.

Maybe then one might grab them from objects and/or unions using a spread as well, hopefully allowing for straight-forward support for generics:

```ts
// destructure object
type Obj = { a: 1, c: 3 };
type { ...Obj, ...Rest } = { a: 1, b: 2 };
// Rest: { b: 2 }
```
Note `Obj`'s role becomes more pattern-matching (leaving the rest for that `...Rest`) than assignment.
Questions on most desirable behavior:
* error if the values for keys in `Obj` don't match?
* ignore unused keys in `Obj`? or error?
* variance?

Alt.: destructure unioned keys
```ts
type Obj = { a: 1, c: 3 };
type Keys = keyof Obj; // 'a' | 'c'
type { ...Keys, ...Rest } = { a: 1, b: 2 };
// Rest: { b: 2 }
```
Notes:
* destructuring unions here is new -- JS never had unions
* `Keys` is a union of keys (pattern-matched to pass on whatever remains), while `Rest` is assigned an object here

@sandersn:
> I arrived at the conclusion that [set difference of literal unions] required too many additional features

Hm. I forgot if I got it from another thread, but I'd imagined this as a unary negating operator `~`, such that `~1` would mean "a type that is not `1`", so a difference might be expressed as `(1 | 2) & ~1` (-> `2`).

That said, it doesn't necessarily just revert union operations -- `(1 | number) & ~1` would produce not `number`, but `number & ~1` (ditto for unresolved generics, `(A | B) & ~B` -> `A & ~B`).

I could theoretically foresee small use-cases e.g. `number & ~0` (useful for typing a safe division operation?), but honestly can't think of much outside of calculating object difference either.

If you foresaw needing 'many additional features' I suppose I didn't get quite as far in exploring further considerations though.

**Comment by tycho01** [comment]
Tried for a bit more to do a union difference operation using today's syntax.

```ts
type UnionDiff1<Big extends string, Small extends string> = UnionDiff<Big, Small>[Big] /*!*/;
type test1 = UnionDiff2<'a' | 'b' | 'c', 'b' | 'c' | 'd'>;
```
This yields `"a" | "b" | "c"` instead of just `"a"`. Somehow having the `[Big]` index operation directly in there fails -- help appreciated!

Second attempt, separate the steps...
```ts
type UnionDiff2<Big extends string, Small extends string> =
  {[K in Big]: { 1: Union2Keys<Big>[K], 0: undefined }[NotS<UnionHas<Small, K>>]} //[Big] /*!*/;
type A = UnionDiff<'a' | 'b' | 'c', 'b' | 'c' | 'd'>;
// now manually do that second step...
type Big = 'a' | 'b' | 'c';
type B = A[Big];
```
This returns either `"a"` (yay!), or `"a" | undefined` if `strictNullChecks` are enabled.

The `strictNullChecks` scenario could be fixed if the assertion operator `!` were exposed on the type level... if my first attempt could be made to work as well, could that perhaps be an elegant route to tackle this feature?

**Comment by jaen** [comment]
How about trying `never` instead of `undefined`? It seems to be working for me in strict mode:

```typescript
type UnionDiff2<Big extends string, Small extends string> =
  {[K in Big]: { 1: Union2Keys<Big>[K], 0: never }[Not<UnionHas<Small, K>>]} //[Big] /*!*/;
type A = UnionDiff2<'a' | 'b' | 'c', 'b' | 'c' | 'd'>;
// now manually do that second step...
type Big = 'a' | 'b' | 'c';
type B = A[Big];

let testYes: B = "a"; // typechecks
let testNo: B = "b";  // fails
```

PS nice type level magic. Kind of sad this works only for string literal types, not arbitrary types due to index signature limitation though.

**Comment by tycho01** [comment]
@jaen: progress! thanks for that! 😄

I'll concede the limitation is unfortunate, yeah. Out of curiosity though, what's your use-case?
They probably closed #4183 under the impression this covered most, as seen in @sandersn's quote:
> I couldn't find examples of any additional problems that difference solves on its own

I couldn't think of much either, hence I'm all the more curious. :)

**Comment by jaen** [comment]
Depends on use case of what you're asking about. If we're talking about subtracting of arbitrary types from union (which is what led me here) it's fairly simple, our codebase uses tsmonad with strict null checks leading to some annoying issues, for example:
```typescript
const maybe: <T>(value: T) => Maybe<T> =
    (value) =>
        !!value
            ? Just<T>(value)
            : Nothing<T>();

maybe(null)
    .fmap(x => x + 2); // complains about `x` being possibly null, even though
                       // `fmap` will by definition be only called with inhabited
                       // `Just` values
```
which could be alleviated with something like either of (or preferably both):
```typescript
const betterMaybe: <T>(value: T) => Maybe<T - null | undefined> = …;
// alternatively by lifting non-null assertion to type level
const betterMaybe: <T>(value: T) => Maybe<T!> = …;
```

Is that a satisfactory answer?

**Comment by tycho01** [comment]
@jaen: hmm. what if you'd write say `.fmap(x => x! + 2)`? type-level `!` would be nicer, but yeah...

**Comment by jaen** [comment]
Yeah, I am aware of the non-null assertion`, but this has the overhead of having to write it out inside each `fmap` lambda, which is suboptimal. It would be nice to solve this in one place with a proper type.

As for your suggestion — this will work I assume, but will require me forking tsmonad and modifying the source, which I wanted to avoid. Being able to do this on the type level has the added benefit on being able to do it in a local typings file to shadow the library's type.

So that's my use case, I guess — this can be done otherwise, by writing down a non-null assertion at each use site or forking and modifying the library to work with strict null checks, but both feel fairly inelegant to me.

**Comment by tycho01** [comment]
@jaen:
Hmm. In this particular case, if I were you I'd just make a PR to `tsmonad`, since this seems like a fairly beneficial change, wouldn't suspect it to be particularly controversial.

From the TS team's perspective, I suppose a general solution was considered fairly involved, in the sense it'd require introducing negation types ('a type that is not `T`'), for one.
That said, the logic that would solve your current use-case appears to be implemented already in that `!` operator -- in my perception, the only change needed to address this would be for them to just expose it as part of the type-level syntax as well.
Given demand for that, perhaps they'd be more open to that idea than to having to tackle the more complex generic case.

**Comment by jaen** [comment]
Hm, I guess I could consider a PR. I thought the library was dead (had improvements over last version in the repo, but no officially released package), but now that I checked it's not, so it might make sense to change that upstream, I guess.

Well, I'd probably prefer a more generic solution, since while lifting the `!` into types solves this use case, I can imagine other kinds of subtractions might come in hand in the future, but even having a type-level `!` would be nice.

Do you have any link explaining why the negation type would be needed? I would assume you can remove from a union by equality (which types already have) so I'm not sure why some not-`T` would be required to implement type union subtraction. Maybe I'm missing some use cases though.

**Comment by tycho01** [comment]
@jaen: that was [this idea](https://github.com/Microsoft/TypeScript/issues/4183#issuecomment-238037194). There may well be ways without it. I personally just hope `-` will still be introduced for type-level numeric substraction hahaha, perhaps that just lead me to adhering that version rather than that in the OP there.

**Comment by tycho01** [comment]
Putting things together based on @nirendy's [solution](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307614501) to work around the glitch by cutting things into steps with generics defaults:

```ts
type Obj<T> = { [k: string]: T };
type SafeObj<O extends { [k: string]: any }, Name extends string, Param extends string> = O & Obj<{[K in Name]: Param }>;
type SwitchObj<Param extends string, Name extends string, O extends Obj<any>> = SafeObj<O, Name, Param>[Param];
type Not<T extends string> = SwitchObj<T, 'InvalidNotParam', {
  '1': '0';
  '0': '1';
}>;
type Union2Obj<Keys extends string> = { [K in Keys]: K };
type Union2Keys<T extends string> = Union2Obj<T> & { [k: string]: undefined };
type UnionHasKey<Union extends string, K extends string> = ({[S in Union]: '1' } & { [k: string]: '0' })[K];

export type UnionDiff_<Big extends string, Small extends string> =
  {[K in Big]: { 1: Union2Keys<Big>[K], 0: never }[Not<UnionHasKey<Small, K>>]}//[Big];
export type UnionDiff<
    Big extends string,
    Small extends string,
    Step extends UnionDiff_<Big, Small> = UnionDiff_<Big, Small>
> = Step[Big];
type TestUnionDiff = UnionDiff<'a' | 'b' | 'c', 'b' | 'c' | 'd'>;
// ^ 'a'
```

**Comment by qm3ster** [comment]
Should this be closed?

**Comment by RyanCavanaugh** [comment]
On hold for now

**Pull request closed without merging**
