### PR TITLE
 Better error message for missing member in tslib

### LINKED ISSUE #33603: Better error message for missing member in tslib
@amcasey brought this up while upgrading Yammer to 3.6/3.7.

```
This syntax requires an imported helper named '__spreadArrays', but module 'tslib' has no exported member '__spreadArrays'.
```

The error message tells us something that is technically correct, but which is not clearly actionable. The user has no idea why `__spreadArrays` gets imported during an upgrade.

We should indicate that the user should try upgrading `tslib`.

```
This syntax requires an imported helper named '__spreadArrays' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.
```

### PR DESCRIPTION
**Pull request by m-henderson**
Please verify that:
* [x] There is an associated issue in the `Backlog` milestone (**required**) #33603 
* [x] Code is up-to-date with the `master` branch
* [x] You've successfully run `gulp runtests` locally
* [x] There are new or updated unit tests validating the change

In this PR I update the error message, generated diagnostics, update src and accepted baselines. I know that we discourage single commits but the tests didn't pass until all of these changes were made. 

This pr fixes #33603 

If there is something that needs updated or is looked over then please let me know and I will make the change. 

**Please Note** 
taggedTemplateWithoughDeclaredHelper.errors.txt was not updated when I ran the check for updating baselines. So, I manually updated the file to reflect the correct diagnostics message. If this is not recommended then let me know what should have been done and I will go back and do it. 

Thanks 😄

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks for the PR!

Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution in the commit history. You can either make sure your GitHub account is associated with the email address you're using for your commits (under Settings in GitHub), or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes. It's not a big deal!
_____

> taggedTemplateWithoughDeclaredHelper.errors.txt was not updated when I ran the check for updating baselines. So, I manually updated the file to reflect the correct diagnostics message. If this is not recommended then let me know what should have been done and I will go back and do it.

I assume this is because some tests are skipped to keep test times low. @sandersn might know better.

> This pr will solve #33603

Can you edit your PR to say "this PR fixes #33603"? GitHub automatically closes issues with key phrases.

https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by m-henderson** [comment]
@DanielRosenwasser I updated the title of the PR to reflect the changes you recommended. 

Hmm, I have never had that problem before but will look into it. If you notice this again in the future please let me know. For now, going ahead and pulling in the changes is not a problem!

**Comment by DanielRosenwasser** [comment]
Sorry, the title should explain the thing the PR does, the body should say "fixes #33603".

**Comment by m-henderson** [comment]
@DanielRosenwasser lol, I realized that right after I commented and fixed it 😆

**Pull request merged**
