### PR TITLE
Improve spread helper emit

### PR DESCRIPTION
**Pull request by sandersn**
Since `__assign` defaults to `Object.assign` if present, our own helper will never be used in ES6 and higher, and `getOwnPropertySymbols` is not needed in ES5 and below because symbols don't exist there.

### CODE REVIEW

**Comment by sandersn** [comment]
@rbuckton here's the __assign improvement you suggested.

**Comment by rbuckton** [comment]
@sandersn Can you merge master now that #11874 and #12250 are in master?

**Comment by sandersn** [comment]
Sure. Done.

**Comment by mihailik** [comment]
The premise is not strictly true. Object.assign and Object.getOwnPropertySymbols may be polyfilled (one of them or both).

It's safer to feature-detect each on separately, rather than rely on presence of one as a clue to another.

**Pull request merged**
