### PR TITLE
Adds puppeteer to test whether typescript.js runs in the browser

### PR DESCRIPTION
**Pull request by orta**
Makes it feasible to test for bugs like #35469 

It does this by using the [puppeteer](https://pptr.dev) to run the JS inside a headless copy of chromium. 

It's not on CI, but it fails correctly:

/cc @dsherret 

Screen Shot 2019-12-03 at 12 41 43 PM

### CODE REVIEW

**Comment by weswigham** [comment]
This is only worth having if we run it on CI - we _used_ to have this, but removed it because it'd constantly break (in the harness) and nobody'd notice for weeks.

**Comment by orta** [comment]
I _think_ this might be more stable then (it's only trying to run ts) - but if this is the same kind of infra we had before I'm cool with closing.

**Comment by weswigham** [comment]
I'm fine with reading it, just only if we _automatically_ check it.

**Comment by orta** [comment]
Bringing back this thread from idle-ness, @weswigham is running it on the GitHub Actions acceptable?

**Comment by weswigham** [comment]
Hm. So we added the action definitions at the request of a GH staffer to help test them, afaik. They're actually slightly incomplete compared to our devops definitions (mostly missing environment variables that make the tests to do more things, but also lacking our extended suite of definitions for on demand tasks). Unless we decide to deprecate devops (and afaik we've not), I'd rather have it as a devops definition; just so we don't have some devops-only definitions and some actions-only definitions.

**Comment by sandersn** [comment]
@orta It looks to me that this PR needs a devops pipeline definition instead of an Actions definition and it'll be ready to go. Did I get that right?

@weswigham have our plans changed re actions vs pipelines? I think I overheard a discussion about it between you and @andrewbranch.

**Comment by weswigham** [comment]
Yeah, our strategy there has changed in the intervening time. We're probably going to try to make new tasks as actions rather than pipelines, wherever possible, and probably try to port over the pipelines that already exist whenever we have time, just since it seems like msft is really going for actions being the primary msft-sponsored CI for GH (vs pipelines). This is maybe complicated for things requiring secrets? I'm not sure. But for normal test tasks, like this, everything should be OK.

**Comment by orta** [comment]
Yep, it would be complicated for things which need secrets (only forks get them) 

Perhaps more of those could be on a request basis with typescript-bot?

**Comment by weswigham** [comment]
So long as secrets can be available to manually triggered actions, yeah.

**Comment by orta** [comment]
They are ( that's how the playground PR builds get triggered )

**Comment by DanielRosenwasser** [comment]
Any thoughts on using Playwright instead so that we can get cross-browser builds?

**Comment by orta** [comment]
Sure, it wasn't public when I made this PR

**Comment by orta** [comment]
OK, this has been updated to use Playwright, here's what the errors would look like if the typescript.js doesnt run in the browser:

```
[14:01:00] Using gulpfile ~/dev/typescript/typescript-compiler/Gulpfile.js
[14:01:00] Starting 'test-browser-integration'...
[14:01:00] > /home/orta/.nvm/versions/node/v12.15.0/bin/node scripts/browserIntegrationTest.js
There was an error running built/typescript.js in chromium
Error: SyntaxError: Unexpected identifier
There was an error running built/typescript.js in firefox
Error: SyntaxError: missing ) in parenthetical
undefined
There was an error running built/typescript.js in webkit
Error: SyntaxError: Unexpected identifier 'is'. Expected ')' to end a compound expression.
[14:01:05] 'test-browser-integration' errored after 4.31 s
[14:01:05] Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/home/orta/dev/typescript/typescript-compiler/scripts/build/utils.js:54:28)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Pull request merged**
