### PR TITLE
Strip tags in placeholders

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR builds on #56434 to strip object type tags in template literal placeholders. We can merge this in case we decide to go that way.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by jakebailey** [comment]
Given the leak problem is not new, I personally prefer #56434 unless there's some major performance wins happening. I still need to test it (though I think you said you did?)

@typescript-bot pack this

@epmatsw Is there any chance you could try this build compared to nightly on your codebase from #52345? This is not a revert of #48044 (in that it doesn't reduce everything to `string`), so I'm curious as to the perf difference. Maybe if you're bored you can also try https://github.com/microsoft/TypeScript/pull/56434#issuecomment-1817043158

**Comment by epmatsw** [comment]
@jakebailey 

Doesn't seem like either has much of an effect, but it does look like something in an upcoming release did!

|Version|Time (s)|
|-------|---------|
|5.2.2|67|
|5.3.2|67|
|5.4.0-dev.20231120|47|
|#56434|49|
|#56458|49|

**Comment by jakebailey** [comment]
Curious; would be interesting to bisect that using something like https://www.npmjs.com/package/every-ts, e.g.:

```console
$ every-ts bisect start
$ every-ts bisect old 5.3.2
$ every-ts bisect new 5.4.0-dev.20231120
$ every-ts tsc ...
$ every-ts bisect <old|new>
...
```

**Comment by epmatsw** [comment]
5.4.0-dev.20231107 seems to be the first "fast" version

**Comment by jakebailey** [comment]
Oh, right. And that actually helped on your real-world case? That's good, at least, though a little suspect to be narrowing something to itself.

**Pull request closed without merging**
