### PR TITLE
Fix es2015.collection regression

### LINKED ISSUE #6500: Remove WeakMap/WeakSet#clear method
changes:

```diff
// lib.es6.d.ts and lib.core.es6.d.ts
// also WeakSet
 interface WeakMap<K, V> {
-    clear(): void;
     delete(key: K): boolean;
     get(key: K): V;
     has(key: K): boolean;
     set(key: K, value?: V): WeakMap<K, V>;
     [Symbol.toStringTag]: "WeakMap";
 }
```

https://tc39.github.io/ecma262/#sec-weakmap-constructor
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
https://bugzilla.mozilla.org/show_bug.cgi?id=1101817

### LINKED ISSUE #10695: Regressions of lib.d.ts
Must fix regressions such as #6500. We need to get other regressions investigated. #6500 is regressed now.

### PR DESCRIPTION
**Pull request by zhengbli**
Fixes #6500
Fixes #10695

### CODE REVIEW

**Comment by mhegazy** [comment]
👍

**Comment by mhegazy** [comment]
@zhengbli can you port this to release-2.0

**Comment by mhegazy** [comment]
Interfaces are augmentable. So you can define them back if you are sure they exist in your runtime.

**Comment by GoToLoop** [comment]
It doesn't exist anymore! That's why I said what a pity! Thx anyways.  :+1:

**Pull request merged**
