### PR TITLE
Enable source maps for typescriptServices.out.js

### PR DESCRIPTION
**Pull request by JannesMeyer**
Source maps for `built/local/typescriptServices.out.js` are currently disabled. This means that you can't step into sourcemapped TypeScript code when using the TypeScript compiler API.

It's especially confusing because the Gulpfile seems to assume that they are enabled and produces a **broken sourcemap** for the downstream files (`typescriptServices.js` and `typescript.js`):

https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/Gulpfile.js#L132-L139

https://github.com/microsoft/TypeScript/blob/06a2210eb53cfce968dc855fcc13738d95d4556a/Gulpfile.js#L149-L155

### CODE REVIEW

**Comment by JannesMeyer** [comment]
Sorry, I didn't know I had to open an issue first. Here it is: https://github.com/microsoft/TypeScript/issues/41439

**Comment by sandersn** [comment]
I'm not sure who knows most about source maps around here? Anybody?

**Comment by weswigham** [comment]
This is probably fine? I generally don't see why we wouldn't have source maps on.

**Comment by JannesMeyer** [comment]
Thanks for your comments!

@weswigham, to be more accurate, some of these sourcemap output files already exist, because gulp creates them (they're just broken). So someone must have already decided on the `gulpfile` side that it's a good idea to have source maps, right?

**Comment by weswigham** [comment]
I think they're off just because we used to have "debug" and "release" builds of all the targets, but that caused too many headaches (and bad incremental behavior when testing locally besides), so the final compiler settings may not have bewn appropriately debuggish because of that merge.

**Comment by orta** [comment]
We're good here - This change happened via https://github.com/microsoft/TypeScript/pull/41589

**Pull request closed without merging**
