### PR TITLE
Properly remove generic types that are constrained to 'null | undefined' in getNonNullableType

### LINKED ISSUE #43425: Can't call `((_: string) => T) | undefined` when conditionally `string extends T`
# Bug Report

I am trying to make a generic callback function `(_: string) => T`, that is allowed to be optional (undefined) only when `T` is `string`. (Specifically, I chose `string extends T` because TS doesn't seem to provide exact equality for conditional types, and I want the default value to be `(x: string) => x`.)

The initial way I wrote this was `string extends T ? ((value: string) => T) | undefined : (value: string) => T`, but I found I was unable to (conditionally) call the function. The error seems to stem from TS treating the type as `(value: T & string) => T`, which prevent me from passing in a string literal.

image

I found a workaround that allows me to call the function: `((value: string) => T) | (string extends T ? undefined : never)` (**which I believe should be exactly equivalent**, though let me know if this is wrong). However, this too is broken in the latest nightly, seemingly because of how `NonNullable` is being distributed over `|`:

Screen Shot 2021-03-29 at 12 17 07 PM

### 🔎 Search Terms

generic extends function parameter union 🤷

### 🕗 Version & Regression Information

- This changed between versions 3.8.3 and 3.9.7, and changed again between 4.2.2 and the nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbAjAHhgD4oBeKACgoDcEAbAVwgC4oVg4BLJAcwEoyJGAIA+ldl15QIAD2AQkAExSwoAfigMlENNwiKorJBGoQ4fANwBYAFChIsRKkw4ATIRLkJ3HtLkLlVQ0qWkYWNg4fAVIhUU1tXWMDVhp6JlZvXmihaxtbNC0AY2BODCQoeXYPCjRcVnhkdCw8DwAaKDRXeqcmtw8BAG9bKA7cNQA6CgAiAAsIOjoMKcthjtcJ6bmFpZWbAF9bIA)

### 💻 Code

```ts
type Transform1<T> = ((value: string) => T) | (string extends T ? undefined : never);
type Transform2<T> = string extends T ? ((value: string) => T) | undefined : (value: string) => T;

function test<T>(f1: Transform1<T>, f2: Transform2<T>) {
  f1?.("hello");  // error in nightly, no error in 4.2.2
  f2?.("hello");  // error since 3.9.7, no error in 3.8.3
}
```

### 🙁 Actual behavior

Error on the call to `f1` in 4.2.2, and errors on both calls in the nightly.

### 🙂 Expected behavior

Both calls should succeed. The function return value is ignored, so `string extends T` should have no impact on the validity of the expression.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #43425.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
This is a *very* safe fix. If possible, we should cherry pick it for 4.3.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
@ahejlsberg the Node 10 check time numbers have me a little bit concerned. Any idea what could have caused that?

CC @amcasey

**Comment by ahejlsberg** [comment]
> The Node 10 check time numbers have me a little bit concerned. Any idea what could have caused that?

Those deltas are all in the noise. If you don't like them, just run the tests again. 😉

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@DanielRosenwasser There we go, basically no difference!

**Comment by DanielRosenwasser** [comment]
That's amazing! I can't believe you drove down those numbers in just a few hours!

@typescript-bot cherry-pick this to release-4.3 and LKG

**Pull request merged**
