### PR TITLE
JSDoc supports null, undefined and never types

### PR DESCRIPTION
**Pull request by sandersn**
This was missing from the literal types PR.

### CODE REVIEW

**Comment by sandersn** [comment]
@mhegazy this was easier than I thought it would be, but no less annoying since I had to duplicate JSDoc type nodes for all three types.

**Comment by sandersn** [comment]
Looks like I need to edit baselines in some unit tests in `src/harness/unittests/jsDocParsing.ts`

**Comment by sandersn** [comment]
OK, unit tests should be fixed now.

**Comment by DanielRosenwasser** [comment]
It'd be good to see a test where you still get a completion list for all the members on `null | undefined | { foo: number }`.

Also, more of a general question (and I don't actually think you should *take out* the functionality), but what purpose does the `never` type really have in Salsa?

**Comment by DanielRosenwasser** [comment]
Actually, perhaps you *shouldn't* see the member list until you've narrowed down.

The bug that probably isn't taken care of here is that you *do* show the member list for something that's nullable because in Salsa we always show members from *every* type in a union.

**Comment by sandersn** [comment]
### 1. why `never` et al?
Jsdoc isn't just for salsa. It's also for `--allowJs`. You can pre-convert files that aren't ready to be `.ts` yet so that you can get good information and errors in the files that you have been able to convert to `.ts`. For example, you could even write `assertNever` in `.js` and use it from `.ts`.

### 2. Completion members
I'll add the test. I don't think `--allowJs` respects `--strictNullChecks`, but maybe that's an effect of the show-all-union-members behaviour you're talking about.

**Comment by sandersn** [comment]
OK, I added the fourslash test.

**Comment by mhegazy** [comment]
👍

**Pull request merged**
