### PR TITLE
Fix Issue #39155 (importModuleSpecifierEnding does not apply for module specifier completions)

### LINKED ISSUE #39155: importModuleSpecifierEnding does not apply for module specifier completions (manual imports)
- VSCode Version: 1.44.2
- OS Version: macOS 10.14.6

A while back, the `importModuleSpecifierEnding` preference was added to specify the preferred path ending for auto imports (see microsoft/vscode#90405).

```json
{
  "javascript.preferences.importModuleSpecifierEnding": "js",
}
```

While this seems to work with auto imports (i.e. referencing an export of another file and letting the editor perform module importing automatically), it does not work with path completions when typing the import statement manually.

```js
import { someFunction } from '../|';
                                 ^ when picking a file from path suggestions here,
                                   the file extension seems to always be omitted
``` 

**Actual Behavior:**

```js
import { someFunction } from '../someModule';
``` 

**Expected Behavior:**

```js
import { someFunction } from '../someModule.js';
``` 

Steps to Reproduce:

1. Set `javascript.preferences.importModuleSpecifierEnding` to `"js"`
2. Start typing an import statement of a relative js module
3. When specifying the import source, choose a relative file path from the completions list
4. The ".js" extension appears to be omitted

Expected Behavior:

The file chosen from the suggestions list should have the ".js" extension. 

---

Does this issue occur when all extensions are disabled?: Yes

### PR DESCRIPTION
**Pull request by Simar-B**
Fixes #39155

### CODE REVIEW

**Review by andrewbranch — APPROVED** [review]
Looks good, thanks!

**Comment by Simar-B** [comment]
My pleasure!

**Comment by AlCalzone** [comment]
@andrewbranch this does not seem to have any effect for me in TypeScript 4.3. With
```
	"javascript.preferences.importModuleSpecifierEnding": "js",
	"typescript.preferences.importModuleSpecifierEnding": "js",
```
TypeScript defaults to importing a `.ts` file and then complains that the import may not end in `.ts`.

**Comment by silkfire** [comment]
Why are you storing TypeScript code in `.js` files?

**Comment by AlCalzone** [comment]
I'm not. https://github.com/microsoft/TypeScript/issues/33079 and https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm for some context

**Comment by silkfire** [comment]
These are two separate things. If you don't want the linter to complain you need to set that in the settings, so the TS Server knows what extensions you are expecting in your imports.

**Comment by AlCalzone** [comment]
Did you even read my first comment? I've set the setting to use a `js` extension, but TypeScript adds a `ts` extension instead. It then complains about the `ts` extension and proposes a `js` extension, which is what I've wanted anyways.

**Comment by silkfire** [comment]
I'm sorry, I didn't mean to misunderstand you. That must surely be a bug as specifying `"js"` should not result in a spurious `.ts` extension being suggested by TS.

I see, what would the upshot of that be?

**Comment by AlCalzone** [comment]
> in a spurious `.ts` extension being suggested by TS for files that aren't even TypeScript files.

They are TypeScript files. But importing them with a `.js` extension is currently the recommended way to do ESModules, because TypeScript does not yet change the extension during compilation. So we need to specify the filename the file is going to have at runtime, which is also why TS suggests using a `.js` extension.

**Comment by andrewbranch** [comment]
@AlCalzone I believe you’re describing #44374, fixed by #44602.

**Pull request merged**
