### PR TITLE
fix(47872): GoToDefinition won't work if CommonJS module contains import statement on the top of a js file

### LINKED ISSUE #47872: (Bug Report): GoToDefinition won't work if CommonJS module contains import statement on the top of a js file
# Bug Report

### 🕗 Version & Regression Information

- TypeScript Version: `typescript@next`
- VSCode Version: `1.64.1`，[relevant issue](https://github.com/microsoft/vscode/issues/136203)
- This is the behavior in every version I tried

### ⏯ Playground Link

[Go to definition with relevant code](https://stackblitz.com/edit/node-c5r7ft?file=index.js)

### 💻 Code

```js
// index.js
const { foo } = require('./foo')
```

```js
// foo.js
import fs from 'fs' // try to toggle comment in this line

function foo() {

}

module.exports = {
  foo,
}
```

### 🙁 Actual behavior

image

### 🙂 Expected behavior

Go to definition could find the definition of `foo`

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #47872

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Review by sandersn — CHANGES_REQUESTED** [review]
I want to hold this until we decide whether to the original bug is worth fixing. As-is the PR makes ESM and commonjs syntax completely interchangeable in JS files, which is a big step. It might be the right one, but I want to make sure.

**Comment by a-tarasyuk** [comment]
> I want to hold this until we decide whether to the original bug is worth fixing

Sure. Could you mark it as `experiment`?

**Comment by a-tarasyuk** [comment]
The issue https://github.com/microsoft/TypeScript/issues/47872 was closed, I think this PR is needless anymore. @sandersn Can I close it?

**Comment by sandersn** [comment]
Yes, let's. It's more important than ever to avoid confusing ES and CommonJS modules, and *someday* CommonJS code won't be that common.

**Pull request closed without merging**
