### PR TITLE
Update CopyrightNotice.txt

### PR DESCRIPTION
**Pull request by krishnatre-siddhartha**
Edited copyright notice to reflect years, as required legally.

Fixes #

### CODE REVIEW

**Comment by kitsonk** [comment]
Who's laws?

**Comment by krishnatre-siddhartha** [comment]
Any state. Since MS is a US company, I will refer here to only the US law. A copyright notice starts in a fixed year and ends after a period of defined years. Ending year, if the copyright is valid, need not be mentioned but the start is needed -- if a dispute arises in future.

**Comment by kitsonk** [comment]
If you are referring to US law, copyright notices are not required at all.  Everything else falls under the Berne Convention, which doesn't require them either.  The year being present _can_ make it easier when asserting a claim, and it is the year of first publish, a range is totally meaningless.

Here is a [source](http://www.copyrightlaws.com/copyright-notice-year/):

> A copyright notice is not mandatory in the U.S. or in Canada or in most countries (specifically it’s not required in Berne Copyright Treaty countries). In these countries, use of the copyright notice and symbol is still useful and a good idea. In these situations, the purpose of the copyright notice is to educate others or to remind others that copyright exists in your work and to respect that copyright.
> 
> In addition, including a copyright notice on your website or blog may help diminish the myth that all online content is free.

So again, where is this _as required legally_?

**Comment by krishnatre-siddhartha** [comment]
In India, it is needed even though it is a Berne Copyright Treaty country.

**Pull request closed without merging**
