### PR TITLE
Control flow analysis for dependent parameters

### LINKED ISSUE #46658: Control flow analysis for dependent function parameters "destructured" from a tuple type
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

dependent arguments, parameters

[This issue](https://github.com/microsoft/TypeScript/issues/35873) is very related to mine here, but I don't believe it's the same. That issue propose some bigger changes to TS - while I'd only like to "reuse" the, just landed, logic for the situation described below.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It's today possible to mimic dependent function parameters with tuples, spreads & co. Using such function parameters is clunky though because one can't destructure the arguments tuple without losing nice control flow analysis.

Since control flow analysis for destructured properties from unions has just landed on the main branch ( https://github.com/microsoft/TypeScript/pull/46266 ), I think it would be great to extend the logic to cover this situation.

I've looked briefly at how this works for the newly introduced control flow analysis and I think the problem is that the information about the identifier coming from the arguments list is not propagated to `getCandidateDiscriminantPropertyAccess`. So it has no chance of handling this "correctly". If we could pass this info there and then check the signature type, if it's spread+tuple based then we could apply the same logic as for binding patterns.

## 📃 Motivating Example

I've added a test case for this here: https://github.com/Andarist/TypeScript/commit/3e87dec24c8cb4c990d048d7d4c1342e6c49f779

```ts
type Args = ['A', number] | ['B', string]

declare function fn10(cb: (...args: Args) => void): void

fn10((kind, data) => {
    if (kind === 'A') {
        data.toFixed();
    }
    if (kind === 'B') {
        data.toUpperCase();
    }
})
```

Currently, with this technique, one could do this to keep the control flow analysis working:
```ts
type Args = ['A', number] | ['B', string]

declare function fn10(cb: (...args: Args) => void): void

fn10((...args) => {
    if (args[0] === 'A') {
        args[1].toFixed();
    }
    if (args[0] === 'B') {
        args[1].toUpperCase();
    }
})
```

but this ain't super friendly to the user.

## 💻 Use Cases

In XState (a state machine library) we have actions (can be thought of as functions/callbacks) that can be declared like this:
```js
assign((context, event) => {
  // this particular action can return a partial update to the context value
  return {}
})
```

Since XState is a state machine library some combinations of context & event types are **impossible**. With this feature in place, we could explore computing valid combinations and **maybe** (since the task ain't trivial) we could narrow down types of the `context` parameter based on different `event.type`s. So for instance, there is a chance that this would become possible:
```js
type Context = { userId: string | null }

assign((context, event) => {
  if (event.type === 'CHANGE_PASSWORD') {
    // `context` could be narrowed down to `{ userId: string }` if we could figure out how to create compute proper parameter tuples
  }
  return {}
})
```

cc @ahejlsberg

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR builds on the work in #46266 to support control flow analysis for dependent parameters contextually typed by a rest parameter with a discriminated union type. Some examples:

```ts
type Args = ['a', number] | ['b', string];

const f1: (...args: ['a', number] | ['b', string]) => void = (kind, payload) => {
    if (kind === 'a') {
        payload.toFixed();  // payload narrowed to number
    }
    if (kind === 'b') {
        payload.toUpperCase();  // payload narrowed to string
    }
};

f1('a', 42);
f1('b', 'hello');

declare function f2(cb: (...args: Args) => void): void

f2((kind, data) => {
    if (kind === 'a') {
        data.toFixed();  // data narrowed to number
    }
    if (kind === 'b') {
        data.toUpperCase();  // data narrowed to string
    }
});

type ReadFileCallbackArgs =
    | [err: undefined, data: unknown[]]
    | [err: Error, data: undefined];

declare function readFile(path: string, cb: (...args: ReadFileCallbackArgs) => void): void;

readFile('hello', (err, data) => {
    if (!err) {
        data.length;  // data narrowed to unknown[]
    }
    else {
        err.message;  // err narrowed to Error
    }
});
```

Fixes #46658.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt

**Review by weswigham — APPROVED** [review]
A test showing how this behavior is disabled when one of the parameters is reassigned would be nice.

With this, would we revisit giving overload implementation parameters a contextual type equal to the union of the overload parameter lists (under noImplicitAny), so overloads can make use of this without kinda contorting your function definition style?

**Comment by Andarist** [comment]
I was wondering if this could help us with some XState types and I've created a more complex test case that resembles how we would like to utilize this feature (which is awesome!) but unfortunately, it turns out that this doesn't work for us.

I believe there is a potential for refining the `context` parameter here in a way that `context.user` would not include `null` as part of its type:
https://github.com/microsoft/TypeScript/commit/44d9f91ae999b15609ef56d1075d41446aaed285#diff-2f166985e9669bbcb575d1ceff7375d792893917411711533a640c0cee0c15a7R232-R244

Is this something that could be addressed in this PR? Is making this work aligning with your goals for this feature? Should this be tracked separately?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by ahejlsberg** [comment]
@Andarist The issue in your example is that the discriminant is stored in a nested object instead of directly in a property. In other words, this doesn't work:

```ts
type XStateActionArgs =
  | [event: { type: "LOG_OUT" }, context: { user: { name: string } }]
  | [event: { type: "LOG_IN" }, context: { user: null }];
```

whereas this does:

```ts
type XStateActionArgs =
  | [event: "LOG_OUT", context: { user: { name: string } }]
  | [event: "LOG_IN", context: { user: null }];
```

Effectively, discriminants only affect the directly containing type. This is true for discriminated unions in general, and isn't specific to this PR.

**Comment by KamenKolev** [comment]
I'm not sure if this is a bug, or out of scope but it seems to me like something like this should work

`
const fn: (...args: [number, number] | [string, string]) => void = (a, b) => {
  if (typeof a === "number") {
    console.log(a + b); // 'b' still 'string | number'
  }
}
`

What could be the reason for this to fail?

**Comment by Jackie1210** [comment]
> I'm not sure if this is a bug, or out of scope but it seems to me like something like this should work
> 
> ```ts
> const fn: (...args: [number, number] | [string, string]) => void = (a, b) => {
>   if (typeof a === "number") {
>     console.log(a + b); // 'b' still 'string | number'
>   }
> }
> ```
> 
> What could be the reason for this to fail?

I came out the same issue. Did you resolve it? @KamenKolev

**Comment by Andarist** [comment]
I'm not 100% sure but I think that this only works for discriminated unions and a discriminated union mandates that you are using a literal member~. `string`, nor `number`, are literals so this doesn't work.

**Comment by jcalz** [comment]
Hmm, is there a reason this doesn't work for methods?

```ts
type Foo = {
  method(...args:
    [type: "str", cb: (e: string) => void] |
    [type: "num", cb: (e: number) => void]
  ): void;
}

// this fails for some reason, as a method
let fooBad: Foo = {
  method(type, cb) {
    if (type == 'num') {
      cb(123) // error!
    } else {
      cb("abc") // error!
    }
  }
};

// suddenly works for arrow function
let fooOkay1: Foo = {
  method: (type, cb) => {
    if (type == 'num') {
      cb(123)
    } else {
      cb("abc")
    }
  }
};

// also works for manual destructuring of rest args
let fooOkay2: Foo = {
  method(...args) {
    const [type, cb] = args;
    if (type == 'num') {
      cb(123)
    } else {
      cb("abc")
    }
  }
};
```

[Playground link](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAYg9nKBeKBvAsAKClAthYACzgBMAKAOioEMAnAcwGcAuLHHAbVEmagCJGwWnwA0UAMYAjXmQi9BtAJYA7egEpkAPigA3OIpIBdKAB827LuDn9lAV1yiJ0qLN53ckiLQ1Jteg4bmarz+JADcWAC+WFgANgRQAGYIAELUJLzwiCgY2HgExOTcEGJSGrnsUIqJLsXIKADk7g3l5pVSZACMAEwAzBoA9ANQXrRwtACEbVCRI7GM0BWVTmR81JLifIPDo+NTeTjReUeREZhxCclwAPIA1tQgnZkIyGjm+ESkMsWlkj7aSxw1VqVnqUCa9habwO7A6PX601mEHmi2mOA6aw2W0R5hOZwuwCSCDuD26z2y0JwH0KlBoDEYrRh4jgykEUEskF+xhQdCYZ0qwLIdSQjWajOWK3hakRcwWlOWGPWm2lMKOhyi+MwQA)

(note to self, follow up on [this SO question](https://stackoverflow.com/q/71300504/2887218))

**Comment by Andarist** [comment]
For the record - I'm in the process of debugging this issue ☝️ . I'm not sure if I will be able to actually fix it - but I'm trying 😉 I already have debugged this to the very exact code line where the behavior is diverging for those cases.

**Comment by jcalz** [comment]
We might need to open a new issue for this and then see if the TS team would even accept a PR for it.

**Comment by Andarist** [comment]
The PR is already up: https://github.com/microsoft/TypeScript/pull/48110

We can go through a ceremony of opening an issue and attaching it to this PR but from my PoV that would just be redundant bureaucracy

**Comment by lifeiscontent** [comment]
I would assume this PR would have fixed this kind of issue, is this a separate issue?

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJICE4GcUG8BQyyYAngA4QBcyARDAPb03IA+tARnFDQNyHIA3OABsArlWRYwUUAHNWk6XIDaAXT4BffPlCRYiFKgBijZBAAekEABMsaTDmQEipCtTqNe-IWIlSZILKa2rrQ8Ej2XGaWEDZ2GNh4-K4SNJzcfEQ+4tT+Kur4WvgwoiAIYMD0IMicOAAUZFxwALZY1Ak4AJRO-FgA7sBgCAAWyA1NrQB0Kd3ORMgIibQMTJT88wtVWPTCEJPC9LLjUC1Y0+QQnTzIAPQ3yCvr81AQYKJQ1SvHp1e3940nKYpZAAXjBy08CjSXBoT0Wjmh3DWGyICC2Oz2ByOANO5wovzuNS4TyILzeHyJUG+rQJ-wmZ2BYJBEKYUPSsKIWiKJTKFSqD0Y1LaaBM9Fm-DJ72qONawWKpXKlWq6SF7UwUHFpNeUuQMqwwSAA

**Comment by Andarist** [comment]
I think this issue is something entirely else. I'm also not sure if this is an issue if we consider how TS is designed. You are operating here on `IBase` but this type has no relation to `IFoo` and `IBar`, so if you "refine" it then the compiler won't recognize that your intention was to pick one of the union members since that implied union doesn't really exist anywhere here. This looks fine to me if we consider that `IFoo` and `IBar` have different types for a `value` property than `IBase`.

However, it seems that perhaps this [TS playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJICE4GcUG8BQyyYAngA4QBcyARDAPb03IA+tARnFDQNyHIA3OABsArlWRYwUUAHNWk6XIDaAXT4BffPlCRYiFKgBijZBAAekEABMsaTDmQEipCtTqNe+LTvDR4SPZcZpYQNnYY2Hj8rhI0nNya2jCiIAhgwPQgyJw4ABRkXHAAtljUkTgAlE78hVAlWAB0sfxYAO7AYAgAFsgFRaXN5BDVzkTICFG0DEyU-OMTWVj0whCNwvSy-fWDsZU8yAD0h8gz8+Mz2w37Ryd1DUMUyAC8r9OeCvFcNOdEl-elZDYYjDegwZAAuwAMicILcyAA5DMEcgNPtfsgoBAwKIoNlztYIPBRMIwHMFkQsTi8fwtD4UmkMllTowrqVyiZ6KN+FTcdlIUl8Az0plsgk2WUglBuZTsXyIQMsEkgA) could actually work 🤔 Either way, I would classify this as a totally separate issue - cause knowing what this PR was about this is something entirely else.

Take my words with a grain of salt - I'm just a bystander here 😅

**Comment by Andarist** [comment]
@jcalz this looks like the issue reported [here](https://github.com/microsoft/TypeScript/issues/48663). I actually have a partial fix [here](https://github.com/microsoft/TypeScript/pull/49218) but need to cover more cases there - I guess it might be the time to revive that PR on my side 😅

**Pull request merged**
