### PR TITLE
Add writeFile and customTransformers to build and buildReferences

### PR DESCRIPTION
**Pull request by sheetalkamat**
This one should help with https://github.com/TypeStrong/ts-loader/pull/1274

### CODE REVIEW

**Comment by sheetalkamat** [comment]
Ping i would like to get this in for 4.3.1

**Review by andrewbranch — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Tremendous!

**Comment by gauriramesh** [comment]
Thanks so much @sheetalkamat !

**Comment by gasnier** [comment]
@sheetalkamat
Once again, thanks for this PR.

I tried to use it and it is finally not sufficient for ts-loader in watch mode

When we build in watch mode, we use createSolutionBuilderWithWatch and the rebuild is initiated by the SolutionBuilderWorker by calling buildNextInvalidatedProject which then calls "done" on the invalidated project without the customTransformers.

Would it be possible to add the same parameter "getCustomTransformers?: (project: string) => CustomTransformers"
 to createSolutionBuilderWithWatch and pass it all the way to buildNextInvalidatedProject ?

----
Also, last year you optimised the project references build in ts-loader but I am not sure to understand how it works.

in instances.ts (https://github.com/TypeStrong/ts-loader/blob/main/src/instances.ts) line 483 function buildSolutionReferences
```
if (!instance.solutionBuilderHost) {
    ...
    instance.solutionBuilderHost = makeSolutionBuilderHost(...)
    const solutionBuilder = instance.compiler.createSolutionBuilderWithWatch(instance.solutionBuilderHost,...)
    ...
} else {
    instance.solutionBuilderHost.buildReferences();
}
```

Within buildReferences I don't find any 'build' call... but when I debug the 'timeout functions' I find the buildNextInvalidatedProject calls (file https://github.com/TypeStrong/ts-loader/blob/main/src/servicesHost.ts line 894)

If we add getCustomTransformers parameter to createSolutionBuilderWithWatch will it be sufficient or do we have to pass it to the solutionBuilderHost in some way ?

Thanks.

Also, should I create a ticket ?

ping @johnnyreilly

**Comment by johnnyreilly** [comment]
I'd just use the discussion here for now - it has the context.

**Pull request merged**
