### PR TITLE
New --strictAny mode

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements a new `--strictAny` compiler option in the `--strict` family of options. This mode forbids unsafe conversions from `any` to other types. Specifically, in `--strictAny` mode, `any` is assignable only to `any` and an empty object type (`{}`). The `--strictAny` option doesn't otherwise alter the special behaviors of `any`, i.e. unrestricted property access and function calls through objects typed as `any` continue to be permitted.

The `--strictAny` option effectively identifies transitions from the loosly typed world of `any` to the strongly typed world of other types and requires such transitions to be accompanied by proof (through control flow based type narrowing) or assumption of responsibility (through explicit type assertions).

An example:

```ts
declare function getValue(propName: string): any;
declare function setLimit(x: number): void;

let counter = getValue("counter");  // Inferred type is any
setLimit(counter);  // Currently permitted but error in --strictAny mode
```

The `--strictAny` mode requires such unsafe conversions to be accompanied by dynamic checks or explicit type assertions:

```ts
// Proof through control flow narrowing
let counter = getValue("counter");
setLimit(typeof counter === "number" ? counter : 0);  // Ok

// Assumption of resposibility
let counter = getValue("counter") as number;  // Trust me, it's a number
setLimit(counter);
```

The `--strictAny` option includes an exception for assignability of function types, permitting strongly typed parameters in the source to be matched by a rest parameter of type `any[]` in the target even though that is technically not safe. For example:

```ts
type AnyFunction = (...args: any[]) => any;
let f: AnyFunction = (x: string) => s.toLowerCase();
f(42);  // Ouch!
```

We could potentially remove this exception and instead require such general function types to use type `never`, which would ensure that it isn't possible to call the function without first explicitly asserting a more specific type:

```ts
type AnyFunction = (...args: never[]) => any;
let f: AnyFunction = (x: string) => s.toLowerCase();
f(42);  // Error, number not assignable to never
```

Note that `--strictAny` is potentially quite disruptive to code bases that use `any` liberally. However, in code bases that are intended to be strongly typed throughout it definitely can be both revealing and informative. For example, `--strictAny` identifies 100+ locations in the TypeScript compiler where we have unsafe conversions from `any`, many of which are unintended.

### CODE REVIEW

**Comment by yortus** [comment]
@ahejlsberg if I understand correctly, with `--strictAny` enabled, we get part way to having the proposed `unknown` top type in #10715, since `any` is no longer assignable to other types (but all other types are still assignable to `any`).

If property acceses and function calls to `any` values were also subject to proof or assertion, we'd be able to build projects where `any` would behave as a properly strict top type. We'd effectively have `unknown` through a compiler flag, without needing a new type.

Can you comment on why `--strictAny` only requires proof for assignments, but not property access and function calls? Is this a consideration for future strictness checks?

**Comment by ahejlsberg** [comment]
> If property acceses and function calls to any values were also subject to proof or assertion, we'd be able to build projects where any would behave as a properly strict top type. We'd effectively have unknown through a compiler flag, without needing a new type.

That is technically true, but I'm not sure it would ever be practical. I think the issue of introducing an `unknown` safe top type is largely orthogonal since there are definitely scenarios where you want to use both in the same code base. (And we are indeed considering introducing such an `unknown` type.)

> Can you comment on why --strictAny only requires proof for assignments, but not property access and function calls? Is this a consideration for future strictness checks?

I think the core intuition people have with the `any` type is that it allows you to treat a particular object as being dynamically typed ("JavaScripty"), i.e. not subject to static checks when you perform operations on it. However, it seems far less intuitive that such objects *implicitly* convert to strongly typed values, and I believe this is where the majority of `any`-related issues arise.

**Comment by yortus** [comment]
I see your point that ideally we'd want both `unknown` _and_ safe `any` in the same codebase.

> I think the core intuition people have with the `any` type is that it allows you to treat a particular object as being dynamically typed ("JavaScripty"), i.e. not subject to static checks when you perform operations on it. However, it seems far less intuitive that such objects implicitly convert to strongly typed values, and I believe this is where the majority of `any`-related issues arise.

Yes I suppose that's true usually. One case that's still a problem is when the `any`s come from imported libraries that use them as eg return types, when they should be using `{} | null | undefined` (or `unknown` if it existed). Eg `JSON.parse` and literally [thousands more on DefinitelyTyped](https://github.com/Microsoft/TypeScript/issues/9999#issuecomment-238009695). So the library effectively turns off type checking in parts of my calling code.

`--strictAny` will help with this case too, but in these cases I'd still like my project, not the library, to decide whether static checks should be disabled, including property access and calls. I guess that's a case for `unknown` (and lots of DT PRs) to solve.

**Comment by NN---** [comment]
Is it similar to TSLint rule?
https://palantir.github.io//tslint/rules/no-unsafe-any/

**Comment by Yogu** [comment]
> `any` is assignable only to `any` and an empty object type (`{}`). 

Shouldn't this be `{}|null|undefined` (and/or `unkown`) with `--strictNullChecks` enabled?

**Comment by DanielRosenwasser** [comment]
After a lot of discussion on the current implementation, we've decided that `--strictAny` isn't something we're actively going to be pursuing in the near future. This was due to a mix of complexity and ease-of-use concerns, and whether the merits outweighed them. You can read more on why at https://github.com/Microsoft/TypeScript/issues/24737.

**Pull request closed without merging**
