### PR TITLE
Fix emit for decorator type metadata.

### PR DESCRIPTION
**Pull request by rbuckton**
The `resolveEntityName` function used by both `emitExpressionIdentifier` and `getTypeReferenceSerializationKind` always resolves the entity name using itself as the location. As a result, if there is a parameter declaration that has the same name as its type reference, that parameter declaration will be used as the value.

This fix clones the typeName that would be passed to `getTypeReferenceSerializationKind` and sets the clone's parent to point to the first non-declaration, non-type ancestor node of the type reference. This allows resolution to resolve a value outside of the class declaration, which is the scope in which the decorator metadata would be evaluated.

Fixes issue #3793.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
So in your test:

```TypeScript
@decorator
class MyComponent {
    constructor(public Service: Service) {
    }
}
```

what does the synthesized `Service` type-node get "parented" to?

I'm still hazy on why this is necessary - isn't there a better way of specifying the entity we actually wanted to refer to?

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
@rbuckton what is holding this off?

**Comment by rbuckton** [comment]
@mhegazy Nothing now, I'll update it with the latest from master and merge.

**Pull request merged**
