### PR TITLE
Disallow calls to async functions from async functions without using 'await'

### LINKED ISSUE #13376: async/await: nowait keyword?
I have a large project that has now been migrated over from javascript to typescript and we're very pleased with the results.  Bugs have fallen dramatically with the improved compiler support in combination with rigorously written code.

Ours is a server-side product that runs under node (ts-node, actually).  By its nature, it is highly asynchronous, so the move to Typescript had the major benefit of providing us access to async/await.  It has been working really well, and dramatically reduced our code size and complexity.

The one problem it has introduced is that we occasionally miss putting an "await" keyword in front of calls to methods returning promises (i.e., other async functions) when inside an async function.  This "send and forget" is something that one occasionally might want to use, but for the most part, this creates a lot of chaos in our design pattern, as in most cases, the call is to something that will complete asynchronously, but most of the time we need to wait for that to complete.  (That method cannot be synchronous because it depends on external services that are asynchronous.)  It is not uncommon in our case to have 5 or 10 await statements in a single method.

A missing "await" keyword can be hard to find -- especially when the method being called doesn't return anything that is needed by the caller.  (If it returns something, type-checking will usually catch the mismatch between the type of the Promise<type> returned from the call.)

Ideally, we could have a "nowait" keyword that would go where one would otherwise put an "await" to indicate to the Typescript compiler that the design intent is to explicitly NOT WAIT for the called method to be completing.  The tsc compiler could have a new flag that controls whether to create a warning if a method call returns a Promise that is missing either "await" or "nowait".  The "nowait" keyword would have no effect whatsoever on the compiled code.

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #13376

### CODE REVIEW

**Comment by cevek** [comment]
@RyanCavanaugh I think it would very useful also to check calls without await in control flow condition statements

Because to catch errors like this I need tslint with slow "strict-boolean-expressions" rule

```ts
async function bar(){return false}

async function foo() {
  if (bar()) {}
  while (bar()) {}  
  do {} while (bar())
  var x = bar() ? 1 : 2;
  for (var x = 1; i++; bar()){}
  switch (bar()) {case bar(): break;}
}
```

**Comment by kpreisser** [comment]
Hi,
is there an ETA when this PR will be merged to `master` (e.g. after a `2.4` branch was created)?
Currently I'm merging this branch for a custom TS build and each time I have to fix the merge conflict in `diagnosticMessages.json`.  :wink:

Thanks!

**Comment by finnigantime** [comment]
Would love to have this! Currently relying on tslint rule `no-floating-promises` but having this guard in TypeScript itself seems preferable.

**Comment by leebenson** [comment]
This would be especially useful for VSCode users, where `no-floating-promises` doesn't work out-the-box with the TSLint plugin. Having code _look_ fine but then throw when hitting `tslint` via the CLI or VSCode task is annoying.

**Comment by mhegazy** [comment]
in light of the [discussion about errors vs warnings](https://github.com/Microsoft/TypeScript/issues/19393) we should instead move this to tslint.

**Comment by leebenson** [comment]
It already is in tslint. This is problematic enough to be in TS proper. The tslint plugin in VS code doesn’t catch it and those without a separate linting step in their build pipeline could be shipping very broken code. I hit a MAJOR security issue with not awaiting a Promise— no way should this be downgraded to a warning.

**Comment by conordickinson** [comment]
The TSLint rule also requires type info to be on, which we do not do because it is so much slower (and causes tslint to run out of memory with our repo last I tried it).

**Comment by leebenson** [comment]
Merging this would prevent things like this:

```
try {
  await someImportantSecurityCheck(); // <-- ditching `await` is a MAJOR security flaw
  runSomePrivilegedFunction();
} catch (e) {
  // deal with unauthorised...
}

// ...
```

Which incidentally, is _exactly_ the issue I ran into.

Not awaiting promises can cause major headaches. Not to mention unhandled Promise rejections are deprecated, and will eventually terminated with a non-zero error code.

Again - this is not linting. It's a significant flaw in an otherwise decent type system.

**Comment by RyanCavanaugh** [comment]
Will pick this up later

**Pull request closed without merging**
