### PR TITLE
Change error message which warn unexposed namespace member

### LINKED ISSUE #10521: Error message uses terminology "module" when referring to a namespace
Hi,
I got the following error message which uses the terminology "module" whereas actually I'm using a namespace. I think the error message could be updated to avoid confusion.

**TypeScript Version:**  Version 2.1.0-dev.20160824

**Code**

```ts
declare namespace ns {
	let f: number;
}
let x: ns.A; // TS2305: Module 'ns' has no exported member 'A'.
```

**Expected behavior:**
`test1.ts(4,11): error TS2305: Module or namespace 'ns' has no exported member 'A'.`
**Actual behavior:** 
`test1.ts(4,11): error TS2305: Module 'ns' has no exported member 'A'.`

Thanks!

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
Fixes #10521 

See namespacesDeclaration**2** test. I think that is descriptive.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks for the PR @YuichiNukiyama - @mhegazy @RyanCavanaugh @sandersn should we just make the message say `namespace` instead?

**Comment by sandersn** [comment]
Yes, I would like to see just 'namespace'. But are there other places that have this 'module or namespace' wording for namespaces? If so, we need another bug to track changing those too.

**Comment by mhegazy** [comment]
I would rather change this to an explicit message for both, i.e. add a new error message `Namespace_0_has_no_exported_member_1` in addition to `Module_0_has_no_exported_member_1`, and check the flags on the symbol to show one or the other.

**Comment by mhegazy** [comment]
merged manually. thanks!

**Pull request merged**
