### PR TITLE
fixes #2507 - bad formatting for formatonkey if convertTabsToSpaces === false

### LINKED ISSUE #2507: Typescript server: bad formatting for formatonkey if convertTabsToSpaces === false
Configure the format options so that convertTabsToSpaces = false.

Type <enter> to insert a new line behind an indented }

Observe: the new line has tabs and spaces. The cursor sits between.

### PR DESCRIPTION
**Pull request by dbaeumer**
See issue #2507

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
A question about how this is being used: what happens if someone uses `Shift`+`Tab`?

**Comment by dbaeumer** [comment]
@DanielRosenwasser this is independent of tab ot shift tab. The existing code adjusts the indent position but it only considers that the formatter indents using spaces. The pull request also takes into account the fact that the formatter uses tabs as indentation characters if requested to do so.

**Comment by mhegazy** [comment]
Feel free to merge whenever you are ready.

**Pull request merged**
