### PR TITLE
Treat ambient shorthand declarations as explicit uses of the `any` type

### LINKED ISSUE #10191: (bug) short-hand module declaration not working in combination with 'noImplicitAny'
**TypeScript Version:**  2.1.0-dev.2016080

**Code**
Trying to declare a module with the new short-hand syntax like this:
```ts
  declare module 'lodash';
```
leads to the following TypeScript-Compiler error
```
error TS7005: Variable ''lodash'' implicitly has an 'any' type.
```
I also can't find a way to make this "explicit any".

**Expected behavior:**

new shorthand syntax for module-declaration should also work with 'noImplicitAny' activated

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #10191.
Pending discussion with @DanielRosenwasser, @RyanCavanaugh, and @mhegazy.

### CODE REVIEW

**Comment by yuit** [comment]
the change looks good. it now seems to be the design matter of whether we should allow this

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
(wait on others)

**Comment by mhegazy** [comment]
👍

**Pull request merged**
