### PR TITLE
Keep track of why files are in the program

### LINKED ISSUE #33515: Keep track of why files are in the program
# Motivation

We currently have `tsc --listFiles` to show the list of files included in the compilation, but it doesn't tell you *why* a file is in there. There are other scenarios where a file is "illegally" part of the compilation, but we're not able to tell you why it's there.

This leads to some difficult debugging scenarios. For example, a customer was confused about why the ES2018 `includes` method was available in their ES5-targeting program:

```
(Customer) Here's a dumb question.  Array.prototype.includes is part of ES7.  In our tsconfig.json we target es6 and lib is just [ "es6" ].  Should I get compilation errors when trying to call includes?  If not, should the generate code have called includes?  How can I learn what the mental model I should be using is here.
(Me) You should see an error. Typescript never polyfills any APIs
(Customer) Would having "@types/node": "latest" in my package.json change the behavior here?
(Me) Yeah it's possible node dts pulls in additional stuff, but they shouldn't do anything that would bring in includes
(Me) that'd be a node dts bug imho
(Customer) So with it, it definitely builds.  But the only place they have an includes is as a method on the Buffer class.
(Me) Where does go to def take you?
(Customer) /usr/share/code/resources/app/extensions/node_modules/typescript/lib/lib.es2016.array.include.d.ts
(Customer) Which is ES7?
(Customer) Yeah - sorry - surprised that go-to def would bring me to lib.es2016.ANYTHING if I was using the es6 target and lib?
(Me) You are correctly surprised
(Me) It means something has a lib reference that's causing it to be included
(Me) Search for "reference lib=" in your project
(Customer) Aside from a bunch of hits in node_modules/typescript, there only other hits are in the @types/node module here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/ts3.2/index.d.ts
(Me) So yeah that file is pulling in es2018
```

# Suggestion

During program creation, the first time a file is added to the program, we should keep track of what caused this to happen - `lib` reference, `types` directive, etc., and resurface that data when needed.

# Examples

### `--listFiles`
```
> tsc --listFiles

node_modules/typescript/lib/lib.es5.d.ts                       Automatic for target: "es5"
node_modules/typescript/lib/lib.es2015.d.ts                    lib reference from node_modules/typescript/lib/lib.es2016.d.ts
node_modules/typescript/lib/lib.es2016.d.ts                    Included from lib: "es2016"
src/compiler/core.ts                                           Part of 'files' list in tsconfig.json
src/compiler/debug.ts                                          Matched by include pattern '*/debug.ts' in tsconfig.json
src/compiler/performance.ts                                    Included via reference from src/compiler/core.ts
node_modules/@types/microsoft__typescript-etw/index.d.ts       Imported from src/compiler/performance.ts
src/compiler/perfLogger.ts                                     Part of 'files' list in tsconfig.json
src/compiler/semver.ts                                         Part of 'files' list in tsconfig.json
src/compiler/types.ts                                          Part of 'files' list in tsconfig.json
node_modules/buffer/index.d.ts                                 Imported from node_modules/@types/node/globals.d.ts
node_modules/@types/node/globals.d.ts                          Entry point for implicit types library 'node'
```

### `rootDir` violations

```
> tsc

Error TS1236: File "test/list.ts" is outside rootDir "src"
  The file is in the program because: Matched by default include pattern "**/*"
```

```
> tsc

Error TS1236: File "test/list.ts" is outside rootDir "src"
  The file is in the program because: Imported by "src/bad_file.ts"
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
1. Instead of keeping reference file reasons tracking, we also keep track of all reasons file is included in the program.
2. The configFileSpecs are stored on tsconfigFile so we dont have to pass them around any more.
3. The reasons are used to write explanations for files when new option `--explainFiles` is specified and program can use it too (earlier program wasnt aware of these)
4. They are also used to report errors about the file eg its not in `rootDir` or doesn't match casing etc
5. Because it is used to report errors while file processing is going on and program is still under construction, we store the metadata for errors instead of converting them in diagnostic right away. This is so we can reuse this data when program is completely reused and still give error locations at correct position.(Because the related information location can change without change but the diagnostic can be in different file)

Fixes #33515

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot perf test this
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@DanielRosenwasser @RyanCavanaugh Thoughts on getting this in?

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by sheetalkamat** [comment]
@typescript-bot pack this

**Comment by RyanCavanaugh** [comment]
Trying on a local build just to see how it feels
```
D:\github\TypeScript\src\services>tsc --explainFiles
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es5.d.ts
  Library 'lib.es5.d.ts' specified in compilerOptions
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.generator.d.ts
  Library 'lib.es2015.generator.d.ts' specified in compilerOptions
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.iterable.d.ts
  Library 'lib.es2015.iterable.d.ts' specified in compilerOptions
  Library referenced via 'es2015.iterable' from file 'C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.generator.d.ts'
C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.symbol.d.ts
  Library referenced via 'es2015.symbol' from file 'C:/Users/Ryan/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.iterable.d.ts'
../../built/local/shims.d.ts
  Output from referenced project '../shims/tsconfig.json' included because '--outFile' specified
../../node_modules/@types/microsoft__typescript-etw/index.d.ts
  Imported via "@microsoft/typescript-etw" from file '../../built/local/compiler.d.ts' with packageId '@types/microsoft__typescript-etw/index.d.ts@0.1.1'
../../built/local/compiler.d.ts
  Output from referenced project '../compiler/tsconfig.json' included because '--outFile' specified
../../built/local/jsTyping.d.ts
  Output from referenced project '../jsTyping/tsconfig.json' included because '--outFile' specified
types.ts
  Part of 'files' list in tsconfig.json
utilities.ts
  Part of 'files' list in tsconfig.json
classifier.ts
  Part of 'files' list in tsconfig.json
stringCompletions.ts
  Part of 'files' list in tsconfig.json
completions.ts
  Part of 'files' list in tsconfig.json
documentHighlights.ts
  Part of 'files' list in tsconfig.json
documentRegistry.ts
  Part of 'files' list in tsconfig.json
importTracker.ts
  Part of 'files' list in tsconfig.json
findAllReferences.ts
  Part of 'files' list in tsconfig.json
callHierarchy.ts
  Part of 'files' list in tsconfig.json
getEditsForFileRename.ts
  Part of 'files' list in tsconfig.json
goToDefinition.ts
  Part of 'files' list in tsconfig.json
jsDoc.ts
  Part of 'files' list in tsconfig.json
navigateTo.ts
  Part of 'files' list in tsconfig.json
(many more, truncated)
```

**Comment by DanielRosenwasser** [comment]
I like the idea, I would prefer different output. Maybe one line per file for easier regex?

```
fileName.ts: Explanation goes here.
```

**Comment by RyanCavanaugh** [comment]
>  I would prefer different output.

Files can have multiple reasons for being in the program - how do you think that should be handled as a single-line format?

**Comment by DanielRosenwasser** [comment]
Huh, didn't catch that from the example 😅- I would say to repeat the file name on both lines. Would that be unreasonable?

**Comment by sheetalkamat** [comment]
Ready for review. 
Quick question @DanielRosenwasser: do you want me to rename the flag to `explainInputFiles` ?

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by thetutlage** [comment]
I see that the `configFileSpecs` has been removed from the output of `getParsedCommandLineOfConfigFile`. What's is alternative to get access to it?

**Comment by sheetalkamat** [comment]
> The configFileSpecs are stored on tsconfigFile so we dont have to pass them around any more.

**Comment by thetutlage** [comment]
I read that, but looking for the ways to access them. Is there is any new API for the same?

**Comment by sheetalkamat** [comment]
It was always internal (meaning subject to change). We do not plan to expose that through API.

**Comment by pelikhan** [comment]
Any easily parseable format would be nice JSON or directly graphviz style files; would allow for visualizations and tooling.

**Pull request merged**
