### PR TITLE
Omit intersection property check when source includes target

### LINKED ISSUE #53009: material-ui docs OOM after intersectionState propagation in relations
While redoing benchmarks for the 5.0 RC blog post, I foud that material-ui's docs now OOM.

A bisect points to #52392, and reverting this PR makes things compile at a reasonable speed again.

Steps to reproduce what I'm doing exactly:

```
$ git clone https://github.com/mui/material-ui.git
$ cd material-ui
$ yarn
$ node ~/path/to/tsc.js -p ./docs
```

cc @ahejlsberg

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53009.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
No regression test included, but I have manually verified that this causes material-ui to successfully compile.

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Just rechecking in case those two regressions are just noise. I'm pretty sure they are.

@typescript-bot perf test

**Comment by DanielRosenwasser** [comment]
Is the test case in this PR representative of the 5.0 regression we saw in the latest material-ui?

**Comment by ahejlsberg** [comment]
Tests and performance all look good. Merging.

**Pull request merged**
