### PR TITLE
More accurate translation for "Function Expression"

### LINKED ISSUE #43975: More correct translations for "Function Expression" in lib/ko/diagnosticMessages.generated.json
# lib Update Request

## Configuration Check

Does not apply.

## Missing / Incorrect Definition

Does not apply.

## Sample Code

Does not apply.

## Documentation Link

Hi 🙌 It's talking about Translation into Korean.

Regarding the notation for "Function Expression", I think "함수 표현식" is a better expression.
As you can see in [MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/function), "Function Expression" is specified as "함수 표현식" rather than "함수 식".

When checked with a translator, the two seem to have the same meaning.
However, strictly speaking, it can be taken in a different meaning.

### PR DESCRIPTION
**Pull request by leon-dunamu**
Update a more correct translation.

Fixes #43975

### CODE REVIEW

**Comment by Kingwl** [comment]
Thanks for the contribution.

AFAIK, You should @csigs.

/cc: @orta.

**Comment by 1Seok2** [comment]
> Thanks for the contribution.
> 
> AFAIK, You should @csigs.
> 
> /cc: @orta.

What does `You should @csigs.` mean?
If there is anything I need to do, please let me know in detail!

**Comment by Kingwl** [comment]
`@csigs` is a localization team who provided the translated TypeScript diagnostic message.

Your PR might conflict with the localization team. So I thought It's better to let them know (And may commit by the localization team their own).

**Comment by 1Seok2** [comment]
I got it! Thank you for explaining 👍

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.

**Pull request closed without merging**
