### PR TITLE
Fix crash with unmet generic constraints

### LINKED ISSUE #3464: TypeError: Cannot read property 'failedTypeParameterIndex' of undefined
I'm getting this exception with TypeScript 1.5.0-beta when I'm creating a class which doesn't satisfy the constraits of the generic type.

```
C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14007
                    ts.Debug.assert(resultOfFailedInference.failedTypeParamete
                                                           ^
TypeError: Cannot read property 'failedTypeParameterIndex' of undefined
    at resolveCall (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14007:60)
    at resolveCallExpression (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14088:28)
    at getResolvedSignature (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14170:47)
    at checkCallExpression (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14186:29)
    at checkExpressionWorker (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14875:28)
    at checkExpressionOrQualifiedName (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14826:42)
    at checkExpression (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14818:20)
    at checkExpressionStatement (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:15785:13)
    at checkSourceElement (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:16946:28)
    at Object.forEach (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:37:30)
    at checkBlock (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:15551:16)
```

Unfortunately, I'm not able to create a small reproducable test case. It should be similar to this:
```
interface A {
    foo: any;
    bar: any;
}

interface C {
    prop: any;
}

interface B extends C {
    foo: any;
}

module Test {
    export class Foo<T extends A> {
    }
}

class Bar extends Test.Foo<B> {
}
```

but that reports the error correctly.

If I comment out lines 14007...14011 in my application's build, the error is reported correctly:
```
C:/Projects/my_project/lib/data_storage.ts(282,45): error TS2344: Type 'FooConfig' does not satisfy the constraint 'BarConfig'.
  Types of property 'foo' are incompatible.
    Type '{ service: { id: string; fooUri: string; barUri: string; }; otherProperty: { barUri: s...' is not assignable to type '{ service: { name: string; type: string; id: string; fooUri: string; barUri: string; ...'.
      Types of property 'service' are incompatible.
        Type '{ id: string; fooUri: string; barUri: string; }' is not assignable to type '{ name: string; type: string; id: string; fooUri: string; barUri: string; }'.
          Property 'name' is missing in type '{ id: string; fooUri: string; barUri: string; }'.
```

### PR DESCRIPTION
**Pull request by randombk**
Fixes #3464

### CODE REVIEW

**Comment by mhegazy** [comment]
@DanielRosenwasser can you take a look.

**Comment by JsonFreeman** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Thanks!

**Pull request merged**
