### PR TITLE
Numeric Range Types

### PR DESCRIPTION
**Pull request by ECrownofFire**
Based on #15480, specifically https://github.com/Microsoft/TypeScript/issues/15480#issuecomment-427790371 by @AnyhowStep.

This likely needs some more plumbing and more test cases, especially for intersections and unions involving ranges. Ideally I would like for intersections and unions to merge ranges as applicable if they overlap, but similar to subtype reduction in unions, it may not be necessary or wanted. Though it may be good to at least do elimination similar to literals and primitives (e.g. `1 | number` -> `number` and `1 & number` -> `1`).

This is of course a bit more limited than the suggestions in #15480, mainly in that it lacks an `int` type (I considered that a separate issue). This makes it less directly applicable to some use cases, but still provides some much stronger guarantees.

So for a couple quick examples: `var foo: (> 0);` denotes a number that must be positive. `(< 0) | (> 0)` denotes any number *but* zero. And `(>= -1) & (<= 1)` is any number between -1 and 1, inclusive.

A couple limitations/notes:

1. Performing any sort of arithmetic with a range type will cause the result to degenerate to a plain `number`. I have [an alternate branch](https://github.com/ECrownofFire/TypeScript/commits/ranges) that does implement this, but e.g. #8112 and #15645 indicate that type arithmetic in general is undesired, so I dropped those commits from this PR.

2. There's no support for anything but a number literal in the range type. This means that, for example, you can't use generics like `type Gt<T> = (> T);`. This was mostly to simplify parsing and such, but it's probably something that could be added. Ideally this would also support the same sort of expressions that enum member initializers do, though that would likely require some reorganizing of `checker.ts` to genericize `evaluate()`.

3. As the compiler doesn't support bigints, ranges also don't support them.

And a couple possibilities/wish list items for the future:

1. Flow analysis, such as narrowing numbers to ranges based on comparison checks. Definitely a "nice to have" thing, and could be added later. Could also do things like say, if you have `var foo: (>= 0)`, then you know `if (foo < 0)` can never be true, and that branch is unreachable.

2. Syntax for other range styles, such as the proposed `a..b`, which in interval notation would be `[a, b]`, or `(>= a) & (<= b)`.

### CODE REVIEW

**Comment by ajafff** [comment]
some more items for the wish list:

* the `length` property of open-ended tuples can be represented as number range
* lib.xxx.d.ts could be updated, e.g. `Array#length`, `Map#size`, `Array#indexOf/findIndex`, etc.

**Comment by calebsander** [comment]
> As the compiler doesn't support bigints, ranges also don't support them

Although the compiler is written to run on environments where `BigInt` is not supported, it would certainly be possible to implement `bigint` ranges. The compiler represents `bigint` literals as base-10 strings and there is a `parePseudoBigInt()` function that standardizes any `bigint` literal (e.g. `0x0000FFFFn`) into its base-10 representation (e.g. `65535`). I don't think it should be too hard to compare two of these `PseudoBigInt` values: if the values have different numbers of digits, the one with more digits is larger; if they have the same number of digits, they can be compared lexicographically.

**Comment by weswigham** [comment]
> As the compiler doesn't support bigints, ranges also don't support them.

Well, we support `bigint` types, though...

**Comment by ECrownofFire** [comment]
Hm, actually yeah it should be possible to set it up in a way that doesn't *require* BigInt support, I'll take a look at doing that.

**Comment by nikeee** [comment]
While type-level arithmetics are rejected, this PR seems like an operation `a % N` (with N being a constant literal and a being a range/number/union of numbers) could actually be useful to create or narrow a range.

**Comment by sandersn** [comment]
I'm cleaning up our PR backlog and this is one is fairly stale, so I'm going to close it.

@ECrownofFire The next step is to create an issue with a complete proposal for numeric range types. You'll need to consider assignability between range types and number types, which can get fairly tricky for type parameters with constraints that are range types. Expect considerable bikeshed discussion on syntax as well, since language designers' favourite quibble is lexical syntax.

**Pull request closed without merging**
