### PR TITLE
Update to npm 8, pin in package.json via volta and corepack

### LINKED ISSUE #49726: Upgrade TypeScript lockfile to v2 (upgrade to NPM v7 or higher)
# Suggestion

https://github.com/microsoft/TypeScript/blob/main/package-lock.json

This file should be upgraded to use NPM lock file V2 (needs NPM v7 or higher).

## 🔍 Search Terms

lock file

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ⭐ Suggestion

Upgrade to NPM v7

## 📃 Motivating Example

Since there is no way to disallow NPM v7 or higher to not update the lock file to v2, it is very annoying when working on the TypeScript repo.

```
TypeScript > npm install

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```

image

Every time you run `npm install`, this will happen.

Upgrading to npm v7/8 is a good way to solve this problem.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #49726

But, I'm a bit apprehensive about this just because we have to make sure people have upgraded versions of things.

- Volta users will be just fine.
- corepack users, maybe not? https://github.com/nodejs/corepack/issues/138
  - It works, but you have to run `corepack enable npm`.
- nvm for *NIX, should be okay https://github.com/nvm-sh/nvm/issues/2803
- nvm for Windows, should be okay. https://github.com/coreybutler/nvm-windows/issues/660
- fnm users, maybe not? https://github.com/Schniz/fnm/issues/566
  - I've had success with corepack under fnm with the same `corepack enable npm`.
- n should work too.

We'd be better if people just used newer versions of node (16+ ship with npm 8), however, I know many people stick with Node 14 as that's the last version with frame restarting for debugging, and that's why our volta config says what it does.

~~I have a TODO for the workflow, but I need to wait a few days to be able to see if the command it runs actually changes anything.~~ Otherwise, it's not the right way to update the lockfile. Honestly, it's probably better to just have it delete the lockfile and recreate it from scratch. It's run nightly, so I do not expect conflicts given the frequency of the fixups.

### CODE REVIEW

**Comment by jakebailey** [comment]
There doesn't seem to be a way to emulate npm 6's odd side-effect behavior to use for updating dependencies automatically. IMO that's good (I hate side effects), but for our action we need something, so I've done what I normally do for "update everything" scripts and just have it remove the lockfile. This should be okay because it runs every day.

The only remaining thing to do here is likely to add some sort of documentation that suggests using `volta` or running `corepack enable npm` (which should work without any extra installing thanks to corepack's inclusion in current Node 14/16 versions). I also will try and add `engines` that specify the npm version to.

**Comment by jakebailey** [comment]
I'm thinking we don't really have to provide any guidance here; I think if people push bad lockfiles to their branches we'll notice and can advise then.

**Comment by jakebailey** [comment]
I have absolutely no idea who's the best to review this.

**Comment by DanielRosenwasser** [comment]
Definitely the best endorsement I could ever receive.

**Review by andrewbranch — APPROVED** [review]
My preferred method of review for this kind of thing is to merge it and see if it causes problems. Seems like you’ve done your research and will recognize if there's some reason we need to roll back.

**Comment by jakebailey** [comment]
Thanks for the approval.

Do we want to wait for this until after we cut 4.8, or is this low risk enough that it's not going to matter?

**Comment by andrewbranch** [comment]
I don’t think this has any impact on release considerations.

**Pull request merged**
