### PR TITLE
Add d.ts for Intl.RelativeTimeFormat

### PR DESCRIPTION
**Pull request by DmitryMakhnev**
[Intl.RelativeTimeFormat proposal](https://github.com/tc39/proposal-intl-relative-time) was moved to [stage 4](https://github.com/tc39/proposal-intl-relative-time#implementation-status) and included into [ecma402 finished proposals](https://github.com/tc39/proposals/blob/master/ecma402/finished-proposals.md#finished-proposals)

Fixes part of #29129

### CODE REVIEW

**Comment by orta** [comment]
👋 hi, you submitted this just as we were preparing for a release, and we get really slow on 3rd party PRs during that period. We're now on 3.9 for master and I think this looks good. You're welcome to ping me on any `Intl` PRs you're looking at.

I've only got one request, can you consider adding some JSDoc comments to the  user facing parts of the API?

**Comment by DmitryMakhnev** [comment]
👋@orta
Thank you so much for information! 🙏

Could you give me the rules for these JSDoc comments or link to example of it in the current codebase.

**Comment by orta** [comment]
There aren't any rules - it's just that you see these in your editor, and it's good to provide context for users. For example, I took some of the [spec text](https://github.com/tc39/proposal-intl-relative-time#api) and applied the useful bits of text to the prominent user-facing parts of the API 

```ts

interface RelativeTimeFormat {
    /**
     * Formats a value and unit according to the locale and formatting options of this Intl.RelativeTimeFormat object.
     *
     * While this method automatically provides the correct plural forms, the grammatical form is otherwise as neutral as possible. It is the caller's responsibility to handle cut-off logic such as deciding between displaying "in 7 days" or "in 1 week". This API does not support relative dates involving compound units. e.g "in 5 days and 4 hours".
    */
    format(
        value: number,
        unit: RelativeTimeFormatUnit,
    ): string;

    /**
     *  A version of the format method which it returns an array of objects which represent "parts" of the object, separating the formatted number into its constituent parts and separating it from other surrounding text.
     */
    formatToParts(
        value: number,
        unit: RelativeTimeFormatUnit,
    ): RelativeTimeFormatPart[];
    
    resolvedOptions(): ResolvedRelativeTimeFormatOptions;
}
```

Screen Shot 2020-02-11 at 3 15 18 PM

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.

**Comment by DmitryMakhnev** [comment]
Hi @sandersn. Sorry for big delay. I added docs by @orta's [request](https://github.com/microsoft/TypeScript/pull/36084#issuecomment-584769420).
Can you reopen this pull request?

**Comment by sandersn** [comment]
Sure.

1. @DmitryMakhnev can you merge with master to get rid of the merge conflict?
2. @orta can you review the newly-added documentation?

**Comment by orta** [comment]
These look great!

**Comment by DmitryMakhnev** [comment]
@sandersn 
> 1. @DmitryMakhnev can you merge with master to get rid of the merge conflict?

Done.

**Comment by DmitryMakhnev** [comment]
@sandersn @orta
Should I do anything else for this PR?

**Comment by orta** [comment]
Nope, this is good to go! Thanks

**Comment by kripod** [comment]
Whoa, I just checked why `Intl.RelativeTimeFormat` was throwing an error on me and ended up at this issue right this time. Great job on getting this done, thank you! 🙏

**Comment by kwasimensah** [comment]
What's the ETA for this being in the published  typescript npm package?

**Comment by sandersn** [comment]
@kwasimensah Should be 4.0. See https://github.com/microsoft/TypeScript/issues/38510 for details.

**Comment by Licen-it** [comment]
> @kwasimensah Should be 4.0. See #38510 for details.

@sandersn any news on the ETA for having this published? Just checked latest version and it's still not there.

**Comment by barakplasma** [comment]
@Licen-it 
It's in Typescript 4.2.3 already, but you have to update your tsconfig.json to target ES2020. Here's an example:
```ts
const timeFormatter = new Intl.RelativeTimeFormat(['en', 'fr', 'es', 'it', 'pt'], { numeric: 'always' });
```

[Playground Link](https://www.typescriptlang.org/play?target=7&jsx=0&module=6&ts=4.2.3#code/MYewdgzgLgBFCWBbApgMRAJ0QQylZGMAvDGMgO4wCSYUANgHQBKydu8AbsgCpJqY4oACgDaAcmRgxAGhhiAZhhlzkEZWPhR1ABy0BdWQG9SAVxQZ4wAFxzsdctgCeamAF8AlAG4gA)

**Comment by Licen-it** [comment]
> @Licen-it
> It's in Typescript 4.0.5 - 4.2.3 already, but you have to update your tsconfig.json to target ES2020. Here's an example:
> 
> ```ts
> const timeFormatter = new Intl.RelativeTimeFormat(['en', 'fr', 'es', 'it', 'pt'], { numeric: 'always' });
> ```
> 
> [Playground Link](https://www.typescriptlang.org/play?target=7&jsx=0&module=6&ts=4.2.3#code/MYewdgzgLgBFCWBbApgMRAJ0QQylZGMAvDGMgO4wCSYUANgHQBKydu8AbsgCpJqY4oACgDaAcmRgxAGhhiAZhhlzkEZWPhR1ABy0BdWQG9SAVxQZ4wAFxzsdctgCeamAF8AlAG4gA)

Thanks...didn't think about changing the target in tsconfig. Thanks

**Pull request merged**
