### PR TITLE
Properly check whether union type contains only primitive types

### LINKED ISSUE #46624: some types in 4.5.0 aren't correctly resolving to same types in 4.4.4
# Bug Report
I recently ran into the this strange error when I updated to typescript 4.5.0-beta, generic types that were resolving properly in 4.4.4, are not correctly resolving in 4.5.0-beta. Instead 4.5.0 returns a unions of all of the possible values while the same code in 4.4.4 returns a narrowed generic type.

### 🔎 Search Terms
4.5.0-beta, unions, generics

### 🕗 Version & Regression Information
typescript@beta, 4.5.0-beta, typescript@next

- This changed between versions 4.4.4 and 4.5.0-beta

### ⏯ Playground Link
Same code for both versions:

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/KYDwDg9gTgLgBDAnmYcDWBLAdgEzgXjgCIItgi4AfYmAdwguqJgAsphyBuAKG9ElhxsMYFABmAQwDGqAPJgYGUgGcAPABUAfHADe3OEJEBbAPwAuOOp4GkKc+mw4eAX1625ZAruc93l+l46Ptx+6mwcgcEhyB7A8ooqXvFKWGqyZJq+Mf4QyYmEeaka9JnRKJbhcQopSdUqGpWl3MKikjJwALISYCg4AJJYIuLSVQmpuvoGxKTkFumjKcrWU8z0RBbq9IVLkwbMlesV7AukLrz80PB+A0NtwACiIDBQ0jDQqpPqcKAiuMoOuAANNxtIQvj9gH8AThJiZOt1ejdWiNtgBtdQAXW+T0hOH+21U2DEojgfWMml2cDhZOARkpFjIADdRJM5nUivMmhdBH4AAoSF5GNTgnFQzC4UGTah6KZTdz2KyU5xwABkcAJSOGMkez1e7y0TRwwCkABsBagxABXLBSMZwADmwBgmruADEoBAjABlZ7Ye0fAwi3546HAzQACgg7OU9n5guFmgAlBYXSMdS9bfqmlIVPB2MpLSb4IRHc7BsiZO7PT6oH7wzoEDELAByOgQZtwZyJzhAA)

### 💻 Code

```ts
export type kind = "one" | "two" | "three";

export interface Options<T> {
  item?: T;
  type?: kind;
}

type One = {};
type Two = {};
type Three = {};

type OneOptions = Options<One>;
type TwoOptions = Options<Two>;
type ThreeOption = Options<Three>;

interface MappedInterfaceOptions {
    "one": OneOptions;
    "two": TwoOptions;
    "three": ThreeOption;
}

export type InterfaceExtractor<
  T extends kind,
> = T extends kind
  ? MappedInterfaceOptions[T] extends Options<infer Item>
    ? Item
    : never
  : Options<One>;

export type Params<T extends kind> = { type?: T; } & Options<InterfaceExtractor<T>>;

declare function getInterfaceFromString<
  T extends kind,
>(options?: Params<T>): InterfaceExtractor<T>;

// Typescript 4.4.4 states the type is `Two`, 4.5.0 states the type is `One` | `Two` | `Three`
const result = getInterfaceFromString({ type: 'two' });
```

### 🙁 Actual behavior

In typescript 4.4.4 the type is correctly resolved to `Two`, whereas in typescript 4.5.0 the type is resolved to `One | Two | Three` which is incorrect.
4.4.4:
Screen Shot 2021-11-01 at 1 27 03 PM
4.5.0-beta:
Screen Shot 2021-11-01 at 1 27 22 PM

### 🙂 Expected behavior

The correct type for `result` in the playground and the codesample is `Two`, not `One | Two | Three`, typescript 4.5.0 should resolve to this type.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #46624.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
I'd definitely recommend cherry picking this for 4.5.1, particularly since the issue is somewhat unpredictable.

**Review by andrewbranch — APPROVED** [review]

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5

**Comment by ahejlsberg** [comment]
Just fixed the regression test. Will start a new cherry pick.

**Comment by ahejlsberg** [comment]
@typescript-bot cherry-pick this to release-4.5

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.5

(#46647)

**Comment by andrewbranch** [comment]
The cherry-pick build checks out the PR head, not the merge commit, so my change to the script didn't get picked up. We'll have to do this one manually.

**Pull request merged**
