### PR TITLE
fix lookup regression again and again

### LINKED ISSUE #26808: wrong referenced symbol in parameter intializer
**TypeScript Version:**  3.1.0-dev.20180831

**Search Terms:**

**Code**

```ts
// @target: ES2016
let foo = 1;
function test(bar = foo, foo = '') {}
```

**Expected behavior:**

`foo` in the initializer of `bar` references the parameter `foo` of type `string`.
Use before declare error for `foo`.

**Actual behavior:**

`foo` in the initializer of `bar` references the outer variable declaration `foo` of type `number`.
No use before declare error.
Exception when running this code.

**Related Issues:** 
introduced by #26317 while trying to fix #22769
#26762 

/cc @Kingwl again

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #26808 

hope do not fix again and again and again🤷🏻‍♂️

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@Kingwl thank you for your persistence and timely responses on this! Obviously we are starting to get a little worried - #26813 also just came up, though it appears to be fixed by this PR.

I'm going to revert the prior two PRs and ask that you submit a fresh PR with this fix and the prior ones all rolled into one, along with testcases. I'll put the tests in the revert PR, along with an extracted repro from #26813, so that we can more easily review the changes together and make sure the right thing is happening.

Thanks again!

**Comment by RyanCavanaugh** [comment]
#26820 is in now, so please rebase

**Comment by Kingwl** [comment]
sorry about that😅

**Comment by Kingwl** [comment]
updated

**Comment by RyanCavanaugh** [comment]
@Kingwl can you fix the merge conflict? Sorry for the delay

**Comment by Kingwl** [comment]
sure, a few moments later

**Comment by RyanCavanaugh** [comment]
Looks good; let's see what shows up in nightly feedback 😅

**Comment by Kingwl** [comment]
seems everything is ok :laughing:

**Pull request merged**
