### PR TITLE
Control flow analysis for destructured discriminated unions

### LINKED ISSUE #10830: aliasing discriminated union tag breaks case analysis
**TypeScript Version:**  2.1.0-dev.20160909

**Code**

```ts
type A = {t: "a", a: string};
type B = {t: "b", b: string};
type U = A | B;

const a: U = {t: "a", a: "a"} as U;

if (a.t === "b") {
	a.b; // works as expected
}

const {t} = a;
if (t === "b") {
	a.b; // error TS2339: Property 'b' does not exist on type 'U'.
}
```

**Expected behavior:**

The type of `a.t` should correctly transfer to `t` when assigning or using destructuring. `t` should be usable as discriminant.

**Actual behavior:** 

The type of `t` is widened from `"a" | "b"` to `string` and therefore can not be used as discriminant any more.

As the same happens also for flow (See https://github.com/facebook/flow/issues/2409), it may be my thinking that is a little bit off. But I think that the case should be valid. The programmer should not be forced to repeat `base.` all over, that’s what variables are for.

### LINKED ISSUE #35283: Type refinement does not get applied to a destructured shared field in a discriminated union
**TypeScript Version:**
`3.8.0-dev.20191121`

**Search Terms:**
- refinement
- guard

**Code**

```ts
interface A<T> {
  variant: 'a'
  value: T
}

interface B<T> {
  variant: 'b'
  value: Array<T>
}

type AB<T> = A<T> | B<T>

function printValue<T>(t: T): void {
  console.log(t)
}

function printValueList<T>(t: Array<T>): void {
  console.log(t)
}

function unrefined1<T>(ab: AB<T>): void {
  const { variant, value } = ab

  if (variant === 'a') {
    printValue<T>(value)
  } else {
    printValueList<T>(value)
  }
}

function unrefined2<T>(ab: AB<T>): void {
  const { variant } = ab

  if (variant === 'a') {
    const { value } = ab
    printValue<T>(value)
  } else {
    const { value } = ab
    printValueList<T>(value)
  }
}

function refined<T>(ab: AB<T>): void {
  if (ab.variant === 'a') {
    const { value } = ab
    printValue<T>(value)
  } else {
    const { value } = ab
    printValueList<T>(value)
  }
}

```

**Expected behavior:**
A destructured shared field of a discriminated union should be refined inside of a block that refines the discriminated union itself. I think the code example explains what I'd expect to happen better than I can in words.

**Actual behavior:**
Variables that are destructured prior to the union being refined are still stuck as unions within a block where the discriminated union is refined.

**Additional comments:**
- For what it's worth, the code example above is still valid without a type parameter i.e. a concrete type where `T` would be
- I can't think of any scenario where the destructured value would not be correctly refined if this behavior were implemented.

**[Playground Link](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20191120&ssl=1&ssc=1&pln=52&pc=1#code/JYOwLgpgTgZghgYwgAgIIB4AqA+ZBvAWAChlkA3OKYOcALmQHI4HjSKAbAVwns2IF9ixUJFiIUAISy5CJcpWp1GAIxZyO3eqihQ4AT2kChRMHoAOKVFJzIAvGmnIAPsmvZjMTiARhgAexBkMypwADU4LghpAAowXgBKejI-YAATfFZkBACAZz92CAA6dj8Ac1j4oyJiT29fAKCQsHDIgBlgHLAYuLQdfWlE8hT02VJskDyC4rKKqpqvH39A4JEW7gB5KHbOgFUQKAgYUAhUgEYYuGUtN0HktIy5cc78eSoaMAAaeUjkfjtkS7GUjAGDIaIUN7gOy2exMBjxB6kUgrMIRbgxDQQSpyP4Qdg5FCjJEo5poiDbLo4cFk7GkQREenzOpLRqrMmbCl7A5HEAnABMFyuaBuSWGiKyuTALwhiilf3sgOqchBYJl72hsOYCKJY0l0rJv3+iqRrNRkQxNMyuPxhMyuomUrw324hoVyjtptJbQ6lOw1MitN+cyItUWDRJawgHJ9ACVDsdUoLrgNRfciSropdCmqoTDNfDxfbnk7Ma6Ae65MimpGLQGrcg8QTCxKHfqfvLyx6I2SKbXuIH6fSgA
)** 

**Related Issues:** 
I couldn't find any open issues regarding object destructuring and type guards, but these were the only two closest to the issue I'm seeing.
#18840 - Type guards on variable break refinements on its properties
#20504 - Nested if statement invalidates type guards

### LINKED ISSUE #38020: Union discrimination breaks when destructuring parameters
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:** discriminated discrimination union destructured parameters

**Code**

```ts
type Action = | {type: 'add', payload: {toAdd: number}}  | {type: 'remove', payload: {toRemove: number}}

const reducerBroken = (state: number, {type, payload}: Action) => {
    switch (type) {
        case 'add':
            return state + payload.toAdd
        case 'remove':
            return state - payload.toRemove
    }
}


const reducerWorking = (state: number, action: Action) => {
    switch (action.type) {
        case 'add':
            return state + action.payload.toAdd
        case 'remove':
            return state - action.payload.toRemove
    }
}
```

**Expected behavior:**
Typescript recognises that the `type` of the action has been checked and that the action has been refined to a specific one where the `payload` properties can be safely accessed.

**Actual behavior:**
Typescript does not refine the type and it errors saying that the `action` could be any of the `payload`s specified in the union type.

**Playground Link:** 
https://www.typescriptlang.org/play/?ssl=21&ssc=2&pln=1&pc=1#code/FAFwngDgpgBAggYxASwPYDsYF4YB8YDe40AXDAOQCGAJteQDQwSVgA2qNZRqctZ6AVwC2AIygAnAL6SYeQsShly4qENQA3KAyYt2neagBKqjYpiDRE6cGAIMAZxAwV1AQgkAhcagDWUTDgAFI6UIGYWYuKMRJBQjMxsHNSSZIgoGACU2AB8hMCysvYA7sggCAAWMIEKWQT5BQ0IlPawVLTkJPUN3c5QIALimCFhMADUOok0AHQgPLRd3U0tFCpqmh0LPbIq-YMww7AAtBN61DNGJpoLksA3Nnbojr2u7uIA6qjiPsjoAObYVQO-GEkUYlCQaHQqQhmRyeQaxVKFSq4PS6BmsVqmwKS1aNDonS23R2AyGIFCsHGqMhUwSp3OvGo2NkuJWly0hKJBRJewOMGO1IwtN0SXOxjWUGutyAA

**Related Issues:**

### LINKED ISSUE #46143: Alias type conditions to desctrutured variables
# Suggestion

## 🔍 Search Terms
is:issue is:open control flow analysis destructure 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

TypeScript 4.4 has a feature called [Control Flow Analysis of Aliased Conditions and Discriminants](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#cfa-aliased-conditions), which essentially allows a variable to carry type information about another variable.
I believe something similar could happen when destructuring discriminated unions.

Object destructuring is a very common pattern in JavaScript, but we need to avoid it often in TypeScript because it loses type information:

```ts
declare var it: Iterator<number>;
const { value, done } = it.next();
if (!done) {
  value; // we know it's a number, but it's any
}
```

has to be artificially transformed to satisfy the typechecker:

```ts
const result = it.next();
if (!result.done) {
  result.value; // is narrowed to a number
}
```

With TypeScript 4.4, it looks like we're very close to having this feature:
```ts
const result = it.next();
const { value, done } = result;
if (!done) {
    result.value; // `done` tracks result's type
    value; // but not value's
}
```
## 📃 Motivating Example
These patterns emerge naturally in JavaScript and currently have to be transformed to fit TypeScript's ability to infer types.
The IteratorResult example above.
Another example is with action to state reducers:
```ts
type Action =
  | { type: 'A', payload: number }
  | { type: 'B': payload: string };

function reducer(state: Whatever, { type, payload }: Action) {
  switch (type) {
    case 'A':
      payload.toFixed();
      break;
    case 'B':
      payload.toUpperCase();
      break;
  }
}
```
## 💻 Use Cases

I think the examples above already cover this.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR implements control flow analysis for dependent parameters and variables declared by destructuring discriminated unions. Specifically, when non-rest binding elements are declared as `const` variables or const-like parameters (parameters for which there are no assignments in the function body) and the parent type for the destructuring is a discriminated union type, conditional checks for variables destructured from discriminant properties now affect the types of other variables declared in the same destructuring.

Some examples:

```ts
type Action =
    | { kind: 'A', payload: number }
    | { kind: 'B', payload: string };

function f10({ kind, payload }: Action) {
    if (kind === 'A') {
        payload.toFixed();
    }
    if (kind === 'B') {
        payload.toUpperCase();
    }
}

function f11(action: Action) {
    const { kind, payload } = action;
    if (kind === 'A') {
        payload.toFixed();
    }
    if (kind === 'B') {
        payload.toUpperCase();
    }
}

function f12({ kind, payload }: Action) {
    switch (kind) {
        case 'A':
            payload.toFixed();
            break;
        case 'B':
            payload.toUpperCase();
            break;
        default:
            payload;  // never
    }
}

function f13(it: Iterator<number>) {
    const { value, done } = it.next();
    if (!done) {
        value;  // number
    }
}
```

Fixes #10830.
Fixes #35283.
Fixes #38020.
Fixes #46143.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
Tests look good (best I can tell, lots of existing noise), performance impact is less than 0.5% and possibly just noise.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test faster

**Comment by athyuttamre** [comment]
This is super exciting, thanks for working on this @ahejlsberg! I just ran into this today when working with `Result` types.

**Comment by slorber** [comment]
@DanielRosenwasser maybe it's worth adding this feature to the 4.6 beta blog post:

https://devblogs.microsoft.com/typescript/announcing-typescript-4-6-beta/#control-flow-analysis-for-dependent-parameters

The blog post does not mention object restructuring, only tuple/union destructuring, but I checked the 4.6 nightly playground and it works with objects too now, which is highly anticipated by React users (more than the example showcased in the blog post IMHO)

**Comment by DanielRosenwasser** [comment]
Seems like the difference there is the spread, right?

Okay, that's a good call, we must have missed that. I will likely add that to the RC post.

**Comment by DawChihLiou** [comment]
Awesome! Thank you so much❤️

**Comment by slorber** [comment]
@luxalpa tracked here: https://github.com/microsoft/TypeScript/issues/46680

Would also like to see this implemented 😄

**Comment by 50an6xy06r6n** [comment]
I've noticed that this feature doesn't seem to play nice with default values:
```
type T = {
	flag: true;
	a: number;
} | {
	flag: false;
	a: string;
}

// This code works if you remove the "= true"
({ flag = true, a }: T) => {
	if (flag) {
		a.toFixed(); // thinks it can be either a string or number again
	} else {
		a.toUpperCase(); // same as above
	}
}
```
Is this also covered by https://github.com/microsoft/TypeScript/issues/46680 or is there another reason it doesn't work?

**Comment by RyanCavanaugh** [comment]
@50an6xy06r6n that feels like a bug

**Comment by ahejlsberg** [comment]
It's a design limitation, but one we could consider removing. We only do CFA for dependent destructured parameters when they're declared without initializers because it adds complexity to consider the contribution the initializer might make to the inferred declared type of the parameter.

**Comment by 50an6xy06r6n** [comment]
@ahejlsberg intuitively it feels like it should work. In my case (react), the way props work means you have to pass parameters as an object, though I realized that there's other ways to set the default value.

**Comment by josh-leyshon** [comment]
This also does not work when destructuring a nested discriminated union type. See [playground link here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAiBLAzgYwE6ILaIHYENgIATAFXGgF4oBvAKCkalwmSOIC5aGneBrPJygByfMJ69GWfCABGEAKq5iEAGZ4SAZWDoA-FzaZcAcwlQAvnXNQAPt14s2JLvUlMByrsNni3UmfJKKuosxNroBjp4pryWlnSqAK64qMCIAPa4UMYQwHBIaJg4BOzkkAAUAJRc+SgY2HiEJGXQrkzouYnoWW1ujuwuZn5QHkKivn7mADRmcXR0APQLUACSqlAA7tAqhompXdDAABbQ-SRQ6bIAVhCpUPgANg-3wBcpEFNQoJDM+Ojo6Q20SgsnwyHOmSgxDqRUa7C+FCh6VYuGEr3SqFQXQAdHRUJk2LRmKwBkTRp9pHJFMo1BowjoLIzqDk8ggYQ0Ss0KFU6Ih1uVRlBKMKRD5KvYmEsoABRABKsoA8rKuAADSmBGkhLQ6FVQZBHdKJB7EX7-QFfdJvB4gKAqwzRXXfCC43j43CEwyRIzGIVQdXU4J08JWeZStabbYk9B7YAHKB4PUQMB-Jp64BNLAQXDAZCfRCvYjI5CbdLoPi4t2EmjEpwm6zM3K1QocppkbmVPEE17V0ZcUYAJgpAQDtNC4S4-qCo+16H7TJr7F5-IHQpF3mE4t6UClAGElbLpTvSFwWqaAVsTYBeDcAsjtmSuvT1p72+yeaoM6ftWIA).

I assume this is because of this line in the PR description:
> and the parent type for the destructuring is a discriminated union type

Since the object is nested, the parent type being destructured is not the discriminated union. Still, it's a shame this does not work.

**Comment by margaretdax** [comment]
I am currently running into issues with this (or a related) analysis. I have a union `[A, B] | [C, D] | [E, F]` and functions isA() isC() isE() and regardless of destructuring or not, narrowing the first tuple member cannot narrow the second tuple member.

**Comment by GulgDev** [comment]
That's a great feature, I personally use it to make global variables dependant on each other:
```ts
interface BrowserAPI {
    context: "browser";
    doBrowserThing(): void;
    doNodeThing: never;
}

interface NodeAPI {
    context: "node";
    doNodeThing(): void;
    doBrowserThing: never;
}

declare const api: BrowserAPI | NodeAPI;

const { context, doNodeThing, doBrowserThing } = api;

if (context === "browser") {
    doBrowserThing();
} else {
    doNodeThing();
}
```
But it lacks one thing necessary for my usecase: a way to use destructuring in a declaration file (`.d.ts`). I can't actually perform destructuring, because all the API is defined on the global object at run-time.

**Pull request merged**
