### PR TITLE
Only call `getLowerBoundOfKeyType` on non-generic mapped types

### LINKED ISSUE #56232: Crash due to circularity in `getIndexTypeForMappedType`
### 🔎 Search Terms

Crash, circularity, mapped type

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwCYAeAFXhAA8MRVgBneAb3gG0AFeLfAaxACeORPAoAyeAwwweAc3hQmAYSgAHLBigQsALxAkOAPgC6ALngA1eAF8ANJco06jSdLmGAFFHNkAlD4BuAChqVRwYDHgwPCl4GCJ4AF4CYg9mAEFzACIoLOtfYKA

### 💻 Code

```ts
declare function foo2<T extends { [P in keyof T & string as Capitalize<P>]: V }, V extends string>(a: T): T;
export const r2 = foo2({A: "a"});
```

### 🙁 Actual behavior

Maximum call stack size exceeded.

### 🙂 Expected behavior

No crash.

### Additional information about the issue

Found this while investigating #49238.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #56232.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test top100
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this faster

**Comment by ahejlsberg** [comment]
Tests and performance all look good.

**Review by weswigham — APPROVED** [review]
In a `keyof` context, the generic component added to the index type *should* function the same anyway (and any cases where it doesn't are surely edge cases we could fix in other ways).

IIRC, originally this had the concrete-bound-adding bit to make mapped types work, but mapped types nowadays pull apart the index type themselves to handle index signatures better (and get around union reduction) *anyway*, so I *think* the removed branch should be wholly redundant. The generic part got added later for either inference or relationship checking (don't remember which, maybe both), but at the time, we still needed the concrete bit for mapped type creation.

**Comment by sandersn** [comment]
@ahejlsberg this looks ready to go for 5.4. Is it? Or maybe it should be in 5.3.3.

**Pull request merged**
