### PR TITLE
Fix 8467: Fix incorrect emit for accessing static property in static propertyDeclaration

### LINKED ISSUE #8467: Bad ES6 emit accessing named class-expression in its own static initializer
```ts
let c = class NCE {
    static x = 1;
    static y = NCE.x * 2;
}
```
Output with `--target ES6`:
```js
let c = (_a = class NCE {
    },
    _a.x = 1,
    _a.y = NCE.x * 2,
    _a);
var _a;
```
This fails at runtime as the class expression's name is out of scope.

(Inspired by https://github.com/Microsoft/TypeScript/issues/8363)

### PR DESCRIPTION
**Pull request by yuit**
Fix #8467

@vladima could you take a look? :)

EDIT: this change need to be ported to "transforms" branch

### CODE REVIEW

**Comment by jeffreymorlan** [comment]
A tricky case to consider - right now class-expression temporary variables are scoped to the whole function, so they may have been overwritten by the time the access is done:
```ts
const arr: {y(): number}[] = [];
for (let i = 0; i < 3; i++) {
	arr.push(class C {
		static x = i;
		static y = () => C.x * 2;
	});
}
arr.forEach(C => console.log(C.y()));
```
This should print 0, 2, 4 but the way class-expression temporaries are currently, it's going to print 4, 4, 4

**Comment by yuit** [comment]
@jeffreymorlan Thanks for pointing this out!. The case in your example will be emit incorrect as well even without this change. I will investigate and pull in the fix here

**Comment by yuit** [comment]
@mhegazy @vladima could you guys take a look?

**Comment by dmudro** [comment]
hopefully this can be merged soon in the master as has been breaking static class members for some time when using TS nightly? thanks!

**Comment by mhegazy** [comment]
👍

**Pull request merged**
