### PR TITLE
Add function "isUnionType"

### PR DESCRIPTION
**Pull request by TroyTae**
I tried to fix an issue and I need to check UnionType.
And I found there is no function that checks unit type, so I added it first!

### CODE REVIEW

**Comment by fightingcat** [comment]
```typescript
type IsUnion<T> = [T] extends [never] ? 0 : [T] extends (T extends any ? [T] : never) ? 0 : 1;

// or a shorter version if you don't mind seen never as union
type IsUnion<T> = [T] extends (T extends any ? [T] : never) ? 0 : 1;

```

**Comment by jack-williams** [comment]
If this function is going to be added I think it should be a type-guard and consistently applied: `type.flags & TypeFlags.Union` appears all over the place.

Though, I'm not sure if the helper function is really better than just inlining the definition.

**Comment by TroyTae** [comment]
> If this function is going to be added I think it should be a type-guard and consistently applied: `type.flags & TypeFlags.Union` appears all over the place.
Yes, you're right!
So I was planning to refactor code after review.

> Though, I'm not sure if the helper function is really better than just inlining the definition.
I wanted to change two things.
- Duplicate code.
The expression that checks Union type is used in many lines.
If we need to add code for checking Union type, we have to change all of them.
- Strict type
As you know, `&` expression doesn't return boolean type.
So I used `!!` expression.

**Comment by TroyTae** [comment]
@jack-williams 
Was there any discussion about this?

**Pull request closed without merging**
