### PR TITLE
chore: skip relation check for named properties in indexed signature checking 

### PR DESCRIPTION
**Pull request by Jack-Works**
```ts
class Parent {
    declare id: string;
}
class Child extends Parent {
    declare name: string;
}

type T = { child: Child; [key: string]: Parent };
const t: T = { child: new Parent(), other: new Parent(), child2: new Child() };
// Property 'name' is missing in type 'Parent' but required in type 'Child'.ts(2741)
```

For the code above, TypeScript will run two relation checks for property `child`. The first one is to check if `child` matches `T['child']`, the second one is to check if `child` matches the index signature of `T`.

The second check is unnecessary because if `child` passes the first check, it is known to pass the second check. (TypeScript requires detailed properties on an object type must compatible (be a subtype) of the index signature.)

In this PR I skipped the index check for named properties. This may speed up when checking a complex indexed & named object type (please run `@typescript-bot perf this` to verify my idea thanks).

PS: This may also help to type a common pattern in JavaScript (I call it `incompatible index signature`) which is not possible (without Negated Type #29317) today:

Before this PR:

image

After this PR:

image

This PR doesn't have any test changes because it passes all existing tests and not breaking anything and not adding any new behaviors (if we ignoring the `incompatible index signature` trick above).

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Comment by RyanCavanaugh** [comment]
Spinning a pack since I have concerns about how this works with intersections as the target type

**Comment by Jack-Works** [comment]
Does the result have statistical significance? 👀

**Comment by RyanCavanaugh** [comment]
Seems like it's a little bit faster on average.

@ahejlsberg / @weswigham thoughts on this?

**Comment by ahejlsberg** [comment]
I don't think there's an issue with intersections since we break them down on the target side before checking. That said, I'm not sold that there's enough value here to merit the extra complexity and the perf number variations are in the noise. Also, it seems from the OP that the motivating scenario is a questionable form of negated types that relies on suppressing errors. I'm not a fan of that.

**Comment by Jack-Works** [comment]
Here is the version without suppressing the error:

```ts
type T = Record<string, number> & { onlyThisString: string }

const t: T = {
    onlyThisString: "string", // OK,
    other: "string", // No
    ok: 123,
};
```

Negated types have "bad performance implications that I couldn't easily work around" (according to @weswigham) so I think it won't land in short times. This is a simpler way to unlock this use case without negated types

**Comment by sandersn** [comment]
I'm going to close this for now since it sounds like the extra complexity isn't worth it.

**Pull request closed without merging**
