### PR TITLE
Correctly emit source maps when emitting JSX text under --jsx preserve

### LINKED ISSUE #4028: Incorrect source map with jsx=preserve
Let's create a file with some JSX inside:

```ts
import React from 'react';

export class JsxNode extends React.Component<{}, {}> {
    render() {
        return <div>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>;
    }
}
```

And compile it:

```ts
tsc test.tsx --target es6 --jsx preserve --sourceMap
```

After that, let's load the result into the http://evanw.github.io/source-map-visualization/:

Everything is fine with the first `div`:

source map visualization

But not for the children:

source map visualization2

It looks like it thinks that all JSX tags are on one line: 

source map visualization3

### PR DESCRIPTION
**Pull request by RyanCavanaugh**
Fixes #4028

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
Let's get a test that has `sourceMap` and `jsx=preseve` set.

**Comment by RyanCavanaugh** [comment]
Hopefully some day our source map tests will be useful :wink:

**Comment by DanielRosenwasser** [comment]
> Hopefully some day our source map tests will be useful

I wonder if we could integrate https://github.com/sokra/source-map-visualization in somehow...

Until then :+1:

**Pull request merged**
