### PR TITLE
fix(49594): Typescript 4.7.3 bracketed class property compilation error strictPropertyInitialization:true

### LINKED ISSUE #49594: Typescript 4.7.3 bracketed class property compilation error strictPropertyInitialization:true
# Bug Report

### 🔎 Search Terms

strictPropertyInitialization bracketed class property

### 🕗 Version & Regression Information
Typescript 4.7.3, 4.7.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/KYOwrgtgBAglDeBYAUFWUC8UDkNsBoU0AhTHY7FAXxRQGMAbAQwGcWpSlUoBtGAOhgBdAFxQWAFwBOASxABzANy1udAPYhJUsHQlqpACgCUCImigSAFjJZ9BQstgCM2ZdzRWbgxy7fmL1ra42A5Yzq5mNMhUQA)

### 💻 Code

```ts
enum A {
  A = 'A',
  B = 'B'
}

class B {
  [A.A]: string;

  constructor() {
    this[A.A] = '1';
    this.A = '1';
    this['A'] = '1';
  }
}
```

### 🙁 Actual behavior
Compilation error:  
Error: Property '[A.A]' has no initializer and is not definitely assigned in the constructor.

### 🙂 Expected behavior
Seems it should be compiled without errors.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #49594

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
FWIW this brings along some other goodness
```ts
enum E {
    E1 = "A", E2 = "B"
}

declare const m: { [K in E]: string | null };
if (m[E.E1] !== null) {
    m[E.E1].toString(); // no longer an error
}
```

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh I've added test for this case

**Comment by RyanCavanaugh** [comment]
@typescript-bot perf test this

**Comment by a-tarasyuk** [comment]
@ahejlsberg Could you review these changes?

**Comment by a-tarasyuk** [comment]
@ahejlsberg Could you review these changes?

**Review by RyanCavanaugh — APPROVED** [review]

**Pull request merged**
