### PR TITLE
Revert "Update version to 1.7.4"

### PR DESCRIPTION
**Pull request by yuit**
Reverts Microsoft/TypeScript#5604

### CODE REVIEW

**Comment by yuit** [comment]
Didn't see the comment till after click merge. Revert the commit and address comment from @mhegazy  to use 1.7.3

**Comment by mhegazy** [comment]
:+1:

**Comment by mhegazy** [comment]
also need to update it in package.json

**Comment by yuit** [comment]
@mhegazy update. I am going to port our update script to public repo tmr to avoid this problem again

**Comment by mhegazy** [comment]
looks good.

**Pull request merged**
