### PR TITLE
Revert "Add check for delete expression must be optional"

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Reverts microsoft/TypeScript#37921, given feedback on https://github.com/microsoft/vscode/issues/96022

### CODE REVIEW

**Comment by mjbvz** [comment]
I actually think this is a good change and it catch some potential errors in the VS Code codebase. For a codebase of VS Code's size, 12 errors isn't bad (but we also pretty rarely use `delete`)

My only complaint is that it took me a a minute or so to understand what the error message  meant. Once I did though, the error was obvious

**Comment by DanielRosenwasser** [comment]
I think that's fine (the break will still happen in a subsequent version) but the message that we communicate is that users shouldn't have to worry about breaks between the beta and the RC. That's not always true (accidents happen) but this seems easy to prevent.

**Comment by weswigham** [comment]
Rather than apply this PR, cut the branch tomorrow afternoon, and then land a revert of this revert tomorrow afternoon, why not just re-target this PR to the 3.9 branch tomorrow afternoon?

**Comment by DanielRosenwasser** [comment]
That's a really good idea, I'll do that. Thanks!

**Comment by weswigham** [comment]
(Though while this is a "break" it definitely falls into the bucket of "helpful new errors that point out something most definitely done incorrectly", and we only _generally_ avoid extra breaks between beta and rc, and it's, at least internally, done more for code stability - this change is minor, so that's not a concern. I would at least bring this up in the design meeting - this might be something we'd rather land sooner rather than later, since [the design for this error has been done for 3 years already.](https://github.com/microsoft/TypeScript/issues/13783#issuecomment-324147507) The issue simply was never re-triaged correctly, so it fell through the cracks until @Kingwl picked it up!)

**Comment by DanielRosenwasser** [comment]
I get that, but it seems easy enough to hold off on for 4.0 to not add too much disruption to the RC. Let's chat about it tomorrow.

Side note: reading it again, I want to mention that my original comment in the other issue clearly comes off as curt and frustrated, but I should have been more understanding and thoughtful, so sorry about that.

**Comment by DanielRosenwasser** [comment]
Actually a double revert will be easier for me to be honest

**Pull request merged**
