### PR TITLE
[experiment] Sort intersections

### PR DESCRIPTION
**Pull request by jakebailey**
For #51188, doing this is the difference between OOMing and just taking "too long", because doing this allows us to reuse intersections, compare using fast paths, etc, when producing intersections which are the same but just happen to be in different orders.

To actually do this, we'd need to add `origin` to intersections too (hence, test failures), but I want to first see what the perf tests say.

### CODE REVIEW

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by DanielRosenwasser** [comment]
Nice job finding other possible wins here - the "fast path" I described in our chat was actually referring to was in `someTypeRelatedToType`.

https://insiders.vscode.dev/github.com/microsoft/TypeScript/blob/f0d1eee9b194d1fc36b64dee5eecc4e4f5d6ac9b/src/compiler/checker.ts#L20835

That function has some code that can now take advantage of intersections being sorted as well.

```diff
- if (source.flags & TypeFlags.Union && containsType(sourceTypes, target)) {
+ if (containsType(sourceTypes, target)) {
      return Ternary.True;
  }
```

**Comment by jakebailey** [comment]
To the former point, I would think unions are more common and therefore the fact that this PR doesn't seem to cause a massive regression is a good sign. I haven't gone through and "enabled" all of the other wins.

For the latter, yes, I need to figure that out. But, all of the tests (except one) fail just because this PR doesn't have the origin type thing to preserve the "looks" of unions. So I'm hopeful I can make everything consistent.

**Comment by fatcerberus** [comment]
> To the former point, I would think unions are more common

Yep, hence my "to be fair" caveat.

**Comment by jakebailey** [comment]
@typescript-bot perf test this

**Comment by jakebailey** [comment]
RE: #51188 this PR with the suggestion above turns into a huge win, not only fixing the problem I'm looking into but making it 40% faster than TS 4.6. Very interested in what the perf test is going to report.

**Comment by DanielRosenwasser** [comment]
Sweet! I'll also mention - even if you don't end up sorting intersection types by their IDs due to other concerns, you can still add a linear walk over every type. That'll provide earlier bail-outs without having to deeply explore every preceding type.

**Comment by jakebailey** [comment]
> Sweet! I'll also mention - even if you don't end up sorting intersection types by their IDs due to other concerns, you can still add a linear walk over every type. That'll provide earlier bail-outs without having to deeply explore every preceding type.

Oh, that's a good idea. I'll have to try that for #51188. We have to go over the intersection's types anyway so another linear iteration seems fine.

**Comment by jakebailey** [comment]
Ugh nevermind I screwed up; I had commented out the slow code in my example...

There's still a benefit, but it goes from 40s to 30s. I mean, still good.

**Comment by DanielRosenwasser** [comment]
I will happily take a 25% speed-up 😄

Still, sounds like we can do better for that issue.

**Comment by jakebailey** [comment]
Hm, not sure where my 40s number came from anymore, because now it's 30 without the last commit too. I'm going to stop giving updates before I make myself look any sillier.

**Comment by jakebailey** [comment]
Yeah, this is the diff I expected; the fast paths mentioned aren't actually that fast because isRelatedTo already checks equality. But still, the perf benchmarks appear to indicate that this sorting itself isn't catastrophic, so I'm going to continue with it and get origin types working.

**Comment by jakebailey** [comment]
My hopes for this went away via standup; I completely forgot that intersection ordering determines overload order, and therefore we can't sort intersections at all.

**Comment by jakebailey** [comment]
@typescript-bot test it

for fun

**Comment by jakebailey** [comment]
fun is over, it's not really faster

**Pull request closed without merging**
