### PR TITLE
Improve inference between types with multiple signatures

### LINKED ISSUE #28867: Inconsistent inferred overloads in conditional types for no-arg signatures with strictFunctionTypes
**TypeScript Version:**  3.3.0-dev.20181205

**Search Terms:**
conditional type, infer, overload, no-arg, zero arguments, strictFunctionTypes

Note that this issue is not about the behavior where the last overload is examined in conditional type inference of a single signature, where some might expect [a union](https://github.com/Microsoft/TypeScript/issues/26591) or [an argument-based choice](https://github.com/Microsoft/TypeScript/issues/27027).  

**Code**
```ts
// turn on --strictFunctionTypes

type InferTwoOverloads<F extends Function> = 
  F extends { (...a1: infer A1): infer R1, (...a0: infer A0): infer R0 } ? 
  [(...a1: A1) => R1, (...a0: A0) => R0] : 
  never;

type Expected = InferTwoOverloads<((x: string) => number) & (() => string)>
// [(x: string) => number, () => string]    

type JustOneSignature = InferTwoOverloads<((x: string) => number)>;
// never

type JustTheOtherSignature = InferTwoOverloads<(() => string)>;
// [(...a1: unknown[]) => {}, () => string]
```

**Expected behavior:**
I would expect that either both `JustOneSignature` and `JustTheOtherSignature` would be `never`, or both `JustOneSignature` and `JustTheOtherSignature` would evaluate to a two-tuple where the first signature is... something.  I suppose `(...a1: unknown[])=>{}`?  Or maybe it should be a copy of one of the other overloads?  Or something in between?

**Actual behavior:**
It looks a zero-argument function is being treated pathologically during conditional type inference; if a type is callable with zero arguments, it will be considered assignable to any number of overloads with what looks like failed inference for the types of the arguments (`unknown[]`) and the return (`{}`).  Otherwise, if a type is only callable with at least one argument, it will only be considered assignable to the matching number of overloads.

This distinction only seems to happen with `--strictFunctionTypes` on.  If you turn it off, `JustOneSignature` above becomes `[(...a1: unknown[]) => {}, (x: string) => number]`, which is at least consistent with the zero-argument situation.  

**Playground Link:** 
[🔗](https://www.typescriptlang.org/play//#src=%2F%2F%20turn%20on%20--strictFunctionTypes%0A%0Atype%20InferTwoOverloads%3CF%20extends%20Function%3E%20%3D%20%0A%20%20F%20extends%20%7B%20%28...a1%3A%20infer%20A1%29%3A%20infer%20R1%2C%20%28...a0%3A%20infer%20A0%29%3A%20infer%20R0%20%7D%20%3F%20%0A%20%20%5B%28...a1%3A%20A1%29%20%3D%3E%20R1%2C%20%28...a0%3A%20A0%29%20%3D%3E%20R0%5D%20%3A%20%0A%20%20never%3B%0A%0Atype%20Expected%20%3D%20InferTwoOverloads%3C%28%28x%3A%20string%29%20%3D%3E%20number%29%20%26%20%28%28%29%20%3D%3E%20string%29%3E%0A%2F%2F%20%5B%28x%3A%20string%29%20%3D%3E%20number%2C%20%28%29%20%3D%3E%20string%5D%20%20%20%20%0A%0Atype%20JustOneSignature%20%3D%20InferTwoOverloads%3C%28%28x%3A%20string%29%20%3D%3E%20number%29%3E%3B%0A%2F%2F%20never%20%28turn%20on%20--strictFunctionTypes%2C%20I%20said%29%0A%0Atype%20JustTheOtherSignature%20%3D%20InferTwoOverloads%3C%28%28%29%20%3D%3E%20string%29%3E%3B%0A%2F%2F%20%5B%28...a1%3A%20unknown%5B%5D%29%20%3D%3E%20%7B%7D%2C%20%28%29%20%3D%3E%20string%5D)

**Related Issues:** 
* Not the same issue as #26591 or #27027, or the choose-last-overload behavior described in #21496
* Maybe related to #27439?
* Or maybe #22615?

### PR DESCRIPTION
**Pull request by ahejlsberg**
Implements what I describe [here](https://github.com/microsoft/TypeScript/issues/28867#issuecomment-1567628124).

Fixes #28867.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by Andarist** [comment]
@ahejlsberg This has an effect on the code reported in https://github.com/microsoft/TypeScript/issues/53508 

```ts
type Overloads<T> = T extends {
    (...args: infer A1): infer R1;
    (...args: infer A2): infer R2;
  } 
  ? [(...args: A1) => R1, (...args: A2) => R2]
  : T extends {
      (...args: infer A1): infer R1;
    } 
    ? [(...args: A1) => R1]
    : any;

interface A {
  hello(str: string): string
}

// was: [(str: string) => string]
// is:  [(str: string) => string, (str: string) => string]
type HelloOverloadsOfA = Overloads<A['hello']>;

interface B {
  hello(): number
  hello(str: string): string
}

// was: [() => number, (str: string) => string]
// is:  [() => number, (str: string) => string]
type HelloOverloadsOfB = Overloads<B['hello']>;

interface C {
  hello(): number
}

// was:             [(...args: unknown[]) => unknown, () => number]
// is:              [() => number, () => number]
// requested by OP: [() => number]
type HelloOverloadsOfC = Overloads<C['hello']>;
```

**Comment by ahejlsberg** [comment]
> This has an effect on the code reported in #53508

The current state of affairs of inference between types with multiple signatures is confusing to say the least. When the source has fewer signatures than the target, we make no inferences to the excess target signatures, leaving type variables in those signatures to assume their defaults (typically `unknown`). In those cases, inference may produce target types with which the source type isn't compatible (because `unknown` in a parameter position is very restrictive). The net effect is that you _sometimes_ can measure overload arity, so the strategy in #53508 of having a ladder with decreasing numbers of overloads is never going to produce consistent results.

With the changes in this PR, our behavior is much more consistent: We'll always make inferences to each signature in the target, ensuring that every type variable in the target is covered. It doesn't give you the ability to measure overload arity with a ladder (because the first step will always succeed), but that ability wasn't really there to begin with.

**Review by RyanCavanaugh — APPROVED** [review]
LGTM. Seems like our test coverage in this area is not great...

**Comment by DanielRosenwasser** [comment]
Let's wait until Monday for TS 5.3.

**Comment by RyanCavanaugh** [comment]
Pushing a merge commit

**Review by weswigham — APPROVED** [review]
I guess this is fine if the extended suites are OK with it - no worse than the existing inference logic, anyway. 

What gets me is I _know_, since this logic differs from the logic in `signaturesRelatedTo` (which has way more special cases), we can infer things from a different order of signature pairs (with differing levels of instantiation) than we end up relating, so we can ultimately choose an inference that ends up failing relationship checks (which makes it a poor inference candidate). Again, already possible, so this doesn't change anything in that regard, just makes the behavioral drift between relating types and inferring between signatures in types a bit bigger.

**Pull request merged**
