### PR TITLE
Convert documentRegistry to class

### PR DESCRIPTION
**Pull request by andy-ms**
No reason not to use classes in services.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Better question: what is the specific motivation to convert this to a class when most of the codebase does not utilize them?

**Comment by mhegazy** [comment]
i agree with @DanielRosenwasser

**Comment by andy-ms** [comment]
shot
* Goto-definition works
* Debugging works (no runtime privates)
* Can add a method and only change one thing (not interface + function declaration + return object literal)

**Comment by DanielRosenwasser** [comment]
1. We have go-to-implementation, though I'll concede it's less convenient.
2. Debugging does work, Chrome allows you to peek at closure-captured variables last I used it.
3. You've now changed our API anyway because now we're guaranteeing that the services layer provides a `new`-able `DocumentRegistry` class. To prevent this, you need to declare an interface that `createDocumentRegistry` returns, so you're back at square one.

**Comment by mhegazy** [comment]
all your arguments are valid. but we have opted into a style that avoid classes in general and prefers detaching data from functions. we have a few instances of classes, mostly when performance is an issue. the document registry is a singleton almost always. so performance is not an issue here.

**Comment by andy-ms** [comment]
Unfortunately the debugger only gives you access to a private method if you are in another method that accesses it. You can't access the private method given a reference to an object, or if you've stepped into a different method. It would be nice if e.g. `typeToString` were available while debugging, although I can't think of a good way to do that besides assign a global variable.

**Pull request closed without merging**
