### PR TITLE
Make IdentifierPart contain ZWNJ/ZWJ in ES6

### LINKED ISSUE #42452: Typescript supports less valid variable names characters than javascript
# Bug Report

### 🔎 Search Terms

unicode invalid character name

### 🕗 Version & Regression Information

- I specifically tried the zero width space non-joiner. In this particular case at least, the support was lost between versions 3.5.1 and 3.6.3, as shown by the playground.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=3.6.3#code/PTAEBUAsFMCdtASwM6gIagF5wPagO6IAmALpKAHY4UC0AVjohXKAEbQn7TQWgBEADz7oKRfgE8+AOgBQAY2rISoAYBgCcaAC8oACwAmANxA)

### 💻 Code

```ts
// There is a zero width non-joiner between "x" and "y".
// All versions starting from 3.6.3 think that I am defining a "x" and a "y" variable separately.
// Version 3.5.1 outputs the expected JS code, which is strictly equal to the TS code in this case.
const x‌y = 42;
```

### 🙁 Actual behavior

Not all variable names valid in JS are supported in TS. At least the zero width non-joiner character is not supported. I didn't go on the hunt for all the unsupported characters but clearly TS does not support the full set of supported JS characters anymore.

### 🙂 Expected behavior

All valid variable names in JS should also be valid variable names in TS. At least when tsconfig is configured to output in an ES version that supports it.

For the record, a wonderful tool exist to test if a variable name is valid in JS: https://mothereff.in/js-variables

### PR DESCRIPTION
**Pull request by uraway**
Fixes #42452 

According to [ES6](https://262.ecma-international.org/6.0/#sec-unicode-format-control-characters), IdentifierPart can contain ZWNJ/ZWJ.

Also, added tests for ES3 and ES5 because the compiler has each IdentifierPart definition.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I think you might be able to reduce the number of tests by writing `// @target: es3, es5, esnext`, but @rbuckton will know best.

**Comment by uraway** [comment]
Thanks, I force-pushed a single test file for `es3, es5, esnext` cases

**Review by sandersn — CHANGES_REQUESTED** [review]
When was this support added? The tests show support in es5 and esnext but not es3. However, from the PR description I expected to see support in es6 and esnext, but not es5 and es3. Which is correct?

**Comment by nguerrera** [comment]
I just happened upon this after realizing, my #43811 was a dupe of #42452.

I believe it is correct for es5 to support ZWJ and ZWNJ: https://262.ecma-international.org/5.1/#sec-7.6

I believe the description is meant to say that it is *adding* support when targeting es6 because it is already working as expected when targeting ES5.

**Comment by sandersn** [comment]
OK, if that's the case, then all this PR needs is an `es6` test to show that ZWJ/ZWNJ are added to ES6 after the change.

**Comment by sandersn** [comment]
It's been almost a year, so I'm going to close this to reduce the number of old open PRs. @uraway let me know if you want to keep working on this.

**Pull request closed without merging**
