### PR TITLE
Don't cache Ternary.Maybe results when recursion is encountered during variance measurement

### LINKED ISSUE #39947: Assignability check not enough for class that is mutually recursive with an interface?
**TypeScript Version:**  3.9.2, 4.0.1-rc

**Search Terms:** class no type error interface

**Code**

Unbelievably this is the *minimal* reproduction I was able to make.

```ts
interface I<Dummy, V> {
  c: C<Dummy, V>;
}

class C<Dummy, V> {
  declare sub: I<Dummy, V>;

  declare covariance: V;
}

// should be a type error, but none emitted
const c1: C<unknown, string> = new C<unknown, number>();
```

**Expected behavior:**

`new C<unknown, number>()` should not be assignable to `C<unknown, string>` due to existence of the `covariance` property.
TSC should emit an error like `Type 'C<unknown, number>' is not assignable to type 'C<unknown, string>'.`

**Actual behavior:** 

No error.

**Playground Link:** [link](https://www.typescriptlang.org/play?ts=3.9.2#code/JYOwLgpgTgZghgYwgAgJIB4AiBXAtrgTwBpkA1APmQG8AoZZBALmQGEs9CSKBuGgXxo0EAGzgBnMa3b5iZSrXoATCCLhQUY7ACNmGHDK7ledZMtXqGAewBua4HBBJmpXgJoB6d8jEALS9mFFZC0UOGQwAgAHFGgoSygSLWwwZBBLEBjcYDBIRSF0sRSEAEZmNmwQAGs0gHcQEkKoUABzSgBeVIgaqQrqyzqSEDwQqHIACgBKbiA)

**Related Issues:** none found (sorry, hard to explain the exact problem so no good search terms came up)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #39947.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Review by weswigham — COMMENTED** [review]
`recursiveVariances` should be un-set by `recursiveTypeRelatedTo` once we want to cache a non-maybe value, no? So if there is, thereafter, a `Maybe` during the same comparison that is _not_ variance related, it is cache able?

**Comment by ahejlsberg** [comment]
@weswigham In some sense we really want to have two different `Ternary.Maybe` values: One that originates in the depth limiter (the original one) and one that originates in a recursive variance measurement (the new one). The new one would be "infectious" and we would never put it in the cache. What's implemented now is sort of a blunt approximation of that, but once we have a `Ternary.Maybe` that originated in recursive variance measurement we have to assume every `Ternary.Maybe` is possibly one of those and thus not cacheable.

**Comment by ahejlsberg** [comment]
Hmm, the effect on performance is definitely unacceptable. It might be better with the two kinds of `Ternary.Maybe` I describe above, but I'm not sure. Unfortunately it's not a small amount of work to find out.

**Comment by ahejlsberg** [comment]
Actually, wasn't too hard to introduce a `Ternary.Unknown` that acts like a signaling `Ternary.Maybe`. We'll see if that helps performance.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@rbuckton Hmm, the reporting from that last test runs seems broken. Any ideas?

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by rbuckton** [comment]
Might be related to the switch to the native performance API. I'll look into it.

**Comment by rbuckton** [comment]
#41253 will fix the issue with tracking performance data.

**Comment by rbuckton** [comment]
#41253 has been merged. If you merge the latest from master the perf results should be working now.

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
Performance looks good now and issues in test suites all appear to be preexisting conditions.

**Review by weswigham — APPROVED** [review]

**Pull request merged**
