### PR TITLE
fix(38080): Add outlining spans for 'type' declarations

### LINKED ISSUE #38080: Add outlining spans for 'type' declarations
From https://github.com/microsoft/vscode/issues/95577

**TypeScript Version:**  3.9.0-dev.20200420

**Search Terms:**
- fold / folding
- outlining spans / `getOutliningSpans`
- type

**Code**
For the TS:

```ts
interface A {
    x: number
}

type B = {
    y: number
}
```

**Expected behavior:**

Both `A` and `B` are foldable

**Actual behavior:**

Only the interface (`A`) is foldable

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #38080

### CODE REVIEW

**Comment by jessetrinity** [comment]
I was just wondering about this. Thanks!

**Comment by orta** [comment]
@a-tarasyuk if you prefer to do a separate PR for `type A = []` then I'm happy to merge this now, otherwise I can wait until early Friday for it to get in 3.9

**Comment by a-tarasyuk** [comment]
@orta I'll make separate PR. :)

**Comment by orta** [comment]
👍

**Pull request merged**
